### ISSUE TITLE
Radio buttons are not active/clickable in repeatable subforms.

### ISSUE THREAD

**Issue by g-e-n-e-z-i-s** [joomla/joomla-cms#42997] opened 2024-03-11 11:42 UTC
### Steps to reproduce the issue
Create radio field and use for subform only, then create repeatable subform. When you create new article and edit custom fields, every newly added radio field have not active/clickable value buttons. You need to save article first to be able pick a value from radio field.

https://github.com/joomla/joomla-cms/issues/40160 

### Expected result

Value buttons should be selectable. 

### Actual result

Not possible to select/pick value button.

### System information (as much as possible)
The currently installed Joomla! version is "‎4.4.3"‎4.4.3
PHP 8.1.27
MySQLi 10.3.7-MariaDB-1:10.3.7+maria~xenial-log

**Comment by Quy** [comment] 2024-03-11 14:44
Closing as duplicate of #40160.

**Closed as completed by Quy** 2024-03-11 14:44 UTC
Labels: No Code Attached Yet
