### ISSUE TITLE
Tag SPAN in title of some items returned from search

### ISSUE THREAD

**Issue by murilodbva** [joomla/joomla-cms#17325] opened 2017-07-28 20:56 UTC
### Steps to reproduce the issue
Do some search. Example at university where I work:
> http://ww2.uft.edu.br/index.phpbusca?searchword=Programa%20de%20P%C3%B3s-Gradua%C3%A7%C3%A3o%20em%20Engenharia%20Ambiental&ordering=oldest&searchphrase=all&limit=20

### Expected result
Titles of somes articles

### Actual result
Titles with tag SPAN

### System information (as much as possible)
Nginx 1.6.2-5+deb8u5.
Joomla version is 3.7.4 and Last commit ([fffdce9](https://github.com/joomla/joomla-cms/commit/fffdce955b9607ea8e2a85455e9cb677840bc0d6)).

Behavior observed in Firefox and Chrome.

### Additional comments
It started in Joomla 3.7.3 and continues in the last change ([fffdce9](https://github.com/joomla/joomla-cms/commit/fffdce955b9607ea8e2a85455e9cb677840bc0d6)). The bug is in this file:
> components/com_search/views/search/view.html.php

Line 268:
`$result->title   = preg_replace("/\b($needle)\b/ui", $hl1 . "$1" . $hl2, htmlspecialchars($result->title, ENT_COMPAT, 'UTF-8'));`

**Comment by tonypartridge** [comment] 2017-07-29 07:27
Hello,

There is a very valid reason for this. It's to highlight the keyword which was searched.

The problem is actually your template is doing some crazy things. See:

http://ww2.uft.edu.br/index.phpbusca?searchword=Programa%20de%20Pós-Graduação%20em%20Engenharia%20Ambiental&ordering=oldest&searchphrase=all&limit=20&template=protostar

When using the default Joomla! Template.

**Comment by tonypartridge** [comment] 2017-07-29 07:33
Looks like it's caused by Joomla and related to issue #17324 since your template has an override in place.

**Comment by ghost** [comment] 2017-07-29 07:35
@tonypartridge can you please correct related Issue (you are on #17325)?

**Comment by brianteeman** [comment] 2017-07-29 08:22
I can confirm what @tonypartridge has said. The problem is in the code of your template override for the search component and not in joomla.

Closing as not joomla core

**Closed as completed by brianteeman** 2017-07-29 08:22 UTC
Labels: No Code Attached Yet

**Comment by tonypartridge** [comment] 2017-07-29 22:14
@murilodbva can I get a copy of your template to see what it's doing g to cause this, I've seen a few people with the same issue.

**Comment by murilodbva** [comment] 2017-07-29 22:41
Yes sure, I believe there is no problem (I'll confirm with my team).
Can I send to your email "ton__im"?

**Comment by tonypartridge** [comment] 2017-07-29 22:42
yep that would be good thanks.

**Comment by murilodbva** [comment] 2017-07-31 13:30
@tonypartridge I just sent my template to your e-mail, for checking what was happening with my project and can be the same with anothers. Please, check if your received. We already found the solution and I'll already post here.

**Comment by murilodbva** [comment] 2017-07-31 13:54
In our template, I don't know why, we were using "**$this->escape($result->title)**;" before print the title. It was enough remove "**$this->escape**" and it works now.

**Comment by murilodbva** [comment] 2017-08-09 13:55
@tonypartridge 
My template is in that link:
[https://drive.google.com/file/d/0By_1LhqC3V1FMVFzODhZMzZUQWc/view?usp=sharing](https://drive.google.com/file/d/0By_1LhqC3V1FMVFzODhZMzZUQWc/view?usp=sharing)
