### ISSUE TITLE
Media manager no longer works when files folder is symlink

### ISSUE THREAD

**Issue by okonomiyaki3000** [joomla/joomla-cms#24959] opened 2019-05-20 09:31 UTC
### Steps to reproduce the issue
Move your files folder outside of your joomla root and put a symlink to it in its place. A totally normal thing you might want to do. 

### Expected result
Since this is a totally normal thing and it has always worked until now, you'd expect it to work exactly the same as if your actual files folder was there. In other words, no different from a completely standard installation.

### Actual result
You will not be able to navigate past the base files folder (COM_MEDIA_BASE) because of this great little addition on line 116 of the media manager's list model:

```php
// Reset base path
if (strpos(realpath($basePath), JPath::clean(COM_MEDIA_BASE)) !== 0)
{
	$basePath = COM_MEDIA_BASE;
}
```

### System information (as much as possible)
Some kind of linux.

### Additional comments
Change it back.

**Comment by SniperSister** [comment] 2019-05-20 09:35
Duplicate of https://github.com/joomla/joomla-cms/issues/24539, closing

**Closed as completed by SniperSister** 2019-05-20 09:35 UTC
Labels: No Code Attached Yet
