### ISSUE TITLE
can't see selected articles for editing

### ISSUE THREAD

**Issue by MostafaHamedAbdelmasoud** [joomla/joomla-cms#27820] opened 2020-02-05 22:51 UTC
![image here](http://rtl-ltr.000webhostapp.com/i.png)

### Steps to reproduce the issue
1- go to articles from content sidebar in admin panel.
2- select article to edit.
3- click on edit button.
4- then click on back button of your browser.
5- then click edit button again without selecting anymore articles. just the previous selected item must be selected automatically.
6-  it will show "Please first make a selection from the list".

### Expected result
- after clicking back button of my browser, and click edit again, it must see selected articles and open it again. 

### Actual result
- it can't see old selected articles.
-  it will show "Please first make a selection from the list".

**Comment by ravisaxena23** [comment] 2020-02-06 02:13
> ![image here](https://camo.githubusercontent.com/23c45d82602837a52f2aae01b785ed832dabbabf/687474703a2f2f72746c2d6c74722e303030776562686f73746170702e636f6d2f692e706e67)
> 
> ### Steps to reproduce the issue
> 1- go to articles from content sidebar in admin panel.
> 2- select article to edit.
> 3- click on edit button.
> 4- then click on back button of your browser.
> 5- then click edit button again without selecting anymore articles. just the previous selected item must be selected automatically.
> 6- it will show "Please first make a selection from the list".
> 
> ### Expected result
> * after clicking back button of my browser, and click edit again, it must see selected articles and open it again.
> 
> ### Actual result
> * it can't see old selected articles.
> * it will show "Please first make a selection from the list".

Sir, I think Joomla is designed in such a way that once you go back using browser back button. You cannot come to selected item. I guess Joomla probhits the use of back button on pages where user do editing. Still I don't know much kindly wait for @brianteeman @richard67 reply.

**Comment by richard67** [comment] 2020-02-06 06:36
To be honest: I have no idea if it is a bug or desired behavior. Question; What happens when after having used the browser‘s back button you don’t use the edit Button of the backend but using the forward button of the browser to come back to the edit view? I can’t test here right now, I will be at work soon .

**Comment by MostafaHamedAbdelmasoud** [comment] 2020-02-06 10:25
> To be honest: I have no idea if it is a bug or desired behavior. Question; What happens when after having used the browser‘s back button you don’t use the edit Button of the backend but using the forward button of the browser to come back to the edit view? I can’t test here right now, I will be at work soon .

yes it may be a common desired behaviour. it should see the old selected articles i think.
when i click forward button of browser, it shows the edit layout of last selected article.

**Comment by richard67** [comment] 2020-02-06 10:28
> when i click forward button of browser, it shows the edit layout of last selected article.

So that seems to be correct and ok for you, right?

I think why should someone use the back button to get back but then use something else than the forward button to go forward again?

Therefore the use case described in the issue seems weird to me.

**Comment by infograf768** [comment] 2020-02-06 10:33
This is not a bug.

**Comment by infograf768** [comment] 2020-02-06 10:37
Closing as not a bug.

**Closed as completed by infograf768** 2020-02-06 10:37 UTC
Labels: No Code Attached Yet
