### ISSUE TITLE
Backend extremely slow on "large" sites due to User Status backend module

### ISSUE THREAD

**Issue by ZoccoloCD** [joomla/joomla-cms#19750] opened 2018-02-21 15:34 UTC
### Steps to reproduce the issue
Try browsing through the backend of a site that has lots of members/users that are logged in.

### Expected result
Normal backend speed.

### Actual result
Extremely slow backend speed.

### System information (as much as possible)
Various systems with various hosts, php 5.6 to 7.1 with newest joomla versions.

### Additional comments
I've done debugging on the sites and in some cases the user stats backend module takes 30.000 milliseconds to load, making the backend unworkable. Disabling the module solves this.
I couldn't find this issue in the tracker yet eventhough many of our clients were running into this issue. Luckily a workaround for now works by disabling the modules, but hope this can be fixed.

**Comment by Kubik-Rubik** [comment] 2018-02-22 07:24
@ZoccoloCD Can you please open the database and check the sessions table? How many entries do you have there?

**Comment by ZoccoloCD** [comment] 2018-02-22 07:48
I'm checking 1 of the sites now; 1 session in the session table currently, but the user status bar shows 2050 logged in users.

**Comment by ZoccoloCD** [comment] 2018-02-22 15:54
@Kubik-Rubik seems like the mod_status.php was changed quite a bit earlier and takes a lot of time to query the session tables. If however you were to put an index on the guest column, the query wouldn't take that long.

So this did it for me:

`ALTER TABLE `#_session` ADD INDEX(`guest`);`

**Comment by nickdring** [comment] 2018-03-01 13:42
Hi, I have had the same issue on a large site. I've been trying to figure out the reason for days when I came across this page. Disabling the user stats plugin brought the site back to normal.

**Comment by ghost** [comment] 2018-03-01 14:02
@nickdring can you please test Pull Request #19708?

**Comment by csthomas** [comment] 2018-03-01 15:55
IMO we have tow options:
1. Add index to guest column, as mentioned above, and slow down insert query a little.
2. Change `WHERE` statement from `guest = 0` to `userid > 0`.  Column `userid` is indexed.
   The issue, B/C break may be at 3rd party extensions that use negative user id, ex Joomdle?

**Comment by GCLW** [comment] 2018-03-01 17:40
Are you absolutely positive your Joomla session db table is empty?
This has all the symptoms of the problem that was created by a 3.8.4 update to how sessions are (or now not) deleted from that table.
When logging into the administrator area, do you take notice it takes a much longer time now?
This sounds like your DB table has a few hundred thousand records in it (as the amount of logged in users is showing). A bloated session table most likely is the cause.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19750">issues.joomla.org/tracker/joomla-cms/19750</a>.</sub>

**Comment by ZoccoloCD** [comment] 2018-03-01 18:22
@GCLW When Kubik-Rubik asked me there was only 1 active session, now I see hundreds of thousands in the same database. But the site is running on 3.8.4.

Do I understand correctly that this problem (sessions are not deleted) was introduced in 3.8.4 but is still existent in 3.8.5?
And is it fixed in the 3.8.6 RC/Stable?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19750">issues.joomla.org/tracker/joomla-cms/19750</a>.</sub>

**Comment by GCLW** [comment] 2018-03-01 19:11
Correct, a change in 3.8.4 causes the runaway session table. It was not reverted for 3.8.5, and I do not know if it will be fixed with 3.8.6. I have to run nightly cron jobs on all but one of my sites to clean the session table.

**Comment by Quy** [comment] 2018-03-01 19:56
Yes, it will be fixed in v3.8.6 per #19687.

**Comment by ghost** [comment] 2018-03-02 06:58
@Quy can this Issue be closed?

**Comment by infograf768** [comment] 2018-03-02 07:23
I guess so as 3.8.6 (to be released on the 13th) solves the issue.

**Comment by nickdring** [comment] 2018-03-02 08:34
I can put the release on a staging or dev server but I cannot deploy to production so this isn't much use to you I fear as we don't have user connected to those environments.

**Comment by Quy** [comment] 2018-03-02 15:18
Closing as this will be fixed in v3.8.6 and there is a discussion on this in [Joomla Forums](https://forum.joomla.org/viewtopic.php?f=9&p=3513825&sid=1091ee7ae861667885d8f8ecf869f4cb#p3512954).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19750">issues.joomla.org/tracker/joomla-cms/19750</a>.</sub>

**Closed as completed by Quy** 2018-03-02 15:18 UTC
Labels: No Code Attached Yet

**Comment by nickdring** [comment] 2018-03-19 10:32
This hasn't been resolved with 3.8.6

**Comment by brianteeman** [comment] 2018-03-19 10:36
@nickdring did you clean up the session table?

**Comment by nickdring** [comment] 2018-03-19 11:14
Hi @brianteeman No I hadn't. I've done it and reenabled the plugin and for now all seems quite speedy.

**Comment by brianteeman** [comment] 2018-03-19 11:27
:)

**Comment by csthomas** [comment] 2018-03-19 11:38
@nickdring You can test https://github.com/joomla/joomla-cms/pull/19708, which should speed up operations such as adding new or updating the session metadata. 

It is difficult to see any improvements on small site, but it speeds up queries to the database with high traffic.
