### ISSUE TITLE
[4.0] Left menu collapsed after saving/closing an item

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22795] opened 2018-10-23 21:15 UTC
### Steps to reproduce the issue

Joomla 4.0-dev @ 9d3acfd9d589989e86bda3fe35f58a47323d66f4
Login to admin -> Content Articles (Note menu is still open) -> click an article to edit it (left menu disappears correctly) -> click close

Note now the left menu is collapsed and Content is no longer open 

### Expected result

Left menu to be open with Articles selected

### Actual result

Note now the left menu is collapsed and Content is no longer open

**Comment by laoneo** [comment] 2018-10-24 06:54
I can confirm this. @ciar4n any idea?

**Comment by SharkyKZ** [comment] 2018-10-24 08:17
It's because closing the article redirects to a different URL (`index.php?option=com_content&view=articles`). Menu item points to `index.php?option=com_content`.

**Comment by dgrammatiko** [comment] 2018-10-24 16:41
@laoneo you can use: https://codepen.io/dgrammatiko/pen/gBQLXE. You don't really need some 3rd party library for the menu...

**Comment by ciar4n** [comment] 2018-10-24 19:55
Is there any particular reason the menu item link's to `index.php?option=com_content` instead of `index.php?option=com_content&view=articles`?

**Comment by laoneo** [comment] 2018-10-26 06:55
@dgrammatiko please open a new pr with your changes. Thanks.

@ciar4n Would it be possible to select the first element when none is found?

**Closed as completed** 2019-02-10 21:32 UTC
Labels: No Code Attached Yet, J4 Issue
