### ISSUE TITLE
Modern routing causes "Notice: Undefined index: option in /libraries/src/Component/Router/Rules/NomenuRules.php on line 104"

### ISSUE THREAD

**Issue by EricdeWaal** [joomla/joomla-cms#25837] opened 2019-08-14 06:52 UTC
### Steps to reproduce the issue
Multi-language site, 2 languages, 2 menus, some associated articles and menu items, Modern Routing/remove numbers

### Expected result
When switching between languages, associated article in selected language is shown.

### Actual result
It is, but for 2 items only, with a line on top of the the page:
"Notice: Undefined index: option in /libraries/src/Component/Router/Rules/NomenuRules.php on line 104"
Edit: it also happens if the 2 menu-items involved are clicked directly, without switching language.

Only occurs with Modern routing, not with Legacy routing

### System information (as much as possible)
Linux, Apache2/litespeed, 10.2.25-MariaDB-cll-lve, PHP 7.3.7, Joomla 3.9.10 and 3.9.11, possibly earlier versions as well

### Additional comments
Google shows 3 pages of results with above error, must have been there some time.
It seems to be an old bug, see https://github.com/joomla/joomla-cms/issues/15823 and https://github.com/joomla/joomla-cms/pull/6488

**Comment by SharkyKZ** [comment] 2019-08-14 07:31
Do you have any "System Links" type menu items (external URLs, headings, separators, menu item aliases)?

**Comment by EricdeWaal** [comment] 2019-08-14 09:22
No, all menu-items display articles, plus 2 or 3 separators under which are sub-items<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25837">issues.joomla.org/tracker/joomla-cms/25837</a>.</sub>

**Comment by Gitjk** [comment] 2019-08-14 09:27
Google lists a number of Joomla sites showing this notice, but I didn't see anything that all of them have in common. Did you try the 'Rebuild' button in the 'Menus' view already?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25837">issues.joomla.org/tracker/joomla-cms/25837</a>.</sub>

**Comment by infograf768** [comment] 2019-08-14 09:54
I looked at one of these sites on google and it has this Notice when we access to the home page with a non-sef url of the type `index.php?option=com_content&view=featured&Itemid=101`
but this has been solved since then as the site has sef on and is/was anyway monolingual.

**Comment by infograf768** [comment] 2019-08-14 10:01
@EricdeWaal
Can you try to switch to Protostar template and test?

**Comment by EricdeWaal** [comment] 2019-08-14 10:09
@gitjk Tried to rebuild, no difference
@infograf768 Protostar shows same message<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25837">issues.joomla.org/tracker/joomla-cms/25837</a>.</sub>

**Comment by EricdeWaal** [comment] 2019-08-14 10:33
It looks like this is an old bug: https://github.com/joomla/joomla-cms/issues/15823<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25837">issues.joomla.org/tracker/joomla-cms/25837</a>.</sub>

**Comment by EricdeWaal** [comment] 2019-08-14 10:40
And it seems to happen on sites with only one language as well<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25837">issues.joomla.org/tracker/joomla-cms/25837</a>.</sub>

**Comment by alikon** [comment] 2019-08-14 10:51
i'm unable to reproduce without 3dp extensions what are you using ? smells like 3dp issues to me

**Comment by Hackwar** [comment] 2021-05-20 17:17
I can't replicate the issue, but based on a codereview I did a change. @EricdeWaal can you check if the change in #34049 fixes this for you? And if it does, we need to merge also #34050 for Joomla 4.

**Comment by richard67** [comment] 2021-05-20 17:20
Closing as having a pull request. Please test #34049 for Joomla 3, and if possible also PR #34050 for Joomla 4. Thanks in advance.

**Closed as completed by richard67** 2021-05-20 17:20 UTC
Labels: No Code Attached Yet
