### ISSUE TITLE
Error in JURI::isInternal

### ISSUE THREAD

**Issue by victorantoniak** [joomla/joomla-cms#8728] opened 2015-12-18 07:50 UTC
#### Steps to reproduce the issue
JURI::isInternal('/index.php?option=com_test') -  return false (Error '/index.php?option=com_test' - is internal url)

JURI::isInternal('index.php?option=com_test') -  return true

#### Expected result

JURI::isInternal('/index.php?option=com_test') - return true

#### Actual result

JURI::isInternal('/index.php?option=com_test') - return false

**Comment by thomaslanger** [comment] 2015-12-18 08:40
See also "Wrong redirect after login on front-end since 3.4.6" #8689

**Comment by beat** [comment] 2015-12-18 08:54
> JURI::isInternal('/index.php?option=com_test')

That should certainly not always return true! E.g. If your Joomla install is in a sub-folder.

I think that this is really a duplicate of #8689 and just spreads out our resources. You can add your comment of this (fixed with my feedback) to the comments of #8689 and close this one.

Actually what would be more useful is if someone can propose a very **simple and secure** PR to improve IsInternal is welcome (simple to be easily reviewable), It needs to pass existing unit tests before new unit tests are added to extend the valid internal URLs.

**Comment by PhilETaylor** [comment] 2015-12-18 12:46
This should never return true as isInternal is designed to accept an input starting with index.php and not with a /

**Closed** 2015-12-18 12:46 UTC
Labels: No Code Attached Yet

**Comment by victorantoniak** [comment] 2015-12-18 12:51
Joomla 3.4.5
JURI::isInternal('/index.php?option=com_test'); - return true
JURI::isInternal('/login');  - return true

**Comment by teleputer** [comment] 2015-12-22 17:23
If you base64_encode(JRoute::_("index.php?...) this will add a "/" to be beginning of the decode variable, resulting in a url of /index.php?....

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8728">issues.joomla.org/joomla-cms/8728</a>.</sub>

**Comment by teleputer** [comment] 2015-12-22 17:27
![screen shot 2015-12-22 at 11 27 29](https://issues.joomla.org/uploads/1/5c8ab48c35e03e7def760a3c2bee5158.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8728">issues.joomla.org/joomla-cms/8728</a>.</sub>
