### ISSUE TITLE
Tooltips disappear instead of showing up

### ISSUE THREAD

**Issue by creative3d** [joomla/joomla-cms#10821] opened 2016-06-15 09:24 UTC
Since Joomla 3.0 Tooltips used in Joomla disappear at some point while hovering over an item.
Before Joomla 3.0 it worked perfect.

#### Steps to reproduce the issue

Open any page containing tooltips (admin panel has a lot, see the example below). Try to hover the mouse over an item with a tooltip. It looks fine at first sight but try to move the mouse more. At some point it will stop appearing. Probably it somehow connected with the speed of how the mouse moves. Try to move it faster.

Now, read more please, I understand most of you will think that I'm wasting your time with such unimportant issues. The problem is that these tooltips are used in some popular plugins which are supposed to show beautiful and helpful tooltips. Instead of doing that, the tooltips blink and disappear. That annoys users. They have to learn how to workaround that instead of just enjoying it.

#### Expected result

![tooltip1](https://cloud.githubusercontent.com/assets/19249899/16073933/5c4b434c-3312-11e6-9b63-9ccf36409ced.jpg)

#### Actual result

![tooltip2](https://cloud.githubusercontent.com/assets/19249899/16073934/5c69bec6-3312-11e6-8f9e-0713a8795ff6.jpg)

#### System information (as much as possible)

Joomla 3.x

#### Additional comments

Guys, I'm not a developer, and I'm not asking you to fix it right away, but just make sure it will be fixed as soon as possible. I and users are just tired of waiting for this fix since Joomla 3.0 but nobody even moved a finger...

**Comment by brianteeman** [comment] 2016-06-15 10:09
Did they fix it yet?
http://magazine.joomla.org/issues/issue-sept-2015/item/2837-did-they-fix-it-yet

**Comment by creative3d** [comment] 2016-06-15 10:45
Brian, don't close the issue. For being not a developer, I've done as much as I can.

**Comment by andrepereiradasilva** [comment] 2016-06-15 10:54
hum, i've seem this behavior befopre, but cannot reproduce this on latest staging / 3.6.0 beta 1.

@creative3d Did you tried in 3.6.0 beta 1?

**Comment by creative3d** [comment] 2016-06-15 10:58
@andrepereiradasilva , no, I've tried on 3.5. Ok, I'll try on 3.6 and report.

**Comment by creative3d** [comment] 2016-06-15 11:08
@andrepereiradasilva , yes, the same on 3.6. Can you confirm that you have reproduced it too? Because Brian thinks that I'm crazy. Try to hover in and out faster on the same item. Thanks.

**Comment by andrepereiradasilva** [comment] 2016-06-15 11:12
no, can't reproduce on chrome 51

**Comment by brianteeman** [comment] 2016-06-15 11:15
I don't think you are crazy and I don't say if there is a big or not. My
comment referred only to your disparaging statement that this bug has
existed for over three years and no one has fixed it.

**Comment by creative3d** [comment] 2016-06-15 11:18
@andrepereiradasilva damn... I can easily reproduce both on Chrome and Firefox the latest versions... That's too bad...
@brianteeman it wasn't disparaging. Can you reproduce it? Have you tried?

**Comment by bertmert** [comment] 2016-06-15 13:42
I cannot reproduce it but can confirm that this tooltip behavior occurs sometimes and also for 3.6 in ISIS backend.
Flickering tooltips. Rapidly closing ones...
Sometimes page reload helps, sometimes window resize, sometimes moving mouse over a preceding tooltip first, sometimes moving mouse in from another direction.
And yes, it exists for a long time now. I am sure because I don't use tooltips anymore for **important** descriptions but use fields of type spacer instead or modal buttons.

**Comment by creative3d** [comment] 2016-06-15 14:09
@bertmert yes, yes, your description is very correct. But why can't everybody reproduce it, that' very strange...

**Comment by mbabker** [comment] 2016-06-15 14:14
The disparaging comments could basically be seen in things like "I and users are just tired of waiting for this fix since Joomla 3.0".  Comments like that are borderline excessive and unnecessary.  Also, I'm fairly sure this is the first issue opened explicitly about this behavior so the reason you're still waiting for a fix is because nobody's ever reported it.

As for reproducing it, I noticed it this morning only because I was explicitly looking for it.  Otherwise, I don't often validate the tooltip behaviors actually work when developing components because I'm expecting them to work fine in the core code where I'm copying most of my scaffolding from.

**Comment by creative3d** [comment] 2016-06-15 14:28
@mbabker "nobody's ever reported it". The previous attempt to point out the issue was closed the same day (maybe even by Brian, that was disparaging behaviour from my point of view). And before that, it was at the very beginning of J3 and also was ignored and closed or delete, don't know. And I meant no offence. Doesn't matter now.
What is matter is that finally it's noticed ! Hopefully it won't be ignored now. Thanks a lot !

**Comment by Bakual** [comment] 2016-06-15 16:09
Afaik we're using the tooltips from Bootstrap without any changes. So it may be worth looking for known isuses with Bootstrap tooltips.
it's also the difference between pre Joomla 3.0 tooltips (Mootools based) and post 3.0 (Bootstrap/jQuery tooltips).

**Comment by brianteeman** [comment] 2016-06-15 16:10
http://lmgtfy.com/?q=bootstrap+tooltip+flicker

**Comment by C-Lodder** [comment] 2016-08-17 08:36
I'll look into this as I too have the same issue (Firefox - Windows). When hovering over a link, the tooltip displays and instantly disappears. To get it working, I have to click around the page a bit and then it works.

**Comment by C-Lodder** [comment] 2016-08-18 16:04
PR submitted: https://github.com/joomla/joomla-cms/pull/11661

**Comment by brianteeman** [comment] 2016-08-18 16:14
Closed as we have a pr.

**Closed by brianteeman** 2016-08-18 16:14 UTC
Labels: No Code Attached Yet
