### ISSUE TITLE
[4.0] Languager Strings in plg_quickicon_joomlaupdate

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#22020] opened 2018-09-05 18:06 UTC
### Steps to reproduce the issue

1. Set a custom url for joomla update. For testing you can use custom url  https://www.jah-tz.de/downloads/core/gsoc18_override_management/gsoc18_update_list.xml
![joomla update options test administration 1](https://user-images.githubusercontent.com/9974686/44952982-d52dc080-ae8c-11e8-8417-310e0841d581.png)

2. Start a joomlaupdate via https://www.jah-tz.de/downloads/core/gsoc18_override_management/gsoc18_update_list.xml
![joomla update test administration 2](https://user-images.githubusercontent.com/9974686/44953005-3d7ca200-ae8d-11e8-9bdb-c0831d08eede.png)

### Expected result

All messages are correct.

### Actual result

In control pane I see the messages are not correct.
![control panel test administration 3](https://user-images.githubusercontent.com/9974686/44953066-7c5f2780-ae8e-11e8-8ce6-6e3164747681.png)

### System information (as much as possible)
The current 4.0-dev branch on ubuntu 18.04

### Additional comments

I noticed this while I tested an other PR: https://github.com/joomla/joomla-cms/pull/21851#issuecomment-417909495

**Comment by brianteeman** [comment] 2018-09-05 18:30
Another issue with the joomla-alert custom element? :(

**Comment by infograf768** [comment] 2018-09-06 09:03
Looks like we have an error in the js. Not sure if it is the cause
`${Joomla.JText._('PLG_QUICKICON_JOOMLAUPDATE_UPDATEFOUND_BUTOON')}</button>`
instead of
`PLG_QUICKICON_JOOMLAUPDATE_UPDATEFOUND_BUTTON`

**Comment by brianteeman** [comment] 2018-09-06 09:08
@infograf768 good spot. Will you do the PR for that please

**Comment by infograf768** [comment] 2018-09-06 10:04
I tested.
Although it is necessary to correct this typo, it does not solve the issue in Control Panel.

The problem is with the js code. After some corrections I can get.
<img width="365" alt="screen shot 2018-09-06 at 12 00 02" src="https://user-images.githubusercontent.com/869724/45150593-78a00d80-b1cc-11e8-926c-62b97e6246fd.png">

Which is not perfect yet (the `0`) but may depend from the package offered above as updating with it does not really change the J version.

Will try to make a PR this afternoon.

**Comment by infograf768** [comment] 2018-09-06 10:27
Closing as we have a patch at least for the language string. ;)
https://github.com/joomla/joomla-cms/pull/22023

**Closed as completed by infograf768** 2018-09-06 10:27 UTC
Labels: No Code Attached Yet, J4 Issue
