### ISSUE TITLE
HTMLHelper('select.radiolist') will not accept custom CSS class.

### ISSUE THREAD

**Issue by daycounts** [joomla/joomla-cms#41205] opened 2023-07-22 01:02 UTC
### Steps to reproduce the issue

Load a radio buttons list using HTMLHelper('select.radiolist') and pass a CSS class in the attributes.

<pre class="language-php"><code>$options=array();
$o = new stdClass();
$o-&gt;value = 1;
$o-&gt;text = 'option 1';
$options[] = $o;

$attribs=array();
$attribs['class'] = 'MyCLass'
HTMLHelper::_('select.radiolist', $options, 'fieldname', $attribs);</code></pre>

### Expected result

Both the <code class="notranslate">form-check-input</code> and <code class="notranslate">MyCLass</code> should be merged in one class attribute

<pre class="language-markup"><code>&lt;div class="controls"&gt;
  &lt;div class="form-check form-check-inline"&gt;
    &lt;input type="radio" class="form-check-input MyCLass"  name="fieldname" id="fieldname1" value="1"&gt;
    &lt;label for="fieldname1" class="form-check-label" id="fieldname1-lbl"&gt;option 1&lt;/label&gt;
  &lt;/div&gt;
&lt;/div&gt;
</code></pre>

### Actual result

<code class="notranslate">class</code> attribute is duplicated.

<pre class="language-markup"><code>&lt;div class="controls"&gt;
  &lt;div class="form-check form-check-inline"&gt;
    &lt;input type="radio" class="form-check-input"  name="fieldname" id="fieldname1" value="1" class="MyCLass"&gt;
    &lt;label for="fieldname1" class="form-check-label" id="fieldname1-lbl"&gt;option 1&lt;/label&gt;
  &lt;/div&gt;
&lt;/div&gt;</code></pre>

Modern browser will remove the second instance of the class attribute and that can cause developper headaches...
This is in particular an issue with Virtuemart that is loading some radio list and then some script is looking for the selected option based on a passed class but the class has been removed by the browser (or some cleanup / compress html scripts)

### System information (as much as possible)

Php 8.1
Joomla 4.3.3

**Comment by igchamp** [comment] 2023-07-22 06:15
bb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41205">issues.joomla.org/tracker/joomla-cms/41205</a>.</sub>

**Comment by igchamp** [comment] 2023-07-22 06:17
Thanks for sharing this amazing essay services topic in the UK. If you are looking to increase your Instagram following in the UK? Look no further than IG Champ, the best site to [buy Instagram followers in the UK](https://igchamp.co.uk/product/buy-instagram-followers-uk/ ""). With IG Champ, you can boost your account's visibility and credibility, giving you a greater chance of making a lasting impression on potential followers. A higher follower count makes your profile more attractive to others and can lead to increased engagement in the form of likes, comments, and shares. So, if you're ready to take your Instagram presence to the next level, head over to IG Champ and start growing your follower base today.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41205">issues.joomla.org/tracker/joomla-cms/41205</a>.</sub>

**Comment by brianteeman** [comment] 2023-08-10 07:06
Shouldnt the code be as follows?

`$attribs['class'] .= 'MyCLass'`

**Comment by Quy** [comment] 2023-08-10 11:39
`.=` is for string concatenation. It is fine since it is for an array.

**Comment by daycounts** [comment] 2023-08-10 22:10
That would not work since the function Select.radiolist is hardcoding the class "form-check-input" to the input 
You can refer to file : /libraries/src/HTML/Helpers/Select.php

`if (is_array($attribs)) {
            $attribs = ArrayHelper::toString($attribs);
        }`


`$html .= '<input type="radio" class="form-check-input" name="' . $name . '" id="' . $id . '" value="' . $k . '" '
                    . $extra . $attribs . '>';`

**Comment by brianteeman** [comment] 2023-09-01 21:59
I am changing this from a bug to a feature request. The HTMLHelper('select.radiolist') does not support the addition of an extra css class as you have seen so its not a bug

**Comment by richard67** [comment] 2024-04-27 15:52
Closing as having a pull request. Please test #43392 . Thanks in advance.

**Closed as completed by richard67** 2024-04-27 15:52 UTC
Labels: Feature, No Code Attached Yet
