### ISSUE TITLE
Sidebar overlaps the debug-area (3.4.0 beta)

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#5976] opened 2015-02-04 21:48 UTC
On a 3.4. beta installation set the dbugmode on. Then choose a component from the -components menu, com_contact or com_installer or something with filters in the sidebar.

The debug area is expected to be at the bottom, below the content
but it is overlapped by the sidebar

![screen shot 2015-02-04 at 15 44 00](http://issues.joomla.org/uploads/1/6d6651fb9a4a02f117d29e0ccb31bd28.png)

**Comment by zero-24** [comment] 2015-02-05 15:56
I can confirm this. Moving to RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5976">issues.joomla.org/joomla-cms/5976</a>.</sub>

**Comment by zero-24** [comment] 2015-02-05 15:57
opps ;) Moving to `Confirmed` :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5976">issues.joomla.org/joomla-cms/5976</a>.</sub>

**Comment by prasoon2211** [comment] 2015-02-06 05:01
A trivial fix is to change the positioning from `absolute` to `relative` (on the sidebar) and give a -20px margin-left. Honestly, I cannot see the point of the absolute positioning in the first place. I'll  submit patch soon.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5976">issues.joomla.org/joomla-cms/5976</a>.</sub>

**Comment by prasoon2211** [comment] 2015-02-06 17:52
I tried making a fix but I'm running into some transition issues. See the last comment of PR #5991 for more.

**Comment by JoomliC** [comment] 2015-03-02 01:55
I will check the code, because i the original PR for the new sidebar toggle, the debug message was tested, and integrated...
Wonder what change could have affected this behaviour in 3.4.0. :-|<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5976">issues.joomla.org/joomla-cms/5976</a>.</sub>

**Comment by JoomliC** [comment] 2015-03-02 02:29
Checked.
Note that if you close and open again the sidebar, the debug console is well displayed!
And the debug issue when loading a page is due to the debug console itself and that the best solution would be a new design for the debug console.

@prasoon2211 absolute position was there for a good reason : the show/hide effect.
Link to the original PR with all files changes to generate this collapsible sidebar.
https://github.com/joomla/joomla-cms/pull/5141
If you find a quick fix for debug console position when loading the page, you're welcome! ;-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5976">issues.joomla.org/joomla-cms/5976</a>.</sub>

**Comment by Harmageddon** [comment] 2015-03-12 09:48
Please have a look at #6401, which should fix this issue!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5976">issues.joomla.org/joomla-cms/5976</a>.</sub>

**Comment by zero-24** [comment] 2015-03-12 23:09
Closing as we have a RTC PR by @Harmageddon Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5976">issues.joomla.org/joomla-cms/5976</a>.</sub>

**Closed by zero-24** 2015-03-12 23:09 UTC
Labels: No Code Attached Yet
