### ISSUE TITLE
Batch window issue

### ISSUE THREAD

**Issue by julos081** [joomla/joomla-cms#9551] opened 2016-03-23 19:29 UTC
#### Steps to reproduce the issue
Go to Menu or articles list and try to do a batch to copy or move an item.

#### Expected result
The dropdown menu to select the category or menu has to be more visible.

#### Actual result
The popup Batch window to copy or move an article or menu item is too small and it's really difficult to work inside. The dropdown menu to select the category or menu is hidden in the window and does not go out of the window anymore.

#### System information (as much as possible)
Issue found on Chrome, Firefox and IE.

#### Additional comments
Solution found by removing overflow-y: auto !important; for .modal-body as previous release 3.4.8

**Comment by dgt41** [comment] 2016-03-23 19:42
Confirmed

**Comment by Twincarb** [comment] 2016-03-23 20:48
a quick look at the css shows at the end the following, is the } in bold in the wrong place? and should it be at the end?

@media (max-width: 767px) {
	.field-media-wrapper .modal .modal-body {
		padding: 5px 0;
	}
**}**
.modal-body {
	-webkit-overflow-scrolling: touch;
	overflow-y: auto !important;
}<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9551">issues.joomla.org/joomla-cms/9551</a>.</sub>

**Comment by andrepereiradasilva** [comment] 2016-03-23 22:38
confirmed

**Comment by brianteeman** [comment] 2016-04-01 10:16
Closed as we have a PR #9683 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9551">issues.joomla.org/joomla-cms/9551</a>.</sub>

**Closed by brianteeman** 2016-04-01 10:16 UTC
Labels: No Code Attached Yet

**Comment by JoomliC** [comment] 2016-04-09 19:01
The redo of Bootstrap scrolling fix in this PR: https://github.com/joomla/joomla-cms/pull/9817 should solve the issue ;-)
@dgt41 your code review is welcome ;-) (and note: i have remove too css padding fix for media BS modal, as remove since the initial PR when i added it...)
