### ISSUE TITLE
Search by page option missing in module manager J3.7

### ISSUE THREAD

**Issue by AndLincoln** [joomla/joomla-cms#15621] opened 2017-04-27 11:50 UTC
The option to search by page in module manager search tools has disappeared in Joomla 3.7

**Comment by brianteeman** [comment] 2017-04-27 13:16
I can confirm that this is a bug

**Comment by brianteeman** [comment] 2017-04-27 13:28
The bug is that this line which exists so that the page type is only displayed as a filter for site modules   is not being processed

https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_modules/models/forms/filter_modules.xml#L55

**Comment by kyriacoullis** [comment] 2017-05-05 10:16
I have the same issue. Is there a solution for this?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15621">issues.joomla.org/tracker/joomla-cms/15621</a>.</sub>

**Comment by brotherdoomsday** [comment] 2017-05-09 17:47
I to have the same issue with J3.7, is there a solution for this? The question should be how soon will there be a solution for this ? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15621">issues.joomla.org/tracker/joomla-cms/15621</a>.</sub>

**Comment by vebnara** [comment] 2017-05-09 20:41
A temp work around or anyone who needs it is to edit /administrator/components/com_modules/models/forms/filter_modules.xml and remove line 55 which is 'showon="client_id:0"' the page filter will reappear for you.

**Comment by ufuk-avcu** [comment] 2017-05-10 08:20
I can confirm this problem also in Joomla 3.7.0

**Comment by communic8** [comment] 2017-05-19 07:24
The problem is not solved in J3.7.1

**Comment by AlexRed** [comment] 2017-05-19 07:38
Sorry, but there is a rule here that does not allow to confirm yet an open issue :(

**Comment by infograf768** [comment] 2017-05-19 07:38
I am looking now for a solution.

**Comment by franz-wohlkoenig** [comment] 2017-05-19 07:52
@AlexRed i thinks its helpfull to confirm a new issue. It doesn't help if many People confirm after each update that Issue exists.

**Comment by AlexRed** [comment] 2017-05-19 07:56
Hello @franz-wohlkoenig, also I thinks its helpfull to confirm the issue in a new Joomla version, but when I do it I was accused of be a troll  8244#issuecomment-298604672   :(
I believe that if this rule exists, it must be respected for everyone.

**Comment by infograf768** [comment] 2017-05-19 08:04
@AlexRed  @franz-wohlkoenig @communic8
Please test https://github.com/joomla/joomla-cms/pull/16118

Closing as we have a patch

**Closed by infograf768** 2017-05-19 08:04 UTC
Labels: No Code Attached Yet

**Comment by mbabker** [comment] 2017-05-19 11:42
> also I thinks its helpfull to confirm the issue in a new Joomla version, but when I do it I was accused of be a troll

The issue in your case is you went to several issues which had already been confirmed as issues and had clearly had no action taken on those issues just to state "yep, still an issue".  We don't need that kind of reconfirmation on confirmed issues with every release.  If/When someone decides to work on the issue, they'd have to confirm they can duplicate it to fix it anyway so at that point if they can't confirm it either they ask for additional info or can close the item.

Yes, it is helpful when a few folks can confirm something, but we don't need a new post of "still an issue" every few days.

**Comment by AlexRed** [comment] 2017-05-19 11:50
sure, not every few days. But can I write after tens of days and for different Joomla version?

**Comment by brianteeman** [comment] 2017-05-19 11:53
As stated by @mbabker no you cannot. It serves no value at all. If it is such a major issue for you then submit a pr or find someone who can.

**Comment by AlexRed** [comment] 2017-05-19 11:54
ok, but this rule is for all or only for me ?

**Comment by mbabker** [comment] 2017-05-19 11:56
It's a general rule of thumb.  Once an issue is confirmed, we don't need people to post on it reminding us that there is an open confirmed issue.  Obviously we can't stop people from doing it, but as a courtesy, we ask that you don't.  For some the issue will be more important than others, but it will either eventually get fixed or remain in an open and confirmed state.

**Comment by AlexRed** [comment] 2017-05-19 11:59
ok, here I write it: https://github.com/joomla/joomla-cms/issues/15621#issuecomment-302632135
but  franz-wohlkoenig say its helpfull to confirm, I know for you and Brian is not helpfull.

**Comment by mbabker** [comment] 2017-05-19 12:01
When an issue is first opened, it is helpful to test and confirm the issue actually exists.  But if we needed to reconfirm every open issue with every release we honestly wouldn't get much else done because we'd spend most of our time retesting 400+ open issues every few weeks.

Maybe if an issue was opened around 3.6.1 or 3.6.2 it'd be good to reconfirm it.  But for something opened during the 3.7 beta/RC or after 3.7.0, not so much.

**Comment by AlexRed** [comment] 2017-05-19 12:05
ok, like I write here: "Sorry, but there is a rule here that does not allow to confirm yet an open issue :("

ok to reconfirm it for old issue.

**Comment by mbabker** [comment] 2017-05-19 12:06
I can't speak for the workflow of others, but in my case, I manage and monitor GitHub almost exclusively through email for projects where I have some kind of maintainership role, which means I'm getting email notifications for everything (commit comments, new commits on PRs, new issues/PRs, items being closed).  It adds to the amount of time I have to spend in my email clearing my queue when there is a stream of "issue still exists" messages.  For items that are still fairly new, I don't feel like those messages are adding any value.  When it's an older issue (I'd say 3-4 months old minimum), it can be helpful.

**Comment by AlexRed** [comment] 2017-05-19 12:07
ok, I hope all we can use this rule.

**Comment by rdeutz** [comment] 2017-05-19 12:17
The other way around would be more helpful, I am pretty sure a lot of the 500 issues we have are obsolet so we could close them. If someone would go to the old ones and commenting when an issue is no longer valid then we could concentrate on the valid ones.

**Comment by AlexRed** [comment] 2017-05-19 12:21
For example the issue where brian accuses me of being a troll is 564 day old. It's right to be accused or just right reconfirm it for old issue.

Now I confirm one old 146 day, is it ok? https://github.com/joomla/joomla-cms/issues/13365#issuecomment-302688007

**Comment by kyriacoullis** [comment] 2017-05-19 12:24
Guys,

Can you please exchange phone numbers and have a conversation? I have
received 22 email notifications the last 4 hours from this threat.




George Kyriacoullis
Multimedia Freelancer

*Web Development | 360 Virtual Tours | Social Media Profile Management |
SEO*
*Tel:* 99436638 <99%20436638>
*Facebook:* CyprusVirtualTours <https://www.facebook.com/CyprusVirtualTours>

**Comment by vebnara** [comment] 2017-05-19 12:32
THIS IS CRAZY OVER 20 NOTIFICATIONS IN AN HOUR NONE IF WHICH RELATE TO THE ISSUE.. you have gone totally off topic, this isn't a bitching forum about how git hub or the joomla Dec team handles bug reports. It's about a specific issue to which I posted a work around to 10 days ago. Please STOP COMMENTING UNLESS IT'S TO ADD SOMETHING MEANINGFUL TO THE ISSUE. 

ps I know I've just added to the mails and for that I'm sorry but hopefully everyone will be respectful and get back on topic.
