### ISSUE TITLE
[4.4 Bug] Forms Required fields

### ISSUE THREAD

**Issue by joomleb** [joomla/joomla-cms#42232] opened 2023-10-27 16:53 UTC
Hi guys,
PHP 7.4.x & 8.1.x + Joomla.4.4 (I did not test it on J5)

What I describe here for the Helix Ultimate:
https://github.com/JoomShaper/helix-ultimate/issues/364
it is happening also on Cassiopeia and not only with the "Forgot your password" link, but also when I click on any site link (menu items).

Why it is happening? Because:
**1** - Joomla is checking the Required fields per field and not when the Login and  / or the Register button is clicked
**2** - the Login page is loaded with the "Username" field yet selected (something that is not happening in the Registration page).

As I wrote, it is a simple issue, but it is causing users to panic as they don't understand what happened and they think to have made a mistake (which doesn't exist) because the field is marked as Required red and the page is not redirected to the link.

Sure you can replicate it,  Do you have any suggestion for the solution ?
From my point of view, for each point:
**1** - to check the Required Fields on all Joomla Forms  (Login page, Registration page, Contact page) only when the Login / the Register etc. button is clicked, NOT per field.
**2** - Once solved the point 1, to open also the Registration page with the "Name" field (the first one) as yet selected > better because is on click less for the User Experience

**Comment by brianteeman** [comment] 2024-11-26 17:21
I have read and re-read this several times and I am sorry I do not understand what the problem is that you are reporting

**Comment by chmst** [comment] 2024-11-26 17:29
Closing this as it is not for Joomla Core. Please watch the issue on the joomshaper forum.

**Closed as completed by chmst** 2024-11-26 17:29 UTC
Labels: No Code Attached Yet, bug
