### ISSUE TITLE
Filters set in com_content stay active in com_menu

### ISSUE THREAD

**Issue by mikeveeckmans** [joomla/joomla-cms#14193] opened 2017-02-22 21:39 UTC
### Steps to reproduce the issue
![comcontent-filters](https://cloud.githubusercontent.com/assets/4589318/23233597/a2d885aa-f94f-11e6-9265-d92cee26e7f8.gif)

### Expected result
In com_menu when creating new article have no filters active

### Actual result
Filters set prior in com_content are active in com_menu when creating a new article by menu item

**Comment by Bakual** [comment] 2017-02-22 21:52
I'd say this is intended behavior. The code (in this case the user states) don't care if you open an article edit view in a modal or full window, the only difference is in the layout.

**Comment by mikeveeckmans** [comment] 2017-02-22 21:58
and the component you're working in...

**Comment by coolcat-creations** [comment] 2017-02-22 22:00
i remember the same thing happened when selecting a module in tinyMCE which was fixed...?

**Comment by Bakual** [comment] 2017-02-22 22:07
> and the component you're working in...

It's always com_content when you open an article edit form. The code doesn't know if the modal is openened from com_menu or com_content or even an smartphone app or whatever.

You would have to either pass an additional request parameter which can be detected (eg ignoreuserstates=1) or work from the layout (which is a bad idea) and then do some different processing based on that.

**Comment by franz-wohlkoenig** [comment] 2017-04-04 17:55
closing as Expected Behaviour.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14193">issues.joomla.org/tracker/joomla-cms/14193</a>.</sub>

**Closed by franz-wohlkoenig** 2017-04-04 17:55 UTC
Labels: No Code Attached Yet
