### ISSUE TITLE
The Joomla! Core database tables have not been converted yet to UTF-8 Multibyte (utf8mb4).

### ISSUE THREAD

**Issue by ltraveler** [joomla/joomla-cms#9511] opened 2016-03-22 07:55 UTC
#### Steps to reproduce the issue
Click on button Fix in Joomla update

#### Expected result
Fix the database

#### Actual result
After some minutes of waiting getting error 
405 Not Allowed

nginx/1.8.1

#### System information (as much as possible)

Setting	Value
 
PHP Built On	Linux 
Database Version	5.5.42-37.1-log
Database Collation	latin1_swedish_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	5.4.43
Web Server	Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 3.5.1-dev Development [ Unicorn ] 21-March-2016 22:00 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

#### Additional comments

My current database kind of big. About 60 Mb.
Through the upgrade procedure from 3.4.8 to 3.5 upgrade process also took kind of long time and then I've got a message like that:

*****

ERROR 504 - GATEWAY TIMEOUT

Why am I seeing this page?

The server that your request has reached is acting as a gateway or proxy to fulfil the request made by your client.

Web Browser => Web Front-End => Web Back-End

This server (Web Front-End) received an invalid response from an upstream (Web Back-End) server it accessed to fulfil the request.

In most cases this will not mean that the upstream server is down, but rather that the upstream server and the gateway/proxy do not agree on the protocol for exchanging data.

This problem is most commonly caused when there is a problem with IP communications between the Web Front and Back-Ends. Before you attempt to resolve this problem you should clear your browser cache completely.

Our support staff will be happy to assist you in resolving this issue. Please contact our Live Support or reply to any Tickets you may have received from our technicians for further assistance.

*****

Then I applied the dev patch 3.5.1.
But the problem still exists.

**Comment by richard67** [comment] 2016-03-22 09:13
Can you swich on error loggin in php.ini and see if some php errors are logged in your log file then?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9511">issues.joomla.org/joomla-cms/9511</a>.</sub>

**Comment by richard67** [comment] 2016-03-22 09:21
Question: In "Global Settings -> System -> Session Settings", which value does the "Session Lifetime" parameter have? Is it about the number of minutes you refer to with "After some minutes of waiting getting error"?

If so, could you try to enlarge this parameter? E.g. if it is 5, could you enlarge it to 15? or if it is 15, could you enlarge it to 30? And then log out, clear browser cache, log in to backend again and try again the Database "Fix" button?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9511">issues.joomla.org/joomla-cms/9511</a>.</sub>

**Comment by richard67** [comment] 2016-03-22 09:29
For others who read, the "dev patch 3.5.1" which @ltraveler refers to is not an official one, it is the one I provided in my PR #9510 for testing. But it should not cause such problems.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9511">issues.joomla.org/joomla-cms/9511</a>.</sub>

**Comment by richard67** [comment] 2016-03-22 10:45
@ltraveler If you cannot wait for a patch or a Joomla! 3.5.1, because this could take a bit time, there is maybe a way to help out.

It would be a bit uncomfortable but maybe fix your site, and if not it would at least show where problems e.g. with too long runtimes of SQL statements occur.

It would be to run the SQL statements for utf8mb4 conversion in phpMyadmin so you can see where errors or long run times happen.

There are 2 sets of statements for 2 execution steps:

Step 1: Dropping of indexes - these statements may cause "index to be dropped does not exist" errors, if some index already has been dropped before but later re-creation failed. Ignore the error and coninue with the next statement then.

Step 2: All other stuff for conversion - here you should report if errors or long runtimes occur.

You can find these statements in 2 scripts, 1 for each step. You should use the files from my PR #9510 , and you can find them here:

File for Step 1: [utf8mb4-conversion-01.sql](https://github.com/richard67/joomla-cms/blob/correct-utf8-conversion-2016-03-21/administrator/components/com_admin/sql/others/mysql/utf8mb4-conversion-01.sql "https://github.com/richard67/joomla-cms/blob/correct-utf8-conversion-2016-03-21/administrator/components/com_admin/sql/others/mysql/utf8mb4-conversion-01.sql")

File for Step 2: [utf8mb4-conversion-02.sql](https://github.com/richard67/joomla-cms/blob/correct-utf8-conversion-2016-03-21/administrator/components/com_admin/sql/others/mysql/utf8mb4-conversion-02.sql "https://github.com/richard67/joomla-cms/blob/correct-utf8-conversion-2016-03-21/administrator/components/com_admin/sql/others/mysql/utf8mb4-conversion-02.sql")

Can you try that and let us know the result?

I know it is not comfortable but would be a great help for us to identify the problem, and it could also fix your site because the php timeout or Joomla!'s sesion timeout will not be a problem when running the statements in phpMyAdmin and not in a php script.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9511">issues.joomla.org/joomla-cms/9511</a>.</sub>

**Comment by ltraveler** [comment] 2016-03-22 12:27
This is the the errors from my php:

[21-Mar-2016 20:53:11 America/Denver] PHP Warning:  session_start(): Cannot send session cookie - headers already sent by (output started at /home*/***/public_html/*******/includes/defines.php:121) in /home*/***/public_html/*******/libraries/joomla/session/session.php on line 651
[21-Mar-2016 20:53:11 America/Denver] PHP Warning:  session_start(): Cannot send session cache limiter - headers already sent (output started at /home*/***/public_html/*******/includes/defines.php:121) in /home*/***/public_html/*******/libraries/joomla/session/session.php on line 651
[21-Mar-2016 20:53:12 America/Denver] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home*/***/public_html/*******/includes/defines.php:121) in /home*/***/public_html/*******/libraries/joomla/input/cookie.php on line 85
[21-Mar-2016 22:16:21 America/Denver] PHP Warning:  Creating default object from empty value in /home*/***/public_html/*******/administrator/components/com_ose_cpu/packages/packages.php on line 214
[21-Mar-2016 22:22:59 America/Denver] PHP Warning:  mysqli::stat(): Couldn't fetch mysqli in /home*/***/public_html/*******/libraries/joomla/database/driver/mysqli.php on line 202
[21-Mar-2016 22:22:59 America/Denver] PHP Warning:  mysqli_close(): Couldn't fetch mysqli in /home*/***/public_html/*******/libraries/joomla/database/driver/mysqli.php on line 209
[21-Mar-2016 22:22:59 America/Denver] PHP Warning:  mysqli::stat(): Couldn't fetch mysqli in /home*/***/public_html/*******/libraries/joomla/database/driver/mysqli.php on line 202
[21-Mar-2016 22:22:59 America/Denver] PHP Warning:  mysqli_close(): Couldn't fetch mysqli in /home*/***/public_html/*******/libraries/joomla/database/driver/mysqli.php on line 209
[21-Mar-2016 22:22:59 America/Denver] PHP Warning:  mysqli::stat(): Couldn't fetch mysqli in /home*/***/public_html/*******/libraries/joomla/database/driver/mysqli.php on line 202
[21-Mar-2016 22:22:59 America/Denver] PHP Warning:  mysqli_close(): Couldn't fetch mysqli in /home*/***/public_html/*******/libraries/joomla/database/driver/mysqli.php on line 209
[21-Mar-2016 22:22:59 America/Denver] PHP Warning:  mysqli::stat(): Couldn't fetch mysqli in /home*/***/public_html/*******/libraries/joomla/database/driver/mysqli.php on line 202
[21-Mar-2016 22:22:59 America/Denver] PHP Warning:  mysqli_close(): Couldn't fetch mysqli in /home*/***/public_html/*******/libraries/joomla/database/driver/mysqli.php on line 209
[21-Mar-2016 22:22:59 America/Denver] PHP Warning:  mysqli::stat(): Couldn't fetch mysqli in /home*/***/public_html/*******/libraries/joomla/database/driver/mysqli.php on line 202
[21-Mar-2016 22:22:59 America/Denver] PHP Warning:  mysqli_close(): Couldn't fetch mysqli in /home*/***/public_html/*******/libraries/joomla/database/driver/mysqli.php on line 209
[21-Mar-2016 22:22:59 America/Denver] PHP Warning:  mysqli::stat(): Couldn't fetch mysqli in /home*/***/public_html/*******/libraries/joomla/database/driver/mysqli.php on line 202
[21-Mar-2016 22:22:59 America/Denver] PHP Warning:  mysqli_close(): Couldn't fetch mysqli in /home*/***/public_html/*******/libraries/joomla/database/driver/mysqli.php on line 209
[21-Mar-2016 22:22:59 America/Denver] PHP Warning:  mysqli::stat(): Couldn't fetch mysqli in /home*/***/public_html/*******/libraries/joomla/database/driver/mysqli.php on line 202
[21-Mar-2016 22:22:59 America/Denver] PHP Warning:  mysqli_close(): Couldn't fetch mysqli in /home*/***/public_html/*******/libraries/joomla/database/driver/mysqli.php on line 209
[21-Mar-2016 22:22:59 America/Denver] PHP Warning:  mysqli::stat(): Couldn't fetch mysqli in /home*/***/public_html/*******/libraries/joomla/database/driver/mysqli.php on line 202
[21-Mar-2016 22:22:59 America/Denver] PHP Warning:  mysqli_close(): Couldn't fetch mysqli in /home*/***/public_html/*******/libraries/joomla/database/driver/mysqli.php on line 209
[22-Mar-2016 00:21:57 America/Denver] PHP Warning:  mysqli::stat(): Couldn't fetch mysqli in /home*/***/public_html/*******/libraries/joomla/database/driver/mysqli.php on line 219
[22-Mar-2016 00:21:57 America/Denver] PHP Warning:  mysqli_close(): Couldn't fetch mysqli in /home*/***/public_html/*******/libraries/joomla/database/driver/mysqli.php on line 226
[22-Mar-2016 00:21:57 America/Denver] PHP Warning:  mysqli::stat(): Couldn't fetch mysqli in /home*/***/public_html/*******/libraries/joomla/database/driver/mysqli.php on line 219
[22-Mar-2016 00:21:57 America/Denver] PHP Warning:  mysqli_close(): Couldn't fetch mysqli in /home*/***/public_html/*******/libraries/joomla/database/driver/mysqli.php on line 226
[22-Mar-2016 00:21:57 America/Denver] PHP Warning:  mysqli::stat(): Couldn't fetch mysqli in /home*/***/public_html/*******/libraries/joomla/database/driver/mysqli.php on line 219
[22-Mar-2016 00:21:57 America/Denver] PHP Warning:  mysqli_close(): Couldn't fetch mysqli in /home*/***/public_html/*******/libraries/joomla/database/driver/mysqli.php on line 226
[22-Mar-2016 00:21:57 America/Denver] PHP Warning:  mysqli::stat(): Couldn't fetch mysqli in /home*/***/public_html/*******/libraries/joomla/database/driver/mysqli.php on line 219
[22-Mar-2016 00:21:57 America/Denver] PHP Warning:  mysqli_close(): Couldn't fetch mysqli in /home*/***/public_html/*******/libraries/joomla/database/driver/mysqli.php on line 226
[22-Mar-2016 00:21:57 America/Denver] PHP Warning:  mysqli::stat(): Couldn't fetch mysqli in /home*/***/public_html/*******/libraries/joomla/database/driver/mysqli.php on line 219
[22-Mar-2016 00:21:57 America/Denver] PHP Warning:  mysqli_close(): Couldn't fetch mysqli in /home*/***/public_html/*******/libraries/joomla/database/driver/mysqli.php on line 226
[22-Mar-2016 00:21:57 America/Denver] PHP Warning:  mysqli::stat(): Couldn't fetch mysqli in /home*/***/public_html/*******/libraries/joomla/database/driver/mysqli.php on line 219
[22-Mar-2016 00:21:57 America/Denver] PHP Warning:  mysqli_close(): Couldn't fetch mysqli in /home*/***/public_html/*******/libraries/joomla/database/driver/mysqli.php on line 226
[22-Mar-2016 00:21:57 America/Denver] PHP Warning:  mysqli::stat(): Couldn't fetch mysqli in /home*/***/public_html/*******/libraries/joomla/database/driver/mysqli.php on line 219
[22-Mar-2016 00:21:57 America/Denver] PHP Warning:  mysqli_close(): Couldn't fetch mysqli in /home*/***/public_html/*******/libraries/joomla/database/driver/mysqli.php on line 226
[22-Mar-2016 00:21:57 America/Denver] PHP Warning:  mysqli::stat(): Couldn't fetch mysqli in /home*/***/public_html/*******/libraries/joomla/database/driver/mysqli.php on line 219
[22-Mar-2016 00:21:57 America/Denver] PHP Warning:  mysqli_close(): Couldn't fetch mysqli in /home*/***/public_html/*******/libraries/joomla/database/driver/mysqli.php on line 226
[22-Mar-2016 00:21:57 America/Denver] PHP Warning:  mysqli::stat(): Couldn't fetch mysqli in /home*/***/public_html/*******/libraries/joomla/database/driver/mysqli.php on line 219
[22-Mar-2016 00:21:57 America/Denver] PHP Warning:  mysqli_close(): Couldn't fetch mysqli in /home*/***/public_html/*******/libraries/joomla/database/driver/mysqli.php on line 226
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9511">issues.joomla.org/joomla-cms/9511</a>.</sub>

**Comment by ltraveler** [comment] 2016-03-22 12:31
All things I've made using incognito window so it shouldn't be a reason.
Session Lifetime: 60
Session Handler: Database<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9511">issues.joomla.org/joomla-cms/9511</a>.</sub>

**Comment by ltraveler** [comment] 2016-03-22 12:31
The error comes after 2-3 minutes<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9511">issues.joomla.org/joomla-cms/9511</a>.</sub>

**Comment by richard67** [comment] 2016-03-22 12:34
@wilsonge Can you check the [above error output](https://github.com/joomla/joomla-cms/issues/9511#issuecomment-199787167) if it is something caused by session handling stuff, or if it is just the session being timed out?

**Comment by ltraveler** [comment] 2016-03-22 12:36
It is magic but after last time of trying I've got the same error
*****
405 Not Allowed

nginx/1.8.1
*****
But when I checked the database for error again Joomla said that there is no errors. So I'm confused...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9511">issues.joomla.org/joomla-cms/9511</a>.</sub>

**Comment by ltraveler** [comment] 2016-03-22 12:36
Right now I'm under the patch, so hope it will no produce any problems for the future updates.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9511">issues.joomla.org/joomla-cms/9511</a>.</sub>

**Comment by ltraveler** [comment] 2016-03-22 12:39
Should a make that 2 steps in your last message with my database?.. If it helps I could but as I said right now Joomla did not see any problems with the database.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9511">issues.joomla.org/joomla-cms/9511</a>.</sub>

**Comment by richard67** [comment] 2016-03-22 12:39
You mean my patch from pull request #9510 ?

You know that untested and unmerged pull requests are not meant to be applied on production sites?

If it gets merged without mayor changes it will not be a problem for you whenlater updating to real 3.5.1, but in case if stuff has to be changed in my PR (patch) I cannot guarantee that now in advance.

**Comment by richard67** [comment] 2016-03-22 12:41
If your database is ok now, no need to execute the sql. Check your components and the site, frontend and backend, if all works. If not, you can try to execute the 2 steps above.

**Comment by ltraveler** [comment] 2016-03-22 12:45
I mean that one:

@ltraveler If you cannot wait for a patch or a Joomla! 3.5.1, because this could take a bit time, there is maybe a way to help out.

It would be a bit uncomfortable but maybe fix your site, and if not it would at least show where problems e.g. with too long runtimes of SQL statements occur.

It would be to run the SQL statements for utf8mb4 conversion in phpMyadmin so you can see where errors or long run times happen.

There are 2 sets of statements for 2 execution steps:

Step 1: Dropping of indexes - these statements may cause "index to be dropped does not exist" errors, if some index already has been dropped before but later re-creation failed. Ignore the error and coninue with the next statement then.

Step 2: All other stuff for conversion - here you should report if errors or long runtimes occur.

You can find these statements in 2 scripts, 1 for each step. You should use the files from my PR #9510 , and you can find them here:

File for Step 1: utf8mb4-conversion-01.sql

File for Step 2: utf8mb4-conversion-02.sql

Can you try that and let us know the result?

I know it is not comfortable but would be a great help for us to identify the problem, and it could also fix your site because the php timeout or Joomla!'s sesion timeout will not be a problem when running the statements in phpMyAdmin and not in a php script.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9511">issues.joomla.org/joomla-cms/9511</a>.</sub>

**Comment by richard67** [comment] 2016-03-22 12:47
I know that you mean that one. And I answered just above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9511">issues.joomla.org/joomla-cms/9511</a>.</sub>

**Comment by ltraveler** [comment] 2016-03-22 12:47
Well I already applied your patch but you said that it is safety, so hope that I will not get any problems in a future update to 3.5.1
For now should I delete custom url and switch back to the Joomla default branch?..<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9511">issues.joomla.org/joomla-cms/9511</a>.</sub>

**Comment by richard67** [comment] 2016-03-22 12:48
Yes, and as I said, you normally should not use a live site for testing with custom url. In future please test with a copy of your site (both files and database a copy of course).

**Comment by ltraveler** [comment] 2016-03-22 12:51
Thank you very much richard67 it was a bit stressful for me to make this upgrade anyway next time I will be more careful and congratulations you've made amazing job with joomla 3.5

**Comment by richard67** [comment] 2016-03-22 12:54
Thanks. Please check if everything on your site is working as you expected, and if so, please close this issue, otherwise, if not, report back the problems. Good luck.

**Comment by richard67** [comment] 2016-03-22 14:26
@ltraveler IMPORTANT: Please remove the following sql script from your server:

administrator/components/com_admin/sql/updates/mysql/3.5.1-2016-03-22.sql

It is the one which came with my patch, and it may cause problems if you later want to update to 3.5.1, because it will very likely be that before my patch will be put into a release, I have to change things on it or even remove this script.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9511">issues.joomla.org/joomla-cms/9511</a>.</sub>

**Comment by richard67** [comment] 2016-03-25 14:23
New PR is #9590 , please test.

**Comment by ltraveler** [comment] 2016-04-18 17:32
@richard67 Well I already upgraded my website on 3.5.1 without deleting this script could it produce futured problems?
Should I deleted now?..

**Comment by ltraveler** [comment] 2016-04-18 17:35
Just noticed that the file still exists and has this code:

`
--
-- Reset utf8/utf8mb4 conversion status to force conversion after update
-- because the conversion has been changed (handling of forgotten columns
-- and indexes added)
--

UPDATE `#__utf8_conversion` SET `converted` = 0;

`

**Comment by richard67** [comment] 2016-04-18 17:40
@ltraveler Yes, delete it.

**Comment by ltraveler** [comment] 2016-04-18 17:42
@richard67 Should I apply any other patches? Or everything is fine and if there is no problem now with a database checking so that means I am fully upgraded to 3.5.1?..
Thank you.

**Comment by richard67** [comment] 2016-04-18 17:44
If your backend shows the right version number at the right bottom corner (with Isis template) and the database schema is up to date (.i.e. database checker shows all ok), then all should be OK.

**Comment by ltraveler** [comment] 2016-04-18 17:46
Thank you very much @richard67

**Closed** 2016-04-18 18:12 UTC
Labels: No Code Attached Yet
