### ISSUE TITLE
Error in com_tag

### ISSUE THREAD

**Issue by vzenix** [joomla/joomla-cms#6055] opened 2015-02-11 13:23 UTC
#### Steps to reproduce the issue
Go to: (Home URL Joomla)/index.php?option=com_tags

#### Expected result
List of Tags

#### Actual result
( ! ) Notice: Trying to get property of non-object in (Joomla Public Dir)\components\com_tags\views\tags\view.html.php on line 125
Call Stack

( ! ) Strict standards: Creating default object from empty value in (Joomla Public Dir)\components\com_tags\views\tags\view.html.php on line 126
Call Stack

( ! ) Notice: Undefined property: stdClass::$title in (Joomla Public Dir)\components\com_tags\views\tags\view.html.php on line 174
Call Stack

( ! ) Notice: Undefined property: stdClass::$metadesc in (Joomla Public Dir)\components\com_tags\views\tags\view.html.php on line 201
Call Stack

( ! ) Notice: Undefined property: stdClass::$metadesc in (Joomla Public Dir)\components\com_tags\views\tags\view.html.php on line 205
Call Stack

( ! ) Notice: Undefined property: stdClass::$metakey in (Joomla Public Dir)components\com_tags\views\tags\view.html.php on line 210
Call Stack

( ! ) Notice: Undefined property: stdClass::$metakey in (Joomla Public Dir)\components\com_tags\views\tags\view.html.php on line 214
Call Stack

( ! ) Notice: Undefined property: stdClass::$created_user_id in (Joomla Public Dir)\components\com_tags\views\tags\view.html.php on line 226
Call Stack

( ! ) Notice: Trying to get property of non-object in (Joomla Public Dir)\components\com_tags\views\tags\view.html.php on line 229
Call Stack

( ! ) Fatal error: Call to a member function toArray() on a non-object in (Joomla Public Dir)\components\com_tags\views\tags\view.html.php on line 229
Call Stack

#### System information (as much as possible)
PHP Built On 	Windows NT NAMIR-PC 6.1 build 7601 (Windows 7 Ultimate Edition Service Pack 1) i586
Database Version 	10.50.1600
Database Collation 	MSSQL UTF-8 (UCS2)
PHP Version 	5.3.28
Web Server 	Microsoft-IIS/7.5
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 3.3.6 Stable [ Ember ] 01-October-2014 02:00 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0 

#### Additional comments
I Change a line in the function display

if ($active)
{ (code) }
else
{ (code) }

for

if ($active)
{ (code) }
else if(isset($item[0]->params))
{ (code) }

File: HOME/components/com_tags/views/tags/tags.php -> Function display

**Comment by infograf768** [comment] 2015-02-11 17:52
Can you test with beta3  as I can't reproduce here.
https://github.com/joomla/joomla-cms/releases/tag/3.4.0-beta3

**Comment by pcmitsis** [comment] 2015-02-22 04:39
I could not reproduce it either with the beta3 version.

System:
Apache/2.4.7
PHP 5.5.9
mysql  Ver 14.14 Distrib 5.5.41,
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:35.0) Gecko/20100101 Firefox/35.0

**Comment by kathastaden** [comment] 2015-08-25 13:16
Just tested it with: 

Joomla 3.4.4
Chrome (44.0.2403.130), 
MySQLi 5.6.21, 
PHP 5.5.18,
Apache/2.2.29

and I can not reproduce the errors. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6055">issues.joomla.org/joomla-cms/6055</a>.</sub>

**Comment by zero-24** [comment] 2015-08-25 13:32
Closing as it can't be reproduced any more. If we get a more detailed description this can allways be reopend. Thanks :smile:

**Closed by zero-24** 2015-08-25 13:32 UTC
Labels: No Code Attached Yet

**Comment by planetcrypton** [comment] 2015-08-28 11:01
I could reproduce this error when being logged in through the frontend(editing).
It's only line nr 253 (Joomla 3.4.3) in my case.

Fatal error: Call to a member function toArray() on a non-object in components/com_tags/views/tags/view.html.php on line 253

Which must be referring to this line:
```php
$mdata = $this->item->metadata->toArray();
```

**Comment by infograf768** [comment] 2015-08-28 14:47
Hmm, is not there something weird in that file : `components/com_tags/views/tags/view.html.php` ?
The method getItem() does not exist in the tags model, only in the tag model, therefore `$this->item` is always `null` on my test site and I can't anyway reproduce the possible issue.
