### ISSUE TITLE
[com_menus] Unknown column 'p.id' in 'where clause' when parent_id is set

### ISSUE THREAD

**Issue by selfget** [joomla/joomla-cms#10618] opened 2016-05-24 22:03 UTC
#### Steps to reproduce the issue

In /administrator/components/com_menus/model/items.php, function:

protected function getListQuery()

		// Filter the items over the parent id if set.
		$parentId = $this->getState('filter.parent_id');

		if (!empty($parentId))
		{
			$query->where('p.id = ' . (int) $parentId);
		}

But p.id causes an SQL error (there is no table with p alias in the query build. Probably it should be:

		// Filter the items over the parent id if set.
		$parentId = $this->getState('filter.parent_id');

		if (!empty($parentId))
		{
			//$query->where('p.id = ' . (int) $parentId);
			$query->where('a.parent_id = ' . (int) $parentId);
		}

#### System information (as much as possible)

The issue was detected in Joomla 3.5.1

**Comment by sovainfo** [comment] 2016-05-24 22:44
Regression due to commit on Jan 5, 2010 by Hackwar
Removing the table with p alias but not changing references!

**Comment by mbabker** [comment] 2016-05-24 22:54
And the award for the longest lived bug in what has to be the biggest edge case in Joomla goes to... 😆

**Comment by brianteeman** [comment] 2016-05-25 09:28
Closed as we have a PR #10618 thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10618">issues.joomla.org/joomla-cms/10618</a>.</sub>

**Comment by alikon** [comment] 2016-05-25 09:28
@selfget can you test #10620

**Closed by brianteeman** 2016-05-25 09:28 UTC
Labels: No Code Attached Yet

**Comment by selfget** [comment] 2016-05-26 09:00
@alikon tested and it works now
