### ISSUE TITLE
Reordering Categories in Articles:Categories view caused JavaScript errors

### ISSUE THREAD

**Issue by aantic** [joomla/joomla-cms#8560] opened 2015-11-28 10:22 UTC
#### Steps to reproduce the issue
Grab one category and move it to reorder

#### Expected result
The category should be placed just below the first visible category above.

#### Actual result
A popup appears informing about unresponsive script jquery.min.rs:4 with three options - Stop, Continue, Debug
When the button Stop is pressed the action is completed.

#### System information (as much as possible)
PHP Built On: 	Linux server.olympic.rs 2.6.32-431.3.1.el6.x86_64 #1 SMP Fri Jan 3 21:39:27 UTC 2014 x86_64
Database Version: 	5.5.46
Database Collation: 	latin1_swedish_ci
PHP Version: 	5.4.45
Web Server: 	Apache
WebServer to PHP Interface: 	apache2handler
Joomla! Version: 	Joomla! 3.4.5 Stable [ Ember ] 22-October-2015 21:30 GMT
Joomla! Platform Version :	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent: 	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0 ![screen shot 2015-11-28 at 04 19 03](https://issues.joomla.org/uploads/1/822fd8b95e58333d3446cae2e9bbf86c.jpg)

#### Additional comments
This occurs when the pagination in the upper right corner was set to 100. When I set it to 10 reordering of categories works fine. But since the Pagination at the bottom doesn't work I must use 100 pagination and even more.

**Comment by RonakParmar** [comment] 2015-11-28 11:54
I am not able to reproduce this issue https://github.com/joomla/joomla-cms/issues/8560

System information:
Joomla! Version: Joomla! 3.4.5 Stable [ Ember ] 22-October-2015 21:30 GMT
Joomla! Platform Version: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
PHP Version: 5.5.30-1+deb.sury.org~precise+1
System Linux desktop 3.5.0-54-generic #81~precise1-Ubuntu SMP Tue Jul 15 04:02:22 UTC 2014 x86_64

**Comment by aantic** [comment] 2015-11-28 12:20
What happened here was that I dragged one category and try to place it just one position above. Pagination was set to 100. When popup appeared I killed the script by pressing the button Stop. The action of reordering categories completed but the pagination stopped working. I solved the problem by clearing browsing history. Now I use Pagination 50 to reorder categories, I tried and it works good.

**Comment by brianteeman** [comment] 2015-12-23 11:09
Reset priority according to https://docs.joomla.org/Priority<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8560">issues.joomla.org/joomla-cms/8560</a>.</sub>

**Comment by aantic** [comment] 2015-12-23 11:11
Please tell me where/how to reset priority?
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
This
email has been sent from a virus-free computer protected by Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Aleksandar Antić
Microsoft Certified Engineer
ANTICFORMA - Web design & development
Kneza Miloša 19/22, Kragujevac
+381 64 138 0054, +381 34 313 688
office@anticforma.com
www.anticforma.com

**Comment by brianteeman** [comment] 2015-12-23 11:16
You dont need to - I have done it

On 23 December 2015 at 11:11, aantic <notifications@github.com> wrote:

> Please tell me where/how to reset priority?
> <
> https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail
> >
> This
> email has been sent from a virus-free computer protected by Avast.
> www.avast.com
> <
> https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail
> >
> <#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
>
> Aleksandar Antić
> Microsoft Certified Engineer
> ANTICFORMA - Web design & development
> Kneza Miloša 19/22, Kragujevac
> +381 64 138 0054, +381 34 313 688
> office@anticforma.com
> www.anticforma.com
>
> On Wed, Dec 23, 2015 at 12:09 PM, Brian Teeman <notifications@github.com>
> wrote:
>
> > Reset priority according to https://docs.joomla.org/Priority
> > ------------------------------
> > This comment was created with the J!Tracker Application
> > <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/8560
> > <https://issues.joomla.org/tracker/joomla-cms/8560>.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/joomla/joomla-cms/issues/8560#issuecomment-166864377
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/8560#issuecomment-166864668>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment] 2016-05-08 14:18
Thank you for taking the time to create this report. Unfortunately as no one has been able to replicate the issue and there have also been several updates to Joomla since this report I am going to have to close it. If you are still having the problem and can provide instructions that someone is able to replicate the issue then this can always be re-opened<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8560">issues.joomla.org/joomla-cms/8560</a>.</sub>

**Closed** 2016-05-08 14:19 UTC
Labels: No Code Attached Yet
