### ISSUE TITLE
recaptcha plugin can be enabled in plugins list even if private/public key are missing

### ISSUE THREAD

**Issue by xillibit** [joomla/joomla-cms#7086] opened 2015-05-31 07:50 UTC
You can always enable the plugin recaptcha in plugins list even if private/public key are missing

**Comment by mbabker** [comment] 2015-05-31 08:04
That's plugins, and extensions in general.  Enabled or not, the code should be checking if it has the data it needs to work or gracefully abort (doing nothing or showing a message if appropriate).

**Comment by xillibit** [comment] 2015-06-02 12:43
I'am alreay checking in my component that public key and private key are not empty before to use captcha plugin

**Comment by Bakual** [comment] 2015-06-02 13:21
I'm not sure what the issue is.
If I enable the plugin without giving the keys, I get a clear error message on the pages where it is supposed to load (eg contact form).

**Comment by xillibit** [comment] 2015-06-02 13:29
In the plugins list if you filter by captcha and you don't have entered private/public keys, you can still enable with the button like on the screenshot without editing the plugin : 

![sdqdsdsds](https://cloud.githubusercontent.com/assets/876395/7936801/1ce5e55a-093c-11e5-91f6-a665a9e6bf9b.png)

**Comment by Bakual** [comment] 2015-06-02 14:21
Yep, as said you can enable it. There is no way to prevent this the way Joomla works.
But that's no real issue. The plugin itself checks during runtime if it can show the captcha and will show an error when it can't.
Since the admin who enables the captcha hopefully also tries the new feature he is going to add, he will see the errror for sure and can take the needed actions.

Or did something break on your site after you enabled the plugin?

**Comment by brianteeman** [comment] 2015-06-02 14:37
The same is true with many other plugins

On 2 June 2015 at 15:21, Thomas Hunziker <notifications@github.com> wrote:

> Yep, as said you can enable it. There is no way to prevent this the way
> Joomla works.
> But that's no real issue. The plugin itself checks during runtime if it
> can show the captcha and will show an error when it can't.
> Since the admin who enables the captcha hopefully also tries the new
> feature he is going to add, he will see the errror for sure and can take
> the needed actions.
>
> Or did something break on your site after you enabled the plugin?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/7086#issuecomment-107971240>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment] 2015-06-18 10:17
Can this be closed as "expected behaviour" ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7086">issues.joomla.org/joomla-cms/7086</a>.</sub>

**Comment by Bakual** [comment] 2015-06-18 10:24
Closed as expected behaviour :smile:

**Closed by Bakual** 2015-06-18 10:24 UTC
Labels: No Code Attached Yet
