### ISSUE TITLE
Searching for special characters not working

### ISSUE THREAD

**Issue by Sporedd** [joomla/joomla-cms#9296] opened 2016-03-03 15:59 UTC
When I search for strings containing a special character Joomla finds no matches.

This is due to an incorrect pass through of the search string

#### Steps to reproduce the issue
Go to:
http://www.deriethorststromenland.nl/index.php?searchword=Di%C3%ABtetiek&searchphrase=all&Itemid=141&option=com_search

I made a var dump for this specific searchphrase. 

#### Expected result
An article containing the word "Diëtetiek"

#### Actual result

No results for this phrase

#### System information (as much as possible)
Webserver	Apache/2.4.12
PHP version: 	5.4.41

More info @
http://www.deriethorststromenland.nl/serverinfo.php

**Comment by nikitadhiman** [comment] 2016-03-08 04:24
Is this an issue for all the special charachter searches?

**Comment by Sporedd** [comment] 2016-03-08 07:12
Yes

mvg,
Jesper

verzonden vanaf mijn telefoon

Op 8 mrt. 2016 5:24 a.m. schreef Nikita Dhiman <notifications@github.com>:

Is this an issue for all the special charachter searches?

**Comment by infograf768** [comment] 2016-03-08 07:48
I can't reproduce here:
![screen shot 2016-03-08 at 08 14 44](https://cloud.githubusercontent.com/assets/869724/13594607/e56536fc-e505-11e5-8438-7acc8ac40332.png)

**Comment by infograf768** [comment] 2016-03-08 07:49
Which browser and OS do you use?

**Comment by Sporedd** [comment] 2016-03-08 09:06
thats interesting.

Im using:
Windows 10 
Dutch
Us keyboard

It goes wrong in all browsers 

I made some var dumps of onContentSearch()
$text:
string(12) "DiÃƒÂ«tetiek"

$phrase:
string(3) "all"

$ordering: string(6) "newest"

$areas: NULL 

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9296">issues.joomla.org/joomla-cms/9296</a>.</sub>

**Comment by infograf768** [comment] 2016-03-09 08:35
I get the same on your site when I search for something else...
http://www.deriethorststromenland.nl/index.php?searchword=cli%C3%ABnten&searchphrase=all&Itemid=141&option=com_search

**Comment by chrisdavenport** [comment] 2016-05-08 10:43
I have not been able to reproduce this issue on a localhost installation.  In the absence of a reproducible set of test instructions involving a fresh Joomla install that can demonstrate the problem, I am closing this issue at this time.  If such can be provided it can always be re-examined.  Thanks for reporting the problem.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9296">issues.joomla.org/joomla-cms/9296</a>.</sub>

**Comment by chrisdavenport** [comment] 2016-05-08 10:43
Set to "closed" on behalf of @chrisdavenport by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9296">issues.joomla.org/joomla-cms/9296</a>

**Closed by chrisdavenport** 2016-05-08 10:43 UTC
Labels: No Code Attached Yet
