### ISSUE TITLE
Language definitions not present in frontend module editing

### ISSUE THREAD

**Issue by stellainformatica** [joomla/joomla-cms#6009] opened 2015-02-07 11:25 UTC
#### Steps to reproduce the issue
Install a new language and set it for frontend. Login in frontend as superadmin and click on the edit button of the module "Latest Article"

#### Expected result
All strings should be translated

#### Actual result
Look at the bottom, the slide titles "Basic" and "Advanced" are not translated and activating the language debug you will see that there is not language definition for them.
The same for other types of modules, in Custom HTML module is not translated also the string "Options"

#### System information (as much as possible)
Joomla 3.4.0 beta2

**Comment by brianteeman** [comment] 2015-02-07 11:32
Are you using a language for 3.4 or is it still a 3.3 language in your test

**Comment by infograf768** [comment] 2015-02-07 11:33
Confirmed.
The issue is that these are hardcoded. Let's find where.

**Comment by stellainformatica** [comment] 2015-02-07 11:48
@brianteeman 
I'm using a 3.4 language, they are not still released, but as italian TT we already have a language package to test
If you need the language attach it here (if it is allowed)

**Comment by brianteeman** [comment] 2015-02-07 12:13
I found the problem and I am writing a patch<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6009">issues.joomla.org/joomla-cms/6009</a>.</sub>

**Comment by zero-24** [comment] 2015-02-07 12:16
The issue is here: https://github.com/joomla/joomla-cms/blob/staging/components/com_config/view/modules/tmpl/default_options.php#L19

**Comment by zero-24** [comment] 2015-02-07 12:17
And this is the correct line: https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_config/view/component/tmpl/default.php#L43

**Comment by zero-24** [comment] 2015-02-07 12:18
Oh sorry @brianteeman i don't see you comment. Ok you can open the PR :smile: Thanks

**Comment by brianteeman** [comment] 2015-02-07 12:18
Please see #6010<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6009">issues.joomla.org/joomla-cms/6009</a>.</sub>

**Comment by brianteeman** [comment] 2015-02-07 12:20
My PR is slightly different to your suggestion - please check

On 7 February 2015 at 12:18, zero-24 <notifications@github.com> wrote:

> Oh sorry @brianteeman <https://github.com/brianteeman> i don't see you
> comment. Ok you can open the PR [image: :smile:] Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6009#issuecomment-73362032>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by zero-24** [comment] 2015-02-07 12:22
yes your patch is the correct one. sorry @brianteeman

**Comment by zero-24** [comment] 2015-02-07 12:24
Thanks @brianteeman for the fix and @stellainformatica for the Tracker. Please have a look into Brians PR that fix the issue for me.

I'm closing here as we have Brians PR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6009">issues.joomla.org/joomla-cms/6009</a>.</sub>

**Comment by brianteeman** [comment] 2015-02-07 12:24
Woohoo my coding is improving

On 7 February 2015 at 12:22, zero-24 <notifications@github.com> wrote:

> yes your patch is the correct one. sorry @brianteeman
> <https://github.com/brianteeman>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6009#issuecomment-73362158>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Closed by zero-24** 2015-02-07 12:24 UTC

**Comment by stellainformatica** [comment] 2015-02-08 18:14
Patch tested, working fine. Thanks Brian.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6009">issues.joomla.org/joomla-cms/6009</a>.</sub>
