### ISSUE TITLE
New feature suggestion

### ISSUE THREAD

**Issue by anabarcellos** [joomla/joomla-cms#10879] opened 2016-06-20 19:33 UTC
When the user is editing an article, it is necessary to use the page scroll bar (not the article one) many times to go back to the editor and then go back to the bottom to continue writing the text. It is annoying since we are focused in the content and we have to stop writing to do it - many times and many times. I realized that my experience with Google Blogger is better because they have a fixed editor. It means that as the text is becoming longer, the editor comes with it and I never need to scroll up and down.  
Not sure if it is possible to fix the editor for Joomla articles but it would make the user's life much easier. :)

**Comment by brianteeman** [comment] 2016-06-20 21:39
Not sure I understand what you mean. Could you perhaps upload an image/mockup<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10879">issues.joomla.org/joomla-cms/10879</a>.</sub>

**Comment by Fedik** [comment] 2016-06-21 05:45
I think @anabarcellos meant auto resize while typing.
There is plugin https://www.tinymce.com/docs/plugins/autoresize/

Made short demo http://codepen.io/anon/pen/mErZoQ

**Comment by dgt41** [comment] 2016-06-21 07:08
I was supposed to code that (tweak the autoresize plugin) after the buttons and the drag and drop but joomla got many options that a user can set for the size of tinymce so I gave up. Best approach will be what @Fedik is proposing above WITH A HARD B/C break that will remove the options for height/width!
You cannot improve UX if you don't go bold. Also this is 2016 and setting up height/width with pixels is not a good option, just saying...

**Comment by brianteeman** [comment] 2016-06-21 08:02
I dont think that can be what @anabarcellos can mean as that makes the scrolling worse <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10879">issues.joomla.org/joomla-cms/10879</a>.</sub>

**Comment by sanek4life** [comment] 2016-06-21 08:13
It should automatically resize the width / height when editing a article!

**Comment by anabarcellos** [comment] 2016-06-21 20:06
Sorry, guys, I was probably sleeping when I wrote that. 

In 3.5, the difficulty that I mentioned has less impact than before, since all buttons are now in the editor instead of below it. But let me try to describe the situation that we still have nowadays. 

We have two scroll bars - one of the article and one of the page. 
I'm writing my very long article and I want to back to the beggining of the text. 
What do I do? I am used that in all pages in internet I go to the right part of the page and scroll up. 
But when I do this, I scroll up the page and not the text. 
So I have to scroll down again. 
And scroll up in the text box. 
When we are writing, we are focused in the content and the rest happens in a automatic way. So I will repeat this scroll up - scroll down - scroll up some times (and hate myself everytime I do it hehe)  

What I wrote in the first post about fixing the menu editor doesn't make sense as a solution in Joomla 3.5. Sorry again.

One possible solution is the text box loading shorter - then we kill the page scroll. 
In this case, the "change editor" button shoud go to the bar above, maybe in the right corner of the editor first row (is it possible?) 
If the user wants the box bigger, he/she can make it bigger with the feature that the editor already has nowadays. 
And is it possible to make the bottom of the menu shorter to give more space for the text?

We would still have the page bar - to support other screen resolutions and a bigger text box if the user wants to increase its size. But, by default, it would be static since the screen is smaller now. 

Is someone from UX team here to analyze if this suggestion makes sense to other users? And if the smaller box couldn't have a negative impact?

**Comment by dgt41** [comment] 2016-06-21 20:24
> In this case, the "change editor" button shoud go to the bar above, maybe in the right corner of the editor first row (is it possible?) 

Very easy to achieve, copy paste a line of code from after the editor tag to before

> And is it possible to make the bottom of the menu shorter to give more space for the text?

Also easy, controlled by the tiny's theme

The idea I was writing about above was to make tinyMCE auto adjust it's height so it will occupy the free space below. As a concept it shouldn't be very hard to achieve (calculate the elements above and below the editor and then put the remaining as the editor's height). I have some starting point (half working or something) code somewhere. If there is an interest I will search for that and give it to anyone that wants to make this happen 😀

**Comment by anabarcellos** [comment] 2016-06-21 20:30
@dgt41 Thanks. :)

Now we need someone to analyze the idea from UX perspective.   

![shorter_text_box](https://cloud.githubusercontent.com/assets/8314551/16245133/cf0fa2f2-37d5-11e6-8106-966638bc4add.png)

**Comment by dgt41** [comment] 2016-06-22 07:31
@anabarcellos The decision for that implementation was set in JAB2015 in Prague. This is an obvious enhancement that, (at least from my point of view) doesn't need any confirmation. I mean is like opening Abobe Photoshop in full screen (default behaviour)...

Check the right hand side, fourth line
![joomla4_jab-notes](https://cloud.githubusercontent.com/assets/3889375/16257994/5707b968-3864-11e6-9f89-80ca52b363c2.jpg)

**Comment by C-Lodder** [comment] 2016-06-24 10:24
I disagree with using an autosize for the editor, **but** instead having a fullscreen button.

Autosize will sometimes become a PITA when you have an extremely long article and keep having to scroll all the way to the top, to use one of the editor toolbar options.

**Comment by PhilETaylor** [comment] 2016-07-12 18:51
The problem is only seen if you have a screen resolution that, when the eidt page loads, the wysiwyg area is larger in height than the screen available. This means you have to scroll the PAGE up and down to see the top and bottom of the wysiwyg area, and then scroll the wysiwyg area to see the content.

For people like me with 27" iMac's this is not a problem

For people like me with a retina macbook this is a problem.

The solution would be to set the editor wysiwyg area HEIGHT to be always contained within the initial viewport, or a size that, when the PAGE is scrolled down, the WHOLE wysiwyg area could be displayed in the viewport of the browser 

This "probably" is a simple 5 line javascript fix.

An "Autosize as I type" just makes the reported issue worse, and is not an option at all (@c-lodder)

**Comment by C-Lodder** [comment] 2016-07-12 19:23
@PhilETaylor - Yup, setting the editor size so that it's within the viewport is an idea. The function triggering this will also have to be executed in `$(window).on('resize')` too. I would strongly suggest having a fullscreen option too as it's nice to have a full page textarea at your disposal without any other UI distractions

**Comment by brianteeman** [comment] 2016-07-12 19:25
There are a lot of new tinyMCE things we are not taking advantage of. Ive
only updated the files without necessarily exposimg the features

**Comment by dgt41** [comment] 2016-07-12 20:35
Can we, pretty please, enable (as default) the paste plugin ?
(that one that will remove any word or other crap from the text users are passing into tinyMCE)
Also I don;t care if it's not B/C

**Comment by brianteeman** [comment] 2016-07-12 20:46
To be honest we need to completely review tinymce. All the plugins. How we
implement them and especially the language files. Also it would be really
cool if we let people use the CDN and the jquery version.

Its a reasonable sized project.

**Comment by dgt41** [comment] 2016-07-12 22:55
@brianteeman I am fine with all of them except the jQuery version, it will be a huge step backwards to go from vanilla js to jquery, especially now that everybody go away from jq...

**Comment by brianteeman** [comment] 2016-07-12 23:01
For front-end use it might be a benefit - i dont know but it should be an option

**Comment by mbabker** [comment] 2016-07-12 23:02
All we have to be able to do is support turning it on for those who want it.  We don't necessarily have to make it the default behavior or even do-able via the UI.  IMO if it's a TinyMCE feature, we should be able to use it in Joomla (whether that be through UI options, custom plugins, or whatever the case may be); it seems wrong to impose arbitrary limitations on third party software.

**Comment by brianteeman** [comment] 2016-07-12 23:02
Exactly my point.

**Comment by brianteeman** [comment] 2016-07-12 23:03
We are so far behind implementing tinymce features and our refusal to use their language files is just a joke

**Comment by dgt41** [comment] 2016-07-12 23:04
@mbabker for the editors will be nice to have a way to install: plugins and themes (code mirror, tinymce, etc all use the same pattern)

**Comment by abenhamdine** [comment] 2017-01-11 14:14
Any new on this ? 
It's really a PITA to write long articles in Jooma currently :(

**Comment by abenhamdine** [comment] 2017-01-11 14:30
For future readers : I just edit the following file as in https://github.com/joomla/joomla-cms/pull/11079/commits/5a5525be016b8381582ce6908142aa959fd5eff5
and it works except you have to use keyboard shorcut (ctrl+shift+f) to toggle fullscren in order to save you edits, since toolbars buttons are hidden by tinyCME.
However it's far better than the current situation :)

**Comment by franz-wohlkoenig** [comment] 2017-01-30 16:02
@anabarcellos in 3.7-staging you can use a Fullscreen-Button > Issue resolved?

**Comment by franz-wohlkoenig** [comment] 2017-04-06 10:51
closed as no reply. @anabarcellos feel free to reopen and discuss further.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10879">issues.joomla.org/tracker/joomla-cms/10879</a>.</sub>

**Closed by franz-wohlkoenig** 2017-04-06 10:51 UTC
Labels: No Code Attached Yet
