### ISSUE TITLE
Popup message leaves blank window behind

### ISSUE THREAD

**Issue by horssenp** [joomla/joomla-cms#27086] opened 2019-11-16 10:41 UTC
### Steps to reproduce the issue
Just any popup message window leaves a grey empty window behind. It seems to me that the script does not close the window after confirmation by the user

### Expected result

The windows should be closed
![joomla4_Alpha 12_popup](https://user-images.githubusercontent.com/17496476/68992028-0746fa80-0866-11ea-9976-b9e81c3097a5.JPG)

**Comment by ChristineWk** [comment] 2019-11-16 11:45
Can't reproduce this. Just checking Code:
#system-message-container joomla-alert.joomla-alert--show {
    display: block;
    opacity: 1;
}
If I would change opacity to 0, then it's grey.

**Comment by ReLater** [comment] 2019-11-16 12:41
The opacity is not the real issue. The alert should get a display: none when closed because an opacity just makes it transparent and all buttons behind the alert are blocked. But some clever guys don't see that...

There are some more issues:
https://github.com/joomla/joomla-cms/issues/23425
https://github.com/joomla/joomla-cms/issues/21803
https://github.com/joomla/joomla-cms/issues/25850

**Comment by brianteeman** [comment] 2019-11-16 13:13
This happens on my system. For me it is because I have the windows accessibility setting for reduced motion enabled. The root cause is the stupid fade-in

**Comment by ChristineWk** [comment] 2019-11-16 13:21
@ReLater OK, I wanted to see it in grey :-) So, I'm not clever enough.
@brianteeman Think, you mean this here: https://github.com/joomla/joomla-cms/issues/25850#issuecomment-525044000<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27086">issues.joomla.org/tracker/joomla-cms/27086</a>.</sub>

**Comment by brianteeman** [comment] 2019-11-16 13:24
Yes that's right

**Comment by horssenp** [comment] 2019-11-16 14:12
I will follow the route as Brian suggests and see what hapens. I am testing 
on Windows 10 environment

Pieter

Op 16 november 2019 14:22:10 schreef ChristineWk <notifications@github.com>:

**Comment by Quy** [comment] 2019-11-16 15:40
Closing as duplicate #25850.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27086">issues.joomla.org/tracker/joomla-cms/27086</a>.</sub>

**Closed as completed by Quy** 2019-11-16 15:40 UTC
Labels: No Code Attached Yet

**Comment by alikon** [comment] 2019-11-16 19:19
can someone close this as a duplicate of #25850

cause this issue it seems not to be present on the issue tracker 
![Screenshot from 2019-11-16 20-18-22](https://user-images.githubusercontent.com/181681/68998115-4e58de00-08ae-11ea-8c08-6f4660186573.png)
