### ISSUE TITLE
JBrowser::isMobile() doesn't recognize android smartphone

### ISSUE THREAD

**Issue by rudisten1** [joomla/joomla-cms#11346] opened 2016-07-29 00:17 UTC
#### Steps to reproduce the issue
echo the JBrowser::isMobile() method output browsing the page with an android smartphone

#### Expected result
true

#### Actual result
false

#### System information (as much as possible)
php 5.6.24
IIS 7
joomla 3.6
MySql 5.7

**Comment by smehrbrodt** [comment] 2016-07-29 06:39
See #6859

**Comment by n9iels** [comment] 2016-07-30 12:44
Calling `JBrowser::isMobile()` that why will give you a PHP error because that method is not made to call static.

**Comment by alexonbalangue** [comment] 2016-09-15 09:22
hi tested until used on with template J3.6, is worked. You should need to "true/false", exemple:
[code]
$browser = JBrowser::getInstance();
if( $browser->isMobile() == true ){
  #show on Mobile because = true
} else {
  #show Desktop
}
[/code]<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11346">issues.joomla.org/joomla-cms/11346</a>.</sub>

**Comment by zero-24** [comment] 2016-09-15 09:39
Closing as `JBrowser::isMobile()` is not valid syntax and @alexonbalangue confirmed it worked with the correct syntax.

If it still not work on your site please open a new issue with your useragent information you can find in the backend under system information. Thanks.

**Closed by zero-24** 2016-09-15 09:39 UTC
Labels: No Code Attached Yet
