### ISSUE TITLE
Disable Mass Mail or Enable Mass Mail?

### ISSUE THREAD

**Issue by BurtNL** [joomla/joomla-cms#10362] opened 2016-05-09 18:25 UTC
I realise this may have been asked or discussed before (I recently joined in 'Tracker'), but the setting 'Disable Mass Mail' seems a bit strange to me. You have to say No to enable it. In all other settings you tick Yes to enable it. It may not be that important, its just something which is a bit odd. To me it is more logical to ask 'Enable Mass Mail' and choose Yes or No accordingly.

![screen shot 2016-05-09 at 13 21 06](https://issues.joomla.org/uploads/1/a40e3ef8ee3e8639ac24eeb0eef76018.jpg)

**Comment by brianteeman** [comment] 2016-05-09 18:51
Yes it is abnormal

**Comment by zero-24** [comment] 2016-05-09 19:00
hmm the problem is that it got released to the user at least with 3.5.0 https://github.com/joomla/joomla-cms/blob/3.5.0/administrator/components/com_config/model/form/application.xml#L456

So we need to hide that option (type=hidden) and replace it with a new option. On the code we need to check if the new option is set. if not we need to use the old option do you agree or i'm thinking bullshit?

**Comment by brianteeman** [comment] 2016-05-09 20:55
Sorry i spoke to soon and i really couldnt comment from my phone

It is correct - You are disabling a default option and we use this in other places

**Comment by brianteeman** [comment] 2016-05-09 20:55
As @zero-24 points out it would have to be a pretty ugly fix to change it now anyway so I am going to close it

**Closed by brianteeman** 2016-05-09 20:55 UTC
Labels: No Code Attached Yet
