### ISSUE TITLE
[4.0] Backend field type color - selection not working

### ISSUE THREAD

**Issue by marcorensch** [joomla/joomla-cms#19187] opened 2017-12-27 17:56 UTC
### Steps to reproduce the issue
Create Field type color and set format to hex rgb or rgba.

```
<field type="color" name"field_name" format="rgba" description="" />
```

### Expected result
color chooser in selected format. with color palette, hue and (if rgba mode) with transparency.

### Actual result
looks like each control is multiple times (at least twice), Color Range selector, Hue Selector and Transparency Selector.
that one in front (and hue selector left) are not working.

### System information (as much as possible)
J4 Alpha 2
PHP 7.1.8
Firefox 57.0.1
Safari 11.0.2

### Additional comments
![screen shot 2017-12-27 at 17 51 03](https://issues.joomla.org/uploads/1/9d7c680ca6241d7baad5671d5047927e.png)

**Comment by dgrammatiko** [comment] 2017-12-27 21:44
@marcorensch this script is under refactoring, so instead of the 2-3 different scripts for the color pickers we will end up with one script, with no dependencies (bye bye jQuery) and also will be a Custom Element. This is the starting point if you want to help: https://codepen.io/dgt41/pen/LjXQoP?editors=0010 it's based on the MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Colors/Color_picker_tool

So appart from making this actually work as intended we need to make it also accessible...

**Comment by ghost** [comment] 2017-12-28 06:51
@dgt41 should i close this Issue?

**Comment by C-Lodder** [comment] 2017-12-28 09:00
Can leave it open as a reference for the time being Franz ;)

**Comment by marcorensch** [comment] 2017-12-28 13:41
Sorry but something like that?

[https://codepen.io/Proximate/pen/EoWmzo](https://codepen.io/Proximate/pen/EoWmzo)

Quick and Dirty (a lot of unused JS) but working so far...

**Comment by C-Lodder** [comment] 2017-12-28 13:49
@marcorensch  - It will be like that but a much more basic implementation. Here was the PR I did for the non custom element version: https://github.com/joomla/joomla-cms/pull/16385

**Comment by brianteeman** [comment] 2018-07-13 21:09
@dgrammatiko any update on this refactoring - its been 6 months

**Comment by dgrammatiko** [comment] 2018-07-14 09:47
@brianteeman the code is here: https://codepen.io/dgrammatiko/pen/zLvXwR

Haven't published anything because there was a discussion about using web components or just custom elements so I needed to know is shadow dom is something we will consider for such components. This has been resolved in our last meeting and once we have the building scripts ready for shadow dom I'll PR this as well

**Comment by jwaisner** [comment] 2020-03-18 02:40
@dgrammatiko has this been worked or can this be closed?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19187">issues.joomla.org/tracker/joomla-cms/19187</a>.</sub>

**Comment by brianteeman** [comment] 2020-03-18 08:46
This is still an open issue

**Comment by dgrammatiko** [comment] 2022-01-26 19:35
@bembelimen theres a pr for the color field https://github.com/joomla/joomla-cms/pull/35639 so this should be closed

**Comment by brianteeman** [comment] 2022-08-23 22:17
Please close as stated above by @dgrammatiko

**Closed as completed** 2022-08-23 22:19 UTC
Labels: No Code Attached Yet, J4 Issue, Information Required
