### ISSUE TITLE
[4.0] Editor field - loss of design when scrolling - more instances

### ISSUE THREAD

**Issue by PhocaCz** [joomla/joomla-cms#35251] opened 2021-08-20 10:36 UTC
### Steps to reproduce the issue

When I use more instances of editor field in my extension:

`<field name="description" type="editor" buttons="true" hide="pagebreak,readmore" class="form-control" label="COM_PHOCADOWNLOAD_FIELD_DESCRIPTION_LABEL" filter="JComponentHelper::filterText" description="COM_PHOCADOWNLOAD_FIELD_DESCRIPTION_DESC" />
<field name="features" type="editor" buttons="true" hide="pagebreak,readmore" class="form-control" label="COM_PHOCADOWNLOAD_FIELD_FEATURES_LABEL" filter="JComponentHelper::filterText" description="COM_PHOCADOWNLOAD_FIELD_FEATURES_DESC" />
<field name="changelog" type="editor" buttons="true" hide="pagebreak,readmore" class="form-control" label="COM_PHOCADOWNLOAD_FIELD_CHANGELOG_LABEL" filter="JComponentHelper::filterText" description="COM_PHOCADOWNLOAD_FIELD_CHANGELOG_DESC" />
<field name="notes" type="editor" buttons="true" hide="pagebreak,readmore" class="form-control" label="COM_PHOCADOWNLOAD_FIELD_NOTES_LABEL" filter="JComponentHelper::filterText" description="COM_PHOCADOWNLOAD_FIELD_NOTES_DESC" />
`

I get problem when scrolling the page. Editor fields lose design when scrolling, see animated GIF:

![issue](https://i.imgur.com/Q4EPv2O.gif)

![issue](https://i.imgur.com/HN2XxAm.png)

### Expected result

Design remains consistent

### Actual result

Design does not remain consistent

### System information (as much as possible)

- Joomla 4 Stable
- Firefox, Chrome on Linux or Windows
- No error in Javascript console
- More editor fields + scrolling (focusing each instance)

Jan

**Comment by salmanansari14** [comment] 2021-08-24 17:19
I want to contribute on this

**Comment by Fedik** [comment] 2023-12-03 15:15
I cannot reproduce it on 4.4 and 5.0.

Do you still have this bug?

**Comment by PhocaCz** [comment] 2023-12-05 23:28
Hi, not more in 4.4 or 5.0

**Comment by alikon** [comment] 2023-12-06 07:21
closing as no more reproducible

**Closed as completed by alikon** 2023-12-06 07:21 UTC
Labels: No Code Attached Yet, bug
