### ISSUE TITLE
J4 atum overflowing input for tags (in article view)

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#35033] opened 2021-08-03 14:28 UTC
### What needs to be fixed
When the translation for the tag Field is longer the Tag Input field (in Article) overlaps
<img width="290" alt="grafik" src="https://user-images.githubusercontent.com/828371/128032898-3e3269cf-68f9-47e5-951e-9cbc079f2737.png">

Maybe the description needs to be below the input, if it gets that long in some languages?

**Comment by simbus82** [comment] 2021-08-23 14:41
Confirmed in the final Joomla 4.0.0

![image](https://user-images.githubusercontent.com/1375730/130465910-30de5980-3bcf-4828-9a48-c34638931a1a.png)

Adding an "overflow: hidden" to the "vertical fieldset" can help and solve the bug, but it is only a workaround.

The problem is on the loading of the page: for some fractions of second the "tag select" expand to a very big width, generating an overflow, probably beacuse it's styled later (JS?)

![image](https://user-images.githubusercontent.com/1375730/130466819-9b2b4e97-28e8-4d1a-8927-f9823956c5d2.png)

No one has read this report of @coolcat-creations :-(

**Comment by Quy** [comment] 2021-08-23 14:58
Duplicate #27907

**Comment by simbus82** [comment] 2021-08-23 15:40
> Duplicate #27907

Uhm, Choices is a dead project...

Ok, but the problem i still here, and the heart of Joomla, the article page, is broken. :-(

Can we put a brutal "overflow: hidden" so the 4.0.1 will be correct?

**Comment by chmst** [comment] 2021-08-23 17:51
Maybe shorten the string to "type or select"

**Comment by brianteeman** [comment] 2021-08-23 18:33
As I have stated before, changing english language strings will only address an issue in english. Other languages may still have the problem

**Comment by simbus82** [comment] 2021-08-23 18:37
> Maybe shorten the string to "type or select"

IMHO it's a css layout problem... the overflow happen with a short string too.

**Comment by chmst** [comment] 2021-08-23 20:32
I found an inline style in the fancy select field.
![grafik](https://user-images.githubusercontent.com/1035262/130515239-0411313f-9b95-49e5-8f33-76870db26da8.png)

But if I remove the inline style in the browser, it is still a litle bit larger that other fields.

**Comment by Quy** [comment] 2022-02-11 00:38
Closing as duplicate

**Closed as completed by Quy** 2022-02-11 00:38 UTC
Labels: No Code Attached Yet
