### ISSUE TITLE
[BUG][J4] SmartSearch unpublished categories  in search results

### ISSUE THREAD

**Issue by angieradtke** [joomla/joomla-cms#39415] opened 2022-12-14 09:37 UTC
Is it possible that unpublished categories are still available  in the search results?
In my case I have lots of content in lots of categories. 
If I unpublish a category, this category is still in  the index.

**Comment by simbus82** [comment] 2022-12-14 14:59
Does this also happen after re-indexing?

**Comment by Quy** [comment] 2023-03-08 00:06
@angieradtke Please advise if this is still an issue. Thanks.

**Comment by Quy** [comment] 2023-03-08 11:30
Closing as not a bug. Thanks for the prompt confirmation!

**Closed as completed by Quy** 2023-03-08 11:30 UTC
Labels: No Code Attached Yet, Information Required, bug
