### ISSUE TITLE
3.4 Use of undefined constant JPATH_COMPONENT_SITE in mod_languages

### ISSUE THREAD

**Issue by Globulopolis** [joomla/joomla-cms#6268] opened 2015-03-03 04:12 UTC
Hi!
After upgrade from J3.3.6 to J3.4 I see in php errors log
> PHP Notice:  Use of undefined constant JPATH_COMPONENT_SITE - assumed 'JPATH_COMPONENT_SITE' in D:\WWW\htdocs\sitename\demo\modules\mod_languages\helper.php on line 67

Maybe something went wrong during upgrade process? Or this is developers mistake?

**Comment by wilsonge** [comment] 2015-03-21 20:47
This constant should be defined in Joomla. Any ideas @Hackwar

**Comment by infograf768** [comment] 2015-03-22 06:38
I can't replicate the issue here.

**Comment by Hackwar** [comment] 2015-03-22 09:05
The constant should indeed be defined in Joomla. I expect this to be a problem with the upgrade and that something went wrong there.

**Comment by Globulopolis** [comment] 2015-03-22 12:21
@Hackwar yes, maybe. But after upgrade to J3.4.1 all seems to be ok.

**Comment by wilsonge** [comment] 2015-03-22 15:52
Ok I have no clue why that would fix the issue. But not going to complain :p will close this for now then. Feel free to reopen if you come across it again!

**Closed by wilsonge** 2015-03-22 15:52 UTC
Labels: No Code Attached Yet

**Comment by Chacapamac** [comment] 2017-01-06 13:59
Still have that — PHP Notice:  Use of undefined constant JPATH_COMPONENT_SITE - assumed 'JPATH_COMPONENT_SITE' in /home/processco2/domains/acy.processco.net/public_html/modules/mod_languages/helper.php on line 67 in a 3.6.5 Joomla site.

Any Ideas?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6268">issues.joomla.org/tracker/joomla-cms/6268</a>.</sub>

**Comment by mbabker** [comment] 2017-01-06 14:13
It will only happen if you are displaying this module on your error page and the error page is triggered before a component is executed.  I've seen it in the https://downloads.joomla.org log files and traced that as the cause.

**Comment by Chacapamac** [comment] 2017-01-06 14:29
Thanks mbabker, I’m using a copy of Protostar template. The site is extremely basic as it’s only a support for the Acymailing components but multilingual — http://acy.processco.net

I made small modification — Should I modified my error page ?

**Comment by mbabker** [comment] 2017-01-06 14:49
You won't need to, doesn't seem to cause any issues.  Just know if you're displaying the language selector module you're going to have that error in your logs.  IMO it's no big deal, unless we're going to start coding modules to be defensive against this stuff.

**Comment by Chacapamac** [comment] 2017-01-06 15:00
Cool — Happy New Year to All
