### ISSUE TITLE
[4.0] The extensions updater has several issues

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#32597] opened 2021-03-06 08:13 UTC
See https://github.com/joomla/joomla-cms/issues/32592#issue-823245734 

Quoting and please forget the hate...

You cannot update the extra_query after an update has been discovered

Files are not copied on update

OPcache problem

**Comment by ssnobben** [comment] 2021-03-07 09:11
Thks Grandpa taking care of the babies.

**Comment by PhilETaylor** [comment] 2021-03-08 19:35
Would it be better to split this up into the individual pieces, so that they can be tackled separately in smaller tasks? Else such a large issue is not going to be tacked by anyone as its too big and complex for a quick code change.

**Comment by PhilETaylor** [comment] 2021-03-28 20:59
> You cannot update the extra_query after an update has been discovered

Is addressed here #32862

**Comment by PhilETaylor** [comment] 2021-03-28 21:52
> OPcache problem

For Joomla 4 is here https://github.com/joomla/joomla-cms/pull/32915 

// cc @nikosdion

**Comment by PhilETaylor** [comment] 2021-04-01 16:05
So the opcache PR's were all rejected without a reason given by @SharkyKZ .. so this issue is still unaddressed, bringing us back to all 3 issues still needing addressing if someone wants to completely waste their time and have the project reject their legitimate (and valid) attempts at resolving these issues.

**Comment by richard67** [comment] 2021-04-01 16:50
@PhilETaylor I hope you know that Sharky doesn't have any right to speak for the JBS or for maintainers. He seems to perform his private war here. So please don't let him influence your motivation for your PR's.

**Comment by PhilETaylor** [comment] 2021-04-01 16:51
I will use official channels to escalate this to OSM. Who I fully expect to do nothing. As they have done for every single CoC issue I have raised. @jeckodevelopment

**Comment by jeckodevelopment** [comment] 2021-04-03 14:34
Hi @PhilETaylor calling @marcodings here as the relevant DC.

**Comment by richard67** [comment] 2021-04-03 14:46
@jeckodevelopment @marcodings More information on what the problem was can be found in this PR: #32915 . You have to expand the comments which are meanwhile hidden on GitHub by default due to the long history. You can also ask me on Glip for details.

**Comment by PhilETaylor** [comment] 2021-04-03 14:48
> due to the long history.

Which is me actually trying to get this right and get it all merged as the opcache issues are valid issues already addressed by all other major cms. And thank you for @richard67 for his timely feedback and time taken to actually understand and test the issues involved. 

As for the Shark attacks, the bites drew blood and left scars... but the shark should never have been in my paddling pool.

**Comment by richard67** [comment] 2021-04-03 14:53
Good we have no piranhas here ;-)

**Comment by brianteeman** [comment] 2021-04-25 10:11
Is there anything left to do here?

**Comment by PhilETaylor** [comment] 2021-04-25 10:13
Yes. The "Files are not copied on update" which still needs doing/testing/debugging/fixing

**Comment by richard67** [comment] 2021-04-25 10:14
... if we will ever be able to reproduce it. As far as I understand, that seems to be not easy.

**Comment by PhilETaylor** [comment] 2021-04-25 13:15
Im kind of hoping it was an opcache thing, but re-reading Nic's explanation Im now not sure. Like you said it seems hard to replicate, so my plan (Before I was sidetracked with he FTP Layer) was to write the code to compare each files checksum after installation and to DIE if the checksum was different (for now just DIE and report the findings, and not actually rewrite the file again like Nic's workaround does) - and publish that as a PR so people could hammer it on some sites, and see if we could then replicate it... 

If we can then replicate it - by using the the PR that DIES if the hash of the files in the package are different to the hash of the file on the hard drive - then at least we have something to look at further. Even better if it only happens sometimes. Even better if its reproducible on demand. 

DIES = Tell the user somehow.

**Comment by richard67** [comment] 2021-04-25 13:17
That sounds like a good plan.

**Closed as completed** 2022-06-28 07:43 UTC
Labels: No Code Attached Yet
