### ISSUE TITLE
Front-end: Image insertion form warning too small

### ISSUE THREAD

**Issue by piergi52** [joomla/joomla-cms#37211] opened 2022-03-06 15:45 UTC
### Steps to reproduce the issue
When you insert an image into an article from the frontend, a very small image insertion screen opens.

**Comment by richard67** [comment] 2022-03-06 15:56
How about providing some information e.g. about which Joomla version and which Template? The corresponding head lines are not there for nothing.

**Comment by brianteeman** [comment] 2022-03-06 15:56
> How about providing some information e.g. about which Joomla version and which Template? The corresponding head lines are not there for nothing.

or even a screenshot

**Comment by piergi52** [comment] 2022-03-08 10:21
You're right sorry, so:
joomla 4.1.0
template:
Et_charity
itl_recycling
et_church
I'm testing it locally and, turning to the developers of this problem, they told me that it depends on the version of joomla 4.
The attached screenshot refers to the itl_recycling template, but for others it has the same effect.
![Screenshot_13](https://user-images.githubusercontent.com/101055458/157217099-7a24ea3e-5291-432b-81ca-b2be09a8eb42.png)

**Comment by drmenzelit** [comment] 2022-03-08 10:25
It seems you are using JCE as editor. Try to change to TinyMCE and look again. It can be a problem from your template and / or JCE not showing the modal window correctly.

**Comment by piergi52** [comment] 2022-03-09 09:57
So: this problem occurs on all three templates (as per attached screenshots) and both with TinyMCE editor and with JCE editor.
Contacted the developers of the templates they told me that it is a problem of joomla 4.
So let's hope they solve this problem.
![Screenshot_12](https://user-images.githubusercontent.com/101055458/157418007-d3fd1d71-62fb-449a-8cab-e35d126f15c8.png)
![Screenshot_13](https://user-images.githubusercontent.com/101055458/157418012-095bae9c-fbcf-4241-ad62-304414d0977e.png)
![Screenshot_14](https://user-images.githubusercontent.com/101055458/157418016-83b52931-218e-482d-8a3a-da671a9bb531.png)

**Comment by brianteeman** [comment] 2022-03-09 10:09
I am 99% certain that the problem is in the templates

Check and make sure that the templates have the following css

```
.jviewport-height70 {
    height: 70vh;
}
```

If they dont then it will look like this
![image](https://user-images.githubusercontent.com/1296369/157420162-bd14f107-362d-4994-b92a-3b6cc70bf850.png)

If they do then it will look like this
![image](https://user-images.githubusercontent.com/1296369/157420111-1dbdd21c-affa-4c86-8c7a-55711db95ec5.png)

**Comment by piergi52** [comment] 2022-03-17 09:03
I found, perhaps, where the problem is, the template was built on the ultimate helix theme there must be an error on (frontend-editor.css).

**Comment by Quy** [comment] 2022-03-17 22:09
Closing as not a core issue. Thank you for following up.

**Closed as completed by Quy** 2022-03-17 22:09 UTC
Labels: No Code Attached Yet, Information Required
