### ISSUE TITLE
[com_fields] Default Value of User is the Userid UX issue

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#14362] opened 2017-03-05 14:26 UTC
The Default field should be also a userfield to select the default user.
Or at least the tooltip should say "type in the Userid" with an integer filter.

![image](https://cloud.githubusercontent.com/assets/828371/23588063/f3c95186-01b7-11e7-81d1-553b28c1859f.png)

**Comment by laoneo** [comment] 2017-03-07 13:03
The problem is with the user field, you can't select multiple users. So it would not be possible to select multiple users as default. In pr #14404 I'v changed the tooltip text and the label to something more meaningful.

**Comment by laoneo** [comment] 2017-03-08 15:42
Guess we can close this one then as we have a pr.

**Closed** 2017-03-08 15:47 UTC
Labels: No Code Attached Yet
