### ISSUE TITLE
3.4 : Article sort is broken

### ISSUE THREAD

**Issue by fsask** [joomla/joomla-cms#6182] opened 2015-02-25 16:58 UTC
#### Steps to reproduce the issue
Upgraded to 3.4 from 3.3.6 After this process completes, article sort does not work: clicking on the "Ordering - Click to sort by this column" set of arrows (In the Article Manager - Articles panel) does not do anything. It shows up as a link, but does not work. I reverted to the previous Joomla! version (3.3.6) and the functionality of the article sort returned.

#### Expected result

Articles could be sorted in Article Manager - Articles

#### Actual result

No sort funciton available

#### System information (as much as possible)

Joomla 3.3.6, Windows 7, Protostar template.

#### Additional comments

I also looked around to make sure that the Menu Item was set to allow ordering by Article Manager order, which of course, it was.

**Comment by mbabker** [comment] 2015-02-25 17:01
I can't reproduce this on a 3.4 site.  Clicking the column heading sorts the admin manager by the ordering column on this site and I'm able to successfully reorder items.

Can you provide any more details?  Any JavaScript errors in your browser perhaps?

**Comment by dgt41** [comment] 2015-02-25 17:08
@fsask Can you clear your browser’s cache and try again?

**Comment by PhilETaylor** [comment] 2015-02-25 17:46
I can replicate this, and after a browser cache flush it was all ok.

**Comment by fsask** [comment] 2015-02-25 18:02
I will try later to see if this fixes the issue. One of the drawbacks of the "automatic" update feature now built into Joomla! (an excellent thing in and of itself...) possibly is that when the process completes, I believe there is a button to clear the system cache - but nothing to suggest that a browser cache is also necessary. It's maybe a bit counter-intuitive, as the browser view is generated from inside Joomla!.

**Comment by brianteeman** [comment] 2015-03-23 18:15
After a month without reply i am closing this. It can always be reopened if required<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6182">issues.joomla.org/joomla-cms/6182</a>.</sub>

**Closed** 2015-03-23 18:15 UTC
Labels: No Code Attached Yet
