### ISSUE TITLE
[4.0] Backend: Joomla-Logo not linked with system or help menu activated

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#26685] opened 2019-10-19 11:49 UTC
### Steps to reproduce the error
In Backend go to the system menu or the help menu  and hover over the joomla logo.

![pbf02](https://user-images.githubusercontent.com/9270310/67144479-193d7980-f277-11e9-84e6-814d7189053a.png)

**Comment by brianteeman** [comment] 2019-10-19 12:14
Read the code. This is by design and only on the home dashboard where it makes no sense

**Comment by brianteeman** [comment] 2019-10-19 18:54
This can be closed as expected and intended behaviour

**Comment by HLeithner** [comment] 2019-10-19 19:45
@brianteeman could you please be a bit more friendly and this issue is valid because it's on every dashboard as the reporter mentioned.

It makes no sense that I'm unable to go to the home dashboard from the system dashboard.

**Comment by brianteeman** [comment] 2019-10-19 21:18
This is the code you will need to change

https://github.com/joomla/joomla-cms/blob/afb0634d2158bb7b7d1f64cfe22441d5b933a483/administrator/templates/atum/index.php#L31

https://github.com/joomla/joomla-cms/blob/afb0634d2158bb7b7d1f64cfe22441d5b933a483/administrator/templates/atum/index.php#L110-L116

**Comment by waader** [comment] 2019-10-23 19:00
As this behaviour serves a higher purpose (a11y) this could be closed.

**Closed as completed** 2019-10-28 12:37 UTC
Labels: No Code Attached Yet
