### ISSUE TITLE
com_content custom vote plugin

### ISSUE THREAD

**Issue by sergeytolkachyov** [joomla/joomla-cms#37367] opened 2022-03-25 05:31 UTC
### Problem identified
Joomla 4.1.
I want to create custom article vote plugin. There is no problem with plugin itself, but I found an interesting thing:
If plugin **Content - Vote** is disabled there is no "Voting" setting in **Article manager setting - Article**. 

In **plugins/content/vote/vote.php** we see a checking $params (line 116):
`if (empty($params) || !$params->get('show_vote', null))  { return '';  }`

The fields with types **Voteradio** and **Votelist** has it's own checking: 
[File administrator/components/com_content/src/Field/VotelistField.php (line 47)](https://github.com/joomla/joomla-cms/blob/f9cb42d60e60d10b675ed735dcfe1aa10cdd360b/administrator/components/com_content/src/Field/VotelistField.php#L48)
[File administrator/components/com_content/src/Field/VoteradioField.php (line 47)](https://github.com/joomla/joomla-cms/blob/f9cb42d60e60d10b675ed735dcfe1aa10cdd360b/administrator/components/com_content/src/Field/VoteradioField.php#L48)

`if (!PluginHelper::isEnabled('content', 'vote'))
		{
			return false;
		}`

### The problem...
1. If I want to use custom vote plugin - I'll disable a standart plugin. 
2. Then if I'll disable a standart plugin - I'll loose an oportunity to enable voting in Article manager settings.
3. Then I can't to show my custom plugin's output because I'll make the same checking
 `if (empty($params) || !$params->get('show_vote', null))  { return '';  }`

### Proposed solution
The decision is to remove checking `if (!PluginHelper::isEnabled('content', 'vote'))` from fields files:
[File administrator/components/com_content/src/Field/VotelistField.php (line 47)](https://github.com/joomla/joomla-cms/blob/f9cb42d60e60d10b675ed735dcfe1aa10cdd360b/administrator/components/com_content/src/Field/VotelistField.php#L48)
[File administrator/components/com_content/src/Field/VoteradioField.php (line 47)](https://github.com/joomla/joomla-cms/blob/f9cb42d60e60d10b675ed735dcfe1aa10cdd360b/administrator/components/com_content/src/Field/VoteradioField.php#L48)

### Open questions
So If the community agrees I can make a PR.

**Comment by brianteeman** [comment] 2022-03-25 07:23
The problem is that for those people not using your plugin they will no longer be able to disable votes

**Comment by sergeytolkachyov** [comment] 2022-03-25 07:34
[https://github.com/joomla/joomla-cms/blob/f9cb42d60e60d10b675ed735dcfe1aa10cdd360b/plugins/content/vote/vote.php#L116](https://github.com/joomla/joomla-cms/blob/f9cb42d60e60d10b675ed735dcfe1aa10cdd360b/plugins/content/vote/vote.php#L116)
True, I didn't think about it. 
`$params->get('show_vote', null)` 
here
`if (empty($params) || !$params->get('show_vote', null)) {  return ''; }`
could changed to ` $params->get('show_vote', 0) != 0`
Result
`if (empty($params) || $params->get('show_vote', 0) != 0) {  return ''; }`

It seems to me it makes more sense to explicitly set the parameter than not to have it at all.

**Comment by chmst** [comment] 2022-04-03 16:58
@sergeytolkachyov is this an issue for joomla core? If not, could you please close it?

**Closed as completed** 2022-04-04 10:02 UTC
Labels: No Code Attached Yet, Information Required
