### ISSUE TITLE
Umlauts in menus are not rewritten 

### ISSUE THREAD

**Issue by hytsch** [joomla/joomla-cms#42734] opened 2024-01-30 17:43 UTC
### Steps to reproduce the problem
Create a menu or menu item with an umlaut.

### Expected result
In the alias, ü becomes ue, ä becomes ae, ö becomes oe and special spaces become - or are eliminated 

### Actual result
umlauts are adopted

### System information (as far as possible)
j 5.02

### Additional comments

**Comment by brianteeman** [comment] 2024-01-30 18:02
This is the expected behaviour UNLESS you have enabled "Unicode Aliases" in the Global Configuration

**Comment by richard67** [comment] 2024-01-30 18:47
> This is the expected behaviour UNLESS you have enabled "Unicode Aliases" in the Global Configuration

@brianteeman Have you mixed up expected and actual result, or is it me getting something wrong? I would the Umlauts to be used in the alias then Unicode Aliases is enabled, which is the actual result, and be transliterated with „ae“ and so on when Unicode Aliases is disabled.

@hytsch Could you report back the value of „Unicode Aliases“ in Global Configuration Site Settings in the SEO section?

**Comment by alikon** [comment] 2024-02-05 18:30
@hytsch can you check this one #42741

**Comment by brianteeman** [comment] 2024-07-15 10:29
Looks like this was resolved with #42741 and can be closed

**Closed as completed** 2024-07-16 04:15 UTC
Labels: No Code Attached Yet, Information Required, bug
