### ISSUE TITLE
custom fields with showon and required - No save possible when hidden

### ISSUE THREAD

**Issue by FilMar61** [joomla/joomla-cms#40547] opened 2023-05-05 16:37 UTC
### Steps to reproduce the issue
Create at least 2 custom fields for an article (same category and fieldgroup), one of type list or radiobutton with some values, the other of wathever type but set them as required and showon on a value of the list field.

Create a new article and choose te value for the list-field where the other (required) field is not shown.
Save the article.

### Expected result
For me, I expected the article would be created and saved.

### Actual result
I get an error:
The form cannot be submitted as it's missing required data.
Please correct the marked fields and try again.

But there are no marked fields to correct as they are hidden...

### System information (as much as possible)
Joomla 4.3.1 - php 8.2

### Additional comments
OK, the field is required but, for me, if it is hidden by the showon, it should be hidden for the validation also...

**Comment by obuisard** [comment] 2023-07-06 16:22
Duplicate of https://issues.joomla.org/tracker/joomla-cms/39257 I believe.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40547">issues.joomla.org/tracker/joomla-cms/40547</a>.</sub>

**Comment by alikon** [comment] 2023-07-06 16:55
@FilMar61 please continue the discussion on #39257

thanks for reporting

**Closed as completed by alikon** 2023-07-06 16:55 UTC
Labels: No Code Attached Yet
