### ISSUE TITLE
Bug with article image upload

### ISSUE THREAD

**Issue by ZviadPochkhua** [joomla/joomla-cms#9649] opened 2016-03-29 12:01 UTC
#### Steps to reproduce the issue
1) While uploading images in admin>articles>images and links (see screenshot), images are being uploaded to wrong directories. 
![screen shot 2016-03-29 at 07 00 54](https://issues.joomla.org/uploads/1/48f0eb95b75f6a50c3bc7642ea3e3f71.png)
#### Expected result
For example, you upload to "World" folder (Images>stories>world), Image should be visible in World folder after you finish upload. 
B) it must be arranged by newest first. So you can easily find last upload and insert it. 
C) you should be able search images, since there is a search icon 
D) in ideal situation, when you upload image through Images (t3) and stories, it should include image into article itself. There must be no additional browsing and insert required. 

#### Actual result
a) In fact images are uploaded to different folder - "IMAGES". Sometime to upper folder "STORIES". This happens in 5 cases of 10. 

B) Images are not arranged by date uploaded or alphabetically. 

c) You can not search image by file name, that makes impossible to find it in 100000 images. 

Can you please suggest fix to this issue and also advise any simple image upload manager. 

#### System information (as much as possible)
Joomla 3X (latest update) 

#### Additional comments
Is there any way to configure image upload rule? or how the order of arranging photos?

**Comment by MATsxm** [comment] 2016-03-29 12:10
Sure thing it's not `Critical` anyway.
Please see: https://docs.joomla.org/Bug_and_Issue_Tracker_Priority<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9649">issues.joomla.org/joomla-cms/9649</a>.</sub>

**Comment by Kubik-Rubik** [comment] 2016-03-29 12:15
I've set priority to "Medium", see link that @MATsxm has posted for explanation. Thank you!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9649">issues.joomla.org/joomla-cms/9649</a>.</sub>

**Comment by ZviadPochkhua** [comment] 2016-03-29 14:07
OK. but any idea related to the issue?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9649">issues.joomla.org/joomla-cms/9649</a>.</sub>

**Comment by infograf768** [comment] 2016-03-30 08:15
I can't reproduce your issue here using staging (3.5.0-rc2)
The image is uploaded to the directory chosen, then one can Insert normally.
The order of the images (thumbnails) is alphabetical from left to right.

Indeed we do not have a Search function in media manager.

**Comment by mikeveeckmans** [comment] 2016-03-30 22:22
I can't reproduce the issue either... <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9649">issues.joomla.org/joomla-cms/9649</a>.</sub>

**Comment by infograf768** [comment] 2016-03-31 07:15
I guess this can be closed as it is specific to the user's site. Maybe an incomplete update or a conflict with one extension.

**Comment by ZviadPochkhua** [comment] 2016-03-31 10:02
This is the link to video which reproduces the bug. 
https://www.wetransfer.com/downloads/0f072fdbbecf000169d402901727e06e20160331094628/77e1c4d8517cafeb7ab326343e50c4c720160331094628/7e7c70

I suppose that it might be issue with this joomla only. Thought can you please assist me to fix this issue. 

P.S> 

and second: May I raise an issue related to how images are uploaded in articles. 
Issue:
To upload image, you need to choose file from computer and upload it. 

Expected result: 
Image must be inserted in article just after upload.  Automatically. 

Actual result: 
You need first upload image, then find it and insert to article. 

There is no reason why files to be uploaded into Articles  >( Images and Links) must be first uploaded, then found and then inserted. This is the useless step with no logical need.

**Comment by ssnobben** [comment] 2016-04-05 06:49
"a) In fact images are uploaded to different folder - "IMAGES". Sometime to upper folder "STORIES". This happens in 5 cases of 10. "

In the video I see your uploaded file in the right media manger folder. Did you see that? You have two files with the same file name one in stories, world and one in top folder as you show in the video.

But I agree that this should be automatically loaded into the article there to save time..

**Comment by ZviadPochkhua** [comment] 2016-04-05 09:16
The second file was uploaded later. As I said this happens in 5 from 10 situation.  As I understand this is due to late load of the folder indexes.  Like when you are in the folder X actually, field above the table shows you are in root folder.

**Comment by ZviadPochkhua** [comment] 2016-04-05 09:18
There is the little code change needed to simplify automatic insertion of the image url in IMAGE URL field.  Hope joomla will include this in next update.

**Comment by brianteeman** [comment] 2016-04-05 09:21
The proposal in #9695 would make it easier - it just needs the code

Anything else will have to wait for 3.6 which is scheduled to have a new media manager component

**Closed by brianteeman** 2016-04-05 09:21 UTC
Labels: No Code Attached Yet

**Comment by JimDee** [comment] 2018-05-30 01:06
@ZviadPochkhua     Did you ever solve this? I'm asking because I have a site w/ the exact same issue. When you go to an article --> images / links --> select image --> navigate to a folder --> upload   .... the image does NOT end up where you were. Instead, it goes one or two folders down.

This issue was closed a long time ago because it was viewed as specific to your install. But, clearly, it's something more than that.

In mine, I have a folder structure like  / images / stories / 2018 / may
... and when I go to "may" and upload something, it ends up in "stories".  Very odd.

**Comment by Quy** [comment] 2018-05-30 02:25
Fixed in #20586 for the upcoming release v3.8.9.

**Comment by JimDee** [comment] 2018-05-30 02:35
Aha! Thanks. :-)

**Comment by Cocominikki** [comment] 2023-01-31 10:28
I can download dance video via tiktok but how can I download it without watermark?  I prefer install <a href="https://www.shareitmod.com?ref=wl">shareit mod</a> app for my Android rather than other app that enables users to download tiktok video without watermark! You can <a href="https://www.shareitmod.com?ref=wl">try it </a> too![Your text to link here...](http://www.shareitmod.com "click here!")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9649">issues.joomla.org/tracker/joomla-cms/9649</a>.</sub>
