### ISSUE TITLE
[4.0] Save and close not possible in Template Style (atum)

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#28850] opened 2020-04-28 07:12 UTC
### Steps to reproduce the issue
- Reset all Values in the Atum template (delete them) 
Click on Save and Close
An Error appears

- If you click just on save it works

![grafik](https://user-images.githubusercontent.com/828371/80457877-4b1f4f00-8930-11ea-8f1e-282f1596a7d9.png)

**Comment by brianteeman** [comment] 2020-04-28 08:12
Confirmed

**Comment by Quy** [comment] 2020-04-28 15:08
Related #26639

**Comment by Quy** [comment] 2020-05-01 16:19
Please test PR #28897

**Comment by SharkyKZ** [comment] 2020-05-01 19:56
Re-opening as #28897 won't solve this.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28850">issues.joomla.org/tracker/joomla-cms/28850</a>.</sub>

**Comment by SharkyKZ** [comment] 2020-05-01 19:59
The issue is specific to Color field. Its JS adds `pattern` attribute which forces validation:

https://github.com/joomla/joomla-cms/blob/8c1f5be8354ba26f5eb955461227eee239ec899e/build/media_source/system/js/fields/joomla-field-color-slider.es6.js#L195

I don't know if this is intentional or not.

**Comment by brianteeman** [comment] 2020-06-20 07:47
I can not replicate this any more. Perhaps a change has been made elsewhere

**Comment by Quy** [comment] 2020-09-05 17:16
Closing as no longer reproducible.

**Closed as completed by Quy** 2020-09-05 17:16 UTC
Labels: No Code Attached Yet
