### ISSUE TITLE
Fatal error: Call to undefined method JFormFieldRadio::getRenderer() in /home/xxx/public_html/libraries/joomla/form/fields/radio.php on line 53

### ISSUE THREAD

**Issue by vsshriakant** [joomla/joomla-cms#9663] opened 2016-03-30 05:22 UTC
#### Steps to reproduce the issue

Click Global Configuration...the above error appears
Click New Article the above error appears

Even tried to manual update to J3.5 the error stays

#### Expected result
Radio buttons are shown

#### Actual result
above error

**Comment by brianteeman** [comment] 2016-03-30 09:16
Sounds like something is not right with your site as this cannot be replicated. It may be a faulty update but more likely it is being caused by an extension that you have installed on the site - probably a content or system plugin<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9663">issues.joomla.org/joomla-cms/9663</a>.</sub>

**Comment by mbabker** [comment] 2016-03-30 13:34
From comments on the forum, seems some folks have had issues with redCORE and 3.5 because of how they've extended/overridden the JForm API.  `getRenderer()` is a new method in 3.5 so as long as your update was completed successfully then with only the core there should be no issues.

Closing this as not a core issue.  If you need further support please use http://forum.joomla.org/

**Closed by mbabker** 2016-03-30 13:34 UTC
Labels: No Code Attached Yet

**Comment by Boris-1** [comment] 2017-01-15 02:06
I've hit the same bug/issue when trying to use redMigrator on Joomla 3.6.5. Unfortunately, there is no way to install an older Joomla and redMigrator was the only free migration tool I could find for Joomla 1.5 -> 3.x (doing this for a non-profit). Could you please clarify more on your description of the issue and any potential solution or workaround?

Thanks a lot!

**Comment by Slobodoslav** [comment] 2017-03-30 17:57
Tak a look at:
https://forum.joomla.org/viewtopic.php?t=913828
And than install:
https://github.com/redCOMPONENT-COM/redCORE/releases
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9663">issues.joomla.org/tracker/joomla-cms/9663</a>.</sub>
