### ISSUE TITLE
[5.2] Breadcrumbs in media: invisible current item

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#44134] opened 2024-09-24 17:52 UTC
### Steps to reproduce the issue
Got to media and open a folder. 
The Breadcrumbs on top does not show the active item. 
The colour is invisible. This is not a big issue, users don't miss the information. Just not quite ok, as screenreaders read the text and a11y tools say that there is a contrast error. 

### Expected result
Either make the active item visible for all or remove the item. 

### Actual result
![grafik](https://github.com/user-attachments/assets/31addea7-b727-4ccc-a407-44e06abe7b98)

![grafik](https://github.com/user-attachments/assets/0f8100da-74b2-4a3f-8382-6e5a37efa7df)

**Comment by brianteeman** [comment] 2024-09-24 21:42
@chmst You have added the tag JS Media Manager but the problem is only in j5

In J4 you can see the last item in the breadcrumbs
![image](https://github.com/user-attachments/assets/7097fecf-c811-429e-8ce3-965928d34437)

The break possibly comes from the dark mode changes in #42986

As you can see it displays correctly in dark mode
![image](https://github.com/user-attachments/assets/1958d2df-d2b0-492e-9bd2-3fb093fdab09)

**Comment by Quy** [comment] 2024-10-08 16:57
Closing as having a pull request. Please test #44212. Thanks in advance.

**Closed as completed by Quy** 2024-10-08 16:57 UTC
Labels: Backend Template, bug
