### ISSUE TITLE
Joomla 3.9.9 upgrade

### ISSUE THREAD

**Issue by sarsami** [joomla/joomla-cms#25485] opened 2019-07-09 21:02 UTC
### Steps to reproduce the issue
The system detects a new version of Joomla (3.9.9)
Upgrade to Joomla 3.9.9 (no issues)
Upon finish, it states that Joomla 3.9.8!!! has been successfully updated!!!
If I try to check for new update now states that I already have the latest version of Joomla 3.9.8???

### Expected result

Expected to have Joomla 3.9.9

### Actual result

Despite the update, the system states that it has Joomla 3.9.8

### System information (as much as possible)
Linux 2.6.32-954.3.5.lve1.4.64.el6.x86_64 #1 SMP Wed May 15 12:53:53 EDT 2019 x86_64
Database Type 	mysql
Database Version 	10.1.40-MariaDB
Database Collation 	utf8_general_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	7.3.6
Web Server 	LiteSpeed
WebServer to PHP Interface 	litespeed
Joomla! Version 	Joomla! 3.9.8 Stable [ Amani ] 11-June-2019 20:00 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

**Comment by HLeithner** [comment] 2019-07-09 21:05
Due to a bug in 3.9.9 we removed 3.9.9 from the update server. You can find more information in the PR #25482

**Comment by jeckodevelopment** [comment] 2019-07-09 21:05
Hello,
Joomla 3.9.9 has been removed from the update server.
Update to 3.9.9 is not recommended due to a bug.
Joomla 3.9.10 will be released as soon as possible.
We recommend to keep Joomla 3.9.8 until 3.9.10 will be available.

**Comment by sarsami** [comment] 2019-07-09 21:08
Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25485">issues.joomla.org/tracker/joomla-cms/25485</a>.</sub>

**Comment by lsmcswain** [comment] 2019-07-09 21:32
Will 3.9.10 fix Joomla sites that have already been upgraded to 3.9.9?? I have 70 sites already updated.

**Comment by HLeithner** [comment] 2019-07-09 21:36
Sadly no we can't recover the template style <> content language mapping. if you don't have a multi language site there is no problem only if you use different styles for different languages.

**Comment by richard67** [comment] 2019-07-10 16:35
@sarsami Now as 3.9.10 is out which fixes this problem, this issue can be closed.

@lsmcswain You can update to 3.9.10 now. The only thing which needs to be fixed manually after having updated to 3.9.10 is if you have made some template style(s) be the default for a particular language. This info got lost by the update to 3.9.9, and due to the error with 3.9.9 it was not possible to fix that manually, but after update to 3.9.10 it will work. Because one can have only as many templates being default for some language as there are languages, and because I don't think your 70 sites are all multilingual and have 20 or 30 languages each site, the effort for manual fixing is not so big.

Beside that, there are no errors to be fixed manually, so if your 70 updated sites are not multilingual or don't have template styles being defautl for any language, there is nothing to be fixed manually.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25485">issues.joomla.org/tracker/joomla-cms/25485</a>.</sub>

**Comment by lsmcswain** [comment] 2019-07-10 16:39
That is correct...and I have already upgraded all my sites to 3.9.10 and
the issue is resolved. Thanks!

Regards,

*Sidney McSwain*
m. (678) 778-0863
*Web Developer, MCSE, MCP, A+*


<https://www.linkedin.com/in/sidneymcswain>

**Comment by richard67** [comment] 2019-07-10 16:40
@lsmcswain Am happy to hear that at the end all went well for you.

**Closed as completed** 2019-07-10 16:58 UTC
Labels: No Code Attached Yet
