### ISSUE TITLE
Encoding Error in the Multilingual Status [module] link in the Burger (...) Menu

### ISSUE THREAD

**Issue by imanickam** [joomla/joomla-cms#34732] opened 2021-07-08 09:16 UTC
### Steps to reproduce the issue

1. Create a multilingual site with the languages English, French, Tamil, and Chinese-Simplified
2. Make English as the Default back-end Administrator language
3. Your would notice a link "Multilingual Status" on the Status Bar on the top
4. Now make the window smaller until the Burger Menu (...) appears
5. Click on the ... icon and observe how the link "Multilingual Status" appears
6. Repeat the steps 2 to 5 and observe how the link text appears before and after making the window smaller

It is expected the link name "Multilingual Status" (with appropriate translation from the language strings) appears same both in the regular status bar and in the Burger (...) Menu.

Notice that the link name appears correctly in the status bar.  Whereas in some languages such as Chinese and Tamil the link name does not appear correctly in the Burger (...) Menu.

### Expected result

Notice that link text appears correctly in English and French when the Burger menu appears.  The link name also appears correctly in Chinese and Tamil languages when it is shown in the Status bar.

![Burger_Menu_ML_Status_Module_Title_Encoding_Correct_English](https://user-images.githubusercontent.com/4947580/124894985-c3d06f80-dff9-11eb-948b-bb115ca25fee.jpg)

![Burger_Menu_ML_Status_Module_Title_Encoding_Correct_French](https://user-images.githubusercontent.com/4947580/124895041-cdf26e00-dff9-11eb-911a-e70f532613f6.jpg)

![ML_Status_Module_Title_Encoding_Correct_Chinese](https://user-images.githubusercontent.com/4947580/124895259-042fed80-dffa-11eb-9c20-6b99fd541677.jpg)

![ML_Status_Module_Title_Encoding_Correct_Tamil](https://user-images.githubusercontent.com/4947580/124895285-098d3800-dffa-11eb-910a-3770c8f3dae3.jpg)

### Actual result

Notice that the link text is garbled.

![Burger_Menu_ML_Status_Module_Title_Encoding_Wrong_Encoding_Chinese](https://user-images.githubusercontent.com/4947580/124895390-21fd5280-dffa-11eb-953a-36f5a2ff8855.jpg)

![Burger_Menu_ML_Status_Module_Title_Encoding_Wrong_Encoding_Tamil](https://user-images.githubusercontent.com/4947580/124895412-27f33380-dffa-11eb-8af3-b124d86fe115.jpg)

### System information (as much as possible)

Joomla Version: 4RC3 
O/s: Windows 10
PHP Version: 7.4.20
MySQL Version: 5.7.34
Apache Version: 2.4.46 

### Additional comments

Most likely this happens only in the languages that have non-Latin Characters.  As one would notice, it shows correctly for the languages English and French.

**Comment by brianteeman** [comment] 2021-07-08 12:40
I can't explain why it happens but it is caused by `data-bs-toggle="modal"`

**Comment by Richell** [comment] 2022-03-02 13:12
I have same problem in japanese(ja-JP).
![screen shot 2022-03-02 at 13 11 13](https://issues.joomla.org/uploads/1/35f22f206cec89dce325b805dcd63605.png)![screen shot 2022-03-02 at 13 11 14](https://issues.joomla.org/uploads/1/71f12b70830c9c6e6bee7fdf48289026.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34732">issues.joomla.org/tracker/joomla-cms/34732</a>.</sub>

**Comment by Hackwar** [comment] 2022-11-05 22:08
I found the issue and solved it in #39155. Please test that PR and mark it accordingly, so that this can be merged into 4.3 as soon as possible. Since we have a PR, I'm closing this for now.

**Closed as completed by Hackwar** 2022-11-05 22:08 UTC
Labels: No Code Attached Yet
