### ISSUE TITLE
[3.8.4 regression] Invalid pagination links in archived search

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#19409] opened 2018-01-19 18:05 UTC
### Steps to reproduce the issue
Install staging.
Archive about 10 articles.
On the frontend, click `Archived Articles`.
In the Filter form, leave `Month` and `Year` and select `5` and click `Filter`.
Click a link in the pagination.

### Expected result
display paginated pages

### Actual result
`404` page.

Here is the URL:
`http://localhost/joomla-cms-staging/index.php?month=0&year=0&start=5`

### System information (as much as possible)
nightly staging

**Comment by alikon** [comment] 2018-01-19 18:15
unable to reproduce with  #19397 + #19391 with legacy url

**Comment by Quy** [comment] 2018-01-19 19:47
I can reproduce with both PRs. Please paste one of the pagination URLs.

**Comment by Quy** [comment] 2018-01-19 20:12
It is fine in v3.8.3, but not in v3.8.4. `view` and `Itemid` are different even though it is the same demo without your PR.

v3.8.3
`/index.php?option=com_content&view=archive&Itemid=256&month=0&year=0&limitstart=5`

v3.8.4 (it is defaulting to the Home ID)
`/index.php?option=com_content&view=featured&Itemid=435&month=0&year=0&limitstart=5`

**Comment by csthomas** [comment] 2018-01-19 20:59
I will look at this soon

**Comment by csthomas** [comment] 2018-01-20 14:41
Please test https://github.com/joomla/joomla-cms/pull/19415

**Comment by ghost** [comment] 2018-01-20 15:12
closed as having Pull Request #19415

**Closed as completed** 2018-01-20 15:11 UTC
Labels: No Code Attached Yet
