### ISSUE TITLE
mutated vowels (Ös, Äs and Üs) are making trouble when you create a new menu

### ISSUE THREAD

**Issue by Worti2** [joomla/joomla-cms#36369] opened 2021-12-21 18:20 UTC
Hi everybody,

I think, that I have found a bug.

### Steps to reproduce the issue
1. Set in your operation system of your computer the keyboard to German.
2. Set in your mainconfiguration of Joomla! 4 the SEO-setting "Unicode Aliases" to Yes.
3. Create a new menu with an ö, ä or ü in the "Unique Name" field.
4. You do not have to create a new navigation module with the new menu.
5. Create some new menuitems in the new menu
6. Then have a look at the menu items in the backend.

### Expected result
The list of all menu items of the new menu should appear and it should be able to change the order.

### Actual result
7. An error message appears "The Menu type does not exist." and you will see all menu items of all menus.
8. If you select the main menue everything is fine.
9. But if you select the new menue, all menueitems and the message will appear. And you are not able to change the order.

### System information (as much as possible)
10. system information is attached

### Additional comments
In Joomla!3 everything is fine with this setting.

Markus
[systeminfo-2021-12-21T19 12 53+01 00.txt](https://github.com/joomla/joomla-cms/files/7757238/systeminfo-2021-12-21T19.12.53%2B01.00.txt)

**Comment by Fedik** [comment] 2021-12-21 18:43
I not sure if I understood your problem correctly,
Do you mean this message?

![image](https://user-images.githubusercontent.com/1568198/146981748-795cc06e-7bc1-4e51-823a-719243fec938.png)

If yes, then this is correct behavior. The ordering will be available only after save the menu, the same is for joomla 3.

**Comment by Worti2** [comment] 2021-12-21 19:04
Hey Fedik,

No, I do not mean this. This is no error message, this is an informational message.

Please follow my instructions.

Markus

**Comment by brianteeman** [comment] 2021-12-21 19:04
I can confirm the problem

![image](https://user-images.githubusercontent.com/1296369/146984120-5c45e6f8-8510-478f-936e-9fdd626dbad2.png)

![image](https://user-images.githubusercontent.com/1296369/146984307-83fe87e6-f7d3-44d8-85ab-8be4d833f6f7.png)

**Comment by Fedik** [comment] 2021-12-21 19:44
now I get it, thanks for screenshot,
yea that a bug

**Comment by HLeithner** [comment] 2021-12-22 10:07
the problem is in the getRedirectToItemAppend function in the controller, we use the `cmd` filter to get the menutype. It's also in j3 but it seems the code is not used in j3 very often.

**Comment by Fedik** [comment] 2021-12-22 10:14
Maybe we have to use `cmd` for the field filter, before a save? or always transliterate that field (it does not meant to be used as alias anyway)

**Comment by richard67** [comment] 2021-12-23 10:28
Or we change the filter from cmd to string.

**Comment by Hackwar** [comment] 2022-11-05 22:13
I just tested this with a menu named `menü` for the "unique name" and can't reproduce this anymore. I set the aliases to unicode, created the menu and it has an umlaut in the name field. When clicking on the backend menu link, I get a proper screen with the right content. Has this since been solved?

**Comment by brianteeman** [comment] 2022-11-05 22:40
>  Has this since been solved?

Looks like it to me

**Comment by Hackwar** [comment] 2022-11-05 22:41
Then I'm closing this one.

**Closed as completed by Hackwar** 2022-11-05 22:41 UTC
Labels: No Code Attached Yet, J4 Issue, bug
