### ISSUE TITLE
tag input field without a form return an error.

### ISSUE THREAD

**Issue by mboucetta** [joomla/joomla-cms#12386] opened 2016-10-11 15:37 UTC
### Steps to reproduce the issue
I am developing a component. 
In this component I would like to add an input tag field (the same you have when you create an article).This input will be associated to a custom search panel. I tried: 
$tags= JFormHelper::loadFieldType('Tag'); 
echo $tags->input; 
But it returns an error:
Fatal error: Call to a member function getName() on null in C:\wamp64\www\mynotes\libraries\cms\form\field\tag.php on line 155

Indeed to be able to execute JFormFieldTag::getInput a form object is required. See tag.php -> getOptions():
if ($this->form->getName() == 'com_tags.tag')

### Expected result
I am expecting a tag input field as when you create an article.

### Actual result
Fatal error: Call to a member function getName() on null in C:\wamp64\www\mynotes\libraries\cms\form\field\tag.php on line 155

### System information (as much as possible)
joomla Joomla! 3.6.2 / Windows 7 / WAMP 3.0.6

### Additional comments
Maybe it is not a bug but a misuse. If so please let me know the correct procedure.

**Comment by mbabker** [comment] 2016-10-11 15:42
Form fields aren't really designed to be used outside of the "normal" form constructs.  It is a requirement to have a `JForm` object set to `JFormField` instances, so if you're trying to use the field to spit out markup outside of the "normal" workflow you'll need to build up a stub `JForm` object with the minimal config needed to make this work.

**Comment by brianteeman** [comment] 2016-10-11 15:47
I am closing this here. this is an issue about using the code not a bug in the code and you already have a topic on the correct google group for support/help

**Closed by brianteeman** 2016-10-11 15:47 UTC
