### ISSUE TITLE
CodeMirror Latest version

### ISSUE THREAD

**Issue by Twincarb** [joomla/joomla-cms#12488] opened 2016-10-20 10:52 UTC
### Steps to reproduce the issue
https://github.com/codemirror/CodeMirror/releases

### Expected result
Latest version installed

### Actual result
We are a couple of versions behind

### System information (as much as possible)
Latest version is 5.20 we are currently using 4.18

**Comment by brianteeman** [comment] 2016-10-20 12:02
We are currently on 5.18 in Joomla 3.6.3 and 5.19 was merged into Joomla 3.7 4 days ago see #12300 

@okonomiyaki3000 does a great job in supplying the codemirror updates but of course because the codemirror release schedule doesnt match the Joomla release schedule there will always be differences

**Closed by brianteeman** 2016-10-20 12:02 UTC
Labels: No Code Attached Yet

**Comment by Twincarb** [comment] 2016-10-20 12:39
@okonomiyaki3000 Codemirror is now at version 5.20

@brianteeman my mistake saying we were still on 4.18 (I got the sub version right!) - version 5.20 was released today hence opening the new tracker, closing it before the latest staging is updated is slightly preemptive.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12488">issues.joomla.org/tracker/joomla-cms/12488</a>.</sub>

**Comment by brianteeman** [comment] 2016-10-20 12:41
There is no need for this issue as @okonomiyaki3000 does a great job at
keeping it update

**Comment by dgt41** [comment] 2016-10-20 12:43
Just a heads up here, in joomla 4 there will be script that will automatically update all these libraries to their latest version

**Comment by brianteeman** [comment] 2016-10-20 12:50
That's not confirmed at all and something that still needs to be fully
considered as there are consequences buy that is completely off topic here

**Comment by dgt41** [comment] 2016-10-20 12:54
> That's not confirmed at all 

What do you mean? The code is already written and accepted

**Comment by brianteeman** [comment] 2016-10-20 12:55
Where

**Comment by dgt41** [comment] 2016-10-20 12:58
not public yet...

**Comment by mbabker** [comment] 2016-10-20 12:59
Nothing is final until it goes into a release.  Even if it's already merged into a repo.  How many pull requests have we all had changed or reverted?

**Comment by dgt41** [comment] 2016-10-20 13:01
OK, lets ignore my initial comment here 😀

**Comment by brianteeman** [comment] 2016-10-20 13:03
So it is not accepted then if its not in the repo. And it won't be in J4
until J4 is released. That's the fact.

It is not beneficial at all to tell people that invisible feature x has
been accepted and will be in a release.

**Comment by dgt41** [comment] 2016-10-20 13:09
@brianteeman this is a feature mainly for the project maintainers, so instead of manually d/l and replace tinyMCE, code mirror, etc this is done automatically
(personally I'm pretty sure it's gonna be accepted as it's enormously helpful and reduces the amount of work to keep things in sync. But as Micheal said, let's wait for the final version and the decision on that...)

**Comment by andrepereiradasilva** [comment] 2016-10-20 13:11
+1 @dgt41

also +1 for all automatizing repeative tasks in the future!

**Comment by brianteeman** [comment] 2016-10-20 14:11
Massive difference between you thinking it's going to be accepted and your statement that it was already accepted.

Massive difference between code being merged into the repo automatically and code being merged into users sites automatically

**Comment by okonomiyaki3000** [comment] 2016-10-20 15:10
Thanks for the heads up about 5.20, I'll have a PR for it soon. Also interesting news about Joomla 4. That feature sounds awesome. 

If there is any issue of people using an old version of Joomla and unable to upgrade for some reason but want to run a new version of codemirror, I can easily make an installable package of the latest version that should work with any Joomla above 3.0 (probably). With a little work, it could also work with older Joomlas. 

In case anyone is interested, this is how I keep CodeMirror in Joomla up-to-date: https://github.com/okonomiyaki3000/joomla-codemirror-builder It seems that 5.20 has some interesting changes that may require an update to this script though.
