### ISSUE TITLE
Smart Search does not highlight search terms when located below the

### ISSUE THREAD

**Issue by Ooops-404** [joomla/joomla-cms#19518] opened 2018-02-01 18:26 UTC
### Steps to reproduce the issue
- Create an article and add the ```<hr id="system-readmore" />``` anywhere in the article.
- Enable the " Highlight Search Terms " under Smart Search options
- Use smart search to find a term that is located after the ```<hr id="system-readmore" />```

### Expected result
Smart Search should fetch the article and highlight the term.

### Actual result
Smarth Search fetches the article but does not highlight the term.

### System information (as much as possible)

PHP Built On | Linux playground 3.10.0-514.21.2.el7.x86_64 #1 SMP Tue Jun 20 12:24:47 UTC 2017 x86_64
-- | --
Database Version | 5.5.56-MariaDB
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.0.27
Web Server | Apache/2.4.6 (CentOS) PHP/7.0.27
WebServer to PHP Interface | apache2handler
Joomla! Version | Joomla! 3.8.4-dev Development [ Amani ] 12-December-2017 15:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0

### Additional comments
I have already created an issue for other inconsistencies with Smart Search. 
Not sure if these should be merged.  #19339

**Comment by ghost** [comment] 2018-02-01 18:32
Changed Description in "Steps to reproduce the issue" to ```<hr id="system-readmore" />```<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19518">issues.joomla.org/tracker/joomla-cms/19518</a>.</sub>

**Comment by ghost** [comment] 2018-02-01 18:42
Issue confirmed:

![bildschirmfoto 2018-02-01 um 19 40 59](https://user-images.githubusercontent.com/8235763/35696496-f5cbb9ac-0787-11e8-93f2-65c36ab4ed36.jpg)

**Comment by brianteeman** [comment] 2018-03-27 15:42
The reason is that only the content of the introtext field and not the introtext + fulltext  is being passed to the $description 

Mybe that will help someone work out how to "fix" this

**Comment by infograf768** [comment] 2018-03-29 09:55
I  may have solved the issue here. We can make it a forced solution or create a new param.
What is preferred?

**Comment by brianteeman** [comment] 2018-03-29 09:58
I cant see any reason myself for it not to be the default behaviour nor for their to be an option to disable it

**Comment by infograf768** [comment] 2018-03-29 12:11
Please test https://github.com/joomla/joomla-cms/pull/20019
Closing as we have a PR

**Closed as completed by infograf768** 2018-03-29 12:11 UTC
Labels: No Code Attached Yet
