### ISSUE TITLE
Joomla stores superadmin login in configuration.php if you save the login credentials in Firefox

### ISSUE THREAD

**Issue by keep** [joomla/joomla-cms#8709] opened 2015-12-16 13:07 UTC
#### Steps to reproduce the issue
Open a Joomla administrator page with Firefox
Log in
Save the username/password in the browser
Open the global configuration menu item
Save

Your saved username/password will appear in your configuration.php as $ftp_user and $ftp_pass.

Firefox fill in these input fields even the FTP layer is disabled!

**Comment by brianteeman** [comment] 2015-12-16 13:17
Which exact versions of Joomla and Firefox are you using?

I could not replicate this with the current staging joomla and firefox 42.0
on osx

On 16 December 2015 at 13:07, keep <notifications@github.com> wrote:

> Steps to reproduce the issue
>
> Open a Joomla administrator page with Firefox
> Log in
> Save the username/password in the browser
> Open the global configuration menu item
> Save
>
> Your saved username/password will appear in your configurationphp as
> $ftp_user and $ftp_pass
>
> Firefox fill in these input fields even the FTP layer is disabled!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/8709>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by N6REJ** [comment] 2015-12-16 14:25
check to be sure ftp fields are empty and then save again and see if its still in configuration.php please

**Comment by ggppdk** [comment] 2015-12-16 20:16
@N6REJ 
- the fields when hidden (FTP layer disabled), are supposed to maintain their existing values passwords 
- for firefox is autofilling the empty fields a workaround to disable auto fill is needed like this:
#7094

**Comment by brianteeman** [comment] 2016-01-27 09:47
This should have been resolved by #8800 I am closing this at this time but it can always be reopened if the problem is still present in Joomla 3.5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8709">issues.joomla.org/joomla-cms/8709</a>.</sub>

**Closed** 2016-01-27 09:47 UTC
Labels: No Code Attached Yet
