### ISSUE TITLE
HTMLHelper.php deprecation error message (added more information)

### ISSUE THREAD

**Issue by aberenguer78** [joomla/joomla-cms#44574] opened 2024-12-03 14:44 UTC
### Steps to reproduce the issue

I provide you an image of the error in my configuration form of the module:

![Image](https://github.com/user-attachments/assets/8f19e124-b1d2-4595-b019-b261bff3ca3d)

When opening my custom module appears this deprecation error:
Deprecated: Automatic conversion of false to array is deprecated in C:\xamppPHP8.2\htdocs\joomla5\libraries\src\HTML\HTMLHelper.php on line 810
The error message is in joomla root\libraries\src\HTMLHelper.php line 810

I detected that in both functions of HTMLHelper.php class have the same issue:
- public static function stylesheet($file, $options = [], $attribs = [])
-  public static function script($file, $options = [], $attribs = [])

On the first line of each of this functions to avoid the error should be added:

### Expected result
No deprecation error is shown

### Actual result
A deprecation message appears

### System information (as much as possible)
Joomla 5.2.2
PHP 8.3.13

### Additional comments
Solution add this line in 810: (Solution provided by chat gpt - deprecation happens in php 8.2)
$options = is_array($options) ? $options : [];
$options['relative'] = $options['relative'] ?? false;

In my scripts I'm not calling directly to this functions, is something done internally by joomla, I haven't find the code that calls to this script function but I think it's something it should be solved.

**Comment by fgsw** [comment] 2024-12-03 16:21
see also closed #44573.

**Comment by Fedik** [comment] 2024-12-03 18:34
This is not the information you were asked for.
Please check previus comments again.

With spamming you not helping yourself.

**Comment by aberenguer78** [comment] 2024-12-04 07:41
I have been debugging the module and the functions are called by joomla on loading the configuration form of the module.
Sorry by the confusion in this module I don't have calls to JHTML or the newest HTMLHelper, so the problem is not related to that I think.
What I have seen is that when it's called the function the value of parameter options is false and for this reason is giving the deprecation message.

**Comment by aberenguer78** [comment] 2024-12-04 08:11
Sorry I have seen in a custom field that I have migrated this:
//JHtml::_('script', 'system/modal-fields.js', array('version' => 'auto', 'relative' => true));
to this:
HTMLHelper::_('script', 'system/modal-fields.js', false, true);

What would be the correct migration for this line provided??

Altough I probably have a bad call to HMTLHelper I think that It would be nice that you add this line to the functions commented to check the array is correct:

$options = is_array($options) ? $options : [];

**Comment by brianteeman** [comment] 2024-12-04 09:13
We really would like to help but without seeing the code it is impossible!!

**Comment by Fedik** [comment] 2024-12-04 09:28
> `HTMLHelper::_('script', 'system/modal-fields.js', false, true);`

This is a reason of the PHP warning.
Valid call would be `HTMLHelper::_('script', 'system/modal-fields.js', array('version' => 'auto', 'relative' => true));`, but it also outdated.

However  ` 'system/modal-fields.js'` is something from Joomla 3 and does not exists animore, you can remove that line.

**Comment by Fedik** [comment] 2024-12-04 12:41
>  ... what would be the correct code for the call

If you have example:
```php
HTMLHelper::_('script', 'mod_mymodule/my-script.js', array('version' => 'auto', 'relative' => true));
```
You can use WebassetManager and register your asset with joomla.asset.json, or just:
```php
$wa->registerAndUseScript('mod_mymodule.my-script', 'mod_mymodule/my-script.js');
```
Can find more at https://manual.joomla.org/docs/next/general-concepts/web-asset-manager/#working-with-scripts
And https://manual.joomla.org/docs/next/building-extensions/modules/module-development-tutorial/step7-javascript/

> I removed the code you mentioned and all seems to continue working properly

Yeap, that file does not exists in Joomla 5.

I am closing the issue as not a bug.

**Closed as completed by Fedik** 2024-12-04 12:41 UTC
Labels: No Code Attached Yet, Information Required
