### ISSUE TITLE
HTTP ERROR 500 after updating joomla 3.8

### ISSUE THREAD

**Issue by SaidBa** [joomla/joomla-cms#18026] opened 2017-09-20 21:35 UTC
Since i have updated to joomla 3.8 i cannot acces my joomla administrator (backend). I get the error:

HTTP ERROR 500

How can i fix this.

Please help.

### System information (as much as possible)
I am using the last version of PHP en MYSQL

### Additional comments
How to i solve this en can i make my backend accesseble

**Comment by brianteeman** [comment] 2017-09-20 22:11
Duplicate of #18025

**Closed as completed by brianteeman** 2017-09-20 22:11 UTC
Labels: No Code Attached Yet

**Comment by SaidBa** [comment] 2017-09-20 22:12
Yes, that is correct, but do you have a solution
