### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by ledavelasquez** [joomla/joomla-cms#17327] opened 2017-07-28 22:43 UTC
### System information (as much as possible)

i´m a user  of acymailing but since last week i can´t access the web to send mailings. It appears this message:

Fatal error: Uncaught Error: Call to undefined function set_magic_quotes_runtime() in /home3/promoto4/public_html/marketing/administrator/includes/framework.php:21 Stack trace: #0 /home3/promoto4/public_html/marketing/administrator/index.php(22): require_once() #1 {main} thrown in /home3/promoto4/public_html/marketing/administrator/includes/framework.php on line 21

http://www.promotoraandalucia.com/marketing/administrator/index.php?option=com_acymailing&ctrl=list

**Comment by zero-24** [comment] 2017-07-28 22:49
Please double check that you use the last version of joomla and the extension. 

https://github.com/joomla/joomla-cms/blob/staging/administrator/includes/framework.php#L21

If you are on the last version you are hacked as the method that throw the error does not exist at the place the error come from. What was the last thing you changed in that installation?

**Comment by ggppdk** [comment] 2017-07-28 23:56
The extension is not related

About this error
you seem to have Joomla 1.5.x and your PHP version has probably been upgraded to PHP 7.x recently

Please note that this is not a bug of Joomla 3.x, and this is not a support forum

You can try to ask your webhost to downgrade PHP version for this website so that you have time to ask a web company to upgrade your website to latest Joomla version ASAP

**Comment by ghost** [comment] 2017-07-29 05:47
closed as no Core-Issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17327">issues.joomla.org/tracker/joomla-cms/17327</a>.</sub>

**Closed as completed by ghost** 2017-07-29 05:47 UTC
Labels: No Code Attached Yet
