### ISSUE TITLE
Backend menu item types not translated

### ISSUE THREAD

**Issue by Denitz** [joomla/joomla-cms#32855] opened 2021-03-25 06:07 UTC
### Steps to reproduce the issue

Enable language debug and create a new admin menu item of "Articles > Create an Article" type.

### Expected result

See in menu items list:

`**Articles** » **Create An Article**`

### Actual result

`**Articles** » article`

### System information (as much as possible)

Unrelated

### Additional comments

Joomla 3 and 4 affected.

**Comment by infograf768** [comment] 2021-03-25 06:19
Can't reproduce
J4
<img width="231" alt="Screen Shot 2021-03-25 at 07 17 32" src="https://user-images.githubusercontent.com/869724/112427646-39118080-8d3a-11eb-98af-78879a23b139.png">

J3
<img width="479" alt="Screen Shot 2021-03-25 at 07 18 20" src="https://user-images.githubusercontent.com/869724/112427697-50506e00-8d3a-11eb-9e75-39024877d5e2.png">

**Comment by Denitz** [comment] 2021-03-25 07:06
@infograf768 Are you sure you create a menu item in Administrator menu, not in Site?

**Comment by infograf768** [comment] 2021-03-25 07:12
Was in site indeed. Should have read better.
In admin, it looks like what you describe is common to all mernu items. Looking into it.

**Comment by infograf768** [comment] 2021-03-25 08:59
Please test
```
diff --git a/administrator/components/com_menus/views/items/view.html.php b/administrator/components/com_menus/views/items/view.html.php
index 9b5a07c..b53cd1c 100644
--- a/administrator/components/com_menus/views/items/view.html.php
+++ b/administrator/components/com_menus/views/items/view.html.php
@@ -157,10 +157,23 @@
 							else
 							{
-								// Get XML file from component folder for standard layouts
-								$file = JPATH_SITE . '/components/' . $item->componentname . '/views/' . $vars['view'] . '/tmpl/' . $vars['layout'] . '.xml';
-
-								if (!file_exists($file))
+								if ($this->state->get('filter.client_id') == 0)
 								{
-									$file = JPATH_SITE . '/components/' . $item->componentname . '/view/' . $vars['view'] . '/tmpl/' . $vars['layout'] . '.xml';
+									// Get XML file from component folder for standard layouts
+									$file = JPATH_SITE . '/components/' . $item->componentname . '/views/' . $vars['view'] . '/tmpl/' . $vars['layout'] . '.xml';
+
+									if (!file_exists($file))
+									{
+										$file = JPATH_SITE . '/components/' . $item->componentname . '/view/' . $vars['view'] . '/tmpl/' . $vars['layout'] . '.xml';
+									}
+								}
+								else
+								{
+									// Get XML file from administrator component folder for standard layouts
+									$file = JPATH_ADMINISTRATOR . '/components/' . $item->componentname . '/views/' . $vars['view'] . '/tmpl/' . $vars['layout'] . '.xml';
+
+									if (!file_exists($file))
+									{
+										$file = JPATH_ADMINISTRATOR . '/components/' . $item->componentname . '/view/' . $vars['view'] . '/tmpl/' . $vars['layout'] . '.xml';
+									}
 								}
 							}
```

i.e. modify `administrator/components/com_menus/views/items/view.html.php` from line 159
from
```
							else
							{
								// Get XML file from component folder for standard layouts
								$file = JPATH_SITE . '/components/' . $item->componentname . '/views/' . $vars['view'] . '/tmpl/' . $vars['layout'] . '.xml';

								if (!file_exists($file))
								{
									$file = JPATH_SITE . '/components/' . $item->componentname . '/view/' . $vars['view'] . '/tmpl/' . $vars['layout'] . '.xml';
								}
							}
```
to
```
							else
							{
								if ($this->state->get('filter.client_id') == 0)
								{
									// Get XML file from component folder for standard layouts
									$file = JPATH_SITE . '/components/' . $item->componentname . '/views/' . $vars['view'] . '/tmpl/' . $vars['layout'] . '.xml';

									if (!file_exists($file))
									{
										$file = JPATH_SITE . '/components/' . $item->componentname . '/view/' . $vars['view'] . '/tmpl/' . $vars['layout'] . '.xml';
									}
								}
								else
								{
									// Get XML file from administrator component folder for standard layouts
									$file = JPATH_ADMINISTRATOR . '/components/' . $item->componentname . '/views/' . $vars['view'] . '/tmpl/' . $vars['layout'] . '.xml';

									if (!file_exists($file))
									{
										$file = JPATH_ADMINISTRATOR . '/components/' . $item->componentname . '/view/' . $vars['view'] . '/tmpl/' . $vars['layout'] . '.xml';
									}
								}
							}
```

**Comment by Denitz** [comment] 2021-03-25 10:30
Templates should be checked as well, maybe this after 143:

```
							$base = $this->state->get('filter.client_id') == 0 ? JPATH_SITE : JPATH_ADMINISTRATOR;

							// Attempt to load the layout xml file.
							// If Alternative Menu Item, get template folder for layout file
							if (strpos($vars['layout'], ':') > 0)
							{
								// Use template folder for layout file
								$temp = explode(':', $vars['layout']);
								$file = $base . '/templates/' . $temp[0] . '/html/' . $item->componentname . '/' . $vars['view'] . '/' . $temp[1] . '.xml';

								// Load template language file
								$lang->load('tpl_' . $temp[0] . '.sys', $base, null, false, true)
								||	$lang->load('tpl_' . $temp[0] . '.sys', $base . '/templates/' . $temp[0], null, false, true);
							}
							else
							{
								// Get XML file from component folder for standard layouts
								$file = $base . '/components/' . $item->componentname . '/views/' . $vars['view'] . '/tmpl/' . $vars['layout'] . '.xml';

								if (!file_exists($file))
								{
									$file = $base . '/components/' . $item->componentname . '/view/' . $vars['view'] . '/tmpl/' . $vars['layout'] . '.xml';
								}
							}
```

**Comment by infograf768** [comment] 2021-03-25 10:37
> Templates should be checked as well, maybe this after 143:

Yep. Also use $base in my proposal to simplify.

Can you make PR?

**Comment by saumyasarkar11** [comment] 2021-03-25 11:10
I've tried to create this PR as per your instructions stated above. Do let me know your feedback

**Comment by infograf768** [comment] 2021-03-25 11:15
I did in your PR.

**Comment by Denitz** [comment] 2021-03-25 12:09
The code is wrong

replace original code
```
							$vars['layout'] = isset($vars['layout']) ? $vars['layout'] : 'default';

							// Attempt to load the layout xml file.
							// If Alternative Menu Item, get template folder for layout file
							if (strpos($vars['layout'], ':') > 0)
							{
								// Use template folder for layout file
								$temp = explode(':', $vars['layout']);
								$file = JPATH_SITE . '/templates/' . $temp[0] . '/html/' . $item->componentname . '/' . $vars['view'] . '/' . $temp[1] . '.xml';

								// Load template language file
								$lang->load('tpl_' . $temp[0] . '.sys', JPATH_SITE, null, false, true)
								||	$lang->load('tpl_' . $temp[0] . '.sys', JPATH_SITE . '/templates/' . $temp[0], null, false, true);
							}
							else
							{
								// Get XML file from component folder for standard layouts
								$file = JPATH_SITE . '/components/' . $item->componentname . '/views/' . $vars['view'] . '/tmpl/' . $vars['layout'] . '.xml';

								if (!file_exists($file))
								{
									$file = JPATH_SITE . '/components/' . $item->componentname . '/view/' . $vars['view'] . '/tmpl/' . $vars['layout'] . '.xml';
								}
							}
```

with

```
							$vars['layout'] = isset($vars['layout']) ? $vars['layout'] : 'default';

							$base = $this->state->get('filter.client_id') == 0 ? JPATH_SITE : JPATH_ADMINISTRATOR;

							// Attempt to load the layout xml file.
							// If Alternative Menu Item, get template folder for layout file
							if (strpos($vars['layout'], ':') > 0)
							{
								// Use template folder for layout file
								$temp = explode(':', $vars['layout']);
								$file = $base . '/templates/' . $temp[0] . '/html/' . $item->componentname . '/' . $vars['view'] . '/' . $temp[1] . '.xml';

								// Load template language file
								$lang->load('tpl_' . $temp[0] . '.sys', $base, null, false, true)
								||	$lang->load('tpl_' . $temp[0] . '.sys', $base . '/templates/' . $temp[0], null, false, true);
							}
							else
							{
								// Get XML file from component folder for standard layouts
								$file = $base . '/components/' . $item->componentname . '/views/' . $vars['view'] . '/tmpl/' . $vars['layout'] . '.xml';

								if (!file_exists($file))
								{
									$file = $base . '/components/' . $item->componentname . '/view/' . $vars['view'] . '/tmpl/' . $vars['layout'] . '.xml';
								}
							}
```

**Comment by infograf768** [comment] 2021-03-25 12:59
@Denitz

I am in fact wondering about modifying the path when we have an alternative menu item in the site template. It does not look right.

**Comment by brianteeman** [comment] 2021-03-25 13:06
@Denitz please submit a pull request instead of posting code in a comment

**Comment by infograf768** [comment] 2021-03-26 08:28
Patch https://github.com/joomla/joomla-cms/pull/32871
closing

**Closed as completed by infograf768** 2021-03-26 08:28 UTC
Labels: No Code Attached Yet
