### ISSUE TITLE
[4.0] Not support DragInDrop to "mediafield" in Article Editor and not Support format WEBP

### ISSUE THREAD

**Issue by korenevskiy** [joomla/joomla-cms#28305] opened 2020-03-10 15:33 UTC
### Steps to reproduce the issue
Bug DragInDrop.
The standard` <input type="file"/>` field supports drag and drop. You can take an image file and drag it to the file field in any form of any Chromium-based browser site.
However, this function does not work when dragging a file to the image field in the material editor.
The modified file field should inherit from the `<input type="file"/>` field, we can use the <label> tag, and add more functions. But you should always use the standard field `<input type= "file"/>`.
However, the material editor uses the `<input type="TEXT"/>` field without using the `<LABEL>`tag.
.
It is important to note that the field supposedly serves for the name of the file selected from the server. However, you can't change the name manually, which means it doesn't matter to the user what type of field this field actually is. If this is the case, we can use the hidden field `<input type="hidden" name="filename"/>`, but use the open field `<input type="file"/>` to upload and drag the file to the content editor.
.
The PHP language perfectly supports all the functions of working with WEBP images natively . 
 C hromium browsers natively support a ll functions o f working with WEBP images .
All viewers support the WEBP format.
MS Paint supports the HEIC format.
However, you need libraries to convert HEIC to PHP. the WEBP format is supported by PHP natively.

**Comment by Quy** [comment] 2020-03-10 15:37
#27477 Please see if this a duplicate report.
#24157 WebP support request.

**Comment by jwaisner** [comment] 2020-03-11 16:07
@korenevskiy please check the issues that Quy commented with. Are these what you are reporting?

**Comment by jwaisner** [comment] 2020-03-11 16:21
Duplicate of [#24157](https://github.com/joomla/joomla-cms/issues/24157 "#24157")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28305">issues.joomla.org/tracker/joomla-cms/28305</a>.</sub>

**Closed as completed by jwaisner** 2020-03-11 16:21 UTC
Labels: No Code Attached Yet

**Comment by brianteeman** [comment] 2020-03-11 16:22
There are two issues here

1. webp - duplicate report

2. draag and drop image upload directly on the image input field - new feature request
