### ISSUE TITLE
[4.0] Problem with pre-update check

### ISSUE THREAD

**Issue by PhocaCz** [joomla/joomla-cms#31883] opened 2021-01-07 23:04 UTC
### Steps to reproduce the issue
1) Install Joomla! 4 Beta 6

2) Install Phoca Top Menu Module or another extension ( https://github.com/PhocaCz/PhocaTopMenuModule/releases/download/4.0.3/mod_phocatopmenu_v4.0.3.zip )

3) Enable debug mode (to work with not minified JS file)

3) Go to System - Update - Joomla! (Joomla! Update)

![img](https://i.imgur.com/QwYnJL8.png)

Page not responding with following error in console:

`
default.js?78b00d0ca57c1fd6d2f9ee3935963d7b:217 Uncaught TypeError: node.data is not a function
    at Object.PreUpdateChecker.checkCompatibility (default.js?78b00d0ca57c1fd6d2f9ee3935963d7b:217)
    at default.js?78b00d0ca57c1fd6d2f9ee3935963d7b:192
    at Array.forEach (<anonymous>)
    at HTMLDocument.PreUpdateChecker.run (default.js?78b00d0ca57c1fd6d2f9ee3935963d7b:189)
PreUpdateChecker.checkCompatibility @ default.js?78b00d0ca57c1fd6d2f9ee3935963d7b:217
(anonymous) @ default.js?78b00d0ca57c1fd6d2f9ee3935963d7b:192
PreUpdateChecker.run @ default.js?78b00d0ca57c1fd6d2f9ee3935963d7b:189
`

This can be solved when editing the line 217
(media/com_joomlaupdate/js/default.js)

FROM:
`+ 'extension-version=' + node.data('extension-current-version')`
TO:
`+ 'extension-version=' + node.getAttribute('data-extension-current-version')`

But then another error occurs:

`
default.js?2ef16fb02f7b20a2a5704e5f6e9cdd03:306 Uncaught TypeError: Cannot read property 'data' of undefined
    at PreUpdateChecker.setResultView (default.js?2ef16fb02f7b20a2a5704e5f6e9cdd03:306)
    at onSuccess (default.js?2ef16fb02f7b20a2a5704e5f6e9cdd03:225)
    at XMLHttpRequest.xhr.onreadystatechange (core.js?2ef16fb02f7b20a2a5704e5f6e9cdd03:214)
PreUpdateChecker.setResultView @ default.js?2ef16fb02f7b20a2a5704e5f6e9cdd03:306
onSuccess @ default.js?2ef16fb02f7b20a2a5704e5f6e9cdd03:225
xhr.onreadystatechange @ core.js?2ef16fb02f7b20a2a5704e5f6e9cdd03:214
XMLHttpRequest.send (async)
Joomla.request @ core.js?2ef16fb02f7b20a2a5704e5f6e9cdd03:228
PreUpdateChecker.checkCompatibility @ default.js?2ef16fb02f7b20a2a5704e5f6e9cdd03:213
(anonymous) @ default.js?2ef16fb02f7b20a2a5704e5f6e9cdd03:192
PreUpdateChecker.run @ default.js?2ef16fb02f7b20a2a5704e5f6e9cdd03:189
`

The source code is:

`var extensionId = extensionData.$element.data('extensionId');`

### Expected result

Information about extensions should be displayed:

![img](https://i.imgur.com/h8YR8qm.png)

### Actual result

Information about extensions are not loaded

### System information (as much as possible)
Joomla! Beta 6 (4.0.0-beta6)
PHP 7.4.1

### Additional comments

Maybe somehow related to: https://github.com/joomla/joomla-cms/pull/29980

Jan

**Comment by PhilETaylor** [comment] 2021-01-08 13:35
I don't get that far - I just get 

`TypeError: e.data is not a function. (In 'e.data("extension-current-version")', 'e.data' is undefined)`

and

<img width="781" alt="Screenshot 2021-01-08 at 13 35 21" src="https://user-images.githubusercontent.com/400092/104021274-68423800-51b6-11eb-869e-de8999ec2316.png">

**Comment by zero-24** [comment] 2021-01-08 16:16
I have discuessed this the other day with @wilsonge already and we are aware of issues with the pre upgrade checker. Given that the JS code has to be rewritten. So please give the 3.10 version a try and lets make sure that this is getting fully converted so we can make sure the 4.x version runs too once we have a complete state of the 3.10 version.

**Comment by wilsonge** [comment] 2021-01-08 16:18
Closing as it's a duplicate of https://github.com/joomla/joomla-cms/issues/31490

**Closed as completed by wilsonge** 2021-01-08 16:18 UTC
Labels: No Code Attached Yet
