### ISSUE TITLE
OpCache: Avoid conflicts when upgrading / installing extensions

### ISSUE THREAD

**Issue by JensKirk** [joomla/joomla-cms#9192] opened 2016-02-22 13:55 UTC
Using OpCache speeds up sites very much (at least for our sites), but it sometimes makes conflicts when installing or opgrading Joomla extensions.

The solution is to empty the opcache before the installation / upgrade (and perhaps also after). If we empty the OpCache manually before and after an opgrade it does not make conflicts at all.

The solution is to insert this in the installer:

if (extension_loaded('Zend OPcache') opcache_reset())

Can this be done in a future version?

**Comment by brianteeman** [comment] 2016-02-22 14:07
Closing as a duplicate of your own issue #8249 

If you want to see this change in Joomla then please consider submitting a Pull Request<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9192">issues.joomla.org/joomla-cms/9192</a>.</sub>

**Closed by brianteeman** 2016-02-22 14:07 UTC
Labels: No Code Attached Yet
