### ISSUE TITLE
[com_contact] After Auto-Update 3.4.8 to 3.5.0 contact form is not rendered anymore

### ISSUE THREAD

**Issue by TinoJ** [joomla/joomla-cms#9536] opened 2016-03-23 01:15 UTC
(Warning: I have no idea of the code.)

#### Steps to reproduce the issue

I used the Joomla update to update from 3.4.8 to 3.5.0. 

#### Expected result

Happy face. ;)

#### Actual result

All is well but the contact page.
I have a menu item contact/imprint that is of type single contact. I have linked that to one contact (me).
The contact has been created over components > contacts. (not now, years ago)
After testing the website, the contact page only shows the "content" but not the header, navi, footer, layout etc.
The html source code starts with
"\<div class="contact" itemscope itemtype="http://schema.org/Person">"
and ends with
\<legend>Eine E-Mail senden\</legend>
(it's German)

I replaced the folder com_contact (3.5.0) with the backup com_contact (3.4.8) and everything was fine again.
I downloaded the upgrade package Joomla_3.5.0-Stable-Update_Package and unzipped it.
Then I replaced the old com_contact files one by one with the new ones.
I could narrow it down to \components\com_contact\views\contact\tmpl\default_form.php
If I replace that, the page is again broken.

#### System information (as much as possible)

SunOS 5.10 Generic_142901-13 i86pc
MySQL 5.5.47
DB utf8_general_ci
PHP-Version 5.5.33
Webserver Apache/2.2.31 (Unix) 

#### Additional comments

Since the files look totally different I have no idea why the old one works.

First screenshot -> broken
Second screenshot -> okay

![screen shot 2016-03-22 at 20 09 40](https://issues.joomla.org/uploads/1/39d7f884195a0b8d621f0db86f3e294d.png)![screen shot 2016-03-22 at 20 11 09](https://issues.joomla.org/uploads/1/e0f69c7523f9156dc7c8199ffcc25340.png)

**Comment by brianteeman** [comment] 2016-03-23 14:32
I cannot confirm this. I would "guess" it is either an issue with your template - can be confirmed by seeing if it works correctly using the protostar template OR a plugin that you have installed that is misbehaving<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9536">issues.joomla.org/joomla-cms/9536</a>.</sub>

**Comment by TinoJ** [comment] 2016-03-23 23:30
Hmm.... protostar works. Although looks totally different. Is it possible that a template has a problem with Joomla 3.x that did not occur until 3.5.0? I will google into that... :-(<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9536">issues.joomla.org/joomla-cms/9536</a>.</sub>

**Comment by xtopes** [comment] 2016-03-31 18:05
Hi All,

I have the same problem that after the upgrade from 3.4.8 to 3.5.0 contact form stopped to work. I mean it's a blank screen in Firefox and same in Internet Explorer. Basically I'm getting server error HTTP 500. 
I have changed the template for this menu to protostar - default, but still doesn't work. I have cleared all cache from the browser to avoid some caching and even used another PC, but no luck. It looks like some issue with 3.5.0 indeed. Can you help?
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9536">issues.joomla.org/joomla-cms/9536</a>.</sub>

**Comment by xtopes** [comment] 2016-03-31 18:26
Hi again,

I have replaced directory /httpdocs/components/com_contact/ with version from 3.4.8 and it works without issues for now. So I'm running semi 3.5.0 now, but if there would be a correct answer to this I would appreciate. I might do a comparison of code as well and will let you know if will find something.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9536">issues.joomla.org/joomla-cms/9536</a>.</sub>

**Comment by TinoJ** [comment] 2016-03-31 20:49
@brianteeman: It seems that my template could be outdated. It did work until know but maybe an old version of the template is the reason. I am going to install a new version of my template in the next few days and check if that fixes the problem.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9536">issues.joomla.org/joomla-cms/9536</a>.</sub>

**Comment by N6REJ** [comment] 2016-04-01 00:47
com_contact form works fine with my template on 3.5
Bear

**Comment by ggppdk** [comment] 2016-04-01 06:13
Temporarily enable error reporting in Joomla Global configuration to see if some PHP notice or warning gets printed (or check your error log file but this would more difficult to read)

**Comment by brianteeman** [comment] 2016-04-06 10:57
I am closing this at this time as an issue with a third party template. If more information is provided to replicate the issue with one of the core templates it can always be reopened<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9536">issues.joomla.org/joomla-cms/9536</a>.</sub>

**Closed** 2016-04-06 10:57 UTC
Labels: No Code Attached Yet

**Comment by TinoJ** [comment] 2016-04-07 22:30
Hi @brianteeman, I just finished updating and testing my template. I can confirm that the template did need an update. It just worked until 3.4.8. Pure luck, I would say. So your hint to find the cause was just brilliant. Thank you for your help.
Best, Tino<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9536">issues.joomla.org/joomla-cms/9536</a>.</sub>

**Comment by brianteeman** [comment] 2016-04-07 22:32
Glad to have helped
