### ISSUE TITLE
JUri::root + HTTP not working reliable with load balancer

### ISSUE THREAD

**Issue by cdekok** [joomla/joomla-cms#10086] opened 2016-04-25 13:09 UTC
https://github.com/joomla/joomla-cms/blob/881021635765e6b055188e6ad7d25d50a6db2cf8/libraries/joomla/uri/uri.php#L66

It should also check on 

[HTTP_X_FORWARDED_PORT] => 443
[HTTP_X_FORWARDED_PROTO] => https

Else it generates an http link for https website.

**Comment by zero-24** [comment] 2016-04-25 15:03
@cdekok can you send your changes as pull request agianst the staging repo?

If you don't know how github works you can have a quick look at: https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests

**Comment by wojsmol** [comment] 2016-04-25 15:23
Simular PR https://github.com/joomla/joomla-cms/pull/7439

**Comment by PhilETaylor** [comment] 2016-05-19 20:41
Duplicate of https://github.com/joomla/joomla-cms/issues/9756

**Comment by franz-wohlkoenig** [comment] 2017-04-06 13:48
closed as Duplicate of #9756, thanks for Hint @PhilETaylor <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10086">issues.joomla.org/tracker/joomla-cms/10086</a>.</sub>

**Closed by franz-wohlkoenig** 2017-04-06 13:48 UTC
Labels: No Code Attached Yet
