### ISSUE TITLE
LDAP broken in 3.8

### ISSUE THREAD

**Issue by arraylabs** [joomla/joomla-cms#17989] opened 2017-09-19 18:09 UTC
### Steps to reproduce the issue
Configure LDAP, try to login with LDAP user

### Expected result
LDAP to authenticate properly, currently failing with line 119 of ldap.php file.

### Actual result
Currently failing with line 119 of ldap.php file, specifically the $ldap->escape method that upon further inspection does not exist in the LdapClient.php file. 

### System information (as much as possible)
LAMP, php 6.x, J3.8

**Comment by mbabker** [comment] 2017-09-19 18:20
Replace the file with https://github.com/joomla-framework/ldap/blob/1.2.0/src/LdapClient.php

Apparently some pull request updating the file didn't get applied (or submitted?).

**Comment by mbabker** [comment] 2017-09-19 18:26
https://github.com/joomla/joomla-cms/commit/d35924eea81983da2e48d29d3256e66d37f9e748 fixes this.  Will be included in 3.8.1.

Leaving this open for a little bit just so we don't get a plethora of similar opened issues.

**Comment by arraylabs** [comment] 2017-09-19 18:28
Appreciate it, thanks!!

**Comment by brianteeman** [comment] 2017-09-19 19:37
Created an FAQ https://docs.joomla.org/J3.x:J3.8.0_LDAP

**Comment by kdhoe1** [comment] 2017-09-21 09:00
This sollution doesn't work with registered users, only super users can login
regards

**Comment by mbabker** [comment] 2017-09-21 12:02
@kdhoe1 not knowing anything more about your problem I can say with certainty that your problem is not related to this issue and you should file a separate report with appropriate details.

**Comment by kdhoe1** [comment] 2017-09-21 12:19
before update to version 3.8.0 no issues during logon of all users through ldap in frontend.
after update: 0 - Call to undefined method Joomla\Ldap\LdapClient::escape() for all users
when replacing ldap file, only super users can login, regular users get: 0 - Class 'Joomla\Ldap\LdapClient' not found
???

**Comment by mbabker** [comment] 2017-09-21 12:28
Then you have not replaced the file correctly as the file contains that class.

**Comment by kdhoe1** [comment] 2017-09-21 12:29
just deleted the file on the server and copied the new file
is there another way?

regards

**Comment by mbabker** [comment] 2017-09-21 12:31
If you downloaded the HTML page and used that, then that would break it.  Make sure you hit the "raw" button on the page so you get the actual PHP file that should be uploaded without any extra HTML.  Additionally, the file must be uploaded with the correct casing in the name otherwise the file loader won't pick it up.

**Comment by kdhoe1** [comment] 2017-09-21 12:58
OK, Big thanks, it works

Regards

Kris

**Closed as completed** 2017-09-21 14:28 UTC
Labels: No Code Attached Yet

**Comment by EHJ-52n** [comment] 2017-09-22 07:17
We had the same error and the solution with replacing the `libraries/vendor/joomla/ldap/src/LdapClient.php` with the [new version](#issuecomment-330627103) solved the issue for us!

**Comment by gojets** [comment] 2017-09-27 17:33
Thanks mbabker! The fix works for me.

**Comment by OlofBailey** [comment] 2019-04-16 18:31
Getting the same error in 3.9.5

**Comment by mbabker** [comment] 2019-04-16 18:55
@OlofBailey Please don't randomly find 18 month old issues and comment "getting same error on new release".  You can't be having the same error as this issue identified as this was an issue of a file not being correctly updated with the 3.8.0 release.  If you believe you have found a bug with the new release, the proper action is to file a new issue report with all required details needed to either replicate the issue or explain why it is not a bug in the core package.
