### ISSUE TITLE
email cloaking kills email value of input field

### ISSUE THREAD

**Issue by Bloggerschmidt** [joomla/joomla-cms#5080] opened 2014-11-10 12:05 UTC
#### Steps to reproduce the issue

The plugin kills the email value of an input field, when ohter inputs of the form don't validate.

```<input value="" size="20" name="form[EMail]" id="EMail" class="rsform-input-box" type="text">```

#### Expected result

```<input value="mail@example.com" size="20" name="form[EMail]" id="EMail" class="rsform-input-box" type="text">```

#### Actual result

```<input value="<span id=" cloak45076"="" type="text">```

#### System information (as much as possible)

Joomla 3.3.6
E-Mail Cloaking enabled

**Comment by spignataro** [comment] 2015-07-19 19:12
For your content pages you can run the following to disable the email cloaking: {emailcloak=off}<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5080">issues.joomla.org/joomla-cms/5080</a>.</sub>

**Comment by roland-d** [comment] 2015-09-05 16:16
Hello @Bloggerschmidt, 

Thank you for your contribution.

The last comment here was on 20 July 2015. So the question is, Is this issue/pull request still valid?
If no reply is received within 4 weeks we will close this issue.

In case the issue still exists, can you please provide clearer step-by-step instructions.

Thanks for understanding! <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5080">issues.joomla.org/joomla-cms/5080</a>.</sub>

**Comment by spignataro** [comment] 2015-09-06 19:28
The issue is still valid. I am not a regular expression person to solve this. It needs to check to see if the email is within a input field as a value.

**Comment by dgt41** [comment] 2015-09-06 19:59
> It needs to check to see if the email is within a input field as a value.

@spignataro this doesn’t sound quite correct, cloaking is supposed to check in the content area.
Input fields are not quite used there and should be part of a form. Also input fields use the javascript validation and the server side validation for an email input. I would say that this is a very odd use case.

**Comment by spignataro** [comment] 2015-09-08 14:45
I would have to disagree. I have many clients whom put in forms on their content pages. I have stopped putting in anything in the value field because of this bug. It just needs to check to see if the value has a email address and if it does just skip over the cloaking.

**Comment by roland-d** [comment] 2015-09-13 23:12
@spignataro As this isssue has no code attached, can you provide a way to reproduce this issue, we can then look at adding the needed code.

**Comment by spignataro** [comment] 2015-09-14 00:06
Put in code into the input area:

<input value="mail@example.com" size="20" name="form[EMail]" id="EMail" class="rsform-input-box" type="text">

with the plugin turned on take a look at the marketup.

**Comment by zero-24** [comment] 2015-10-09 13:14
here is a PR for that issue: #8039

**Closed by zero-24** 2015-10-09 13:14 UTC
Labels: No Code Attached Yet
