### ISSUE TITLE
Migration from 2.5.28 to 3.6 returns Fatal errors

### ISSUE THREAD

**Issue by stellainformatica** [joomla/joomla-cms#11117] opened 2016-07-14 12:01 UTC
#### Steps to reproduce the issue
Migrate a fresh install of Joomla 2.5.28 to 3.6.0 by the Joomla Update component.

#### Expected result
Joomla 3.6.0 administration working fine

#### Actual result
Joomla 3.6.0 administration not working, appears just a blank page with 
Notice: Undefined property: LoginController::$input in ...administrator\components\com_login\controller.php on line 36
Fatal error: Call to a member function set() on null in ...administrator\components\com_login\controller.php on line 36

#### System information (as much as possible)
A fresh install of 2.5.28

**Comment by AlexRed** [comment] 2016-07-14 12:14
I can confirm the problem.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11117">issues.joomla.org/joomla-cms/11117</a>.</sub>

**Comment by gpenglase** [comment] 2016-07-16 13:38
Experiencing same problems as well<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11117">issues.joomla.org/joomla-cms/11117</a>.</sub>

**Comment by zero-24** [comment] 2016-07-16 15:15
Please make sure all files get replaced by the update. So get a fresh copy of 3.6.0 stable and extract. Remove the installation folder and override all files with the downloaded one. Please keep in mind that all core hacks gets reverted this way. Thanks.

**Comment by AlexRed** [comment] 2016-07-16 21:03
Hello zero-24, same error also after extract fresh copy of 3.6.0 and remove the installation.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11117">issues.joomla.org/joomla-cms/11117</a>.</sub>

**Comment by zero-24** [comment] 2016-07-16 21:29
@alexred Please double check that there is no issue with uploading the files to the server.

Than please double check that this file is the same on your server: https://github.com/joomla/joomla-cms/blob/staging/libraries/legacy/controller/legacy.php

**Comment by AlexRed** [comment] 2016-07-17 06:51
I test it in my local server, in a fresh new 2.5.28. No problem to copy file. But in your test is ok the update from Joomla 2.5.28 to 3.6.0 ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11117">issues.joomla.org/joomla-cms/11117</a>.</sub>

**Comment by gpenglase** [comment] 2016-07-18 07:28
I had already tried a entirely fresh copy of 3.6.0 before submitting my entry - same deal. I would surmise it has more to do with an incorrect entry in the database.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11117">issues.joomla.org/joomla-cms/11117</a>.</sub>

**Comment by csthomas** [comment] 2016-07-18 07:58
My guess:
It may be that some old file from 2.5 (or 1.5) is loaded instead of a new from Joomla 3.6.
Joomla auto loading try to find some lib file in incorrect directory.
After you delete old file from libraries,  joomla should start working again.
You may try to find some old file in libraries/joomla folder that exists but should not.  
Can you compare new Joomla 3.6 extracted from zip with your copy?

**Comment by csthomas** [comment] 2016-07-18 08:13
For example delete if exists /libraries/cms/controller/legacy.php

**Comment by infograf768** [comment] 2016-07-18 09:12
I confirm the issue
Although these files are present in script.php, they are not deleted.
Once these 3 files are deleted, one can login without errors.

**Comment by infograf768** [comment] 2016-07-18 09:50
@mbabker
What you think?

**Comment by csthomas** [comment] 2016-07-18 09:51
I suppose that the problem also exists in 3.5.1 because I fixed it manually a few month ago.

**Comment by zero-24** [comment] 2016-07-18 12:06
Ok. I have reproduced the problem. please see: https://github.com/joomla/joomla-cms/issues/11117#issuecomment-233253886

**Comment by gpenglase** [comment] 2016-07-18 13:36
Thanks for the help so far

Deleted the three legacy files, which then allowed me to login successfully.
Updated NoNumber Sourcerer (the only 3rd party plugin)

General 3.6 update (from 3.4.8)
Notices another issue with this (and other 3.6 installs i've done):
Sometime the intall the "Install from Web" plugin button doesn't work (or other install plugins), so have to discover the plugin(s).
When installed it doesn't show (even though it's enabled) so I have disab;e and then re-enable install plugins to activate them.
this also occured with this update from 2.5.28

Additionally, with this install (from 2.5.28) while I seem to be able to access every other page, I now cannot access Global Config.
So... trying http://wisereaction.org/administrator/index.php?option=com_config
I get:


Fatal error: Call to undefined method JStringNormalise::fromCamelCase() in /home/wiseract/public_html/components/com_config/view/cms/html.php on line 210

Permissions were 444 I changed to 777 for this test with no luck.
Of course, I can edit the configuration file directly but thought you might like to know.

Also, this 2.5.28 to 3.6 threw up database errors. The database requires the following fixes:

	•	Table 'jos_session' does not have column 'session_id' with type varchar(200);. (From file 1.7.1-2011-09-15.sql.)
	•	Table 'jos_redirect_links' does not have column 'old_url' with type varchar(255);. (From file 1.7.1-2011-09-20.sql.)
	•	Table 'jos_redirect_links' does not have column 'new_url' with type varchar(255);. (From file 1.7.1-2011-09-20.sql.)
	•	Table 'jos_banners' does not have column 'alias' with type VARCHAR(255). (From file 1.7.3-2011-10-15.sql.)
	•	Table 'jos_categories' does not have column 'alias' with type VARCHAR(255). (From file 1.7.3-2011-10-15.sql.)
	•	Table 'jos_contact_details' does not have column 'alias' with type VARCHAR(255). (From file 1.7.3-2011-10-15.sql.)
	•	Table 'jos_content' does not have column 'alias' with type VARCHAR(255). (From file 1.7.3-2011-10-15.sql.)
	•	Table 'jos_content' does not have column 'title_alias' with type VARCHAR(255). (From file 1.7.3-2011-10-15.sql.)
	•	Table 'jos_menu' does not have column 'alias' with type VARCHAR(255). (From file 1.7.3-2011-10-15.sql.)
	•	Table 'jos_newsfeeds' does not have column 'alias' with type VARCHAR(255). (From file 1.7.3-2011-10-15.sql.)
	•	Table 'jos_content' does not have column 'alias' with type VARCHAR(255). (From file 1.7.3-2011-11-10.sql.)
	•	Table 'jos_newsfeeds' does not have column 'alias' with type VARCHAR(255). (From file 1.7.4-2011-11-23.sql.)
	•	Table 'jos_content' does not have column 'alias' with type VARCHAR(255). (From file 1.7.4-2011-11-23.sql.)
	•	Table 'jos_content' does not have column 'title_alias' with type VARCHAR(255). (From file 1.7.4-2011-11-23.sql.)


On clicking the "Fix" button I get a problem with the first one:
Table 'jos_session' does not have column 'session_id' with type varchar(200);. (From file 1.7.1-2011-09-15.sql.)
from which I get the error:
Specified key was too long; max key length is 767 bytes SQL=ALTER TABLE `#__session` MODIFY `session_id` varchar(200); 
only way I could fix this was to changed collation from multilingual ( utf8mb4_unicode_ci to utf8_unicode_ci )

Next one:
Table 'jos_content' does not have column 'title_alias' with type VARCHAR(255). (From file 1.7.3-2011-10-15.sql.)
then throws up an error:
Unknown column 'title_alias' in '#__content' SQL=ALTER TABLE `#__content` CHANGE `title_alias` `title_alias` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT ''; 

Unless you have some bright ideas with this, I'll manually work through these...
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11117">issues.joomla.org/joomla-cms/11117</a>.</sub>

**Comment by gpenglase** [comment] 2016-07-22 04:54
So it seems the rest of the problems associated with upgrading from 2.5.28 to 3.6.0 such as database update errors, subsequent inability to save changes to articles, are related to a multilingual install.

**Comment by zero-24** [comment] 2016-07-23 17:47
please test #11282

**Comment by brianteeman** [comment] 2016-07-24 05:26
Closed as we have a PR for testing

**Closed by brianteeman** 2016-07-24 05:26 UTC
Labels: No Code Attached Yet
