### ISSUE TITLE
Confusing setting Articles to List in menu item List All Categories

### ISSUE THREAD

**Issue by bertmert** [joomla/joomla-cms#7924] opened 2015-09-21 09:26 UTC
Page Pagination display in blog layout of subcategories is dependent on a setting in tabulator "List Layouts" (and a bit confusing at all if you don't know it).

Test:
- Create a main category (level 1) + one subcatecory (level 2)
To go shure check in subcategory: Tab Options >  Alternative Layout > Use Global (or Blog if you have other setting in global options).

- Create/move/copy 11 or more articles in/to subcatecory. *Subcategory must not have an own menu item!*
- Create menu item "List All Categories" pointing to main category.
- Go to tab "Blog Layout"
Set options:
- Leading Articles: 1
- Intro Articles: 1
- Columns: 2
- Links: 1
- Go to tab "List Layouts"
Set option:
- Articles to List: ALL

- Save. Open menu item in frontend. Click subcategory link. You'll see a blog layout (but not all articles. Just 3.).
- Without page pagination!

- Go back to menu item in backend.
- Go to tab "List Layouts"
Set option:
- Articles to List: 5

- Now there's a page pagination in frontend blog (with 3 articles but not 5).

EDIT-> Looks like there are some deeper dependicies that fail. Depends on the combination of "Articles to List" and values in Tab "Blog Layout" if you see pagination or not.

**Comment by bertmert** [comment] 2015-09-21 11:48
OK, I think this is a known "problem" since ever with blogs under List All Categories. We don't have a line
```
<field name="layout_type" type="hidden" default="blog" />
```
or similiar in default.xml of this view. So the blog is handled like a list at some places in code. An additional switch "Handle as Blog: Y|N" would be too much

There's an option "Choose a Layout" (category_layout) in global settings but I don't know how to get "layout_type" from XML file of this selected layout in cateory model.

** Please feel free to close this issue if you think "Who cares?" ;-) **

**Comment by pe7er** [comment] 2016-05-08 11:41
Thank you for reporting this issue. 
However, I am not able to reproduce it on basis of your description: In Menus > mainmenu > create new menu > type: Category Blog,
I can set the "Blog Layout" but there's no tab for "List Layouts" (I can only find that in Content > Categories [Options]).

Your issue and your code suggestion seems valid, but because no one else has reported this behavior, or shown any interest in providing any code to correct it, I am closing this issue at this time. If code is provided (a pull request) it can always be re-examined. 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7924">issues.joomla.org/joomla-cms/7924</a>.</sub>

**Comment by zero-24** [comment] 2016-05-08 11:43
Set to "closed" on behalf of @zero-24 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7924">issues.joomla.org/joomla-cms/7924</a>

**Comment by zero-24** [comment] 2016-05-08 11:43
Closing to the reasons above by @pe7er <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7924">issues.joomla.org/joomla-cms/7924</a>.</sub>

**Closed by zero-24** 2016-05-08 11:43 UTC
Labels: No Code Attached Yet
