### ISSUE TITLE
[4.0 RC2] When I activate the cache, I lose several modules

### ISSUE THREAD

**Issue by Magnytu2** [joomla/joomla-cms#34568] opened 2021-06-19 12:25 UTC
### Steps to reproduce the problem
Create a site with Joomla 4RC2 with Cassiopeia. Activate the system cache.

### Expected result
No change in Frontend

### Current result
The menus and several modules disappear. Sometimes just the borders of the modules disappear. This is the case for modules in bottom position a or b. https://joomla-4.fr
![Capture 073 - Accueil - joomla-4 fr](https://user-images.githubusercontent.com/26197929/122642312-21178600-d10a-11eb-8906-b0b830f8fcf3.jpg)

### System information (as much as possible)
Joomla 4 RC2 Php 7.4.2

**Comment by particthistle** [comment] 2021-07-15 00:12
Just encountered similar issue with an install, testing with builds through to J4 RC5-Dev 14 July 2020. Site is PHP 7.4.19 on cpanel.

With cache off, menu modules and other modules behave normally.

With cache on (progressive or conservative) you may get the pages on the site to load with the menus a few times, but then when you return to a page, you get a stripped down page without various modules.

In my case, the modules that disappear are the main menu (Cassiopeia > menu position) and the footer menu (Cassiopeia > footer position).

Setting the menu modules individually to "No caching" appears to restore the functionality, but in most cases menus would be content that should be able to be cached as they're typically not dynamically generated.

Turning on Debug, I noticed that when the problem is occurring, queries drop from 27 to 8, with bulk of them being the queries loading the module and then the menu.

With Cache off:
![image](https://user-images.githubusercontent.com/5515866/125708022-29f721cc-efe2-4705-954e-ea49d709555e.png)

With Cache on:
![image](https://user-images.githubusercontent.com/5515866/125708044-303afd21-a435-432d-b605-2e4f4ede3c45.png)

**Comment by richard67** [comment] 2021-08-17 14:35
See also #35180 .

@Magnytu2 Can you still reproduce the issue? If so, check my post at the end of issue #35180 . I don't really think it helps, but I'm not sure, so it is worth trying.

**Comment by Magnytu2** [comment] 2021-08-17 14:41
I still have the problem. If I activate progressive cache, the menu disappears.
My site and now under Joomla! 4.0 today, with the same dysfunction. See here> https://joomla-4.fr

**Comment by richard67** [comment] 2021-08-17 14:46
@Magnytu2 Then check if my comment here helps: https://github.com/joomla/joomla-cms/issues/35180#issuecomment-900342927

**Comment by Magnytu2** [comment] 2021-08-17 14:54
The problem is the same after removing the requested rows.

**Comment by richard67** [comment] 2021-08-22 10:58
Closing as having a pull request. Please test #35225 . Thanks in advance.

**Closed as completed by richard67** 2021-08-22 10:58 UTC
Labels: No Code Attached Yet
