### ISSUE TITLE
Unable to enable HTTPS on Server

### ISSUE THREAD

**Issue by suklamc** [joomla/joomla-cms#11780] opened 2016-08-25 06:33 UTC
### Steps to reproduce the issue

In Joomla 3.6.2 unable to enable HTTPS in Global Configuration

### Expected result

Message
Configuration successfully saved.

### Actual result

Warning
HTTPS has not been enabled as it is not available on this server.

### System information (as much as possible)

Setting	Value
 
PHP Built On	Linux sgx.HIDDEN.in 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64
Database Version	5.5.50-0ubuntu0.14.04.1
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	5.5.9-1ubuntu4.19
Web Server	Apache/2.4.7
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 3.6.2 Stable [ Noether ] 4-August-2016 23:41 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2838.0 Safari/537.36

=====
Setting	Value
 
Safe Mode	Off
Open basedir	None
Display Errors	Off
Short Open Tags	Off
File Uploads	On
Magic Quotes	Off
Register Globals	Off
Output Buffering	On
Session Save Path	/home/magadi/tmp
Session Auto Start	0
XML Enabled	Yes
Zlib Enabled	Yes
Native ZIP Enabled	Yes
Disabled Functions	pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,
Multibyte String (mbstring) Enabled	Yes
Iconv Available	Yes
Mcrypt Enabled	No
Maximum Input Variables	1000

=====

![screen shot 2016-08-25 at 01 32 32](https://issues.joomla.org/uploads/1/426bdb5bad802e0de8914319bf0ecfd0.png)

### Additional comments

The Server uses Certificates from Lets Encrypt (Automatically handled in Webmin/VirtualMin)

**Comment by andrepereiradasilva** [comment] 2016-08-25 09:30
hi. can't reproduce with the information you give.

please add this two lines of code

```php
unset($response->body);
$app->enqueueMessage(nl2br(print_r($response, true)), 'notice');
```
In this line https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_config/model/application.php#L141

Then choosee "Administrator Only" or "Entire site".
You will get a notice after saving with some debug info.

Example:
![image](https://cloud.githubusercontent.com/assets/9630530/17963752/ed8d5984-6aae-11e6-8823-51a12740dacf.png)

**Comment by suklamc** [comment] 2016-08-25 11:08
This is what i got ... 

Notice

JHttpResponse Object
(
[code] => 400
[headers] => Array
(
[Date] => Thu, 25 Aug 2016 11:08:24 GMT
[Server] => Apache/2.4.7
[Content-Length] => 226
[Connection] => close
[Content-Type] => text/html; charset=iso-8859-1
)

)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11780">issues.joomla.org/joomla-cms/11780</a>.</sub>

**Comment by suklamc** [comment] 2016-08-25 11:15
I see Issue Number #11785  is also for the same thing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11780">issues.joomla.org/joomla-cms/11780</a>.</sub>

**Comment by andrepereiradasilva** [comment] 2016-08-25 11:18
is not the same thing:

> 400 Bad Request
> The request could not be understood by the server due to malformed syntax. The client SHOULD NOT repeat the request without modifications.

See https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

**Comment by brianteeman** [comment] 2016-08-25 16:05
Reset priority according to our standards<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11780">issues.joomla.org/joomla-cms/11780</a>.</sub>

**Comment by andrepereiradasilva** [comment] 2016-08-25 17:28
A HTTP 400 status code seems to be server config issue

**Comment by brianteeman** [comment] 2016-08-27 09:04
I am closing this issue. It is a server issue and Joomla is correctly telling you that. Nothing we can can do<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11780">issues.joomla.org/joomla-cms/11780</a>.</sub>

**Closed** 2016-08-27 09:04 UTC
Labels: No Code Attached Yet
