### ISSUE TITLE
4.1.3 RC 1 - Warning: Undefined property: Joomla\CMS\Object\CMSObject::$inheritable

### ISSUE THREAD

**Issue by Stevec4** [joomla/joomla-cms#37733] opened 2022-05-03 15:04 UTC
### Steps to reproduce the issue
Installed 4.13.RC1 over a 4.1.2 Install, received a notice of 3 overrides to check. When selecting my template I receive the following warning

### Expected result
No Warning

### Actual result
Warning: Undefined property: Joomla\CMS\Object\CMSObject::$inheritable \\administrator\components\com_templates\src\Model\TemplateModel.php on line 2221

### System information (as much as possible)
PHP 8.0.13
Database Version | 10.4.22-MariaDB
utf8mb4_general_ci
Frontend Template - Yo0theme
XAMMP

**Comment by Stevec4** [comment] 2022-05-03 15:13
I changed the line of code to, and the error is removed.
`if (!isset($template->xmldata->inheritable))`

**Comment by chmst** [comment] 2022-05-03 15:28
Is this new? Not in 4.1.2?

**Comment by brianteeman** [comment] 2022-05-03 15:40
Installed over, how?
Or did you mean upgraded

**Comment by richard67** [comment] 2022-05-03 16:48
I think the problem is that the Yotheme template doesn't provide the inheritable property in the template details XML file, like Cassiopeia has it here: https://docs.google.com/spreadsheets/d/1VY77oqekLMzKExyqlJ3q_H692bRl3ik8_-0J8aP0ZV0/edit#gid=0

To handle this, [line 2221 of the template model](https://github.com/joomla/joomla-cms/blob/4.1-dev/administrator/components/com_templates/src/Model/TemplateModel.php#L2221) should indeed be changed like @Stevec4 suggested above.

@dgrammatiko Do you agree? Or do we **_require_** the inheritable property in the template details XML files in 4.1?

@Stevec4 Do you want to make a pull request? Testing instructions would be more or less the same as here: #36250 .

**Comment by dgrammatiko** [comment] 2022-05-03 16:57
> @dgrammatiko Do you agree? Or do we require the inheritable property in the template details XML files in 4.1?

This is weird as the installer should always inject the inheritable and parent at the installation process: https://github.com/joomla/joomla-cms/blob/279c2403f06ae25f4d937f735f02d2616bd26a15/libraries/src/Installer/Adapter/TemplateAdapter.php#L342-L343 

And when we did the upgrade from 4.0.x to 4.1 we also injected the values (not inheritable no parent) to all templates, iirc. So this is weird...

**Comment by Stevec4** [comment] 2022-05-03 17:02
To clarify:
It was an upgrade using the full RC1 zip file from github, not via Joomla update, 
This warning was not present in my Joomla 4.1.2

Steve

**Comment by dgrammatiko** [comment] 2022-05-03 17:05
@Stevec4 actually your solution is fine, the code as written right now expects that the `inheritable` attribute exists in the XML, which is falsy for legacy templates. Maybe `if (!isset($template->xmldata->inheritable) || !$template->xmldata->inheritable)` to get the falsy part for templates with an `inheritable` attribute with a `0` value

**Comment by richard67** [comment] 2022-05-03 18:03
@dgrammatiko `if (!isset($template->xmldata->inheritable) || !$template->xmldata->inheritable)` ... wouldn't that just be easier with `if (empty($template->xmldata->inheritable))`?

**Comment by dgrammatiko** [comment] 2022-05-03 18:06
@richard67 that would work as well

**Comment by Stevec4** [comment] 2022-05-03 21:37
@richard67 I have never done a PR but I am happy to if you like. I tried both changes the one Dimitris suggested and yours above and both solve the issue.

Steve

**Comment by richard67** [comment] 2022-05-03 22:01
> @richard67 I have never done a PR but I am happy to if you like.

@Stevec4 Go for it. If you struggle with Git or GitHub we can advise.

**Comment by richard67** [comment] 2022-05-04 13:36
@Stevec4 Or did I get you wrong and I shall make the PR?

**Comment by Stevec4** [comment] 2022-05-04 13:48
I will give it a go now @Richard67

**Comment by Stevec4** [comment] 2022-05-04 14:59
@richard67 feel free correct the PR if I have messed it up.

**Comment by richard67** [comment] 2022-05-04 15:00
Closing as having a pull request. See #37739 .

**Closed as completed by richard67** 2022-05-04 15:00 UTC
Labels: No Code Attached Yet
