### ISSUE TITLE
Since 3.7, new categories are directly created in trash

### ISSUE THREAD

**Issue by Engelmann** [joomla/joomla-cms#15795] opened 2017-05-03 14:23 UTC
Since the 3.7 update, when I'm adding a new category it appears in the trash and no way to publish it again. Older categories aren't affected and have a normal behaviour.

PHP Version : 7.0.15
MySQL Version : 5.5.54-0+deb7u1-log
Server Information : Linux
Fix jQuery? : Yes
Load JEvents Bootstrap CSS? : Yes
Joomla : 3.7.0
component_com_jevents : 3.4.36
component_com_jevlocations : 3.4.15
component_com_jevpeople : 3.0.37
component_com_rsvppro : 3.4.17
component_com_jce : 2.6.12
component_com_comprofiler : 2.1.2
component_com_acymailing : 5.7.0
module_mod_acymailing : 3.7.0
module_mod_jevents_cal : 3.4.36
module_mod_jevents_calendarplus : 3.3.4
module_mod_jevents_custom : 3.4.36
module_mod_jevents_filter : 3.4.36
module_mod_jevents_latest : 3.4.36
module_mod_jevents_legend : 3.4.36
module_mod_jevents_switchview : 3.4.36
module_mod_jevlocations : 3.4.15
layout_JEventsFlatplusLayout : 3.4.9
layout_JEventsIconicLayout : 3.5.6
layout_JEventsMapLayout : 3.4.1
layout_JEventsRuthinLayout : 3.4.6
layout_extplus : 3.2.4
layout_float : 3.4.0
layout_smartphone : 3.4.0
plugin_acymailing_contentplugin : 3.7.0 (not enabled)
plugin_acymailing_managetext : 1.0.0
plugin_acymailing_online : 3.7.0
plugin_acymailing_share : 1.0.0
plugin_acymailing_stats : 3.7.0
plugin_acymailing_tablecontents : 1.0.0
plugin_acymailing_tagcontent : 3.7.0
plugin_acymailing_tagsubscriber : 5.7.0
plugin_acymailing_tagsubscription : 5.7.0
plugin_acymailing_tagtime : 5.7.0
plugin_acymailing_taguser : 5.7.0
plugin_acymailing_template : 5.7.0
plugin_content_jevents : 3.4.36
plugin_editors_acyeditor : 5.7.0
plugin_finder_jevents : 3.4.36
plugin_jevents_jevlocations : 3.4.15
plugin_jevents_jevpeople : 3.0.37
plugin_jevents_jevrsvppro : 3.4.17
plugin_jevents_jevusers : 3.4.2
plugin_search_eventsearch : 3.4.36
plugin_search_jevlocsearch : 3.4.15
plugin_system_gwejson : 3.4.36
plugin_system_hika_rsvp_redirect : 3.4.17 (not enabled)

**Comment by Bakual** [comment] 2017-05-03 14:25
Can't reproduce that.

**Comment by PhilETaylor** [comment] 2017-05-03 14:26
If the last filter state you used is trash - then new items will default to trash unless you change the state before saving... (@brianteeman told me I was silly when I said that users would do this haha)

**Comment by Bakual** [comment] 2017-05-03 14:28
But that wouldn't prevent him from publishing the category again.

**Comment by PhilETaylor** [comment] 2017-05-03 14:30
That is correct - you should be able to re-edit it, and change its state to published/unpublished

**Comment by Engelmann** [comment] 2017-05-03 14:37
Thanks.
During creation of the new category, status is: published.
The status in the database for the publish field is -2. If I correct it in the database to 1 (published) it is appearing again.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15795">issues.joomla.org/tracker/joomla-cms/15795</a>.</sub>

**Comment by PhilETaylor** [comment] 2017-05-03 14:59
I have tested exhaustively and I cannot replicate this - I always get 1 = published in my database

**Comment by Bakual** [comment] 2017-05-03 15:07
Try disabling non-core plugins and see if that solves it.

I'm closing this issue as it doesn't look like it is a core one. If you need help solving your issue, please use the forum.joomla.org for further support.

**Closed by Bakual** 2017-05-03 15:07 UTC
Labels: No Code Attached Yet

**Comment by Engelmann** [comment] 2017-05-03 15:12
OK, thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15795">issues.joomla.org/tracker/joomla-cms/15795</a>.</sub>
