### ISSUE TITLE
[4.0] Table Search - Clear

### ISSUE THREAD

**Issue by DrDreave** [joomla/joomla-cms#17800] opened 2017-08-31 13:59 UTC
### Steps to reproduce the issue

* Open an admin table view (i.e. Content > Articles)
* Enter a search string in the search input
* Start the search
* Click the 'Clear' button

### Expected result

The search input gets cleared.

### Actual result

The input doesn't get cleared.

### System information (as much as possible)
* **PHP Version:** 7.1.6
* **Joomla! Version:** Joomla! 4.0.0-dev
* **Browser:** 60.0.3112.113

### Additional comments
Clicking the clear button throws a JS exception:
```
searchtools.min.js?5db449f2a258ef8a1cac138587e3af6d:1 Uncaught TypeError: Cannot read property 'value' of null
    at t.checkFilter (searchtools.min.js?5db449f2a258ef8a1cac138587e3af6d:1)
    at searchtools.min.js?5db449f2a258ef8a1cac138587e3af6d:1
    at Array.forEach (<anonymous>)
    at t.clear (searchtools.min.js?5db449f2a258ef8a1cac138587e3af6d:1)
    at HTMLButtonElement.<anonymous> (searchtools.min.js?5db449f2a258ef8a1cac138587e3af6d:1)
```

**Comment by brianteeman** [comment] 2017-08-31 14:11
Duplicate of #17195

**Closed as completed by brianteeman** 2017-08-31 14:11 UTC
Labels: No Code Attached Yet
