### ISSUE TITLE
[3.7 RC3] Tool tips not visble

### ISSUE THREAD

**Issue by yasirunilan** [joomla/joomla-cms#15387] opened 2017-04-18 16:15 UTC
### Steps to reproduce the issue
From the main menu go to Content-> Articles
Click on one of the articles. Go to the "Publishing" tab. Go and click on the input field named as Created by. A modal opens. Hover over the table names. 

### Expected result
Tool tips should be completely visible

### Actual result
Tool tips are partially visible.
![17965408_1344850785572050_2074236180_n](https://cloud.githubusercontent.com/assets/9814784/25141172/5678a4e0-2480-11e7-9555-305074cf7926.jpg)

### System information (as much as possible)
Joomla! 3.7 RC 3
Windows 10
Chrome 57.0.2987.110 (64-bit)
PHP 5.6

**Comment by C-Lodder** [comment] 2017-04-18 16:25
Wasn't this issue posted for Joomla 3.x too? Can't remember

**Comment by zero-24** [comment] 2017-04-18 16:26
This is a issue for 3.x @C-Lodder or what exactly do you mean?

**Comment by C-Lodder** [comment] 2017-04-18 16:27
Oops, my bad. I think this issue has already been posted somewhere.

**Comment by yasirunilan** [comment] 2017-04-18 16:31
I posted the same issue for 4.0 as well

**Comment by Quy** [comment] 2017-04-18 16:43
Duplicate #15028

**Comment by mbabker** [comment] 2017-04-18 16:44
In this case it's not a duplicate since it's basically two different templates and two different CSS frameworks.

**Comment by Quy** [comment] 2017-04-18 16:52
It is a duplicate based on the title for v3.7.

**Comment by brianteeman** [comment] 2017-05-19 22:01
I am closing this as i have confirmed it is a duplicate of #15028

**Closed by brianteeman** 2017-05-19 22:01 UTC
Labels: No Code Attached Yet
