### ISSUE TITLE
User Action Logs, since 3.9.24, have been sending untranslated macros.

### ISSUE THREAD

**Issue by erenfro** [joomla/joomla-cms#32158] opened 2021-01-25 17:11 UTC
### Steps to reproduce the issue

Enable User Action Logs.
Write Article or modify a user, or anything that triggers a UAL event.

### Expected result

Macros for subject and field headers in email are translated from macro to expected language, not left as-is.

### Actual result

COM_ACTIONLOGS_EMAIL_SUBJECT

COM_ACTIONLOGS_ACTION | COM_ACTIONLOGS_DATE | COM_ACTIONLOGS_EXTENSION | COM_ACTIONLOGS_NAME | COM_ACTIONLOGS_IP_ADDRESS
-- | -- | -- | -- | --
User psi-jack updated the user Psi-Jack | 2021-01-25 17:02:16 UTC | Users | Psi-Jack | IP Address

### System information (as much as possible)

Ubuntu 20.04 up-to-date
MariaDB 10.3.25
PHP 7.4
Joomla 3.9.24
Joomla configured to use SMTP to localhost for mail delivery instead of PHP Mail.

### Additional comments

This literally just started happening after the recent Joomla core updates, so I suspect strongly something in that broke the macro translations in the UAL component somewhere.

**Comment by toivo** [comment] 2021-01-26 08:56
@erenfro - confirmed the behaviour after update to 3.9.24.  An out-of-the-box Joomla 3.9.24 does not have this issue.

As a temporary workaround, download the update package Joomla_3.9.24-Stable-Full_Package.zip, go to Joomla! Update - Upload & Update and run the update, which fixes the problem.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32158">issues.joomla.org/tracker/joomla-cms/32158</a>.</sub>

**Comment by richard67** [comment] 2021-01-26 10:21
> As a temporary workaround, download the update package Joomla_3.9.24-Stable-Full_Package.zip, go to Joomla! Update - Upload & Update and run the update, which fixes the problem.

The "Joomla_3.9.24-Stable-Full_Package.zip" is not an update package, it's the installation package for new installations.

**Comment by toivo** [comment] 2021-01-26 10:39
@richard67 - true, but it works as a temporary workaround.  I verified the issue in my remote 3.9.24 website.  Previously I had not checked Users - User Actions Log, and now it listed the language constants instead of the translated text. After the update was run in Upload & Update using the Full 3.9.24 package no language constants were displayed in the User Actions Log and the report was back to normal.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32158">issues.joomla.org/tracker/joomla-cms/32158</a>.</sub>

**Comment by richard67** [comment] 2021-01-26 10:41
@toivo Yes, it's a good workaround, I just wanted to point out the wrong description "update package" in the text to avoid misunderstanding. So beside this little wording thing, thanks for your help and many testing and advise here.

**Comment by toivo** [comment] 2021-01-26 15:58
@richard67 - cheers, my mistake, missed 'update'.  My 3.9.x localhost test site was updated to 3.9.24 and then almost immediately to 3.9.25-dev and the User Actions Log displays all the titles and messages correctly, no corrective update with the Full package done, only the daily 3.9.25-dev update packages applied.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32158">issues.joomla.org/tracker/joomla-cms/32158</a>.</sub>

**Comment by erenfro** [comment] 2021-01-26 15:59
@toivo 
I tried that, and yes, it did correct the standing problem. Thank you.

**Comment by sozzled** [comment] 2021-01-27 05:17
Just guessing:  there may be (or there may have been) a problem with the packaging of the update package.  There doesn't appear to be anything peculiar with **com_actionlogs** itself but rather with what happens (or happened) when updating from an older version of J! to J! 3.9.24.  The problem can be fixed by using the _Joomla! Update_ component and re-instal the J! core files.  That's all I can add to this discussion.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32158">issues.joomla.org/tracker/joomla-cms/32158</a>.</sub>

**Comment by rodlie** [comment] 2021-02-04 13:01
Not an issue when updating from .18/.21 to .24. Probably an issue with .23=>.24(?).

**Comment by sozzled** [comment] 2021-02-05 21:54
I'm sure I corrected the problem (by "re-installing" the J! core files), but I looked again today and all my websites show these untranslated language strings.  Haven't a clue what's happening.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32158">issues.joomla.org/tracker/joomla-cms/32158</a>.</sub>

**Comment by sozzled** [comment] 2021-02-05 21:58
Not sure why I can't edit my previous post here.  I can re-apply the "re-instal" and it fixes the non-translation issue, but I'm wondering why it didn't work the first time around?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32158">issues.joomla.org/tracker/joomla-cms/32158</a>.</sub>

**Comment by chmst** [comment] 2021-02-05 22:16
Thank you for this information. I really don't know why this happened - I only can think on a error while writing the language files. As nobody else had this issue, could you close it? If necessary, we can re-open.

**Comment by sozzled** [comment] 2021-02-05 22:22
I'm saying that, I "re-installed the J! core files" on most, if not all, my J! websites 10 days ago (and it corrected the problem) but when I look again today, the untranslated language strings re-appear again.  I checked with my webhosting provider and we haven't made any changes to the server environment (and I doubt this is a potential cause) so I'm just saying that the issue has mysteriously re-surfaced ... I don't have an explanation.

If it's true that "nobody else" has this issue, I would like to leave the matter open until, at least, J! 3.9.25 has been released.  Thanks.

UPDATE:  Scratch my comment about all J! websites having this problem.  I went through all of them again and it's only 70% of them (not all of them) so I'm putting this on the back-burner for the present.  One good thing that's happened, however, is that I was able to edit this post after I wrote it.  Don't know why (maybe something temporary with _GitHub_?

And, no, I can't close this issue because I didn't open it in the first place.

**Comment by chmst** [comment] 2021-02-05 23:06
No, I have no clue why github sometimes refuses editing. So we let it open and watch.

**Comment by sozzled** [comment] 2021-04-16 04:35
Looks like this problem was fixed (or fixed itself) with the release of J! 3.9.26.

**Comment by Quy** [comment] 2021-04-29 13:52
@sozzled Thanks for checking. Closing. If still an issue please comment in this issue.

**Closed as completed by Quy** 2021-04-29 13:52 UTC
Labels: No Code Attached Yet, Information Required

**Comment by JahangirPackages** [comment] 2024-06-02 08:27
**[Jahangir Packages](https://jahangirpackages.pk/)** provides cutting-edge packaging solutions with advanced technology, ensuring your products stand out with high-quality, durable packaging. Jahangir Packages offers custom packaging design services, ensuring each package is uniquely tailored to fit your brand and product specifications with creativity and precision.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32158">issues.joomla.org/tracker/joomla-cms/32158</a>.</sub>

**Comment by JahangirPackages** [comment] 2024-06-24 18:34
**[Jahangir Packages](https://jahangirpackages.pk/)**__ provides cutting-edge packaging solutions with advanced technology, ensuring your products stand out with high-quality, durable packaging. Jahangir Packages offers custom packaging design services, ensuring each package is uniquely tailored to fit your brand and product specifications with creativity and precision.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32158">issues.joomla.org/tracker/joomla-cms/32158</a>.</sub>
