### ISSUE TITLE
[4.0] Toolbar - Delete Button missing

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#28689] opened 2020-04-15 11:48 UTC
### Steps to reproduce the issue
The delete permanently button is missing in the toolbar. It's also not in the Actions dropdown.

![grafik](https://user-images.githubusercontent.com/828371/79333963-becc5f80-7f1f-11ea-86c9-30979c5837a9.png)

**Comment by brianteeman** [comment] 2020-04-15 11:56
It's the stupidly confusing workflows. You need to filter on condition and not on state. Said this from the beginning but no one listened

**Comment by brianteeman** [comment] 2020-04-15 12:08
![image](https://user-images.githubusercontent.com/1296369/79335629-3e573000-7f1a-11ea-9c7e-979d4292302a.png)

Closing as not a bug

**Closed as completed by brianteeman** 2020-04-15 12:08 UTC
Labels: No Code Attached Yet

**Comment by coolcat-creations** [comment] 2020-04-15 12:10
There are more UX issues than that. Thank you for the hint with the condition!

- When I select condition, the button appears but is not active, because in joomla "Empty Trash" means actually only "Delete selected items permanently". If we have a Empty trash button it should do what it says.

- Second issue I reported seperately is the order of the Filters. Ordering by condition must be the first in the order. I understand that the filters are ordered by the order of the table headings but the condition must be first. It's the probably most common filter and you don't want the user to have to search for it. If possible we could put the filters also in seperate Rows?

- Third issue is the one you mention here @brianteeman - we need to improve this, and we need to find out how to improve the communication at all. "Said this from the beginning but no one listened" I know this feeling very good. 

How can we solve A) this issue and B) where can we track UX issues better so they don't get lost as before?

**Comment by coolcat-creations** [comment] 2020-04-15 12:11
Sorry, can you reopen as it's not a bug but a UX issue? @brianteeman

**Comment by brianteeman** [comment] 2020-04-15 12:14
1. Please keep to referring to one thing in any issue report as it makes thing much easier to track and fix. Otherwise its a nightmare to manage

2. @bembelimen is supposed to be completely rewriting workflows so its all kind of a waste of time at the moment. Until he completes the rewrite we have no way of knowing what the UI will be etc etc

**Comment by coolcat-creations** [comment] 2020-04-15 12:23
Ok thank you!
