### ISSUE TITLE
[4.0b7] No loading of Workflows in Default mode

### ISSUE THREAD

**Issue by Magnytu2** [joomla/joomla-cms#32348] opened 2021-02-07 16:46 UTC
After installing the Blog demo and even having created my own Workflows, it is impossible to have the correct management of Workflows by default in the articles. I have verified that the categories do indeed use the default mode for Workflows.

![Erreur-Workflows](https://user-images.githubusercontent.com/26197929/107153163-4b8f5080-696c-11eb-88d6-51bdf45853ed.jpg)

**Comment by chmst** [comment] 2021-02-07 17:19
Sample data connect only the blog category to the blog workflow.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32348">issues.joomla.org/tracker/joomla-cms/32348</a>.</sub>

**Comment by richard67** [comment] 2021-02-07 19:03
Closing as expected behavior. We wanted to have both kinds of example in Blog Sample Data, some with and some without Workflow. That's why the Blog Category is connected to the Blog Workflow and the others are not.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32348">issues.joomla.org/tracker/joomla-cms/32348</a>.</sub>

**Comment by Magnytu2** [comment] 2021-02-07 19:39
@richard67 , sorry, but I created my own workflows, with my test articles. I have the correct workflows selected in the category, but I remain with the original workflows. This is what I wanted to point out by showing the blog example. Do you have an updated tutorial because what I find on Joomla.org is no longer up to date. The content-joomla plugin for example no longer has the management of notifications. Thank you.

https://docs.joomla.org/Publishing_Workflow/Scenarios/en

![Erreur-workflows2-2](https://user-images.githubusercontent.com/26197929/107157469-8ac99b80-6984-11eb-8c18-99acfb9284ed.jpg)

**Comment by richard67** [comment] 2021-02-07 19:48
Well as long as I don't know the names of stages and transitions of your workflow, I can't see in the screenshots if it's correct or not.

If your stages and transitions have the same name as the default ones, you won't see any difference in the dropdown.

@chmst @bembelimen Do you know if there is newer documentation than the one linked in the previous comment?

**Comment by Magnytu2** [comment] 2021-02-08 06:54
I made a copy of the original workflows, which I renamed "My workflow". I added a "display" transition. Then selected my default workflows. I have verified that my categories use the default workflows. But when I go back to reading the articles. There is only one workflow, the original one with the 7 transitions.

![etape-du-workflows](https://user-images.githubusercontent.com/26197929/107185523-ec205780-69e2-11eb-8878-add0070a37c4.jpg)

**Comment by bembelimen** [comment] 2021-02-11 08:55
Categories are not using workflows, they are just the transmitter for the initial state, nothing more.
If you want to change the workflow for an article, use the batch functionality.

So your "issue" is expected behaviour...

**Comment by richard67** [comment] 2021-02-11 09:07
Closing as expected behaviour. Explanation see previous comment. Feel free to re-open if you think this is wrong.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32348">issues.joomla.org/tracker/joomla-cms/32348</a>.</sub>

**Closed as completed by richard67** 2021-02-11 09:07 UTC
Labels: No Code Attached Yet

**Comment by Magnytu2** [comment] 2021-02-11 09:27
@richard67 @bembelimen Definitely I don't understand anything about the functioning of Workflows in this latest version.
In the article categories we can choose which Workflows to use. And we must find the list of transitions in the management of articles. I am wrong ?

![Capture d’écran 2021-02-11 à 10 25 13](https://user-images.githubusercontent.com/26197929/107619621-be8e1500-6c53-11eb-8f57-3bfd15ee4174.png)

**Comment by richard67** [comment] 2021-02-11 09:36
@Magnytu2  If you create a new article in that category, it should use that workflow defined for that category.

If you now change the workflow for a category, it will not change the workflow for all the articles already existing in that category, it will only change the workflow which will be used for newly created articles in that category from that moment on.

@bembelimen Correct me if the above is not right.

**Comment by Magnytu2** [comment] 2021-02-11 10:08
Ah yes, I just understood. And it works. But therefore we cannot change the flow of an article already created.
It's not easy to understand that way. It is expected that the change of workflows will be possible. There should be an alert, or an instruction to signal the functioning and the changes of workflows which are possible or not.

![Capture d’écran 2021-02-11 à 11 04 18](https://user-images.githubusercontent.com/26197929/107623366-825db300-6c59-11eb-9c3e-82d4b4873563.png)

**Comment by richard67** [comment] 2021-02-11 10:12
@Magnytu2 Anglais s'il vous plaît ;-)

And like Benjamin said, you can change it for existing articles with batch action.

**Comment by Magnytu2** [comment] 2021-02-11 10:13
oups

**Comment by bembelimen** [comment] 2021-02-11 10:29
> 
> 
> Ah yes, I just understood. And it works. But therefore we cannot change the flow of an article already created.
> It's not easy to understand that way. It is expected that the change of workflows will be possible. There should be an alert, or an instruction to signal the functioning and the changes of workflows which are possible or not.

You can, using the batch functionality as a Super User, because changing the workflow of an article is a serious thing and it needs in theory some kind of "migration" (otherwise it could be, that an already published article is not visible anymore or an article is stuck in a dead end). So we implemented the manual solution via the batch.

> @bembelimen Correct me if the above is not right.

It's 100% right.

**Comment by bembelimen** [comment] 2021-02-11 10:36
Btw. if you have some minutes to write your knowledge/findings about the workflow [into the documentation here](https://docs.joomla.org/J4.x:Workflow), it would be really helpful.

**Comment by Magnytu2** [comment] 2021-02-11 10:45
I know, and I think about it. But I am a handyman on Joomla! I'm just testing to understand. But the Workflows seem complex to me to explain. And for me, what is really great is being able to notify a group when a new article is published, without going through a newsletter and risking the newsletter to be spamming. But I can not ...
