### ISSUE TITLE
Debug console not working as expected?

### ISSUE THREAD

**Issue by Globulopolis** [joomla/joomla-cms#8362] opened 2015-11-09 17:44 UTC
After latest Joomla updates(starting from 3.4.3) debug console stop working to show explain and profile information for queries.
This is that I see in console
![clipboard01](https://cloud.githubusercontent.com/assets/740757/11041158/229b81f4-8721-11e5-8ebb-376ddbae195e.jpg)
No changes has been made on server from Joomla 3.4.3 to Joomla 3.4.5.

**Comment by brianteeman** [comment] 2015-11-11 13:51
I can confirm this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8362">issues.joomla.org/joomla-cms/8362</a>.</sub>

**Comment by infograf768** [comment] 2015-11-11 18:09
Tested by changing in staging current debug.php by the file released in 3.4.2, 3.4.3 and 3.4.4 and I confirm that it is broken since 3.4.4.

The PR concerned is
https://github.com/joomla/joomla-cms/pull/7279

**Comment by alikon** [comment] 2015-11-12 07:34
reverting #7279 works as expected

**Comment by infograf768** [comment] 2015-11-12 13:19
As far as I understood, we can't revert this as it can create issues for users implementing "register_shutdown_function()" callbacks in extensions.
Another solution is required.

**Comment by mbabker** [comment] 2015-11-12 15:13
The reason it worked before #7279 is because of the order of shutdown of the various objects.  The database driver's destructor would get called before the system plugin's destructor, and the database driver destructor calls a shutdown routine (usually `$this->disconnect()`).  In order to make the log data work again without reverting #7279 in the debug plugin you will need to call `$db->disconnect()` before starting to get all the data out of the driver.

Reverting #7279 will send an implicit message that Joomla does not offer 100% feature support for cases where someone registers a custom shutdown function via `register_shutdown_function()`.  Logic like rendering the debug console should not be placed in a class destructor for this reason.

**Comment by zero-24** [comment] 2015-11-12 18:34
Closing as we have a PR by @alikon. Thanks

**Closed by zero-24** 2015-11-12 18:34 UTC
Labels: No Code Attached Yet
