### ISSUE TITLE
J4.4 "Content - Email Cloaking" plugin runs out of memory and gets disabled

### ISSUE THREAD

**Issue by eddiekonczal** [joomla/joomla-cms#43124] opened 2024-03-22 19:34 UTC
### Steps to reproduce the issue

Enable the "Content - Email Cloaking" plugin

### Expected result

The "Content - Email Cloaking" plugin should remain enabled

### Actual result

On some websites, the "Content - Email Cloaking" plugin runs out of memory and becomes disabled.  These errors are seen in our logs:

> Jan 27 23:01:28 0 2024-01-27T23: 01:28.372429-05:00 lamp204 httpd.worker[1125427]: - httpd.worker: [warn] [client 43.133.56.97] mod_fcgid: stderr: PHP Fatal error: Out of memory (allocated 8388608) (tried to allocate 131072 bytes) in /mnt/data/vhosts/casite-1407156.cloudaccess.net/httpdocs/plugins/content/emailcloak/src/Extension/EmailCloak.php on line 455
> Jan 27 23:01:34 0 2024-01-27T23: 01:34.748011-05:00 lamp204 httpd.worker[1125430]: - httpd.worker: [warn] [client 43.133.56.97] mod_fcgid: stderr: PHP Fatal error: Out of memory (allocated 8388608) (tried to allocate 131072 bytes) in /mnt/data/vhosts/casite-1407156.cloudaccess.net/httpdocs/plugins/content/emailcloak/src/Extension/EmailCloak.php on line 455

### System information (as much as possible)

PHP Built On | Linux lamp204.cloudaccess.net 3.10.0-962.3.2.lve1.5.65.el6h.x86_64 #1 SMP Wed Jan 19 11:33:04 UTC 2022 x86_64
Database Type mysql 5.7.44-cll-lve 
Database Collation utf8mb4_general_ci
Database Connection Collation utf8mb4_general_ci
Database Connection Encryption None
Database Server Supports Connection Encryption Yes
PHP Version 8.1.27
Web Server Apache
WebServer to PHP Interface cgi-fcgi
Joomla! Version Joomla! 4.4.3 Stable [ Pamoja ] 20-February-2024 16:00 GMT

**Comment by brianteeman** [comment] 2024-03-22 20:00
the php put of memory error is probably the most unhelpful and confusing error message as it is usually not telling you what is causing the memory usage it is only telling you what was the last thing it fell over on.

**Comment by Hackwar** [comment] 2024-03-22 20:46
What do you mean with "disabled"? Do you mean the error messages or is the plugin actually somehow automatically set to unpublished?

In any case, your error message says that you only have 8MB of memory for your PHP process available and that is simply way to little. You will need maybe 64MB and I would say that commonly you would have that set to 256MB on a normal host. The problem is not the emailcloak plugin, but the hosting with way to little memory.

**Comment by eddiekonczal** [comment] 2024-03-22 20:50
The plugin actually gets automatically disabled.

**Comment by brianteeman** [comment] 2024-03-22 21:25
I cant see how a php memory issue can change a value in a mysql database

**Comment by Hackwar** [comment] 2024-03-22 21:36
Indeed, disabling the plugin is not a core feature of Joomla...

**Comment by richard67** [comment] 2024-03-28 09:38
> Indeed, disabling the plugin is not a core feature of Joomla...

@Hackwar Are you sure? This page tells that plugins are automatically disabled if they throw an error in their initialization: https://docs.joomla.org/Why_are_my_plugins_automatically_disabling

**Comment by Hackwar** [comment] 2024-03-28 09:43
Yes, I am sure, since that code is not in the PluginHelper and it was the code which was removed again in 1.5.18. Or in other words: This was introduced in 1.5.17 and removed in 1.5.18 again, since it was completely impractical.

**Comment by Hackwar** [comment] 2024-03-30 15:59
I've looked into this again and we definitely don't have a mechanism to disable plugins on failure. Since your original issue is pretty much entirely due to not enough memory on your host, I'm closing this issue.

**Closed as completed by Hackwar** 2024-03-30 15:59 UTC
Labels: No Code Attached Yet, Information Required, bug
