### ISSUE TITLE
[4.0] Uncaught TypeError in mobile view if article is open

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#34330] opened 2021-06-01 10:38 UTC
### Steps to reproduce the issue
The first click is at the three dots at the bottom of the screen:

![1](https://user-images.githubusercontent.com/78906980/120308305-4025b380-c2d4-11eb-825b-f7610a2f7022.gif)

### Expected result
Click on link open frontend.

### Actual result
Click on link cause Uncaught TypeError.

### System information
![image](https://user-images.githubusercontent.com/78906980/120309389-79aaee80-c2d5-11eb-8d0e-736277947ba5.png)

### Additional comments
Rotate the viewport and error is gone. Same behaviour using Safari/Mac.

**Comment by PhilETaylor** [comment] 2021-06-01 11:45
@dgrammatiko ;-)

**Comment by dgrammatiko** [comment] 2021-06-01 11:46
@PhilETaylor once https://github.com/joomla/joomla-cms/pull/33877 is merged I will patch also this one as well

**Comment by brianteeman** [comment] 2021-08-01 07:34
I'm getting a different error

```
dropdown.min.js?5.0.2:1 Uncaught TypeError: Cannot read property 'classList' of undefined
    at Dropdown.show (dropdown.min.js?5.0.2:1)
    at Dropdown.toggle (dropdown.min.js?5.0.2:1)
    at HTMLDivElement.<anonymous> (dropdown.min.js?5.0.2:1)
    at HTMLDivElement.n (dom.min.js?1627422273:1)
```

**Comment by dgrammatiko** [comment] 2021-08-01 10:03
There's no real issue here, the problem is the Mobile emulator:

On a real browser:
<img width="501" alt="Screenshot 2021-08-01 at 12 01 24" src="https://user-images.githubusercontent.com/3889375/127767003-4ae2dfc9-dd1a-480f-a268-2feccedf6da3.png">


On EMULATION mode:
<img width="396" alt="Screenshot 2021-08-01 at 12 02 05" src="https://user-images.githubusercontent.com/3889375/127767011-ae9d3b17-a044-41de-9416-a44077155474.png">

**Comment by brianteeman** [comment] 2021-08-01 10:51
No it depends on your screen size and if it will display the three dots or not which is where the bug is.

This is from my phone not an emulator

![Screenshot_20210801-114736](https://user-images.githubusercontent.com/1296369/127768155-7d733a26-7c99-4c92-809a-bc4ea50d0489.png)

**Comment by dgrammatiko** [comment] 2021-08-01 10:54
Test https://github.com/joomla/joomla-cms/pull/35011

**Comment by brianteeman** [comment] 2021-08-01 11:12
for reference can also be tested in a desktop browser with a width of approx 700px

**Comment by richard67** [comment] 2021-08-01 13:20
Closing as having a pull request. Please test #35011 . Thanks in advance.

**Closed as completed by richard67** 2021-08-01 13:20 UTC
Labels: No Code Attached Yet
