### ISSUE TITLE
Update to joomla 3.5 - custom modules - pages freeze

### ISSUE THREAD

**Issue by meninaisabella** [joomla/joomla-cms#9567] opened 2016-03-24 12:27 UTC
#### Steps to reproduce the issue
Admin - modules - on opening a custom module page, the page does not seem to load fully (see attached screenshot)![screen shot 2016-03-24 at 07 26 32](https://issues.joomla.org/uploads/1/198986abdb2cc789033ae0c2d9ea9485.jpg) and freezes. Extension based modules are working fine. Access: admintest - admintest24

#### Expected result
full functionality of custom modules

#### System information (as much as possible)
Joomla! version
    3.5
PHP version
    5.5.31
MySQL version
    5.5.46

**Comment by MATsxm** [comment] 2016-03-24 12:44
Not able to reproduce, the editor loads as expected. Could you please add a step by step process for "How to reproduce"?

Anyway, this should not be a Highest level issue:
https://docs.joomla.org/Priority
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9567">issues.joomla.org/joomla-cms/9567</a>.</sub>

**Comment by meninaisabella** [comment] 2016-03-24 12:59
Thank you and apologies for priority error ( I don't know where to change it at the minute, will do when I've found that)
Step by step process: 
1. I go to http://future-is-now.net/administrator/index.php, 
2. log in with my usual super user credentials
3. go to extensions and then modules
4. select type "custom" 
5. open an existing module
The module appears in source code mode, can be toggled, though. The normal menu (module, menu assignment, module permissions etc.) is not appearing and none of the buttons (save, save and close etc) are working. The module cannot be closed. 

I have cleared the joomla cache, browser cache, tried a different browser but the problem persists. I have got another joomla site with still 3.4.8 running and there the modules work fine.

**Comment by brianteeman** [comment] 2016-03-24 13:10
i have changed the priority for you ;)

**Comment by brianteeman** [comment] 2016-03-24 13:10
This sounds like a failed update

On 24 March 2016 at 13:09, Brian Teeman <brian@teeman.net> wrote:

> i have changed the priority for you ;)
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by meninaisabella** [comment] 2016-03-24 13:13
Same problem with articles. what next?

**Comment by brianteeman** [comment] 2016-03-24 14:38
What wysiwyg editor do you have installed or is it just the default<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9567">issues.joomla.org/joomla-cms/9567</a>.</sub>

**Comment by meninaisabella** [comment] 2016-03-24 14:41
Just default.

**Comment by meninaisabella** [comment] 2016-03-24 14:41
just default

**Comment by brianteeman** [comment] 2016-03-24 14:46
So I would guess that there is a third party content plugin that is
misbehaving or a faulty update
Go to your plugin manager and try to disable any content plugins that you
have installed and see if that fixes it

**Comment by meninaisabella** [comment] 2016-03-24 16:24
It's the TinyMCE that's not working and blocking things. When I switch it off, the tabs appear again and the buttons work.

**Comment by brianteeman** [comment] 2016-03-24 16:28
OK we are getting close. Do you have any editor plugins? Try disabling them

**Comment by meninaisabella** [comment] 2016-03-24 16:29
There are only the three that come with Joomla. CodeMirror, None, and TinyMCE. Do you want me to disable all of them?

**Comment by brianteeman** [comment] 2016-03-24 16:32
I am not talking about those. I am taking about the plugins in this group
editors-xtd

**Comment by meninaisabella** [comment] 2016-03-24 16:39
That's it! I've disabled all of them and the editor is working again. The rest I can figure out myself I think, finding out which one causes the problem. Brilliant, thank you so much!!

**Comment by brianteeman** [comment] 2016-03-24 16:57
Great - I am closing this now - if it turns out to be one of the core plugins please post back but I am sure it wont be

**Closed by brianteeman** 2016-03-24 16:57 UTC
Labels: No Code Attached Yet

**Comment by meninaisabella** [comment] 2016-03-24 17:00
No, it's not, it's the POWr Icon one, for the facebook feed. Thanks again!
