### ISSUE TITLE
Fatal error: Using $this when not in object context

### ISSUE THREAD

**Issue by eaexo** [joomla/joomla-cms#22619] opened 2018-10-15 05:52 UTC
### Steps to reproduce the issue

Run Joomla 3.8.13 (updated from 3.8.12) on PHP 7.x (both 7.1 and 7.2) does not work, then instead of showing a frontend, an error page with error code 0 and error message "Using $this when not in object context" is shown.

To fix it edit in CMSApplication.php

the method
    public function getMenu($name = null, $options = array())

and replace
            $options['app'] = $this;
by
           $options['app'] = \JFactory::getApplication();

### Expected result

One can open the frontend page

### Actual result

error page with message "Using $this when not in object context" is shown.

Swithching PHP version to 5.6 "fixes" the error.

**Comment by SharkyKZ** [comment] 2018-10-15 05:55
Duplicate of #22597. The issue is in 3rd party extension or template. Update your extensions or enable debug to see where the error is coming from and follow https://github.com/joomla/joomla-cms/issues/22597#issuecomment-429535987 to fix it.

**Comment by eaexo** [comment] 2018-10-15 06:13
It is clearly not a template - tried also a default joomla template -> same issue.

But I will double-check the code and look for the calls such "JSite::getMenu()" or "JApplicationSite::getMenu()"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22619">issues.joomla.org/tracker/joomla-cms/22619</a>.</sub>

**Comment by ggppdk** [comment] 2018-10-15 06:32
Why don't you enable Joomla debug as it was suggested above by @SharkyKZ  ?
it should tell you which extension code is doing this

**Comment by brianteeman** [comment] 2018-10-15 08:29
I am closing this as a non core joomla issue

**Closed as completed by brianteeman** 2018-10-15 08:29 UTC
Labels: No Code Attached Yet
