### ISSUE TITLE
_removeAdminMenus removes wrong menu items - nested table error?

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/joomla-cms#11044] opened 2016-07-07 14:43 UTC
#### Steps to reproduce the issue

I've been testing the latest builds of Joomla 3.6 and I've just noticed that when I install an extension. **_removeAdminMenus** removes _not only_ admin menu items associated with the extension.

I've found how to reproduce the issue with [Weblinks](https://github.com/joomla-extensions/weblinks/releases).

The key to force the bug is in the order of menu items.

1. Modify _**removeAdminMenus** to force an inverse order of deletion, libraries/cms/installer/adapter/component.php, line 1087

		// Get the ids of the menu items
		$query = $db->getQuery(true)
					->select('id')
					->from('#__menu')
					->where($db->quoteName('client_id') . ' = 1')
					->where($db->quoteName('component_id') . ' = ' . (int) $id)
					->order('id desc');

2. Install [Weblinks](https://github.com/joomla-extensions/weblinks/releases).
3. Manually add a menu item (any type)
4. Install [Weblinks](https://github.com/joomla-extensions/weblinks/releases) again. 
5. New menu item is removed!

#### Expected result

Only extension admin menu items must be deleted

#### Actual result

Extra menu items are removed

#### System information (as much as possible)

Joomla 3.6 RC2
MySQL Server version: 5.5.49-0ubuntu0.14.04.1
PHP 5.6.23-1

#### Additional comments

I have tested two solutions:

1. The list of menu items must be visited orderly

		// Get the ids of the menu items
		$query = $db->getQuery(true)
					->select('id')
					->from('#__menu')
					->where($db->quoteName('client_id') . ' = 1')
					->where($db->quoteName('component_id') . ' = ' . (int) $id);
					->order('id');

2. JTableNested cannot compress "the left and right values" since it is not adjusting the width of the parent node.

			// Compress the left and right values.
			/*
			$query->clear()
				->update($this->_tbl)
				->set('lft = lft - ' . (int) $node->width)
				->set('rgt = rgt - ' . (int) $node->width)
				->where('lft > ' . (int) $node->rgt);
				*/

Please, note that when the list of menu items is NOT ordered and it is returned by MySQL in any order, then the parent node has the orignal width (rgt-lft). If it is the last item of the list, it includes other menu items.

**Comment by mbabker** [comment] 2016-07-07 15:08
You're going to have to give a lot better reproduction instructions to get anywhere with this one.  Assuming you mean `JInstallerAdapterComponent::_removeAdminMenus()` and not some custom code the query in question already filters on admin menu items only (ordering is irrelevant here unless you're only looking for parent items and will rely on the JTable API to delete its children).

Also the left/right values should be updated so as to ensure the nested data set is correct, I'd advise against not executing that query.

If a frontend menu item is being assigned as the child item of an admin menu item, that is a major error with how the menu items are being inserted.  Considering the data set you're giving is nothing but a bunch of IDs, it's hard to say what's going on.

**Comment by anibalsanchez** [comment] 2016-07-07 15:25
Hi Michael,

Sorry to be unclear. Yes, you are right. I'm referring to JInstallerAdapterComponent::_removeAdminMenus().

No, a frontend menu item is being assigned as the child item of an admin menu item. Menu items are consistent.

The error is found when _removeAdminMenus() is executed with a list of admin menu items not ordered by ID.

I think that the main clue of the problem is that  JTableNested re-arranges lft and rgt values ... and parent node keeps the same values until the end... when it has invalid values.

I'm going to try to reproduce it in a Joomla demo site.

**Comment by anibalsanchez** [comment] 2016-07-07 15:41
Addtionally, I can only reproduce it in Joomla 3.6.

**Comment by ggppdk** [comment] 2016-07-07 16:14
There is no problem with the SQL query of the method
_removeAdminMenus

if this bug exists it must be a problem with method ?

JTableNested::delete

is this change relevant ?
https://github.com/joomla/joomla-cms/commit/28195290de257d791e0fb4ed41ad4bf5a7e09ce5

**Comment by anibalsanchez** [comment] 2016-07-07 16:45
Hi @ggppdk , Yes, it's related with that modification.

I've found how to reproduce the issue with [Weblinks](https://github.com/joomla-extensions/weblinks/releases).

The key to force the bug is in the order of menu items.

1. Modify _**removeAdminMenus** to force an inverse order of deletion, libraries/cms/installer/adapter/component.php, line 1087

		// Get the ids of the menu items
		$query = $db->getQuery(true)
					->select('id')
					->from('#__menu')
					->where($db->quoteName('client_id') . ' = 1')
					->where($db->quoteName('component_id') . ' = ' . (int) $id)
					->order('id desc');

2. Install [Weblinks](https://github.com/joomla-extensions/weblinks/releases).
3. Manually add a menu item (any type)
4. Install [Weblinks](https://github.com/joomla-extensions/weblinks/releases) again. 
5. New menu item is removed!

**Comment by anibalsanchez** [comment] 2016-07-07 16:51
Hi @wilsonge , please, check this issue that removes menu items.

**Comment by ggppdk** [comment] 2016-07-07 18:53
Ok @anibalsanchez  @mbabker 
i confirm the issue of wrong menu items being deleted !

- a fix is to move the $table->rebuild() inside the deletion loop, thus executing a rebuild after every menu deletion

Is this seems performance unwise ? maybe rebuild() can be changed to limited to a subtree ?

Also the bug, seems to be a side effect of the changes made to:
JTableNested::delete()
- now rebuild() is required to be called after every deletion ?

is there are other code similar to _removeAdminMenus() ?
are 3rd party extensions that can be using similar code ?

This is a release blocker ?

**Comment by anibalsanchez** [comment] 2016-07-07 21:21
Yes. It is a release blocker.

This a case about menu items, but it could also affect other cases
associated with nested table usage.

**Comment by wilsonge** [comment] 2016-07-07 23:41
I've set a release blocker label and pinged the maintainer team in glip to make them aware. I'm away on holiday until saturday evening. If no one picks up on it by then, I'll deal with things here on my return

**Comment by infograf768** [comment] 2016-07-11 18:19
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11044">issues.joomla.org/joomla-cms/11044</a>

**Comment by infograf768** [comment] 2016-07-11 18:20
closed as we have a patch<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11044">issues.joomla.org/joomla-cms/11044</a>.</sub>

**Closed by infograf768** 2016-07-11 18:19 UTC
Labels: No Code Attached Yet, release-blocker
