### ISSUE TITLE
[com_fields] Cannot save article without selecting List Item (forced selection)

### ISSUE THREAD

**Issue by JoshuaLewis** [joomla/joomla-cms#15688] opened 2017-04-29 22:52 UTC
When creating/editing an article with the custom field type "list" it selects the first list value without viewing the fields tab. The list item shouldn't select anything without the user selecting from the list. Note that when allowing multiple values it does not automatically select any of the custom fields.

**Comment by Bakual** [comment] 2017-04-30 11:40
If you only add two values (eg Yes and No), it will indeed select the first one automatically. If you don't want that, you need to add a third empty option and make that the top one. That's how a HTML "select" works.

Closing as it is expected behavior.

**Closed by Bakual** 2017-04-30 11:40 UTC
Labels: No Code Attached Yet

**Comment by AlexRed** [comment] 2017-04-30 11:57
very bad user experience....   we need to fix it, please.
Or we need to delete the "power through simplicity" from the Joomla! Development Strategy

**Comment by brianteeman** [comment] 2017-04-30 11:59
We cant fix the way that the web works

**Comment by AlexRed** [comment] 2017-04-30 13:16
if our dev team can't add a default empty option and make that the top one, we can try to write this info in the Field.

**Comment by JoshuaLewis** [comment] 2017-04-30 17:32
Originally I was attempting to set the default value to a blank space, however validation wanted an existing value. @brianteeman is right about how the web works, you can see this in action:
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select

Thanks @Bakual for the advise on solving the select issue. Works great.

**Comment by Bakual** [comment] 2017-04-30 18:30
> very bad user experience.... we need to fix it, please.

Seriously?

> if our dev team can't add a default empty option and make that the top one, we can try to write this info in the Field.

I think there is a misunderstanding. That's how you have to set up the list options if it should be possible to have an empty value selected:
![options](https://cloud.githubusercontent.com/assets/1018684/25566942/abbadd8a-2de3-11e7-9c21-d39b6f443ac6.PNG)
Which results in this:
![list](https://cloud.githubusercontent.com/assets/1018684/25566943/b2072d6a-2de3-11e7-9205-641796029642.PNG)

When you save that, you have "nothing" selected by default.
It's just a question to set up the field the way you need it. If "empty" is a valid option, you need to add it.

**Comment by AlexRed** [comment] 2017-04-30 18:52
I hope we can write this instructions in the field if we can't add it by default.

**Comment by brianteeman** [comment] 2017-04-30 18:59
That would mean that for consistency we would have to write instructions on every field everywhere explaining absolutely everything that there is to know about how the web works. Sorry but this is a crazy idea.

**Comment by AlexRed** [comment] 2017-04-30 19:10
no, I have never written such a thing. Kindly avoid inventing strange allusions

**Comment by laoneo** [comment] 2017-04-30 19:14
I think we can expect some cleverness from people when they want to use custom fields in Joomla. If they are dealing with such use cases, then they have a certain level of Joomla experience.

**Comment by AlexRed** [comment] 2017-04-30 19:22
Why?
An use can access in the Joomla control panel and for you it is an expert html users?

**Comment by mbabker** [comment] 2017-04-30 19:34
It is not our role to document directly into the CMS how basic HTML structures work or every known issue or quirk with everything.  So yes, there is some expectations that users would either need a basic level of understanding on how some things work or do the research required to learn those things.

**Comment by Bakual** [comment] 2017-04-30 19:35
Custom Fields aren't designed to be used by complete web N00bs. I also would expect at least some basic knowledge from users setting up (not using!) custom fields. And if not, they will be able to figure it out with the help of forums and Google.

**Comment by AlexRed** [comment] 2017-04-30 19:37
Many users choose to use CMS because they are not HTML expert.
And if for you Custom Fields aren't designed to be used by complete web N00bs you need to write it, only for expert in the Joomla menu  :(

**Comment by AlexRed** [comment] 2017-04-30 19:39
Joomla tries to follow the slogan “power through simplicity”

**Comment by AlexRed** [comment] 2017-04-30 19:41
I can understand your reasoning for features not so in the foreground, like ACL. But custom fields are in the menu, immediate and simple to create. Really does not seem to be just for experts.

**Comment by brianteeman** [comment] 2017-04-30 19:42
you are showing your age. That was the slogan of mambo. ;)

**Comment by AlexRed** [comment] 2017-04-30 19:42
here the slogan: Joomla! Development Strategy  https://developer.joomla.org/development-strategy.html

**Comment by mbabker** [comment] 2017-04-30 19:45
Alex, it is not our responsibility to explain how to use the web in the context of the CMS interface.  So no, we should not add something to com_fields explaining how you configure a list form field from start to end or explaining every little quirk or issue that you have come across.  Personally, I would find that experience degrading as an end user if the platform assumed I was a complete idiot.

This is why we have a suite of documentation and support channels.  These are the places where things are explained in greater depth (to a reasonable extent, again, it's not our responsibility to explain the semantics and logic behind a `<select>` element and its various configurations) or users go to ask questions that either might be above their skill level or deal with complex scenarios.

**Comment by JoshuaLewis** [comment] 2017-04-30 19:51
I would have created a blank list item from the get go, however I assumed validation would require text input. Indeed we do not want to over document something that follows HTML standards. Perhaps the default value field could accept a blank space as a valid input? Understandable if this is not a proper exception.

**Comment by AlexRed** [comment] 2017-04-30 19:52
ok, you don't want to write info. But can the selection be like for the "Multiple" values ?

**Comment by JoshuaLewis** [comment] 2017-04-30 19:54
Having it auto select by default is slightly rougher user experience especially considering that we can already set the default value but cannot set a blank by default except for the scenario mentioned by Bakual.

**Comment by brianteeman** [comment] 2017-04-30 19:56
NO it cant. That would not be the correct usage of a select

Sorry @AlexRed but multiple people have told you that this is not going to be changed the way that you are requesting. If you were any other commenter I would lock this issue. But because you are a "member" that will have no effect.

**Comment by Bakual** [comment] 2017-04-30 20:06
> ok, you don't want to write info. But can the selection be like for the "Multiple" values ? (but limit it for only one value)

And what if I don't want the user to be able to leave the select empty? It absolutely depends on the use case if there should be such an empty option or not.

> considering that we can already set the default value but cannot set a blank by default except for the scenario mentioned by Bakual. 

Actually, you can have the "blank" option also at the end or in between. It just doesn't make much sense imho from an UX perspective. But the field by default will select the empty one regardless where it is in the list if you have left the "Default Value" parameter empty. I wrote that a bit misleading above.

**Comment by AlexRed** [comment] 2017-04-30 20:14
Like for the module "Position", a select where you can insert only one value. And if you do not insert a value it is empty.

**Comment by mbabker** [comment] 2017-04-30 20:32
Not all select lists are optional and as such it should not be mandated to have an empty option nor the code try to create one when the user did not set up their field to behave as such.

**Comment by Bakual** [comment] 2017-04-30 20:33
> Like for the module "Position", a select where you can choose only one value. And if you do not choose a value it is empty.

Because in the module, the position isn't a requirement and an empty value is absolutely fine. You can do that in the custom field as well, just set it up correctly.
As said, it depends on the use case if there should be such an empty value or not. There are many other examples of selects where you can't choose an empty value. Both are valid list fields.

**Comment by JoshuaLewis** [comment] 2017-04-30 20:41
The fact that a blank field anywhere handles this makes a description not needed. It's up to the admin to not assume that validation would fail it's submission.

**Comment by laoneo** [comment] 2017-05-01 04:12
And when you want to have an empty entry in all select fields, then you can define one in the list plugin and it will be populated on all list fields.

**Comment by ggppdk** [comment] 2017-05-01 05:57
> you  need to add a third empty **option** and make that the top one

> if our dev team can't add a default empty **option** and make that the top one, we can try to write this info in the Field.

> Actually, you can have the "blank" **option** also 

>I think there is a misunderstanding. That's how you have to set up the **list options** if it should be possible to have an empty value selected:

So they are list **OPTIONS** and not list **VALUES** (HTML calls them "options", and other CMS call them options, for some reason we selected to call them "values")

Correct terms are:
List options
Checkboxes (or Checkbox options)
Radio buttons (or Radio options)

instead of
List values
Checkbox values
Radio values

**Comment by AlexRed** [comment] 2017-05-01 06:40
same problem with the "sql" field. But here you can't add a default empty option and make that the top one so simple.
