### ISSUE TITLE
Saving strings in User - Profile (extra info) in greek saves as unicode characters

### ISSUE THREAD

**Issue by tetterip** [joomla/joomla-cms#8301] opened 2015-11-06 23:15 UTC
#### Steps to reproduce the issue
Enable User - Profile plugin
Go to Users -> Manage, select a user and add some info in the User Profile tab, in greek.

#### Expected result
Joomla saves the info in greek in the database table #_user_profiles

#### Actual result
Joomla saves the info in unicode characters (\u03a7\u03af\u03bf\u03c2)

#### System information (as much as possible)
PHP Built On	Darwin Mikes-Air.lan 15.0.0 Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64 x86_64
Database Version	5.5.33
Database Collation	utf8_general_ci
PHP Version	5.5.3
Web Server	Apache/2.2.25 (Unix) mod_ssl/2.2.25 OpenSSL/0.9.8zg DAV/2 PHP/5.5.3
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 3.4.5 Stable [ Ember ] 22-October-2015 21:30 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36

**Comment by infograf768** [comment] 2015-11-07 09:33
And? What is the problem? Are'nt the unicode correctly displayed?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8301">issues.joomla.org/joomla-cms/8301</a>.</sub>

**Comment by tetterip** [comment] 2015-11-07 15:14
I have a helpdesc component that lists the active users with their details. There, the address is'nt displayed in greek, but in unicode characters (\u03a7\u03af\u03bf\u03c2) as taken from the db.

**Comment by infograf768** [comment] 2015-11-10 07:13
Try using `json_decode($value, true)` to get the correct display in your component.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8301">issues.joomla.org/joomla-cms/8301</a>.</sub>

**Comment by brianteeman** [comment] 2015-11-19 11:46
I am closing this as it is not an issue with the core of joomla which is working as intended<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8301">issues.joomla.org/joomla-cms/8301</a>.</sub>

**Closed by brianteeman** 2015-11-19 11:46 UTC
Labels: No Code Attached Yet
