### ISSUE TITLE
Multilingual associations doesnt save language

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#14562] opened 2017-03-13 09:54 UTC
### Steps to reproduce the issue
Using Multilingual Associations select an article and a target language
Select Copy reference to target in the toolbar
Message on screen that the new article has been saved
Close and return to the article manager

### Expected result
A duplicate article has been created but in the selected target language

### Actual result
An unpublished article (see #14561) has been created but instead of it being in the target language you selected it is in the **default** language

**Comment by brianteeman** [comment] 2017-03-13 09:57
Note it says **default** language which is odd as this isnt actually something you can select anywhere else as the language for anything????

**Comment by wilsonge** [comment] 2017-03-13 10:51
@infograf768 this seems like a pretty big bug. Adding a release blocker here

**Comment by infograf768** [comment] 2017-03-20 15:35
Testing now

**Comment by infograf768** [comment] 2017-03-20 15:42
I can't reproduce.

Default Language is English en-GB.
Displaying a French article. Target is Italian.
The new target article is saved correctly with Italian language.

![assoctarget](https://cloud.githubusercontent.com/assets/869724/24107744/dc5e2b4a-0d8b-11e7-96e2-d6e5efa0fe57.gif)

@wilsonge
Please take off the release blocker until we get a better explanation of the possible bug.

**Comment by infograf768** [comment] 2017-03-20 15:46
I see why Brian got that: he did not save the new target, just closed it.

**Comment by brianteeman** [comment] 2017-03-20 15:52
Yes that is what I said in the report. Note that my report also stated that you get the message that the reference article has been saved.

you can see in your own movie above that after clicking on copy reference to target you get a message that the article has been saved.

and it has been saved but with the non-existant language "default" - you can see this if you go to the article manager and view a list of all the articles.

**Comment by infograf768** [comment] 2017-03-20 16:02
Yes, I did confirm that. The Target has to be Saved with "Save Target" before.

As for the Reference article, when we use "Copy Reference to Target", it pre-save it with the new association. That is normal and will work fine if the Target is saved before Closing.

Closing as you did  does not create an association and the new article is saved with no tagged language, therefore its language is displayed as Default by this code in /layouts/joomla/content/language.php

```
if ($item->language == '')
{
	echo JText::_('JDEFAULT');
}
```

Now what can we do about it?
Not fully sure.
Correct behaviour would be to not save the new item at all if Save Target is not used.

**Comment by infograf768** [comment] 2017-03-20 16:07
I guess we should look at the controller

**Comment by brianteeman** [comment] 2017-03-20 16:07
> Correct behaviour would be to not save the new item at all if Save Target is not used

Why wouldn't the correct behaviour be to save it with the selected language in the first place. The item language was selected already on the process - you can't copy reference to target until you have selected a language.

**Comment by infograf768** [comment] 2017-03-20 16:09
Why do you think we have a Save Target for?
Anyhow, patch is welcome

**Comment by infograf768** [comment] 2017-03-20 16:19
hmm, it may be in the js file...

@dgt41 @Fedik 
we need help here.

**Comment by brianteeman** [comment] 2017-03-20 16:20
We have a save target for subsequent changes after the creation and saving of the initial item.

**Comment by infograf768** [comment] 2017-03-20 16:42
one has to understand that when using copy reference, it copies everything except the language.
it is very likely that many modifications have to be done to the target:

title, alias, category are the usual main ones.
therefore target in that case has always to be saved before the association is created.
that works fine.

we therefore have tp prevent closing when the language is empty or display an alert.

**Comment by brianteeman** [comment] 2017-03-20 17:58
While i disagree with this approach you still should not be setting the language to the non existent string 'default'

**Comment by infograf768** [comment] 2017-03-20 18:44
i am not setting anything voluntarily. it comes from the way the feature is used. i am sure we will find a way for people who close instead of saving. patience.

**Comment by alikon** [comment] 2017-03-20 18:56
the  _copy reference_  is something like  as "_**set to work in progress**_ "
before this issue i've never experienced this situation ,   cause  i've always pushed the "save target" button after pushing a _copy reference_  button, yuo can blame me as a bad tester :cry:
but , the target language should be the actual language  not "DEFAULT"  even if you don't complete  the entire workflow  
i think this is a valid point

**Comment by Fedik** [comment] 2017-03-20 18:59
It seems something with component logic in general. It create a new article when push "copy reference", but do not add "association" between "reference article" and "target".

In result it can produce 1000 "un-associated" articles, with strange new language "default" 😄  
Where is this country Default? I want to visit there 😄

**Comment by alikon** [comment] 2017-03-20 19:02
if you push the **_copy reference_** button then the target language is already setted
maybe is only a bug :innocent:

**Comment by infograf768** [comment] 2017-03-21 11:14
The issue is that `save2copy` is a generic method. It can't therefore pick up the Target language when creating the new Target when using `Copy Reference to Target`.

I have a patch implementing an alert reminding user to use the "Save Target" before confirming Closing.
It would display anytime the `Close` button is used.

It would give this:

![screen shot 2017-03-21 at 12 12 53](https://cloud.githubusercontent.com/assets/869724/24145043/d01fb0de-0e2f-11e7-87ad-094ea41a3ae1.png)

What do you think?

**Comment by Fedik** [comment] 2017-03-21 11:32
@infograf768 but even with the alert, the "draft" article will remain after user push "ok" in the alert

**Comment by infograf768** [comment] 2017-03-21 11:33
Not if one uses `Save Target`...

**Comment by infograf768** [comment] 2017-03-21 11:35
I.e. one should cancel the alert, then Save Target, then can click OK.
Same behaviour with the Alert behaviour for items delete. If one clicks OK and did not want to delete, it will be too late...

**Comment by infograf768** [comment] 2017-03-21 11:37
@Fedik 
If you have a better idea, look at
https://github.com/joomla/joomla-cms/blob/staging/media/com_associations/js/sidebyside-uncompressed.js

to Copy reference, we use
```
else if(task == 'copy')
		{
			window.frames['reference-association'].Joomla.submitbutton(document.getElementById('adminForm').getAttribute('data-associatedview') + '.save2copy');
}
```

**Comment by Fedik** [comment] 2017-03-21 11:52
hm, I have no better idea currently

**Comment by infograf768** [comment] 2017-03-21 14:22
will make pr

**Comment by infograf768** [comment] 2017-03-21 15:39
Closed as we have a PR

https://github.com/joomla/joomla-cms/pull/14834<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14562">issues.joomla.org/tracker/joomla-cms/14562</a>.</sub>

**Closed by infograf768** 2017-03-21 15:39 UTC
Labels: No Code Attached Yet, release-blocker
