### ISSUE TITLE
[4.2] $version variable used before initialization in Installer.php

### ISSUE THREAD

**Issue by joeforjoomla** [joomla/joomla-cms#37934] opened 2022-05-30 22:10 UTC
### Steps to reproduce the issue
Install an extension with schema updates

### Expected result
No installer error

### Actual result
Warning because an unitialized variable $version is used at line 1334 in the file root/libraries/src/Installer/Installer.php
`Log::add(Text::sprintf('JLIB_INSTALLER_SQL_BEGIN_SCHEMA', $version), Log::INFO, 'Update');
`

### System information (as much as possible)
Joomla 4.2 Alpha 3

### Additional comments
![j42_installer](https://user-images.githubusercontent.com/17835460/171063699-d0568430-be01-4815-ac13-5443039aa668.JPG)

**Comment by richard67** [comment] 2022-05-31 12:51
Confirmed. In 4.1-dev we have that log statement below the code where we fetch the version from DB (and set it to '0.0.0' if not found), so 4.1-dev is ok: https://github.com/joomla/joomla-cms/blob/4.1-dev/libraries/src/Installer/Installer.php#L1179

In 4.2-dev we have that log statement before the code where we fetch the version: https://github.com/joomla/joomla-cms/blob/4.2-dev/libraries/src/Installer/Installer.php#L1334 . This was caused by PR #36506 .

The solution is to move that log to below so it comes just before this foreach: https://github.com/joomla/joomla-cms/blob/4.2-dev/libraries/src/Installer/Installer.php#L1364 .

**Comment by richard67** [comment] 2022-05-31 13:01
Closing as having a pull request. Please test #37941 . Thanks in advance.

**Closed as completed by richard67** 2022-05-31 13:01 UTC
Labels: No Code Attached Yet
