### ISSUE TITLE
Open Site / Admin after sucessfull install

### ISSUE THREAD

**Issue by 1337180** [joomla/joomla-cms#35179] opened 2021-08-17 12:51 UTC
### Steps to reproduce the issue
install j4 click open site or open admin after sucessfull installation

### Expected result
open site / admin

### Actual result
404

### System information (as much as possible)
PHP 8 
mariadb 10.15

### Additional comments
it probably is run on deleted file

**Comment by PhilETaylor** [comment] 2021-08-17 12:58
what is the exact URL you are on? 

What web server? nginx/apache/other?

**Comment by RickR2H** [comment] 2021-08-17 13:19
Cannot reproduce the issue on WAMP server on Windows. 
Both frontend and backend links work after installation.
@1337180 please provide sever specs / setup info as @PhilETaylor suggested so we can investigate the issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35179">issues.joomla.org/tracker/joomla-cms/35179</a>.</sub>

**Comment by 1337180** [comment] 2021-08-17 14:02
Back/Frontend are working, I was just mentioning the link from the Installer wasnt. Again Im talking only of link from installer (when installation finished) gave 404, highly probably because installer has been deleted after sucessfull install. 
So the problem was that it didnt reconnected me from the sucessfull installation to the admin.
Again everything is fine but this 404 installation -> website jump

**Comment by RickR2H** [comment] 2021-08-17 14:05
Isn't this intended behavior...?

**Comment by richard67** [comment] 2021-08-17 14:27
If the 404 happens when going to `http://<yourdomain>/installation/index.php`then yes, it is intended behaviour.

At the end of the installation the installation folder is removed, and you either can install additional languages or go to the backend using the corresponding button.

@1337180 Can you confirm if it was like I described?

**Comment by PhilETaylor** [comment] 2021-08-17 14:27
When you hit to the complete buttons, it runs ajax to delete the installation folder, and then redirects using the JS that is already loaded in the page to redirect you to the location you choose - it should work that way.

**Comment by HLeithner** [comment] 2021-08-17 14:34
sounds like the file caching problem I tried to prevent in the last installer fixes... can you repeat the installation and paste your system information here?

And of course be sure that you don't mean hitting the back button is the problem.

**Comment by PhilETaylor** [comment] 2021-08-17 14:59
So that begs the question what are the opcache settings on this server? 

Also is nginx full page caching,  caching the GET requests to any of the urls ?

**Comment by 1337180** [comment] 2021-08-17 15:11
output_buffering was on also op cache is on and http cache is on
PHP Built On | Linux php80 4.15.0-151-generic #157-Ubuntu SMP Fri Jul 9 23:07:57 UTC 2021 x86_64
-- | --
mysql
10.5.9-MariaDB-1:10.5.9+maria~focal-log
utf8mb4_unicode_ci
utf8mb4_general_ci
None
No
8.0.7
Apache
apache2handler
Joomla! 4.0.0 Stable [ Furaha ] 17-August-2021 12:30 GMT
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0

**Comment by PhilETaylor** [comment] 2021-08-17 15:37
This is nothing to do with output_buffering

What are ALL your opcache settings - you can find these in your PHP configuration tab

Another thing that could be happening is that if you initially went to / and were redirected to /installation/index.php by Joomla, then your browser can cache that 302 Found redirect. They are not meant to, but browsers DO cache 302 Found redirects!!! 

```
HTTP/1.1 302 Found
Connection: keep-alive
Content-Type: text/html; charset=UTF-8
Date: Tue, 17 Aug 2021 15:32:30 GMT
Location: installation/index.php
Server: nginx/1.21.1
Transfer-Encoding: chunked
```

Open up your browsers debug console (Ensure disabling caching is enabled by NOT selecting in your browsers debug console to disable network caching, so that it uses its internal resource cache normally!)  and try again, inspecting each and every network request as you generate them looking where it redirects to after clicking the Complete buttons. 




Consulting StackOverflow: https://stackoverflow.com/questions/12212839/how-long-is-a-302-redirect-saved-in-browser

"With no expires headers or cookies, the results were as follows:

Chrome 71: Not Cached 
Firefox 64: Cached 
Safari 12: Cached 

So despite what RFC 2616, section 10.3.3 302 Found states, not all browsers follow these guidelines or what might be considered expected behaviour :("


So Joomla "should"  Add the
```
Cache-Control: no-store
```
header to the response and it won't be cached. "As of Jul 20, 2020 all mainstream browsers respect this."

**Comment by PhilETaylor** [comment] 2021-08-17 15:42
Please also post your web server access logs... where you should see the 302 redirects IF your browser is asking the web server for the homepage

```
joomla-php-fpm    | 172.19.0.5 -  17/Aug/2021:15:41:01 +0000 "GET /index.php" 302
joomla-php-fpm    | 172.19.0.5 -  17/Aug/2021:15:41:01 +0000 "GET /installation/index.php" 200
joomla-php-fpm    | 172.19.0.5 -  17/Aug/2021:15:41:11 +0000 "GET /index.php" 302
joomla-php-fpm    | 172.19.0.5 -  17/Aug/2021:15:41:11 +0000 "GET /installation/index.php" 200
```

**Comment by 1337180** [comment] 2021-08-17 15:55
Firefox/91.0

**Comment by Quy** [comment] 2022-02-11 00:17
@1337180 Is this still an issue? If yes, please provide web server access logs as requested [previously](https://github.com/joomla/joomla-cms/issues/35179#issuecomment-900409667).

**Comment by 1337180** [comment] 2022-02-11 16:25
Hello, its JurajB.
https://joomlatesting.jurajbevilaqua.com/installation/index.php?view=remove&layout=default
PHP 8.1
webserver - modified apache
joomla 4.0.6

NO SERVER (ACCESS/ERROR) LOG was created at this situation

still gives 404 because the file forwarding to admin/frontend has been deleted so this is how it works in here
any more info I will reply asap
JurajB

**Comment by Quy** [comment] 2022-02-11 17:16
So the Site / Admin buttons link to the URL you provided? 
Please test with 4.1 nightly build to see if it is still an issue: https://developer.joomla.org/nightly-builds.html

**Comment by 1337180** [comment] 2022-02-11 18:08
Hello.
4.1 is running fine
tho it is in developer mode, I will retest in in final (normal mode)

**Comment by Quy** [comment] 2022-02-15 10:17
Closing as 4.1 has been released without this issue as confirmed by you. Thank you.

**Closed as completed by Quy** 2022-02-15 10:17 UTC
Labels: No Code Attached Yet, Information Required
