### ISSUE TITLE
Source url can not be empty!

### ISSUE THREAD

**Issue by onedego** [joomla/joomla-cms#16972] opened 2017-07-04 23:45 UTC
### Steps to reproduce the issue
Refresh page, 2 browsers, 2 systems.  When accessing site following Joomla 3.7.3 Upgrade, now receiving error.

### Expected result

Home Page displayed as normal

### Actual result

Oop's, we have a 0
Source url can not be empty!
Please try one of the following pages:
Home Page

### System information (as much as possible)
System Information
Setting	Value
 
PHP Built On	Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux
Database Version	5.5.55-0+deb7u1-log
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	7.0.20
Web Server	Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 3.7.3 Stable [ Amani ] 4-July-2017 08:03 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

### Additional comments
Admin console is still accessible, and files in the backend are visible.

**Comment by franz-wohlkoenig** [comment] 2017-07-05 04:33
To reproduce Issue you mean: Refresh same Page in different Browsers (Firefox, Safari) and different Systems (Mac, Linux) at same Time and then you get ` Source url can not be empty!`?

**Comment by brianteeman** [comment] 2017-07-05 06:57
> Source url can not be empty!

This is not a string in the core of joomla

**Comment by onedego** [comment] 2017-07-05 08:15
franz, correct, but MacOS and Windows.  

brian, perhaps not, but the site worked before 3.7.3, and now does not.

**Comment by brianteeman** [comment] 2017-07-05 08:15
so we need to know where that message comes from in order to try and debug and solve

**Comment by onedego** [comment] 2017-07-05 08:23
thanks... just checked on the source of the page and the error is being called as part of the template Joostrap (v2)

`

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-gb" lang="en-gb" dir="ltr">
<head>
	<title>0 - Error: 0</title>
	<link rel="stylesheet" href="/templates/joostrap_v2/css/system/error.css" type="text/css" />
	</head>
<body>
	<div class="error">
		<div id="errorboxbody">
			<h1>Oop's, we have a 0</h1>
			<h2 class="error-type">Source url can not be empty!</h2>
			<h3>Please try one of the following pages:</h3>
		<div class="home-btn">
			<a style="color:#000;font-size:18px;" href="/index.php" title="Go to the Home Page">Home Page</a>
		</div>
			<p> 			</p>
	</div>
</body>
</html>`

**Comment by onedego** [comment] 2017-07-05 08:23
just checked and it's being called from the template I am using, which is based on JooStrap v2.  



<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-gb" lang="en-gb" dir="ltr">
<head>
	<title>0 - Error: 0</title>
	<link rel="stylesheet" href="/templates/joostrap_v2/css/system/error.css" type="text/css" />
	</head>
<body>
	<div class="error">
		<div id="errorboxbody">
			<h1>Oop's, we have a 0</h1>
			<h2 class="error-type">Source url can not be empty!</h2>
			<h3>Please try one of the following pages:</h3>
		<div class="home-btn">
			<a style="color:#000;font-size:18px;" href="/index.php" title="Go to the Home Page">Home Page</a>
		</div>
			<p> 			</p>
	</div>
</body>
</html>

**Comment by franz-wohlkoenig** [comment] 2017-07-05 10:35
@onedego so its a Template-Issue. Please talk to Template-Dev. and close this Issue, thanks.

**Comment by onedego** [comment] 2017-07-05 11:16
I wouldn't be so sure about that.  The template worked yesterday on 3.7.2.  I updated what is supposed to be a minor update to 3.7.3, and now it doesnt work.  So the update has broken the template.

**Comment by brianteeman** [comment] 2017-07-05 12:07
You cannot conclude it is a template issue - it **might** be just an issue that is being displayed by the template in a way we dont recognise.  You can test if that is the case by temperarily switching to the protostar template

**Comment by onedego** [comment] 2017-07-05 12:14
where can i get the prostar template from?  (have always tried to keep things minimalist)

**Comment by mbabker** [comment] 2017-07-05 12:21
> where can i get the prostar template from? (have always tried to keep things minimalist)

If you go to the Extension Manager's Discover page and discover uninstalled extensions it's probably sitting in your filesystem.  It's really not advisable to completely uninstall extensions shipped with core, disable them if you desire but don't uninstall them (they end up back on your filesystem anyway when you update Joomla).

**Comment by onedego** [comment] 2017-07-05 12:31
okay, so the Prostar template does work

**Comment by onedego** [comment] 2017-07-05 13:31
just to add, this seems to be the case on the other Joostrap templates I have on the site (3 versions)

**Comment by Werkverweg** [comment] 2017-07-05 21:24
Add: Looks like a similar problem. We use Joomspirit templates. From joomla 2.5 until 3.7.2 it worked perfect. Updated yesterday to 3.7.3 template is not working. Installed other templates from Joomspirit same bad result under 3.7.2. Tried it on an other server same bad result. Installed templates from Joomdev the free ones they works perfect under 3.7.3. We run ESXi on windows server 2012R2. All plugins updated to the latest. Went back to 2.7.2 for now.

**Comment by onedego** [comment] 2017-07-05 22:19
thanks for adding on Werkverweg - can you tell me if there's an easy way to get back to 3.7.2 without restoring the site?

**Comment by Werkverweg** [comment] 2017-07-05 22:36
Hi, I,am afraid I cannot help you with this one other then say do you have a backup? We run a virtual server so we just go back to the snapshot we always make.

**Comment by franz-wohlkoenig** [comment] 2017-07-06 04:48
closed as no Core Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16972">issues.joomla.org/tracker/joomla-cms/16972</a>.</sub>

**Closed by franz-wohlkoenig** 2017-07-06 04:48 UTC
Labels: No Code Attached Yet

**Comment by onedego** [comment] 2017-07-06 08:29
How can this be 'no core issue' - you have me with a Joostrap template, and Werkverweg with a Joomspirit template both of which broke as a result of the 3.7.3 update.  You can't say it's not a core issue when it breaks things that work perfectly well before the update.  Please re-open the issue.

**Comment by infograf768** [comment] 2017-07-06 09:13
It is suggested to contact the template developers and get from them a patch, and to help solve the issue in the future, ask them to post here what they had to change to get their templates to work in 3.7.3.
It will therefore be easier to track down the issue as it may come from an error on their side that that have let joomla < 3.7.3  forgive the error, but not anymore 3.7.3.
Knowing what they had to change will let us know if core is responsible or not.

**Comment by mbabker** [comment] 2017-07-06 12:37
Just to add also, in the core Joomla package and from what I could ascertain the core PHP engine, there is not a "Source url can not be empty" error message.  So whatever is giving the error seems to be localized to templates (why so many I can't say, but I've seen it with a few template frameworks now).  If there is a core change that can be identified as a culprit, we can re-open and investigate further, but based on the data we have right now there isn't enough to pursue this as a core bug.

**Comment by franz-wohlkoenig** [comment] 2017-07-06 12:44
@onedego i closed Issue as it looks like an Template-Issue (no Issue using Protostar). As others stated to, this Issue can always be reopen if its a Core Issue to solve a Bug.

**Comment by kat05** [comment] 2017-07-06 12:52
Just to add, one of our members, using the RocketTheme Voxel template is experiencing the same issue after the Joomla update to 3.7.3

**Comment by mahagr** [comment] 2017-07-06 13:10
It may not be the template as RT Voxel works just fine for me. Maybe it is some module in the page?

**Comment by kat05** [comment] 2017-07-06 13:11
BTW, blaming a 3rd party template just because there is no error with Protostar is a joke. Lots of modules won't get loaded when switching templates due to module positions being named differently.

**Comment by marktaylor46** [comment] 2017-07-06 13:26
Just adding here that I found this on a site and it turned out to be a plugin called "dpcalendar" causing the issue. specifically "dpcalendar upcoming" plugin - once disabled the site then works again with J3.7.3.

**Comment by mbabker** [comment] 2017-07-06 13:26
Nobody is trying to explicitly blame a template or extension.  But right now there is no concrete data to say there is a core bug that we can fix (the error message does not exist in our package and when I scanned the PHP source repo I couldn't find anything like it there).  There are 261 commits in the [3.7.2 to 3.7.3 diff](https://github.com/joomla/joomla-cms/compare/3.7.2...3.7.3), it's not a simple "this is the culprit" thing.

If someone can provide concrete data (stack traces help here) showing where the error is originating from, and we can use that to figure out if something in core is causing the issue, then we can address it.  With nothing but a "Source url can not be empty" error string and a "all I did was update to 3.7.3" reproduction instruction, there is simply not enough information to classify this as a core bug.

**Comment by kat05** [comment] 2017-07-06 13:28
There was simply not enough information to classify this as a template bug either. :)

**Comment by mbabker** [comment] 2017-07-06 13:29
And that's why I've tried to be careful with explicitly saying that other than noting every report of this message I've seen has seemingly been related to the template in use.  The DPCalendar comment is new info to me.

**Comment by marktaylor46** [comment] 2017-07-06 13:32
I must admit I was very surprised that this issue was closed without real investigation as a "must be a template issue".

Anyway I hope the extra info I provided about it being dpcalendar plugin in my case helps you...

**Comment by Bakual** [comment] 2017-07-06 13:35
@laoneo Maybe something for you since DPCalendar got mentioned :smile:

**Comment by onedego** [comment] 2017-07-06 14:34
I just disabled the DPCalendar Upcoming module in my site and it is working again...

**Comment by laoneo** [comment] 2017-07-06 14:48
Yes it's a bug in DPCalendar which got fixed in version 6.0.9 which was released today. Please upgrade to the latest version and then the error should be gone.

**Comment by onedego** [comment] 2017-07-06 14:50
Confirmed - updated and working fine.  Thanks to all and apologies.
