### ISSUE TITLE
mailtemplates are saved in database when editing language, results in malformed email

### ISSUE THREAD

**Issue by Pinkeltje** [joomla/joomla-cms#44143] opened 2024-09-26 09:07 UTC
### Steps to reproduce the issue
Set site language to your language (in my example nl-NL)
Edit mailtemplate for your language
Save mailtemplate

### Expected result
Use of language constants as defined in mailtemplate
![Schermafbeelding 2024-09-26 110040](https://github.com/user-attachments/assets/8d205084-ef55-46f9-8e73-0ce4baedb1f2)

### Actual result

![Schermafbeelding 2024-09-26 105347](https://github.com/user-attachments/assets/3da0f5a1-d154-4952-ba1c-fe604e4bc4c4)

### System information (as much as possible)
Joomla 5.1.4
PHP 8.2.12

### Additional comments
This is caused by the fact that mailtemplate for language is stored in database
![2024-09-26 Screenshot 623](https://github.com/user-attachments/assets/c211e79e-108a-492a-b631-3dc614db4e74)

When removing entry from database, result is ok again.
This issue was reported already several times
#43503 
#42353 
#39228

**Comment by Quy** [comment] 2024-09-26 15:28
Is this report a duplicate of #43503? If yes, please don't open multiple reports for the same issue. Thank you.

**Comment by Quy** [comment] 2024-09-27 22:16
Closing as duplicate.

**Closed as completed by Quy** 2024-09-27 22:16 UTC
Labels: No Code Attached Yet, Information Required
