### ISSUE TITLE
[4.0] installing: "LoginHelper" not found

### ISSUE THREAD

**Issue by stankurd** [joomla/joomla-cms#20828] opened 2018-06-21 15:05 UTC
### Steps to reproduce the issue
An error has occurred.
Class 'Joomla\Module\Login\Administrator\Helper\LoginHelper' not found

**Comment by carlitorweb** [comment] 2018-06-21 15:45
You have to delete the file `/libraries/autoload_psr4.php`. Or clone and install again the repo.

**Comment by ghost** [comment] 2018-06-21 16:33
Changed Title to explain whats the Issue is about.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20828">issues.joomla.org/tracker/joomla-cms/20828</a>.</sub>

**Comment by Quy** [comment] 2018-07-01 19:43
@brianteeman I assume this is the same issue as #20902.

**Comment by roland-d** [comment] 2018-07-01 19:44
@Quy As far as I can see, it is.

**Comment by brianteeman** [comment] 2018-07-01 19:45
yes its the same thing.

I am closing this as there is no bug to fix

**Closed as completed by brianteeman** 2018-07-01 19:45 UTC
Labels: No Code Attached Yet, J4 Issue
