### ISSUE TITLE
[3.9] Prevent authentication plugins to be disabled

### ISSUE THREAD

**Issue by joeforjoomla** [joomla/joomla-cms#31619] opened 2020-12-09 09:50 UTC
### Steps to reproduce the issue
Disable all authentication plugins installed

### Expected result
It's not possible to disable all authentication plugins

### Actual result
It's possible to disable all of them, as a result it's no longer possible to login to the backend, it's result in an authentication library error because no plugins are enabled

### System information (as much as possible)
Joomla 3.9.23

### Additional comments

![image](https://user-images.githubusercontent.com/17835460/101613661-50876080-3a0c-11eb-906e-b0ece2c31603.png)

**Comment by brianteeman** [comment] 2020-12-09 09:58
This is a known issue which is why the plugins all have warning text about this. If you can come up with a way to programmatically prevent the last authentication plugin from being disabled that would be awesome. Remember that there can be 3pd authentication plugins as well

**Comment by bembelimen** [comment] 2020-12-09 10:00
Especially that an easy check "are you the last publish auth plugin" is not enough, because at the end there could be an auth plugin left which still does not allow to login and the site is "broken".

**Comment by joeforjoomla** [comment] 2020-12-09 11:20
Just wanted to point out because a user contacted me for support being blocked to login to the backend. He thought that the problem was one extension of mine... but actually it's the Joomla core that allows a similar situation.

**Comment by PhilETaylor** [comment] 2020-12-16 16:59
I would vote for just changing the warning message to a more helpful "There are no authentication plugins enabled"

It is perfectly reasonable to expect/allow a site to operate with no authentication plugins enabled, should the admin/developer wish. The site might never be logged into and deployed using a deployment scheme from git or ci/cd processes. 

The plugin architecture has been abused so much (core/protected plugins that can never be disabled etc) that the original aim (that they could be enabled/disabled) has been lost.

**Comment by rdeutz** [comment] 2020-12-20 14:09
Closing because thie is expected behaviour.

**Closed as completed by rdeutz** 2020-12-20 14:09 UTC
Labels: No Code Attached Yet

**Comment by PhilETaylor** [comment] 2020-12-20 14:12
However this is yet another example of error messages showing the PHP class name and method ... these need to be nuked
