### ISSUE TITLE
JModelList::populateState() does not work in frontend

### ISSUE THREAD

**Issue by Hackwar** [joomla/joomla-cms#5350] opened 2014-12-08 15:30 UTC
If you have a component in the frontend that uses JModelList and calls the parent populateState method, the pagination will be overwritten by session data. That means that you can not move back to page 1 of a list of items. This should be changed so that it works identical in both front- and backend. Most likely it would be best to do this in the new MVC classes...

**Comment by brianteeman** [comment] 2015-01-01 15:42
Is this still an open issue then?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5350">issues.joomla.org/joomla-cms/5350</a>.</sub>

**Comment by Hackwar** [comment] 2015-01-01 17:07
This is indeed still an issue. While in the backend, you can do a parent::populateState() and have most stuff taken care of, this will break your component in the frontend and for example prevent pagination from working.

**Comment by brianteeman** [comment] 2015-01-13 21:06
Resetting to open<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5350">issues.joomla.org/joomla-cms/5350</a>.</sub>

**Comment by bcordis** [comment] 2015-01-16 11:17
Is anyone fixing this?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5350">issues.joomla.org/joomla-cms/5350</a>.</sub>

**Comment by Hackwar** [comment] 2015-01-16 11:27
I doubt that someone is working on this right now. It is not easy to solve, when I looked into it.

**Comment by itsam** [comment] 2015-02-16 18:33
I don't know if related but try to set e.g. limit = 2; directly to frontend populateState and see that nothing actually happens. The same goes for any other filter as well (e.g. catid). On the other hand, at backend everything works as expected. Please verify that problem indeed exists.

**Comment by Hackwar** [comment] 2015-02-16 18:45
The issue is, that the backend expects a form to be submitted via POST with the values when moving through the pagination, while the frontend uses GET URLs instead. This is not easily solvable currently. The best bet would be to fix this with new MVC classes.

**Comment by itsam** [comment] 2015-02-16 19:32
How do you explain the following:
        $limit = $app->getUserStateFromRequest('global.list.limit', 'limit', $app->getCfg('list_limit'));
        $limit = 2;
        $this->setState('list.limit', $limit);

I would expect to get only 2 items but that's not the case...
It's like parent::populateState overrides everything else...

Sorry if I miss the forest here but I am really confused

**Comment by Bakual** [comment] 2015-02-16 19:41
One difference between front- and backend is that the backend uses the session (UserState) to store the current value. That means if you don't pass a limit, the value from the session is used.

> It's like parent::populateState overrides everything else...

Yes, parent::populateState will set the limits again, overriding your value. See https://github.com/joomla/joomla-cms/blob/staging/libraries/legacy/model/list.php#L551

If you need to adjust them different in your extension, you need to do it after that call.

**Comment by bcordis** [comment] 2015-02-16 19:46
So is this a bug or we just need to abandon in are code the use of the set state?

**Comment by Bakual** [comment] 2015-02-16 20:13
It's not a bug that parent::populateState does set the limit. It's part of the job of that method.

You can set your own limits after you have called the parent method, or you just don't call it in your own method.

**Comment by roland-d** [comment] 2015-12-12 11:17
Hello @Hackwar 

Thank you for your contribution.

The last comment here was on February 17th. So the question is, Is this issue/pull request still valid?
If no reply is received within 4 weeks we will close this issue.

Thanks for understanding! <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5350">issues.joomla.org/joomla-cms/5350</a>.</sub>

**Comment by brianteeman** [comment] 2016-01-16 10:53
closed as per the last comment<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5350">issues.joomla.org/joomla-cms/5350</a>.</sub>

**Closed by brianteeman** 2016-01-16 10:53 UTC
Labels: No Code Attached Yet
