### ISSUE TITLE
[4.0] When moving child menus back and forth they don't sit well the second time

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-cms#25270] opened 2019-06-19 11:32 UTC
### Steps to reproduce the issue
Install J4
Install patch #25205 
Ensure you have two menus
Create a parent item in both
Create a child item on the first parent, then create a second child item on the first child
Move the first child item to the second parent item in the other menu
It should move and bring its own child with it

Move the first child item back to the first menu parent
Both items move, but they don't appear to be part of the parent but sit in limbo on the parent item root although indented, orphaned

### Expected result
Child moves to parent bringing all children (grandchildren?) with it

### Actual result
Items on the second move become menu item root with no parent but appear to have a parent as they are indented

### System information (as much as possible)
J4 Alpha 10

**Comment by brianteeman** [comment] 2019-12-29 21:38
From what I can tell the problem is that when you change the menu in the select then the menu items in that select dont update at the same time

**Comment by uglyeoin** [comment] 2019-12-29 22:12
Possibly you have described the problem better than I. Thank you.

**Comment by brianteeman** [comment] 2022-01-31 23:11
@uglyeoin dam - I remembered it but didnt find it when I created an issue the other day https://github.com/joomla/joomla-cms/issues/36893

Happy to close mine but as its newer perhaps it will get noticed and acted upon in which case can you close this one.

**Comment by Quy** [comment] 2022-02-02 23:47
Closing as duplicate. Thanks.

**Closed as completed by Quy** 2022-02-02 23:47 UTC
Labels: No Code Attached Yet, J4 Issue

**Comment by uglyeoin** [comment] 2022-02-03 14:41
Thanks both.  It makes no odds to me whether this is the one closed or the other one, hopefully it gets solved :)
