### ISSUE TITLE
Duplicate issue when using tags component as a menu item

### ISSUE THREAD

**Issue by Slava287** [joomla/joomla-cms#42770] opened 2024-02-07 10:48 UTC
### Steps to reproduce the issue 
if you add any numbers at the end, for example /55/

site: https://recepty.mobi/postnye-retsepty.html

### Expected result
So that when you open the site/menu-item-list-of-tags/55, a 404 error is displayed and not a duplicate.

### Actual result
The page is accessible and a duplicate is opening

### System information (as much as possible)
Joomla! 5.0.2 Stable [ Kuboresha ] 9-January-2024 16:00 GMT

### Additional comments

For some reason, this problem does not occur with all tag menu items. But when creating any new ones, a duplicate always appears.

For example, if you add /55/ https://recepty.mobi/novyj-god/salaty-k-novomu-godu.html for this page, then it will not have such a problem, but for some reason the page will still be accessible and will not return 404 error.

**Comment by Slava287** [comment] 2024-02-13 11:05
I found out that the problem is related to child tags, when they are enabled, there is a problem.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42770">issues.joomla.org/tracker/joomla-cms/42770</a>.</sub>

**Comment by Quy** [comment] 2024-05-29 05:17
Please close this issue if it is a duplicate of #43543.

**Closed as completed** 2024-05-31 21:17 UTC
Labels: No Code Attached Yet, Information Required, bug
