### ISSUE TITLE
Problem with Menu > URL (internal link)

### ISSUE THREAD

**Issue by BRoehling** [joomla/joomla-cms#29792] opened 2020-06-27 14:09 UTC
### Steps to reproduce the issue

if I enter index.php?option=com_content&view=article&id=5#section1 into the URL field of my menu > menu item, save it and refresh my homepage,
I will see that joomla changed my URL code changes to http://www.aaa.de/aaa/aaa/index.php?option=com_content&amp;view=article&amp;id=5&amp;Itemid=128#section1&amp;Itemid=120
in the browser.

### Expected result

http://www.aaa.de/aaa/aaa/index.php?option=com_content&view=article&=5&Itemid=120#section1

### Actual result

http://www.aaa.de/aaa/aaa/index.php?option=com_content&amp;view=article&amp;id=5&amp;Itemid=128#section1&amp;Itemid=120

### System information (as much as possible)

Joomla 3.9.19
Windows 10
Google Chrome

### Additional comments

is seems to be a problem with the ascii code-table for once because I'm getting &amp instead of &
and secondly joomla adds a second Itemid to the url.

Is it a bug or can it be solved somehow?

**Comment by Quy** [comment] 2020-07-16 18:28
Where are you seeing the `&` to `&amp;` conversion?  This is the expected behavior when viewing the page source/markup.

**Comment by BRoehling** [comment] 2020-07-17 05:40
Joomla 3.9.19 & 3.9.20 convert the **URL Type** string **from** http://www.aaa.de/aaa/aaa/index.php?option=com_content&view=article&=5&Itemid=120#section1 **to** http://www.aaa.de/aaa/aaa/index.php?option=com_content&amp;view=article&amp;id=5&amp;Itemid=128#section1&amp;Itemid=120 and that is not only in the source code inspector but also when I hover over the link on my homepage with a mouse.

Why I am using the URL Type? The answer is, to be able to scroll from my submenu link to a specific #anchor in my page. But it doesn't work with the 3.9.19 & 3.9.20 version/

**Comment by ReLater** [comment] 2020-07-17 07:15
The main issue here seems to be that the fragment `#section1` is not at the end of the "converted" URL.

`... #section1&amp;Itemid=120`

An Example with installed demo data "learning" in Joomla 3.9.21-dev:
- SEO on, URL rewrite on.
- Existing article with ID 5 (Title: "Authentication")
- This article has already a menu item "Authentication" (ID 318). But that's not too relevant here.
- When I create a menu item type `URL` with link

`index.php?option=com_content&view=article&id=5#section1`

- The output of Joomla is

`/using-joomla/extensions/plugins/authentication#section1&amp;Itemid=615`

- The trailing itemid is the id of the newly created URL item type.
- The fragment `#section1` is not at the end.

**Comment by brianteeman** [comment] 2020-07-17 07:27
> if I enter index.php?option=com_content&view=article&id=5#section1 into the URL field of my menu > menu item, save it and refresh my homepage,

That is your mistake as that is not the url. The url includes the itemid.

Personally I would recommend using the SEF url instead as its much easier.

For example the SEF url is www.example.com/contact

So I make the new menu url /contact#map or www.example.com/contact#map

Works perfectly

**Comment by ReLater** [comment] 2020-07-17 07:32
Whwn I debug my example item above inside helper.php of mod_menu then I get

```
[15] => Joomla\CMS\Menu\MenuItem Object
        (
            [id] => 615
            [menutype] => mainmenu
            [title] => URLtesten
            [alias] => url
            [note] => 
            [route] => url
            [link] => index.php?option=com_content&view=article&id=5#section1
            [type] => url
            [level] => 1
            [language] => *
            [browserNav] => 0
            [access] => 1
            [params:protected] => {"menu-anchor_title":"","menu-anchor_css":"","menu-anchor_rel":"","menu_image":"","menu_image_css":"","menu_text":1,"menu_show":1,"pageheader_suffix_ghsvs":"","page_subheading_ghsvs":"","mega-menu-ul-class":"","mega-menu-li-class":""}
            [home] => 0
            [img] =>  
            [template_style_id] => 0
            [component_id] => 0
            [parent_id] => 1
            [component] => 
            [tree] => Array
                (
                    [0] => 615
                )

            [query] => Array
                (
                    [option] => com_content
                    [view] => article
                    [id] => 5#section1
                )

        )
```
Look at the [query] block. The `[id] => 5#section1` looks weird somehow.

**Comment by BRoehling** [comment] 2020-07-17 07:35
it should be

[id] => 5
[anchor] => section1

right?

**Comment by ReLater** [comment] 2020-07-17 07:49
it should be

```
[id] => 5
[fragment] => section1
```

or something like that. I don't know. I always use the recommendation of brianteeman with hidden article menu items if I don't want them in my front end menu.

But the fragment should be kept always at the end of the url if the url is rebuilt; somehow...

**Comment by brianteeman** [comment] 2020-07-17 07:50
It makes no sense at all for you to be trying to build sef urls for this. Just do what I say and use the sefurl in the link

**Comment by BRoehling** [comment] 2020-07-17 07:59
I'll try brianteeman's recommendation with the sefurl.

**Comment by Quy** [comment] 2020-07-17 16:50
Closing per https://github.com/joomla/joomla-cms/issues/29797#issuecomment-660217213

**Closed as completed by Quy** 2020-07-17 16:50 UTC
Labels: No Code Attached Yet
