### ISSUE TITLE
Joomla update fails despite correct log and tmp path in configuration.php

### ISSUE THREAD

**Issue by esenpix** [joomla/joomla-cms#18153] opened 2017-09-28 17:43 UTC
![joomla-error](https://user-images.githubusercontent.com/6815387/30982345-62d619fc-a487-11e7-95fc-6b655739aaaa.PNG)
### Steps to reproduce the issue
This only happens, when you have in the backend under:

administration->configuration->server 
administration->configuration->system

a wrong path but if you have additionally in your configuration.php the correct paths in the variables $log_path and $tmp_path. If you then try to update your joomla version to e.g. joomla 3.8 then it promts the alert
JFolder::create: Das Verzeichnis kann nicht erstellt werden!

Joomla seems not to apply your configuration settings from the configurations.php fully.
If it is set in the backend wrong and in the configuration.php correct then it does NOT work.
You have to set it in the backend and in the configuration.php that means you have to do double work.

### Expected result
It is expected that if you change the configuration.php via ftp that joomla shows those parameters also in the backend.

### Actual result
JFolder::create: Das Verzeichnis kann nicht erstellt werden!

### System information (as much as possible)
Joomla 3.8
PHP 7
Firefox 55.0.3

**Comment by brianteeman** [comment] 2017-09-28 18:05
As those backend views just read the configuration.php file when it is displayed I cannot see how anything other than your expected result is possible

**Comment by esenpix** [comment] 2017-09-28 18:16
Thats the point. The backend is not reading the configuration.php when the parameters  $log_path and $tmp_path in the configuration.php is changed. It still keeps the old log and temp paths from the backend which causes an error when you try to update joomla.

**Comment by brianteeman** [comment] 2017-09-28 18:23
thats simply not possible - at least i cannot see how

**Comment by esenpix** [comment] 2017-09-28 18:29
But some other users had also the same problem: 

http://www.joomlaportal.de/allgemeine-fragen-zu-joomla-1-5/266167-jfolder-create-das-verzeichnis-kann-nicht-erstellt-werden.html

Seems the problem exists since Joomla 1.5

![joomla-error2](https://user-images.githubusercontent.com/6815387/30983752-98ed8a4e-a48b-11e7-8814-866bad1d705e.PNG)

**Comment by brianteeman** [comment] 2017-09-28 18:34
No it doesnt - the problem is that you have all missed one thing when you did the ftp. You will see that your changed file did NOT get uploaded due to a permissions issue.

**Comment by AndySDH** [comment] 2017-09-28 20:11
> No it doesnt - the problem is that you have all missed one thing when you did the ftp. You will see that your changed file did NOT get uploaded due to a permissions issue.

Classic.

@esenpix The configuration.php cannot just be uploaded and overwritten for permissions restrictions. You need to delete it from the server or change permissions before you can re-upload it, if you want to customize it manually. Otherwise it won't get overwritten.

**Comment by wojsmol** [comment] 2017-09-29 03:49
@AndySDH AFAIK Joomla! changes only chmod of configuration.php do 444 Chmod can be easily quenched using FTP client.

**Comment by brianteeman** [comment] 2017-09-29 13:11
I am closing this as it is a user error not a joomla error

**Closed as completed by brianteeman** 2017-09-29 13:11 UTC
Labels: No Code Attached Yet
