### ISSUE TITLE
Saving item in filtered list (Admin) returns to Page 1 of list

### ISSUE THREAD

**Issue by Bodge-IT** [joomla/joomla-cms#10822] opened 2016-06-15 09:26 UTC
#### Steps to reproduce the issue
Filter articles using categories(not tested with other filters).  Saving & Closing an item in the list on a page > page 1

#### Expected result
That you are returned to the same page of your filtered list

#### Actual result
You are returned to page 1 of the filtered list

#### Additional comments
The expected behaviour is present on unfiltered lists.

**Comment by andrepereiradasilva** [comment] 2016-06-15 10:50
in articles categories, whent to page 2 in the list view, clicked to edit a item, then save & close, returned to page 2 in the view.

So can't reproduce this in latest staging / 3.6.0 beta 1

**Comment by andrepereiradasilva** [comment] 2016-06-15 10:51
ok sorry i misunderstood. I CAN reproduce.

in articles ~list, filter by a categorie, whent to page 2 in the list view, clicked to edit a item, then save & close, returned to page 1 in the view.

**Comment by andrepereiradasilva** [comment] 2016-06-15 10:57
Just aditional info one this.

If you: in articles list, filter by a category, whent to page 2 in the list view, go to another menu and then return to article list menu, you'll have the same problem.

So the issue is the current page is not being saved.

**Comment by bertmert** [comment] 2016-06-15 11:36
This is a known issue for a long time now.
Starting here:
https://github.com/joomla/joomla-cms/pull/7052
you'll find remarks concerning pagination resets.
https://github.com/joomla/joomla-cms/pull/7052#issuecomment-106660771

I still don't know why pagination must be resetted (Hathor again?). It worked fine without resets ;-)

**Comment by Bodge-IT** [comment] 2016-06-16 08:40
Yes but #7052 is now closed and has missed this secondary issue with pagination.  Getting to page 2 now fixed, staying on it after saving isn't.

**Comment by bertmert** [comment] 2016-06-16 15:49
I know. 

Pls. read comments
https://github.com/joomla/joomla-cms/pull/7052#issuecomment-106336701

> It works, but has the downside that it also no longer resets the pagination if you change the search filter. It will stay on the last selected page.

https://github.com/joomla/joomla-cms/pull/7052#issuecomment-107078799

> I still think it's not a correct fix. It fixes one thing and breaks another one (resetting pagination when filter changes).

> I still don't know why pagination must be resetted (Hathor again?).
I never got an answer why this is a must. As I said already it worked fine while I was testing 7052 and I would prefer NOT to reset pagination, too.

**Comment by wilsonge** [comment] 2016-06-21 21:00
Closing as we have a PR in #10897

**Closed by wilsonge** 2016-06-21 21:00 UTC
Labels: No Code Attached Yet
