### ISSUE TITLE
Bug in URL routing in Joomla 3.7.5 and Joomla 3.8.0 beta 3

### ISSUE THREAD

**Issue by arrowthemes** [joomla/joomla-cms#17719] opened 2017-08-25 15:23 UTC
### Steps to reproduce the issue
1. Install a clean Joomla installation with 3.7.5 or Joomla 3.8.0 beta 3 with no sample data
2. Create the following menu structure
<img src="https://preview.ibb.co/jVhEu5/menu_structure_2.png" alt="menu_structure">
3. Turn off Search Engine Friendly URLs in Global Configuration
4. Go to the front-end and click on the menu as follows:
a) Click on Style 1
b) Click on Style 2
c) Click on Style 2 the second time

### Expected result
a) The URL when you click on Style 1 is: index.php?option=com_content&view=article&id=1&Itemid=104
b) The URL when you click on Style 2 is: index.php?option=com_content&view=article&id=1&Itemid=105 
c) The URL when you click on Style 2 the second time should still be index.php?option=com_content&view=article&id=1&Itemid=105 

### Actual result
a) The URL when you click on Style 1 is: index.php?option=com_content&view=article&id=1&Itemid=104 (see screenshot)
<img src="https://preview.ibb.co/mFvngk/style_1_clicked.png" alt="style_1_clicked">
b) The URL when you click on Style 2 is: index.php?option=com_content&view=article&id=1&Itemid=105 (see screenshot)
<img src="https://preview.ibb.co/jnXB7Q/style_2_clicked_once.png" alt="style_2_clicked_once">
c) The URL when you click on Style 2 the second time is index.php?option=com_content&view=article&id=1&Itemid=104 (see screenshot)
<img src="https://preview.ibb.co/mOP2E5/style_2_clicked_second_time.png" alt="style_2_clicked_second_time">

### System information (as much as possible)
=============
System Information
=============
dbversion: 5.6.35
dbcollation: utf8_general_ci
dbconnectioncollation: utf8mb4_general_ci
phpversion: 7.1.6
server: Apache
sapi_name: apache2handler
version: Joomla! 3.8.0-beta3 Beta [ Amani ] 22-August-2017 14:00 GMT
platform: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36

### Additional comments
If you enable Search Engine URL, the issue doesn't ok.

**Comment by brianteeman** [comment] 2017-08-25 15:40
Do you get the same problem when you are linking to different articles. I suspect the problem is you are trying to create duplicate views of the same article to showcase your template.

**Comment by mbabker** [comment] 2017-08-25 15:44
There are several open issues related to having multiple menu items pointing to the same piece of content.

**Comment by arrowthemes** [comment] 2017-08-25 15:45
@brianteeman That's the case but I've encountered real world scenarios where I'd want to link to the same article but just change the modules for the url.
When I link to different articles, the issue does not occur

**Comment by brianteeman** [comment] 2017-08-25 16:51
First people complain about joomla creating duplicate content and then they moan that it wont let them create duplicate content #cantwin

**Comment by arrowthemes** [comment] 2017-08-26 07:27
@brianteeman 
Most template frameworks allow you to hide the article completely. So in that case you won't have duplicate content and that's what I mean.
Take for instance a site I did for [LogicalDOC](https://www.logicaldoc.com/). The home page is built of modules only - but the home menu is linked to a placeholder article. The [overview](https://www.logicaldoc.com/product/overview) page works the same way - built of modules only and linked to the same placeholder article. If I disabled SEF URLs then clicking on overview twice would take me to another page with a different itemid.

If you enable Search Engine Friendly URLs, the issue doesn't occur, so it will be nice to have a consistent expected result. This to me is not a must have; If you feel it's not worth looking into it, that's pretty fine with me.

**Comment by Bakual** [comment] 2017-08-26 09:01
It's not a problem to have the same article accessible under multiple URLs. Duplicate Content is only an issue if it is spread over different domains. But facts never counted, people believe what they want 😀

**Comment by Twincarb** [comment] 2017-08-27 15:20
Having the same content at 2 separate URL's with different templates causes the both URL's to use the lower itemid number as well. The workaround is to have the same content duplicated which makes each one unique.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17719">issues.joomla.org/tracker/joomla-cms/17719</a>.</sub>

**Comment by ggppdk** [comment] 2017-08-27 15:31
> If you enable Search Engine Friendly URLs, the issue doesn't occur, so it will be nice to have a consistent expected result. 

ok it should be consistent,
router selecting different Itemid when SEF urls is off, is surely a bug
and makes testing web-sites with SEF off problematic

and even if this appeared with both SEF on / off, it is still a bug,
since it changes expected behaviour of every menu item being able to use its own Itemid !

and reasons for having 2 menu items to same content have been already mentioned above

**Comment by ghost** [comment] 2017-08-28 15:35
closed as having Pull Request #17746 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17719">issues.joomla.org/tracker/joomla-cms/17719</a>.</sub>

**Closed as completed by ghost** 2017-08-28 15:35 UTC
Labels: No Code Attached Yet
