### ISSUE TITLE
Custom Fields not rendering in Smart Search results

### ISSUE THREAD

**Issue by afri-can** [joomla/joomla-cms#17557] opened 2017-08-16 06:53 UTC
### Steps to reproduce the issue
Used Custom Fields to add content to article, Used Manual Display, {field 1} etc... to call the custom field into the article's grid

### Expected result
The fields shows up on the page in frontend and should show in search result

### Actual result
now getting {field x} in my Smart Search's Snippets (see attached)

### System information (as much as possible)
La![screen shot 2017-08-16 at 06 47 54](https://issues.joomla.org/uploads/1/78afe6636b4db787b463066e81451738.jpg)test Joomla 3.7.4

**Comment by laoneo** [comment] 2017-08-19 08:32
Guess this one is similar to #17175, the on content prepare event is not triggered.

**Comment by ghost** [comment] 2017-08-19 09:07
closed as stated above. Please reopen if guess isn't correct.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17557">issues.joomla.org/tracker/joomla-cms/17557</a>.</sub>

**Comment by laoneo** [comment] 2017-08-19 10:09
Please reopen, my comment was just a hint where to search.

**Comment by afri-can** [comment] 2017-10-19 07:35
Any news on this cannot really us custom fields if they do not appear correctly on search results<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17557">issues.joomla.org/tracker/joomla-cms/17557</a>.</sub>

**Comment by laoneo** [comment] 2017-10-23 09:13
Had a look on the code, @Bakual any idea why the plugin [does not](https://github.com/joomla/joomla-cms/blob/staging/plugins/content/fields/fields.php#L35) run on the indexer as the content event is fired properly?

**Comment by Bakual** [comment] 2017-10-23 09:36
The issue is that com_finder calls the event with its own context ('com_finder.indexer'). See https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_finder/helpers/indexer/helper.php#L500

**Comment by laoneo** [comment] 2017-10-23 09:39
I saw that, but this can be handled in the fields content plugin itself. I thought it would crash as it is run on the back end in the indexer.

**Comment by Bakual** [comment] 2017-10-23 09:51
The plugin event is called, but it doesn't find any fields due to the wrong context.

**Comment by laoneo** [comment] 2017-10-24 10:01
Please test #18402 which should fix the issue.

**Comment by ghost** [comment] 2017-10-24 10:13
closed as having Pull Request #18402

**Closed as completed** 2017-10-24 10:13 UTC
Labels: No Code Attached Yet

**Comment by afri-can** [comment] 2017-10-24 10:40
I am new to this forum, so if someone could please explain, "so please test #18402 which should fix issue", means I go to #18402 and implement the 4 changes to the four files mentioned and this will fix the issue, how do I know when the changes will be implemented to the Joomla core?

**Comment by ghost** [comment] 2017-10-24 10:44
@afri-can please read https://docs.joomla.org/Bug_Tracking_Process and test on a dev-Enviroment using [Patchtester](https://github.com/joomla-extensions/patchtester).

If a Pull Request have at least 2 successfully Test Release Lead decide if its merged in next Release.
