### ISSUE TITLE
com_tags Joomla 3.4 - do not shows category image in front end

### ISSUE THREAD

**Issue by goshalviv** [joomla/joomla-cms#6331] opened 2015-03-06 09:20 UTC
If in menu item sets "Article Categories"
On front end category image do not show. For "Article" image show work propertly.

**Comment by goshalviv** [comment] 2015-03-06 09:25
If I print_r($item), variable "core_images" it was empty.

**Comment by Harmageddon** [comment] 2015-03-11 13:52
I can confirm this. The problem is, that article images are stored in the column "images" (or "core_images" in ucm_content), whereas the category image is stored as a param in the "params" column ("core_params" in ucm_content).

However, I still don't figure out everything that com_tags is doing when saving an article. On first glance, one possibility to fix this would be making com_content and com_categories more consistent and make both store their images the same way. The other could be a dirty fix inside com_tags to check for images inside params, too.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6331">issues.joomla.org/joomla-cms/6331</a>.</sub>

**Comment by bertmert** [comment] 2015-05-27 07:56
@goshalviv 
Do you want to test this PR https://github.com/joomla/joomla-cms/pull/6792 ?
It's related to your feature request because without it it's not possible to pick images from core_params at all e.g. of categories, some other items than articles and so on.
Detailed test instructions: https://github.com/joomla/joomla-cms/pull/6792#issuecomment-104980292

Testing it successfully would be a step forward.

**Comment by n9iels** [comment] 2015-10-10 15:17
I don't have problem with the category images, so it seems like this issue is solved now.

If this issue is fixed indeed, please close this issue :)

**Comment by Harmageddon** [comment] 2015-10-12 09:43
@n9iels The issue still exists for me with current staging branch. Just to clarify, I'll add some testing instructions here.

### Testing instructions
1. Create a tag, e.g. "Red".
2. Create or edit an article:
  - Add the previously created tag.
  - Add an intro image.
  - Save.
3. Create or edit a category:
  - Add the previously created tag.
  - Add an image (under "options").
  - Save.
4. Create a menu item:
  - Type: Tagged Items
  - Tag: "Red" (your tag)
  - Content type: "Article"
  - Item Options - Item Image: Show (or set this option in the global options).
5. Create a menu item:
  - Type: Tagged Items
  - Tag: "Red" (your tag)
  - Content type: "Category"
  - Item Options - Item Image: Show (or set this option in the global options).
6. Compare both menu item views in frontend. The article one displays the item/intro image, while the category one doesn't display any image.

**Comment by n9iels** [comment] 2015-10-12 09:59
Thanks for provide this test instructions! I confirmed the issue, and will try to find a solution.

**Comment by Kubik-Rubik** [comment] 2016-05-08 16:58
@n9iels Could you find a solution for this issue?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6331">issues.joomla.org/joomla-cms/6331</a>.</sub>

**Comment by franz-wohlkoenig** [comment] 2017-01-28 15:45
this Issue exists.

**Comment by tonypartridge** [comment] 2017-03-19 09:52
@franz-wohlkoenig can you please test?

https://github.com/joomla/joomla-cms/pull/14747

**Comment by tonypartridge** [comment] 2017-03-23 22:53
@goshalviv @Kubik-Rubik @n9iels there is a pull request in waiting to be tested! See my above comment.

**Comment by brianteeman** [comment] 2017-05-20 09:06
i am closing this as #14747 was merged to address this issue

**Closed by brianteeman** 2017-05-20 09:06 UTC
Labels: No Code Attached Yet
