### ISSUE TITLE
[5.0]  DateTime::__construct(): Passing null to parameter 

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#41998] opened 2023-09-29 21:50 UTC
### Steps to reproduce the issue
php 8.1
install the testing sample data
go to
` /index.php/news-feeds-component/feed-display-module`

### Expected result
no errors, warnings or notices

### Actual result
`Deprecated: DateTime::__construct(): Passing null to parameter #1 ($datetime) of type string is deprecated in libraries\src\Date\Date.php on line 126`

![image](https://github.com/joomla/joomla-cms/assets/1296369/1f317e5e-6dce-4d5c-ba0a-ece4ec1592da)

### Additional comments
There are quite a few closed issues about this.

**Comment by richard67** [comment] 2023-10-05 15:21
@brianteeman Does this also happen with your PR #42000 applied?

**Comment by brianteeman** [comment] 2023-10-05 16:49
good point I will check. Also realised later and forgot to restest but it might actually be a problem with the sample data.

**Comment by richard67** [comment] 2023-10-05 16:54
Well that was my idea, to see if it comes from sample data or from the module itself.

**Comment by richard67** [comment] 2023-10-05 16:56
Of course it still can be the one or the other when it can be reproduced with the other PR applied, but maybe it gives us a better idea where it could come from.

**Comment by brianteeman** [comment] 2023-10-05 17:02
Found it.

**Comment by richard67** [comment] 2023-10-05 17:17
Well I would assume it is the `$feed->publishedDate` not being set here: https://github.com/joomla/joomla-cms/blob/5.0-dev/modules/mod_feed/tmpl/default.php#L64 .

**Comment by brianteeman** [comment] 2023-10-05 17:18
So this is what causes the problem. Someone else can decide the best fix.

The module params in the sampledata does NOT have a value for rssdate. It should have a value of 0 or 1.

The default value for the rssdate field in the xml is 0

When the module is displayed this line checks to see if the date should be displayed

`<?php if ($params->get('rssdate', 1)) : ?>`

But as it has neither value it tries to display the date and its empty so you get the reported error.

This could be fixed by adding the param in the sampledata.
A feed module created in the normal way in the module manager will always be ok has it writes a default value.

But in my gut that would not be a proper fix.

**Comment by richard67** [comment] 2023-10-05 17:18
... or the `$feed[$i]->publishedDate` here: https://github.com/joomla/joomla-cms/blob/5.0-dev/modules/mod_feed/tmpl/default.php#L100

**Comment by richard67** [comment] 2023-10-05 17:22
For now I would say let's fix the sample data so it reads the parameters `rssdate` with default 1 and `rssitemdate` with default 0.

**Comment by brianteeman** [comment] 2023-10-05 17:25
are you sure? if thats the approach then it could still happen for anyone creating modules in the same way. the testing sample data is only used internally and not on released sites so its not urgent to fix that

**Comment by richard67** [comment] 2023-10-05 17:26
> are you sure? if thats the approach then it could still happen for anyone creating modules in the same way. the testing sample data is only used internally and not on released sites so its not urgent to fix that

I don't have a better idea right now. But maybe it's just because I am too tired already.

**Comment by richard67** [comment] 2023-10-05 17:27
Alternatively we could fix the module so it doesn't show call the html helper and doesn't show these dates when they are empty?

**Comment by richard67** [comment] 2023-10-05 19:50
Closing as having a pull request.

**Closed as completed by richard67** 2023-10-05 19:50 UTC
Labels: No Code Attached Yet, PHP 8.x
