### ISSUE TITLE
404 Error after upgrade 3.8.2 > 3.8.3

### ISSUE THREAD

**Issue by DJSmy** [joomla/joomla-cms#19083] opened 2017-12-16 00:17 UTC
Prior to the upgrade my Jumi links worked fine. Right after the upgrade while I was snooping around the site that I have under development I discovered that an Application module I wrote is not broke. The first call to the module works, however, within that module are php requires that are failing. It seems that all the form post actions need to have the entire url with router to function whereas before they only required the alias.

The error I am getting is 
#404 View not found [name, type, prefix]: select, html, contentView 
and it is caused by not recognizing the module call by it's alias (char-manager in this case).

Joomla 3.8.3 on Apache2.4 with php 5.6 and Ubuntu 14.04

Here is some further clarification: I updated from 3.8.2 to 3.8.3. I made no change to the configuration, nor any other change, just clicked update. After the update:
All router portion of the URL are exposed,
Modules cannot be called by their alias in links,
This issue is not just Jumi, it is prevalent in other modules as well.

I uploaded my 3.8.2 from my localhost and the site works and functions as expected. I made some changes to it the last couple of days so to further test this issue, tonight (or tomorrow) I am going to FTP download the entire site and dump the databases. I will then click on the update link to 3.8.3 again and try to document everything. If you are interested in the site it is https://www.play-rsc.com. I upgraded the site (see below).

![screenshot_34](https://user-images.githubusercontent.com/31643237/34187936-ae70896e-e4e8-11e7-8713-96cfb2067fbc.png)

**Comment by ghost** [comment] 2017-12-16 06:43
Please ask help on the [forums - Migrating and Upgrading to Joomla! 3.x](https://forum.joomla.org/viewforum.php?f=710). This repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.

**Comment by DJSmy** [comment] 2017-12-16 06:48
It really seems to be a Joomla issue and not a plugin issue. It works fine on 3.8.2 and not 3.8.3 so somewhere something went wrong. Just as the URLs were not shown as they are now.

________________________________

**Comment by ghost** [comment] 2017-12-16 06:50
Reopened as its an update from 3.8.2 > 3.8.3. and not as i guessed from an earlier Version.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19083">issues.joomla.org/tracker/joomla-cms/19083</a>.</sub>

**Comment by DJSmy** [comment] 2017-12-16 06:53
To clarify a little further it was an auto update from the site. I am trying (and will continue) to find the work around or the cause tomorrow. If I find anything I will let you guys know.

Thank you,


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by ghost** [comment] 2017-12-16 06:54
changed the Title so its clear which Update is about.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19083">issues.joomla.org/tracker/joomla-cms/19083</a>.</sub>

**Comment by ghost** [comment] 2017-12-16 06:56
@DJSmy thanks for your Information. Can you please give all Informations in your first Comment so People can find them in one Place? If you open an Issue there are Subheads like "Steps to reproduce the issue", ... which help others to understand the Issue, thanks.

**Comment by anuragteapot** [comment] 2017-12-16 07:01
@DJSmy Yes, can you provide a  Steps to reproduce the issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19083">issues.joomla.org/tracker/joomla-cms/19083</a>.</sub>

**Comment by bobmats** [comment] 2017-12-18 14:13
Have the same problem on my vps and did some testing.

Tried php 7 and 7.1 php-fpm

Installed a new joomla installation thru instalatron, new page gave error
Switched back to php 5.6 installed a new  joomla 3.8 this worked fine
Switched back to php 7.1 and the version installed under 5.6 work work in php 7.1

On one website I changed back to php 5.6 existing 3.8.2 website would not display
Would do installatron update to 3.8.3 and website would load.
Switched back to php 7.1 and update to 3.8.3 worked fine

Did the same on another domain and this does not work.
Seems to be a php issue, very strange.
Have disabled autoupdate to 3.8.3 on 5 websites and reverted them to 3.8.2 (working)

**Comment by tonypartridge** [comment] 2017-12-19 21:37
So is the issue with the core or jumi links? 

How can we attempt to recreate it to Debug?

**Comment by DJSmy** [comment] 2017-12-20 02:08
Here is some further clarification: I updated from 3.8.2 to 3.8.3. I made no change to the configuration, nor any other change, just clicked update. After the update:
All router portion of the URL are exposed, 
Modules cannot be called by their alias in links,
This issue is not just Jumi, it is prevalent in other modules as well.

I uploaded my 3.8.2 from my localhost, it functions as expected. I made some changes to it so to further test this issue, tonight (or tomorrow) I am going to FTP down the entire site and dump the databases. I will then click on the update link to 3.8.3 again and try to document everything. If you are interested in the site it is https://www.play-rsc.com

**Comment by DJSmy** [comment] 2017-12-20 02:11
![screenshot_34](https://user-images.githubusercontent.com/31643237/34187814-11a120bc-e4e8-11e7-8f28-5dce0d0db764.png)

**Comment by tonypartridge** [comment] 2017-12-20 09:19
Please check you Joomla! Config is still setup correctly and that you have a .htaccess file. What your saying sounds like similar problems to the above.

**Comment by ghost** [comment] 2017-12-29 09:42
Any Updates @DJSmy @bobmats?

**Comment by Sophist-UK** [comment] 2017-12-30 10:16
I have a similar problem (using Fabrik).

Fabrik's legacy router is not being passed all menu items so that it can decode a URL which is a menu item followed by additional segments. 

I have several very similar menu items, and all but one of them work - so my guess is that it is a boundary issue on a loop - though I have not been able to track it down further as yet.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19083">issues.joomla.org/tracker/joomla-cms/19083</a>.</sub>

**Comment by Sophist-UK** [comment] 2017-12-30 10:18
I should add it works fine with J's standard SEF set OFF, and breaks for the one menu item when SEF is set on.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19083">issues.joomla.org/tracker/joomla-cms/19083</a>.</sub>

**Comment by brianteeman** [comment] 2018-01-08 09:53
@djsmy and @bobmats cant have the same problem - or at least not the same cause as the problem for @bobmats was resolved by switching php version and the version that worked was the same version that @DJSmy reported to be using.

Based on the information provided it is impossible to debug from this end

**Comment by Quy** [comment] 2018-01-25 02:22
@franz-wohlkoenig This should be closed and be in [Joomla Forums](https://forum.joomla.org/viewforum.php?f=710) for more details to debug.

**Comment by ghost** [comment] 2018-01-25 06:37
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19083">issues.joomla.org/tracker/joomla-cms/19083</a>.</sub>

**Closed as completed by ghost** 2018-01-25 06:37 UTC
Labels: No Code Attached Yet
