### ISSUE TITLE
Missing Empty trash button when status filter is set to "All"

### ISSUE THREAD

**Issue by RonakParmar** [joomla/joomla-cms#11187] opened 2016-07-19 06:25 UTC
#### Steps to reproduce the issue
Go to Article Manager at administrator side.
- Set "Trashed" in Status Filter option, you can see "Empty trash" button.
- Set "All" in Status Filter option, "Empty trash" button is not there.

#### Expected result
Toolbar should have "Empty trash" button, because we have trashed articles and if want to remove them, we must have to apply "Trashed" filter. 

#### Actual result
No "Empty trash" button when Status Filter set to "All".

#### System information (as much as possible)
Joomla! 3.6.1-dev Development [ Noether ] 13-July-2016 10:08 GMT

**Comment by RonakParmar** [comment] 2016-07-19 06:27
![screen shot 2016-07-19 at 01 27 06](https://issues.joomla.org/uploads/1/b2bc3c8a58b1aad5b8e2afec89dbc0a2.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11187">issues.joomla.org/joomla-cms/11187</a>.</sub>

**Comment by SharkyKZ** [comment] 2016-07-19 06:56
This is intended behavior. Note that empty trash button requires to make a selection. So making the proposed change raises some usability concerns. For instance, what would happen when a mix of trashed and non-trashed items are selected for deletion?

**Comment by brianteeman** [comment] 2016-07-19 10:08
Closed as expected behaviour - the "empty trash" should correctly only display when ONLY trashed items are displayed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11187">issues.joomla.org/joomla-cms/11187</a>.</sub>

**Closed by brianteeman** 2016-07-19 10:08 UTC
Labels: No Code Attached Yet

**Comment by RonakParmar** [comment] 2016-07-19 10:09
It is user responsibility to make proper selection of items for deletion.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11187">issues.joomla.org/joomla-cms/11187</a>.</sub>
