### ISSUE TITLE
2nd search filter adds data into URL which stops results showing

### ISSUE THREAD

**Issue by RustyIngles** [joomla/joomla-cms#40777] opened 2023-06-15 15:06 UTC
### Steps to reproduce the issue

In Joomla 4.x setup a filter:

Smart Search > Filters > New

Add a title (Test 1), toggle the relevant content maps

Click 'Save & Close'

Setup a new Smart Search > Search menu item and select the above filter.

Run through the process again, but this time add a different title (Test 2) and toggle a different set of content maps.

Index the content.

When going to the frontend, the 'Test 1' search menu item will return results, but when going to the 'Test 2' item no results will be returned.

### Expected result

Both should return a different set of results depending on the content filters.

### Actual result

The first result works but the second search doesn't and it includes "&f=2" in the URL. If this is removed, then the search results are shown.

### System information (as much as possible)

Setting	Value
PHP Built On	Linux www 5.15.0-60-generic #66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64
Database Type	mysql
Database Version	8.0.33-0ubuntu0.22.04.2
Database Collation	utf8mb4_0900_ai_ci
Database Connection Collation	utf8mb4_0900_ai_ci
Database Connection Encryption	None
Database Server Supports Connection Encryption	Yes
PHP Version	8.1.16
Web Server	Apache/2.4.54
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 4.3.2 Stable [ Bora ] 30-May-2023 16:00 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

**Comment by footsteps-design** [comment] 2023-06-15 15:42
Thanks for adding this bug report @RustyIngles. I found this issue myself today. If anyone can shed any light I'd very much appreciate it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40777">issues.joomla.org/tracker/joomla-cms/40777</a>.</sub>

**Comment by sergiovaldi** [comment] 2023-07-10 13:47
In the site modules I set "start publishing date" --> to today's date and now it works.... <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40777">issues.joomla.org/tracker/joomla-cms/40777</a>.</sub>

**Comment by SniperSister** [comment] 2023-08-26 14:14
@RustyIngles please verify that this is not a duplicate of the issue fixed in #40687

**Comment by Hackwar** [comment] 2023-08-28 20:05
This is the bug from #39751 and thus has been fixed.

**Closed as completed by Hackwar** 2023-08-28 20:05 UTC
Labels: No Code Attached Yet, PBF, bug
