### ISSUE TITLE
[5.0] External Newsfeeds not displayed

### ISSUE THREAD

**Issue by dautrich** [joomla/joomla-cms#42175] opened 2023-10-19 10:21 UTC
### Steps to reproduce the issue

1. Choose an arbitrary RSS Feed (i.e. Stadt Wächtersbach, displayed in Thunderbird)
   
![RSS_Feed](https://github.com/joomla/joomla-cms/assets/7933215/39782a75-c68b-495b-8fd0-7719001e0d11)

2. In Joomla 5.0.0 backend, navigate to  Components - News Feeds - Feeds

3. Add a new Newsfeed as in the screenshots below

![New_Newsfeed](https://github.com/joomla/joomla-cms/assets/7933215/1861710b-9632-49ec-a93e-7f874d55457b)
![grafik](https://github.com/joomla/joomla-cms/assets/7933215/6300ab4f-0ffe-4e35-8ff2-aa16038c50de)
   Save and close

4. Create a new menu item of type Single Newsfeed as in the screenshot below
![Create_Menuitem](https://github.com/joomla/joomla-cms/assets/7933215/1dbfc31a-8859-4269-b04e-ba01869d6d05)
    Save and close

5. Open frontend and click on menu item "News Feed Wächtersbach"

### Expected result
The first 5 posts from the newsfeed of Stadt Wächtersbach are displayed.

### Actual result
An error message is displayed: "Error. Feed could not be retrieved. "

![Frontend](https://github.com/joomla/joomla-cms/assets/7933215/f78690c3-a54f-4ce4-bb39-5c06a53da853)

### System information (as much as possible)

Joomla 5.0.0
PHP 8.2.
MySQL 8.0.33

Fresh Joomla installation without any other content or extensions.

**Comment by brianteeman** [comment] 2023-10-19 10:53
Unable to replicate with multiple feeds including https://lorem-rss.herokuapp.com/

**Comment by dautrich** [comment] 2023-10-19 11:06
The issue seems to exist with the specific feed I used as an example. Using a feed created from one of my sites, the feed is displayed:
![grafik](https://github.com/joomla/joomla-cms/assets/7933215/8cb0294e-3a66-42f5-b0d7-d264abede50e)

**Comment by brianteeman** [comment] 2023-10-19 11:08
can you share a link to that feed then

**Comment by dautrich** [comment] 2023-10-19 11:18
Here is the start of the feed:
![grafik](https://github.com/joomla/joomla-cms/assets/7933215/5e3c022d-9330-441e-90af-0755edc0835f)

**Comment by brianteeman** [comment] 2023-10-19 11:40
Works fine from here
![image](https://github.com/joomla/joomla-cms/assets/1296369/9bc63194-f93a-40b4-bea7-c4c4d0074ab1)

**Comment by dautrich** [comment] 2023-10-19 11:44
@brianteeman 
So, what's wrong with my installations. The feed doesn't display under J5.0.0 on two completely different installations: 
- A freshly set up J5.0.0 with no other content,
- My complex website updated to J5.0.0 (in a testdomain).

**Comment by brianteeman** [comment] 2023-10-19 11:47
No idea as I am not sat in front of your computer. Could even be that the feed provider has blocked your ip address

**Comment by dautrich** [comment] 2023-10-19 11:52
@brianteeman
> "Could even be that the feed provider has blocked your ip address"
No, I work closely together with them. I don't think that they would ever block an IP address.

**Comment by HLeithner** [comment] 2023-10-19 12:17
hmm works for me too on a fresh joomla 5.0 installation same out put as brian.

Feed could not be retrieved could have several reasons, could you activate debug mode and see if you get any useful information?

**Comment by dautrich** [comment] 2023-10-19 13:39
@HLeithner 
I can do so, but I'm not particularly good at interpreting debug mode displays. Would you like to look yourself? If yes, I can add a superuser account to both my testsites.

**Comment by brianteeman** [comment] 2023-10-19 13:39
either way this is not a core joomla bug and should be closed here and moved elsewhere which is targetted at user support

**Comment by dautrich** [comment] 2023-10-19 13:42
@brianteeman 
I don't completely agree. My setup has been working in numerous Joomla versions, up to and including J4.4.0. I didn't change the setup, only updated to J5.0.0. There must be a reason for that. 
And I verified the issue in a fresh J5 installation.

**Comment by HLeithner** [comment] 2023-10-19 13:45
@dautrich contact me at harald.leithner@community.joomla.org

**Comment by HLeithner** [comment] 2023-10-19 13:46
it's likley not a joomla issue but if it works on the same server with 4.4 and not with 5.0 looks like a regression, we will see.

**Comment by HLeithner** [comment] 2023-10-22 11:11
I checked your site and get the following out of curl for debugging:

```
*   Trying 80.69.201.211:443...
* Connected to www.stadt-waechtersbach.de (80.69.201.211) port 443 (#0)
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=www.stadt-waechtersbach.de
*  start date: Dec 29 00:00:00 2022 GMT
*  expire date: Dec 29 23:59:59 2023 GMT
*  subjectAltName: host "www.stadt-waechtersbach.de" matched cert's "www.stadt-waechtersbach.de"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=Sectigo Limited; CN=Sectigo RSA Domain Validation Secure Server CA
*  SSL certificate verify ok.
> GET /service/news-feed-der-stadt-waechtersbach/rss.xml HTTP/1.1
Host: www.stadt-waechtersbach.de
Accept: */*

* old SSL session ID is stale, removing
* Mark bundle as not supporting multiuse
< HTTP/1.1 303 See Other
< Date: Sun, 22 Oct 2023 11:02:27 GMT
< Server: Apache
< Set-Cookie: AL_SESS-S=AfdxOn42YIXV6YjZBTKK3jLuvl67Y5EFkZL6eTyPkJW3DtAymFTTOuSbj3N3dBgaJbr8; Path=/; Secure; HttpOnly; SameSite=Lax
< Content-Length: 123
< Location: /error_path/400.html?al_req_id=ZTUBQ0A6qMbMvXDVcQ7kGgAAA1M
< Content-Type: text/html
< 
* Ignoring the response-body
* Connection #0 to host www.stadt-waechtersbach.de left intact
* Issue another request to this URL: 'https://www.stadt-waechtersbach.de/error_path/400.html?al_req_id=ZTUBQ0A6qMbMvXDVcQ7kGgAAA1M'
* Found bundle for host www.stadt-waechtersbach.de: 0x7f9f8ddff7f0 [serially]
* Re-using existing connection! (#0) with host www.stadt-waechtersbach.de
* Connected to www.stadt-waechtersbach.de (80.69.201.211) port 443 (#0)
> GET /error_path/400.html?al_req_id=ZTUBQ0A6qMbMvXDVcQ7kGgAAA1M HTTP/1.1
Host: www.stadt-waechtersbach.de
Accept: */*

* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Date: Sun, 22 Oct 2023 11:02:27 GMT
< Server: Apache
< Cache-Control: no-cache
< Pragma: no-cache
< Connection: close
< Transfer-Encoding: chunked
< Content-Type: text/html
< 
* Closing connection 0
```

I'm not sure where the problem is but it looks more server like... I tried XMLReader directly, HTTPFactory (which I would expect use curl), curl directly see debug output and file_get_contents. All functions fails on this server...

Can you install me a 4.4 on the same server please and send me the login data?

**Comment by dautrich** [comment] 2023-10-22 11:20
@HLeithner 

I don't know whether you got two e-mails that I sent to your business mail address. I've attached those mails to a response mail to this post.

The first mail gives you superuser access to my test site. The second one shows the result of checking the RSS feed with the W3C validator.

Give me some time to prepare a J4 site for you. I'll come back to you later.

**Comment by HLeithner** [comment] 2023-10-22 15:39
I'm closing this for now, because it looks like an issue on the server (hoster or xml provider) which blocks the request. If you find out that the issues is part of joomla please feel free to reopen the issue.

**Closed as completed by HLeithner** 2023-10-22 15:39 UTC
Labels: No Code Attached Yet
