### ISSUE TITLE
Could not connect to MySQL server on very first installation page

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#19864] opened 2018-03-08 11:36 UTC
### Steps to reproduce the issue

Download Joomla 3.8.5
Load the very first page of the installation as a GET request
Eg . http://example.com/installation/index.php
On mac hit CMD+R (On windows refresh page? F5 ?) REPEATEDLY

### Expected result

No attempt to connect to the db is made, no errors are given

### Actual result

intermittent error message appended after closing </html> tag of 

`Could not connect to MySQL server`

Message raised from libraries/joomla/database/driver/mysqli.php Line 173

<img width="730" alt="screen shot 2018-03-08 at 11 35 53" src="https://user-images.githubusercontent.com/400092/37149156-e5b95d28-22c4-11e8-942a-d922e84a834c.png">

// Bug discovered by @rouenollivier

**Comment by maliknaik16** [comment] 2018-03-10 14:05
@PhilETaylor Unable to reproduce the issue.

**Comment by PhilETaylor** [comment] 2018-03-10 21:13
Now at home, on macbook laptop - so third mac in total that can replicate this - watch video: http://screenshot.myjoom.la/3J3v2C3Q1c2G

**Comment by maliknaik16** [comment] 2018-03-11 05:49
@PhilETaylor - I'm able to reproduce this issue on Google Chrome(OS: Linux Mint)

![screenshot from 2018-03-11 11-13-00](https://user-images.githubusercontent.com/6859756/37250228-d790a084-251d-11e8-9661-c56be02570ee.png)
![screenshot from 2018-03-11 11-13-18](https://user-images.githubusercontent.com/6859756/37250229-d7bd63a8-251d-11e8-87ba-fa442c7be3d7.png)

**Comment by Quy** [comment] 2018-03-11 18:29
I can reproduce it, but it is random/sporadic when it happens.

**Comment by zero-24** [comment] 2018-03-15 20:30
hmm can someone enable XDebug and check where the error is raised? I can not reproduce that issue on my side.

**Comment by PhilETaylor** [comment] 2018-03-15 20:38
In bed but yes it might have been during the time I was demoing xdebug to @rouenollivier 

Will test again tomorrow with and without xdebug

**Comment by zero-24** [comment] 2018-03-16 14:19
Yes that could show us the place where the sql call is made so we can try to uneerstand why it is failing there :-)

**Comment by PhilETaylor** [comment] 2018-03-16 14:51
I was unable to replicate it on the iMac (my oldest iMac - PHP Version 7.1.14 Built-in HTTP server)  at home with or without xdebug 

```
This program makes use of the Zend Scripting Language Engine:
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.14, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans
```

Just going to get the laptop from the car and I'll try that again :(

**Comment by zero-24** [comment] 2018-03-25 14:08
@PhilETaylor did you got a chance to test this on the laptop from the car?

**Comment by PhilETaylor** [comment] 2018-03-25 14:21
I did and was unable to replicate it then or again last night on the laptop - with or without xdebug... its crazy but as this thread states im not the only one who could replicate it.

**Comment by zero-24** [comment] 2018-03-25 14:24
Thanks @PhilETaylor 

@quy & @maliknaik16 can you try to reproduce this again? And tell us what you did on the latest code? If this is still a issue I need to know how to debug it ;)

**Comment by PhilETaylor** [comment] 2018-03-25 14:32
Just tried here in the office on the computer (iMac) that started this thread, and I cannot replicate with 

- PHP 7.2.3 CLI and with/without xdebug/opcache
- PHP 7.1.10 CLI and with/without xdebug/opcache
- PHP 5.6.33 with no xdebug

This is a really really strange bug...

**Comment by Quy** [comment] 2018-03-25 15:22
I can no longer reproduce it. Closing it for now.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19864">issues.joomla.org/tracker/joomla-cms/19864</a>.</sub>

**Closed as completed by Quy** 2018-03-25 15:22 UTC
Labels: No Code Attached Yet

**Comment by PhilETaylor** [comment] 2018-03-25 15:24
I'll check with @rouenollivier on Monday morning - her mac doesnt get as updated as often as mine, I run bleeding edge versions of most services.

**Comment by zero-24** [comment] 2018-03-29 02:48
Any update from @rouenollivier 's Mac? ;)
