### ISSUE TITLE
Some of the font awesome icons are not displayed

### ISSUE THREAD

**Issue by denism300** [joomla/joomla-cms#39381] opened 2022-12-08 12:30 UTC
### Steps to reproduce the issue
in site template css file:
`
.some-el::before {
    content: "\f2e5"; /*you can print any other icon with a number above f2e0, for example, f358 or f590 or etc. */
    font-family: 'Font Awesome 5 Free';
}
`

### Expected result
Icons with numbers f2e5 and higher are displayed.

### Actual result
Icons with numbers f2e5 and higher are not displayed.

### System information (as much as possible)
clean Joomla 4.2.5, custom template

### Additional comments
Icons with numbers f2e5 and higher are not displayed. A clean CMS is installed without third-party components, plugins, modules.
In DevTools, you can see that /media/vendor/fontawesome-free/css/font awesome.css is enabled?5.15.4

**Comment by brianteeman** [comment] 2022-12-08 12:40
It should be

`    font-family: "Font Awesome 5 Free";`

**Comment by brianteeman** [comment] 2022-12-08 12:49
ok - was just a quick suggestion

**Comment by denism300** [comment] 2022-12-08 21:44
solution:
add font-weight: 600 in css
ex.
.some-el::before { content: "\f2e5"; /*you can print any other icon with a number above f2e0, for example, f358 or f590 or etc. */ font-family: 'Font Awesome 5 Free'; font-weight: 600; }

**Comment by Kaushik1216** [comment] 2022-12-24 06:47
I checked font f2e5 and some above all are working fine for me .

**Comment by brianteeman** [comment] 2023-02-06 08:40
The issue is because fontawesome is not a single font of icons. Joomla includes brands, regular and solid and you need to use the additional class for those as well as the icon class 

eg 
fab fa-youtube
fas fa-folder-open
far fa-folder-open
fa fa-folder-open _same as far above_

All icons are not present in each font so it is important to use the correct additional class

**Comment by Quy** [comment] 2023-02-14 15:56
Closing as not a core bug.

**Closed as completed by Quy** 2023-02-14 15:56 UTC
Labels: No Code Attached Yet, Information Required
