### ISSUE TITLE
Custom fields in subforms still present in subform after configuration change

### ISSUE THREAD

**Issue by hytsch** [joomla/joomla-cms#41030] opened 2023-06-23 12:25 UTC
### Steps to reproduce the problem
Create a custom field A, create a custom field B (only in subforms), add field B as a field in field A. Change field B: Deactivate the option "only in subforms".

### Expected result
Field B becomes a normal field, field B is no longer present as a subform in field A.

### Actual result
Field B exists as a normal field, but in field A it is still listed as a subform field.

### System information (as far as possible)
Joomla 4.3.2, PHP 8.1

### Additional comments

**Comment by richard67** [comment] 2023-06-23 17:46
Thanks for reporting this issue. However, it’s not clear to me why you expect the field to disappear from the subform when the option  “only in subform” is disabled. As the name of that option says, the option means that the field can only be in a subform but not outside a subform as a stand-alone field when it is on. But that does not mean that the field can not be is a subform when that option is off. It only means that the field can be in a subform as well as a stand-alone field when the option is off, and it can be in a subform but not be a stand-alone field when the option is on.

**Comment by brianteeman** [comment] 2023-06-23 20:25
@richard67 is correct. You have misunderstood what it means "only in subform".

FieldX  - can be displayed in a subform and/or as a normal field
FieldX (only in subform) - can be displayed only in a subform

**Comment by brianteeman** [comment] 2023-06-23 20:25
Can be closed - the code is working as intended and as described

**Comment by richard67** [comment] 2023-06-23 21:02
Closing as expected behavior.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41030">issues.joomla.org/tracker/joomla-cms/41030</a>.</sub>

**Closed as completed by richard67** 2023-06-23 21:02 UTC
Labels: No Code Attached Yet, bug
