### ISSUE TITLE
[4.0] Increase depth of template editor pane

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#31035] opened 2020-10-10 11:42 UTC
### Is your feature request related to a problem? Please describe.
Open the template editor
Open a file
The editor is contained within a div `id="override-pane"` and is only 315px deep
In J3 the equivalent is 43% deeper at 450px

The J4 editor override-pane div is inside another container, the `<fieldset class="options-form">` which has - in my view - unneccesary padding of: `padding: 1vw 2vw`, which takes up valuable width.

### Describe the solution you'd like
Increase depth of to 450px deep
Remove the padding from the fieldset container

### Additional context
I have searched for similar issues but cannot find any based on their titles. Apologies if there is one.

**Comment by PhilETaylor** [comment] 2020-10-10 12:44
is this a duplicate of this https://github.com/joomla/joomla-cms/issues/30955 which is fixed in https://github.com/joomla/joomla-cms/pull/30990 ?

**Closed as completed** 2020-10-10 12:48 UTC
Labels: No Code Attached Yet
