### ISSUE TITLE
[4.0] [atum-bs5] Input type file - browser button colour

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#32167] opened 2021-01-26 09:05 UTC
### Steps to reproduce the issue

1. Go to `administrator/index.php?option=com_templates&view=template`
2. Click `Cassiopeia Details and Files`
3. Click `New File` in the toolbar

### Actual result

`Browse` button text barely visible

![Untitled](https://user-images.githubusercontent.com/2019801/105823928-a9f42080-5fb5-11eb-8a5a-f15e686d9c1f.png)

**Comment by infograf768** [comment] 2021-01-26 09:29
Confirmed:
this due to bs5 which has the scss
```
// File input buttons theming
  // stylelint-disable-next-line selector-pseudo-element-no-unknown
  &::file-selector-button {
    padding: $input-padding-y $input-padding-x;
    margin: (-$input-padding-y) (-$input-padding-x);
    margin-inline-end: $input-padding-x;
    color: $form-file-button-color;
    @include gradient-bg($form-file-button-bg); = > gives `background-color: #132f53;`
    pointer-events: none;
    border-color: inherit;
    border-style: solid;
    border-width: 0;
    border-inline-end-width: $input-border-width;
    border-radius: 0; // stylelint-disable-line property-disallowed-list
    @include transition($btn-transition);
  }
  ```

**Comment by wilsonge** [comment] 2021-01-26 17:33
Fixed in https://github.com/joomla/joomla-cms/commit/2ea201f457f5afbfc2ea27a83e4b43081da7fcc0

**Closed as completed by wilsonge** 2021-01-26 17:33 UTC
Labels: No Code Attached Yet
