### ISSUE TITLE
Publish hour (articles) not respected

### ISSUE THREAD

**Issue by acs-ferreira** [joomla/joomla-cms#10916] opened 2016-06-23 12:29 UTC
#### Steps to reproduce the issue

- Set both server, php.ini and Joomla at "Paris" time
- Publish an article in a future date/hour (let's say 28-06-2016, 16h00)

#### Expected result

- Article shoud be published at 28-06-2016, 16h00

#### Actual result

- Article is published at 28-06-2016, 17h00 (+1h)

#### System information (as much as possible)

- Ubuntu 14.04 LTS, "dpkg-reconfigure tzdata" Europe>Paris (confirmed with "date" command)
- php.ini timezone "Europe/Paris" (confimed with a simple "echo date()" command inside a php file)
- Joomla timezone set at "Paris" on Global Configuration

#### Additional comments

Why there is an hour (+1h) added in the published date ?

**Comment by brianteeman** [comment] 2016-06-23 12:44
The problem is that you have the wrong setting in the global configuration for the Server Time Zone.

As it is not a Joomla bug I am closing this. If you need extra support please use the forum http://forum.joomla.org
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10916">issues.joomla.org/joomla-cms/10916</a>.</sub>

**Closed** 2016-06-23 12:45 UTC
