### ISSUE TITLE
[5.0] Dark Mode: Usability issue - Options - Permissions

### ISSUE THREAD

**Issue by dautrich** [joomla/joomla-cms#41953] opened 2023-09-27 17:59 UTC
### Steps to reproduce the issue

1. Set dark mode 
    (On Windows, set Display Preferences to Dark Mode. Also set browser to Dark Mode or System standard).
2. Login to backend.
3. Go to Global Configuration  -  Articles  -  Permissions
4. Navigate the permissions submenu

### Expected result
All menu entries are visible.

### Actual result
Only the active and the hovered menu item are visible:
![grafik](https://github.com/joomla/joomla-cms/assets/7933215/83063aee-d546-4b26-9528-c68b39fe071b)

### System information (as much as possible)
J 5.0.0.-beta3
Windows 10 Dark Mode
Firefox Dark Mode

### Additional comments
This issue can be seen in all the components, not only in Articles.

**Comment by wilsonge** [comment] 2023-09-27 21:56
Thankyou so much for testing the joomla 5 beta and reporting this. It’s super appreciated. In this case it’s a duplicate of https://github.com/joomla/joomla-cms/issues/41778 so I’m closing this to keep conversations together

**Closed as not planned by wilsonge** 2023-09-27 21:56 UTC
Labels: No Code Attached Yet
