### ISSUE TITLE
List All Categories in an Article Category Tree - empty category

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#39910] opened 2023-02-22 09:28 UTC
### Steps to reproduce the issue
On a clean site 

1. create the following category structure
- Category1
 -- Subcategory 1-1
- Category 2
-- Subcategory 2-1
- Category 3
-- subcategory-empty
2. Add at least one article to each category except for _subcategory-empty_
3. create a menu item of type _ List All Categories in an Article Category Tree_ 
4. in the categories tab of the menu set Empty Categories to hide

### Expected result
![image](https://user-images.githubusercontent.com/1296369/220578570-c594f3b3-defd-4861-b9de-27e634a1cade.png)

![image](https://user-images.githubusercontent.com/1296369/220578679-b0d2b913-e461-4735-9aef-e400153242cb.png)

### Actual result
![image](https://user-images.githubusercontent.com/1296369/220578291-be65ce1b-8b32-4fa6-ae90-3434b9daf67d.png)

![image](https://user-images.githubusercontent.com/1296369/220578322-b4b66512-36aa-4ebe-aa44-fce54b7ce1ce.png)

**Comment by alikon** [comment] 2023-02-22 11:34
expected and actual are equal ??

**Comment by brianteeman** [comment] 2023-02-22 11:55
look again ;) on the right

**Comment by alikon** [comment] 2023-02-22 11:57
ahh my bad, was looking at numbers only

**Comment by joomdonation** [comment] 2023-02-22 14:29
Do I understand correctly that the expected behavior is there is no plus icon to allow expanding **Category 3** ? It could be fixed but quite hard (think of the case **subcategory-empty** does not have any articles assigned to it, but contains other empty children categories). I would mark this issue as won't fix because it is not worth to make our code complicated to solve this issue.

**Comment by brianteeman** [comment] 2023-02-22 14:47
yes you understand correctly. For me this is a bug because you expect the button to do something and if there is nothing to display then the button should not be present.

**Comment by joomdonation** [comment] 2023-02-22 14:58
Yes, I also agree that it's a bug. But it is complicated to make it work perfectly for all the cases, and users can always unpublish the empty categories to have right behavior. That's why I would mark this as won't fix.

**Comment by wojtekxtx** [comment] 2023-02-25 11:18
@Hackwar I will side with @joomdonation here: this is very complicated and complex matter, so I also would want it to be `won't fix` or similar.

**Comment by joomdonation** [comment] 2023-03-09 14:19
As discussed on Bug Squash channel, this is a won't fix issue for the reason I mentioned earlier. I'm closing.

**Closed as not planned by joomdonation** 2023-03-09 14:19 UTC
Labels: No Code Attached Yet, bug
