### ISSUE TITLE
PHP Warning:  session_set_save_handler() & session_set_cookie_params()

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#19127] opened 2017-12-22 00:30 UTC
### Steps to reproduce the issue
Just upgraded to PHP 7.2.0

Go to the front end.
Log in.
See php error log.

### Actual result
`PHP Warning:  session_set_save_handler(): Cannot change save handler when session is active in \libraries\joomla\session\storage.php on line 106`

`PHP Warning:  session_set_cookie_params(): Cannot change session cookie parameters when session is active in \libraries\src\Session\Session.php on line 807`

### System information (as much as possible)
PHP 7.2.0

**Comment by joomdonation** [comment] 2017-12-22 01:14
I can confirm the issue. Updated our website to PHP 7.2 last week and saw the same warning in error logs

**Comment by brianteeman** [comment] 2017-12-22 13:34
Is this PR a fix? #15742

**Comment by Quy** [comment] 2017-12-22 17:04
Sadly no.

**Comment by joomdonation** [comment] 2017-12-23 15:48
Just want to add that this issue happens when user logs in and seems like a bug in fork method of Session class https://github.com/joomla/joomla-cms/blob/staging/libraries/src/Session/Session.php#L792

I don't understand deep enough about session, however, look like https://github.com/joomla/joomla-cms/blob/staging/libraries/src/Session/Session.php#L804 doesn't need to be called as the session is active (comment it will solve the first warning)

Also, I am not sure this command https://github.com/joomla/joomla-cms/blob/staging/libraries/src/Session/Session.php#L811 is needed as because after the previous line called $this->_handler->regenerate(true, null);, session is started already

@mbabker Could you please take a look at this issue?

**Comment by ghost** [comment] 2017-12-28 15:35
closed as having Pull Request #19199

**Closed as completed** 2017-12-28 15:34 UTC
Labels: No Code Attached Yet

**Comment by haggar30** [comment] 2018-01-14 17:38
Have same issue, solved copy this into php.ini

error_log=C:\Windows\temp\PHP7_errors.log
upload_tmp_dir=C:\Windows\temp
session.save_path=C:\Windows\temp
cgi.force_redirect=0
cgi.fix_pathinfo=1
fastcgi.impersonate=1
fastcgi.logging=0
max_execution_time=300
date.timezone=Europe/Belgrade

**Comment by Quy** [comment] 2018-01-14 18:04
@haggar30 can you test PR #19199?
