### ISSUE TITLE
[4.0] Module with same position name on other template showing in Cassiopeia layout

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#30563] opened 2020-09-03 14:39 UTC
### Steps to reproduce the issue
Create a new template in J4 with a module of same name as one in Cassiopeia, e.g. 'breadcrumbs'
Create two modules, one assigned to the 'breadcrumbs' position in Cassiopeia, one to the 'breadcrumbs' position in the new template.

### Expected result
Only one of these modules should appear in either rendering.

### Actual result
Both modules are displayed:

![breadcrumbs](https://user-images.githubusercontent.com/36987494/92129491-80b2d800-edfb-11ea-9470-e6d9bd5adcbb.jpg)

It happens whichever template is assigned as default.

### System information (as much as possible)
Joomla 4 Beta 3 and also Joomla 4 Beta 4 nightly from 02/09/2020.

### Additional comments
I appreciate that in the end it is unlikely that anyone would assign two modules of the same name and type to the same page, but for testing purposes, it's a bit confusing.

**Comment by brianteeman** [comment] 2020-09-03 17:13
If I am not mistaken this has always been the case and its actually really useful if templates use the same position names. Otherwise when you change the site template you would have to change all your modules

**Comment by Scrabble96** [comment] 2020-09-04 08:43
> Otherwise when you change the site template you would have to change all your modules

You may have a point, but having said that, the module names for the new J4 Cassiopeia template are totally different from those of Protostar with the only names in common being 'banner' and 'debug'.

**Comment by brianteeman** [comment] 2020-09-04 15:14
My point still stands. This is also why the UI just displays the module position and not the module position and template

**Comment by brianteeman** [comment] 2020-10-03 09:19
This should be closed as the intended and expected behaviour

**Closed as completed** 2020-10-03 11:06 UTC
Labels: No Code Attached Yet
