### ISSUE TITLE
[4.0] What function does the component.php file in Cassiopeia have?

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#30538] opened 2020-09-01 11:30 UTC
### Problem identified
I can't see what function this file provides. Adding code to it makes no difference, such as adding a test class or an extra div:
`<body class="<?php echo $this->direction === 'rtl' ? 'rtl' : ''; ?> test">`
	`<jdoc:include type="message" />`
	`<jdoc:include type="component" />`
    `<div>This is a test div in the component.php file</div>`
`</body>`

Deleting the content of the component.php file has no effect on the rendering of Cassiopeia, at least for a standard single article item or a category blog item.

### Proposed solution
If it is redundant, remove the file and the reference to it in templateDetails.xml

**Comment by chmst** [comment] 2020-09-01 11:36
It enables users to show the pure content without Headings, modules and other template elements. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30538">issues.joomla.org/tracker/joomla-cms/30538</a>.</sub>

**Comment by Scrabble96** [comment] 2020-09-01 11:40
> 
> 
> It enables users to show the pure content without Headings, modules and other template elements.
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/30538](https://issues.joomla.org/tracker/joomla-cms/30538).

Do you mean by replacing the index.php code with the component.php code? I guess that would work for a single-page site but it wouldn't show a menu.

**Comment by chmst** [comment] 2020-09-01 11:51
If you have a component, for example, you don't want to have the complete tempate in your printed page.

**Comment by Hackwar** [comment] 2020-09-01 11:56
You can add ?tmpl=component to any URL and only get the output that would be generated by the component.php. You can actually put any php file in the root of your template and then add ?tmpl=<filename> and get that rendered. That file is definitely needed and not redundant.

**Comment by Bakual** [comment] 2020-09-01 11:57
If you append `?tmpl=component` to any URL, it will use the component.php instead of the index.php. You can also add other entry points if you want but component is used by the system and expects to only render the output of the component (without menus, modules, ...).
Most used usecase is probably modals.

**Comment by Bakual** [comment] 2020-09-01 11:57
I see Hackwar was a bit faster 😄

**Comment by brianteeman** [comment] 2020-09-01 12:11
It is not a new feature. It has been present since joomla 1.0

**Comment by Scrabble96** [comment] 2020-09-01 12:26
> 
> 
> If you append `?tmpl=component` to any URL, it will use the component.php instead of the index.php. You can also add other entry points if you want but component is used by the system and expects to only render the output of the component (without menus, modules, ...).
> Most used usecase is probably modals.

Ah, I see, so used for printing pop-ups etc. Thank you.

**Comment by Scrabble96** [comment] 2020-09-01 12:27
> 
> 
> It is not a new feature. It has been present since joomla 1.0

I didn't think it was new, just wondered what it actually did. Now I know.

**Comment by infograf768** [comment] 2020-09-01 14:13
Closing as not a bug.

**Closed as completed by infograf768** 2020-09-01 14:13 UTC
Labels: No Code Attached Yet

**Comment by N6REJ** [comment] 2020-09-02 03:05
good thing to put into the docs.  Perhaps someone who knows its behavior well can write it up.
@chmst know who that would be?
