### ISSUE TITLE
Module Manager: Module Login: In ''menu assignment tab'', display a message 'No matching Results', If search result is not exist

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#5736] opened 2015-01-15 12:17 UTC
-Go to 'Module Manager: Module Login'
-select 'menu assignment tab'
-select 'Only on the pages selected' option in 'Module Assignment' drop-down
-search an invalid keyword in search text fields

![screen shot 2015-01-15 at 06 14 11](http://issues.joomla.org/uploads/1/f32831fc20624de5a50d32b95f390048.png)

**Comment by zero-24** [comment] 2015-01-15 13:33
Confirmed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5736">issues.joomla.org/joomla-cms/5736</a>.</sub>

**Comment by infograf768** [comment] 2015-01-16 08:11
can't reproduce here on staging.

**Comment by aasimali** [comment] 2015-01-16 08:30
Its on staging!  **'No matching result'** message is not there on staging.

15 Jan 2015 package: http://developer.joomla.org/cms-packages/ (I installed this package on staging)

**Comment by brianteeman** [comment] 2015-01-16 08:37
I can confirm this behaviour as reported

**Comment by infograf768** [comment] 2015-01-16 12:08
Oh, I think I misunderstood: it does NOT display "No matching results" indeed.

**Comment by zero-24** [comment] 2015-01-16 22:36
Closing as we have a PR by @prasoon2211 here: http://issues.joomla.org/tracker/joomla-cms/5766 Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5736">issues.joomla.org/joomla-cms/5736</a>.</sub>

**Closed by zero-24** 2015-01-16 22:36 UTC
