### ISSUE TITLE
Subfields repeatable can't use media until article saved

### ISSUE THREAD

**Issue by nozaro33** [joomla/joomla-cms#33401] opened 2021-04-29 02:19 UTC
### Steps to reproduce the issue
1. Use media type field with subfields
2. Go to articles and click on + 
3. You can't use the media button until article saved, and then it can function properly.  (So if I want 4 repeatable fields, I create 4 empty fields and save to use.

### Expected result
When using subforms, when you click on add button, expected to be able to directly use the media button to input image.

### Actual result
You won't be able to use the media button in subfields until article is saved. 

### System information (as much as possible)
Joomla! 4.0.0-beta7
PHP 7.3.27
mysql 5.6.41-84.1

### Additional comments
This is my first time posting an issue, so let me know if I should improve on anything! Thanks!

**Comment by Quy** [comment] 2021-04-29 02:53
Welcome! You have an outdated version. Please test using the nightly builds: https://developer.joomla.org/nightly-builds.html

**Comment by Quy** [comment] 2021-04-29 18:37
Thanks for the report. I cannot reproduce. There have been many changes since beta7. Closing for now. Please report back if the issue persists.

**Closed as completed by Quy** 2021-04-29 18:37 UTC
Labels: No Code Attached Yet

**Comment by nozaro33** [comment] 2021-05-01 01:06
@Quy  Thanks! I've been putting off updating to Beta8, so it's most likely a old problem
