### ISSUE TITLE
PHP 8.1  Explode() deprecated message Joomla 4.2 & 4.3

### ISSUE THREAD

**Issue by Stevec4** [joomla/joomla-cms#39858] opened 2023-02-13 16:18 UTC
I am seeing this message on pages that have third party components loaded. The only change on my system was updating to php 8.1

Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in \Joomla_4.3\administrator\components\com_fields\src\Helper\FieldsHelper.php on line 59

If I cast string to $contextString the msg goes away but I am not sure if that is the best way to solve it.
 ```
public static function extract($contextString, $item = null)
    {
        $parts = explode('.', $contextString, 2);

        if (count($parts) < 2) {
            return null;
        }
```

**Comment by Quy** [comment] 2023-02-13 16:22
Closing as duplicate of #39719. Thanks.

**Closed as completed by Quy** 2023-02-13 16:22 UTC
Labels: No Code Attached Yet
