### ISSUE TITLE
Sort order of categories in smart search is incorrect

### ISSUE THREAD

**Issue by stimpsonjcat** [joomla/joomla-cms#41930] opened 2023-09-26 09:37 UTC
### Steps to reproduce the issue
Create a category and some sub categories of this category

### Expected result

In the advanced search I would expect the list of categories to be in the same order as the categories list when setting a category to an article. That is, the subcategories shown as a sub of the parent. 

_Example_:
Colors
  - Red
  - Blue
  - - Light blue
  - Green

Blog

News
  - Red

Help

### Actual result
All categories are ordered alphabetically, with a dash in front of the subcategory. Thus making believe that the subcategory is a child of the main category above in alphabetical order. And if you have two categories with the same name, you can't make a distinction which is which.

_Example_:
Blog
  - Blue
  - Green

Colors
Help
  - - Light blue
 
News
  - Red
  - Red
  
### System information (as much as possible)
Joomla! 4.3.4 Stable 

### Additional comments
![Scherm­afbeelding 2023-09-26 om 11 20 17](https://github.com/joomla/joomla-cms/assets/3033162/529025f6-458b-4466-87d1-c2c0d970b4e4)
![Scherm­afbeelding 2023-09-26 om 11 19 57](https://github.com/joomla/joomla-cms/assets/3033162/0b4cbfbc-9222-46c4-9305-7515c24c35e2)

**Comment by brianteeman** [comment] 2023-10-10 16:21
I can confirm this bug

**Comment by brianteeman** [comment] 2023-10-10 16:45
If anyone wants to try and work on this the problem is that all of the filters are sorted by title and the relevant code can be found in `administrator\components\com_finder\src\Service\HTML\Filter.php`

**Comment by Hackwar** [comment] 2024-02-19 14:56
With #42835 we have a PR to fix this. Please check that PR and test it, so that it can be part of one of the next releases. Closing this ticket.

**Closed as completed by Hackwar** 2024-02-19 14:56 UTC
Labels: No Code Attached Yet, bug

**Comment by stimpsonjcat** [comment] 2024-02-20 07:19
Thank you for fixing this. Do I understand correctly that this will only be fixed in Joomla 5?
