### ISSUE TITLE
Search with a [, (, or ) in a title

### ISSUE THREAD

**Issue by dtdpro** [joomla/joomla-cms#18478] opened 2017-11-02 13:45 UTC
### Steps to reproduce the issue

1. Create an article with "This is (Test) [Article]" as a title
2. Search for "(Test" or "test)" or "[Art"

### Expected result

Search contains title that links to the article

### Actual result

Title is missing in matching search results

### System information (as much as possible)

Joomla 3.8
PHP 7.0

### Additional comments

This is similar to Issues #18432 and #18220 with Pull Requests #18433 and #18221 

These are regular expression characters, other regular expressions characters may produce similar results.

### Sugested Fix

Change on Line 161

`$needle = str_replace('/', '\/', $needle);`

to

`$needle = preg_quote($needle,"/");`

**Comment by ghost** [comment] 2017-11-02 13:53
~~Can't confirm.~~

~~Search for "(en" as Part of Title "Article (en-gb)" got:~~
![bildschirmfoto 2017-11-02 um 14 52 36](https://user-images.githubusercontent.com/8235763/32329470-7d7a7c46-bfdd-11e7-82ca-3cc43aff0cd1.jpg)

Issue confirmed: Tried with given Example Article "This is (Test) [Article]" isn't found.

### System information
3.8.2-dev
Multilanguage Site
macOS Sierra, 10.12.6
Firefox 56 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by tonypartridge** [comment] 2017-11-02 22:27
This is usually down to the template since we added color highlighting a few version back the template may need updating.

Please test under protostar.

**Comment by ghost** [comment] 2017-11-03 06:30
@tonypartridge Test used Protostar.
### System information
3.8.2-dev
Multilanguage Site
macOS Sierra, 10.12.6
Firefox 56 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by brianteeman** [comment] 2017-11-05 20:17
I had no problem with **(test)** but i did have a problem with **[test]**<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18478">issues.joomla.org/tracker/joomla-cms/18478</a>.</sub>

**Comment by dtdpro** [comment] 2017-11-07 20:02
@brianteeman Did you test with "(test)" or "(test", with both parenthesis the search results will appear as they should, but with only one the title will not appear.

Upon further investigation into the code for the search component and looking at the results with error reporting turned on, in /components/com_search/views/search/view.html.php $needle is not being properly escaped before being put into preg_replace (Line 271). This causes an error to occur when a regular expression character is used that would cause a bad expression, for instance when including just the left parenthesis:

**Warning: preg_replace(): Compilation failed: missing ) at offset 10 in [WEBDIR]/components/com_search/views/search/view.html.php on line 270**<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18478">issues.joomla.org/tracker/joomla-cms/18478</a>.</sub>

**Comment by tonypartridge** [comment] 2017-11-07 20:11
I’ll take a deeper look

**Comment by brianteeman** [comment] 2017-11-07 22:22
I tested with both @dtdpro

**Comment by ghost** [comment] 2017-11-08 05:59
closed as having Pull Request #18522

**Closed as completed** 2017-11-08 06:01 UTC
Labels: No Code Attached Yet
