### ISSUE TITLE
[4.0] No databases detected in Alpha 2 Joomla Web Installer

### ISSUE THREAD

**Issue by simbus82** [joomla/joomla-cms#18783] opened 2017-11-21 15:47 UTC
### Steps to reproduce the issue
Download Alpha2
Extract it in the root of your "webspace"
Start the installer
In the 3rd step, after entering site name and admin data, no databases was found.

### Expected result
The dropdown with the label "Select the database type. *" show "MySQLi" or other DBs.
Joomla installation proceed.

### Actual result
The dropdown with the label "Select the database type. *" show only "None".
Impossible to install Joomla.
![awesomescreenshot-2017-11-21t15-27-09-094z](https://user-images.githubusercontent.com/1375730/33082085-32199738-cedc-11e7-9c40-01fd25af2243.gif)

### System information (as much as possible)
Apache 2.4
PHP 7
WHM/Cpanel environment
(hundreds of perfectly functioning Joomla 3.8.2 installations)
MariaDB 10.1 (the one that came with WHM/Cpanel)

### Additional comments
New installer is very good, simply steps, less fields and distracting data. But in this case i think two things are needed: 1) a hint about the "error", 2) a button to "copy" system data for future support

**Comment by ghost** [comment] 2017-11-21 16:12
duplicate of #18660?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18783">issues.joomla.org/tracker/joomla-cms/18783</a>.</sub>

**Comment by simbus82** [comment] 2017-11-21 16:17
For me is a little different, i'm trying on a "standard" online production server with WHM/Cpanel.

**Comment by mbabker** [comment] 2017-11-21 16:18
It's the same root cause.  If your PHP build does not use `mysqlnd` right now the MySQLi driver is not an option.  PDO on the other hand I haven't found a reason for people reporting that isn't an option but it is not restricted in any way.

**Comment by ghost** [comment] 2017-11-21 16:27
~~@mbabker should this Issue be closed?~~

**Comment by simbus82** [comment] 2017-11-21 16:31
@mbabker uhm... my php build uses mysqlnd...

![image](https://user-images.githubusercontent.com/1375730/33084211-a92d1ea8-cee1-11e7-97f0-401d043418c1.png)

Any things to check?

**Comment by mbabker** [comment] 2017-11-21 16:34
About to leave the house, but going to ask the stupid questions just to make sure (because there is seriously no other valid explanation I can think of right now).  Either the PDO extension (with MySQL support) or the MySQLi extension are enabled on the PHP version(s) you're testing on, right?  https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/vendor/joomla/database/src/Mysqli/MysqliDriver.php#L350 is the checks that must pass for MySQLi support (note the `function_exists('mysqli_stmt_get_result')` part is only true with mysqlnd enabled) and https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/vendor/joomla/database/src/Mysql/MysqlDriver.php#L209 for PDO MySQL.

**Comment by simbus82** [comment] 2017-11-21 17:07
**SOLVED!!!**

Info from a Joomla 3.8.2 installed on same server, same PHP 7.0, same settings.

![image](https://user-images.githubusercontent.com/1375730/33085082-f0b82ebe-cee3-11e7-9b47-d66ff5941b81.png)

![image](https://user-images.githubusercontent.com/1375730/33084713-f37ec9f6-cee2-11e7-8fbd-c2633a71ceb0.png)

![image](https://user-images.githubusercontent.com/1375730/33084814-30c5e9ac-cee3-11e7-9a21-028e4c65cc85.png)


This from WHM

![image](https://user-images.githubusercontent.com/1375730/33084741-0247e67a-cee3-11e7-9874-aea2e5e484ed.png)


I think is all ok... right?

But then I tryed to see if the function "mysqli_stmt_get_result" exist with a simple if ... and the function does not exist! OMG!

Then i have switched PHP to 5.6, and now the function "exists".

So i have switched another time to PHP 7.0 and now function "exists" and i can install Joomla 4. YEAH!

I think I found a Cpanel/CloudLinux bug due to an upgrade of EasyApache 4 :sweat_smile:

**Comment by ghost** [comment] 2017-11-21 17:09
@simbus82 can you please close this Issue?

**Closed as completed** 2017-11-21 17:10 UTC
Labels: No Code Attached Yet

**Comment by simbus82** [comment] 2017-11-21 17:11
Thanks to drive me to the solution @mbabker.  And if this problem also occurs in many other installations?Checking the "mysqli_stmt_get_result" is mandatory?

**Comment by mbabker** [comment] 2017-11-21 17:52
Right now yes, because our prepared statement support uses that function and it is only available with mysqlnd.  Still need to adjust the code to remove that requirement.
