### ISSUE TITLE
Joomla 3.4 multiple issues

### ISSUE THREAD

**Issue by visualtribe** [joomla/joomla-cms#6328] opened 2015-03-06 04:19 UTC
#### Steps to reproduce the issue
Save, close, unpublish, publish, trash, edit, batch buttons don't work after updating to Joomla 3.4. On module list page there is an extra blank list that states nothing. Can't delete. If I have multiple pages of modules it shows up until the end. Basically I can't do anything in my backend except to pages. I can however click New and that will pass me to another page. 

If I select All for seeing all of something in list view like Module Manager or Modules, I can't see all in list, and then the footer disappears. 

On one module page the footer that states the version of Joomla is not there. On one module page I get this error, Calendar.setup: Nothing to setup (no fields found).  Please check your code

This module is not in another website that I have, so it can't be the module. All my modules are up to date. 

I have turned off a bunch of modules too and still the same issue.

I don't use weblinks that was taken out of Joomla. 

#### Expected result

Things to work properly 

#### Actual result

Can't a bunch of stuff listed above

#### System information (as much as possible)

Server Linux 
PHP 5.4
Joomla 3.4
All browsers

**Comment by n9iels** [comment] 2015-03-06 16:05
It looks like you have some problems in your installation.  These problems are definitely not bug in Joomla!, cause i can't reproduce them.

Maybe you can open a topic on http://forum.joomla.org? People there can help you to solve this issues.

**Comment by PhilETaylor** [comment] 2015-03-06 17:19
Was this a site you upgraded?

Did you clear your browser cache?

I cannot replicate any of these issues. Propose closing this in favour of support on the form.

**Closed** 2015-03-06 17:19 UTC
Labels: No Code Attached Yet

**Comment by visualtribe** [comment] 2015-03-06 18:13
Yes, these sites have been running for a while, and has been an upgrade through 3 versions until this 3.4 version when I started to encounter issues. I turned off all my extensions, but the symptoms are still there. The other versions had the same extensions in them and I had no issues. One site doesn't even have the same extensions and the issues are there too, so it can't be them. I cleared cache, purged cache, cleared cookies. I have done everything I know to fix this issue.

**Comment by PhilETaylor** [comment] 2015-03-06 18:14
Take a look in the Javascript Console of your web browser - you will see a long list of issues for you to resolve (probably, from my experience).

**Comment by visualtribe** [comment] 2015-03-06 18:22
When I go to the module page the file that has all the errors is media/jui/js/jquery.min.js

bunch of syntax and reference errors.

**Comment by PhilETaylor** [comment] 2015-03-06 18:23
There you go then - your customisations to Joomla are causing Javascript conflicts. Most often with multiple versions of jQuery or Mootools loaded that are incompatible. I see this all the time.

**Comment by visualtribe** [comment] 2015-03-06 18:46
Well quite frankly, I have seen where Jquery doesn't run other Jquery code even if it is one level up. I have often tried to run one, or the newest and they don't work, so why isn't Jquery built to run everything even if it is new. And other developers create Jquery conflicts to solve their issues, why doesn't Joomla? This sounds just like the upgrade of to 3.3.6 where Joomla never warned people that it was using PHP 5.3.10 and took down millions of sites and left everyone scrambling to fix. I know of a server company right now who only have 5.3.3, not even 5.3.28 or 5.4. It's great if you use the newest, but it is just taking down everyone's sites. What's the point? Why even bother developing on Joomla if you can't extend something that should have a lot of these functionalities built in from the get go. Several versions ago Joomla should have had K2 or similar built in rather than the antiquated Article manager. I don't even bother with the Article manager. So far behind the curve it's useless.

And as I said, one of my sites has different modules to the other site. So the issue IS with Joomla, not the other developers. Thanks Joomla, thanks for screwing up my websites and then blaming everyone else. Thanks a lot.

**Comment by PhilETaylor** [comment] 2015-03-06 18:49
```So the issue IS with Joomla```

I'm sorry it is not

```a server company right now who only have 5.3.3```

Then you should run from them a mile and move to a webhost that takes security and stability seriously then!

Please provide a screen shot of your Javascript console. What EXACT errors are you getting?

what is the URL of your website?

**Comment by mbabker** [comment] 2015-03-06 18:51
> This sounds just like the upgrade of to 3.3.6 where Joomla never warned people that it was using PHP 5.3.10 and took down millions of sites and left everyone scrambling to fix.

Umm, this was announced over a year ago.  http://community.joomla.org/blogs/leadership/1798-raising-the-bar-on-security.html

**Comment by visualtribe** [comment] 2015-03-06 19:19
You understand that Wordpress inside their admin area put warnings there to let you know you should do this or that before you updgrade right? Joomla doesn't, regardless of some article written a year ago. And I think that is the point. Joomla keeps trying to recreate itself, where Wordpress doesn't. Yet, there are 100 times more Wordpress sites to Joomla. Every client I have wants Wordpress because one of their friends, sister, brother, nephew says that they should have Wordpress because everybody has Wordpress, and I suggest they use Joomla. I get that Wordpress is hole ridden, but all of us developers are asking is warnings. If you are going up a version of PHP or JQuery, put it in big red type so that we intern can go back to the module developers and have them create better products. 
![jquery](https://cloud.githubusercontent.com/assets/11344074/6531817/4e2e602a-c3f9-11e4-94da-0b855fd5270f.jpg)

And what happened to the gradual introduction of 3.4. Everyone was waiting for 3.3.7, 3.3.8, 3.3.9 that was supposed to be out months ago? Read many a discussion on it. But then suddenly 3.4. It's great to make things faster and better. I applaud the effort, but if it causes more issues than resolves then were are we to continue with it. I don't need clients screaming at me because their admin area doesn't work any more. If Joomla isn't going to build modules for all these abilities so everything works together, then where are any of us?

I now read where Joomla may change completely and not be a CMS anymore. There is a whole debate on what is Joomla. I don't even get this. It is so mind boggling. Wordpress and Drupal don't sit there wondering what they are. They know what they are. A way in which people can build websites.

bubblensqueak.ca hasn't got a footer and missing an element on the side and backend issues. visualtribe.com only has the issues in the backend.

Sorry to be so pissy, but I hate it when my sites tank and I am left scrambling to figure what the problem is.

**Comment by PhilETaylor** [comment] 2015-03-06 19:26
I'm not going to individually dissect your many mistruths, mis-information, inexperience or blatant lies in your last - its clear you are just looking to blame and rant and not looking to actually get help to resolve this issues you blame Joomla for causing, and your experience level in a solution you are providing to your own clients is exhausted. Therefore, on this occasion, I'm going to leave this thread.

**Comment by visualtribe** [comment] 2015-03-06 19:33
Excuse me. Help! You had no intention of helping me Phil. You closed this thread at the get go, remember!

**Comment by mbabker** [comment] 2015-03-06 19:49
And on that note, I'm going to lock this thread.  @visualtribe if you can provide steps that can be used to reproduce any of the issues you've experienced, please submit a new issue detailing them so we can investigate.  With what you've presented, the issues you're experiencing could range anywhere from a failed upgrade to extension incompatibilities.
