### ISSUE TITLE
4.3 RC2 Button text color issue

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#40306] opened 2023-04-02 21:17 UTC
### Steps to reproduce the issue

Create a new module, banner position and a new button. Example. Click `<a class="btn btn-success" href="#!">Get started</a>` and it will color when active: #fff; It was supposed to be but it uses the color of the Cassiopeia theme.

```
a:focus, a:hover {
    color: var(--cassiopeia-color-hover);
}
```
Same issue with the others except the default primary.

### Expected result

![banner-position](https://user-images.githubusercontent.com/423588/229597931-212f70c4-64eb-472d-9210-383fac02712f.jpg)

**Comment by chmst** [comment] 2023-04-02 21:52
I cannot replicate this on a fresh installation. You have changed some colours in your template?

**Comment by Hittitech** [comment] 2023-04-02 23:57
i would love to work on this issue .Can you please assign it to me?

**Comment by joomlaphp** [comment] 2023-04-03 07:00
> Bunu yeni bir yüklemede çoğaltamam. Şablonunuzdaki bazı renkleri değiştirdiniz mi?

No, the default

**Comment by richard67** [comment] 2023-04-03 08:42
> i would love to work on this issue .Can you please assign it to me?

@Hittitech We normally don't assign issues here (except if something special to be handled by a maintainer). If you want to work on it, just start and make a pull request when you have something ready. Of course you should have tested your changes before submitting a pull request. Then, when it is submitted, it will need 2 additional human tests (i.e. not by you).

**Comment by Hittitech** [comment] 2023-04-03 13:00
can i get link of the page where changes needed as i cannot find such interface provided in issue image

**Comment by dgrammatiko** [comment] 2023-04-06 09:48
This is an easy, change https://github.com/joomla/joomla-cms/blob/5296a7b89bd90d33004109c995fa73c0c0510fea/build/media_source/templates/site/cassiopeia/scss/blocks/_global.scss#L63-L66

to

```sass
  &:not([.btn]):hover,
  &:not([.btn]):focus {
    color: var(--cassiopeia-color-hover);
  }
```

**Comment by joomlaphp** [comment] 2023-04-06 10:04
Thank you, I hope they add this to the core file.

**Comment by joomlaphp** [comment] 2023-04-06 10:15
> 

Did you try, unfortunately it didn't work. J4.3 RC2

`.btn, a:focus, a:hover {
    color: var(--white);
}`

When I add this css code to user.css file it is fixed.

**Comment by richard67** [comment] 2023-04-06 10:18
@joomlaphp The file mentioned by @dgrammatiko is used to build the template.css file. Where did you try the change? It will not help just to put the change suggested by @dgrammatiko into a user.css file. You have to recompile the template.css after having made the change in the file which he has mentioned.

**Comment by joomlaphp** [comment] 2023-04-06 10:27
> @joomlaphptarafından belirtilen dosya@dgrammatikotemplate.css dosyasını oluşturmak için kullanılır. Değişikliği nerede denediniz? tarafından önerilen değişikliği koymak yardımcı olmayacaktır.@dgrammatikobir user.css dosyasına. Bahsettiği dosyada değişiklik yaptıktan sonra template.css dosyasını yeniden derlemeniz gerekiyor.

Ok it's done now, thank you very much.

**Comment by joomlaphp** [comment] 2023-04-18 17:35
Has this been fixed with 4.3.0 Stable release? 
Thanks

**Comment by brianteeman** [comment] 2023-04-18 17:40
As the issue is still open then I would assume not

**Comment by richard67** [comment] 2023-04-20 12:04
Closing as having a pull request. Please test #40435 . Thanks in advance.

**Closed as completed by richard67** 2023-04-20 12:04 UTC
Labels: No Code Attached Yet, bug
