### ISSUE TITLE
[4.0] Unstyled Close Button

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22968] opened 2018-11-08 05:56 UTC
### Steps to reproduce the issue

Install Joomla 4.0 at 

> commit 2a76a1d930d617773c80b2c9eee5d5605918e8e2 (HEAD -> 4.0-dev, origin/4.0-dev)

Navigate to http://example.com/administrator/index.php?option=com_menus&view=menus

Click the modules dropdown under Linked Modules

Select Menu Menu item in that dropdown 

### Expected result

Styled close button

### Actual result

![screenshot 2018-11-08 at 05 56 04](https://user-images.githubusercontent.com/400092/48180318-01e1d680-e31b-11e8-9f17-9dbcbf6ee221.png)

### System information (as much as possible)

Google Chrome Version 70.0.3538.77 (Official Build) (64-bit) Mac

**Comment by brianteeman** [comment] 2018-11-08 09:50
Duplicate of your own report.

**Closed as completed by brianteeman** 2018-11-08 09:50 UTC
Labels: No Code Attached Yet
