### ISSUE TITLE
Breadcrumbs module fails Google Structured Data test

### ISSUE THREAD

**Issue by aint-broke** [joomla/joomla-cms#37510] opened 2022-04-07 18:29 UTC
### Steps to reproduce the issue

Create a breadcrumbs module and add it to a page(s).  Run [Rich Results Test](https://search.google.com/test/rich-results) on the page.

### Expected result

May have minor warnings, but should be error free.

### Actual result

Get structured data errors indicating one or more missing itemprop fields for item, name, and/or position.

### System information (as much as possible)

Happens on a fresh install of Joomla! 4.1.2 using default Cassiopeia template.

### Additional comments

The html code that is generated for the breadcrumbs includes a reference to itemscope for BreadcrumbsList in the ordered-list tag that shouldn't be there.  The full breadcrumbs meta data definition is included in JSON format by the same module, and that code is formatted and processed correctly by Google.  The itemscope in the ordered-list tag should be removed.

**Comment by chmst** [comment] 2022-04-07 20:24
https://github.com/joomla/joomla-cms/issues/27151#issuecomment-1091838333

**Comment by brianteeman** [comment] 2022-04-07 21:12
@chmst the code for the breadcrumbs module is very different in 4.1 to 4.0
This bug was fixed for 4.0 but as the code changed in the module for 4.1 the fix was no longer relevant

**Comment by chmst** [comment] 2022-04-07 21:23
The issue is a duplicate -  @aint-broke could you delete you rfirst comment? It was he wrong place.

Same issue here: https://github.com/joomla/joomla-cms/issues/37508

**Comment by aint-broke** [comment] 2022-04-07 22:03
It's the same module, but different issue.  [nadjak77](https://github.com/nadjak77) reported that the problem was related non-menu items and whether or not the breadcrumb module was set to show/hide the last item.  I reported that it is always failing because there is a leftover itemscope in the output of the ordered-list that is no longer needed.

**Comment by richard67** [comment] 2022-04-27 12:36
Closing as having a pull request. Please test #37679 . Thanks in advance.

**Closed as completed by richard67** 2022-04-27 12:36 UTC
Labels: No Code Attached Yet
