### ISSUE TITLE
Add Q&A to help menu in backend?

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#5934] opened 2015-01-31 11:38 UTC
Joomla Stack Exchange is now becoming quite a popular resource for support so would the PT object to me making a PR to add an item to the HELP dropdown saying "Q&A" which links to joomla.stackexchange.com ?

**Comment by brianteeman** [comment] 2015-01-31 11:43
As we are in language string freeze now for 3.4 this would not be able to
be merged until after the release of 3.4

**Comment by C-Lodder** [comment] 2015-01-31 12:31
@brianteeman - No problem. But would such a PR be ok considering JSE is not an official Joomla resource for support?

**Comment by brianteeman** [comment] 2015-01-31 12:32
That I dont have an answer for. I would submit it and see

On 31 January 2015 at 12:31, Lodder <notifications@github.com> wrote:

> @brianteeman <https://github.com/brianteeman> - No problem. But would
> such a PR be ok considering JSE is not an official Joomla resource for
> support?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5934#issuecomment-72315978>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by wilsonge** [comment] 2015-01-31 15:01
My personal opinion is that as joomla.stackexchange is largely a developer resource (not by design but by experience) and as such im not sure it having a menu item in the CMS is necessarily a good idea But romiting it more to dev's is definitely a good idea

**Comment by brianteeman** [comment] 2015-01-31 15:06
Romiting?

**Comment by wilsonge** [comment] 2015-01-31 15:34
promoting - sorry autocorrect fails :)

**Comment by roland-d** [comment] 2015-02-01 20:14
Actually I have no problem with adding this entry since we also have the Developer Resources link in there. The joomla.stackexchange may become less developer oriented as other users find their way there. Just my thoughts on this.

**Comment by brianteeman** [comment] 2015-04-30 11:59
See #6868 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5934">issues.joomla.org/joomla-cms/5934</a>.</sub>

**Comment by zero-24** [comment] 2015-04-30 12:03
Closing as we have a PR by Brian :smile:

**Closed by zero-24** 2015-04-30 12:03 UTC
Labels: No Code Attached Yet
