### ISSUE TITLE
Protostar logo problem

### ISSUE THREAD

**Issue by rbuelund** [joomla/joomla-cms#10819] opened 2016-06-15 04:52 UTC
#### Steps to reproduce the issue
Insert a wide banner image as logo!![screen shot 2016-06-14 at 23 55 52](https://issues.joomla.org/uploads/1/50b3b07ef960217674847288f6959932.png)

#### Expected result
Logo exceeds the right border of the template in some browsers

#### System information (as much as possible)
Joomla 3.5.1 - clean protostar template.

#### Additional comments
A solution has been proposed here, but not shure that it is the right way to do it: http://forum.joomla.org/viewtopic.php?t=820231

**Comment by RonakParmar** [comment] 2016-06-27 07:20
I have uploaded logo image with the size 3000x500 and not able to reproduce this issue.

Tested browser info:

Windows10: IE-8,9,10 and Edge, Chrome 51.0.2704.103m, Firefox 47.0 and Safari 5.1.7
Ubuntu 12.04: Firefox 47.0 and Chrome Version 49.0.2623.110 (64-bit)

Please specify browser and OS to test this issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10819">issues.joomla.org/joomla-cms/10819</a>.</sub>

**Comment by brianteeman** [comment] 2016-06-28 10:59
Tested with an image 4000px wide and not able to reproduce

![screen shot 2016-06-28 at 05 59 46](https://issues.joomla.org/uploads/1/9a8fc7e5b386afe5c875a31768832bba.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10819">issues.joomla.org/joomla-cms/10819</a>.</sub>

**Comment by JamalTailored** [comment] 2016-07-11 11:13
I have uploaded logo with the size 3000px and able to reproduce this issue using following browser :

FireFox 44.0.2
Ubuntu 14.04 (64-bit)

Not able to reproduce this issue using following browser :

Chrome 51.0.2704.106 (64-bit), Chromium 49.0.2623.108  (64-bit)
Ubuntu 14.04<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10819">issues.joomla.org/joomla-cms/10819</a>.</sub>

**Comment by kalpeshtailored** [comment] 2016-07-12 12:46
I have tested with upload 4000 pixel width logo but not able to see issue. 

Tested in below browser :
OS : Window 10
Firefox 47.0
Google chrome Version 51.0.2704.106 m

![screen shot 2016-07-12 at 07 46 13](https://issues.joomla.org/uploads/1/597526269e1d2ca6a35109ea786f65bb.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10819">issues.joomla.org/joomla-cms/10819</a>.</sub>

**Comment by gunjanpatel** [comment] 2016-07-13 05:24
Set to "closed" on behalf of @gunjanpatel by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10819">issues.joomla.org/joomla-cms/10819</a>

**Comment by gunjanpatel** [comment] 2016-07-13 05:24
Closing as not able to reproduce this issue. We can always reopen if someone able to reproduce later or issue has new testing steps to reproduce it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10819">issues.joomla.org/joomla-cms/10819</a>.</sub>

**Closed by gunjanpatel** 2016-07-13 05:24 UTC
Labels: No Code Attached Yet

**Comment by gunjanpatel** [comment] 2016-07-13 05:25
Thank you @rbuelund and everyone for your contribution.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10819">issues.joomla.org/joomla-cms/10819</a>.</sub>

**Comment by gunjanpatel** [comment] 2016-07-13 05:36
@rbuelund I noticed that you have tested it in joomla 3.5.1. Please use latest joomla staging branch to test the issues. As staging branch will be the next release version of joomla. :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10819">issues.joomla.org/joomla-cms/10819</a>.</sub>
