### ISSUE TITLE
[5.3][PWA]: [Web Share API] - Share button, bookmark button

### ISSUE THREAD

**Issue by 4digitalworld** [joomla/joomla-cms#44311] opened 2024-10-18 18:52 UTC
### Is your feature request related to a problem? Please describe.
Joomla does not have https://github.com/joomla/joomla-cms/issues/44309 a built-in button to share content (for articles, categories, etc.), but @Joomla had built-in buttons to share content from version `1.0` to version `4.0` https://github.com/joomla/joomla-cms/pull/24025

![Image](https://github.com/user-attachments/assets/b85349fd-40a7-4a20-abda-80bc4b3f45b3)
This is how this feature looked like before Joomla `4.0`  (+ there was also an `Edit` button for editors)

![Image](https://github.com/user-attachments/assets/4b897ed5-22da-4289-bb3d-14ff126a7a0b)
since Joomla `4.0` we only have an `Edit` button (for editors) which is visible without the drop down list

People still **share** `articles` online every day, they may not use the `Print` and `Email` features anymore, but they still send links to their friends (using messengers or private messages on social networks).

PWA in `fullscreen` and `standalone` display mode does not have a built-in `Share` feature in smartphones, so this button will solve the problem of sharing content while using the website in PWA mode.
### Describe the solution you'd like
I suggest adding 2 new buttons to the drop-down list: `Share` and `Bookmark` instead of `Print` and `Email` (also move the `Edit` button back to the drop-down list for editors)

![Image](https://github.com/user-attachments/assets/56d310c6-484b-46ed-85cf-8db73e34912a)

Font Awesome icons: `share-nodes`, `bookmark`, `pen-to-square`, `gear`

If the `Share` button cannot be displayed to the user (if the browser does not support it), then instead of the `Share` button, the `Copy Link` and `Print` buttons can be displayed (this feature still works in Joomla 5, but this button is not displayed). 
Web Share API can automatically detect if the browser supports this button and instead show other text/buttons if this button is not supported by the browser.

You can test this button [here](https://w3c.github.io/web-share/demos/share.html) (supported by all browsers and systems except the desktop version of Firefox)

![Image](https://github.com/user-attachments/assets/1ecbe858-71af-4d66-9fe2-4b2627dfd2e8)

additional Font Awesome icons: `link`, `print`

This issue is also part of the PWA https://github.com/joomla/joomla-cms/issues/19877 https://github.com/joomla/joomla-cms/discussions/44182 for Joomla, since this is the `share_target` member for the PWA.
### Additional context
@W3C **Web Share Test:** [https://w3c.github.io/web-share/demos/share.html](https://w3c.github.io/web-share/demos/share.html)
Can i use (91%+): [https://caniuse.com/web-share](https://caniuse.com/web-share)
@google **Integrate with the OS sharing UI with the Web Share API** - [https://web.dev/articles/web-share](https://web.dev/articles/web-share)
@mdn **Web Share API** - [https://developer.mozilla.org/docs/Web/API/Web_Share_API](https://developer.mozilla.org/docs/Web/API/Web_Share_API)
@w3c **Web Share API** - [https://www.w3.org/TR/web-share/](https://www.w3.org/TR/web-share/)
@pwa-builder **Web Share API** - [https://docs.pwabuilder.com/#/home/native-features?id=web-share-api](https://docs.pwabuilder.com/#/home/native-features?id=web-share-api)
**How to Share From Your PWA** - [https://docs.pwabuilder.com/#/home/native-features?id=how-to-share-from-your-pwa](https://docs.pwabuilder.com/#/home/native-features?id=how-to-share-from-your-pwa)

**Comment by brianteeman** [comment] 2024-10-18 19:45
> You can test this button [here](https://w3c.github.io/web-share/demos/share.html) (supported by all browsers and systems except the desktop version of Firefox)

That prevents it being included in the core of joomla

**Comment by HLeithner** [comment] 2024-10-19 08:21
duplicate of #44309

**Closed as completed by HLeithner** 2024-10-19 08:21 UTC
Labels: No Code Attached Yet
