### ISSUE TITLE
[4.2.2] Serialization Error when using mod_articles_categories with cache

### ISSUE THREAD

**Issue by sakicnet** [joomla/joomla-cms#38782] opened 2022-09-18 18:07 UTC
### Steps to reproduce the issue
- Turn on caching in Global Configuration.
- Publish mod_articles_categories module and set it to display all categories.
- Reload the frontend and you will get following error:
Serialization of 'Closure' is not allowed

### Expected result
Displaying list of categories.

### Actual result
Error 500: Serialization of 'Closure' is not allowed

### System information (as much as possible)
The bug is present in prod 4.2.2 and 4.2.3-dev

### Additional comments
The bug was not present in 4.1.5 version.

**Comment by alikon** [comment] 2022-09-19 07:17
confirmed probably regression from #37139

**Comment by tramber91** [comment] 2022-09-20 00:22
Confirm also, in joomla 4.2.2 (php 8)
I have a blank page with a mod_articles_categories (No error message on my side even if error is enable, just blank page)
If, in advanced Tab option of the module mod_articles_categories, Caching, i enter "No Caching" 
I can load my page without issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38782">issues.joomla.org/tracker/joomla-cms/38782</a>.</sub>

**Comment by caglayanevren** [comment] 2022-09-22 09:19
+1

**Comment by ReLater** [comment] 2022-10-09 20:29
Confirmed for J4.2.3 stable, PHP 8.1

**Comment by alikon** [comment] 2022-10-13 06:54
please test #38950

**Comment by SharkyKZ** [comment] 2022-11-25 09:37
Will this B/C break be mitigated?

**Comment by mrownicki** [comment] 2022-12-13 10:00
Confirm this buq still exist. Joomla 4.2.5 and PHP 8

Serialization of 'Closure' is not allowed
/public_html/libraries/src/Cache/Controller/CallbackController.php:156<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38782">issues.joomla.org/tracker/joomla-cms/38782</a>.</sub>

**Comment by Sabrina-Travail-Lewagon** [comment] 2023-03-17 11:37
Bug present on Joomla 4.2.9 too

**Comment by Vegaturk** [comment] 2023-03-19 15:56
The bug still persists in version 4.2.9
I think there is information that they will fix this problem in version 4.3.0

Until we fix this issue in version 4.3.0 the workaround is to disable cache in articles-categories module




<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38782">issues.joomla.org/tracker/joomla-cms/38782</a>.</sub>

**Comment by joomdonation** [comment] 2023-03-31 14:24
@Denitz Could you please take a look at this issue to see if it is related to your PR https://github.com/joomla/joomla-cms/pull/37139 and hopefully come up with a solution ? Thanks !

**Comment by joomdonation** [comment] 2023-03-31 14:58
Great. Many thanks @Denitz

**Comment by joomdonation** [comment] 2023-03-31 16:10
@Denitz Thanks for the info. Asked you to look at it because someone mentioned reverting your PR solves the issue (haven't really tested it).

**Comment by Denitz** [comment] 2023-03-31 16:21
The issue raised after Jun 18, 2022 via injecting database instance into Categories (via `DatabaseAwareTrait`) which are stored in node as `_constructor` property.
The module cache should not serialize database layer, it's ridiculous and just impossible because layer contains non-serialazable objects like i.e. `PDOStatement`.

Here is this commit:
https://github.com/joomla/joomla-cms/commit/26c634184ebf532f922e07319a157c6ef417f6bd

I can do a PR and change the mod_articles_categories cached data to simple `stdClass`, but only if this PR will be actually merged but not hang around for months/years like other PRs :(

**Comment by joomdonation** [comment] 2023-03-31 16:26
@Denitz Please make PR. I will test it myself and find someone to test it, too. We should have this fixed ASAP.

**Comment by alikon** [comment] 2023-03-31 17:09
i'll test that too @Denitz

**Comment by Denitz** [comment] 2023-03-31 20:53
Many thanks for your help, I will add a PR by the end of Monday, hope tomorrow, please hold on...

**Comment by Denitz** [comment] 2023-04-01 08:49
@joomdonation @alikon https://github.com/joomla/joomla-cms/pull/40275

**Comment by joomdonation** [comment] 2023-04-01 15:54
@Sabrina-Travail-Lewagon  @Vegaturk  Please test PR https://github.com/joomla/joomla-cms/pull/40275 . It should solve your issue. Thanks !

**Closed as completed by joomdonation** 2023-04-01 15:54 UTC
Labels: No Code Attached Yet, bug

**Comment by Vegaturk** [comment] 2023-04-19 22:46
I have installed version 4.3.0 with great hope that the error can be fixed, I disabled the caching of the module, I turned on caching again, but unfortunately the error persists.
0 Serialization of 'Closure' is not allowed

**Comment by Denitz** [comment] 2023-04-20 05:25
Sure, the patch was not merged into 4.3.0, I guess we can wait for a year.
