### ISSUE TITLE
loadposition (regex) (sometimes) not working

### ISSUE THREAD

**Issue by Robdebert** [joomla/joomla-cms#5822] opened 2015-01-19 10:51 UTC
#### Steps to reproduce the issue
Active plugin "Content - Load Modules". Create a module and place it on position "openstreetmap", visible, on all menuitems.
I edited the code of the file plugins/content/loadmodule/loadmodule.php to see the regex, the text and the found matches, see attached screenshot.

#### Expected result
$matches should contain something

#### Actual result
$matches is an empty array, althoug the regex seems correct.

#### System information (as much as possible)
PHP 5.5, Joomla 3.3.6, Ubuntu 12.04

#### Additional comments
Only newley created articles are not working. We have old articles, that actually do show the modules. It seems totally random. There is no HTML between the two brackets { and } just this text:
<p>{loadposition openstreetmap}</p>

I also tried to remove the p-tags, but this didn't solve it.

**Comment by brianteeman** [comment] 2015-01-19 20:09
Looks like the screenshot didnt get attached<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5822">issues.joomla.org/joomla-cms/5822</a>.</sub>

**Comment by sensenel** [comment] 2015-01-20 09:59
+1 here , any recommendations? 

thx<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5822">issues.joomla.org/joomla-cms/5822</a>.</sub>

**Comment by brianteeman** [comment] 2015-01-20 10:23
From the information provided it is impossible to give any answer<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5822">issues.joomla.org/joomla-cms/5822</a>.</sub>

**Comment by Robdebert** [comment] 2015-01-20 11:48
Heres the screenshot again. Sorry, there was a server-error when i tryed it yesterday.![screen shot 2015-01-20 at 05 48 24](http://issues.joomla.org/uploads/1/467c70e0c045716b8037fd25a5d43a15.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5822">issues.joomla.org/joomla-cms/5822</a>.</sub>

**Comment by Robdebert** [comment] 2015-01-26 14:42
@brianteeman : I see you changed the status to "no code attached yet". What more code do you need? Everything that is needed to reproduce this bug is already in the description and the result can be seen in the screenshot.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5822">issues.joomla.org/joomla-cms/5822</a>.</sub>

**Comment by Robdebert** [comment] 2015-01-26 14:44
$matches is an empty array, although the plugin-code was written correctly in the article-content: {loadposition ...}<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5822">issues.joomla.org/joomla-cms/5822</a>.</sub>

**Comment by Fedik** [comment] 2015-01-26 14:59
I cannot reproduce.

I made *Custome Html* module on position `openstreetmap` and added to article `{loadposition openstreetmap}` tag - and all works as expected

**Comment by brianteeman** [comment] 2015-01-26 15:06
"no code attached yet" means that there is no Pull Request with this issue

On 26 January 2015 at 14:59, Fedir Zinchuk <notifications@github.com> wrote:

> I cannot reproduce.
>
> I made *Custome Html* module on position openstreetmap and added to
> article {loadposition openstreetmap} tag - and all works as expected
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5822#issuecomment-71473100>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Webdongle** [comment] 2015-09-01 01:47
Using Protostar Template loadposition is not working for me<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5822">issues.joomla.org/joomla-cms/5822</a>.</sub>

**Comment by infograf768** [comment] 2015-09-01 06:52
No problem here (3.4.4-dev, protostar and beez)

**Comment by Webdongle** [comment] 2015-09-01 09:59
Tested on a shared Host and it worked.  Tested again on localhost and only failed for 'Custom HTML'.  Not sure why must be a problem with my localhost

**Comment by brianteeman** [comment] 2016-04-06 11:37
After a year without confirmed replication I am closing this at this time.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5822">issues.joomla.org/joomla-cms/5822</a>.</sub>

**Closed** 2016-04-06 11:37 UTC
Labels: No Code Attached Yet
