### ISSUE TITLE
[4.0] [com_fields] Error when creating field

### ISSUE THREAD

**Issue by coolman01** [joomla/joomla-cms#18920] opened 2017-11-29 19:04 UTC
### Steps to reproduce the issue
in a new article, click "new field"
add title, selcted textfield, set to required and save

### Expected result

Saved new field

### Actual result

Error message : Component\Fields\Administrator\Table\Field' not found
Can't save

### System information (as much as possible)

PHP Built On	Windows NT HP-NOTEBOOK 10.0 build 16299 (Windows 10) i586
Database Version	5.5.5-10.1.28-MariaDB
Database Collation	utf8_general_ci
Database Connection Collation	utf8_general_ci
PHP Version	7.1.11
Web Server	Apache/2.4.29 (Win32) OpenSSL/1.0.2l PHP/7.1.11
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 4.0.0-dev Development [ Amani ] 31-March-2017 23:59 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

**Comment by brianteeman** [comment] 2017-11-29 19:08
Updated title to show it is for J4

**Comment by infograf768** [comment] 2017-11-30 08:34
I can't reproduce here.
<img width="738" alt="screen shot 2017-11-30 at 09 34 06" src="https://user-images.githubusercontent.com/869724/33421214-ab775fb2-d5b1-11e7-8b82-9b0436ebfae9.png">

**Comment by stutteringp0et** [comment] 2017-12-06 03:17
I'm getting the same thing with com_user and com_contact fields.  Fresh install - this is the very first thing I did after installing.

![screenshot from 2017-12-05 21-13-01](https://user-images.githubusercontent.com/310899/33642780-2185a26a-da01-11e7-9af8-9f01d5e118c6.png)

**Comment by stutteringp0et** [comment] 2017-12-06 06:58
I've identified the problem, although I'm not certain what the solution is.

I was looking through the class path to determine what was being loaded, and it occurred to me to try creating a Field.php file in /administrator/components/com_fields/Table - the path that autoload_psr4.php points to for Joomla\\Component\\Fields\\Administrator.  Within that new file I simply created a class that extended FieldTable and voila - everything worked.

So, the problem has to do with the classmap and or the class name - but I can't seem to identify where the problem is (probably because it's 5 minutes to 1AM). It's something silly, I know it.

Here's the file I created in the same directory as FieldTable.php

[Field.zip](https://github.com/joomla/joomla-cms/files/1534184/Field.zip)

**Comment by stutteringp0et** [comment] 2017-12-06 07:07
OK, I've solved it.  I'll issue a PR shortly.

**Comment by ghost** [comment] 2017-12-06 07:53
closed as having Pull Request #18994

**Closed as completed** 2017-12-06 07:53 UTC
Labels: No Code Attached Yet

**Comment by stutteringp0et** [comment] 2017-12-06 08:21
@franz-wohlkoenig Who should be notified if the build tests are erroring out with software issues?  I noted them in the PR - something about the wrong libsodium version and missing packages.

**Comment by ghost** [comment] 2017-12-06 08:32
i suggest to append "@mbabker" in your [Comment](https://github.com/joomla/joomla-cms/pull/18994#issuecomment-349557051).

**Comment by stutteringp0et** [comment] 2017-12-06 09:52
@mbabker

**Comment by ghost** [comment] 2017-12-06 10:29
@stutteringp0et i meant calling him at your [Comment](https://github.com/joomla/joomla-cms/pull/18994#issuecomment-349557051)

**Comment by stutteringp0et** [comment] 2017-12-06 13:51
Got it.  2am is unkind to rational thought
