### ISSUE TITLE
Fatal error: Call to undefined method JInstallerAdapterTemplate::setManifest() 

### ISSUE THREAD

**Issue by fastslack** [joomla/joomla-cms#6840] opened 2015-04-25 04:56 UTC
After update to 3.4.1 i receive this fatal error:

Fatal error: Call to undefined method JInstallerAdapterTemplate::setManifest() in /wwwroot/libraries/cms/installer/adapter/template.php on line 183

Seems that this method is not declared

```
$ grep setManifest * -d rec
libraries/cms/installer/adapter/module.php:		$this->setManifest($this->parent->getManifest());
libraries/cms/installer/adapter/module.php:		$this->setManifest($this->parent->getManifest());
libraries/cms/installer/adapter/module.php:		$this->setManifest($this->parent->getManifest());
libraries/cms/installer/adapter/template.php:		$this->setManifest($this->parent->getManifest());
libraries/cms/installer/adapter/template.php:		$this->setManifest($this->parent->getManifest());

```

**Comment by infograf768** [comment] 2015-04-25 06:01
See https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/installer/adapter.php#L865
That is staging, but I just checked and it is on the same line in 3.4.1

`JInstallerAdapterTemplate` extends `JInstallerAdapter`

**Comment by fastslack** [comment] 2015-04-27 17:56
I solved the issue unpacking the 3.4.1 package to rewrite all files but seems that into the update is not included some needed files

**Comment by OctavianC** [comment] 2015-04-29 13:38
Happened to me as well, but as I recall I updated to the stable version after using an alpha or beta build of 3.4.0. Can't reproduce it at this point though :(

**Comment by ggppdk** [comment] 2015-04-30 20:22
It happened to me too not long ago,
also i know another user, 

i solved it by unpacking J3.4.1 to overwrite all files too

i looked at the class file it was older version, it seems that Joomla update is not including all needed files when Updating from J3.4.0 betas (sorry i don't remember exact version)

**Comment by brianteeman** [comment] 2015-04-30 20:29
It is expected that updates from beta releases may have issues. Upgrading a
beta is not supported

On 30 April 2015 at 21:22, Georgios Papadakis <notifications@github.com>
wrote:

> It happened to me too not long ago,
> also i know another user,
>
> i solved it by unpacking J3.4.1 to overwrite all files too
>
> i looked at the class file it was older version, it seems that Joomla
> update is not including all needed files when Updating from J3.4.0 betas
> (sorry i don't remember exact version)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6840#issuecomment-97955240>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by ggppdk** [comment] 2015-04-30 20:50
@brianteeman , that explains it,
the packages were made to included needed files for updating from stable

then this is not a serious issue,
since no real production sites are using Betas

**Comment by zero-24** [comment] 2015-04-30 21:01
As it sounds that this issue comes from a beta update i will close this issue for now.

If we get reports on a stable update this can always re-open again. Thanks :smile:

**Closed by zero-24** 2015-04-30 21:01 UTC
Labels: No Code Attached Yet
