### ISSUE TITLE
[4.3] The text of a dark colored button cannot be read when focused for a moment

### ISSUE THREAD

**Issue by sandewt** [joomla/joomla-cms#40420] opened 2023-04-19 09:13 UTC
### Steps to reproduce the issue

After a dark colored button is clicked, the text is no longer visible for a moment. That's because the text will turn dark. That is messy.

### Expected result

The button text is always readable on focus.

### Actual result

The button text is NOT readable on focus for a moment

### System information (as much as possible)

This has been happening since Joomla 4.3 with Bootstrap 5.2.3.

### Additional comments

I made examples myself, see the images, for illustrationto what's happening.
Text button is readable
![screen shot 2023-04-19 at 09 06 17](https://issues.joomla.org/uploads/1/2839f3acedde897fc22ee817d4556b37.png)
Text button is NOT readable
![screen shot 2023-04-19 at 09 06 17](https://issues.joomla.org/uploads/1/68bfb9d52eb1b3995dc08c679151685f.png)

**Comment by chmst** [comment] 2023-04-19 09:16
Closing as it is a duplicate of https://issues.joomla.org/tracker/joomla-cms/40306

**Closed as completed** 2023-04-19 09:17 UTC
Labels: No Code Attached Yet, bug

**Comment by sandewt** [comment] 2023-04-19 09:30
> Closing as it is a duplicate

Oops
