### ISSUE TITLE
Showon-Feature in XML-Formdeclarations does not work on frontend

### ISSUE THREAD

**Issue by SPQRInc** [joomla/joomla-cms#9633] opened 2016-03-28 11:58 UTC
#### Steps to reproduce the issue

Use showon in an XML-field-declaration in frontend like this:

```
<field name = "title"
type = "list"
label = "COM_BESTIA_FIELDS_USERTITLE_LABEL"
description = "COM_BESTIA_FIELDS_USERTITLE_DESC"
filter = "safehtml"
default = "">
<option value = "">COM_BESTIA_FIELDS_VALUES_NOTITLE</option>
<option value = "other">COM_BESTIA_FIELDS_VALUES_OTHERTITLE</option>
<option value = "dr">COM_BESTIA_FIELDS_VALUES_DR</option>
</field> 
<field name = "testtest" 
type = "text" 
class = "input box
size = "40" 
label = "Test"
description = "Test" 
showon = "title:dr"
filter = "safehtml"/> 
```

Render fields in layout-file of the view: 

`$this->userform->renderFieldset('contact');`

#### Expected result

Field `testtest` is only visible if value `dr` is chosen on dropdown-field `title`. 

#### Actual result

Field `testtest` is always visible.

#### System information (as much as possible)

=============
Systeminformationen
=============

**Comment by Bakual** [comment] 2016-03-28 18:05
Just tested with my own component and it works fine in frontend.
Make sure you use JForm to render the field and also try with Protostar to rule out a template issue.
Also check the browser console for JavaScript errors.

**Comment by GABBAR1947** [comment] 2016-04-02 18:40
Works fine on my system too !

**Comment by Bakual** [comment] 2016-04-02 19:33
Closing as not able to reproduce.

**Closed by Bakual** 2016-04-02 19:33 UTC
Labels: No Code Attached Yet
