### ISSUE TITLE
Override check cannot be reset.

### ISSUE THREAD

**Issue by rbuelund** [joomla/joomla-cms#38700] opened 2022-09-06 05:30 UTC
### Steps to reproduce the issue
Update J!3 site with protostar template (containing overrides) still installed  to J!4. Change default template to Cassiopeia (With no overrides). Uninstall Protostar template.

### Expected result
No overrides to check

### Actual result
12 overrides to check, which come from the deleted protostar template. Not possible to reset, as the template is uninstalled..

### System information (as much as possible)
J!4.2.2
PHP 7.4

**Comment by brianteeman** [comment] 2022-09-06 05:38
> Delete Protostar template.

How did you delete it?

**Comment by rbuelund** [comment] 2022-09-06 05:40
I uninstalled it from backend

**Comment by richard67** [comment] 2022-09-07 09:36
> Change default template to Cassiopeia

This change should not have bee necessary after a successful update. The database updates should have done that for you if Protostar or Beez3 was the default template before the update. Has that been the case?

**Comment by brianteeman** [comment] 2022-09-07 09:47
I can confirm the problem and there is at ;least one other open issue here about this

When you uninstall a template it does NOT remove the database entry for any overrides for that template in #__template_overrides.

As a result the count on the quickicon does not change.

## Before
![image](https://user-images.githubusercontent.com/1296369/188847528-8774b293-5ed4-4568-914e-4aa6befcbe66.png)
![image](https://user-images.githubusercontent.com/1296369/188847561-784eb6db-00c4-4893-a2eb-c40f162455fe.png)

## After uninstalling the template (called editor)
![image](https://user-images.githubusercontent.com/1296369/188847667-7cd6f148-e7e4-4eec-a319-af8f4d1a3b5a.png)
![image](https://user-images.githubusercontent.com/1296369/188847679-1cb0acac-b49b-4c65-bb5a-981ce303f1bb.png)
![image](https://user-images.githubusercontent.com/1296369/188847829-5c075d6d-334e-4b9c-aa84-eb2382110a64.png)

**Comment by brianteeman** [comment] 2022-09-07 12:15
It probably needs the following code to be added to the finaliseUninstall function in the TemplateAdapter but that will not fix existing problems

```
        // Remove any overrides
        $query = $db->getQuery(true)
            ->delete($db->quoteName('#__template_overrides'))
            ->where($db->quoteName('template') . ' = :template')
            ->bind(':template', $element);
        $db->setQuery($query);
        $db->execute();
```

**Comment by PMWilliams123** [comment] 2022-09-07 15:43
What will fix the existing problem?, Do I need too fiddle with the database? If what do I need to do?

**Comment by richard67** [comment] 2022-09-07 16:40
> What will fix the existing problem?, Do I need too fiddle with the database? If what do I need to do?

You could use following SQL statements in PhpMyAdmin to clean it up (replace the `#__` by your actual database prefix):

```
DELETE FROM `#__template_overrides` WHERE `template` NOT IN (SELECT `name` FROM `#__extensions` WHERE `type`='template');
```

**Comment by brianteeman** [comment] 2022-09-07 17:08
@richard67 will that query work if I put it in an update sql

If so then I will create a PR with the query AND the ammended code to make sure they are removed on uninstall

**Comment by richard67** [comment] 2022-09-07 17:20
> @richard67 will that query work if I put it in an update sql
> 
> If so then I will create a PR with the query AND the ammended code to make sure they are removed on uninstall

@brianteeman It will work with an update SQL, but an update SQL would not be the right place because if someone updates to a version so it is run and then later deletes the template, they have the problem again, and the update SQL swill not run anymore because older than the database schema version.

Therefore it should not be added to any update SQL script but to a procedure in script.php which runs at the end of each update.

Another possibility would be to add it to the database checker and fixer so it runs only if such a problem was detected, using a pre-defined check and update query similar to the utf8mb4 check we still have.

If that is the way to go, I would prefer that it's me who implements it because there are not many other people who know in detail how the database checker works.

**Comment by richard67** [comment] 2022-09-07 17:21
P.S.: But I won't have time before the weekend to do anything.

**Comment by brianteeman** [comment] 2022-09-07 17:25
dont worry its a combination pr. #38714 just writing the test isnstructions

**Comment by richard67** [comment] 2022-09-07 17:26
P.P.S.: Of course if we can make sure the problem does not happen again, we can make an update SQL script which runs when updating to the version with that fix, and later we won't need it again. But as soon as the delete statement on template uninstallation fails for some reason, the problem will be back.

So maybe do a PR with both things now, and later when we implement the health check (was somewhere on the road map for a future version) we can add a check for that.

**Comment by richard67** [comment] 2022-09-07 17:28
> dont worry its a combination pr. #38714 just writing the test isnstructions

@brianteeman Yes, we can do that. The PR looks ok to me.

**Comment by brianteeman** [comment] 2022-09-07 17:51
Please test #38714

**Comment by richard67** [comment] 2022-09-07 17:53
Closing as having a pull request. Please test #38714 . Thanks in advance.

**Closed as completed by richard67** 2022-09-07 17:53 UTC
Labels: No Code Attached Yet
