### ISSUE TITLE
Module name not appearing in Modules list when containing "mod"

### ISSUE THREAD

**Issue by buskerricc** [joomla/joomla-cms#44365] opened 2024-10-28 12:03 UTC
### Steps to reproduce the issue
1-Create a new custom module with a name containing "mod" (e.g., "mod_mymodule").
2-Install and enable the module.
3-Go to the Modules section in the Joomla backend.
4-Search for the module name.

### Expected result
The module should appear in the search results and be selectable for configuration.

### Actual result
The module is not found in the search results.

### System information (as much as possible)
Joomla Version: 5.2.0
PHP Version: 8.2.24
MySQL Version: 8.0.40
Web Server: Apache
PHP Handler: cgi-fcgi
Browser: Chrome 130.0.0.0
Operating System: Linux (SuLinux)

### Additional comments
I've created the custom module manually by following the official Joomla documentation. The module is designed to display a simple text block. I've tried placing the module in various positions within my template, but it consistently fails to appear.

I've also attempted to create a basic HTML module with the same name to see if the issue was specific to my custom module, but the result was the same.

I've checked the Joomla error log, but there are no relevant error messages.

Relevant code snippet from my module's XML file:
```
XML
<extension version="3.1" type="module" client="site">
    <name>mod_mymodule</name>
    </extension>

```

**Comment by brianteeman** [comment] 2024-10-28 14:38
obviously the cause of your problem is not the name as every core module has a name element with mod_something

you havent said what documentation you have followed but I suspect it was for J3 and not j5

**Comment by buskerricc** [comment] 2024-10-28 15:35
I created two test modules, mod_test and mod_test_mod, I load them as
extensions and both are listed in the extensions list, however in the
module management I only see the first one. I don't know why but if you say
it's not possible, I trust you.

Il giorno lun 28 ott 2024 alle ore 15:39 Brian Teeman <
***@***.***> ha scritto:

**Comment by chmst** [comment] 2024-10-28 21:22
@buskerricc I think that you should post your issue in https://forum.joomla.org. I am closing here because this is surely not a Joomla core issue.

**Closed as completed by chmst** 2024-10-28 21:22 UTC
Labels: No Code Attached Yet
