### ISSUE TITLE
[4.0Alpha2] The "clear" button on search filter does nothing

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18715] opened 2017-11-19 17:38 UTC
### Steps to reproduce the issue

go to article manager
search for an article using text in the search box
page reloads with correct results
click clear

### Expected result

search term is cleared, and form submitted, leaving the filter empty on the page load

### Actual result

search term is not cleared, form submitted, next page loads leaving the filter text still in the text area

### System information (as much as possible)
http://screenshot.myjoom.la/3w1F2K2y1f05

**Comment by brianteeman** [comment] 2017-11-19 17:46
Closed as a duplicate of #17195

**Closed as completed by brianteeman** 2017-11-19 17:46 UTC
Labels: No Code Attached Yet
