### ISSUE TITLE
Extension Manager: Manage :: Filter not working correctly with multiple selection

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#5781] opened 2015-01-17 09:29 UTC
-Go to 'Extension Manager: Manage'
-Select filter: select type>Component
-Select filter: select folder>captcha

---------------------------------
**Application will display many records, Ideally there should be no records**

![screen shot 2015-01-17 at 03 28 51](http://issues.joomla.org/uploads/1/46c14f0c22ac7de1daf7989c99a595ce.png)

**Comment by brianteeman** [comment] 2015-01-17 12:34
Confirmed

On 17 January 2015 at 09:29, Aasim Ali <notifications@github.com> wrote:

> -Go to 'Extension Manager: Manage'
> -Select filter: select type>Component
> -Select filter: select folder>captcha
> ------------------------------
>
> *Application will display many records, Ideally there should be no records*
>
> [image: screen shot 2015-01-17 at 03 28 51]
> <https://camo.githubusercontent.com/d5e3cf4e0edd288303182a6b40d2cdc0da85b882/687474703a2f2f6973737565732e6a6f6f6d6c612e6f72672f75706c6f6164732f312f34366331346630633232616337646531646166373938396339396135393563652e706e67>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5781>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Erftralle** [comment] 2015-02-19 17:53
One can find the reason for this behaviour in the file **administrator/components/com_installer/models/manage.php**.

In the function ```getListQuery()``` lines 326-329 the folder filter is only applied if the type filter has specific values (namely 'plugin', 'library', '').
```
		if ($group != '' && in_array($type, array('plugin', 'library', '')))
		{
			$query->where('folder=' . $this->_db->quote($group == '*' ? '' : $group));
		}
```
So, if the type filter is set to 'component' the folder filter is not applied, no matter what is set there.
For me, this behavior is at least unexpected. I'm sure, the one who wrote that code has a different opinion.

It would be easy to change that behaviour by changing the code to
```
		if ($group != '' )
		{
			$query->where('folder=' . $this->_db->quote($group == '*' ? '' : $group));
		}
```
Then, regarding to your example filter setting (namely 'component', 'captcha'), no records would be listed.
I'll do a pull request if this solution will be supported.

**Comment by aasimali** [comment] 2015-02-20 06:05
@Erftralle 

Hi, I'm not technically sounds like you but your suggestion sounds good. Can you made this change at your testing site and check this thoroughly? If it works nicely, then, you can made the pull request for this.
Thanks for your effort.

**Comment by infograf768** [comment] 2015-02-20 07:37
I do confirm that the code proposed is fine, Please make a PR.

**Comment by Erftralle** [comment] 2015-02-20 13:31
Thanks for your feedback. Opened pull request #6130.

**Comment by zero-24** [comment] 2015-02-20 13:40
Closing as we have a PR by @Erftralle Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5781">issues.joomla.org/joomla-cms/5781</a>.</sub>

**Closed by zero-24** 2015-02-20 13:40 UTC
Labels: No Code Attached Yet
