### ISSUE TITLE
?tmpl=

### ISSUE THREAD

**Issue by inverser-pro** [joomla/joomla-cms#10207] opened 2016-05-02 20:48 UTC
?tmpl=
If we add ?tmpl= Joomla in the address line of> 1.5, we get the white page
Example:
http://joomla-site.org/?tmpl= > blank page!
You can substitute anything at the end of
http://joomla-site.org/?tmpl=scgsgfg > blank page!

**Comment by brianteeman** [comment] 2016-05-02 20:49
Please use the forum for support. Http://forum.Joomla.org

**Comment by mbabker** [comment] 2016-05-02 20:54
It's a bug.  `https://www.joomla.org/?tmpl=` does it too.

The code in the app classes rendering the document needs an additional sanity check against an empty `tmpl` query parameter.

**Comment by Bakual** [comment] 2016-05-02 21:18
It's not strictly an empty one. It's just an invalid one. Try "test" or "foo" or anything where there is no template file for it. If the file is missing, it will create that blank page.
It's not really an error as no error or warning is shown (not like blank pages usually would indicate).

So the options would be to show a Joomla error page "file not found" or just silently fall back to the regular index.php file.
Not sure what makes more sense.

**Comment by brianteeman** [comment] 2016-05-02 21:22
https://docs.joomla.org/Priority

Hardly a Priority 2 issue

On 2 May 2016 at 22:18, Thomas Hunziker <notifications@github.com> wrote:

> It's not strictly an empty one. It's just an invalid one. Try "test" or
> "foo" or anything where there is no template file for it. If the file is
> missing, it will create that blank page.
> It's not really an error as no error or warning is shown (not like blank
> pages usually would indicate).
>
> So the options would be to show a Joomla error page "file not found" or
> just silently fall back to the regular index.php file.
> Not sure what makes more sense.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/10207#issuecomment-216367578>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by mbabker** [comment] 2016-05-02 21:26
> So the options would be to show a Joomla error page "file not found" or just silently fall back to the regular index.php file.

JDocumentHtml already falls back on the system template if it can't find the file, so that part's somewhat OK (but it doesn't account for if the file doesn't exist in the system template too).  Another part of the issue is JDocumentHtml::render() shouldn't be getting called to begin with while the file data is empty (start at https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/application/site.php#L706 and trace it forward).  JApplicationCms should be ensuring it defaults to `index.php` no matter what.

**Comment by Bakual** [comment] 2016-05-03 06:47
I went and added a fallback in `JDocumentHtml` where the current fallback to the system template already exists. I think it makes most sense there.
See https://github.com/joomla/joomla-cms/pull/10210

**Comment by Bakual** [comment] 2016-05-03 06:47
Closing as we have a PR.

**Closed by Bakual** 2016-05-03 06:47 UTC
Labels: No Code Attached Yet
