### ISSUE TITLE
New SEF plugin bug for enforce trailing slash

### ISSUE THREAD

**Issue by joeforjoomla** [joomla/joomla-cms#43056] opened 2024-03-16 14:43 UTC
### Steps to reproduce the issue
Enable the new SEF plugin parameter to:
![image](https://github.com/joomla/joomla-cms/assets/17835460/3dc1e8bc-7ffd-4ce3-9918-3bbbfef64271)

Open a page with a whatever query string parameter, example:
http://joomla50dev/?whatever

### Expected result
No errors

### Actual result
Infinite loop
![image](https://github.com/joomla/joomla-cms/assets/17835460/2d8812f8-256c-4dcd-98bf-f0de03323db9)

### System information (as much as possible)
Joomla 5.1 Beta1

**Comment by joeforjoomla** [comment] 2024-03-16 14:44
Ping @Hackwar as usual

**Comment by brianteeman** [comment] 2024-03-16 15:00
confirmed on the home page

**Comment by Hackwar** [comment] 2024-03-16 20:59
I've created a PR to fix this. Please have a look at #43063. Closing since we have a PR.

**Closed as completed by Hackwar** 2024-03-16 20:59 UTC
Labels: No Code Attached Yet
