### ISSUE TITLE
Error 404 with multilingual feature sample data installation and solution.

### ISSUE THREAD

**Issue by gmobravo** [joomla/joomla-cms#6036] opened 2015-02-10 02:25 UTC
#### Steps to reproduce the issue
Create a new installation with the "sample testing" data and then at the end of installation choose also the multilingual feature.

#### Expected result
All the menu items in the Top Menu should works both english and the language you choose to use the multilingual feature.

#### Actual result
404 Error when you click on the "Parks" menu item in other language than english. Only works in english.

#### Additional comments
This occurs becouse the sample data in the sample_testing.sql in the "#__menu" table create the "Australian Parks" menu with "en-GB" instead '*' and as the "Parks" menu item in the Top Menu is just an alias to the "Parks Home" menu item of the "Australian Parks" menu, the the resoult is and 404 error page due the multilingual feature.

To solve this, it is necessary modify the sample_testing.sql file and replace, in the "#__menu" table the references to the "en-GB" language, for the '*' to make it available in all the languages.

As my skills does not allow me to creat a new pull in the GitHub I put the solution here:
We have to replace the "en-GB" reference for a '*' in the lines 385, 387, 388, 389, 439, 440 of the /installation/sql/mysql/sample_testing.sql file

**Comment by infograf768** [comment] 2015-02-10 08:02
You should NOT use a sample data when installing a multilanguage site from scratch. This is clearly stated on the page where one chooses a sample or not.
Closing as not a bug.

**Closed by infograf768** 2015-02-10 08:02 UTC

**Comment by javigomez** [comment] 2015-02-10 08:54
Thanks @gmobravo for the report. Jean Marie is right, when we did the multisite installer we were forced to add this clause at the demo data:

![screen shot 2015-02-10 at 09 56 43](https://cloud.githubusercontent.com/assets/1375475/6124094/90437290-b10a-11e4-8973-799d87400d1a.png)

Because to be able to generate the dummy data internationalised we needed to have a clean database, otherwise we couldn't predict possible conflicts. So is a must that we do not add any demo data.
