### ISSUE TITLE
COLUMNS Option not showing under Blog layout tab of Cat Blog or Featured Items Menu Link

### ISSUE THREAD

**Issue by sdrawdenek** [joomla/joomla-cms#30044] opened 2020-07-07 17:47 UTC
### Steps to reproduce the issue

Select NEW menu item from Menu Manager screen.

Select LAYOUT tab

Scroll down to view COLUMNS field (missing)

Same applies regards Featured Items menu link (layout tab).

### Expected result

Expected to see COLUMNS field.

### Actual result

See grey horizontal line in place of COLUMNS field.

See image.

### System information (as much as possible)

J4 Dev 3 7 July 2020 Nightly Build

### Additional comments

COLUMNS was available in J3 and useful feature.

COLUMNS are referenced in the HELP pop up window for Cat Blog Link.

**Comment by ReLater** [comment] 2020-07-07 23:22
Duplicate. Please read discussion here: https://github.com/joomla/joomla-cms/issues/27478

The current state is that you have to use CSS classes and know the correct ones like described in https://github.com/joomla/joomla-cms/pull/18319

**Comment by ReLater** [comment] 2020-07-07 23:25
> COLUMNS are referenced in the HELP pop up window for Cat Blog Link.

Yes. You're right. The help doc is wrong as this setting has been removed in J4.

**Comment by SharkyKZ** [comment] 2020-07-08 07:57
Closing as duplicate of https://github.com/joomla/joomla-cms/issues/27478.

**Closed as completed by SharkyKZ** 2020-07-08 07:57 UTC
Labels: No Code Attached Yet
