### ISSUE TITLE
loadmodule not working in banner description

### ISSUE THREAD

**Issue by grantg182** [joomla/joomla-cms#14415] opened 2017-03-07 20:47 UTC
### Steps to reproduce the issue
Create a login module titled My Login Module
Create a banner to open in modal with the following in the Description field:-
{loadmodule login, My Login Module}

### Expected result
Banner opens modal on click
Expect to see contents of the My Login Module inside the modal

### Actual result
Source code of {load module...} is displayed.

### System information (as much as possible)
Joomla 3.5.1
OSX Xampp

### Additional comments
Tested the same {loadmodule....} in an article description and it works, so my {loadmodule} code is correct.

**Comment by bertmert** [comment] 2017-03-07 21:19
Please see here why the loadmodule button was removed in banner description in Joomla 3.6.3
https://github.com/joomla/joomla-cms/pull/11419

**Comment by zero-24** [comment] 2017-03-07 21:53
the PR #11419 just removes the option to use the GUI for that. The problem is that this text field is not renderd in the frontend so it also does not pass the relevant plugin event ;) So we can close this as expected behavior.

> Joomla 3.5.1

Please update to the last stable version of Joomla 3.6.5 https://downloads.joomla.org/latest

Thanks for reporting.

**Closed by zero-24** 2017-03-07 21:53 UTC
Labels: No Code Attached Yet
