### ISSUE TITLE
Issue in pagination in Joomla 3.4.4

### ISSUE THREAD

**Issue by RonakParmar** [joomla/joomla-cms#8364] opened 2015-11-10 06:04 UTC
#### Steps to reproduce the issue
- Create more then 6 users to test this issue in Joomla back-end under same user-group.
- Set pagination number of record limit to 5.
- Check pagination without using search-tools filters.Pagination is working fine in this scenario.
- Apply user-group, state or active filter in search-tools and click on pagination next button, redirect to same page.

#### Expected result
On-click of next button/ or second page button, redirect to that second page or next page.

#### Actual result
Right now, redirects to same page.

#### System information (as much as possible)
Joomla 3.4.4
PHP Version 5.5.30-1+deb.sury.org~precise+1
System	Linux tasol-desktop 3.5.0-54-generic #81~precise1-Ubuntu SMP Tue Jul 15 04:02:22 UTC 2014 x86_64
Apache Version: Apache/2.4.12 (Ubuntu)

**Comment by saiyedirshad** [comment] 2015-11-10 06:51
I have fellowed the given steps and able to reproduce this issue in joomla 3.4.4.
PHP Version 5.5.30
System: Linux 3.5.0-54-generic #81~precise1-Ubuntu SMP Tue Jul 15 04:02:22 UTC 2014 x86_64
Apache Version: Apache/2.4.12 (Ubuntu)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8364">issues.joomla.org/joomla-cms/8364</a>.</sub>

**Comment by saiyedirshad** [comment] 2015-11-10 07:00
I have tested this PR using Patch tester component and successfully tested it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8364">issues.joomla.org/joomla-cms/8364</a>.</sub>

**Comment by Bakual** [comment] 2015-11-10 07:14
> I have tested this PR using Patch tester component and successfully tested it.

This isn't a PR, so you certainly haven't tested it.

@RonakParmar Can you please test with current 3.5.0 Beta 1 or staging? Because it should be fixed already with the merged https://github.com/joomla/joomla-cms/pull/7487

**Comment by RonakParmar** [comment] 2015-11-10 07:29
@Bakual Thanks for updating me, I have updated my local Joomla 3.4.4 to Joomla 3.5.0 Beta version to test this issue.
It is being fixed in this version.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8364">issues.joomla.org/joomla-cms/8364</a>.</sub>

**Comment by RonakParmar** [comment] 2015-11-10 07:29
Please close my PR:
https://github.com/joomla/joomla-cms/pull/8365<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8364">issues.joomla.org/joomla-cms/8364</a>.</sub>

**Comment by Bakual** [comment] 2015-11-10 09:24
Closing issue as it will be fixed in 3.5.0

**Closed by Bakual** 2015-11-10 09:24 UTC
Labels: No Code Attached Yet
