### ISSUE TITLE
Media manager: Delete message is not center aligned

### ISSUE THREAD

**Issue by uthorat** [joomla/joomla-cms#26663] opened 2019-10-19 10:12 UTC
### Steps to reproduce the issue
Login to backend of joomla 4.0.0.alpha12-dev
Go to media
Select any file or folder
click on delete
Observe the message

### Expected result
Message should be centered aligned to popup

### Actual result
Message is not center aligned

![screen shot 2019-10-19 at 10 11 33](https://issues.joomla.org/uploads/1/08015e1ea4c3db08014dc7ffbc6e1bb3.png)

**Comment by spahno** [comment] 2019-10-24 12:24
Hey @uthorat,
I'm going to fix your issue!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26663">issues.joomla.org/tracker/joomla-cms/26663</a>.</sub>

**Comment by brianteeman** [comment] 2019-11-05 06:53
The message should not be centered. 

The problem is that there is no styling being loaded at all on any of the media manager images

**Comment by brianteeman** [comment] 2019-11-05 07:32
Closer inspection reveals that the styling is not the issue. The problem that there is no ``<div class="alert-heading`

**Comment by brianteeman** [comment] 2020-02-23 11:29
closed by #28025

**Closed as completed by brianteeman** 2020-02-23 11:29 UTC
Labels: No Code Attached Yet, J4 Issue
