### ISSUE TITLE
Pagination next and previous both go to the right

### ISSUE THREAD

**Issue by GASOLINE** [joomla/joomla-cms#40059] opened 2023-03-09 12:55 UTC
### Steps to reproduce the issue
I made a new website and with pagination arrows both go to the right

 Latest Joomla 4.2.8 & PHP 8.1.16

### Additional comments
See attached images, also with standard Joomla template. So appearantly something is wrong.

The code for own template & result image is with Joomla standard template.
![joomlapagination](https://user-images.githubusercontent.com/958515/224029328-dc261f9a-a0d1-4128-8f4d-83496519f0b3.jpg)

![cassiopeia](https://user-images.githubusercontent.com/958515/224029347-c2542c0c-dc83-467f-8fb5-8e77d39defa7.png)

**Comment by drmenzelit** [comment] 2023-03-09 14:43
I can't reproduce the issue

**Comment by chmst** [comment] 2023-03-09 15:04
Which language is this? In English or German I cannot reproduce the Errot but you have another language.

**Comment by brianteeman** [comment] 2023-03-09 15:06
> Which language is this? In English or German I cannot reproduce the Error but you have another language.

Dutch

**Comment by brianteeman** [comment] 2023-03-09 15:12
The language shouldnt make a difference to the code for an icon though as that is markup not a string for translation

**Comment by chmst** [comment] 2023-03-09 15:34
It works here also for Dutch, Really strange.

**Comment by GASOLINE** [comment] 2023-03-09 17:23
Here is an [example link](https://louisvanbeek.nl/werk/brochures?start=3), you can see in the page source what is going wrong. I unchecked the arrows in code because it did not work as intended, but that's all.

**Comment by VaibhavAPatil** [comment] 2023-03-09 17:44
Namaste Sir 🙏
We just need to change the one class "icon-angle-double-right" to "icon-angle-double-left"
I can Solve this issue Assign this Issue to me

**Comment by brianteeman** [comment] 2023-03-09 18:30
> Namaste Sir 🙏 We just need to change the one class "icon-angle-double-right" to "icon-angle-double-left" I can Solve this issue Assign this Issue to me

It will be a miracle if you can fix that as that is what the code is.

@GASOLINE You must have an override in place with the wrong code. The link doesnt help as that is the generated code

**Comment by chmst** [comment] 2023-03-09 18:53
@VaibhavAPatil thanks for your interest in solving this issue.  It is not as easy in Joomla. See here: 
https://github.com/joomla/joomla-cms/blob/4.2-dev/layouts/joomla/pagination/link.php#L30
Te icon is set automatically and this workx in millions if sites. 

This means the user here has a problem which is not related to Joomla Core.

**Comment by chmst** [comment] 2023-03-12 08:10
Closing this as it template specific and not a joomla issue. @GASOLINE please post in forum.joomla.org, the supporters can help finding the override.

**Closed as completed by chmst** 2023-03-12 08:10 UTC
Labels: No Code Attached Yet, Information Required, bug
