### ISSUE TITLE
Search by Extension Name - Clear button not working

### ISSUE THREAD

**Issue by MixingOnBeat** [joomla/joomla-cms#8641] opened 2015-12-10 00:42 UTC
#### Steps to reproduce the issue

1) go to admin control panel
2) go to Extensions on the top menu.
3) select Manage from drop down.
4) select Manage on the left side menu
5) Search by Extension Name -- just enter something to search
6) after that, try clearing it by pressing the Clear (X) button.

#### Expected result

It should clear, but it seems it doesn't.  

#### Actual result

Doesn't clear.  I have to log out and log back in, in order for it to be cleared so I can do another search and etc.

#### System information (as much as possible)

Joomla! 3.4.5
OS Linux n
PHP 5.6.14
MySQL 5.5.46-cll
Caching Enabled
GZip Enabled

#### Additional comments

See screenshot to learn where exactly is my issue--red arrow points to the clear button.

![screen shot 2015-12-09 at 18 41 28](https://issues.joomla.org/uploads/1/fdcd4ca12957299ac4873b349cc4c659.png)

### Workaround
Log out and log back in and the search results will be cleared.  Or simply do a search by entering a single space (spacebar).

**Comment by MixingOnBeat** [comment] 2015-12-10 00:44
Just tested other areas (articles, categories, and etc.) where the search feature exists, and the same issue.  Can't clear it.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8641">issues.joomla.org/joomla-cms/8641</a>.</sub>

**Comment by infograf768** [comment] 2015-12-10 08:30
Please test on staging as I can't reproduce here.
https://github.com/joomla/joomla-cms/archive/staging.zip

**Comment by infograf768** [comment] 2015-12-10 08:33
hmm, you created another issue for the same topic where you point to the version of PHP as responsible.
https://github.com/joomla/joomla-cms/issues/8421

**Comment by gwsdesk** [comment] 2015-12-15 10:52
See my response JM on #8421 I confirm the issue

**Comment by MixingOnBeat** [comment] 2015-12-16 00:22
So what's the verdict here?  Do I need to tell my host to update PHP, if yes to what PHP version?  Or will you guys figure out a fix for us?

I just updated to Joomla 3.4.6 and the issue is still there, unfortunately.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8641">issues.joomla.org/joomla-cms/8641</a>.</sub>

**Comment by MixingOnBeat** [comment] 2015-12-16 00:26
P.S. Since the last time I reported this issue, it seems that my host has updated PHP to 5.6.16 -- and the problem still exists on my side.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8641">issues.joomla.org/joomla-cms/8641</a>.</sub>

**Comment by MixingOnBeat** [comment] 2015-12-22 00:53
Just letting you know that I've updated to Joomla! 3.4.7 and this problem/bug still exists.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8641">issues.joomla.org/joomla-cms/8641</a>.</sub>

**Comment by MixingOnBeat** [comment] 2015-12-22 00:59
Added two known workarounds.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8641">issues.joomla.org/joomla-cms/8641</a>.</sub>

**Comment by izharaazmi** [comment] 2016-01-19 12:10
Could not reproduce the issue
PHP 5.6.11
Joomla 3.4.5 ~ 3.4.8

**Comment by N6REJ** [comment] 2016-01-20 07:34
I've reported this on more then one occasion and am constantly told it 
doesn't exist.
Bear

**Comment by izharaazmi** [comment] 2016-01-20 07:48
@N6REJ Please perform one more test as I mentioned in https://github.com/joomla/joomla-cms/issues/8421#issuecomment-172896473.
We are still working on to find and fix the issue, don't worry.

**Comment by infograf768** [comment] 2016-01-20 18:03
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8641">issues.joomla.org/joomla-cms/8641</a>

**Comment by infograf768** [comment] 2016-01-20 18:03
Closed as not Joomla Core. See https://github.com/joomla/joomla-cms/issues/8421<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8641">issues.joomla.org/joomla-cms/8641</a>.</sub>

**Closed by infograf768** 2016-01-20 18:03 UTC
Labels: No Code Attached Yet

**Comment by MixingOnBeat** [comment] 2016-01-21 02:44
Not sure if my host has Suhosin installed or not. I just sent them an email to find out. I hope this fixes this issue on my side also.

I echo what @N6REJ stated above about trying to fix this issue on Joomla's end. Other software like phpBB, Vbulletin, Wordpress and etc. Don't have this issue.

**Comment by N6REJ** [comment] 2016-01-23 12:57
@MixingOnBeat please ask your host to set suhosin.request.disallow_nul=Off instead of "on" which is the default and let me know if this fixes it.

**Comment by gwsdesk** [comment] 2016-01-23 17:09
Troy that is no solution. It disables Suhosin (which is "hardening" of 
PHP and very much needed) and is a bad advise imho

Leo

**Comment by N6REJ** [comment] 2016-01-24 03:36
It was as a test to be sure I was on the right track... I was reading in 
suhosin git and that apparently is the issue which is why they updated 
suhosin, now, IF that does solve it, which I bet it will, then we can 
change joomla so its outputting a empty string instead of a null to 
$post can't we?  if_empty() treats null just the same as "" or '' so ......
Bear

**Comment by MixingOnBeat** [comment] 2016-01-24 04:00
@N6REJ, my host won't do it.  Since I am on a host server, what affects my site affects others.

Hopefully you can figure this out.  I think Joomla needs to find a common ground here.

**Comment by N6REJ** [comment] 2016-01-24 13:24
@MixingOnBeat makes sense... perhaps @izharaazmi can check if what my suspicion is is true and then fix it :dash:

**Comment by MixingOnBeat** [comment] 2016-03-29 07:16
I'm still having this issue with Joomla 3.5

Site Information:
    OS Linux n
    PHP 5.6.17
    MySQL 5.6.29
    Caching Enabled
    GZip Enabled
    Articles 204

**Comment by izharaazmi** [comment] 2016-03-29 07:39
Since this is essentially not caused by Joomla, it will be observable with
any of the PHP application out there.

However @MOB, if you want me to fix it for you I can develop a Joomla
plugin for you.

I still recommend to fix your suhosin installation or move to another host.

**Comment by gwsdesk** [comment] 2016-03-29 08:22
Hi Izhar,
Just to confirm that installing the later version of Suhosin all is still working with Joomla 3.5.0 & J3.5.1 RC1. As discussed and resolved previously this is indeed cPanel's Suhosin version causing the problems.

I think it would be a good idea if you could find the time to address this with a plugin (found a descnt amount of posts on the Joomla forums on this) and since it seems that this will not find a "home" at/in Joomla I am most willing to list it (as your product) on the JED with a download-link from gws-desk.com (free of course) as token of appreciation. You have my email and I have yours so we can detail this off-Github

**Comment by izharaazmi** [comment] 2016-04-03 11:05
@gwsdesk I emailed you regarding the test env for said plugin. Probably you didn't receive that. Well I do not have the setup to test it therefore I am putting it on github today, untested.
You can always tell me when it doesn't work. :smile:

**Comment by UWiX-nl** [comment] 2016-04-06 07:31
@izharaazmi I would be very glad to test the plugin also. Tried to find it on your Github account but only readme is found.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8641">issues.joomla.org/joomla-cms/8641</a>.</sub>

**Comment by izharaazmi** [comment] 2016-04-06 07:45
@MixingOnBeat @gwsdesk @UWiX-nl I have uploaded it at https://github.com/izharaazmi/joomla-suhosinfix

**Comment by UWiX-nl** [comment] 2016-04-07 07:53
@izharaazmi: thanx! That does the trick for now. Already in discussion with my hosting provider about this.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8641">issues.joomla.org/joomla-cms/8641</a>.</sub>

**Comment by gwsdesk** [comment] 2016-04-07 09:11
@izharaazmi I did miss your email I am sorry and found it. I have tested this on a box and can confimr this works like a charm. Nice one!

**Comment by izharaazmi** [comment] 2016-04-07 10:47
I created a plugin to workaround this issue. You can download it here https://github.com/izharaazmi/joomla-suhosinfix/releases.

Endorse me on [LinkedIn](http://in.linkedin.com/in/izharaazmi), if you feel like. :smile:

**Comment by MixingOnBeat** [comment] 2016-04-09 00:46
@izharaazmi just loaded your plugin on Joomla 3.5.1 and it's working good.

I tested the search function first to see if in case 3.5.1 update would fix it, but no.  So I then loaded your plugin and enabled it.  Now I can clear my searches in the admin panel.

Thanks! :)

**Comment by izharaazmi** [comment] 2016-04-09 15:47
Glad that I could help. I have posted this at few places where I could find this topic. If any of you find this anywhere else please share this plugin with them too.

**Comment by UWiX-nl** [comment] 2016-04-13 09:18
Nice one - the latest update of Joomla (3.5.1) didn't fix this indeed. But the plugin works perfectly!
Also reported this to my hosting provider and with the information on this page (thank you izharaazmi) the have scheduled an update of Suhosin :-) Way the go Hosty (hostingtime.eu)!

Thank you for the great plugin izharaazmi! <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8641">issues.joomla.org/joomla-cms/8641</a>.</sub>
