### ISSUE TITLE
[4.0] Creating a new admin menu leads of php notices 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29810] opened 2020-06-28 18:17 UTC
### Steps to reproduce the issue

Login to Joomla 4 admin as super admin

Menus -> Manage -> Select Administrator from dropdown

Click New - Set title = `asfjkdhcksjdfyb` - set unique name `asfjkdhcksjdfyb` -> click save and close

Click "Add a module for this menu" button 

Give module a title - select position = menu [menu] click save and close

(The first time there was a link about "menu recovery mode" that I clicked, the second time this never showed)

<img width="1300" alt="Screenshot 2021-05-05 at 19 47 46" src="https://user-images.githubusercontent.com/400092/117193453-cab0eb00-adda-11eb-922e-36287399341f.png">

### Expected result

No PHP Notices

Only ONE of the default menus 

### Actual result

```
Notice: Undefined property: Joomla\CMS\Menu\AdministratorMenuItem::$element in /var/www/html/administrator/modules/mod_menu/src/Menu/CssMenu.php on line 313
```

<img width="745" alt="Screenshot 2020-06-28 at 19 13 33" src="https://user-images.githubusercontent.com/400092/85955006-9925f280-b973-11ea-931d-b4939aa46eac.png">

## And if I scroll down I see another default set of the menu system with "menu recovery" hide/show link

<img width="645" alt="Screenshot 2020-06-28 at 19 15 44" src="https://user-images.githubusercontent.com/400092/85955031-cd011800-b973-11ea-94ab-d781fb0e92b0.png">

### System information (as much as possible)

Joomla 4 beta 1

**Comment by infograf768** [comment] 2020-06-29 06:00
(4.0-dev)
Looks like you forgot to say if you have or not chosen a preset when creating the menu or the module and which preset.

**Comment by PhilETaylor** [comment] 2020-06-29 06:01
I don't believe I did select a preset. No.

**Comment by infograf768** [comment] 2020-06-29 06:01
If I do not select a preset, I do not get your errors.

**Comment by PhilETaylor** [comment] 2020-06-29 06:08
Strange. I'll try again today. Thanks for testing.

**Comment by infograf768** [comment] 2020-06-29 06:20
There are other problems concerning admin menu creation: if one uses a preset (joomla or alternate) when creating the menu (and then that menu in the module instead of a preset), then if you need to delete some menu items through the menu items interface it takes ages to TRASH the menu items in that menu as we get into a loop (also problems with actionlogs...)
Then Empty trash is real broken. Only way is to delete the menu.

Remark that editing the menu itself does not display anymore the preset used. It is confusing.

**Comment by PhilETaylor** [comment] 2020-06-29 08:46
ok I have it replicated now. The Notices dont show when on the Home Dashboard, but if you navigate to Menus ->All menu items then the notes show.

I also had this which I clicked to enable recovery mode 

<img width="1314" alt="Screenshot 2020-06-29 at 09 43 30" src="https://user-images.githubusercontent.com/400092/85992842-602a6400-b9ed-11ea-85fa-e2a1a284b451.png">

**Comment by PhilETaylor** [comment] 2020-06-29 08:52
I replicated as:

Menus -> Manager -> Select Administrator -> Click New =>
Title = MyBrokenMenu
Unique Name = MyBrokenMenu
Import a preset = none
Click Save and close
Click "Add a module for this menu"
Select MyBrokenMenu under Administrator in the left menu
Title = MyBrokenMenuModule
Menu to show = MyBrokenMenu
CheckMenu = yes
Position = Menu [menu]
Click save & close 
Enable Menu Recovery Mode

**Comment by infograf768** [comment] 2020-06-30 08:37
Sorry, confused about this
>  Select MyBrokenMenu under Administrator in the left menu

as it comes after
> Click "Add a module for this menu"

as we are in a modal

But if I ignore this I do indeed get all these Notices from the module in the menu position because the Menu has no menu items (no presets were chosen when creating the Menu and same when creating the module) and **`CheckMenu` was set to `Yes`.**

I guess the solution would be to throw an error somewhere. We just have to find where.

**Comment by infograf768** [comment] 2020-06-30 09:21
btw, I confirm
>(The first time there was a link about "menu recovery mode" that I clicked, the second time this never showed)

**Comment by brianteeman** [comment] 2021-03-14 08:59
This bug is caused by #23452 which probably should not have been merged due to lack of tests

**Comment by PhilETaylor** [comment] 2021-05-05 18:49
This is still a bug today. Ran into it again.

**Closed as completed** 2022-03-07 18:39 UTC
Labels: No Code Attached Yet
