### ISSUE TITLE
[4.0] Joomla Beta 3 — Wamania\Snowball\NotFoundException: Stemmer not found for 

### ISSUE THREAD

**Issue by vintzl** [joomla/joomla-cms#30372] opened 2020-08-14 09:49 UTC
### Steps to reproduce the issue

Do some search with _Smart Search_ while debugging with Xdebug from Vscode.

### Expected result

No exception.

### Actual result

Get exception inside `StemmerFactory.php`:
`Wamania\Snowball\NotFoundException: Stemmer not found for `

inside the following function:

```
  /**
     * @throws NotFoundException
     */
    public static function create(string $code): Stemmer
    {
        $code = UTF8::strtolower($code);

        foreach (self::LANGS as $classname => $isoCodes) {
            if (in_array($code, $isoCodes)) {
                return new $classname;
            }
        }

        throw new NotFoundException(sprintf('Stemmer not found for %', $code));
    }
```

### System information (as much as possible)

Joomla Beta 3 from here :

- https://github.com/joomla/joomla-cms/releases/tag/4.0.0-beta3

### Additional comments

Tested with a clean install.

**Comment by brianteeman** [comment] 2020-08-14 11:23
What language is your site?

**Comment by vintzl** [comment] 2020-08-14 15:32
English (United Kingdom), the only one installed.

**Comment by alikon** [comment] 2020-08-15 08:53
Confirmed
i suspect the cause is that `$code`  is equal `*`
` public static function create(string $code): Stemmer`

**Comment by infograf768** [comment] 2020-08-15 09:19
@Hackwar 
Could you please look at that?

**Comment by brianteeman** [comment] 2020-12-20 14:36
The stemmer has been updated can you please retest. See #31732

**Comment by vintzl** [comment] 2020-12-24 20:57
Seems not solved, as I get this

![image](https://user-images.githubusercontent.com/44751088/103106111-0cfb3c00-4633-11eb-8df5-f07d97d99d2f.png)

**Comment by Quy** [comment] 2020-12-24 21:00
Are you testing with the nightly builds?

https://developer.joomla.org/nightly-builds.html

**Comment by vintzl** [comment] 2020-12-24 21:00
Just tested with Joomla_4.0.0-beta6-dev-Development-Update_Package.zip from here:
- https://developer.joomla.org/nightly-builds.html

**Comment by infograf768** [comment] 2020-12-25 09:47
@alikon is right in a multilingual site:

If you var_dump $code

```
    public static function create(string $code): Stemmer
    {
        $code = UTF8::strtolower($code);
var_dump($code);
        foreach (self::LANGS as $classname => $isoCodes) {
            if (in_array($code, $isoCodes)) {
                return new $classname;
            }
        }

        throw new NotFoundException(sprintf('Stemmer not found for %s', $code));
    }
```

You get when en-GB is the site language (would be *, fr, fr for French):
    
    `string(1) "*" string(2) "en" string(2) "en" `
    
    
If you work in a monolanguage site, then you may have to set Smart Search Options to your language or Default Site Language.
    
<img width="728" alt="Screen Shot 2020-12-25 at 10 42 25" src="https://user-images.githubusercontent.com/869724/103130681-fdfda380-469d-11eb-8384-dd4cc957db40.png">

Do you still get the Exception in that case?

    
### Note
I do not get any suggestions when typing in the search field.
Could someone confirm?

**Comment by infograf768** [comment] 2020-12-25 09:47
@Hackwar

**Comment by richard67** [comment] 2020-12-25 11:32
"Information Required" label removed since the requested information if it still happens with current 4.0 has been provided.

**Comment by bembelimen** [comment] 2020-12-28 04:59
The problem is not the exception. That is caught and the indexer still runs. So no need to fix here anything, it's expected behaviour that there is one when the current language has no stemmer.
But the thing is, that if "*" is the current language, then it's not translated in e.g. "en-GB" (= the current language on the site).
#31795 tries to fix it and reduces the exception numbers.

**Comment by Hackwar** [comment] 2023-02-27 21:26
#39959 should fix this. Closing since we have a PR.

**Closed as completed by Hackwar** 2023-02-27 21:26 UTC
Labels: No Code Attached Yet, bug
