### ISSUE TITLE
Large archive files can' t be uploaded because of false positives in isSafeFile function

### ISSUE THREAD

**Issue by ArtisKrumins** [joomla/joomla-cms#20618] opened 2018-05-29 17:22 UTC
### Steps to reproduce the issue
Create a large (~20MB) zip files containg pdf or docx.
Allow upload of such files in php settings if needed, remove restrictions to upload zip files.
Try to upload file via administrator/index.php?option=com_media

### Expected result
File should be uploaded and if not - more detailed reason why it is not uploaded is welcome.

### Actual result
Blocks upload with msg "You have tried to upload file(s) that are not safe."

### System information (as much as possible)
Joomla 3.8.7

### Additional comments
If archive file is large, there are too many false positives. See screenshot as example. 
Changing 'fobidden_ext_in_content' to FALSE in isSafeFile function (InputFilter.php) resolves issue. Perhaps there is better way to achieve this via UI, but could not find one.

**Comment by ArtisKrumins** [comment] 2018-05-29 17:23
Adding scrrenshot![screen shot 2018-05-29 at 17 23 47](https://issues.joomla.org/uploads/1/33a7e4d48138c08dfce9b5e0a834aba2.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20618">issues.joomla.org/tracker/joomla-cms/20618</a>.</sub>

**Comment by Quy** [comment] 2018-05-29 20:30
Duplicate of #15563?

**Comment by ArtisKrumins** [comment] 2018-05-30 04:17
Yes, looks like the same issue.

**Closed as completed** 2018-05-30 04:22 UTC
Labels: No Code Attached Yet
