### ISSUE TITLE
Joomla 4 - Cannot use a scalar value as an array

### ISSUE THREAD

**Issue by EugyRdT** [joomla/joomla-cms#41103] opened 2023-07-02 14:14 UTC
The call of only some articles generates an error of "0- Cannot use a scalar value as an array"

### perfect example of the issue:
https://eugy.it/it/informatica/56-ingegneria-sociale.html

Expected result: like the corresponding English page:
https://eugy.it/en/informatics/57-social-engineering.html

### System information (as much as possible)
Server LAMP Cpanel
Joomla 4.3.2 just upgraded from 3.10
Template T3 Framework + Purity III

### Additional comments
Issue is generated in articles, it shows also when clicking upper tabs "informatics" and "coffer" because that link should show a two-columns view of the intro of the articles, for example the tab "goliardia" has NOT the issue becaus it shows only ONE article.

I'm not able to check it, because all articles are made - more or less - in the same way.

This is my first issue, I didn't find anything to solve it by my self. Hope I'm doing the right thing.

**Comment by chmst** [comment] 2023-07-02 14:20
It is not quite the right place - a better place for your question is https://forum.joomla.org. They surely know how to help you. 
Because this is probably caused by older override for articles, in your Template.

**Comment by EugyRdT** [comment] 2023-07-02 16:28
It seems like my template has NO overrides, more it sounds strange to me, override work for just some articles and not for others... I'm not able to check all files shown in the error page...

**Comment by brianteeman** [comment] 2023-07-02 17:08
Unpublish the module mod_social_comments_sharing - that is what is causing the problem.

**Comment by chmst** [comment] 2023-07-02 17:11
As @brianteeman says.  Pleasepost in  forum.joomla.org if you need a replacement for your module. Closing here as it is not a Joomla Core issue.

**Closed as completed by chmst** 2023-07-02 17:11 UTC
Labels: No Code Attached Yet
