### ISSUE TITLE
joomla 3.8.8 error uploads images to child folder

### ISSUE THREAD

**Issue by ViscountVic** [joomla/joomla-cms#20585] opened 2018-05-27 04:40 UTC
### Steps to reproduce the issue
Please go to Article Manager -> Add Article.
If move to "Images and Links" block and press "Select" for "Intro Image".
Folder path not changing - all time showing first parent folder.
Images saving in first parent folder all time.

### Expected result
Should add sub folder path: "/news/2018/" and etc.

### Actual result
All time showing path "/news" folder - but I opened 2 other sub folders.
All files saving in "/news" (/images/news/) folder.

### System information (as much as possible)
Joomla 3.8.8 Update
PHP Version 5.6.33
mysqli mysqlnd 5.0.11-dev - 20120503

Checked in different sites, different hosting's providers. 

#![screen shot 2018-05-27 at 04 39 36](https://issues.joomla.org/uploads/1/b77e7f49af9763fe9ba420daafaa7889.jpg)## Additional comments

**Comment by ghost** [comment] 2018-05-27 05:43
Can't confirm.
Click on Path-Dropdown works as expected:
![bildschirmfoto 2018-05-27 um 07 44 01](https://user-images.githubusercontent.com/8235763/40582853-c8185c28-6181-11e8-8c99-c053697ac476.jpg)
### System information
- 3.8.8
- Monolanguage Site
- Template: Protostar
- macOS Sierra, 10.13.4
- Firefox 60 (64-bit)
#### MAMP 4.2
- Apache-Server
- PHP 7.1.12
- MySQLi 5.6.38

**Comment by ViscountVic** [comment] 2018-05-27 06:05
Drop down menu working right. 

If you will click folder in list of folders and images. Then will be openned necessary folder, but path in dropdown list will not changed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20585">issues.joomla.org/tracker/joomla-cms/20585</a>.</sub>

**Comment by ViscountVic** [comment] 2018-05-27 06:14
![screen shot 2018-05-27 at 06 14 55](https://issues.joomla.org/uploads/1/d5e3a01a062206244855fc4efdac1c15.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20585">issues.joomla.org/tracker/joomla-cms/20585</a>.</sub>

**Comment by ViscountVic** [comment] 2018-05-27 06:44
Users with same problem: 

https://forum.joomla.org/viewtopic.php?f=706&t=962279<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20585">issues.joomla.org/tracker/joomla-cms/20585</a>.</sub>

**Comment by ghost** [comment] 2018-05-27 08:19
Got it, thanks for Info, so Issue confirmed.

But If i choose a Image in an Subfolder it works as expected.

**Comment by ViscountVic** [comment] 2018-05-27 08:42
Yes, but you can't upload images into sub folder. It is really big problem.

For example: I have all images placed in folders and sorted by year, then by month, then by day.
'/news/2018/05/27/'

If I will place all files in root news folder, then I will have 2 000 photos and more in one folder.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20585">issues.joomla.org/tracker/joomla-cms/20585</a>.</sub>

**Comment by Quy** [comment] 2018-05-27 12:12
@mbabker Working as of 3.8.8-RC 1979fe9b6077a938622d54571d50b0f50f59cdc9 I assume one of the update packages broke this.

@ViscountVic For a temporary solution, upload via `Content > Media`

**Comment by mbabker** [comment] 2018-05-27 14:37
If I had to guess it's part of that big patch in com_media to escape all the file paths (which also broke the random image module).  @joomla/security someone look into this...

**Comment by PhilETaylor** [comment] 2018-05-27 14:52
Correct, however the change in the com_media is correct as its url encoding all chars in the folder path,  the issue is that the JS is not then reversing that url encoding before using the folder path.

**Comment by PhilETaylor** [comment] 2018-05-27 15:07
Please test https://github.com/joomla/joomla-cms/pull/20586

**Comment by ghost** [comment] 2018-05-27 15:24
closed as having Pull Request #20586

**Closed as completed** 2018-05-27 15:24 UTC
Labels: No Code Attached Yet
