### ISSUE TITLE
[3.7.0b1] [com_fields] Errors when using invalid SQL

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#13867] opened 2017-02-02 21:50 UTC
### Steps to reproduce the issue

Create a new field of type SQL

Input some crap instead of a SQL (or a sql that doesn't return text and value values) 

### Expected result

basic validation on saving the field to ensure text and value are strings in the sql input

No errors output to the screen

### Actual result

Notice: Undefined property: stdClass::$value in /Users/phil/Downloads/Joomla_3.7.0-beta1-Beta-Full_Package/libraries/joomla/form/fields/sql.php on line 298

Notice: Undefined property: stdClass::$text in /Users/phil/Downloads/Joomla_3.7.0-beta1-Beta-Full_Package/libraries/joomla/form/fields/sql.php on line 298

### System information (as much as possible)

Mysql

**Comment by Bakual** [comment] 2017-02-02 22:48
Needs to be fixed in JFormFieldSql then. Or how would you want to sanitizse the input in the field itself? The input will always be a string and the formfield will only know if it's valid SQL when it tries to run it against the database.

However imho it's fine to show an error.
It's not like a visitor is going to create such fields, it's an admin type (site integrator, or similar) who will create those and it will be helpful for him to see the errors.

**Comment by laoneo** [comment] 2017-02-03 06:49
Please test PR #13882. The SQl form field will catch now the exception. About the error handling I'm not sure.

**Comment by marrouchi** [comment] 2017-02-03 10:00
I was unable to reproduce the issue ...

**Comment by laoneo** [comment] 2017-02-03 12:41
Did you follow the instructions on the pr?

**Comment by marrouchi** [comment] 2017-02-03 13:08
Yes

**Closed** 2017-02-03 17:40 UTC
Labels: No Code Attached Yet
