### ISSUE TITLE
Update Joomla 3.8.7 to 3.8.8

### ISSUE THREAD

**Issue by mandersp** [joomla/joomla-cms#20553] opened 2018-05-23 16:36 UTC
When renewing Joomla 3.8.7 to 3.8.8.
I get the following error message on the website.
The administrator side is still accessible.

```
Error: 0 - Using $this when not in object context

You may not be able to visit this page because of:

an out-of-date bookmark/favourite
a search engine that has an out-of-date listing for this site
a mistyped address
you have no access to this page
The requested resource was not found.
An error has occurred while processing your request.

The php version is 7.1
```

The problem is the random image of Joomla

This is the problem in default.php 
`<?php echo JHtml::_('image', $image->folder . '/' . $this->escape($image->name), $this->escape($image->name), array('width' => $image->width, 'height' => $image->height)); ?>`

This is the good one:
`<?php echo JHtml::_('image', $image->folder . '/' . $image->name, $image->name, array('width' => $image->width, 'height' => $image->height)); ?>`

Here can you find it default.php 
modules\mod_random_image\tmpl\default.php

**Comment by mbabker** [comment] 2018-05-23 16:37
Duplicate of #20541

**Closed as completed by mbabker** 2018-05-23 16:37 UTC
Labels: No Code Attached Yet
