### ISSUE TITLE
JError::raiseError inconsistency when module is configured to use different positions

### ISSUE THREAD

**Issue by dkanchev** [joomla/joomla-cms#4762] opened 2014-10-17 11:22 UTC
#### Steps to reproduce the issue

Many developers use the JError::raiseError to show errors and redirect users to the default Joomla! 403/404 pages. Sometimes JError::raiseError shows backtrace information when the module which uses JError::raiseError is configured to use certain module positions. 

For example when a module which uses JError::raiseError is configured to use the "Debug" position it shows the backtrace and the end users see the information on the front page. If such module uses the "Search" position the backtrace is not displayed. The same behavior is valid for other module positions.

Check the screenshot for more info.

#### Expected result

I believe that the JError::raiseError legacy class should not show the backtrace by default in any cases.

#### Actual result

The backtrace is displayed in some cases.

#### System information (as much as possible)

CentOS
PHP 5.5
MySQL 5.5

#### Additional comments

None

**Comment by brianteeman** [comment] 2015-11-12 13:39
Is this still a valid issue - its been almost a year since the last comment<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4762">issues.joomla.org/joomla-cms/4762</a>.</sub>

**Comment by photodude** [comment] 2015-11-21 19:40
Would it be worth doing a mass search and replace of `JError::raiseError` with `JFactory::getApplication()->enqueueMessage` and determine cases needing Exception handling later?

**Comment by mbabker** [comment] 2015-11-21 19:56
I wouldn't go that route.  `JError::raiseError()`, the way the handlers are configured in the application bootstrap, is meant to redirect immediately to the error page and end processing.  Enqueuing a message without altering what happens after that can result in unexpected behaviors.  `JError::raiseError()` should probably map to Exceptions being thrown instead of just enqueuing a message.  Problem is there is so much code in the CMS that expects JError style handling or doesn't handle errors at all that you're looking at a rather large project with no simple fix which is why PRs like https://github.com/joomla/joomla-cms/pull/8130 get accepted as massive hacks to mask the poor error handling in general.

**Comment by photodude** [comment] 2015-11-29 01:03
Would the more correct replacement for:
`JError::raiseError(403, JText::_('JLIB_APPLICATION_ERROR_ACCESS_FORBIDDEN'));`
be along the lines of:
`throw new Exception(JText::_('JLIB_APPLICATION_ERROR_ACCESS_FORBIDDEN'), 403);`

(of course I'm not sure where the exception catch in the CMS would happen, or if an exception catch would need to be added along with the JError replacements)

**Comment by brianteeman** [comment] 2016-05-08 15:20
Thank you for creating this but based on the comments above about jerror I am closing this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4762">issues.joomla.org/joomla-cms/4762</a>.</sub>

**Closed** 2016-05-08 15:20 UTC
Labels: No Code Attached Yet
