### ISSUE TITLE
Blank registration form page after upgrading to 3.6.5

### ISSUE THREAD

**Issue by Frostbourn** [joomla/joomla-cms#13423] opened 2016-12-30 15:02 UTC
Registration form just dissapeared after upgrading from 3.6.4 to 3.6.5. 

> /component/users/?view=registration

There was only blank page, no errors (error_reporting set to maximum in the backend and turned on in php.ini). I solved this issue by replacing:  

> components/com_users/models/registration.php

from 3.6.4 release.

**Comment by bertmert** [comment] 2016-12-30 18:03
I don't know if it's really related but did you test this change already:
https://github.com/joomla/joomla-cms/commit/37222604e2ce92f00072f554f44b6a97cfc66756

**Comment by Frostbourn** [comment] 2016-12-31 09:08
+1, thank you bertmert.

**Comment by Frostbourn** [comment] 2016-12-31 09:09
+1, thank you bertmert.

**Comment by tonypartridge** [comment] 2017-01-03 06:51
Did the fix by mbabker solve your issue?

Do you have a template override in place?

**Comment by franz-wohlkoenig** [comment] 2017-02-06 07:09
@Frostbourn is this still an Issue?

**Comment by Quy** [comment] 2017-04-17 21:51
Unable to reproduce.
Installed Joomla 3.6.4.
Upgraded to Joomla 3.6.5.
Registration form appears and works as expected.

**Comment by zero-24** [comment] 2017-04-17 22:42
Closing again. As this is fixed by the change posted above.

**Closed** 2017-04-17 22:41 UTC
Labels: No Code Attached Yet
