### ISSUE TITLE
[3.8.2] Open disabled menu links in a new page (administrator)

### ISSUE THREAD

**Issue by PixedBo** [joomla/joomla-cms#18977] opened 2017-12-04 15:22 UTC
Hello, i don't know if this is intended but if you enter a page where main menu is disabled (like "new article") if you click on a menu entry nothing happens (and that's ok) but if you click with middle mouse button (the scroll wheel) the link opens in a new tab.
For example if you do it when akeeba is making a backup the new opened tab creates a new backup process and don't know what errors this may cause...

**Comment by tonypartridge** [comment] 2017-12-05 00:39
This is standard and expected in my opinion. The reason the menu is locked out is to prevent the user navigating away whilst processing a task. But opening in a new tab is fine since the session and task in question is left perfectly intact.

**Comment by PixedBo** [comment] 2017-12-05 07:42
Ok, thank you for your answer.

**Comment by ghost** [comment] 2017-12-05 12:54
closed as expected Behaviour.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18977">issues.joomla.org/tracker/joomla-cms/18977</a>.</sub>

**Closed as completed by ghost** 2017-12-05 12:54 UTC
Labels: No Code Attached Yet
