### ISSUE TITLE
[Isis] Menu separator on mobile has wrong background

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#17987] opened 2017-09-19 16:02 UTC
### Steps to reproduce the issue

- Reduce the viewport size until the mobile menu kicks in
- Expand the "Menus" dropdown

You'll notice that the "Site" (and probably "Admin" too, if used) has the wrong background colour

### Expected result

A clear separator, where you can still read the text

### Actual result

![screeny](https://user-images.githubusercontent.com/2019801/30602422-692041de-9d5c-11e7-87c7-df705d56ada6.png)

**Comment by mbabker** [comment] 2017-09-19 16:15
Duplicate of https://github.com/joomla/joomla-cms/issues/16267

**Closed as completed by mbabker** 2017-09-19 16:15 UTC
Labels: No Code Attached Yet
