### ISSUE TITLE
Menu Item Filter in Module Manager None doesn´t show modules that were assigned to a deleted page

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#13108] opened 2016-12-06 21:55 UTC
### Steps to reproduce the issue
Assign a module to a menu-item (only to one)
Delete the menu-item permanently (also from trash)
Go into module-manager and select "None" in the Select Page Filter

![image](https://cloud.githubusercontent.com/assets/828371/20945226/b4e9bb0a-bc06-11e6-9a63-751ad3076c2c.png)

The module is not in the filtered list.

### Expected result

There should be all currently unassigned modules. If the menu-item is deleted, the module shouldn´t be assigned anymore.

### Actual result

It shows only modules that are "really" unassigned

### System information (as much as possible)
Current staging

### Additional comments

useful option to cleanup module-mess from template startup packages...

**Comment by andrepereiradasilva** [comment] 2016-12-07 23:02
Confirmed.

probably the issue is when you delete a menu item all modules references to that menu item id in `#__modules_menu` table aren't being removed.

I confirmed they are not removed from the modules_menu table.
So that seems to be the issue.

**Comment by brianteeman** [comment] 2016-12-08 09:25
Closed as we have a PR for testing #13126

**Closed by brianteeman** 2016-12-08 09:25 UTC
Labels: No Code Attached Yet
