### ISSUE TITLE
In the Backend the Contacts Menü under Components are not available

### ISSUE THREAD

**Issue by Hendrik81Polo** [joomla/joomla-cms#15925] opened 2017-05-09 20:35 UTC

**Comment by Hendrik81Polo** [comment] 2017-05-09 20:37
When updating to 3.7, the contacts can no longer be found in the backend in the administrative menu under Components

**Comment by franz-wohlkoenig** [comment] 2017-05-10 06:10
closed as Duplicate of #15719<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15925">issues.joomla.org/tracker/joomla-cms/15925</a>.</sub>

**Closed by franz-wohlkoenig** 2017-05-10 06:10 UTC
Labels: No Code Attached Yet
