### ISSUE TITLE
[com_fields] Custom Fields: Creating a New Field with the same Name (therefore alias) of another field fails

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#13404] opened 2016-12-29 13:04 UTC
1) Create a text field with the name test and save it
2) Create a media field with the name test and save it
3) It says successfully saved
4) Check the field overview
5) the second test field is missing, maybe because of the same alias

**Comment by Bakual** [comment] 2016-12-29 14:32
Yep, alias have to be unique or it will not work. Since there is a discussion to remove (or at least rename) that field that isn't solved yet.

**Comment by jajodiaraghav** [comment] 2017-01-11 07:53
What changes can be made in order to fix this issue? Will showing a warning that says "Name already in use, Use a different one" work? Or is there something else that can be done?

**Comment by Bakual** [comment] 2017-01-11 07:57
My suggestion is to remove the alias completely and use the ID (which is unique by design) instead: https://github.com/joomla/joomla-cms/pull/13182

**Comment by laoneo** [comment] 2017-01-16 07:26
Can we close this one as we have a pr #13576 for it.

**Closed** 2017-01-16 10:20 UTC
Labels: No Code Attached Yet
