### ISSUE TITLE
The BATCH feature of Module Manager UNpublishes and changes module names.

### ISSUE THREAD

**Issue by nemmar** [joomla/joomla-cms#4918] opened 2014-10-24 15:43 UTC
#### Steps to reproduce the issue

I am a Joomla website admin. I would like to report a possible Joomla 3.3.6 bug:

When I use the BATCH feature of the Module Manager to change module positions it also changes the name of the module which I don't want (like you are copying the module when you're not) and it also UNpublishes the modules.

**Comment by zero-24** [comment] 2015-05-09 12:54
Moving to `Needs Review` so a Maintainer can decide if this should changed or not. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4918">issues.joomla.org/joomla-cms/4918</a>.</sub>

**Comment by stellainformatica** [comment] 2016-03-14 12:35
Hi, this is an old tracker, but I confirm that the issue about the moved modules that are unpublished is still in Joomla 3.5.0rc2
The problem is more evident when an administrator moves a lot of modules.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4918">issues.joomla.org/joomla-cms/4918</a>.</sub>

**Comment by wilsonge** [comment] 2016-05-07 09:45
See #10270 for a PR

**Closed by wilsonge** 2016-05-07 09:45 UTC
Labels: No Code Attached Yet
