### ISSUE TITLE
Joomla 4 - PATCH is not working

### ISSUE THREAD

**Issue by fernandomarra** [joomla/joomla-cms#35699] opened 2021-09-29 13:22 UTC
### Steps to reproduce the issue

Get an article:

```
curl --location --request GET 'http://camminodelgusto-001-site1.mysitepanel.net//api/index.php/v1/content/articles/1' \
--header 'Authorization: Bearer ---------------------------------
```
Here is the article:
```
{
    "links": {
        "self": "http://camminodelgusto-001-site1.mysitepanel.net/api/index.php/v1/content/articles/1"
    },
    "data": {
        "type": "articles",
        "id": "1",
        "attributes": {
            "typeAlias": "com_content.article",
            "id": 1,
            "asset_id": 63,
            "title": "Prova Fernando",
            "alias": "prova-fernando",
            "state": 1,
            "created": "2021-09-27 09:18:35",
            "created_by": 274,
            "created_by_alias": "",
            "modified": "2021-09-28 10:38:18",
            "modified_by": 274,
            "publish_up": "2021-09-27 09:18:35",
            "publish_down": null,
            "images": {
                "image_intro": "",
                "float_intro": "",
                "image_intro_alt": "",
                "image_intro_caption": "",
                "image_fulltext": "",
                "float_fulltext": "",
                "image_fulltext_alt": "",
                "image_fulltext_caption": ""
            },
            "urls": {
                "urla": false,
                "urlatext": "",
                "targeta": "",
                "urlb": false,
                "urlbtext": "",
                "targetb": "",
                "urlc": false,
                "urlctext": "",
                "targetc": ""
            },
            "version": 3,
            "metakey": "",
            "metadesc": "",
            "access": 1,
            "hits": 0,
            "metadata": {
                "robots": "",
                "author": "",
                "rights": "",
                "xreference": ""
            },
            "featured": 1,
            "language": "*",
            "note": "",
            "tags": [],
            "featured_up": null,
            "featured_down": null,
            "text": "Pippero11 "
        },
        "relationships": {
            "category": {
                "data": {
                    "type": "categories",
                    "id": "2"
                }
            },
            "created_by": {
                "data": {
                    "type": "users",
                    "id": "274"
                }
            },
            "modified_by": {
                "data": {
                    "type": "users",
                    "id": "274"
                }
            }
        }
    }
}
```

Perform PATCH on the existing article 

```
curl --location --request PATCH 'http://camminodelgusto-001-site1.mysitepanel.net//api/index.php/v1/content/articles/1' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer ----------------------------------------- \
--data-raw '{"title": '\''Updated article'\''}'
```

### Expected result

[]

### Actual result

HTTP Error 404.0 - Not Found

### System information (as much as possible)

<html>
<body>

Setting | Value
-- | --
PHP Built On| Windows NT WIN5248 10.0 build 17763 (Windows Server 2016) AMD64
PHP| 7.4.14
Web Server| Microsoft-IIS/10.0
Joomla| VersionJoomla! 4.0.3 Stable [ Furaha ] 12-September-2021 10:39 GMT
User Aget | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36

</body>
</html>

**Comment by alikon** [comment] 2021-10-01 06:02
unable to reproduce
![image](https://user-images.githubusercontent.com/181681/135572979-1adc3d12-5c46-4d07-942f-f369728f3ec3.png)

**Comment by Quy** [comment] 2021-12-16 22:08
Closing as not reproducible.

**Closed as completed by Quy** 2021-12-16 22:08 UTC
Labels: No Code Attached Yet, Information Required
