### ISSUE TITLE
Creating Menu Item as Text Separator causes error displaying list of menu items

### ISSUE THREAD

**Issue by ConfidantCommunications** [joomla/joomla-cms#18494] opened 2017-11-03 23:06 UTC
### Steps to reproduce the issue
On a site with multiple menu items, go to the back end and edit the Main menu. Create one menu item of type "Text Separator" or "Menu Heading"![screen shot 2017-11-03 at 23 05 40](https://issues.joomla.org/uploads/1/a3d2bc281aa577d4567a7783c2065a04.png). 

### Expected result
It should create a single menu item and display it in the list.

### Actual result
It creates a single menu item in the database, but in the listing of the Main Menu items (option=com_menus&view=items) the new item appears multiple times and appears to take up several pages.

### System information (as much as possible)
PHP Built On 	Linux usm40.siteground.biz 3.12.18-clouder0 #85 SMP Mon Apr 3 10:28:14 EEST 2017 x86_64
Database Version 	5.6.36-82.1-log
Database Collation 	utf8_general_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	5.6.31
Web Server 	Apache
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 3.8.1 Stable [ Amani ] 4-October-2017 14:00 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:57.0) Gecko/20100101 Firefox/57.0

**Comment by brianteeman** [comment] 2017-11-03 23:13
Sounds like a corruption in your database. Try clicking on the rebuild icon on the toolbar

**Comment by ConfidantCommunications** [comment] 2017-11-03 23:16
I did that now. This does not reduce the number of items shown.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18494">issues.joomla.org/tracker/joomla-cms/18494</a>.</sub>

**Comment by tonypartridge** [comment] 2017-11-05 06:52
You haven’t got any items under it? What happens when you add items under it since that is what menu item headings are for.

**Comment by infograf768** [comment] 2017-11-06 09:58
@tonypartridge 
with or without items under it, these menu items display here OK.
The OP issue is imho unrelated.

**Comment by ConfidantCommunications** [comment] 2017-11-06 12:04
This happens to me when adding a Text Separator or a Menu Heading. The screenshot shows what happens directly after adding it. I have since been able to add child items of the repeated item, but it still shows as repeated. 
@infograf768 Sorry I don't know what an "OP" issue is.

**Comment by infograf768** [comment] 2017-11-06 16:35
> Sorry I don't know what an "OP" issue is.

OP = Original poster => you 😄 

What I said was that I can't reproduce your issue, whether with or without using the text separator or Heading before another menu item.

**Comment by ConfidantCommunications** [comment] 2017-11-06 16:40
Alright, thanks for trying!

**Comment by brianteeman** [comment] 2017-12-21 00:04
I am closing this at this time as not reproducible. It can always be reopened if further information is provided

**Closed as completed by brianteeman** 2017-12-21 00:04 UTC
Labels: No Code Attached Yet
