### ISSUE TITLE
Bootstrap tab contains slash if language file or override contains single quote

### ISSUE THREAD

**Issue by vinespie** [joomla/joomla-cms#11400] opened 2016-08-02 12:54 UTC
After JHtmlBootstrap modification #3922, tab label contains slashes if language text (example in FR-fr) contains single quote.

#### Steps to reproduce the issue
1- Go to Administrator -> Extensions -> Langages -> Overrides
2- Add override with single quote :
![2016-08-02 14_29_41-languages_ edit override - joomla 3 - administration](https://cloud.githubusercontent.com/assets/5129879/17328456/268060a4-58be-11e6-8ea3-104122762b0f.jpg)
3- Go to "Add New Menu Item"
4- Table label contains slash :
![2016-08-02 14_32_47-menus_ new item - joomla 3 - administration](https://cloud.githubusercontent.com/assets/5129879/17328488/511651de-58be-11e6-9a21-ad200d1df4d6.jpg)

#### Expected result
Tab label whithout slash before single quote

#### Actual result
![2016-08-02 14_32_47-menus_ new item - joomla 3 - administration](https://cloud.githubusercontent.com/assets/5129879/17328488/511651de-58be-11e6-9a21-ad200d1df4d6.jpg)

#### System information (as much as possible)
Joomla 3.6.0

#### Additional comments
It is necessary to add javascript safe when generating bootstrap tab ?
[https://github.com/joomla/joomla-cms/blob/staging/layouts/joomla/edit/params.php#L52](url)
`$label = JText::_($fieldSet->label, true);`

**Comment by brianteeman** [comment] 2016-08-02 14:42
I can confirm it on the menu tab but not the article tab and only when using the ' but not the `

![screen shot 2016-08-02 at 09 39 42](https://issues.joomla.org/uploads/1/ac5df5d6489eadc49890d2967b1633ee.png)![screen shot 2016-08-02 at 09 39 45](https://issues.joomla.org/uploads/1/cf8b1e0aa6cd7308c2e9b4c8968cc977.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11400">issues.joomla.org/joomla-cms/11400</a>.</sub>

**Comment by vinespie** [comment] 2016-08-02 15:12
In article tab, chain translation is not javascript safe.

administrator\components\com_content\views\article\tmpl\edit.php line 123
`<?php echo JHtml::_('bootstrap.addTab', 'myTab', 'images', JText::_('COM_CONTENT_FIELDSET_URLS_AND_IMAGES')); ?>`

But possibly same problem in :
administrator\components\com_plugins\views\plugin\tmpl\edit_options.php line 16
administrator\components\com_weblinks\views\weblink\tmpl\edit.php line 38 - 52 - 64
components\com_contact\views\contact\tmpl\default.php line 174

**Comment by infograf768** [comment] 2016-08-02 15:18
There are many occurences of bootstrap.addTab and none has addslashes added before the JText:: Good find!

it only concerns ' and not ` as this last one is not a quote in the php sense of the term.

**Comment by brianteeman** [comment] 2016-08-02 15:19
I'm confused because I showed that the URLS and IMAGES tab works ok

**Comment by infograf768** [comment] 2016-08-02 15:21
issue is that we have 81 `bootstrap.addTab` in core and adding addslashes() everywhere is not the perfect solution. We may need a better one that would be global. Don't know if possible.

**Comment by infograf768** [comment] 2016-08-02 15:23
Let me check further

**Comment by vinespie** [comment] 2016-08-02 15:28
in \layouts\libraries\cms\html\bootstrap\addtabscript.php line 19 , there is "json_encode" apply on title.
Maybe a change must be made on this file.

**Comment by infograf768** [comment] 2016-08-02 15:36
I confirm that reverting the part of  #3922 concerning \layouts\libraries\cms\html\bootstrap\addtabscript.php solves the issue

**Comment by infograf768** [comment] 2016-08-02 15:57
@vinespie 

To solve the issue I changed the line 17 to

`$li = '<li class="' . $active . '"><a href="#' . $id . '" data-toggle="tab">' . stripslashes($title) . '</a></li>';`

can you test this?

**Comment by vinespie** [comment] 2016-08-02 16:07
Yes it solve the issue but for example you also can change "layouts\joomla\edit\params.php" line 52
`$label = JText::_($fieldSet->label, true);`
by
`$label = JText::_($fieldSet->label);`

what is the best/correct solution ?

**Comment by infograf768** [comment] 2016-08-02 16:27
Maybe better in params.php:
If we use the second proposal I guess we also have to change the rest, i.e.
```
		if (!empty($fieldSet->label))
		{
			$label = JText::_($fieldSet->label);
		}
		else
		{
			$label = strtoupper('JGLOBAL_FIELDSET_' . $name);
			if (JText::_($label) == $label)
			{
				$label = strtoupper($app->input->get('option') . '_' . $name . '_FIELDSET_LABEL');
			}
			$label = JText::_($label);
		}
```
Can you make a PR?

**Comment by vinespie** [comment] 2016-08-02 16:52
Yes I can do a PR.
It will also correct the problems in other files.

**Comment by roland-d** [comment] 2016-08-02 16:56
What I find very odd is that it doesn't happen on all views. Does this mean we render tabs in different ways in different places?

The jsSafe parameter should only be used if the text string is going to be used in Javascript code which is not the case for tabs.

I agree the fix in the params.php file should be good enough as we don't need Javascript escaping here.

**Comment by vinespie** [comment] 2016-08-02 17:12
Yes I agree
Do not escape the title to add tabs
What I found is that in some views using JText with jsSafe on tab title.

Same issue with jsSafe parameter in components/com_contact/views/contact/tmpl/default.php  line 174
`<?php echo JHtml::_('bootstrap.addTab', 'myTab', 'display-profile', JText::_('COM_CONTACT_PROFILE', true)); ?>`

**Comment by roland-d** [comment] 2016-08-02 17:21
@vinespie That may just be copy-paste rather than a conscious decision. As far as I know is the title not used for any Javascript related functions, that is what the ID is for.

**Comment by vinespie** [comment] 2016-08-02 18:33
@roland-d  ok, should I do a pull request for each files or all in one ?

**Comment by roland-d** [comment] 2016-08-02 18:42
@vinespie How many files are there?

**Comment by vinespie** [comment] 2016-08-02 18:50
@roland-d 4 files but for testing using different 

administrator\components\com_admin\views\profile\tmpl\edit.php
administrator\components\com_plugins\views\plugin\tmpl\edit_options.php
components\com_contact\views\contact\tmpl\default.php
joomla-cms\layouts\joomla\edit\params.php

**Comment by roland-d** [comment] 2016-08-02 19:10
@vinespie Since there are only 4, do it in 1 PR but provide test details per file as that will help testers to see what they need to check. Thanks.

**Comment by brianteeman** [comment] 2016-08-02 19:36
That will be great - thanks

**Comment by infograf768** [comment] 2016-08-03 06:03
@vinespie 
Can you make the PR towards staging please

**Comment by infograf768** [comment] 2016-08-03 06:11
If you have no time, I will do.

**Comment by vinespie** [comment] 2016-08-03 06:45
@infograf768 Yes you can do it.
I have 3 problems and I block : 
- commit with unknow user
- go  on .gitignore
- why my PR contains old commits ?

I can write test process.
Thanks

**Comment by infograf768** [comment] 2016-08-03 06:51
OK, on it now

**Comment by infograf768** [comment] 2016-08-03 07:19
@vinespie Please add the test instructions in https://github.com/joomla/joomla-cms/issues/11409

**Comment by infograf768** [comment] 2016-08-03 07:33
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11400">issues.joomla.org/joomla-cms/11400</a>

**Comment by infograf768** [comment] 2016-08-03 07:33
Closing as we have a PR (Thanks @vinespie <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11400">issues.joomla.org/joomla-cms/11400</a>.</sub>

**Closed by infograf768** 2016-08-03 07:33 UTC
Labels: No Code Attached Yet
