### ISSUE TITLE
The Debug Permissions Report don't work correct on Joomla 3.x

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#4117] opened 2014-08-15 09:43 UTC
#### Steps to reproduce the issue

1. Install J25
2. Enable debug on J25
3. Go to Backend --> Users --> User Manager --> Debug Permissions Report
4. See what is there; Something like:

![screen shot 2014-08-15 at 04 33 58](http://issues.joomla.org/uploads/1/aaa6234e079d2ea7e8a792b4597cba2d.jpg)

1. Install J3
2. Enable debug on J3
3. Go to Backend --> Users --> User Manager --> Debug Permissions Report
4. See what is there; Something like:

![screen shot 2014-08-15 at 04 34 34](http://issues.joomla.org/uploads/1/e67d64251b69c2011f00a72631c2e4da.jpg)

#### Expected result

Show the permissions for the user (see J2.5.x)
![screen shot 2014-08-15 at 04 33 58](http://issues.joomla.org/uploads/1/aaa6234e079d2ea7e8a792b4597cba2d.jpg)

#### Actual result

Don't show the permissions for the user (see J3.x)
![screen shot 2014-08-15 at 04 34 34](http://issues.joomla.org/uploads/1/e67d64251b69c2011f00a72631c2e4da.jpg)

#### System information (as much as possible)

PHP 5.4.16 (xampp)
J3.3.4-dev && J2.5.25-dev

#### Additional comments

Same issue is if for the Group Permission Report: Backend --> Users --> Groups --> Debug Permissions Report

**Comment by brianteeman** [comment] 2015-01-21 00:37
I can confirm that this doesnt work at all - as can be seen from the screenshots there is a legend displayed but nothing is displayed in the tanle - checked in Isis and Hathor<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4117">issues.joomla.org/joomla-cms/4117</a>.</sub>

**Comment by brianteeman** [comment] 2015-01-21 01:35
It looks to me as if this hasnt worked at all since before the release of J3.2

I am guessing it is related to the change from models to model and forms to form etc

Hopefully thats enough of a clue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4117">issues.joomla.org/joomla-cms/4117</a>.</sub>

**Comment by brianteeman** [comment] 2015-01-21 01:55
See #5841 for a fix<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4117">issues.joomla.org/joomla-cms/4117</a>.</sub>

**Closed** 2015-01-21 01:55 UTC
Labels: No Code Attached Yet
