### ISSUE TITLE
Category visible after upgrade to 3.7.0

### ISSUE THREAD

**Issue by dsimonse** [joomla/joomla-cms#16008] opened 2017-05-14 08:45 UTC
### Steps to reproduce the issue

After the upgrade to Joomla 3.7.0 the "category" is visible at top of the article, and I can't get rid of it.
http://rojteatern.nu/foerestaellningar/hemsoeborna.html > select "Medverkande" and click och the image.
Normally I adjust this in the article-settings but no effect now.

![screen shot 2017-05-14 at 08 40 46](https://issues.joomla.org/uploads/1/594df47ed061f56b8b5ba135932f86de.png)### Expected result

Medverkande i Hemsöborna
Skådespelare

### Actual result

 Artiklar <<<<<<<<<<<<<<<<<<<<<<<<<<
Medverkande i Hemsöborna
Skådespelare

### System information (as much as possible)
Joomla 3.7.0
Yougrids template
PHP 5.6.30

**Comment by brianteeman** [comment] 2017-05-14 08:49
Can you please temporarily switch to one of the default templates like protostar and see if the problem is resolved as this will indicate an issue with the template and not the core of joomla

**Comment by dsimonse** [comment] 2017-05-14 14:19
If I add a hidden menu to this article, the category doesn't show if I use the direct URL to the article.
The category still shows up when I acess it through the pop-up-link to the article (regardless if I use JCE-popup or Windows-popup).
Altering the template shows the same result as for the direct URL described above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16008">issues.joomla.org/tracker/joomla-cms/16008</a>.</sub>

**Comment by dsimonse** [comment] 2017-05-17 21:32
No change with 3.7.1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16008">issues.joomla.org/tracker/joomla-cms/16008</a>.</sub>

**Comment by dsimonse** [comment] 2017-05-23 19:42
No change with 3.7.2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16008">issues.joomla.org/tracker/joomla-cms/16008</a>.</sub>

**Comment by franz-wohlkoenig** [comment] 2017-05-24 04:46
@dsimonse 
have you asked help on the [forums](https://forum.joomla.org/)? Cause this repository concerns mainly Joomla coding and if this Issue is a common one there would be more Informations like yours.

**Comment by dsimonse** [comment] 2017-05-24 06:23
Hi,

I put this issue on theforum at first, and then here, and then to the YouJoomla support.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16008">issues.joomla.org/tracker/joomla-cms/16008</a>.</sub>

**Comment by franz-wohlkoenig** [comment] 2017-05-24 07:13
so then please close this issue here as this is mainly about Joomla Core coding. Thanks.

**Closed** 2017-05-24 19:48 UTC
Labels: No Code Attached Yet
