### ISSUE TITLE
Article editor tabs form publishing not displaying in joomla 3.7

### ISSUE THREAD

**Issue by jeroenduller** [joomla/joomla-cms#15731] opened 2017-05-02 08:18 UTC
### Steps to reproduce the issue
update to 3.7
replaced Isis template from other updated website
empty browser cache
other browser

### Expected result

Tabs for: Content, Images and links, options, publishing, configure edit screen, permissions

### Actual result

no tabs

### System information (as much as possible)

PHP Built On 	Linux s213.webhostingserver.nl 2.6.32-673.26.1.lve1.4.18.el6.x86_64 #1 SMP Fri Oct 21 11:58:14 EDT 2016 x86_64
Database Version 	5.5.5-10.0.27-MariaDB-cll-lve
Database Collation 	latin1_swedish_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	5.6.28
Web Server 	Apache
WebServer to PHP Interface 	litespeed
Joomla! Version 	Joomla! 3.7.0 Stable [ Amani ] 25-April-2017 15:36 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:52.0) Gecko/20100101 Firefox/52.0 

### Additional comments

on other website updated to 3.7 no issues

**Comment by tonypartridge** [comment] 2017-05-02 09:33
This isn't a Joomla! core error. It is usually caused by a 3rd part plugin. i.e. calling the the calendar field which is broken at the moment in the core without calling the JS / CSS files separately.

**Comment by brianteeman** [comment] 2017-05-19 17:38
I am closing this at this time. If you can replicate this without any external plugins then please let us know and it can be reopened

**Closed by brianteeman** 2017-05-19 17:38 UTC
Labels: No Code Attached Yet
