### ISSUE TITLE
Article Alternative Layout resets to default when saved on front end edit

### ISSUE THREAD

**Issue by amelcher** [joomla/joomla-cms#20513] opened 2018-05-21 11:49 UTC
**Steps to reproduce the issue**
Add an alternative layout file in the article overrides

Go to the article and select the alternative layout from the options tab in the backend

Refresh frontpage article with override to confirm alternative layout.

Next use the front end editor for the article and hit save, the article layout resets to default layout that is chosen in global configuration.

**Expected result**
The article layout should remain the same when editing on the front end.

**Actual result**
There is no option to select alternative layout in front-end article editing. Once I confirmed that the front-end save change the layout - I then selected the alternative layout as the default option in the articles-global configuration. I then refreshed the front-end article page and saved it with the front-end editor. The page did not change to Joomla default, rather it stayed the same as the alternative layout that I selected in global configuration.

**System Info**: 

3.8.7

**Comment by ghost** [comment] 2018-05-28 05:14
Can you please update on [latest Version 3.8.8](https://github.com/joomla/joomla-cms/releases/tag/3.8.8) and test again?

**Comment by amelcher** [comment] 2018-05-29 00:27
Franz,

I was on 3.8.7 and just updated to 3.8.8 and after logging in as admin on frontend, I did not change anything in frontend article edit, just hit the save button and no change from before. It still reverted back to default article setting. Was 3.8.8 supposed to fix this issue? Thanks,

Adam

**Comment by ghost** [comment] 2018-05-29 04:00
> Was 3.8.8 supposed to fix this issue?

It was that this Issue is on latest Release, thanks for making this clear.

**Comment by Klipper** [comment] 2018-06-03 18:38
I tested this issue in Joomla 3.8.8, but could not reproduce this issue. I created new articles in the front-end editor. Then I changed the layout property to a custom layout value in the back-end editor (administrator) and saved. Then I edited the same article again in the frontend editor, saved, but the article-layout property was not changed to default again. So for me is this not an issue.

For me is the issue that I cannot set the Layout property from front-end editor. Still searching for a way to establish that...

**Comment by ghost** [comment] 2018-06-03 18:43
@Klipper thanks for Investigation.

**Comment by amelcher** [comment] 2018-06-04 14:56
@Klipper I had previously only created articles in backend, so I created a new Create Article menu item and then created a new article from the front end.  I then went into the backend and changed the layout from global to each of my 6 different article layouts and each time, it reset the layout to the global setting.  I then thought that versions could of played a part so I turned that off and retested again and same results.  Are you using a 3rd party template?

**Comment by amelcher** [comment] 2018-06-04 22:24
Would it help for me to do a short video clip showing everything that is happening?

**Comment by brianteeman** [comment] 2018-06-04 22:30
@amelcher always helps. If you need some quick, easy to use and free software for this try licecap http://www-dev.cockos.com/licecap/

**Comment by Klipper** [comment] 2018-06-04 22:59
@amelcher Did you changed the global article settings for this? I only changed layout-property on single article level. 
So:
Frontend: article creation => Layout is set automaticly to Default (= global setting) ==>
Backend: open article => changed Layout to 'Blog'(=name of my custom layout) => saved ==>
Frontend: open article => changed some text => saved ==>
Tested article in site => Layout setting is still 'Blog'.
So I havn't changed any Global Articles settings.

**Comment by amelcher** [comment] 2018-06-04 23:43
@Klipper I didn't change the global article settings, but that is what it keeps defaulting to when I save it in front end.  Could you send me the Blog override to see if that is the difference in our results? I can send you mine as well.

**Comment by amelcher** [comment] 2018-06-05 01:21
@Klipper @brianteeman  @franz-wohlkoenig 
Weirdest thing. It is now working just as it should. I am able to create an article in front end and backend and change the layout, then open article in frontend and save it, and the layout doesn't revert back to default.
The only thing I did differently this time around is in the template override edit.php page under content/forms/  I commented out 
//JHtml::_('formbehavior.chosen', '#jform_catid', null, array('disable_search_threshold' => 0));
//JHtml::_('formbehavior.chosen', 'select');

and now it seems to work. I will test some more but so far, I have created a new article from front end and was able to change the layouts of both that article as well as one I created from backend and then save both in front end successfully.

I'm think this may have been creating some conflicts?

Adam

**Comment by ghost** [comment] 2018-06-05 03:43
@amelcher glad you solved Issue - closed as stated above. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20513">issues.joomla.org/tracker/joomla-cms/20513</a>.</sub>

**Closed as completed by ghost** 2018-06-05 03:43 UTC
Labels: No Code Attached Yet
