### ISSUE TITLE
[4.2] Posts - Hide title (and all options)- is changed unintentionally when saving in the frontend

### ISSUE THREAD

**Issue by sonvnn** [joomla/joomla-cms#38508] opened 2022-08-18 03:46 UTC
No matter what was preset for an individual post in the backend, it will be overwritten by the post options set in the global settings in the backend (posts / options) when the post is edited and saved in the frontend.

Thus, the user has to go back to the backend and adjust the option of the edited post again and again.

If I have set options for a post in the backend and open and save the editor in the frontend, all individual options set in the backend are overwritten by the global options.

### Steps to reproduce the issue
For testing

1. Posts Options "Show title set to YES by default"
2. Open or create a post in the backend and set the title display to "do not show" for this individual post, deviating from the standard.
3. Go to article detail and title disappear.
4. Open this post in the frontend, edit it and save it.
5. Now the title is automatically set to "show" again, which I don't think was the case before.
6. Go to article detail and title "show" again.

So it only happens when editing in the frontend.

### System information (as much as possible)

- Joomla 4.1, Joomla 4.2
- PHP 8.0 and PHP 8.1

**Comment by brianteeman** [comment] 2022-08-21 06:19
I have followed your instructions and I am unable to replicate this.

**Comment by chmst** [comment] 2022-08-21 08:22
I cannot replicate with cassiopeia. @sonvnn Are you using a template override?

**Comment by ReLater** [comment] 2022-08-21 12:32
I can't reproduce it with 4.2.1-rc3-dev. Only CacheCleaner, AkeebaBU installed.

Logged in as SuperUser in BE and FE. Shared Sessions: NO. Not tested with other groups.

**Comment by sonvnn** [comment] 2022-08-22 02:39
I re-checked and found the problem came from one of our plugin. Sorry for the inconvenience. I close this issue as resolved and continue to check the issue on our side.

**Comment by sonvnn** [comment] 2022-08-23 04:19
Hi everyone,
I found issue from Joomla Form:loadFile() function. I tested with Astroid Framework and Helix Framework got same issue, too.

When plugins call `$form->loadFile` from `onContentPrepareForm trigger`, the params will be get default value from xml.
![Screen Shot 2022-08-23 at 10 18 41](https://user-images.githubusercontent.com/3204103/186062217-abce64fa-a105-4ec8-b5e0-0234b9545753.png)

### Testing Instructions

1. Download [Astroid Framework ](https://github.com/templaza/astroid-framework/releases/download/v2.5.18/astroid-framework-2.5.18.zip) or [Helix Framework](https://www.joomshaper.com/downloads/template/helixultimate)
2. Install to your Joomla site.
3. Posts Options "Show title set to YES by default"
4. Open or create a post in the backend and set the title display to "do not show" for this individual post, deviating from the standard.
5. Go to article detail and title disappear.
6. Open this post in the frontend, edit it and save it.
7. Now the title is automatically set to "show" again, which I don't think was the case before.
8. Go to article detail and title "show" again.

Please check my testing video to understand more. https://www.screencast.com/t/TRMAZAxAq

I notice that with Pure Joomla. It's no problem. But if extensions use `$form->loadFile()` function in `onContentPrepareForm` trigger. It will happen.

I fixed this issue in Astroid with onContentBeforeSave trigger. I re-open this issue again, because I think it will affect to other extensions like Helix framework, etc. But if you feel it is not a Joomla bug. Feel free to close it.

Thank you & Best Regards,
Sonny

**Comment by brianteeman** [comment] 2023-08-30 09:04
I am closing this as the bug is in the third part code and not the core.

**Closed as completed by brianteeman** 2023-08-30 09:04 UTC
Labels: No Code Attached Yet, bug
