### ISSUE TITLE
Backend adminmenu not updated

### ISSUE THREAD

**Issue by AboutTimeIT** [joomla/joomla-cms#15560] opened 2017-04-26 00:58 UTC
### Steps to reproduce the issue
Joomla 3.7.0 (updated from 3.6.5) in Firefox 53.0
Created an adminmenu with access to Articles and Cleaning cache.
Set the module to the newly created adminmenu (Check menu is ON) --> Save & Close
The menu is NOT reset to the new adminmenu
Then suddenly when clicking on Menu - Manage the new adminmenu appears.
Extentions - Modules - Adminmenu - System preset - Save & Close --> The menu is not reset to default.

### Expected result
The menu is not reset to default.

### Actual result
The menu is NOT reset to the new adminmenu or reset to the default adminmenu

### System information (as much as possible)
Joomla 3.7.0 (updated from 3.6.5) in Firefox 53.0

**Comment by infograf768** [comment] 2017-04-26 07:10
Normally, there should be a menu module for each adminmenu (default preset and any one newly created). 

I guess we did not consider this way of dealing with the new feature.
@izharaazmi 
Any idea to prevent this error?

**Comment by izharaazmi** [comment] 2017-04-26 07:57
I tested on a fresh install, could not reproduce. Will test on upgrade from
j365 soon.

**Comment by Gavakshi** [comment] 2017-04-26 12:21
Could not reproduce the issue on upgrade too

**Comment by PhilETaylor** [comment] 2017-04-26 12:48
Is your Admin Cache on? Is this related to https://github.com/joomla/joomla-cms/issues/15588

**Comment by AboutTimeIT** [comment] 2017-04-26 15:41
Cleared the cache --> no improvement
No relation to #15588 (as far as i can see)
Send a e-mail to @izharaazmi <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15560">issues.joomla.org/tracker/joomla-cms/15560</a>.</sub>

**Comment by AboutTimeIT** [comment] 2017-04-26 16:32
If the  System Cache is set to: OFF --> the change in the admin menu is changed directly<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15560">issues.joomla.org/tracker/joomla-cms/15560</a>.</sub>

**Comment by mbabker** [comment] 2017-04-26 16:35
So changes in `com_menus` need to ensure `mod_menu` cache gets cleared for the backend module too.  Right now it clears the frontend one, so it should be a simple PR adding it for the backend cache as well.

**Comment by mbabker** [comment] 2017-04-27 01:02
#15606 should address the cache clearing issue.

**Comment by franz-wohlkoenig** [comment] 2017-04-27 06:19
closed as having PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15560">issues.joomla.org/tracker/joomla-cms/15560</a>.</sub>

**Closed by franz-wohlkoenig** 2017-04-27 06:19 UTC
Labels: No Code Attached Yet
