### ISSUE TITLE
Schema Checker doesn't check for modified columns in PostgreSQL

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#29279] opened 2020-05-30 17:53 UTC
### Steps to reproduce the issue
In mysql we check for columns changed with the `CHANGE` syntax. we don't have an equivalent in postgres which leads to skipped checks.

### Expected result
PostgreSQL db schema checker validates columns where the names are changed

### Actual result
It doesn't

### System information (as much as possible)
Postgres

### Additional comments
None

**Comment by richard67** [comment] 2020-05-30 18:05
In addition, it doesn't check on both kinds of databases for
- DROP TABLE - that's why for the finder schema updates currently no errors are shown ;-)
- ALTER TABLE .. RENAME ... (renaming tables)

I plan to work on that.

**Comment by richard67** [comment] 2020-05-31 10:46
Seems I‘ve made a mistake when checking this for @wilsonge : The schema checker for PostgreSQL DOES support column type changes, only the syntax is different to the (erroneous and meanwhile corrected) syntax in one of the recently corrected update SQL scripts.

But the other issues I‘ve mentioned in my previous comment are still valid.

@wilsonge Just change title and description of this one? Or close it because the other issues are expected behavior?

**Comment by wilsonge** [comment] 2020-06-01 07:51
So the change column does work already (after the fixes we did on Saturday). It’s just deleting and renaming tables now?

**Comment by richard67** [comment] 2020-06-01 08:35
@wilsonge Correct. But if we add support fopr "DROP TABLE" (tables are dropped, not deleted) we might have the same problem with Hannes' update SQL as we had whe we developed the utf8mb4 conversion and tried to drop and then add back an index with the same name, like Hannes does with a table in the update sql for the finder. It would need either make the schema checker more clever for this, or change the sql so the table is modified in the right way instead of drop and create again.

I suggest we close this issue.

**Comment by richard67** [comment] 2020-06-01 09:41
@wilsonge For table rename I'm already working on a solution.

**Closed as completed** 2020-06-01 10:09 UTC
Labels: No Code Attached Yet
