### ISSUE TITLE
[com_fields] type Text area - parameter "Columns" not working

### ISSUE THREAD

**Issue by AlexRed** [joomla/joomla-cms#15802] opened 2017-05-03 15:37 UTC
### Steps to reproduce the issue
For user custom fields create new custom field type Text area and insert a number for the parameter "Columns".
Edit your superuser profile in frontend, the "Columns" number for Text area seems not working.

### System information (as much as possible)
Joomla 3.7.1dev

### Additional comments

![field-text-area](https://cloud.githubusercontent.com/assets/1362388/25668554/ebb24ed6-301e-11e7-8342-f515fcb3b137.png)

**Comment by franz-wohlkoenig** [comment] 2017-05-03 15:59
Issue confirmed. Width of Textarea stay independet of given Columns.

**Comment by chmst** [comment] 2017-05-03 17:28
@AlexRed do you have an example where the columns attribute works as expected, with columns? I'd really like to know how to make this work for an own field. I've never found a textarea where the value for columns is respected - not in JFormField Textarea or in a plain html. I think, the attribute could (should) simply be removed. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15802">issues.joomla.org/tracker/joomla-cms/15802</a>.</sub>

**Comment by Bakual** [comment] 2017-05-03 18:10
That just depends on the template. Most probably set a width for input elements using CSS which overrules columns settings (as well as the "size" for a text input).
Not much we can do here, it's how HTML and CSS interact.
In case of Isis it is this rule
````
input, textarea, .uneditable-input {
    width: 206px;
}
````
If you disable that one, the column parameter works as expected.

**Comment by chmst** [comment] 2017-05-03 18:16
Yes, this is what I want to say. The JFormField or custom field have no influence on the template / CSS (except via js, enforcing a change of the width, maybe).  So the issue is no issue ;)

**Comment by laoneo** [comment] 2017-05-05 06:49
It is indeed an issue. IMO, the template should be fixed then as the core should come all the options supported.

**Comment by Bakual** [comment] 2017-05-05 10:00
Not really. Those attributes just are legacy HTML ones. "Modern" templates specify the width of those elements using CSS instead of HTML attributes. You can still specify the attributes for templates which don't have CSS rules for that.
For those templates using CSS rules for the width, they usually also have classes like "input-small" which help to adjust the width of the elements.

**Comment by brianteeman** [comment] 2017-05-19 17:40
sorry but I am closing this as expected behaviour as the css in the admin template (default bootstrap) overrides the value of the columns.

**Closed by brianteeman** 2017-05-19 17:40 UTC
Labels: No Code Attached Yet
