### ISSUE TITLE
New articles are created with last possible "ordering"

### ISSUE THREAD

**Issue by bartnikj** [joomla/joomla-cms#11103] opened 2016-07-13 11:45 UTC
#### Steps to reproduce the issue

In Joomla 3.6.0:
1. Go to backend
2. Create article
3. Save and close
4. List all articles using ordering

#### Expected result

New article is listed as first one, just like before J3.6

#### Actual result

New article is listed as last one, which is pretty bad if you already have 1000+ articles and need to drag and drop it from bottom to the top.

#### System information (as much as possible)

Joomla 3.6.0

**Comment by brianteeman** [comment] 2016-07-13 11:57
Seems to be the same as in 3.5.1

**Comment by bartnikj** [comment] 2016-07-13 12:02
Same as "new article is last" or "new article is first". It happened to me after upgrading from 3.5.1 to 3.6.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11103">issues.joomla.org/joomla-cms/11103</a>.</sub>

**Comment by bartnikj** [comment] 2016-07-13 12:23
Hmmm... that's weird. I updated 5 of my J35 to J36 and two got this problem. The other 3 are just fine... The JTable->reorder code is identical so it must be something else.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11103">issues.joomla.org/joomla-cms/11103</a>.</sub>

**Comment by csthomas** [comment] 2016-07-13 16:47
What can I see in J3.6 the ordering is reversed, please check changes in #8576.
@alikon, @rdeutz Could you check it?

The performance is better because reordering is removed and any new article is added at the end.

**In short: Ordering was reversed for better performance.**

But it has created problem with  B/C for people that based on article ordering column.

I suggest to notice users that article ordering was reversed. May be advice to wait for 3.6.1.

IMHO J3.6.1 should add some sql update to reverse ordering of existed articles (on installation) before users will add new articles. And reverse ordering direction from ASC to DESC and from DESC to ASC in modules/category view, etc.

**Comment by brianteeman** [comment] 2016-07-13 16:51
>

> IMHO J3.6.1 should add some sql update to reverse ordering of existed
articles (on installation) before users will add new articles. And reverse
ordering direction from ASC to DESC and from DESC to ASC in
modules/category view, etc.

You can't do that. It will completely break any existing site that uses
ordering

**Comment by csthomas** [comment] 2016-07-13 17:05
Hmm, Joomla 3.6 broke ordering, but done good thing for performance 
and I like that change.

I see two ways:
1) Back to ordering from 3.5.1 and still have problem with performance - reverse #8576.
People who has 3.6 may be not happy. It will has mess with current new articles.

2) Go forward (and maybe add some sql updates to fix old ordering)
and explain users that new article will get last number (in column ordering) and older articlea have lower numbers. And they should change ordering direction for modules, etc.

**Comment by alikon** [comment] 2016-07-13 17:05
i'm not an expert of B/C , sem 2.0 etc ,  so not so sure if this is an issue that break some rules when upgrading to a new minor version .... for me is an improvement.

**Comment by csthomas** [comment] 2016-07-13 17:15
@alikon 
Your patch change way of set ordering for a new article:
Before:
 - new article was set as ordering=0 and all existed articles was reordering (old moved by +1 in the same category), so at the end the new article had column ordering=1

After:
 - new article is set as the last one in the same category and all existed articles are **NOT** reordering - this is performance boost

I may wrong, please check.

**Comment by alikon** [comment] 2016-07-13 17:20
yes correct, 
but again i don't see the problem

**Comment by csthomas** [comment] 2016-07-13 17:37
The problem is that the users may use some modules/articles view with sql ```order by "ordering ASC"``` to get the newest articles at the top of result - something like "Last published".
In Joomla 3.6 that does not work because the newest articles go down in result, after older.

**Comment by alikon** [comment] 2016-07-13 17:42
i think is wrong  to use the "field ordering"  to get content sorted by a date

**Comment by csthomas** [comment] 2016-07-13 18:12
May be but Joomla allow to sort by ordering field and now it is work in reverse order.

If ordering field is not important for Joomla 3.6 
then I do not have to discuss about it because personally I do not use it.

Other example:
Line 1357:
https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/table/table.php

Users in J3.5 could set some articles to be always on the top of newest articles. (sort by ordering ASC)
Joomla 3.5 then allow to display extra article(-s) (means with set ordering=-1) to be always on the top of result.

IMHO: Some information about change order direction in ordering field should be added.

**Comment by csthomas** [comment] 2016-07-13 18:24
I only want to mention that featured table also have ordering field which direction was reversed.

**Comment by joo7** [comment] 2016-07-14 06:02
"add new article at top / at the end" setting in options would be great.
(I like the changes, performance + at the end)

**Comment by sanderdw** [comment] 2016-07-14 07:22
Yes i have the same 'problem', now an extra step is needed to place the article at the top. Best of both worlds would be indeed the solution joo7 describes.

**Comment by csthomas** [comment] 2016-07-14 10:58
I don't think Joomla 3.6 want to back to the old order. 
IMHO additional option to choose direction will complicate too much.

A solution would be to accept a new direction, but...
there should be a button or some function to change direction of all existed articles / featured
to fix direction for old articles.

__For a new installation of Joomla 3.6 category view/modules with 'article order' or 'featured articles order' display incorrectly.__

Means older articles are at the top, newer at the bottom.

Take a look at:
https://github.com/joomla/joomla-cms/blob/staging/components/com_content/helpers/query.php#L92-L114

IMHO It should be changed from:
```$orderby = 'a.ordering';```
to:
```$orderby = 'a.ordering DESC';```

and:
```$orderby = 'a.featured DESC, fp.ordering, ' . $queryDate . ' DESC ';```
to:
```$orderby = 'a.featured DESC, fp.ordering DESC, ' . $queryDate . ' DESC ';```

**Comment by Quibi** [comment] 2016-07-14 19:01
In my opinion, the behaviour of featured articles in J36 (last featured goes to last order position not to first as usual) is against usability and cannot be considered a better performance from user's point of view.

It is strange and misleading that the last article that you mark as featured becomes the last of the CMS.

In my case, as I use featured articles in my front page, my workflow has become very inefficient.

In J35 and earlier, when I wanted to highlight an article, I just featured (clicked) it in the articles list and it becomes the first of featured articles.

Now, after featured it, I must go to "Featured" and reorder articles. It is a waste of time and prone to errors.

I suggest that the old behaviour should be restored for the sake of users.

**Comment by csthomas** [comment] 2016-07-14 20:28
I have created an example PR what should be (at least) changed. 
It is not completed but example. 

IMHO joomla should remove/hide sort by ordering field. 
Can we replace it with publish_up field?

**Comment by brianteeman** [comment] 2016-07-14 20:32
Being able to control the order that articles are displayed in is a
fundamental function

**Comment by bartnikj** [comment] 2016-07-14 20:49
In the meantime... is there any simple way to move article (in terms of order) from bottom to top? Right now I have to display all articles (1000+) and drag and drop it all the way up... which takes about 2 minutes. I guess (as this is JavaScript and jQuery) I could spend some hours to look for (or make) a single line script that would do just that in my browser's debug mode. Thank god it's not J15 where you would click those small arrows that reloads the page every time you move item by one row...

**Comment by brianteeman** [comment] 2016-07-14 20:52
Are all the articles in a single category? If not then filter by the
category

On 14 July 2016 at 21:49, bartnikj <notifications@github.com> wrote:

> In the meantime... is there any simple way to move article (in terms of
> order) from bottom to top? Right now I have to display all articles (1000+)
> and drag and drop it all the way up... which takes about 2 minutes. I guess
> (as this is JavaScript and jQuery) I could spend some hours to look for (or
> make) a single line script that would do just that in my browser's debug
> mode. Thank god it's not J15 where you would click those small arrows that
> reloads the page every time you move item by one row...
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/11103#issuecomment-232788085>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8UEJc2OfsdZT6lYZmz1yBYDjkFxYks5qVqDlgaJpZM4JLVTd>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by bartnikj** [comment] 2016-07-14 20:56
Yup, already tried that. It narrowed my list from 1700 to 1600 articles :P

**Comment by bartnikj** [comment] 2016-07-14 21:13
Idea: in article list there's a dropdown icon in every row. It could contain extra icon with "move to top" functionality (available only when articles are displayed ordered).

Ideally 3.6 update should rebuild ordering in articles so the change would be transparent to users (but on the other hand it would break some addons if they use ordering column).

**Comment by csthomas** [comment] 2016-07-14 21:20
This is my thought only.

__Lazy way and not tested by me__
Use files from backup and unpack joomla 3.5.1 files to other folder, test it and replace it if everything works. There is no too much changes in database so should works.

__Full solution and not tested__
- Stop adding a new articles for a while. 
- Fix any ordering, means the newest with the lower ordering value.

- Change ordering by sql or own script, 
means reverse ordering for each category and for frontpage table.

- Replace at least one file components/com_content/helpers/query.php from  PR #11134.
- In modules like mod_articles_category change sort direction from ascending to descending.

**Comment by bartnikj** [comment] 2016-07-14 22:11
Wouldn't just "reversing" the order in SQL be enough? Like that:
1. grab maximum ordering value ORDERING_MAX
2. assign new ordering value of ORDERING_MAX-ordering

**Comment by csthomas** [comment] 2016-07-14 22:23
You can reserve the order of article per cat_id field.
In category "One" you have articles with ordering field with value 1,2,3,...
In category "Two" you also have articles with ordering field with values 1,2,3,...

**Comment by ggppdk** [comment] 2016-07-14 22:26
@csthomas 

Reversing the ordering is a B/C break for existing web-sites that already have an ordering set

Proper way to have done this:
- when table re-ordering is triggered it changes **positives orders** to start from **10,000 and NOT from 0**
- then new article ordering will then be min(OF positive orderings) - 1, without re-ordering needed to be done
- when min(OF positive orderings)-1 reaches zero, a table re-ordering is forced to run

**Comment by csthomas** [comment] 2016-07-14 22:50
Take a look at https://github.com/joomla/joomla-cms/pull/8563#issuecomment-225231023

I have similar idea but instead of 10000 I use 2147483647 (MAX_INT_IN_MYSQL)
And I do not use reordering when  MIN(OF positive orderings)-1 reaches zero.

10,000 is too small number.

**Comment by ggppdk** [comment] 2016-07-14 22:52
@csthomas 
10,000 is just an example

and you can not use the max allowed you probably would want to use MAX_ALLOWED / 2  ... think of why ...

**Comment by ggppdk** [comment] 2016-07-14 22:55
I have just looked at the table re-order code

!!! **why does it do 1 update per row** ?

We can update 1000 or 20,000 records with a single query (depending on SQL server configuration),  with a great performance effect (ok 10 queries to 1 queries you would not see much difference but 1000 to 1 you will see big !!)

@alikon 
(correct me here but the following works in ALL db server ??, because it is standard SQL ??):

```
UPDATE  __content
    SET ordering = CASE id
        WHEN 45 THEN '100000'
        WHEN 34 THEN '100001'
        WHEN 53 THEN '100002'
        WHEN 17 THEN '100002'
    END
WHERE id IN (45,34,53,17)
```

1. so the PHP loop will collect / calculate the new orderings, 
2. then issue the updates in 1000 chunks 


In fact with default MAX_PACKET_SIZE of 1MByte in MySql you could do more than 20,000 rows in a single query, so 1,000 is safe

**Comment by csthomas** [comment] 2016-07-14 23:01
I know that signed limits is half.

Currently for Joomla 3.5.1 and mysql I use:
https://github.com/joomla/joomla-cms/pull/8563#issuecomment-224108944

To support all database types there will be more work.

**Comment by ggppdk** [comment] 2016-07-14 23:08
> To support all database types there will be more work

@csthomas 

- please clarify, so you say that 
SET - CASE  - WHEN - THEN - END

(WHERE ... IN ...) is for performance ...

is not supported by all DBs ??
my mistake , i thought it was , which DB type does not support it ?

**Comment by csthomas** [comment] 2016-07-14 23:18
This is  misunderstanding. I said about my comment from #8563.

**Comment by csthomas** [comment] 2016-07-14 23:45
What do you think of gaps in numbering:
- ex. article with ordering=10002 may be missing and we have articles with ordering field values 10001, 10003, 10004, 10005,...

That should make PR simpler to do because Joomla does not need to reorder table on create article / delete artcile.

**Comment by csthomas** [comment] 2016-07-15 02:17
If someone use patch from PR #11134 then I suggest to revert it and use new one from PR #11139.
@ggppdk What do you think of PR #11139?

**Comment by bartnikj** [comment] 2016-07-15 08:02
Ok, as J36 broke existing ordering (making moving from 3.5 more of a migration than upgrade) and it's mostly because of performance issue why just not shift article ordering while doing reordering and keep order direction from pre-J36 era. Example would be:
1. We had articles with ordering 0,1,2,3,4 
2. Shift them by around 2147483647/2 minus (ARTICLE_MIN_ORDERING+ARTICLE_MAX_ORDERING)/2
You'd have to do it once during an upgrade (or after first reorder) and it wouldn't break existing installations.
3. Now you should have 1073741820,1073741821,1073741822,1073741823,107374184.

Or... if it's signed INT... we could go negative numbers and no shifting is needed. Performance and backward compatibility at the same time :)

**Comment by ggppdk** [comment] 2016-07-15 08:13
> Or... if it's signed INT... we could go negative numbers and no shifting is needed

you should not use negative numbers
as these can be utilized for "sticky" behaviour = meaning they are not subject to reordering

**Comment by ggppdk** [comment] 2016-07-15 08:16
Anyway the PR of @csthomas
looks good

**Comment by gwsdesk** [comment] 2016-07-18 15:22
Performance upgrades in code that brings people to despair as we can see on the Joomla forums is pure wrong. See for instance http://forum.joomla.org/viewtopic.php?f=9&p=3414231#p3414231 or http://forum.joomla.org/viewtopic.php?f=710&t=929169 . These posts show exactly why this change in Joomla 3.6 is wrong. Stating that "i think is wrong to use the "field ordering" to get content sorted by a date" is just one opinion. Look at this 'functionality' over the past years alone on the forums. I request this to be rapidly reversed?

**Comment by ggppdk** [comment] 2016-07-18 15:37
@gwsdesk 

yes it is a B/C break and #11139 should fix it,  can you test it ?
i will do too , i hope "today"

**Comment by gwsdesk** [comment] 2016-07-18 15:49
I am not sure if that makes sense based on the comments posted so far

**Comment by csthomas** [comment] 2016-07-18 16:12
We have to take a decision with number should get a new article or fronpage (featured) or module or banner or other table row with ordering column.

Options:
1) ```1```as in joomla 3.5.1
or ```min(ordering) - 1```. This is a little problem with display big numbers to users (example PR #11139)
Currently my PR use ordering with big numbers only for content and content_frontpage.
This is B/C for 3.5.1 and lower but not for 3.6.

2) ```max(ordering) + 1``` as in joomla 3.6 (example/incomplete patch at PR #11134)
- This is the least complicated way for coders.
- Break B/C. 
- Other extension developers would complain about it.

But it is the simplest way for future maintains. 
Only we have to change the thinking of ordering field.

For 3.5.1 and lower:
- "Article Order: Ordering" means ```ordering ASC``` (from the last added to the oldest)

it may be worth to change it and break B/C and all user (who use ordering column) has to change Article Order from ```Ordering``` to ```Reversed Ordering```. 

Then we will have (reversed situation):

"Article Order: Reversed Ordering" (sql: ordering DESC) - from the last to the oldest.
"Article Order: Ordering" (sql: ordering ASC) - from the oldest to the last.

**Comment by gwsdesk** [comment] 2016-07-18 16:20
IMHO under no circumstances can we ask people to manually re-arranged thousands of articles. I think it is wrong to "quickly" patch this issue with a solution that is not covering all options and is not well discussed nor using proper coding as I read the comments correct #11139. Once again I propose to PLT to revert this to J3.5.1 methods and after that we work on a proper solution that covers all ordering (featured/articles/categories/modules/ect

**Comment by xupacabra** [comment] 2016-07-28 02:40
Hi guys.
I use Joomla since version 1.0 and have had installed more than 50 sites across. Always helping people.
It started with games and then migrated to more serious things like companies that needed help in spreading sites. Even the Brazilian surf museum site, won one. The greatest ever tevem 40 million visitors and I am very grateful for all that joomla team made over that time.
It is very good to help everyone. But this latest version is aging me.

### ### Off Topic
Migration was hard. I had to buy a component to help me, but I ended up losing the comments Jcomment ... I see on the internet that some people have managed, but I left it forward.
The administration area was very slow when saved articles into categories that have many. I have a 14,000 items and consumes a minute to write an article.
### End of Off Topic ###

As regards Featured Artices, sorting by negative id for an article to stay fixed on the top, it was a clean and simple solution.
After the migration, my articles are fixed around the site and get them to the top hand is terrible.
Making changes for QUERY works, but we do not have the option existed to reorder numbers. It was magical.
Well, once again obrigaod for everything and we will wait if we can evolve this point.
In this image: The best solution off all times:
http://www.infosolutionsgoa.com/cms/img4/ordering-menu-items.gif

**Comment by ggppdk** [comment] 2016-07-28 07:10
Your off topic comment is not off topic ,
it was why the B/C break in the ordering was created , which is also a usability issue

**Comment by csthomas** [comment] 2016-07-28 08:18
> The administration area was very slow when saved articles into categories that have many. I have a 14,000 items and consumes a minute to write an article.

To speed up adding new articles
You can try this one, but before do it please create a COPY of `#__assets` table at least.
http://www.itoctopus.com/creating-new-articles-on-your-joomla-website-is-taking-a-long-time-clean-your-assets-table

from that forum http://forum.joomla.org/viewtopic.php?t=876649

**Comment by bartnikj** [comment] 2016-07-28 08:58
As the thread still's alive: **what are the options right now**? 3.6 should not be an upgrade but migration. B/C could be kept just by shifting ordering instead of reversing it. Same/similar performance.
Options:
1. Keep it as it is - adding new articles is faster, but the time saved is wasted on manually reordering the newest article to be the first one.
2. Manual fix: reverse your ordering in SQL by using `UPDATE j3_content j SET j.ordering = 10000 - j.ordering` to fix the B/C in com_content... but the option to sort articles by ordering DESC is not present in Joomla (that should really be fixed with J36 ordering change)... The downside is - if anything else rely on this ordering the way it was it'll break.
3. Use @csthomas fix that is adding before-J36-like ordering option and deal with performance degradation over time.
4. Same as 3. but with `UPDATE j3_content j SET j.ordering = 100000 + j.ordering`. And the part that is probably not ready yet - new articles should get ordering of MIN(ordering)-1 instead of 0.

I'm definitely a fan of 4., so **the shift method**. And as a quick patch there should be extra "reversed ordering" option in article ordering (as I can live with 2. if I only had an option to order things on the frontend J36-style)

**Comment by csthomas** [comment] 2016-07-28 09:44
I think that my PR is not understand correctly.

I'm start talking about ordering from J3.5, means
articles has ordering like:
1,2,3,4,5,6,7,8,9
* after add a new one we get:
0,12,3,4,5,6,7,8,9 then problematic reorder do 1,2,3,4,5,6,7,8,9,10

* Then I applied my PR:
* Before adding any new articles I have:
1,2,3,4,5,6,7,8,9,10
* after add a new article:
* joomla find that min(ordering) -1 is less that 1 
* then trigger reorder method (only once when we move from <= J3.6.0 to my PR)
* new ordering after reorder will be (LAST means 2147483647):
* LAST-10, LAST-9, LAST-8, LAST-7, LAST-6, LAST-5, LAST-4, LAST-3, LAST-2, LAST-1 
* above sort is not changed, this is only +offset:
* new_ordering = LAST - COUNT(articles) - 1 **+ old_ordering**
* means old (1) = LAST-10, (2) = LAST-9, ...
* after that joomla find again min(ordering) -1 and get LAST-11, then use it and we have:
* LAST-11, LAST-10, LAST-9, LAST-8, LAST-7, LAST-6, LAST-5, LAST-4, LAST-3, LAST-2, LAST-1
* next time when we want to add a new article we do not need to reorder because now ordering
has large numbers.

**If that explanation is still problematic.** 

Then open text editor write a few words:
```
This is old behavior.
This is new behavior.
```

Then adjust second line to the right.
```
This is old behavior.                                                               |MAX
                                                               This is new behavior.|MAX
```

Before we have: **align to the left side** (1,2,3,4,5)
After we will have: **align to the right side** (LAST-5, LAST-4, LAST-3, LAST-2, LAST-1) 

Then add a new word (NEW):
```
NEW This is old behavior.                                                              |MAX
                                                              NEW This is new behavior.|MAX
```

At the first line we have to shift old words to the right.
Now you see that no shift was required for second line.

**Comment by xupacabra** [comment] 2016-07-29 00:31
One thanks to all !
well,
 now, when I mark one article with FEATURES, it receive one large number.
And my only option is change the order by PHPMyadmin

The article 14409 was write today, Featured checked and receive ORDERING = 13922 in xxx_content_frontpage

![image](https://cloud.githubusercontent.com/assets/20694073/17233866/05567132-550a-11e6-85de-38f47d3fae72.png)

**Comment by csthomas** [comment] 2016-07-29 05:26
This is known bug in 3.6.0. 

If you want to help you can test PR #11139 on some dev joomla.
Instead 1,2,3 numbers you will get bignumber-3, bignumber-2, bignumber-1.

For temporary you can also revert #8576 also on production.
This slow down adding a new articles but new article will get number 1 instead 14409.

**Comment by spopic** [comment] 2016-08-26 10:36
MENUS - MAIN MENU - (NAME OF THE MENU FOR FEATURED ARTICLES) - LAYOUT - ARTICLE ORDER = MOST RECENT FIRST!

It works now on Joomla 3.6.2.!

In Global configuration for articles it was configured the same (correctly), but for some reasons and after the update to 3.6.0. and 3.6.2. you have to configure the menu item as well for the existing and new Featured Articles!

Best regards!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11103">issues.joomla.org/joomla-cms/11103</a>.</sub>

**Comment by bartnikj** [comment] 2016-08-26 10:48
I think "most recent first" is not referring to the way articles are saved but only to the way they are displayed regardless of ordering. There is still no "ordering - reversed" option that would make sense as new articles get higher order when created. And I would assume that's the option to go as most sites are displaying news/articles and newer should go on top of the page with minor tweaks.

**Comment by brianteeman** [comment] 2016-08-26 10:52
I am closing this as the reported issue was the result of a PR that has now been reverted by #11581 and will be in the next release

**Closed by brianteeman** 2016-08-26 10:52 UTC
Labels: No Code Attached Yet
