### ISSUE TITLE
[com_fields] Undefined property: stdClass::$assigned_cat_ids, com_fields

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/joomla-cms#13565] opened 2017-01-11 21:00 UTC
### Steps to reproduce the issue

1. Define a field in Users
2. Navigate to create or edit a user 

### Expected result

No notice

### Actual result

Notice: Undefined property: stdClass::$assigned_cat_ids, com_fields/helpers/fields.php on line 453

**Comment by Bakual** [comment] 2017-01-11 22:10
@laoneo That's because com_users doesn't use categories, right? The parameter is thus missing in the field definition as well.
I think I can make a PR tomorrow to deal with that.

**Comment by laoneo** [comment] 2017-01-12 05:49
This issue reveals a problem when a component doesn't use categories for grouping. Correctly implemented, we need to offer for the component a way to define the hardcoded category_id more dynamically 
- https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_fields/models/field.php#L152
- https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_fields/helpers/fields.php#L118.

I guess this would mean that we can't use the category form field here https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_fields/models/forms/field.xml#L35. Instead of we need to make our own generic one. But I don't know if this is doable in a stable way?

**Comment by Bakual** [comment] 2017-01-12 08:29
The first one isn't an issue as $tupel->category_id refers to the #__fields_categories table. That will always be that column name :smile: 

The other one may be an issue if an extension doesn't use catid as property. However it may also be possible for them to just copy the property to catid before it goes through fields. Otherwise we would need a way to alias the category property of an item. But it isn't the cause of the issue here.

The category field however is fine. That should work with all extensions using com_categories.

**Comment by Bakual** [comment] 2017-01-12 08:50
See PR https://github.com/joomla/joomla-cms/pull/13570

Closing this.

**Closed by Bakual** 2017-01-12 08:50 UTC
Labels: No Code Attached Yet

**Comment by laoneo** [comment] 2017-01-12 09:05
> The category field however is fine. That should work with all extensions using com_categories.

Like it is now, it ONLY works for categories. It is not possible to assign fields to user groups or other component specific grouping items.

**Comment by Bakual** [comment] 2017-01-12 09:09
Ah sure, that isn't possible. But it's also not something which we tried to support so far.

**Comment by laoneo** [comment] 2017-01-12 09:17
That's what I wanted to say :speak_no_evil:
