### ISSUE TITLE
An error has occurred. 0 Class "CoalawebtrafficHelperTools" not found

### ISSUE THREAD

**Issue by killerbossoriginal** [joomla/joomla-cms#36626] opened 2022-01-10 01:42 UTC
### Steps to reproduce the issue
install a joomla v3 plugin in version 

### Actual result
Error

### Additional comments
I found the cause of the error, I removed all folders by doing ubuntu `rm -r *plugin name*`, `rm -r **/*pluginname*` `rm -r **/**/*pluginname` `rn -r **/**/**/*pluginname*` and I fixed the error it gave me before, but now from this error, how can I solve it?

**Comment by killerbossoriginal** [comment] 2022-01-10 01:44
Else, is there a method to bypass the admin page error?
![Screenshot_20220110-024349](https://user-images.githubusercontent.com/73131550/148709974-eea1cd75-90a7-4995-a362-be4736057022.png)

**Comment by richard67** [comment] 2022-01-10 06:47
> Install a joomla v3 plugin in version

@killerbossoriginal in which version? Could you complete your sentence?

**Comment by killerbossoriginal** [comment] 2022-01-10 07:44
> > Install a joomla v3 plugin in version
> 
> @killerbossoriginal in which version? Could you complete your sentence?

I don't remember the version, but I didn't have any updates to make. So I think the latest
@richard67

**Comment by richard67** [comment] 2022-01-10 07:47
@killerbossoriginal And which version is that? The version of the plugin? Or Joomla? Did you try to install a plugin which is made for Joomla 3 on a Joomla 4?

**Comment by killerbossoriginal** [comment] 2022-01-10 07:56
> @killerbossoriginal And which version is that? The version of the plugin? Or Joomla? Did you try to install a plugin which is made for Joomla 3 on a Joomla 4?

what I said was the Joomla version, but the plugin was created for Joomla3 and I tried to put it in the latest version of Joomla 4.
[This is the plugin, I put it in the latest version](https://extensions.joomla.org/extension/coalaweb-traffic/)

**Comment by richard67** [comment] 2022-01-10 07:58
> the plugin was created for Joomla3 and I tried to put it in the latest version of Joomla 4.

@killerbossoriginal Well, then it is definitely not a bug but a support request. Please ask in the support forum https://forum.joomla.org/ .

Closing as not a core issue.

**Closed as completed by richard67** 2022-01-10 07:58 UTC
Labels: No Code Attached Yet

**Comment by joomdonation** [comment] 2022-01-10 08:04
@killerbossoriginal If you look at the JED entry https://extensions.joomla.org/extension/coalaweb-traffic/ , you will see that the plugin is only compatible with Joomla 3 only, not Joomla 4 and that's the reason causing the error. You should contact the developer of the plugin and ask him to see if he has a version which compatible with Joomla 4 (or at least to see if he has plan to make the plugin compatible with Joomla 4). This error has nothing to do with Joomla core.

**Comment by zoiabr** [comment] 2022-09-03 06:55
Hi i am not sure if this is the place to ask for hepl but i  have the same issu with joomla 3 and coalawebtraffic. @killerbossoriginal what can i do to remove comletely this extention?
![image](https://user-images.githubusercontent.com/112747681/188259582-ed5b18b2-81d8-4e16-a94c-55288d42765f.png)
