### ISSUE TITLE
[4.2.6]If an SVG image is selected, then the height and width values are zero

### ISSUE THREAD

**Issue by PhocaCz** [joomla/joomla-cms#39543] opened 2023-01-02 12:56 UTC
### Steps to reproduce the issue

This issue is associated with the following issue:
https://github.com/joomla/joomla-cms/issues/39538

Templates: Styles (Site) - edit Cassiopeia - tab Advanced - select SVG image:

![Image](https://i.imgur.com/BoA9W3n.png)

### Expected result

Width and height will be correctly set

### Actual result

Width and height is set to zero

### System information (as much as possible)

Joomla 4.2.6
PHP 8.1

**Comment by brianteeman** [comment] 2023-01-02 13:28
confirmed. @dgrammatiko I guess the lazy load stuff should not be applied to svg files

**Comment by dgrammatiko** [comment] 2023-01-02 13:31
> I guess the lazy load stuff should not be applied to svg files

It doesn't **IF** someone is using the recommended way of rendering images (eg using the respective layout): https://github.com/joomla/joomla-cms/blob/4f1a4f15de6722c750c8a8a14cd0c95afc3ccd90/layouts/joomla/html/image.php#L35

**Comment by PhocaCz** [comment] 2023-01-02 13:39
Hi,

can you explain more. What should a standard Joomla user do with an SVG image?

**Comment by dgrammatiko** [comment] 2023-01-02 13:40
@PhocaCz please read this: https://magazine.joomla.org/all-issues/february-2022/new-image-convention-to-help-developers

**Comment by PhocaCz** [comment] 2023-01-02 13:49
I still don't understand, I don't edit any code there. I just select SVG image in template. Does it mean, that Cassiopeia still uses some obsolete code?

**Comment by dgrammatiko** [comment] 2023-01-02 14:19
> Does it mean, that Cassiopeia still uses some obsolete code?

Yes Cassiopeia (and Atum) should use the JLayout for their logos, this is a bug and an easy 2 lines conversion fix

**Comment by PhocaCz** [comment] 2023-01-02 14:31
Ok, thank you for the info.

**Comment by brianteeman** [comment] 2023-01-02 18:30
actually its a bit wierd. If you manually delete the text highlighted in the screenshot then as soon as you focus away the width and height values return and are correct

**Comment by dgrammatiko** [comment] 2023-01-02 21:47
> actually its a bit weird

Well, the inconsistency here comes from the way the image URL is validated and as a side effect of having a load event for the image the code actually has access to the *actual image size*:
https://github.com/joomla/joomla-cms/blob/4f1a4f15de6722c750c8a8a14cd0c95afc3ccd90/build/media_source/system/js/fields/joomla-field-media.w-c.es6.js#L230-L233

On the other side the SVG files inside the media manager as loaded as simple html `<img>` tags and thus the size is coming from the PHP side which in this case both width and height have 0 values. A simple solution is to have the MM to use the same onLoad event for the svg files and thus get the actual size. Should be a few lines of code and an easy implementation. That said, both templates should use the JLayout for the logos because apart from the size part for the svg files the URLs have the junk of the hash-etc...

**Comment by wojtekxtx** [comment] 2023-01-06 15:01
Both @brianteeman and @dgrammatiko are right. From what I know/think: why using `svg` while `jpg` is commonly used standard nowadays? Not to mention that `jpg`s are easier to work with.

**Comment by prajwalah28** [comment] 2023-01-08 05:38
actually its a bit wierd. If you manually delete the text highlighted in the screenshot then as soon as you focus away the width and height values return and are correct.
Well, the inconsistency here comes from the way the image URL is validated and as a side effect of having a load event for the image the code actually has access to the actual image size:
[joomla-cms/build/media_source/system/js/fields/joomla-field-media.w-c.es6.js](https://github.com/joomla/joomla-cms/blob/4f1a4f15de6722c750c8a8a14cd0c95afc3ccd90/build/media_source/system/js/fields/joomla-field-media.w-c.es6.js#L230-L233)

Lines 230 to 233 in [4f1a4f1](https://github.com/joomla/joomla-cms/commit/4f1a4f15de6722c750c8a8a14cd0c95afc3ccd90)

 img.onload = () => { 
   this.inputElement.value = `${urlParts[0]}/${rest.join('/')}#joomlaImage://local-${urlParts[0]}/${rest.join('/')}?width=${img.width}&height=${img.height}`; 
   this.validatedUrl = `${urlParts[0]}/${rest.join('/')}#joomlaImage://local-${urlParts[0]}/${rest.join('/')}?width=${img.width}&height=${img.height}`; 
   this.markValid();`` 
On the other side the SVG files inside the media manager as loaded as simple html <img> tags and thus the size is coming from the PHP side which in this case both width and height have 0 values. A simple solution is to have the MM to use the same onLoad event for the svg files and thus get the actual size. Should be a few lines of code and an easy implementation. That said, both templates should use the JLayout for the logos because apart from the size part for the svg files the URLs have the junk of the hash-etc...

**Comment by richard67** [comment] 2023-01-08 17:14
Closing as having a pull request. Please test #39574 . Thanks in advance.

**Closed as completed by richard67** 2023-01-08 17:14 UTC
Labels: No Code Attached Yet, Backend Template, Frontend Template
