### ISSUE TITLE
Smart Search to return articles in archived state

### ISSUE THREAD

**Issue by sakiss** [joomla/joomla-cms#42280] opened 2023-11-03 15:04 UTC
### Steps to reproduce the issue
1. Set an article in `archived` state.
2. Go to your front-end and use some keywords related to that article in the Smart Search (module or menu item).
3. The article is still returned as result.

### Expected result
Archived articles not to be returned

### Actual result
The article is still returned as result.

### System information (as much as possible)
Tested in J4.4.0

### Additional comments
Seem to work with the articles in 'unpublished' state.

**Comment by Quy** [comment] 2023-11-03 15:19
Reported in #41339 and fixed in v5 #41504.

**Comment by Quy** [comment] 2023-11-03 16:27
Archived articles are not unpublished. They should be discoverable. Please upgrade to v5 as it will not be ported to v4.4 because it is a feature and not a bug.

**Closed as completed by Quy** 2023-11-03 16:27 UTC
Labels: No Code Attached Yet
