### ISSUE TITLE
Custom fields - checkboxes does not store non-standard characters as options

### ISSUE THREAD

**Issue by bubi-luka** [joomla/joomla-cms#16685] opened 2017-06-14 12:02 UTC
### Steps to reproduce the issue

1. Create new field of type **checkboxes**
2. Title:  Občine
3. Insert some checkbox values

Text | Value
------ | -------
Ajdovščina | 1
Križevci | 2
Ljubljana | 3

### Expected result
In the database I would expect something like this:

Field name | Value
--- | ---
Title | Občine
fieldparams | {"options":{"options0":{"name":"Ajdovščina","value":"1"},"options1":{"name":"Križevci","value":"2"},"options2":{"name":"Ljubljana","value":"3"}}}

### Actual result

Field name | Value
--- | ---
Title | Občine
fieldparams | {"options":{"options0":{"name":"Ajdov\u0161\u010dina","value":"1"},"options1":{"name":"Kri\u017eevci","value":"2"},"options2":{"name":"Ljubljana","value":"3"}}}

### System information (as much as possible)

Settings | Version
--- | ---
Database Version | 5.5.5-10.1.21-MariaDB
Database Collation | utf8mb4_unicode_ci
Database Connection Collation | utf8mb4_unicode_ci
PHP Version | 7.0.20
Web Server | Apache/2.4.25 (Fedora) OpenSSL/1.0.2k-fips PHP/7.0.20
WebServer to PHP Interface | apache2handler
Joomla! Version | Joomla! 3.7.2 Stable [ Amani ] 22-May-2017 09:46 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

**Comment by franz-wohlkoenig** [comment] 2017-06-14 12:10
Issue confirmed.
### System information
3.7.3-beta1 (latest nightly build)
Multilanguage Site
macOS Sierra, 10.12.5
Firefox 53 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by franz-wohlkoenig** [comment] 2017-06-14 12:12
can you please edit the Issue at [Issue Tracker](https://issues.joomla.org/tracker/joomla-cms "") and select the Categories – thanks.

**Comment by bubi-luka** [comment] 2017-06-14 12:27
@franz-wohlkoenig: I am new to this. Can you direct me on what needs to be done? I do not see the Categories to be able to select them.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16685">issues.joomla.org/tracker/joomla-cms/16685</a>.</sub>

**Comment by mbabker** [comment] 2017-06-14 12:35
@franz-wohlkoenig not everybody has the ability to set all of the extra fields.

**Comment by franz-wohlkoenig** [comment] 2017-06-14 12:41
got ot, thanks for Info, @mbabker

**Comment by laoneo** [comment] 2017-06-19 06:14
As these characters are json encoded probably they have to be stored that way. Why do you care how they are stored in the database? Important is that they are displayed correctly on the web page.

**Comment by bubi-luka** [comment] 2017-06-20 07:58
I do not know all of the properties of the JSON encoding/decoding, and do not have much experience with it, but as I read it supports UTF-8/UTF-16 I thought it is a bug in the code. If it is the only way of storing the data in json, than I guess it is OK. As I said I have little experience with this format and this representation of the letter looked strange to me.

**Comment by laoneo** [comment] 2017-06-20 08:13
But are the values displayed correctly on the page?

**Comment by bubi-luka** [comment] 2017-06-20 08:16
Yes, with the use of json_decode() they are displayed correctly. The issue is mainly referring on the storing the data in the database.

**Comment by laoneo** [comment] 2017-06-20 08:20
Guess then we can close this issue.

**Comment by brianteeman** [comment] 2017-06-20 08:22
Not so fast

If they are not stored as utf then it makes it impossible to search for them. If they can be stored as utf then it would be much better

**Comment by laoneo** [comment] 2017-06-20 08:26
Keep in mind that this string is json encoded and the database needs to support that otherwise you will not get accurate results. When the results are json decoded then it should let you find the results properly.

**Comment by bubi-luka** [comment] 2017-06-20 08:52
Well the search is working. But ... the search is giving the same result if I search for "Ajdovščina" as well as "Ajdovscina".

**Comment by bubi-luka** [comment] 2017-06-20 08:58
I noticed that that is not only the way the search is working on custom fields but on the whole article ... Perhaps another issue? Zemlja (Earth, even soil) and žemlja (bun) are two different words but they are displayed in the same search result.

**Comment by infograf768** [comment] 2017-06-20 08:58
Imho, this is fine. Storing or presenting a character as "pure" readable utf8 or as its `\uxxx` equivalent is perfectly working.
As for the search for latin characters, afaik, it is by design that it is indifferent whether the search word contains accents or not.
This can be closed as intended behaviour.

**Comment by franz-wohlkoenig** [comment] 2017-06-20 09:07
closed as expected Behaviour.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16685">issues.joomla.org/tracker/joomla-cms/16685</a>.</sub>

**Closed by franz-wohlkoenig** 2017-06-20 09:07 UTC
Labels: No Code Attached Yet
