### ISSUE TITLE
[4.0] [backend-template] Top nav icon colours

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#28464] opened 2020-03-26 09:59 UTC
Not sure if this applies on the default colour scheme for Atum, but I changed the template's hue value to `360` (red) and the top navgation icons appear to use 3 different colours

![screeny](https://user-images.githubusercontent.com/2019801/77634051-45f16d80-6f48-11ea-9c57-6d5a9949b7a7.png)

**Comment by brianteeman** [comment] 2020-03-26 10:24
the version icon and text is using text-muted - it shouldnt be as it fails the contrast. I have an open issue on that already.  don't know about the others

**Comment by Quy** [comment] 2020-06-29 03:13
I am not able to reproduce the gray color.

![28464](https://user-images.githubusercontent.com/368084/85969147-b1017480-b97b-11ea-8435-dfe64495a44d.png)

![28464=css](https://user-images.githubusercontent.com/368084/85969150-b3fc6500-b97b-11ea-99ce-5f8fa23f8ad3.png)

**Comment by Quy** [comment] 2020-07-02 17:06
Closing as non-reproducible.

**Closed as completed by Quy** 2020-07-02 17:06 UTC
Labels: No Code Attached Yet, Information Required
