### ISSUE TITLE
canonical does not show appropriate URL

### ISSUE THREAD

**Issue by pieter-groeneweg** [joomla/joomla-cms#6069] opened 2015-02-12 15:45 UTC
I did install latest 3.4.0b3

when browsing to http://dev.bizgo.nl/category-test/1-art-test.html there is no canonical set as one would expect.
However when addressing same page as http://dev.bizgo.nl/category-test/1 the canonical shows:

    <link href="http://dev.bizgo.nl/category-test.html?id=1" rel="canonical" />

Instead of expected

    <link href="http://dev.bizgo.nl/category-test/1-art-test.html" rel="canonical" />

Meaning when unlucky one will have three pages indexed.... as duplicates.... :(
This is on a vanilla Joomla 3.4.0b3, 

    public $sef = '1';
    public $sef_rewrite = '1';
    public $sef_suffix = '1';
    public $unicodeslugs = '0';
    public $sitename_pagetitles = '0';

.htaccess set.

apache 2.2.15
php 5.4.16

How can this be addressed?

Thanks!

**Comment by Hackwar** [comment] 2015-02-16 17:50
This is a known bug in Joomla for the last several years. I proposed a change a few months ago where the canonical tag is only included if the current page is not the canonical URL, which is how it is supposed to be according to Google. That change was accepted. Without that change, you would have the same situation as now, just that the "right" page would have the canonical tag, too. Which again is wrong by Googles own definition of the canonical tag.

If you want to solve this issue, help by supporting my routing related PRs. They are moving towards that and try to solve the issue.

**Comment by pieter-groeneweg** [comment] 2015-02-23 16:18
I'd love to support..... I am not that familiar with how it works here (I am a github.com noob) tell me which ones and how to promote.. Tx!

**Comment by ggppdk** [comment] 2015-08-22 00:16
Can someone explain why the plugin code for rel canonical is comparing an absolute URL with a relative ?


```
$router = $app::getRouter();

$uri     = JUri::getInstance();
$domain  = $this->params->get('domain');

if ($domain === null || $domain === '')
{
	$domain = $uri->toString(array('scheme', 'host', 'port'));
}

$link = $domain . JRoute::_('index.php?' . http_build_query($router->getVars()), false);

if ($uri->toString() !== $link)
{
	$doc->addHeadLink(htmlspecialchars($link), 'canonical');
}
```

- if you save SEF plugin once, you get into the parameters:
domain:false

thus
```if ($domain === null || $domain === '') {...}```
is not executed and this
```if ($uri->toString() !== $link)```
is comparing an absolute URL with a relative
is this done deliberately ? is this what we want the plugin to do ?

can someone explain what is the intention of code:
```if ($domain === null || $domain === '') {...}```
why is not ?:
```if ($domain == '') {...}```

**Comment by fititnt** [comment] 2016-02-17 09:32
I can confirm that this bug still exist on Joomla 3.4.8.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6069">issues.joomla.org/joomla-cms/6069</a>.</sub>

**Comment by infograf768** [comment] 2016-03-02 14:49
We have modified the code in 3.5.0

**Comment by elpescador-nl** [comment] 2016-03-23 17:56
I have still issues with the sef plugin, also in 3.5.0 . When I add `$domain === null` ($domain is null many times) the comparision is done between absolute urls and fixes the problem:

`if ($domain === null || $domain === false || $domain === '') {...}`

**Comment by roland-d** [comment] 2016-05-19 09:34
@elpescador-nl Are you suggesting a fix?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6069">issues.joomla.org/joomla-cms/6069</a>.</sub>

**Comment by ggppdk** [comment] 2016-05-19 10:01
@roland-d 

That code J3.5.0 code, no longer exists in J3.5.1+, comment is no longer valid,

the issue is fixed in J3.5.1 , 

- the SEF plugin can never guess what the canonical URL should be, so no canonical is added at all, so it is now the current URL, unless component decides otherwise
- the SEF plugin will only care to fix the alternative domain ...  please read the initial posting of this PR, and all of the postings to know more:

https://github.com/joomla/joomla-cms/pull/9565

I think this can be closed

**Comment by roland-d** [comment] 2016-05-19 15:39
@ggppdk Thank you for your comment. Closing this now, it can always be reopened if needed.

**Closed by roland-d** 2016-05-19 15:39 UTC
Labels: No Code Attached Yet
