### ISSUE TITLE
User registration sends admin mail to all users

### ISSUE THREAD

**Issue by spinne1000** [joomla/joomla-cms#17222] opened 2017-07-24 08:07 UTC
### Steps to reproduce the issue
User registration is allowed.
Send mail to administrator set to yes.
The group for the new users is "intern", the parent group is "Registered"

A new user is going to register himself at the frontend.

### Expected result
The user gets an activation mail.
The admin gets an information mail.

### Actual result
The user gets an activation mail.
The admin gets an information mail.
ALL users in the group "Registered, intern" are getting the information mail for the Admin!!

### System information (as much as possible)
Joomla! Version 	Joomla! 3.7.3 Stable [ Amani ] 4-July-2017 08:03 GMT 
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT 
Database Version 	5.5.55-0+deb8u1 
PHP Version 	5.6.30-0+deb8u1 
Web Server 	Apache/2.4.10 (Debian)

**Comment by brianteeman** [comment] 2017-07-24 08:19
I can not confirm this

**Comment by spinne1000** [comment] 2017-07-24 08:27
Apparently the same problem as there descriped: https://developer.joomla.org/joomlacode-archive/issue-28291.html<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17222">issues.joomla.org/tracker/joomla-cms/17222</a>.</sub>

**Comment by brianteeman** [comment] 2017-07-24 08:46
In that issue from a very long time ago the problem was that the site owner had set all users to receive system emails - it was not a joomla bug but a user error

**Comment by spinne1000** [comment] 2017-07-24 08:50
Is there no difference between system emails and mails for the admin?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17222">issues.joomla.org/tracker/joomla-cms/17222</a>.</sub>

**Comment by brianteeman** [comment] 2017-07-24 09:26
No they are the same thing. Mass mail emails are more not system emails

**Comment by spinne1000** [comment] 2017-07-24 09:29
Wow!!! I think that should be marked very much clearlier than "Recieve system mails". <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17222">issues.joomla.org/tracker/joomla-cms/17222</a>.</sub>

**Comment by brianteeman** [comment] 2017-07-24 09:44
Remember that you have to deliberately turn on "receive system emails"

**Comment by brianteeman** [comment] 2017-07-24 09:44
Closed as expected behaviour

**Closed as completed by brianteeman** 2017-07-24 09:44 UTC
Labels: No Code Attached Yet
