### ISSUE TITLE
url parametrs save as posted data !

### ISSUE THREAD

**Issue by hrzolfaghar** [joomla/joomla-cms#37020] opened 2022-02-13 06:29 UTC
set variable in URL: site.com/index.php?my_variable=1

But to our surprise, we see that it is saved as a posted variable & you can retrieve that variable as posted data!

JFactory::getApplication()->input->post->get('my_variable');

**Comment by Quy** [comment] 2022-02-15 01:00
Sorry I don't understand the issue. It is the expected behavior. How does this affect Joomla core?

**Comment by hrzolfaghar** [comment] 2022-02-16 16:17
How do you say It is the expected behavior ?
this method must contain just posted data not GET Data !
There is no such problem in Joomla Series 3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37020">issues.joomla.org/tracker/joomla-cms/37020</a>.</sub>

**Comment by Fedik** [comment] 2022-02-17 09:24
I cannot confirm, while accessing URL query from post I get a `null` while POST request, 
eg `$input->post->get('my_variable')`

**Comment by hrzolfaghar** [comment] 2022-02-17 09:32
> I cannot confirm, while accessing URL query from post I get a `null` while POST request, eg `$input->post->get('my_variable')`

did you test on which version of joomla?

**Comment by Fedik** [comment] 2022-02-17 09:35
4

**Comment by Fedik** [comment] 2022-02-20 09:17
I closing it, I cannot reproduce issue. Works good for j3 and 4.

**Closed as completed by Fedik** 2022-02-20 09:17 UTC
Labels: No Code Attached Yet, Information Required
