### ISSUE TITLE
Searchresults: Case-insensitive title

### ISSUE THREAD

**Issue by Vmadmax** [joomla/joomla-cms#17241] opened 2017-07-25 12:51 UTC
### Steps to reproduce the issue
Use search box to find keyword in title

### Expected result
Original title from content

### Actual result
Lowercase word in title, if it is highlighted

### System information (as much as possible)
Joomla 3.7.3

### Additional comments
It's this line in /components/com_search/views/view.html.php
`$result->title   = StringHelper::str_ireplace($needle, $hl1 . $needle . $hl2, htmlspecialchars($result->title, ENT_COMPAT, 'UTF-8'));`

You don't have to use `str_ireplace` here.

**Comment by ghost** [comment] 2017-07-25 13:07
Issue confirmed. 

Searched for "Sample Sites", got:
![screen shot 2017-07-25 at 13 07 30](https://issues.joomla.org/uploads/1/a92d1132de5fa870404928b996a81ac5.jpg)
### System information
3.7.4-dev (latest nightly build)
Multilanguage Site
macOS Sierra, 10.12.5
Firefox 54 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17241">issues.joomla.org/tracker/joomla-cms/17241</a>.</sub>

**Comment by tonypartridge** [comment] 2017-07-26 23:59
Personally I don't see it as an issue since I wouldn't know if a word was or was not capitalised when searching I would want all results.

I suppose given the usuage case, another option could be added for case sensitive searching.

**Comment by brianteeman** [comment] 2017-07-27 07:32
For me this is a bug that should be fixed. its not about the search but the search results

**Comment by Vmadmax** [comment] 2017-07-27 09:02
For me it's a bug. 
In german, it's often that you have many uppercase words. It's a spelling mistake, it doesn't look good for the user and it's wrong.

I think, you have to search for lower and uppercase, but don't print out the highlighted words in lowercase. It should be the original.

**Comment by brianteeman** [comment] 2017-07-27 09:06
I agree and i would fix it if i could

**Comment by tonypartridge** [comment] 2017-07-27 11:01
Ok I have a partial fix, but the problem is the whole search has been coded to force lower, it lowers the title and result. So now the highlighting is messed up. In turn it looks like StringHelper::substr_replace isn't actually working either! since it should be able to replace StringHelper::str_ireplace without any changes, yet it fails as it never finds a match.

**Comment by INOSIM** [comment] 2017-07-27 11:51
@tonypartridge There seems to be a misunderstanding about the issue. Searching for e.g. joomla and finding joomla, Joomla or JOOMLA is good but searching for joomla and having all title results highlighted as joomla when they originally were Joomla or JOOMLA is the bug.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17241">issues.joomla.org/tracker/joomla-cms/17241</a>.</sub>

**Comment by tonypartridge** [comment] 2017-07-27 11:53
@inosim not according to @brianteeman and @Vmadmax there issue is it's finding all cases. Which is right in different languages.

I'm fixing the replacement to soon, we use ireplace but this doesn't support case sensitive so I'll have to move it to preg_replace.

**Comment by brianteeman** [comment] 2017-07-27 12:02
No I am happy that the search is insensitive. The bug is that when the term
is highlighted then it is transformed to be displayed as lowercase

**Comment by tonypartridge** [comment] 2017-07-27 12:04
Ahhh! 😂 will change the PR

**Comment by INOSIM** [comment] 2017-07-27 12:09
@tonypartridge First off, thanks for working on the replacement issue. But on the case-sensitive search issue, @brianteeman said "its not about the search but the search results" and @vmadmax "I think, you have to search for lower and uppercase, but don't print out the highlighted words in lowercase. As a german, it's not strange to be lazy and search for a word all lowercase but it looks like a typo when the result is lowercase when it normally would be written Uppercase.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17241">issues.joomla.org/tracker/joomla-cms/17241</a>.</sub>

**Comment by tonypartridge** [comment] 2017-07-27 13:15
PR now in guys:
https://github.com/joomla/joomla-cms/pull/17303

**Comment by ghost** [comment] 2017-07-27 13:46
closed as having PR #17303<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17241">issues.joomla.org/tracker/joomla-cms/17241</a>.</sub>

**Closed as completed by ghost** 2017-07-27 13:46 UTC
Labels: No Code Attached Yet
