### ISSUE TITLE
Editor Custom Fileds not work in Contacts

### ISSUE THREAD

**Issue by AlexRed** [joomla/joomla-cms#14005] opened 2017-02-10 07:21 UTC
### Steps to reproduce the issue
On Joomla 3.7.0 Beta2 create a new contact field, Type = editor.
In the single contact edit screen, in the tab "Fieds" the editor don't appear, only the "Toggle editor" button.

### Expected result
the editor appear

### Actual result
the editor don't appear

### Additional comments
![http://alexred.com/joomla/2017/no-editor-contact-fields.png](http://alexred.com/joomla/2017/no-editor-contact-fields.png "http://alexred.com/joomla/2017/no-editor-contact-fields.png")

**Comment by gwsdesk** [comment] 2017-02-10 07:23
I can confirm this issue. The editor is not working here<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14005">issues.joomla.org/tracker/joomla-cms/14005</a>.</sub>

**Comment by Bakual** [comment] 2017-02-10 19:53
This works for me.

Can you check if it works when you change the alias of the field (not the contact alias!) to another name? Because if it is the same as an already existing field (custom field or one from the contact itself) it may break.

**Comment by AlexRed** [comment] 2017-02-10 21:38
Not work also when I change the alias of the field.

**Comment by franz-wohlkoenig** [comment] 2017-02-11 06:21
Confirm Issue, no Editor-Field is shown.
#### Test on:
Joomla! 3.7.0-beta3
macOS Sierra, 10.12.3
Firefox 50.1.0
PHP 7.0.4
MySQLi 5.5.54-0

**Comment by infograf768** [comment] 2017-02-11 07:17
The issue is only present when using TinyMCE.
If Editor None or CodeMirror, all is fine.

**Comment by gwsdesk** [comment] 2017-02-11 07:20
I confirm @infograf768 but we should fix it since most users will use an editor

**Comment by Bakual** [comment] 2017-02-11 07:23
Hmm, can you guys say which browser and OS you use? I'm pretty sure I tested with Tiny as well and it worked. Using Chrome on Windows I think.
Can you also check the console for JavaScript errors?

**Comment by franz-wohlkoenig** [comment] 2017-02-11 07:30
confirm working if not using TinyMCE.
#### Test on:
Joomla! 3.7.0-beta3
macOS Sierra, 10.12.3
Firefox 50.1.0
PHP 7.0.4
MySQLi 5.5.54-0

**Comment by infograf768** [comment] 2017-02-11 07:31
Firefox 48.0.2 Macintosh, PHP 5.4.4

It works with Safari!

With Firefox, I do get js errors
```js
08:29:40.475 TypeError: e is undefined
r()tinymce.min.js:13
a()tinymce.min.js:13
i/</<()tinymce.min.js:13
i()tinymce.min.js:8
.fire()tinymce.min.js:8
this.nodeChanged()tinymce.min.js:4
L.prototype.nodeChanged()tinymce.min.js:12
<anonymous>tinymce.min.js:7
i()tinymce.min.js:8
.fire()tinymce.min.js:8
s.add()tinymce.min.js:7
<anonymous>tinymce.min.js:7
i()tinymce.min.js:8
.fire()tinymce.min.js:8
L.prototype.initContentBody()tinymce.min.js:11
L.prototype.init()tinymce.min.js:11
t/<()tinymce.min.js:11
n/this.loadScripts/v/<()tinymce.min.js:4
n()tinymce.min.js:3
n/this.loadScripts/v()tinymce.min.js:4
n/this.loadScripts/v/</<()tinymce.min.js:4
o()tinymce.min.js:4
1tinymce.min.js:13:17430
```

**Comment by franz-wohlkoenig** [comment] 2017-02-11 07:33
Chrome works too.

**Comment by infograf768** [comment] 2017-02-11 07:43
@Bakual
It may be of interest to know that it does work for a user field.

**Comment by gwsdesk** [comment] 2017-02-11 08:13
Works in Edge as well

**Comment by gwsdesk** [comment] 2017-02-11 08:16
and oh way this is weird. Upgraded my Firefox to 51.0.1 and see for yourself. Now working in FF as well
![editor](https://cloud.githubusercontent.com/assets/8178486/22852358/18d65c00-f06d-11e6-8d25-ff6b04148155.gif)

**Comment by AlexRed** [comment] 2017-02-11 08:31
In my test:
No work on Firefox 51.0.1 (64-bit)
Work on Chrome 56.0.2924.87 (64-bit)

Linux PC, 
Server Apache/2.4.10  PHP 5.5.15
Error console:
L’utilizzo di getAttributeNode() è deprecato. Al suo posto utilizzare getAttribute().  jquery-migrate.min.js:2:1714
TypeError: e is undefined[Ulteriori informazioni]  tinymce.min.js:13:17430

**Comment by Bakual** [comment] 2017-02-11 08:31
My tiny JavaScript knowledge fails here. Maybe someone else can figure out if this is a browser bug (may be since upgrading FireFox seems to fix it) or an error in the editor JS. Or both.

**Comment by franz-wohlkoenig** [comment] 2017-02-11 08:36
Firefox 51.0.1 shows no TinyMCE, test on Windows7, MacOS Sierra:
![bildschirmfoto 2017-02-11 um 09 34 40](https://cloud.githubusercontent.com/assets/8235763/22852486/80fddcb6-f03d-11e6-92c6-6701dc14c087.JPG)

**Comment by gwsdesk** [comment] 2017-02-11 08:46
For the non-believers ;-)  Windows 10 (tailor build PC)
![editor2](https://cloud.githubusercontent.com/assets/8178486/22852576/21d9c72a-f071-11e6-912a-c0a960c39676.gif)

**Comment by AlexRed** [comment] 2017-02-11 08:48
it seems ok on Firefox 51.0.1 (32-bit) and not on Firefox 51.0.1 (64-bit),

**Comment by AlexRed** [comment] 2017-02-11 09:15
No, it is not related to the 32 or 64 bit.
gwsdesk use the TinyMCE "medium preset" for the Administrator user, if I set it also in the Firefox 51.0.1 (64-bit) I can see the editor.
But if I set the default "advanced preset" for the Administrator user I can't see the editor.
Please gwsdesk try with the "advanced preset".

**Comment by gwsdesk** [comment] 2017-02-11 09:18
@Alexred Nice catch Alessandro! Indeed with "advanced preset" it is not loading ouch!

**Comment by infograf768** [comment] 2017-02-11 09:21
I confirm that using the Medium Preset works on my Firefox 48.0.2.
@dgt41
Can you look at this, please.

**Comment by infograf768** [comment] 2017-02-11 09:22
and @Fedik

**Comment by gwsdesk** [comment] 2017-02-11 09:24
In addition what @infograf768 mentioned nly the medium-preset work. Also the "simple" preset does not work

**Comment by AlexRed** [comment] 2017-02-11 09:26
Editor "simple" preset (Set 0) is ok for me in the Contact Field

**Comment by gwsdesk** [comment] 2017-02-11 09:33
Not for me see image 
![editor3](https://cloud.githubusercontent.com/assets/8178486/22852841/c7554e4e-f077-11e6-93ef-f9d3139b4942.gif)

**Comment by AlexRed** [comment] 2017-02-11 09:36
it is not **Set 0** but **Set 2** for Public not for administrator

**Comment by gwsdesk** [comment] 2017-02-11 09:48
Sorry I am missing out what you mean. I am opening Glip - CMS RTto avoid clutter here

**Comment by gwsdesk** [comment] 2017-02-11 10:00
I am not sure if we need to open a new Issue for this but for e the entire layout of this configuration of TinyMCE is horrendous. We will face a fury of comments and problems on the forums for sure. It is difficult the least and before I had a chat with @AlexRed on Glip I simply could not get it right. The tabs for 2/1/0 should be in logical order ("0" first), the image in the top is confusing (even clickable without effect) and should be removed since has no function imho. The entire layout is very much cluttered and needs to be addressed imho. This will create a lot of confusion with the end-users

**Comment by AlexRed** [comment] 2017-02-11 10:08
I agree, should be in logical order (SET "0" first).
The "demo" editor advanced mode in the top is not necessary and it creates confusion. 
We should open it only when we need to drag the buttons in the set.

**Comment by Fedik** [comment] 2017-02-11 11:11
> In the single contact edit screen, in the tab "Fieds" the editor don't appear, only the "Toggle editor" button.

what about other (Article, Category), whether there the editor works in another tab?

**Comment by gwsdesk** [comment] 2017-02-11 11:25
The editor works normal in the other sections where it is used (articles/modules/cats/etc) except for the custom fields as outlined

**Comment by AlexRed** [comment] 2017-02-11 11:49
The problem seems only the "**Font Family**" button.  If you try to remove (drag out) the "Font Family" button in the "advanced preset" and save it, the editor is ok in the Contact Field.

**Comment by AlexRed** [comment] 2017-02-11 12:23
In Joomla 3.6.5, editor TinyMCE "Functionality"--> Extended 
in a new article edit page in the editor the "Font Family" button appears by default not select, it is in "Font Family" mode:

![http://alexred.com/joomla/2017/editor365.png](http://alexred.com/joomla/2017/editor365.png "http://alexred.com/joomla/2017/editor365.png")


In Joomla 3.7.0 Beta 2, editor TinyMCE in "Advanced" preset
in a new article edit page in the editor the "Font Family" button appears by default in "serif" and 12pt font size.

![http://alexred.com/joomla/2017/370editor.png](http://alexred.com/joomla/2017/370editor.png "http://alexred.com/joomla/2017/370editor.png")


and when the cursor in the editor area the "Font Family" button appears "Tahoma" and 9pt ont size.

![http://alexred.com/joomla/2017/test-text.png](http://alexred.com/joomla/2017/test-text.png "http://alexred.com/joomla/2017/test-text.png")


sorry for my bad english, I hope screenshot can help.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14005">issues.joomla.org/tracker/joomla-cms/14005</a>.</sub>

**Comment by gwsdesk** [comment] 2017-02-11 14:07
This does not only happen in the custom fileds situation a described in this Issue but happens throughout all instances where TinyMCE is loaded such as Articles/Cats/modules etc

**Comment by Fedik** [comment] 2017-02-11 15:01
It looks like TinyMCE bug, see changelog: https://www.tinymce.com/docs/changelog/ for Version 4.5.3 - February 1, 2017 , 

>  FIXED bug where the editor would throw error with the fontselect plugin on hidden editor instances in Firefox.

Should be fixed in new version of TinyMCE.
Who brave to do update? 😄

**Comment by dgt41** [comment] 2017-02-11 15:03
I'll do that

**Comment by AlexRed** [comment] 2017-02-11 15:49
Patch ok, now Editor is ok in Custom Fileds,
but the remains the problem https://github.com/joomla/joomla-cms/issues/14005#issuecomment-279140582

**Comment by Bakual** [comment] 2017-02-11 15:53
I'm closing this issue as there is a PR.
@AlexRed Can you open a new one for that issue with the the button so we can better track it?

**Closed by Bakual** 2017-02-11 15:53 UTC
Labels: No Code Attached Yet

**Comment by Fedik** [comment] 2017-02-11 16:05
> but the remains the problem #14005 (comment)

It looks like TinyMCE feature, does not related to Joomla.

**Comment by AlexRed** [comment] 2017-02-11 16:08
yes, looks like TinyMCE feature in the new versions
