### ISSUE TITLE
[3.7 RC3] Error The apc Cache Storage is not supported on this platform

### ISSUE THREAD

**Issue by bugsmafia** [joomla/joomla-cms#15400] opened 2017-04-19 04:51 UTC
### Steps to reproduce the issue
Install Joomla 3.0.0 RC3 FULL
Open: System -> Global Configuration
Click the "save" button.

### Expected result
Successful save configuration without error output

### Actual result
**An error has occurred.**
0 The apc Cache Storage is not supported on this platform.

![1d22b82e6467632f4d753a18d5ab6462 1](https://cloud.githubusercontent.com/assets/1024296/25163541/88aa3352-24e4-11e7-8483-6f6559e84c9b.png)

### System information (as much as possible)

> php: Linux vh62.timeweb.ru 4.9.18-timeweb #1 SMP Mon Mar 27 16:26:02 MSK 2017 x86_64
> dbversion: 5.5.52-38.3
> dbcollation: utf8_general_ci
> dbconnectioncollation: utf8mb4_general_ci
> phpversion: 7.0.15
> server: Apache/2.4.7
> sapi_name: apache2handler
> version: Joomla! 3.7.0-rc3 Release Candidate [ Amani ] 18-April-2017 16:00 GMT
> platform: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

### Additional comments
The cache data is different from the one specified in configuration.php

![3e561eb5c23efb7b1561ba0e4fe41f5c 1](https://cloud.githubusercontent.com/assets/1024296/25163641/44c1f8d6-24e5-11e7-9648-5d1207df1f79.png)

=============
Configuration File
=============
smtpport: 25
caching: 0
**cache_handler: apc**
cachetime: 15
cache_platformprefix: 0

**Comment by bugsmafia** [comment] 2017-04-19 05:15
If you manually change the line in configuration.php - public $ cache_handler = 'file';
The error is gone
It is not clear why the ACP configuration was the default

**Comment by rdeutz** [comment] 2017-04-19 07:33
Is this problem re-produceable, really can't see a reason why this should happen.

**Comment by richard67** [comment] 2017-04-19 10:15
I can't reproduce that.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15400">issues.joomla.org/tracker/joomla-cms/15400</a>.</sub>

**Comment by franz-wohlkoenig** [comment] 2017-04-22 07:46
@bugsmafia as this Issue seems not re-produceable i will close it. Please feel free to reopen for further Information.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15400">issues.joomla.org/tracker/joomla-cms/15400</a>.</sub>

**Closed by franz-wohlkoenig** 2017-04-22 07:46 UTC
Labels: No Code Attached Yet
