### ISSUE TITLE
[4.0] [IE11] Image Intro modal JS error

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#23810] opened 2019-02-08 12:13 UTC
### Steps to reproduce the issue

1. In IE11, open any article in your Article Manager
2. Go to the "Images and Links" tab
3. For the Image Intro option, click "select" which will open up a modal

You'll notice 2 errors in the browser console

![screeny44](https://user-images.githubusercontent.com/2019801/52477755-f8c30880-2b9a-11e9-89ff-e3e705dea92a.png)

**Comment by alikon** [comment] 2019-04-10 17:21
can we close this for reason 

> Closing as template team are working on backend template

**Comment by brianteeman** [comment] 2019-04-10 17:36
Are they actually working on it or is it wishful thinking

**Comment by alikon** [comment] 2019-04-10 17:51
some issues recently have been closed for the same reason...
i would like to start to reduce the number of opened issues ....so ...

> Are they actually working on it or is it wishful thinking

I hope the 1st option :smile:

**Comment by brianteeman** [comment] 2019-04-10 18:04
I wouldn't close the issue until it's resolved.

**Comment by brianteeman** [comment] 2019-05-23 12:25
Looks like the same root cause as #23825

**Comment by brianteeman** [comment] 2019-06-10 20:41
This issue can be closed as the production department have decided to adopt a browser support policy of PROD2019/005 - Change minimum version requirements for all browsers to n-2 and drop support for Internet Explorer. https://volunteers.joomla.org/departments/production/reports/1031-production-dept-meeting-may-28-2019

**Closed as completed** 2019-06-10 20:45 UTC
Labels: No Code Attached Yet, J4 Issue
