### ISSUE TITLE
[5.0] Error Message during installation 

### ISSUE THREAD

**Issue by ChristineWk** [joomla/joomla-cms#40503] opened 2023-04-29 15:48 UTC
### Steps to reproduce the issue
During the installation of Joomla 5.0.0-dev I got the following message:
```
Joomla\Filesystem\File::write(): Argument #2 ($buffer) cannot be passed by reference
```

The installation itself (frontend and backend) was successful

### Expected result
No failure message

### Actual result
See above message

### System information (as much as possible)
Database Type mysql 
Database Version 5.7.41-log 
Database Collation latin1_swedish_ci 
Database Connection Collation utf8mb4_general_ci 
Database Connection Encryption None 
Database Server Supports Connection Encryption Yes 
PHP Version 8.1.16 
Web Server Apache 
WebServer to PHP Interface cgi-fcgi 
Joomla! Version Joomla! 5.0.0-dev Development [ Schnitzel ] 29-August-2022 12:18 GMT

**Comment by Hackwar** [comment] 2023-04-29 19:15
Please test #40504 if that fixes your issue. Since we have a PR, I'm closing the issue.

**Closed as completed by Hackwar** 2023-04-29 19:15 UTC
Labels: No Code Attached Yet

**Comment by richard67** [comment] 2023-04-30 08:17
I think this issue happens also with 4.4-dev. I haven't checked yet, but from code review this should be the case. If someone is faster than me to check this, please do and report back here.

**Comment by richard67** [comment] 2023-04-30 09:20
I just have tested and can reproduce the issue also on the 4.4-dev branch.

**Comment by ChristineWk** [comment] 2023-04-30 10:09
@richard67

loaded 4.4.0-dev and confirm issue during installation

**Comment by sandewt** [comment] 2023-04-30 12:28
> During the installation of Joomla 5.0.0-dev I got the following message:

I don't see an error message. Even a reinstall showed no error.
Did I miss something? Where was it seen?

System Information
=============
php: Windows ....
dbserver: mysql
dbversion: 10.4.25-MariaDB
dbcollation: utf8mb4_unicode_ci
dbconnectioncollation: utf8mb4_general_ci
dbconnectionencryption: 
dbconnencryptsupported: false
phpversion: 8.1.10
server: Apache/2.4.54 (Win64) OpenSSL/1.1.1p PHP/8.1.10
sapi_name: apache2handler
version: Joomla! 5.0.0-dev Development [ Schnitzel ] 29-August-2022 12:18 GMT
useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0

**Comment by richard67** [comment] 2023-04-30 12:43
@sandewt You have to use a remote database host and not localhost so that you get created the file in the installation folder which you have to remove to show that you have access to the server.

**Comment by sandewt** [comment] 2023-04-30 12:51
@richard67 

Thanks. This is completely new to me. Is there any documentation about that?

**Comment by ChristineWk** [comment] 2023-04-30 12:53
Think @sandewt wasn't on local anyway.
You can see it during installation if you hover up.

**Comment by richard67** [comment] 2023-04-30 12:53
@sandewt It is like that since ages (3.4 or 3.5 or so) and there is some documentation but I won't have the time to search for it now. If you make a new installation and the database host is not equal to localhost or 127.0.0.1, that thing with the file happens. If you have your website since longer time and always updated it you won't have noticed that.

**Comment by richard67** [comment] 2023-04-30 12:59
@sandewt https://docs.joomla.org/J3.x:Secured_procedure_for_installing_Joomla_with_a_remote_database .

**Comment by richard67** [comment] 2023-04-30 13:00
It was 3.7 when this was established.

**Comment by ChristineWk** [comment] 2023-04-30 13:23
> It was 3.7 when this was established.

That's correct @richard67 
"..... we require you to delete a file in the installation folder that was randomly created by the installer" (from your link)

Yes, that is known, but then you got a message similar to: delete the xzy.txt file. Only then did the installation go through.

But here it is different situation: it gives a different message than above and the installation still goes through, without deleting a txt file.

**Comment by richard67** [comment] 2023-04-30 13:27
> But here it is different situation: it gives a different message than above and the installation still goes through, without deleting a txt file.

Yes, I know. I was only answering @sandewt question. Due to the issue here, that text file is not written. When that error is fixed, it will work again. But it needs to close the browser between the 2 tests because when you have tested it before with the error and now fix the error, there is still the saved state of that localhost check in the session saved in the browser. But that's something for experts. Normally it works as described.
