### ISSUE TITLE
Repeatedly logged out of backend - Any thoughts why?

### ISSUE THREAD

**Issue by R-R-M** [joomla/joomla-cms#30776] opened 2020-09-26 10:54 UTC
### Steps to reproduce the issue
Clean install of Joomla 4 beta 4
Front end is signed out
GLOBAL CONFIG SETTING:
Set System session handler to 60 minutes & Database
Shared sessions set to off
Tracking session metadata set to off
System cache set to off
Built on a sub domain

The only external plugins are Akeeba backup & Akeeba Admin tools

### Expected result
Remain logged in until session time of 60 minutes expires or I sign out 

### Actual result
After about 3 / 6 clicks around the backend of the website I get logged out and have to sign back in. No no warning no error message

### System information (as much as possible)
PHP 7.4.10
Joomla 4 Beta 4
Using my own template but not visiting the front end

### Additional comments

**Comment by HLeithner** [comment] 2020-09-26 10:57
Could you please check the browser developer console if there is a problem load a file for example?

**Comment by R-R-M** [comment] 2020-09-26 11:12
Hi, The developer console does not report any issues. However after submitting this post I uninstalled Akeeba admin tools and Akeeba backup. The uninstall did not go very well with various issues. I am now getting this message: (An error has occurred. 0 Class 'FOF30\Container\Container' not found). But interestingly have not been logged out either.  So suspect this is disappointingly an Akeeba issue. I am going to rebuild without using Akeeba. On another note does anyone know if it is ok at this point to built a site using Joomla 4 Beta 4. As a production version without going live until the final release of Joomla 4. Basically would I be able to upgrade from a Beta to a production version of Joomla 4 down the line.

**Comment by HLeithner** [comment] 2020-09-26 11:41
@nikosdion do you have any idea if this is related to your components?

**Comment by nikosdion** [comment] 2020-09-26 11:47
I haven't had that problem and I'm in the middle of developing a Joomla 4 template for our site, on a copy of the site with ALL of my software installed (including things the OP didn't include). So on first blush I am inclined to say it's probably unrelated or at least I haven't observed it with the settings I use on my local J4 sites, including the upgraded copy of our live site. 

One quick test for the OP is disabling Admin Tools system plugin and watch if this issue happens again within a few hours of using the site continuously. Nothing else I have published could be related.

**Comment by R-R-M** [comment] 2020-09-26 11:48
I think I have fixed the error message and it looks like that was due to me switching off part of Akeeba. I am currently rebuilding the site without Akeeba and if there are no issues it would be safe to assume that it related to admin tools or Akeeba backup.

**Comment by R-R-M** [comment] 2020-09-26 12:35
OK I now have a clean install of just Joomla 4 Beta 4 no third-party plugin's no custom templates and tested on Safari and chrome and it keeps logging me out after several clicks in less that 5 minutes. Any thoughts?
Cleared browser cache,
all settings are at default
Site is built using a sub domain
Going to investigate Cloudflare, but running out of ideas...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30776">issues.joomla.org/tracker/joomla-cms/30776</a>.</sub>

**Comment by R-R-M** [comment] 2020-09-26 13:07
![screen shot 2020-09-26 at 13 04 16](https://issues.joomla.org/uploads/1/b1cc850c0eb503191e70a09257108b39.png)

The attached image has been seen a few times, once this shows in the console the next click forces me out of the site. Maybe this will help find the issue I am having? Any thoughts?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30776">issues.joomla.org/tracker/joomla-cms/30776</a>.</sub>

**Comment by R-R-M** [comment] 2020-09-26 13:18
The image above is causing the problem. If I login to the control panel as per the image above and refresh the page several times, after about 4 / 7 page refreshes the error code is loaded into the developers console and the privacy request icon goes from green to red. The following refresh logs me out. Is this a bug or a server issue, I have many other sites pre Joomla 4 on the server and no issues. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30776">issues.joomla.org/tracker/joomla-cms/30776</a>.</sub>

**Comment by R-R-M** [comment] 2020-09-26 13:54
Similar issue repeating the same steps. Every time I refresh the page the system checks for Joomla updates, this time the attached image triggered the console error, the next refresh logged me out.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30776">issues.joomla.org/tracker/joomla-cms/30776</a>.</sub>

**Comment by R-R-M** [comment] 2020-09-26 13:54
![screen shot 2020-09-26 at 13 54 26](https://issues.joomla.org/uploads/1/97f9063e60dcb0d8fae7d61f502c18c4.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30776">issues.joomla.org/tracker/joomla-cms/30776</a>.</sub>

**Comment by nikosdion** [comment] 2020-09-26 14:32
Your screenshot is a symptom, not a cause. When Joomla Update tries to fetch the core update status you are already logged out and you get an HTML page (login) which causes the JSON parsing error. 

You said the problem occurs even when you haven't installed Akeeba software so the root cause is not my software, as I suspected. 

What are the pages you visit BEFORE you get logged out? My suspicion is that the session storage gets either full or erased, causing the problem. 

You also said you're using CloudFlare. First of all, J4 is not production ready. Using it on a live site is... brave :) Second, can you try WITHOUT CloudFlare? Some of its features such as RocketLoader and some caching rules may cause that kind of a problem with admin pages. If that was the problem add a page rule to disable caching and security controls for all administrator URLs. This should work. Once you confirm it you can start optimizing the security settings if you want. That's basically what I had to do on our live Joomla 3 site.

**Comment by R-R-M** [comment] 2020-09-26 15:01
Hi Nicholas,
The errors above are replicated by logging into the website backend and refreshing the page 4/6 times, the console will then catch the error and then the next refresh will log you out. The same error happens when browsing other pages. refreshing the same page just proves that this error is not related to something I was actively doing. Or that the problem was related to Akeeba. 
I am not using it on a production site but I am wanting to know if it would be safe to say I can upgrade from J4 Beta to a production version when it becomes available. I don't want to start creating pages of content if I cannot upgrade later? 

CloudFlare is installed and caching the site. So this is my next avenue to investigate. Just surprised that no one else is having this issue. Other than Cloudflare this is an out of the box setup.

**Comment by jiweigert** [comment] 2020-09-26 15:46
Hi, just throwing in an idea:
Could it be that Your Browser got updated and now have a problem with the ```SameSite``` cookie attribute?
I experienced that recently with the different Browser Google Chrome 85.xx version on serveral sites, that I got kicked out, nonetheless that i should stayed logged-in ..
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30776">issues.joomla.org/tracker/joomla-cms/30776</a>.</sub>

**Comment by R-R-M** [comment] 2020-09-26 15:57
It's been happening for a few days and over multiple browsers.

**Comment by alikon** [comment] 2020-09-26 16:07
i suggest you to read this https://support.cloudflare.com/hc/en-us/articles/201997250-Cloudflare-and-Joomla-Recommended-First-Steps
as this is not a joomla issue i'm closing this

**Closed as completed by alikon** 2020-09-26 16:07 UTC
Labels: No Code Attached Yet

**Comment by infograf768** [comment] 2020-09-26 17:45
> I am not using it on a production site but I am wanting to know if it would be safe to say I can upgrade from J4 Beta to a production version when it becomes available. I don't want to start creating pages of content if I cannot upgrade later?

It is not safe at all imho.

**Comment by R-R-M** [comment] 2020-09-26 18:06
@infograf768 Thanks appreciate your advise

Just to close this off. I tried various things with Cloudflare RocketLoader was not active and tried using a page rule to remove page cache. But the issue continued. I have built another clean copy of J4 using the same server and avoiding Cloudflare and it's working fine.

**Comment by agile-deployer** [comment] 2021-05-31 20:43
I have had the exact same issue with Joomla 4 Beta 7. The symptoms are identical and I haven't been able to find out why it is happening. My set up is out of the box Joomla 4 Beta 7 using the NGINX Webserver. I use Cloudflare and have tried as many different configurations of its settings as possible to see if it resolves, but, without success.
