### ISSUE TITLE
Multi-language menu item selector url cache bug Joomla 3.6.1/ J 3.6.2

### ISSUE THREAD

**Issue by ssnobben** [joomla/joomla-cms#11470] opened 2016-08-05 10:09 UTC
#### Steps to reproduce the issue
1. Set up/test your multi-language site where you have menu items for different menus to different languages. 
2. Update to Joomla 3.6.1/J 3.6.2
3. Activate Joomla cache --> Conservative cache.
4. Click on one menu and see article en-GB etc.
5. Click on Language selector to have the same menu item for that article in another langauge example it-IT etc
6. Error and bug is that Joomla goes to the main home page of that language ie it-IT instead of the menu for that language selected and that article in other languge etc

#### Expected result

***  If you disable the cache of Joomla example conservative cache the menus work and you get redirected to the correct menu for that selected language. 

#### Actual result

You get redirected to the wrong menu ie home page of that choosen language home page.

#### System information (as much as possible)

Update from Joomla 3.6.0 to Joomla 3.6.1/ Joomla 3.6.2 still have this problem.

**Comment by infograf768** [comment] 2016-08-05 10:11
Was that working in 3.5.1 ?

**Comment by andrepereiradasilva** [comment] 2016-08-05 10:36
i presume you only have language associations between the menu items in different languages.
If so i can't reproduce this.

Associations is very hard to debug, so please add the most information possible, like which menu items, which have associations, do articles also have associations? etc

**Comment by ssnobben** [comment] 2016-08-05 10:43
infograf768 - yes. 

It works i f you disable the Joomla conservative cache then the menu associations works. 

If you enable Joomla conservative cache then you being redirected to respective language home page instead when you click on Language selector module and each languages that you have.

**Comment by ssnobben** [comment] 2016-08-05 10:44
andrepereiradasilva  - its all menu items and its all language associations.

**Comment by infograf768** [comment] 2016-08-05 10:49
I can't reproduce the issue here on my test site

**Comment by andrepereiradasilva** [comment] 2016-08-05 10:50
with the information you gave, i tried the following

- Used clean 3.6.2 with multilanguage (two languages - en-GB and pt-PT)) , with protostar
- Created two menu items (one en-GB and the other it-IT) and associated them
- Enabled conservative cache
- In frontend used the language switcher to switch between sites.
- All worked fine.

Can't reproduce.

**Comment by brianteeman** [comment] 2016-08-05 11:15
I tested it as well - could not reproduce

**Comment by ssnobben** [comment] 2016-08-05 11:24
hmm thanks guys..

ok I will have to live with disabling the Joomla standard cache feature for while then and see if any other guys have this problem and could come up with any solution for it. 

Any hint for me what I can do for testing and what the problem could be appreciated..

Cheers and thanks infograf768 ,andrepereiradasilva, brianteeman!

**Comment by andrepereiradasilva** [comment] 2016-08-05 11:38
disable all extensions you have installed to check if there is a problem with an extension you have.

But since this does not seem a core joomla bug, please use the forum for more help.

**Comment by brianteeman** [comment] 2016-08-05 11:38
Closing this at this time

@ssnobben if you ever track this down please report back

**Closed by brianteeman** 2016-08-05 11:38 UTC
Labels: No Code Attached Yet

**Comment by ssnobben** [comment] 2016-08-10 09:10
Maybe similar like #6253 3.4 language switcher module (mod_languages) creates wrong url using &lang or not?
