### ISSUE TITLE
[4.3] template.min.js error for document.cookie

### ISSUE THREAD

**Issue by joeforjoomla** [joomla/joomla-cms#40374] opened 2023-04-12 17:11 UTC
### Steps to reproduce the issue
Joomla 4.3 RC3

### Expected result
No errors in the backend console

### Actual result
Error as below in the getCookie function

![image](https://user-images.githubusercontent.com/17835460/231532239-85669382-afee-4d42-b86a-0613089e438c.png)

**Comment by brianteeman** [comment] 2023-07-12 12:05
has anyone been able to replicate this?

@joeforjoomla are you still seeing this?

**Comment by VillaesterModerneMedien** [comment] 2023-08-29 16:52
I was able to reproduce the error today on a customer site. For me the problem was/is that the cookie atumSidebarState was not set.

Why this is not set I could not find out. After I added it manually via debugger, the JS console error was gone.

**Comment by richard67** [comment] 2023-09-24 14:38
Closing as having a pull request. Please test #41909 . Thanks in advance.

**Closed as completed by richard67** 2023-09-24 14:38 UTC
Labels: No Code Attached Yet, bug
