### ISSUE TITLE
Backend module 'save and new' you can't choose backend location

### ISSUE THREAD

**Issue by joris85** [joomla/joomla-cms#28926] opened 2020-05-04 09:50 UTC
### Steps to reproduce the issue

1. Go to backend modules.
2. Set to Administrator modules
3. Create new administrator module
4. Click on Save and new 
Result:
You have a new module but i can't choose a backend location (you can choose frontend locations).
Looks like it is creating a frontend module after save and new.

### Expected result
I would expect that i can create multiple modules in a row in the location cpanel after click on save and new.

**Comment by infograf768** [comment] 2020-05-04 10:03
Which J version are you using?

**Comment by infograf768** [comment] 2020-05-04 10:07
My guess is that you created a site module and not an administrator module.
You first have to filter the modules manager to be sure you are creating and admin module.
Here for a custom admin module (3.9.x). Remark the badge,

<img width="848" alt="Screen Shot 2020-05-04 at 12 04 45" src="https://user-images.githubusercontent.com/869724/80955493-b1f4aa80-8dff-11ea-9c7e-c701a7f6f724.png">

**Comment by ReLater** [comment] 2020-05-04 10:40
I cannot confirm this issue.

Joomla 3.9.19-dev (nightly build)

**Comment by coolcat-creations** [comment] 2020-05-10 13:21
Can't reproduce either

**Comment by coolcat-creations** [comment] 2020-05-10 13:49
@joris85 - I created two screens showing the backend positions.
It maybe explains better how to use the backend positions.

https://xd.adobe.com/view/658d54b4-403a-40c3-6212-af09c5d53a29-13bc/grid/

If anyone has an idea how to implement it in the backend as a preview I can deliver image files. I think this is a little bit easier to understand for new users where the positions are than the template preview.

**Comment by joris85** [comment] 2020-05-12 04:48
I will test it again, i have this issue often but i do use advanced module manager of regular labs on most sites. So i think i have to say sorry for not testing it on core 😅

Thanks all for testing and i check on with peter about this issue i think. 
🙏

**Comment by chmst** [comment] 2020-06-14 14:37
@coolcat-creations this would be agreat improvement! Very nice - make a feture reqest! 

@joris85 is this still an issue in Joomla? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28926">issues.joomla.org/tracker/joomla-cms/28926</a>.</sub>

**Comment by Quy** [comment] 2020-06-25 15:44
Closing as not an issue.

**Closed as completed by Quy** 2020-06-25 15:44 UTC
Labels: No Code Attached Yet, Information Required
