### ISSUE TITLE
[4.1] menu item link calss doesn't accept @

### ISSUE THREAD

**Issue by aschkenasy** [joomla/joomla-cms#37529] opened 2022-04-10 20:56 UTC
### Steps to reproduce the issue
try to add `uk-visible@m` as link class to any menu item

### Expected result
`uk-visible@m` should be stored

### Actual result
class name value throws error Invalid field: Link Class

### System information (as much as possible)
j4.1.2

### Additional comments

**Comment by brianteeman** [comment] 2022-04-10 21:32
> class name value throws error Invalid field: Link Class

That is because it is an invalid class

https://www.w3.org/TR/CSS21/syndata.html#characters

**Comment by chmst** [comment] 2022-04-11 11:05
This is intended behaviour. Closing.

**Closed as completed by chmst** 2022-04-11 11:05 UTC
Labels: No Code Attached Yet
