### ISSUE TITLE
[4.0-dev] Installation folder is deleted after installation without deleting it manually.

### ISSUE THREAD

**Issue by socke300** [joomla/joomla-cms#35218] opened 2021-08-18 13:37 UTC
### Steps to reproduce the issue
1. Setup Joomla with 4.0-dev branch.
2. Follow the installation instructions
3. When the installation is finished, do not press the "Delete installation folder" button.
4. Click on the "open backend" button

### Expected result
The installation folder should remain.

### Actual result
The folder is deleted without pressing the "delete" button.

### System information (as much as possible)
I only noticed the error on Branch 4.0-dev, other versions were not tested.

**Comment by PhilETaylor** [comment] 2021-08-18 14:07
Confirmed. 

@wilsonge is a naughty boy.

**Comment by infograf768** [comment] 2021-08-18 14:09
The dev case is not anymore taken care of in `Joomla.deleteJoomlaInstallationDirectory = function (redirectUrl) {` in `remove.js`

**Comment by PhilETaylor** [comment] 2021-08-18 14:11
It should - here: 

https://github.com/joomla/joomla-cms/blob/c59286034b3794ddd63f302e569ef09714447dde/installation/template/js/remove.js#L55

**Comment by infograf768** [comment] 2021-08-18 14:17
You are correct. There were many changes in that js file since I looked at it.

**Comment by PhilETaylor** [comment] 2021-08-18 14:21
fixed in https://github.com/joomla/joomla-cms/pull/35220

**Comment by richard67** [comment] 2021-08-18 14:23
Closing as having a pull request, Please test #35220 (as soon as testing instructions are ready there). Thanks in advance.

**Closed as completed by richard67** 2021-08-18 14:23 UTC
Labels: No Code Attached Yet
