### ISSUE TITLE
[4.0] Users - Tab for Custom Fields is labeled as "Fields"

### ISSUE THREAD

**Issue by pe7er** [joomla/joomla-cms#24793] opened 2019-05-05 09:35 UTC
### Steps to reproduce the issue

1. Create a new Field Group: Users > Field Groups > New
Name: [My User Profile Group]

![fields3](https://user-images.githubusercontent.com/1217850/57191787-a2f7c580-6f29-11e9-8b37-069c4e0fc6bd.png)

2. Create a new Field: Users > Fields > New 
Name: [Photo]

3. Edit User: Users > Manage > Click on a User

### Expected result
I would expect that the Field Group Tab would be labeled as "[My User Profile Group]"

### Actual result
The Field Group Tab is labeled as "Fields"

![fields4](https://user-images.githubusercontent.com/1217850/57191786-a2f7c580-6f29-11e9-9e0e-89c88e3c0930.png)

**Comment by ReLater** [comment] 2019-05-05 12:15
At the moment I can't confirm your find. In your testing instructions I miss the step
- Select the field group "[My User Profile Group]" and save the field.

Did you do that?

Which J4 version are you using?

I will update mine to current nightly version and try again.

**Comment by brianteeman** [comment] 2019-05-05 12:28
I can't confirm this either

**Comment by ReLater** [comment] 2019-05-05 12:32
I still can't reproduce after update to newest nightly
![05-05-_2019_14-31-10](https://user-images.githubusercontent.com/20780646/57194073-992e8c00-6f42-11e9-82e3-5e832b650491.jpg)

**Comment by pe7er** [comment] 2019-05-05 13:53
Thank you for testing @ReLater and @brianteeman !
I had this issue with the current 4.0-dev (synchronized this morning).

When I tried to reproduce this issue again, I found out that I **had NOT assigned** the [Photo] field to the [My User Profile Group] Field Group. So **my Field Group said "None"**.
![users-backend3](https://user-images.githubusercontent.com/1217850/57194963-6938b600-6f4d-11e9-9e27-0438e5bca9f1.png)

IMHO the Tab "Fields" might be confusing. 
Would it appropriate to relabel that tab to "Ungrouped Fields"?

**Comment by brianteeman** [comment] 2019-05-05 13:58
> Would it appropriate to relabel that tab to "Ungrouped Fields"?

Not for me. That would imply that all fields really should be in a group and there really isnt a need for that to be the case

**Comment by ReLater** [comment] 2019-05-05 14:19
@pe7er 

You can create a language override for `JGLOBAL_FIELDS` or if you want to be more component specific you can create **new** language strings via `Languages: Overrides` in the back-end like `COM_USERS_FIELDS_USER_LABEL`, `COM_CONTENT_FIELDS_ARTICLE_LABEL` and so on.

These language strings don't exist yet in Joomla core but are tested here: https://github.com/joomla/joomla-cms/blob/4.0.0-alpha8/administrator/components/com_fields/Helper/FieldsHelper.php#L422-L427 .

Add.: Override for `JGLOBAL_FIELDS` may have conflicts. I wouldn't do that.

**Comment by wilsonge** [comment] 2019-05-06 09:00
I’m going to close this as the original issue can’t be reproduced. In terms of the field groups. If we want to rename the none group (I’m sympathetic to that actually to improve UX) then that should be done against staging not j4

**Closed as completed by wilsonge** 2019-05-06 09:00 UTC
Labels: No Code Attached Yet, J4 Issue
