### ISSUE TITLE
[4.0] Installer warnings not inline

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29621] opened 2020-06-15 08:15 UTC
### Steps to reproduce the issue

install Joomla 4, not meeting the full requirements
view last page

### Expected result

Off/On values to be aligned with their column headers

### Actual result

<img width="715" alt="Screenshot 2020-06-15 at 09 09 58" src="https://user-images.githubusercontent.com/400092/84633681-a6a99a00-aee8-11ea-8642-74cb028df245.png">

### System information (as much as possible)

Safari on Mac

**Comment by chmst** [comment] 2020-06-15 08:46
I cannot reproduce this on firefox, edge and chrome.

<img width="450" alt="install-table" src="https://user-images.githubusercontent.com/1035262/84637243-c2676d00-aef5-11ea-9ef0-c21ed645a4cf.PNG">

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29621">issues.joomla.org/tracker/joomla-cms/29621</a>.</sub>

**Comment by C-Lodder** [comment] 2020-06-15 09:26
I thought this Safari bug was fixed in: https://github.com/joomla/joomla-cms/pull/28921

**Comment by PhilETaylor** [comment] 2020-06-15 09:27
I tested today with Joomla 4.0 beta 1

**Comment by brianteeman** [comment] 2020-06-15 09:43
that fix was only in the admin - this report is the installer

**Comment by brianteeman** [comment] 2020-06-15 10:33
See #29624

**Closed as completed** 2020-06-15 10:39 UTC
Labels: No Code Attached Yet
