### ISSUE TITLE
ACL problem assets table upgrade Joomla 3.7.5

### ISSUE THREAD

**Issue by lorenzopf** [joomla/joomla-cms#17690] opened 2017-08-23 15:32 UTC
Sql dump off the assets table joined

    good before upgrade : only 6 occurences for com_zoo ACL
    Bad after upgrade 1 : 82 occurences found for com_zoo
    bad after upgrade 2 : 84 occurences found for com_zoo when try to modify them via BO

### Expected result

modify Administrator ACL on SYSTEM > CONFIGURATION > ZOO > ACL.

Assets table looks like : 

[wz1mj_assets_good_beforeupgrade.txt](https://issues.joomla.org/uploads/1/dedc35d81e22efe656ab753efb7e2b1e.txt)

### Actual result

Administrator ACL are blocked as "refused" on SYSTEM > CONFIGURATION > ZOO > ACL.

Assets table looks like : 

[wz1mj_assets_broken_after_uprage1.txt](https://issues.joomla.org/uploads/1/13b1d23b5d849103d194fb6b31360886.txt)

### Additional content

I add ASSETS TABLE file before the joomla 3.7.4 upgrade and ASSETS TABLE file after the joomla 3.7.4 upgrade.

After the upgrade :

[wz1mj_assets_broken_after_uprage1.txt](https://issues.joomla.org/uploads/1/13b1d23b5d849103d194fb6b31360886.txt)

Before the upgrade : 

[wz1mj_assets_good_beforeupgrade.txt](https://issues.joomla.org/uploads/1/dedc35d81e22efe656ab753efb7e2b1e.txt)

**Comment by ghost** [comment] 2017-08-23 15:56
have you asked Devs. of com_zoo?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17690">issues.joomla.org/tracker/joomla-cms/17690</a>.</sub>

**Comment by ggppdk** [comment] 2017-08-23 19:30
One of the asset handling changes in J3.7.4+ is that empty assets will not be saved
so actually the asset entries should now be less than before ...

we adjusted our initial asset creation in our component (flexicontent component) to account for this
because we were creating a small number of empty assets ...

about zoo component:
> Administrator ACL are blocked as "refused" on SYSTEM > CONFIGURATION > ZOO > ACL.

the problem is that you have about 20 or 30 of assets for 'com_zoo' component !!!
(i mean of the component itself !, i do not speak of its categories or its fields, etc)

i am not sure how this happened, but once you have 2 assets for a component and you click to save component configuration, then you will get 1 new asset every time (if i remember correctly)

The multiple assets can manifest the behaviour that all non-super user groups (e.g. administrator usergroup) will show as having all permissions refused !

- a solution is delete all these duplicates assets of component

e.g. make full site backup and do execute an SQL query to delete the assets

and then hopefully next time you save component only 1 component asset 
and any further saves will not create any more duplicate component assets 

in any case report to the authors that multiple assets of the component itself are created ...

i do not know who should be responsible for checking for duplicate assets,

but it is good if the component checks ... and account for this case, and deletes all duplicate assets and then creates a single one ...

**Comment by lorenzopf** [comment] 2017-08-25 12:43
thank you for your answer, I will follow your instructions.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17690">issues.joomla.org/tracker/joomla-cms/17690</a>.</sub>

**Comment by ghost** [comment] 2017-08-25 12:53
closed as stated above; it can always reopened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17690">issues.joomla.org/tracker/joomla-cms/17690</a>.</sub>

**Closed as completed by ghost** 2017-08-25 12:53 UTC
Labels: No Code Attached Yet
