### ISSUE TITLE
Own module raises error 500: behavior::modal not found. 

### ISSUE THREAD

**Issue by MGampper** [joomla/joomla-cms#37466] opened 2022-04-03 11:57 UTC
### Steps to reproduce the issue
Entering in admin area an existing own module or trying to create new one raises reproducable this error

### Expected result
Open editor to enter details as in earlier version

### Actual result
above error

### System information (as much as possible)
PHP erstellt für 	Linux sh-79 4.15.0-136-generic #140-Ubuntu SMP Thu Jan 28 05:20:47 UTC 2021 x86_64
Datenbanktyp 	mysql
Datenbankversion 	8.0.26-0ubuntu0.20.04.3
Datenbankzeichensatz 	utf8mb4_0900_ai_ci
Datenbankverbindungszeichensatz 	utf8mb4_0900_ai_ci
Datenbankverbindungsverschlüsselung 	Keine
Datenbankserver unterstützt Verbindungsverschlüsselung 	Nein
PHP-Version 	8.0.13
Webserver 	Apache
PHP-Interface für den Webserver 	cgi-fcgi
Joomla-Version 	Joomla! 4.1.2 Stable [ Kuamini ] 30-March-2022 16:00 GMT
Browsererkennung 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0

**Comment by ReLater** [comment] 2022-04-03 13:56
I can't reproduce this issue.

I don't think that Joomla 4 core is still using `behavior.modal` somewhere.

@MGampper Please activate "Debug" in Joomla's configuration and set "Error Reporting" to "Maximum". Then try again. Post the backtrace output (a longer list) here. Maybe it's a "stupid" plugin or so that is responsible for the error.

**Comment by MGampper** [comment] 2022-04-03 16:11
Dear Joomla Team,

As it later throws same error with other attempts where a editor is opened I found that a extension was still active which adds a button for famous Phoca Gallery. The Gallery is meanwhile compatible but it seams the button still not.
Freundliche Grüße 
Marcus Gampper

Am 3. April 2022 13:56:27 UTC schrieb ReLater ***@***.***>:
>I can't reproduce this issue.
>
***@***.*** Please activate "Debug" in Joomla's configuration and set "Error Reporting" to "Maximum". Post the backtrace output (a longer list) here. Maybe it's a "stupid" plugin or so that is responsible for the error.

**Comment by ReLater** [comment] 2022-04-03 16:30
Thanks for reporting back. Could you please close your issue because it's not a Joomla core issue.

**Comment by chmst** [comment] 2022-04-03 16:33
As @ReLater says - I close this and ping  @PhocaCz

**Closed as completed by chmst** 2022-04-03 16:33 UTC
Labels: No Code Attached Yet

**Comment by MGampper** [comment] 2022-04-03 16:35
Thanks for closing

**Comment by PhocaCz** [comment] 2022-04-04 10:10
Hi, thank you for the info, yes, Phoca Gallery plugin and Phoca Gallery Button plugin are not ready for Joomla 4. For now, if Phoca Gallery images should be displayed in content, then Phoca Photo plugin can be used in Joomla 4 (there is no need to have button plugin as the plugin code is simple), see demo:

https://www.phoca.cz/demo/phoca-photo-plugin-demo

More info:
https://www.phoca.cz/phocaphoto
https://www.phoca.cz/phoca-photo-content-plugin


Jan
