### ISSUE TITLE
[4.0][Cassiopea] Wrong ItemId: Call to a member function getParams() on null

### ISSUE THREAD

**Issue by bato3** [joomla/joomla-cms#30812] opened 2020-09-30 10:05 UTC
### Steps to reproduce the issue
Go to article (without mod_rewrite) with wrong `itemid`
/index.php?option=com_content&view=article&id=187&Itemid=64

### Expected result
HTTP 200 / 404

### Actual result
HTTP 500
0 Call to a member function getParams() on null 

### Additional comments

From stack is [line 29](https://github.com/joomla/joomla-cms/blob/4.0-dev/templates/cassiopeia/index.php#L29)  in `template/cassiopea/index.php`
```php
$pageclass = $menu->getParams()->get('pageclass_sfx');
```

My quick fix:
```php
$pageclass = empty($menu)?'':$menu->getParams()->get('pageclass_sfx');
```
is not working completely correctly because the breadcrumbs are not working properly (shows the home page)

**Comment by richard67** [comment] 2020-09-30 17:20
I can't reprodue that here on a clean, current 4.0-dev with blog sample data, SEF URLS=off, no URL rewriting. And I know at least one other contributor who can't reproduce.

Could you provide some more information about your configuration regarding SEO options in Global Configuration, and if you have an .htaccess file and so on.

How does it normally work for you when having a 404? Do you see the template's error.php, or do you see the server's generic error page? Or have you set up custom error pages?

The more relevant information we get, the better we can reproduce it.

**Comment by richard67** [comment] 2020-09-30 17:22
Information required as stated in my previous comment.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30812">issues.joomla.org/tracker/joomla-cms/30812</a>.</sub>

**Comment by chmst** [comment] 2020-09-30 17:24
In general, a Joomla site has as at least one menuItem and no matter where you are there is always an active menuItem. Can you describe in detail how you got this error?

**Comment by bato3** [comment] 2020-10-01 13:31
This is probably some sort of bug due to migration issues. I am happy to prepare database dumps to illustrate the problem.

After migration, I have a few problems:
- Where it does not detect that the specified ItemId does not exist
- Index with `com_finder` returns red` null` or "Data too long for column 'route' at row 1"
- Does not process internal links in the content of articles and modules. https://github.com/joomla/joomla-cms/issues/30818
- I did not disable old extensions (e.g. `com_search`) https://github.com/joomla/joomla-cms/issues/30843

**Comment by sakiss** [comment] 2020-10-15 14:15
I confirm that.
It can also happen if you try to access an article without a sef url.
E.g. /index.php/component/content/article/70-quick-icons

**Comment by Quy** [comment] 2020-10-15 14:56
Please test PR #31100

**Comment by richard67** [comment] 2020-10-17 10:13
Re-opening the issue because the pull request #31100 has been closed. We can close the issue again as soon as there is a new pull-request.

**Comment by richard67** [comment] 2020-10-19 10:54
New pull request is #31156 . Please test. Thanks in advance.

**Closed as completed by richard67** 2020-10-19 10:54 UTC
Labels: No Code Attached Yet, Information Required, Frontend Template
