### ISSUE TITLE
4.2.2 User Require Password reset doesn't work

### ISSUE THREAD

**Issue by morefriendm** [joomla/joomla-cms#38788] opened 2022-09-20 12:33 UTC
1. Please login to https://discvrmas.periopmedicine.org.au
2. login with user: testuser password: 12345678
3. I have already enabled "Require Password Reset" for the above user. 

### Expected result
The user profile page should be loaded to change the user's password

### Actual result
Page redirect logged in home page rather than user profile to change the password

### System information (as much as possible)
J4.2.2
PHP  8.0.23 
Default Joomla template

**Comment by nikosdion** [comment] 2022-09-21 09:09
On it. I think I know where the problem lies.

**Comment by nikosdion** [comment] 2022-09-21 09:24
Looking at how the require password reset works I will say that we MUST check for Multi-factor Authentication before allowing the user to change their password.

Joomla does not use the password reset flow for resetting a password in this case, it gives full and unrestricted(!) access to the user profile edit page. This means that anyone who knows the user's old password can log into the site, see the user's personally identifiable information and even disable, change or add Multi-factor Authentication and WebAuthn Passwordless Authentication methods. That is to say, they can do **a complete account takeover**.

We use the Requires Password Reset feature when we provide a user with a temporary password which is transmitted over insecure transports (e.g. email, phone, ...) or when we suspect the user's password is compromised. If by doing so we also disable the MFA protection of that user's account we are exposing them to danger!

If there is a legitimate use case where the user has forgotten their password, they don't have access to their MFA Method **and** we need to convey a temporary password over an insecure transport the correct process would be this:
* Super User goes into the user's account, Multi-factor Authentication tab and disables MFA with the handy Turn Off button.
* The Super User then goes to the first tab, enters a temporary password and sets Requires Password Reset to Yes, then clicks on Save & Close.
* The Super User contacts the user with the temporary password.

As a result I would close this as Won't Fix because the problem is not with MFA but the way Requires Password Reset is implemented. This feature needs to deny the user access to the site, instead redirecting them to the Forgot Your Password page with a message that they are required to go through the password reset process. For that, I'd recommend opening a different issue.

**Comment by morefriendm** [comment] 2022-09-22 08:39
Thanks @nikosdion.
We are using the "Require password reset" feature, so that when users first login, they need to setup their password and profile details if needed.
At the moment, even if all MFA is disabled, it's not redirecting to the profile edit page.

**Comment by ahvink** [comment] 2022-12-08 15:44
What's the status on this at the moment ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38788">issues.joomla.org/tracker/joomla-cms/38788</a>.</sub>

**Comment by Mika17420** [comment] 2023-01-31 16:18
Why this bug is on removed label ?
The problem persists
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38788">issues.joomla.org/tracker/joomla-cms/38788</a>.</sub>

**Comment by nikosdion** [comment] 2023-01-31 16:36
@Mika17420 Read my comment from September: https://github.com/joomla/joomla-cms/issues/38788#issuecomment-1253440628

The original poster did open a new issue (https://github.com/joomla/joomla-cms/issues/38806) so someone would fix the way Requires Password Reset works… but it was closed as a duplicate of this issue, even though the body of the issue clearly referenced this issue (therefore my comment).

I would recommend someone opening a ticket with the title "Requires Password Reset does not work with users who have MFA enabled" and the content "The Requires Password Reset feature needs to deny login to the site and ask the user to go through the password reset (instead of trying to redirect them to the password reset page) when MFA is enabled for this user. For the reasoning see https://github.com/joomla/joomla-cms/issues/38788#issuecomment-1253440628".

Then, and only then, someone might actually take the 2 minutes it needs to understand the issue and the 10 minutes it takes to fix it…

**Comment by coolcat-creations** [comment] 2023-02-20 11:53
I experienced the same bug in backend. When Password reset is set to yes and the user is using 2FA he is caught in a redirect loop.

**Comment by nikosdion** [comment] 2023-02-20 11:57
@joomla/joomla-experience-team-jxt I believe this qualifies as a UX issue. Please see my [comment](https://github.com/joomla/joomla-cms/issues/38788#issuecomment-1253440628) from five months ago — read the last paragraph for the proposed solution.

**Comment by coolcat-creations** [comment] 2023-02-20 12:06
I hope I did not misunderstood you, I created the issue like suggested. Thank you

**Comment by KeesZNL** [comment] 2023-07-06 13:51
Having just upgraded from 3.10.11 to 4.3.2 I am experiencing the same problem. The user who is required to enter a new password must first click on the welcome page before the form appears where the password can be changed. This issue talks about MFA users. That is not applied in my site.
I am new on github referred by NL Joomla Forum. Where is the best place to report this issue?
Does anyone know an interim solution, because it is impossible to explain to 60 users that member information is visible before the mandatory changed password has been entered.

sorry for my bad English

**Comment by pl71** [comment] 2024-03-21 11:46
Joomla 5.
Brand new test site with test data on Xampp for Windows.
Created new user with Password Reset Required.
Users can log in without a password reset.
In the backend:
![mfa](https://github.com/joomla/joomla-cms/assets/4776779/82fe2802-6565-4114-9b4b-f405238da43f)

**Comment by carrieredaniel** [comment] 2024-09-09 20:40
Joomla 5, freshly installed two weeks ago:
When a user is asked to reset it's password the "change password" question is not shown.

Behaviour shown: Password change is enforced when trying to log OUT.
Expected behaviour: Password change is required shortly after logging in<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38788">issues.joomla.org/tracker/joomla-cms/38788</a>.</sub>

**Comment by Hackwar** [comment] 2024-12-03 07:55
I've created a PR to fix this: #44521 Please test. Since we have a PR, I'm closing this one.

**Closed as completed by Hackwar** 2024-12-03 07:55 UTC
Labels: No Code Attached Yet, bug
