### ISSUE TITLE
add language switch in menu

### ISSUE THREAD

**Issue by Laurent-Cosmic** [joomla/joomla-cms#44665] opened 2024-12-24 15:07 UTC
### Is your feature request related to a problem? Please describe.
I'm doing a lot of website in different language and most of them are simply using 2 language (French and English).  To add switch, I'm oblige to add a new position in my template.  This is easy on a PC but less good-looking on a mobile.

### Describe the solution you'd like
I would like to add language switch in the menu - it could be either the letter, the flag or the drop list.

### Additional context
Joomla! in multiple language is working so fine and is for me one of our best assets against WP that it could be great to have this function more userfriendly than it is (even if it's already a great tool)

**Comment by brianteeman** [comment] 2024-12-24 15:45
You may use an External URL menu item with the correct full url in each lang menu (http: //mysite.com/en/ or /fr/ etc.)
But this would not deal with associations and only redirect you to the home pages for a language.

**Comment by Laurent-Cosmic** [comment] 2024-12-24 18:35
Indeed, I want to have association not only the home page...  having the home page is OK when you have a couple of articles but I have around 2500.  that's why I'm talking about the switcher

**Comment by brianteeman** [comment] 2024-12-24 20:23
It is not going to be possible. The menu is a collection of links whereas the language switcher contains a lot of logic.

When I searched to see if others had asked the same question they all placed the language switcher in the same position as the menu

**Comment by Laurent-Cosmic** [comment] 2024-12-24 21:16
even if we ask Santa Claus :D 
some menu extension (for instance, if I'm not wrong) as https://extensions.joomla.org/extension/dj-megamenu/ let us include module so I was thinking "why not?"
but I'm not developer so I can be wrong

**Comment by Laurent-Cosmic** [comment] 2024-12-24 21:20
thanks anyway

**Comment by brianteeman** [comment] 2024-12-24 21:39
That is just putting a module inside the menu - not adding language switvher to the menu

**Comment by chmst** [comment] 2024-12-25 08:39
Closing this as it is not a bug in Joomla.

**Closed as completed by chmst** 2024-12-25 08:39 UTC
Labels: No Code Attached Yet
