### ISSUE TITLE
[com_fields]  not display in com_contact form

### ISSUE THREAD

**Issue by ymages** [joomla/joomla-cms#12673] opened 2016-11-01 08:44 UTC
### Steps to reproduce the issue
create a  com_contact named Contact  ,  category  Forms
create a custom field (radio :  Sex->M/F)  for com_contact form,   category Forms 

in Contact settings:
tab Display  -> Show User Custom Fields -> All  (category Forms is not in the list)
tab Fields -> sex displayed  as label only <label id="jform_params_contact_sex-lbl" for="jform_params_contact_sex" class="">Sex</label>

### Expected result
custom field Sex should be displayed in frontend contact form

### Actual result
not displayed

### System information (as much as possible)
php 5.6
on localhost AMPPS

### Additional comments
question for @laoneo https://github.com/joomla/joomla-cms/pull/11833#issuecomment-257508991

**Comment by laoneo** [comment] 2016-11-01 09:01
Did you switch to contact form context **Mail**?
![image](https://cloud.githubusercontent.com/assets/251072/19884461/21d82336-a01a-11e6-81a3-4c5481d636af.png)

**Comment by ymages** [comment] 2016-11-01 09:14
No  look at my screenshots

![fields](https://cloud.githubusercontent.com/assets/5959946/19884853/f8647d5e-a01b-11e6-81f1-8557db882b28.png)
![contact](https://cloud.githubusercontent.com/assets/5959946/19884855/f8a3485e-a01b-11e6-89b8-05dbdce7dc59.png)
![contact-frontend](https://cloud.githubusercontent.com/assets/5959946/19884856/f8a49b5a-a01b-11e6-975e-4e364c419a7c.png)

**Comment by ymages** [comment] 2016-11-01 09:16
![fiels-values](https://cloud.githubusercontent.com/assets/5959946/19884939/4d50cc64-a01c-11e6-8b67-71fd61815642.png)
![field-edit](https://cloud.githubusercontent.com/assets/5959946/19884940/4d7d446a-a01c-11e6-8a7c-c2745f80da23.png)

**Comment by laoneo** [comment] 2016-11-01 09:25
You need to set them for the context Mail, otherwise they will appear on contacts.

**Comment by ymages** [comment] 2016-11-01 09:29
I cannot switch from contact to mail , and if I select mail I cannot create a custom field
no idea how to do it

**Comment by laoneo** [comment] 2016-11-01 09:36
In the list where the fields are displayed (as shown in my screenshot of the first comment) select mail. Then hit the new button and create your field.

**Comment by ymages** [comment] 2016-11-01 09:47
ok got it ! , the field is displayed but not as radio buttons
![screenshot 2016-11-01 a 10 46 41](https://cloud.githubusercontent.com/assets/5959946/19885760/9f558924-a020-11e6-8429-a92768465f2b.png)

**Comment by ymages** [comment] 2016-11-01 09:59
added another field -> Job (text)
it's displayed but disabled  and disabled = no in the settings

```
<div class="controls"><input type="text" name="jform[params][mail-field-job]" id="jform_params_mail_field_job" value="" disabled="">
</div>
```

**Comment by ymages** [comment] 2016-11-01 10:02
And now the tab Fields is not displayed anymore

![screenshot 2016-11-01 a 11 01 46](https://cloud.githubusercontent.com/assets/5959946/19886229/a24db7da-a022-11e6-9bcf-ff6073dab770.png)

**Comment by laoneo** [comment] 2016-11-01 13:46
This fields do belong to the front end form. You will see the fields on the contact form on the front end.

**Comment by ymages** [comment] 2016-11-01 15:05
no they are not on the frontend form
the text field is disabled and the radio buttons are not displayed

**Comment by ymages** [comment] 2016-11-01 15:09
text field disabled
radio button not displayed

![screenshot 2016-11-01 a 16 08 59](https://cloud.githubusercontent.com/assets/5959946/19894499/89d3197c-a04d-11e6-92c1-27f4d9b55371.png)

**Comment by laoneo** [comment] 2016-11-01 16:04
You need to set the edit value permission for the public group to allowed.

**Comment by ymages** [comment] 2016-11-01 16:27
how  to do that ?
in User Groups  I cannot find it or what to do exactly

in the field itself >  Permissions  > create , delete , edit 
I have tried  Edit > Allowed , but nothing change

**Comment by laoneo** [comment] 2016-11-02 07:51
I was talking about the "Edit Value" permission
![image](https://cloud.githubusercontent.com/assets/251072/19920533/90d13114-a0d9-11e6-9ffb-b5fc5ec5a8ea.png)

**Comment by ymages** [comment] 2016-11-02 07:56
ok  now it works for textarea but not for radio buttons, they are not displayed

`<div class="controls"><fieldset id="jform_params_field_mail_sex" class="radio"></fieldset></div>`

**Comment by infograf768** [comment] 2016-11-02 09:42
Concerning permissions, see https://github.com/joomla/joomla-cms/issues/12693

**Comment by ymages** [comment] 2016-11-02 10:00
@infograf768 I have set the permissions but button radio are not displayed

**Comment by infograf768** [comment] 2016-11-02 10:05
I meant that permissions are flawed imho in com_fields. They are unsufficient at best.

**Comment by laoneo** [comment] 2016-11-02 10:08
@infograf768 please discus the sense of the new permission in #12693 and not here. The problem is that the checkbox is not shown properly.

**Comment by ymages** [comment] 2016-11-02 10:09
@laoneo I did something wrong with radio buttons or do you get the same result than me ?

thanks a lot for your work and I keep on trying all :-)

**Comment by laoneo** [comment] 2016-11-02 13:07
Yes, also on the back end. I try to fix it...

**Comment by laoneo** [comment] 2016-11-02 13:21
Glad to hear that the rest is working. Please test #12698 which should fix the display issue for radio buttons and checkboxes.

**Comment by ymages** [comment] 2016-11-02 15:07
Not sure if I did it right
libraries/joomla/form/parameters/radio.xml
<fieldset hidden="true" name="list_templates_modal" repeat="true">
					<field
						name="name"
						label="JLIB_FORM_FIELD_PARAM_RADIO_MULTIPLE_VALUES_KEY_LABEL"
						size="30"
						type="text"
					/>

					<field
						name="value"
						label="JLIB_FORM_FIELD_PARAM_RADIO_MULTIPLE_VALUES_VALUE_LABEL"
						size="30"
						type="text"
					/>
				</fieldset>

**Comment by laoneo** [comment] 2016-11-03 07:16
You need to save the values again when you edit the radio field.

**Comment by ymages** [comment] 2016-11-05 14:35
I saved the values again
![options-cf](https://cloud.githubusercontent.com/assets/5959946/20030812/d07da74e-a36c-11e6-8219-e2dd102049a7.png)
but what I get is wrong 
![form-cf](https://cloud.githubusercontent.com/assets/5959946/20030814/dc536856-a36c-11e6-8d59-a3be6f4a72f6.png)

the displayed code
```
<fieldset id="jform_params_field_mail_sex" class="radio">
<input type="radio" id="jform_params_field_mail_sex0" name="jform[params][field-mail-sex]" value="M">
<label for="jform_params_field_mail_sex0">1</label>
<input type="radio" id="jform_params_field_mail_sex1" name="jform[params][field-mail-sex]" value="F">
<label for="jform_params_field_mail_sex1">F</label>
</fieldset>
```

it should be
```
<input type="radio" id="jform_params_field_mail_sex1" name="jform[params][field-mail-sex]" value="1">
<label for="jform_params_field_mail_sex1">M</label>
<input type="radio" id="jform_params_field_mail_sex0" name="jform[params][field-mail-sex]" value="0">
<label for="jform_params_field_mail_sex0">F</label>
```

in the admin panel there is no fields tab anymore
![admin-missing-tab](https://cloud.githubusercontent.com/assets/5959946/20030845/6302704a-a36d-11e6-9143-3b327ede140f.png)
this fiels tab exists in com_content

**Comment by ymages** [comment] 2016-11-05 14:50
if I  submit the contact form I get that email

```
This is an enquiry email via http://192.168.178.20/j37/ from:
My Name<my@email>

contenu de mon message

<br />
<b>Notice</b>:  Undefined property: stdClass::$render_class in <b>/www/j37/components/com_contact/layouts/field/render.php</b> on line <b>19</b><br />
Sex: F
<br />
<b>Notice</b>:  Undefined property: stdClass::$render_class in <b>/www/j37/components/com_contact/layouts/field/render.php</b> on line <b>19</b><br />
Job: photographe
```

_job: photographe_   is  the custom field type= text (it works)

**Comment by laoneo** [comment] 2016-11-07 09:10
The render notice should be solved with the merge of PR #12729.

The key value confusion is discussed here #12739. You need to flip the values and keys in the list definition.

**Comment by laoneo** [comment] 2016-11-14 12:18
Can you please test it with the most actual code from staging as most of the issues you experience should be solved now. Thanks.

**Comment by ymages** [comment] 2016-11-14 12:39
I never know what to download and install exactly, is there a very las version of joomla with your code ?

thank you

**Comment by laoneo** [comment] 2016-11-14 12:49
You can download the latest builds from here https://developer.joomla.org/nightly-builds.html.

**Comment by ymages** [comment] 2016-11-17 09:05
I get the email

```
This is an enquiry email via http://192.168.178.20/j37/ from:
NAME <myname@gmail.com>

MESSAGE

<dl class="fields-container article-info muted"></dl>
```

with _<dl class="fields-container article-info muted"></dl>_  instead of the radio value

**Comment by ymages** [comment] 2016-11-17 09:26
If I create a field group _my-fields_   it is  not displayed  in the box Field Group Type or select a group , even by typing

**Comment by ymages** [comment] 2016-11-22 15:30
any news ? :-)

**Comment by laoneo** [comment] 2016-11-24 08:20
I need to test that, sorry for the late response, but I was occupied with some other things.

**Comment by ymages** [comment] 2016-11-24 08:22
no problem ... I wasn't sure if you had seen my replies, thanks for your work

**Comment by laoneo** [comment] 2016-11-26 14:26
I'v just tested it with the latest code from staging and it worked. Here is a screenshot about my form
![image](https://cloud.githubusercontent.com/assets/251072/20640909/6d3f782a-b3ec-11e6-84a3-976466c06e36.png)

And here the raw output which will be sent by mail

```
This is an enquiry email via http://joomla.box/cms/ from:
Test <test@test.com>

Demo

Dep: Accounting, Development

```

So I suggest that you are doing a new installation of the most actual Joomla code and then redo the test again.

**Comment by laoneo** [comment] 2016-12-14 07:43
Can we close this one?

**Comment by laoneo** [comment] 2017-01-26 08:01
I guess we can close this one as, as I and other have been testing contacts extensively in the last weeks.

**Comment by Bakual** [comment] 2017-01-26 08:38
Closing as there was no response.

**Closed by Bakual** 2017-01-26 08:38 UTC
Labels: No Code Attached Yet

**Comment by ymages** [comment] 2017-05-01 15:10
the new  fields are disabled

**Comment by brianteeman** [comment] 2017-05-01 15:11
Check the permissions for the field!

**Comment by ymages** [comment] 2017-05-01 15:14
Thanks but what should be the permissions ?  that it works as expected for everybody

**Comment by ymages** [comment] 2017-05-01 17:32
ok now it works but if I get the email the custom field is displayed in that way

```
<div class="field-container" data-alias="">
<span class="field-label">telefon: </span>
<span class="field-value">0</span>
</div>
`

how can I customize the email ?

thank you

**Comment by laoneo** [comment] 2017-05-01 17:36
That doesn't really makes sense. Can you open please a new issue which describes the problem and what do you expect for the fields? Thanks.

**Comment by ymages** [comment] 2017-05-01 17:38
I  have really no idea how works Github and where to open a new issue

**Comment by brianteeman** [comment] 2017-05-01 17:38
Goto https://issues.joomla.org

**Comment by ymages** [comment] 2017-05-01 17:40
thanks

**Comment by ymages** [comment] 2017-05-04 11:37
Warning: SimpleXMLElement::__construct(): Entity: line 2: parser error : Entity 'auml' not defined in /libraries/joomla/form/form.php on line 728

Warning: SimpleXMLElement::__construct(): <option value="Zahnarzt">Zahnarzt</option><option value="Zahnärztin">Zahn&auml; in /libraries/joomla/form/form.php on line 728

Warning: SimpleXMLElement::__construct(): ^ in /libraries/joomla/form/form.php on line 728

**Comment by laoneo** [comment] 2017-05-04 14:33
Please open a new issue with the steps to reproduce your error. Make sure you are using the 3.7 final version. Thanks.

**Comment by ymages** [comment] 2017-05-04 14:54
I am using the 3.7 final version 
if you write a char like ä or a letter with  any accent on custom field type list you get that error

line 728 = $data = new SimpleXMLElement($data);

**Comment by franz-wohlkoenig** [comment] 2017-05-04 15:03
@ymages Please open a new issue with the steps to reproduce your error as @laoneo wrote, thanks.

**Comment by laoneo** [comment] 2017-05-04 16:35
Can somebody lock that issue please?

**Comment by brianteeman** [comment] 2017-05-04 16:41
locked as requested
