### ISSUE TITLE
Search Tools moved under toolbar

### ISSUE THREAD

**Issue by teccrow** [joomla/joomla-cms#8190] opened 2015-10-28 18:52 UTC
#### Steps to reproduce the issue
With Safari 9.0.2, it sometimes happens that the search tools are displayed hidden behind the toolbar. If you move the mouse over the toolbar, the search tools is scrolled down to where it was supposed to be. Good produce can be the problem when the "Reset" button pressed for a selected filter. With Chrome, there is not this behavior.

#### Expected result
![screen shot 2015-10-28 at 13 46 02](http://issues.joomla.org/uploads/1/ff6ad409c042568c501b7a0a4c95927f.png)

#### Actual result
![screen shot 2015-10-28 at 13 45 34](http://issues.joomla.org/uploads/1/bbf186f700fd9d145d42b28f6cf7dc4a.png)

#### System information (as much as possible)
MAC OS X 10.11.2

#### Additional comments

**Comment by brianteeman** [comment] 2016-01-28 11:34
I see a bounce that i never see with chrome but it always seems to bounce to the correct place<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8190">issues.joomla.org/joomla-cms/8190</a>.</sub>

**Comment by teccrow** [comment] 2016-01-28 13:29
The problem still exists with Joomla 3.4.8 and Safari 9.1 and Mac OS X 10.11.3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8190">issues.joomla.org/joomla-cms/8190</a>.</sub>

**Comment by dcsjapan** [comment] 2016-03-30 01:54
Using Joomla 3.5.0 ... this glitch affects not only the search field; all controls in that row overlap the row above:

![screen shot 2016-03-29 at 20 50 38](https://issues.joomla.org/uploads/1/63cee34d56c3e22ceac5ce4d57f4ca12.png)

Moving the pointer toward the top of the window causes them to drop down to the correct position.

It's a minor display glitch, but gets irritating after a while. Safari 9.1 on OS X 10.10.5. (It doesn't occur with Firefox either.)

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8190">issues.joomla.org/joomla-cms/8190</a>.</sub>

**Comment by dgt41** [comment] 2016-03-30 02:07
This has been fixed in 3.5. Make sure that you empty your browser's cache

**Comment by dcsjapan** [comment] 2016-03-30 04:36
Thank you @dgt41 ... clearing the browser cache did the trick.

I thought I had seen the issue even after clearing the cache ... but I have a couple of pre-3.5 installations that I'm using to check out templates on the same box. It must have been cached data from those that was causing the problem.

**Comment by infograf768** [comment] 2016-03-31 08:19
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8190">issues.joomla.org/joomla-cms/8190</a>

**Comment by infograf768** [comment] 2016-03-31 08:19
Closed as not a bug.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8190">issues.joomla.org/joomla-cms/8190</a>.</sub>

**Closed by infograf768** 2016-03-31 08:19 UTC
Labels: No Code Attached Yet
