### ISSUE TITLE
[4.0] Deleting Usergroups destroys view

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#28522] opened 2020-03-31 09:24 UTC
### Steps to reproduce the issue
Go to usergroups.
Mark a group which has at least one subgroup, for example editor.
Delete it.

### Expected result
The group is deleted,
The screen is reloaded and is complete, as usual.

### Actual result
The group is deleted, but toolbar, modules on top and navigation are empty. It seems that there no modules are rendered.  

![screen shot 2020-03-31 at 08 49 09](https://issues.joomla.org/uploads/1/8ec387662e4c7d7dd7e60a25b7f76478.jpg)

**Comment by brianteeman** [comment] 2020-03-31 12:36
I can not replicate this

**Comment by ReLater** [comment] 2020-03-31 13:46
Neither do I. J4 nightly.

**Comment by astridx** [comment] 2020-03-31 21:29
I can't replicate that either. I have created a group with two subgroups. I was able to delete them. Then I deleted the group editor because you gave this as an example. That was OK too.
Maybe you can narrow the error down?

![Users  Groups   test   Administration](https://user-images.githubusercontent.com/9974686/78076503-dabff500-73a6-11ea-965a-451e9f053763.png)
![Users  Groups   test   Administration(1)](https://user-images.githubusercontent.com/9974686/78076504-db588b80-73a6-11ea-8bf6-e07c408c77fd.png)

**Comment by chmst** [comment] 2020-03-31 21:42
Strange, I had it permanently with several fresh installations. Can you re-try deleting several groups (with child groups)  at the same time?  I just deletd one group and it was comme il faut. Then I deleted two groups at the same time and the issue was as described.

**Comment by astridx** [comment] 2020-03-31 22:02
I tested this and everything, including the toolbar and the sidebar, was OK.

You're still experiencing the problem. What group names do you use? Maybe there is something irrelevant.

![Users  Groups   test   Administration(2)](https://user-images.githubusercontent.com/9974686/78079219-f5489d00-73ab-11ea-9fa0-fa581ea2d386.png)

**Comment by ReLater** [comment] 2020-03-31 22:11
Can't reproduce but I didn't use a fresh installation.

but I think I found another issue????

1) Deleted 1 group "Publisher". OK. Message OK.

![31-03-_2020_23-58-38](https://user-images.githubusercontent.com/20780646/78079337-33de5780-73ac-11ea-98c4-6178e0ce0ee6.jpg)

2) Then I tried to delete several groups in one go and checked them all. See image:

![31-03-_2020_23-56-25](https://user-images.githubusercontent.com/20780646/78079384-4b1d4500-73ac-11ea-9bd9-5e28f66f1895.jpg)

**No message(!) and several groups left:**

![01-04-_2020_00-06-59](https://user-images.githubusercontent.com/20780646/78079674-ddbde400-73ac-11ea-897c-19530cae12dd.jpg)

**Comment by chmst** [comment] 2020-04-05 09:10
After several new installations, I cannot reproduce the issue. Also deleting several groups works fine now. 
@ReLater I could not reproduce your issue. PCould you open a new issue for that? 
Then I colud close this one.

**Comment by ReLater** [comment] 2020-04-05 13:19
Ah, close please. Not that important for me.

**Comment by jwaisner** [comment] 2020-04-07 16:53
Closing as this is not reproducible.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28522">issues.joomla.org/tracker/joomla-cms/28522</a>.</sub>

**Comment by jwaisner** [comment] 2020-04-13 21:55
Confirmed on latest build. System info below:

PHP - 7.4.4
Database - MSQL 5.7.26
OS - Windows 10
Error Reporting - Maximum (no errors shown)

This was done with a complete wipe of all local data and SQL database.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28522">issues.joomla.org/tracker/joomla-cms/28522</a>.</sub>

**Comment by astridx** [comment] 2020-04-13 21:59
My System Information for the tests last week
=============
php: Linux astrid-TravelMate-5760G 4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64
dbserver: mysql
dbversion: 5.7.29-0ubuntu0.18.04.1
dbcollation: utf8mb4_unicode_ci
dbconnectioncollation: utf8mb4_general_ci
dbconnectionencryption: 
dbconnencryptsupported: true
phpversion: 7.2.29-1+ubuntu18.04.1+deb.sury.org+1
server: Apache/2.4.29 (Ubuntu)

**Comment by richard67** [comment] 2020-04-13 22:13
I just could reproduce the issue by deleting the "Manager" user group (which deleted the administrator group too, because it's a child) on a fresh installed 4.0-dev without any sample data.

I don't know if it is related, but I noticed that the `lft`and `rgt`values in the user group table in database are not adjusted then the user group is deleted, see following 2 screenshots before and after.

Before:
![j4_usergroup-delete-manager_table-before](https://user-images.githubusercontent.com/7413183/79165822-385f3300-7de4-11ea-8772-03ce1a462a8e.png)

After:
![j4_usergroup-delete-manager_table-after](https://user-images.githubusercontent.com/7413183/79165834-3d23e700-7de4-11ea-93e7-9833f24b9692.png)

Patching the `lft`and `rgt`values in the database to the correct values doesn't help, the navigation menu, toolbar and so on is still disappeared.

Patched:
![j4_usergroup-delete-manager_table-patched](https://user-images.githubusercontent.com/7413183/79166049-af94c700-7de4-11ea-825b-e35d7eb3f446.png)

![j4_usergroup-delete-manager_view-after](https://user-images.githubusercontent.com/7413183/79166073-b91e2f00-7de4-11ea-8252-1230fb8e8548.png)

**Comment by richard67** [comment] 2020-04-13 22:18
@ReLater Your finding above [https://github.com/joomla/joomla-cms/issues/28522#issuecomment-606904172](https://github.com/joomla/joomla-cms/issues/28522#issuecomment-606904172) could be caused by what I found in my previous comment.

**Comment by richard67** [comment] 2020-04-13 22:21
Btw. I saw nothing in PHP error log or database server log.

**Comment by richard67** [comment] 2020-04-14 17:18
The issue I've found and mentioned in my comment above about `lft` and `rgt` values not being recalculated in the usergroups table is not related to this issue here and vice versa. My issue already exists in staging and 3.9.16. PR for my issue is #28684 .

**Comment by SharkyKZ** [comment] 2020-04-15 08:29
Please test PR https://github.com/joomla/joomla-cms/pull/28687.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28522">issues.joomla.org/tracker/joomla-cms/28522</a>.</sub>

**Closed as completed by SharkyKZ** 2020-04-15 08:29 UTC
Labels: No Code Attached Yet
