### ISSUE TITLE
[4.0] Editor HTML View doesn't save the changes

### ISSUE THREAD

**Issue by AndySDH** [joomla/joomla-cms#29308] opened 2020-05-31 10:53 UTC
When you go to the html view in the editor (toggle editor), and then save, it doesn't save the changes.

### Steps to reproduce the issue

- Write some text in normal Editor Mode
- Save, it will save fine
- Switch to code mode with "Toggle Editor"
- Change / add text
- Save

### Expected result

- The changes are saved.

### Actual result

- The changes are not saved.

### System information (as much as possible)

Joomla 4.0 Beta

**Comment by brianteeman** [comment] 2020-05-31 10:54
Duplicate of #26579

**Closed as completed** 2020-05-31 11:07 UTC
Labels: No Code Attached Yet
