### ISSUE TITLE
Better SEO options in edit articles

### ISSUE THREAD

**Issue by JoomlaFan** [joomla/joomla-cms#15833] opened 2017-05-05 11:22 UTC
I think this may improve the SEO option, grouped in one tab.

![screen shot 2017-05-05 at 11 20 34](https://issues.joomla.org/uploads/1/ba939b87f14827f9a64bf859ebc9b87c.png)

**Comment by tomekomel** [comment] 2017-05-05 11:29
Nice improvement!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15833">issues.joomla.org/tracker/joomla-cms/15833</a>.</sub>

**Comment by brianteeman** [comment] 2017-05-05 16:56
I dont personally see the benefit of moving these options from the publishing tab to a dedicated tab - but if you do then feel free to submit a PR to make this change. Note that for consistency you would need to make the same change in all the core components. Also you should ensure that the option to hide the publishing tab still works etc

**Comment by dgt41** [comment] 2017-05-05 17:12
8 tabs that someone needs to go through to publish an article? Really?
We are doing it wrong!

**Comment by bertmert** [comment] 2017-05-05 20:23
Why ist this when or where "SEO"???

- Author
- Content Rights
- Browser Page Title
...

I think this should not go into core. It's easy to handle things like this with a short custom plugin.

**Comment by brianteeman** [comment] 2017-05-05 20:46
@bertmert this is just moving items from the publishing tab to their own tab

**Comment by bertmert** [comment] 2017-05-06 11:48
@brianteeman 

> this is just moving items from the publishing tab to their own tab

Yes, I know. But these options are not all "SEO" or not only "SEO" or maybe sometimes "SEO". The tabulator label is misleading nonsense.

**Comment by JoomlaFan** [comment] 2017-05-07 21:05
These options are now scattered. For example, see where in Joomla 3.7 was added override the article title meta - in the article parameters tab - at the bottom. It is really difficult to find in the article options. If this is not improved, the opinion about SEO in Joomla will still be bad.

Meta title, description, keywords and robots should be together. Not necessarily on one card. But a separate tab is in my opinion the best one.

Sorry for my english ;-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15833">issues.joomla.org/tracker/joomla-cms/15833</a>.</sub>

**Comment by photodude** [comment] 2017-05-14 23:17
I'm not for moving it to a new tab, but not against grouping as an "SEO" section  under the existing publishing tab.

**Comment by Quy** [comment] 2017-05-16 03:32
Similar to #12043

**Comment by brianteeman** [comment] 2018-08-18 16:54
I know that this is really just about moving things around but at this point in Joomla  3 lifespan I am not in favour of what will actually be quite a disruptive change to peoples workflow and documentation etc.

I am going to set it to be reevaluated for Joomla 4 where such a change would be more appropriate.

**Comment by uglyeoin** [comment] 2018-12-05 17:16
I think having it an SEO tab changes the perception of it.  We all know (probably) that SEO is quite detailed work and there's no silver bullet.  But many end users of Joomla! think that Yoast for WordPress is a silver bullet.  And therefore Joomla! is missing this.  Which is in my opinion not correct but it's not about correctness it's about perception and from ensuring users find Joomla! easy to use and has good UX.

**Comment by uglyeoin** [comment] 2018-12-05 17:37
Additional fields that could be added are the social open graph meta tags http://ogp.me/ which are pretty standard fields now-a-days and should not require a plugin

**Comment by uglyeoin** [comment] 2018-12-05 17:45
From the other pull.  
https://camo.githubusercontent.com/8b0c6b40c7ed86ce4854921291a4924279b056f9/68747470733a2f2f6973737565732e6a6f6f6d6c612e6f72672f75706c6f6164732f312f63303430656636363439353738623532323866646261613738633463383439642e6a7067

**Comment by anibalsanchez** [comment] 2018-12-06 09:54
I think that we can't add more tabs and fields in the backend.

If 7 is a magic number to deal with complexity in UX, we are way beyond that limit. 

BTW: Remember to test this on a smartphone

**Comment by uglyeoin** [comment] 2018-12-06 13:55
Well yes, of course, and I think there are tonnes of options, but in other systems there are these options too.  Unfortunately we cannot change the backend layout.  Other systems just don't stick them all in tabs in a row.  There's nothing we can do about that, or the possible perception of Joomla! being complicated, with bad UX and hard to use.  But we can solve the SEO perception.  I think all of this stuff has to be a Joomla! 4 issue anyway because it could break B/C otherwise.  And in J4 we DO have the opportunity to change the admin layout.

**Comment by anibalsanchez** [comment] 2018-12-06 14:40
There is always a good reason to add a new field, tab, or checkbox. I'm not questioning the need for improving the SEO perception, or how it can be achieved.

My point is that we always find the same action _adding one more item to a long list of fields, tabs, or checkboxes_.

**Comment by uglyeoin** [comment] 2018-12-07 12:40
Yes, and unfortunately, without breaking b/c it's hard to change this action.  But perhaps it is something to consider for J4.  Although it's a little late perhaps.  But the idea that we could add an infinite amount of items (unrealistic but a concept) without breaking everything should be at least discussed.  But not here.  Here I just want to back up this person and the other person who had the same idea because I feel that although there may be many other good ideas, the feedback I get from customers is that they want to see this.

**Comment by AndySDH** [comment] 2018-12-22 19:32
I'm all for this. This makes a lot of sense to group all the SEO-related options together. Right now finding the option for the "Browser Page Title" aka Meta Title is almost impossible, buried at the end of the Options tab. No reason for it to not be together with Meta Description etc.

> 8 tabs that someone needs to go through to publish an article? Really?
> We are doing it wrong!

Totally disagree. Nobody _needs_ to go through any tab other than the "Content" tab (and maybe the "Images" tab). All the rest is optional stuff that is OFFERED in addition to the basic stuff that you can do in the first tab.

So you'd propose stripping away functionallity or jamming it all in one page instead, making it a lot more confusing?

Joomla is very powerful and has a lot of additional features IN ADDITION to the simple stuff. Nothing wrong with that.

**Comment by wilsonge** [comment] 2019-06-17 22:50
> I think having it an SEO tab changes the perception of it. We all know (probably) that SEO is quite detailed work and there's no silver bullet. But many end users of Joomla! think that Yoast for WordPress is a silver bullet. And therefore Joomla! is missing this. Which is in my opinion not correct but it's not about correctness it's about perception and ensuring users find Joomla! easy to use and has good UX.

I 100% agree with @uglyeoin on this. This was intended for this years GSOC project (unfortunately we couldn't get a mentor team on this). But it's definitely a valid feature request

**Comment by brianteeman** [comment] 2019-06-17 22:56
I have a PR to submit in the morning to kill the useless meta keywords

**Comment by uglyeoin** [comment] 2019-06-17 23:35
@brianteeman doesn't related articles use that?

**Comment by franz-wohlkoenig** [comment] 2019-06-18 03:38
> doesn't related articles use that

Module Articles Related use Meta Keywords.

**Comment by AndySDH** [comment] 2020-11-01 10:30
@wilsonge any word on this since you agreed with the idea?

**Comment by brianteeman** [comment] 2020-11-01 10:46
As with every "idea" it needs to scratch someone's itch enough for them to write the code.

**Comment by uglyeoin** [comment] 2020-11-01 10:52
For me I wouldn't scratch the itch unless someone tells me it would be accepted. And for that I would need to fully understand the process for it being accepted. Like who makes the final decision. This idea has been raised several times and yet this issue is closed. So I wouldn't write the code purely for that reason at the moment. 

Since it's been raised a fee times I'm sure I'm not the only one who would scratch the itch. Someone will have to tell the naysayers that it's being accepted and green light the idea

**Comment by AndySDH** [comment] 2020-11-01 10:58
I think at the very LEAST, we should move the Browser Page Title above the Meta Description field (in the Publishing tab). That would be a start and an improvement already. I could do the code for that, it's a 2 line fix.

**Comment by AndySDH** [comment] 2020-11-01 12:07
Actually not so easy as I have no idea where the code for that is. The XML looks like a mess with everything out of order...

**Comment by wilsonge** [comment] 2020-11-01 22:58
> This idea has been raised several times and yet this issue is closed

The issue never got closed... Just no one worked on it. I'm still happy to have an SEO tab if someone wants to work on it. But at this point would need to be to the 4.1 branch

**Comment by uglyeoin** [comment] 2020-11-02 06:53
Ah yes, the other issues got closed.  Ok, I will try to find some time one day to work on this on the condition that it will defintiely get put through.  If there is going to be a debate at the END after I've done the work then please get the powers that be to either say that debate is null and void or else have that debate up front, I don't want to work on something if it's not going to be accepted I don't have that level of spare time at the moment.

**Comment by uglyeoin** [comment] 2020-11-02 06:53
Happy to team up @AndySDH if you want to work together

**Comment by AndySDH** [comment] 2020-11-02 08:28
I'm up for it, just haven't found the file/code where this is the controlled :D

Also, another idea:

If we add a new SEO Tab, we could streamline the tabs a little bit more, by moving the "Configure Edit Screen" options under a block inside the "Options" tab instead of being a separate tab. I don't think it deserves its own tab (anymore).

**Comment by uglyeoin** [comment] 2020-11-02 08:54
I think perhaps that would be two pull requests.  And there is information in other places about where to find the stuff.  I think it comes out as JSON or something somewhere.  It's not so straight forward as moving things in an XML file is what I can remember.  Send me a message via www.squareballoon.co.uk and we'll work out how to do a fix.  BUT... only if it's going to get approved.

**Closed** 2020-12-28 01:21 UTC
Labels: J4  Re-evaluate, No Code Attached Yet
