### ISSUE TITLE
Malformed SEF URLs generated for com_tags in some cases

### ISSUE THREAD

**Issue by AndySDH** [joomla/joomla-cms#42208] opened 2023-10-23 14:08 UTC
### Steps to reproduce the issue

Nonsef URLs like this:
_**index.php?option=com_tags&Itemid=657&id=4-apple&view=tag**_
are turned into a correct SEF like this:
[menu-item-name]/[tag-name]
eg:
tags/apple
So this converts correctly.

However, nonsef URLs like this:
_**index.php?option=com_tags&Itemid=657&id[0]=4&view=tag**_
fail to generate a correct SEF, converting to ths:
menu-item-name/[TAG-ID]
eg:
tags/4
So in this case it doesn't use the name but it uses the ID of the tag.

To reproduce the issue, link to a URL formed like the above ones, for an existing com_tags tag.

### Expected result
_**index.php?option=com_tags&Itemid=657&id[0]=4&view=tag**_

should form an URL like:
tags/apple

### Actual result

But instead it forms an URL like:
tags/4

### System information (as much as possible)

Tested on Joomla 4.3.4

**Comment by richard67** [comment] 2023-10-23 14:50
@Hackwar Could you have a look on this issue? To me it seems expected behaviour, but I'm not sure.

**Comment by simbus82** [comment] 2023-10-26 15:00
@AndySDH 

> index.php?option=com_tags&Itemid=657&**id[0]**=4&view=tag

Where does a URL like this come from?

**Comment by Hackwar** [comment] 2023-10-26 16:10
will do

**Comment by Quy** [comment] 2024-02-08 22:28
Duplicate #39708?

**Comment by Hackwar** [comment] 2024-08-07 04:57
This is not expected behavior and should be fixed. The problem is in the router of com_tags. The router does not load the right alias when the alias isn't given. This has to be added at the end of the build method. Would anybody be willing to take this up? It is a rather straightforward lookup in the database.

**Comment by Hackwar** [comment] 2024-11-23 22:43
I created a PR. Please test #44515. Since we have a PR, I'm closing this issue.

**Closed as completed by Hackwar** 2024-11-23 22:43 UTC
Labels: No Code Attached Yet, Information Required, bug
