### ISSUE TITLE
PHP Deprecated: stripos(): Passing null to parameter #1 ($haystack) of type string is deprecated in WebClient.php

### ISSUE THREAD

**Issue by o-joomla-issues** [joomla/joomla-cms#43415] opened 2024-05-02 09:03 UTC
### Steps to reproduce the issue
Do a raw http request on an URL that gets redirected, like / on a multi-language site:
$ openssl s_client -connect some-website.com:443
GET / HTTP/1.1[enter]
Host: some-website.com[enter]
[enter]

### Expected result
No error

### Actual result
PHP Deprecated:  stripos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /htdocs/libraries/vendor/joomla/application/src/Web/WebClient.php on line 380 (and other lines)

### System information
php8.3-fpm     8.3.6-1+0~20240424.32+debian12~1.gbp9a7ce5

### Additional comments
I don't know which client actually does http request without user agent, but I see these errors in the logs quite often.
Anyway, we should always validate user-supplied variables.

An easy fix should be:
htdocs/libraries/vendor/joomla/application/src/Web/WebClient.php
[...]
public const NONE = 0; // maybe UNKOWN instead?
[...]
protected function detectEngine($userAgent)
    {   
        if(empty(trim($userAgent))) {
            $this->engine = self::NONE;
        } elseif [...]
    }

**Comment by brianteeman** [comment] 2024-05-02 10:17
As your fix is in `libraries/vendor/joomla/application` then it should be reported/fixed there and not in the cms
https://github.com/joomla-framework/application

Can be closed as not a bug in the cms but in the upstream library

**Comment by alikon** [comment] 2024-05-02 10:41
please test https://github.com/joomla-framework/application/pull/124

**Closed as completed by alikon** 2024-05-02 10:41 UTC
Labels: No Code Attached Yet

**Comment by o-joomla-issues** [comment] 2024-05-02 11:07
Sorry, I was mislead by the "Library" option in the categories selection. I didn't appear to me that "Joomla! Issue Tracker - CMS" excludes the Joomla library (although I am certainly aware of the difference between the CMS and the framework).
