### ISSUE TITLE
No result with smart search on multilingual J4 website

### ISSUE THREAD

**Issue by peterwouda** [joomla/joomla-cms#38957] opened 2022-10-14 08:11 UTC
### Steps to reproduce the issue
Searching for "bedding" in smart search module on front-end of multi-lingual website (EN and NL)

### Expected result
Showing search suggestions
List of all articles containing "bedding"

### Actual result
Search suggestions are working fine
No search results in English (en-GB) could be found for query: bedding.

### System information (as much as possible)
Joomla 4.2.3
PHP 8.0.24
Database: 10.5.17-MariaDB 

### Additional comments
![screen shot 2022-10-14 at 08 09 19](https://issues.joomla.org/uploads/1/3fb6a2ee52a23fe267d2d49ae0e5b00f.jpg)![screen shot 2022-10-14 at 08 09 19](https://issues.joomla.org/uploads/1/566d580554c25c63ce378e0f5f3ad442.jpg)

**Comment by crystalenka** [comment] 2023-01-25 18:58
I am also experiencing this on 4.2.6. Did you ever figure it out?

**Comment by peterwouda** [comment] 2023-01-26 09:45
I removed the filter that selected the articles of one language, and now it works. 
It should work with filter, but I did not get it to work.

**Comment by crystalenka** [comment] 2023-01-26 09:50
So it's a filter issue also! I am trying to figure out how to reproduce this so it can be debugged. Thank you!

**Comment by peterwouda** [comment] 2023-01-26 09:53
Maybe it is the combination of a filter with multi lingual websites? Good luck with debugging!

**Comment by crystalenka** [comment] 2023-01-26 11:09
Can I ask what your category structure looks like on that site? Like, did you have top level categories for each language, or did you have a top level category with language set to all and sub-categories for each language? I have a theory.

**Comment by peterwouda** [comment] 2023-01-26 11:15
I use both. There is a top level category for each language with articles in English and Dutch, and there are top level categories for one language ( english or dutch).

**Comment by crystalenka** [comment] 2023-01-26 11:17
Thanks! I think I have managed to reproduce it now. Will open a new issue and reference this one.

**Comment by peterwouda** [comment] 2023-01-26 11:23
Great, you are a pro!

**Comment by crystalenka** [comment] 2023-01-26 11:36
Okay, I opened the issue. Does that look like the same problem you were having? If so, I will close this issue as duplicate since I have more detailed info in the new one :)

**Comment by peterwouda** [comment] 2023-01-26 12:52
Your issue looks like the same as my problem, so it is OK with me if you close this issue.
Thanks!

**Comment by crystalenka** [comment] 2023-01-26 12:58
Thanks! Closing in favor of #39718

**Closed as not planned by crystalenka** 2023-01-26 12:58 UTC
Labels: No Code Attached Yet
