### ISSUE TITLE
[4.0]Not able to select a new image for Component Banners

### ISSUE THREAD

**Issue by nileshprasad137** [joomla/joomla-cms#14630] opened 2017-03-15 04:19 UTC
### Steps to reproduce the issue
1. go to component banners
2. Add a new Banner.(Click new)
3. In the details tab, try to select an image. The image doesn't get selected. Insert button doesn't work.

### Expected result
The image should have been selected. 

### System information (as much as possible)
PHP 7.0.0
Database Version 	5.7.9 
Joomla! Version -	Joomla! 4.0.0-dev Development
Database Collation - utf8_general_ci
Database Connection Collation - utf8mb4_general_ci 
Web Server 	Apache/2.4.17 (Win64) PHP/5.6.16

**Comment by franz-wohlkoenig** [comment] 2017-03-15 06:49
Issue confirmed.
### System information
Joomla! 4.0.0-dev
macOS Sierra, 10.12.3
Firefox 52.0 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by tonypartridge** [comment] 2017-03-18 14:23
@nileshprasad137 the media manager is getting a full re-work for 3.8 and this type of change will / can be looked into more detail then.

**Comment by tonypartridge** [comment] 2017-03-19 11:17
@wilsonge please close since media manager needs a full re-work.

**Comment by wilsonge** [comment] 2017-03-19 11:18
Closing in favour of https://github.com/joomla/joomla-cms/issues/14741 which is the generic media manager issue

**Closed by wilsonge** 2017-03-19 11:18 UTC
Labels: No Code Attached Yet
