### ISSUE TITLE
Invalid HTTP 1.1 Status lines generated by Joomla for 404/500 and maybe more

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#16038] opened 2017-05-15 17:10 UTC
### Steps to reproduce the issue

check the headers of a 404 page in Joomla 

### Expected result

Valid HTTP 1.1 Status line as per https://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html which states 

> The first line of a Response message is the Status-Line, consisting of the protocol version followed by a numeric status code **and its associated textual phrase**

Therefore:

`HTTP/1.1 404 Not Found`

### Actual result

```
HTTP/1.1 404
Cache-Control: no-cache
Connection: keep-alive
Content-Type: text/html; charset=UTF-8
Date: Mon, 15 May 2017 17:04:39 GMT
Pragma: no-cache
Server: nginx/1.12.0
Set-Cookie: 2b5a6d72eb04b3ca2060919d2e69f2c9=89t2b6579gogie33tnjpmvdirq; path=/; HttpOnly
Transfer-Encoding: chunked
X-Powered-By: PHP/7.1.5
```

### Other Comments 

same happens for 500 errors:

`HTTP/1.1 500`

instead of 

`HTTP/1.1 500 Internal Server Error`

**Comment by rdeutz** [comment] 2017-05-15 17:12
Which Joomla version 3.7.1-rc2?

**Comment by PhilETaylor** [comment] 2017-05-15 17:13
Test was done on 61b9fcc4702467fdb0500057c49577037561fcc1

**Comment by rdeutz** [comment] 2017-05-15 17:14
might be a side effect of https://github.com/joomla/joomla-cms/pull/15738

**Comment by PhilETaylor** [comment] 2017-05-15 17:15
Look here: https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/application/web.php#L722

```php 
// 'status' headers indicate an HTTP status, and need to be handled slightly differently
					$this->header('HTTP/1.1 ' . (int) $header['value'], true);
```

**Comment by PhilETaylor** [comment] 2017-05-15 17:16
Also see #15738 - see where they DELIBERATELY changed the Unit tests that were failing to suit their new BROKEN implementation of the HTTP 1.1 Status codes!!! 

THIS IS NOT WHAT YOU DO WITH UNIT TESTS!!!!

**Comment by mbabker** [comment] 2017-05-15 17:17
Regardless of the changes in #15738 we've never handled Status headers very well as we don't enforce having a full header in our API.  So we do need to look at better handling that somehow in general.

**Comment by PhilETaylor** [comment] 2017-05-15 17:18
The unit tests used to be right, Joomla used to be right. Then #15738 changed that.

**Comment by wilsonge** [comment] 2017-05-15 17:22
That was actually an unintended side effect of me trying to do fancy stuff with the redirect methods. I also changed the unit test when we reverted back to using the api. Given that everything else didn't have the text I didn't see it as an issue for that pull request. Although it is something we should solve generically

**Comment by PhilETaylor** [comment] 2017-05-15 17:30
Well however it has been caused, Joomla 3.7.x will soon output invalid HTTP 1.1 status codes as the first output it ever sends to the browser.

Would be easy to fix by extending the use of the [$responseMap](https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/application/web.php#L84) and using those as the code instead of the int.

I would do the PR but Im on my way out for an indian curry...

**Comment by PhilETaylor** [comment] 2017-05-15 17:38
if you dump out headers from http://joomla-cms/index.php?option=com_asd

```php
$header['value']
```
in 

```php
// 'status' headers indicate an HTTP status, and need to be handled slightly differently
$this->header('HTTP/1.1 ' . (int) $header['value'], true);
``` 
You get

`404 Component not found.`

So the fact that casting it to (int) is gett 404 is lucky.. is is very tacky at best!

**Comment by brianteeman** [comment] 2017-05-15 17:42
just for fun i checked drupal and wordpress they also are "wrong" as is myjoomla.com although at least github was correct

## drupal 
<img width="327" alt="screenshotr18-36-22" src="https://cloud.githubusercontent.com/assets/1296369/26070785/c8c0b204-399d-11e7-9a64-a5f2b7b28af9.png">

## wordpress
<img width="339" alt="screenshotr18-36-45" src="https://cloud.githubusercontent.com/assets/1296369/26070786/c8ca93b4-399d-11e7-9258-de762c3b3184.png">

## myjoomla.com
<img width="303" alt="screenshotr18-41-50" src="https://cloud.githubusercontent.com/assets/1296369/26070909/37765c30-399e-11e7-9e3e-8e9689a96304.png">


## github
<img width="308" alt="screenshotr18-39-57" src="https://cloud.githubusercontent.com/assets/1296369/26070838/f58bd0d4-399d-11e7-8d5e-69c607a5bd32.png">

**Comment by PhilETaylor** [comment] 2017-05-15 17:44
so just cause other projects do the wrong thing so should Joomla? 

Just because Joomla **USED TO DO THE RIGHT THING** it is acceptable to change the unit tests to accept the **WRONG THING** now for whatever reasons?

**Comment by brianteeman** [comment] 2017-05-15 17:45
its a bug - calm down - its not the end of the world

**Comment by PhilETaylor** [comment] 2017-05-15 17:46
Its not a bug, Its a regression
Its made Joomla worse than it already was

**Comment by brianteeman** [comment] 2017-05-15 17:48
hardly - but keeping banging your drum

the day any developer writes perfect code we can all go out and get new jobs - until then....

**Comment by PhilETaylor** [comment] 2017-05-15 17:49
Well Im sorry for demanding that Joomla is held to some kind of standard... shoot me.

**Comment by mbabker** [comment] 2017-05-15 17:50
The only time Joomla did the right thing was with redirect responses because that one explicitly mapped a status code to a value in an array.  Any other way to set the Status header doesn't go through any form of validation, so it hasn't always been right.

So yes it's a regression in that this change was allowed, but no we haven't completely FUBAR'd the handling of that header.

**Comment by mbabker** [comment] 2017-05-15 17:55
It's a valid issue...

**Comment by rdeutz** [comment] 2017-05-15 18:46
closing because we can discuss a PR #16040

**Closed by rdeutz** 2017-05-15 18:46 UTC
Labels: No Code Attached Yet
