### ISSUE TITLE
[4.0] tinyMCE: Image-Button in own Row

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#18860] opened 2017-11-25 12:29 UTC
### Steps to reproduce the issue
as mentioned by @infograf768 in another Issue:

![bildschirmfoto 2017-11-25 um 13 26 16](https://user-images.githubusercontent.com/8235763/33230489-865ab06a-d1e4-11e7-8ebb-4bbca306fcd8.jpg)
### System information
4.0.0-dev
Multilanguage Site (4 Lang.) & Sample Data
macOS Sierra, 10.12.6
Firefox 57 (64-bit)
#### MAMP 4.2
- PHP 7.0.22
- MySQLi 5.6.35

**Comment by brianteeman** [comment] 2017-12-04 14:17
it is related to this code
https://github.com/joomla/joomla-cms/blob/4e21575a1e0cc7110e64fca33680cabee4200f63/plugins/editors/tinymce/tinymce.php#L711

**Comment by brianteeman** [comment] 2017-12-11 13:26
and if you look the tinymce image icon is never proposed as an available icon - even if the xtd-editor image plugin is not enabled

**Comment by ghost** [comment] 2017-12-11 13:28
so this is expected Behaviour?

**Comment by brianteeman** [comment] 2017-12-11 13:38
no

**Comment by dgrammatiko** [comment] 2017-12-11 14:09
Ok, these are right observations and would be fixed once all joomla xtd-buttons are converted to native tinymce plugins. Also since we have a request to make the editor context aware there is quite some work ahead till we can reach the desired target. All and all, at this point, this is the expected behavior but will be changed as the rest of the changes are implemented.

**Comment by brianteeman** [comment] 2017-12-20 23:56
@dgt41 why convert the buttons to be tinymce buttons? That would mean they wont work with the other editors

**Comment by ghost** [comment] 2018-01-08 15:15
closed as having Pull Request #19334

**Comment by brianteeman** [comment] 2018-01-08 16:40
reopened

**Comment by brianteeman** [comment] 2018-03-25 13:48
Closed as this has been resolved elsewhere by putting all xtd plugins into a single drop-down

**Closed as completed by brianteeman** 2018-03-25 13:48 UTC
Labels: No Code Attached Yet, J4 Issue
