### ISSUE TITLE
[3.5-beta1] Databaseproblem

### ISSUE THREAD

**Issue by akinom500** [joomla/joomla-cms#8368] opened 2015-11-10 12:05 UTC
#### Steps to reproduce the issue
after update from 3.4 to 3.5 
I open Extensions: Database
and found the Warning that the db is not uptodate

12 Database problems were found:

    Database schema version (3.4.0-2015-02-26) does not match CMS version (3.5.0-2015-11-05).
    Database update version (3.4.5) does not match CMS version (3.5.0-beta).
    Table 'jos_banners' does not have column 'alias' with type 'varchar(191)'. (From file 3.5.0-2015-07-01.sql.)
    Table 'jos_categories' does not have column 'alias' with type 'varchar(191)'. (From file 3.5.0-2015-07-01.sql.)
    Table 'jos_contact_details' does not have column 'alias' with type 'varchar(191)'. (From file 3.5.0-2015-07-01.sql.)
    Table 'jos_content' does not have column 'alias' with type 'varchar(191)'. (From file 3.5.0-2015-07-01.sql.)
    Table 'jos_menu' does not have column 'alias' with type 'varchar(191)'. (From file 3.5.0-2015-07-01.sql.)
    Table 'jos_newsfeeds' does not have column 'alias' with type 'varchar(191)'. (From file 3.5.0-2015-07-01.sql.)
    Table 'jos_tags' does not have column 'alias' with type 'varchar(191)'. (From file 3.5.0-2015-07-01.sql.)
    Table 'jos_ucm_content' does not have column 'core_alias' with type 'varchar(191)'. (From file 3.5.0-2015-07-01.sql.)
    Table 'jos_contentitem_tag_map' should not have index 'idx_tag'. (From file 3.5.0-2015-10-26.sql.)
    Table 'jos_contentitem_tag_map' should not have index 'idx_type'. (From file 3.5.0-2015-10-26.sql.)

after click on the button fix an 500 internal server error appears

#### Expected result

fix database 

#### Actual result

500 internal server error 

#### System information (as much as possible)
 
PHP Built On 	Windows NT SRV10069 6.1 build 7600 (Windows Server 2008 R2 Enterprise Edition) i586
Database Version 	5.1.56-community
Database Collation 	utf8_general_ci
Database Connection Collation 	utf8_general_ci
PHP Version 	5.6.0
Web Server 	Microsoft-IIS/7.5
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 3.5.0-beta Beta [ Ember ] 06-November-2015 24:00 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT 

#### Additional comments
test.dancing-dangerous.at if needed a user and pw could be send

**Comment by zero-24** [comment] 2015-11-10 17:07
@alikon can you check it? @akinom500 what databse do you use on the Windows server? MSSQL oder MySQL or other?

**Comment by alikon** [comment] 2015-11-10 18:17
yes, but info needed
what are the (12) tables structure ?

**Comment by akinom500** [comment] 2015-11-10 20:16
i use mysql Database Version 5.1.56-community<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8368">issues.joomla.org/joomla-cms/8368</a>.</sub>

**Comment by richard67** [comment] 2015-11-11 00:33
Could this one here be related to #8267 ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8368">issues.joomla.org/joomla-cms/8368</a>.</sub>

**Comment by zjw** [comment] 2015-11-11 00:37
There can be no doubt that this is related to #8267.

**Comment by roland-d** [comment] 2015-11-17 10:41
@akinom500 Thanks for your report, I am going to close it as it is a duplicate of #8267 and we are working to fix this for the next beta release.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8368">issues.joomla.org/joomla-cms/8368</a>.</sub>

**Closed** 2015-11-17 10:52 UTC
Labels: No Code Attached Yet

**Comment by zero-24** [comment] 2015-11-17 10:54
@joomla-cms-bot please don't reopen issues that gets closed by maintainers thanks :+1:
