### ISSUE TITLE
An error has occurred. 0 Class 'JToolbarHelper' not found

### ISSUE THREAD

**Issue by Latos88** [joomla/joomla-cms#23078] opened 2018-11-14 16:23 UTC
Hello,

Please I have issue with my administrator joomla, when i want to access to Administrator panel I got this issue : An error has occurred.
0 Class 'JToolbarHelper' not found  
Version 3.9.0 

Thanks

**Comment by Quy** [comment] 2018-11-14 16:29
Duplicate of #21960<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23078">issues.joomla.org/tracker/joomla-cms/23078</a>.</sub>

**Closed as completed by Quy** 2018-11-14 16:29 UTC
Labels: No Code Attached Yet
