### ISSUE TITLE
Preview on "Articles: Edit"

### ISSUE THREAD

**Issue by joomlerPRO** [joomla/joomla-cms#43520] opened 2024-05-23 23:33 UTC
### Steps to reproduce the issue

The Preview on "Articles: Edit" is loading the error page and not the article Preview. The article Preview is showing only is the article is published!

### Expected result

Expected result is to show the Preview of the article after the article is saved and even its not published

### Actual result

The Preview on "Articles: Edit" is loading the error page and not the article Preview. 

### System information (as much as possible)

Latest joomla 5.1.0
php 8.1

**Comment by Quy** [comment] 2024-05-23 23:43
Closing as duplicate of  #24132.

**Closed as completed by Quy** 2024-05-23 23:43 UTC
Labels: No Code Attached Yet

**Comment by joomlerPRO** [comment] 2024-05-23 23:49
and what is the solution? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43520">issues.joomla.org/tracker/joomla-cms/43520</a>.</sub>
