### ISSUE TITLE
Error when a negative number is entered in leading articles in featured view

### ISSUE THREAD

**Issue by drmenzelit** [joomla/joomla-cms#40116] opened 2023-03-14 13:47 UTC
### Steps to reproduce the issue

Create a menu item from type featured articles
Enter -1 (I know it doesn't make sense, but it is possible to do) in leading articles

### Expected result
An error message, because a negative number doesn't make sense or at least no problems on the page

### Actual result

0 Attempt to modify property "params" on null 

![grafik](https://user-images.githubusercontent.com/9153168/225020550-16fe8ca1-28c3-4b7a-b9c6-70913cdc12ea.png)

### System information (as much as possible)

Joomla 4.2.8
PHP 8.0.4

### Additional comments
I checked entering a negative number in the intro articles fields and also with a menu item of type category blog, no errors there.

**Comment by brianteeman** [comment] 2023-03-14 14:15
confirmed

**Comment by brianteeman** [comment] 2023-03-14 16:11
@joomdonation the weird part is that the field definition is the same in the blog view and it doesnt give tyhe error there

**Comment by joomdonation** [comment] 2023-03-15 05:31
@brianteeman @drmenzelit Because we use different code to getting leading, intro and link items on the two views. For reference

- In featured view https://github.com/joomla/joomla-cms/blob/4.2-dev/components/com_content/src/View/Featured/HtmlView.php#L177-L194
- In category view https://github.com/joomla/joomla-cms/blob/4.2-dev/components/com_content/src/View/Category/HtmlView.php#L126-L133

And although there is no fatal error in category blog view, allow negative value for the parameter will cause logical error. For example, if you set **Leading Articles** parameter to **-1**, **Intro Articles** parameter to **-3**, you will only have **2** intro articles displayed instead of **3** intro articles as expected.

With that said, we should add the suggested validation to prevent this kind of errors.

**Comment by joomdonation** [comment] 2023-03-15 09:26
Closing as we have PR https://github.com/joomla/joomla-cms/pull/40120 .

**Closed as completed by joomdonation** 2023-03-15 09:26 UTC
Labels: No Code Attached Yet, bug
