### ISSUE TITLE
Postinstall messages fatal error

### ISSUE THREAD

**Issue by ot2sen** [joomla/joomla-cms#19832] opened 2018-03-04 20:10 UTC
### Steps to reproduce the issue
Fresh install. Clicked Postinstall messages.

### Expected result
See list of messages.

### Actual result
Got a Fatal error: Maximum execution time of 30 seconds exceeded in C:\wampps\Ampps\www\386rc1\libraries\src\Http\Transport\CurlTransport.php on line 204

and page with no styling.

### System information (as much as possible)
3.8.6 RC 1
Added learning demodata (is that an issue?)
![screen shot 2018-03-04 at 20 10 15](https://issues.joomla.org/uploads/1/0154d96c5db39d43746ddf24cccce36d.png)PHP 7

### Additional comments

![screen shot 2018-03-04 at 20 10 18](https://issues.joomla.org/uploads/1/b1244e79c8a773036097c9095a6dfbf6.png)

**Comment by ot2sen** [comment] 2018-03-04 20:46
Tried with standard demo data to make sure it wasn´t relate to learning data but still getting same issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19832">issues.joomla.org/tracker/joomla-cms/19832</a>.</sub>

**Comment by infograf768** [comment] 2018-03-05 11:04
Can't reproduce on MAMP php 7.1.8

**Comment by ot2sen** [comment] 2018-03-05 12:50
Gave the 3.8.6 RC1 a third try. This time with no demo data. Still getting the same issue nomatter if postinstall is visited through module read more at main admin or via the component menu.

**Comment by ot2sen** [comment] 2018-03-05 12:50
Using AMPPS with PHP 7.1.8

**Comment by zero-24** [comment] 2018-03-05 13:11
What happes with increase the max execution time?

**Comment by ot2sen** [comment] 2018-03-05 13:22
By raising the default 30 to 60 the page loads after about 40 secs
Feed from joomla.org is empty.
![05-03-2018_postinstall_30to60_took40toload](https://user-images.githubusercontent.com/790445/36977213-ae2c0fa4-2080-11e8-9989-73c1dd5ea7ac.png)

**Comment by zero-24** [comment] 2018-03-05 13:24
Looks like sidelock is blocking that feed again. @mbabker can you open a ticket there?

**Comment by brianteeman** [comment] 2018-03-05 14:59
yes its a feed problem again.


Closing it here as its not a joomla bug

**Closed as completed by brianteeman** 2018-03-05 14:59 UTC
Labels: No Code Attached Yet
