### ISSUE TITLE
Error reporting: None displays mysql errors

### ISSUE THREAD

**Issue by duetltd** [joomla/joomla-cms#15045] opened 2017-04-01 18:47 UTC
### Steps to reproduce the issue
Going into administrator and setting error reporting to "None"
Opening a custom written component (that worked using Joomla 2.5.xx) displays a Mysql error message.

### Expected result
Since the option states: Display errors: None - one would assume that no errors would display. 
The component should then display the content following where the error occurs.

### Actual result
No content appears - just an error message. 

### System information (as much as possible)
Setting 	                   Value
Database Version 	           5.7.17
Database Collation 	           latin1_swedish_ci
Database Connection Collation 	   utf8mb4_general_ci
PHP Version 	                   5.4.16
Web Server 	                   Apache/2.4.6 (CentOS) PHP/5.4.16
WebServer to PHP Interface 	   apache2handler
Joomla! Version 		   Joomla! 3.6.5 Stable [ Noether ] 1-December-2016 22:46 GMT
Joomla! Platform Version  	   Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

**Comment by brianteeman** [comment] 2017-04-01 20:07
the display errors option refers specifically to php errors

Set the option to maximum or development and you should see the php error that you need to fix.

I am closing this here as the option is working as intended and we cannot support specific issues with non core code here. If you have further questions regarding making your component work please use the forum https://forum.joomla.org

**Closed by brianteeman** 2017-04-01 20:07 UTC
Labels: No Code Attached Yet
