### ISSUE TITLE
TinyMCE will delete all anchors except for the first one

### ISSUE THREAD

**Issue by gorgonz** [joomla/joomla-cms#6426] opened 2015-03-14 15:18 UTC
#### Steps to reproduce the issue
create a new article in the backend

#### Expected result
insert this code:
<table cellspacing="0" cellpadding="0" border="0" id="lesungen_tabelle">
<tbody>
<tr>
<td valign="top" align="left" rowspan="4" class="pappnasen" id="portrait-cover">
<a class="ceraBox" href="/images/Lesungen/Zwei-Pappnasen/zwei-pappnasen.jpg"> <img border="0" alt="" src="/images/Lesungen/Zwei-Pappnasen/zwei-pappnasen.jpg"></a>
<a style="display: none;" class="ceraBox" href="/images/Lesungen/Zwei-Pappnasen/pappnasen_01.jpg"></a>
<a style="display: none;" class="ceraBox" href="/images/Lesungen/Zwei-Pappnasen/pappnasen_02.jpg"></a> 
</td>
</tr>
</tbody>
</table>

Then toggle the editor with the button below the editor field (on the right corner)
Toggle back again

#### Actual result
only this code is left over:
<table id="lesungen_tabelle" border="0" cellspacing="0" cellpadding="0">
<tbody>
<tr>
<td id="portrait-cover" class="pappnasen" rowspan="4" align="left" valign="top"><a class="ceraBox" href="../images/Lesungen/Zwei-Pappnasen/zwei-pappnasen.jpg"> <img src="../images/Lesungen/Zwei-Pappnasen/zwei-pappnasen.jpg" alt="" border="0" /></a></td>
</tr>
</tbody>
</table>

#### System information (as much as possible)
seen it with released 3.4 and staging version of 14.March 2015

**Comment by gorgonz** [comment] 2015-03-14 15:23
soory, the code was stripped, created two files now:
anchor.txt => the article text to be included
anchor-leftover.txt => the remaining text after toggling<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6426">issues.joomla.org/joomla-cms/6426</a>.</sub>

**Comment by gorgonz** [comment] 2015-03-14 15:38
sorry, hat to find a method to transfer code ;-)

Enter this code into the editor:
`<table cellspacing="0" cellpadding="0" border="0" id="lesungen_tabelle">
<tbody>
<tr>
<td valign="top" align="left" rowspan="4" class="pappnasen" id="portrait-cover">
<a class="ceraBox" href="/images/Lesungen/Zwei-Pappnasen/zwei-pappnasen.jpg"> <img border="0" alt="" src="/images/Lesungen/Zwei-Pappnasen/zwei-pappnasen.jpg"></a>
<a style="display: none;" class="ceraBox" href="/images/Lesungen/Zwei-Pappnasen/pappnasen_01.jpg"></a>
<a style="display: none;" class="ceraBox" href="/images/Lesungen/Zwei-Pappnasen/pappnasen_02.jpg"></a> 
</td>
</tr>
</tbody>
</table>
`
This is the resulting code after toggling the editor:

`<table id="lesungen_tabelle" border="0" cellspacing="0" cellpadding="0">
<tbody>
<tr>
<td id="portrait-cover" class="pappnasen" rowspan="4" align="left" valign="top"><a class="ceraBox" href="../images/Lesungen/Zwei-Pappnasen/zwei-pappnasen.jpg"> <img src="../images/Lesungen/Zwei-Pappnasen/zwei-pappnasen.jpg" alt="" border="0" /></a></td>
</tr>
</tbody>
</table>`<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6426">issues.joomla.org/joomla-cms/6426</a>.</sub>

**Comment by brianteeman** [comment] 2015-03-14 15:44
The problem is that tinymce is correcting (cleaning) your bad code.

It is removing the links that dont work

As soon as you add something between the opening and closing a tags it works

On 14 March 2015 at 15:38, gorgonz <notifications@github.com> wrote:

> sorry, hat to find a method to transfer code ;-)
>
> Enter this code into the editor:
> <table cellspacing="0" cellpadding="0" border="0" id="lesungen_tabelle">
> <tbody>
> <tr>
> <td valign="top" align="left" rowspan="4" class="pappnasen"
> id="portrait-cover">
> <a class="ceraBox"
> href="/images/Lesungen/Zwei-Pappnasen/zwei-pappnasen.jpg"> <img border="0"
> alt="" src="/images/Lesungen/Zwei-Pappnasen/zwei-pappnasen.jpg"></a>
> <a style="display: none;" class="ceraBox"
> href="/images/Lesungen/Zwei-Pappnasen/pappnasen_01.jpg"></a>
> <a style="display: none;" class="ceraBox"
> href="/images/Lesungen/Zwei-Pappnasen/pappnasen_02.jpg"></a>
> </td>
> </tr>
> </tbody>
> </table>
>
> This is the resulting code after toggling the editor:
>
> <table id="lesungen_tabelle" border="0" cellspacing="0" cellpadding="0">
> <tbody>
> <tr>
> <td id="portrait-cover" class="pappnasen" rowspan="4" align="left"
> valign="top"><a class="ceraBox"
> href="../images/Lesungen/Zwei-Pappnasen/zwei-pappnasen.jpg"> <img
> src="../images/Lesungen/Zwei-Pappnasen/zwei-pappnasen.jpg" alt=""
> border="0" /></a></td>
> </tr>
> </tbody>
> </table>
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/6426
> <http://issues.joomla.org/tracker/joomla-cms/6426>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6426#issuecomment-80537048>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by jayblaq** [comment] 2015-03-15 18:34
Correct the TINY MCE editor is doing its job of cleaning the html<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6426">issues.joomla.org/joomla-cms/6426</a>.</sub>

**Comment by roland-d** [comment] 2015-03-15 18:38
Closing this report as 2 users have confirmed this to be the expected behavior. Thank you for your contribution.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6426">issues.joomla.org/joomla-cms/6426</a>.</sub>

**Closed by roland-d** 2015-03-15 18:37 UTC
Labels: No Code Attached Yet

**Comment by gorgonz** [comment] 2015-03-15 20:07
i see the point and accept it, really. Still i must use a different editor for now, because the plugin is not ready for the behaviour and too many articles would have to be changed, if i switch now.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6426">issues.joomla.org/joomla-cms/6426</a>.</sub>

**Comment by jayblaq** [comment] 2015-03-16 06:20
Have you checked the WYSIWYG settings for filtering?
