### ISSUE TITLE
[4.0] Multilang broken. Router issue!!

### ISSUE THREAD

**Issue by Chacapamac** [joomla/joomla-cms#24292] opened 2019-03-21 16:12 UTC
### Steps to reproduce the issue
Just Install Alpha 8 and create a multilingual site with Cassiopeia

### Expected result

To have the french article ( Article (fr-fr) ) appear in front-end

### Actual result
**I get this error**
_Il n'y a aucun article dans cette catégorie. Si des sous-catégories sont affichées sur cette page, elles peuvent contenir des articles._

The article is present and publish —>
Article (fr-fr) Alias: article-fr-fr
Category: Catégorie (fr-fr)

### System information (as much as possible)
Mamp — PHP 7.2.1 — MYSQL 5.6.38

### Additional comments

**Comment by infograf768** [comment] 2019-03-21 17:37
have you installed the multingual sample data through the module?
which precise url gives this result?

**Comment by Chacapamac** [comment] 2019-03-21 21:52
I install the new language and content language by the administration after I use the “Install Multilingual” with every notes of success + Multilingual Status OK.

What is weird I even verified that both menu items are pointing to the right (french/English) Category Blog and both article are in their right specific category. I think I will reinstall from scratch to see if I can repeat the problem.

The site is on my local Mamp.

**Comment by Chacapamac** [comment] 2019-03-21 22:30
Ok I just reinstall the full Alpha 8 everything work well but see these 2 screenshot something is up?
![French-default-English-page](https://user-images.githubusercontent.com/1907276/54788901-2c1b9d00-4c07-11e9-8d9a-b77fddb36a98.jpg)
When French is default
The english page have a french title and no article — The french page is ok

![English-default-French_page](https://user-images.githubusercontent.com/1907276/54788836-ef4fa600-4c06-11e9-9282-90dbcaba65b2.jpg)
When English is default
The french page have an english title and no article — The english page is ok

**Comment by infograf768** [comment] 2019-03-22 07:41
Will test with a clean install once https://github.com/joomla/joomla-cms/issues/24300 is solved

**Comment by infograf768** [comment] 2019-03-22 08:13
I confirm.

**Comment by infograf768** [comment] 2019-03-22 08:25
The issue is with the router.

**Comment by infograf768** [comment] 2019-03-22 09:32
I am modifying the title of this Issue

**Comment by infograf768** [comment] 2019-03-22 09:36
This can be tested again on a 4.0-dev branch clean install.
Looks like it works fine for a monolingual site

**Comment by infograf768** [comment] 2019-03-22 10:00
Hint: the issue is only when SEF is on.

**Comment by infograf768** [comment] 2019-03-22 14:55
@SharkyKZ 
could this be due to one of your prs merged recently?

**Comment by SharkyKZ** [comment] 2019-03-22 16:12
@infograf768 this has to do with Language Filter plugin changes in 3.9. See https://github.com/joomla/joomla-cms/pull/24192/files#diff-9a4ee24a09bcef172864692ed05135ca.

**Comment by infograf768** [comment] 2019-03-22 16:22
@SharkyKZ 
it works fine in 3.9 and was working fine 3 days ago for 4.0
therefore, something has been modified in the last days that broke it.

**Comment by infograf768** [comment] 2019-03-22 16:52
sorry, i now understand that some changes from 3.9 have been recently merged by @wilsonge in 4.0

**Comment by joeforjoomla** [comment] 2019-03-22 16:59
I confirm, i had a Joomla 4 multilanguage website working since months, once installed the latest Alpha 8 all pages throw a 404. Disabling the multilanguage filter plugin fixes the problem, so it must be something merged in recent days about multilanguage.

**Comment by infograf768** [comment] 2019-03-23 07:52
The issue is in the modification of the `onAfterInitialise()` method.
It was
```
	public function onAfterInitialise()
	{
		$this->app->item_associations = $this->params->get('item_associations', 0);

		if ($this->app->isClient('site'))
		{
			$router = $this->app->getRouter();
			// Attach build rules for language SEF.
			$router->attachBuildRule(array($this, 'preprocessBuildRule'), Router::PROCESS_BEFORE);
			$router->attachBuildRule(array($this, 'buildRule'), Router::PROCESS_BEFORE);
			if ($this->mode_sef)
			{
				$router->attachBuildRule(array($this, 'postprocessSEFBuildRule'), Router::PROCESS_AFTER);
			}
			else
			{
				$router->attachBuildRule(array($this, 'postprocessNonSEFBuildRule'), Router::PROCESS_AFTER);
			}
			// Attach parse rules for language SEF.
			$router->attachParseRule(array($this, 'parseRule'), Router::PROCESS_BEFORE);
		}
	}
```
it is now
```
	public function onAfterInitialise()
	{
		$this->app->item_associations = $this->params->get('item_associations', 0);

		// We need to make sure we are always using the site router, even if the language plugin is executed in admin app.
		$router = CMSApplication::getInstance('site')->getRouter('site');

		// Attach build rules for language SEF.
		$router->attachBuildRule(array($this, 'preprocessBuildRule'), Router::PROCESS_BEFORE);
		$router->attachBuildRule(array($this, 'buildRule'), Router::PROCESS_BEFORE);

		if ($this->mode_sef)
		{
			$router->attachBuildRule(array($this, 'postprocessSEFBuildRule'), Router::PROCESS_AFTER);
		}
		else
		{
			$router->attachBuildRule(array($this, 'postprocessNonSEFBuildRule'), Router::PROCESS_AFTER);
		}

		// Attach parse rules for language SEF.
		$router->attachParseRule(array($this, 'parseRule'), Router::PROCESS_DURING);
	}
```
This last one works fine in 3.9 but breaks 4.0

**Comment by joeforjoomla** [comment] 2019-03-23 08:37
Thanks for the clarification @infograf768 ... waiting for someone more expert to fix it

**Comment by joeforjoomla** [comment] 2019-03-23 08:49
I confirm that the previous version of onAfterInitialise solves the problem with multilanguage on J4 Apha 8

**Comment by SharkyKZ** [comment] 2019-03-23 09:39
Using `Router::PROCESS_BEFORE` instead of `Router::PROCESS_DURING` here appears to fix the issue. 
```
$router->attachParseRule(array($this, 'parseRule'), Router::PROCESS_DURING);
```
This needs a lot of testing.

**Comment by joeforjoomla** [comment] 2019-03-23 10:06
I agree @SharkyKZ a lot of testing

**Comment by infograf768** [comment] 2019-03-23 10:09
@SharkyKZ 
tested that OK here.
But is'nt the main issue with the modifications of the `getInstance()` method in CMSApplication between 3.x and 4.0 ?

**Comment by infograf768** [comment] 2019-03-24 08:02
Closing as we have a patch where this can be discussed further if necessary.
https://github.com/joomla/joomla-cms/pull/24332

**Closed as completed by infograf768** 2019-03-24 08:02 UTC
Labels: No Code Attached Yet, J4 Issue
