### ISSUE TITLE
[3.7 com_fields] Undefined property: FieldsTableField::$assigned_cat_ids

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#13331] opened 2016-12-22 16:54 UTC
### Steps to reproduce the issue

Run php development server at command line
Install Joomla 3.7.0 Alpha 1 
Login to Admin 
Content -> Fields -> New
Enter test for title and label
click save

(Note that we did not create a field group, we did not select a field group)

### Expected result

No warnings or notices 

### Actual result

Undefined property before 303 redirect on save.

<img width="950" alt="screen shot 2016-12-22 at 16 53 54" src="https://cloud.githubusercontent.com/assets/400092/21433308/43be31b4-c867-11e6-8303-f7adaa0c6bdc.png">

```
[Thu Dec 22 16:51:44 2016] PHP Notice:  Undefined property: FieldsTableField::$assigned_cat_ids in /Users/phil/Sites/Joomla_3.7.0/administrator/components/com_fields/tables/field.php on line 113
[Thu Dec 22 16:51:44 2016] 127.0.0.1:55280 [303]: /administrator/index.php?option=com_fields&context=com_content.article&layout=edit&id=0
```

### System information (as much as possible)

https://gist.github.com/c9327e4186cc2940ab5adc40a9c4a53a

**Comment by laoneo** [comment] 2016-12-22 17:55
@Bakual is this still needed. Looks like a regression from #13246.

**Comment by Bakual** [comment] 2016-12-22 19:05
Hmm, I can't reproduce this on staging. I also wouldn't know why it is missing.

> (Note that we did not create a field group, we did not select a field group)

It is unrelated to field groups anyway. It's this field:
![category](https://cloud.githubusercontent.com/assets/1018684/21437051/e47eff92-c881-11e6-9206-97d08184f017.PNG)

**Comment by PhilETaylor** [comment] 2016-12-22 19:07
> I can't reproduce this on staging

er...

I said:
> **Install Joomla 3.7.0 Alpha 1**

:-) 

I cannot git clone from my winter let accommodation as the internet is so bad (git clone always fails), I'll try staging from the office tomorrow.

**Comment by zero-24** [comment] 2016-12-22 19:16
Maybe this helps: https://github.com/joomla/joomla-cms/archive/staging.zip no git clone required ;)

**Comment by PhilETaylor** [comment] 2016-12-22 19:18
24mins remaining :-( 

<img width="673" alt="screen shot 2016-12-22 at 19 17 34" src="https://cloud.githubusercontent.com/assets/400092/21437363/589f4e56-c87b-11e6-9b88-023d5948999c.png">

**Comment by PhilETaylor** [comment] 2016-12-22 19:29
I can still replicate it with staging as of now.

see: http://screenshot.myjoomla.io/102L0d3V0h1v

**Comment by Bakual** [comment] 2016-12-22 20:40
Ah, my fault.
It's indeed a leftover from the PR Allon linked and I haven't adjusted my testing database yet to that change.
Preparing PR....

**Comment by Bakual** [comment] 2016-12-22 20:44
See PR #13334

Closing as we have a PR.

**Closed by Bakual** 2016-12-22 20:44 UTC
Labels: No Code Attached Yet
