### ISSUE TITLE
Clear cache not working if define custom path for JPATH_CACHE in custom defines.php

### ISSUE THREAD

**Issue by remotehelp** [joomla/joomla-cms#6791] opened 2015-04-17 04:29 UTC
Clear cache not working if define custom path for JPATH_CACHE in custom defines.php - in this case need clear cache manually through FTP manager.

**Comment by bertmert** [comment] 2015-04-18 01:13
I don' know if I understand aright. Normally one shouldn't change constants in file defines.php or am I wrong?

So, I entered new line/absolute path in my configuration.php
```
public $cache_path = 'C:\\xampp\\htdocs\\joomla34/mycache';
```
Created new folder /mycache/ in Joomla root.
Activated caching in configuration.

And all worked as expected. All cached folder/files in /mycache/ and could clear cache in Joomla backend (administrator/index.php?option=com_cache).

**Comment by mbabker** [comment] 2015-04-18 01:36
The path constants can be overridden (see https://github.com/joomla/joomla-cms/blob/staging/index.php#L25-L34)

**Comment by joomdonation** [comment] 2015-04-18 06:42
Unfortunately, I don't see an easy way to fix this issue, so if you want to use custom path for cache, you should use the solution which @bertmert  mentioned above

**Comment by bertmert** [comment] 2015-04-18 09:21
> The path constants can be overridden (see https://github.com/joomla/joomla-cms/blob/staging/index.php#L25-L34)
I didn't know that. Thank you.

**Comment by remotehelp** [comment] 2015-04-20 04:49
@bertmert - "public $cache_path = '...'" worked fine! This var ($cache_path) no by default in configuration.php... Where I can get full list variable's allowed for configuration.php?

Thank.

**Comment by zero-24** [comment] 2015-04-29 22:11
Closing as the issue is fixed.

@remotehelp 
>Where I can get full list variable's allowed for configuration.php?

try: https://raw.githubusercontent.com/joomla/joomla-cms/staging/installation/configuration.php-dist

**Closed by zero-24** 2015-04-29 22:11 UTC
Labels: No Code Attached Yet
