### ISSUE TITLE
Descriptions of extensions in the administration are not displayed

### ISSUE THREAD

**Issue by philigrane** [joomla/joomla-cms#43712] opened 2024-06-26 16:20 UTC
Joomla 4.4.5

The descriptions of my extensions and also others are not displayed.
For example in the module Login Form there are no descriptions.

There is a d-none class that prevents their display.
This is in: Joomla> Form> Renderfield.php at line 40.
"$descClass = ($options['descClass'] ?? '') ?: (!empty($options['inlineHelp']) ? 'hide-aware-inline-help d-none' : '');"

without the class d-none
![Capture d’écran 2024-06-26 à 18 11 53](https://github.com/joomla/joomla-cms/assets/9150840/30c96286-b824-4325-96fd-0a8f849f26a1)

With the class d-none
![Capture d’écran 2024-06-26 à 18 14 43](https://github.com/joomla/joomla-cms/assets/9150840/9e5b730a-0f7a-4ac5-97b1-cfc83a131b48)

What solution except to manually modify this file.
Regards

**Comment by drmenzelit** [comment] 2024-06-27 05:22
That is intended behavior: to reduce the amount of information in forms the help is hidden by default, if you click on the button "Toggle Inline Help" the description will be displayed.
Closing the issue because it is expected behavior.

**Closed as completed by drmenzelit** 2024-06-27 05:22 UTC
Labels: No Code Attached Yet
