### ISSUE TITLE
REGRESSION com_contact - menu item not saved

### ISSUE THREAD

**Issue by nzimas** [joomla/joomla-cms#7308] opened 2015-07-01 20:23 UTC
Steps to reproduce:

1. Create new menu item
2. Choose Contacts > List Contacts in a Category	
3. Add a title to the menu item
4. Save the menu item

Desired result:
Menu item should be stored on the DB and the menu item title should show in the Title input field.

Actual result:
The menu item is not saved, the title field is blank and a warning message is thrown.

Server environment:
Joomla 3.4.2
MySQL 5.5.43
PHP 5.5.9
Apache 2,4.c

Client environment:
Safari 8.0.7 on Mac OSX 10.9

Screenshot:
https://www.dropbox.com/s/ki0h6ilckkfkxpi/Screenshot%202015-07-01%2021.14.52.png?dl=0

**Comment by brianteeman** [comment] 2015-07-01 22:06
I an confirm this issue. 

I wonder if the root cause of this is the same as with #7309<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7308">issues.joomla.org/joomla-cms/7308</a>.</sub>

**Comment by zero-24** [comment] 2015-07-02 06:28
Closing as we have a PR at https://github.com/joomla/joomla-cms/pull/7312 please test there

**Closed by zero-24** 2015-07-02 06:28 UTC
