### ISSUE TITLE
Not correct "Count Module positions"

### ISSUE THREAD

**Issue by radik10** [joomla/joomla-cms#6007] opened 2015-02-07 10:03 UTC
#### Steps to reproduce the issue
Publish "Syndication Feeds Module" or "Similar Tags Module" in Protostar template in to the position-7 or position-8. Other modules unpublish from those positions. 
If this module has empty results (= not displayed module), that module position can't be calculated (and must be ignored) by Joomla! 3.3.6.

#### Expected result
With blank/empty results of those modules (e.g. no RSS in article view), mean if is RSS module in position-7 or position-8 (left or right sides of template) is empty, that positions should not be displayed (calculated), But now Joomla! 3.3.6 is displaying empty module position-7 or position-8 as blank column, but that column of template should not be visible (in case you don't have other modules in that position).

#### Actual result
Blank columns if you have in Protostar template published (in positon-7,8) only RSS or Similar tags modules. But it is not bug of Protostar template, it is bug of Joomla when is calculating positions. 

#### System information (as much as possible)
Database Version: 	5.5.25a
Database Collation: 	utf8_general_ci
PHP Version: 	5.4.4
Web Server: 	Apache/2.4.2 (Win32) OpenSSL/1.0.1c PHP/5.4.4
WebServer to PHP Interface: 	apache2handler
Joomla! Version: 	Joomla! 3.3.6 Stable [ Ember ] 01-October-2014 02:00 GMT
Joomla! Platform Version: 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent: 	Mozilla/5.0 (Windows NT 5.1; rv:35.0) Gecko/20100101 Firefox/35.0 

#### Additional comments
It is annoying to have empty columns in template (in case that RSS or similar tags modules have empty resaults and are only ones in that positions).

**Comment by rdeutz** [comment] 2015-02-07 10:26
This is the behaviour since Joomla 1.5 (maybe 1.0) so this is at least something we can't change now, but I agree it would be great if we could extend it so that the count respect if there is content or not.

**Comment by brianteeman** [comment] 2015-02-07 11:08
I disagree that an empty module should equal a non existing module. They
are not the same thing.

If I build a site and put a module in a position I must be able to see
where it is displayed, and how that effects the site layout, even before it
has any content.

Secondly do you really want to have your site layout constantly changing
because of the content of a module. Eg feed present you have 2 columns.
Feed empty you have 1 column.

**Comment by brianteeman** [comment] 2015-02-07 13:12
Reset priority https://docs.joomla.org/Bug_and_Issue_Tracker_Priority<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6007">issues.joomla.org/joomla-cms/6007</a>.</sub>

**Comment by wilsonge** [comment] 2015-02-08 02:22
I should also add the entire premise of nonumbers nothing module depends on this behaviour (empty module means position is filled. So this is definitely not something we can do in a b/c fashion. I'm going to close this as expected behaviour

**Closed** 2015-02-08 02:22 UTC
Labels: No Code Attached Yet

**Comment by radik10** [comment] 2015-02-08 06:28
Hi guys, I think, Joomla must be customizable as much as possible... and not to put barriers in webpage development... Joomla now is not enough flexible, is extremely complicated.

brianteeman said:
"If I build a site and put a module in a position I must be able to see where it is displayed, and how that effects the site layout, even before it has any content."
--- my reply: it is not problem, because you can see modules in their positions with template preview (www.webpage.xx/index.php?tp=1&templateStyle=yy)
 
"Secondly do you really want to have your site layout constantly changing because of the content of a module. Eg feed present you have 2 columns. Feed empty you have 1 column."
--- my reply: where is problem? module positions are counted for every genarated page/subpage during their loading... there is only 1 more step (to determine if any module have any content in left/right columns and close or not that module position/column), thats all.

**Comment by rdeutz** [comment] 2015-02-08 10:56
As already said, the behaviour can't be change now, but you could add a parameter countEmptyModules=true to the function. @radik10 would you make a PR?

**Comment by radik10** [comment] 2015-02-08 14:14
Sorry, I am not sure what is "PR". But I have solved my problem by moving the module to another module position (outside the left and right columns in template). 
Thanks.

**Comment by mbabker** [comment] 2015-02-08 15:25
> "Secondly do you really want to have your site layout constantly changing because of the content of a module. Eg feed present you have 2 columns. Feed empty you have 1 column."
> --- my reply: where is problem? module positions are counted for every genarated page/subpage during their loading... there is only 1 more step (to determine if any module have any content in left/right columns and close or not that module position/column), thats all.

The problem with doing that is now you have an inconsistent layout on your page.  It would be entirely possible for columns to disappear which would affect your page's appearance, potentially in a negative manner.  I think the behavior right now is accurate personally, when countModules is called, it is **NOT** rendering any modules but rather counting the number of active modules in a position for a given page (based on published modules and menu assignments).  In almost every case I am aware of where that method is used, it is called before we start rendering the module position a count is requested for.  It is not aware of the module's output, nor are any of our existing API methods.  To account for your scenario, countModules would have to render the modules in a position which would be a breaking change in behavior for the method and give it a purpose it was not written to serve.
