### ISSUE TITLE
Multilanguage site issue.

### ISSUE THREAD

**Issue by Handy84** [joomla/joomla-cms#11159] opened 2016-07-16 17:51 UTC
#### Steps to reproduce the issue
Setup a multilanguage Joomla 3.6.0 site with 2 languages 
1. Switch with the language module from the default language to the other language.
2. Switch back to the default language.
3. Switch again to the other language. (this triggers something in the cached browser files)
4. Try to select the default language. (my screen flashes but nothing is happening)

#### Expected result
A switch back to the default language.

#### Actual result
Now you are stuck in the last choosen language, unless you clear your browser cache.
I detected this bahaviour on different Joomla sites I created. Which formerly works correct (before the update to Joomla 3.6.0)
Tested this in IE Chrome and Firefox.

#### System information (as much as possible)
Joomla 3.6.0
php version 7.0.8
I am using browsercaching by ExpiresByType.
The domain: http://www.handysplace.nl

#### Additional comments
In my case I have default language Dutch and another language English.

**Comment by andrepereiradasilva** [comment] 2016-07-16 18:23
same as https://github.com/joomla/joomla-cms/issues/11143 ?

**Comment by Handy84** [comment] 2016-07-16 19:01
I claim this is not the same issue as #11143 because after I switched twice to English I can't visit my dutch home page anymore unless I first clear the browser cache!
Visits from my browser will always go to the http://www.handysplace/en language even if I visit http://www.handysplace.nl/nl it will rewrite to /en.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11159">issues.joomla.org/joomla-cms/11159</a>.</sub>

**Comment by andrepereiradasilva** [comment] 2016-07-16 19:02
the problem is the cached 301 redirect right?

**Comment by ggppdk** [comment] 2016-07-16 19:03
Same reason,

- but this time more problematic effect, issue #11143 is rather minor
- language switching of home-page, is impossible if you enable "**Remove URL Language Code**", 
which **removes language code for default language**

**at least if you are at a non-home page url the language switching will work**,

so in great majority of web-sites, users will be able to switch language
- thus it is not urgent, but really needs to be fixed
- the bad is that as time passes more websites are telling browsers to cache the home page redirect permanently (if website has enabled "**Remove URL Language Code**") 

to see the effect look at the picture

you visit /nl/ 
it is redirected permanently to /
which then redirects permanently to /en/

![redirect2](https://cloud.githubusercontent.com/assets/5092940/16896538/48b6eebc-4b9f-11e6-810c-07c069b4043a.png)

![redirect3](https://cloud.githubusercontent.com/assets/5092940/16896539/4c94450c-4b9f-11e6-873e-31ea44719e4e.png)

**Comment by ggppdk** [comment] 2016-07-16 19:06
@Handy84 
Please, see my above description and check the parameter,

Please note that after disabling the parameter,
**the effect will not go away**
unless you force the browser to clear its cache

**Comment by andrepereiradasilva** [comment] 2016-07-16 19:42
i think there are two options:
1. Send HTTP header to remove browser cache from 301 redirect
2.  Use a 302 or 303 redirect (doesn't cache) but less SEO

Anyway the changes are in here https://github.com/joomla/joomla-cms/blob/staging/plugins/system/languagefilter/languagefilter.php#L397-L402

For 301 with no cache i think prepending this lines would work
```php
$this->app->setHeader('Cache-Control', 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0');
$this->app->setHeader('Expires', 'Mon, 26 Jul 1997 05:00:00 GMT');
$this->app->sendHeaders();
```

**Comment by Handy84** [comment] 2016-07-16 20:10
I have implemented those lines and it's working, big thumbs up !

**Comment by andrepereiradasilva** [comment] 2016-07-16 22:45
please test https://github.com/joomla/joomla-cms/pull/11161

**Comment by infograf768** [comment] 2016-07-17 06:42
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11159">issues.joomla.org/joomla-cms/11159</a>

**Comment by infograf768** [comment] 2016-07-17 06:42
Closed as we have a patch . https://issues.joomla.org/tracker/joomla-cms/11161<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11159">issues.joomla.org/joomla-cms/11159</a>.</sub>

**Closed by infograf768** 2016-07-17 06:42 UTC
Labels: No Code Attached Yet

**Comment by simbus82** [comment] 2016-10-31 15:12
I have the same problem with Joomla 3.6.4, but i have a modified htaccess with:

```
# EXPIRES CACHING #
<IfModule mod_expires.c>
	ExpiresActive On
	ExpiresDefault "access plus 2 days" <------ AFTER REMOVE IT, PROBLEM SOLVED.
	ExpiresByType image/jpg "access plus 1 year"
	ExpiresByType image/jpeg "access plus 1 year"
	ExpiresByType image/gif "access plus 1 year"
	ExpiresByType image/png "access plus 1 year"
	ExpiresByType text/css "access plus 1 month"
	ExpiresByType application/x-font-woff "access plus 1 month"
	ExpiresByType application/pdf "access plus 1 month"
	ExpiresByType video/mp4 "access plus 1 month"
	ExpiresByType text/js "access plus 1 month"
	ExpiresByType text/javascript "access plus 1 month"
	ExpiresByType application/javascript "access plus 1 month"
	ExpiresByType application/x-javascript "access plus 1 month"
	ExpiresByType application/x-shockwave-flash "access plus 1 month"
	ExpiresByType image/x-icon "access plus 1 year"
</IfModule>
```

If i remove "ExpiresDefault "access plus 2 days"" the problem is solved.
How can i be more specific with expires without breaking the multilanguage cache control?

Thanks

**Comment by andrepereiradasilva** [comment] 2016-10-31 15:23
if you are caching all html pages in browser for 2 days you will have issues more problematic than this.

Anyway you can't change the joomla cache http headers for 301/302/303 redirects with your webserver for the language filter to work fine.

**Comment by simbus82** [comment] 2016-10-31 17:44
You are right, this is an old setup not valid with Joomla. Thanks!
