### ISSUE TITLE
Warning when no custom fields

### ISSUE THREAD

**Issue by joeforjoomla** [joomla/joomla-cms#13313] opened 2016-12-21 10:01 UTC
![warnings](https://cloud.githubusercontent.com/assets/17835460/21384944/d172098c-c76c-11e6-93ec-0d55627b910b.PNG)

**Comment by Bakual** [comment] 2016-12-21 11:06
What did you do to get to this? Are there any steps to reproduce it?

I think I can see the source of it but don't know yet how to reproduce it.

**Comment by joeforjoomla** [comment] 2016-12-21 14:25
I did nothing, just install a fresh Joomla 3.7 without any custom field created.
The foreach gets a non-array so there is the warning.

**Comment by joeforjoomla** [comment] 2016-12-21 14:26
As a side note there is even this issue
![fields](https://cloud.githubusercontent.com/assets/17835460/21392789/d6ec6798-c791-11e6-8c38-700b97c079fa.PNG)

**Comment by Bakual** [comment] 2016-12-21 15:01
Did you use latest staging (or the alpha1) to create that installation and created a fresh database for it? Because the field should have been created with that SQL: https://github.com/joomla/joomla-cms/blob/staging/installation/sql/mysql/joomla.sql#L643

**Comment by Bakual** [comment] 2016-12-21 15:09
I've tried deleting all entries in all fields related tables and can't reproduce this error.

**Comment by zero-24** [comment] 2016-12-21 20:36
> I did nothing, just install a fresh Joomla 3.7 without any custom field created.

hmm i have a alpha1 here and i can't reproduce this too. Can you please double check that on a clean installation with a clean database too. As we are allowed to do breaking chnages between dev and alpha versions etc ;)

Also can you tell us which page do you visite on the frist screenshot? The single article view or something different?

**Comment by franz-wohlkoenig** [comment] 2017-02-01 15:07
@joeforjoomla can't get your Issue. Is issue on latest staging too?

**Comment by Bakual** [comment] 2017-02-01 15:23
I'm closing this for now since nobody seems to be able to reproduce it. Feel free to reopen if it's still an issue with latest staging.

**Closed by Bakual** 2017-02-01 15:23 UTC
Labels: No Code Attached Yet
