### ISSUE TITLE
Package Uninstallation - Call to a member function attributes() on null

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/joomla-cms#22431] opened 2018-09-28 17:30 UTC
### Steps to reproduce the issue

1. Install an extension with a package
2. Uninstall it

### Expected result

No error

### Actual result

Call to a member function attributes() on null

### System information (as much as possible)

Joomla 3.9 Beta 3

**Comment by anibalsanchez** [comment] 2018-09-28 17:34
As a workaround, disable "Action Log - Joomla" plugin.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22431">issues.joomla.org/tracker/joomla-cms/22431</a>.</sub>

**Comment by mbabker** [comment] 2018-09-28 17:37
Duplicate of #22237

**Closed as completed by mbabker** 2018-09-28 17:37 UTC
Labels: No Code Attached Yet
