### ISSUE TITLE
jInsertEditorText broken in TinyMCE

### ISSUE THREAD

**Issue by Bakual** [joomla/joomla-cms#18121] opened 2017-09-26 11:03 UTC
### Steps to reproduce the issue
Try to use the ARS button in TinyMCE.

### Expected result
I cna insert an ARS item

### Actual result
Nothing happens

### Additional comments
I get a console error:
![ars](https://user-images.githubusercontent.com/1018684/30856981-696567c4-a2ba-11e7-9169-10d507e018d4.png)
According to @nikosdion this is caused by a backward incompatible API break in the editor. See https://github.com/akeeba/release-system/issues/126#issuecomment-332128453 for his explanation.

**Comment by dgrammatiko** [comment] 2017-09-26 12:08
@Bakual is the form that contains the editor field rendered through jform?

**Comment by nikosdion** [comment] 2017-09-26 12:22
I have only tried and succeeded to reproduce the issue with com_content (which uses JForm). However, how you display the editor should not break the API used by editor-xtd plugins to insert raw content into it.

**Comment by Bakual** [comment] 2017-09-26 19:45
@dgt41 Tested with an article (com_content) as well as a category description in Akeeba Release System (com_ars). It's the same in both.

**Comment by dgrammatiko** [comment] 2017-09-26 20:42
Hmm strange, how about moving these lines: https://github.com/joomla/joomla-cms/blob/staging/media/editors/tinymce/js/tinymce.js#L12-L15 after line 107?

**Comment by Bakual** [comment] 2017-09-26 21:03
Didn't work for me, but not sure if I did it right. JS is all magic to me. 😄

**Comment by dgrammatiko** [comment] 2017-09-26 21:06
you still need to compress that file or use debug mode

**Comment by dgrammatiko** [comment] 2017-09-27 08:14
It turns out that it wasn't the core in this case
<img width="825" alt="screen shot 2017-09-27 at 10 03 10" src="https://user-images.githubusercontent.com/3889375/30902435-94f03fe8-a36b-11e7-9405-456087c552ce.png">

The `editor` variable that is passed to the function has way too many quotes, so in arslink.php (the xtd-button) the js part should be:
```js
		$js = <<<JS


;// This comment is intentionally put here to prevent badly written plugins from causing a Javascript error
// due to missing trailing semicolon and/or newline in their code.
		function arsSelectItem(id, title) {
			var tag = '<a href='+'\"index.php?option=com_ars&amp;view=Item&amp;id='+id+'\">'+title+'</a>';
			jInsertEditorText(tag, '$name');
			jModalClose();
		};

JS;
```

**Comment by nikosdion** [comment] 2017-09-27 08:34
Why had this code been working ever since Joomla! 1.5.15 without a problem? Or why did JCE never had an issue with it? You can see the version history in https://github.com/akeeba/release-system/commits/development/plugins/editors-xtd/arslink/arslink.php  The code is untouched since 2012. In fact it's untouched for much longer, I just didn't care enough to import older SVN history to Git :)

**Comment by dgrammatiko** [comment] 2017-09-27 08:51
@nikosdion you used to have the javascript wrapped in double quotes till bda0d61afa7ee66a8c707b675450f74fe51bdc4b then you switched to `<<<JS` but you forgot to take out the extra unneeded double quote an the dots from that variable. Why does this work with other editors? I have no clue, but honestly I find it extremely weird that this line actually resolves correctly the id in any js script

**Comment by zero-24** [comment] 2017-09-27 17:42
Closing as a vendor Problem.. thanks.

**Closed as completed by zero-24** 2017-09-27 17:42 UTC
Labels: No Code Attached Yet
