### ISSUE TITLE
[4.0] Misssing margins for Buttons on Edge

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#28856] opened 2020-04-28 09:42 UTC
### Steps to reproduce the issue
Use the Browser Edge for Joomla V4

### Expected result
Buttons and Buttongroups are separated by a small margin as in firefox or chrome

### Actual result
![buttons-edge](https://user-images.githubusercontent.com/1035262/80472344-e1f60680-8944-11ea-846d-970767de1a2e.JPG)

### System information (as much as possible)
win10, Browser Edge, latest version

**Comment by jwaisner** [comment] 2020-04-28 15:09
Confirmed. That and many more issues when using Edge.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28856">issues.joomla.org/tracker/joomla-cms/28856</a>.</sub>

**Comment by brianteeman** [comment] 2020-04-28 21:49
This is not the latest version of Edge. This is the version of edge before the switch to chromium. With the actual latest version which is Version 81.0.416.64 (Official build) (64-bit) there is no problem

![image](https://user-images.githubusercontent.com/1296369/80541139-8eb2a100-89a2-11ea-99b3-4f584260c2c1.png)

**Comment by ReLater** [comment] 2020-04-29 08:26
On my Windows 10 the version is:
Microsoft Edge 44.18362.449.0
Microsoft EdgeHTML 18.18363

Therefore it looks like Windows 10 didn't update yet to chromium on all installations. The rest is obscurity...

**Comment by ReLater** [comment] 2020-04-29 08:51
Confirmed with version like mentioned in https://github.com/joomla/joomla-cms/issues/28856#issuecomment-621061699

**Comment by chmst** [comment] 2020-04-29 09:10
Downloaded and installed the latest Version manually - now it looks all right for me. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28856">issues.joomla.org/tracker/joomla-cms/28856</a>.</sub>

**Comment by ReLater** [comment] 2020-04-29 09:32
And now tell the users "you first have to update this or that before you can use Joomla 4"?

Let's hope that the chromium version will be the final state when J4 is released. Because the EdgeHTML has not been abandoned yet. It's still a current Edge version on many WIN systems.

**Comment by brianteeman** [comment] 2020-10-02 12:42
This should be closed as the chromium version of edge is now available for everyone automatically

**Comment by HLeithner** [comment] 2020-10-02 13:05
EOL of edge legacy is 9.3.2021

**Closed as completed** 2020-12-03 22:57 UTC
