### ISSUE TITLE
Creation of override for module or component fails

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#5926] opened 2015-01-29 18:08 UTC
The creation of an override for a module or a component fails under windows (in my case using ampps under win7). Layout overrides though can be created. Under linux everything is fine.

![template_override](https://cloud.githubusercontent.com/assets/9270310/5963163/1ee5c590-a7ea-11e4-90fe-cbce34a15a51.png)

**Comment by fcschippers** [comment] 2015-04-10 13:51
With Xampp I can't reproduce this problem; a known issue with Xampp is the location for Xampp. If Xampp is installed in the program files(x86) map you might get issues with UAC rights. With Xampp it's adviced to place the Xampp map in the root of your harddrive.
You could try to reinstall your Ammps in the root of your harddrive in stead of the current location (as a sub folder from the program files folder).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5926">issues.joomla.org/joomla-cms/5926</a>.</sub>

**Comment by brianteeman** [comment] 2015-08-07 13:11
After considerable time without any further comment or reports I am closing this.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5926">issues.joomla.org/joomla-cms/5926</a>.</sub>

**Closed** 2015-08-07 13:11 UTC
Labels: No Code Attached Yet
