### ISSUE TITLE
[5.0] clear cache doesnt

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#41404] opened 2023-08-20 12:19 UTC
### Steps to reproduce the issue
Turn on cache
Check contents of cache folder
system -> clear cache
delete cache files
Check contents of cache folder

### Expected result
system->cache reports the same as in the physical folder

### Actual result
system->cache doesnt report all files

see video

https://github.com/joomla/joomla-cms/assets/1296369/db71b03a-73d4-465b-89d5-2a7f57f303bf

### Additional comments
the cli cache:clean does remove all the files

**Comment by HLeithner** [comment] 2023-08-20 15:17
That's expected behavior.

1. you see all cached files, like in the file browser
2. you click on clean (all)
3. Joomla deleted all files
4. you get redirected to the cache view and you see only the files created till joomla does ask the cache what cache files exists
5. joomla creates addition cache entries
6. you reload the page
7. you see the entries created in point 5

the reason you don't have this in the CLI is because you didn't trigger a page redirect (see point 4.)

I'm closing this.

**Closed as completed by HLeithner** 2023-08-20 15:17 UTC
Labels: No Code Attached Yet
