### ISSUE TITLE
[4.0] Invisible Articles - Categories module

### ISSUE THREAD

**Issue by adj9** [joomla/joomla-cms#29426] opened 2020-06-04 19:54 UTC
### Steps to reproduce the issue
Create an Articles - Categories module.
I use the default template.
The Demo article is part of Joomla's default category.

### Expected result
I expect to see the

### Actual result
Invisible Articles - Categories modele
### Front end
<img width="1250" alt="Schermata 2020-06-04 alle 21 41 24" src="https://user-images.githubusercontent.com/5918444/83803157-62c6c180-a6ac-11ea-97c9-172e6a7453a8.png">
### Back end
<img width="1317" alt="Schermata 2020-06-04 alle 21 44 51" src="https://user-images.githubusercontent.com/5918444/83803457-e2ed2700-a6ac-11ea-9b18-bba7ef57170b.png">

### System information (as much as possible)
- Web site
- Safari 13.0.5
- macOS Catalina 10.15.3

**Comment by SharkyKZ** [comment] 2020-06-04 20:15
Did you create any child categories for `Uncategorised` category?

**Comment by ceford** [comment] 2020-06-05 02:06
I see exactly this too. I made Blog (en-GB) the Parent Category and assigned the module to the left column. The left column appears completely empty as illustrated.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29426">issues.joomla.org/tracker/joomla-cms/29426</a>.</sub>

**Comment by infograf768** [comment] 2020-06-05 05:48
As @SharkyKZ says, this displays the CHILDREN Categories from a defined Parent category.
If you have no child category, the module will not display.

<img width="992" alt="Screen Shot 2020-06-05 at 07 45 07" src="https://user-images.githubusercontent.com/869724/83841197-acd99280-a700-11ea-9437-f1b80e5b6eaf.png">

<img width="809" alt="Screen Shot 2020-06-05 at 07 45 46" src="https://user-images.githubusercontent.com/869724/83841208-b236dd00-a700-11ea-95ca-15d775469a61.png">

<img width="944" alt="Screen Shot 2020-06-05 at 07 46 10" src="https://user-images.githubusercontent.com/869724/83841217-b8c55480-a700-11ea-908b-9c2fa0b1de4f.png">

Closing as not a bug

**Closed as completed by infograf768** 2020-06-05 05:48 UTC
Labels: No Code Attached Yet
