### ISSUE TITLE
[com_fields] 'Show Label'  - > 'Hide' has no effect in contact and (user) profile views

### ISSUE THREAD

**Issue by nordmograph** [joomla/joomla-cms#15304] opened 2017-04-14 15:49 UTC
### Steps to reproduce the issue
Create a new field in Joomla contacts or Joomla users. In field settings, Options tab, set the 'Show Label' option to 'Hide'

### Expected result
The field label should not be displayed when the field is rendered in contact and profile views (default layouts) (working as expected in Articles)

### Actual result
Field Label keeps showing

**Comment by franz-wohlkoenig** [comment] 2017-04-14 15:54
Issue confirmed.
### System information
3.7.0-rc2 (nightly Build)
macOS Sierra, 10.12.4
Firefox 52 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by AlexRed** [comment] 2017-04-14 20:45
Seems related to #14377  #15244
Unfortunately currently is not possible to change the Field parameter for a context (com content, com user, com contact or external component)

**Comment by Bakual** [comment] 2017-04-14 20:50
Nope, this is not related to the other issues. It's just that com_contact has an override for the field layout and that one doesn't check the label parameter.
See https://github.com/joomla/joomla-cms/blob/staging/components/com_contact/layouts/field/render.php
I don't know about the user one, that one should use the regular layout as far as I know.

The regular JLayout is this one: https://github.com/joomla/joomla-cms/blob/staging/components/com_fields/layouts/field/render.php

**Comment by AlexRed** [comment] 2017-04-14 20:53
oppsss...  sorry
then a new bug for the custom fields

**Comment by nordmograph** [comment] 2017-04-14 21:20
Well com_users doesn't use an override yet for the field layout it doesn't use either the regular JLayout

At least it can be easily addressed for com_contact <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15304">issues.joomla.org/tracker/joomla-cms/15304</a>.</sub>

**Comment by laoneo** [comment] 2017-04-15 05:36
If I'm not wrong, but com_users uses JForm to show the fields. It has a totally different behavior than com_contact. But yes, com_contact should have the same behavior as com_content.

**Comment by zero-24** [comment] 2017-04-21 14:11
@laoneo can you do than a PR for fix the com_contact behavior?

**Comment by laoneo** [comment] 2017-05-03 09:03
Please test the pr #15756 which should fix the contact label hide issue.

**Comment by franz-wohlkoenig** [comment] 2017-05-03 09:16
closed as having PR #15756<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15304">issues.joomla.org/tracker/joomla-cms/15304</a>.</sub>

**Closed by franz-wohlkoenig** 2017-05-03 09:16 UTC
Labels: No Code Attached Yet

**Comment by AlexRed** [comment] 2017-05-16 08:24
but the PR is only for the contact, the problem is also in the user, please reopen.

**Comment by laoneo** [comment] 2017-05-16 08:27
As already said, the profile view is a form and has a totally different set up. I suggest to open a new issue for that one as the logic is very different then the rest of Joomla.
