### ISSUE TITLE
[4.0] Password - Minimum Length

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#30397] opened 2020-08-17 11:08 UTC
### Steps to reproduce the issue

1. Go to `administrator/index.php?option=com_config&view=component&component=com_users`
2. Navigate to the "Password Options" tab
3. Change the `Minimum Length` parameter to `7` or below, by **typing** it in
4. Click `save`

### Expected result

- Allow me to set a value below 8

or:

- Display inline error

or:

- prevent keystrokes in the field

### Actual result

Value defaults back to 12

### Additional comments

Having used the input arrows to decrease the number, I can see that `8` is the mimimum.
I dont mind the default as 12, but it should not be up to Joomla to force a minimum length like this....even for development on a localhost.

**Comment by Quy** [comment] 2020-08-17 15:22
Related #30282

**Comment by roland-d** [comment] 2020-08-17 20:05
The issue #30282 is not related, it just uses this feature to show a bug in the system. It could have been any other feature that does form validation.

Issue #29859 is the implementation of this feature.

**Comment by ceford** [comment] 2020-10-10 14:48
I think that com_config/src/controller/ComponentController.php needs return false; on line 120.

**Comment by HLeithner** [comment] 2020-10-18 14:33
That's expected behavior because 8 chars are the minimum password length. One of the main reasons for this is that even on localhost and especially local development get deployed on live systems.

If you really want a insecure password you have to write a plugin to override the limitation settings.

**Comment by C-Lodder** [comment] 2020-10-18 15:11
@HLeithner I don't care if it's expected or not. If you don't allow 7 character passwords, display an inline alert. This is simple UX.
A blind user will have a nightmare trying to fill this form in.

Please re-read the issue. I'm not raising an issue about the actual minimum length required for a password. I'm raising an issue because the page allows you to save a min value that isn't actually allowed, with no warning whatsoever.

**Comment by HLeithner** [comment] 2020-10-18 15:23
Ok sorry then the validator should be fixed but I would expect that a screenreader notifies the user about the min and max attributes.

**Comment by brianteeman** [comment] 2020-10-18 16:01
#30906 came close to fixing this as it gave the error message but it didnt stop the form also saying it was successfuly saved

**Comment by Quy** [comment] 2021-11-19 22:48
Fixed in #31105.

**Closed as completed by Quy** 2021-11-19 22:48 UTC
Labels: No Code Attached Yet
