### ISSUE TITLE
Problems loading module inside article with {loadmodule} if there is a whitespace character in the end

### ISSUE THREAD

**Issue by PixedBo** [joomla/joomla-cms#18664] opened 2017-11-18 14:47 UTC
### Steps to reproduce the issue

Create a custom module and name it something with a white space in the end, like "Something ". Then go inside an article and load a module from the button "Load module", and select the "Something " module.

### Expected result

The module is loaded in the article

### Actual result

Nothing shows up

### System information (as much as possible)

Joomla 3.8.2 with nothing installed except the core

### Additional comments

The problem is caused by the white space:
- The module has the name "Something " 
- The loadmodule button writes "{loadmodule mod_custom,something }" with the whitespace at the end
- I think that the whitespace is ignored so the module is not loaded
- If i modify the code "{loadmodule mod_custom,something}" without the whitespace the module is not loeade either
- If i remove the whitespace from the code "{loadmodule mod_custom,something}" AND from the module title it works again

I think it's important to fix because with copy/paste of the module name is easy to get a whitespace in the end of the name.

**Comment by ghost** [comment] 2017-11-18 15:00
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18664">issues.joomla.org/tracker/joomla-cms/18664</a>.</sub>

**Comment by infograf768** [comment] 2017-11-20 11:13
I guess the only way to solve this is preventing a module Title do be saved with whitespaces.
Patch is easy to do, but it may not be B/C.

```
diff --git a/administrator/components/com_modules/models/module.php b/administrator/components/com_modules/models/module.php
index 206cac8..8458163 100644
--- a/administrator/components/com_modules/models/module.php
+++ b/administrator/components/com_modules/models/module.php
@@ -919,4 +919,6 @@
 		}
 
+		$data['title'] = JFilterInput::getInstance()->clean($data['title'], 'TRIM');
+
 		// Alter the title and published state for Save as Copy
 		if ($input->get('task') == 'save2copy')
```

**Comment by brianteeman** [comment] 2017-11-20 11:44
I doubt it would be b/c if you can currently save a module title with trailing spaces. you never know what a user might do.

**Comment by tonypartridge** [comment] 2017-11-21 00:16
The only solution I can see, is for the loadmodule to allow white spaces, if you trim the module title now it would be a B/C since users may have been using white space, I know very unlikely but still...

**Comment by brianteeman** [comment] 2017-12-22 23:14
@tonypartridge do you think you clouod take a look at this one as well - please

**Comment by tonypartridge** [comment] 2017-12-22 23:38
Ok Ok, so I can make it work with spaces but can see why it's done as it is. 

I suggest we leave as is because of the BC and apply @infograf768 patch to J4.

**Comment by ReLater** [comment] 2019-04-19 14:12
Is this issue still dramatically relevant for Joomla **3**? The module button now inserts `{loadmoduleid 123}` when you click on the title of the module but not the title.

**Comment by alikon** [comment] 2019-04-19 14:26
can be closed indeed

**Closed as completed** 2019-04-19 14:27 UTC
Labels: No Code Attached Yet
