### ISSUE TITLE
[4.0] Menu: Unable to select single article

### ISSUE THREAD

**Issue by beedaddy** [joomla/joomla-cms#30065] opened 2020-07-10 10:18 UTC
### Steps to reproduce the issue
1. Create an article
2. Create a menu item
3. Set menu item type to "single article"
4. Try to select the article

### Expected result
The article can be selected and is used as single article for the menu.

### Actual result
It's not possible to select the article. You can only close the selection dialog.

### System information (as much as possible)
- Joomla 4.0 beta 2 (fresh installation)
- PostgreSQL 11
- PHP 7.3

### Additional comments
I'm a Joomla newbie, but with Joomla 3.9, the above steps worked.

**Comment by ChristineWk** [comment] 2020-07-10 11:02
We had similar PRs: https://github.com/joomla/joomla-cms/pull/29860, https://github.com/joomla/joomla-cms/issues/29897
Merged 8 days ago. (4.0.0-dev3)
So, I'm not sure, if your version: 4.0 beta2 includes above, as implemented on June30th. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30065">issues.joomla.org/tracker/joomla-cms/30065</a>.</sub>
The bug was fixed after the release of beta2.

**Comment by toivo** [comment] 2020-07-10 11:42
Unable to reproduce the issue in 4.0 Beta3-dev.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30065">issues.joomla.org/tracker/joomla-cms/30065</a>.</sub>

**Comment by Quy** [comment] 2020-07-10 13:06
Duplicate #30055.  Please test with nightly builds: https://developer.joomla.org/nightly-builds.html

**Closed as completed by Quy** 2020-07-10 13:06 UTC
Labels: No Code Attached Yet
