### ISSUE TITLE
[4.4] Back-end Edit form(s): focus on the Title field is missing

### ISSUE THREAD

**Issue by pe7er** [joomla/joomla-cms#43684] opened 2024-06-20 15:21 UTC
When creating a new Article, Category, Menu Item, or Module in Joomla 4.4.5 and 5.1.1, 
the focus doesn't automatically land on the Title field.

### Steps to reproduce the issue
In the back-end, create a new Article, Category, Menu Item or Module. 

### Expected result
I would expect the mouse cursor to start in the first required Title field, 
so that I can begin typing a title right away.

![new-article-2](https://github.com/joomla/joomla-cms/assets/1217850/2e72b91a-3b34-412b-b391-329eda53cd00)

### Actual result
Instead, there's no focus on the Title field. 
You have to manually click in the Title field with your mouse 
or press the Tab key eight times on your keyboard.
Then the focus is on the Title field and you can start typing a title.

![new-article-1](https://github.com/joomla/joomla-cms/assets/1217850/29e6c8b6-0961-4271-8786-f741d0221374)
 
### Additional comments
For existing item the focus should probably not be on the Title when you open the item for editing.

**Comment by rdeutz** [comment] 2024-06-26 11:58
> That would create a whole bunch of accessibility issues

Could we use for new articles an id for the title field and use this in the edit link?

**Comment by brianteeman** [comment] 2024-06-26 12:57
the issue is for new articles not editing existing articles

**Comment by rdeutz** [comment] 2024-06-26 17:03
I know that's why I am asking

**Comment by brianteeman** [comment] 2024-06-26 17:17
The same accessibility issues would be present

**Comment by chmst** [comment] 2024-07-07 19:34
In this single case it would be possible to use the autofocus. But in consequence we would have a non consistent behaviour, because all other foms don't have autofocus. 
Autofocus is an issue for accessibility, as you can find in different publications.

Accessiblity and consisent behaviour has priority so I close this issue.

**Closed as completed by chmst** 2024-07-07 19:34 UTC
Labels: No Code Attached Yet, UI/UX

**Comment by pe7er** [comment] 2024-07-09 08:25
> Accessiblity and consisent behaviour has priority so I close this issue.

Agreed. Gary (thanks @Bodge-IT !) asked a Joomla user that uses a Screen Reader. 
They answered that **maintaining consistent focus behavior** in all areas of the Joomla back-end **is important for SR users** to avoid unnecessary confusion and frustration.
