### ISSUE TITLE
Translation bug in AJAX part of ACL manager

### ISSUE THREAD

**Issue by JurgenG** [joomla/joomla-cms#9968] opened 2016-04-18 08:53 UTC
#### Steps to reproduce the issue
1. Create a multilingual site (EN + NL)
2. Set admin language to different language.
3. Go to permissions tab of an article or a category (I'm assuming it will be everywhere)
4. Change settings.

#### Expected result

I expect the strings to remain in Dutch.

#### Actual result

You'll see how the current status - which is in Dutch at this moment - switches to English in the AJAX action.
See this small video if the explanation isn't clear (I will remove this video in 1 month from now):
https://dl.dropboxusercontent.com/u/7584025/troubleshooting.ogv

**Comment by brianteeman** [comment] 2016-04-19 10:08
Confirmed using en-gb and fr-fr<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9968">issues.joomla.org/joomla-cms/9968</a>.</sub>

**Comment by infograf768** [comment] 2016-04-28 05:45
Forgot to add that I confirm this too.

**Comment by infograf768** [comment] 2016-04-28 05:46
@dgt41 
Could you have a look at this, as it is js related?

**Comment by brianteeman** [comment] 2016-04-28 09:30
The problem is that the JS file uses english strings  https://github.com/joomla/joomla-cms/blob/staging/media/system/js/permissions.js#L58 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9968">issues.joomla.org/joomla-cms/9968</a>.</sub>

**Comment by infograf768** [comment] 2016-04-28 10:13
Preparing a PR

**Comment by brianteeman** [comment] 2016-04-28 10:14
lol - so was I - I will stop

On 28 April 2016 at 11:13, infograf768 <notifications@github.com> wrote:

> Preparing a PR
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9968#issuecomment-215377314>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by infograf768** [comment] 2016-04-28 10:28
https://github.com/joomla/joomla-cms/pull/10117

LOL

**Comment by brianteeman** [comment] 2016-04-28 10:30
Closed as we have a PR thanks

**Closed by brianteeman** 2016-04-28 10:30 UTC
Labels: No Code Attached Yet
