### ISSUE TITLE
Unable to process PNG image (Uncaught (in promise) Error)

### ISSUE THREAD

**Issue by cloudfaction** [joomla/joomla-cms#43889] opened 2024-08-07 06:45 UTC
### Steps to reproduce the issue

i have several png images that result in this error. and halt. nothing is shown.

### Expected result

have the media manager show all images.

### Actual result

for some reason the system halts, if there is only 1 image it cannot process, nothing is shown. it should only not show the image that it has issues with, but should show all other images.

### System information (as much as possible)

PHP 7.4.33
MySQLi 8.0.36
J 4.4.6

### Additional comments

media-manager.min.js?8e3a78d4ae3e1ccce3bedff2c951a25009d8e086:5 Uncaught (in promise) Error: [object XMLHttpRequest]
at media-manager.min.js?8e3a78d4ae3e1ccce3bedff2c951a25009d8e086:5:21404

**Comment by brianteeman** [comment] 2024-08-07 10:38
Without being able to test with your png it will be impossible to test

**Comment by Fedik** [comment] 2024-08-07 10:50
It is very likely the PNG resolution is high, or server memory limit is low, or both. 
In general, PHP GD need a lot of memory for large images.

**Comment by Fedik** [comment] 2024-08-07 10:58
Without detailed information it is hard to tel what is going on. There can be 1000 reasons.
Addittionaly to "Uncaught (in promise) Error" the browser may show actual error, sometimes.

> it should only not show the image that it has issues with, but should show all other images.

I do not think it is realy possible in Media manager.

**Comment by brianteeman** [comment] 2024-08-09 10:56
Unfortunately github probably changes the image when you upload it so we cant test with it. Perhaps you can zip the image and then share the zip - that might work

**Comment by cloudfaction** [comment] 2024-08-09 11:34
[ov002_02.png.zip](https://github.com/user-attachments/files/16560557/ov002_02.png.zip)
This is the zipped png file

**Comment by brianteeman** [comment] 2024-08-09 11:50
Thanks for doing that. Unfortunately I am unable to replicate your error. The only thing I can think of to check at this time is to see if you have the php extensions gd and fileinfo 

You can determine this by checking the system information available fropm the system dashboard

![image](https://github.com/user-attachments/assets/0ee942cf-4173-4d86-9f3e-e96c03f388fc)

**Comment by fgsw** [comment] 2024-08-09 11:54
@cloudfaction also using the new uploaded file i'm unable to reproduce the error you have reported:
![Untitled](https://github.com/user-attachments/assets/6080d01b-d0d6-4c55-8985-8a11615f5644)

**Comment by cloudfaction** [comment] 2024-08-09 11:56
[ov002_03.png.zip](https://github.com/user-attachments/files/16560798/ov002_03.png.zip)

my bad, it was this file.

**Comment by cloudfaction** [comment] 2024-08-09 11:57
> Thanks for doing that. Unfortunately I am unable to replicate your error. The only thing I can think of to check at this time is to see if you have the php extensions gd and fileinfo
> 
> You can determine this by checking the system information available fropm the system dashboard
> 
> ![image](https://private-user-images.githubusercontent.com/1296369/356581255-0ee942cf-4173-4d86-9f3e-e96c03f388fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMDQ4NjUsIm5iZiI6MTcyMzIwNDU2NSwicGF0aCI6Ii8xMjk2MzY5LzM1NjU4MTI1NS0wZWU5NDJjZi00MTczLTRkODYtOWYzZS1lOTZjMDNmMzg4ZmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDlUMTE1NjA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzVkZGQ2OGY4ZWI1YTI4YmEyNzJjNjgzY2FkYTYwZGJiYTVhYTI0NjVlMzZmZjY1MzZiMjg1MzljYzJjZDE0YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.f5e0oNy0nkr5jRxx4fN5FQFWssGqSdLjJ1z-09EOS3c)

both are the same as your screenshot.

**Comment by brianteeman** [comment] 2024-08-09 12:01
Still no problem with 003

If you open and save the file with another graphic program do you still have the problem?

**Comment by cloudfaction** [comment] 2024-08-09 12:14
no, it shows, but you can see that the bottom of the image is gone. the png is not faulty. but still it should not block my entire media manager, in my opinion.

**Comment by brianteeman** [comment] 2024-08-09 12:25
![image](https://github.com/user-attachments/assets/212d4148-cc0a-48a8-a0a4-6c40c3141f23)

I have opened the png in multiple programs and in 003 there is empty space in the bottom 2/3

**Comment by cloudfaction** [comment] 2024-08-09 12:27
yep it is. but that is not the point. i have a joomla install with the mediamanager stalling on this image. but if no one can reproduce this, i guess closing the issue is the best. thank you all for your efforts!

**Comment by brianteeman** [comment] 2024-08-09 15:17
Can someone close this as has been requested - thanks

**Closed as completed** 2024-08-09 15:19 UTC
Labels: No Code Attached Yet
