### ISSUE TITLE
[4 Alpha 12] inconsistent publishing behavior

### ISSUE THREAD

**Issue by blueforce** [joomla/joomla-cms#26693] opened 2019-10-19 12:28 UTC
### Steps to reproduce the issue
1. Go to Content > New Item and klick save
2. actual result: the item is unpublished per default
3. Go to menu > New Item and save
4. actual result: the item is published per default

### Expected result
new content items and menu items are published per default or unpublished per default

### Actual result
at the moment the behavior is inconsistent for content and menu on saving item

**Comment by simbus82** [comment] 2019-10-19 22:03
Ok for the consistent, but Published as default is wrong because in a normal Publishing Workflow is needed an explicit action by the editor user.

**Comment by SharkyKZ** [comment] 2019-10-31 09:06
This is the new Workflows feature in 4.0. You can change the default stage in the default Workflow or create an entire new Workflow. See documentation https://docs.joomla.org/Publishing_Workflow.

**Comment by SharkyKZ** [comment] 2019-10-31 09:07
Closed as expected behavior.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26693">issues.joomla.org/tracker/joomla-cms/26693</a>.</sub>

**Closed as completed by SharkyKZ** 2019-10-31 09:07 UTC
Labels: No Code Attached Yet
