### ISSUE TITLE
Banners SQL fails to install with Joomla! 3.4.8 -> Joomla! 3.5.1 Update when component removed

### ISSUE THREAD

**Issue by xtech86** [joomla/joomla-cms#9774] opened 2016-04-06 22:58 UTC
#### Steps to reproduce the issue
On Joomla! 3.4.8, uninstall the banners component
Upgrade Joomla! to 3.5.1
Go to Database Manager and click Fix tables
Fails, as the banners component is no longer installed. 

#### Expected result
No error should be returned. com_banners SQL should only be offered/run if the component is installed.

#### Actual result
Joomla! Database tool reports SQL out of sync and fails to sync the banners.

#### System information (as much as possible)

=============
System Information
=============
php: Linux SERVER1 2.6.32-531.29.2.lve1.3.11.1.el6.x86_64 #1 SMP Thu Dec 18 06:49:17 EST 2014 x86_64
dbversion: 5.5.48-cll
dbcollation: latin1_swedish_ci
dbconnectioncollation: utf8mb4_general_ci
phpversion: 5.4.36
server: Apache/2.2.29 (Unix) mod_ssl/2.2.29 OpenSSL/1.0.1e-fips mod_bwlimited/1.4
sapi_name: cgi-fcgi
version: Joomla! 3.5.1 Stable [ Unicorn ] 05-April-2016 22:45 GMT
platform: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/601.5.17 (KHTML, like Gecko) Version/9.1 Safari/601.5.17

=============
PHP Settings
=============
safe_mode: false
display_errors: false
short_open_tag: true
file_uploads: true
magic_quotes_gpc: false
register_globals: false
output_buffering: false
open_basedir: 
session.save_path: xxxxxx
session.auto_start: 0
disable_functions: 
xml: true
zlib: true
zip: true
mbstring: true
iconv: true
max_input_vars: 2500

#### Additional comments

<img width="1284" alt="screen shot 2016-04-06 at 23 59 36" src="https://cloud.githubusercontent.com/assets/1400982/14335495/acf57b5a-fc53-11e5-9783-a075089570ed.png">

**Comment by mbabker** [comment] 2016-04-06 23:01
Duplicate of https://github.com/joomla/joomla-cms/issues/8691

**Closed by mbabker** 2016-04-06 23:01 UTC

**Comment by xtech86** [comment] 2016-04-06 23:02
Thanks Michael, I couldn't find anything matching, at first sorry!
