### ISSUE TITLE
[4.0] Paths in configuration.php

### ISSUE THREAD

**Issue by AlekVolsk** [joomla/joomla-cms#24139] opened 2019-03-09 11:34 UTC
Windows server

Multidirectional slashes in the paths in configuration.php
```php
public $log_path = 'C:\\OSPanel\\domains\\j4.local\\administrator/logs';
public $tmp_path = 'C:\\OSPanel\\domains\\j4.local/tmp';
```
The same goes for global `JPATH_*` constants.

**Either use DIRECTORY_SEPARATOR constant or write `/` everywhere.**

**Comment by Septdir** [comment] 2019-03-09 11:38
OSPanel download link
https://ospanel.io/download/

**Comment by HLeithner** [comment] 2019-03-09 11:56
Php handles this correct so not a problem?

On windows the php api gives us \ as seperator and we add /tmp to this so it's a simple concat. The rest is done by php so no chance requiered.

But if you like to write a PR to rewrite \ to / it will be considered.

I closing this but you can always reopen it

**Comment by AlekVolsk** [comment] 2019-03-09 11:59
Well, now open it again, since PHP does not handle this correctly: try applying realpath or is_dir to this path and you will realize that it does not work

**Comment by b2z** [comment] 2019-03-09 12:36
@HLeithner so you confirm that '/' is a bug? On Windows it should be `\\`, right?

**Comment by brianteeman** [comment] 2019-03-09 14:07
My development system is windows
The paths on this system are written

`	public $log_path = 'C:\\htdocs\\joomla-cms\\administrator/logs';
`

Windows happily writes the logs into that directory.

So what is the problem that needs to be solved?

**Comment by AlekVolsk** [comment] 2019-03-09 14:26
There are extensions. who use this parameter for their own purposes and do not use Joomla classes to work with them, do not check for a platform delimiter. In addition, Joomla itself does not work correctly with these paths in JFile and JFolder, unless you previously run the values of the variables through `JPath::clean()`.

But who cares, you can not prove anything.

**Comment by HLeithner** [comment] 2019-03-09 14:29
can you give me an example component? that has this problem?

**Comment by brianteeman** [comment] 2019-03-09 14:30
whats the point in having an api if its not going to be used?

**Comment by HLeithner** [comment] 2019-03-09 14:42
there could be many reasons why you don't us the Joomla API, 
But I can't reproduce it:

```php
$path = 'c:\\temp\\test';
var_dump(is_dir($path));

$path = 'c:\\temp/test';
var_dump(is_dir($path));
```
```
C:\temp>c:\php\php test.php
C:\temp\test.php:5:
bool(true)
C:\temp\test.php:9:
bool(true)
```

@AlekVolsk and why do you delete your comments?

Oh you edit your issue, sry didn't notice this. Please make comments.

**Comment by roland-d** [comment] 2019-03-09 14:44
Long time Windows user. Never had a problem with paths like `C:\\OSPanel\\domains\\j4.local\\administrator/logs`

**Comment by HLeithner** [comment] 2019-03-09 15:04
The only problem I can think of at the moment is if you try to manipulate the path, f.ex. removing parts of it.

**Comment by mbabker** [comment] 2019-03-09 15:48
General bit of advice, any time a path is going to be shown to a user it's a good idea to run it through `JPath::clean()` which standardizes the directory separator.  So when saving config changes, putting these (and other configurable paths like the `cache_path` or in 4.0 the `session_filesystem_path`) through the API wouldn't hurt anything, but it clearly isn't something that's mandatory for PHP to work right.

**Comment by Septdir** [comment] 2019-03-09 15:54
Such paths are not a bug. But you must admit, this is not the correct one.

**Comment by jwaisner** [comment] 2020-04-17 14:56
Closing as it is expected behavior and does not effect operation of the CMS outside of what is expected.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24139">issues.joomla.org/tracker/joomla-cms/24139</a>.</sub>

**Closed as completed by jwaisner** 2020-04-17 14:56 UTC
Labels: No Code Attached Yet, J4 Issue
