### ISSUE TITLE
Joomla 3.5 Backward compatibility break: update without internet access stopped working

### ISSUE THREAD

**Issue by fititnt** [joomla/joomla-cms#9443] opened 2016-03-15 23:18 UTC
#### Steps to reproduce the issue

- Install any fresh Joomla version (tested with 3.4.8, and 3.5.0RC2)
- Download any zip or tar.gz of Joomla version of Joomla 3.5+ (tested with 3.5.0RC2, 3.5.0RC3, Joomla < 3.4 are all OK) to your computer
- Go to Joomla! > Administrator > Extensions > Manage > Install
- 1ª try: Tab "Upload Package file", choose your Joomla update package, and click "Upload & install"
- 2º try: Tab "Install from a folder" choose a local folder with uncompressed content of your Joomla update package, and click "install"
- 3º try: Tab "Install from URL", choose a url from your own site, like http://intranet/joomla/tmp/joomla35update.zip, move your Joomla update package to your tmp/tmp/joomla35update.zip (or a tar.gz), and click "install"

#### Expected result
- 1ª try: Joomla update to 3.5+ without errors
- 2ª try: Joomla update to 3.5+ without errors
- 3ª try: Joomla update to 3.5+ without errors

#### Actual result
- 1ª try: Joomla fail to update (see image)
- 2ª try: Joomla fail to update (see image)
- 3ª try: Joomla fail to update (see image)

.

![screen shot 2016-03-15 at 18 06 48](https://issues.joomla.org/uploads/1/ace3ad24fc055a75996c73c60e838956.png)
![screen shot 2016-03-15 at 18 06 48](https://issues.joomla.org/uploads/1/5ae69908b2cce432ec2dbe003d2980e3.png)
![screen shot 2016-03-15 at 18 06 48](https://issues.joomla.org/uploads/1/907c5c5a2aa07b1689cfd7261a687d64.png)

.

#### System information (as much as possible)
$ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"

$ php -v
PHP 5.6.19-1+deb.sury.org~trusty+1 (cli) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.3.3, Copyright (c) 2002-2015, by Derick Rethans

#### Additional comments

This feature is necessary in intranets without direct remote access. It is common in cases where, by government safety standards or standard military security, an internal network may not have any remote access, and even any added code should be manually reviewed by a technical team.

The compatibility breaks can also affect other minor cases, as simply a situation where there is a very slow internet and can cause timeout PHP, both countries with bad internet or even an event like hackaton.

Until version 3.4 of Joomla this feature worked without problems. If this problem was actually confirmed, or should be corrected or at least explicitly warned at the time of release of the stable version of Joomla 3.5

**Comment by fititnt** [comment] 2016-03-15 23:27
Important: where says on title "installation without internet access stopped working" should be "UPDATE without internet access stopped working".


Simple Joomla installation without internet access work. Update that was stopped. Site "issues.joomla.org" does not allow me to change the title after creation, but was changed on github issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9443">issues.joomla.org/joomla-cms/9443</a>.</sub>

**Comment by zero-24** [comment] 2016-03-16 05:08
@wilsonge a side issue of: https://github.com/joomla/joomla-cms/pull/9402

**Comment by zero-24** [comment] 2016-03-16 05:10
@fititnt please check: https://docs.joomla.org/J3.x:Upgrading_from_Joomla_3.4.x_to_3.5

**Comment by Hoffi1** [comment] 2016-03-16 08:26
See also #9441 with some discussion and a suggestion for dedicated local networks w/o access to real internet.

**Comment by Bakual** [comment] 2016-03-16 08:36
Duplicate report and intended behavior. Closing.

**Closed by Bakual** 2016-03-16 08:36 UTC
Labels: No Code Attached Yet

**Comment by wilsonge** [comment] 2016-03-18 17:50
We have a PR readding this through the "correct" mechanisms in Joomla Update - see Please see https://github.com/joomla/joomla-cms/pull/9469 for manual installations through Joomla Update :)
