### ISSUE TITLE
Greek language pack Joomla 3.9.17

### ISSUE THREAD

**Issue by WhiteSymmetry** [joomla/joomla-cms#28747] opened 2020-04-21 17:31 UTC
### Steps to reproduce the issue
Warning: simplexml_load_file(): administrator/language/el-GR/el-GR.xml:23: parser error : Opening and ending tag mismatch: creationDate line 5 and metafile in /libraries/src/Language/LanguageHelper.php on line 656

Warning: simplexml_load_file(): </metafile> in /libraries/src/Language/LanguageHelper.php on line 656

Warning: simplexml_load_file(): ^ in /libraries/src/Language/LanguageHelper.php on line 656

Warning: simplexml_load_file(): /administrator/language/el-GR/el-GR.xml:23: parser error : Premature end of data in tag metafile line 2 in /libraries/src/Language/LanguageHelper.php on line 656

Warning: simplexml_load_file(): </metafile> in /libraries/src/Language/LanguageHelper.php on line 656

Warning: simplexml_load_file(): ^ in /libraries/src/Language/LanguageHelper.php on line 656

**Comment by zero-24** [comment] 2020-04-21 17:41
Hi it seams to be something broken in the el-GR language pack? Can you check the XML and share it with us?

**Comment by HLeithner** [comment] 2020-04-21 17:41
The issue is in the language pack of the Greece language 
@nikosdion you  are listed on https://community.joomla.org/translations/joomla-3-translations.html#el-gr as Coordinator could you have a look?

**Comment by nikosdion** [comment] 2020-04-21 17:44
The contact person for that is Aris Ntatsis. I’ve not been an active Greek language maintainer for quite a while. You can contact the current maintainers either though Joomla.gr or from the CrowdIn page for the Greek translation. If you can’t seem to be able to reach anyone give me a holler and I’ll email them directly.

**Comment by richard67** [comment] 2020-04-21 17:44
@WhiteSymmetry Do you use the latest Greece language pack 3.9.17? If not please update your language pack, try again and report back the result here. Thanks in advance.

**Comment by HLeithner** [comment] 2020-04-21 17:44
@nikosdion thanks for the info so the cjo has an old entry

**Comment by nikosdion** [comment] 2020-04-21 17:46
At least two to three years out of date :)

**Comment by infograf768** [comment] 2020-04-21 17:49
Just talked to Aris. He will check/correct in 30 minutes

**Comment by ntatsis** [comment] 2020-04-21 18:26
There was an error at administaror/language/el-GR/el-GR.xml file.
It is corrected and a new package el-GR_joomla_lang_full_3.9.17v2.zip has been uploaded @ joomlacode<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28747">issues.joomla.org/tracker/joomla-cms/28747</a>.</sub>

**Comment by zero-24** [comment] 2020-04-21 18:30
Thanks @ntatsis closing here as the issue has been solved

**Closed as completed by zero-24** 2020-04-21 18:30 UTC
Labels: No Code Attached Yet

**Comment by svdumitrescu** [comment] 2021-08-02 09:12
Hi. I've installed the Greek language right on Joomla installation, along with several other languages I want to promote the website. The Greek language does not show in Content Languages. Even stranger, some other languages do not on show in Content Languages, I mean languages that otherwise, in other Joomla installations, used to show in Content Languages directly. So would anyone please provide the values I have to put in the Details fields as I have to manually add the Greek language?

**Comment by nikosdion** [comment] 2021-08-02 09:57
@svdumitrescu As far as I know there is no Joomla 4 release of the Greek language pack — or at least that was the case until three days ago when I last checked. I am no longer a member of the Greek translation team and CrowdIn seems to not know who I am (probably my account was linked to a Facebook account I've closed a year or two ago). Best contact the Greek translation team in the Joomla forum to ask when is the planned release for a 4.0 lang pack.

**Comment by svdumitrescu** [comment] 2021-08-02 10:22
@nikosdion :: My installation currently updated says Joomla! 3.9.28. And I suppose the Content Language Details won't change with Joomla's next version. So I'm talking about those variables Title, Title Native, Language Tag etc. What are the Greek values to fill in those fields, please?

**Comment by svdumitrescu** [comment] 2021-08-02 11:07
@nikosdion :: Don't mind anymore, thanks anyway. I installed another fresh site, checked only Greek as additional language and the Content Languages updated succesfully all alone. (Then I copied the values from one site to another)

**Comment by nikosdion** [comment] 2021-08-02 11:20
I was about to say. I installed a fresh Joomla 3.9 site, Greek was installed just fine and the content languages were there just fine too. I guess the install partially failed on the first site?

**Comment by svdumitrescu** [comment] 2021-08-02 11:49
@nikosdion :: Right. And what's strange, it happens frequently. I check say 4-5 languages and only 2 of them have the Content Languages Details filled in. I guess somewhere on the servers may be some problems. Thanks for your time.
