### ISSUE TITLE
[com_fields] Media Field when using defaults and only required fields set

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#14926] opened 2017-03-27 13:28 UTC
### Steps to reproduce the issue

Install joomla-cms/staging@1c52ed38516f2406fe63dbb762242ae3b82cfcb2

Create media field, only completing the required fields such as: 

<img width="727" alt="screen shot 2017-03-27 at 14 26 39" src="https://cloud.githubusercontent.com/assets/400092/24358554/68fdd312-12f9-11e7-93af-1175cc987fc6.png">

Go to front end and edit article - click select on the media field

### Expected result

Nice model with a good look and feel

### Actual result

Note the invalid blank dropdown next to the up button. 

<img width="1074" alt="screen shot 2017-03-27 at 14 27 07" src="https://cloud.githubusercontent.com/assets/400092/24358584/84d0fb00-12f9-11e7-8d76-d56194f27a95.png">

### System information (as much as possible)

https://gist.github.com/PhilETaylor/b1ff259a06518f903339950ca81e35d7

**Comment by brianteeman** [comment] 2017-03-27 13:46
Are you on the latest staging? I cant replicate this

<img width="394" alt="screenshotr14-45-13" src="https://cloud.githubusercontent.com/assets/1296369/24359386/17c748e0-12fc-11e7-8ab1-5b6daf2e4b61.png">

<img width="401" alt="screenshotr14-46-22" src="https://cloud.githubusercontent.com/assets/1296369/24359408/2a0ca82e-12fc-11e7-9834-e10f31f1fb21.png">

**Comment by PhilETaylor** [comment] 2017-03-27 13:48
<img width="1039" alt="screen shot 2017-03-27 at 14 47 25" src="https://cloud.githubusercontent.com/assets/400092/24359462/54b445c8-12fc-11e7-90e3-ff1e415eba57.png">

```
commit 1746f5798b0b71c7b32ae1350d70fff18d8ff228
Author: Allon Moritz <allon.moritz@digital-peak.com>
Date:   Thu Feb 23 11:39:44 2017 +0100

    Remove home option in media form field (#13893)
```

**Comment by brianteeman** [comment] 2017-03-27 15:24
double checked on staging and still cant replicate

**Comment by PhilETaylor** [comment] 2017-03-27 15:40
Are you trying the frontend or the admin console? 

joomla-cms/staging@d7caa77

**Comment by PhilETaylor** [comment] 2017-03-27 15:41
As the opening statement stats: 

> ## Steps To Replicate
> 
> Go to **front end** and edit article - click select on the media field

Its fine in admin, and broken in the frontend.

**Comment by PhilETaylor** [comment] 2017-04-24 16:21
This was not fixed for Joomla 3.7.0 and therefore the media field in com_fields is has no folder dropdown :-(

**Comment by Bakual** [comment] 2017-04-24 17:27
Can't reproduce that as well. Dropdown folder appears as expected in frontend article edit. Even without first saving the plugin parameters.

**Comment by PhilETaylor** [comment] 2017-04-24 17:29
close the model and invoke it from the "select" part of the media field several times - it fails 9 out of 10 times for me

**Comment by Quy** [comment] 2017-04-24 18:02
I am unable to reproduce too. Your 1st screenshot is different than in RC4. For the `Directory` field, it should have an `- Use Default -` option. Have you done a clean install of RC4 downloaded from here:
[](https://github.com/joomla/joomla-cms/releases/tag/3.7.0-rc4)

**Comment by PhilETaylor** [comment] 2017-04-24 18:35
Im fully aware of where to download Joomla from thanks @Quy 

The fact is that this is reproducible - right up to Joomla_3.7.0-Stable-Full_Package.zip which will be released tomorrow.

I am now at home, on a totally different mac, with Google Chrome, and I have just downloaded Joomla_3.7.0-Stable-Full_Package.zip (from our internal pre-release) and tested it again 

You can watch the steps here:

http://screenshot.myjoomla.io/2k3l3P2p3G1j

As you can see, in this test, it worked the FIRST TIME, but never worked after that, even after a hard page refresh and even now after CHANGING BROWSER to safari 

![screen shot 2017-04-24 at 19 33 40](https://cloud.githubusercontent.com/assets/400092/25352753/fa954440-2924-11e7-91e8-5add2f583542.png)

So the facts are that I can reproduce it in RC4 and the StableZip about to be released, in two physical locations, on two totally different macs, with totally different browsers on both macs - no syncing of profiles or anything in Safari as I dont use it normally. 

There is a bug here to be fixed.

**Comment by Bakual** [comment] 2017-04-24 18:38
Tested again on Chrome and Edge on Windows XAMPP, can't reproduce that behavior even after opening and closing the modal multiple times.
I noticed a 404 error in the console about the ajax-loader.gif, but should not be related (imho).
So it may be related to Mac somehow?

**Comment by PhilETaylor** [comment] 2017-04-24 18:41
See the source code, the "normal" <select/> has options, but the "chosen" js widget has no options, so this looks to be the implementation of the chosen dropdowns, or something along those lines.

**Comment by PhilETaylor** [comment] 2017-04-24 18:42
`width: 2px;` . WTF!!!

**Comment by PhilETaylor** [comment] 2017-04-24 18:46
upstream bug confirmed.  https://github.com/harvesthq/chosen/issues/2029

Putting this:
```

.chosen-container .search-field input {
width: 100% !important;
}
```

into the templates css fixes the problem for me like https://github.com/harvesthq/chosen/issues/2029#issuecomment-88078597 states

**Comment by PhilETaylor** [comment] 2017-04-24 18:51
Actually - it never fixed it - it worked twice and then broke again... 

But at least others confirm this is a problem upstream!

**Comment by dgt41** [comment] 2017-04-24 18:53
@PhilETaylor the sooner Joomla goes away from chosen the better: https://github.com/harvesthq/chosen/pull/1740#issuecomment-248279918

**Comment by zero-24** [comment] 2017-04-24 18:54
hmm can somone on a Mac try to confirm this? I have tryed this now multible times. But i can not reproduce the problem on Windows using the last version of chrome.

**Comment by PhilETaylor** [comment] 2017-04-24 18:59
If I load http://127.0.0.1:8000/index.php/index.php?option=com_media&view=images&tmpl=component&asset=61&author=16&fieldid=jform_com_fields_somemedia&ismoo=0&folder= directly in the browser it works fine - the width is fine

Its only when that url is loaded as an iframe source in a modal on the frontend that I can replicate the upstream issue

**Comment by franz-wohlkoenig** [comment] 2017-04-24 19:37
Can't confirm:
Difference in Screenshot of opened Comment is `Directory`:
![1](https://cloud.githubusercontent.com/assets/8235763/25355164/fffdbff0-2935-11e7-8919-da3ae560fc8d.JPG)
So is looks fine in Modal:
![bildschirmfoto 2017-04-24 um 21 36 21](https://cloud.githubusercontent.com/assets/8235763/25355202/1e3c4a72-2936-11e7-9f27-fa50640ed480.JPG)
### System information
3.7.0-rc4
macOS Sierra, 10.12.4
Firefox 53 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by PhilETaylor** [comment] 2017-04-24 21:15
The same modal is used when you click the image button in TinyMCE when editing a content item on the front of the site - this ALWAYS displays the folder list correct. 

This further leads me to believe that this is a com_fields initialisation of the modal that is at fault

**Comment by Bakual** [comment] 2017-04-25 13:10
If you want to have a look at the respective com_fields specific code for that formfield: https://github.com/joomla/joomla-cms/blob/staging/plugins/fields/media/media.php

It's the exact same code in front- and backend. I honestly can't think of a place within the PHP code of fields which could generate your issues. It should be the same behavior everytime anyway.

**Comment by PhilETaylor** [comment] 2017-04-25 13:22
@Bakual as the comments above prove - it is an issue - and is caused by upstream bugs in chosen...

**Comment by Bakual** [comment] 2017-04-25 13:29
I never said it's not an issue. It's just that com_fields doesn't do anything different here than com_content does. It's the same formfield that gets rendered and it's also the same code in JForm which does it. There is no difference here.
Thus I wonder where the issue cos from, as I don't think it's a com_fields specific one.

**Closed** 2019-02-10 21:34 UTC
Labels: J3 Issue, No Code Attached Yet
