### ISSUE TITLE
Blur event in validation causes poor UX [4.2.x]

### ISSUE THREAD

**Issue by ron4mac** [joomla/joomla-cms#39419] opened 2022-12-14 17:12 UTC
### Steps to reproduce the issue
Bring up a login form (not module). Click on 'remember me' or forgot username or password (as well as create an account).

### Expected result
The click causes the desired action.

### Actual result
It takes two clicks for the action to occur.

### System information (as much as possible)
Joomla 4.2.6, Mac OS, Safari/Chrome/Firefox

**Comment by chmst** [comment] 2022-12-14 18:11
Confirmed, but different on browsers.

**Comment by brianteeman** [comment] 2022-12-28 17:36
I cannot replicate this

**Comment by chmst** [comment] 2022-12-28 20:56
http://j4.chmst.de/index.php/login test here

It is a menuitem to login page - if I open here and click "Forgot your Password" or even before, the validation is too quick.

**Comment by brianteeman** [comment] 2022-12-28 21:22
ah - its the same as https://github.com/joomla/joomla-cms/issues/26317 then?

**Comment by chmst** [comment] 2022-12-28 21:26
Not sure - but it could really be the same.

**Comment by brianteeman** [comment] 2022-12-28 21:28
same script - same problem

**Comment by JackKellyUK** [comment] 2023-01-03 19:05
Looks to be the same issue as #32692. Looking into this I'm pretty sure this is happening because when you land on the page the Username field is selected, so if you attempt to click without entering a valid Username the blur (unfocus) event is triggered, showing the validation message and jumping the page.

Happy to work on a fix, but will need some guidance how it wants to be approached. These are the options I can think of:

- A delay is added to the blur event function, just needs to long enough for the click event to fire
- The validation message is absolute positioned, so it doesn't effect the flow of the page
- The blur event is no longer used (unsure of an alternative)

**Comment by richard67** [comment] 2023-02-11 10:19
Closing as having a pull request. Please test #39838 . Thanks in advance.

**Closed as completed by richard67** 2023-02-11 10:19 UTC
Labels: No Code Attached Yet, bug
