### ISSUE TITLE
Issue with 'Add a module for this menu' modal

### ISSUE THREAD

**Issue by jamield** [joomla/joomla-cms#11173] opened 2016-07-18 10:56 UTC
#### Steps to reproduce the issue

In backend, go to Menus -> Manage
Find menu that does not currently have a menu assigned
Click 'Add a module for this menu' button
Create new module and click 'Save & Close' at top of modal

#### Expected result

Modal should close

#### Actual result

You are then presented with the module manager inside the modal

#### System information (as much as possible)

Joomla 3.6.0
Ubuntu 14.04
PHP 5.5.9
Apache 2.4.7
FPM-FCGI

#### Additional comments

I imagine this might be an issue on other modals but have not testes

**Comment by andrepereiradasilva** [comment] 2016-07-18 11:00
cannot reproduce this is latest staging.did you clear the browser cache?

> Create new module and click 'Save & Close' at top of modal

the "Save and close" is at the **bottom** of the modal, not top.

**Comment by jamield** [comment] 2016-07-18 11:04
No there's one at the top as well. Above the title box.


Jamie Derrick
mobile: +44 (0)7740 348799
web: jderrick.co.uk
email: jamie.derrick@jderrick.co.uk
<http://twitter.com/jamiederrick>  <http://uk.linkedin.com/in/jamiederrick>

**Comment by jamield** [comment] 2016-07-18 11:05
Hang on... I've just realised this is only when using the NoNumber Advanced Module Manager extension. All is well!

**Comment by andrepereiradasilva** [comment] 2016-07-18 11:07
close the issue then

**Comment by jamield** [comment] 2016-07-18 11:08
Please?!

**Comment by andrepereiradasilva** [comment] 2016-07-25 11:35
@brianteeman can you close this?

**Comment by brianteeman** [comment] 2016-07-25 12:21
Closed as requested

**Closed by brianteeman** 2016-07-25 12:21 UTC
Labels: No Code Attached Yet
