### ISSUE TITLE
send test email not working

### ISSUE THREAD

**Issue by umaha** [joomla/joomla-cms#9517] opened 2016-03-22 12:25 UTC
#### Steps to reproduce the issue
In administrator/index.php?option=com_config -> server -> Mail Settings
Setup SMTP - I used smtp-relay.gmail.com, port 587, No SMTP Authentication.

#### Expected result
Send test Email should send a test email. This works via say Contact Form or a custom code on the site.

#### Actual result
Got system error 

Test mail could not be sent.

Could not instantiate mail function.

#### System information (as much as possible)
System Information
Setting	Value
 
PHP Built On	Linux instance-1 3.19.0-56-generic #62~14.04.1-Ubuntu SMP Fri Mar 11 11:03:15 UTC 2016 x86_64
Database Version	5.5.5-10.1.12-MariaDB-1~trusty
Database Collation	utf8_unicode_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	5.5.9-1ubuntu4.14
Web Server	Apache/2.4.7 (Ubuntu)
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 3.5.0 Stable [ Unicorn ] 21-March-2016 22:00 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36

#### Additional comments
Joomla Mail Setting works fine. Only the Send test Email did not work.

**Comment by roland-d** [comment] 2016-03-22 12:26
Thank you for your report but I am going to close this as a duplicate of #9373 

Can you please check my last comment there on how to debug the issue? Thanks.

**Closed by roland-d** 2016-03-22 12:26 UTC
Labels: No Code Attached Yet
