### ISSUE TITLE
Search box won't clear, search dropdowns won't go back to none

### ISSUE THREAD

**Issue by laurelle** [joomla/joomla-cms#8421] opened 2015-11-13 16:37 UTC
#### Steps to reproduce the issue

See forum post: http://forum.joomla.org/viewtopic.php?f=708&t=895755

Clean Joomla 3.4.5 install on a server running PHP 5.6.15.
Login as a Super Admin in the backend of the site.
Go to the Article Manager and type something in the search text box and search for it. Now click the Clear button. Page reloads, but the search text box still has what you searched for in it, it doesn't clear. Same thing happens with the Module Manager or anywhere else there is a search box.
Click on the Search Tools and change any of the dropdown boxes, for example Categories to a particular category. Then try to changed the dropdown box back to no categories selected, page reloads but the previously chosen category is still selected.

#### Expected result

Expected that the Clear button will clear the search text box or deleting what is in the text search box and doing a search will give you all the search results back.

#### Actual result

Instead you get the search box still populated with the previous entered search text and the search results are for the previously entered value.

#### System information (as much as possible)

Server info is in this post: http://forum.joomla.org/viewtopic.php?f=708&t=895755#p3343784

#### Additional comments

Switch the server to PHP 5.5 and the problem goes away. Doesn't seem to matter if you are running Apache 2.2 or 2.4 it is the PHP version that seems to cause the issue to happen.

**Comment by MixingOnBeat** [comment] 2015-12-10 00:49
I've also reported this issue today: https://issues.joomla.org/tracker/joomla-cms/8641

**Comment by bertmert** [comment] 2015-12-10 09:47
I'm using PHP 5.6.13 and cannot reproduce this issue.

**Comment by gwsdesk** [comment] 2015-12-15 10:52
I can confirm this issue. I have it on our servers where we run PHP 5.6.15. When box is compiled with PHP 5.5.x or PHP5.4.x works as expected

Database Version 	5.5.5-10.0.22-MariaDB-log
PHP Version 	5.6.15
Web Server 	Apache
WebServer to PHP Interface 	cgi-fcgi

**Comment by anarcist69** [comment] 2016-01-14 22:36
I am running 5.6.14 and having this same issue

**Comment by izharaazmi** [comment] 2016-01-19 12:10
Could not reproduce the issue
PHP 5.6.11
Joomla 3.4.5 ~ 3.4.8

**Comment by izharaazmi** [comment] 2016-01-19 12:14
If someone can set-up an environment for me where this issue can be reproduced, I will be happy to attempt a  fix for it.

**Comment by MixingOnBeat** [comment] 2016-01-19 12:19
@izharaazmi 

try updating your PHP to see if you can spot it.

**Comment by gwsdesk** [comment] 2016-01-19 12:23
I have a Joomla 3.4.8 development domain what I use for Joomla patch 
testing. send me an email and I provide you access details. This is the 
site where you see this http://screencast.com/t/lehjDB2B8 we have on the 
Joomla forums also many posts on this and I experience this on our PHP 
5.6 driven servers. See also 
https://groups.google.com/forum/#!topic/joomla-dev-cms/NLEJwpAG1wQ

Leo Lammerink
MD GWS-Desk.com

**Comment by izharaazmi** [comment] 2016-01-19 12:49
@gwsdesk  I've sent a private message via [Google Groups](https://groups.google.com/forum/#!topic/joomla-dev-cms/NLEJwpAG1wQ)

**Comment by gwsdesk** [comment] 2016-01-19 14:16
I replied with access details

**Comment by izharaazmi** [comment] 2016-01-19 14:45
@gwsdesk I was able to login to ftp and site both but the FTP is very slow
and is timing out every moment. :(

**Comment by gwsdesk** [comment] 2016-01-19 15:05
That is your internet connection. Server is a powerhouse 16 core, 31 GB 
memory and located at the Liquidweb Datacenters in Michigan USA

If you want discuss details on our server or similar issues post in 
private and do not provide information to the public where I provide you 
with a testing platform. Keep your comments private please or I will 
need to remove your access?

Thanks for caring and understanding

Leo

**Comment by gwsdesk** [comment] 2016-01-19 15:08
You have been blocked ny our firewall (CFS IPTables). You used wrong 
credentials

  117.221.46.202 # lfd: (smtpauth) Failed SMTP AUTH login from 
117.221.46.202 (IN/India/-): 10 in the last 300 secs - Fri Oct 16 
08:45:58 2015

**Comment by izharaazmi** [comment] 2016-01-19 15:54
Thanks to @gwsdesk for providing the testing environment for this issue.

I was doing the initial sanity test on the server which was experiencing this issue. For this I set up this test file (`test.php`):
```php
<html>
<body>
	<pre>POST DATA IS:<br><?php print_r($_POST); ?></pre>
	<br/>
	<form action="test.php" method="post">
		<input type="text" name="textbox" value=""/>
		<br>
		<select name="select1">
			<option value=""></option>
			<option value="one">ONE 1</option>
			<option value="two">TWO 1</option>
		</select>
		<br>
		<select name="select2">
			<option></option>
			<option value="one">ONE 2</option>
			<option value="two">TWO 2</option>
		</select>
		<br>
		<button type="submit">SEND</button>
	</form>
</body>
</html>
```

When submitted with **blank** values in the input fields, the `$_POST` did not contain the value at all.
The output was expected to be:
```php
Array
(
    [textbox] => 
    [select1] => 
    [select2] => 
)
 ```
but the actual output on the test server was:
```php
Array
(
)
```
All empty valued keys missing altogether. This is why the Joomla user state is not updated.

Hence I conclude that **this is not any Joomla issue** and essentially related to server / php configuration.
Other people facing similar issue can perform similar sanity check with their web server. If their server passes this sanity test and still they face same issue, I am always there to help.

I leave the decision about closing this (and similar) issues to the owners / collaborators.

Thanks.

**Comment by MixingOnBeat** [comment] 2016-01-19 16:00
Should we report this bug to PHP developers?

**Comment by izharaazmi** [comment] 2016-01-19 16:03
@MixingOnBeat I am not sure which versions of PHP are affected. But I have 5.6.11 that works right. If the latest release in 5.6 still is victim, then "Yes, we should" :+1:

**Comment by gwsdesk** [comment] 2016-01-19 16:03
Well it is nice to conclude that it is a "server issue" but if this is a 
"server-issue" (which many people are experiencing) It would be nice not 
to point just to "server" but provide reasons, possible solutions.. Jut 
pointing to "server" is worthless and does not help. Once again we do 
not have the issue on PHP 5.5.xx or PHP 5.4.xx but only from PHP 5.6 
onwards.... as shown on many posts on the Joomla forums. I am sorry but 
your post here is not helpful in resolving any of this. Thanks for the ffort

Leo

**Comment by gwsdesk** [comment] 2016-01-19 16:06
I have commented and you are wrong in your assessment

Leo

**Comment by gwsdesk** [comment] 2016-01-19 16:19
So when we have the same issues on hosting accounts with multiple 
hosting-providers (high end) you state here that they all have their PHP 
5.6.15 to PHP 5.6.17 wrongly configured? If so prove and do not make 
assumptions based on your litte testing script and provide solutions? 
Blaming hosting companies of configuring servers wrong without stating 
what is actually wrong (in your very specialized knowledge ....) or what 
might be changed to avoid this is just damaging... What is your proposed 
solution besides closing a valuable threat which is biugging dozens of 
users of Joomla?

Thanks

Leo

**Comment by izharaazmi** [comment] 2016-01-19 16:59
Really sorry for not being helpful. 

Unfortunately, I am currently only available for Joomla fixes. Since I found that the particular issue was not caused by to Joomla, I simply step back. I do **not** intend to challenge any web hosting company or just anybody.
And I also stated that I am still available for the fix if it is in Joomla. If somebody having the same issue but getting the expected correct output from the given `test.php` can bug me anytime. And I'd happily join.

I can suggest workaround if Joomla leadership team decides to provide compatibility for this scenario. Without their consent I am nobody here.

**Comment by izharaazmi** [comment] 2016-01-19 17:20
A little **effort** for being helpful from my side:

People over the internet are discussing about `suhosin` v/s `php` conflicts. One such is https://github.com/stefanesser/suhosin/issues/98. There are several other, but I am not sure if this is the real cause.

You may try disabling suhosin (for once) and see if the issue persists. If not then you may need to update suhosin on your server.

One better check you can do is with following code in the above `TEST` code given:

```php
<pre>INPUT WAS:<?php
		$data = file_get_contents("php://input");
		print_r($data);
?></pre>
```

**Comment by MixingOnBeat** [comment] 2016-01-20 02:32
My issue started with:

PHP 5.6.14

I am currently on:

PHP 5.6.16

And still have the issue.

Seems from what I'm reading there was a older version that it used to work okay.  But later stopped.  Perhaps it started with PHP Version 5.6.14?

My host hasn't updated to the latest version, which is:

PHP 5.6.17

Can anyone check the change log for PHP 5.6.17 to see if it points to this issue being fixed?
http://php.net/ChangeLog-5.php#5.6.17

This way I can ask my host to update to that version.  I doubt they will downgrade, since most of the time, updating PHP is to help from hacks and attacks.

**Comment by gwsdesk** [comment] 2016-01-20 09:10
Well your help is much appreciated and if you can propose a work around 
that would be indefinitely helpful. Switching off Suhosin is a 
non-option from security point of view . Besides that it works with 
Suhosin 0.9.36 (not latest) on a box with PHP 5.4 and 5.5 so it simply 
cannot be caused by Suhosin imho

**Comment by izharaazmi** [comment] 2016-01-20 09:17
@gwsdesk I am already working on some **nice** workaround for this in case of Joomla. But that would take time as we are on weekdays.
However, the actual issue (whatever the reason be) is indeed a big one. And since it can be observed even without Joomla, it has certainly not caused by Joomla. I am sorry that I can't point to the exact reason.

For now, can you please report here the output of my test code above when run on your server. I have updated it to be more informative. Submit the form empty valued once and once with values filled.

Thank you.

**Comment by infograf768** [comment] 2016-01-20 09:26
Tested on a 5.6.17 php and your test passes fine.

**Comment by gwsdesk** [comment] 2016-01-20 09:28
I have just recompiled a box with PHP 5.6.17 and it does not resolve

I am not recompiling without Suhosin (I do not want to be ignored

**Comment by izharaazmi** [comment] 2016-01-20 09:42
@infograf768 Are you facing the issue and still your server passes my test? If so, please paste your output here.

**Comment by gwsdesk** [comment] 2016-01-20 09:43
Izhar..... you are a *****    And you have been absolutely right. I have 
recompiled a box without Suhosin (cPanel distro's 0.9.36 where Suhosin 
is now on 0.9.38) and I have this all working again with PHP 5.6.17 
without Suhosin. You can check with the credentials I gave you.

We will now update Suhosin to latest (bypass cPanel distro) and report 
that result as well

Thanks and you made my day!!!

**Comment by infograf768** [comment] 2016-01-20 09:44
Did not test the issue itself, only your test.

**Comment by izharaazmi** [comment] 2016-01-20 09:44
I edited my comment https://github.com/joomla/joomla-cms/issues/8421#issuecomment-172896473 to show more information. Please use updated code.

I do **not** suggest disabling suhosin. Just for the moment during the test.

**Comment by gwsdesk** [comment] 2016-01-20 09:45
***** stands for 5-Star . In other words it is indefinitely caused by an issue between Suhosin and PHP 5..6 (since it works with PHP 5.5.31 with Suhosin compiled)

**Comment by gwsdesk** [comment] 2016-01-20 09:46
Sorry your testing instructions are not clear to me....I do not understand what code I need to upload. Kind of confusing to me

**Comment by gwsdesk** [comment] 2016-01-20 09:50
http://gwsdev2.work/test.php you will see the output Not sure what I am 
suppose to see

**Comment by izharaazmi** [comment] 2016-01-20 09:50
**Copy the entire code and create a file on your server `test.php`**. Then open it in your browser.
And submit it with just one field with value, keeping other blank. Post your output here. 

Please note this is important only for those who **are able to** reproduce the actual issue.

**Comment by gwsdesk** [comment] 2016-01-20 09:53
INPUT WAS:textbox=&select1=one&select2=

POST DATA IS:
Array
(
    [textbox] => 
    [select1] => one
    [select2] => 
)

**Comment by izharaazmi** [comment] 2016-01-20 09:54
@gwsdesk Your server output now looks fine.

**Comment by gwsdesk** [comment] 2016-01-20 09:56
yeah but that is because I have disabled Suhosin 0.9.36?

**Comment by N6REJ** [comment] 2016-01-20 10:07
@izharaazmi  when I run the test.php ( http://hallhome.us/test.php ) with nothing in the fields I get 
INPUT WAS:textbox=&select1=&select2=
POST DATA IS:
Array
(
)
feel free to run it yourself...
my system info is...
```
PHP Built On	Linux host.hallhome.us 3.10.0-229.7.2.el7.x86_64 #1 SMP Tue Jun 23 22:06:11 UTC 2015 x86_64
Database Version	5.6.28
Database Collation	latin1_swedish_ci
PHP Version	5.6.16
Web Server	Apache/2.4.16 (Unix) OpenSSL/1.0.1e-fips mod_bwlimited/1.4
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 3.4.8 Stable [ Ember ] 24-December-2015 19:30 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36
```

Like leo my server is in Liquid Webs DC in lancing.

**Comment by gwsdesk** [comment] 2016-01-20 10:15
Trou, LW is irrelevant. We run many, many servers at LW. Besides that I get on your server the following output output

INPUT WAS:textbox=&select1=one&select2=

POST DATA IS:
Array
(
    [select1] => one
)

So you have issues as per izharaazmi . You have Suhosin compiled? After I disabled Suhosin on the testing server this issue was resolved. My team is now recompiling with Suhosin 0.9.38 (latest version) and I will post back if that resolves

**Comment by N6REJ** [comment] 2016-01-20 10:17
@izharaazmi  #7957 & #8866 are also part of this I'm sure.

**Comment by N6REJ** [comment] 2016-01-20 10:19
@gwsdesk I agree its not LW... I'm using Suhosin v0.9.36.

**Comment by gwsdesk** [comment] 2016-01-20 10:22
If you disable that you will see that all is back to normal. But just 
wait a while till I post back if Suhosin latest 0.9.38 resolves as 
@izharaazmi <https://github.com/izharaazmi> suggested. Should be done in 
a few minutes

**Comment by N6REJ** [comment] 2016-01-20 10:38
@gwsdesk since jm reported 5.6.17 didn't have the problem I'm going to leave suhosin as is for the moment and update my php and see if that works as well.. so between you and me we should have a solid answer as to whats messing up what... I'll report later after I've had some sleep.. just as a note, the kernel needed an update so doing that at the same time.

**Comment by brianteeman** [comment] 2016-01-20 10:41
Sigh - outdated software - whoever would have thought that might cause a
problem

On 20 January 2016 at 10:38, Bear <notifications@github.com> wrote:

> @gwsdesk <https://github.com/gwsdesk> since jm reported 5.6.17 didn't
> have the problem I'm going to leave suhosin as is for the moment and update
> my php and see if that works as well.. so between you and me we should have
> a solid answer as to whats messing up what... I'll report later after I've
> had some sleep.. just as a note, the kernel needed an update so doing that
> at the same time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/8421#issuecomment-173166166>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by izharaazmi** [comment] 2016-01-20 10:45
@brianteeman Can we add this as 'known issue' somewhere, if this is eligible enough?
Where should I head for this?

**Comment by gwsdesk** [comment] 2016-01-20 10:53
@Brian, That is a non realistic remark. This is not related at all to 
outdated software. Read all what has been posted by @izharaazmi and the 
testing etc and make than conclusions. They will be different from this 
remark I am sure?  We have latest distro from cPanel, kernel is fully 
updated, all of Apache and PHP is on latest versions as provided via 
cPanel. I have clearly identified based on the input from izharaazmi 
that the issue is caused by a conflict between PHP 5.6.xx and Suhosin. 
(PHP 5.5.31 nd PHP 5.4 with Suhosin (both) do not give the issue. Only 
PHP 5.6.xx. Suhosing disabled and all works normal as mentioned. We are 
now updating to latest Suhosin 0.9.38 wich should solve as @izharaazmi 
mentioned (this is not in the cPanel distro as you can run with 
EasyApache 3 or 4) You need to download this from the Suhosing Github 
repository and compile from the command line or ask Liquidweb to do that 
for you if you are not able to do so Troy

Leo

**Comment by gwsdesk** [comment] 2016-01-20 10:54
I happen to disagree. A Known issue does not requires a solution. Sorry 
but we have dozens of related posts and it is still not proven that this 
is not caused by Joomla code imho?

**Comment by izharaazmi** [comment] 2016-01-20 11:41
This time its me to disagree. :smile: 
The issue can be observed even where Joomla is **not** installed at all. 
So I guess this cannot be caused by Joomla.

**Comment by N6REJ** [comment] 2016-01-20 11:49
It's totally irrelevant who's fault it is.  IT IS AN OBSERVABLE BUG THAT 
EXISTS IN JOOMLA'S BEHAVIOR!  The cause is irrelevant to that BECAUSE it 
effects joomla's behavior.
albeit it might not be something that we can fix, it is still something 
to watch for.  Does php 7 have this issue?
@leo thanks for the heads up.
can a trap be set in joomla for this specific bug?  If so we'd be 
prudent to do so since it directly effects our product.  Sluffing it off 
is not a prudent solution imo.
Bear
/rant

**Comment by N6REJ** [comment] 2016-01-20 11:53
@gwsdesk Leo, updating kernel and php ( 5.6.17 ) had no effect.

**Comment by gwsdesk** [comment] 2016-01-20 11:53
Ok I am so pleased now @Izharaazmi to confirm now that *IT IS ACTUALLY 
SUHOSIN* which is causing this. We have recompiled to Suhosin v0.9.39dev 
on PHP 5.6.17 and we have a fully running Joomla 3.4.8 without issues. 
As stated you are a 5-star and I will get back to you in private on your 
email. You can be mighty proud of yourself and you have been right from 
the very beginning.

I do owe you a couple........ Thanks Izhar You are a real asset here!

Leo

**Comment by gwsdesk** [comment] 2016-01-20 11:55
Bear, ask Liquidweb to update your Suhosin to v0.9.39dev on PHP 5.6.17 
and your issue will be resolved. I can confirm this a non-Joomla issue!

Leo 8)

**Comment by N6REJ** [comment] 2016-01-20 11:57
thanks leo, i'm doing so now.. I feel much better letting them do it since I've forgotten so much.  Now I'll sleep.. I THINK.... don't take a nap just before dinner LOL

**Comment by izharaazmi** [comment] 2016-01-20 11:58
Thanks @gwsdesk, I was just trying to be **helpful**. Cheers! :+1: 

On a side note, I am trying to propose different approach to _clear search values_ mechanism in Joomla. Well, this is not related to current issue anyway.

**Comment by N6REJ** [comment] 2016-01-20 11:59
@izharaazmi pardon me if this is a really dumb question but why isn't it simple like.. on button $search = '';

**Comment by izharaazmi** [comment] 2016-01-20 12:06
Yes, this is actually being done this way only! Right now and since very long time. But in my experiences I have seen several cases where this is __not sufficient__.

> Questions are never dumb (stupid), answers are!

**Comment by infograf768** [comment] 2016-01-20 18:06
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8421">issues.joomla.org/joomla-cms/8421</a>

**Comment by infograf768** [comment] 2016-01-20 18:06
Closed as not Joomla core.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8421">issues.joomla.org/joomla-cms/8421</a>.</sub>

**Closed by infograf768** 2016-01-20 18:06 UTC
Labels: No Code Attached Yet

**Comment by N6REJ** [comment] 2016-01-20 22:32
@gwsdesk yep, fixed... so, the solution is to update suhosin... 
@infograf768 I don't know that this should be closed without a work around in place.  This will rear its head again in the near future as others upgrade to 5.6.x and don't upgrade suhosin.

**Comment by MixingOnBeat** [comment] 2016-01-21 02:42
Not sure if my host has Suhosin installed or not.  I just sent them an email to find out.  I hope this fixes this issue on my side also.

I echo what @N6REJ stated above about trying to fix this issue on Joomla's end.  Other software like phpBB, Vbulletin, Wordpress and etc.  Don't have this issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8421">issues.joomla.org/joomla-cms/8421</a>.</sub>

**Comment by MixingOnBeat** [comment] 2016-01-23 01:42
Well I asked my host to update Suhosin, and they tell me that it the new version doesn't come with the standard version of Cpanel.  So I think its not so easy for some hosts to do the update. Currently my site is using Suhosin v0.9.36

Their message:

"We can only install the standard versions which come with cPanel and currently v0.9.38 is not available."

Saying that, I think JOOMLA devs need to figure this out for the rest of us.

**Comment by gwsdesk** [comment] 2016-01-23 03:15
They can do that manually as we did ourselves. The method is outlined 
here: http://suhosin.org/stories/install.html

Leo

**Comment by izharaazmi** [comment] 2016-04-07 10:47
I created a plugin to workaround this issue. You can download it here https://github.com/izharaazmi/joomla-suhosinfix/releases.

Endorse me on [LinkedIn](http://in.linkedin.com/in/izharaazmi), if you feel like. :smile:

**Comment by chrispr-os** [comment] 2016-04-11 04:23
I have discovered this problem as my hosting company upgrade to PHP 5.6.20 last week.  Thankfully I found this thread.  However two issues:  
1) My hosting company will not upgrade the Suhosin to 0.3.9.38 as CPanel comes standard with 0.3.9.26
2) I installed the plugin and it works on the backend for articles but it does not work on my front end components.

I would also like to comment like others above.  While this may be an issue with Suhosin and PHP, the end user community will see this as a Joomla issue / bug considering 
a) Most people are not so technically oriented and do not have access to making such updates.
b) A Joomla plugin is written to address this 
c) Wordpress sites do not have this issue

Again, I understand this is not a Joomla issue exactly, Joomla is still what we see and 'drive'.  So when we drive Joomla and WP side by side and one doesn't work .....  
- All the average community user (who is not technical, does not have root access and certainly cannot upgrade to the latest suhosin) will think is if WP can work why can't Joomla?  

Thanks izharaazmi for the plugin,  can you think of any reason why your patch will not work on the front end?  Is there something we can do to change the patch to work?

**Comment by izharaazmi** [comment] 2016-04-11 05:33
> the end user community will see this as a Joomla issue / bug considering 
a) ...
b) A Joomla plugin is written to address this 
c) ...

why this is one of the reason for it? Sorry I didn't understand. Please explain!

Now about the problem that the plugin doesn't work in the front-end, I say that this plugin doesn't care whether it is front-end or a backend.

I can see two possible scenario when the plugin won't work:

1. The form which is submitted have the `enctype="multipart/formdata"` attribute set. 
*I do not have a solution for this.*

2. Some other plugin (or any extension) may be reading `php://` stdin before this plugin is even called. 
This is because of the fact that the stdin can be read only once. See [php:// manual](http://php.net/manual/en/wrappers.php.php)
*Try to set the ordering for this plugin as `first` in the plugin manager. See if this helps.*

**Comment by chrispr-os** [comment] 2016-04-11 09:18
Thanks for your quick reply.  

The plugin is already in the first position.  According to the developer it is not a multipart.  I am not a coder but can read php and make simple hacks to see if I can get the search box isolated enough to see if something else is causing the conflict on the page. I will play around to see if I can find something in the code causing it.

As for the first comment, I was referring to the previous comments that this should be closed because it is not a Joomla bug.  I appreciate the effort you have done to make a plugin for us however, IMHO, just because it is a PHP / Suhosin conflict does mean that the core Joomla shouldn't 'compensate'.

**Comment by chrispr-os** [comment] 2016-04-11 14:41
After some additional searching, I found a 'fix' using php.ini

In your php.ini add the following lines
suhosin.cookie.disallow_nul=Off
suhosin.get.disallow_nul=Off
suhosin.post.disallow_nul=Off
suhosin.request.disallow_nul=Off 

I did not play to see which particular one of the four, I guess it is the get & post, that we are looking for.  I just did all four.

**Comment by izharaazmi** [comment] 2016-04-11 14:55
Yes, that's right. But most of the people on shared hosting are not allowed to override these parameters.
