### ISSUE TITLE
JHtmlBootstrap::startAccordion

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#17853] opened 2017-09-03 21:42 UTC
### Steps to reproduce the issue
Sorry not worked out exactly how to replicate this other than install the test data and then go to feagtured contacts - select any of the contacts and you will see the following error
`
Notice: Undefined index: JHtmlBootstrap::startAccordion in C:\Apache24\htdocs\cms\libraries\cms\html\bootstrap.php on line 693`

**Comment by ghost** [comment] 2017-09-04 04:49
Can't confirm. No Notice in Frontend or php_error.log, Error Reporting is set on "Maximum".
### System information
3.8.0-beta5-dev
Multilanguage Site
macOS Sierra, 10.12.6
Firefox 55 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17853">issues.joomla.org/tracker/joomla-cms/17853</a>.</sub>

**Comment by brianteeman** [comment] 2017-09-04 07:37
@franz-wohlkoenig did you check ALL the featured contacts?

**Comment by ghost** [comment] 2017-09-04 07:39
Checked this Contact by click on each:
![bildschirmfoto 2017-09-04 um 09 39 03](https://user-images.githubusercontent.com/8235763/30016340-fc450b70-9154-11e7-98d6-1069f779e79c.jpg)

**Comment by brianteeman** [comment] 2017-09-04 07:40
strange

**Comment by Quy** [comment] 2017-09-04 16:13
Unable to reproduce with nightly staging.

**Comment by izharaazmi** [comment] 2017-09-15 16:46
Looking at the code its clear that this error will occur when `addSlide` is called before calling `startAccordion` with same `$selector`. Now it boils down to find where it is called this way.

Further should we or not check this error condition in `addSlide`?

**Comment by Quy** [comment] 2017-11-12 05:25
To reproduce:
Enable `Maximum` for Error Reporting.
Under Contacts > Contact, set `Contact Information` to hide and `Show User Articles` to show.
On front end, click `Featured Contacts`.
Click `Shop Address` contact.

**Comment by ghost** [comment] 2017-11-12 07:29
Issue confirmed, haven't clicked on "Shop Address" before. Thanks for Hint @Quy.

**Comment by ghost** [comment] 2017-11-15 06:12
closed as having Pull Request #18573

**Closed as completed** 2017-11-15 06:12 UTC
Labels: No Code Attached Yet
