### ISSUE TITLE
[J! 4.4.3] Unable to Clear Filter Options for SQL form field

### ISSUE THREAD

**Issue by samuelagus** [joomla/joomla-cms#43210] opened 2024-04-04 11:28 UTC
### Steps to reproduce the issue
I have some filter field in my custom component, one of them is "Name Filter" which get the dropdown list from SQL form field.

This is the "Filter Options" screenshot:
![Filter-Name](https://github.com/joomla/joomla-cms/assets/74813999/40e8b40c-a6d4-46d7-b974-a699da5c1a74)

This is the XML ( **_/models/forms/filter_itemdetails.xml_** ) :
```
<field name="name" 
	id="name" 
	type="**sql**" 
        label="COM_MYCOMPONENT_FORM_LBL_ITEMDETAIL_NAME"
        description="COM_MYCOMPONENT_FORM_DESC_ITEMDETAIL_NAME"
	sql_select="name, date"
	sql_from="#__itemdetails"
	sql_order="date DESC"
	sql_group="name"
	key_field="name"
    	value_field="name"
	header="Name Filter"
	layout="joomla.form.field.list-fancy-select"
	onchange="this.form.submit();
/>
```

The filtering is works fine.
But the problem occurs when filtering by "Name Filter" then Clear it.
"Name Filter" works normally (the table filtered by Name), but when I click "Clear" button, the table is still filtered by "Name Filter", it should be Reset the filtering (no filter anymore).
The Clear problem (Resetting the Name Filter) will be solve if I click the little cross icon _(in the blue circle in my attached screenshot)_, then the table will be show all datas (no Name Filter anymore)

I try to remove the layout="joomla.form.field.list-fancy-select" from sql field, then the Clear button works fine.
I guess it (the layout) may be the cause of this problem.
But if I don't use this layout, the filtering dropdown will be just show a select list (not combo box), so I need "combo box" for this Name filter :)

### Expected result
SQL Filtering can be cleared by click the "CLEAR" button

### Actual result
The Clear button can not Reset/Clear the Name Filtering (SQL form field)

### System information (as much as possible)
Joomla v4.4.3
PHP 8.3

**Comment by Hackwar** [comment] 2024-04-04 18:19
Not disagreeing with you on the bug, but why do you have an id attribute? You can remove that and it would still generate an ID for your field, although one slightly different.

**Comment by samuelagus** [comment] 2024-04-05 07:11
> Not disagreeing with you on the bug, but why do you have an id attribute? You can remove that and it would still generate an ID for your field, although one slightly different.

Do you mean: id="name" ?
OK, I remove the ID in the XML, but the problem still happened.
"Clear" button did not clear the filter.

**Comment by samuelagus** [comment] 2024-04-05 16:15
> Do you need the layout="joomla.form.field.list-fancy-select"? If not, the filter will be cleared.

Yes, I need the layout to utilize the combo box, because the data list is very large, it's a bit difficult to choose from the select options list without combo-box

**Comment by samuelagus** [comment] 2024-04-09 08:00
I just realized that besides clicking the little cross icon _(in the blue circle in my attached screenshot)_, pressing the refresh button on the browser will clear (reset) the Name filter.
Is this "not auto-refreshing" thing the cause of the failure to reset the filter?

May this additional information help to find the cause of the problem?

**Comment by Hackwar** [comment] 2024-08-05 17:40
Your problem is, that the list doesn't have an empty value. So the reset code doesn't know to which value it should set the field. You have to add an empty value in the XML in an `<option>` tag.

This is not a bug in joomla. Closing this one.

**Closed as completed by Hackwar** 2024-08-05 17:40 UTC
Labels: No Code Attached Yet

**Comment by samuelagus** [comment] 2024-08-06 15:28
@

> Your problem is, that the list doesn't have an empty value. So the reset code doesn't know to which value it should set the field. You have to add an empty value in the XML in an `<option>` tag.
> 
> This is not a bug in joomla. Closing this one.

Do you mean like this:

```
<field name="name"
type="sql"
label="COM_MYCOMPONENT_FORM_LBL_ITEMDETAIL_NAME"
description="COM_MYCOMPONENT_FORM_DESC_ITEMDETAIL_NAME"
sql_select="name"
sql_from="#__itemdetails"
sql_order="date DESC"
sql_group="name"
key_field="name"
value_field="name"
header="Name Filter"
layout="joomla.form.field.list-fancy-select"
onchange="this.form.submit();
>
      **<option value="">Filter Name</option>**
</field>
```

I've try to do it, the result is: 
When the filter is active (filtering the table), the "Clear" button is not active, so I can't click Clear button.
I have to click each "little cross icon" to clear the filtering.
I try to add `default=""` but still doesn't works
