### ISSUE TITLE
taging issue in AJAX mode with Persian, Arabic, Hebru

### ISSUE THREAD

**Issue by A-Kasaaian** [joomla/joomla-cms#10761] opened 2016-06-09 05:26 UTC
Hi there,
I have seen an issue with tags. When a user wants to add a tag, after typing 3 letters no matter the user is still typing or not, Joomla automatically completes the tag if there is a word in the list width those letters.
For example, if I want to write "signature" and there is the word "sign" in the list, joomla selects "sign" and doesn't let me to type the compete word "signature" (I wrote in English for everyone to understand but in English it is ok the issue is in Arabic, Persian and Hebru).
It's an annoying issue. I tried editing libraries-> cms-> html-> formbehavior.php by placing `$afterTypeDelay = $options->get('afterTypeDelay', '250000');` but it doesn't work and I couldn't find any solution.

**Comment by infograf768** [comment] 2016-06-09 07:11
@chrisdavenport 

Can you have a look?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10761">issues.joomla.org/joomla-cms/10761</a>.</sub>

**Comment by chrisdavenport** [comment] 2016-06-09 07:33
@A-Kasaaian Can you copy-paste some of the tags that are causing the issue here?  I suspect that the problem is with the UTF-8 handling so we will need some test strings to look at.

**Comment by A-Kasaaian** [comment] 2016-06-09 10:07
@chrisdavenport  I'm sorry for interrupting you. I tested tag fields a lot. It seems that `$afterTypeDelay = $options->get('afterTypeDelay', '250000');` has solved the issue, but some previously added tags like, پرو  , فیسبوک have the problem yet (the web site is using Persian language). I went to tags list and found something weird. Th mentioned tags are not listed in "components -> tags". All tags in this list are working fine and also recently added tags are fin too.

**Comment by Fedik** [comment] 2016-06-09 12:03
@A-Kasaaian the 4 letter always the same?
it sounds like Keycode problem, 
somewhere here already was opened issue for similar problem for Cyrilic keyboard layout, cannot find ..

**Comment by A-Kasaaian** [comment] 2016-06-09 12:28
@Fedik  @chrisdavenport  I found what's the problem but I don't know how to solve it. To describe the problem, while I'm typing letters other than "و" it's working fine but when I press "و" joomla selects the word as a tag automatically. It should be something with "و" ASCII code, probably.

**Comment by brianteeman** [comment] 2016-06-10 07:39
Sounds the same as #10741 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10761">issues.joomla.org/joomla-cms/10761</a>.</sub>

**Comment by brianteeman** [comment] 2016-06-10 07:42
Yes it does sound like a keycode problem with non-latin character sets using the same keycode as the latin comma causing this problem. The report about russian #10741 seems to confirm that<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10761">issues.joomla.org/joomla-cms/10761</a>.</sub>

**Comment by A-Kasaaian** [comment] 2016-06-10 10:00
You guys know these things better than me. Why this function is set on a keycode but not an ASCII code????

**Comment by chrisdavenport** [comment] 2016-06-25 11:52
Just tried to reproduce this issue, but I'm getting strange behaviour with the comma character even with pure ASCII input.  I'm pretty sure this is a JavaScript problem, so I'm going to leave it to the JS experts.

**Comment by Ssupreme** [comment] 2016-06-30 16:31
Actually, I have the same bug with pure English tags.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10761">issues.joomla.org/joomla-cms/10761</a>.</sub>

**Comment by A-Kasaaian** [comment] 2016-07-27 11:09
Isn't there any solution for this issue or any suggestion?????<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10761">issues.joomla.org/joomla-cms/10761</a>.</sub>

**Comment by A-Kasaaian** [comment] 2016-10-09 13:27
Please, check the change I made. I've tested these changes in different languages and it works very well.
https://github.com/joomla/joomla-cms/compare/staging...A-Kasaaian:patch-1
I'll be glad if you you apply it to the next release.

**Comment by brianteeman** [comment] 2016-10-09 13:28
Closed as we have a pr for testing see #12366

**Closed by brianteeman** 2016-10-09 13:28 UTC
Labels: No Code Attached Yet

**Comment by A-Kasaaian** [comment] 2017-10-18 09:08
@brianteeman several months passed. I checked pull request status. There was a conflict, which I resolved. I know you are so busy but It may help someone, if Joomla team accept the change and merge.

**Comment by ghost** [comment] 2017-10-18 09:45
@A-Kasaaian Pull Request needs 2 successfully Tests before Maintainers decide if PR is good for merge.

**Comment by A-Kasaaian** [comment] 2017-10-18 10:20
@franz-wohlkoenig I know. But, one year ago it passed both tests successfully, but no decision was taken.

**Comment by brianteeman** [comment] 2017-10-18 10:24
human tests not automated tests

**Comment by A-Kasaaian** [comment] 2017-11-15 08:12
This time I changed my solution. I simply just replaced keyup with keypress and event.which === 188 with event.charCode === 44. It should work fine and solves all the issues with all languages because "which" compares key code what is not depend on language but "charCode" is depend on language and the character you type. Comma charCode is 44 in all languages, which are containing it.

**Comment by A-Kasaaian** [comment] 2017-11-15 09:21
All auto tests are passed, human test is required.
