### ISSUE TITLE
[4.0] Several administrator menu modules - Error

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#23070] opened 2018-11-13 23:09 UTC
### Steps to reproduce the issue
Generate a new Administrator Menu. Define a Module for this menu and set it on position menu in template isis. 

In J 3.x the additional Menu is added to the Administator menu. So it is possible to extend the admin menu.
This does not make much sense, but at least it is possible 

![screen shot 2018-11-13 at 22 56 04](https://issues.joomla.org/uploads/1/5be3a81f69f2d9779ac7fdca80c935cb.png)

Do the same in J 4.0 with template atum and see this result: Another toggle button.

![screen shot 2018-11-13 at 23 03 17](https://issues.joomla.org/uploads/1/9554a703547f0c1b5b2e2f1f568574f1.png)

**Comment by ReLater** [comment] 2018-12-30 22:36
Confirmed.
And other side effects found: https://github.com/joomla/joomla-cms/issues/23397#issuecomment-450574823

**Comment by brianteeman** [comment] 2019-12-13 14:38
Seems to be ok until you toggle

**Comment by infograf768** [comment] 2019-12-15 07:29
This has been totally solved a while ago.
Remains only one toggle button. Closing.

**Closed as completed by infograf768** 2019-12-15 07:29 UTC
Labels: No Code Attached Yet, J4 Issue

**Comment by chmst** [comment] 2019-12-15 09:15
thx. Some problems are solved by waiting a year :)

**Comment by infograf768** [comment] 2019-12-15 09:20
Patience is a virtue... LOL
