### ISSUE TITLE
[4.0] Change default order for Modules (Site) from Position to Title

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#26528] opened 2019-10-09 08:37 UTC
### What needs to be fixed
In J3x, modules are listed by default in alphabetical order of title. In J4x (Content > Site Modules) the default is alpha by module position:

![default-order-by-position](https://user-images.githubusercontent.com/36987494/66465048-07d6bf00-ea78-11e9-898b-6b3e94300e88.jpg)

This applies to both the backend template nightly package downloaded 08 Oct 2019 (pictured) and to the 4.0 Dev 12 nightly update as at 07 Oct 2019.

### Why this should be fixed
Most people are likely to be searching for module name rather than position?

### How would you fix it
Ask someone else to do it.

### Side Effects expected
None

**Comment by alikon** [comment] 2019-10-09 09:18
should be quite easy to switch back to module name order like j3, just i don't know if this change was made by design/on purpose

**Comment by SharkyKZ** [comment] 2019-10-09 10:06
Modules are ordered by position by default in 3.9 too.

**Comment by Scrabble96** [comment] 2019-10-09 11:30
> 
> 
> Modules are ordered by position by default in 3.9 too.

Ah. I use Advanced Module Manager in J3.9 so perhaps the default ordering by title is built into that.

**Comment by brianteeman** [comment] 2019-10-13 23:34
This should be closed as there has been no change in Joomla

**Closed as completed** 2019-10-13 23:35 UTC
Labels: No Code Attached Yet
