### ISSUE TITLE
Problem with banner keyword search appearance on the front-end

### ISSUE THREAD

**Issue by SeoPro24** [joomla/joomla-cms#14053] opened 2017-02-13 14:21 UTC
### Steps to reproduce the issue
Add the keywords 'dog' and 'cat' to the appropriate Articles.
Add the Tags 'dog' and 'cat' to the appropriate Banners in the Banner Manager New/Edit screen.
Set the Banner module Parameter 'Search By Tags' to 'Yes' in the Banner Module Edit screen.
Checked the frontend article where the banner must appear, only a empty box appears.

### Expected result
To see the connected banners (related banners) accordingly the meta keywords in the respective page.

### Actual result
No banner appears to the article what has the same meta keywords set

### System information (as much as possible)
System Information
Setting	Value
 
PHP Built On	Linux ct1.srv.run 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64
Database Version	5.5.46-MariaDB
Database Collation	latin1_swedish_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	5.6.26
Web Server	Apache/2
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 3.6.5 Stable [ Noether ] 1-December-2016 22:46 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3006.0 Safari/537.36

### Additional comments
It looks for me like a bug that the connection with the keyword is not made. I was follow the exact official steps to accomplish the expected result.
https://docs.joomla.org/Help36:Components_Banners_Banners_Edit
Here a other user https://github.com/joomla/joomla-cms/issues/7958 had the same issue, but the bug looks like still present.

**Comment by marrouchi** [comment] 2017-02-13 16:04
I have tested and was unable to reproduce the issue. Please make sure that your banner is assigned to a category and client and that you banner module is configured accordingly.

**Comment by SeoPro24** [comment] 2017-02-14 08:41
Thank you for your fast reply & help for the workaround!
But sorry, that is a bug obviously. Its nowhere written that its mandatory to use a client and a category[.](url) And it makes also no sense for me as Admin to select a client and a category when i don't need them.

Even in the official help site of Joomla its nowhere that i could find mentioned that those fields are mandatory see yourself https://docs.joomla.org/Help25:Components_Banners_Banners_Edit

**Comment by brianteeman** [comment] 2017-03-10 11:12
Are you using the banner module in a template position or are you including it in an article using the loadmodule plugin

There was a report in the past that this will not work when included in an article

**Comment by brianteeman** [comment] 2018-03-25 10:44
It has been a year since the request for more information. I am going to close this at this time.

**Closed by brianteeman** 2018-03-25 10:44 UTC
Labels: No Code Attached Yet
