### ISSUE TITLE
menu manager - when result not found

### ISSUE THREAD

**Issue by knoby2015** [joomla/joomla-cms#6425] opened 2015-03-14 14:58 UTC
go in menu manager and then write a name what does´t exits, so you get the error
![screen shot 2015-03-14 at 09 55 52](http://issues.joomla.org/uploads/1/aa77787bf746361577de7a39318e405e.jpg)

try it with an name that menuname is not in datebase

**Comment by brianteeman** [comment] 2015-03-14 15:05
Can not replicate<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6425">issues.joomla.org/joomla-cms/6425</a>.</sub>

**Comment by losedk** [comment] 2015-03-14 15:07
@brianteeman did you enable error reporting? I can reproduce

**Comment by Harmageddon** [comment] 2015-03-14 15:08
Closing - caused by applied patch of #4661. We falsely interpreted it as a core bug. Sorry!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6425">issues.joomla.org/joomla-cms/6425</a>.</sub>

**Closed by Harmageddon** 2015-03-14 15:08 UTC
