### ISSUE TITLE
[4.0] Module Class

### ISSUE THREAD

**Issue by rinka88** [joomla/joomla-cms#29183] opened 2020-05-20 19:10 UTC
Wherever a "Module class" is used, textarea is used. And where is the "Header Class" used there input type = "text". And joomla 3 uses the same type everywhere.
http://prntscr.com/sklhzz
You can look in the module settings and wherever this class is used

**Comment by chmst** [comment] 2020-05-20 20:58
Thank you for your hint, this indeed is different, but I don't know why.  
Why is it an issue for you? What would you suggest? Both as text-area or both as text?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29183">issues.joomla.org/tracker/joomla-cms/29183</a>.</sub>

**Comment by particthistle** [comment] 2020-05-23 08:20
The only reason I'd see to change it would be for consistency.
- If you were to have a long set of module classes or header classes in a text field, you would need to move along the text box to see everything.
- The advantage with a textarea would be you can see it all and resize the textarea if you need to see more.

@rinka88 thoughts?

_@chmst Raised during PBF 23 May 2020_<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29183">issues.joomla.org/tracker/joomla-cms/29183</a>.</sub>

**Comment by brianteeman** [comment] 2020-05-23 08:32
Those were the reasons that the module class was changed to a text area. No reason that the header class couldnt be changed as well

**Comment by rinka88** [comment] 2020-05-23 08:38
I think it's better to use input type = "text"

**Comment by rinka88** [comment] 2020-05-23 08:39
> I think it's better to use input type = "text"
@chmst

**Comment by brianteeman** [comment] 2020-05-23 08:40
Can you explain why

**Comment by rinka88** [comment] 2020-05-23 08:47
When textarea move the corner then fly off the whole design. And on input type = "text" does not change from a hard-coded area.
p.s Try on joomla 4

**Comment by ReLater** [comment] 2020-05-23 10:23
I would prefer textarea for all class fields. It's common e.g. in Bootstrap 4 to use many responsive classes. I can increase the height of a textarea field to see them all but can't increase a text field.
We have this 3-columns layout (whyever) in the back-end and the width of text fields is limited and classes are hidden.

![23-05-_2020_12-22-30](https://user-images.githubusercontent.com/20780646/82728407-43b15280-9cf0-11ea-9274-612ac4b84e5c.jpg)

**Comment by rinka88** [comment] 2020-05-23 12:58
> Я бы предпочел textarea для всех полей класса. Например, в Bootstrap 4 часто используется много адаптивных классов. Я могу увеличить высоту текстового поля, чтобы увидеть их все, но не могу увеличить текстовое поле.
> У нас есть этот 3-колоночный макет (как бы то ни было) в бэк-энде, ширина текстовых полей ограничена, а классы скрыты.
> 
> ![23-05-_2020_12-22-30](https://user-images.githubusercontent.com/20780646/82728407-43b15280-9cf0-11ea-9274-612ac4b84e5c.jpg)

And you try clicking the textarea frame from the bottom, and stretch a little to the right, it will go down sharply, disrupting the design.

**Comment by particthistle** [comment] 2020-05-23 13:49
> And you try clicking the textarea frame from the bottom, and stretch a little to the right, it will go down sharply, disrupting the design.

This is partially by design: The layout uses css flex layout, and so automatically allocates the contents across the three columns proportionally. 

Resizing the text area then needs to balance out the flex columns and so if it's made longer than the second column it redistributes the contents in the columns. You would need to further wrap the content into 3 column divs to stop the layout changing as you resize the textarea. I don't think that people would be changing the size of the textarea frequently enough to warrant fixing the contents into three columns.

I agree that changing Header Class to a textarea is a good idea.

**Comment by chmst** [comment] 2020-05-23 14:49
Close this as we have a PR  #29201

**Closed as completed by chmst** 2020-05-23 14:49 UTC
Labels: No Code Attached Yet

**Comment by ReLater** [comment] 2020-05-23 14:51
> And you try clicking the textarea frame from the bottom, and stretch a little to the right, it will go down sharply, disrupting the design.

Perhaps that's a browser issue and you should open a new issue? I can't confirm this find with Firefox 76.0.1 (64-Bit)/WIN. I only can resize vertically. Not horizontally.

**Comment by particthistle** [comment] 2020-05-23 14:53
Horizontally is styled that way so the field width is fixed at 100% of the column.

**Comment by ReLater** [comment] 2020-05-23 14:57
> open a new issue?

Screenshots can be helpful then. What you mean with "disrupting the design".

@particthistle 

> Horizontally is styled that way so the field width is fixed at 100% of the column.

Yes, but @rinka88 said: "and stretch a little to the right"

**Comment by rinka88** [comment] 2020-05-23 15:12
![GIF 2](https://user-images.githubusercontent.com/40716604/82734030-86dfe580-9d31-11ea-9e92-db296bab436d.gif)
@ReLater @particthistle @chmst 
I meant it

**Comment by brianteeman** [comment] 2020-05-23 15:24
But why would you do that?

**Comment by rinka88** [comment] 2020-05-23 16:05
> But why would you do that?

Purely by accident.
There, I just moved a little to the right, and the automatic itself was pulled down. And he did not pull it. The mouse is not visible in the video.
