### ISSUE TITLE
[4.0] Menu item not enabled on view

### ISSUE THREAD

**Issue by 810** [joomla/joomla-cms#24721] opened 2019-04-24 13:09 UTC
### Steps to reproduce the issue

Install kunena 6.1 alpha 2
Go to menu - mainmenu

### Expected result

When clicking on publish item, the icon should be green.

### Actual result

The view said the item is unpublished, but when you open the menu item, you will see its published.

![image](https://user-images.githubusercontent.com/876623/56661765-b346af80-66a2-11e9-9177-3a768d265b2d.png)

### System information (as much as possible)

Joomla! 4.0.0-alpha9-dev Development [ Amani ] 19-April-2019 09:23 GMT
PHP Version | 7.3.2

**Comment by chetanmadaan** [comment] 2019-04-24 23:20
Hi,

I tested and wasn't able to reproduce on default Joomla install. My best guess it has something to do with Kunena, which we shouldn't be worried about.

Thanks,
Chetan

**Comment by 810** [comment] 2019-04-24 23:27
Its a joomla issue. 
Please create a Menu Item Alias on mainmenu, then you will see the issue.

**Comment by chetanmadaan** [comment] 2019-04-25 01:02
Hello,

My bad, I thought you said Kunena so it must have something to do with Kunena. I'll check again.

**Comment by chetanmadaan** [comment] 2019-04-25 16:06
It's working just fine. Can't reproduce this.
![2019-04-25_12-03-05](https://user-images.githubusercontent.com/3968575/56750776-7fc35e00-6752-11e9-8ff1-9cbaa19a5106.gif)

**Comment by 810** [comment] 2019-04-28 01:13
looks like a local issue then.

**Comment by SharkyKZ** [comment] 2019-04-30 06:47
Reopen please. I can reproduce this issue. It was introduced with https://github.com/joomla/joomla-cms/pull/24416, specifically this part https://github.com/joomla/joomla-cms/pull/24416/files#diff-94f7ebd2e6d116a7e0e4e66ae94f5e06R173.

**Comment by SharkyKZ** [comment] 2019-04-30 06:47
@chetanmadaan please use the latest nightly.

**Comment by infograf768** [comment] 2019-05-09 06:40
@alikon

**Comment by infograf768** [comment] 2019-05-09 07:00
I can reproduce when creating a Menu Item Alias or system links in general, not any other it seems.

**Comment by alikon** [comment] 2019-05-09 15:39
confirm, but weird

**Comment by infograf768** [comment] 2019-05-10 07:30
I can apparently solve it here by modifying the model 
/administrator/components/com_menus/Model/ItemsModel.php line 277 +
from
```
		$query->select(
			'CASE ' .
				' WHEN a.type = ' . $db->quote('component') . ' THEN a.published+2*(e.enabled-1) ' .
				' WHEN a.type = ' . $db->quote('url') . ' AND a.published != -2 THEN a.published+2 ' .
				' WHEN a.type = ' . $db->quote('url') . ' AND a.published = -2 THEN a.published-1 ' .
				' WHEN a.type = ' . $db->quote('alias') . ' AND a.published != -2 THEN a.published+4 ' .
				' WHEN a.type = ' . $db->quote('alias') . ' AND a.published = -2 THEN a.published-1 ' .
				' WHEN a.type = ' . $db->quote('separator') . ' AND a.published != -2 THEN a.published+6 ' .
				' WHEN a.type = ' . $db->quote('separator') . ' AND a.published = -2 THEN a.published-1 ' .
				' WHEN a.type = ' . $db->quote('heading') . ' AND a.published != -2 THEN a.published+8 ' .
				' WHEN a.type = ' . $db->quote('heading') . ' AND a.published = -2 THEN a.published-1 ' .
				' WHEN a.type = ' . $db->quote('container') . ' AND a.published != -2 THEN a.published+8 ' .
				' WHEN a.type = ' . $db->quote('container') . ' AND a.published = -2 THEN a.published-1 ' .
			' END AS published '
		);
```

to
```
		$query->select(
			'CASE ' .
				' WHEN a.type = ' . $db->quote('component') . ' THEN a.published+2*(e.enabled-1) ' .
				' WHEN a.type = ' . $db->quote('url') . '  THEN a.published ' .
				' WHEN a.type = ' . $db->quote('alias') . '  THEN a.published ' .
				' WHEN a.type = ' . $db->quote('separator') . '  THEN a.published ' .
				' WHEN a.type = ' . $db->quote('heading') . '  THEN a.published ' .
				' WHEN a.type = ' . $db->quote('container') . '  THEN a.published ' .
			' END AS published '
		);
```
Since 1.7 we were using the `MenusHtmlMenus` `state()` method to display the state on the grid.
It considered the `$enabled` status of the component and displayed a tip
<img width="386" alt="Screen Shot 2019-05-10 at 09 28 37" src="https://user-images.githubusercontent.com/869724/57510043-07d66580-7306-11e9-90cf-e5a213f4ab40.png">

Therefore not sure of the code above for the component as the helper method is not present anymore in 4.0

**Comment by infograf768** [comment] 2019-05-10 07:49
Note:
if we do not need anymore `$enabled` for the component, we could simplify the whole query select by taking off the `CASE`, simply using:
```
		$query->select(
			$this->getState(
				'list.select',
				$db->quoteName(
					array(
						'a.id', 'a.menutype', 'a.title', 'a.alias', 'a.note', 'a.path', 'a.link', 'a.type', 'a.parent_id',
						'a.level', 'a.published', 'a.component_id', 'a.checked_out', 'a.checked_out_time', 'a.browserNav',
						'a.access', 'a.img', 'a.template_style_id', 'a.params', 'a.lft', 'a.rgt', 'a.home', 'a.language',
						'a.client_id', 'a.publish_up', 'a.publish_down'
					)
				)
			)
		);
```
What do you think?

**Comment by infograf768** [comment] 2019-05-11 06:36
Just found out we still have the `state()` method in Service/HTML/Menus.php.
Shall we keep the method or just delete it too?

**Comment by infograf768** [comment] 2019-05-11 06:42
With former code we do get a tip, although wrongly displayed
<img width="479" alt="Screen Shot 2019-05-11 at 08 40 02" src="https://user-images.githubusercontent.com/869724/57566088-ac20e080-73c8-11e9-9b9d-1ba5f028304d.png">

**Comment by infograf768** [comment] 2019-06-12 10:02
Please test https://github.com/joomla/joomla-cms/pull/25185
closing this issue

**Closed as completed by infograf768** 2019-06-12 10:02 UTC
Labels: No Code Attached Yet, J4 Issue

**Comment by infograf768** [comment] 2019-06-13 12:18
Please test this new one
https://github.com/joomla/joomla-cms/pull/25197
