### ISSUE TITLE
Language switcher module contains link to default language with prefix

### ISSUE THREAD

**Issue by lipatovroman** [joomla/joomla-cms#40012] opened 2023-03-04 20:04 UTC
### Steps to reproduce the issue
We have multilingual site.
We configured the default language (English).
In Language Filter plugin configured Remove URL Language Code = Yes.
So, now we on main page and alternate languages displays correct. English version of the link does not have prefix /en/.

![image](https://user-images.githubusercontent.com/6747127/222926163-912f7617-d279-4f63-ad85-dd90853f78de.png)

But Language switcher module contains the prefix /en/ 

![image](https://user-images.githubusercontent.com/6747127/222926205-2221b95f-0e8c-4ed3-83b9-dfde0da17d24.png)

Yes, when we select default English language, we'll get 301 redirect to the URL without prefix.
But it happens for all site URLs. 
So, my site have 20K items and hundreds categories and 5 additional languages.
It means, that we're getting more than 100K 301 redirects just because module have not correct link to the default language page.

![image](https://user-images.githubusercontent.com/6747127/222926464-cee28778-dd67-4122-accf-babd4498f2dd.png)

**Comment by richard67** [comment] 2023-03-05 12:24
That has been reported in past several times, see e.g. issues #26480 and #23144 , and several attempts to fix it have failed, see e.g. #23178 and #28265 , so the issues had been closed as expected behaviour. That's why I label this issue not as a bug but as a new feature.

**Comment by wojtekxtx** [comment] 2023-03-06 06:48
@lipatovroman as of your first screeshot: `URL` for default `lang` does not include `lang` prefix because default language is mapped to `site root` (`/`)

**Comment by lipatovroman** [comment] 2023-03-12 17:13
> @lipatovroman as of your first screeshot: `URL` for default `lang` does not include `lang` prefix because default language is mapped to `site root` (`/`). See [.htaccess file](https://github.com/joomla/joomla-cms/blob/8da00729eb22d445d23d8d7d78b1008c63bb8550/htaccess.txt)

I'm talking about link from the module. It's mapped to the site.com/en/ and then redirects to domain root.

**Comment by Hackwar** [comment] 2024-04-07 12:21
You reported this again as #41634. Since these are duplicate reports, I'm closing this one.

**Closed as completed by Hackwar** 2024-04-07 12:21 UTC
Labels: Feature, No Code Attached Yet

**Comment by lipatovroman** [comment] 2024-05-02 16:07
> You reported this again as #41634. Since these are duplicate reports, I'm closing this one.

All my reports and all reports from other users were closed.
Problem not solved.
Someone wrote, that it's not a bug, it's a feature.
If this is a feature, so how to disable it?
I don't need thousands of 301 redirects on my site.
Google Search Console sends me alerts, that my site have too much 301 redirects.
Why alternate URLs are different with URLs from language module?
So, again. If it's a feature (strange, bad feature) - we should have ability to disable it.

**Comment by nikosfa** [comment] 2025-02-10 18:45
Same problem here. 
There should be a "quick and dirty" in the module to overcome the problem, since this IS real problem for SEO.

**Comment by fgsw** [comment] 2025-02-11 05:21
@nikosfa Please comment at #41634 (it's the open Issue; comments on closed Issues like here are mostly ignored).

**Comment by Kycb27** [comment] 2025-02-12 09:55
> Та же проблема в Joomla 5. Кто-нибудь нашел решение? Должно быть исправление в этом модуле, так как это РЕАЛЬНАЯ проблема для всех сайтов Joomla, так как эта "фича" имеет очень плохие последствия для SEO на многоязычных сайтах.

I changed the module a little, maybe my solution will help: 
src/modules/mod_languages/src/Helper/LanguagesHelper.php
```
use Joomla\CMS\Component\ComponentHelper;
use Joomla\CMS\Plugin\PluginHelper;
```
```
$default_lang = ComponentHelper::getParams('com_languages')->get('site', 'en-GB');
$plugin = PluginHelper::getPlugin('system', 'languagefilter');
$pluginParams = json_decode($plugin->params);

```
```
 if ($multilang) {
...
  if ($pluginParams->remove_default_prefix && $language->lang_code === $default_lang) {
                        $language->link= preg_replace('|/' . $language->sef . '/|', '/', $language->link, 1);
                    }
}
```

**Comment by fgsw** [comment] 2025-02-12 10:03
@Kycb27 Please comment at #41634 (it's the open Issue; comments on closed Issues like here are mostly ignored).
