### ISSUE TITLE
Publishing tab still shows

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#44118] opened 2024-09-20 09:04 UTC
### Steps to reproduce the issue
In Article Options >>> Editing Layout (tab) ...Publishing options Hide
Login front end as Super User (or as as user with 'Edit State')

### Expected result
The 'Publishing' tab does not show

### Actual result
The 'Publishing' tab shows but the 'Metadata' tab does not show

**Comment by fgsw** [comment] 2024-09-20 10:40
#37816 related?

**Comment by brianteeman** [comment] 2024-09-20 13:20
Can you check if there is a difference here between j4 and j5

**Comment by Webdongle** [comment] 2024-09-20 14:25
J3.4.4.8 Hide set SHOW
![fe edit 01](https://github.com/user-attachments/assets/e07fc4e0-d72d-4aae-b2b5-244b8b5ae4ec)

J3.4.4.8 Hide set HIDE
![fe edit 02](https://github.com/user-attachments/assets/99697a31-5bd5-49a8-b000-f6a348ddc3ee)

**Comment by brianteeman** [comment] 2024-09-20 14:47
@Webdongle 
> Can you check if there is a difference here between j4 and j5

**Comment by Webdongle** [comment] 2024-09-20 15:26
Doesn't look like any difference to me.  Have a look at the screenshots please.  Does that look the same as J5 to you?

**Comment by brianteeman** [comment] 2024-09-20 15:51
Your screenshots are both for j4

**Comment by Webdongle** [comment] 2024-09-20 20:22
Yes and when I compare them to J5 they look the same.  When you have J5 up and compare them to the J4 screenshots do they look the same to you?

**Comment by Pinkeltje** [comment] 2024-09-26 09:25
Can reproduce in J5 as well

**Comment by coolcat-creations** [comment] 2024-10-11 06:59
What needs to be done here? 
I read the other closed PRs and guess its a naming issue.

Instead of the Option to Show or Hide "Publishing Options" maybe "Publishing Date fields" ? 
And why is Metadata hidden with it, should that be added as extra option or should the condition be removed?

**Comment by Pinkeltje** [comment] 2024-10-11 08:16
Not a programmer but I think problem with Metadata showing is because tab is inside the if condition of publishing tab.
"components\com_content\tmpl\form\edit.php"
`  <?php // Do not show the publishing options if the edit form is configured not to. ?>
        <?php if ($params->get('show_publishing_options', 1) == 1) : ?>
            <?php echo HTMLHelper::_('uitab.addTab', 'myTab', 'publishing', Text::_('COM_CONTENT_FIELDSET_PUBLISHING')); ?>
            <div class="row">
                <div class="col-12 col-lg-6">
                    <fieldset id="fieldset-publishingdata" class="options-form">
                        <legend><?php echo Text::_('JGLOBAL_FIELDSET_PUBLISHING'); ?></legend>
                        <div>
                        <?php echo LayoutHelper::render('joomla.edit.publishingdata', $this); ?>
                        </div>
                    </fieldset>
                </div>
                <div class="col-12 col-lg-6">
                    <fieldset id="fieldset-metadata" class="options-form">
                        <legend><?php echo Text::_('JGLOBAL_FIELDSET_METADATA_OPTIONS'); ?></legend>
                        <div>
                        <?php echo LayoutHelper::render('joomla.edit.metadata', $this); ?>
                        </div>
                    </fieldset>
                </div>
            </div>
            <?php echo HTMLHelper::_('uitab.endTab'); ?>
        <?php endif; ?>`

**Comment by coolcat-creations** [comment] 2024-10-11 08:47
Yes I know, that's what I am asking if there was any reason putting it in the condition. and what needs to be done, then I create a PR

**Comment by Pinkeltje** [comment] 2024-10-11 08:59
Edited my previous contribution. Think this solves it.

**Comment by Pinkeltje** [comment] 2024-10-11 12:33
Just found out that when doing this, one is unable to select category (which is located in publishing tab.
Maybe it can be solved by changing line 57 to
                <?php echo $this->form->renderField('articletext'); ?>
                  <?php if ($params->get('show_publishing_options', 1) == 0) : ?>
                  <?php echo $this->form->renderField('catid'); ?>
   <?php endif; ?>

**Comment by chmst** [comment] 2024-10-13 18:21
Where did you set the param, @Webdongle? I cannot find any param for for the frontend. 
`show_publishing_options` is meant as param for the **backend**, but for some reason it is used in the edit screen on frontend.

I would see this as a bug in frontend edit screen.

![Image](https://github.com/user-attachments/assets/4f3e2a84-a85e-42f2-8ffa-930b48abd2df)

**Comment by brianteeman** [comment] 2024-10-13 19:48
@chmst where is that text from? I would say that the text is wrong for both publishing and article options and that text and its use of the word TAB are what is causing the confusion. For me everything is working exactly as it was designed

**Comment by Webdongle** [comment] 2024-10-14 01:24
@brianteeman 
That is from the help page for Article options

@chmst 
When the option is **show** then on the front end the frontend edit screen shows **more options** on the Publishing tab (the header that says 'Publishing').  And the Metadata tab (the header that says 'Publishing') is **seen**
When the option is **Hide** then on the front end the frontend edit screen shows **less options** on the Publishing tab (the header that says 'Publishing').  And the Metadata tab (the header that says 'Publishing') is **NOT seen**.

@brianteeman 
Says that is as expected.

So if that is the way it is supposed to work then we have to work with it and hope someone can update the help docs.


Spot the difference

Set Show
![Image](https://github.com/user-attachments/assets/7683454d-eda4-4ac5-8496-cc575e5d57eb)

Set Hide
![Image](https://github.com/user-attachments/assets/afc8481e-bebd-4410-a18e-06ca6f6f7e15)

**Comment by coolcat-creations** [comment] 2024-10-14 05:54
Should we just clean up these options a bit and add options for frontend and backend and make everything more clear?

**Comment by chmst** [comment] 2024-10-14 06:44
I have prepared a PR with a re-arrangement of fields and tabs. Will commit when I am back on my laptop. 

But I disagree with changing the docs. All these switches are only for backend and it is not consistent that one of theses switches is for backend and frontend, the others are not. 
We schould have eihter a switch for Show_published on frontend (like for images) or show always all fields

**Comment by Webdongle** [comment] 2024-10-14 09:57
> But I disagree with changing the docs. All these switches are only for backend 

But the Help screen says the switch is for admin when the switch actually alters fields and removes a whole tab from the edit screen in the front end.

Perhaps the questions should be:
Why is the layout of front edit screen different to the admin edit screen (except of course for the Permissions tab)
and
Why does the switch have different affects on the front edit screen than it does the admin side.

**Comment by chmst** [comment] 2024-10-14 10:29
> Perhaps the questions should be:
Why is the layout of front edit screen different to the admin edit screen (except of course for the Permissions tab)
and
Why does the switch have different affects on the front edit screen than it does the admin side.

This is the question, but I have no answer. Please test the PR #44246 if this is convenient.

**Comment by brianteeman** [comment] 2024-10-14 10:57
the help screen is simply wrong. the code is correct

**Comment by chmst** [comment] 2024-10-14 11:13
If the code is correct, then the help screen is wrong. 
The question is, IF the code is correct. 

Fact is, that the edit screen is confusing, because general article options and publishing Option are mixed in one tab.

**Comment by Webdongle** [comment] 2024-10-14 12:19
I do not understand why you have the featured field in one tab but Start Featured and Finish Featured in a different tab

**Comment by brianteeman** [comment] 2024-10-14 14:04
> If the code is correct, then the help screen is wrong. The question is, IF the code is correct.


Check the history of the code. That gives you the answer

**Comment by coolcat-creations** [comment] 2024-10-14 14:25
Where is the PR @chmst :-)

**Comment by chmst** [comment] 2024-10-14 14:27
https://github.com/joomla/joomla-cms/pull/44246

**Comment by chmst** [comment] 2024-10-14 14:27
https://github.com/joomla/joomla-cms/pull/44246

**Comment by coolcat-creations** [comment] 2024-10-14 14:28
thank you :-)

**Comment by chmst** [comment] 2024-12-15 12:11
I close this for now, https://github.com/joomla/joomla-cms/pull/44246 resolves the issue.

**Closed as completed by chmst** 2024-12-15 12:11 UTC
Labels: No Code Attached Yet, bug, UI/UX
