### ISSUE TITLE
Super admin can't access categories

### ISSUE THREAD

**Issue by rajmohanvy** [joomla/joomla-cms#15960] opened 2017-05-11 07:16 UTC
Hi team,
After upgrade the joomla to 3.7, the super admin can't access the categories. Only public categories has been displayed.

Ex :  Categories name        - Content Editor
        Access group Name   -  Content owner

In back end i can't use this categories from super admin.

PHP version : 5.6

**Comment by photodude** [comment] 2017-05-14 23:10
Is the super-admin checked in all access groups?

**Comment by Vityushka** [comment] 2017-05-15 14:09
Same problem (or similar). After upgrading to 3.7 I can't add articles to some category. Also categories are not displayed in drop-down filter (but still here in Categories component. As I see in permissions tab - Superuser can manage this categories.

**Comment by rajmohanvy** [comment] 2017-05-16 12:57
@photodude 

No, There is different type of access level i used. In old version no limitation for super admin. Am i correct...

**Comment by stevlam** [comment] 2017-05-16 17:35
also have the issue in 3.7.0 in the category selector box.
I think is this line https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_categories/models/fields/categoryedit.php#L189 that causes the issue.
when i deleted that line it worked like it worked in 3.6.5.

maybe that line needs to be inside a if (!$user->authorise('core.admin')) to allow super users to view all.

note: i wrote this also here because i think this is the same issue as the other one https://github.com/joomla/joomla-cms/issues/15799

**Comment by photodude** [comment] 2017-05-16 22:39
@rajmohanvy Super Users "group" must always be checked in the view access levels see the image in this section of the Joomla ACL tutorial https://docs.joomla.org/J3.x:Access_Control_List_Tutorial#Access_Levels

When someone forgets to check the Super Users group or if someone removed it by mistake it can create unusual access issues (there are atypical reasons to do this, but for everyone else, it should be checked). Always important to double check that all the settings are correctly set to ensure proper ACL function. (I can't count how many times a co-admin unchecked the Super Users group and then was wondering why things were not functioning as expected)

**Comment by stevlam** [comment] 2017-05-17 18:29
Example of bug:
- 3.7.1 joomla default install
- Create category name "Guest Category" with "Guest" acess level
- Create article and put it in "Guest Category" - not possible, no "Guest Category" in the category selector. cannot also chosse "Guest Category" in search tools box.
- in 3.6.5 worked.

This change from 3.6.5 to 3.7.0 https://github.com/joomla/joomla-cms/commit/a7ae028f76a006270c8931946978f9e32eeaec90 seem to be the problem

**Comment by mbabker** [comment] 2017-05-17 18:33
The fact that commit causes the problem indicates a misconfigured viewing access level setup on your site(s), as mentioned above.

**Comment by stevlam** [comment] 2017-05-17 18:45
I used default Guest acess level of joomla.
To confirm is not my site problem also tried a new joomla 3.7.1 install and it's the same behaviour.

**Comment by stevlam** [comment] 2017-05-18 10:27
tried again using joomla 3.7.1 default joomla zip install file from https://downloads.joomla.org/latest
also same result

try to explain further.

Categories list: category name "test" assigned to "Guest" acess level
![image](https://cloud.githubusercontent.com/assets/28737091/26197496/59f25156-3bba-11e7-92d2-96b179c03f56.png)

Articles list: there is an article assigned to Guest acess level and super user can edit. But there is no "test" category in the filters - Problem!
![image](https://cloud.githubusercontent.com/assets/28737091/26197525/7029896c-3bba-11e7-9ded-564dd3a07df0.png)

Edit article: super user can edit a article with "Guest" acess. But there is no "test" category in the category selector - Problem!
![image](https://cloud.githubusercontent.com/assets/28737091/26197583/ac2309de-3bba-11e7-930a-d93ed55c3b19.png)

And as a super user when save existent article created by other user assigned to "test" category goes back to "Uncategorized" - Problem!

only happens in 3.7.0 and 3.7.1.
please try ... seems like a bug to me...

**Comment by franz-wohlkoenig** [comment] 2017-05-18 13:08
@stevlam thanks for Explanation, can confirm issue.
### System information
3.7.2-dev
macOS Sierra, 10.12.4
Firefox 53 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by stevlam** [comment] 2017-05-23 10:33
any chance a fix for this in 3.7.3?

**Comment by franz-wohlkoenig** [comment] 2017-05-23 10:36
@stevlam if a Dev. has Time and is interested.

**Comment by stevlam** [comment] 2017-05-23 10:44
OK. thanks. hope is interest.
Besides the super user issue. Content writers Losing the categories when editing article because access   levelss a real problem for my sites.
Probably people that use several  view. acess levels are having this issue too

**Comment by franz-wohlkoenig** [comment] 2017-05-23 11:39
Please open a new Issue about "Content writers Losing the categories" if neccessary so every issue has only one Topic Dev's has to look on.

**Comment by stevlam** [comment] 2017-05-24 00:09
@franz-wohlkoenig after some tests discovered the content writers thing was my mistake. sorry.

the only real issue is the one described in this issue and futher explained in https://github.com/joomla/joomla-cms/issues/15960#issuecomment-302365268

**Comment by idefax** [comment] 2017-05-29 07:32
I can reproduce the problem as follows:
1.	Install Joomla! 3.7.2 with example data and login at the backend as Super User.
2.	Create a new user group with “Public” as parent group.
3.	Create a new access level. Assign the newly created user group to it.
4.	Got to category manager and create a new category. Set access to the access level created before. 
5.	Go to article manager and open any article. Assign the newly created category and save.
6.	Open the article that got the new category assigned in step 5.
Result: In the Dropdown “Category” the new category is missing.
7.	In article manager, click the Search Tools button. Open the dropdown menu for categories.
Result: The new category is missing.

Adding the user group “Super User” to the access level created in 3. will solve the problem. 
But: A Super User always should be able to see all categories in the backend.
This problem is new since 3.7.0. It does not exist in 3.6.5.

It’s a big problem if upgrading a 3.6.5 site to 3.7.2 and if that site has many different access levels. Editing an article means losing the assigned category, unless you add “Super User” to all access levels first.

**Comment by franz-wohlkoenig** [comment] 2017-05-29 07:55
@idefax thanks, Issue is confirmed.

**Comment by ggppdk** [comment] 2017-05-29 08:22
The 'categoryedit' field is e.g. used here:
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_content/models/forms/article.xml#L45-L46

And it used to be, that it only considered core.create ACL  for creating / assigning records to categories
- now it also considers the access levels !

This was done by PR #12931

**This is a change in a very long standing behavior**,
and also i believe it is **wrong change** too because

Access levels are for viewing the categories, right ?
they are not a replacement or a complement to  "core.create" ACL

**Comment by Bakual** [comment] 2017-06-01 08:17
See https://github.com/joomla/joomla-cms/pull/16411

Closing as there is a PR

**Closed by Bakual** 2017-06-01 08:17 UTC
Labels: No Code Attached Yet
