### ISSUE TITLE
[4.0] \Joomla\Input\Input inconsistency with J3 (B/C issue?)

### ISSUE THREAD

**Issue by Ruud68** [joomla/joomla-cms#34542] opened 2021-06-17 15:39 UTC
### Steps to reproduce the issue
create a SEF url with Route::_ like this:
```
Route::_('index.php?option=com_example&task=payment.response&processor=paylater&order=1234567890&test1=123&test2=456', true, Route::TLS_IGNORE, true)`
```
the router builds the following URL:
```
[yourdomain]/nl/sub/payment-page/payment/response?processor=paylater&amp;order=1234567890&amp;test1=123&amp;test2=456
```

now in the site controller for com_example do a var_dump for: \Jooma\Input\Input

### Expected result

The extra query parameters (order, test1, test2) should be part of the data (retrievable with getString)

### Actual result
Joomla 3: this works okay as the following data is in Input:
```
protected 'data' => 
    array (size=12)
      'processor' => string 'paylater' (length=8)
      'amp;order' => string '1234567890' (length=10)
      'amp;test1' => string '123' (length=3)
      'amp;test2' => string '456' (length=3)
      'language' => string 'nl-NL' (length=5)
      'order' => string '1234567890' (length=10)
      'test1' => string '123' (length=3)
      'test2' => string '456' (length=3)
      'Itemid' => string '4490' (length=4)
      'option' => string 'com_example' (length=20)
      'task' => string 'payment.response' (length=16)
      'lang' => string 'nl-NL' (length=5)
```

On Joomla 4 however this will fail as the data is not fully stored / converted, as you can see below only the (e.g. 'amp;order' is stored and not 'order' so trying to getString('order') will fail

```
protected 'data' => 
    array (size=4)
      'processor' => string 'paylater' (length=8)
      'amp;order' => string '1234567890' (length=10)
      'amp;test1' => string '123' (length=3)
      'amp;test2' => string '456' (length=3)
```

### Additional comments
workaround (or better solution) is not to use \Joomla\Input\Input but Factory::getApplcation()->input as this works correct in both Joomla 3 and Joomla 4

**Comment by Fedik** [comment] 2021-06-17 15:59
I not fully understood what exactly you dumping, and how it related to `Route::_()`
but yes, you should always use `$app->input`


In Joomla 3 `Input::$data` is reference to `$_REQUEST`, so the changes applies in both ways:
https://github.com/joomla/joomla-cms/blob/9cb87eed8770c2db53f75df2f887c2f06acef048/libraries/vendor/joomla/input/src/Input.php#L112-L115

in Joomla 4 `Input::$data` is copy of `$_REQUEST`:
https://github.com/joomla-framework/input/blob/bba837434b13a0d5cb495bb6eeee3547da306f8e/src/Input.php#L93-L98

**Comment by Ruud68** [comment] 2021-06-17 16:07
Thanks for the followup :)
I have search documentation and especially the BC document but couldn't find any reference to this difference in J3 / J4
In order to avoid time loss / 'frustration' / debugging why things are not working as expected this should at least be documented.
That is why I took the time to report, already started to change (and test everything all over again) for my own extensions :)

**Comment by Ruud68** [comment] 2021-06-17 18:59
And is in J4 the $_REQUEST by design or should it be &$_REQUEST like it is in J3?

**Comment by Fedik** [comment] 2021-06-17 20:04
I cannot say, I do not know.
I suspect it is by design, but better to ask someone who know :)

**Comment by HLeithner** [comment] 2021-06-17 20:34
It's expected but need documentation @wilsonge ?

Reference https://groups.google.com/g/joomla-dev-framework/c/ngYzAqZMnSY

**Comment by Ruud68** [comment] 2021-06-18 06:41
Thanks @HLeithner for digging this up. Should definitely be documented as it is (imo) a b/c break. My experience is that when it happens to me, it will for sure happen to others to :)

**Comment by wilsonge** [comment] 2021-06-18 09:03
Yeah I think this is expected. We can definitely add it to the b/c breaks page

**Comment by Hackwar** [comment] 2024-03-29 10:52
@wilsonge can you write the documentation or can we close this one?

**Comment by HLeithner** [comment] 2024-03-29 13:13
here is the page to document it https://docs.joomla.org/index.php?title=Potential_backward_compatibility_issues_in_Joomla_4/en&action=edit

Sadly I'm not allowed to edit it @wilsonge

**Closed as completed** 2024-04-02 12:51 UTC
Labels: No Code Attached Yet, Documentation Required, bug
