### ISSUE TITLE
[4.0] API: Token can not be reset

### ISSUE THREAD

**Issue by Hackwar** [joomla/joomla-cms#28962] opened 2020-05-06 09:47 UTC
### Steps to reproduce the issue
Go to the user manager, edit your super user and maybe save it once to generate a token in the "Joomla API Token" tab. Now set the "Reset" switch to yes and save again. Notice that the token stays the same.

### Expected result
The token changes.

### Actual result
The token stays the same

### Additional comments
I couldn't find any code related to the reset in the plg_user_token plugin. Is this maybe currently missing?

**Comment by brianteeman** [comment] 2020-05-06 10:43
I can not confirm - working fine for me

![mods](https://user-images.githubusercontent.com/1296369/81168395-d0d57700-8f8e-11ea-8cd1-a1d1a9c563a6.gif)

**Comment by richard67** [comment] 2020-05-06 12:33
I can't reproduce either. What I've noticed is that the first 14 characters of the token remain the same, so on a small screen it may appear as if it had not changed.

**Comment by Quy** [comment] 2020-05-06 19:52
Not reproducible. Here is code to reset: https://github.com/joomla/joomla-cms/blob/4.0-dev/plugins/user/token/token.php#L296

**Comment by jwaisner** [comment] 2020-05-06 21:52
@Hackwar can you retest this? It seems it is not reproducible by many. Is there any additional environmental elements to take into account?

**Comment by richard67** [comment] 2020-05-07 17:32
I still think @Hackwar was just confused by the first 14 characters of the tokens always being equal, but the rest not, and on small screen you only see those 14 characters, so it appears as if the token wouldn't change.

**Comment by Quy** [comment] 2020-05-07 17:34
I thought that too initially, so this can be closed.

**Comment by richard67** [comment] 2020-05-07 17:39
Let's wait a bit before we close it, maybe we get feedback before.

**Comment by Hackwar** [comment] 2020-05-07 17:45
I've checked this quickly on that installation again and the tokens are both 100% identical. However I have to do some more tests and see if there are some side effects which come into play here. Anyway, I did the necessary steps probably 5 times and I always get the same token. Will report back soon.

**Comment by richard67** [comment] 2020-05-07 17:46
Maybe that installation is broken somehow?

Does it have the code which Quy linked above? https://github.com/joomla/joomla-cms/blob/4.0-dev/plugins/user/token/token.php#L296

**Comment by Quy** [comment] 2020-07-13 03:07
Closing as non-reproducible.

**Closed as completed by Quy** 2020-07-13 03:07 UTC
Labels: No Code Attached Yet, Information Required
