### ISSUE TITLE
Guest modules dissapear from back-end

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/joomla-cms#18974] opened 2017-12-04 14:13 UTC
### Steps to reproduce the issue

In the front-end, modules assigned to the **Guest** group. However, in the back-end, when a module is assigned to the **Guest** group, they cannot longer be accessed from the list by the Super User.

To test it, in a clean Joomla 3.8.2, assign a module ("Most Read Posts" or "Older Posts") to the Guest group. 

### Expected result

The modules must be shown in the module manager always to the administrator (Super User).

### Actual result

After it is assigned to the group, the module disappears.

### System information (as much as possible)

J 3.8.2

### Additional comments

The issue seems to be located here:

administrator/components/com_modules/models/modules.php (line 317-319)

	$user   = JFactory::getUser();
	$groups = implode(',', $user->getAuthorisedViewLevels());
	$query->where('a.access IN (' . $groups . ')');

If the administrator user is manually added to the Guest group, then the admin user can access the Guest modules.

Issue found and credit to |@sergiois

**Comment by mbabker** [comment] 2017-12-04 14:14
Duplicate of #18542 and numerous other items.

**Closed as completed by mbabker** 2017-12-04 14:14 UTC
Labels: No Code Attached Yet
