### ISSUE TITLE
Issue backend on tablet

### ISSUE THREAD

**Issue by webmasterab** [joomla/joomla-cms#18347] opened 2017-10-15 21:31 UTC
### Steps to reproduce the issue

if I want to customize on the backend on my tablet
and then I mean rights to a menu.
This does not work because I can not click on anything in the drop-down menu.
If I do it on my mobile, I get a choice option see picture.
how can i do it on the tablet too

translated with Google![screen shot 2017-10-15 at 21 31 11](https://issues.joomla.org/uploads/1/cf18727af93c359849f135e8bd046bfb.png)

**Comment by brianteeman** [comment] 2017-10-15 21:35
please use the forum for support https://forum.joomla.org

**Comment by N6REJ** [comment] 2017-10-15 21:43
why are you summarily dismissing this @brianteeman <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18347">issues.joomla.org/tracker/joomla-cms/18347</a>.</sub>

**Comment by webmasterab** [comment] 2017-10-15 22:00
why closed
This is not a help question
I can not choose from pulldown menus on a tablet.

even here at issue report of category can not be done
but fortunately you can type it again so that it is chosen.

This is not a support question
but a serious issue message !!

already tried.

If there is more information then I would like to hear that<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18347">issues.joomla.org/tracker/joomla-cms/18347</a>.</sub>

**Comment by N6REJ** [comment] 2017-10-16 02:03
@webmasterab can you post the exact url to the issue?  Or at the very least include detailed steps to recreate? What did you push, what plug-in, extension, template, etc...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18347">issues.joomla.org/tracker/joomla-cms/18347</a>.</sub>

**Comment by C-Lodder** [comment] 2017-10-16 08:16
Which browaer are you using on your tablet? Could simply be a matter of jquery chosen that need updating.

**Comment by webmasterab** [comment] 2017-10-16 09:00
1. I log in and then go to articles
2. If I want to choose if I only have the items in the litter box, I have to click on it, see attachment.
3. I get to see the options but can not click on anything
4. On my mobile I get a kind of popup that I can choose.
5. Have it on both chrome and on my tablet.

thanks for the weather being open and you want to think and watch with me
![20171016_105203](https://user-images.githubusercontent.com/8011751/31603688-3237cf24-b261-11e7-848c-52152f763c13.png)

**Comment by webmasterab** [comment] 2017-10-16 09:02
have it with all other options that have to be chosen in this way.

ps: Also on my mobile phone issue site, I was having trouble on my mobile to make a category.
I could not click this either.

**Comment by C-Lodder** [comment] 2017-10-16 09:27
jQuery Chosen should be completely disabled on both mobiles and tablets. The fact it's still working seems odd. Which tablet are you using?

**Comment by webmasterab** [comment] 2017-10-16 09:48
How can i disabel Jquery
My tablet is Android 6.0.1

**Comment by C-Lodder** [comment] 2017-10-16 10:02
It's not a jQuery related issue, but a Chosen issue. Chosen is a jQuery plugin for select boxes.

When I asked what tablet you're using, I ment the make/model
Samsung Galaxy Tab, Asus ZenPad, etc...

**Comment by C-Lodder** [comment] 2017-10-16 10:20
That said, unless the Joomla hacks in this plugin have caused any issues which I don't believe they have, then this is the wrong place to raise an issue and instead should be raised on the [jQuery Chosen Github repo](https://github.com/harvesthq/chosen/issues)

**Comment by webmasterab** [comment] 2017-10-16 10:20
Its a tablet galaxy tab a

Can i disable the plugin?

**Comment by C-Lodder** [comment] 2017-10-16 10:30
I suppose you could create a layout override for this layout: https://github.com/joomla/joomla-cms/blob/staging/layouts/joomla/html/formbehavior/chosen.php

Then just remove the code from the overide so that the plugin doesn't get imported. Please note, I haven't tested that.

@brianteeman - you can close this again as it's **not** a Joomla related issue

**Comment by webmasterab** [comment] 2017-10-16 11:27
will also test this on a clean installation

**Comment by ghost** [comment] 2017-10-16 11:37
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18347">issues.joomla.org/tracker/joomla-cms/18347</a>.</sub>

**Closed as completed by ghost** 2017-10-16 11:37 UTC
Labels: No Code Attached Yet

**Comment by N6REJ** [comment] 2017-10-16 22:10
@C-Lodder tyvm!  I appreciate you finding the root cause.
If I'm understanding things correctly, jquery chosen control how controls behave? 
And it loaded automatically by J! load jquery routine.

I'm asking cause I want to spend a bit of time better understanding this issue.  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18347">issues.joomla.org/tracker/joomla-cms/18347</a>.</sub>

**Comment by brianteeman** [comment] 2017-10-16 22:11
It is loaded by behaviour chosen which younwilkmsee at the topmof many/most views

**Comment by brianteeman** [comment] 2017-10-16 23:45
Sorry for the typos

**Comment by webmasterab** [comment] 2017-10-21 09:43
@N6REJ And do you also have this problem on the tablet.
You're welcome to spend some time there too.
Hopefully we will find out what to do.

**Comment by N6REJ** [comment] 2017-10-22 18:46
I can CONFIRM this issue.  
@webmasterab only my "Samsung Galaxy View 18.4" tablet ( only has horizontal mode ) I do NOT have this issue.
only the Samsung Galaxy Tab 3 ( 7" ) VERTICALLY I do NOT see the search tool and Horizontally I'm unable to select ANY of the drop down menu options.
so, imo This is definitely a bug!
I'm running J! 3.8.1

@franz-wohlkoenig we need to reopen this I think. unless @mbabker has a better idea?

**Comment by brianteeman** [comment] 2017-10-22 18:51
Check the code. You will see that search tools are not enabled for small
width screens

**Comment by N6REJ** [comment] 2017-10-22 19:33
![22751311_10210686674108626_1073483051_o](https://user-images.githubusercontent.com/1850089/31865545-e033d950-b735-11e7-9f62-98d5e0d8c094.jpg)
![22751351_10210686674148627_2017730141_o](https://user-images.githubusercontent.com/1850089/31865546-e134332c-b735-11e7-8ec3-34b346a394e4.jpg)
@brianteeman ok, but that still doesn't explain horizontal where the tool IS available.

**Comment by dgrammatiko** [comment] 2017-10-22 21:43
This will be fixed in J4 (we're dropping the outdated chosen). For J3 unless someone wants to spent time to patch chosen I don't see any solution (BTW you can't disable chosen partially if other scripts depends on it!)
