### ISSUE TITLE
[com_fields] Guest access level not working

### ISSUE THREAD

**Issue by sanderpotjer** [joomla/joomla-cms#14380] opened 2017-03-06 10:30 UTC
### Steps to reproduce the issue
Set the `Access` for a field to "Guests". In that way a field should not be visible to logged in users (assuming you have the Guest access level correctly configured). Check if field is visible in the frontend, login on the frontend and notice the field is still visible. 

Please see the screenshots below. To check if the Guest access level is working correctly I have set the "Login" menu-item to `Access` Guest too.

#### Before logging in
![guest-before](https://cloud.githubusercontent.com/assets/522834/23606181/ea6876e6-025f-11e7-84f4-bace4f025d94.png)

#### After logging in
![guest-after](https://cloud.githubusercontent.com/assets/522834/23606187/ed307e82-025f-11e7-97ac-f5ea7701a897.png)

#### Backend settings field
![screen shot 2017-03-06 at 11 29 24](https://cloud.githubusercontent.com/assets/522834/23606262/375fd110-0260-11e7-9ddf-7bfccbf1204d.png)

### Expected result
The field with access set to Guest **should not be visible** after login.

### Actual result
The field with access set to Guest **is visible** after login.

**Comment by franz-wohlkoenig** [comment] 2017-03-06 10:51
Confirmed. Field is always shown, independend of which Acces-Level is set.

**Comment by coolcat-creations** [comment] 2017-03-06 11:27
The Access Level is working only for the INPUT field i think?

**Comment by Bakual** [comment] 2017-03-06 14:16
Can you please try with a user that isn't allow to manage the fields (actually doesn't have global "core.admin" permission)? Because the ACL check is skipped for those.

**Comment by sanderpotjer** [comment] 2017-03-06 14:23
@Bakual then the field is indeed not displayed if you login. So it indeed seems to be an issue when you have "core.admin" permissions.

**Comment by Bakual** [comment] 2017-03-06 14:46
Good. That doesn't mean the code is correct but it explains the behaviour :smile: 
The code in question is https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_fields/models/fields.php#L230-L235

We need that check because we use the same model in frontend and backend. And we obviously need to be able to see fields with access level "guest" in backend :smile: 
I'm not sure if that could be solved easy somehow. Maybe with an additional check for the application (site vs administrator)?

**Comment by laoneo** [comment] 2017-03-07 15:46
@Bakual guess the easiest solution would be indeed to do an application check.

**Comment by laoneo** [comment] 2017-03-11 19:25
What happens when somebody doesn't have view access but can edit the field, should the field then be visible when editing an article?

**Comment by Bakual** [comment] 2017-03-11 19:36
Try to keep it consistent with other places in the CMS. Eg look what happens if a user isn't set to see an article but could edit it.

**Comment by laoneo** [comment] 2017-03-20 08:32
I made a test and could successfully edit an article I don't have the necessary access level. So when we can agree that in fields it will be the same that the access level is not checked when editing an article then I can do a pr for it. But first I would like to get a confirmation for it. @sanderpotjer what do you think about that?

**Comment by laoneo** [comment] 2017-04-01 12:42
I would like to get that solved, any opinions about the proposal to make it work the same way as with articles?

**Comment by laoneo** [comment] 2017-04-11 19:44
Should we label this one as release blocker?

**Comment by brianteeman** [comment] 2017-04-11 19:52
Y4s

**Comment by zero-24** [comment] 2017-04-11 20:25
> I made a test and could successfully edit an article I don't have the necessary access level.

What does that exactly mean?

**Comment by Bakual** [comment] 2017-04-11 20:45
@sanderpotjer Can you give your inputs one Allons question?

**Comment by laoneo** [comment] 2017-04-12 04:16
@zero-24 That I logged in as a user which does belong to the Registered user group only. I gave an article edit permission for the Registered groups. On the front, I logged in as that user and started to edit an article. Then I set the access level of that article to special in the back end. On the front where I'm logged in as registered user I hit the F5 button. I'm still able to save the article, despite the fact that I don't have the right access level.

**Comment by Bakual** [comment] 2017-04-12 05:05
Imho F5 on the edit view does bypass some checks since you have the flag already set in the session. A more appropriate test would be to use the original "&task=edit" link on an article you haven't edited yet in that session.

**Comment by rdeutz** [comment] 2017-04-17 13:56
@laoneo please implement it in the way it is done in other areas so that we can merge it after RC3, don't wait any time longer on Sander

**Comment by rdeutz** [comment] 2017-04-17 14:14
removed release blocker, because it is not critical, to get the information you just need to log out and get it. The way around would be a bigger problem

**Comment by Bakual** [comment] 2017-04-18 08:19
Closing as we have a PR to test: https://github.com/joomla/joomla-cms/pull/15365

**Closed by Bakual** 2017-04-18 08:19 UTC
Labels: No Code Attached Yet
