### ISSUE TITLE
[4.0] Modules batch language

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#24264] opened 2019-03-20 14:52 UTC
there has been a change in
        joomla-cms/administrator/components/com_modules/tmpl/modules/default_batch_body.php
 since joomla 3

It looks like it was an attempt to fix an issue whereby the language option didnt appear when a site had multiple admin languages installed but its not correct as it results in two language selectors when batch changing site modules.

From my tests the third instance of the language selector needs to be removed and that the problem is that this code is never evaluating as true and that is the real bug

`$clientId == 1 && ModuleHelper::isAdminMultilang`

**Comment by infograf768** [comment] 2019-03-21 07:40
The issue is a duplicate.
`$clientId == 1 && ModuleHelper::isAdminMultilang` is evaluated as true when param is set to yes
```
        <div class="form-group col-md-6">
			<div class="controls">
				<?php echo LayoutHelper::render('joomla.html.batch.language', []); ?>
			</div>
		</div>
```
making patch now

**Comment by brianteeman** [comment] 2019-03-21 07:44
It should be that's correct but my test of that didn't work. Maybe I missed something but I tried for a while.

**Comment by infograf768** [comment] 2019-03-21 07:50
It works here for that part, but we still have an issue for the type field.
Working on both now

**Comment by infograf768** [comment] 2019-03-21 08:15
Please test
https://github.com/joomla/joomla-cms/pull/24273
Closing as we have a patch.

**Closed as completed by infograf768** 2019-03-21 08:15 UTC
Labels: No Code Attached Yet
