### ISSUE TITLE
Timezone offset added to Article Publishing Dates when changing categories if fields are applying to categories.

### ISSUE THREAD

**Issue by JamesNGarrett** [joomla/joomla-cms#15995] opened 2017-05-13 04:15 UTC
### Steps to reproduce the issue

1. Create a category.
2. Create a content > field group.
3. Create a content > field and add this field to the field group and assign to the category made in step 1
4. Set the Global Config to a timezone - anything without an offset of 0 will do
5. Create and save an Article
6. Change the article's category causing the page to refresh due to the custom field
7. Switch to the Publishing tab
8. Look at the Start Publishing and Created Date entries
9. Gasp in horror

### Expected result
Once the article is saved the start publishing and created date fields should not change unless the user changes them

### Actual result
The timezone offset is added to / subtracted from both dates every time the category is changed - thus causing issues with new articles being pending.

### System information (as much as possible)
Tested on cloud linux cpanel and a ubuntu 14 vm
Tested on php7.0 and 5.6
Tested on Joomla 3.7.0 and 3.7.1 RC1
Tested with both TinyMCE and JCE

**Comment by franz-wohlkoenig** [comment] 2017-05-13 06:46
Confirmed. 

Set Timezone on "Chicago", Published Time is (7h earlier) `2017-05-13 01:41`. After change Article to Category using com_fields Published Time is `2017-05-12 20:41`.

**Comment by photodude** [comment] 2017-05-14 23:07
I think this has been addressed in 3.7.1 with the fix the JDate, perhaps someone can confirm that this has been fixed.

**Comment by fmmarmello** [comment] 2017-06-01 14:31
So... Was this fixed?
Having this issue in 3.7.2

**Comment by gabrielnazario25** [comment] 2017-06-05 20:18
I am experiencing the exact same issue, in Joomla 3.7.2

**Comment by andrepereiradasilva** [comment] 2017-06-06 18:08
confirmed ... why does changing category with fields changes the article published and created date!?!?!
this is not related to the JDate issue in 3.7.0

This is probably some JS behaviour that is doing this

**Comment by andrepereiradasilva** [comment] 2017-06-06 18:34
The reload is caused by [categoryHasChanged](https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_fields/helpers/fields.php#L340) js function that is submitng the article form to com_fields and, with it, sending all the article form data.

Com_fields [receives the article form data](https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_fields/controllers/field.php#L67) (which as already the wrong date) and redirect the app back to the article edit view (which now loads the wrong date).

@dgt41 any idea why the article form js submit event send the wrong date in this scenario (different timezone)? Could it be something related to the calendar?

**Comment by dgt41** [comment] 2017-06-06 18:44
> This is probably some JS behaviour that is doing this

I think is the way the data is passed to the form the second time (2 transformations === wrong time)
Javascript should always parse and print (send to PHP) UTC dates `new Date("2017-03-25T12:00:00-06:30");` but that was out of question for J3.x due to B/C break, maybe in J4?

@mbabker @wilsonge can we change the value of form field calendar to `2017-03-25T12:00:00-06:30`?

**Comment by andrepereiradasilva** [comment] 2017-06-06 18:46
i think the second time the date is `2017-03-25 12:00:00` format

**Comment by dgt41** [comment] 2017-06-06 18:49
Let's ping @laoneo here, he's more familiar with the Fields code

**Comment by laoneo** [comment] 2017-06-07 06:35
I will have a look together with @Bakual. Not an easy one to fix to keep everything intact. Basically the validate function does need to be called. From a first glance I have no clue how.

**Comment by Bakual** [comment] 2017-06-07 14:25
Yep, that's indeed not an easy fix. Running the validate method (which would apply the tz difference back) would require that we know the form (the XML) itself, but we don't know that at this point. Also it would mean that it fails when the form is invalid (eg no title yet). So it's not a viable solution imho.

Basically the current solution to reload the whole form with new custom fields is sort of a hack.

Ideally we would use some AJAX which replaces the custom fields (and fieldsets) itself with the new ones directly without reloading the whole form. But that is probably not that easy as well due to the possibility of template overrides. But I'd say it is the most promising approach (my JS skills lack me here however)

**If** we had an "autosave" feature which saves the current work into an "autosave version" in the version history, then that one could be used for the reloading. But while that would be an interesting feature, it needs someone to write it first  and it's probably not simpler :smile:

**Comment by fmmarmello** [comment] 2017-06-07 15:24
What about saving the original value (from DB) in State, Session or LocalStorage..
Overwrite this if the user changes the field .. maybe ? If not, we apply TZ to the "original" value

**Comment by Bakual** [comment] 2017-06-07 15:37
To decide if the TZ has to be applied or not (and which one, server or user TZ), you need the form definition. That one as well as the original value isn't available in the browser. So you can't do anything here. Maybe we could make it available to the browser somehow, but in the end it would just be another hack specific to fields and calendar formfields.
On server side, we already have the validate method which does change the value back based on TZ settings and form definition. So if we have to deal with it on the server, we already have the method to do it. What we don't have within com_fields at this point is the form definition.

**Comment by laoneo** [comment] 2017-06-07 15:40
A way would be to go over the controller of the extension (eg. ContentControllerArticle) to store the data into the session instead of the com_fields controller, just with another task like `reload` for example.

**Comment by laoneo** [comment] 2017-06-13 11:33
Please test #16665 which should fix the issue.

**Comment by brianteeman** [comment] 2017-06-13 11:34
Closed as we have a PR for testing

**Closed by brianteeman** 2017-06-13 11:34 UTC
Labels: No Code Attached Yet
