### ISSUE TITLE
Cassiopeia mobile menu collapse bug

### ISSUE THREAD

**Issue by xeno024** [joomla/joomla-cms#44140] opened 2024-09-26 06:10 UTC
### Why this should be fixed
I have discovered a bug in the Cassiopeia theme, and I can't find a solution to it, and I don't even know what's causing it.
Searching, I found such a page, and it appears here, on several browsers: https://cassiopeia.joomla.com/help/menu-module
When in mobile view, and I open the hamburger menu ("Page Modules" - menu module settings in the "Advanced" tab under "Layout" - "Collapsible Dropdown" ), then open the submenus, any of them, then close the entire hamburger menu as is, then open it again... If you play this for a while, randomly, something will get stuck, and suddenly their collapsible submenus won't open. I'm watching the inspector, can't find the cause of the error.
Has anyone experienced anything similar?
Does anyone know what could cause this bug?

### How would you fix it
It's probably a javascript error, but I can't fix it, I don't understand OOP JS that well

### Side Effects expected
The mobile menu works properly and does not get stuck.

**Comment by chmst** [comment] 2024-09-29 19:57
This is a privete demo site, not Jooma core. 

Can you replicate the effect with an own freshly installed site with cassiopeia?

**Comment by tiny-play** [comment] 2024-09-30 08:25
Helpful tips for writing essays and tips for doing exam exercises and [wordle unlimited](https://wordleunlimited.io "wordle unlimited") online.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44140">issues.joomla.org/tracker/joomla-cms/44140</a>.</sub>

**Comment by xeno024** [comment] 2024-09-30 09:13
Yes, I saw it afterwards, sorry!
I could repeat it, on localhost, with a fresh install, without any settings. Unfortunately, the error occurred there too. It must be a cassiopeia error, I just can't find where to write about it.

**Comment by Fedik** [comment] 2024-10-03 08:50
The bug was also reproduced at joomla.stackexchange https://joomla.stackexchange.com/a/33969/87

**Comment by coolcat-creations** [comment] 2024-10-09 16:12
@richard67 I found that the issue is in this file: build/media_source/templates/site/cassiopeia/js/mod_menu/menu-metismenu.es6.js 
I also found out that the Problem occurs when the transitioning is delayed then sometimes the collapsing class and the inline 0px are not removed from the submenu
But I dont have enough Javascript skills to fix it. Since you wrote that block, maybe you know what to do to fix it? The issue only appears in Chrome.

**Comment by richard67** [comment] 2024-10-09 17:11
> [@richard67](https://github.com/richard67) I found that the issue is in this file: build/media_source/templates/site/cassiopeia/js/mod_menu/menu-metismenu.es6.js I also found out that the Problem occurs when the transitioning is delayed then sometimes the collapsing class and the inline 0px are not removed from the submenu But I dont have enough Javascript skills to fix it. Since you wrote that block, maybe you know what to do to fix it? The issue only appears in Chrome.

@coolcat-creations I am no javascript expert either, and I don't remember having written that block.

**Comment by coolcat-creations** [comment] 2024-10-09 17:50
Sorry I misinterpreted the information in the IDE, was it @dgrammatiko ?

**Comment by dgrammatiko** [comment] 2024-10-09 18:13
Without testing anything I can only comment on the code and it seems that there's a racing condition on lines https://github.com/joomla/joomla-cms/blob/5.2-dev/build/media_source/templates/site/cassiopeia/js/mod_menu/menu-metismenu.es6.js#L18-L19

The `mm.hide(event.detail.shownElement);` is an asynchronous fn and needs to finish any animations before calling synchronous the next line `window.removeEventListener('click', mmClick);`. Probably there's another event when the hide has finished and if so the next line should execute there. If not before calling the `mm.hide()` the animation should be tracked and fire the removeListener on the animation.finished. Either would work the first is way easier (if there's such an event)

**Comment by coolcat-creations** [comment] 2024-10-10 07:46
@dgrammatiko @richard67 sorry in my IDE I had this "Info" in my screen that's why I asked first Richard, 

![Image](https://github.com/user-attachments/assets/6c9295e4-04e1-48fa-9a9e-d20474d81569)

Yesterday I checked the file then with my phone and could not find blame, but it was mentioning you Dimitris in the history, no idea why.

![Image](https://github.com/user-attachments/assets/edb2e8d3-fbee-4e21-b0ba-2588b4cfb46d)

:-) 

Thank you for the code, I will test it and create a PR if its working

**Comment by richard67** [comment] 2024-10-10 12:12
Closing as having a pull request. Please test #44221 . Thanks in advance.

**Closed as completed by richard67** 2024-10-10 12:12 UTC
Labels: No Code Attached Yet, bug
