### ISSUE TITLE
Modern Routing creates invalid URL links in menu: List of tagged items

### ISSUE THREAD

**Issue by EricdeWaal** [joomla/joomla-cms#34998] opened 2021-07-31 10:31 UTC
### Steps to reproduce the issue
1 create some tags
2 add tags to some articles
3 create Menu item: Tags > Tagged items or Tags > Compact list of tagged items, select a tag to be displayed
4 open this menu item in front-end
5 click link to an article in the list

### Expected result
aricle is displayed

### Actual result
invalid link in Modern URL Routing: /?view=article&id=311:6-augustus-bbq-weekend&catid=37
works in Legacy URL Routing; created link: /37-agenda/2021/311-6-augustus-bbq-weekend

### System information (as much as possible)
Joomla version: 3.9.28
PHP version: 7.4.22
WebServer to PHP Interface: cgi-fcgi 
OS: Debian 4.19.194-1

**Comment by brianteeman** [comment] 2021-07-31 11:07
Just trying to help debug this. Is it only on articles where the title begins with a number

**Comment by EricdeWaal** [comment] 2021-07-31 11:52
Well spotted, Brian! I did a test with an article where the name dus not start with a number and then it works as expected.
Did not notice it before because we only use this for an agenda where all item names start with a date.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34998">issues.joomla.org/tracker/joomla-cms/34998</a>.</sub>

**Comment by brianteeman** [comment] 2021-07-31 11:55
It is still a bug but at least
1. You can work around it
2. It isnt going to hold up your site waiting for a fix

**Comment by wilsonge** [comment] 2021-08-15 22:27
// cc @Hackwar

**Comment by Hackwar** [comment] 2022-10-31 20:51
Is this still an issue?

**Comment by EricdeWaal** [comment] 2022-11-01 11:07
Yes it is in the latest version of J!3

**Comment by Hackwar** [comment] 2022-11-01 11:19
JA doesn't get any Bugfixes anymore, so the question was related to J4.

**Comment by Hackwar** [comment] 2022-11-03 09:35
After further investigations, this is not a bug but a misconfiguration. You have to either set your homepage to be of a category type and then make the category 37 reachable via that menu item or create a (hidden) menu item for this. Closing this one here.

**Closed as completed by Hackwar** 2022-11-03 09:35 UTC
