### ISSUE TITLE
[4.3 RC] Unable to toggle check status of a single updated override file using the "Checked" status icon

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#40393] opened 2023-04-14 17:18 UTC
### Steps to reproduce the issue

Make changes to an updated override and then click the X next to the file name in the Updated Files tab

### Expected result
File marked as updated and X changed to tick

### Actual result
Orange message saying "No file selected"

![image](https://user-images.githubusercontent.com/36987494/232112695-b3acee48-e8f8-439b-8f98-1e83a53e8726.png)

I have tried with the check box to the left of the X ticked and without. With the same result.
I logged out and back in again. Same result.
I cleared the cache. Same result.

### System information (as much as possible)
PHP 8.0.28 on Litespeed server

**Comment by richard67** [comment] 2023-04-16 12:13
I can confirm that changing the checked status by clicking on the "Checked" icon does not work. I have checked on a clean, current 4.3-dev branch with a new installation.

Maybe there is some relation to PR #39380 ?

For creating changed updated files I have proceeded as described in that PR. The SQL statements I have modified to the extension ID and so on are not hard-coded.

So I have created in the template manager in backend for the Cassiopeia template overrides of the default views of com_content/article and com_newsfeed/newsfeed.

Then I have run the following SQL statements to create the two changed overrides:

```
INSERT INTO `j3ux0_template_overrides` (`id`, `template`, `hash_id`, `extension_id`, `state`, `action`, `client_id`, `created_date`, `modified_date`)
SELECT 1, `name`, 'L2h0bWwvY29tX25ld3NmZWVkcy9uZXdzZmVlZC9kZWZhdWx0LnBocA==', `extension_id`, 0, 'Joomla Update', `client_id`, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
  FROM `j3ux0_extensions`
 WHERE `name` = 'cassiopeia' AND `type` = 'template' AND `element` = 'cassiopeia' AND `client_id` = 0;

INSERT INTO `j3ux0_template_overrides` (`id`, `template`, `hash_id`, `extension_id`, `state`, `action`, `client_id`, `created_date`, `modified_date`)
SELECT 2, `name`, 'L2h0bWwvY29tX2NvbnRlbnQvYXJ0aWNsZS9kZWZhdWx0X2xpbmtzLnBocA==', `extension_id`, 0, 'Joomla Update', `client_id`, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
  FROM `j3ux0_extensions`
 WHERE `name` = 'cassiopeia' AND `type` = 'template' AND `element` = 'cassiopeia' AND `client_id` = 0;
```

After that, go to the Home Dashboard in backend so the Overrides Check runs.

Then you have 2 changed override files.

Selecting one or both files and changing the "checked" status with the action from the "... Check Overrides" dropdown action menu works.

But toggling the status of one file by clicking the "Checked" icon doesn't work, even if the tooltip says it should work. You get the "No file selected" error message.

**Comment by richard67** [comment] 2023-04-16 12:16
Confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40393">issues.joomla.org/tracker/joomla-cms/40393</a>.</sub>

**Comment by richard67** [comment] 2023-04-16 22:17
Closing as having a pull request. Please test #40397 . Thanks in advance.

**Closed as completed by richard67** 2023-04-16 22:17 UTC
Labels: No Code Attached Yet, bug

**Comment by Scrabble96** [comment] 2023-04-17 13:24
I just tried to test this using the Patch Tester component and got this message:

"There are no files to patch from this pull request. This may mean that the files in the pull request are not present in your installation."

My overrides are in a custom template, not Cassiopeia

**Comment by richard67** [comment] 2023-04-17 13:27
@Scrabble96 You can't test the PR with patchtester because it changes javascript sources. To rebuild the javascript it needs a development environment with NPM. Or you use the patch package or custom update URL created by Drone for that PR.
