### ISSUE TITLE
XAMPP 3.3.0 J4.2.9

### ISSUE THREAD

**Issue by rgtr** [joomla/joomla-cms#40134] opened 2023-03-16 11:55 UTC
### Steps to reproduce the issue
Running Windows 11 Pro on an HP Z2 Tower G9 with i9 processor and 32.0 GB (31.7 GB usable)
Started Xampp - had some problems with starting my SQL - starts then closes ... 3rd time runs port:3306
This is a recurring problem . . . Apache starts ok but mysql often faults . . . 
Run Kickstart 7.2.0 

### Expected result
Unzips file ok.
Does the ANGIE check ok
Click the Next button - Firefox says its busy - seem to be in a loop somewhere . . . .

### Actual result
nothing happens

### Additional comments
J 4.2.8 works fine ...
Noted that upgraded Akeeba Backup ... is that the fault ?

I hate Windows 11 . . .  so many weird things happen

**Comment by brianteeman** [comment] 2023-03-16 13:11
I'm not really sure why you have posted this here as your problem is occuring when you are using the installer from akeebabackup.

Having said that I doubt very much that the problem lies with that software either. As you have said - mysql regularly _dies_. Whatever is causing that is most likely to be the cause of your problems.

This should be closed as not a joomla bug

**Comment by drmenzelit** [comment] 2023-03-16 13:18
Please post your problem in the forum: forum.joomla.org , there is the better place to ask for help.

**Closed as completed by drmenzelit** 2023-03-16 13:18 UTC
Labels: No Code Attached Yet

**Comment by rgtr** [comment] 2023-03-16 13:31
Thanks
Will do
Fired up my old w7 machine, and all worked fine.
W11 is a disaster !
Richard

**Comment by brianteeman** [comment] 2023-03-16 13:44
fyi I am using windows 11 with no problems at all.
