### ISSUE TITLE
[4.0] WYSIWYG Editor "Page Break" Button leads to 404

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18618] opened 2017-11-17 20:35 UTC
### Steps to reproduce the issue

edit content on frontend 
using the WYSIWYG Editor "Page Break" Button, press that button

### Expected result

page break something ... 

### Actual result

popup with a 404 inside
![screen shot 2017-11-17 at 20 34 16](https://user-images.githubusercontent.com/400092/32967819-de211c58-cbd6-11e7-917a-dc43c246c33a.png)

**Comment by ghost** [comment] 2017-11-18 09:15
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18618">issues.joomla.org/tracker/joomla-cms/18618</a>.</sub>

**Comment by mbabker** [comment] 2017-11-18 09:34
This and the other similar issues are due to a logic bug in the component dispatchers.  The request needs to trigger the admin component classes but the dispatcher is using the site component classes.  // @laoneo @wilsonge

**Comment by ghost** [comment] 2017-11-21 14:11
~~@PhilETaylor can you please recheck? Didn't get Error anymore.~~

**Comment by PhilETaylor** [comment] 2017-11-21 14:35
@franz-wohlkoenig You mean recheck with current git commit on the 4.0 branch or recheck Alpha 2 ?

**Comment by ghost** [comment] 2017-11-21 14:35
Test was on Backend, my Fault.

**Comment by ghost** [comment] 2018-03-31 17:45
closed as having Pull Request #20040

**Closed as completed** 2018-03-31 17:45 UTC
Labels: No Code Attached Yet, J4 Issue
