### ISSUE TITLE
[4.0] [RFC] Private Messages

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#19542] opened 2018-02-02 19:44 UTC
### Steps to reproduce the issue
Open the in backend the component for private messages. Components | Messaging | New private message and create a message. Fill a correct user name into the field Recipient or fill in a possible id into the field Recipient.

### Expected result
I can choose a user than seeing a 0 in the field recipient and when click send the message is send.

### Actual result
If you insert an id or if you insert an user name an error occurs.

![private messages write test administration 1](https://user-images.githubusercontent.com/9974686/35751520-3587dc2a-0859-11e8-99c1-f778ad6eafb2.png)
![private messages write test administration 2](https://user-images.githubusercontent.com/9974686/35751521-35b57a04-0859-11e8-934d-b1439c7a81a1.png)
![error 500 could not instantiate mail function](https://user-images.githubusercontent.com/9974686/35751707-c4295dd2-0859-11e8-8acd-59563e09a94e.png)

### Systeminformation
I tested on a local machine on ubuntu with the current branch 4.0-dev

### Additional comments
Do we really need the component messaging?

**Comment by anuragteapot** [comment] 2018-02-04 09:45
@astridx Issue Confirmed.
Error <code>500 Could not instantiate mail function.</code>

One question, Is recipient field takes both <code>ID</code> and <code>Username</code> ?

**Comment by ReLater** [comment] 2018-02-05 19:44
Concerning Recipient field and 0 instead of user selection. Similiar reason as described here for Parent Item in com_menus
https://github.com/joomla/joomla-cms/issues/18633#issuecomment-363194678

Change line https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_messages/forms/message.xml#L6
to
```
type="UserMessages"
```
and you'll see the user selection.

**Comment by brianteeman** [comment] 2018-02-15 15:18
I cannot replicate this with the current staging - can you recheck as it looks like it has been resolved elsewhere

**Comment by ReLater** [comment] 2018-02-15 15:22
@brianteeman 
Did you test it with Mamp or Xampp or similiar or with a "real" Linux/LAMP environment?

See also https://github.com/joomla/joomla-cms/issues/18633#issuecomment-363194678 and following discussion

**Comment by anuragteapot** [comment] 2018-02-15 15:26
@brianteeman I can replicate this issue.

OS-Linux
Xampp
PHP-7.1

**Comment by astridx** [comment] 2018-02-15 20:23
I added the RFC label, because I wonder if we really need the component messaging in Joomla! 4 or if we can remove it?

**Comment by brianteeman** [comment] 2018-02-16 00:24
It is essential if we want to have any sort of workflow

**Comment by brianteeman** [comment] 2018-05-22 21:40
Closed as the reported bug has been resolved

**Closed as completed by brianteeman** 2018-05-22 21:40 UTC
Labels: RFC, No Code Attached Yet, J4 Issue
