### ISSUE TITLE
[4.0] Mass email HTML Mode sends text/plain header

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29536] opened 2020-06-09 18:34 UTC
### Steps to reproduce the issue

Go to Admin -> Users -> Mass Mail Users

Tick "Send in HTML Mode" after reading the help which states

> Send in HTML mode. Whether or not to send the Email with headers that identify it as an HTML document. Email clients that support this will render any HTML codes.

Compose mail using HTML tags

Send the email 

### Expected result

Email sent as HTML and renders as HTML because of correct HTML content-type header in the email. 

### Actual result

Email sent as plain text with wrong header

```
Content-Type: text/plain; charset=utf-8
Date: Tue, 9 Jun 2020 18:29:11 +0000
From: Test <phil@phil-taylor.com>
MIME-Version: 1.0
Message-ID: <KxC1Z9ohNmRpZBG4jwZo6PJJpTxKNs9v2rdNOc7uk@localhost.localdomain>
Received: from localhost.localdomain by mailhog.example (MailHog)
          id iZEbrW-062JQBGZHslpAC3SmXyvlvAbRFBXdyJWBeuQ=@mailhog.example; Tue, 09 Jun 2020 18:29:11 +0000
Return-Path: <phil@phil-taylor.com>
Subject: asd
To: "phil@phil-taylor.com" <phil@phil-taylor.com>

<test>asd</test>

```

<img width="429" alt="Screenshot 2020-06-09 at 19 33 56" src="https://user-images.githubusercontent.com/400092/84186239-2d451e00-aa88-11ea-850b-d8f98868b3e4.png">

### Additional comments

Note: Joomla 3.9.19 Sends in HTML Mode with correct headers:

<img width="275" alt="Screenshot 2020-06-09 at 19 37 12" src="https://user-images.githubusercontent.com/400092/84186608-b0667400-aa88-11ea-8015-a35bfb7da3b0.png">

```
<snip>
To: 
Subject: test
X-PHP-Script: thecabanajersey.com/administrator/index.php for 87.244.90.206
X-PHP-Originating-Script: 601:class.phpmailer.php
Date: Tue, 9 Jun 2020 18:30:31 +0000
To: undisclosed-recipients:;
From: testsite <phil@phil-taylor.com>
<snip>
Message-ID: <7d3476f5416c357af43cdf24dfa9118b@thecabanajersey.com>
MIME-Version: 1.0
Content-Type: text/html; charset=utf-8
<snip>

<h1>test</h1>

```

**Comment by richard67** [comment] 2020-06-09 20:21
You have to enable HTML in the mail template.

**Comment by richard67** [comment] 2020-06-09 20:22
And then in the template the HTML box needs some content.

But it might be some bug left with that.

**Comment by PhilETaylor** [comment] 2020-06-09 20:23
> You have to enable HTML in the mail template.

Act like a user, not a Joomla developer. 

There is nothing to say this and no documentation to tell you that's the case 

A user would click the box and expect it to be HTML

**Comment by richard67** [comment] 2020-06-09 20:26
Yes, documentation about mail templates has to be made, and that HTML check box in the mass mail form either has to be removed because HTML mode shall controlled with the mail template, or it has to be fixed so it works, there I agree with you.

Wanted to make an issue about that and then have forgotten about it.

Good we have one now.

**Comment by richard67** [comment] 2020-06-09 20:28
Issue confirmed.

**Comment by brianteeman** [comment] 2021-05-24 14:25
This can be closed as its no longer relevant with mail templates

**Comment by richard67** [comment] 2021-05-24 14:30
Closing as stated in previous comment. Thanks @brianteeman for the hint.

**Comment by PhilETaylor** [comment] 2021-05-24 14:35
Im sorry but you are both completely wrong. This has nothing to do with Mail Template and Mail Templates is not used by the Mass Mail feature of com_users which allows an admin to type their own email and send it. 

I have tested again today and again I can replicate the issue. 

```
Content-Type: text/plain; charset=utf-8
Date: Mon, 24 May 2021 14:34:05 +0000
From: Joomla4 <phil@phil-taylor.com>
MIME-Version: 1.0
Message-ID: <FRNMKxxGnpucbVpnv1DA7PlsRG7Y4m0dTUxRst9yoQA@localhost.localdomain>
Received: from localhost.localdomain by mailhog.example (MailHog)
          id XTyVLw-TMnpCELjDviFbxW6k1Z_c5sE74wpYsxrqu2o=@mailhog.example; Mon, 24 May 2021 14:34:05 +0000
Return-Path: <phil@phil-taylor.com>
Subject: asdfasdf
To: Joomla4 <phil@phil-taylor.com>

<h1>test</h1>

```

<img width="1291" alt="Screenshot 2021-05-24 at 15 35 05" src="https://user-images.githubusercontent.com/400092/119363359-a17ece80-bca5-11eb-98bb-8e4027809d4e.png">

**Comment by PhilETaylor** [comment] 2021-05-24 14:37
> Yes, documentation about mail templates has to be made, and that HTML check box in the mass mail form either has to be removed because HTML mode shall controlled with the mail template, or it has to be fixed so it works, there I agree with you.

> Wanted to make an issue about that and then have forgotten about it.

**Comment by PhilETaylor** [comment] 2021-05-24 14:38
Plus - if Mail Template is set to BOTH (Plain and HTML) then how on earth is a Mass Email meant to be created in two modes... there is a lot of work needed here to make this compatible with mail templates :-(

**Comment by richard67** [comment] 2021-05-24 14:41
> Plus - if Mail Template is set to BOTH (Plain and HTML) then how on earth is a Mass Email on this screen meant to be created in two modes so that its inserted with the `{BODY}` tag into the mail template?

Multi-part MIME should be used, as far as I remember. text part coming from the text template and html part from the html template of a mail template.

**Comment by brianteeman** [comment] 2021-05-24 14:42
sorry I confused this with private messges

**Comment by PhilETaylor** [comment] 2021-05-24 14:48
> Multi-part MIME should be used, as far as I remember. text part coming from the text template and html part from the html template of a mail template.

But... the Mail Template just has a place holder for the `{BODY}` that is provided the text your type in this text area... you only get one text area to type in and that same text is injected into the plain and html mail template ... so still impossible for me to send a nicely formatted email if BOTH is enabled in Mail Templates. 

This checkbox on the right is totally misleading and no longer actually used - the only use this has right now is that if its NOT checked, then the input is filtered to remove html formatting... 

Like I said,  there is a lot of work needed here to make this compatible with mail templates :-(

**Comment by PhilETaylor** [comment] 2021-05-24 14:49
> sorry I confused this with private messges

Again not sure why you would - Private Messages dont use Mail Templates at all and are always HTML as they have a WYSIWYG Editor for their construction.

**Closed as completed** 2022-03-07 18:39 UTC
Labels: No Code Attached Yet

**Comment by rinenweb** [comment] 2024-11-28 09:18
Issue is still replicated after 2,5 years. I agree the "Send in HTML Mode" checkbox on the right is totally misleading if it doesn't serve the intended purpose. Mass mail should either send the message in HTML when this checkbox is checked or this checkbox should be removed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29536">issues.joomla.org/tracker/joomla-cms/29536</a>.</sub>
