### ISSUE TITLE
[4.0b1] Another example of feedback message out of view

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29491] opened 2020-06-08 15:22 UTC
### Steps to reproduce the issue

Edit Global Config in Joomla 4.0.0 b1 on a screen that requires you to scroll down to get to the bottom of the page

Enable SMTP Mail for mail settings
Enable Authentication for SMTP (just to make a longer page) 
Click send test email

### Expected result

Feedback where I can see it - did my email go or not? Was it a success or not?

### Actual result

Actual feedback is way off screen at the top of the page - not visible to the user
User is not forced to the top of the screen to see the feedback
user grumpy and needs more coffee

<img width="1920" alt="Screenshot 2020-06-08 at 16 23 10" src="https://user-images.githubusercontent.com/400092/84049458-62784000-a9a4-11ea-9a34-27c235765f8c.png">

----

<img width="1920" alt="Screenshot 2020-06-08 at 16 19 23" src="https://user-images.githubusercontent.com/400092/84049296-2a70fd00-a9a4-11ea-84f0-6321c252d7f9.png">

### Additional comments
another example https://github.com/joomla/joomla-cms/issues/29291

**Comment by brianteeman** [comment] 2020-06-08 18:47
We don't need multiple reports of the same thing. We both know the fix for one will fix for both. If necessary you can add this information to the other report.

Please close.

**Comment by PhilETaylor** [comment] 2020-06-08 18:50
Its not the same thing. And you dont know what the fix is so you cannot claim it will fix this either.

**Comment by brianteeman** [comment] 2020-06-19 22:22
It is exactly the same problem as #29461 

It is a fundamental problem caused by the change from _popup_ alerts to fixed messages

**Comment by HLeithner** [comment] 2021-01-08 14:44
I'm closing this because it's the related as #29461 thanks for the report.

**Closed as completed by HLeithner** 2021-01-08 14:44 UTC
Labels: No Code Attached Yet
