### ISSUE TITLE
[4.0] Reload core feature missing.

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#26453] opened 2019-10-02 17:27 UTC
### Steps to reproduce the issue
go to systems -> update/joomla->set options to "test" or some other setting if desired
run update check.

### Expected result
![image](https://user-images.githubusercontent.com/1850089/66066865-fb9ab100-e50f-11e9-9bb6-48e3382f6b30.png)

### Actual result
![image](https://user-images.githubusercontent.com/1850089/66066816-e32a9680-e50f-11e9-8de3-6ae5cf6fe89a.png)

**Comment by ChristineWk** [comment] 2019-10-02 17:38
It seems OK for me - above response. If you are going to: Reinstall Joomla core files, the system will take the latest nightly building.
Just check after this: database, if it's up to date. 
Are you on Custom Url > Update Channel: https://update.joomla.org/core/nightlies/next_major_list.xml
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26453">issues.joomla.org/tracker/joomla-cms/26453</a>.</sub>

**Comment by N6REJ** [comment] 2019-10-02 23:25
@ChristineWk where do you see the reinstall core button?

**Comment by ChristineWk** [comment] 2019-10-03 09:36
@N6REJ 
![live_update](https://user-images.githubusercontent.com/15275917/66115891-0a499c80-e5d2-11e9-8a04-533776934194.JPG)

**Comment by ChristineWk** [comment] 2019-10-03 09:45
Ah, I see the point/difference. 

You are on the "Testing" update channel. This channel is designed for testing new releases and fixes in Joomla.
It is only intended for JBS (Joomla Bug Squad™) members and others within the Joomla community who are testing. 

There is no connection to Custom Url (Update channel).

**Comment by N6REJ** [comment] 2019-10-03 18:26
ok, so the update feature is missing from testing channel then? Is this by design or bug? 
if design then we can discuss a possible enhancement in squad.

**Comment by ChristineWk** [comment] 2019-10-03 22:01
Someone from JBS Team can answer that question. 
I see now, you are a Member, therefore :-)
https://volunteers.joomla.org/teams/bug-squad

**Comment by ChristineWk** [comment] 2019-10-03 22:02
> 
> 
> > ok, so the update feature is missing from testing channel then? Is this by design or bug?
> > Someone from JBS Team can answer that question.
> > if design then we can discuss a possible enhancement in squad.
> > I saw, you are a Member, therefore :-)
> > https://volunteers.joomla.org/teams/bug-squad

**Comment by ChristineWk** [comment] 2019-10-03 22:03
> 
> 
> ok, so the update feature is missing from testing channel then? Is this by design or bug?
> if design then we can discuss a possible enhancement in squad.

**Comment by Quy** [comment] 2020-01-10 04:48
https://developer.joomla.org/nightly-builds.html

For V4, see the following from the above link.

> To always use the latest version and test the update component you can use this custom update server: https://update.joomla.org/core/nightlies/next_major_list.xml

**Comment by richard67** [comment] 2020-01-10 17:34
The reinstall core button shall reinstall the files from the same version which is already installed, it shall not do an update and not do anything with database.

If you are on the nightly build URL as custom URL then the nightly build is not the same "version" as installed, even if they both are "4.0-beta1-dev", because between the installed software and the current nightly build there might have been changes.

So even if that should work with nightly build it would be wrong in my opinion, because between the installed nightly build from days or weeks ago and the nightly build of today there might have been code changes in the file, and maybe even database changes.

And what is also not supported anymore since 3.5 is to update the files and then run the database fixer to apply the database changes, which would be same as using the "reinstall core files" to update the files to a later nightly and then using db fixer.

**Comment by brianteeman** [comment] 2020-12-24 15:25
This should be close as its not an issue

**Comment by richard67** [comment] 2020-12-24 19:29
Closing as expected behaviour. Feel free to re-open if I'm wrong.

**Closed as completed by richard67** 2020-12-24 19:29 UTC
Labels: No Code Attached Yet
