### ISSUE TITLE
Search by Fields doesn appears

### ISSUE THREAD

**Issue by Sukinoz** [joomla/joomla-cms#14719] opened 2017-03-18 11:22 UTC
### Steps to reproduce the issue

Create a search module or a smart search module

### Expected result
As said in https://docs.joomla.org/J3.x:Adding_custom_fields  "Can you search custom fields?Short answer: Yes, you can."
Available to search by custom fields 

### Actual result

I cant find this option

### System information (as much as possible)

joomla 3.7

### Additional comments

maybe it is not an issue, but

**Comment by Bakual** [comment] 2017-03-18 11:46
It's not an option, just search for a value you stored in a field and it should find the corresponding item (eg the article).

**Comment by Sukinoz** [comment] 2017-03-19 08:07
Thanks for replaying. 

PD: Maybe this should be a "to do" task for the future of the Search Component? Or better, create a "Filter Component"...

**Comment by Bakual** [comment] 2017-03-19 12:10
I'm not sure what you mean? Do you want to be able to turn off searching for field values?

**Comment by coolcat-creations** [comment] 2017-03-19 13:08
It will probably never be possible to search / filter by field, due to performance issues. Fields are not a CCK...

**Comment by mbabker** [comment] 2017-03-19 15:29
Field values when using com_search as your search component are included in the search result (check the plugin code, it even mentions joining over the fields data).  Presumably Smart Search plugins could somehow be updated to include this data in the search index too at some point.

Fields can't be used for filters on list views.  That requires CCK type architecture that is not supported.

**Comment by Sukinoz** [comment] 2017-03-19 16:34
"Fields are not a CCK..."
"That requires CCK type architecture that is not supported."

My heart is broken...

**Comment by Bakual** [comment] 2017-03-19 19:50
>  Presumably Smart Search plugins could somehow be updated to include this data in the search index too at some point.

Afair, smart search does index the values as well. There was a glitch to it which I think is fixed by now.

**Comment by brianteeman** [comment] 2017-03-20 09:25
Closing as expected behaviour

**Closed by brianteeman** 2017-03-20 09:25 UTC
Labels: No Code Attached Yet

**Comment by Sukinoz** [comment] 2017-03-22 18:26
Sorry, but i thought that this was the "expected behaviour": https://www.joomlart.com/blog/joomla-extensions/joomla-custom-field-filter-added-in-ja-megafilter-demo?utm_source=newsletter&utm_medium=email&utm_campaign=J37FIELDS

**Comment by mbabker** [comment] 2017-03-22 18:30
No.  As stated, fields isn't offering CCK like functionality which is how you would get into including filters like that.

**Comment by iouliaboula** [comment] 2017-06-01 11:54
Question to Sukinoz:
I'm looking for the same functionality. Since this cannot be solved through joomla, I'm thinking about buying the JA megafilter extension. Did you try this already Sukinoz? If so did it prove helpful? 

Thanks!

**Comment by Sukinoz** [comment] 2017-06-01 20:02
Not tested it. But in the description and in the demo page they say that it is prepared:
https://www.joomlart.com/blog/joomla-extensions/joomla-custom-field-filter-added-in-ja-megafilter-demo

**Comment by iouliaboula** [comment] 2017-06-06 14:59
Thanks Sukinoz. I finally bought it but it was of no use since I cannot actually link my theme's search bar with the Megafilter's result page. The only option I have is to search through Megafilter's search bar but I have no control on how this will actually appear on my page.
