### ISSUE TITLE
[com_fields] Joomla 3.7.0. RC1: Warning Error loading component: com_fields, Component not found.

### ISSUE THREAD

**Issue by Gitjk** [joomla/joomla-cms#15144] opened 2017-04-06 22:43 UTC
### Steps to reproduce the issue
1. Update a Joomla 3.6.5 site to Joomla 3.7.0 RC1
2. Go to the Control Panel

### Expected result
The following warning should not display

### Actual result

Warning
Error loading component: com_fields, Component not found.

Some files missing in the 3.7.0. RC1 package?

**Comment by laoneo** [comment] 2017-04-07 07:34
How did you update?

**Comment by franz-wohlkoenig** [comment] 2017-04-07 07:51
test Update 3.6.5 > 3.7.0rc1 by Update Channel "Testing" without Error-Warning.

**Comment by AlexRed** [comment] 2017-04-07 08:07
I can confirm notice and error in update from 3.5.1 to 3.7.0Rc1  by Update Channel "Testing"

![notice-370rc1](https://cloud.githubusercontent.com/assets/1362388/24791340/a4a38cd8-1b71-11e7-90ee-260fd2e58b54.png)

**Comment by Gitjk** [comment] 2017-04-07 09:53
> laoneo: How did you update?

In my case I downloaded and installed the update from this link: [https://github.com/joomla/joomla-cms/releases/tag/3.7.0-rc1](https://github.com/joomla/joomla-cms/releases/tag/3.7.0-rc1 "https://github.com/joomla/joomla-cms/releases/tag/3.7.0-rc1")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15144">issues.joomla.org/tracker/joomla-cms/15144</a>.</sub>

**Comment by infograf768** [comment] 2017-04-07 10:17
No issue here from a 3.6.4 or a 3.6.5 in respect with that.

**Comment by infograf768** [comment] 2017-04-07 10:31
I tested on a 3.4.5 and it finally works: these are my findings

First we get the error
![screen shot 2017-04-07 at 12 23 59](https://cloud.githubusercontent.com/assets/869724/24796538/995cdcfa-1b8d-11e7-9876-bde00988a3c5.png)

Then one has to confirm and be presented with an other Confirm
![screen shot 2017-04-07 at 12 25 04](https://cloud.githubusercontent.com/assets/869724/24796562/b199ce68-1b8d-11e7-9021-2a37f8c2e4fe.png)

Then update completes

![screen shot 2017-04-07 at 12 25 19](https://cloud.githubusercontent.com/assets/869724/24796586/c7aefc6e-1b8d-11e7-9d84-67e5f4d5ee66.png)

No more error and fields are working.

Therefore, we just have an unwanted error message before the process completes.

**Comment by infograf768** [comment] 2017-04-07 13:28
@laoneo @Bakual 
could it be because the fields system plugin is loaded at this time? I am not sure it should be enabled by default btw.
the language filter plugin is not, why would the fields one be?

**Comment by mbabker** [comment] 2017-04-07 13:32
The fields system as a whole is turned on by default, so its plugins need to be enabled.

**Comment by Bakual** [comment] 2017-04-07 18:49
The error comes from JComponentHelper::load. It would be interesting where exactly that is called, because the fields plugin itself doesn't use JComponentHelper as far as I see. It may also come from a completely different place.
That being said, the fields plugin could probably use some checks if com_fields isn't disabled and refuse to work if it is the case.

**Comment by infograf768** [comment] 2017-04-08 07:45
> The fields system as a whole is turned on by default, so its plugins need to be enabled.

I question this decision. Most people will never use that feature. Why should it be turned on by default?

**Comment by brianteeman** [comment] 2017-04-08 08:10
Because most people are not you. 

Seriously we have no way of knowing what most people will use.

**Comment by webmatrix** [comment] 2017-04-10 15:50
Steps to reproduce the issue

Update a Joomla 3.7.0 Beta 4 site to Joomla 3.7.0 RC1
Go to the Control Panel
Go to  Content > Fields

Result

Error
Unknown column 'a.name' in 'field list'

![administration](https://cloud.githubusercontent.com/assets/612147/24870272/60bce856-1e33-11e7-950c-e329ae14ff6e.jpeg)

**Comment by Bakual** [comment] 2017-04-10 15:55
@webmatrix That's a different issue and a known and expected one due to unsupported upgrade path (from beta to RC). Just renamed the alias column to name in the #__fields table and this is solved.

**Comment by webmatrix** [comment] 2017-04-10 16:04
Yup. Renaming alias column to name solves the issue. Thanks

**Comment by brianteeman** [comment] 2017-04-10 16:09
Closed as expected behaviour as there is no upgrade path from beta to rc

**Comment by brianteeman** [comment] 2017-04-10 16:09
re-opened as I was only commenting on @webmatrix

**Comment by nextgen-networks** [comment] 2017-04-26 14:20
Error message exists even after update from 3.6.5 to 3.7.0 final.

**Comment by Bakual** [comment] 2017-04-26 15:35
https://github.com/joomla/joomla-cms/pull/15465 should have fixed the case where com_fields for some reason wasn't installed properly.

**Comment by l-arnold** [comment] 2017-05-17 14:45
UPdated from 3.65 to 3.7.  3.65 system uses FlexiContent.  FlexiContent seems to take over Joomla Articles.  Cannot garner access to Joomla Fields and not finding any plugin or other files related to com_fields.

Constant Warning in Joomla Backend:
Warning
Error loading component: com_fields, Component not found.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15144">issues.joomla.org/tracker/joomla-cms/15144</a>.</sub>

**Comment by zero-24** [comment] 2017-05-17 14:48
please hit the database fixer and try discover install as this sounds like you did not update using com_joomlaupdate. Please move any site spezific issues to forum.joomla.org or the developers of FlexiContent. Thanks.

**Comment by l-arnold** [comment] 2017-08-14 11:45
Fixed the "above" problem by choosing "discover" Under the Extensions/Manage Tab.
There were only about 4 items to "install" (quite old).  I choose them, then hit "install".
This in turn brought the new "Fields" and other elements up as potential installs (finally).
Error message went away though I have not actually installed the "fields" named elements as yet.

This page shows up under any relevant searches so seems best to document the solution.  Will move my queries to forum.joomla.com and flexicontent.  (Relatively undocumented so far)

**Comment by brianteeman** [comment] 2017-08-18 11:24
I am closing this as it was resolved with #15465

**Closed by brianteeman** 2017-08-18 11:24 UTC
Labels: No Code Attached Yet
