### ISSUE TITLE
Articles by tag, not showing authors aliases

### ISSUE THREAD

**Issue by maciejczub** [joomla/joomla-cms#4033] opened 2014-07-29 13:13 UTC
#### Steps to reproduce the issue
1. Create article.
2. Fill in Author Alias field.
3. Add some tags to article.
4. List articles by tag (frontend).

#### Expected result
Under each article should be displayed author. The value should be taken from the field "Author Alias​​" (if it is filled).

#### Actual result
Author value is always taken from "created_user_id".

#### System information (as much as possible)
Default Joomla 3.3.3 installation.

#### Additional comments
IMO there is a problem with UCM. Tags component uses new UCM model and copy articles to the "ucm_content" database table, losing values from "created_by_alias" field. In "ucm_content" table "core_created_by_alias" field is always empty.

**Comment by Hackwar** [comment] 2015-01-04 18:16
Please don't throw in yet another 100 additional Parameters towards this. We already have way too many parameters.

**Comment by zero-24** [comment] 2015-05-09 12:52
Moving to `Needs Review` so a Maintainer / PLT can decide if this should included or not. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4033">issues.joomla.org/joomla-cms/4033</a>.</sub>

**Comment by roland-d** [comment] 2015-11-08 17:53
Hello @maciejczub 

Thank you for your contribution. Since this is not a bug and can be solved by updating your template view, I am closing the issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4033">issues.joomla.org/joomla-cms/4033</a>.</sub>

**Closed by roland-d** 2015-11-08 17:53 UTC
Labels: No Code Attached Yet
