### ISSUE TITLE
All categories marked as trashed in articles view ??

### ISSUE THREAD

**Issue by rbuelund** [joomla/joomla-cms#38673] opened 2022-09-02 17:03 UTC
### Steps to reproduce the issue
Update from Joomla 4.2.0 to 4.2.1

### Expected result
Everything ok

### Actual result
In articles list in backend![screen shot 2022-09-02 at 17 03 20](https://issues.joomla.org/uploads/1/e32061cef6df689e01353acfeb649924.jpg), all categories are marked as (trashed)

### System information (as much as possible)
Joomla 4.2.1
Linux
Php 7.4

### Additional comments
In the article list view in backend all articles have a (trashed) mark! But non of the categories are actually trashed ???
![screen shot 2022-09-02 at 17 03 20](https://issues.joomla.org/uploads/1/da62ccf5ab74dce43a6aa66da632859d.jpg)

**Comment by richard67** [comment] 2022-09-02 17:11
@rbuelund Do you still have these categories with names "2017" and "2018"? Or have they been trashed once and then deleted (empty trash) so they don't exist anymore?

**Comment by rbuelund** [comment] 2022-09-02 17:12
All categories are still there when I look in the categories list. Nothing changed there.

**Comment by rbuelund** [comment] 2022-09-02 17:14
I saw this when investigating another problem, that all of a sudden a few articles could not be saved anymore. When I press save I am simply returned to the article list and nothing is saved - but do not know if this problem is related.

**Comment by richard67** [comment] 2022-09-02 17:15
Hmm I cannot reproduce it here. Have updated and categories are not shown as trashed in the articles list. But I have characters in my category names. Maybe it has to do with the numeric names "2017" and "2018" (just a silly idea)?

**Comment by chmst** [comment] 2022-09-02 17:16
In my applications everything in categories is published as before. Are you using template overridee in backend?

**Comment by rbuelund** [comment] 2022-09-02 17:17
No, no overrides in backend

**Comment by richard67** [comment] 2022-09-02 17:17
> In my applications everything in categories is published as before. Are you using template overridee in backend?

@chmst As far as I understood the issue, the categories are not the problem. The problem is the display of the categories in the Articles list showing the categories as being trashed but they are not.

**Comment by rbuelund** [comment] 2022-09-02 17:18
Exactly

**Comment by rbuelund** [comment] 2022-09-02 17:19
Could this be a problem in the assets table ? This IS a site that was migrated way back from 1.5

**Comment by chmst** [comment] 2022-09-02 17:20
Yes, sorry - I wanted to say that all categories in articles overviews is correct. But your idea with numbers  .. maybe. We can investigate here. The asset table  - no.

**Comment by rbuelund** [comment] 2022-09-02 17:20
But just wondering, why the problem has arissen right now ?? Has there been som code changes related to the categories view or the way categories are marked as trashed ?

**Comment by rbuelund** [comment] 2022-09-02 17:21
I also have top categories with no numbers - same problem.

**Comment by rbuelund** [comment] 2022-09-02 17:22
As you can see here
![categories trashed](https://user-images.githubusercontent.com/1399437/188206037-67422f78-2a79-43a9-96bb-930c66ba94f1.jpg)

**Comment by richard67** [comment] 2022-09-02 17:23
Really stange. The copy of my 3.10 homepage which I once had updated to 4.0 and then later kept up to date is till fine. It has an update history not back to 1.5 but to 2.5. And it's really strange why that comes with an update from 4.2.0 to 4.2.1.

**Comment by rbuelund** [comment] 2022-09-02 17:24
Well it might also have come from 4.1 to 4.2 - I am not quite shure there...

**Comment by richard67** [comment] 2022-09-02 17:26
And the categories in question show up fine in the categories list?

**Comment by brianteeman** [comment] 2022-09-02 17:27
go to categories
click on rebuild

**Comment by rbuelund** [comment] 2022-09-02 17:27
Yes they do. All articles, in all categories are shown this way.

**Comment by rbuelund** [comment] 2022-09-02 17:28
@brianteeman tried that - no change

**Comment by chmst** [comment] 2022-09-02 17:33
@rubelund can you change a file in your application? 


If yes:
https://github.com/joomla/joomla-cms/blob/4.2-dev/administrator/components/com_content/tmpl/articles/default.php#L301

replace these lines by 

```
                                            if ($item->category_published < 1) :
                                                echo $item->category_published === 0 ? ' (' . Text::_('JUNPUBLISHED') . ')' : ' (' . Text::_('JTRASHED') . ')';
                                            endif;
```

maybe ...

**Comment by rbuelund** [comment] 2022-09-02 17:36
So you mean the extra = sign - that makes no change if i add that.

**Comment by richard67** [comment] 2022-09-02 17:37
Maybe better not with the strict comparison. But to change the check for < 1 is a good idea, so:

```
                                            if ($item->category_published < 1) :
                                                echo $item->category_published == 0 ? ' (' . Text::_('JUNPUBLISHED') . ')' : ' (' . Text::_('JTRASHED') . ')';
                                            endif;
```

**Comment by rbuelund** [comment] 2022-09-02 17:38
And also removing the '' around 0 and 1 - no change

**Comment by rbuelund** [comment] 2022-09-02 17:38
Ahh - now they are all marked as Unpublished instead with @richard67's code

**Comment by chmst** [comment] 2022-09-02 17:40
Could be something with the categories table. @richard67 any idea about the published field?

**Comment by richard67** [comment] 2022-09-02 17:42
So possibly the `$item->category_published` is not set right? What values for `published` do you get when you issue following query in PhpMyAdmin (replace `#__` by your database prefix?

```
SELECT `title`, `published` FROM `#__categories` WHERE `title` IN ('2017, '2018');
```

**Comment by rbuelund** [comment] 2022-09-02 17:45
Sorry - I have to leave now - gusts. I will write it later..

**Comment by chmst** [comment] 2022-09-02 17:54
Seems not so critical .. but 
@richard67 as the published field is a tinyint(4) in my database, the comparision with strings seems a bit strange. Maybe the column was a string in earlier joomla versions? I don't remember.

**Comment by richard67** [comment] 2022-09-02 17:55
@chmst Depending on the database driver (MySQLi or MySQL PDO) and the kind of database (MySQL and MariaDB) and their versions, some drivers return a string and some an integer.

**Comment by richard67** [comment] 2022-09-02 18:02
@rbuelund So 2 queries to be checked in PhpMyAdmin when you are back, wuth `#__` being replaced by your database prefix:

1. As mentioned above:
```
SELECT `title`, `published` FROM `#__categories` WHERE `title` IN ('2017, '2018');
```
2. Data type of the category table's published column:
```
SHOW COLUMNS IN `#__categories` WHERE `field` = 'published';
```

**Comment by rbuelund** [comment] 2022-09-03 05:27
Ok - now I have run the two sql queries. 
The first one returns nothing.
The second returns:
![result](https://user-images.githubusercontent.com/1399437/188257196-f4f081ad-b27e-4dc2-8c18-4c9d85ce3678.jpg)

**Comment by richard67** [comment] 2022-09-03 08:34
@rbuelund Ehy does the first query return nothing? The titles in the where clause were the same as shown in your screenshots. Anyway, l ave the where clause away and check the values of the published column.

**Comment by rbuelund** [comment] 2022-09-03 08:43
Here aret the result of the query without where:
![categories-db](https://user-images.githubusercontent.com/1399437/188263176-6d850ed3-f2b6-4d9d-a655-69d2833d1c3e.jpg)
And here is my categories list from backend:
![categories_backend_1](https://user-images.githubusercontent.com/1399437/188263183-0cec8d59-46c8-4714-b7a5-39d85dff7852.jpg)
![categories_backend_2](https://user-images.githubusercontent.com/1399437/188263187-86e162ca-01ee-467a-b5a9-75f3bdd7a948.jpg)
![categories_backend_3](https://user-images.githubusercontent.com/1399437/188263189-e675545d-145c-4368-8fa4-6b99f5fb6e66.jpg)

**Comment by rbuelund** [comment] 2022-09-03 08:43
Very odd - i think ???

**Comment by rbuelund** [comment] 2022-09-03 08:49
Ahh wait wait! Let me check a little later if i actually use the correct prefix in the queries!

**Comment by rbuelund** [comment] 2022-09-03 12:10
Terrible sorry - it was the wrong prefix of course !!
Result of query 1:
![1 query](https://user-images.githubusercontent.com/1399437/188269836-7ea59ea4-5de3-48c5-afa7-4818e20178d8.jpg)
Result of query 2:
![2 query](https://user-images.githubusercontent.com/1399437/188269855-df0dd0be-6beb-4984-93f2-b9c79f43ffca.jpg)

**Comment by rbuelund** [comment] 2022-09-06 05:26
Any ideas on this issue ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38673">issues.joomla.org/tracker/joomla-cms/38673</a>.</sub>

**Comment by rbuelund** [comment] 2022-09-07 08:07
What du you mean ? I have no overrides in backend.

**Comment by chmst** [comment] 2022-09-07 13:03
Is was just a question, as I have no explanation why your system finds a value < 0 but not == 0 here: 
https://github.com/joomla/joomla-cms/blob/4.2-dev/administrator/components/com_content/tmpl/articles/default.php#L301. 

Canyou  add a line before this condition:
var_dump($item->category_published);

![grafik](https://user-images.githubusercontent.com/1035262/188884209-1e4b4a48-a848-4294-ac01-a9887a8b8f1b.png)

So you can see the values here - in my articles overview it is  an integer 1. 
![grafik](https://user-images.githubusercontent.com/1035262/188884639-88b5a9f9-5966-4c12-a998-27ebc98b36e3.png)

**Comment by rbuelund** [comment] 2022-09-07 17:37
If I add var_dump($item->category_published); in line 301 I get this output:
![dump](https://user-images.githubusercontent.com/1399437/188943299-cc7c5993-f038-4e65-accb-9b8dd365e27e.JPG)

**Comment by chmst** [comment] 2022-09-07 20:10
> I saw this when investigating another problem, that all of a sudden a few articles could not be saved anymore. When I press save I am simply returned to the article list and nothing is saved - but do not know if this problem is related.

That could be related. Didi you find the reason for that?

**Comment by rbuelund** [comment] 2022-09-08 04:15
@chmst Yes, I found the reason for the other save problem. PHP max_input_vars had to be raised on the server, because I have a lot of custom fields with galleries coupled to the articles. Would be nice though if one got a warning about that problem - quite hard to debug.

**Comment by brianteeman** [comment] 2022-09-08 06:34
we did have a pr for that in the past but it was rejected ;(

**Comment by rbuelund** [comment] 2022-09-08 15:33
But no one has an idea about the trashed marking on all my categories in the articles listing in backend??

**Comment by richard67** [comment] 2022-09-08 15:34
> But no one has an idea about the trashed marking on all my categories in the articles listing in backend??

@rbuelund Not yet. Maybe tomorrow or on weekend.

**Comment by tmumm** [comment] 2022-09-26 21:50
I'm finding this same issue.  This site was an upgrade from 3.10.11 to 4.22.   All categories show (Trashed) in article list, but of course are now.  Tried rebuild categories and checked the database.   It doesn't affect functionality, but confuses my client. 

![Content_Manager__Items_-_The_Children_s_Center_Utah_-_Administration](https://user-images.githubusercontent.com/19676184/192386790-e60b5e4c-90a7-4d61-97a7-203c1cdee1a6.jpg)

**Comment by richard67** [comment] 2022-10-07 07:18
@alikon As found out here https://github.com/joomla/joomla-cms/issues/38673#issuecomment-1239689055 , the category_published values are NULL. My first idea was that the join of the categories table in the list query does not happen when there is no filtering by category, but that is not the case. The categories table should always be joined. So I have no idea why that can happen, except if the category id of the article would be wrong, but then people would see much more issues. Could you check the list query? Maybe you have an idea or see something which I am missing?

**Comment by alikon** [comment] 2022-10-07 07:43
like it seems that the issue has been introduced on 4.2 then this  could be the root cause #37583

**Comment by richard67** [comment] 2022-10-07 07:48
> like it seems that the issue has been introduced on 4.2 then this could be the root cause #37583

@alikon That was my first thought, too, but I did not find any mistake in that code which could cause this, and the list query already joins the categories table in all cases, so the `c.published` should always be in the query results. That's why I asked you, maybe I am just blind.

**Comment by chmst** [comment] 2022-10-09 13:06
See this comment (https://github.com/joomla/joomla-cms/issues/38673#issuecomment-1239689055).

How can $item->category_published be NULL after upgrading?
```

**Comment by richard67** [comment] 2022-10-09 14:16
@chmst It can be null not in the categories table but in the list query when the JOIN fails, i.e. doesn't find the right category records.

**Comment by brianteeman** [comment] 2022-11-29 22:31
I identified the cause of this on aat least one site. There was a plugin from Joomlart running called System - JA Content Type. I dont know what it was for but as soon as I disabled it then everything works as expected

**Comment by brianteeman** [comment] 2022-11-29 22:39
As soon as I enabled display of errors it was obvious - the plugin rips the guts out of core. Spits it on the floor and replaces it with a pile of poop.

https://www.joomlart.com/documentation/joomla-templates/ja-hotel-template/content-type

**Comment by tmumm** [comment] 2022-11-29 22:45
That was part of of the migration from K2 to articles on Joomla3 site, and must not have uninstalled with the package.   Probably the culprit on the my other sites.

**Comment by brianteeman** [comment] 2022-11-29 22:46
You really should audit what is installed on that site. there is a LOT of garbage installed that you are not using.

**Comment by brianteeman** [comment] 2022-11-29 22:47
AND PLEASE PLEASE PLEASE when you have a problem enable error reporting and debug - it will save everyone a LOT of time

**Comment by tmumm** [comment] 2022-11-30 00:31
I did turn on error reporting on another site, and didn't see anything related to that plugin.    I've now removed it on that site but removing it didn't fix the issue.  Error reporting is showing an issue with the file administrator/components/com_content/tmpl/articles/default.php

![Content_Manager__Items_-_The_Children_s_Center_Utah_-_Administration](https://user-images.githubusercontent.com/19676184/204678519-8f683989-134b-48e9-a6b1-d9c95d22bed0.jpg)

**Comment by rbuelund** [comment] 2022-11-30 05:23
Hmm.. just checked on my site. I did not have the Joomlart plugin installed, but now all of a sudden the problem is gone ?? If it was an update that did the trick - I have no idea.

**Comment by mrownicki** [comment] 2022-11-30 10:11
> As soon as I enabled display of errors it was obvious - the plugin rips the guts out of core. Spits it on the floor and replaces it with a pile of poop.
> 
> https://www.joomlart.com/documentation/joomla-templates/ja-hotel-template/content-type

I confirm this issue and fix. Like Brian wrote.

**Comment by chmst** [comment] 2022-11-30 10:19
Thanks a lot, @brianteeman - from now on we will aks for the debugging settings, I always presumed that. 

So closing this as it is not a Joomla issue.

**Closed as completed by chmst** 2022-11-30 10:19 UTC
Labels: No Code Attached Yet

**Comment by brianteeman** [comment] 2022-11-30 10:33
If that joomlart plugin is listed on the JED then it should be reported and removed. It basically hacks com_content by replacing it with their modified version.
