### ISSUE TITLE
[4.0] com_media: "Save & Close" don't save

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#30664] opened 2020-09-17 05:57 UTC
### Steps to reproduce the issue
- modify a Picture in ```Crop```, ```Resize``` or ```Rotate```,
- click ```Save & Close```
- nothing is saved.

### Expected result
Changes are saved.

### Actual result
Changes are not saved.

### System information (as much as possible)
php: Linux lamp10.cloudaccess.net 3.10.0-962.3.2.lve1.5.24.4.el6h.x86_64 #1 SMP Thu Nov 15 04:53:17 EST 2018 x86_64
dbserver: mysql
dbversion: 5.7.29-cll-lve
dbcollation: utf8_general_ci
dbconnectioncollation: utf8mb4_general_ci
dbconnectionencryption: 
dbconnencryptsupported: true
phpversion: 7.3.21
server: Apache
sapi_name: cgi-fcgi
version: NightlyBuild - Joomla! 4.0.0-beta5-dev Development [ Mañana ] 15-September-2020 19:15 GMT
useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:80.0) Gecko/20100101 Firefox/80.0

### Additional comments
```Save``` works.

**Comment by infograf768** [comment] 2020-09-17 06:33
Confirmed.
The issue appears after https://github.com/joomla/joomla-cms/pull/30617 was merged.
Reverting that PR solves it here.
Looks like we did not test that aspect.

@SharkyKZ 
@wilsonge

**Comment by SharkyKZ** [comment] 2020-09-17 06:53
I can reproduce this on an older branch without #30617.

We perform an asynchronous request here and navigate away before it's finished:

https://github.com/joomla/joomla-cms/blob/2787e0c928e7abeaca49d7482b039f94b1dc1ee9/build/media_source/com_media/js/edit-images.es6.js#L228

This should be handled as synchronous request or something along the lines.

**Comment by infograf768** [comment] 2020-09-17 07:14
Correct. Issue was before #30617

**Comment by SharkyKZ** [comment] 2020-09-22 12:35
Please test PR https://github.com/joomla/joomla-cms/pull/30730.

**Closed as completed by SharkyKZ** 2020-09-22 12:35 UTC
Labels: No Code Attached Yet
