### ISSUE TITLE
Creating article with filtered category

### ISSUE THREAD

**Issue by Denitz** [joomla/joomla-cms#17974] opened 2017-09-17 13:55 UTC
### Steps to reproduce the issue

Set error reporting to development
Open articles manager
Filter articles by category
Create new article

### Expected result
No errors

### Actual result
See PHP notice:

( ! ) Notice: Array to string conversion in \administrator\components\com_categories\models\fields\categoryedit.php on line 281
--

### System information (as much as possible)
Joomla 3.8 RC1

### Additional comments

Since we have multiple categories filter, first filtered category should be pre-configured for new articles.

**Comment by ghost** [comment] 2017-09-17 14:08
Confirmed:

![bildschirmfoto 2017-09-17 um 16 08 07](https://user-images.githubusercontent.com/8235763/30521612-753ae1fe-9bc2-11e7-9641-5a4571a37719.jpg)

**Comment by alikon** [comment] 2017-09-22 06:17
undesidered side effect from #17668

make no sense to check if  "Allowed to add" on multiple categories since 1 article is related to 1 and only  1 category  https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_content/controllers/article.php#L50

**Comment by infograf768** [comment] 2017-09-23 07:24
@laoneo 
As the first Notice concerns the fields, could you have a look?

**Comment by laoneo** [comment] 2017-09-23 07:40
The problem is not fields itself, the issue is that JForm->getAttribute is returning an array instead of a string as it was before.

**Comment by Shazrina1994** [comment] 2017-09-23 08:06
so it is better to set for single filter selection for category rather than multi filter selection. after selecting multiple categories and adding a new article, that new one always being included to that last added categorized id. 
so I think better to fix for single filter

**Comment by Shazrina1994** [comment] 2017-09-23 08:10
it always should not first filtered category should be pre-configured for new articles.
as @Denitz said under additional comments want to think of.

**Comment by Shazrina1994** [comment] 2017-09-23 08:22
as i tested it didnt give me as selected filter order and sometimes gave me the highest categorize id when new article added.

**Comment by alikon** [comment] 2017-09-24 09:31
test/comment #18090

**Comment by ghost** [comment] 2017-09-24 10:02
closed as having Pull Request #18090<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17974">issues.joomla.org/tracker/joomla-cms/17974</a>.</sub>

**Comment by laoneo** [comment] 2017-09-24 10:05
Does that pr fix all the issues here?

**Comment by alikon** [comment] 2017-09-24 10:15
not sure 
is a dirty one  :cry:

**Comment by Quy** [comment] 2017-09-30 19:08
@franz-wohlkoenig Please reopen.

**Comment by ghost** [comment] 2017-09-30 19:18
reopened as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17974">issues.joomla.org/tracker/joomla-cms/17974</a>.</sub>

**Comment by ggppdk** [comment] 2017-09-30 21:21
I have made PR #18176

**Comment by ghost** [comment] 2017-10-01 05:16
closed as having Pull Request #18176<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17974">issues.joomla.org/tracker/joomla-cms/17974</a>.</sub>

**Closed as completed by ghost** 2017-10-01 05:16 UTC
Labels: No Code Attached Yet
