### ISSUE TITLE
SEF urls issue 

### ISSUE THREAD

**Issue by mohamadArdestani** [joomla/joomla-cms#41139] opened 2023-07-11 11:18 UTC
The SEF Urls doesn't work in localhost in joomla 4 but with joomla3 work correctly.

**Comment by brianteeman** [comment] 2023-07-11 12:03
This is down to your local configuration and not a joomla code issue. Please use the forum for support https://forum.joomla.org

**Comment by richard67** [comment] 2023-07-11 13:55
@mohamadArdestani Could you provide more details? What is not working? Maybe provide an example for the URL which you expect and what you get instead. In addition, please provide details on your configuration. Do you have URL rewrite switched on? If so, are you using an .htaccess file?

As the previous comment says, it looks right now like a configuration issue and not a bug of the CMS core. So if you can't provide any information which shows that it is a bug of the CMS core, we will close this issue soon.

For support questions you should indeed use the forum.

**Comment by mohamadArdestani** [comment] 2023-07-18 14:58
I install joomla 4 on my local development ( laragon ) and enable SEF URL option and renamr htaccess.txt to .htaccess  but in frontend The url displayed as ?index.php....
but for joomla 3 althing is ok.

**Comment by brianteeman** [comment] 2023-08-01 17:44
Please the forum for support.

This should be closed

**Comment by alikon** [comment] 2023-08-01 17:48
@mohamadArdestani  Please use the forum for support https://forum.joomla.org/

**Closed as completed by alikon** 2023-08-01 17:48 UTC
Labels: No Code Attached Yet, Information Required
