### ISSUE TITLE
[4.0] Checked out tooltip has html source in it

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22783] opened 2018-10-23 20:22 UTC
### Steps to reproduce the issue

Hover over a checked out lock in 4.0 @ 9d3acfd9d589989e86bda3fe35f58a47323d66f4

### Expected result

A tooltip with no HTML 

### Actual result

![img_2619](https://user-images.githubusercontent.com/400092/47388262-a81dc180-d709-11e8-9178-f1b2d0256845.jpg)

**Comment by Quy** [comment] 2018-10-23 21:44
Duplicate of #21373 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22783">issues.joomla.org/tracker/joomla-cms/22783</a>.</sub>

**Closed as completed by Quy** 2018-10-23 21:44 UTC
Labels: No Code Attached Yet

**Comment by PhilETaylor** [comment] 2018-10-23 21:45
I did search - I searched for checked out :) not locked article :)

**Comment by Quy** [comment] 2018-10-23 21:53
I vaguely remembered it so it took several tries to locate it.
