### ISSUE TITLE
Since 3.8.4 ContentHelperAssociation::getAssociations doesn't returns articles of the current user language

### ISSUE THREAD

**Issue by agilare** [joomla/joomla-cms#19615] opened 2018-02-08 11:17 UTC
In my Joomla website (recently updated to 3.8.4) I developed a module showing a list of links to Joomla articles.

I stack in a MySQL table a list of articles id of the main language (french). If the visitor is in german part of the site, the module retrieve the (french) article id from this table and use `ContentHelperAssociation::getAssociations` to find the german equivalent; however with the new condition `if ($item->language != JFactory::getLanguage()->getTag())` in [getAssociations() method](https://github.com/joomla/joomla-cms/blob/e4c2ac1d51da10b44a2bbfa7236fbb908a1e53fb/components/com_content/helpers/association.php#L33) associated articles extracted of the current user language are excluded from the array of articles returned.

Is there a way to bypass this limitation ?

Thank you

**Comment by Bakual** [comment] 2018-02-08 11:46
For reference that line was introduced with https://github.com/joomla/joomla-cms/pull/19314 (and https://github.com/joomla/joomla-cms/pull/19009).

To me it looks like intended behavior of that method to not return the items of the active language.
For your usecase, you should probably do your own method.

**Comment by ghost** [comment] 2018-02-21 19:17
@agilare can this Issue be closed?

**Comment by agilare** [comment] 2018-02-23 14:25
I understand what @Bakual explains : 

> intended behavior of that method to not return the items of the active language

but maybe this could be less rigid and could be for example an option, like an additional parameter of method `getAssociations` which by default exclude current language ?

**Comment by Bakual** [comment] 2018-02-23 14:35
Imho, that usecase is so specific to your needs that it doesn't make sense to support by in core.
Just run your own query and fetch the artciles without using the API.

**Comment by agilare** [comment] 2018-02-23 15:33
Of course, if few users are concerned, I would follow the advice of @Bakual 
Thank you for your help

**Comment by brianteeman** [comment] 2018-02-23 15:38
Closed as expected behaviour

**Closed as completed by brianteeman** 2018-02-23 15:38 UTC
Labels: No Code Attached Yet
