### ISSUE TITLE
Manual ordering in object list bug

### ISSUE THREAD

**Issue by PetarT** [joomla/joomla-cms#7243] opened 2015-06-22 15:34 UTC
#### Steps to reproduce the issue

For reproducing this bug yuo should use drag and drop option for reordering objects in the list. If object has any permission options set, once you change the order of that object in the list, JModel->storeorder() method (JTable defined function I suppose) is reseting permissions to defaults.

#### Expected result

Permissions untouched and order applied.

#### Actual result

Order applied but permissions reset to default.

#### System information

Joomla 3.4.1

#### Additional comments

In most cases I saw the usage like this:
```
    public function saveOrderAjax()
	{
		$pks = $this->input->post->get('cid', array(), 'array');
		$order = $this->input->post->get('order', array(), 'array');

		// Sanitize the input.
		JArrayHelper::toInteger($pks);
		JArrayHelper::toInteger($order);

		// Get the model.
		$model = $this->getModel();

		// Save the ordering.
		$return = $model->saveorder($pks, $order);

		if ($return)
		{
			echo "1";
		}

		// Close the application.
		JFactory::getApplication()->close();
	}
```
I think it should be changed in favor of using JSON result here like this:
```
    public function saveOrderAjax()
	{
		$pks = $this->input->post->get('cid', array(), 'array');
		$order = $this->input->post->get('order', array(), 'array');

		// Sanitize the input.
		JArrayHelper::toInteger($pks);
		JArrayHelper::toInteger($order);

		// Get the model.
		$model = $this->getModel();

		// Save the ordering.
		echo json_encode($model->saveorder($pks, $order));

		// Close the application.
		JFactory::getApplication()->close();
	}
```

**Comment by AteDev** [comment] 2015-06-22 18:49
### For the first part (permissions reseting).
Could you provide more details about "object", are you using third application or 1 component from joomla?
What are thoose "permission options" ?

### About the second part (json response)
see that: [JResponseJson](https://docs.joomla.org/JSON_Responses_with_JResponseJson) / [Generating json](https://docs.joomla.org/Generating_JSON_output)

**Comment by javigomez** [comment] 2015-06-23 07:35
I can't reproduce, but while testing discovered http://issues.joomla.org/tracker/joomla-cms/7251<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7243">issues.joomla.org/joomla-cms/7243</a>.</sub>

**Comment by PetarT** [comment] 2015-06-23 07:47
I couldn't reproduce this on any Joomla component along side Joomla (com_content for instance). Talked with Javi about this, and it might be a problem problem with component I am working on. Feel free to close this one.

About 2nd part, I am aware of JResponseJson, and I believe we should go with it instead of outputing "1" as result of success there.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7243">issues.joomla.org/joomla-cms/7243</a>.</sub>

**Comment by brianteeman** [comment] 2015-06-23 07:53
Closed as requested<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7243">issues.joomla.org/joomla-cms/7243</a>.</sub>

**Closed by brianteeman** 2015-06-23 07:53 UTC
Labels: No Code Attached Yet
