### ISSUE TITLE
Debug LANG configuration display issu

### ISSUE THREAD

**Issue by philippegm** [joomla/joomla-cms#32084] opened 2021-01-19 12:53 UTC
### Steps to reproduce the issue

Set ON the debug language button on the configuration control panel! Result in the join file
[screen shot 2021-01-19 at 12 44 40](https://issues.joomla.org/uploads/1/237ac82a08984fa3490390f40704b167.png)

### Expected result

No problem with display

### Actual result

[screen shot 2021-01-19 at 12 44 40](https://issues.joomla.org/uploads/1/237ac82a08984fa3490390f40704b167.png)

**Comment by brianteeman** [comment] 2021-01-19 13:24
This the correct and expected behaviour when you enable Debug Languages **AND** set Language Display to constant
![image](https://user-images.githubusercontent.com/1296369/105040255-841cc800-5a59-11eb-9f1c-2035d9fdd144.png)

There is just no alternative when displaying the  constants. What you probably wanted was the default setting of Values

**Comment by chmst** [comment] 2021-01-19 13:26
You are right that the output is ugly. But it is only meant for desperate bug fixing cases, so I think we must live with it.

**Comment by brianteeman** [comment] 2021-01-19 13:27
Of course if anyone comes up with a way to display these long strings without breaking the layout that would be awesome

**Comment by philippegm** [comment] 2021-01-19 18:03
I didn't know what I was going to find.
A display like this prohibits any navigation except for a specialist.
At least you have the feeling of someone trying for the first time and thinking there is a bug.
Wouldn't it be possible to have all these values in popup of the mouse while keeping the display identical? 
I've seen this in other software before.
Yootheme has something similar in the style settings of Yoothemepro

**Comment by brianteeman** [comment] 2021-01-19 18:19
> I didn't know what I was going to find.

That's one reason for it not being enabled by default for language debug

> A display like this prohibits any navigation except for a specialist.

Only a specialist should be using this tool

> At least you have the feeling of someone trying for the first time and thinking there is a bug.
> Wouldn't it be possible to have all these values in popup of the mouse while keeping the display identical?
> I've seen this in other software before.
> Yootheme has something similar in the style settings of Yoothemepro

You can something like that for a simple form but you can't for something like a menu item or a select with a list of options.

Irrespective of that - what were you trying to achieve that made you want to debug the language?

**Comment by philippegm** [comment] 2021-01-19 18:35
Hi Brian
I thought it was a way to help correct the many incomplete translations I have on the site.
If it's only for specialists, why show it?
I did what anyone looking to know would do. My clients would do that. We're not all specialists. And the result effectively gives the impression that something is not finished. Hence my question.

**Comment by chmst** [comment] 2021-01-19 21:36
It is a help for debugging and yes it is for specialists. 
May I aks which language you are translating? 
If there are many incomplete translations, then in general there is only one simple character wrong and all the following strings are not translated.

**Comment by philippegm** [comment] 2021-01-19 22:19
I'm trying Joomla 4 in French. And it's not just simple characters that are missing. It is complete pages as well as system dashboard.
So I leave you between specialists sorry to have disturbed you.

**Comment by infograf768** [comment] 2021-01-20 07:09
@philippegm 
The work is in progress fro the 4.0 French language pack.
It will be released when 4.0 is released. It is quite useless to translate on your side.
If you need to test the work already done, go to https://crowdin.com/project/joomla-cms/fr# and download.

**Comment by philippegm** [comment] 2021-01-20 08:06
In some Joomla extensions that I was able to test, the programmer put a button to directly access the translation. We make our corrections which are sent back to the company, which then validates them. The process is extremely simple. No waste of time.
In fact I thought it was the same. I thought, cool, they did something to just make me participate. But I was wrong.
Thanks, but one more website in the joomla site galaxy which is just incomprehensible. Why make it simple when you can make it complicated.

**Comment by infograf768** [comment] 2021-01-20 08:55
Joomla 4 is in beta phase and SHOULD NOT BE USED as production site.
As stated, core language packs are not provided yet for ANY language.
You can participate on crowdin if you wish.

Closing as not a bug.

**Closed as completed** 2021-01-20 08:55 UTC
Labels: No Code Attached Yet
