### ISSUE TITLE
Factory::getLanguage() is deprecated

### ISSUE THREAD

**Issue by pinochico** [joomla/joomla-cms#37729] opened 2022-05-03 01:28 UTC
### Steps to reproduce the issue

Install plugin n3t Debug - https://bitbucket.org/n3t/n3t-debug/downloads/
Setup - Scream - YES

### Expected result

Without all deprecated errors :)

### Actual result

PHP User Deprecated: Joomla\CMS\Factory::getLanguage() is deprecated. Load the language from the dependency injection container or via Joomla\CMS\Factory::getApplication()->getLanguage(). in .../joomla4.easy.minion.cz/public_html/libraries/src/Factory.php:273

### System information (as much as possible)

J4.2.1
PHP7.4.21

### Additional comments

![Snímek obrazovky 2022-05-03 v 3 27 37](https://user-images.githubusercontent.com/395559/166392076-0e15f539-85c5-4eee-b6a0-0efa6c7f1ac2.png)

**Comment by brianteeman** [comment] 2022-05-03 06:33
it is dprecated for removal in 5.0

**Comment by chmst** [comment] 2022-05-03 12:22
Closing as this is intended.

**Closed as completed by chmst** 2022-05-03 12:22 UTC
Labels: No Code Attached Yet

**Comment by rambro** [comment] 2023-01-14 20:03
Hi all,

So I backed up my RSFormpro! forms from joomla 3.x and restored them them in the joomla 4.x (test site). via the RSFormProl extension. However when I run the form in joomla 4.x (with debug on) I am getting errors like this.

Joomla\CMS\Factory::getLanguage() is deprecated. Load the language from the dependency injection container or via Joomla\CMS\Factory::getApplication()->getLanguage(). 16384

I know previously when going from joomla 3.x to joomla 4.x, I basically had to reinvent the wheel and reproduce stuff manually.  Do you think I have to go from scratch and create a new form in joomla 4.x ? 

Let me know what you think

Rick Ambrosino

![rsformpro error1](https://user-images.githubusercontent.com/4724475/212494097-dde8a868-32e6-4524-a5f6-da8d6818cb42.jpg)
![rsformpro error2](https://user-images.githubusercontent.com/4724475/212494099-f0bf94ec-63f7-42ba-9e04-383c544f3208.jpg)
![rsformpro error3](https://user-images.githubusercontent.com/4724475/212494100-39a48ddd-a711-4474-a9c7-b85b79da18c9.jpg)
![rsformpro error4](https://user-images.githubusercontent.com/4724475/212494101-86542ff6-fd13-49ad-9f34-760fc9bd197f.jpg)
![rsformpro error5](https://user-images.githubusercontent.com/4724475/212494103-71dba60e-45a4-418f-8663-ac6c5282107d.jpg)

**Comment by ReLater** [comment] 2023-01-14 22:04
Why don't you disable debug? Or switch it to more silent?

**Comment by rambro** [comment] 2023-01-15 00:14
Hi,

I turned on debug to find out where the errors were with my RSFormPro form that I created. I did turn it off though. I probably am going to create a form from scratch and put all the setting in their from my previous forms that I upload into joomla 4.x from joomal 3.x.

Rick Ambrosino

**Comment by joomdonation** [comment] 2023-01-15 02:12
@rambro Creating a new form won't help solving your issue. Better contact RSFormPro developer, ask them to check and solve the issue in their extension.

**Comment by ReLater** [comment] 2023-01-15 12:06
> I turned on debug to find out where the errors were with my RSFormPro form

What I meant: You can configure debugging less noisy. If you use for example n3t Debug plugin you can switch off USER_DEPRECATED messages and others. You don't need then Joomla's debug configuration and "Error reporting". At the moment it is a waste of time to debug Joomla inclusive USER_DEPRECATED messages when you are not a developer. If an extension also wants to support 4.0, 4.1 by promise it is almost pointless.
