### ISSUE TITLE
Notice:  Undefined index: option in components/com_content/views/category/view.html.php

### ISSUE THREAD

**Issue by dioubernardo** [joomla/joomla-cms#25029] opened 2019-05-28 13:14 UTC
### Expected result
No notice

### Actual result

[Tue May 28 10:09:08.334702 2019] [php7:notice] [pid 30629] [client 46.229.168.143:60256] PHP Notice:  Undefined index: option in components/com_content/views/category/view.html.php on line 269

### System information (as much as possible)
PHP executando em | Linux joomla 3.13.0-170-generic #220-Ubuntu SMP Thu May 9 12:40:49 UTC 2019 x86_64
-- | --
Tipo de banco de dados | mysql
Versão do Banco de Dados | 5.5.62-0ubuntu0.14.04.1
Colação do Banco de Dados | utf8_general_ci
'Collation' da conexão com o banco de dados | utf8mb4_general_ci
Versão PHP | 7.3.4-1+ubuntu14.04.1+deb.sury.org+3
Servidor Web | Apache
Interface PHP com servidor Web | apache2handler
Versão do Joomla | Joomla! 3.9.6 Stable [ Amani ] 7-May-2019 15:00 GMT
Versão da Plataforma Joomla | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
Navegador do Usuário | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36

**Comment by SharkyKZ** [comment] 2019-05-28 13:21
Using a SEF extension like sh404sef? Probably a duplicate of #22973.

**Comment by alikon** [comment] 2019-07-04 19:58
@dioubernardo please answer the question posted https://github.com/joomla/joomla-cms/issues/25029#issuecomment-496513767 else this will be closed in 1 week

**Comment by dioubernardo** [comment] 2019-07-08 17:56
these are my extensions
![extensions](https://user-images.githubusercontent.com/3487994/60831694-875ea480-a190-11e9-866b-b547c61a7ddf.png)

**Comment by dioubernardo** [comment] 2019-07-08 18:01
I manage many websites, and only in some of them does this occur, basically everyone has the same extensions with few variations.
Here is another one that runs the problem
![extensions2](https://user-images.githubusercontent.com/3487994/60831997-44e99780-a191-11e9-98c3-1a42a47baf61.png)

**Comment by SharkyKZ** [comment] 2019-08-08 08:58
Test PR #25796 please.

**Closed as completed** 2019-08-08 11:34 UTC
Labels: No Code Attached Yet
