### ISSUE TITLE
[5.2] Usability: Media Manager - Move image to other folder

### ISSUE THREAD

**Issue by woluweb** [joomla/joomla-cms#43555] opened 2024-05-28 09:57 UTC
## Problem identified

Once a Media has been uploaded, the Media Manager does not allow to move it to another folder.
Just like it is possible to Rename an Image via the interface, it should be possible to Move an Image via the interface.

Note: actually, there is a little hack: if you rename for example `joomla_black` (.png) which is in the root folder to `banners/joomla_black` then it will be moved to the `banners` folder. But you can only move this way to a *sub*folder, not to a parent or sibling folder.

## Proposed solution

On top of the existing possibilities like `Rename`, `Edit` etc, add a `Move to` option
![move](https://github.com/joomla/joomla-cms/assets/4510979/893055cd-f65e-4ec4-bcd1-a1842c76ea37)

**Comment by brianteeman** [comment] 2024-05-28 11:14
duplicate of #43339 ?

**Comment by HLeithner** [comment] 2024-05-28 11:19
Closing since it's a duplicate

**Closed as completed by HLeithner** 2024-05-28 11:19 UTC
Labels: Feature, No Code Attached Yet, UI/UX
