### ISSUE TITLE
Special access menu items not updating corretly when cache is on

### ISSUE THREAD

**Issue by Basstrup** [joomla/joomla-cms#11049] opened 2016-07-07 21:51 UTC
#### Steps to reproduce the issue
Turn on site cache in System > Global Configuration > System > Cache Setting
Make new menu item (any type)
Change Access to Registered
Go to front end log in

#### Expected result

Menu item with special access should show / disappear instantly depending on log in status

#### Actual result

Menu item does not show until cache is cleared or reset.
When logged in the menu item stays visible after log out - until cache is cleared

#### System information (as much as possible)
J 3.6rc2
PHP 5.4.45
MySQLi 5.5.48-37.8
Caching Enabled
Gzip Disabled

**Comment by brianteeman** [comment] 2016-07-07 21:57
There are several cache settings. Which exact settings did you set?

**Comment by Basstrup** [comment] 2016-07-07 23:39
Conservative Caching<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11049">issues.joomla.org/joomla-cms/11049</a>.</sub>

**Comment by Basstrup** [comment] 2016-07-07 23:43
Browsers Chrome Version 51.0.2704.103 (64-bit) Mac and Firefox 47.0.1 Mac

Also tried Progressive Caching<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11049">issues.joomla.org/joomla-cms/11049</a>.</sub>

**Comment by ggppdk** [comment] 2016-07-08 00:53
Tested and it only happens when **System - Page Cache** plugin is enabled
- it works when only using conservative / progressive caching

also looked at the code, the model will clear the caching group: 'mod_menu'
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_menus/models/item.php#L1454
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_menus/models/item.php#L1664

and the module helper uses the same caching group:  'mod_menu'
https://github.com/joomla/joomla-cms/blob/staging/modules/mod_menu/helper.php#L41

Furthermore you need to have done this to see the effect:
- page cache plugin is enabled
- view the page with menu module
- change the menu item access registered
- view the page with menu module again , and login / logout

@Basstrup 
can you check if you have enabled plugin:
**System - Page Cache**

**Comment by mbabker** [comment] 2016-07-08 01:17
AFAIR nothing in core clears the page cache except for explicitly going to
the cache manager and flushing the cache.  So as long as the module cache
is properly set and cleared with changes in the menu manager, I'd call this
expected behavior.

The page cache uses a special group to be able to cache full page and
return results quickly versus how the core cache works with only small data
segments and still runs the full page request.

**Comment by Basstrup** [comment] 2016-07-08 01:50
here's what I see https://youtu.be/m19mdkmw7B4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11049">issues.joomla.org/joomla-cms/11049</a>.</sub>

**Comment by ggppdk** [comment] 2016-07-08 06:53
Yes, that is the intended purpose of plugin

**System - Page Cache**

It will postpone changes from appearing in the frontend until
- either the cache expires (e.g. 15 mins)
- or you clear the cache

**thus works as intended**

Furthermore in order to do what you need 
Only enable Conservative or Progressive caching without the plugin: **System - Page Cache**

Conservative or Progressive caching
- works indepedent of **System - Page Cache**
- views / modules HTML is updated when settings / content are changed, **because the corresponding part of the cache** is cleaned

----

** i would say that the only bad thing in all this is the description of the plugin**
- but there is no description, it is mystery plugin

no wonder i see sometimes people confusing it with conservative / progressive caching, lucky thing is that most users do not know it is there, thus they confuse it less with conservative / progressive and they enabled it less times

The plugin should have a description instead of having almost none

**Comment by ggppdk** [comment] 2016-07-08 10:23
Please suggest corrections to description texts (language strings) that i have wrote in this PR:
#11052

**Comment by gunjanpatel** [comment] 2016-07-08 10:24
Set to "closed" on behalf of @gunjanpatel by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11049">issues.joomla.org/joomla-cms/11049</a>

**Comment by gunjanpatel** [comment] 2016-07-08 10:24
Closing see #11052<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11049">issues.joomla.org/joomla-cms/11049</a>.</sub>

**Closed by gunjanpatel** 2016-07-08 10:24 UTC
Labels: No Code Attached Yet
