### ISSUE TITLE
Version checking with joomal 4

### ISSUE THREAD

**Issue by jschmi102** [joomla/joomla-cms#30254] opened 2020-08-01 10:38 UTC
### Steps to reproduce the issue
code:
1. use Joomla\CMS\Version; 

2. $this->joomla_version = new Version();

3. if (version_compare($this->joomla_version->RELEASE, '3.4', '<'))

### Expected result
should return or check current version

### Actual result
 Undefined property: Joomla\CMS\Version::$RELEASE in ...

### Additional comments
pls. clarify how to do version (release) checking with joomla V4

**Comment by joomdonation** [comment] 2020-08-01 11:07
In your step 3 above, change code to:

if (version_compare($this->joomla_version->getShortVersion(), '3.4', '<'))

It should work.

**Comment by SharkyKZ** [comment] 2020-08-01 11:18
https://api.joomla.org/cms-3/classes/Joomla.CMS.Version.html

`RELEASE` constant has been removed. You can get the same value using `MAJOR_VERSION` and `MINOR_VERSION` constants. Magic `__get()` method for accessing constants as properties also removed. Use constants directly. Exact replacement for your code is:

    if (version_compare($this->joomla_version::MAJOR_VERSION . '.' . $this->joomla_version::MINOR_VERSION, '3.4', '<'))

**Comment by brianteeman** [comment] 2020-08-01 12:06
https://docs.joomla.org/Potential_backward_compatibility_issues_in_Joomla_4#JVersion

**Comment by richard67** [comment] 2020-08-01 14:08
Closing as expected behavior. Check previous comments for the reasons.

But thanks for reporting it, better one false report than one report missing for a real bug.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30254">issues.joomla.org/tracker/joomla-cms/30254</a>.</sub>

**Closed as completed by richard67** 2020-08-01 14:08 UTC
Labels: No Code Attached Yet
