### ISSUE TITLE
[4.0] [RFC] AMP template for Joomla Core?

### ISSUE THREAD

**Issue by alex7r** [joomla/joomla-cms#15150] opened 2017-04-07 11:41 UTC
### Should Joomla follow the trend?
Should Joomla provide (Google) AMP template for users out of the box?
Wordpress do, Joomla lacks in this aspect. And from my own experience most users (not professional developers, but sometimes they are too) looks for incredible amount of plugins to exclude default javascript files instead of using Joomla native features (via template override).
So question is: 
Is there is interest in having this kind of feature (template) in core?

**Comment by franz-wohlkoenig** [comment] 2017-04-07 11:45
similar to #12520

**Comment by alex7r** [comment] 2017-04-07 11:50
Ok, I see. @franz-wohlkoenig can you explain what politics are mentioned there?

**Comment by franz-wohlkoenig** [comment] 2017-04-07 11:53
i remembered that AMP was discussed before, so i searched for it.

**Comment by alex7r** [comment] 2017-04-07 12:06
May be @mbabker could give some explanations or links to issues that were mentioned there and stopped this effort?

**Comment by mbabker** [comment] 2017-04-07 12:19
I stopped purely based on the backlash people were having with supporting an opt-in Google effort.

AMP is not just adding a template to core.  AMP basically requires an additional view format because it has separate output requirements than a normal HTML document.

**Comment by alex7r** [comment] 2017-04-07 12:26
Ok, so it's basically about AMP issues and Joomla Code, and not some Joomla Community politics?

**Comment by mbabker** [comment] 2017-04-07 12:46
If you get past the politics some people have with using Google services or standards, then yes, it is entirely code structure related.  We basically need a `JDocumentAmp` and each component that would support AMP output would need a `view.amp.php` view class for each view that would support AMP.  And that's barely the tip of the iceberg.  We'd still have to sort out dispatching plugin events, figure out if modules could be supported and how that would be integrated, and address some of the AMP requirements related to loading CSS and JavaScript.

**Comment by C-Lodder** [comment] 2017-04-07 12:57
I would also probably note that there wouldn't be enough time to do this as it would take a serious amount of work to do it properly.

**Comment by mbabker** [comment] 2017-04-07 13:04
Luckily, it wouldn't require any B/C breaks in the existing architecture, unless telling plugins they have to check the view format and return early if they don't support it is a B/C break (which they should be doing anyway, especially if https://github.com/joomla/joomla-cms/issues/14176 gets followed through on).  Most of the changes would be introducing new architecture, so it doesn't have to be a 4.0 item if the resources just aren't there.

**Comment by dgt41** [comment] 2017-04-07 13:04
is still AMP a thing?

**Comment by ysrostov** [comment] 2017-04-07 14:44
Pardon me, just too curious to not ask as templates are being descussed - does frontend in Joomla now are completly free from any markup from backend (bootstrap2) in layouts that views generate for example in blog or other parts in frontend?

**Comment by mbabker** [comment] 2017-04-07 14:52
The core layouts are all built based on Bootstrap 2 in 3.x and will be Bootstrap 4 in 4.x.  But, aside from a couple of edge cases now, everything that produces markup in core can be overridden in some form (either through the use of JLayout and its override system, the existing layouts and override system for components and modules, or in the case of JHtml the use of its ability to register callbacks for the various keys).  Hopefully that helps to answer your question.

**Comment by ysrostov** [comment] 2017-04-07 14:56
Thanks a lot, @mbabker 
that definitely helps me to understand some points

**Comment by brianteeman** [comment] 2017-04-07 17:06
If we were to go down the route of adding AMP support then we should probably add Facebook Instant Article support at the same time

**Comment by Fedik** [comment] 2017-04-08 18:04
I think all this (amp, facebook etc) is work for 3d extension developers.
Joomla! just need to make such thing easier for them.

**Comment by wilsonge** [comment] 2017-04-16 14:43
The biggest problem is modules imho. Components can have AMP support and adding a JDocumentAmp is a bit time consuming but not impossible. What makes things really hard is the fact that modules are by design only outputting full HTML. And there would be large b/c breaks to modules in order to get them supporting non-HTML output formats.

**Comment by alex7r** [comment] 2017-04-16 19:11
@wilsonge but if we go with AMP template like the solution:
- any component output can be overrided to match AMP requirements
- any module can be overrided
- 3rd party extension builders can ship AMP layouts of their extensions as add-on that would place file to the template

**Comment by mbabker** [comment] 2017-04-16 19:16
AMP output requirements are different than normal HTML requirements and as such we cannot just simply add a template layout to existing core templates, a full AMP template to core, or AMP specific layouts in extensions, and call the task complete.  If you take a look at the wbAMP extension, you'll see all the extra effort it has to go through to work with our default HTML views.  This is why architecturally it is required to have a completely separate view format.

**Comment by wilsonge** [comment] 2017-04-16 19:48
i'm not saying no to the idea. What I'm saying is that it's a significant piece of work and depending on how hard it impacts backwards compatibility in modules one that will take a opt-in approach from modules (because even in Joomla 4 we can't force people to rewrite every module in the ecosystem to get amp support). We'd need to assemble a team to work on it - and given the amount of work involved in it it probably isn't something that would be ready in time for 4.0

**Comment by brianteeman** [comment] 2017-08-20 11:45
I am going to close this at this time. As @wilsonge says it is not a small piece of work and in the many months since this issue was created no one has come forward to work on it. Also since this issue was created there has been significant reduction in the usage of amp as a desired format

**Closed by brianteeman** 2017-08-20 11:45 UTC
Labels: No Code Attached Yet
