### ISSUE TITLE
[4][com_finder] Unable to unpublish a category within reasonable time

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#32904] opened 2021-03-28 18:41 UTC
### Steps to reproduce the issue

On a large site (thanks to [Overload](https://github.com/nikosdion/overload)) 
26512 Articles 
125 categories

Not an unreasonable size for a Joomla site really. (https://Afloat.ie currently has 35695 k2 items and 275 categories for example).

Here is a dump of a HUGE database for you https://www.phil-taylor.com/HUGE.sql.gz (Joomla admin u: admin p: adminadminadmin)

Go to the categories and attempt to unpublish the category (either with single click in categories view, or edit the category, change state and click save)

Watch the flurry of mysql queries using `show full process list`... 

Then watch your white screen of death.

### Expected result

The indexer completes within a reasonable time, and certainly before the PHP or apache/nginx timeouts. 

### Actual result

White screen of death. A timeout has been reached, Unreasonably length of time taking to save a page with the browser sat in a "loading" state. 

### Additional comments

I know a lot of work has gone into the indexer with the recent changes to make it more secure, I appreciate that. But on a large site where it would most be of use, its under performing. 

Remember these tests were done on a development server (My iMac, with 32Gb of ram!) on a shared webhosting instance the performance would be worse. :-( Sorry.

If I enable debug mode it gets worse, as each of the queries are being logged and so you hit a memory limit error before a timeout.

**Comment by Hackwar** [comment] 2021-05-13 21:01
Confirming the issue. The problem is, that on state change, the system not only changes the state of the content item in the index, but also reindexes everything again. There are situations where this is reasonable, but I would say that generally this is not necessary. Which means that we would drop the reindex from state changes. If a data source needs to reindex the content on state change, then that data source can do that in its plugin. I will create a PR.

**Comment by richard67** [comment] 2021-05-13 22:20
Closing as having a pull request. Please test #33853 .

**Closed as completed by richard67** 2021-05-13 22:20 UTC
Labels: No Code Attached Yet
