### ISSUE TITLE
[4.0] Link validation in newsfeeds

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#27331] opened 2019-12-21 14:25 UTC
### Steps to reproduce the issue
1. Create a newsfeed without entering a link
2. create a newsfeed with an invalid link protocal such as blank://test

### Expected result
1. Required field missing alert on save
2. Info about incorrect scheme on save

### Actual result
1. message about scheme
2. message about invalid link but without the scheme information

![newsfeed](https://user-images.githubusercontent.com/1296369/71309241-8e573780-23fd-11ea-8c5d-b63eedcc0e0e.gif)

**Comment by Gaurav-Punjabi** [comment] 2019-12-23 08:29
Can i work on this issue?

**Comment by SharkyKZ** [comment] 2019-12-23 08:38
@Gaurav-Punjabi of course. And you don't need to ask for permission. Just be aware that point 1 is a duplicate of #26639 and the solution is discussed there.

**Comment by Gaurav-Punjabi** [comment] 2019-12-23 08:44
Okay, got it👍.

**Comment by vbv2312** [comment] 2020-01-08 15:54
which file do we need to look up for this issue ??i am a beginner please help a bit

**Comment by SharkyKZ** [comment] 2020-01-09 08:48
@vbv2312 See #26639.

@Gaurav-Punjabi Are you still working on this?

**Comment by vbv2312** [comment] 2020-01-09 19:13
@SharkyKz thanks but with the help of discussions there i faced issues 
1) i cannot replicate the issues on my system 
2) i did not understand where was that particular code to be found 
3) i don't know how to create a fix on the basis of the comments i got there because they had no end to it .the function joomla.submitform(task,document.getElementbyId()) was called in for all article,newsfeed and user  then how come there are differences in the performance ?though i cannot replicate errror yet i am asking my assumptions .
also can you list some good first bugs that a beginner can look upto to increase the involvement in open source .
thanks

**Comment by SharkyKZ** [comment] 2020-02-11 14:55
@vbv2312 sorry for late response. This fell off my radar.

1. Did you click `Save` and not `Save & Close` button?
2. Some of the files concerned are listed in the discussion here https://github.com/joomla/joomla-cms/issues/26639#issuecomment-565336094.
3. `Joomla.submitform()` is executed but no validation is performed because button lacks `form-validation` attribute.

**Comment by AndyGaskell** [comment] 2020-11-19 10:52
I was just having a look at the second part of this, which seems to still be an issue.  So, from the initial description...

Steps to reproduce the issue
* create a newsfeed with an invalid link protocol such as blank://test

Expected result
* Info about incorrect scheme on save

Actual result
* message about invalid link but without the scheme information

Trying this out in in Joomla 4.0.0 beta5, I can recreate it ok I think.

![screengrab_news_feed_27331_a](https://user-images.githubusercontent.com/91541/99656305-9f1c8d00-2a54-11eb-83c6-44e83f5b6aa8.png)

So I guess it should be pulling in the string...
`JLIB_FORM_VALIDATE_FIELD_URL_SCHEMA_MISSING="Invalid URL: URL schema is missing in %1$s. Please add one of the following at the beginning: %2$s."`
...rather than the vanilla Invalid field: Link message.

I'll see if I can figure out what this is, the logic seems to be in `libraries/src/Form/Rule/UrlRule.php` and the form is, i think, defined in `administrator/components/com_newsfeeds/forms/newsfeed.xml `

**Closed as completed** 2022-02-01 23:16 UTC
Labels: No Code Attached Yet, J4 Issue
