### ISSUE TITLE
\Joomla\String\Inflector::getInstance()->toPlural fails on 'aircraft'

### ISSUE THREAD

**Issue by alfredojdd** [joomla/joomla-cms#30332] opened 2020-08-10 10:23 UTC
### Steps to reproduce the issue
in FormController set 'view_item' as 'aircraft'. To get the 'view_list' the function toPlural returns the same word 'aircraft' instead the plural form 'aircrafts'

### Expected result
The plural form of 'aircraft' -> 'aircrafts'

### Actual result
'aircraft' instead of 'aircrafts'

### System information (as much as possible)
Laragon 4.0.16, php 7.4.7

### Additional comments
Excuse my english :)

**Comment by SharkyKZ** [comment] 2020-08-10 11:17
Apparently, plural form of aircraft is aircraft. So it's correct as it is. You'll have to to manually define list view name.

**Comment by richard67** [comment] 2020-08-10 11:34
@brianteeman Can you confirm this as a native English speaker? I think @SharkyKZ is right, but we both are not native English speakers.

**Comment by alfredojdd** [comment] 2020-08-10 11:34
Oh! Thanks….


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by brianteeman** [comment] 2020-08-10 11:43
confirmed - aircraft is both singular and plural

**Comment by richard67** [comment] 2020-08-10 11:44
Closing as expected behavior.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30332">issues.joomla.org/tracker/joomla-cms/30332</a>.</sub>

**Closed as completed by richard67** 2020-08-10 11:44 UTC
Labels: No Code Attached Yet

**Comment by richard67** [comment] 2020-08-10 11:45
Funny detail: I am also sure that "aircrafts" is wrong. But Google Translator offers that as a possible translation from German "Flugzeuge". So it seems to be a common mistake, so common that Google Translator has adapted to it ;-)

**Comment by brianteeman** [comment] 2020-08-10 11:50
as the plural of airplane is airplanes that might suit your purpose easier
