### ISSUE TITLE
[4.0] Select button for category image not visible under Apple Safari browser

### ISSUE THREAD

**Issue by FrankyJust** [joomla/joomla-cms#30298] opened 2020-08-06 06:46 UTC
### Steps to reproduce the issue
Use Safari browser
Login to admin backend
Go to Content/Categories
Choose a category
Click on tab Options

### Expected result
Showing button for selecting a category image ![screen shot 2020-08-06 at 07 17 29](https://issues.joomla.org/uploads/1/93de64ea60c9f82a8ea1cfb3c64c9e2a.png)

### Actual result
No select button visible for category image ![screen shot 2020-08-06 at 07 06 24](https://issues.joomla.org/uploads/1/712e60f54d05f55a857a7a1b07c28339.png)

### System information (as much as possible)
local server - using MAMP - testing under Safari
When testing under e.g. Firefox the select button is visible

### Additional comments
button appears when disabling in template.min.css in selector .input-group-append -> overflow:hidden

**Comment by infograf768** [comment] 2020-08-06 08:03
Confirmed
changing `overflow:hidden` to `overflow:initial` corrects the issue, but this would have to be tested on other browsers/OSes
See also https://github.com/joomla/joomla-cms/pull/30283

Will test a patch

**Comment by Quy** [comment] 2020-08-06 08:07
Duplicate #29314

**Comment by infograf768** [comment] 2020-08-06 11:24
I have tested `overflow: -moz-hidden-unscrollable;` and it looks like working in Safari and Firefox.
In Safari we may lose a rounded corner in the Associations tab when 2 buttons only.
Did not test other browsers
What do you think?

**Comment by infograf768** [comment] 2020-08-19 09:37
Closing as we have a patch
https://github.com/joomla/joomla-cms/pull/30420

Please test

**Closed as completed by infograf768** 2020-08-19 09:37 UTC
Labels: No Code Attached Yet
