### ISSUE TITLE
Joomla 3.8.8 > Protostar - Default Template:: This template is not responsive in mobile, if you use table in the article

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#20758] opened 2018-06-14 15:15 UTC
**Go to Article Manager > Create an article
Use table in the article and save it
Access the same article in the front end from mobile
Refer the attached screenshot for the same!!**

![screen shot 2018-06-14 at 15 13 07](https://issues.joomla.org/uploads/1/b6b7d86e210eb0cc1015224606c0f336.png)

**Comment by brianteeman** [comment] 2018-06-14 15:29
This is absolutely nothing to do with the template. The problem is your own markup in the article.

**Comment by ghost** [comment] 2018-06-14 15:42
@aasimali Please ask further help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla-Core coding. For this Reason closing this Issue, thanks.

**Closed as completed** 2018-06-14 15:41 UTC
Labels: No Code Attached Yet

**Comment by ciar4n** [comment] 2018-06-14 16:15
@aasimali looks like you might have some fixed widths set on your table columns.

**Comment by aasimali** [comment] 2018-06-15 10:20
@brianteeman @ciar4n 
My problem was, The article looks perfect in the Desktop ( 1024 x 768, 1280 x 768, 1360 x 768 and above all resolutions)

But, the same article is not looking good or I would say the table in the article is not fitting well in the mobile resolution. (I have checked on iPhone 5s)!

If it's about fixed width and mark up? Then? why does it look good and fit well in the desktop resolution? [ I am a non technical end user of Joomla, Hoping to get a non-technical answer for the same : ) ]

Thank you.
Have a great day guys!!

**Comment by brianteeman** [comment] 2018-06-15 10:23
Please ask for help on the forum https://forum.joomla.org

**Comment by aasimali** [comment] 2018-06-15 10:26
@brianteeman ! No, it's alright! : ) [ I will try to resolve the issue by my own, usability matters! ]
Thank you.
