### ISSUE TITLE
Install from Web Clear search

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#42965] opened 2024-03-05 17:06 UTC
In the web installer it is never possible to clear a search

### Steps to reproduce the issue
Go to the extensions installer and the Install from web tab.
In the search box enter backup and click on search

### Expected result
Search is performed
Search box contains the string searched for (backup)
Clear button is enabled

### Actual result
Search is performed
Search box empty
Clear button is disabled

**Comment by Quy** [comment] 2024-03-05 17:24
Closing as duplicate of #41966.

**Closed as completed by Quy** 2024-03-05 17:24 UTC
Labels: No Code Attached Yet
