### ISSUE TITLE
Menu link URL to an in-page anchor ( ...#some-id) not working from a submenu

### ISSUE THREAD

**Issue by stonebyter** [joomla/joomla-cms#43324] opened 2024-04-20 21:35 UTC
### Steps to reproduce the issue

Add an article 'Music' with two divs that should be navigable with an in-page
anchor `<div id="video">` and `<div="audio">`.

Build a menu hierarchy:
[Music]       URL: index.php?option=com_content&view=article&id=6
-- [Videos]   URL: index.php?option=com_content&view=article&id=6#videos
-- [Audio].   URL: index.php?option=com_content&view=article&id=6#audio

### Expected result
When selecting one of the submenus [Videos] or [Audio] the browser should 
scroll down to the `<div>` associated with the menu item.

### Actual result
The top of the page is displayed. The browser does not scroll down.

The cause of the problem is, that two itemIds are added to the link.
The menu link created/enhanced by Joomla looks as follows:
index.php?option=com_content&view=article&id=6&itemId=130#videos&itemId=199

If I manually correct the link and put #videos at the end it works:
index.php?option=com_content&view=article&id=6&itemId=130&itemId=199#videos

### System information (as much as possible)
Einstellung	Wert
PHP erstellt für	MacBookPro 19.6.0 Darwin Kernel Version 19.6.0: Tue Jun 21 21:18:39 PDT 2022; root:xnu-6153.141.66~1/RELEASE_X86_64 x86_64
Datenbanktyp	mysql
Datenbankversion	10.4.27-MariaDB
Datenbankzeichensatz	utf8mb4_general_ci
Datenbankverbindungszeichensatz	utf8mb4_general_ci
Datenbankverbindungsverschlüsselung	Keine
Datenbankserver unterstützt Verbindungsverschlüsselung	Nein
PHP-Version	8.2.0
Webserver	Apache/2.4.54 (Unix) OpenSSL/1.1.1s PHP/8.2.0 mod_perl/2.0.12 Perl/v5.34.1
PHP-Interface für den Webserver	apache2handler
Joomla-Version	Joomla! 5.1.0 Stable [ Kudumisha ] 16-April-2024 16:00 GMT
Joomla Abwärtskompatibilität Plugin	Aktiviert ()
Browsererkennung	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36

**Comment by brianteeman** [comment] 2024-04-20 21:54
This is not a joomla bug!!

The problem is that you are not creating the anchors correctly in your content

`<div="audio"> is not valid html it must be <div id="audio">

**Comment by brianteeman** [comment] 2024-04-20 21:56
Joomla will never create a url like the one you suggest it does as it has two itemid

`index.php?option=com_content&view=article&id=6&itemId=130#videos&itemId=199`

**Comment by stonebyter** [comment] 2024-04-20 22:11
Sorry this was a typo. The div's on my page are correct, the same as you wrote `<div id="audio">`.

Hmm regarding the URL: I suppose the itemId=130 is top menu (Music) and the itemId=199 is the submenu (Video). When I check the link, there are really two itemId's and unfortunately the second one (199) is behind the #video for some reasons. The two itemId's are added by Joomla (or maybe by a plugin). I guess it is to track the the menu where the page was called from. In the menu is just the URL `index.php?option=com_content&view=article&id=6#videos`. From my point of view, the additional itemId are created by Joomla. I have no idea what else could modify the link...

**Comment by brianteeman** [comment] 2024-04-20 23:02
Sorry!!!!!

You are quite correct - thats a new bug as it should not work like that at all

**Comment by brianteeman** [comment] 2024-04-20 23:18
What you can do (and I tested myself this time) is to use the sef url instead of the non-sef url.

![image](https://github.com/joomla/joomla-cms/assets/1296369/d7b83734-4acb-44db-93df-7d581910bee2)

![image](https://github.com/joomla/joomla-cms/assets/1296369/4a107540-6153-4989-971c-365ae5280c87)

![anchor](https://github.com/joomla/joomla-cms/assets/1296369/34d2a287-2281-4aa4-a65f-116b070d3983)

**Comment by stonebyter** [comment] 2024-04-21 07:13
Thanks a lot for your help! I really do appreciate your work!

**Comment by gwstyles** [comment] 2024-04-21 12:59
In Brian's last post there are 3 links that when clicked on just go to a blank page with "private user image". What is the point if you can't see them?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43324">issues.joomla.org/tracker/joomla-cms/43324</a>.</sub>

**Comment by brianteeman** [comment] 2024-04-21 13:28
@gwstyles thats a limitation of the issues.joomla.org site. If you view it on github itself then you ccan see them - which obviously @stonebyter did https://github.com/joomla/joomla-cms/issues/43324

**Comment by gwstyles** [comment] 2024-04-21 13:47
Thank you Brian.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43324">issues.joomla.org/tracker/joomla-cms/43324</a>.</sub>

**Comment by Hackwar** [comment] 2024-08-05 15:46
There are several things here at play. In this exact case, the solution is indeed to work with the SEF URL. However there is a bug in mod_menu where it should properly parse the URL and then add the Item ID to the query part instead of doing a simple string concatenation. For performance reasons we might want to check for a hash sign before we take the effort of running the URI class.

**Comment by Hackwar** [comment] 2024-09-14 09:16
After some more thoughts about this, I've decided that using the SEF URL is the right solution and we won't change this further. Closing this issue. If you think this is in error, please report back here.

**Closed as completed by Hackwar** 2024-09-14 09:16 UTC
Labels: No Code Attached Yet

**Comment by BillyGeat** [comment] 2024-10-30 08:49
This is a good solution, but it works only if you have a flat menu structure I think...

If the link is like https://website/article1#jump-to-2, it works.

But if there are sub-menu items like https://website/products/product1, 
it does not work because the resulting link is then like this 

https://website/product1#jump-to-3 

instead of the correct one 

https://website/products/product1#jump-to-3

If I am not missing something, this could be a bug?

**Comment by BillyGeat** [comment] 2024-11-14 09:51
This issue (as stated above) is not solved in Joomla 5.2.1 (and I do not have rights to re-open the issue...)
