### ISSUE TITLE
Languages and Assets

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#14824] opened 2017-03-21 11:06 UTC
### Steps to reproduce the issue
Install several languages
and then check the assets and language database tables

### Expected result
All languages have an asset_id and the entry in the assets table includes the language name

### Actual result
All languages except for the default en-GB have an asset id
The languages that do have an asset_id have an asset name and an asset title of 
#__languages.2 etc

### Additional comments
I have no idea if this assets table is even relevant for languages as to me it _looks_ like assets is only used for acl but it looks wrong not to have at least a title that represents the language name

<img width="540" alt="screenshotr11-07-05" src="https://cloud.githubusercontent.com/assets/1296369/24144812/95606938-0e26-11e7-8a36-4e12b6f61058.png">
<img width="459" alt="screenshotr11-07-22" src="https://cloud.githubusercontent.com/assets/1296369/24144813/9585bcb0-0e26-11e7-9ce2-4d59a4763ff1.png">

**Comment by mbabker** [comment] 2017-03-21 12:14
Duplicate of https://github.com/joomla/joomla-cms/issues/13602

**Closed by mbabker** 2017-03-21 12:14 UTC
Labels: No Code Attached Yet

**Comment by brianteeman** [comment] 2017-03-21 13:08
Yes its a duplicate although your description reveals a much bigger issue
