### ISSUE TITLE
While install Joomla! the language Danish is not selectable

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#13541] opened 2017-01-10 14:42 UTC
### Steps to reproduce the issue

1. Use the current version of Joomla! 3.7.0-alpha2 
2. Start a installation and select Danish as installation language.
3. See that the language of the page does not change to Danish.

### Expected result
The language should change form English to Danish.

See also: https://github.com/joomla-projects/joomla-browser/pull/127

### System information (as much as possible)

PHP Built On 	Linux acer 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64
Database Version 	5.7.16-0ubuntu0.16.04.1
Database Collation 	utf8_general_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	7.0.8-0ubuntu0.16.04.3
Web Server 	Apache/2.4.18 (Ubuntu)
WebServer to PHP Interface 	apache2handler
Joomla! Version 	Joomla! 3.7.0-alpha2 dev [ Amani ] 20-December-2016 23:59 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0

**Comment by PhilETaylor** [comment] 2017-01-10 16:23
Confirmed.

This is due to an invalid ini file

other languages are also effected. 

Fixing...

**Comment by PhilETaylor** [comment] 2017-01-10 16:29
<img width="1127" alt="screen shot 2017-01-10 at 16 28 33" src="https://cloud.githubusercontent.com/assets/400092/21814674/f9b3c1ac-d751-11e6-8c84-1f5bf72aec02.png">

**Comment by PhilETaylor** [comment] 2017-01-10 16:37
fixed in #13544

**Closed** 2017-01-10 17:17 UTC
Labels: No Code Attached Yet
