### ISSUE TITLE
[3.8] mod_random_image broken in 3.8.8

### ISSUE THREAD

**Issue by jack77er** [joomla/joomla-cms#20536] opened 2018-05-22 16:27 UTC
### Steps to reproduce the issue
Activate the module on the frontend.

### Expected result
Nice images shown.

### Actual result
Frontend Error:
```
Using $this when not in object context	
/var/www/clients/client5/web20/web/modules/mod_random_image/tmpl/default.php:16

Call stack
#	Function	Location
1	()	JROOT/modules/mod_random_image/tmpl/default.php:16
2	require()	JROOT/modules/mod_random_image/mod_random_image.php:29
3	include()	JROOT/libraries/src/Helper/ModuleHelper.php:201
4	Joomla\CMS\Helper\ModuleHelper::renderModule()	JROOT/libraries/src/Document/Renderer/Html/ModuleRenderer.php:98
5	Joomla\CMS\Document\Renderer\Html\ModuleRenderer->render()	JROOT/libraries/src/Document/Renderer/Html/ModulesRenderer.php:47
6	Joomla\CMS\Document\Renderer\Html\ModulesRenderer->render()	JROOT/libraries/src/Document/HtmlDocument.php:491
7	Joomla\CMS\Document\HtmlDocument->getBuffer()	JROOT/libraries/src/Document/HtmlDocument.php:783
8	Joomla\CMS\Document\HtmlDocument->_renderTemplate()	JROOT/libraries/src/Document/HtmlDocument.php:557
9	Joomla\CMS\Document\HtmlDocument->render()	JROOT/libraries/src/Application/CMSApplication.php:1041
10	Joomla\CMS\Application\CMSApplication->render()	JROOT/libraries/src/Application/SiteApplication.php:780
11	Joomla\CMS\Application\SiteApplication->render()	JROOT/libraries/src/Application/CMSApplication.php:201
12	Joomla\CMS\Application\CMSApplication->execute()	JROOT/index.php:49
```

### System information (as much as possible)

Debian 8, PHP7

**Comment by mbabker** [comment] 2018-05-22 16:29
Duplicate of #20533

**Closed as completed by mbabker** 2018-05-22 16:29 UTC
Labels: No Code Attached Yet
