### ISSUE TITLE
Article Manager fails to display after upgrade to Joomla 3.3.6

### ISSUE THREAD

**Issue by rjksmith** [joomla/joomla-cms#5739] opened 2015-01-15 15:38 UTC
I have recently upgraded my site to Joomla 3.3.6. All seemed well so I checked in my changes, and began updating my site content.

After about half a day of successfully editing articles and menus, my Article Manager suddenly failed to display anything in both Firefox 34.0.5 and Safari 6.1.6.

Firefox shows http://localhost:8088/administrator/index.php?option=com_content&view=articles as:
![articlemanagerfail](https://cloud.githubusercontent.com/assets/6151111/5759775/e72d9858-9cc7-11e4-8aeb-6623ecad21ab.jpg)

Firefox shows http://localhost:8088/administrator/index.php?option=com_content as:
![articlemanagerfail2](https://cloud.githubusercontent.com/assets/6151111/5759821/62882c8e-9cc8-11e4-9abd-541379fd1036.jpg)

Safari shows a blank white page in both cases. Other Joomla pages - admin and site - are still shown normally, including individual articles (via Control Panel) and the Menu Manager.

A quick search of your error database revealed another user who reported a very similar issue: #4462. However, I can add some further details.

My installation is running on my localhost using MAMP 2.1.3, which has been working flawlessly for over a year without any config changes. Looking at my MAMP logs, I see that the Apache log contains the following error message, which coincides with each failed attempt to view the Article Manager:
[Thu Jan 15 15:03:42 2015] [notice] child pid 11651 exit signal Segmentation fault (11)

MAMP reports Apache/2.2.23 (Unix) mod_ssl/2.2.23 OpenSSL/0.9.8za DAV/2 PHP/5.4.10.

[Update] I have just stopped and restarted my MAMP servers, and the problem has vanished. However, I thought it was still worth reporting as others have experienced similar problems, and this might shed some light on the issue.

**Comment by zero-24** [comment] 2015-01-16 11:59
i can't confirm this. on two upgrades 2.5.28 -> 3.3.6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5739">issues.joomla.org/joomla-cms/5739</a>.</sub>

**Comment by zero-24** [comment] 2015-01-16 12:00
maybe a issue with your `MAMP` envoirment. I'm using `XAMPP` (Windows 8.1)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5739">issues.joomla.org/joomla-cms/5739</a>.</sub>

**Comment by brianteeman** [comment] 2015-01-16 14:23
I use mamp.. Can't confirm

**Comment by zero-24** [comment] 2015-01-16 14:36
Thanks @brianteeman 

Closing here as we can't reproduce this issue here and is fixed by a server restart thanks for your report @rjksmith<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5739">issues.joomla.org/joomla-cms/5739</a>.</sub>

**Closed by zero-24** 2015-01-16 14:36 UTC
Labels: No Code Attached Yet

**Comment by rjksmith** [comment] 2015-01-16 17:08
One day later, the problem has recurred - exactly as I previously described.

[Fri Jan 16 16:38:24 2015] [notice] child pid 13120 exit signal Segmentation fault (11)

I can confirm that I have been developing my website with Joomla for over 2 years now, and this issue has only appeared in the last 2 days, since I updated to Joomla 3.3.6 (from 3.2.1).

* My MAMP installation only supports Joomla, so this is not due to some third party interaction.
* Restarting the MAMP servers corrects the problem, so it is unlikely to be a database corruption.
* It *only* affects the Article Manager page, which narrows the code search.
* It does *not* affect the Menu Manager, so it is not in common code to both managers.
* My most-recently edited article can still be displayed in the Article Editor, via Control Panel, so only the manager is affected, not the editor.

I'll leave you to decide how to proceed.

**Comment by philmarty** [comment] 2015-05-22 09:51
Same problem with a 3.3.6 Joomla website, and it occured from one day to the other on a prod site :(

Unable to access the article view in admin page today, and yesterday everything was fine.
I get an error net::ERR_EMPTY_RESPONSE when trying to access administrator/index.php?option=com_content&view=articles
The categoies view is fine...

Where can I find a solution?

**Comment by blueboar2** [comment] 2015-05-22 12:54
I have just encountered this issue and fixed it by increasing php memory limit in php.ini from 128 to 256MB. But it seems strange that there is segmentation error and not simply message "increase memory limit"

**Comment by brianteeman** [comment] 2015-05-22 12:56
the issue is 99%certainly nothing to do with the memory limit but is
instead the result of a badly coded content plugin

On 22 May 2015 at 13:54, blueboar2 <notifications@github.com> wrote:

> I have just encountered this issue and fixed it by increasing php memory
> limit in php.ini from 128 to 256MB. But it seems strange that there is
> segmentation error and not simply message "increase memory limit"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5739#issuecomment-104653085>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by philmarty** [comment] 2015-05-22 14:33
A content plugin? 
How could it be possible, yesterday, no problem, today that weird error without installation of any new extension in the meantime...
I really don't see where the problem could be within Joomla.

The server side, which I don't manage, seems to be the best suspect, no?

**Comment by asysta** [comment] 2015-06-01 16:58
we have the same problem today.
We do the following.
doing an akeeba backup
make a new directory and and new database on the same server
then restore the backup in the new directory and take the new database
for us it works<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5739">issues.joomla.org/joomla-cms/5739</a>.</sub>

**Comment by Bakual** [comment] 2015-06-01 17:28
This is a closed issue. Please don't post here.
I'm going to lock this so it isn't misused any longer.
