### ISSUE TITLE
[5.2.0*] Scheduled Tasks Cron Scheduler User Interface is Broken

### ISSUE THREAD

**Issue by bascherz** [joomla/joomla-cms#44203] opened 2024-10-08 00:09 UTC
### Steps to reproduce the issue
1. Open Scheduled Tasks.
2. Click on any existing task.
3. Select Execution Rule "Cron Expression (Advanced)"
4. Click on any number in the Minutes column.
5. Click on any number in the Hours column.

### Expected result
Both the Minutes and Hours numbers should remain selected (highlighted).

### Actual result
Both the selected Minute and Hour should remain highlighted, but the selected Minutes value does not.

### System information (as much as possible)
Reproduced with 5.2.0 RC1, RC2, and RC3, even during PBF.

System: Linux na8861.serversignin.com 4.18.0-477.10.1.lve.el8.x86_64 #1 SMP Wed May 17 07:12:55 EDT 2023 x86_64
Build Date: Sep 2 2024 12:05:34
Server API: LiteSpeed V8.1 Cloudlinux 1.3
Database Type: mysql
Database Version: 10.11.9-MariaDB
Database Collation: utf8mb4_unicode_ci
Database Connection Collation: utf8mb4_general_ci
PHP Version	8.2.23

### Additional comments
I have been trying to use the Cron Expression execution rule since the Task Scheduler became available. The UI did work originally, but since 5.2.0 PBF the UI has acted as described above. This method of scheduling has never worked, but there is new code that needs to be tested. It just cannot be without fixing the UI first.

**Comment by Quy** [comment] 2024-10-08 02:03
I am not able to replicate it. In dark mode, the highlight is barely visible but it doesn't exhibit the issue you are experiencing.

![Image](https://github.com/user-attachments/assets/5f01e2be-966c-4944-be14-ff18868b4821)

![Image](https://github.com/user-attachments/assets/d3622550-7e27-400f-9bdb-b15972f16ff9)

**Comment by tecpromotion** [comment] 2024-10-08 06:13
Right, dark mode isn't really good here. Maybe @coolcat-creations can take a look at it?

I tested it too and can't reproduce it either.
![Image](https://github.com/user-attachments/assets/12373a76-867d-4faf-9456-7eab5ca35348)

**Comment by drmenzelit** [comment] 2024-10-08 09:27
I can't reproduce the problem
![Image](https://github.com/user-attachments/assets/803fa1d1-de60-4668-ba00-fde4c05c3d15)

**Comment by Hackwar** [comment] 2024-10-08 09:28
I also tested this and can not replicate this. Can you please check again that this is NOT a problem with visibility in dark mode or an issue in your specific browser?

**Comment by brianteeman** [comment] 2024-10-08 12:15
Please confirm that you are using the atum admin template

**Comment by bascherz** [comment] 2024-10-08 12:47
Looks like dark mode is the culprit. But something definitely changed here. The selection color didn't change from blue to black before 5.2. Is that really necessary? And this is a real problem since it appears Atum defaults to dark mode. Other than these observations, I retract the issue.

**Comment by bascherz** [comment] 2024-10-08 12:50
> And this is a real problem since it appears Atum defaults to dark mode.

Okay, so it defaults to the OS setting, not dark. Still an issue since many folks use dark mode.

**Comment by Hackwar** [comment] 2024-10-08 12:59
Thank you for reporting this. Since the interface is fine, I'm closing this one. Please check if we have another issue regarding dark mode which fits this problem or create a new issue for this problem.

**Closed as completed by Hackwar** 2024-10-08 12:59 UTC
Labels: No Code Attached Yet

**Comment by coolcat-creations** [comment] 2024-10-08 15:06
I made a PR for the dark mode
