### ISSUE TITLE
Canonical link looses article ID

### ISSUE THREAD

**Issue by kainhofer** [joomla/joomla-cms#6751] opened 2015-04-12 17:38 UTC
#### Steps to reproduce the issue

  * Create an article (say with ID 41)
  * Access it via http://localhost/component/content/article.html?id=41 (*)
  * Look at the source code of that page. The canonical link will have lost the article ID:

    &lt;link href="http://localhost/component/content/article.html?id=article" rel="canonical" />

(*)  (These URLs are created as canonical links when you call the page via  http://localhost/component/content/article/41, see [issue 6069](http://issues.joomla.org/tracker/joomla-cms/6069)

#### Expected result

The canonical should retain the article id 41 rather than replacing it by "article". Ideally, the canonical would be

    <link href="http://localhost/component/content/article/41" rel="canonical" />

but even the originally called URL would be okay:

    <link href="http://localhost/component/content/article.html?id=41" rel="canonical" />

#### Actual result

The article ID is completely lost in the canonical link and replaced by the string "article"

    <link href="http://localhost/component/content/article.html?id=article" rel="canonical" />

#### System information (as much as possible)

Joomla 3.4.1 (from the released package), PHP 5.5.12 installed from stock Ubuntu packages
SEF enabled

**Comment by bertmert** [comment] 2015-04-12 18:26
Confirmed also with current staging Joomla

**Comment by franzpeter** [comment] 2015-04-17 07:51
I can confirm that strange behaviour too. Wrong built canonical with missing id!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6751">issues.joomla.org/joomla-cms/6751</a>.</sub>

**Comment by joomir** [comment] 2015-05-16 09:11
I write a plugin for solving joomla articles diplicate issues. this plugin canonical all duplicate content to original content. http://extensions.joomla.org/extensions/extension/site-management/seo-a-metadata/articles-canonical

**Comment by franzpeter** [comment] 2015-05-18 08:21
joomir, OK, but that does not solve the main problem. It should work too without any workaround plugin.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6751">issues.joomla.org/joomla-cms/6751</a>.</sub>

**Comment by SEWilco** [comment] 2016-01-27 20:36
Issue still exists. Generic canonical emitted: /component/content/article?id=article<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6751">issues.joomla.org/joomla-cms/6751</a>.</sub>

**Comment by rdeutz** [comment] 2016-08-17 20:31
can't reproduce the problem seems fixed, closing, can be opened if the problem still exists.

**Closed by rdeutz** 2016-08-17 20:31 UTC
Labels: No Code Attached Yet
