### ISSUE TITLE
When logged in as Registered, links from MS Word result unexpected page

### ISSUE THREAD

**Issue by jonathanCA** [joomla/joomla-cms#21654] opened 2018-08-16 19:31 UTC
### Steps to reproduce the issue
1. Create an article and menu item in Joomla, set to Registered
2. Login to the front end with a Registered user, the page will now be accessible
3. Create a MS Word document and hyperlink any text to the newly created page 
4. Click the hyperlink from within MS Word (Ctrl+click is the shortcut)

### Expected result
After successfully logging into Joomla, the hyperlink from MS Word should take users to the page created in Step 1 (since the session is currently active). This is the result when navigating from any other desktop based program (email clients, pdf, OpenOffice, etc). 

### Actual result
Despite being logged into Joomla front-end as a Registered User, when the user clicks on the link from MS Word, they are taken back to the default Joomla account profile page, which does indicate the session is still active. 

### System information (as much as possible)
Windows 10
Chrome 68.0.3440.106
Edge 42.17134.1.0
MS Word 2016 (only one we have to test with) 

Joomla 3.8.11 (and tested a few previous versions with same results) 
PHP 7.0.30
MySQL 	5.7.21

### Additional comments
Quick video reproducing problem: https://www.screencast.com/t/sDqh1Ms8zu

We also tried changing default browser, same result. The result of this will likely be that the problem is with MS Word. Still I think it's important for us to verify this.. a lot of people use Word and if a small update to Joomla can resolve this, it might be worth implementing.

**Comment by dgrammatiko** [comment] 2018-08-16 19:39
> Create a MS Word document and hyperlink any text to the newly created page

How did you manage to create an MS Word document **in** Joomla?

**Comment by jonathanCA** [comment] 2018-08-16 20:05
This has to do with people linking from local desktop MS Word documents to non-local Joomla websites, apologies if that wasn't clear.   I posted because people do hyperlink from Word documents to websites for various reasons, and it appears this causes an unexpected result. 

Again, very low priority and it is possibly a MS Word problem. Still it's worth documenting and checking on as time permits.

**Comment by Joomv** [comment] 2018-08-17 15:57
I've had something similar happen but I'm pretty sure this is word at play rather than J!

**Comment by jwaisner** [comment] 2020-03-18 03:03
Not a bug. Closing.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21654">issues.joomla.org/tracker/joomla-cms/21654</a>.</sub>

**Closed as completed by jwaisner** 2020-03-18 03:03 UTC
Labels: No Code Attached Yet
