### ISSUE TITLE
Custom Category Overrides broken

### ISSUE THREAD

**Issue by jennixgit** [joomla/joomla-cms#36027] opened 2021-11-13 23:34 UTC
### Steps to reproduce the issue
1) create overrides in Cassiopeia template as normal
2) pull either blog.php or default.php and children to same folder, rename as "custom.php" (and children), modify .php and .xml as desired, and upload into template/Cassiopeia/html/com_content/category
3) create menu item using new option in new menu item dialog, which does appear as expected
4) open menu item in front end and see default component view instead of override

### Expected result

I should expect to see my custom.php (and children) rendering as they used to. 

### Actual result

I see the component default view instead of my custom override view

### System information (as much as possible)

cPanel Version	98.0 (build 11)
Apache Version	2.4.51
PHP Version	7.4.25
MySQL Version	5.7.36
Architecture	x86_64
Operating System	CentOS 7-9.2009.0.e17.centos.x86_64

### Additional comments

I tried this twice on two installs. Maybe i'm missing something dumb, but it sure seems broken.

**Comment by nozaro33** [comment] 2021-11-14 04:32
I cannot replicate this, works for me without issue

**Comment by HLeithner** [comment] 2021-11-14 08:38
I have already done a couple of J4 sites always with overrides which are working. Are you sure you uploaded the right files?

**Comment by jennixgit** [comment] 2021-11-14 17:48
i copied the default.php and children, added some code (which works when i put it in the default.php override. But when i rename that file and the children, it does not work, i see the component default.php and children. if i rename the files back to default.php, the desired view renders.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36027">issues.joomla.org/tracker/joomla-cms/36027</a>.</sub>

**Comment by jennixgit** [comment] 2021-11-14 17:55
i dunno why it would matter, but the mod is:

in default_children.php, in insert 

	<?php if ($this->items[$i]->created_by == JFactory::getUser()->id) : ?>

between lines 172 & 173, and then close the if before the endforeach, as one does. It renders the category with only the articles written by the current user while the file's named "default_children.php" but not when it (and its family) are named "anythingelse_children.php".

I could be missing something easy. But i've wrangled with this for a few hours. Thanks for y'all's time<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36027">issues.joomla.org/tracker/joomla-cms/36027</a>.</sub>

**Comment by HLeithner** [comment] 2021-11-14 18:05
So is it fixed for you? It's not clear for me if you still have a problem or not.

**Comment by jennixgit** [comment] 2021-11-14 18:13
No, @HLeithner it doesn't work. The mod above only works when the override is named default_articles.php. It does not work for any custom.php and children... for me. 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36027">issues.joomla.org/tracker/joomla-cms/36027</a>.</sub>

**Comment by HLeithner** [comment] 2021-11-14 20:13
I'm sorry but I can't replicate the issue.

I copied default.php, default.xml, default_articles.php and default_children.php to xxx.php, xxx.xml, xxx_articles.php and xxx_children.php
Then I changed only the title in the xxx.xml to "xxx" and created a menu item with the "xxx" layout. Selected a category with multiple sub categories and checked the frontend. I can confirm that this works like excepted. The page is update from 3.10 to 4.0 to 4.1.

I think something is wrong with your path or file names.

**Comment by chmst** [comment] 2021-11-15 14:28
To be honest - if you ask supporters in forum.joomla.org you will get better help.

But if you are convinced that it is a bug in Joomla: Please post a screen of your template/html/com_content folder with all files. As @HLeithner says - there must be an error in your structure.

**Comment by jennixgit** [comment] 2021-11-15 18:56
i made another clean install and started from scratch. Apparently there was some kind of issue with the old install and naming/renaming/moving/etc. Thanks for all your time. I'll check again again and again before i post again. 

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36027">issues.joomla.org/tracker/joomla-cms/36027</a>.</sub>

**Comment by jennixgit** [comment] 2021-11-15 18:57
FWIW, the old install still breaks if i only rename the files. no idea what i did to it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36027">issues.joomla.org/tracker/joomla-cms/36027</a>.</sub>

**Comment by HLeithner** [comment] 2021-11-15 21:08
So now it works? that's good I'm closing this.

**Closed as completed by HLeithner** 2021-11-15 21:08 UTC
Labels: No Code Attached Yet
