### ISSUE TITLE
[4.0] error on clean update

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#30918] opened 2020-10-04 18:25 UTC
### Steps to reproduce the issue
Update a clean joomla 3.9 to 3.10alpha2 and then joomla 4 beta4

### Expected result
No errors

### Actual result
error about a missing template
having to log back in (twice) to complete the update when I thought it was finished

See this 1 minute silent video
https://youtu.be/dJm-XjxZjek

**Comment by brianteeman** [comment] 2020-10-04 18:56
Note the documentation (https://docs.joomla.org/Joomla_3.x_to_4.x_Step_by_Step_Migration) makes no note of this error message and says I am finished when I thought I was. Not that I am not finished until I have done the second login and waited for completion

`Make tea whilst the spinning circle goes round and round. The amount of time the wheel spins is dependent on your site, Internet connection and server speed. The process takes about two minutes. When the update is finished, you will probably be logged out of the Administrator. Sign in again. Twice.`

cc @

**Comment by zero-24** [comment] 2020-10-04 19:25
Yes this is a known issue right now and should be marked as release blocker already. I have tried to debug it but i haven't found the reason yet. It might need someone with more skills on that process than me.

**Comment by zero-24** [comment] 2020-10-04 19:27
https://github.com/joomla/joomla-cms/issues/28465 that is the issue i mean.

**Comment by ceciogit** [comment] 2020-10-04 21:25
Hi Guys, it happened also to me couple of times yesterday and the second one i had dev debug opened and it showed me something about "parent" and "inherited"columns missing.. do you think it is possibly something linked?

**Comment by zero-24** [comment] 2020-10-04 21:39
how did you upgrade? Did you upgrade to 3.10 alpha2 before you did the upgrade to 4.x?

**Comment by ceciogit** [comment] 2020-10-04 21:45
First Time it was CLEAN 3.10 a2 to 4 b4 (i was kicked out like video of @brianteeman )
Second Time it was CLEAN 4b2 to 4b4 > the update finished with error about missing template and php vars $parent and $inherited
edited , the update were to Joomla 4 Beta 4
And ive found the broken update is still on my localhost

![image](https://user-images.githubusercontent.com/51973854/95027919-7f93f580-069c-11eb-8e78-7e9baa544fcf.png)

**Comment by zero-24** [comment] 2020-10-04 21:52
> First Time it was CLEAN 3.10 a2 to 4 b3 (i was kicked out like video of @brianteeman )

Yes that is right now expected / known issue as mention above. 

> Second Time it was CLEAN 4b2 to 4b3 > the update finished with error about missing template and php vars $parent and $inherited

beta 2 to beta 3? It should be beta 3 to beta 4 that breaks right or better anyting to beta4 that is not going via 3.10alpha2 For that specific case an manual step has to be made: https://docs.joomla.org/Special:MyLanguage/J4.x:Upgrade_to_4.0_Beta_4

**Comment by ceciogit** [comment] 2020-10-04 21:53
> beta 2 to beta 3? It should be beta 3 to beta 4 that breaks right? For that specific case an manual step has to be made: https://docs.joomla.org/Special:MyLanguage/J4.x:Upgrade_to_4.0_Beta_4

yep edited sorry for typo

**Comment by zero-24** [comment] 2020-10-04 21:53
Yes so that doc explains the issue and how to fix ;)

**Comment by jwaisner** [comment] 2020-10-05 21:21
Closing as duplicate of #28465 please reference for future tracking of issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30918">issues.joomla.org/tracker/joomla-cms/30918</a>.</sub>

**Closed as completed by jwaisner** 2020-10-05 21:21 UTC
Labels: No Code Attached Yet
