### ISSUE TITLE
Bug Ui Menu Joomla! 3.6

### ISSUE THREAD

**Issue by lungkao** [joomla/joomla-cms#11113] opened 2016-07-14 00:10 UTC
#### Steps to reproduce the issue

Create a Menu Type 2 menu Length does not equal

#### Expected result
 please see on images

![2016-07-14_07-04-55](https://cloud.githubusercontent.com/assets/2047778/16823940/fe36d6cc-4991-11e6-9286-3ecaf2cfd3f4.jpg)

![2016-07-14_07-05-18](https://cloud.githubusercontent.com/assets/2047778/16823963/1ee37790-4992-11e6-9abd-e93e34b70ddf.jpg)
![2016-07-14_07-12-58](https://cloud.githubusercontent.com/assets/2047778/16824011/740529bc-4992-11e6-8f8e-80790d6c4a36.jpg)

**Comment by JamalTailored** [comment] 2016-07-14 06:40
I am able to reproduce this issue in current staging version and joomla 3.6 but i am not able to reproduce the same issue in joomla 3.5.1

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11113">issues.joomla.org/joomla-cms/11113</a>.</sub>

**Comment by brianteeman** [comment] 2016-07-14 09:05
I cannot replicate this using Google Chrome

![screen shot 2016-07-14 at 04 04 55](https://issues.joomla.org/uploads/1/a9731b7a1b74b2863f023d7d53825cd0.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11113">issues.joomla.org/joomla-cms/11113</a>.</sub>

**Comment by RonakParmar** [comment] 2016-07-14 09:08
I am not able to reproduce this issue in Firefox 47.0.1 Ubuntu 12.04 with latest staging setup.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11113">issues.joomla.org/joomla-cms/11113</a>.</sub>

**Comment by killoltailored** [comment] 2016-07-14 09:15
I able to reproduce this issue in operating system Windows 8.1, Browser: Chrome Version 51.0.2704.106 m
![screen shot 2016-07-14 at 04 14 53](https://issues.joomla.org/uploads/1/61dca23ca9e1d14fac62c0d068b65630.png)

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11113">issues.joomla.org/joomla-cms/11113</a>.</sub>

**Comment by lungkao** [comment] 2016-07-14 11:08
google chrome Version 51.0.2704.103 (64-bit) on mac
![chrome](https://cloud.githubusercontent.com/assets/2047778/16837430/8c2e8082-49ed-11e6-8b75-0d95d2bc370c.png)

Firefox 47.01
![firefox](https://cloud.githubusercontent.com/assets/2047778/16837460/b34fa088-49ed-11e6-832b-9cad9c01be92.png)

Safari 9.1.1
![safari](https://cloud.githubusercontent.com/assets/2047778/16837500/dc13c8d2-49ed-11e6-9a7d-cf352d782051.png)

**Comment by C-Lodder** [comment] 2016-07-14 12:13
I cannot replicate this either:

![menu1](https://cloud.githubusercontent.com/assets/2019801/16839058/ca13fa40-49c4-11e6-9632-988ee73710e6.png)
![menu2](https://cloud.githubusercontent.com/assets/2019801/16839059/cb5d77c8-49c4-11e6-9661-9687f4b9549d.png)

**Comment by brianteeman** [comment] 2016-07-14 12:17
Can everyone who reported this issue please ensure that they have cleared
their BROWSER cache!!!

On 14 July 2016 at 13:13, Lodder <notifications@github.com> wrote:

> I cannot replicate this either:
>
> [image: menu1]
> <https://cloud.githubusercontent.com/assets/2019801/16839058/ca13fa40-49c4-11e6-9632-988ee73710e6.png>
> [image: menu2]
> <https://cloud.githubusercontent.com/assets/2019801/16839059/cb5d77c8-49c4-11e6-9661-9687f4b9549d.png>
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/11113#issuecomment-232648587>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8Yj9SDR24ZLb0UrYa34a6uyAMZgsks5qVif_gaJpZM4JL-BI>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by lungkao** [comment] 2016-07-15 00:24
on css template.css line 7271 test remove  
`.navbar .nav > li ul::-webkit-scrollbar {
	-webkit-appearance: none;
	width: 7px;
}`
![screen shot 2559-07-15 at 7 24 02 am](https://cloud.githubusercontent.com/assets/2047778/16859909/2a9bf820-4a5d-11e6-85e9-67444513ebb9.png)

**Comment by andrepereiradasilva** [comment] 2016-09-01 10:37
i can't reproduce this on latest staging ....

**Comment by brianteeman** [comment] 2016-09-07 08:30
Hi 

I am closing this as it has not been reproduced on current staging. It can always be reopened if someone can show it not working with current staging<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11113">issues.joomla.org/joomla-cms/11113</a>.</sub>

**Closed** 2016-09-07 08:30 UTC
Labels: No Code Attached Yet
