### ISSUE TITLE
[5.2][Guided Tours] auto start functionality breaks manager user

### ISSUE THREAD

**Issue by heelc29** [joomla/joomla-cms#44080] opened 2024-09-15 12:46 UTC
### Steps to reproduce the issue

- Create an user and assign it to the “Manager” group
- Visit the backend

### Expected result

no error

### Actual result

If you open home dashboard the "Welcome to Joomla!" tour starts
When click "Cancel" or "Hide Forever" an error appears (also when you try to finish the tour)
![image](https://github.com/user-attachments/assets/e0ce4378-5542-4016-ae14-45f1e9493809)

Console Error:
`/administrator/index.php?option=com_guidedtours&task=ajax.fetchUserState&format=json&tid=12&sid=1&context=tour.skip`
```json
{
    "error": true,
    "code": 403,
    "message": "You don't have permission to access this. Please contact a website administrator if this is incorrect."
}
```

This error is also present if you try to cancel any other tour.

### System information (as much as possible)

j5.2.0-beta3-dev

### Additional comments

Caused by #43814
Should be a release blocker

**Comment by richard67** [comment] 2024-09-15 12:48
Ping @obuisard

**Comment by obuisard** [comment] 2024-09-15 14:14
I can reproduce the problem. Looking into it.

**Comment by obuisard** [comment] 2024-09-15 15:50
It is a permission issue. We call the Ajax controller fetchUserState but the Manager is missing the Access Administration Interface permission for /administrator/index.php?option=com_guidedtours&task=ajax.fetchUserState&format=json&tid=12&sid=1&context=tour.skip to go through

**Comment by dautrich** [comment] 2024-09-15 16:07
I got the identical error message after logging in as Super User when I clicked Complete at the end of the Welcome Tour.

**Comment by obuisard** [comment] 2024-09-15 16:10
> I got the identical error message after logging in as Super User when I clicked Complete at the end of the Welcome Tour.

@dautrich Rolf, what was the error in the browser console?

**Comment by dautrich** [comment] 2024-09-15 16:55
When I tried for the first time, I didn't have a look at the browser console (shame on me). 
I deleted everything (db + directory) and started from scratch. But this time I didn't get any error. Strange!

**Comment by obuisard** [comment] 2024-09-15 17:11
> When I tried for the first time, I didn't have a look at the browser console (shame on me). I deleted everything (db + directory) and started from scratch. But this time I didn't get any error. Strange!

Thanks, I am glad because it should not happen... But still concerning why it happened the first time.

**Comment by obuisard** [comment] 2024-09-15 17:11
I have created a fix. Please wait for PR. I created a Dispatcher for Guided Tours, none was provided.

**Comment by richard67** [comment] 2024-09-15 17:55
Closing as having a pull request. Please test #44082 . Thanks in advance.

**Closed as completed by richard67** 2024-09-15 17:55 UTC
Labels: No Code Attached Yet, Guided Tours
