### ISSUE TITLE
Component options dialog - "permissions" tab mandatory?

### ISSUE THREAD

**Issue by schultz-it-solutions** [joomla/joomla-cms#11668] opened 2016-08-19 13:18 UTC
### Steps to reproduce the issue
0) referring to Joomla 3.6.2 stable
1) login to administration, open the "Options" dialog window for "Banners" (or any other component)
this works as expected
2) change the components "config.xml" file by "commenting out" the permissions tab like this:

![19-08-2016 15-20-00](https://cloud.githubusercontent.com/assets/8665822/17810958/7681edba-6620-11e6-9217-fba7e1782aa3.png)

### Expected result
this used to work without issues up to Joomla version 3.5.1
just **"not showing"** the Permissions tab, but everything else in the configuration.

### Actual result
you cannot access the configuration panel anymore, you get an:
**0 Call to a member function getFieldsets() on boolean** 
error

### System information (as much as possible)
Joomla 3.6.2

### Additional comments
I used this method to secure our demo website, where potential customers can try out our joomla extensions. I want them to be able to configure the extensions, however I do not want them to be able to change the "Permissions" (and some other crucial settings).

What is the background why this is no longer possible?

**Comment by brianteeman** [comment] 2016-08-19 15:21
I can not confirm this. I deleted the code you highlighted and the configuration shows as expected

![screen shot 2016-08-19 at 10 21 37](https://issues.joomla.org/uploads/1/47cabd03908631af72c3c3c3465fa1b0.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11668">issues.joomla.org/joomla-cms/11668</a>.</sub>

**Comment by Bakual** [comment] 2016-08-19 15:36
@schultz-it-solutions You know you can set the ACL so the user is able to edit the options but not the permissions? No need to hack the files :smile: 
We added this around Joomla 3.4

**Comment by brianteeman** [comment] 2016-08-19 20:45
I am closing this as not a bug and as @Bakual states this can be done without hacking the core using the existing ACL

**Closed by brianteeman** 2016-08-19 20:45 UTC

**Comment by ggppdk** [comment] 2016-08-19 21:38
I cannot confirm the issue

I commented out the permission in com_banners and in another component
and the error does not occur

- and we can not know where the issue is because  we do not print **file and number** of where the error occured , see: https://github.com/joomla/joomla-cms/pull/11675, and it is not printed even when DEBUG flag is ON

@schultz-it-solutions 
can it be , that that the error is not thrown not inside Joomla code, but inside a 3rd party extension ?
please add line and file to the error.php of isis backend template and check ...

@Bakual 
we cannot deny ACL to super admins , right ? 
but even if could , it would still be problematic of the component to configure this on installation and then user could change ACL and hit on the issue
that is if there is an issue, because i cannot confirm it

**Comment by Bakual** [comment] 2016-08-19 21:44
@ggppdk Super Admins can do anything per definition :smile:

**Comment by schultz-it-solutions** [comment] 2016-08-20 08:37
Thanks for your answer.
I know superadmins can do anything. but in this case (a demo site) I want "Managers" to be able to configure the component, but not changing permissions. @Bakual: I am not aware of the possibility to "finegrain" the usage of the options dialog, will check this - if this works as expected, that would of course solve the issue.
I will doublecheck (again) and try to find more infos about the issue...

**Comment by ggppdk** [comment] 2016-08-20 10:01
@schultz-it-solutions 

> and we can not know where the issue is because we do not print file and number of where the error occured, see: #11675, and this info (PHP7) is not printed even when DEBUG flag is ON

**Comment by schultz-it-solutions** [comment] 2016-08-20 16:34
@brianteenman: Please note that "deleting" the respective passage is not identical to "uncommenting". If I delete the complete fieldset, I also get no error message. So the issue has to be connected to the "commenting" behaviour.
@ggppdk: agreed, this makes debugging harder. but If I ONLY flipflop this one change (doing it and undoing it) and have the behaviour consistent, I tend to belief this is the root of the issue.

**Comment by brianteeman** [comment] 2016-08-20 16:39
Looking again at your screenshot it looks to me like you are not commenting a multi line block correctly. My understanding is that you begin the block with <!-- and end the block --!> But you are ending the line not the block

**Comment by schultz-it-solutions** [comment] 2016-08-20 17:18
the "End Comment" is "inactive" in the first line, it is   - -> with SPACE between the two hyphens
at the end, the "Beginn Comment" is "inactive as well with SPACES between the exclamation mark and the hypens.
 - this used to work up to the current version.

But I agree, the issue must be somewhere in the interpretation of these things. If I make "just one comment" (I think this is what you are referring to), the error does not appear. 

But this would mean, that the interpreting of the xml stream beliefs this  " <!  -  -  " to be a "start comment as well..
