### ISSUE TITLE
SQL error on com_fields

### ISSUE THREAD

**Issue by ghazal** [joomla/joomla-cms#13130] opened 2016-12-08 11:57 UTC
### Steps to reproduce the issue
Update to commit b1460357808f44b99f2877d8a9133b8c6c8a8c0d

### Actual result
Error on : administrator/index.php?option=com_fields&context=com_content.article

``` sql
Unknown column 'a.group_id' in 'field list' 
SQL=SELECT a.id, a.title, a.alias, a.checked_out, a.checked_out_time, a.note, a.state, a.access, a.created_time, a.created_user_id, a.ordering, a.language, a.fieldparams, a.params, a.assigned_cat_ids, a.type, a.default_value, a.context, a.group_id, a.label, a.description, a.required,l.title AS language_title, l.image AS language_image,uc.name AS editor,ag.title AS access_level,ua.name AS author_name,g.title AS group_title, g.access as group_access, g.state AS group_state FROM #__fields AS a LEFT JOIN `#__languages` AS l ON l.lang_code = a.language LEFT JOIN #__users AS uc ON uc.id=a.checked_out LEFT JOIN #__viewlevels AS ag ON ag.id = a.access LEFT JOIN #__users AS ua ON ua.id = a.created_user_id LEFT JOIN #__fields_groups AS g ON g.id = a.group_id WHERE a.context = 'com_content.article' AND a.state IN (0, 1) ORDER BY a.ordering asc LIMIT 100 Unknown column 'a.group_id' in 'on clause' 
SQL=SELECT COUNT(*) FROM #__fields AS a LEFT JOIN `#__languages` AS l ON l.lang_code = a.language LEFT JOIN #__users AS uc ON uc.id=a.checked_out LEFT JOIN #__viewlevels AS ag ON ag.id = a.access LEFT JOIN #__users AS ua ON ua.id = a.created_user_id LEFT JOIN #__fields_groups AS g ON g.id = a.group_id WHERE a.context = 'com_content.article' AND a.state IN (0, 1)
```

### System information (as much as possible)
PHP 7.0.11

### Additional comments
Error on two different 3.7.dev installations

**Comment by Bakual** [comment] 2016-12-08 11:59
Run the database fixer. That should fix it.

**Comment by ghazal** [comment] 2016-12-08 12:06
I did this BEFORE posting.
And no.
It didn't.

**Comment by laoneo** [comment] 2016-12-08 12:43
Can you  try it on a fresh installation?

**Comment by ghazal** [comment] 2016-12-08 13:12
Test 1 and 2:
two 3.7 sites installed around October and regularly updated.
1 from github staging
1 from nightlybuilds
-> SQL error as described

Test 3
A fresh install (yesterday's nightly build full package)
Updated from today's "nightlybuilds" archive.
-> no SQL error (except #13128 issue and commit that's correcting the sql error targetted)

**Comment by Bakual** [comment] 2016-12-08 13:56
> Test 1 and 2:
two 3.7 sites installed around October and regularly updated.
1 from github staging
1 from nightlybuilds
-> SQL error as described

The problem is that updating a nightly build isn't really supported. This may be the issue in your case.
You can test the update path using a 3.6.4 and update that to staging/nightly. If that works it is fine.

**Comment by mbabker** [comment] 2016-12-08 13:59
The thing that makes upgrades between nightlies "tricky" is the SQL schema files (part of the reason we went back to dated files versus all updates rolled into one was to help with this path).  Of course if you're changing the already existing files it complicates things and might cause breakage.  Otherwise, using the upload & install (or even sitting on the nightly build channel since it uses a higher version number than staging) should generally be OK.

**Comment by Bakual** [comment] 2016-12-08 14:09
Yeah, that's what we did in this case because it doesn't make much sense to first create a catid column for #__fields and then change it in the next file to group_id.
Since the upgrade path from nightlies isn't a "supported" path, we decided to merge the files into one.

**Comment by laoneo** [comment] 2016-12-08 14:28
I just did a fresh installation and it worked as expected.

**Comment by brianteeman** [comment] 2016-12-09 10:58
Closed as it is not an error. You cannot reliably update nightlybuilds or staging<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13130">issues.joomla.org/tracker/joomla-cms/13130</a>.</sub>

**Closed** 2016-12-09 10:59 UTC
Labels: No Code Attached Yet
