### ISSUE TITLE
Isis Non-Scrolling Menu

### ISSUE THREAD

**Issue by SwingShoes** [joomla/joomla-cms#5663] opened 2015-01-10 23:39 UTC
#### Steps to reproduce the issue
If numerous components are utilized on Joomla 3.3.6, one cannot scroll past the size of the browser window to see the components at the bottom (or below) the window-border.

#### Expected result
One would expect the menu to continue to scroll down to see the bottom most items on the component menu.

#### Actual result
The menu only shows what is shown within the browser window.

**Comment by brianteeman** [comment] 2015-01-11 00:01
Is this a duplicate of  #5131 or is it something different.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5663">issues.joomla.org/joomla-cms/5663</a>.</sub>

**Comment by SwingShoes** [comment] 2015-01-11 00:12
yes - That seems to be the same issue. The original poster didn’t correlate it to the Administrator Isis template.

Thanks,
Erik

**Closed** 2015-01-11 00:13 UTC
