### ISSUE TITLE
Get 404 not found by adding a new article on the main menu

### ISSUE THREAD

**Issue by pranaymirchandani** [joomla/joomla-cms#32298] opened 2021-02-04 13:46 UTC
### Steps to reproduce the issue
1) Create a category named hello.
2) Create an article named hello.
3) Create a new menu item for main menu.
4) Name the title hello.
5) Select the menu item type as articles.
6) Select single article and save.
7) go to the frontend and click on hello in the main menu.

### Expected result

Hello article should open up with any test text you typed when creating it 

### Actual result

404 not found

### System information (as much as possible)

PHP Built On	Linux lamp120.cloudaccess.net 3.10.0-962.3.2.lve1.5.24.7.el6h.x86_64 #1 SMP Mon Dec 17 12:02:35 EST 2018 x86_64
Database Type	mysql
Database Version	5.7.30-cll-lve
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
Database Connection Encryption	None
Database Server Supports Connection Encryption	Yes
PHP Version	7.3.23
Web Server	Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 4.0.0-beta8-dev Development [ Mañana ] 2-February-2021 20:02 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36

### Additional comments
none

**Comment by ChristineWk** [comment] 2021-02-04 13:58
Can't confirm.
Check if it's set to: published. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32298">issues.joomla.org/tracker/joomla-cms/32298</a>.</sub>

**Comment by chmst** [comment] 2021-02-04 14:05
@pranaymirchandani thank you for your first contribution, but @ChristineWk is right. Either your article is not published or your category. I am closing this now as this is not a Joomla issue.

**Comment by richard67** [comment] 2021-02-04 14:06
~~Or possibly URL rewriting on in Global Configuration but no .htaccess file present?~~
Forget it. Unpublished is more likely the problem.

**Closed as completed** 2021-02-04 14:06 UTC
Labels: No Code Attached Yet

**Comment by pranaymirchandani** [comment] 2021-02-06 04:58
- Article was was already in published state.
- Turned off URL rewriting in Global configuration and confirmed .htaccess file (its present) but the issue was that it was named as htaccess.txt so renamed it to .htaccess and this resolved the issue.

**Comment by richard67** [comment] 2021-02-06 10:50
>     * Turned off URL rewriting in Global configuration and confirmed .htaccess file (its present) but the issue was that it was named as htaccess.txt so renamed it to .htaccess and this resolved the issue.

@pranaymirchandani That's expected behavior. We can't just overwrite any present .htaccess (or in case of IIS web.config) file because it might already contain site-specific adjustments, so we provide a txt file which can be used without modifications, if there is no present file, or which can be used to compare with the present file and merge them together into one. It's done the same way with the robots.txt, where we ship a file robots.txt.dist in order not to overwrite a present file.

When you switch on URL rewriting, a small help text is shown, telling to rename the file:
![2021-02-06_01](https://user-images.githubusercontent.com/7413183/107116090-64ffa200-6871-11eb-9c8f-df412c0b5e67.png).

Maybe you have missed that text?
