### ISSUE TITLE
[3.9] com_contact icon settings are not available in the administrator contact form even thought they are defined

### ISSUE THREAD

**Issue by shoulders** [joomla/joomla-cms#31435] opened 2020-11-20 13:04 UTC
### Steps to reproduce the issue
create a new contact or edit a contact and you will find there are no options to define the different types of icons as you can in the component global options
![image](https://user-images.githubusercontent.com/319997/99802004-d52e3f80-2b2e-11eb-833e-a48345de04b7.png)

These icons parameters are defined in `administrator/models/forms/contact.xml` but are not rendered in the form to set icons on a per contact basis.

https://github.com/joomla/joomla-cms/blob/a5b37ed5b199b7489e9f91b35a47209947d41c02/administrator/components/com_contact/models/forms/contact.xml#L238-L296

### Expected result
If the options are defined in the **contact.xml** they should be rendered or the referenced should be removed.

### Actual result
These fields are not rendered but are referenced in the template.

### System information (as much as possible)

Setting | Value
-- | --
 
PHP Built On | Windows NT E6540 10.0 build 19041 (Windows 10) AMD64
Database Type | mysql
Database Version | 5.5.5-10.4.10-MariaDB
Database Collation | utf8mb4_unicode_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.3.12
Web Server | Apache/2.4.41 (Win64) OpenSSL/1.1.1c PHP/7.3.12
WebServer to PHP Interface | apache2handler
Joomla! Version | Joomla! 3.9.22 Stable [ Amani ] 6-October-2020 15:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0

### Additional comments
I had a quick look and it appears this issue is present in J4.x

**Comment by drmenzelit** [comment] 2020-11-20 13:08
What do you mean? Do you want to have different icons in each individual contact?

**Comment by shoulders** [comment] 2020-11-20 13:17
Do you want to have different icons in each individual contact? = this is what I am discussing.  😄 

I am not for or against this feature, it is just these input definitions are present and are not used.

so one of the following is required:

1. remove the unused definitions in `contact.xml` and just have the global options defined in the component.
2. correct the edit template to use these input fields

It is probably easier to remove the values in the `contact.xml` as I am not sure anyone has ever been able to use them on a per contact basis. However I would like to point you to the install.sql file which shows these options:

https://github.com/joomla/joomla-cms/blob/a5b37ed5b199b7489e9f91b35a47209947d41c02/installation/sql/mysql/joomla.sql#L503

As far as I know you dont have to define these options (i.e. `icon_fax`) in the `contact.xml` to be able to use the global option equivalent.

**Comment by Quy** [comment] 2021-06-07 15:09
@HLeithner Should #34418 be ported to J3? This is not a bug per se. If no, can this be closed?

**Comment by HLeithner** [comment] 2021-06-08 07:28
I would expect the fields would work they are not displayed in the backend. On the other side no one seems to miss them the last 10 years or so. 

I would keep them in 3.9, I'm not sure if we get any side effects removing them (don't think so) but they are already removed in #34418 so keep them in 3.x series and we are safe.

Closing this because it's solved in 4.0

**Closed as completed by HLeithner** 2021-06-08 07:28 UTC
Labels: No Code Attached Yet, Information Required
