### ISSUE TITLE
[4.0] Mobile toolbar button requires double touch to close

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#26543] opened 2019-10-11 09:14 UTC
### Steps to reproduce the issue
In the backend open articles list on a small screen. The toolbar toggle button requires 2 clicks to close. The first click attempts to open the already open toolbar.

**Comment by Quy** [comment] 2019-11-26 04:00
Is this a duplicate of #26771?

**Comment by Quy** [comment] 2020-01-15 14:11
Duplicate #27534

**Comment by ciar4n** [comment] 2020-01-15 14:26
This is a separate issue.

**Comment by brianteeman** [comment] 2020-02-06 23:11
confirmed the issue

**Comment by Subhang23** [comment] 2020-02-16 08:16
I think the following issue is not limited to only articles component but extends to wherever this type of toolbar exists.

**Comment by Subhang23** [comment] 2020-02-16 08:17
I think this issue can be solved by adding appropriate class names whenever the screen is loaded.

**Comment by Subhang23** [comment] 2020-02-16 08:17
I would like to work on this issue.

**Comment by alikon** [comment] 2020-02-16 08:37
thanks  @ Subhang23

**Comment by alikon** [comment] 2020-02-16 08:37
thanks @Subhang23

**Comment by Subhang23** [comment] 2020-02-17 06:05
Can you please review PR #27958 ?

**Closed as completed** 2020-02-18 09:31 UTC
Labels: No Code Attached Yet
