### ISSUE TITLE
Articles - more Category select

### ISSUE THREAD

**Issue by Ivan599** [joomla/joomla-cms#13982] opened 2017-02-08 22:50 UTC
### Steps to reproduce the issue
How select more Category in create article?

### Expected result
It's possible in joomla 3.7?

**Comment by Bakual** [comment] 2017-02-09 06:22
You mean selecting more than one category? No that is not possible. Use Tags instead if you need to group the articles by mutple keywords.

**Comment by jeckodevelopment** [comment] 2017-02-11 18:57
Closing since it's not a bug.

**Closed by jeckodevelopment** 2017-02-11 18:57 UTC
Labels: No Code Attached Yet
