### ISSUE TITLE
Updating Radio Type Custom Field Removes Selection from Article

### ISSUE THREAD

**Issue by SumCompanyInc** [joomla/joomla-cms#43453] opened 2024-05-09 15:43 UTC
### Steps to reproduce the issue

Create a Radio Type Custom Field, and add some options
In Article, Select an option from the Custom Field
Go Back to Custom Field and Update the Value of an existing custom field, that was chosen in the Article
Go Back to Article, and see that the Selection is now removed
Additional Test: Changing "Name" of option does not affect the Article.

Video Example: https://youtu.be/UZEk8wuhWW0

### Expected result

I would expect that changing a value in a custom field would not affect the article at all.

### Actual result

The article selected radio option has been removed, after the update to the custom field radio button value. i can verify also that changing the name of the option does not affect the article.

### System information (as much as possible)

attached the systeminfo text

**Comment by richard67** [comment] 2024-05-09 16:22
> attached the systeminfo text

@SumCompanyInc Where? If you tried to attach it in our issue tracker, it might have not worked. Please try directly on GitHub.

**Comment by SumCompanyInc** [comment] 2024-05-09 16:27
[systeminfo-2024-05-09T15_41_27+00_00.txt](https://github.com/joomla/joomla-cms/files/15264902/systeminfo-2024-05-09T15_41_27%2B00_00.txt)
you're right, i did try to upload, but failed.. im in github now..

**Comment by brianteeman** [comment] 2024-05-09 16:51
> I would expect that changing a value in a custom field would not affect the article at all.

I would not expect that

**Comment by chmst** [comment] 2024-05-20 08:36
This is correct and inteded. If you remove a value - how should it be displayed? Closing this as expected behaviour.

**Closed as completed by chmst** 2024-05-20 08:36 UTC
Labels: No Code Attached Yet

**Comment by brianteeman** [comment] 2024-05-20 12:37
In your case it might be just changing the value to fix a spelling error but it could also be to change a yes to a no. Thats why its the intended behaviour
