### ISSUE TITLE
User registration

### ISSUE THREAD

**Issue by JSWebdesign** [joomla/joomla-cms#44524] opened 2024-11-26 09:35 UTC
### Steps to reproduce the issue
go to users - manage
set allow user registration to Yes
do not make a login or registration menuitem
the url ?option=com_users&view=registration is active . Always

### Expected result
The registration url should only be active if there is a login menuitem made or registration menu item
### Actual result
The url is always active
### System information (as much as possible)
This problem occurs on Joomla 5 and many previous versions.

**Comment by brianteeman** [comment] 2024-11-26 09:49
This is working as intended. There are many ways to register on a site - some in core and others might be from an extension. An example would be the link in the login module.

If your intent was to disable registration completely then this should be done in the users component options

**Comment by brianteeman** [comment] 2024-11-26 15:56
you have a strange definition of annoying

anyway this should be closed as a cannot fix

**Comment by Hackwar** [comment] 2024-11-26 17:14
Joomla 5.2 contains a change to automatically redirect to the menu item if you create it. Besides that, this is indeed not something we will change. Because of that, I'm closing this.

**Closed as completed by Hackwar** 2024-11-26 17:14 UTC
Labels: No Code Attached Yet
