### ISSUE TITLE
Custom Fields not showing in Contact Form Joomla 3.7.Beta2

### ISSUE THREAD

**Issue by gwsdesk** [joomla/joomla-cms#14004] opened 2017-02-10 07:11 UTC
I am not able to get a custom field to show on the contact form for a single contact. 

* In global for com_contacts I have enabled "custom fields" and to show on "All" 
* The plugin "custom list" is enabled
* I create in the component a new field called "amount" (type list) 
* I create a Custom Field Group and assign the custom field to the group 
* Set field to show on both site & admin 
* Custom field shows up in admin at user "buyer" settings 
* Set in menu link to show all user custom groups

No custom firlds are showing on the contact form in com_contact

**Comment by AlexRed** [comment] 2017-02-10 07:12
I can confirm, no custom field to show on the contact form  :(<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14004">issues.joomla.org/tracker/joomla-cms/14004</a>.</sub>

**Comment by AlexRed** [comment] 2017-02-10 07:35
Also the User custom field don't appear in the user contact page, appear only the title "Fields" under the contact form.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14004">issues.joomla.org/tracker/joomla-cms/14004</a>.</sub>

**Comment by gwsdesk** [comment] 2017-02-10 07:57
> "User custom field don't appear in the user contact page, appear only the title "Fields" under the contact form"  

Confirmed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14004">issues.joomla.org/tracker/joomla-cms/14004</a>.</sub>

**Comment by Bakual** [comment] 2017-02-10 14:11
For the custom fields from the user, this one should fix it: https://github.com/joomla/joomla-cms/pull/13956

For the contacts, I already saw that and have some code. Just did not the PR yet.
Reason for the issue is that the contact mail form and the contact itself use the exact same context and we can't differentiate them. https://github.com/joomla/joomla-cms/compare/staging...Bakual:FixingContactFields?expand=1 is my approach. I just need to wrap it up so it's ready for a PR.

**Comment by Bakual** [comment] 2017-02-10 19:48
Can you please test https://github.com/joomla/joomla-cms/pull/14015 and https://github.com/joomla/joomla-cms/pull/13956 for the two issues mentioned here?

Closing as we have PRs.

**Closed by Bakual** 2017-02-10 19:48 UTC
Labels: No Code Attached Yet
