### ISSUE TITLE
Menu item ordering working erratic after 3.6.2

### ISSUE THREAD

**Issue by AnrietteC** [joomla/joomla-cms#11476] opened 2016-08-05 14:27 UTC
#### Steps to reproduce the issue
In Menu Manager, edit a menu's items. Click the Up/Down arrows to allow for ordering of menu items. Drag an item to below another item (of the same level, but with multiple sub-items).

#### Expected result
Simple order of other items should be kept that they were initially were in.

#### Actual result
Menu item ordering is jumbled and items are randomly outputting on the front-end and sometimes needs a menu rebuild to correct.

#### System information (as much as possible)
Joomla! 3.6.2 Stable [ Noether ] 4-August-2016 23:41 GMT
PHP 5.6.24-1~dotdeb+7.1
Joomla Platform 13.1.0
MySQL 5.5.49-0+deb7u1

**Comment by ggppdk** [comment] 2016-08-05 14:29
This is probably not new
How many menu items do you have ?

**Comment by AnrietteC** [comment] 2016-08-05 14:32
97 in this particular menu of which 3 are trashed.

Level 1: 15
Level 2: 56
Level 3: 3
Level 4: 5
Level 5: 18

**Comment by ggppdk** [comment] 2016-08-05 14:34
and total in all menus ?

**Comment by AnrietteC** [comment] 2016-08-05 14:36
264 menu items in total, scattered into 12 menu types.

**Comment by ggppdk** [comment] 2016-08-05 14:40
have you seen this:
https://github.com/joomla/joomla-cms/issues/4303

**Comment by AnrietteC** [comment] 2016-08-05 14:45
No, but I looked through the latest issues before posting and didn't see anything menu related. Maybe I missed that one.

**Comment by ggppdk** [comment] 2016-08-05 14:47
I mean is it the same issue ? 
Does it happen if you reorder the records fast ?

Are you sure it was not happening before ? (maybe it was happening more rarely ?)

**Comment by AnrietteC** [comment] 2016-08-05 14:49
It happens regardless of my speed. I thought maybe if I gave the scripts time to do their stuff in the background, but that didn't help as well.

No, it was not happening before, with 3.5.1. I only upgraded to 3.6.2 this week, after being on 3.5.1 for months.

**Comment by ggppdk** [comment] 2016-08-05 14:55
Yes the problem of #4303 should appear when having menu with thousands of records

**Comment by ggppdk** [comment] 2016-08-05 14:57
So this must something different

**Comment by AnrietteC** [comment] 2016-08-05 14:57
Well, I don't have thousands. 264 is about average I would guess. Plus 3.5.1 did not have the problem. Can you recreate this in your local environment?

**Comment by AnrietteC** [comment] 2016-08-05 15:01
It sort of has an order to it, I drag one item, with no sub-items anywhere in the same level. When I refresh the front-end, basically every other sub-item from other sibling items goes and sits below it that item I just ordered. The back-end ordering seems unaffected. Yet, the front-end looks totally random.

**Comment by DavidBoggitt** [comment] 2016-08-05 19:18
Have you tried the rebuild function in Menu Manager?  Is it the same in all browsers?

**Comment by mahagr** [comment] 2016-08-12 08:55
@AnrietteC Do you have any trashed menu items? If you display all the menu items, are the trashed menu items in wrong place, like in middle of inner level?

**Comment by mahagr** [comment] 2016-08-12 12:28
One of our customers had a site, which had issues with menu items behaving somewhat erratic and after looking into the database it looks like ordering was wrong for trashed menu items -- they had the same `lft` and `rgt` values as some other menu items. Rebuilding menu doesn't fix the issue and trying to delete those trashed items causes wrong menu items to be deleted along with the trashed items (likely because of conflicting `lft`). 

I have no idea why the ordering got broken in the first place (and I did try hard to reproduce it), but it seems that there's a bug in rebuilding menus which causes trashed items to be ignored.

**Comment by mahagr** [comment] 2016-08-12 12:44
I finally found out what causes the issue. If there is a (trashed) menu item which has non-existing parent, it will cause all kinds of weird issues. The menu item will be ignored when rebuilding menus and removing it will cause other menu items to disappear on delete as well.

There are some other erratic behaviours as well, like on save menu item can suddenly move to another location etc.

**Comment by mahagr** [comment] 2016-08-12 12:49
To recreate this issue, just take a clean install and trash one of the menu items. After that go edit the menu item from database and change its `parent_id=9999`. Then just rebuild menu and look into database again. Rebuild fixes `lft` and `rgt` from all the menu items except the one with bad parent.

**Comment by mahagr** [comment] 2016-08-12 13:03
@ggppdk I saw you have been working on the menu, so I will ping you just in case. Maybe your reordering pull request needs to be updated to take orphan menu items into account?

**Comment by ggppdk** [comment] 2016-08-12 13:07
My PR (which i need to redo or rebase) is about performance,

it does not modify the behaviour, so the fix for this must be a different PR !

**Comment by franz-wohlkoenig** [comment] 2017-04-06 08:01
@AnrietteC can you confirm this Issue on latest Staging?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11476">issues.joomla.org/tracker/joomla-cms/11476</a>.</sub>

**Comment by franz-wohlkoenig** [comment] 2017-05-27 10:03
This has been closed due to lack of response to the requests above – it can always be reopened in the future if it is updated.

**Closed** 2017-05-27 10:02 UTC
Labels: No Code Attached Yet
