### ISSUE TITLE
[4.0] Frontend search not working

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#19217] opened 2017-12-29 16:56 UTC
### Steps to reproduce the issue

install from 8256b0f8c2141e1014d6b58d3ad048b0853f0896 with sample data

go to frontend, enter a search term in the top right search box

### Expected result

search results

### Actual result

page reloads to where it was before - no search results

**Comment by ghost** [comment] 2017-12-29 16:58
Issue confirmed.
### System information
4.0.0-dev
Sample Data
macOS Sierra, 10.12.6
Firefox 57 (64-bit)
#### MAMP 4.2
- Apache-Server
- PHP 7.0.22
- MySQLi 5.6.35<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19217">issues.joomla.org/tracker/joomla-cms/19217</a>.</sub>

**Comment by C-Lodder** [comment] 2017-12-29 17:33
@PhilETaylor How are you installing sample data on a fresh install? I just get a console log error when I try to install it

**Comment by ghost** [comment] 2017-12-29 17:34
@C-Lodder i used Module in Backend, which don't stop correct, After reload of Site all was fine installed.

**Comment by PhilETaylor** [comment] 2017-12-29 17:35
I never installed it on the install, I installed it using the admin area after install - yes that seemed to error but I ignored that error and after page refresh tried again, and it said the data was already installed

Then I went to the frontend, top right of the home page and did a search for anything

**Comment by C-Lodder** [comment] 2017-12-29 17:44
Ok cheers.

Just taken a look at this and it only appears to be an issue when SEF is enabled.

**Comment by brianteeman** [comment] 2017-12-29 18:23
works fine for me :)

**Comment by PhilETaylor** [comment] 2017-12-29 18:24
Works with SEF off.

Doesnt work with SEF on.

**Comment by brianteeman** [comment] 2017-12-29 18:25
I have sef on

**Comment by PhilETaylor** [comment] 2017-12-29 18:29
try using the PHP built in server and SEF on:

cd  /path/to/joomla && php -S 0.0.0.0:8001

**Comment by C-Lodder** [comment] 2017-12-29 20:15
Definitely an issue. Perhaps something to do with DisplayControler.php 
I had a mess around with it but couldn't fix.

The `option` query is being added to the end of the URL, so maybe the router can't handle that properly.

**Comment by impressionestudio** [comment] 2018-02-05 17:35
I have the same problem after the update from 3.8.3 to 3.8.4. Many websites that were working fine, now show an error page "Page not found" or an empty of content page with header and footer but no results and no content.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19217">issues.joomla.org/tracker/joomla-cms/19217</a>.</sub>

**Comment by brianteeman** [comment] 2018-02-05 17:36
@impressionestudio this issue is for J4 and nothing to do with your issue

**Comment by impressionestudio** [comment] 2018-02-05 18:00
Ops, sorry. I was so frustrated and didn't notice it. Do you want me to delete the comments?

**Comment by Quy** [comment] 2018-05-20 23:51
It is working for me. Please confirm.

**Comment by Hackwar** [comment] 2018-05-21 08:32
It is working for me, too.

**Comment by ghost** [comment] 2018-05-21 09:06
Closed as Issue seems to be resolved elsewhere. Please reopen if necessary.

**Closed as completed** 2018-05-21 09:05 UTC
Labels: No Code Attached Yet, J4 Issue
