### ISSUE TITLE
Pre-Update Check Warning for Child Template of Cassiopeia - J! 4.2.9 => J! 4.3.0

### ISSUE THREAD

**Issue by imanickam** [joomla/joomla-cms#40459] opened 2023-04-23 06:53 UTC
### Steps to reproduce the issue

(a) Install Joomla! 4.2.9
(b) Log into the admin back-end
(c) Create a Child template of the template Cassiopeia
(d) Go to the screen "Joomla Update" (System => Update -> Joomla)
(e) In the section " Pre-Update Check for Joomla ‎4.3.0", click on Extensions (where thee warning sign is displayed)
(f) Notice that the child template of Cassiopeia is displayed in the warning list - "Joomla cannot detect the extension's compatibility with the target version of Joomla."

### Actual result
![screen shot 2023-04-23 at 06 40 14](https://issues.joomla.org/uploads/1/a9b6275c399cea494e9a5e3ecb6ba8e2.jpg)

### Additional comments
It is not clear whether this warning would be displayed for third party templates as well.  Probably this happens because of the missing _targetplatform_ tag.

**Comment by richard67** [comment] 2023-04-24 15:07
@imanickam I think the warning is ok in that case. It should not be shown for a core template (original). But when you crate a child template, the pre-update check can not know what kinds of modifications you have made in that child template. E.g. you could have copied the index.php from the parent and then have modified it, or you could have created layout overrides in that child template, and these overrides might not be compatible. The warning only says that there is no update information so you have to check your child template manually, it does not say that your child template is invalid.

"Missing update information" means that for an extension there is no update site, or the update site exists but does not provide any information.

As a child template of a core template (or in old times before child templates were invented: a copy of a core template) does not have an update site and so does not provide any update information for the pre-update checker. Such things always need to be checked manually, therefore I think the "Missing update information" is ok for those.

>  Probably this happens because of the missing targetplatform tag.

The targetplatform tag is checked in the update information when there is an update site, but it is not checked from any locally present manifest XML.

If you are ok with my explanations then please close this issue because it's expected behaviour, or tell me and I will do that.

If you are not ok with my explanations, then lets see if other opinions come in.

**Comment by imanickam** [comment] 2023-04-26 04:01
@richard67 Thanks for the explanation.  I will close the Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40459">issues.joomla.org/tracker/joomla-cms/40459</a>.</sub>

**Closed as completed** 2023-04-26 04:03 UTC
Labels: No Code Attached Yet, Information Required
