### ISSUE TITLE
The number of hits is calculated wrong.

### ISSUE THREAD

**Issue by ilya800918** [joomla/joomla-cms#40476] opened 2023-04-25 04:05 UTC
### Steps to reproduce the issue
After the update from joomla 2.5 to joomla 4, the number of hits is calculated wrong. 
I think this is a common issue as it has been discussed on the forums.

### Expected result
The real number of article views.

### Actual result
Now the number of hits has become approximately 10 times more. And I know that this is not true. 

### System information (as much as possible)
Joomla 4.2.9
Php 8.0

**Comment by ilya800918** [comment] 2023-04-25 16:35
I have updated Joomla a year ago. Everything works great. Apart from the fact that the number of views of materials is greatly inflated. I updated using the paid component Migrate Me Plus, and then up to Joomla 4, according to all the rules and recommendations.

Yes, I mean exactly the counter of the cms core.

The situation is such that if earlier the number of views was about 2K per article, now it is about 15-20K per article, while I know from the statistics of Awstats and Google that the real number of visitors has not increased. Perhaps now views are counted differently and the problem is because of this.

Unfortunately, I can't find the topic right now that talked about overestimating views. But I was able to find a few similar messages that are probably somewhat similar in meaning:

"Joomla 3.1.5

The statistics module is unrealistically lying. Today I saw how I supposedly had 290 guests at the same time. hits of articles are winding up just unbelievably. less than a week 2300 views. attendance 2-5 people per day. informer showed a maximum of 200 views per day. Just as unexpectedly, from 290 there were 140 guests, and then 1.
The counter is ticking right constantly, the number of views will soon be cosmic."

"Maybe I'm wrong, but the statistics of viewing articles counts not only real visitors, but also bots
Some kind of bot got into the habit of going to my page and leaving comments, I closed this shop, but the "Number of views" statistics are winding up Wow
And even with these bots you won't understand whether people are watching or bots are rummaging around
In general, how can this be changed? What would count only real visitors, real people with a real browser!
   +
Strange, no one was interested or...
In fact, bots wind up these statistics, the "Most read" module is then generally irrelevant, since it is not clear who is interested in the page, bots or real visitors.
Yes, and I myself want to see the real picture of the attendance of articles
"
I understand that the problem is not clearly defined. I have met the opinion that views can wind up browser bookmarks or the front panel of browsers, even loading icons or screenshots without actually visiting the pages by users. Or something like that.
If you think it's right, you can close the topic, but I would like to draw attention to this possible problem.

**Comment by richard67** [comment] 2023-04-26 13:10
There was one change made for the hits counter after Joomla 2.5: With Joomla 3.5.0, the hits counter has been fixed for enabled cache. See this pull request: #8887 . Maybe this explains why the counter counts faster now compared to 2.5?

Anyway, I can not really reproduce that the counter counts wrong. I have it enabled on my private website, also with cache enabled, and for me the hits counter works well.

**Comment by richard67** [comment] 2023-04-26 13:26
> > And I know that this is not true.
> 
> How?

@brianteeman Well, he could check the server logs. There he could even distinguish (more or less accurately) bots from normal users by the user agent. But I doubt he has done that, because if he had done that, he would provide that here as proof.

**Comment by ilya800918** [comment] 2023-04-27 04:14
> he could check the server logs

Thank you for the advice!
Now I have the latest article and more than 6000 views in the admin panel. I have selected all the strings from the log file and am attaching it here. I now saw the problem, but I do not know how to deal with it now.
[my-site-log.txt](https://github.com/joomla/joomla-cms/files/11339473/my-site-log.txt)

**Comment by ilya800918** [comment] 2023-04-28 17:39
Please promt me. This fact that Joomla records HEAD requests as hits, like this one, is it OK or not?
`Line 4875: 66.249.83.3 - - [02/Apr/2023:17:32:57 +0200] "HEAD /my-article-x HTTP/1.1" 200 0 "-" "FeedBurner/1.0 (http://www .FeedBurner.com)"`

**Comment by chmst** [comment] 2023-05-11 18:08
@zero-24 maybe this is  yor field of experience?

**Comment by zero-24** [comment] 2023-05-12 18:54
> @zero-24 maybe this is yor field of experience?

No its not but when looking into the code right now HEAD does not seem to be filtered: https://github.com/joomla/joomla-cms/blob/4.3-dev/components/com_content/src/Model/ArticleModel.php#L282-L302

Not sure why feedburner should call a normal page in the first place isnt that a RSS tool that should "just" call the RSS etc URLs?

**Comment by Hackwar** [comment] 2024-04-08 08:47
I created a PR. Please test #43231. Since we have a PR, I'm closing this issue.

**Closed as completed by Hackwar** 2024-04-08 08:47 UTC
Labels: Feature, No Code Attached Yet
