### ISSUE TITLE
Admin menu dropdown in Joomla! 3.6.0 RC1

### ISSUE THREAD

**Issue by viocassel** [joomla/joomla-cms#10972] opened 2016-06-29 21:39 UTC
Admin menu dropdown in Joomla! 3.5.1

![](http://image.prntscr.com/image/2a35594ce7044af586a84baa7954a361.png)

Admin menu dropdown in Joomla! 3.6.0 RC1

![](http://image.prntscr.com/image/98a39849fc55417ab44de113cb1ddea7.png)

This is a bug or a feature? :confused:

**Comment by brianteeman** [comment] 2016-06-29 21:43
I assume you refer to the missing pointer?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10972">issues.joomla.org/joomla-cms/10972</a>.</sub>

**Comment by viocassel** [comment] 2016-06-29 21:49
Yes. And dropdowns appear crooked.

![](http://image.prntscr.com/image/0688c7f7f75b4e01993756bff6e3df8b.png)

**Comment by brianteeman** [comment] 2016-06-29 21:54
Probably related to https://github.com/joomla/joomla-cms/pull/9375

On 29 June 2016 at 22:49, Vio Cassel <notifications@github.com> wrote:

> Yes. And dropdowns appear crooked.
>
>
> <https://camo.githubusercontent.com/65c853f6b87aeb80831d5c64052b81aaddfc0a83/687474703a2f2f696d6167652e70726e747363722e636f6d2f696d6167652f30363838633766376637356234653031393933373536626666366533646638622e706e67>
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/10972#issuecomment-229499676>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8SMU2fs6ex4HRjDxp-VQjeL-Es7eks5qQuhUgaJpZM4JBmAA>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by StefanSTS** [comment] 2016-06-30 08:37
For the difference in height for the second ul: There is a margin: 2px 0 0; on .dropdown-menu. This causes the submenu to move down 2px while the first dropdown has that overridden in .navbar .nav > li ul with margin: 0;.
Suggested solution would be to remove the 2px top margin on .dropdown-menu.

**Comment by brianteeman** [comment] 2016-06-30 12:05
@joomlic could you take a look please<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10972">issues.joomla.org/joomla-cms/10972</a>.</sub>

**Comment by RonakParmar** [comment] 2016-07-01 06:24
I have checked in Joomla 3.5.1 and latest Joomla Staging branch and I am able to reproduce this issue.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10972">issues.joomla.org/joomla-cms/10972</a>.</sub>

**Comment by RonakParmar** [comment] 2016-07-01 12:18
I have changes administrator template to "hathor" and menu selection is working fine in this template, but having issue in "isis" template.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10972">issues.joomla.org/joomla-cms/10972</a>.</sub>

**Comment by kalpesh681** [comment] 2016-07-01 12:30
I am able to reproduce same issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10972">issues.joomla.org/joomla-cms/10972</a>.</sub>

**Comment by JoomliC** [comment] 2016-07-01 17:01
@brianteeman i don't know exactly why you request me here to have a look... maybe you meant @C-Lodder  ;-)

I have checked a bit, and you're right, issue is related to #9375
The missing pointer is due to the overflow set to the all container (ul) : https://github.com/joomla/joomla-cms/pull/9375/files#diff-92bd4bc9fc868397bd2dcf5f303c0ec4R7160
And the extra margin at top of sub menu : https://github.com/joomla/joomla-cms/pull/9872/files#diff-6337832bd45e0f9af1521049cb78e03eR77 (a PR which was supposed to fix the 2 issues here already reported here : https://github.com/joomla/joomla-cms/issues/9841 )
Here, i wonder why <code>+5</code> (if set to 8, it's ok for sub menu top placement, but i don't think using value inside the script will be consistent in the future...) or <code>-13</code> in script template.js ?

As no PR yet, i have created one #10987 (@StefanSTS you fix proposal for missing pointer is the right one! :+1: )
@C-Lodder could check this PR too ;-)

Thanks!

**Comment by brianteeman** [comment] 2016-07-01 17:08
Please test #10987 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10972">issues.joomla.org/joomla-cms/10972</a>.</sub>

**Comment by brianteeman** [comment] 2016-07-03 06:59
Closed as we have a PR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10972">issues.joomla.org/joomla-cms/10972</a>.</sub>

**Closed** 2016-07-03 06:59 UTC
Labels: No Code Attached Yet
