### ISSUE TITLE
i should change date and time with calendar in jalali calendar (Persian language)

### ISSUE THREAD

**Issue by ghasemy50** [joomla/joomla-cms#16886] opened 2017-06-27 20:37 UTC
### Steps to reproduce the issue
hi
there is a problem in last editing of joomla 3.7.3
if you change date from field ( not use calendar ) , date and time convert to now date.
for example , if date field was equal to: 1396-04-04 20:40:00 and i update text to anything after save date convert to: 1396-04-07 01:04:00 that is time of now.
but if i change it from calendar it's work fine.

### Expected result
if change text of date it's not work correctly

### Actual result
work currectly

### System information (as much as possible)
On Website:
PHP Built On Linux linux3.centraldnserver.com 3.10.0-614.10.2.lve1.4.50.el7.x86_64 #1 SMP Mon May 22 16:28:14 EDT 2017 x86_64
Database Version 10.1.22-MariaDB-cll-lve
Database Collation utf8_general_ci
Database Connection Collation utf8mb4_general_ci
PHP Version 5.5.38
Web Server Apache
WebServer to PHP Interface litespeed
Joomla! Version Joomla! 3.7.2 Stable [ Amani ] 22-May-2017 09:46 GMT
Joomla! Platform Version Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent Mozilla/5.0 (Windows NT 10.0; rv:54.0) Gecko/20100101 Firefox/54.0

On localhost:
PHP Built On Windows NT DESKTOP-6J51U5V 6.2 build 9200 (Windows 8 Business Edition) i586
Database Version 5.6.17
Database Collation latin1_swedish_ci
Database Connection Collation utf8mb4_general_ci
PHP Version 5.5.12
Web Server Apache/2.4.9 (Win32) PHP/5.5.12
WebServer to PHP Interface apache2handler
Joomla! Version Joomla! 3.7.2 Stable [ Amani ] 22-May-2017 09:46 GMT
Joomla! Platform Version Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent Mozilla/5.0 (Windows NT 10.0; rv:54.0) Gecko/20100101 Firefox/54.0

**Comment by franz-wohlkoenig** [comment] 2017-06-28 04:20
can you please test #16794?

**Comment by richard67** [comment] 2017-06-28 05:43
Seems this is a duplicate to #16590 , which is solved by #16794 , which is already merged , so the problem is solved in staging. @ghasemy50 please check and close this issue if duplicate.

**Comment by ghasemy50** [comment] 2017-06-28 16:50
Hi 
No it's new problem and tested on  yesterday's edit of joomla 3.7.3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16886">issues.joomla.org/tracker/joomla-cms/16886</a>.</sub>

**Comment by ghasemy50** [comment] 2017-06-28 16:50
Hi 
No it's new problem and tested on  yesterday's edit of joomla 3.7.3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16886">issues.joomla.org/tracker/joomla-cms/16886</a>.</sub>

**Comment by ghasemy50** [comment] 2017-06-28 16:54
This problem is same with this comment on #16794 :

I have test joomla 3.7.3 RC!
problem for select date by popup calendar fix and not reset but after set manual time and date and save it, time and date reset to today.

**Comment by Quy** [comment] 2017-06-28 20:44
Duplicate #16179 ?

**Comment by ghasemy50** [comment] 2017-06-28 21:01
@Quy 
yes but it's not solved in 3.7.3 last edit.
thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16886">issues.joomla.org/tracker/joomla-cms/16886</a>.</sub>

**Comment by ghasemy50** [comment] 2017-06-28 22:02
@Quy
but in 3.7.3 version if also i change date , date and time set to today and now.
thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16886">issues.joomla.org/tracker/joomla-cms/16886</a>.</sub>

**Comment by Quy** [comment] 2017-06-28 22:07
I understand it is not fixed yet, however, I assume it is the same issue as the other report.

**Comment by Quy** [comment] 2017-06-28 22:24
@ghasemy50 Please answer this question here:
https://github.com/joomla/joomla-cms/pull/16794#issuecomment-311725618

**Comment by franz-wohlkoenig** [comment] 2017-06-29 04:24
closed as duplicate Report of #16179 

Thanks for Hint, @Quy <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16886">issues.joomla.org/tracker/joomla-cms/16886</a>.</sub>

**Closed by franz-wohlkoenig** 2017-06-29 04:24 UTC
Labels: No Code Attached Yet
