### ISSUE TITLE
J3.4. Fatal error: Class FOFModelFieldNumber contains 2 abstract methods

### ISSUE THREAD

**Issue by michaelmullan** [joomla/joomla-cms#6191] opened 2015-02-26 00:25 UTC
#### Steps to reproduce the issue
When installing j3.4 update could not access admin panel.

#### Expected result
Admin panel access

#### Actual result

Fatal error: Class FOFModelFieldNumber contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (FOFModelField::range, FOFModelField::modulo) in C:\HostingSpaces\virus\dairyscience.info\wwwroot\libraries\fof\model\field\number.php on line 130

#### System information (as much as possible)

I was running J3.3.6 on a commercial windows hosting package. I also use RS-Firewall extension to protect admin loginin.

#### Additional comments
I tried to insert abstract in as many places as I could in number.php. Still got error.

I can use administrator/index.php?option=com_NAME to access componets so can still work on site
Regards

**Comment by PhilETaylor** [comment] 2015-02-26 00:48
Paging @nikosdion :)

**Comment by michaelmullan** [comment] 2015-02-26 00:51
Hello @nikosdion :)

I am not sure how to respond. Not an expert!

**Comment by nikosdion** [comment] 2015-02-26 07:18
What is your exact PHP version number?

**Comment by nikosdion** [comment] 2015-02-26 07:31
Actually... hold on a minute! The FOFModelFieldNumber class has *already defined* the range and modulo methods, see https://github.com/joomla/joomla-cms/blob/staging/libraries/fof/model/field/number.php#L144

So, this means that you have one of two non-Joomla-related issues:

* Some files were not written on disk when upgrading your site, or your upgrade failed with an error about unwritable files.
* You have manually replaced files inside the site's libraries/fof directory or a badly written third party extension did.
* If the file libraries/fof/model/field/number.php contents on your site match the link I gave you above then your server has a code cache which screws you up. Please ask your host to clear the code cache OR disable it. Please note that if you have a code cache you are advised to disable it before updating Joomla! or any of its extensions and clear and enable it after the updates are complete.

Since this is not a Joomla! issue I'd propose to close it.

**Comment by michaelmullan** [comment] 2015-02-26 21:30
Thank you

**Comment by Bakual** [comment] 2015-02-26 21:37
Closing this issue as per comment from Nicholas.

@michaelmullan If it turns out the issue isn't coming from your installation, please request to reopen it or just open a new issue.

**Closed by Bakual** 2015-02-26 21:37 UTC

**Comment by michaelmullan** [comment] 2015-02-26 21:40
Thank you

 

I changed the class heading to abstract class headings and now everything works. So it may still be a J3.4 issue.

 

Thanks for the rapid response

 

Mike

**Comment by alijen** [comment] 2015-04-22 23:14
@michaelmullan not a programmer here, what is the exact script you used and did you write on the line you are getting the error on or elsewhere?

**Comment by michaelmullan** [comment] 2015-04-22 23:28
This matter has been fully resolved.

 

I am not a professional  PHP coder so cant comment further.

 

MM
