### ISSUE TITLE
Install from Web not formatted correctly in Joomla 3.7.0

### ISSUE THREAD

**Issue by AlexRed** [joomla/joomla-cms#13383] opened 2016-12-27 16:51 UTC
### Steps to reproduce the issue
activate the installa from web and see if is correctly formatted

### Expected result
![http://alexred.com/joomla/install-365.png](http://alexred.com/joomla/install-365.png "http://alexred.com/joomla/install-365.png")

### Actual result
![http://alexred.com/joomla/install-from-web-370.png](http://alexred.com/joomla/install-from-web-370.png "http://alexred.com/joomla/install-from-web-370.png")

**Comment by Bakual** [comment] 2016-12-27 18:29
There is already a ticket open for that, but it's a good example from Core.

Closing as duplicate of https://github.com/joomla/joomla-cms/issues/13349

**Closed by Bakual** 2016-12-27 18:29 UTC
Labels: No Code Attached Yet
