### ISSUE TITLE
Not logged out in backend

### ISSUE THREAD

**Issue by w13ear** [joomla/joomla-cms#42842] opened 2024-02-20 17:09 UTC
### Steps to reproduce the issue
Login in the backend of any Joomla website.
Confirm the time duration of any session
Visit the page system - templates - any template 
Open any css or js file
Wait twice the time duration before going to any other page

### Expected result
The expected result is that you should have been logged off from the backend

### Actual result
Your account is still active in the backend after the time duration of your session has been reached

**Comment by brianteeman** [comment] 2024-02-20 18:32
@w13ear The session does not end after x minutes and you are not logged out after x minutes. 

What does happen is that the session does end after x minutes of inactivity. However it is not possible to determine activity when you are inside an editor and we wouldnt want you to be logged out in the middle of writing an article or editing a template. So on those pages an additi9onal script runs to keepalive the session.

So on a list type page you will be logged out after x minutes of inactivity but on an edit type page you will not be as the script is keeping alive the session.

Hope that explains things.

**Comment by joomdonation** [comment] 2024-02-24 09:03
Closing this issue because this is expected behavior as @brianteeman explained above.

**Closed as completed by joomdonation** 2024-02-24 09:03 UTC
Labels: No Code Attached Yet, Information Required
