### ISSUE TITLE
Admin Logo and Profile dropdown list is disabled on edit screen of plugin,article,module in backend.

### ISSUE THREAD

**Issue by rbsl-ravi** [joomla/joomla-cms#5989] opened 2015-02-06 07:00 UTC
#### Steps to reproduce the issue
#1. Open a Plugin/Article/Category/Module.
#2. Admin Logo and Profile dropdown list is disabled.

#### Expected result
Admin Logo and dropdown list should be enabled for navigation if required.

#### System information (as much as possible)
Ubuntu 14.04.1
PHP 5.5.9
MySQL 5.5.41

#### Additional comments
![screen shot 2015-02-06 at 00 59 34](http://issues.joomla.org/uploads/1/42cbf2f052163e4c5f067d5e5325d09d.png)

**Comment by Bakual** [comment] 2015-02-06 07:19
That was changed intentionally with https://github.com/joomla/joomla-cms/pull/4694.

Closing as working as intended.

**Closed by Bakual** 2015-02-06 07:19 UTC
