### ISSUE TITLE
An error has occurred after installing non compatible with Joomla! 4 component

### ISSUE THREAD

**Issue by szoupi** [joomla/joomla-cms#32733] opened 2021-03-18 14:46 UTC
### Steps to reproduce the issue
Try to install a Joomla! 3.x component. In this case gantry5 framework joomla-pkg_gantry5_v5.4.36.zip through System > Extension install

### Expected result
The action should be forbidden. Message should appear and user should be redirected to back to previous state.

### Actual result
- Installation is interrupted. Message appears:
An error has occurred.
0 Call to undefined method Joomla\CMS\Application\AdministratorApplication::isAdmin() 

-Backend of Joomla! 4 is broken. Only sidebar and menu links are working. Front end is broken too. No content only menu links and the same as above error message is displayed.

### System information (as much as possible)
- ubuntu 18.04 LTS
- apache
- php 7.3

### Additional comments
![screen shot 2021-03-18 at 14 46 11](https://issues.joomla.org/uploads/1/81beaac064687c9490375295421e65af.png)

**Comment by ReLater** [comment] 2021-03-18 14:54
> The action should be forbidden. Message should appear and user should be redirected to back to previous state.

How should Joomla know if an extension isn't compatible? It's the job of the programmers to protect users from such disasters.. That can be easily managed by installer scripts and /or update manifests. And/or your job to make an backup first.

Just because an extension is not explicitly marked as "Joomla 4 compatible" that doesn't mean that it is not compatible.

**Comment by ChristineWk** [comment] 2021-03-18 15:22
See also: #31825  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32733">issues.joomla.org/tracker/joomla-cms/32733</a>.</sub>

**Comment by szoupi** [comment] 2021-03-18 16:11
> Just because an extension is not explicitly marked as "Joomla 4 compatible" that doesn't mean that it is not compatible.

I tested with a component that that was written and tested for J3x. The component's programmers cannot be held responsible for future versions of Joomla! code, the code of which are unaware of, it is impossible. I suggest that installation process should not start if minimum requirements are not met, eg explicit J4 compatibility  or whatever, otherwise accidentally J3.x component installation could have disastrous results. 

Taking backups is out of question, the current issue is how to offer an error-proof installation process without the need to use a backup. 

The #31825 addresses the issue

**Comment by jwaisner** [comment] 2021-03-18 16:40
Closing this as #31825 defines the changes that can be recommended to ensure compatibility with J4, but not a bug.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32733">issues.joomla.org/tracker/joomla-cms/32733</a>.</sub>

**Closed as completed** 2021-03-18 16:40 UTC
Labels: No Code Attached Yet

**Comment by ReLater** [comment] 2021-03-18 21:25
> The component's programmers cannot be held responsible for future versions of Joomla! code, the code of which are unaware of, it is impossible.

They are responsible. Joomla 4 can be tested for years.. And as I've said it's not too difficult to block installation on Joomla 4 in an extension. 10 additional lines of code. OR TO MARK THE EXTENSION ACCORDINGLY on download pages which is not the case with Gantry 5.
