### ISSUE TITLE
Changing category layout in menu options tab

### ISSUE THREAD

**Issue by BrainforgeUK** [joomla/joomla-cms#35005] opened 2021-07-31 16:10 UTC
### Steps to reproduce the issue

Create category.
Selecting different category layouts (from template _html/com-content/category_) works as expected.

Create a category list menu item for that category.
The previously selected category layout displays correctly.

What does **Choose a layout** in the **options** tab do?
It lists article layouts from template _html/com-content/article_
When menu item used in front-end I cannot see anywhere that the selected article layout is used.

It looks like _article_layout_ is only used in _view/article_ not in _view/category_ - which is what I would expect, so at this point it looks to me like a 'do nothing option'.

### Expected result

**Choose a layout** in **options** tab lists category layouts from template html/com-content/category

I would expect this to provide a method to override the selected category layout.
I.E. could have 2 menu items with different layout / stylings for the same category article list.

### Actual result

**Choose a layout** in **options** tab lists article layouts from template html/com-content/article

### System information (as much as possible)

Joomla 4 RC5
PHP 7.4

### Additional comments

Suggestions
(a) Simplest - remove **Choose a layout** from the **options** tab _(category/default.xml)_.
(b) Change it so that it enables the site dev / admin to override the chosen layout for that category.

**Comment by brianteeman** [comment] 2024-08-06 21:56
> What does Choose a layout in the options tab do?
> It lists article layouts from template html/com-content/article
> When menu item used in front-end I cannot see anywhere that the selected article layout is used.
> It looks like article_layout is only used in view/article not in view/category - which is what I would expect, so at this point it looks to me like a 'do nothing option'.

The layout option is in the tab labelled Options and the option has a description "layout for items"
![image](https://github.com/user-attachments/assets/8538ec91-cfed-4fb4-a71b-21523d20151c)

You are correct that the layout is for the display of any article accessed via this menu item. It works correctly as shown in the screen recording below. The one time that you may not see the article layout being used is when the article can also be accessed by another menu item. In that scenario the menu item with the lowest id will take precedence and so you may not see the selected layout. If you only have one menu item pointing to an article (as you should do) then it works correctly as intended.


https://github.com/user-attachments/assets/d3b671dd-780b-4171-a503-7fd42c272f4b




This should be closed as the option works correctly as intended and there is nothing to fix

**Closed as completed** 2024-08-06 22:10 UTC
Labels: No Code Attached Yet, bug
