### ISSUE TITLE
Time Zone changes when calling Jdatabase query

### ISSUE THREAD

**Issue by pdoolz** [joomla/joomla-cms#8958] opened 2016-01-21 20:04 UTC
#### Steps to reproduce the issue
I was trying to find which of the queries in my component are slowing my site down.  So I echoed out some time checkpoints and look what happens:
Line 64 Debug point 1: 08:41:19
Line 92 Debug point 2: 08:41:19
Line 118 Debug point 3: 08:41:19
Line 122 Debug point 4: 12:41:19
Line 126 Debug point 5: 12:41:19

It did not take 4 hours to run from point 3 to point 4.  This is the code:
118		echo "<p>Line ".__LINE__." Debug point ".$tz++.": ".date("H:i:s")."</p>";
119			$db->setQuery($query1);
120			//$db->execute();
121			$cats = $db->loadAssocList();
122		echo "<p>Line ".__LINE__." Debug point ".$tz++.": ".date("H:i:s")."</p>";

To reproduce the issue:
1) Set a timezone other than whatever your server default is (I can't change my host's timezone)
date_default_timezone_set('Pacific/Auckland');

2) run some kind of query using jdatabase
$db		 = JFactory::getDbo(); // Get a db connection.
echo "<p>Line ".__LINE__." Debug point ".$tz++.": ".date("H:i:s")."</p>"; //Time in your TimeZone
$db->setQuery("select * from table limit 1");
$cats = $db->loadAssocList();
echo "<p>Line ".__LINE__." Debug point ".$tz++.": ".date("H:i:s")."</p>"; // Time in Server TimeZone

#### Expected result
Line 64 Debug point 1: 08:41:19
Line 92 Debug point 2: 08:41:19
Line 118 Debug point 3: 08:41:19
Line 122 Debug point 4: 08:41:19
Line 126 Debug point 5: 08:41:19

#### Actual result
Line 64 Debug point 1: 08:41:19
Line 92 Debug point 2: 08:41:19
Line 118 Debug point 3: 08:41:19
Line 122 Debug point 4: 12:41:19
Line 126 Debug point 5: 12:41:19

#### System information (as much as possible)
Latest Joomla version
Running on LAMP on GoDaddy hosted service

#### Additional comments
This code runs in the component's root php file
defined('_JEXEC') or die;
date_default_timezone_set('Pacific/Auckland');
$controller = JControllerLegacy::getInstance('DStore');
$controller->execute(JFactory::getApplication()->input->get('task'));
$controller->redirect();

Also the Timezone set in Joomla Configuration is
public $offset = 'Pacific/Auckland';

**Comment by fruppel** [comment] 2016-01-27 19:23
echo date("H:i:s"); echo "<br />";
		date_default_timezone_set('Pacific/Auckland');
		echo date("H:i:s"); echo "<br />";
		$db = JFactory::getDbo();
		echo date("H:i:s"); echo "<br />";
		$db->setQuery("select * from #__content limit 1");
		$cats = $db->loadAssocList();
		echo date("H:i:s"); echo "<br />";

Result:

20:22:23
08:22:23
08:22:23
08:22:23

Can't confirm that JDatabase changes timezone

**Comment by brianteeman** [comment] 2016-01-28 10:08
@pdoolz can you test the code above from @fruppel please - do you still have an issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8958">issues.joomla.org/joomla-cms/8958</a>.</sub>

**Comment by musinik** [comment] 2016-01-30 21:05
I have the same problems.
I also tried to change the date directly in MySQL, what actually doesn't work also.
It looks like Joomla resets the timezone each query.
===

$db->execute( "SET time_zone = '**Europe/Moscow**';"); // server normally accepts this. Checked in MySQL server directly. Time changes.
$db->setQuery("SELECT @@global.time_zone, @@session.time_zone;");
$db->execute();
$rows=$db->loadAssocList();
echo json_encode($rows);

**Result:**
[{"@@global.time_zone":"SYSTEM","@@session.time_zone":"**SYSTEM**"}]

Notes: SYSTEM timezone is other than 'Europe/Moscow'.
===
Joomla! 3.4.5 Stable [ Ember ] 22-October-2015 21:30 GMT <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8958">issues.joomla.org/joomla-cms/8958</a>.</sub>

**Comment by Fedik** [comment] 2016-01-30 22:30
I think it is caused by JDate behavior, JDate caches the date objects (by date key), and if at some point of time was requested cached date, but with different timezone, then cached object changes to requested timezone, and you get result exactly as you described

**Comment by mbabker** [comment] 2016-01-30 22:36
JDate itself isn't caching anything.  JFactory::getDate() does cache by the
time string plus timezone and always returns a clone.

**Comment by Fedik** [comment] 2016-01-31 09:49
sorry, ignore whole my message,
@mbabker  is right.

**Comment by Fedik** [comment] 2016-01-31 11:28
in theory, for fix it, need to add `__clone()` to the `JDate`:
```php
function __clone()
{
  $tz = clone $this->tz;
  $this->setTimezone($tz);
}
```

**Comment by musinik** [comment] 2016-01-31 12:09
Just in case, a workaround I used by now is taking the timezone from user
(or config) and bussing it as a variable to the stored procedure which
executes set time zone and makes a select.

воскресенье, 31 января 2016 г. пользователь Fedir Zinchuk написал:

> in theory, for fix it, need to add __clone() to the JDate:
>
> function __clone(){  $tz = clone $this->tz;  $this->setTimezone($tz);}
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/8958#issuecomment-177471149>.
>


-- 

*С уважением, Ключко Никита*

**Comment by Devportobello** [comment] 2016-02-08 16:56
Just tested something and dunno if this is related.
Maybe i'm missing something but both constructor(JDate and Datetime) dont return same result with a timezone given;

To demonstrate, use this:
```php
$d1 = new JDate('2016/08/02 16:30:00',new DateTimeZone('Europe/Paris'));
$d2 = new DateTime('2016/08/02 16:30:00',new DateTimeZone('Europe/Paris'));
echo '<pre>'.$d1->format('d/m/Y H:i:s (e)').'</pre><pre>'.$d2->format('d/m/Y H:i:s (e)').'</pre>';
```
```
02/08/2016 14:30:00 (GMT)
02/08/2016 16:30:00 (Europe/Paris)
```

**Comment by mbabker** [comment] 2016-05-08 19:17
`JDate` is a quirky beast and the `format()` method default signature goes against the parent `DateTime` object.  By default it formats dates to GMT and you have to pass a second parameter to get the date converted to the "local" timezone (so `$d1->format('d/m/Y H:i:s (e)', true);` should give you the date in the right timezone).

**Comment by Devportobello** [comment] 2016-05-09 07:47
Thx for explanation @mbabker , i missed this param...

**Comment by brianteeman** [comment] 2016-05-09 07:57
Can we close this?

**Comment by mbabker** [comment] 2016-05-09 11:56
I'd say yes as it's expected behavior (debatable whether it's correct depending on who you ask).  The JDate [constructor changes the system timezone](https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/date/date.php#L105) to UTC and it is recommended to use the JDate class for date/time operations in the CMS environment instead of the procedural date functions or the DateTime class (the main thing JDate offers is a standardized timezone for date/time values and translatability of the strings that come with it).

**Comment by brianteeman** [comment] 2016-05-09 14:41
Closed as expected behaviour<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8958">issues.joomla.org/joomla-cms/8958</a>.</sub>

**Closed by brianteeman** 2016-05-09 14:41 UTC
Labels: No Code Attached Yet

**Comment by max-payne-7** [comment] 2016-11-29 16:50
Hi,

Could somebody please test the code below and let me know why the dates returned are different ?

`
$mainframe = \JFactory::getApplication();
date_default_timezone_set($mainframe->getCfg('offset'));

print_r(date('Y-m-d H:i:s'));
\JDatabase::getInstance();
print_r(date('Y-m-d H:i:s'));
`
Thanks!

**Comment by mbabker** [comment] 2016-11-29 17:01
1) No part of the database API touches the system timezone (either read or write), so if the date is getting changed then there is something else not part of Joomla core making the change.

2) All places in Joomla core which do change the system timezone immediately reset that value.  The changes are done to standardize time operations to UTC (or a user configured timezone when converting values).  So at the worst the timezone has changed for 3 or 4 lines of code which don't even have an integration point to hook into.

3) The database API does log statements.  When the logger API creates a `JLogEntry` object, it creates a new `JDate` object.  As explained earlier, the `JDate` constructor does change the system timezone to create an object standardized on the UTC timezone.  But also immediately resets the timezone.  It does this by creating a `DateTimeZone` object based on the default system timezone via `date_default_timezone_get()`, however, this function call also has error suppression in front of it.  So if the `date_default_timezone_get()` call fails, the system timezone won't be known and the time can't be correctly reset.  This is indicative of a PHP configuration error on your local platform.
