### ISSUE TITLE
Articles not unlocked under Chrome

### ISSUE THREAD

**Issue by PascalNetenvie** [joomla/joomla-cms#8042] opened 2015-10-09 15:42 UTC
#### Steps to reproduce the issue
Open an article
Close it or save and close it
Click on his title to open it again

#### Expected result
Access the article

#### Actual result
Error saying :
You're not autorized to use this link to access this page (translated from french)
Error occur only on Google Chrome (last version under Win7 and Mac OS).

#### System information (as much as possible)
Joomla 3.4.4 under php 5.4.45-0+deb7u1

**Comment by n9iels** [comment] 2015-10-09 17:26
I can't reproduce the problem at this moment. But I have the same problem quite often on different website with different hosts. No idea under which circumstances this happens

**Comment by vdespa** [comment] 2015-10-24 08:11
I cannot reproduce it as well.

As far as I understand this is a Chrome error that occurs. Can you confirm?

- Can you please test on different hosts / different Joomla installations with your Chrome?
- Do you get the error in Incognito Mode (in Chrome)?
- Do you get the error on a new Joomla installation?

Please try to provide additional information to narrow the problem.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8042">issues.joomla.org/joomla-cms/8042</a>.</sub>

**Comment by PascalNetenvie** [comment] 2015-10-26 16:19
Yes it occurs only on Chrome (on different OS).
The website Have been created on Joomla 3.2 if  i remember well then was upgraded to 3.4.

**Comment by Bakual** [comment] 2015-10-26 16:35
Some technical background in case it helps:
When you edit an article, you click on an URL like this:
`index.php?option=com_content&task=article.edit&id=75`
This sets some session states variables and then redirects to this URL using a HTTP 303 (See Other) redirect:
`index.php?option=com_content&view=article&layout=edit&id=75`

Now maybe Chrome tries to be clever and directly calls this URL instead of the one with the `task`, because it already knows that there will be a redirect?

**Comment by PascalNetenvie** [comment] 2015-10-26 16:37
Also there is some third party plugin (Nonumber, JCE) that i use on numerous other websites.
I've tested on another website and i have same problem.

I made more tests and if i click on title it don't work (first with the error message then with no more message).
But if i check the article then click on edit button it work !

I tried to disable all 3rd party system and content plugins and problem remains.

**Comment by PascalNetenvie** [comment] 2015-10-26 16:44
I just tested in incognito mode and the problem still there.
But as said it work if if i check article and use edit button.

**Comment by brianteeman** [comment] 2015-10-26 16:55
There is no version of chrome called latest. Which exact version are you
using

**Comment by ataki0** [comment] 2015-11-26 16:01
I got the same error with Chrome Version 46.0.2490.86 m.

When I open an article with the direct link, close it and reopen it, it gives me an error: "You are not permitted to use that link to directly access that page (#101)." 

I can use the Edit button, but the direct link doesn't work.

I didn't have this problem with Firefox.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8042">issues.joomla.org/joomla-cms/8042</a>.</sub>

**Comment by ataki0** [comment] 2015-11-26 16:03
It give me the error with Joomla 3.4.5.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8042">issues.joomla.org/joomla-cms/8042</a>.</sub>

**Comment by PascalNetenvie** [comment] 2015-11-26 16:49
I still get this error.
Chrome Version 46.0.2490.86 m<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8042">issues.joomla.org/joomla-cms/8042</a>.</sub>

**Comment by bertmert** [comment] 2015-11-27 09:30
I'm working a lot with Chrome and Joomla backend for a longer time now. Saw many versions of both.
.
I can't confirm this issue.

Windows 7, Windows XP, Linux.

**Comment by brianteeman** [comment] 2015-11-27 10:09
I use google chrome exclusively on mac using Joomla all day and everyday

Your problem is either something you are doing wrong or something unique to
your installation of joomla (perhaps a plugin)

If it really was an issue with chrome not working with joomla then we would
have had a considerable volume of reports not just one

On 27 November 2015 at 09:30, bertmert <notifications@github.com> wrote:

> I'm working a lot with Chrome and Joomla backend for a longer time now.
> Saw many versions of both.
> .
> I can't confirm this issue.
>
> Windows 7, Windows XP, Linux.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/8042#issuecomment-160090238>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by ataki0** [comment] 2015-11-27 14:31
It seems to be related with the SSL encryption. If I use the http, it works very well.

It must be a bug with Chrome on Windows.

Thanks


Jonathan Dagenais
Intégrateur Web / Web integrator
jdagenais@duchesnay.com<mailto:jdagenais@duchesnay.com>

[cid:image001.gif@01CCDB7A.23E44FC0]

950 boul. Michèle-Bohec, Blainville QC  Canada J7C 5E2
Tél. Tel.: + 1 450 433-7734/1 877 833-7734 # 152
www.duchesnay.com<http://www.duchesnay.com/>

L'information transmise par ce courriel est destinée à l'usage du destinataire ci-dessus. Il est donc strictement interdit d'utiliser cette information, de la copier, de la distribuer ou de la divulguer.  Si cette communication vous a été transmise par erreur, veuillez la détruire et nous en aviser immédiatement par courriel.

This information is directed in confidence solely to the person above and may not otherwise be distributed, copied or disclosed.  Therefore, this information should be considered strictly confidential.  If you have received this email in error, please notify the sender immediately via a return e-mail for further direction.

P Pensez à l'environnement avant d'imprimer ce courriel.  Think of the environment before printing this e-mail.



De : Brian Teeman [mailto:notifications@github.com]
Envoyé : 27 novembre 2015 05:11
À : joomla/joomla-cms <joomla-cms@noreply.github.com>
Cc : Jonathan Dagenais <jdagenais@DUCHESNAY.COM>
Objet : Re: [joomla-cms] Articles not unlocked under Chrome (#8042)

I use google chrome exclusively on mac using Joomla all day and everyday

Your problem is either something you are doing wrong or something unique to
your installation of joomla (perhaps a plugin)

If it really was an issue with chrome not working with joomla then we would
have had a considerable volume of reports not just one

On 27 November 2015 at 09:30, bertmert <notifications@github.com<mailto:notifications@github.com>> wrote:

> I'm working a lot with Chrome and Joomla backend for a longer time now.
> Saw many versions of both.
> .
> I can't confirm this issue.
>
> Windows 7, Windows XP, Linux.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/8042#issuecomment-160090238>.
>



--
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment] 2015-11-27 14:37
I repeat my previous comment

**Comment by ataki0** [comment] 2015-11-27 14:39
Thanks for your help

Have a great day


De : Brian Teeman [mailto:notifications@github.com]
Envoyé : 27 novembre 2015 09:39
À : joomla/joomla-cms <joomla-cms@noreply.github.com>
Cc : Jonathan Dagenais <jdagenais@DUCHESNAY.COM>
Objet : Re: [joomla-cms] Articles not unlocked under Chrome (#8042)

I repeat my previous comment
On 27 Nov 2015 2:31 pm, "ataki0" <notifications@github.com<mailto:notifications@github.com>> wrote:

> It seems to be related with the SSL encryption. If I use the http, it
> works very well.
>
> It must be a bug with Chrome on Windows.
>
> Thanks
>
>
> Jonathan Dagenais
> Intégrateur Web / Web integrator
> jdagenais@duchesnay.com<mailto:jdagenais@duchesnay.com<mailto:jdagenais@duchesnay.com%3cmailto:jdagenais@duchesnay.com>>
>
> [cid:image001.gif@01CCDB7A.23E44FC0]
>
> 950 boul. Michèle-Bohec, Blainville QC Canada J7C 5E2
> Tél. Tel.: + 1 450 433-7734/1 877 833-7734 # 152
> www.duchesnay.com<http://www.duchesnay.com/<http://www.duchesnay.com%3chttp:/www.duchesnay.com/>>
>
> L'information transmise par ce courriel est destinée à l'usage du
> destinataire ci-dessus. Il est donc strictement interdit d'utiliser cette
> information, de la copier, de la distribuer ou de la divulguer. Si cette
> communication vous a été transmise par erreur, veuillez la détruire et nous
> en aviser immédiatement par courriel.
>
> This information is directed in confidence solely to the person above and
> may not otherwise be distributed, copied or disclosed. Therefore, this
> information should be considered strictly confidential. If you have
> received this email in error, please notify the sender immediately via a
> return e-mail for further direction.
>
> P Pensez à l'environnement avant d'imprimer ce courriel. Think of the
> environment before printing this e-mail.
>
>
>
> De : Brian Teeman [mailto:notifications@github.com]
> Envoyé : 27 novembre 2015 05:11
> À : joomla/joomla-cms <joomla-cms@noreply.github.com<mailto:joomla-cms@noreply.github.com>>
> Cc : Jonathan Dagenais <jdagenais@DUCHESNAY.COM<mailto:jdagenais@DUCHESNAY.COM>>
> Objet : Re: [joomla-cms] Articles not unlocked under Chrome (#8042)
>
> I use google chrome exclusively on mac using Joomla all day and everyday
>
> Your problem is either something you are doing wrong or something unique
> to
> your installation of joomla (perhaps a plugin)
>
> If it really was an issue with chrome not working with joomla then we
> would
> have had a considerable volume of reports not just one
>
> On 27 November 2015 at 09:30, bertmert <notifications@github.com<mailto:

**Comment by PascalNetenvie** [comment] 2015-11-27 16:02
Ataki, what plugin are you using ?
We can compare our plugins extensions and perhaps find where is the problem.
Perhaps it can also be a security software on our computers?

But the problem was said to me from a customer working on chrome under Macintosh.
So for me the problem come from Chrome + perhaps one plugin we use regularly.

**Comment by sanmugamk** [comment] 2015-12-09 04:35
I also facing same problem with chrome after upgraded to Joomla 3.4. Straight content edit link is not working.
But i tick the box for the content i want to edit, then click Edit, that works for me.
Thanks.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8042">issues.joomla.org/joomla-cms/8042</a>.</sub>

**Comment by PascalNetenvie** [comment] 2015-12-09 13:07
Comon elements from now are :
 - Site upgraded from 3.x to 3.4
 - Chrome used to browse Backoffice
So it seems to be a bug ... perhaps from update ?

Sanmugamk, are you using :
Any plugins or extension on Joomla ?
Any Chrome plugins ?

**Comment by brianteeman** [comment] 2016-04-06 11:14
I am closing this at this time - if you are still having this issue please provide as much information as possible to enable someone to replicate the issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8042">issues.joomla.org/joomla-cms/8042</a>.</sub>

**Closed by brianteeman** 2016-04-06 11:14 UTC
Labels: No Code Attached Yet

**Comment by nitromedia** [comment] 2016-09-15 13:01
Hi ! 

I got the same problem with several clients.

They are editing articles then save and they can't enter back in the article. It always happen on Google Chrome (PC or Mac). It seems to happen when you modify and switch between several articles (or going back in the same article for several times).

Clients always click on the title. (I just found out about the difference with the edit button, i'll try this next time see if it makes any difference)

In the meantime, I installed this plug-in https://chrome.google.com/webstore/detail/clear-cache/cppjkneekbjaeellbfkmgnhonkkjfpdn . I also made my client install it. So if they can't enter in an article, they click on the button of the plug-in then try again and they can enter.

I have this problem since several months, but clients complaint more about it recently. My Joomla's are all up to date and all in French. Google Chrome is in French too. (I don't know if it could be of any help)

**Comment by ggppdk** [comment] 2016-09-15 18:15
@nitromedia 

When user's browser decides to do caching, the re-editing the article / record will fail !

reason for user's browser deciding to do caching, is usually configation of your web-server

Read this comment
https://github.com/joomla/joomla-cms/issues/8757#issuecomment-172797060

you may try this patch:
https://github.com/joomla/joomla-cms/pull/10753
