### ISSUE TITLE
"Read More" Link and Read More with Title in menu options do not override global Options

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#41192] opened 2023-07-20 01:00 UTC
### Steps to reproduce the issue
Install sample data
Edit the 'Your Template' Article add a readmore.  
Edit the 'Main Menu Blog >>> Blog menu item ... Options (tab)
Set "Read More" Link and Read More with Title to No
In the frontend navigate to Sample Layouts >>> Blog

### Expected result
Readmore should not show

### Actual result
Readmore shows with Title

### Additional comments
'Unauthorised Links' in menu options does not override global settings either

**Comment by brianteeman** [comment] 2023-08-12 21:46
Closed as not a bug

**Closed as completed by brianteeman** 2023-08-12 21:46 UTC
Labels: No Code Attached Yet
