### ISSUE TITLE
Problem with updating from 3.4.1 to 3.4.2. or 3.4.3

### ISSUE THREAD

**Issue by bps73cx** [joomla/joomla-cms#7383] opened 2015-07-08 18:31 UTC
#### Steps to reproduce the issue

Hello,

since version 3.4.2 I have problem when I try to update to 3.4.2 or 3.4.3 I have a message:

_Warning
JFolder::create: Infinite loop detected.
Extension Install: Failed to create directory: 
Error
Error installing file_

I figured it out that problem is in chroot function. I have many web pages on my server. When I turn off chroot function, every things work fine, update is successful.  Unfortunately because of safety reasons I cannot turn of chroot.  Everything was fine with version 3.4.1 and less. Something was changed in higher versions. 

#### Expected result

I don’t know that was a purposive change or a error. How can I fix it?

**Comment by bps73cx** [comment] 2015-07-09 07:30
I have check that update from 3.3.6 to 3.4.3 was successful by package: Joomla_3.4.3-Stable-Update_Package.zip.
But I still can’t update from 3.4.1 to 3.4.3 with Joomla_3.4.3-Stable-Update_Package.zip or Joomla_3.4.x_to_3.4.3-Stable-Patch_Package.zip.
Maybe problem causing 3.4.1 version. 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7383">issues.joomla.org/joomla-cms/7383</a>.</sub>

**Comment by PhilETaylor** [comment] 2015-07-10 19:20
Check your value for the tmp folder in configuration.php

**Comment by bps73cx** [comment] 2015-07-13 07:05
Hi, i don't change path of temp folder. I check, but it is still /tmp. I change for test porpoise path of temp folder, but nothing change. Still I can't update. I can't update since 3.4.0 version. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7383">issues.joomla.org/joomla-cms/7383</a>.</sub>

**Comment by PhilETaylor** [comment] 2015-07-13 11:41
If your tmp path in configuration is set as /tmp then you HAVE changed it because as default Joomla sets this as the tmp folder within your Joomla folders - so it should be something like /home/username/public_html/tmp and not just /tmp which points to the main tmp partition on a linux server. 

It might be that you are on an incorrectly configured server that doesnt allow you to access /tmp

**Comment by bps73cx** [comment] 2015-07-13 12:53
thank you, but i had try every possible configuration on that path of temp folder. Server settings don’t change. Something change in Joomla since 3.4.0. Even now I can normal update from < 3.3.6 to 3.4.3, but I can’t update it from 3.4.0, 3.4.1 and 3.4.2.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7383">issues.joomla.org/joomla-cms/7383</a>.</sub>

**Comment by PhilETaylor** [comment] 2015-07-13 18:01
@bps73cx In the spirit of resolving this quickly I need to be able to debug the problem on a server that replicates the issue. I have attempted this for the last few hours and I cannot find a problem here. The fact that the issue is with creating folders and infinite loops leads itself to be a problem with your servers folder structure. Symbolic links from hacks are well known to cause looping when deleting folders/creating folders - so that is one possibility 

In the spirit of trying to get to the bottom of this, to identify if this is a problem with Joomla or your hosting, please can you complete the secure form at https://fix.myjoomla.com (A non-official joomla service I might add) and I will (for FREE) personally debug this on your infrastructure until we have a definitive root cause - that way we can identify the issue quickly and address it in Joomla core, or educate you what is causing it in your infrastructure.

Once I have your site login details I can then work on this right away for you.

**Comment by bps73cx** [comment] 2015-07-14 08:11
Hi,
Thank your for help, unfortunately i can’t give any access to server (this are product servers). My hosting provider tell me that nothing change in chroot function, and it must be something in new version of Joomla. 

We have many Joomla installation on this server. Configuration is the same to everyone. I see that:
- I can update form 3.3.6 and less to >3.4
- I can’t update from >3.4.0 to 3.4.1/3.4.2/3.4.3

When I switch off chroot, all updates is successful. If that was a server problem, I wouldn’t update even version 3.3.6 but it is possible. I have that problem only on shared hosting.  On VPS server updates from any version are successful. But there we don’t use chroot. Something must change from 3.4.0 version with chroot services in Joomla.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7383">issues.joomla.org/joomla-cms/7383</a>.</sub>

**Comment by PhilETaylor** [comment] 2015-07-14 17:27
I'm sorry - I have spent hours trying to replicate a server that causes issues with the upgrade such as you are presenting and I have not been able to replicate the issues at all.

That is your value for the tmp_path in Joomla Global Configuration? 

Are you sure all folders/files ownerships and permissions are set correctly.

IIRC the other thing that changed recently is that the source update files are hosted at github and not on joomlacode - this change might have something to do with this (@mbabker might know more) - also I think that the Github URLs are over SSL (https://) whereas the old ones were not (I might be talking out my arse here... cant be bothered to check as I know this is not a Joomla core issue!) 

As this is specific to your environment, and not a major life changing worldwide Joomla issue (else hundreds would be reporting it), and as you have refused me access to the environment - I recommend that this issue in Github is closed as this clearly is not a Joomla issue.

**Comment by mbabker** [comment] 2015-07-14 17:33
Yes, packages are served from GitHub due to JoomlaCode's instability and will be moving back to an "on-property" domain once the new site is finished.  There are some servers that have SSL issues connecting to GitHub, but that error is thrown much sooner than any point that the OP's error is happening.

Joomla doesn't use anything related to chroot (there are 4 instances of the string in the full CMS repo, all in CodeMirror JS files).  So there is no change within Joomla that could have affected that as your host may be implying.

**Closed** 2015-07-14 18:27 UTC
Labels: No Code Attached Yet

**Comment by bps73cx** [comment] 2015-07-15 09:17
Hi,

am I very grateful for your time. I try all of tmp path combination for example: “/tmp”, “/serweqzx/public_html/web/tmp” etc. All of folders are writable (I check also in Joomla info panel). We don’t use ssl. 

I don’t know how it is possible. On the same server one version works, other don’t. maybe new releases of Joomla or my server will help. 

Once again, thank Your for your time.  
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7383">issues.joomla.org/joomla-cms/7383</a>.</sub>

**Comment by thebodzio** [comment] 2015-10-23 03:23
I believe this could have something to do with the issue at hand: http://issues.joomla.org/tracker/joomla-cms/7866

**Comment by bps73cx** [comment] 2015-10-23 09:01
Hi, thank you. I think it’s may be it. Unfortunately I don’t know, what code I should, modify, and what path will be correct. In current versions that problem still exists.
