### ISSUE TITLE
Custom Tag field does not allow custom entries

### ISSUE THREAD

**Issue by grantg182** [joomla/joomla-cms#29033] opened 2020-05-11 10:51 UTC
### Steps to reproduce the issue
Create a custom tag field, with [params as per the documentation](https://docs.joomla.org/J3.x:Using_Tags_in_an_Extension).

Here's mine:

`<field name="tag" mode="ajax" multiple="false" custom="allow" type="tag" label="My Custom Tag" description="Description of My Custom Tag" hint="Hint of My Custom Tag"/>`

### Expected result
Admin user can select existing tag, or create a new tag.

### Actual result
Admin user can only select an existing tag, there is no option to enter a new tag. If set to `multiple="true"` then the user can type in the field, which appears to only be doing a search for a matching tag, but of course this is a new tag, so nothing is returned and alas, nothing is saved.

### System information (as much as possible)
Joomla 3.9.8.

### Additional comments
As per the document linked above, I would expect an admin user to be able to create a new custom tag, but this appears not to be the case. Also same issue mentioned in [#28298](https://github.com/joomla/joomla-cms/issues/28298).

**Comment by ReLater** [comment] 2020-05-11 11:31
Do I understand correctly?
You have created a custom component and then you integrated the tag features for one or more views like described in the docs.
Then you cannot create a new tag in one of the edit views of this custom component?

Or is your expectation to create a new tag somewhere? See https://github.com/joomla/joomla-cms/issues/29015#issuecomment-626236860

**Comment by grantg182** [comment] 2020-05-11 14:30
@ReLater Correct; the tag field has been added into a custom component form XML, just as described in the docs. The tag field appears as an option list, therefore I can select existing tags, save, and the tag selected is saved as expected, but the issue is I cannot create a new tag from here, which the documentation clearly states I should be able to as per [here](https://docs.joomla.org/J3.x:Using_Tags_in_an_Extension#Add_a_Tag_Field_to_Edit_Screens "here") under "Ajax Mode".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29033">issues.joomla.org/tracker/joomla-cms/29033</a>.</sub>

**Comment by ReLater** [comment] 2020-05-11 15:22
> the tag field has been added into a custom component form XML

And you followed all the other steps, i.e. table fields mapping, new content types in database and so on?

**Comment by grantg182** [comment] 2020-05-11 20:48
@ReLater yes, I believe so. Literally every other form field, custom or not, works...except this `tag` field.  I also updated the Actual result in the OP to make it a bit clearer, I hope.

**Comment by Quy** [comment] 2020-05-13 14:01
Please test PR #29051.

**Comment by alikon** [comment] 2020-05-13 17:01
closing as we have a pr

**Comment by SharkyKZ** [comment] 2020-05-13 20:35
#29051 is not related.

**Comment by grantg182** [comment] 2020-05-13 21:00
[#29051](https://github.com/joomla/joomla-cms/pull/29051) did not look related; and can confirm it made no difference to this issue.

**Comment by grantg182** [comment] 2020-05-19 13:07
Another update to this one. It appears custom fields do get added to the field and do get saved if the user physically hits the Enter key. Clicking outside of the tag field does not retain the custom tag, hence it is not saved. Same behaviour experienced on J 3.6.5 and 3.9.8.

**Comment by Hackwar** [comment] 2022-11-06 19:47
I can understand that the behavior is not 100% intuitive, however this is intended behavior, mainly because a tag can consist out of more than one word. Without confirming by hitting the enter key, we wouldn't know if a string with x words is one single tag or x separate ones. So I'm closing this one as expected behavior.

**Closed as completed by Hackwar** 2022-11-06 19:47 UTC
Labels: No Code Attached Yet
