### ISSUE TITLE
TinyMCE drag & drop - "Unable to upload file" error

### ISSUE THREAD

**Issue by b2z** [joomla/joomla-cms#24544] opened 2019-04-10 14:02 UTC
Issue after update from 3.9.4 to 3.9.5.

### Steps to reproduce the issue
1. Ensure that you are using TinyMCE editor.
2. Open article.
3. Try to drag & drop an image.

### Expected result
Image is uploaded successfully.

### Actual result
Error "Unable to upload file"

### System information (as much as possible)

PHP Version: 7.2.10
Web Server: Apache/2.4.6 (CentOS) mpm-itk/2.4.7-04 OpenSSL/1.0.2k-fips PHP/7.2.10
Joomla! Version: Joomla! 3.9.5 Stable [ Amani ] 9-April-2019 15:00 GMT

### Additional comments
Console response
`{"status":"0","message":"Unable to upload file.","error":"Unable to upload file."}`

**Comment by HLeithner** [comment] 2019-04-10 17:33
Confirmed.

**Comment by Webdongle** [comment] 2019-04-16 08:26
Confirmed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24544">issues.joomla.org/tracker/joomla-cms/24544</a>.</sub>

**Comment by SolutioAndy** [comment] 2019-04-18 20:18
The problem was introduced with this change in 3.9.5:

https://github.com/joomla/joomla-cms/commit/1547f8e76000a22d9befc2551ca9929f5d2d0c56#diff-e5953bc3eadad37980d677840c9d4f6dR97

There are a couple issues with this check:

- $filepath may not exist yet, so realpath() will return false (the target directory should be checked instead of the full file path)
- the logical not operator has higher precedence and will turn the result of strpos() into a boolean, which will never pass the strict equality test against 0 (the logical not operator should be removed)

**Comment by Quy** [comment] 2019-04-18 20:45
@SolutioAndy Can you please submit a PR? Thanks.

**Comment by Quy** [comment] 2019-04-18 21:58
Thank you! Please test PR #24637.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24544">issues.joomla.org/tracker/joomla-cms/24544</a>.</sub>

**Closed as completed by Quy** 2019-04-18 21:58 UTC
Labels: No Code Attached Yet

**Comment by AndyGaskell** [comment] 2019-04-30 11:27
I hit this problem, exactly as described.  The fix worked for me too.
