### ISSUE TITLE
[com_fields] Insert Field in Articles shows as Field Number {field } when clicked on Title in Category Blog

### ISSUE THREAD

**Issue by esskay303** [joomla/joomla-cms#18288] opened 2017-10-09 11:21 UTC
### Steps to reproduce the issue

Insert Field in Article
Article Options - Set Linked Titles to Yes, Show Unauthorised Links to Yes, Show Intro Text to Hide,
Set Article Access to Registered
Create any custom field with access right to public and insert in the article before read more (intro text)
Create category blog menu item
Check front end as non logged in user.

### Expected result

Clicking on article title should show inserted field value.

### Actual result

Clicking on article title show field name as (field --}

### System information (as much as possible)

PHP 7.0.18
Joomla 3.8.1
Database 5.6.28
Database Collation utf8_general_ci
Joomla Platform Version 13.1.0 Stable

**Comment by ghost** [comment] 2017-10-14 09:01
Can't confirm, Test as Superuser.

Using given Options shows com_fields Value.

**Comment by ghost** [comment] 2017-10-22 09:29
If this Issue get no Response, it will be closed at 26th November 2017.

**Comment by esskay303** [comment] 2017-10-23 10:12
> Can't confirm, Test as Superuser.
> 
> Using given Options shows com_fields Value.

Does this mean that you are getting expected results ? I have just checked on my system and can confirm that the issue exists on my site. Is there a way to send link of my website where this exists ?

**Comment by ghost** [comment] 2017-10-23 10:15
> Does this mean that you are getting expected results?

Yes.

Maybe another one can test this so we know if its Core-related or local.

**Comment by ghost** [comment] 2017-12-26 08:12
If this Issue get no Response, it will be closed at 26th January 2018.

**Comment by esskay303** [comment] 2017-12-26 08:20
The issue is still there and not fixed...

**Comment by ghost** [comment] 2017-12-26 08:21
@esskay303 thanks for Update, Issue stay open.

**Comment by Bakual** [comment] 2017-12-26 08:21
@esskay303 You may have to provide more details so it can be reproduced.

**Comment by brianteeman** [comment] 2018-01-08 15:16
I cannot replicate this. Please test with one of the default templates eg protostar just to rule out it being caused by your template.

**Comment by esskay303** [comment] 2018-01-09 06:21
alright...I will test on Protostar...

**Comment by Quy** [comment] 2018-01-19 00:47
@esskay303 Unable to reproduce. Have you upgraded/tested with v3.8.3?

**Comment by ghost** [comment] 2018-01-27 08:05
If this Issue get no Response, it will be closed at 28th February 2018.

**Comment by ghost** [comment] 2018-02-28 07:54
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18288">issues.joomla.org/tracker/joomla-cms/18288</a>.</sub>

**Closed as completed by ghost** 2018-02-28 07:54 UTC
Labels: No Code Attached Yet
