### ISSUE TITLE
[4.0] Users: Edit Profile: Two Factor Authentication - Subheadings are not highlighted in any way

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#34187] opened 2021-05-24 20:19 UTC
### Steps to reproduce the issue
Enable two-factor authentication plugins. Go to editing a user profile (for example, your own). On the Two Factor Authentication tab, step subheadings (or information block subheadings) are not highlighted in any way.

For all field values: One time emergency passwords / Google Authenticator / YubiKey.

![Screenshot_2](https://user-images.githubusercontent.com/8440661/119402941-4f11d200-bce6-11eb-87a8-5a1bf7e88fdd.png)

Below you can see how it looks in Joomla 3.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/119402954-53d68600-bce6-11eb-872b-c6502b82e574.png)

**Comment by brianteeman** [comment] 2021-05-24 20:39
Caused by this pr https://github.com/joomla/joomla-cms/pull/33389 which is setting a fieldset on something that isnt a fieldset

**Comment by Kostelano** [comment] 2021-05-24 21:06
@YatharthVyas please take a look at this. Perhaps you will quickly understand what's what.

**Comment by YatharthVyas** [comment] 2021-05-25 03:49
> Caused by this pr #33389 which is setting a fieldset on something that isnt a fieldset

I reverted the changes in PR #33389 but it wasn't enough to fix the issue. I think this is happening because each of the steps is enclosed in an individual fieldset where the heading of the step is a legend tag:

https://github.com/joomla/joomla-cms/blob/a95cdfc2bdbc87cdba8c4865e9a5e87f46bb6b1f/plugins/twofactorauth/totp/tmpl/form.php#L46-L49

![image](https://user-images.githubusercontent.com/53610833/119436271-7b0a7300-bd39-11eb-9b7c-239cf9bbb5eb.png)

Edit: This is also the case in J3 which I believe is incorrect as the 'Steps' are not forms and hence they must not be in fieldsets.

![image](https://user-images.githubusercontent.com/53610833/119437030-e9036a00-bd3a-11eb-9bc1-8a137fd05557.png)

**Comment by brianteeman** [comment] 2021-05-25 08:32
>  I believe is incorrect as the 'Steps' are not forms and hence they must not be in fieldsets.

Correct they are not. A fieldset (and therefore a legend) are only to be used to group input fields

**Comment by richard67** [comment] 2021-05-25 14:02
Closing as having a pull request. Please test #34205 . Thanks in advance.

**Closed as completed by richard67** 2021-05-25 14:02 UTC
Labels: No Code Attached Yet
