### ISSUE TITLE
system updatenotification is sent in the wrong language

### ISSUE THREAD

**Issue by sh-si** [joomla/joomla-cms#17595] opened 2017-08-18 05:58 UTC
### Steps to reproduce the issue
* Install more than one language in your joomla backend (e.g. English (1), German (2), Polish (3) => sort order in Brackets)
* Mark one Language as default Language (German)
* All Languages are up to date
* Plugin system updatenotification is enabled, existing email address is set, language setting is set to "automatic"
* Wait for a Joomla Update

### Expected result
* joomla updatenotification mail comes in default language (German)

### Actual result
* joomla updatenotification mail comes in polish Language

### System information (as much as possible)
PHP 7.0.13
Joomla 3.7.4

### Additional comments
none

**Comment by ghost** [comment] 2017-08-18 06:06
Can't confirm.

Got a Notification in German from a Site set Backend: English, Frontend: German.

**Comment by ggppdk** [comment] 2017-08-18 08:32
This is "expected" behaviour, auto means use language of the  **frontend or backend user** visitor triggering the plugin executon ! ... just the description of the parameter about "auto" is not so clear

>If you choose Auto (default), the update notification email to Super Users will be in the site language at the time the plugin is triggered.

notice the "at the time the plugin is triggered"

a note, the case that a backend visit will trigger the plugin is very rare, because it would mean that your site frontend have very little traffic ...

I am not sure if the parameter description needs to be improved

**Comment by brianteeman** [comment] 2017-08-18 22:15
Closed as the expected behaviour. It does exactly what it says.

**Comment by gwsdesk** [comment] 2017-09-20 03:02
I happen to disagree. This behavior is rather 'strange" If you have an multi-lingual site with main language "English", you are a UK webmaster in Wales and you get a German-language "update notification" ? That is not normal. My personal perception was (and I know now that was wrong) that this would take the default site language but it makes not a bit sense that the visitor language is triggered. Who is the recipient of the notification? Right the Englsih speaking webmaster in wales. 

I am very much in favor of changing the "auto" functionality to use the "default" site language

**Comment by ghost** [comment] 2017-09-20 05:03
reopened cause of Comment above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17595">issues.joomla.org/tracker/joomla-cms/17595</a>.</sub>

**Comment by brianteeman** [comment] 2017-10-05 18:59
If you want to force the email to be sent in a specific language you can do - thats why the option is there.

**Closed as completed by brianteeman** 2017-10-05 18:59 UTC
Labels: No Code Attached Yet
