### ISSUE TITLE
Module front editing : custom positions not listed

### ISSUE THREAD

**Issue by makinero** [joomla/joomla-cms#6461] opened 2015-03-16 17:45 UTC
Hello !

#### Steps to reproduce the issue
Log into the front using a super admin account and edit a module. Click on the position list : if you set some custom positions, you won't see it in the list. If you edit a module which is on a custom position and save, the module will be placed to the first default position (banner)

#### Expected result
A bug of the new module front edit.

#### Actual result
No custom position in front editing. Modules moved to another position without user action.

#### System information (as much as possible)
Bug appears on an upgraded installation and a fresh installation

#### Additional comments
Please correct it fast

**Comment by Josh-Lewis** [comment] 2015-03-17 02:17
Issue confirmed, good catch. When not using Protostar it does this too. It falls back on the first module position mentioned in the templateDetails.xml file. Hope this gets resolved in the next release of Joomla.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6461">issues.joomla.org/joomla-cms/6461</a>.</sub>

**Comment by makinero** [comment] 2015-03-17 08:19
Thank you for the tip! When I add my custom positions in templateDetails.xml file, my custom positions becomes default position so it works.

I also wish that will be fixed in the next release!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6461">issues.joomla.org/joomla-cms/6461</a>.</sub>

**Comment by brianteeman** [comment] 2015-03-20 15:49
Confirmed

The front end module editing only shows the positions in the current template<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6461">issues.joomla.org/joomla-cms/6461</a>.</sub>

**Comment by infograf768** [comment] 2015-03-21 07:13
Was this working in 3.3.6 ?

**Comment by Josh-Lewis** [comment] 2015-03-21 07:15
Joomla 3.3.6 redirected you to the backend when clicking the edit icon on modules, Joomla 3.4 introduced module editing on the frontend.

**Comment by Achal-Aggarwal** [comment] 2015-04-17 08:25
I think I am not understanding the problem correctly, please do correct me if I am wrong.

In backend, module position dropdown field gets populated by positions mentioned in templateDetails.xml file of each template for client side and under 'Custom Positions' it gets positions of other modules are assigned to.

In frontend if a module is edited, the module position field gets populated by positions mentioned in templateDetails.xml file of currently activated template.

So if you are able to open a module for editing in frontend that means it has some position assigned which is visible and if you want to change its position to any other in the activated template you can do that easily.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6461">issues.joomla.org/joomla-cms/6461</a>.</sub>

**Comment by brianteeman** [comment] 2015-04-17 08:29
Easy example would be a module that has been placed in an article using the
loadmodule plugin and a custom position

Plus it is quite common for someone to add a module to the index.php of the
template and not bother to add it to the templateDetails.xml file as it is
not required and a user can just manually enter that position.

Basically the dropdown module select should show the same options in the
front as it does in the admin.

Hope that helps to explain

On 17 April 2015 at 09:25, Achal Aggarwal <notifications@github.com> wrote:

> I think I am not understanding the problem correctly, please do correct me
> if I am wrong.
>
> In backend, module position dropdown field gets populated by positions
> mentioned in templateDetails.xml file of each template for client side and
> under 'Custom Positions' it gets positions of other modules are assigned to.
>
> In frontend if a module is edited, the module position field gets
> populated by positions mentioned in templateDetails.xml file of currently
> activated template.
>
> So if you are able to open a module for editing in frontend that means it
> has some position assigned which is visible and if you want to change its
> position to any other in the activated template you can do that easily.
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/6461
> <http://issues.joomla.org/tracker/joomla-cms/6461>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6461#issuecomment-93942233>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Achal-Aggarwal** [comment] 2015-04-17 10:43
Ohh, now I get it. Thanks Brain for explaining.

But still I don't think module position dropdown filed should have positions from templates which are not activated. It should contain only current template & custom positions.

**Comment by sovainfo** [comment] 2015-04-17 11:46
Pun intended? Brian Brain

**Comment by Achal-Aggarwal** [comment] 2015-04-17 11:58
No bad intentions. Totally my fault.
Sorry Brian for misspelling your name.

**Comment by brianteeman** [comment] 2015-04-17 12:06
Happens all the time - just check http://lmgtfy.com/?q=%22brain+teeman%22

On 17 April 2015 at 12:58, Achal Aggarwal <notifications@github.com> wrote:

> No bad intentions. Totally my fault.
> Sorry Brian for misspelling your name.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6461#issuecomment-93972456>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by sovainfo** [comment] 2015-04-17 13:35
:smile:

**Comment by brianteeman** [comment] 2015-04-30 14:25
> current template & custom positions.

Agreed

**Comment by heiro** [comment] 2015-05-04 00:42
I have problems with my template when editing modules from frontend in Joomla 3.4. Could it be possible to redirect the frontend edting of modules to the backend administrator, like it was in J 3.3? Does anybody know how to do it?

**Comment by JoshuaLewis** [comment] 2015-05-04 00:49
@heiro That doesn't seem relevant to the discussion. As far as I know redirecting is no longer used. Your better off evaluating the cause, carefully describing it in the issues section, and hopefully someone comes up with a fix for it.

**Comment by Achal-Aggarwal** [comment] 2015-07-25 09:31
IMO, giving option to all custom positions on frontend is not a good idea. But the dropdown should contain/retain the position so that user can edit the module without changing its position unintentionally.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6461">issues.joomla.org/joomla-cms/6461</a>.</sub>

**Comment by brianteeman** [comment] 2015-07-25 09:37
Please see #7540 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6461">issues.joomla.org/joomla-cms/6461</a>.</sub>

**Closed by brianteeman** 2015-07-25 09:37 UTC
Labels: No Code Attached Yet
