### ISSUE TITLE
[4.0] Content Language Creation

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#28176] opened 2020-03-01 13:19 UTC
### Steps to reproduce the issue
1. Install Joomla 4
2. Install the language German and Persian (edit: Make the installation of the languages while with the installation of Joomla)
3. Check the Content Languages System > Manages > Content Languages

### Expected result
You see Persian and German language or see no of this languages and you have to create all the Content Languages yourself.

### Actual result
Persian Language for Content is created. You have to install the German Content Language yourself.

**Comment by infograf768** [comment] 2020-03-01 15:37
Have you installed the languages at the same time as J install, or later after logging into admin and using the Install Languages manager?

**Comment by richard67** [comment] 2020-03-01 15:38
Yes, I wanted to ask the same. When doing it later in backend I don't have that problem, but when doing it with the installation I can confirm.

**Comment by astridx** [comment] 2020-03-01 15:58
Sorry, yes I did it with the installation.

**Comment by infograf768** [comment] 2020-03-01 15:59
Then, this is a recent issue as it was working ok before.

**Comment by astridx** [comment] 2020-03-01 16:32
This is strange. Now I can no longer reproduce that. For me no content language is created anymore. Not even for Persian.
But the Persian Content Language was create in the Past and I didn't do it.
How should it work? I really do not know: Should the Content Language be created automatically if a language is installed?

**Comment by infograf768** [comment] 2020-03-01 16:41
One aspect to know:
If the language already exists in the languages folders, then the content language may not be created when installing J again.

Normally it should work fine when it is a totally clean install.

**Comment by astridx** [comment] 2020-03-01 16:56
That is the explanation. I had only run `npm ci `and deleted the `configuration.php`. 

Now I've  deleted the language files. And then the Content Languages were created.

I think these should all the time be created during installation if they don't already exist. What do you all mean?

**Comment by richard67** [comment] 2020-03-01 16:59
I think when you have this situation you can use "Discover" after a new installation to find the languages, and then install them with "Disvover" and not with Language Installation. Of course the discovery installation should then create the content languages. That would be the right way when doing a new install with previously being installed extensions or languages present on the file system and having to be installed again after the new CMS installation.

@astridx Would that work for you? I currently can't test and don't remember last time when I tested that. Can you check if discovery installation adds the content languages?

**Comment by brianteeman** [comment] 2020-03-01 17:36
Discovery install does not create content language.

**Comment by astridx** [comment] 2020-03-01 17:55
@brianteeman That is another reason not to make the creation of the content language dependent on existing files.

**Comment by infograf768** [comment] 2020-03-01 18:21
This issue has been present since the creation of the Content Language has been automatically added to the installation of languages.

I am sure there is a solution to this by some modifications in the language adapter.
`/libraries/src/Installer/Adapter/LanguageAdapter.php`

@Bakual Any idea?

**Comment by brianteeman** [comment] 2020-03-01 18:23
Installation is a package install
Discover is a language install

Probably points to where

**Comment by Bakual** [comment] 2020-03-01 18:23
I think it was done like this on purpose.
You only can create the content language automatically on the initial installation. When doing a discover or reinstall, you don't know if the content language has already beeen created or not. It may have also been deleted on purpose or whatever.

Of course it can be changed if someone wants to dig into it. You would have to check the #__languages table and see if the language code of the installed language is present in the `lang_code` column. If yes, content language exists. If not, create it.

**Comment by infograf768** [comment] 2020-03-01 18:37
> Of course it can be changed if someone wants to dig into it. You would have to check the #__languages table and see if the language code of the installed language is present in the lang_code column. If yes, content language exists. If not, create it.

I think it would be sensible to do that.

**Comment by brianteeman** [comment] 2020-03-05 09:03
Closed by #28718

**Comment by astridx** [comment] 2020-03-05 09:08
@brianteeman May I ask you what May I ask you what #28718 is?

**Comment by brianteeman** [comment] 2020-03-05 09:52
sorry typo should have been #28178

**Comment by infograf768** [comment] 2020-03-05 12:32
See https://github.com/joomla/joomla-cms/issues/28176#issuecomment-593128101

https://github.com/joomla/joomla-cms/pull/28178 is unrelated.

**Comment by brianteeman** [comment] 2020-03-05 13:08
If I misunderstood it can always be re-opened

**Comment by infograf768** [comment] 2020-03-05 15:38
It has been explained that the OT issue is not a bug, but that we could improve as suggested by @Bakual 
Therefore let’s indeed reopen if someone is interested to prpose a patch

**Comment by Bakual** [comment] 2020-03-05 21:32
See #28243

**Closed as completed by Bakual** 2020-03-05 21:32 UTC
Labels: No Code Attached Yet
