### ISSUE TITLE
[4.0] Front end module edit function fails to save

### ISSUE THREAD

**Issue by b10tds** [joomla/joomla-cms#28748] opened 2020-04-21 18:09 UTC
### Steps to reproduce the issue
J400 totally default vanilla installation.
Login as a super-user.
Edit default image module from the home page using the displayed module edit button.
With, or without, making any changes in the editor, select either of the Save options.

Also in the front end the [edit] button is still displayed AND appears active when you are editing. 

### Expected result
Correct saving of any change and clean exit.

### Actual result
Following error message appears on blank white screen:
{"error":true,"code":0,"message":"Call to a member function getType() on null"}

### System information (as much as possible)
 PHP 7.2.0
 MySQLi 8.0.16
 Caching Disabled
 Gzip Disabled
 Users 1
 Articles 6

### Additional comments
Same error occurs no matter which editor is used. 
In the back end (Admin CP) it edits and save correctly, no matter which editor is used.

**Comment by Quy** [comment] 2020-04-21 20:35
Please make sure you are testing with the nightly builds. 
https://developer.joomla.org/nightly-builds.html

**Comment by richard67** [comment] 2020-04-22 08:24
> J400 totally default vanilla installation.
> Login as a super-user.
> Edit default image module from the home page using the displayed module edit button.

@b10tds I'm confused because on a Joomla 4 "default vanilla installation" there is no "default image module from the home page". What kind of module is it? Have you created it, or have you installed some kind of sample data after the installation? Please report back all details we need to reproduce the issue.

**Comment by b10tds** [comment] 2020-04-22 08:30
My apologies, yes I used the "add sample data" option in the admin CP after the install so there was some content to see how it worked.

**Comment by richard67** [comment] 2020-04-22 08:31
@b10tds Which one? Blog sample data? Or multilingual sample data?

**Comment by b10tds** [comment] 2020-04-22 08:33
Blog sample.

**Comment by richard67** [comment] 2020-04-22 08:34
@b10tds Language of backend and frontend is the default "en-GB"?

**Comment by b10tds** [comment] 2020-04-22 08:34
Yes

**Comment by infograf768** [comment] 2020-04-22 08:36
What do you call the `default image module from the home page` ?
Please add a screenshot

**Comment by infograf768** [comment] 2020-04-22 08:39
I see now which module is concerned.
No issue here:

<img width="923" alt="Screen Shot 2020-04-22 at 10 39 03" src="https://user-images.githubusercontent.com/869724/79960346-9693b200-8485-11ea-82a1-a86465b29767.png">

**Comment by infograf768** [comment] 2020-04-22 08:41
<img width="944" alt="Screen Shot 2020-04-22 at 10 40 43" src="https://user-images.githubusercontent.com/869724/79960508-c3e06000-8485-11ea-9954-69b221abf1e9.png">

**Comment by richard67** [comment] 2020-04-22 08:42
I can't reproduce either, same module as shown by @infograf768 .

**Comment by b10tds** [comment] 2020-04-22 08:47
Okay thanks, I have just installed 4.0.0-beta1-dev version and tested that and it is not doing it, however this may be related to the change in PHP version required for this beta1-dev version to install  from 7.2 to 7.3 to run.

**Comment by infograf768** [comment] 2020-04-22 08:50
Closing this.

**Closed as completed by infograf768** 2020-04-22 08:50 UTC
Labels: No Code Attached Yet
