### ISSUE TITLE
[4.0] Installation issues

### ISSUE THREAD

**Issue by alex7r** [joomla/joomla-cms#17782] opened 2017-08-30 15:48 UTC
### Steps to reproduce the issue
Can't perform clear install.
Can't pass first step.

### Expected result
Click "Next" leads me to the next step.

Token matches.
At least mismatch message.

### Actual result
Click "Next" shows loading and removes it after a bit.

Token doesn't match
Nothing at all happens.

### Additional comments
Session token somehow do not match.
Because of that respond is triggered.
```PHP
JSession::checkToken() or $app->sendJsonResponse(new Exception(JText::_('JINVALID_TOKEN'), 403));
```
In this case I would expect to see a message. But somehow there is no response with message. (Seems caused by 'installation' and not 'working CMS' process) Instead the application seems to be redirected (installation view rendered in response after new PHP process is triggered (proved with Xdebug)).
After everything described above `jQuery` triggers fail (status 200 OK, but there is HTML and not JSON) and tries to parse message. But there is nothing to parse. So it's just removes loading screen.

**Comment by alex7r** [comment] 2017-08-30 16:01
Commenting
```PHP
JSession::checkToken() or $app->sendJsonResponse(new Exception(JText::_('JINVALID_TOKEN'), 403));
```
made PHP side to work. 
```JSON
{"token":"f1eb1b926c3f732ed0cc577163784fdd","lang":"en-US","error":false,"data":{"view":"database"}}
```
But request to `view=database` gives `303` status code and moves to `index.php`.

**Comment by dgrammatiko** [comment] 2017-08-30 16:13
@alex7r thanks for reporting this, but we are currently refactoring the installation and it should be be available shortly for testing

**Comment by alex7r** [comment] 2017-08-30 16:44
@dgt41 doesn't this kind of refactoring needs to be a feature branch/fork or something?
Or 4.0 branch is straight forward pushing branch for each commit?
I believe broking installation in the middle of development is a critical issue because it prevents anybody new from participating in testing/development process?

**Comment by brianteeman** [comment] 2017-08-30 17:01
i agree

**Comment by dgrammatiko** [comment] 2017-08-30 17:13
@alex7r @brianteeman my comment was meant to be a heads up: `hey we are already doing something in the area`. Of course if anyone feels like debugging this error they're more than welcome, the message was not meant to be a stopper in ant shape or form...

**Comment by alex7r** [comment] 2017-11-19 07:37
Seriously, guys? Alpha released out for testing?... 
![2017-11-19_10-33-47](https://user-images.githubusercontent.com/18716997/32988404-4d512c00-cd15-11e7-9ff9-9f843a468601.png)
Shouldn't developer test Blocker things by himself before involving "testing team"?
_______
Sorry for mentioning you here without a particular need, but I think that's the way to get attention to it. @brianteeman @wilsonge

**Comment by wilsonge** [comment] 2017-11-19 11:07
I have tested this - I have repeatedly installed Joomla since I merged the new installer more than 50+ times. Please tell me what you are doing so I can attempt to reproduce your error

**Comment by alex7r** [comment] 2017-11-19 12:44
Well, that's strange, as all I've done is setting up host like https://github.com/alex7r/joomladeception/blob/updating/attach/setup_host.sh and after that: 
- downloaded zip of release
- unpackaged it
- deleted "tests" folder
- renamed .htaccess
- go and try to install
___
I may try to record the actions, but don't think as it will help because it's simple as described - all actions are mentioned above.

**Comment by wilsonge** [comment] 2017-11-19 13:27
OK. Interesting. What browser are you using?

**Comment by alex7r** [comment] 2017-11-19 14:03
Google Chrome, you can see it at the screenshot

**Comment by alex7r** [comment] 2017-11-22 05:31
Did you manage to reproduce the issue? 
As some people were able to install it as I see from few articles coming all over the internet (or those just pretend).

**Comment by wilsonge** [comment] 2017-11-25 14:07
No :( I’ve only seen two issues so far that I’m working on

1) On some Joomla installs people don’t have write access to the installation session directory so we’re gonna move that back to global temp sir

2) there’s a bug when you enter incorrect database credentials that ends up in a hung state of the installer

3) a possible bug with passwords with ampersands in being truncated. I’m still trying to investigate this

I’ve not seen any other reports of issues so far beyond those and this one you’ve reported I’m unable to reproduce at the moment. Can you provide links to these other reports so I can investigate them please?

**Comment by dgrammatiko** [comment] 2017-11-25 14:25
> renamed .htaccess

I've never tested the installer with .htaccess and would expect this step to happen after the installation...

**Comment by alex7r** [comment] 2017-11-26 22:46
@wilsonge @dgt41 
Ok, I'll ask a few of my colleagues to try to install Joomla 4.
Because I've just tried it once again:
- Download Joomla 4 alpha 2 (latest for today Joomla_4.0.0-alpha2-Alpha-Full_Package.zip);
- Used same vagrant box that I have linked before;
- Unzipped and didn't rename anything (htaccess.txt);
- Step 1: Joomla4Test;
- Step 2: admin / admin@mailforspam.com / qweasdzxc
- Step 3: localhost / root / qweasd / joomla_db / (autogenerated prefix)
Still no results :(

See:
![2017-11-27_01-34-38](https://user-images.githubusercontent.com/18716997/33245134-974500b6-d314-11e7-8331-2aa5bf1c9461.png)
Redirect and JS error because waiting for JSON and got full HTML page.
I've tried my luck and renamed .htaccess and did one more attempt, the same issue.
Files/folders permissions are 777.

**Comment by alex7r** [comment] 2017-11-26 22:56
_Off topic:_

Great thing that Joomla have certification difference between J3 and J4, as J3 Certified Administrator can't install J4 :)
We should have J4 Installation certification! :)

**Comment by alex7r** [comment] 2017-11-27 11:21
Ok, we will run a few more tests, but for now it's **0/4** for those who have server machine running on **Ubuntu** (virtual server) and **3/3** for those who run the **Windows** server side (OpenServer), **0/1** shared web hosting (**CentOs likely**).
_**successful installation / attempts on different machines**_

**Comment by alex7r** [comment] 2017-11-28 10:04
@wilsonge 
So I've tried to install it on the real web server.
**j4test.webface.by** - check this out / try it yourself.
(db user may be used "DB: **webfaceb_test**, user: **webfaceb_test**, pass: **qweasd**")
I can't even select DB type. It just lists "None" and nothing more.
![2017-11-28_13-01-23](https://user-images.githubusercontent.com/18716997/33313668-682a87fa-d43c-11e7-85f9-fcb21bc26c25.png)

**Comment by alex7r** [comment] 2017-11-28 13:16
Don't know if you'll need the info, but if someone will install the Joomla 4 with OpenServer and then send it over to me (files and DB). I'm able to restore it and lunch it on the vagrant server. 
"Without installation it works".

**Comment by Fedik** [comment] 2017-11-28 13:36
issue about detecting a database was also reported there #18660

**Comment by wilsonge** [comment] 2017-12-02 15:48
I've just done https://github.com/joomla/joomla-cms/pull/18958 for the installer - which handles a couple of server side issues - see if that helps at all (note the ux isn't good in my PR - but if the db check errors it bails you out and stops you going further and you can scroll to the top of the page and see an error message). But your gif suggest its much more likely to be a javascript issue I *think* so think it's unlikely to help

**Comment by ghost** [comment] 2017-12-08 08:16
@alex7r can you please test #18958?

**Comment by wilsonge** [comment] 2018-05-10 17:21
Various fixes have been merged since this issue was opened and we haven't anything more in here. i'm going to close this issue. If you still have problems please open a fresh ticket.

**Closed as completed by wilsonge** 2018-05-10 17:21 UTC
Labels: No Code Attached Yet, J4 Issue
