### ISSUE TITLE
Admin errors after 3.7.5 to 3.8 update

### ISSUE THREAD

**Issue by stepd123** [joomla/joomla-cms#18020] opened 2017-09-20 18:00 UTC
### Steps to reproduce the issue

Update from Joomla 3.7.5 to 3.8

### Expected result

Successful update

### Actual result

Update reaches 100%, but when page reloads/redirects, the following error is received:

Fatal error: Call to undefined method JVersion::refreshMediaVersion() in /libraries/src/Application/WebApplication.php on line 1064

Site front end works after update, but after logging in to back end, the following error is received when it tries to load the home control panel page:

Fatal error: Cannot redeclare class JInput in /libraries/fof/input/jinput/input.php on line 39

After logging in, trying to go to any other page in admin directly using a URL (bypassing the home control panel page), the following error is received:

Fatal error: Undefined class constant 'PRODUCT' in /administrator/modules/mod_version/helper.php on line 39

### System information (as much as possible)

The site is on a Microsoft IIS 7.5 server running PHP 5.4.30, but I also have a copy of the pre-updated site on my apache development server running PHP 5.6 at inmotion hosting, and running the update caused the same errors there.

### Additional comments

After troubleshooting, I'm able to get into back end pages after logging in without the Fatal error: Undefined class constant 'PRODUCT' if I disable mod_version using phpMyAdmin (which apparently adds the Joomla version number to the browser status bar), but trying to get to the home control panel page still results in the Fatal error: Cannot redeclare class JInput message.

Also, I should mention that I found another report of this problem at:

https://joomla.stackexchange.com/questions/21574/update-to-joomla-from-3-7-4-to-3-8-failing

**Comment by ghost** [comment] 2017-09-20 18:02
@stepd123 thanks for reporting. We have here also Reports about this Issue.

**Comment by micker** [comment] 2017-09-21 07:56
i have the problem too only for one site (i update 47 sites)

**Comment by ghost** [comment] 2017-09-21 08:00
@micker there are other Threads with some Solutions. Please have a Look if some can help you.

**Comment by micker** [comment] 2017-09-21 09:19
hello i didn't found any threat in github .. sorry
i try to re upload j3.8 file same error

**Comment by wojsmol** [comment] 2017-09-21 09:24
@micker Give exact errors.

**Comment by ghost** [comment] 2017-09-21 10:10
@micker i meant #18011 #18012 #18015 #18018 #18020 or #18025. At [Issue Tracker](https://issues.joomla.org/tracker/joomla-cms) they are marked as "Critical".

**Comment by wojsmol** [comment] 2017-09-21 10:54
@stepd123 Do you have `/libraries/cms/version/version.php` after update to Joomla 3.8.0?

**Comment by micker** [comment] 2017-09-21 11:43
my error is Fatal error: Cannot redeclare class JInput in /home/comiteol/www/libraries/fof/input/jinput/input.php on line 39
i didn't have version folder in libraries/cms/ (only class, html less)

i trying to upload all core file but same error

**Comment by wojsmol** [comment] 2017-09-21 12:02
@micker Check if you have `/libraries/joomla/input/input.php` file.

**Comment by stepd123** [comment] 2017-09-21 17:08
@wojsmol the /libraries/cms/version/ and /libraries/joomla/input/ have been reoved in 3.8, so I don't have either folder.

I've gone through the other threads referenced by @franz-wohlkoenig and none have a solution to this problem. Also, I can't run the postupdate.php script, because it gives that same error messsage that showed up at the end of my update from 3.7.5 to 3.8: Fatal error: Call to undefined method JVersion::refreshMediaVersion() in /libraries/src/Application/WebApplication.php on line 1064

Under System|System Information the version is now listed as Joomla! 1.6.3 Stable [ Onward ] 18-Apr-2011 23:00 GMT. Where is it pulling that information from? Is there some was we can manually update the Joomla version number in the database or somewhere else?

@micker, if you're comfortable using phpMyAdmin, you can disable mod_version under the extensions table, then instead of logging in at /administrator/ log in to a direct page like /administrator/index.php?option=com_content which will bypass the home control panel page (that's the only page that gives the "Fatal error: Cannot redeclare class JInput in..." error message. If you get in, check the System Information page and let me know what version of Joomla is listed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18020">issues.joomla.org/tracker/joomla-cms/18020</a>.</sub>

**Comment by rgtr** [comment] 2017-09-21 17:23
Hi

There is definitely something wrong with the 3.8 upgrade. have reinstalled from backups, and tried twice more. failed.

NO messages after installation.

Out of six sites, four upgraded fine. Two - both are sub domains at tdocplus.co.uk - did not.
Sites work fine, but in the back end all the additional plug ins have disappeared from the components menu including JCE, Akeeba, etc.
I am going back to 3.75 for these sites.
Anyone want the Akeeba back up files - please email me.

Richard

parkdavidson.co.uk - fine
accountabilityscotland.org.uk - fine
unaccountablescotland.org.uk - fine
rgtr.tdocplus.co.uk - fine
lp.tdocplus.co.uk - site works, back end problem - a large site from J2 
wp.tdocplus.co.uk - site works, back end problem - an old site from J1

**Comment by wojsmol** [comment] 2017-09-21 17:30
@rgtr On this 2 sites the only problem is related to Components menu?

**Comment by wojsmol** [comment] 2017-09-21 17:42
@stepd123 I know about file move but I recently see cases when update timeout during the process. Which version of Joomla did you upgrade from?

**Comment by stepd123** [comment] 2017-09-21 18:47
Hi @wojsmol, like it says in my report, I upgraded from 3.7.5. :-) The important information in my report is that right after the update hit 100% and apparently tried to finalize, it was unable to update the Joomla version information and gave the error "Fatal error: Call to undefined method JVersion::refreshMediaVersion() in /libraries/src/Application/WebApplication.php on line 1064" Because it wasn't able to update the version information, the Joomla! Version Information  module (mod_version) that shows the version number a the bottom of all admin pages breaks admin until you disable the module.

Whether there were a few other finalizations that were supposed to happen after the Joomla version info gets updated, I don't know. Developers would know the installation order.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18020">issues.joomla.org/tracker/joomla-cms/18020</a>.</sub>

**Comment by Skyla-Scott** [comment] 2017-09-21 19:14
Reporting in to confirm we have the same issue with 1 particular website. We upgrade numerous other websites which are all hosted and essentially the same core setup without problems.

I restored and went through every extension one by one and compare with a working website to make sure nothing was interfering and still got the issue.

Updating from 3.7.5 to 3.8

*I checked other issues linked above and none are related or helped with their suggestions.

As I am out of options I have rolled back to 3.7.5 until this is figured out.

**Comment by wojsmol** [comment] 2017-09-21 19:20
@stepd123 Please check if files `/libraries/src/Version.php` and `/libraries/classmap.php` exists

**Comment by wkumari** [comment] 2017-09-21 19:38
I'm having the same issue. I do have a /libraries/src/Version.php, but it (and factory.php) are both dated Sep 19 -- everyting else in that directory is dated Sep 21 (today).
My classmap.php also exists, and is also dated Sep 19th (as are some other files in that dir):

drwxr-xr-x 29 www-data www-data  4096 Sep 21 15:20 joomla
drwxr-xr-x 16 www-data www-data  4096 Sep 21 15:20 legacy
drwxr-xr-x  5 www-data www-data  4096 Sep 21 15:20 cms
drwxr-xr-x 52 www-data www-data  4096 Sep 21 15:20 src
drwxr-xr-x 12 www-data www-data  4096 Sep 21 15:20 .
-rw-r--r--  1 www-data www-data 40763 Sep 19 08:00 classmap.php
-rw-r--r--  1 www-data www-data  3940 Sep 19 08:00 cms.php
-rw-r--r--  1 www-data www-data  2848 Sep 19 08:00 import.legacy.php
-rw-r--r--  1 www-data www-data  1553 Sep 19 08:00 import.php
-rw-r--r--  1 www-data www-data    31 Sep 19 08:00 index.html
-rw-r--r--  1 www-data www-data 22079 Sep 19 08:00 loader.php
drwx------ 25 www-data www-data  4096 Aug 30 14:55 ..
drwxr-xr-x 11 www-data www-data  4096 Apr 26 09:50 vendor
drwxr-xr-x  2 www-data www-data  4096 May 19  2016 php-encryption
drwxr-xr-x 26 www-data www-data  4096 Apr 21  2015 fof
drwxr-xr-x  2 www-data www-data  4096 Oct  1  2014 phpass
drwxr-xr-x  2 www-data www-data  4096 Oct  1  2014 idna_convert
drwxr-xr-x  5 www-data www-data  4096 Jan 19  2011 phputf8

Possibly of interest (?):
$ grep JVersion classmap.php
JLoader::registerAlias('JVersion',                          '\\Joomla\\CMS\\Version', '5.0');

**Comment by stepd123** [comment] 2017-09-21 19:39
@wojsmol yes I have both files. I don't think I'm missing any files at this point.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18020">issues.joomla.org/tracker/joomla-cms/18020</a>.</sub>

**Comment by Skyla-Scott** [comment] 2017-09-21 19:40
I have attempted to install the full 3.7.5 package again over the original 3.7.5 website and attempt the upgrade again - got the same error. I have tried on this website through various troubleshooting a good 5-8 time.

@wojsmol I checked for those two files exist for me.

Administrator Error after update: 
0 Call to undefined method JVersion::refreshMediaVersion()

error_log entry:
PHP Fatal error:  Cannot declare class JInput, because the name is already in use in /home/XXXXXX/public_html/libraries/fof/input/jinput/input.php on line 39

**Comment by wkumari** [comment] 2017-09-21 20:12
Another datapoint. Running postupdate.php manually brings up:
Call to undefined method JVersion::refreshMediaVersion()

but then clicking on any of the menu items gets:
"Undefined class constant 'PRODUCT'"

**Comment by wojsmol** [comment] 2017-09-21 20:23
@wkumari Please compare https://github.com/joomla/joomla-cms/blob/590fd61dfacabe0f776880864667631ff8ec9014/libraries/classmap.php#L172 with entry in your libraries/classmap.php. in your comment I see `\` instead of `\\`.

**Comment by Skyla-Scott** [comment] 2017-09-21 20:28
Mine has \\\ as expected

It may just have been the comment editor here - I have to put three lines because it strips off one \

**Comment by Skyla-Scott** [comment] 2017-09-21 20:28
I have a doubles - it seemed to have stripped it out in the comment
\\\

**Comment by wkumari** [comment] 2017-09-21 20:34
Yup, sorry, I simply coped and pasted -- didn't realize GH would strip the double slash.
Here it is again: 
`JLoader::registerAlias('JVersion',                          '\\Joomla\\CMS\\Version', '5.0');`

md5sum of classes:
77ca1b48d7199b2164f40cef16c874f4  /var/www/html/kumari.net_old/libraries/classmap.php

**Comment by wojsmol** [comment] 2017-09-21 20:38
@mbabker Any idea about source of this error?

**Comment by mbabker** [comment] 2017-09-21 20:56
1) `JVersion` isn't a "real" class anymore in 3.8 (see all the other comments I've made about the alias stuff), no error message should be using that class name.

2) The fact there is an error message using that class name means it still exists somewhere in the file system (if you can, grep "class JVersion").  The fact that it's not at `libraries/cms/version/version.php` means either some extension overloaded it (that'd be crazy) or you still have a copy of the file from an even older release (except for the 1.5 path none of these paths would be autoloaded, but for completeness), the `JVersion` class was moved to `libraries/cms` at 2.5.0 and stayed there until the namespacing work in 3.8, in 1.7 it was at `includes/version.php`, in 1.6 at `libraries/version.php`, and in 1.5 at `libraries/joomla/version.php`.

**Comment by Skyla-Scott** [comment] 2017-09-21 21:02
Perfect information @mbabker - I have resolved the problem. This was an extremely old website that was upgraded over the years.

I had a `libraries/joomla/version.php`

I removed that file and the backend errors are gone.

A++

**Comment by wkumari** [comment] 2017-09-21 21:05
From my broken site:
$/var/www/html/kumari.net# grep -ri 'class JVersion' *
libraries/joomla/version.php:class JVersion
$ ls -al version.php
-rw-r--r-- 1 www-data www-data 3092 Jan 12  2011 version.php
$ mv version.php ~/tmp/

... and fixed!

From the old version.php (in case it is useful):
<?php
/**
 * @version             $Id: version.php 20261 2011-01-10 19:52:34Z ian $
 * @package             Joomla.Framework
 * @copyright   Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license             GNU General Public License version 2 or later; see LICENSE.txt
 */

**Comment by stepd123** [comment] 2017-09-21 21:21
I also have an old version of that file at \libraries\joomla\version.php

Removing it fixed the errors for me too. Good call @mbabker 

Probably would be a good idea to have Joomla installer check for older versions of that file, or add some kind of error handling. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18020">issues.joomla.org/tracker/joomla-cms/18020</a>.</sub>

**Comment by wojsmol** [comment] 2017-09-21 21:24
@wkumari  and @stepd123 Then use [this](https://github.com/joomla/joomla-cms/issues/18047#issuecomment-331185205) instruction

**Comment by cmirnow** [comment] 2017-09-22 07:09
My site is very old (more than 2000 pages). After the upgrade from J3.7.5 to J3.8, several pages do not open, ERROR 500. Other pages work fine. Any ideas? Guys, I'm really surprised, the work of developers leave much to be desired. I was forced to roll back to the old version, J3.7.5.

**Comment by micker** [comment] 2017-09-22 07:15
for solved with delete /libraries/joomla/version.php

**Comment by cmirnow** [comment] 2017-09-22 07:19
@micker, I do not have this file:

```
$ ls libraries/joomla/
access          cache       document     filesystem  http        linkedin   oauth1         platform.php  twitter
application     client      environment  filter      image       log        oauth2         profiler      updater
archive         controller  event        form        index.html  mail       object         route         uri
association     crypt       facebook     github      input       mediawiki  observable     session       user
authentication  database    factory.php  google      keychain    microdata  observer       string        utilities
base            date        feed         grid        language    model      openstreetmap  table         view
```

**Comment by cmirnow** [comment] 2017-09-22 07:48
Any ideas? I do not use seo-extensions on the site. But after the last update, the site can not work in a normal mode.

**Comment by Webdongle** [comment] 2017-09-22 08:31
> for solved with delete /libraries/joomla/version.php
If that works is there anyway to do that during the update process ?

**Comment by rgtr** [comment] 2017-09-22 09:17
Hi

In answer to these questions:
1) @rgtr On this 2 sites the only problem is related to Components menu?
YES, four are perfectly ok. just the add ons missing - akeeba, jce, mavik, etc
2) @stepd123 Please check if files /libraries/src/Version.php and /libraries/classmap.php exists
YES - both dated 19 Sept 17
3) @franz-wohlkoenig  /libraries/joomla/version.php
I do NOT have this file

I have read issue 18000.
So it seems we have a problem still.

Anyone want the akeeba jpa before upgrade, please let me know.

Richard

**Comment by rgtr** [comment] 2017-09-22 09:51
Hi
I do not have any of these files, the offending sites were started in J1.5

in 2.5 at libraries/cms/version/version.php
in 1.7 at includes/version.php, 
in 1.6 at libraries/version.php, 
in 1.5 at libraries/joomla/version.php.

Richard

**Comment by jsubri** [comment] 2017-09-22 10:51
On a particular site I had the same issue on the backend only "Fatal error: Cannot redeclare class JInput in /libraries/fof/input/jinput/input.php on line 39" . That was an old site migrated continuously since 2007, removing "libraries/joomla/version.php" solved the issue.  I was adding the file in script.php , updated Joomla_3.8.0-Stable-Update_Package.zip and completely re-run the upgrade with "Upload & Update", worked like a charm.

**Comment by Skyla-Scott** [comment] 2017-09-22 11:57
This topic should be closed and resolved so others with unrelated issues can open a new one. This is becoming confusing. 

@stepd123 - can you help closing?

**Comment by ghost** [comment] 2017-09-22 12:02
@Skyla-Scott There are 2 more Issues open to similar Issues: #18033, #18064. I would let this Issue open for a few Days more as it has helpful Comments.

Users can always open a new Issue.

**Comment by Skyla-Scott** [comment] 2017-09-22 12:05
I didn't know it was typical to bundle issues together - this topic had a very specific error a number of us had and was resolved by the exact same root cause. I figured it would be better to keep it clean in that sense but if it works better for others - go at it. I will simply unsubscribe to this topic at this point.

**Comment by mbabker** [comment] 2017-09-22 12:17
Part of the problem is we aren't getting issue reports with substantial data.  The cases where there are error details (like the admin CSS class thing or this JVersion issue) have been able to be addressed, but there are still a lot of people just posting "after update I have a 500 error" and have no error details so they either just file a new issue or find something with a title that sounds like "yep, this is me" and post a "me too" comment.

It really doesn't matter if this item gets closed or not.  It's not going to change much.

**Comment by rgtr** [comment] 2017-09-22 12:29
Hi

We seem to have two issues here. One is that certain files that should not be on site, and I think that is closed.

But my issue is the loss of components from the admin menu - so accessing Akeeba in particular is difficult. I have uninstalled it and JCE.

I ask why we have FOF and why it is locked ...

Richard

**Comment by rgtr** [comment] 2017-09-22 12:34
Hi
I have reinstalled JCE and it is NOT on the component menu.
That means there is something in 3.8 which is preventing this from being added ....
Should I start another issue.
Richard

**Comment by mawdsk** [comment] 2017-09-22 12:50
Hi
My sites are quite old, I wish I had the folders listed but I don't so no simple cure here by deleting a file. Backend errors and front end too :( extracted 3.7.5 back over it and site runs again. Posting to keep an eye on any other ideas. maybe it's time to start anew.

**Comment by romocetra** [comment] 2017-09-22 12:54
@wojsmol Just to know..

After login from backend (/administrator)
I had Fatal error: Cannot redeclare class JInput in /website/public_html/libraries/fof/input/jinput/input.php on line 39

0 I reloaded full version of Joomla on ftp: Joomla_3.8.0-Stable-Full_Package.zip
1 I removed installation folder.
2 Then I use this step as described [here](https://gist.github.com/mbabker/d7bfb4e1e2fbc6b7815a733607f89281#file-readme-md).

On page /administrator/postupdate.php
I had Fatal error: Call to undefined method JVersion::refreshMediaVersion() in /website/public_html/libraries/src/Application/WebApplication.php on line 1064

Now I removed "libraries/joomla/version.php" and now it’s work.

Thank you very much!

**Comment by Webdongle** [comment] 2017-09-22 13:20
This is completely different to #18012 yet that was closed in favour of this.  Big mistake closing #18012

**Comment by simm12** [comment] 2017-09-22 13:26
I am having the same problem.
After updating to Joomla 3.8.0 my website stoped working and I get this message: This page isn’t working
ipsmlb.org is currently unable to handle this request.
HTTP ERROR 500. I even restored the site from Backup, but still I get the same message. Also the on the backend I get the same message.
Please Advise how can I solve the problem. Thank You

**Comment by mawdsk** [comment] 2017-09-22 13:44
Actually just remembered I had a newish unfettled installation buried to test a template style out. Just put the update up over that and the site died, no front or backend. 500 Application Instantiation Error

**Comment by wojsmol** [comment] 2017-09-22 13:51
@mawdsk 

0.  Make sure you have a backup of your site (files and database).
1. Download [this](https://downloads.joomla.org/cms/joomla3/3-8-0/joomla_3-8-0-stable-full_package-zip?format=zip) package
2. Upload it to your site root and extract it  with file manager.
3. Remove installation folder.
4. Remove /libraries/joomla/version.php
5. Then use [this](https://gist.githubusercontent.com/mbabker/d7bfb4e1e2fbc6b7815a733607f89281/raw/4f8bd9cfd2c54f853ca99bae3033586a81f9f236/postupdate.php) file as described [here](https://gist.github.com/mbabker/d7bfb4e1e2fbc6b7815a733607f89281#file-readme-md).

**Comment by ghost** [comment] 2017-09-22 13:55
@Webdongle reopened #18012

**Comment by simm12** [comment] 2017-09-22 14:11
i couldn't find     /version.php

**Comment by mawdsk** [comment] 2017-09-22 14:13
0. already done
1. did do but was scared to update :D 
2. done
3. done
4. didn't have
5. did and message said upgrade to 3.8.0 complete

6. backend works and version correct, all other updates already applied. Front end not running but does with beez3 template so looks like I need to check jsn templates now before updating.

Thanks for that, I'll go investigate further.

**Comment by simm12** [comment] 2017-09-22 14:19
did as instructed, now i have this message on both frontend and backend
: Error displaying the error page

**Comment by wojsmol** [comment] 2017-09-22 14:20
@rgtr Please run https://raw.githubusercontent.com/joomla/joomla-cms/staging/administrator/components/com_admin/sql/updates/mysql/3.7.0-2017-01-17.sql Replace `#__` with table prefix.

**Comment by wojsmol** [comment] 2017-09-22 14:21
@simm12 Frontend and backend?

**Comment by ghost** [comment] 2017-09-22 14:22
@wojsmol thanks for helping.

**Comment by wojsmol** [comment] 2017-09-22 14:23
@franz-wohlkoenig No problem :)

**Comment by simm12** [comment] 2017-09-22 14:23
yes both of them. so how can I restore the website?

**Comment by wojsmol** [comment] 2017-09-22 15:03
@simm12 Plesae check server error log if there any errors.

**Comment by simm12** [comment] 2017-09-22 15:11
yes there are, lots of them

**Comment by wojsmol** [comment] 2017-09-22 15:22
Attach as txt file.

**Comment by rgtr** [comment] 2017-09-22 15:30
wojsmol

Thanks for that.

Will report back on Sunday ...

I take it that these are sql commands to be run in root of database with phpmyadmin
I can cut and paste code one step at a time.

Richard

**Comment by wojsmol** [comment] 2017-09-22 15:36
@rgtr Yes, remember to replace `#__` with table prefix

**Comment by rgtr** [comment] 2017-09-23 10:37
Hi #wojsmol

the script ran fine. 

however, the problem remains ... no  plugins in the components menu.

some more thinking required ....
noted that i changed the table prefix a couple of times with admin tools - and it creates a set of tables with the new prefix leaving the old. so i removed all tables that did not have the current prefix ... 

i have uninstalled akeeba and jce, and reinstalled them ... no change

attached the list of plugins ... is that any help.

none of my menus are called "main" or "menu" .

looks like the solution be a new install. is there a quick way to import menus and text. can copy the media no problem.

richard
[wp38_plugin_list.txt](https://github.com/joomla/joomla-cms/files/1326479/wp38_plugin_list.txt)

**Comment by wojsmol** [comment] 2017-09-23 11:48
@rgtr Please attach dump of #__menu table in sql format.

**Comment by rgtr** [comment] 2017-09-23 12:21
#wojsmaol

attached menu table, and whole database just in case.
had to zip them as that sql format is not allowed

[cl26-wp_290417.zip](https://github.com/joomla/joomla-cms/files/1326524/cl26-wp_290417.zip)
[eqib_menu.zip](https://github.com/joomla/joomla-cms/files/1326525/eqib_menu.zip)

just tried updating from version 3.70 backup ... same so its seems its in the update process

richard

**Comment by rgtr** [comment] 2017-09-23 13:13
#wojsmaol

is the problem that the admin menu rows with capital letter descriptors [JCE etc] are not being read  properly...
very strange

richard

**Comment by wojsmol** [comment] 2017-09-23 13:15
@rgtr Give me chence to check the database 😄

**Comment by rgtr** [comment] 2017-09-23 13:17
@wojsmol 

Sorry - brain in overdrive ....

R

**Comment by rgtr** [comment] 2017-09-23 13:49
@wojsmol 

Hi, have been investigating. 

In the two sites which have lost stuff on the admin components menu both had their prefix changed in admin tools.
[zpdm7_menu.zip](https://github.com/joomla/joomla-cms/files/1326574/zpdm7_menu.zip)

attached the other menu from lp.tdocplus.co.uk

richard

**Comment by wojsmol** [comment] 2017-09-23 16:25
@rgtr On database from https://github.com/joomla/joomla-cms/issues/18020#issuecomment-331630402 run this query
````SQL
UPDATE `#__menu` SET `access` = 1 WHERE `client_id` = 1 AND `menutype` = 'main' AND `access` = 4;
````
Replace #__ with table prefix.

**Comment by wojsmol** [comment] 2017-09-23 16:51
@cmirnow Has your problem been resolved?

**Comment by cmirnow** [comment] 2017-09-23 17:04
@wojsmol Yes, thank you. The decision was unexpected for me. In Joomla 3.8 the old module "DisplayNews by BK" suddenly refused to work (in 3.7.5 it worked fine):

```
Warning: require_once(/public_html/libraries/legacy/table/category.php): failed to open stream: No such file or directory in /public_html/modules/mod_dn/helper.php on line 22

Fatal error: require_once(): Failed opening required '/public_html/libraries/legacy/table/category.php' (include_path='.:/opt/php70/share/pear:/usr/share/pear') in /public_html/modules/mod_dn/helper.php on line 22
```

**Comment by wojsmol** [comment] 2017-09-23 18:11
@cmirnow This module is incompatible with 3.8.0 developer uses `require_once` for files moved to different folder.

**Comment by simm12** [comment] 2017-09-24 07:52
[error log](https://github.com/joomla/joomla-cms/files/1327117/error.log)

**Comment by classicpark** [comment] 2017-09-24 08:41
@franz-wohlkoenig
Please help me out

I did this
@classicpark
1.	Make sure you have a backup of your site (files and database).
2.	Download this package
3.	Upload it to your site root and extract it with file manager.
4.	Remove installation folder.
5.	Then use this file as described here.



I can not find the version.php
in 2.5 at libraries/cms/version/version.php
in 1.7 at includes/version.php,
in 1.6 at libraries/version.php,
in 1.5 at libraries/joomla/version.php.


But still having errors

Error: 0 Call to undefined method JAdminCssMenu::addChild()
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by wojsmol** [comment] 2017-09-24 08:45
@simm12 Do you haqve a recent backup taken before update? If yes will go with little risky procedure.

**Comment by ghost** [comment] 2017-09-24 08:49
@classicpark @wojsmol and others can help you more than me as i'm user, no Dev.

**Comment by wojsmol** [comment] 2017-09-24 08:50
@classicpark Do you use sp page builder?

**Comment by classicpark** [comment] 2017-09-24 09:01
@wojsmol 
Yes i have sp page builder but did not use it for a long time (;
And i never did make something with it so how can i delete it now i can not use my admin panel

In my database i found one table named sppagebuilder
Amd on de server there is one dir under components/com_sppagebuilder and by admin also under components/com_sppagebuilder
Can i dele those incl the database table?

**Comment by wojsmol** [comment] 2017-09-24 09:10
@classicpark See [this](https://www.joomshaper.com/forums/mod-sppagebuiler-problems-after-upgrade-with-joomla-3-8#reply-103939) post. After accessing back-en uinstaall or update sp page builder.

**Comment by classicpark** [comment] 2017-09-24 09:19
@wojsmol  thank you so mutch that fixed the problem .
Final qestion if i delete sp page builder bij joomla admin than is the problem gone for in the future also i never realy used it

**Comment by wojsmol** [comment] 2017-09-24 09:28
@classicpark There is simple rule: If you don't use same extension, then make backup and of the site uninstall it. You can delete error.log from your reply in you wont.

**Comment by rgtr** [comment] 2017-09-24 10:15
@wojsmol

that worked 

thank you so much

richard

**Comment by swishimage** [comment] 2017-09-25 07:51
Hi guys, (i'm desperate!)
I ran the Joomla 3.8 update and it's broken the site/connection to the localhost MAMP.
This site was using SP Pagebuilder and I now can NOT see the Front/ or Backend login page.
All I get now for both the front and backend is:
Error displaying the error page
On my localhost (MAMP), I updated it from Joomla 3.7.5.
I normally backup using AKEEBA, but this one time I have stuffed up and didn't back up.

IS THE FOLLOWING POSSIBLE:
I am on a MAC, so I tried using Time Machine to go back a week and recall the 'site' and 'database' folders, but I have tried several ways unsuccessfully - including deleting my MAMP folder in Applications and bringing back last weeks version of the folder (pre the update)... 
When I do this... it stopped MySQL working. In MAMP, after I delete the ib_logfile0, ib_logfile0, ibdata1 in MAMP - DB folder, I can get MYSQL to start, and I can install a completely new test site and everything works, but with the site I was building for the past 3 weeks - I get
    'Error displaying the error page'.
I did get HTTP ERROR 500 after updating joomla 3.8 at one stage, but after recalling the older version of the site back... I now only get 'Error displaying the error page'.
I also have another site (that is NOT using SP Pagebuilder) and I now get on this site:
    "Error displaying the error page: Application Instantiation Error: Table 'acwhalan.#__session' doesn't exist SQL=SELECT `session_id` FROM `#__session` WHERE `session_id` = '4773dcce42ab0ac63edd23c4974df369' LIMIT 1"

I am SO desperate to get this fixed ASAP.
What has this 3.8 update done... as it was all working fine last week.

So my question is... can I recover/restore this website (if I have NOT used a backup component like AKEEBA) by going back in time (using Time Machine on my MAC) and restoring the 'Document Root directory' (site files) and the Database (in the DB folder in MAMP), or are there other directories I need to recover this... as this hasn't worked for me so far?
 
Are the only 2 files that Joomla requires to run a site are the:
'Document Root directory' (site files) and the Database (in the DB folder in MAMP)?

Thanks,
Syco

**Comment by brianteeman** [comment] 2017-09-25 07:59
> So my question is... can I recover/restore this website (if I have NOT used a backup component like AKEEBA) by going back in time (using Time Machine on my MAC) and restoring the 'Document Root directory' (site files) and the Database (in the DB folder in MAMP), or are there other directories I need to recover this... as this hasn't worked for me so far?

Yes that should work.

When you say it doesnt work what happens

**Comment by mawdsk** [comment] 2017-09-25 07:59
@swishimage the only think that seems to work for my sites is to extract the 3.7.5 update over your site and mine all ran again both front and back

**Comment by wojsmol** [comment] 2017-09-25 09:02
@franz-wohlkoenig and others: I'm on work today so my replays may be delayed.

**Comment by swishimage** [comment] 2017-09-25 13:59
Hi Brian,

Thank you for the reply. When I say it doesn't work... After the roll back of both the MAMP Folder and the 'Sites' (root or htdocs)... 

I just get the following message -for both Frontend and also the Backend Admin login... so I can't even login to do any suggested fixes?
> Error displaying the error page<

**Comment by ghost** [comment] 2017-09-25 14:03
@swishimage which Template you use?

**Comment by wojsmol** [comment] 2017-09-25 14:05
@swishimage Please set `$error_reportong='maximum'` in configuration.php and post displayed errors.

**Comment by swishimage** [comment] 2017-09-25 14:06
It's the wheeler template - which uses SP Pagebuilder.
http://preview.themeforest.net/item/wheeler-taxi-company-cab-service-joomla-template/full_screen_preview/19299937?_ga=2.188337704.1469584736.1496124773-1706854449.1475126167

**Comment by swishimage** [comment] 2017-09-25 14:07
Where do I find this if I can't log in?
> Please set $error_reportong='maximum' and post errors

**Comment by wojsmol** [comment] 2017-09-25 14:08
@swishimage See updated https://github.com/joomla/joomla-cms/issues/18020#issuecomment-331891725

**Comment by ghost** [comment] 2017-09-25 14:09
@swishimage there are known Issues by SP Pagebuilder (in other Threads) and also with different Templates (also other Threads).

**Comment by swishimage** [comment] 2017-09-25 14:10
I'm that desperate.. I'd be happy to pay someone... if they want to login remotely with Team Viewer to check it out  :(

**Comment by swishimage** [comment] 2017-09-25 14:12
> @swishimage there are known Issues by SP Pagebuilder (in other Threads) and also with different Templates (also other Threads).

Yes... i read some of them, but SP support will not respond to me contacting them about the issue.
One thing... I do have another site (not using SP Pagebuilder) and I get the following error:

_Error displaying the error page: Application Instantiation Error: Table 'acwhalan.#__session' doesn't exist SQL=SELECT `session_id` FROM `#__session` WHERE `session_id` = '071303cd7e1d0c1ec33f203a6d8b1dd1' LIMIT 1_

**Comment by swishimage** [comment] 2017-09-25 14:18
With the SP Pagebbuilder site (Wheeler)...I did try deleting the the configuration.php file.. then copied the installation folder from the Wheeler Template and reinstalled ... and this DOES allow me to see and log into the back end. The only issue is when I do this is all the components like SP Pagebuilder are missing and the site looks like the default Joomla site. I then got 'errors' when trying to install the individual components that were missing.

**Comment by wojsmol** [comment] 2017-09-25 14:18
@swishimage Checki if $dbprefix in configuration.php is correct.

**Comment by wojsmol** [comment] 2017-09-25 14:20
Restore deleted configuration.phh and see https://github.com/joomla/joomla-cms/issues/18020#issuecomment-331895721

**Comment by swishimage** [comment] 2017-09-25 14:24
`Restore deleted configuration.phh and see #18020 (comment)`

I've restored the whole MAMP folder bback to PRE 3.8.0, and the 'htdocs' folder, but I don't get a login page... or frontend. It's like there's something else broken??

I guess I will try restoring the MAMP again - using Time Machine on my MAC tomorrow... nearly 1am need some sleep  :)  Thanks for the quick replies. I will come back to let you know how it goes.

**Comment by wojsmol** [comment] 2017-09-25 14:31
````
_Error displaying the error page: Application Instantiation Error: 
Table 'acwhalan.#_session' doesn't exist SQL=SELECT session_id FROM #__session WHERE session_id = '071303cd7e1d0c1ec33f203a6d8b1dd1' LIMIT 1
````
I'm referring this database error.

**Comment by Webdongle** [comment] 2017-09-25 18:01
Perhaps individual help is best dealt with in the forums not in error reporting ?

**Comment by wojsmol** [comment] 2017-09-25 18:37
@Webdongle As you can see I'm recently quite active on forum, so if you wont we can close this issue and redirect to forum as always.

**Comment by ghost** [comment] 2017-09-25 18:42
closed as stated above<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18020">issues.joomla.org/tracker/joomla-cms/18020</a>.</sub>

**Closed as completed by ghost** 2017-09-25 18:42 UTC
Labels: No Code Attached Yet

**Comment by wojsmol** [comment] 2017-09-25 18:50
@Webdongle Additionally god idea we should add few items to release FAQ to reduce number of new forum topics.

**Comment by Webdongle** [comment] 2017-09-25 18:55
A FAQ would be a good idea but I dont understand the problem enough to write one.  There are that many posts in the forum where the failure is down to 3rd party extensions/templates that its difficult to see what the real bug is ... let alone the work around until the devs bring out 3.8.1 that updates correctly.

**Comment by wojsmol** [comment] 2017-09-25 19:10
@Webdongle IMHO the main issue is amount of files deleted is script.php and the problems with extracting or downloading the update package.

**Comment by Webdongle** [comment] 2017-09-25 20:46
@wojsmol 
IMHO "_problems with extracting or downloading the update package_" are due to bad (or insufficient) server settings.

**Comment by wojsmol** [comment] 2017-09-25 21:14
@Webdongle Yes, you are right, but we must somehow resolve the issue. @Kubik-Rubik developed nice standalone script  to check filesystem state, but it is incompatible with Joomla 3.8.0, no checksums. This would be nice tool when helping on forum.

**Comment by simm12** [comment] 2017-09-26 19:53
I have a backup dated 20-09-2017 one day before the update.

**Comment by wojsmol** [comment] 2017-09-26 23:16
@simm12 Please create topic on forum [here](https://forum.joomla.org/viewforum.php?f=710)  As sugeststed by @Webdongle [here](https://github.com/joomla/joomla-cms/issues/18020#issuecomment-331963234) this issue is now closed.

**Comment by PawelSzymanski89** [comment] 2018-09-27 11:33
Try this: 
youradress.com/administrator/index.php?option=com_installer&task=database.fix
