### ISSUE TITLE
Language Plugin: Language Suffix Persists After Removing It in Settings

### ISSUE THREAD

**Issue by Stuartemk** [joomla/joomla-cms#44341] opened 2024-10-22 20:38 UTC
### Steps to reproduce the issue
Install Joomla 5.2
Activate the language plugin
Configure the "Remove Language Suffix" option in the plugin settings.
Access a page in a specific language (for example, misitio.com/en). The URL will display correctly as misitio.com.
Change the language using the language change module or set the site's language to the browser's language.

### Expected result

The URL should remain without the language suffix (misitio.com) regardless of the selected language.

### Actual result
The language suffix reappears in the URL (misitio.com/es) after changing the language.

### System information (as much as possible)

Joomla version: 5.2

### Additional comments
This inconsistency creates confusion for users and contradicts the plugin's configuration setting to remove the language suffix.

**Comment by Hackwar** [comment] 2024-10-23 10:06
The languagefilter plugin allows to hide the language suffix for the default language, but not for all languages. This is expected behavior, since otherwise you wouldn't be able to provide a link to content in a specific language. Since this is expected behavior, I'm closing this one.

**Closed as completed by Hackwar** 2024-10-23 10:06 UTC
Labels: No Code Attached Yet

**Comment by Stuartemk** [comment] 2024-10-24 03:27
> El complemento languagefilter permite ocultar el sufijo de idioma para el idioma predeterminado, pero no para todos los idiomas. Este es el comportamiento esperado, ya que de lo contrario no podría proporcionar un enlace a contenido en un idioma específico. Dado que este es el comportamiento esperado, voy a cerrar este.

Give me an example

On a single language site the language switching module doesn't make sense, and on a multilingual site, the categories are translated and associated for the articles, so any url is unique, so for example if you share a url https://mysite.com/recipes/bread what you want is for it to take you to https://mysite.com/recipes/bread

But if you share https://mysite.com/recipes/bread you want it to take you to https://mysite.com/recipes/bread

So each url is unique

I don't find any sense to what you say on a multilingual site, however, if you give me a good example maybe your answer will help in that case, but if we evaluate the possibilities then there are more possibilities of use in the way I give you the example.
