### ISSUE TITLE
Newsfeed component stopped working after upgrade

### ISSUE THREAD

**Issue by techfry** [joomla/joomla-cms#38531] opened 2022-08-19 09:29 UTC
### Steps to reproduce the issue

Navigate to news feed component. Create a new feed item. You can add this: https://www.joomla.org/announcements.feed?type=rss

Create a menu item for the same to view in the frontend. 

### Expected result

The page should display content from the feed.

### Actual result

In Joomla ! 4.1.5, it was working. After updating to 4.2, error is coming - String could not be parsed as XML

### System information (as much as possible)

No third-party extensions installed.

**Comment by rdeutz** [comment] 2022-08-19 09:50
Confirmed on 4.2dev

**Comment by rdeutz** [comment] 2022-08-19 12:25
Closing because it is fixed with #38312

**Closed as completed by rdeutz** 2022-08-19 12:25 UTC
Labels: No Code Attached Yet, bug
