### ISSUE TITLE
Outgoing RSS Feed for created articles

### ISSUE THREAD

**Issue by web-eau-net** [joomla/joomla-cms#30264] opened 2020-08-03 08:28 UTC
### Steps to reproduce the issue
- Create an article in a category 
- Setup a publishing date in the future for this article
- Access to the RSS Feed of this category, the article is visible

### Expected result
- The RSS Feed must be updated only when an article is published, not created.

### Actual result
- The outgoing RSS feed is updated when an article is created (or added) in a category

### System information (as much as possible)
- Joomla 3.9.20

**Comment by brianteeman** [comment] 2020-08-03 09:09
Ouch that would be really bad as it could result in confidential data being exposed eg product launch information before the embargo date.

However I just tested this and was not able to replicate the issue.

![image](https://user-images.githubusercontent.com/1296369/89166115-71790a00-d571-11ea-8023-7411b7b25323.png)

![image](https://user-images.githubusercontent.com/1296369/89166125-75a52780-d571-11ea-9940-f4d3d4353214.png)

**Comment by web-eau-net** [comment] 2020-08-03 09:35
Ok, thanks for your reply but I've also tested and I see an upcoming article in my RSS feed:

- https://www.web-eau.net/blog?format=feed&type=rss: <title>10 exemples de Header pour vous inspirer</title>

This article will be publish in 2 days (05 August) and shouldn't be available here.

Here is a screenshot from my RSS Feed agregator where this upcoming article is also available:

<a href="https://ibb.co/p0vYP3k"><img src="https://i.ibb.co/GxvzJVr/erruer-rss-joomla-agregateur.png" alt="erruer-rss-joomla-agregateur" border="0"></a><hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30264">issues.joomla.org/tracker/joomla-cms/30264</a>.</sub>

**Comment by web-eau-net** [comment] 2020-08-03 09:49
Edit: the article was in my RSS Feed because I was login as admin on frontend. A public user don't see it.

However, this article shouldn't be available in any RSS Feed agregator (see screenshot posted earlier).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30264">issues.joomla.org/tracker/joomla-cms/30264</a>.</sub>

**Comment by ReLater** [comment] 2020-08-03 13:47
The feed view uses (nearly) the same database queries like the related html view (category blog or list...). Feed uses the same model. Category blog or list display also unpublished articles when you are logged in as Admin or SuperUser in the frontend if you don't suppress that via template overrides.

I would say: Not an issue, this issue.

**Comment by brianteeman** [comment] 2020-08-03 13:51
> I would say: Not an issue, this issue.

agreed

**Comment by web-eau-net** [comment] 2020-08-03 14:17
You may be agree but this not explain why this upcoming article is displayed by the RSS aggregator.
It shouldn't be and must be fixed.

**Comment by ReLater** [comment] 2020-08-03 14:21
You said

> Edit: the article was in my RSS Feed because I was login as admin on frontend. A public user don't see it.

Therefore it's not a bug but the expected behavior if you see these articles in the same browser that your login runs on.

**Comment by ReLater** [comment] 2020-08-03 14:22
> but this not explain why this upcoming article is displayed by the RSS aggregator.

See https://github.com/joomla/joomla-cms/issues/30264#issuecomment-668032478 , please

**Comment by web-eau-net** [comment] 2020-08-03 14:31
> > but this not explain why this upcoming article is displayed by the RSS aggregator.
> 
> See [#30264 (comment)](https://github.com/joomla/joomla-cms/issues/30264#issuecomment-668032478) , please

Because you can create an article today and finish to write it in few days, what happen if someone click on the RSS Feed generated when the article is created but no published? A 404. 
The outgoing RSS Feed **must** be generated by Joomla only when the article is **published**, not created 
I don't think it's so complicated to do.

**Comment by web-eau-net** [comment] 2020-08-03 14:32
> You said
> 
> > Edit: the article was in my RSS Feed because I was login as admin on frontend. A public user don't see it.
> 
> Therefore it's not a bug but the expected behavior if you see these articles in the same browser that your login runs on.

Thank you, I've understood this earlier.
The point is not here, please read my previous comment :)

**Comment by web-eau-net** [comment] 2020-08-03 14:52
Article created as example with these parameters:
<a href="https://imgbb.com/"><img src="https://i.ibb.co/qFSgywN/test-rss-article.png" alt="test-rss-article" border="0"></a>

Article displayed in the RSS Feed aggregator:
<a href="https://imgbb.com/"><img src="https://i.ibb.co/QQtBBqw/test-rss-feed.png" alt="test-rss-feed" border="0"></a>

I'm not sure but I'ts not a normal behaviour... 
Thankds in advance to consider this issue.

**Comment by ReLater** [comment] 2020-08-03 14:58
What is this "RSS Feed aggregator"?

**Comment by brianteeman** [comment] 2020-08-03 16:50
I can not replicate the problem you are describing. The rss feed **you**  are seeing when logged in as an admin can never be seen by anyone else. The rss feed reader is looking at your site as a guest.

**Comment by brianteeman** [comment] 2020-11-25 10:30
This should be closed as not reproducible

**Comment by HLeithner** [comment] 2020-11-25 13:09
@web-eau-net since it's not replicate able I'm closing this, if you still see this as a bug please reopen and add the "RSS Feed Aggreator" you are using. Thanks

**Closed as completed by HLeithner** 2020-11-25 13:09 UTC
Labels: No Code Attached Yet
