### ISSUE TITLE
[4.0] Impossible to add image in editor from media manager

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29660] opened 2020-06-16 23:09 UTC
### Steps to reproduce the issue

Joomla 4.0.0 beta 1
Go to edit an article
Click the `CMS Content` button in the WYSIWYG Editor

NOTE RIGHT HERE YOU GET YOUR FIRST console.log error message 

```
Error: <path> attribute d: Expected number, "…4.99-12 10zM2224h-18v-12h3.934c0…" <truncated>
```

Select an image
Click insert image

### Expected result

Image inserted

### Actual result

No image inserted

Console.log Errors... 

<img width="1602" alt="Screenshot 2020-06-17 at 00 09 18" src="https://user-images.githubusercontent.com/400092/84836978-d06cd900-b02e-11ea-80db-3ca8e036fa38.png">

```
[Error] Error: Problem parsing d="M8 20c0 0 1.838-6 12-6v6l12-8-12-8v6c-8 0-12 4.99-12 10zM2224h-18v-12h3.934c0.315-0.372 0.654-0.729 1.015-1.068 1.374-1.287 3.018-2.27 4.879-2.932h-13.827v20h26v-8.395l-4 2.667v1.728z"
	each (theme.min.js:9:2066)
	Li (theme.min.js:9:34652)
	Xi (theme.min.js:9:36488)
	(anonymous function) (theme.min.js:9:37749)
	V (theme.min.js:9:4239)
	Xi (theme.min.js:9:36322)
	(anonymous function) (theme.min.js:9:37749)
	V (theme.min.js:9:4239)
	Xi (theme.min.js:9:36322)
	(anonymous function) (theme.min.js:9:37749)
	V (theme.min.js:9:4239)
	Xi (theme.min.js:9:36322)
	(anonymous function) (theme.min.js:9:37749)
	(anonymous function) (theme.min.js:9:102570)
	(anonymous function) (theme.min.js:9:5867)
	(anonymous function) (theme.min.js:9:5936)
	ft (theme.min.js:9:5799)
	mt (theme.min.js:9:5912)
	e (theme.min.js:9:102316)
	(anonymous function) (theme.min.js:9:105323)
	run (theme.min.js:9:24417)
	(anonymous function) (theme.min.js:9:30225)
	(anonymous function) (theme.min.js:9:154454)
	Ab (theme.min.js:9:154801)
	triggerEvent (theme.min.js:9:157449)
	Go (theme.min.js:9:23940)
	Lo (theme.min.js:9:23746)
	As (theme.min.js:9:65531)
	Vs (theme.min.js:9:66050)
	Rs (theme.min.js:9:65947)
	Us (theme.min.js:9:66725)
	Ws (theme.min.js:9:66772)
	(anonymous function) (theme.min.js:9:173099)
	(anonymous function) (theme.min.js:9:173029)
	promiseReactionJob
[Error] TypeError: Joomla.getImage is not a function. (In 'Joomla.getImage(Joomla.selectedFile, 'jform_articletext')', 'Joomla.getImage' is undefined)
	onclick (index.php:360)
```

### System information (as much as possible)

Reproduced in Safari and Google Chrome on Mac.

**Comment by infograf768** [comment] 2020-06-17 07:48
Confirmed. Setting as release blocker.

**Comment by wilsonge** [comment] 2020-06-17 10:14
I think this was fixed by https://github.com/joomla/joomla-cms/pull/29323 already as I can't reproduce this on nightly (using chrome or safari on Mac).

The original JS notice when you click on the menu item isn't fixed (although functionally doesn't cause issues) so removing release blocker tag

**Comment by PhilETaylor** [comment] 2020-06-17 10:18
Maybe its time for another beta then if people are being asked to test the beta but most of the issues are resolved in git only.... #justsaying

**Comment by infograf768** [comment] 2020-06-17 10:19
@wilsonge
My test are always in 4.0-dev. not beta

**Comment by brianteeman** [comment] 2020-06-17 10:20
thats why we have nightly releases

**Comment by PhilETaylor** [comment] 2020-06-17 10:20
I can replicate this in 4.0-dev @ 00a94b6e0fb526e2384acec35c3c3644d2f1f5dd

**Comment by PhilETaylor** [comment] 2020-06-17 10:23
Correction: The Image can be added now, but the other console log error message still happens. 

<img width="1599" alt="Screenshot 2020-06-17 at 11 22 50" src="https://user-images.githubusercontent.com/400092/84886875-e6a98200-b08c-11ea-9a54-ad6dfc7449b4.png">

**Comment by infograf768** [comment] 2020-06-17 10:23
<img width="1566" alt="Screen Shot 2020-06-17 at 12 20 55" src="https://user-images.githubusercontent.com/869724/84886752-1b213c00-b095-11ea-97c9-8f7f613e005f.png">

Image can be inserted btw after patching with https://github.com/joomla/joomla-cms/pull/29675
To test, make sure btw that safari cache is cleared

**Comment by Quy** [comment] 2020-07-03 02:55
@PhilETaylor Can you still replicate this? Thanks.

**Comment by PhilETaylor** [comment] 2020-07-03 07:40
As said before - after #29675 its possible to insert and image - however console.log errors still occur.

Its no longer a release blocker but is still an issue. 



```
[Error] Error: Problem parsing d="M8 20c0 0 1.838-6 12-6v6l12-8-12-8v6c-8 0-12 4.99-12 10zM2224h-18v-12h3.934c0.315-0.372 0.654-0.729 1.015-1.068 1.374-1.287 3.018-2.27 4.879-2.932h-13.827v20h26v-8.395l-4 2.667v1.728z"
	each (theme.min.js:9:2066)
	Li (theme.min.js:9:34652)
	Xi (theme.min.js:9:36488)
	(anonymous function) (theme.min.js:9:37749)
	V (theme.min.js:9:4239)
	Xi (theme.min.js:9:36322)
	(anonymous function) (theme.min.js:9:37749)
	V (theme.min.js:9:4239)
	Xi (theme.min.js:9:36322)
	(anonymous function) (theme.min.js:9:37749)
	V (theme.min.js:9:4239)
	Xi (theme.min.js:9:36322)
	(anonymous function) (theme.min.js:9:37749)
	(anonymous function) (theme.min.js:9:102570)
	(anonymous function) (theme.min.js:9:5867)
	(anonymous function) (theme.min.js:9:5936)
	ft (theme.min.js:9:5799)
	mt (theme.min.js:9:5912)
	e (theme.min.js:9:102316)
	(anonymous function) (theme.min.js:9:105323)
	run (theme.min.js:9:24417)
	(anonymous function) (theme.min.js:9:30225)
	(anonymous function) (theme.min.js:9:154454)
	Ab (theme.min.js:9:154801)
	triggerEvent (theme.min.js:9:157449)
	Go (theme.min.js:9:23940)
	Lo (theme.min.js:9:23746)
	As (theme.min.js:9:65531)
	Vs (theme.min.js:9:66050)
	Rs (theme.min.js:9:65947)
	Us (theme.min.js:9:66725)
	Ws (theme.min.js:9:66772)
	(anonymous function) (theme.min.js:9:173099)
	(anonymous function) (theme.min.js:9:173029)
	promiseReactionJob
```

**Comment by Quy** [comment] 2020-07-03 16:12
Reproducible in Chrome but not Firefox.

**Comment by PhilETaylor** [comment] 2020-07-03 16:18
Dont panic, its only been broken for 15 months :) I have the fix :-)

**Comment by PhilETaylor** [comment] 2020-07-03 16:22
PR #29935

**Comment by alikon** [comment] 2020-07-03 16:23
please test #29935

**Closed as completed by alikon** 2020-07-03 16:23 UTC
Labels: No Code Attached Yet
