### ISSUE TITLE
Batch copied 2x the item to new destination (IE11)

### ISSUE THREAD

**Issue by 810** [joomla/joomla-cms#4511] opened 2014-10-10 22:40 UTC
#### Steps to reproduce the issue

backend - menus - select menu item- click batch - select copy - change destination- run batch Then you see 2x times the menu item on the destination. ... on IE11

#### Expected result

Just copy the item 1 time

#### Actual result

Its copied 2x

#### System information (as much as possible)

Effects only IE

#### Additional comments

http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=33817&start=0

**Comment by brianteeman** [comment] 2015-11-12 17:24
It has been over a year since the last comment on this issue. Can anyone still replicate this with the current release of Joomla or has it been resolved elsewhere?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4511">issues.joomla.org/joomla-cms/4511</a>.</sub>

**Comment by 810** [comment] 2015-11-12 17:45
The bug is still there.

J35B1
Win10 IE11

**Comment by brianteeman** [comment] 2015-11-12 18:38
Thanks for confirming - setting status back to confirmed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4511">issues.joomla.org/joomla-cms/4511</a>.</sub>

**Comment by Simonkloostra** [comment] 2016-04-15 13:55
I can also confirm the issue still happens, both in IE11 and Edge (On Windows 10)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4511">issues.joomla.org/joomla-cms/4511</a>.</sub>

**Comment by Iclamer** [comment] 2016-04-15 14:10
Bug still exits on Win 8.1 IE 11 & Edge and on Win 10 IE 11 & Edge<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4511">issues.joomla.org/joomla-cms/4511</a>.</sub>

**Comment by 810** [comment] 2016-04-15 14:19
ok, now I'm getting some errors on the staging build:

Warning: Header may not contain more than a single header, new line detected in C:\wamp\www\develop\libraries\joomla\application\web.php on line 959

Error
 
An error has occurred.

1062 Duplicate entry '0-1-xwsxw-2-*' for key 'idx_client_id_parent_id_alias_language' SQL=INSERT INTO `#__menu` (`parent_id`,`level`,`lft`,`rgt`,`alias`,`id`,`menutype`,`title`,`note`,`path`,`link`,`type`,`published`,`component_id`,`checked_out`,`checked_out_time`,`browserNav`,`access`,`img`,`template_style_id`,`params`,`home`,`language`,`client_id`) VALUES ('1','1','137','138','xwsxw-2','0','mainmenu','xwsxw (2)','','xwsxw','index.php?option=com_content&view=article&id=1','component','1','22','0','0000-00-00 00:00:00','0','1',' ','0','{\"show_title\":\"\",\"link_titles\":\"\",\"show_intro\":\"\",\"info_block_position\":\"\",\"show_category\":\"\",\"link_category\":\"\",\"show_parent_category\":\"\",\"link_parent_category\":\"\",\"show_author\":\"\",\"link_author\":\"\",\"show_create_date\":\"\",\"show_modify_date\":\"\",\"show_publish_date\":\"\",\"show_item_navigation\":\"\",\"show_vote\":\"\",\"show_icons\":\"\",\"show_print_icon\":\"\",\"show_email_icon\":\"\",\"show_hits\":\"\",\"show_tags\":\"\",\"show_noauth\":\"\",\"urls_position\":\"\",\"menu-anchor_title\":\"\",\"menu-anchor_css\":\"\",\"menu_image\":\"\",\"menu_text\":1,\"menu_show\":1,\"page_title\":\"\",\"show_page_heading\":\"\",\"page_heading\":\"\",\"pageclass_sfx\":\"\",\"menu-meta_description\":\"\",\"menu-meta_keywords\":\"\",\"robots\":\"\",\"secure\":0}','0','*','0')   
 
Warning: session_write_close(): Failed to write session data (user). Please verify that the current setting of session.save_path is correct (C:/wamp/tmp) in C:\wamp\www\develop\libraries\joomla\session\handler\native.php on line 192

**Comment by Kubik-Rubik** [comment] 2016-05-08 14:17
Hi @810! You created this issue sometime ago but have not provided any code for people to evaluate. As no one else has shown any interest in providing the code and you have not, then I am closing this issue at this time. If code is provided (a pull request) it can always be re-examined. Thank you!

**Closed by Kubik-Rubik** 2016-05-08 14:17 UTC
Labels: No Code Attached Yet
