### ISSUE TITLE
Versioning ignores all CustomFields 

### ISSUE THREAD

**Issue by hytsch** [joomla/joomla-cms#44130] opened 2024-09-24 09:32 UTC
### Steps to reproduce the problem
Save a post (and create a new version)
Change a value in a custom field
### Expected result
The system updates the modification date and creates a new version
### Actual result
The system updates the modification date and does not create a new version 

### System information (as far as possible)
j 5.1.4 php 8.3

### Additional comments
CustomFields are a powerful and central component. For the user it does not matter whether a field is a CoreField or a CustomField, most content managers do not even know the difference. For developers or supporters, this situation means a shortcoming: for websites in which essential content is also stored in CustomFields, the versioning that does not take effect is as if it did not even exist.
Wouldn't it even be possible to optionally decide for each CustomField whether or not it is taken into account by versioning? - That would be very nice!

**Comment by Quy** [comment] 2024-09-24 13:43
Closing as duplicate of #39217

**Closed as completed by Quy** 2024-09-24 13:43 UTC
Labels: No Code Attached Yet
