### ISSUE TITLE
Mod_menu basic entry not working

### ISSUE THREAD

**Issue by shoffmann90** [joomla/joomla-cms#17794] opened 2017-08-31 08:23 UTC
### Steps to reproduce issue
I have created a new menu with some menu headings. Now I have made some menu aliases under these menu headings. Further I have created a menu module (mod_menu) and tried to set one menu heading in the new menu as a basic entry. So I pressed the select button. 

### Expected result
A window should appear which shows all menu items in my menu.

### Actual result
The window (Select or Change Menu Item)shows only 3 items instead of the default 20. There is more than one page. On each page there are many items missing. Not one menu headding is shown.

### System information (as much as possible)
Joomla was updated to Joomla! 3.7.5
I guess the error exists at least since the Joomla 3.5 update

### Additional comments
Please help me ;-)

![screen shot 2017-08-31 at 08 24 54](https://issues.joomla.org/uploads/1/e0ff8e0a041fcc1d6d454e6cb80f28ee.jpg)

**Comment by tonypartridge** [comment] 2017-08-31 22:52
Looks like a duplicate of issue #17726

**Comment by ghost** [comment] 2017-09-01 05:06
@tonypartridge looks similaer, @shoffmann90 can you please look at #17726 if its a duplicate and close your Issue if so?

**Comment by shoffmann90** [comment] 2017-09-01 06:13
The issue may be the same origin, but it affect the menu heading as well as the text separator. In my case the menu items should not be hidden rather they should be selectable. Should I close it anyway? The only workaround for now is to set the item in the module table of the database. But for our normal joomla user this isn't an option. Do you have an idea how to fix it?

**Comment by ghost** [comment] 2017-09-01 06:22
@shoffmann90 if its a different Issue please don't close, otherwise close, thanks.

**Comment by brianteeman** [comment] 2017-09-27 23:10
The issue is the same. Its the same piece of code that is effecting this and I will try to work on a fix for this soon. I am going to close this one  for now

**Closed as completed by brianteeman** 2017-09-27 23:10 UTC
Labels: No Code Attached Yet
