### ISSUE TITLE
Pagination issues when unset items at getItems()

### ISSUE THREAD

**Issue by itsam** [joomla/joomla-cms#6645] opened 2015-04-03 11:58 UTC
#### Steps to reproduce the issue
At any component /models/bars  <-- bars is the plural of model bar (could be articles or whatever)

Unset some (or all for example's sake) items at **public function getItems()**

    for ($x = 0, $count = count($items); $x < $count; $x++)
    {
        unset($items[$x]);
    }

#### Expected result
I would expect the pagination to contain no pages 

#### Actual result
Depending on the number of items before unset varies from 1 to N pages

#### System information (as much as possible)
Joomla 3.4.1 
definitely occurs on previous versions as well

#### Additional comments
I suspect that JModelList "calculates" pagination taking into account only the getListQuery and not the getItems() of the model

Is this normal?

**Comment by laoneo** [comment] 2015-10-05 14:36
Because of performance reasons it tries to return only the count of the records as seen here https://github.com/joomla/joomla-cms/blob/staging/libraries/legacy/model/legacy.php#L326 in a second db call. If that is not possible it does a second query, getting all the items. So this behavior is expected.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6645">issues.joomla.org/joomla-cms/6645</a>.</sub>

**Comment by brianteeman** [comment] 2016-01-28 13:14
Closing as expected behaviour based on the comment above<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6645">issues.joomla.org/joomla-cms/6645</a>.</sub>

**Closed by brianteeman** 2016-01-28 13:14 UTC
Labels: No Code Attached Yet
