### ISSUE TITLE
You need MariaDB 10.4 or higher to continue the installation

### ISSUE THREAD

**Issue by lipatovroman** [joomla/joomla-cms#42159] opened 2023-10-18 10:16 UTC
Hello!
I'm trying to install Joomla 5.
Getting message, that I can't install it with this error:

**You need MariaDB 10.4 or higher to continue the installation. Your version is: 10.1.48-MariaDB-0+deb9u2**

I'm confused, because I'm using MySQL DB.

I think Joomla can't work with two different databases at the same time...

**Comment by brianteeman** [comment] 2023-10-18 11:54
You can't be or Joomla would not have been able to detect that specific mariadb versionn info

**Comment by richard67** [comment] 2023-10-18 12:59
The database credentials entered in the installation form are used to connect to the database, and then the version string is obtained from the database. So if it returns `10.1.48-MariaDB-0+deb9u2` then it's clearly a MariaDB (which is compatible with but not the same as MySQL).

What you mean with "I'm using MySQL DB" is maybe that you have selected "MySQLi" or "MySQL (PDO)" as database type in the installation form. This was right, there is no special database client for MariaDB, and the MySQL client is used.

As said, the database you have specified to use is clearly a MariaDB, and for that Joomla 5 requires version 10.4. Your version 10.1.48 is too low.

**Comment by richard67** [comment] 2023-10-18 13:01
Closing as expected behaviour for the reason stated above.

**Closed as completed by richard67** 2023-10-18 13:01 UTC
Labels: No Code Attached Yet

**Comment by lipatovroman** [comment] 2023-10-18 18:26
> As said, the database you have specified to use is clearly a MariaDB, and for that Joomla 5 requires version 10.4. Your version 10.1.48 is too low.

I didn't specify to use MariaDB. There is no such option during installation. I specified MySQLi.

![2023-10-18 21-07-40](https://github.com/joomla/joomla-cms/assets/6747127/52592c3b-ab00-44b3-bd9b-2b4225002f32)

So, as I understand MariaDB is a fork of MySQL. And Debian server have both installed.

So, it is still unclear to me why Joomla requires a higher version of MariaDB. We are not using this database. Why does Joomla require a higher version?

**Comment by brianteeman** [comment] 2023-10-18 18:33
You are using that database

**Comment by richard67** [comment] 2023-10-18 18:33
@lipatovroman Have you read my comment above https://github.com/joomla/joomla-cms/issues/42159#issuecomment-1768403171 ?

I explain again with other words: There is no "MariaDB" option for the database type in the installation form because it is using the same way to connect (the same client). If you connect to the MySQL database or a MariaDB database is decided by you when you enter the database server's host name and database name. If you enter the host name and database name of the present MariaDB then you decide to connect to that DB.

MariaDB use different version numbers than MySQL, that's why we can't say we require the same version as for MySQL. Which version Joomla requires depends on the features provided by the database server, so if we want to use JSON functions we need MySQL 8.x or MariaDB 10.y.

If you want to know more about the different version numbering these databases use, check https://en.wikipedia.org/wiki/MySQL and https://en.wikipedia.org/wiki/MariaDB .

So don't blame Joomla for something which is your decision when you decide to use the MariaDB and not the MySQL database.

**Comment by lipatovroman** [comment] 2023-10-18 19:29
Ok, I got it :)
My Debian server does not have MySQL at all.
I've been used MariaDB for years.
I just didn't know it.
So, I'm trying to install J5 - it detects, that server use MariaDB, as MySQL fork and shows me error about low version.
Thanks.

**Comment by richard67** [comment] 2023-10-18 19:32
Yes, you need a newer MariaDB version, yours is too old for Joomla 5.

**Comment by lipatovroman** [comment] 2023-10-18 20:26
Ok. To get a newer version of MariaDB, I need to upgrade Debian from 9 to 10 or 11.
There are Joomla 3 sites on the server. Will they work after this upgrade?

**Comment by richard67** [comment] 2023-10-18 20:35
> Will they work after this upgrade?

Updating Debian will also update the PHP version. The Joomla core will work when the PHP and database Version meet the requirements for the particular Joomla version and the Joomla version is not too old. Bad old 3rd party extensions might break when they are not compatible with the newer PHP version.

As you did not tell which Joomla versions these sites have and which 3rd party extensions you use, we can not answer your question.

A Joomla 1.5 or 2.5 or anything else older than 3.10 will break when PHP is updated to 8.1 or 8.2.

Anyway, such questions are for the support forum. Here is not a support forum but the place to handle Joomla bugs and issues, so I won’t provide any further advice here.
