### ISSUE TITLE
Site moves a little

### ISSUE THREAD

**Issue by sandewt** [joomla/joomla-cms#17292] opened 2017-07-27 07:17 UTC
### Steps to reproduce the issue

If you click on the TOS - link (terms of services) in the User Registration Form, a modal window opens.
First, you should have selected a TOS article in the User Plugin!

### Expected result / ### Actual result

At this moment the site moves a little to the right. And when you close the modal window, the site moves a little to the left.

### System information (as much as possible)

This is messy.

### Additional comments

This is caused by the scrollbar of the site, which is disappearing.
Solution: Scrollbar site should not disappear.

**Comment by ghost** [comment] 2017-07-27 07:29
Thanks for reporting. Can you use Protostar if this Issue happens too?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17292">issues.joomla.org/tracker/joomla-cms/17292</a>.</sub>

**Comment by sandewt** [comment] 2017-07-27 07:57
Well noticed.

Corcerning templates: Protostar and Beez3.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17292">issues.joomla.org/tracker/joomla-cms/17292</a>.</sub>

**Comment by ghost** [comment] 2017-07-27 08:01
Didn't get your Answer: You tested on Protostar?

**Comment by sandewt** [comment] 2017-07-27 08:08
I tested both: Protostar and Beez3.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17292">issues.joomla.org/tracker/joomla-cms/17292</a>.</sub>

**Comment by ghost** [comment] 2017-07-27 08:27
Can't confirm. 
### Test on
3.8-dev
Multilanguage Site
macOS Sierra, 10.12.6
Firefox 54 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by sandewt** [comment] 2017-07-27 09:21
**Laptop: TEST 1** (local)
Joomla 3.7.4
Windows 10
Browsers: Firefox (54.0.1), Google Chrome (59.0.3071.115)
XAMPP: v3.2.2
PHP 7.0.15 
5.5.5-10.1.21-MariaDB 

Can confirm (NOK) (can also confirm this online)
Note: The site has a scrollbar at the right site. 


**Tablet: TEST 2** (online)
Joomla 3.7.4
Android 4.4.4
Google Chrome (59.0.3071.125)

Can NOT confirm (OK)
Note: The site has not a scrollbar at the right site.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17292">issues.joomla.org/tracker/joomla-cms/17292</a>.</sub>

**Comment by ghost** [comment] 2017-07-27 09:27
can you test on a clean Install (no 3rd-Party Plugins) and different Browsers?

**Comment by sandewt** [comment] 2017-07-27 09:59
I have installed a clean and new Joomla 3.7.4 version.
And repeat **Laptop: TEST 1** (local) with the same results (issue).
There are no 3rd-Party Plugins.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17292">issues.joomla.org/tracker/joomla-cms/17292</a>.</sub>

**Comment by C-Lodder** [comment] 2017-07-27 10:04
If anything this os a BS2 related issue. Not Joomla related

**Comment by Bakual** [comment] 2017-07-27 10:22
This is not an issue at all. It's an expected browser behavior. They show a scrollbar if the site is longer than the visible area. Since that scrollbar is around 10px width, the whole window gets narrower by that 10px. Any centered layout will move 5px to the left then.

The only solution would be to always show a scrollbar, or never show them. Both are not acceptable imho.

**Comment by sandewt** [comment] 2017-07-27 11:09
I found in \media\system\css\modal.css

/* Hides scrollbars */
.body-overlayed {
 overflow: hidden;
}

If you delete line 83 "overflow: hidden;" I see that the scrollbar are visible and the site doesn't move.
So it (possible) a css behavior!  

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17292">issues.joomla.org/tracker/joomla-cms/17292</a>.</sub>

**Comment by C-Lodder** [comment] 2017-07-27 15:13
If a default BS2 behaviour is annoying for you, just override the CSS.

**Comment by ghost** [comment] 2017-07-27 15:17
closed as expected Behaviour.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17292">issues.joomla.org/tracker/joomla-cms/17292</a>.</sub>

**Closed as completed by ghost** 2017-07-27 15:17 UTC
Labels: No Code Attached Yet

**Comment by sandewt** [comment] 2017-07-27 19:11
I override it in the custom.css.
In Firefox, Chrome, Edge it works, except in Opera (Windos 10).

Thanks all.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17292">issues.joomla.org/tracker/joomla-cms/17292</a>.</sub>

**Comment by sandewt** [comment] 2017-07-27 20:42
Sorry, I mean the user.css.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17292">issues.joomla.org/tracker/joomla-cms/17292</a>.</sub>
