### ISSUE TITLE
The problem is how to address joomla links

### ISSUE THREAD

**Issue by DPGiran** [joomla/joomla-cms#18182] opened 2017-10-01 16:58 UTC
### Steps to reproduce the issue
I think that this problem also exists in versions before 3!
Look at the link below :
https://extensions.joomla.org/extensions/extension/site-management/sef/sh404sef/

### Expected result
Now, if you change the group and the category in the above link, you will have to go to page 404.
But it is not...

### Actual result
As described above, I will continue to change the group and category link above.

https://extensions.joomla.org/extensions/extension/news-display/images/sh404sef/

You will see again that the page related with the extension will appear !!!???

### System information (as much as possible)
joomla 3.8

### Additional comments
This is a very serious and even dangerous problem that has a negative effect on SEO.

Thanks
R.gholamrezaei

**Comment by jeckodevelopment** [comment] 2017-10-01 17:01
Hi @DPGiran , is this a JED (Joomla! Extensions Directory) issue?

**Comment by brianteeman** [comment] 2017-10-01 17:16
the JED uses a custom component so its not the best example

**Comment by DPGiran** [comment] 2017-10-01 17:25
Hi !

 

Exactly not!

This problem is related to the way Joomla addresses.

This problem exists on all Joomla sites.

I used the Joomla site to better explain the bug.

**Comment by mbabker** [comment] 2017-10-01 17:28
Much of routing is handled at the component level, so as stated the JED isn't the best example because it is a custom component.

If you really want to use a Joomla site to demonstrate your point, you are better off using pages rendered by com_content.  The news areas on www.joomla.org, community.joomla.org, and developer.joomla.org use com_content.

Even with the issues confirmed, there are only so many fixes that can be made in the library router APIs.  Many fixes are still component level and can't be fixed by core for all extensions.

**Comment by brianteeman** [comment] 2017-10-01 17:28
It is not a problem because although those links might work Joomla will never generate them so links to them dont exist.

**Comment by DPGiran** [comment] 2017-10-01 17:55
Can you explain why they are on the sitemap?

Does this not mean that Joomla has created these links?

If not, why is it coming?

**Comment by brianteeman** [comment] 2017-10-01 18:05
What sitemap?

**Comment by DPGiran** [comment] 2017-10-02 17:24
My friend will reply you soon …

**Comment by tonypartridge** [comment] 2017-10-04 23:06
Joomla! Core doesn’t have a sitemap. So sounds like an issue with a 3rd party component.

**Comment by ghost** [comment] 2017-10-05 05:27
closed as no Core-Issue. Issue can always be reopened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18182">issues.joomla.org/tracker/joomla-cms/18182</a>.</sub>

**Closed as completed by ghost** 2017-10-05 05:27 UTC
Labels: No Code Attached Yet

**Comment by DPGiran** [comment] 2017-10-06 11:01
hi friends !

I'm sorry to reply late, my right hand was damaged.

When did I say that Joomla is producing a sitemap?

 

I transferred the main problem to you.

In my opinion, this is a very important problem to be solved.

 

If you do not find it difficult

So answer my questions

 

Why create a category to create content?

When we create separate category, why are the categories linked together?

 

With these interpretations, this is not a problem?

**Comment by brianteeman** [comment] 2017-10-06 11:04
you said
> Can you explain why they are on the sitemap?

**Comment by DPGiran** [comment] 2017-10-06 20:30
Let me answer you tomorrow…

**Comment by DPGiran** [comment] 2017-10-08 09:36
Hello !
I almost looked at the JED sitemap and did not see two similar links
Or a file that has several different links.
And I've come to the conclusion that this happens in some components.
 
With these interpretations, there is still a problem that I mentioned to you in the first post.
 
In response to our colleague “ mbabker ”
I must say :
I reviewed the main site of Joomla! For the sake of you and again it was the same problem
In the first post I also said that there is a problem on all Joomla sites.
 
example  for com_content:
 
main link release joomla 3.8.1 :
 
https://www.joomla.org/announcements/release-news/5715-joomla-3-8-1-release.html
 
now , By changing the category, Joomla! 3.8.1 release link will be displayed again
 
https://www.joomla.org/announcements/about-joomla/5715-joomla-3-8-1-release.html
 
or :
 
https://www.joomla.org/about-joomla/release-news/5715-joomla-3-8-1-release.html
 
Do you think this is not a problem ?????
 
at the end
 
You still did not answer my questions as I asked above!
 
1.     Why create a category to create content? 
2.       When we create separate category, why are the categories linked together?

**Comment by brianteeman** [comment] 2017-10-08 09:39
As stated before - it is not a problem that you can access the content by entering the url manually as Joomla will not automatically generate those links.

For all your other questions please use the forum https://forum.joomla.org

**Comment by DPGiran** [comment] 2017-10-08 10:22
ok !
You are right.

But I can not understand this,
because Not normal
You do not see such a case in the other CMS,

You still did not answer my questions as I asked above!

1.     Why create a category to create content?
2.     When we create separate category, why are the categories linked together?
