### ISSUE TITLE
[4.0] Update switcher label?

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#18813] opened 2017-11-23 05:09 UTC
### Steps to reproduce the issue
Go to Configuration > Installer
See `Joomla! Extensions Directory`

### Expected result
Show / Hide ????

### Actual result
Show message / Hide message

**Comment by ghost** [comment] 2017-11-23 06:05
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18813">issues.joomla.org/tracker/joomla-cms/18813</a>.</sub>

**Comment by brianteeman** [comment] 2017-11-23 09:58
The issue is that the label needs to be changed as well so that it is clear it refers to the JED message

**Comment by brianteeman** [comment] 2017-11-23 10:02
in fact a better question might be do we still need that message? shouldnt the plugin be installed by default in j4 (even if it is not enabled)

**Comment by C-Lodder** [comment] 2017-11-23 13:36
I really have no idea why we even have a parameter to display this message. I agree with @brianteeman, enable plugin by default and the user can disable it.

**Comment by brianteeman** [comment] 2017-11-23 14:29
the reason is historical and it was only supposed to be a temporary measure. the plt at the time thought the plugin was not very good etc etc so they wanted to test it as an add-on first.

**Comment by brianteeman** [comment] 2018-04-09 16:24
Closed by #20121 20121

**Closed as completed by brianteeman** 2018-04-09 16:24 UTC
Labels: No Code Attached Yet, J4 Issue
