### ISSUE TITLE
Double entry of "Serve gzip compressed CSS files..." in htaccess

### ISSUE THREAD

**Issue by propellerhuvud** [joomla/joomla-cms#43581] opened 2024-05-30 16:40 UTC
### Steps to reproduce the issue
Updating a Joomla 4.4.x site to 4.4.5 may break the CSS for the backend GUI

### Expected result
A working admin GUI styled with CSS after login

### Actual result
After login to the backend, the styling fails and all HTML is shown as a very long vertical page. Technically working, but extremely confusing. If the 3 duplicated code lines are removed, the CSS styling works as expected.

### System information (as much as possible)
Joomla 4.4.5 stable on Litespeed server, PHP 8.2.19, Maria-DB 10.6.17
Swedish language, SP PageBuilder, Helix Ultimate template, Tassos Convert Forms, OSMap Free

### Additional comments
This problem surfaced on Joomla 4.4.4 after updating to 4.4.5 and remained broken until duplicate code in htaccess was removed.
I attach the htaccess file from a Joomla 4.4.5 stable package, with the problematic section enclosed with lines of §.

**Comment by propellerhuvud** [comment] 2024-05-30 16:42
I cannot find my atteched htaccess file in this report. Submitted from Firefox 126.0.1
How can I fix this?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43581">issues.joomla.org/tracker/joomla-cms/43581</a>.</sub>

**Comment by brianteeman** [comment] 2024-05-30 20:33
https://docs.joomla.org/J4.x:Assorted_Issues#A_Page_Displays_with_No_Styling

**Comment by propellerhuvud** [comment] 2024-05-30 20:45
Thank you for the link Brian! I will go through that page first thing tomorrow. Could very well be that my report was  unnecessary.
Good night to you!

**Comment by rdeutz** [comment] 2024-06-01 13:08
Closing it for now, can be reopened when the problem is not solved. Just mention me and I will reopen it.

**Closed as completed by rdeutz** 2024-06-01 13:08 UTC
Labels: No Code Attached Yet, Information Required
