### ISSUE TITLE
[4.1]Saving update key into extra_query in #__update_sites leaves update site checked out

### ISSUE THREAD

**Issue by toivo** [joomla/joomla-cms#37204] opened 2022-03-05 04:12 UTC
### Steps to reproduce the issue
Install a third party extension that requires a download key like Akeeba Backup Pro
Go to System - Update - Update Sites.
The installed third party extension displays the text 'The Download Key key missing' in red background.
Select the update site.
Enter the required value into the field Download Key.
Save and Close.
The extension shows the text Download Key in blue background and the value of the download key.
Go to System - Maintenance.

### Expected result
Global Check-in shows no items to be checked in.

### Actual result
Global Check-in shows that an item needs to be checked in.

### System information (as much as possible)
Joomla 4.1.1-dev of 5 March 2022, Wampserver 3.2.7 with PHP 8.0.15

### Additional comments
In each case the row in #__update_sites has the following values:
- checked_out 0
- checked_out_time 0000-00-00 00:00:00

The issue was reproduced in 4.1.0 and 4.1.1-dev with the latest versions of Akeeba Backup Pro, Akeeba Admin Tools Pro and JCE Pro.
![screen shot 2022-03-05 at 04 08 46](https://issues.joomla.org/uploads/1/b7935f2466c5c463b98e0ce5b1c677c3.jpg)![screen shot 2022-03-05 at 04 09 05](https://issues.joomla.org/uploads/1/0f88e25340f264dd1c2512ce70539d38.jpg)

**Comment by richard67** [comment] 2022-03-05 09:45
Which kind of database server (MySQL or MariaDB) and which version did you use? Do you have any SQL failures in the database server‘s log file? I ask because it seems that the extension still uses the old zerodates which are deprecated in MySQL 8 and not real null values.

Not sure if it’s related, just asking.

**Comment by richard67** [comment] 2022-03-05 09:50
Hmm I think it is related because I remember now that the zerodate value for the checked_out_time caused an extension to be shown as checked out. Not sure yet where to fix it.

**Comment by richard67** [comment] 2022-03-05 09:52
Will investigate later … I think I have an idea where to start.

**Comment by richard67** [comment] 2022-03-05 10:31
@toivo Is the extension also shown as checked out in the "System -> Manage -> Extensions" view? Or only in Global Checkin?

**Comment by toivo** [comment] 2022-03-05 10:58
It is MySQL 8.0.27.  The Extensions view does not show any extensions as checked out and I checked the extensions table, too.  Only the Global Checkin shows the checked out update sites.  Will update once I find the MySQL logs.

**Comment by richard67** [comment] 2022-03-05 10:59
@toivo No need to check the logs. I know what the problem is, I'm just not sure yet about how and where to fix it.

**Comment by toivo** [comment] 2022-03-05 11:02
Ok, thank you @richard67

**Comment by richard67** [comment] 2022-03-05 11:25
@toivo Do you have a backup from before the extensions update or a test site, so you can reproduce the issue, and are you available for testing a PR with a fix?

**Comment by toivo** [comment] 2022-03-05 11:28
I can easily install either 4.1 or 4.1.1-dev and I am available for testing after about 1.5 hours

**Comment by richard67** [comment] 2022-03-05 11:29
I think I will need more than 1.5 hours because will soon be busy with other stuff.

**Comment by toivo** [comment] 2022-03-05 12:15
Ok, no problems.

**Comment by richard67** [comment] 2022-03-05 13:46
It can be reproduced with this fake [ "paid download" ](http://updates.myoldsite.com/file_null-1.0.zip)extension Null file which was used for testing several PRs in past, e.g. #34419 or #34386 . Thanks @nikosdion for the file.

**Comment by richard67** [comment] 2022-03-05 17:56
Closing as having a pull request. Please test #37206 . Thanks in advance.

**Closed as completed by richard67** 2022-03-05 17:56 UTC
Labels: No Code Attached Yet
