### ISSUE TITLE
[4.0] Dropdown color bleeds over

### ISSUE THREAD

**Issue by roland-d** [joomla/joomla-cms#34682] opened 2021-07-01 14:17 UTC
### Steps to reproduce the issue
1. Login to the Joomla 4 backend
2. Go to Components -> Banners
3. Create a new banner
4. Click on the banner details tab
5. See the color bleeding into the dropdown. You will only see this if your screen is wide enough. This seems to start at a width from 2625px.

### Expected result
![image](https://user-images.githubusercontent.com/359377/124138882-61babc00-da87-11eb-8efc-83c02261e309.png)

### Actual result
![image](https://user-images.githubusercontent.com/359377/124138830-56679080-da87-11eb-88fc-f2081c62fddc.png)

### System information (as much as possible)
Joomla 4.0-dev branch
PHP 7.4

**Comment by brianteeman** [comment] 2021-07-02 06:16
It is caused by the use of the background image which is used for the dropdown arrow. Despite repeated attempts to change that it is supposed to be the full width of the field and not just for the arrow. Amongst many issues that this causes you just added another to the list.

**Comment by RickR2H** [comment] 2021-07-07 10:29
Is making the image twice as big not an option? :wink: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34682">issues.joomla.org/tracker/joomla-cms/34682</a>.</sub>

**Comment by brianteeman** [comment] 2021-07-09 16:40
@RickR2H that will probably work

**Comment by angieradtke** [comment] 2021-07-14 09:38
We can change the background-position from   100%/116rem  -> to 100%/126rem



```
.custom-select, .form-select {
...
    background: url(../images/select-bg.svg) no-repeat 100%/116rem;
   ...
}

custom-select, .form-select {
....
    background: url(../images/select-bg.svg) no-repeat 100%/126rem;

}
```

**Comment by drmenzelit** [comment] 2021-07-21 14:48
The problem starts at a width of 2354px and the solution posted by Angie does work only until a certain width, at 2528px the background appears again...

**Comment by angieradtke** [comment] 2021-07-21 15:52
@drmenzelit  we can go up  from   100%/126rem -> to 100%/136rem;
Maybe somebody width a screen bigger than mine   can play around width the em size

**Comment by HLeithner** [comment] 2021-08-24 15:44
274rem for about 5000px not a real solution
![image](https://user-images.githubusercontent.com/1497730/130647692-7bae863f-b1e6-4b16-a325-bfb54ef5e63c.png)

**Comment by richard67** [comment] 2023-01-08 10:34
Closing as having a pull request. Please test #39569 . Thanks in advance.

**Closed as completed by richard67** 2023-01-08 10:34 UTC
Labels: No Code Attached Yet
