### ISSUE TITLE
[4.0] searchtools.js

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#21550] opened 2018-08-11 08:54 UTC
### Steps to reproduce the issue
Set a filter with the table options on any list eg articles at administrator/index.php?option=com_content&view=articles

Press the clear button to resent the filters

### Expected result
Filters removed

### Actual result
No change to the filters and JS error in the console
```
Uncaught TypeError: e.getFilterFields is not a function
    at HTMLButtonElement.value (searchtools.min.js?cb212280df1d7911f3f17dd682c7d63b:1)
value @ searchtools.min.js?cb212280df1d7911f3f17dd682c7d63b:1

```

**Comment by infograf768** [comment] 2018-08-11 09:53
@dgrammatiko knows the solution. I tested it OK here.

**Comment by Saurabh1** [comment] 2018-08-11 14:33
Tested and it worked for me without throwing an error.

**Comment by infograf768** [comment] 2018-08-11 16:02
The problem is in Firefox, but not only.
The file to make PR is

[searchtools.es6.js.zip](https://github.com/joomla/joomla-cms/files/2280366/searchtools.es6.js.zip)

**Comment by infograf768** [comment] 2018-08-12 04:48
closing as we have PR https://github.com/joomla/joomla-cms/pull/21562

**Closed as completed by infograf768** 2018-08-12 04:48 UTC
Labels: No Code Attached Yet, J4 Issue
