### ISSUE TITLE
[5.x] Features/Published tooltips with workflow enabled

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#44625] opened 2024-12-16 12:18 UTC
### Steps to reproduce the issue
With workflow enabled the tooltip displayed for Featured and Published is incorrect as the buttons are disabled

![Image](https://github.com/user-attachments/assets/9b3e58c2-12cd-45d9-8601-b37d61654f14)

![Image](https://github.com/user-attachments/assets/2a9ce785-91ac-4d14-94e2-2c4c60127253)

The string JGLOBAL_TOGGLE_FEATURED and JLIB_HTML_PUBLISHED_UNPUBLISH should not be in the tooltip when workflow is enabled and/or the button is disabled

**Comment by chmst** [comment] 2024-12-16 15:37
Closing this, it is a duplicate of  https://github.com/joomla/joomla-cms/issues/33575

**Closed as completed by chmst** 2024-12-16 15:37 UTC
Labels: No Code Attached Yet
