### ISSUE TITLE
Parameter in a componets default.xml file are not sourced anymore

### ISSUE THREAD

**Issue by andreas-isele** [joomla/joomla-cms#19540] opened 2018-02-02 17:07 UTC
### Steps to reproduce the issue
You have an XML file of a component using paramater e.g in 
components\com_fileuploader\views\fileuploader\tmpl\default.xml:

when you load your model and you want to get the parameters from the XML doing:

$app = JFactory::getApplication('site');
$params = $app->getParams('com_fileuploader');
$rubrik = $params->get('rubrik'); // => Retruns null

### Expected result
$rubrik has the parameter specified in the XML of the component

### Actual result
$rubrik is empty

**Comment by ggppdk** [comment] 2018-02-02 17:43
The file
`components/com_fileuploader/views/fileuploader/tmpl/default.xml`
are parameters of a menu item
they are not parameters of the component

Parameters of componet are
`administrator/components/com_fileuploader/config.xml`

You can ask more in forums,  https://forum.joomla.org

**Comment by Bakual** [comment] 2018-02-02 17:47
I can't reproduce it with com_content. So it is either something with your extension or a misunderstanding (as @ggppdk indicated).

I'm closing this as non-core issue. If you can reproduce it in core, feel free to reopen.

**Closed as completed by Bakual** 2018-02-02 17:47 UTC
Labels: No Code Attached Yet

**Comment by ggppdk** [comment] 2018-02-02 17:51
@andreas-isele 

Probably you have some parameters with 
-- same name in component configuration and in menu item configuration

and the above has caused some confusion
if the parameters name are the same then yes
... you will not get a parameter value ...
