### ISSUE TITLE
Module article categories as submenu, active item

### ISSUE THREAD

**Issue by LaurensGoedel** [joomla/joomla-cms#7935] opened 2015-09-23 15:05 UTC
# Steps to reproduce the issue
1. Create a category
2. Create a menu-item linking to that category as blog for instance
3. Create a categories module with the same category and visible on the just created menu item
4. Do not enable SEF in your Joomla configuration

# Expected result
The li element with the same category should have a 'active'-class

# Actual result
Because of the difference in $_SERVER['REQUEST_URI'] and the ContentHelperRoute::getCategoryRoute in HTML characters, the li-element does not get the class 'active'.

# Possible solution
File /modules/mod_articles_categories/tmp/default_items.php, replace the if-statement on ~ 13
Add:
```
$activeCatId = '';
if(JFactory::getApplication()->input->get('view') === 'category' )
{
	$activeCatId = JFactory::getApplication()->input->get('id');
}
```
And replace 
```
<li <?php if ($_SERVER['REQUEST_URI'] == JRoute::_(ContentHelperRoute::getCategoryRoute($item->id))) echo ' class="active"';?>> <?php $levelup = $item->level - $startLevel - 1; ?>
```
with:
```
<li <?php if (!empty($activeCatId) && $activeCatId == $item->id) echo ' class="active"';?>> <?php $levelup = $item->level - $startLevel - 1; ?>
```

**Comment by zero-24** [comment] 2015-09-23 16:13
Hi @LaurensGoedel can you send your fixes as patch against staging? If you need help see: https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7935">issues.joomla.org/joomla-cms/7935</a>.</sub>

**Comment by brianteeman** [comment] 2016-05-11 09:51
> This module displays a list of categories from one parent category.

In your example above you are in the parent category so it is not expected that it will display the name of that category. It is only intended to display any subcategories<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7935">issues.joomla.org/joomla-cms/7935</a>.</sub>

**Comment by brianteeman** [comment] 2016-05-11 09:51
Closed as expected behaviour<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7935">issues.joomla.org/joomla-cms/7935</a>.</sub>

**Closed by brianteeman** 2016-05-11 09:51 UTC
Labels: No Code Attached Yet
