### ISSUE TITLE
Joomla 4 cli core:install doesn't work  in Docker

### ISSUE THREAD

**Issue by nickyeoman** [joomla/joomla-cms#40634] opened 2023-05-20 20:25 UTC
### Steps to reproduce the issue

1. Create a Joomla container in Docker using the image `joomla:4.3.1` from [Docker Hub](https://hub.docker.com/_/joomla).
2. Try to run the command `php cli/joomla.php core:install` inside the container, following the instructions outlined in the [Joomla CLI Update documentation](https://docs.joomla.org/J4.x:CLI_Update#Installing_Joomla.21_via_the_CLI).

### Expected result

The Joomla installer should run successfully.

### Actual result

The output displays: `Install Joomla to run cli commands`. This behavior is expected according to the code found in [cli/joomla.php](https://github.com/joomla/joomla-cms/blob/4.3-dev/cli/joomla.php) on line 46:

```php
// Check if installed
if (
    !file_exists(JPATH_CONFIGURATION . '/configuration.php')
    || (filesize(JPATH_CONFIGURATION . '/configuration.php') < 10)
) {
    echo 'Install Joomla to run cli commands' . PHP_EOL;
    exit;
}
```

### System information

- Docker image: `joomla:4.3.1` from [Docker Hub](https://hub.docker.com/_/joomla)

### Additional comments

According to the [Installing Joomla via the CLI](https://docs.joomla.org/J4.x:CLI_Update#Installing_Joomla.21_via_the_CLI) documentation, it should be possible to install Joomla using Joomla cli. However, this is currently not working because the `cli/joomla.php` file checks for the existence of `configuration.php` before attempting the installation. This check prevents the installation process when trying to create the `configuration.php` file in the first place.

**Comment by alikon** [comment] 2023-05-21 06:47
please follow this https://docs.joomla.org/J4.x:Joomla_CLI_Installation

**Comment by Fedik** [comment] 2023-05-21 08:00
Hi,

> According to the [Installing Joomla via the CLI](https://docs.joomla.org/J4.x:CLI_Update#Installing_Joomla.21_via_the_CLI) documentation

Because you use Docker image please follow the information from the image description. https://hub.docker.com/_/joomla
If I right understood it will "pre install" joomla for you.

For bugs in the image please reaport https://github.com/joomla-docker/docker-joomla/

**Comment by alikon** [comment] 2023-05-21 08:08
@Fedik  `php cli/joomla.php core:install` has never been landed in core,  that doc  page must be amended
starting for 4.3 you can install from cli with `php installation/joomla.php install`

so imho it's not a bug more a doc issue

**Comment by Fedik** [comment] 2023-05-21 08:23
Okay :)

**Comment by rdeutz** [comment] 2024-05-06 20:56
not an core issue

**Closed as completed** 2024-05-06 20:56 UTC
Labels: Feature, No Code Attached Yet, Documentation Required
