### ISSUE TITLE
Regarding Modal Login Plugin

### ISSUE THREAD

**Issue by XenyFord** [joomla/joomla-cms#42310] opened 2023-11-07 12:59 UTC
Mr. Teenman, Good morning :)

I hope you are doing great, sir!

I've enabled the Modal Login module on a website, and it is working fine on all the pages except a page where the EventBooking component is enabled. It has just disappeared from creating a popup div. I request you to please be so kind to help me rectify this problem.

Website: https://astro-remedies.com/events

Thank you in advance for your help!

![ERROR](https://github.com/joomla/joomla-cms/assets/89290310/80fdb765-3d54-4159-bac7-347dd51cd4c9)

---Working Modal on other pages ---

![WORKING POPUP](https://github.com/joomla/joomla-cms/assets/89290310/0fca5088-5d79-4841-a48e-810f8c8a1a0f)

**Comment by drmenzelit** [comment] 2023-11-07 17:02
The problem is related with the template or login module / plugin you are using. I suggest you ask in the forum (forum.joomla.org) or directly be the developer of the template / module / plugin.

**Comment by Quy** [comment] 2023-11-07 17:13
Closing as this is the wrong place to ask support questions.

**Closed as completed by Quy** 2023-11-07 17:13 UTC
Labels: No Code Attached Yet
