### ISSUE TITLE
Wrong default language in backend

### ISSUE THREAD

**Issue by renekorss** [joomla/joomla-cms#8906] opened 2016-01-15 08:43 UTC
#### Steps to reproduce the issue

User should have default settings for languages. Edit profile > Basic settings > Backend Language > - Use default -

1. Install new language (Extensions > Language(s) > Install language).
2. Set newly installed language as default to administrator.
3. Log out.
4. Log in again.

#### Expected result

- Administrator side should be in newly installed default language.

#### Actual result

- Administrator side is in english.

#### System information

- Joomla! 3.4.8

#### Additional comments

- Login view is in newly installed default language (not neglish).
- Debugging language shows no errors.
- I could investigate this if someone verifies it.

**Comment by anabarcellos** [comment] 2016-01-15 22:31
When you say "install new language", you mean from "Extensions" > "Language(s)" > "Install language" button, right?

Since my intranet websites can't connect to internet, I install language packages using "Extensions" > "Manage" > "Install" > Upload Package File.

I have just tested here (Joomla 3.4.8) and this issue didn't happen. I don't need even to logout and login again to have my Control Panel in the new language. It is automatic for me, in the moment that I set the new one. If I logout and login, I still see the Control Panel in the new language.  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8906">issues.joomla.org/joomla-cms/8906</a>.</sub>

**Comment by infograf768** [comment] 2016-01-16 07:20
When logout/login and the user preferred administrator language is NOT set to default or NOT to the newly installed language but to another language, it is this other language that will be used. In your case en-GB.

**Comment by renekorss** [comment] 2016-01-16 08:43
@anabarcellos Yes, "Install language" button.
@infograf768 My user settings are all set to default.

**Comment by infograf768** [comment] 2016-01-16 09:23
I can't reproduce your issue.

**Comment by infograf768** [comment] 2016-01-16 10:14
Have you deleted all Caches? Joomla and Browser?

**Comment by renekorss** [comment] 2016-01-16 20:19
@infograf768 Yes, I have deleted all caches. Didn't help. Only way I could get desired language was to select it on login. Even setting it under user profile didn't help. 

Could it be somehow from server configuration? Where is language set on source? Can't check source right now. Also, all other clients sites running on our company server and on 3.4.8 (upgraded) works fine. Only this has problems (client server, fresh 3.4.8 install).

**Comment by renekorss** [comment] 2016-01-21 15:06
@infograf768 

I investigated this issue and found out that client server is running with Suhosin PHP extension with `suhosin.post.disallow_nul = 1` which results empty `$_POST` variables to be removed. So there is no `lang` key in `$_POST`.

Therefore on login, settings language will always default to `en-GB` [in here](https://github.com/joomla/joomla-cms/blob/98aa6f5175b201fd57c8c45a24037555519c19c5/libraries/cms/application/administrator.php#L331).

    $lang = $this->input->getCmd('lang', 'en-GB');

Solution would be to remove `'en-GB'` and if it's empty, it would use default language like expected.

**Comment by infograf768** [comment] 2016-01-27 09:28
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8906">issues.joomla.org/joomla-cms/8906</a>

**Comment by infograf768** [comment] 2016-01-27 09:28
Closing as we have a patch https://github.com/joomla/joomla-cms/issues/8956<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8906">issues.joomla.org/joomla-cms/8906</a>.</sub>

**Closed by infograf768** 2016-01-27 09:28 UTC
Labels: No Code Attached Yet
