### ISSUE TITLE
Joomla 4.0.3 - Toggle Menu - Dashboards do not load

### ISSUE THREAD

**Issue by Rickard19** [joomla/joomla-cms#35598] opened 2021-09-18 14:49 UTC
### Steps to reproduce the issue
Hello.

When I toggle the menu and it only displays the icons. The Home Dashboard and Help Dashboard are the only buttons that display the dashboards. The other icons when clicked re-expand the toggle menu and their respective drop menu drops down.

Thank you

**Comment by PhilETaylor** [comment] 2021-09-18 16:04
I believe this is the expected behaviour, although several of us have commented before how this is not the real-world user expectation for a collapsed menu.

**Comment by Quy** [comment] 2022-01-17 02:30
Duplicate #32934. Thanks for the report.

**Comment by brianteeman** [comment] 2022-03-08 13:33
> The other icons when clicked re-expand the toggle menu and their respective drop menu drops down.

How else would you do it? A button should only do one thing

**Comment by Hackwar** [comment] 2024-03-30 21:17
Thank you for reporting this issue, however this is expected behavior. Because of that, I'm closing this one.

**Closed as completed by Hackwar** 2024-03-30 21:17 UTC
Labels: No Code Attached Yet, bug
