### ISSUE TITLE
why name in user profile in joomla is name by default?!

### ISSUE THREAD

**Issue by saman222** [joomla/joomla-cms#39822] opened 2023-02-08 13:49 UTC
### Is your feature request related to a problem? Please describe.
In real world each man and woman has a firstname and lastname. when you fill some forms such as gmail, you must fill first name and last name. yes i understand we can use additional field for that but it is not good way to implement for each website.

### Describe the solution you'd like
simply separate name to first and last name fields. (wordpress has that two field if you don't fight with me.)
Why should the name and surname be separate? Because Joomla is a built-in multi-language cms, it is not easy to recognize English as the name and surname in different languages. This is a problem that we have encountered in the Persian language version of our site with more than 90 thousand users. For some of our users, we are unable to distinguish between firstname and lastname. (I remind you again that I understand that this problem can be solved somehow by using additional fields. But it is much better if it is solved by default.)

**Comment by brianteeman** [comment] 2023-02-08 14:19
In your culture everyone may simply have a first and a lastname but that is not universally true.

It is a topic that I lecture on

https://www.youtube.com/watch?v=0kMesXoeqAA&ab_channel=Joomla%21London

**Comment by richard67** [comment] 2023-02-08 18:01
Closing as expected behaviour due to reasons explained in the previous comment and the video linked in that comment.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39822">issues.joomla.org/tracker/joomla-cms/39822</a>.</sub>

**Closed as completed by richard67** 2023-02-08 18:01 UTC
Labels: No Code Attached Yet
