### ISSUE TITLE
Media manager - no permissions at Firefox

### ISSUE THREAD

**Issue by TristisOris** [joomla/joomla-cms#38880] opened 2022-09-30 08:52 UTC
### Steps to reproduce the issue
at firefox open Content>Media

### System information (as much as possible)
Joomla 4.2.3, FF 105.

### Additional comments
![изображение](https://user-images.githubusercontent.com/1270117/193231730-395dd6c9-330c-4aad-8f34-7adcce4f22bf.png)

**Comment by Abernyte-Git** [comment] 2022-09-30 09:53
I cannot replicate on J4.2.4-dev and FF106b
If the error is a 403 then perhaps local folder permissions or server mod_security rule.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38880">issues.joomla.org/tracker/joomla-cms/38880</a>.</sub>

**Comment by TristisOris** [comment] 2022-09-30 12:56
but it works at any chrome browser.

**Comment by TristisOris** [comment] 2022-09-30 13:09
both files:
```
...components/com_tz_portfolio_plus/js# ls -l
total 312
-rw-r--r-- 1 www-data www-data   613 Aug 10 12:12 classie.min.js
-rw-r--r-- 1 www-data www-data  1218 Aug 10 12:12 **core.min.js**
-rw-r--r-- 1 www-data www-data    30 Aug 10 12:12 index.html
-rw-r--r-- 1 www-data www-data 95970 Aug 10 12:12 jquery-1.11.3.min.js
-rw-r--r-- 1 www-data www-data  8376 Aug 10 12:12 jquery.dm-uploader.min.js
-rw-r--r-- 1 www-data www-data 68265 Aug 10 12:12 jquery.fancybox.min.js
-rw-r--r-- 1 www-data www-data 21064 Aug 10 12:12 jquery.infinitescroll.min.js
-rw-r--r-- 1 www-data www-data 15977 Aug 10 12:12 jquery.isotope.min.js
```
```
/media/system/js# ls -l
total 676
-rw-r--r-- 1 www-data www-data 27752 Sep 27 16:37 core-es5.js
-rw-r--r-- 1 www-data www-data  7421 Sep 27 16:37 core-es5.min.js
-rw-r--r-- 1 www-data www-data  3085 Sep 27 16:37 core-es5.min.js.gz
-rw-r--r-- 1 www-data www-data 26267 Sep 27 16:37 core.js
-rw-r--r-- 1 www-data www-data  7669 Sep 27 16:37 **core.min.js**
-rw-r--r-- 1 www-data www-data  3156 Sep 27 16:37 core.min.js.gz
-rw-r--r-- 1 www-data www-data  6373 Sep 27 16:37 draggable-es5.js
-rw-r--r-- 1 www-data www-data  2240 Sep 27 16:37 draggable-es5.min.js
-rw-r--r-- 1 www-data www-data   950 Sep 27 16:37 draggable-es5.min.js.gz
-rw-r--r-- 1 www-data www-data  5907 Sep 27 16:37 draggable.js
```

**Comment by nikosdion** [comment] 2022-10-08 20:04
I cannot reproduce on Firefox 105.0.3 on macOS.

Most likely you are using a browser extension _only on Firefox_ which sends some header the server does not like. 

It would also help us a lot if you could submit your screenshots with the language of your browser and Joomla itself set to English. Don't expect everyone to read your language, especially if it's using non-latin characters (I am not being sovinist; I am Greek and I always set my environment to English when submitting issue reports as I became keenly aware very early that nobody else except fellow Greeks can read error messages in the Greek alphabet). If my hunch is correct it complains about the document type which would mean that a Firefox extension is messing up the content-type or accepts HTTP header of the request.

**Comment by TristisOris** [comment] 2022-10-09 06:35
`You are not allowed to access the item. Please contact the site administration to solve the problem.`
this item always on russian even with english joomla interface and browser locale.
that not extension problem - 3 people confirm bug in private mode.

**Comment by HLeithner** [comment] 2022-10-09 08:53
I tried it on windows with Firefox 104.0.2 and Firefox 105.0.3, can you please create a https://launch.joomla.org and replicate it there?

**Comment by brianteeman** [comment] 2023-02-26 22:11
This should really be closed as no one has been able to reproduce it and its been many months

**Closed as completed** 2023-02-26 22:14 UTC
Labels: No Code Attached Yet, Information Required, bug
