### ISSUE TITLE
Limited Categories being shown in articles after upgrade to 3.7.0

### ISSUE THREAD

**Issue by 4dsiao** [joomla/joomla-cms#15613] opened 2017-04-27 09:19 UTC
### Steps to reproduce the issue

Ensure that you had active categories in Articles Categories

Take note of the existing category  

Create a new article and file this new article in existing category

Even creating new category does not show the new category

### Expected result

You should see only limited categories being shown

### System information (as much as possible)

Joomla 3.7.0

**Comment by 4dsiao** [comment] 2017-04-27 10:51
Issue Workaround as I had move permissions from XXXX to Registered or Public and now the category re-appear in com_articles.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15613">issues.joomla.org/tracker/joomla-cms/15613</a>.</sub>

**Comment by brianteeman** [comment] 2017-04-27 13:35
That sounds like the expected behaviour that a category is not available that the user creating the content doesnt have access to

**Comment by 4dsiao** [comment] 2017-04-27 13:45
Example the category is set up to Basic which is not the norm Joomla permission with only

Administrator
Registered
Public
Guest
Manager
Author
Editor
Publisher
Super User

I was using Super User since day 1.

It was working fine prior to <3.6.5 and after upgrading to 3.7.0, all the menu that point to the various categories disappeared.

After I had changed the basic to Registered or Public, the categories re-appeared and I am able to create articles and point to the right categories.

My concerned why did the upgrade 3.7.0 change the security settings. 


Could this be the reasons as this is only the changes to Category

https://github.com/joomla/joomla-cms/pull/11830

**Comment by jsubri** [comment] 2017-04-28 08:01
My 2ct, since 3.7 you shall explicitly add the corresponding User Groups to the Super User for the Super User to see the categories that belongs to the User Groups. Expected behaviour as stated above. I spotted the same pull id as you when I noticed that change early in the beta version.

**Comment by izoj2013** [comment] 2017-07-19 07:07
Just starting with Joomla. I have installed Joomla 3.7.3 on a linux mint 17.2, with php7.1 and mysql 5.7.
When trying to customise Photostar (copy) template, I get the following:

Warning
Warning: Failed to move file: /tmp/phpWbE8Za to /var/www/html/joomla/images/my_logo.png
Error
Unable to upload file.

After installation, I had issued the command on my_linux$: sudo chmod -R 755 /var/www/html/joomla.
BTW - I have no problems on a Windows 10 machine!!!

What am I missing on the linux box?

i.-<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15613">issues.joomla.org/tracker/joomla-cms/15613</a>.</sub>

**Comment by brianteeman** [comment] 2017-08-18 11:01
I am closing this as the expected behaviour. 

(the comment from @izoj2013 is completely unrelated to this )

**Closed by brianteeman** 2017-08-18 11:01 UTC
Labels: No Code Attached Yet
