### ISSUE TITLE
[4] Pagebreak modal missing style to make textboxes pop

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#30877] opened 2020-10-02 18:03 UTC
### Steps to reproduce the issue

Add article in Joomla 4 admin (tested using safari) 
Click CMS Content in wysiwyg edit
click page break
see modal load

### Expected result

The two text boxes to be bordered to provide clarity 

### Actual result

Missing the class attributes

<img width="816" alt="Screenshot 2020-10-02 at 19 01 38" src="https://user-images.githubusercontent.com/400092/94955057-ea4d0180-04e1-11eb-87a5-fd38581cdb81.png">

### System information (as much as possible)

Safari on Mac

**Comment by brianteeman** [comment] 2020-10-02 18:06
Duplicate of your existing issue #29992

**Comment by PhilETaylor** [comment] 2020-10-02 18:12
That previous issue was about the frontend, the hattip to the admin console in that issue was just to compare it to the frontend, it was not an issue reporting about the admin console. 

The screenshot of the admin console in that issue was clearly better than it is now. 

This is how it used to look:
<img width="621" alt="86534844-b575e200-bed3-11ea-8668-fd621f1ae59b" src="https://user-images.githubusercontent.com/400092/94955777-08673180-04e3-11eb-9699-608d920fd1c1.png">

Now its all washed out with no border at all. 

**Therefore this issue being open on its own is justified and not a duplicate.**

**Comment by PhilETaylor** [comment] 2020-10-02 18:50
And for the record the frontend looks terrible too now.

<img width="366" alt="Screenshot 2020-10-02 at 19 50 01" src="https://user-images.githubusercontent.com/400092/94959058-782beb00-04e8-11eb-8b0a-4292d77e1210.png">

**Comment by Quy** [comment] 2020-10-02 20:31
PR #30889

**Closed as completed by Quy** 2020-10-02 20:31 UTC
Labels: No Code Attached Yet
