### ISSUE TITLE
[com_config] No votes/ratings switches

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#18079] opened 2017-09-23 03:40 UTC
### Steps to reproduce the issue
Go to Global Configuration > Articles > List Layouts

### Expected result
Switches to toggle settings

### Actual result
![articles-list-layouts](https://user-images.githubusercontent.com/368084/30769817-911c1ba6-9fd5-11e7-8ff9-e8459adf6f9d.jpg)

### System information (as much as possible)
clean install of v3.8 with Sample Data

**Comment by ghost** [comment] 2017-09-23 05:02
Plugin "Content - Vote" isn't enabled. So its expected Behaviour.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18079">issues.joomla.org/tracker/joomla-cms/18079</a>.</sub>

**Comment by Quy** [comment] 2017-09-23 12:58
Shouldn't `Show Voting` behave in the same manner under Global Configuration > Articles > Articles?

**Comment by ghost** [comment] 2017-09-23 13:57
reopened.

@Quy don't get what you mean.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18079">issues.joomla.org/tracker/joomla-cms/18079</a>.</sub>

**Comment by Quy** [comment] 2017-09-23 16:27
When Content - Vote plugin is disabled, under Global Configuration > Articles:

Articles tab: `Show Voting` has a toggle switch
List Layout tab: `Show Votes in List` and `Show Ratings in List` have no toggle switches

Shouldn't all 3 settings behave the same to either show or not show switches dependent on the Vote plugin?

**Comment by ghost** [comment] 2017-09-23 16:30
got it. Both should only shown if Plugin is enabled.

**Comment by tonypartridge** [comment] 2017-09-23 22:42
@quy no they should not be grouped buttons since each of them two have more than 2 selectable options and therefore must be a list.

**Comment by Quy** [comment] 2017-09-23 22:51
You may misunderstood my explanation. When Vote plugin is disabled, the `Show Votes in List` and `Show Ratings in List` toggles do not appear as seen in the screenshot so you can not configure to show/hide. Yet, the `Show Voting` toggle can be configured. I assume the 3 settings are related to the Vote plugin. Therefore, either hide the 3 settings or toggles when the Vote plugin is disabled. I hope that is more clear.

**Comment by sandewt** [comment] 2017-09-30 18:57
If the content plugin "Vote" is disabled, I expect that the radio buttons remain visible (Joomla! 3.8.0).
That is now not the case!

See drawing "List Layouts":

![screen shot 2017-09-30 at 18 39 48](https://issues.joomla.org/uploads/1/c1a358554bbf2d0a6c06c27f8f8e9e10.png)

They remain visible in Joomla! 3.7.5 (as a show/hide switch, not as a radio button). 

See: JFormFieldVotelist extends wrong field #17370.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18079">issues.joomla.org/tracker/joomla-cms/18079</a>.</sub>

**Comment by alikon** [comment] 2017-10-16 08:00
can be closed for #18293

**Comment by ghost** [comment] 2017-10-16 08:02
closed as stated above.

**Closed as completed** 2017-10-16 08:01 UTC
Labels: No Code Attached Yet

**Comment by Quy** [comment] 2017-10-16 11:05
@franz-wohlkoenig This is still an issue. Please open.

**Comment by tonypartridge** [comment] 2017-10-16 11:06
@Quy why? why pull was merged? are you wanting to hide them based on if the plugin is enabled too?

**Comment by Quy** [comment] 2017-10-16 11:11
Why the switches hidden, but not the labels?

**Comment by alikon** [comment] 2017-10-16 19:00
sorry my fault @Quy is right cc: @tonypartridge 
please test #18354
