### ISSUE TITLE
[4.0] Installing Joomla is no more proposing to choose admin and site languages

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#27087] opened 2019-11-16 10:48 UTC
In J3, we can, after installing languages (including if we have already 2 languages installed in a J package) choose one of these languages as default for site and administrator.

This is not possible in J4. There is no more follow-up after the Install Languages page.
The necessary code is still present in the LanguagesModel but it is not used.

**Comment by HLeithner** [comment] 2020-01-02 11:25
Duplicate of #27059

**Closed as completed by HLeithner** 2020-01-02 11:25 UTC
Labels: No Code Attached Yet, J4 Issue
