### ISSUE TITLE
Missing Tooltips

### ISSUE THREAD

**Issue by kalpeshtailored** [joomla/joomla-cms#11051] opened 2016-07-08 09:25 UTC
#### Steps to reproduce the issue
1. Install latest Joomla CMS staging 
2. Login for administrator
3. Checked in Content > Categories > Edit category
4. Clicked on Publishing Tab
5. Mouse hover on Created Date, Created By, Modified Date and  Modified By  no tool-tips available

#### Expected result
» Tool-tips working fine in all fields, but in given highlighted fields no appear any tool-tips, So I expected consistency in all fields for field information.

#### Actual result
» In Edit Category all fields show with tool-tips but in given screenshot missing tool-tip.

#### System information (as much as possible)
» Joomla Version : Joomla! 3.6.0-rc  —  © 2016 joomlacmsstaging
» OS : Window 10
» Browser : Firefox 47.0

![screen shot 2016-07-08 at 04 21 48](https://issues.joomla.org/uploads/1/19f82516e7c82bdd8b6eda873b20015e.png)

**Comment by Bakual** [comment] 2016-07-08 10:01
For those fields, there is no description specified and thus no tooltip is shown. That is intended.
What tooltip would you expect for those fields? They are quite self-explanatory and don't need additional information imho.

Closing as it is not a bug.

**Comment by brianteeman** [comment] 2016-07-08 10:02
I am re-opening this - while @bakual is correct it is not consistent with the display of those same fields in other views. It seems to be only in com_categories that those fields do not have a tooltip

**Comment by gunjanpatel** [comment] 2016-07-08 10:04
Thanks for creating issue.
I think tooltip is not required here and I think that is why not added here. Label of the fields looks enough to explain what user will needs to enter. (This is what I am thinking. Not sure if it is still needed or not.)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11051">issues.joomla.org/joomla-cms/11051</a>.</sub>

**Comment by killoltailored** [comment] 2016-07-08 10:07
I have tested in OS: Windows 8.1, Browser: Firefox 47.0.1
Tool-tip not display on Created Date, Created By, Modified Date, Modified By fields
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11051">issues.joomla.org/joomla-cms/11051</a>.</sub>

**Comment by brianteeman** [comment] 2016-07-08 10:07
While I agree it is probably not needed it is not consistent with the display of those fields elsewhere - we should be consistent

**Comment by RonakParmar** [comment] 2016-07-08 10:08
I have checked in article edit view in publishing tab I can see tooltip for the mentioned fields, but not able to see tooltip in category edit page.

Joomla! 3.6.0-rc  —  © 2016 joomlacmsstaging<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11051">issues.joomla.org/joomla-cms/11051</a>.</sub>

**Comment by Bakual** [comment] 2016-07-08 10:10
Article is a bit different as it has published up/down and author fields instead of created and created by. So it's not exactly the same.
If someone wants to add a description for the field, here is the file to edit: https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_categories/models/forms/category.xml

**Comment by hardikPTailored** [comment] 2016-07-12 10:55
I have tested in OS: Ubuntu 12.04, Browser: Firefox 47.0.1
Created Date, Created By, Modified Date, Modified By fields are not display tool-tip.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11051">issues.joomla.org/joomla-cms/11051</a>.</sub>

**Comment by gunjanpatel** [comment] 2016-07-15 11:56
Set to "closed" on behalf of @gunjanpatel by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11051">issues.joomla.org/joomla-cms/11051</a>

**Comment by gunjanpatel** [comment] 2016-07-15 11:56
Closing as we have PR in #11144<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11051">issues.joomla.org/joomla-cms/11051</a>.</sub>

**Closed by gunjanpatel** 2016-07-15 11:56 UTC
Labels: No Code Attached Yet
