### ISSUE TITLE
mod_login (helper.php) problem switching language (J3.4.1 - 3)

### ISSUE THREAD

**Issue by europower** [joomla/joomla-cms#7348] opened 2015-07-06 06:29 UTC
#### Steps to reproduce the issue
After upgrading J3.4.0 to 3.4.2 (or 3.4.3) the mod_login switches language to **any language that is ordered to the last position** in the content language manager. It does this every time after login or logout.
[Posted on Joomla forum](http://forum.joomla.org/viewtopic.php?f=711&t=890828&p=3314714#p3314714 "Problem mod_login") 

#### System information
- Upgrade J3.4.0 to 3.4.2
- SEF turned off (when SEF is turned on, the issue does NOT occur)
- Also installed FALANG 2.0
- Template does not have mod_login override.
- default language is EN-GB (with 9 languages in total)

#### Additional comments
Only occurs with login module. (does not when using component for login)
When using "helper.php" from version J3.4.0 problem is also fixed.

**Comment by infograf768** [comment] 2015-07-06 07:37
You had not specified you used Falang on the forum.

As I can't reproduce your issue with a pure Joomla! set as multilingual, I suggest you contact the Falang developer.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7348">issues.joomla.org/joomla-cms/7348</a>.</sub>

**Comment by europower** [comment] 2015-07-09 13:22
The FaLang developer has found the problem and is working on a sollution  - follow at [Joomla forum](http://forum.joomla.org/viewtopic.php?f=711&t=890828&p=3314714#p3314714 "Joomla forum")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7348">issues.joomla.org/joomla-cms/7348</a>.</sub>

**Comment by sbouey** [comment] 2015-07-09 13:35
The problem occur when the mod_falang module is before the mod_login.

This is due to the line in the helper of mod_falang line 252 when i build the $language->link for non sef url
$uri->setVar('lang',$language->sef);
$language->link = JUri::getInstance()->toString(array('scheme', 'host', 'port', 'path', 'query'));
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7348">issues.joomla.org/joomla-cms/7348</a>.</sub>

**Comment by sbouey** [comment] 2015-07-09 13:37
It's seem the 

JUri::reset();
$language->link = JUri::getInstance()->toString(array('scheme', 'host', 'port', 'path', 'query'));

Work fine<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7348">issues.joomla.org/joomla-cms/7348</a>.</sub>

**Comment by zero-24** [comment] 2015-07-09 14:38
ok so as this is no Joomla Core Problem i'm closing here. Thanks :smile:

**Closed by zero-24** 2015-07-09 14:38 UTC
Labels: No Code Attached Yet
