### ISSUE TITLE
Fix warning mb_strpos(): Offset not contained in string com_search

### ISSUE THREAD

**Issue by f00x** [joomla/joomla-cms#30501] opened 2020-08-28 10:59 UTC
### Steps to reproduce the issue
Text search standard search component.
Joomla! 3.9.21
### Actual result
Warning: mb_strpos(): Offset not contained in string in \libraries\vendor\joomla\string\src\phputf8\mbstring\core.php on line 43

### System information (as much as possible)

( ! ) SCREAM: Error suppression ignored for
--

1 | 0.0003 | 411400 | {main}( ) | ...\index.php:0
2 | 0.0985 | 4669160 | Joomla\CMS\Application\SiteApplication->execute( ) | ...\index.php:49
3 | 0.0985 | 4669160 | Joomla\CMS\Application\SiteApplication->doExecute( ) | ...\CMSApplication.php:196
4 | 0.2201 | 8451648 | Joomla\CMS\Application\SiteApplication->dispatch( $component = ??? ) | ...\SiteApplication.php:233
5 | 0.2310 | 8686552 | Joomla\CMS\Component\ComponentHelper::renderComponent( $option = 'com_search', $params = ??? ) | ...\SiteApplication.php:194
6 | 0.2319 | 8690864 | Joomla\CMS\Component\ComponentHelper::executeComponent( $path = 'C:\\f00x\\projects\\golden.local/components/com_search/search.php' ) | ...\ComponentHelper.php:377
7 | 0.2320 | 8709064 | require_once( 'C:\f00x\projects\golden.local\components\com_search\search.php' ) | ...\ComponentHelper.php:402
8 | 0.2354 | 8891912 | SearchController->execute( $task = NULL ) | ...\search.php:13
9 | 0.2355 | 8891912 | SearchController->display( $cachable = ???, $urlparams = ??? ) | ...\BaseController.php:710
10 | 0.2355 | 8891912 | SearchController->display( $cachable = FALSE, $urlparams = FALSE ) | ...\controller.php:34
11 | 0.2479 | 9296176 | SearchViewSearch->display( $tpl = ??? ) | ...\BaseController.php:672
12 | 0.2959 | 10179144 | SearchViewSearch->highLight( $string = 'About', $needle = 'the', $searchWords = array (0 => 'the') ) | ...\view.html.php:153
13 | 0.2960 | 10179144 | SearchHelper::prepareSearchContent( $text = 'About', $searchword = 'the' ) | ...\view.html.php:219
14 | 0.2960 | 10179176 | SearchHelper::_smartSubstr( $text = 'About', $searchword = 'the' ) | ...\search.php:199
15 | 0.2961 | 10179208 | Joomla\String\StringHelper::strpos( $str = 'About', $search = ' ', $offset = 200 ) | ...\search.php:293
16 | 0.2961 | 10179208 | utf8_strpos( $str = 'About', $search = ' ', $offset = 200 ) | ...\StringHelper.php:185
17 | 0.2961 | 10179208 | mb_strpos ( 'About', ' ', 200 ) | ...\core.php:43

$offset = | int 200
$search = | string ' ' (length=1)
$str = | string 'About' (length=5)

### Additional comments
Correcting by change, but this is not the best solution
https://github.com/joomla/joomla-cms/commit/f13585189b09e172b6be9f9abdc58e68bfb3763d

**Comment by ReLater** [comment] 2020-08-28 14:23
I can't reproduce your find. I made several searches with com_search, error_reporting "maximum" and don't see any entries in my error log afterwards.

Perhaps your testing instructions aren't sufficient?

PHP7.4
Joomla3.9.21

**Comment by SharkyKZ** [comment] 2020-09-10 07:36
I was able to reproduce this on PHP 8 or by removing error suppression on older versions. Searched for `content` on site with testing sample data installed.

@f00x Your suggestion https://github.com/joomla/joomla-cms/pull/29008#issuecomment-682658228 works fine. Do you want to make a PR?

**Comment by SharkyKZ** [comment] 2020-10-26 08:02
@f00x Are you going to make the PR?

**Comment by HLeithner** [comment] 2020-11-20 22:47
@f00x can you please test #31444 closing this issue

**Closed as completed by HLeithner** 2020-11-20 22:47 UTC
Labels: No Code Attached Yet, PHP 8.x
