### ISSUE TITLE
version 4 beta 1 Invalid controller class: display

### ISSUE THREAD

**Issue by no-matter-0** [joomla/joomla-cms#26863] opened 2019-10-30 08:21 UTC
0

Php 7.2 localhost MAMP

I am having the same issue as here with Joomla_4.0.0-beta1-dev-Development (Monday, 28 October 2019 02:01:09 UTC)

4.0.0-beta1-dev Development [ Amani ] 17-October-2019 20:21 GMT

In admin panel, when trying to click on any Options, or Global configuration when calling administrator/index.php?option=com_config :

An error has occurred. 0 Invalid controller class: display

**Comment by no-matter-0** [comment] 2019-10-30 08:23
I mean as here : https://joomla.stackexchange.com/q/26316/12352<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26863">issues.joomla.org/tracker/joomla-cms/26863</a>.</sub>

**Comment by SharkyKZ** [comment] 2019-10-30 08:32
Duplicate of #25531.

**Comment by SharkyKZ** [comment] 2019-10-30 08:34
Did you update from any version or reinstalled through `com_joomlaupdate` component? Could be duplicate of https://github.com/joomla/joomla-cms/issues/25531.

**Comment by no-matter-0** [comment] 2019-10-30 08:36
I have updated 4 alpha 11  to 4 beta 1 dev directly from https://developer.joomla.org/nightly-builds.html<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26863">issues.joomla.org/tracker/joomla-cms/26863</a>.</sub>

**Comment by SharkyKZ** [comment] 2019-10-30 08:45
It's the same issue then. Updates are not supported yet. They should become supported at Beta.

**Comment by no-matter-0** [comment] 2019-10-30 08:46
#25531 solved it , com_config files were missing

thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26863">issues.joomla.org/tracker/joomla-cms/26863</a>.</sub>

**Closed as completed** 2019-10-30 08:46 UTC
Labels: No Code Attached Yet

**Comment by ghazal** [comment] 2019-11-23 10:21
> #25531 solved it , com_config files were missing

I confirm this. It works.
Thanks.
