### ISSUE TITLE
Banner Finish Publishing field date and time issue

### ISSUE THREAD

**Issue by JamalTailored** [joomla/joomla-cms#11969] opened 2016-09-07 12:14 UTC
### Steps to reproduce the issue
1. Create banner with image and select Publishing tab
2. Set past time(less then current time) in Finish Publishing field and save banner
3. Go to the Extensions -> Modules menu.
4. Click on New button, select "Banners" from the selection list
5. You will be redirected to the module detail page
6. You need to write module name and select Banner[banner] position (according to template) and save module
7. Go to site side 
### Expected result

if admin selected a past time (less then current time)in Finish Publishing field then banner should not be displayed.
### Actual result

Getting following error :

"jos-Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 3 SQL=UPDATE #__banners SET impmade = (impmade + 1) WHERE id IN ()"
### System information (as much as possible)

PHP Version 5.5.9-1ubuntu4
Joomla! Version Joomla! 3.6.3-dev Development [ Noether ] 5-August-2016 00:32 GMT
Joomla! Platform Version Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
### Additional comments

![screen shot 2016-09-07 at 07 12 54](https://issues.joomla.org/uploads/1/eac19f5ae62d0f88ec4d1ca5b4a9b909.png)

**Comment by brianteeman** [comment] 2016-09-07 12:18
Pretty sure you did not mean to tag this with MS SQL<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11969">issues.joomla.org/joomla-cms/11969</a>.</sub>

**Comment by brianteeman** [comment] 2016-09-07 12:35
How did you do step 2 - I always get
Error
Save failed with the following error: Item start publishing date must be before finish publishing date

**Comment by JamalTailored** [comment] 2016-09-07 12:39
I have manually edited time in past.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11969">issues.joomla.org/joomla-cms/11969</a>.</sub>

**Comment by brianteeman** [comment] 2016-10-09 10:28
OK so having manually set the banner to be expired and then displaying the banners on the front end I can not replicate your issue and get the expected result you identified.

Please can you retest and confirm that you can replicate this with one of the default templates and on a clean install of the latest staging release<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11969">issues.joomla.org/tracker/joomla-cms/11969</a>.</sub>

**Comment by PhilETaylor** [comment] 2016-10-20 18:55
This has something to do with timezones. I believe there is a fringe case still a problem in 3.6.3, and I have at least one other customer with it at the moment, Im waiting for their site logins to look myself deeper. 

What EXACT timezone are you using in Joomla Global Config

What EXACT time are you testing your site at (including where are you physically in the world, and whats your computer time/date at that time of testing)

What EXACT times are you inputting for the start/finishing times

ref: PR #11978 #11978 #11929

**Comment by PhilETaylor** [comment] 2016-10-20 18:59
For example. My Joomla Config time zone is FIJI, the time right now in FIJI is 06:56 Tomorrow.

My computer time now is 2016-10-20 19:55:49

However the SQL that attempts to load banners on my frontpage is using UTC times 

`SELECT a.id as id,a.type as type,a.name as name,a.clickurl as clickurl,a.cid as cid,a.description as description,a.params as params,a.custombannercode as custombannercode,a.track_impressions as track_impressions,cl.track_impressions as client_track_impressions FROM #__banners as a LEFT JOIN #__banner_clients AS cl ON cl.id = a.cid WHERE a.state=1 AND (a.publish_up = '0000-00-00 00:00:00' OR a.publish_up <= '**2016-10-20 18:55:49**') AND (a.publish_down = '0000-00-00 00:00:00' OR a.publish_down >= '**2016-10-20 18:55:49**') AND (a.imptotal = 0 OR a.impmade <= a.imptotal) ORDER BY a.sticky DESC,a.ordering`

This means that if you configure your banner to stop at 00:00 FIJI TIME - then the banner sql would be wrong, and could potentially show me a banner that should have stopped (or started) 

The time in the SQL should be converted from my local time (and/or GMT) to the local FIJI Time (as thats the timezone in the Joomla Config, before being placed in the SQL. 

Therefore I dont believe #11978 #11929 fixed the underlying issue.

**Comment by PhilETaylor** [comment] 2016-10-20 19:37
scratch that - I unpublished all banners and still I get the error 

`You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 3 SQL=UPDATE #__banners SET impmade = (impmade + 1) WHERE id IN ()`

I'll have to wait for the FTP details from the client to debug whats going on.

**Comment by peterwouda** [comment] 2016-10-21 10:19
Same problem here, exept in my case I don't use banners and then the same SQL-error appears. But after adding a dummy-banner the error is gone. Deleting the banner causes the error again.

**Comment by PhilETaylor** [comment] 2016-10-21 10:23
Funny you should say that you dont use banners, because when I trashed all the banners on this customers site, I still got the sql error too... which is strange. I did check caching was off... 

I still dont have access to that customers site to debug this, waiting on FTP details, their site is still down because of it. 

@peterwouda do you have a screenshot of the error? was it just the error? or a formatted page? did it mention jos-Error or not?  Do you have any template overides in your /templates/[templatename]/html/com_banners/ ?

**Comment by peterwouda** [comment] 2016-10-21 10:32
![screenshot_error_banner](https://cloud.githubusercontent.com/assets/18345618/19595464/5cab6268-978a-11e6-98a1-c9b19c9f30dd.png)

**Comment by peterwouda** [comment] 2016-10-21 10:33
I do not have overrides in /html/com_banners

**Comment by PhilETaylor** [comment] 2016-10-21 10:35
Thanks.
It would help nail this issue down if I could get access to play with your site later on tonight (UK Time) if that were at all possible. I understand if you do not wish to provide access, however there is obviously an issue that needs identifying and the easiest way is for an experienced developer to debug on a site that can replicate the issue time and time again. 

Please send me your site details using the form at https://fix.myjoomla.com/now and I'll take a look as soon as I can. There is no charge for this at all and your details will be encrypted and only used for the above purpose.

**Comment by peterwouda** [comment] 2016-10-21 10:37
OK, thanks! I will send it to you in about an hour or so. First I will recover the live-site.

**Comment by PhilETaylor** [comment] 2016-10-21 10:38
Excellent - Im travelling all day anyway (at an airport now) so there is no rush - if you can provide exact details on how to replicate the issue (and how to remove the issue on your live site, I think you said by adding a dummy banner) in the secure form when submitting the details as I need to see it "broken" and with the error message in order to debug the problem.

**Comment by alikon** [comment] 2016-10-22 05:10
i'm unable to reproduce this issue under 3.6.3
![bannere](https://cloud.githubusercontent.com/assets/181681/19617057/02be2c9e-9826-11e6-8d79-bdf0674db41d.PNG)

finish publishing was changed via phpmyadmin cause you cant't set finish publishing  <start publishing via banner edit

**Comment by PhilETaylor** [comment] 2016-10-22 13:03
I have raised a PR #12508 - that addresses a code quality issue, that causes this exception, Please test this - I have applied this on @peterwouda site and on another and it fixes both sites - its a fringe case to replicate, but the code was of poor quality in this area anyway - the PR makes it more reliable.

**Comment by peterwouda** [comment] 2016-10-25 18:17
It works fine now, no exceptions after testing with adding and deleting 
banners. Thanks!

Peter


Op 22-10-2016 om 15:03 schreef Phil Taylor:

**Comment by davenir** [comment] 2016-10-26 08:50
I just spent half a day attempting to sort this issue after upgrading to 3.6.4. 
Creating a banner or (inexplicably)changing to default template sorted it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11969">issues.joomla.org/tracker/joomla-cms/11969</a>.</sub>

**Comment by PhilETaylor** [comment] 2016-10-26 09:36
So does that mean you were using a custom template? Do you/did you have any custom template overrides for com_banners in your templates html folder?

**Comment by davenir** [comment] 2016-10-26 09:46
No there were no overrides for banners. The theme was "University" by Gavick which I reinstalled again to see if this was the issue but the error persisted. Also no relevant apache errors. Switching theme removed the issues. Only when I finally disabled Gavick's custom error page and got a more verbose error was I able to actually view the specific error..which led me here..

Disabling the banner STILL causes the issue unless I switch to Beez or similar default theme. I can provide URL if you're curious.

**Comment by PhilETaylor** [comment] 2016-10-26 09:50
the fact that changing themes fixes this issue, means that its highly likely to be a theme override of sorts. 

Im manic busy today but if you want to provide your site details securely at https://fix.myjoomla.com/now I'll take a quick look at your site to see if we can further nail this down - there is no charge, and no commitment - this is not official support, Im just looking to nail the issue down

Please also see the workaround in https://github.com/joomla/joomla-cms/issues/12508 which will fix the issue for you, but is not the best practice fix, more a belt and braces thing we can add in core.

**Comment by davenir** [comment] 2016-10-26 10:19
No problem Phil - publishing a non-visible banner is as good a fix as I need for the moment!

**Comment by PhilETaylor** [comment] 2016-10-26 10:21
I understand you needed a quick fix to get your siteonline, but providing a broken site as a test site for someone like me to replicate the issue every time is invaluable in debugging the root cause of the issue so it can be identified and fixed for the good of everyone - even if its not a Joomla core issue we can then put this to bed.

**Comment by davenir** [comment] 2016-10-26 10:26
Of course - I just meant that the site is online and working. I've added the site to myjoomla.com. ID: 11195130 if you're interested.

**Comment by PhilETaylor** [comment] 2016-10-26 10:27
that doesnt help me sorry - I need FTP access to debug this issue :)

**Comment by davenir** [comment] 2016-10-26 10:34
My apologies. I've submitted them as you did originally specify.

**Comment by PhilETaylor** [comment] 2016-11-20 08:11
Fixed with PR #12514 for 3.7 - Please close this @brianteeman

**Comment by brianteeman** [comment] 2016-11-20 10:01
Closed as requested<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11969">issues.joomla.org/tracker/joomla-cms/11969</a>.</sub>

**Closed** 2016-11-20 10:01 UTC
Labels: No Code Attached Yet
