### ISSUE TITLE
Updating Joomla removes libraries installed using Composer

### ISSUE THREAD

**Issue by v-escobar** [joomla/joomla-cms#17293] opened 2017-07-27 07:48 UTC
### Steps to reproduce the issue
Install something through composer and then update to a new version of Joomla

### Expected result
Nothing happens

### Actual result
Vendor folder get cleaned and all what you have installed using composer get deleted.

### Additional comments
I have created a composer.json file with all the dependencies needed by Joomla! and everytime I update my site, my dependencies get cleaned and I have to install them again. Deleting the content of vendor folder is not acceptable.

**Comment by zero-24** [comment] 2017-07-27 08:43
Please see here: https://docs.joomla.org/J3.x:Using_Composer_with_Joomla 

```
Can you install any extra libraries via Composer?

Not at the moment in Joomla! 3.4. In the longer term it is the CMS's aim that you can download extra packages. To emphasize this, we will not yet be releasing the composer.json file within the main Joomla! download.
```

Even that the behavior you are experience is not expected. The only thing that should happen is that all the files shipped by the CMS get overwritten by a update.

Please try to reproduce this in a clean install containing no 3rd party code and place a text file in the vendor folder.

**Comment by mbabker** [comment] 2017-07-27 11:39
We are not deleting the `library/vendor` directory contents.  What happens during the update which is presumably what is messing with your installation is the `library/vendor/composer` files are being overwritten, which contains the autoloader files for core and as such your additional libraries are being removed from that.

If you want to use Composer on your site, you'll need to install the dependencies to a different location and register the autoloader for your extra dependencies through a plugin.  You should not try to change the `libraries/vendor` folder in any way.

**Comment by brianteeman** [comment] 2017-07-27 20:47
I am going to close this for the reasons stated above

**Closed as completed by brianteeman** 2017-07-27 20:47 UTC
Labels: No Code Attached Yet
