### ISSUE TITLE
Call to undefined method JApplicationAdministrator::isClient()

### ISSUE THREAD

**Issue by Kulikovpavel** [joomla/joomla-cms#18044] opened 2017-09-21 12:08 UTC
Got error, after update from 3.4.8 to 3.8.0, with update package

### Steps to reproduce the issue

Update joomla from 3.4.8 to 3.8.0 with update file

### Actual result

"Fatal error: Call to undefined method JApplicationAdministrator::isClient() in /www/plugins/system/logout/logout.php on line 48" on all pages

**Comment by ghost** [comment] 2017-09-21 12:10
can you try update 3.4 > 3.5 > 3.6 > 3.7 > 3.8?

**Comment by ggppdk** [comment] 2017-09-21 12:19
Try updating all your 3rd party extensions
one of them maybe replacing this class

**Comment by Kulikovpavel** [comment] 2017-09-21 14:08
3.6.5 files work good, no error, btw.

**Comment by mbabker** [comment] 2017-09-21 14:13
3.6.5 doesn't have the method that is causing your error.

You're having two problems.

1) Updates from before 3.6.1 to 3.8.0 are having several problems right now, see other open issues on this repo
2) Assuming you actually did complete the full update (got the "successfully upgraded" message), `JApplicationAdministrator` isn't a "real" class in 3.8 anymore and shouldn't be used in an error message (this concept has been explained in other issues too)

Follow https://gist.github.com/mbabker/d7bfb4e1e2fbc6b7815a733607f89281 to upgrade the 3.4.8 install to 3.7.5 (https://downloads.joomla.org/cms/joomla3/3-7-5/Joomla_3-7.5-Stable-Update_Package.zip?format=zip is the package you'll need for that).  Then use the core update component to upgrade 3.7.5 to 3.8.

**Comment by PhilETaylor** [comment] 2017-09-21 21:00
ive run into this several times today - once you rename the logout folder you get another error about the remember file, I rename that and the install kinda completes fine, then I have to run the post-update script (provided by @mbabker here https://gist.github.com/PhilETaylor/a291525b1539b2254a5ea7a36c458ded and then all is good :) 

However, listen, if you have a site that is Joomla 3.6.1 or below, then I have absolutely no sympathy for you at all. Yes it should work seamlessly, but if you had bothered keeping up to date then you would not have run into this bug in the first place. Nuff said.

**Comment by Kulikovpavel** [comment] 2017-09-22 07:29
Sad story, that was long update from 1.7.3, with several steps, 1.7.3 -> 1.7.5 -> 2.5.0 ->.... Don't tell anything :) Legacy.

**Comment by AlexRed** [comment] 2017-09-29 12:04
I can confirm the problem from 3.5.1 to 3.8.0
(from a 2.5.28 update)

**Comment by AWilco** [comment] 2017-10-03 14:39
If this is being investigated, I found this error from my update was caused by the /libraries/cms/application directory not being deleted (the latest version only has 3 subdirectories in it). Replacing this folder with with the files a fresh install leads to another error...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18044">issues.joomla.org/tracker/joomla-cms/18044</a>.</sub>

**Comment by uglyeoin** [comment] 2017-11-14 18:40
I had this issue the other day, I think I resolved it by copying a fresh copy of the "libraries" folder.  After that I got a new error about Admin Tools/Akeeba Backup.  I renamed the folders, logged in, reinstalled and then everything was ok.

**Comment by daneyuleb** [comment] 2017-12-12 02:50
>  However, listen, if you have a site that is Joomla 3.6.1 or below, then I have absolutely no sympathy for you at all. Yes it should work seamlessly, but if you had bothered keeping up to date then you would not have run into this bug in the first place. Nuff said.

What an annoying, ignorant statement. As if everyone who is tasked with updating a site is responsible for the owner's previous update schedule, or as if people don't have local test sites they don't access regularly but sometimes need to. 

Yes, it should be seamless, or at least warn about the ridiculous crap shoot it is with Joomla  to update from previous versions.

**Comment by scottstreet** [comment] 2017-12-19 00:16
Had this exact error today when upgrading from 3.6.5 to 3.8.3, sorry mbabker.

Just pushed the "Upgrade now" button, silly me.

Error was same as title of this topic. So far I did what awilco and uglyeoin have suggested and have:
1. downloaded the full install package https://downloads.joomla.org/us/cms/joomla3/3-8-3 and 
2. extracted all and compressed only the libraries folder and 
3. uploaded and extracted that folder with all subdirectories.

Result is site is working again. But no back end and some other small errors.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18044">issues.joomla.org/tracker/joomla-cms/18044</a>.</sub>

**Comment by ghost** [comment] 2017-12-19 06:24
@scottstreet i suggest to ask help on the [forums - Migrating and Upgrading to Joomla! 3.x](https://forum.joomla.org/viewforum.php?f=710) if you haven't.

**Comment by scottstreet** [comment] 2017-12-19 07:54
Yes, I have been over there too. But that page was inconclusive and I wanted to report what I did in clear fashion for the next person. 

scott

**Comment by ghost** [comment] 2017-12-19 08:11
@scottstreet thanks for Info. Can you give please Forum-Thread so People can see what was discussed?

**Comment by Quy** [comment] 2018-01-06 04:43
It is my understanding that upgrade issues should be posted in [Migrating and Upgrading to Joomla! 3.x forum](https://forum.joomla.org/viewforum.php?f=710). There is a [closed issue](https://github.com/joomla/joomla-cms/issues/16603#issuecomment-331232244) that has a fix to this issue.

**Comment by ghost** [comment] 2018-01-06 07:01
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18044">issues.joomla.org/tracker/joomla-cms/18044</a>.</sub>

**Closed as completed by ghost** 2018-01-06 07:01 UTC
Labels: No Code Attached Yet

**Comment by vinitbajaj** [comment] 2019-12-02 07:55
Thanks your guidance solved the issue easily.
