### ISSUE TITLE
Too many redirects on a password reset

### ISSUE THREAD

**Issue by Stevec4** [joomla/joomla-cms#40729] opened 2023-06-06 14:56 UTC
### Steps to reproduce the issue
In the back end I set a user to reset their password. Password reset required is displayed next the usersname

The user then logs into the front end of the site normally, there is no message or dialog to reset the password and they have access to the whole site,
When the logged in user attempts to log out they are presented with "ERR_TOO_MANY_REDIRECTS" in the browser window
Closing the browser and navigating back to the page shows the profile page and the opportunity to change the password. 

If the user closes their browser and then attempt to go to the site they are brought back to this page but appear to still be logged in

### Expected result
Notify the user that a password reset is required 
present a reset password window 
prevent the user from viewing the site in until a password reset is completed. 

### Actual result
No message is displayed, and the user can view the entire site. When logging out the user is told they have too many redirects
"ERR_TOO_MANY_REDIRECTS"

This behavior occurs using Chrome / Edge / Firefox browsers

### System information (as much as possible)
=============
System Information
=============
php: Linux  3.10.0-962.3.2.lve1.5.67.el7.x86_64 #1 SMP Fri Mar 25 07:13:21 UTC 2022 x86_64
dbserver: mysql
dbversion: 10.5.20-MariaDB-log
dbconnectioncollation: utf8mb4_general_ci
dbconnectionencryption: 
dbconnencryptsupported: false
phpversion: 8.0.28
server: Apache
sapi_name: cgi-fcgi
version: Joomla! 4.3.2 Stable [ Bora ] 30-May-2023 16:00 GMT

**Comment by toivo** [comment] 2023-06-07 04:13
Unable to reproduce the message about too many redirects.  However, the option 'Require Password Reset' for a front end user does not change the login behaviour at the front end. In other words, the user is not forced to reset the password to be able to continue the session, as it used to be. At the back end the option 'Require Password Reset' remains turned on and the user listing shows 'Password Reset Required' under the name of user in the Name column.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40729">issues.joomla.org/tracker/joomla-cms/40729</a>.</sub>

**Comment by Stevec4** [comment] 2023-06-07 13:21
Thanks for confirming Toivo, 
Maybe the message is generated due to my setup. The site is set up for registered users only, and has a hidden log in menu item set to public, The log out menu item is set to registered clicking on the log out menu item is when the message occurs on my site.

**Comment by Stevec4** [comment] 2023-06-07 15:10
Log out is redirected to the log in form. which does not create any redirect issue normally.

![log out](https://github.com/joomla/joomla-cms/assets/6751354/a21eb995-c855-4a1d-ae01-eaecd3ad91d2)

**Comment by KeesZNL** [comment] 2023-07-10 03:52
I can reproduce this error.
# **Steps to reproduce the issue**![screen shot 2023-07-10 at 03 46 44](https://issues.joomla.org/uploads/1/4a9d5c70f6a4d958e2ca3cdc5acd323b.png)
The user option "reset password required" is enabled. (image 1)
There is no menu item profile defined in the menu "for members" (the absence of this menu item causes the error: too many redirects if the user logs out before entering the new password. If this menu item is enabled then the error does not appear).
Login option refers to "Members menu" with menu item: "Members only". (image 2)
Logout option refers to the home page. (image 3)
# **Expected result**
As soon as the user logs in, the "Set password required" page is displayed, which means that information should not be visible to members whose new password has not been re-entered and validated.
## **Actual result**
The user first sees the complete entire "Members Only" page including the defined modules on that page. (data breach?)
The user must first click on a link on that page. Only then will the screen appear: "Password reset required".
The user is listed as "logged in" in the admin console. (???)
If the menu item "Reset password" is not enabled and the user logs out before resetting the password, the error "ERR_TOO_MANY_REDIRECTS" occurs.
I do not find it acceptable that member information is shown before the password reset procedure is completed.

The website has just been upgraded from version 3.10.11 to 4.3.2. In 3.10.11 this worked flawlessly.![screen shot 2023-07-10 at 03 46 44](https://issues.joomla.org/uploads/1/b8b28f2bdfe0d887631a7c7b618bf74f.png)![screen shot 2023-07-10 at 03 46 44](https://issues.joomla.org/uploads/1/68d6252eecd706dc4bc86481dc825a52.png)
## **System information**
HP gebouwd op	Linux linux2029.webawere.nl 4.18.0-305.17.1.lve.el8.x86_64 #1 SMP Wed Sep 8 06:07:49 EDT 2021 x86_64
Databasetype	mysql
Database versie	10.6.13-MariaDB
Database collatie	latin1_swedish_ci
Collatie van de databaseverbinding	utf8mb3_general_ci
Database verbinding versleuteling	Geen
Databaseserver ondersteunt verbindingsversleuteling	Nee
PHP versie	8.1.18
Webserver	LiteSpeed
Webserver naar PHP interface	litespeed
Joomla! versie	Joomla! 4.3.2 Stable [ Bora ] 30-May-2023 16:00 GMT
Gebruikersagent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40729">issues.joomla.org/tracker/joomla-cms/40729</a>.</sub>

**Comment by KeesZNL** [comment] 2023-07-10 03:59
Please see also: https://github.com/joomla/joomla-cms/issues/39895<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40729">issues.joomla.org/tracker/joomla-cms/40729</a>.</sub>

**Comment by KeesZNL** [comment] 2023-07-10 04:19
Simular: https://github.com/joomla/joomla-cms/issues/38788<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40729">issues.joomla.org/tracker/joomla-cms/40729</a>.</sub>

**Comment by Stevec4** [comment] 2023-08-12 19:14
This problem has been reported several times since Joomla 4.2 yet it does not get a bug tag or anyone trying to work to remedy it.
What does it take to elevate this to a problem that a developer will look into it?

**Comment by JohnVesey** [comment] 2024-02-11 09:41
I can confirm this. Suggest it's a priority.

Redirect loop occurs when privacy consent expired and MFA enabled on my Super User Account. Logging in to frontend should go to User Profile page to accept privacy consent but redirect loop occurs. User is actually logged in but can't do anything due to redirect loop/expired privacy consent.

Work around: Disable MFA in admin, login to frontend, accept privacy consent, logout of frontend, reset MFA on the account in Admin.

Joomla 5.0.2 (b/c plugin enabled)
PHP 8.2.9
Maria-db 10.6.15-live

Hope this helps

John V<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40729">issues.joomla.org/tracker/joomla-cms/40729</a>.</sub>

**Comment by Hackwar** [comment] 2024-11-24 23:00
This is actually a duplicate of #38788. Since it is a duplicate, I'm closing this one. I'm looking into a fix right now.

**Closed as completed by Hackwar** 2024-11-24 23:00 UTC
Labels: No Code Attached Yet, bug
