### ISSUE TITLE
Joomla 3.7 - Unable to select item alias, heading, text separator in base item (mod_menu)

### ISSUE THREAD

**Issue by aaron-harding** [joomla/joomla-cms#16051] opened 2017-05-16 14:39 UTC
### Steps to reproduce the issue
Setup some menu items which consist of:
- article
- text separator
- menu heading
- alias
- url
- article

### Expected result
When creating a menu module, selecting the "Base Item" option should display all menu items.

### Actual result
When creating a menu module, selecting the "Base Item" option only shows menu items which point to a component (article, category etc...)

### System information (as much as possible)
**Database Version**: 	        5.6.35
**PHP Version**: 	                7.0.14
**Web Server**: 	                Apache
**Joomla! Version**:	        Joomla! 3.7.0 Stable [ Amani ] 25-April-2017 15:36 GMT
**Joomla! Platform Version**: 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

### Additional comments
Testing this in Joomla 3.6.5, the base item option lists menu items of all types. After upgrading from Joomla 3.6.5 to Joomla 3.7 it has broken a couple of my menu modules. I have a list of menu items which are children of my "Heading" menu. I was using the module to list only child items of my "Heading" menu but I can no longer select this menu item in the modal to achieve this.

**Comment by Devportobello** [comment] 2017-05-16 15:23
Duplicate of https://github.com/joomla/joomla-cms/issues/15617

**Comment by franz-wohlkoenig** [comment] 2017-05-16 16:02
closed as duplicate Report #15617<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16051">issues.joomla.org/tracker/joomla-cms/16051</a>.</sub>

**Closed by franz-wohlkoenig** 2017-05-16 16:02 UTC
Labels: No Code Attached Yet
