### ISSUE TITLE
Suffix class ignored on custom module

### ISSUE THREAD

**Issue by diyfr** [joomla/joomla-cms#39520] opened 2022-12-29 10:58 UTC
### Steps to reproduce the issue  
Define  an custom module, with suffixe class  
see documentation [here](https://help.joomla.org/proxy?keyref=Help42:Site_Modules:_Custom&lang=fr#Advanced_Tab)
### Expected result  
Suffix class append to custom module  
### Actual result  
No suffix class  
### System information (as much as possible)
Current version `4.2.6` (and Master branch)        

### Additional comments  
Solution :  
Edit `modules/mod_custom/tmps/default.php`  
replace [L29](https://github.com/joomla/joomla-cms/blob/4.2-dev/modules/mod_custom/tmpl/default.php#L29)  
```php
<div id="<?php echo $modId; ?>" class="mod-custom custom">
    <?php echo $module->content; ?>
</div>
```
by  
```php
<div id="<?php echo $modId; ?>" class="mod-custom custom<?php echo $params->get('moduleclass_sfx'); ?>">
    <?php echo $module->content; ?>
</div>
```

**Comment by sandewt** [comment] 2022-12-29 13:46
Is this issue only limited to the custom module? I suspect this is also the case for other modules.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39520">issues.joomla.org/tracker/joomla-cms/39520</a>.</sub>

**Comment by brianteeman** [comment] 2022-12-29 14:19
This is not a bug and it is the intended behaviour that you will see in all modules.

The module class sfx is added by the module chrome 

https://github.com/joomla/joomla-cms/blob/22184cbc06004a99125e2fac3756ee526bc19392/layouts/chromes/html5.php#L26

The module chrome is defined for the module position in the template - in this case the chrome is **card**
https://github.com/joomla/joomla-cms/blob/22184cbc06004a99125e2fac3756ee526bc19392/templates/cassiopeia/index.php#L221

The chrome defined in the template can also be overridden at the module level here
![image](https://user-images.githubusercontent.com/1296369/209966067-456115b1-1b08-4b6a-9a30-5e13428d41c8.png)

In some templates you will see a module with a style=none
That means its using the  chrome none.php and this one does **not** have the code wrapping the module output with the module class sfx

https://github.com/joomla/joomla-cms/blob/22184cbc06004a99125e2fac3756ee526bc19392/layouts/chromes/none.php#L13

**Comment by richard67** [comment] 2022-12-29 15:02
In addition it should be mentioned that the class is not a suffix anymore. It is not appended as a suffix but as a class, with a space, as you can see by the code mentioned in the previous comment. In the UI the field has been renamed, but the parameter name `moduleclass_sfx` has not been renamed for b/c reasons so that name might be a bit misleading when reading code.

**Comment by richard67** [comment] 2022-12-29 15:04
Closing as expected behaviour for the reasons mentioned in previous comments. Feel free to reopen if you think this is wrong.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39520">issues.joomla.org/tracker/joomla-cms/39520</a>.</sub>

**Closed as completed by richard67** 2022-12-29 15:04 UTC
Labels: No Code Attached Yet

**Comment by sandewt** [comment] 2022-12-29 19:35
Thks for the info
