### ISSUE TITLE
[4.0] Media manager modal size incorrect when trying to insert image in admin

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15796] opened 2017-05-03 14:27 UTC
### Steps to reproduce the issue

Edit article in Joomla 4 with default editor
Click Image button in the wysiwyg editor toolbar

### Expected result

modal of appropriate

### Actual result

<img width="1266" alt="screen shot 2017-05-03 at 15 25 30" src="https://cloud.githubusercontent.com/assets/400092/25665283/0b6e248e-3015-11e7-8e86-f7ee1fb99d76.png">
 size

**Comment by brianteeman** [comment] 2017-05-03 15:05
closing as expected behaviour due to media manager being completely replaced for j4

**Closed by brianteeman** 2017-05-03 15:05 UTC
Labels: No Code Attached Yet

**Comment by PhilETaylor** [comment] 2017-05-03 15:08
The size of the modal is nothing to do with the media manager or the url it contains at all...

**Comment by brianteeman** [comment] 2017-05-03 15:11
whatever - you really are wasting both your own and everyone elses time with these tests. J4 is nowhere near ready for this type of testing. If it was then we could all raise thousands of issues. Lets give the people working on it a chance to complete what they are doing before testing. 

For example there are 100+ css classes that need to be replaced so it is expected that layouts are wrong.

**Comment by PhilETaylor** [comment] 2017-05-03 15:16
oh give me a break and attack someone else. 

So I'm **wasting my own time and everyone elses time** by testing the 4.0 branch - and you are doing what exactly? https://github.com/joomla/joomla-cms/issues/created_by/brianteeman hmmm talk about pot calling the kettle black! 

>  it is expected that layouts are wrong.

Yet you raise issues about css. double standards much! https://github.com/joomla/joomla-cms/issues/15697
