### ISSUE TITLE
Update from 3.4.5 to 3.4.6 to 3.4.7: error in backend: You are not permitted to use that link to directly access that page

### ISSUE THREAD

**Issue by level420** [joomla/joomla-cms#8731] opened 2015-12-18 14:48 UTC
Running Joomla 3.4.6 on centos 7.2, httpd 2.4.6, mariadb 5.5.4. Upated from 3.4.5 via backend joomlaupdate. Applies to both backend templates isis and Hathor.

After successfully logging in and editing one article by clicking on the article title and afterwards clicking "Save & Close", trying to edit that article again by clicking on the title of that article leads to an error message "You are not permitted to use that link to directly access that page (#someid)".

Another attempt to click on the title for editing does simply reload the page, but does not open the editor and does not display the error message above. This behavior remains until logging out and logging in again.

Please note that selecting the article via the left side check box and then clicking on the edit button does work, even repeatedly.

**Comment by level420** [comment] 2015-12-18 15:04
May be related to #8689

**Comment by level420** [comment] 2015-12-21 10:13
It seems that the subsequent ignored clicks on the article title come from the GET request with status code 303 being cached by e.g. Chrome 47.

When disabling the Chrome cache (within developer tools network tab, check button "Disable cache") everything is working as expected.

**Comment by level420** [comment] 2015-12-21 14:46
Unfortunately or fortunately, which depends on your point of view, since approx. 14:30 CET suddenly everything started working again, without having done anything. I don't know what's going on here. Kind of spooky!

The issue was at first verified to be there by two colleagues of mine with Chrome 47 and 48 on Windows 7 and IE 11.

This morning i verified the issue on two fresh joomla installations, a 3.4.5 instance where the problem didn't show up and 3.4.6 instance where the issue was reliably present.

Today one colleague also verified that the problem is gone without changing anything.

I'm closing this issue, til we maybe can reproduce it again.

**Comment by level420** [comment] 2015-12-22 09:02
After update to 3.4.7 the behaviour is back.

To reproduce:

1. Logout from backend if logged in
2. go to Content and click on a article titel to edit
3. on the edit page click "Save & Close"
4. back on the article list click the save article title again

you'll get the message 

Error
You are not permitted to use that link to directly access that page (#72).

on first click. For all consecutive clicks the article list simply reloads.

**Comment by PhilETaylor** [comment] 2015-12-22 09:16
This is a non-issue - clear your cache, logout, clear your cache and kill your session and then everything will be fine.

**Comment by tampe125** [comment] 2015-12-22 09:18
I updated a site to Joomla 3.4.7 => visit link => error
Signed out/login again => visit link => success

What's your session handler? Do you have any cache enabled?

**Comment by level420** [comment] 2015-12-22 09:25
@tampe125 Cache: "OFF - Caching disabled", Cacha Handler: "File", Cache Time: "15".

And yes after logging out and logging in again the first edit succeeds. Please edit the same article again and again by clicking the article title!

**Comment by Kubik-Rubik** [comment] 2015-12-22 09:36
I can not reproduce it on 3 completely different instances. It looks like a local problem on your Joomla! installation.

**Comment by level420** [comment] 2015-12-22 09:51
@PhilETaylor I've allready cleared all caches in joomla and the browser and explicitly deleted all cookies. Terminated all browser instances.

**Comment by PhilETaylor** [comment] 2015-12-22 10:00
@level420 I'm sorry but I cannot replicate it. 

What is your exact PHP version?

**Comment by level420** [comment] 2015-12-22 10:04
php version is 5.4.16 on centos (rhel) 7.2, which means that there are a lot of backported patches from higher versions.

**Comment by PhilETaylor** [comment] 2015-12-22 10:41
Duplicate issue - see: #8757

Please close this one.

**Comment by infograf768** [comment] 2015-12-22 10:42
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8731">issues.joomla.org/joomla-cms/8731</a>

**Comment by infograf768** [comment] 2015-12-22 10:42
See https://github.com/joomla/joomla-cms/issues/8757<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8731">issues.joomla.org/joomla-cms/8731</a>.</sub>

**Closed by infograf768** 2015-12-22 10:42 UTC

**Comment by durian808** [comment] 2016-01-28 22:00
@level420, you are very right to keep this issue open.  I first started working on this glitch in 2012 and can report today that it is still occurring.  This relates to a 403 Forbidden error produced by code in this file: ./components/com_content/controller.php.  The same code is in J2.5.x and J3.4.8.  You can see my extensive research into the subject in this old bug tracker:  http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=29000.  See "John Calvert" and scroll down to see the whole story.

If this is related to caching, or proxies, or timing... that is no excuse... we need to determine why this is happening in the field and find a solution inside of Joomla so that it doesn't keep rearing it's ugly head.  It's not browser specific.  The key is that Joomla's response to whatever condition is causing this is not the appropriate one, which presently is just giving the user a mysterious and frustrating message.  We actually don't know that the root cause of this has anything to do with caching, proxies, or timing... it could be an actual defect in Joomla's coding, which is precipitated by caching, proxies, timing, (fill in the blank).

My background:  I have 10 years of experience working with Joomla, PHP programming, and server administration.  Before that I was a system software engineer for over 20 years.

So, let's fix this thing!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8731">issues.joomla.org/joomla-cms/8731</a>.</sub>

**Comment by durian808** [comment] 2016-01-30 04:05
This issue has been reopened here:
https://issues.joomla.org/tracker/joomla-cms/9013<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8731">issues.joomla.org/joomla-cms/8731</a>.</sub>
