### ISSUE TITLE
Shared sessions require extensions update

### ISSUE THREAD

**Issue by joeforjoomla** [joomla/joomla-cms#13314] opened 2016-12-21 10:21 UTC
### Steps to reproduce the issue

Activate shared sessions in the global configuration

### Expected result
Everything works as before

### Actual result
Extensions expecting the #__session table field as client_id = 0 or client_id = 1 fail because the field client_id is left NULL

Wouldn't be better to leave by default the client_id set as 0 when a shared session is started and mark it adding a new field to the #__session table? That would avoid the need to update all extensions to evaluate the field not only as 0 but even as NULL

**Comment by zero-24** [comment] 2016-12-21 20:00
Should any extension check the #__sessions table direkt? Don't we have a api for that in JSession ?

https://github.com/joomla/joomla-cms/tree/staging/libraries/joomla/session

I'm not that familiar with that part of the Libs but I would expecte something there.

And if we set any value which should we use? If you query that table direkt we need both values there so nothing is won / changed in that game or do i miss something? ;)

**Comment by mbabker** [comment] 2016-12-21 20:05
We decided to set it as NULL because client_id 0 implies the session is assigned specifically to the site application.  It should be treated similarly to a foreign key in that the client_id if assigned matches directly with a Joomla application client and NULL if it is not bound.

The only parts of Joomla affected by this change are if you're creating a "who's online" feature or logout handlers.  Beyond that there are few legitimate cases where direct reading of the session database table (and remember though it'll always have this extraneous session metadata that can't be turned off it won't always be the actual session's storage handler) should be considered.

**Comment by mukul11** [comment] 2016-12-22 11:13
If you query that table direkt we need both values there so nothing is won / changed in that game or do i miss something?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13314">issues.joomla.org/tracker/joomla-cms/13314</a>.</sub>

**Comment by zero-24** [comment] 2016-12-22 11:38
@mukul11 why did you just quote me? Is something of your comment missing?

**Comment by Bakual** [comment] 2016-12-22 13:03
@zero-24 Because he is a spammer. Already reported and blocked him.

**Comment by PhilETaylor** [comment] 2017-01-11 13:36
can this be closed then?

**Comment by Bakual** [comment] 2017-01-11 13:58
Since it's basically a new feature, admins will have to make sure each extension supports it before using it. Same as for other new features.

Closing as expected behavior.

**Closed by Bakual** 2017-01-11 13:58 UTC
Labels: No Code Attached Yet
