### ISSUE TITLE
[4.0] Error on modal article edit

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#23877] opened 2019-02-11 18:21 UTC
### Steps to reproduce the issue
Backend, Menus, New Menu Item.
Select Menu Item Type: Single Article.
Choose "New Article"
A modal window for edit article is opened
Write an article and "save and close"

### Expected result
Click on save and Close stores the article and closes the modasl

### Actual result
Nothing happens - js-error: 
![screen shot 2019-02-11 at 18 20 56](https://issues.joomla.org/uploads/1/97f4d6cb6861f5e9ae7eea416f2634b5.png)

**Comment by Quy** [comment] 2019-02-11 18:42
Duplicate #23260?

**Comment by chmst** [comment] 2019-02-11 20:20
@Quy - I don't know :) but probably yes

**Comment by Quy** [comment] 2019-02-11 23:37
Duplicate of #23393<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23877">issues.joomla.org/tracker/joomla-cms/23877</a>.</sub>

**Closed as completed by Quy** 2019-02-11 23:37 UTC
Labels: No Code Attached Yet
