### ISSUE TITLE
Dupplicated module won't accept different Module Class Suffixes

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#9302] opened 2016-03-04 15:35 UTC
#### Note
This only applies to 3rd party modules, not core ones!

#### Brief
Let say for example you want to display a module in position `X` on desktops, but on mobile, you want to display it in position `Y`.

#### Steps to reproduce the issue
1. Install any **3rd party** module ([example](https://github.com/C-Lodder/test-module))
2. Set the **first** instances to `position-7`
3. Assign the **first** instances to a module class suffix of ` visible-desktop`
4. Set the **second** instances to `position-8`
5. Assign the **second **instances to a module class suffix of ` visible-phone`
6. Ensure they're both assigned to the same page

#### Expected result
- The **first** instance should display on large a viewport size (desktop)
- The **second** instance should display on a small viewport size (mobile)

#### Actual result
Both modules display on large a viewport size (desktop)

#### System information (as much as possible)
**Joomla**: 3.4.8
**PHP**: 5.5
**MySQL**: 5.6

**Comment by SharkyKZ** [comment] 2016-03-04 18:44
I cannot reproduce this on 3.5.0 Beta 3. Note that you must add a leading space before suffix class. The space is not seen in test instructions.

**Comment by C-Lodder** [comment] 2016-03-04 19:39
I'm aware of the space needed for a module class suffix. I'll give it a test on J3.5-beta 3

**Comment by SharkyKZ** [comment] 2016-03-04 19:43
What HTML output are you getting? Which template and module chrome are you using?

Note about spaces, some module chromes have a space added before module suffix, e.g. https://github.com/joomla/joomla-cms/blob/staging/templates/protostar/html/modules.php#l47
Not sure if this was intended. Because none of system module chromes have this.
https://github.com/joomla/joomla-cms/blob/staging/templates/system/html/modules.php

**Comment by C-Lodder** [comment] 2016-03-05 10:28
Using the default Protostar template and the `Inherited` mocChrome. I've also tried switching to the `html5` modChrome.

**Comment by brianteeman** [comment] 2016-03-07 22:47
Tested on beta4 with protostar
Scenario1
Visible-desktop position8
Visible-phone position7
Works as intended


Scenario2
Visible-desktop position7
Visible-phone position7
Works as intended

Scenario3
Scenario1
Visible-desktop position7
Visible-phone position8
Works as intended


Note that although the module is not displayed on desktop it is still counted as existing by the logic in the template that decides if it should display the column so you do get an empty column. - This is a known issue what despite numerous attempts has not been resolved

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9302">issues.joomla.org/joomla-cms/9302</a>.</sub>

**Comment by brianteeman** [comment] 2016-04-19 18:09
It has been 4 weeks since the last comment showing that there was no issue so I am closing this. If you have any further issues and can provide more information to replicate the issue it can always be reopened<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9302">issues.joomla.org/joomla-cms/9302</a>.</sub>

**Closed** 2016-04-19 18:09 UTC
Labels: No Code Attached Yet
