### ISSUE TITLE
Mass Mailer BCC option not working

### ISSUE THREAD

**Issue by westiefan** [joomla/joomla-cms#17487] opened 2017-08-11 09:35 UTC
### Steps to reproduce the issue

Have multiple users set up in User manager
Go to "Users -> Mass Mail Users"
Add a subject and test message
Check the "Recipients as BCC" check box
Select any group or leave as default "All User Groups"
Click "Send Email" button

### Expected result

Email sent with all recipints email addresses hidden (e.g. in Bcc field)
Recipient receives email with no list of email addresses in "to" field except for sender email address

### Actual result

All recipient email addresses listed in "To" field

### System information (as much as possible)

Joomla 3.7.4
PHP 7.0.21

### Additional comments

This has been discussed in the Joomla forums as having been an issue since Joomla 3.3.6, but it is the first time I have used the mass mailer on one of my client sites.

John

**Comment by ghost** [comment] 2017-08-11 09:40
closed as duplicate Report of #17223<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17487">issues.joomla.org/tracker/joomla-cms/17487</a>.</sub>

**Comment by brianteeman** [comment] 2017-08-11 09:50
This is not the same issue
That issue said that bcc should be enabled by default
This issue says that bcc does not work when checked

**Comment by westiefan** [comment] 2017-08-11 16:47
Corrected a Typo<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17487">issues.joomla.org/tracker/joomla-cms/17487</a>.</sub>

**Comment by zero-24** [comment] 2017-08-13 13:57
hmm can you please double check that issue by installing staging?

**Comment by westiefan** [comment] 2017-08-13 16:58
Not sure how to use staging as never used it (or patches from GitHub) before.  This issue is on a live site, so have to be careful what I do on it.  It is using the latest stable version of Joomla, and based on what I have been reading in the forums about this issue, and just to clarify, as I mentioned in my initial report it appears to have been an issue since version 3.3.6, as others reported that it was working in earlier versions, but not since the 3.3.6 release.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17487">issues.joomla.org/tracker/joomla-cms/17487</a>.</sub>

**Comment by zero-24** [comment] 2017-08-13 17:00
This here: https://github.com/joomla/joomla-cms/archive/staging.zip is staging.

Just download that and install it as clean install (don't touch the live site with that!). And do what you have done before and try again.

**Comment by westiefan** [comment] 2017-08-14 11:22
Ok, thanks for that.  If I understand you correctly I need to install this separately as a clean install, is that correct?  If so how will that help me, as I will not have a significant number of registered users that I could send a test mass email to etc, so if I have only a single user in a test site how will this show me that the Bcc option is working? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17487">issues.joomla.org/tracker/joomla-cms/17487</a>.</sub>

**Comment by zero-24** [comment] 2017-08-14 13:05
> If I understand you correctly I need to install this separately as a clean install, is that correct? 

Yes.

>  If so how will that help me, as I will not have a significant number of registered users that I could send a test mass email to etc, so if I have only a single user in a test site how will this show me that the Bcc option is working?

You can create 2 dump users from the backend ;)

**Comment by brianteeman** [comment] 2017-08-14 13:08
Dump= dummy :)

**Comment by zero-24** [comment] 2017-08-14 13:13
Yes dummy sorry.

**Comment by westiefan** [comment] 2017-08-14 13:58
Ok, thank you.

I have now set up a test staging site http://www.hsdjoomla.co.uk/joomla-cms-staging/, and I set up 2 test users.

I have sent a test message, and on the first test I only received 1 email (I think that may have been because I used forwarding addresses that end up in the same mailbox).

On the second test I changed one of the recipient email addresses so that they go to individual mailboxes instead of forwarding to the same one, and this sent out 2 copies of the address.

I have only tested the Bcc element of the staging site and it does appear to be working in thie staging version (e.g. 3.8.0 ???), and this was checked by default (I assume because of the other issue that was raised over privacy etc), but I also noticed that in the "Group" box there is no longer a drop down to choose the user group or other sending options, and it is only displaying 0 (e.g. Zero).

My only comment based on the received emails is that it is not clear who is receiving the emails, i.e. is it the full user list (including the admin user), or is it only to the registered users, and is the send list confined to only send to single destination addresses.  I'm just asking as first test email was (I assume) sent to the admin user plus the 2 test user email addresses, but only a single email was received, whereas the second test email was sent to the same recipients, but this time 2 emails were received.

Just to clarify the recipients, 3 email addresses were used (based on the same domain name) for the first test, 2 of which are "forwarded" to the 3rd address, which is a POP3 mailbox, and only 1 email was received.  In the second test, only 2 email address used the same domain with only 1 being "forwarded" to the other POP3 mailbox, while the 3rd email address was a stand alone POP3 mailbox, and in the second test 2 emails were received.

I guess what I'm asking is how can I confirm how many emails were actually sent so that I can confirm that the correct number were received.  I hope this makes sense.

Next question is how can I test this fix on my live site without causing any issues?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17487">issues.joomla.org/tracker/joomla-cms/17487</a>.</sub>

**Comment by brianteeman** [comment] 2017-08-14 14:02
If you send an email! To  two email addresses via bcc to the same mailbox it is correct to only see one message in the inbox.

**Comment by westiefan** [comment] 2017-08-14 14:12
Hi Brian,

Thank you for the confirmation, that was my suspiscion, but I wasn't 100% sure that is what was happening.

In that case, all looks to be working as expected on the staging site, so what happens next?  How can I update my live site to fix this issue, or do I need to wait for the next security update release?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17487">issues.joomla.org/tracker/joomla-cms/17487</a>.</sub>

**Comment by brianteeman** [comment] 2017-08-15 19:28
In theory there is nothing on your site to update as this code hasnt changed I dont think.

You can confirm that by replacing the test site you built with staging with a test site built with 3.7.4

If bcc works correctly for you there then the problem can not be caused by the core of joomla

**Comment by westiefan** [comment] 2017-08-15 22:10
Hi Brian,

I beg to differ.  The code must have changed as by default in 3.7.4 the BCC option is NOT selected by default as is the case with the 3.8.0 staging version, plus the BCC option has been proven not work in version 3.7.4 already.

This is confirmed by other reports in the Joomla Forums, as I have mentioned previously the consensus is that the BCC option stopped working with the version 3.3.6 release, and the reports are that it has not worked since in a stable release version up to and including version 3.7.4.

For the sake of completenes I will test again with a clean install of 3.7.4, but as I said above, the code must have been changed in the staging version to have fixed the BCC option to be selected by default, plus as I mentioned in an earlier reply, the group to send to options are not working correctly, which tells me that the code must have been changed in some way, otherwsie these issues would not have been updated.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17487">issues.joomla.org/tracker/joomla-cms/17487</a>.</sub>

**Comment by brianteeman** [comment] 2017-08-16 07:56
yes the code has been changed to have bcc selected by default. However your report was that bcc was not working when it was selected

**Comment by westiefan** [comment] 2017-08-16 16:22
Hi Brian,

My comment was based on your statement "as this code hasnt changed".  I took this to be the wider meaning that none of the code had been changed, so apologies for any misunderstnding.

Anyway, I have now had a chance to set up a clean installation of Joomla 3.7.4, and I have tested the BCC option for the mass emailer, and on a clean version this does appear to be working.

Therefore it seems likely that it must be another component that is causing the issue for the BCC not working, but without any error messages there is little or no chance for me to find out whatever it is that is causing the error.

I will keep looking, but at least my testing has eliminated the Joomla core from being at fault.

Thank you for your help, please feel free to close this as resolved(at least from your perspective!!).

Best regards

John R.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17487">issues.joomla.org/tracker/joomla-cms/17487</a>.</sub>

**Comment by ghost** [comment] 2017-08-16 16:26
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17487">issues.joomla.org/tracker/joomla-cms/17487</a>.</sub>

**Closed as completed by ghost** 2017-08-16 16:26 UTC
Labels: No Code Attached Yet
