### ISSUE TITLE
Redirect component

### ISSUE THREAD

**Issue by Greblys** [joomla/joomla-cms#5801] opened 2015-01-17 23:34 UTC
Redirection from http://www.example/old/old-article to http://www.example/new/new-article doesn't work in Redirect component.

**Comment by zero-24** [comment] 2015-01-18 01:38
@Greblys 

did the URL `http://www.example/old/old-article` call a 404 error? (make sure you don't miss the TLD :smile: )

**Comment by Greblys** [comment] 2015-01-18 01:47
Yes, it did call 404 error

**Comment by zero-24** [comment] 2015-01-18 01:49
redirect plugin enabled? What exactly joomla version?

**Comment by Greblys** [comment] 2015-01-18 01:51
Redirect plugin is enabled. Joomla version is 3.3.6.

**Comment by zero-24** [comment] 2015-01-18 02:00
I'm unable to confirm a issue with this:

- install staging
- enable redirect plugin and enable collect URLs
- try to access a non existing page like: http://www.example.org/index.php/content-component_example
- 404 Error
- go to the redirect manager
- see the new entry
- edit and add a new page like:  http://www.example.org/index.php/sample-sites
- save
- trx to access http://www.example.org/index.php/content-component_example will redirect you to  http://www.example.org/index.php/sample-sites

please try this on a clean install of joomla 3.3.6 or staging / Nightly Builds (http://developer.joomla.org/cms-packages/) .

**Comment by Greblys** [comment] 2015-01-18 02:16
Coul it be that i have this issue because there is a directory called 'new' and there is menu item with alias new as well which is directing it to directory page.  new-article is in new directory

**Comment by Kubik-Rubik** [comment] 2015-01-18 03:06
You can not use a URL which contain a directory name in the path.

I will close this issue since it is a expected behavior. You are free to reopen this issue if think that your problem is not related to the given solution.

**Closed by Kubik-Rubik** 2015-01-18 03:06 UTC
Labels: No Code Attached Yet
