### ISSUE TITLE
Module manager - search with utf-8 characters does not work 

### ISSUE THREAD

**Issue by stawebnice** [joomla/joomla-cms#18791] opened 2017-11-22 09:34 UTC
### Steps to reproduce the issue
Name a module with UTF-8 characters e.g. Škola, then try to search for it using the searchbox, it does not return anything. But  searching for skola returns module called Škola.

Video: http://www.youtube.com/watch?v=2MizTbgJYKI&hd=1

### Expected result

Should return module called Škola.

### Actual result

Empty result

### System information (as much as possible)

Joomla 3.8.2, Chrome, Windows 10

**Comment by infograf768** [comment] 2017-11-22 09:55
Closing as duplicate of https://github.com/joomla/joomla-cms/issues/18745

**Closed as completed by infograf768** 2017-11-22 09:55 UTC
Labels: No Code Attached Yet

**Comment by boomsya** [comment] 2018-01-17 09:36
![12](https://user-images.githubusercontent.com/8008462/35035610-a2946a40-fb7a-11e7-9e88-98536969d875.png)
