### ISSUE TITLE
List All Categories in an Article Category Tree -  is not showing the correct hierarchy

### ISSUE THREAD

**Issue by DiGwork** [joomla/joomla-cms#43686] opened 2024-06-20 17:44 UTC
### 
What I did to get this result
Create Article master category "Faculties"
with six sub-categories: 
Each of these sub-categories have a sub-sub-categories.
Then create a "Faculty" menu with this menu item type: List All Categories in an Article Category Tree
Set all to show even if empty (no articles)

### Expected result

The expected tree for Faculty is
[Faculties]
---16px--->[Applied Sciences]
------32px------>[Biotechnology]
------32px------>[Horticulture]
------32px------>[Etc..]
------32px------>[Etc..]
---16px--->[Business]
------32px------>[Law-of-contracts]
------32px------>[Etc...]
------32px------>[Etc..]
------32px------>[Etc..]
---16px--->[Education]
------32px------>[Sociolinguistics]
------32px------>[Etc...]
------32px------>[Etc..]
------32px------>[Etc..]
---16px--->[Engineering]
------32px------>[Mechanical Engineering]
------32px------>[Etc...]
------32px------>[Etc...]
------32px------>[Etc...]
etc.

With each sub Category with a padding-left: 16px ;
and each Sub Sub Category with a padding-left: 32px ; 
with the next sub menu going back to  a padding-left: 16px ;

Which is the same hierarchy as they were set up

### Actual result

[Faculties]
---16px--->[Applied Sciences]
------32px------>[Biotechnology]
------32px------>[Horticulture]
------32px------>[Etc..]
------32px------>[Etc..]
------32px------>[Business]
---------48px--------->[Law-of-contracts]
---------48px--------->[Etc...]
---------48px--------->[Etc..]
---------48px--------->[Etc..]
---------48px--------->[Education]
------------64px------------>[Sociolinguistics]
------------64px------------>[Etc...]
------------64px------------>[Etc..]
------------64px------------>[Etc..]
------------64px------------>[Engineering]
---------------80px--------------->[Mechanical Engineering]
---------------80px--------------->[Etc...]
---------------80px--------------->[Etc...]
---------------80px--------------->[Etc...]
etc.
as you can see the next sub menu has the same padding left as the previous sub sub menu which keeps pushing the the list left instead of jumping back to show the correct placement hierarchy

This makes it look like we have sub-categories
followed sub sub-categories
followed by sub-sub-sub-categories
and the sub-sub-sub-sub-categories etc. 
Hence continually indenting further which is not accurate to the category hierarchy.

### System information (as much as possible)

The currently installed Joomla! version is "‎5.1.0"‎5.1.0
Template is shaper_helixultimate - Default]
screenshot of inspector: https://mega.nz/file/ZRpGCToA#J_KdBWKMVKA_OAAO0rNZAemhyRq_ZZWa3MaghOlvtYw
screenshot of page with red text showing what the hierarchy should be:  https://mega.nz/file/BcYEnAjK#5kWlzKO-9kEzwMnCEQGLRI7DUvoTBnLA-I0dU5jz5Xg

**Comment by brianteeman** [comment] 2024-06-20 17:46
Just to rule out an issue with a template override please can you switch to the Cassiopeia template and confirm that the issue is still present.

**Comment by DiGwork** [comment] 2024-06-20 18:09
OK let me give it a try
That gives a different result but does not even show the sub-sub-categories

**Comment by DiGwork** [comment] 2024-06-20 18:12
Here is  ascreenshot of Classtopia template selected

![classtopia screenshot](https://github.com/joomla/joomla-cms/assets/6685896/d2dc1d53-4991-4ac8-b651-4e73b5b8181f)

**Comment by brianteeman** [comment] 2024-06-20 18:26
PS we now know that your template has an override for this view.

From the information you have provided I am fairly certain that it is missing a closing element and that is why the nesting keeps incrementing.

**Comment by DiGwork** [comment] 2024-06-20 18:32
what would I need to do to create a closing element?

**Comment by brianteeman** [comment] 2024-06-20 18:35
I have never seen that template so I can't advise you. I suggest you contact the makers of the template to fix their bug 

As this is a third party template bug it should be closed here.

**Comment by DiGwork** [comment] 2024-06-20 18:37
Ok I will do so thank you for your assistance Brian, much appreciated
.

**Closed as completed** 2024-06-20 20:30 UTC
Labels: No Code Attached Yet
