### ISSUE TITLE
[5.1] com_privacy admin tests

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#42523] opened 2023-12-14 19:48 UTC
### Steps to reproduce the issue
run the e2e cypress tests for administrator->com_privacy->consent

### Expected result
all tests pass

### Actual result
most of the tests for sorting ascending and descending fail

### System information (as much as possible)
php 8.1.3
joomla51branch

### Additional comments
I suspect that the code to work out what value should = what result is wrong and that there is nothign wrong with the component just the test

**Comment by alikon** [comment] 2023-12-17 13:01
something weird it's happening on cypress tests in general
that's from 4.4-dev

![image](https://github.com/joomla/joomla-cms/assets/181681/8886734f-c36f-4346-b734-6f83767871ec)

**Comment by alikon** [comment] 2024-02-24 07:51
it seems to be fixed now

**Comment by alikon** [comment] 2024-03-03 07:10
Closing this issue now, has been resolved elsewhere
but feel free to reopen if needed.

**Comment by brianteeman** [comment] 2024-03-03 09:08
no not resolved

**Comment by alikon** [comment] 2024-03-03 09:29
i'm unable to reproduce nor drone

**Comment by muhme** [comment] 2024-04-24 15:55
@alikon it looks like the tests are not stateless 😱 I compared `can list by user_id in descending order` with `can list by user_id in ascending order` and found out, if I test both alternately first run fails always and starting with second run it is green :white_check_mark: The reason looks to me like the sort order is selected and the table content is captured before the table has changed.

Both test cases have to be adopted. My solution is a little bit complicated, perhaps you have a simpler one?  For example, for ascending replace the one `select`-line with:

```
// first select a completely different option to always make a POST request for the next selection
cy.get('#list_fullordering').select('ID ascending');
// catch the next POST request
cy.intercept('POST', '**').as('anyPost');
// selecting ASC
cy.get('#list_fullordering').select('User ID ascending');
// wait for the POST request and the completion of the table
cy.wait('@anyPost');
// double check ASC is selected
cy.get('#list_fullordering').should('have.value', 'a.user_id ASC');
```

**Comment by alikon** [comment] 2024-04-29 13:47
please test https://github.com/joomla/joomla-cms/pull/43400

**Closed as completed by alikon** 2024-04-29 13:47 UTC
Labels: No Code Attached Yet, bug
