### ISSUE TITLE
List all tags menu item pagination missing

### ISSUE THREAD

**Issue by pnkr** [joomla/joomla-cms#42131] opened 2023-10-13 07:28 UTC
### Steps to reproduce the issue
1. Go to Menu manager
2. Create a new menu item for tags > List all tags
3. Go to Selection Options

### Expected result
After pagination fields there should be a pagination limit so you can control how many tagged items will show per page.

### Actual result
There is no option to select how many tagged items will show and the view default to 20 per page without a way to change it.

### System information (as much as possible)
Joomla 4.3.4

### Additional comments

The following field is missing from com_tags/tmpl/tags/default.xml, where it gives the administrator the functionality to set his number of tagged items per page. If you put it, it will work fine.

			<field
				name="display_num"
				type="number"
				label="Limit per page"
				>
			</field>

**Comment by chmst** [comment] 2023-10-18 11:01
![grafik](https://github.com/joomla/joomla-cms/assets/1035262/c3a6a5d0-b7be-40b9-8073-b31bfe970517)

Is your "display select" activated?

**Comment by Quy** [comment] 2023-11-19 21:26
Closing due to no response.

**Comment by brianteeman** [comment] 2023-11-19 22:28
You've closed this but it has not been answered. (there was a board motion that issues can not be closed for this reason)


The question is how to control the number of items to be displayed on the page so that there is pagination.
The answer given is not relevant to the question

**Comment by alikon** [comment] 2023-12-28 10:07
no more reproducible on 4.4.1
![image](https://github.com/joomla/joomla-cms/assets/181681/97568f7b-22a5-4ef1-a8d8-5dd7e6f2dded)

**Closed as completed by alikon** 2023-12-28 10:07 UTC
Labels: No Code Attached Yet, Information Required
