### ISSUE TITLE
Bad url returned from standard search against archived articles

### ISSUE THREAD

**Issue by jeanfrancoisgoude** [joomla/joomla-cms#7084] opened 2015-05-31 07:16 UTC
#### Steps to reproduce the issue

install a new virgin 3.4.1 installation with tests datas : blog English sample datas. In such a site, search 'blog' word returns 6 replies. If I flag the 'About your home page' article as archived, there are always 6 replies from the search request but the 'about your home page' link has the following url :
http://127.0.0.1:8080/test/index.php/component/content/archive?year=2011&month=1

which of course doesn't work at all. Linked page is not the 'About your home page' article but the list archived articles, which in this case contains 0 article, we can find the 'About your home page' article by choosing 2012 year in the list box in the displayed form (bug in the bug ?)

#### Expected result

the 'About your home page' link reply in the search modules should be : http://127.0.0.1:8080/test2/index.php/4-about-your-home-page

#### Actual result
http://127.0.0.1:8080/test/index.php/component/content/archive?year=2011&month=1

#### System information (as much as possible)
Joomla! 3.4.1 US English version with datas in blog English presentation form. SEF  or no SEF doesn't matter

#### Additional comments

I find the problem on my personal site http://www.guerrier-celeste.fr

**Comment by jeanfrancoisgoude** [comment] 2015-07-27 09:18
Bug is still present in Joomla 3.4.3 can someone give me an advice ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7084">issues.joomla.org/joomla-cms/7084</a>.</sub>

**Comment by ghazal** [comment] 2015-08-21 08:02
Another way of describing this issue :

* many archived articles
* search (front-end)
* result OK, archived article selected
* click on link to article
* Result : display of all articles archived -> NOT GOOD

We guessed the pb is in content.php of search plugin for content :
/plugins/search/content/content.php<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7084">issues.joomla.org/joomla-cms/7084</a>.</sub>

**Comment by schnuti** [comment] 2015-08-24 11:12
I believe there is a bug but not where you think.
It's expected behaviour that the Archived articles view is called.
So first you should create a menu item for that view. It is possible to hide it, if you do not want it on the page.
If the problem described below is solved, you'll probably do not need this view. Create one anyway and set the parameters as you need. 

There seems to be a bug in the article(content) router for archived articles with activated SEO.
The link looks like this with year before and month after the view name.
"/site-name/menu-name/2011?view=archive&amp;month=1"

This line will never run in the article router.php

if (isset($query['year']) && isset($query['month'])) as year is unset before this line.

Should the link look like this (month and year is filled in the called archived view)
?view=archive&year=2011&month=1

or like this (monthz and year is NOT filled in the called archived view)
/2011/1?view=archive

I guess the first would be preferred

Or are changes to the parse method neccessary?

Someone with good knowledge of the article (content) router should have a look.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7084">issues.joomla.org/joomla-cms/7084</a>.</sub>

**Comment by schnuti** [comment] 2015-08-24 12:43
The same hint I made on the Cms Google mail list

In addition:
The Joomla search has technical limitations and limitations in the number of shown hits..You could try the Smart Search component.

For the Archived articles view you can activate the field "Filter Field" on the archive tab.
You can then filter by text in the article titles. Could be used to find the one you clicked on in the search result.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7084">issues.joomla.org/joomla-cms/7084</a>.</sub>

**Comment by ghazal** [comment] 2015-08-24 13:19
Thanks for your comments.
Your solutions are probably adequate in case of a few number of archived articles.
But nowadays, ppl have been building Joomla sites for long term use.
I think about a particular case where the site is 3/4 years old, updated daily, with about hundreds of archived articles, even though they go back six months only, and are deleted prior to this length of time.

But we were not looking for a workaround, this we can do (be it a hack of the original code, smart use of joomla functionalities or third party extension) and, if so, we would have posted on a forum. 

We thought Archived article deserves a better and simpler display of the search function.
Visitors of a site don't care about the cleverness of a search function. They want to find - easily - what they came to look for.
Anyhow, tks for your help.

**Comment by jeanfrancoisgoude** [comment] 2015-08-24 13:29
Magnifique,

 

Merci pour ta réponse … j’étais en train de chercher une formulation pour leur répondre  (euh comment dire ?) : sans les froisser.

 

Ta réponse me convient parfaitement !

 

Merci à toi

 

De : ghazal [mailto:notifications@github.com] 
Envoyé : lundi 24 août 2015 15:20
À : joomla/joomla-cms
Cc : jeanfrancoisgoude
Objet : Re: [joomla-cms] Bad url returned from standard search against archived articles (#7084)

 

Thanks for your comments.
Your solutions are probably adequate in case of a few number of archived articles.
But nowadays, ppl have been building Joomla sites for long term use.
I think about a particular case where the site is 3/4 years old, updated daily, with about hundreds of archived articles, even though they go back six months only, and are deleted prior to this length of time.

But we were not looking for a workaround, this we can do (be it a hack of the original code, smart use of joomla functionalities or third party extension) and, if so, we would have posted on a forum. 

We thought Archived article deserves a better and simpler display of the search function.
Visitors of a site don't care about the cleverness of a search function. They want to find - easily - what they came to look for.
Anyhow, tks for your help.

**Comment by schnuti** [comment] 2015-08-24 15:03
You're welcome!
It's not my solution. I just pointed out that the std search functionality has limitations, Smart Search is a component included in the Joomla core distribution. I do not know, if it handels archived aticles by default.

If someone could confirm the problem wih the router described above, it would be great. I can't really believe what i found.

1. Set the site to SEO.
2. Set some article/articles to archived.
3. Search for the article or in an active Archived articles module, inspect the created link(s). 

Is it something like "/site-name/menu-name/2011?view=archive&month=1" ?

Weird!


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7084">issues.joomla.org/joomla-cms/7084</a>.</sub>

**Comment by chrisdavenport** [comment] 2016-05-08 10:02
Hi @jeanfrancoisgoude you created this issue sometime ago but have not provided any code for people to evaluate. As no one else has shown any interest in providing the code and you have not then I am closing this issue at this time. If code is provided (a pull request) it can always be re-examined.  Thank you for reporting the issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7084">issues.joomla.org/joomla-cms/7084</a>.</sub>

**Comment by chrisdavenport** [comment] 2016-05-08 10:03
Set to "closed" on behalf of @chrisdavenport by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7084">issues.joomla.org/joomla-cms/7084</a>

**Closed by chrisdavenport** 2016-05-08 10:03 UTC
Labels: No Code Attached Yet

**Comment by jeanfrancoisgoude** [comment] 2016-05-08 10:38
Hello again !

I provided explanations in order to reproduce the problem in my first post. Nothing changed from that time ! You can still reproduce the problem with a standard fresh installation of Joomla! 3.5.1 with standard samples as said above : 

> install a new virgin 3.4.1 installation with tests datas : blog English sample datas. In such a site, search 'blog' word returns 6 replies. If I flag the 'About your home page' article as archived, there are always 6 replies from the search request but the 'about your home page' link has the following url :
http://127.0.0.1:8080/test/index.php/component/content/archive?year=2011&month=1

> which of course doesn't work at all. Linked page is not the 'About your home page' article but the list archived articles, which in this case contains 0 article, we can find the 'About your home page' article by choosing 2012 year in the list box in the displayed form (bug in the bug ?)

For my own I found the following solution in order my visitors did not complain about problems not finding articles they were searching on my site : I only added a rule in my .htaccess with following text : 

`#modification du 01/04/2016 : correction problème d'archivage
 RedirectMatch 301 /archives/48-frontnews/(.*) /48-frontnews/$1
`

This rule works perfectly as is

**Comment by chrisdavenport** [comment] 2016-05-08 10:52
I'm glad you found a solution that works for you.  @brianteeman has just pointed out this issue that could be related: https://issues.joomla.org/tracker/joomla-cms/9566<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7084">issues.joomla.org/joomla-cms/7084</a>.</sub>

**Comment by jeanfrancoisgoude** [comment] 2016-05-08 12:46
could be related ? this is exactly the same problem, hopefully this will be finally solved without adding somewhat in the .htaccess :)
