### ISSUE TITLE
Regression: 3.5.0 Installation with "Send configuration settings" active shows Step 3 page after successful installation

### ISSUE THREAD

**Issue by bertmert** [joomla/joomla-cms#8972] opened 2016-01-23 19:52 UTC
Installed oomla! 3.5.0-beta - Staging 2016-01-23.
Activated options
- Send configuration settings
- Include Passwords in Email

Installation successfully finished (received email, too) but not at page with button "Remove installation folder". 
Still page "Step 3" where I could start a new installtion.

This time without option "Include Passwords in Email". Same behavior.

After setting "Send configuration settings" to NO next installation finished as expected (page with remove button)

**Comment by infograf768** [comment] 2016-01-24 18:21
I confirm the issue here.
After Setting "Email Configuration" to Yes and then clicking install, Page 3 reloads.

**Comment by infograf768** [comment] 2016-01-24 18:24
I also get this error ::
```
[24-Jan-2016 18:17:47 UTC] PHP Warning:  ini_set(): A session is active. You cannot change the session module's ini settings at this time in ROOT/libraries/joomla/session/handler/joomla.php on line 45
[24-Jan-2016 18:17:47 UTC] PHP Stack trace:
[24-Jan-2016 18:17:47 UTC] PHP   1. {main}() ROOT/installation/index.php:0
[24-Jan-2016 18:17:47 UTC] PHP   2. JApplicationCms->execute() ROOT/installation/index.php:32
[24-Jan-2016 18:17:47 UTC] PHP   3. InstallationApplicationWeb->doExecute() ROOT/libraries/cms/application/cms.php:257
[24-Jan-2016 18:17:47 UTC] PHP   4. InstallationApplicationWeb->dispatch() ROOT/installation/application/web.php:200
[24-Jan-2016 18:17:47 UTC] PHP   5. InstallationControllerInstallEmail->execute() ROOT/installation/application/web.php:161
[24-Jan-2016 18:17:47 UTC] PHP   6. InstallationModelSetup->getOptions() ROOT/installation/controller/install/email.php:54
[24-Jan-2016 18:17:47 UTC] PHP   7. JFactory::getSession() ROOT/installation/model/setup.php:28
[24-Jan-2016 18:17:47 UTC] PHP   8. JFactory::createSession() ROOT/libraries/joomla/factory.php:176
[24-Jan-2016 18:17:47 UTC] PHP   9. JSessionHandlerJoomla->__construct() ROOT/libraries/joomla/factory.php:597
[24-Jan-2016 18:17:47 UTC] PHP  10. ini_set() ROOT/libraries/joomla/session/handler/joomla.php:45
```

**Comment by infograf768** [comment] 2016-01-24 18:26
Changing title as this is an important regression<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8972">issues.joomla.org/joomla-cms/8972</a>.</sub>

**Comment by infograf768** [comment] 2016-01-25 09:03
Looks like the issue comes from
https://github.com/joomla/joomla-cms/blob/staging/installation/controller/install/email.php#L31

As it resets the session.

**Comment by infograf768** [comment] 2016-01-25 09:10
@bertmert 
Can you test after commenting `JFactory::$session = null;` ?

**Comment by infograf768** [comment] 2016-01-26 07:03
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8972">issues.joomla.org/joomla-cms/8972</a>

**Comment by infograf768** [comment] 2016-01-26 07:03
Closing as we have a patch https://github.com/joomla/joomla-cms/pull/8983<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8972">issues.joomla.org/joomla-cms/8972</a>.</sub>

**Closed by infograf768** 2016-01-26 07:03 UTC
Labels: No Code Attached Yet
