### ISSUE TITLE
Save failed with the following error: Incorrect integer value: '' for column 'hits' at row 1

### ISSUE THREAD

**Issue by no-matter-0** [joomla/joomla-cms#28360] opened 2020-03-16 06:56 UTC
Joomla 4 beta 11
php 7.4

when trying to save an article in backend i get 
Save failed with the following error: Incorrect integer value: '' for column 'hits' at row 1

**Comment by alikon** [comment] 2020-03-16 07:43
close as duplicate of #28359

**Closed as completed** 2020-03-16 07:44 UTC
Labels: No Code Attached Yet
