### ISSUE TITLE
jdoc:include - Zero width No-Break Space (U+FEFF)

### ISSUE THREAD

**Issue by maaaaartin** [joomla/joomla-cms#19651] opened 2018-02-12 14:17 UTC
### Steps to reproduce the issue

'**&#x26;#65279;**' character is being added to the begining of component code inserted by jdoc:include<br>_(I've reviewed template's index.php content to be sure it's not present inside it)_<br>
![screen shot 2018-02-12 at 14 11 27](https://issues.joomla.org/uploads/1/49874725e22c34718adcf10646ec6cac.png)

**Comment by brianteeman** [comment] 2018-02-12 14:19
Can you replicate this with the core template protostar?

**Comment by maaaaartin** [comment] 2018-02-12 14:23
Yes, it's still present in the dom after using protostar.

![capture20180212152212673](https://user-images.githubusercontent.com/36411398/36101088-9f163180-1008-11e8-8abd-576024f44ca9.png)

**Comment by mbabker** [comment] 2018-02-13 00:23
Can't confirm with the template we use for `joomla.org`, or against the 4.0 branch build, or a custom template rolled out by my employer.  So this seems to be something template specific, I wouldn't know what specifically though.

**Comment by Chaosxmk** [comment] 2018-02-13 14:43
Looks like an error caused by invalid BOM type for a file somewhere.

**Comment by brianteeman** [comment] 2018-02-15 15:06
Can't replicate this either

**Comment by Quy** [comment] 2018-02-21 20:00
@maaaaartin Can you reproduce this on a new installation?

**Comment by Quy** [comment] 2018-02-26 16:59
Closing as not reproducible.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19651">issues.joomla.org/tracker/joomla-cms/19651</a>.</sub>

**Closed as completed by Quy** 2018-02-26 16:59 UTC
Labels: No Code Attached Yet
