### ISSUE TITLE
[4.0b4] Class 'Joomla\CMS\Installation\Helper\ArrayHelper' not found

### ISSUE THREAD

**Issue by lancedouglas1** [joomla/joomla-cms#30900] opened 2020-10-03 07:11 UTC
### Steps to reproduce the issue
1. Download Joomla_4.0.0-beta4-Beta-Full_Package.tar.gz
2. tar -zxvf
3. set permissions on dirs/files
4. visit with browser to kickoff installation
5. add installation details (site name, login, db)
6. click "install joomla" button

### Expected result
- Installation begins

### Actual result
- Error Message: 

> **Class 'Joomla\CMS\Installation\Helper\ArrayHelper' not found**

### System information (as much as possible)
OS: Ubuntu 20.04LTS - Pro
PHP: php7.4-fpm
RProxy: 1.18.0-0ubuntu1 

### Additional comments
I'm repeating the same steps the I followed this morning successfully (on ubuntu 18.04LTS).

**Comment by zero-24** [comment] 2020-10-03 07:42
Can you please post the full message with the file where the issue is? It seems there is a missing use statment in that file.

**Comment by lancedouglas1** [comment] 2020-10-03 08:01
Thanks @zero-24 for the quick reply.

<img width="656" alt="Screen Shot 2020-10-03 at 1 59 41 AM" src="https://user-images.githubusercontent.com/7749611/94986460-3c127d80-051c-11eb-9800-70fb3dcc53ea.png">
The error message only shows up on the installation screen, not in the logs, so I'm not sure of the specific file/line that is triggering the error.

**Comment by lancedouglas1** [comment] 2020-10-03 08:02
I just tried with the nightly build, that's why that image shows the beta5-dev in the header, by the way.  Same issue.

**Comment by lancedouglas1** [comment] 2020-10-03 08:08
If found it based on your question @zero-24 
Issue is that installation/src/Helper/DatabaseHelper.php is missing the use.

On line 20 I added:
`use Joomla\Utilities\ArrayHelper;`

**Comment by zero-24** [comment] 2020-10-03 08:18
Can you send a PR with that change?

**Comment by zero-24** [comment] 2020-10-03 08:34
Closing as there is a PR. thanks @lancedouglas1 👍

**Closed as completed by zero-24** 2020-10-03 08:34 UTC
Labels: No Code Attached Yet
