### ISSUE TITLE
[5.0] Bug in Tagged Items Menu pagination

### ISSUE THREAD

**Issue by 1inkin** [joomla/joomla-cms#41492] opened 2023-08-28 07:08 UTC
### Steps to reproduce the issue
1. create tags Tag1 and Tag2
2. create articles so that only with Tag1 is greater than 5 and with both tags too
3. create a Menu1 type Tagged Items for only Tag1 and Menu2 type Tagged Items for both tags
4. in the frontend select Menu1 and display pagination
5. select second page in pagination of Menu1

### Expected result
the second page of menu1 opened

### Actual result
the second page of menu2 opened

**Comment by alikon** [comment] 2023-08-28 07:11
duplicate of #40750
please don't open the same issue twice
thanks in advance

**Closed as completed by alikon** 2023-08-28 07:11 UTC
Labels: No Code Attached Yet
