### ISSUE TITLE
Bootstrap.dropdown with illogical dependency

### ISSUE THREAD

**Issue by Open2logic** [joomla/joomla-cms#38640] opened 2022-08-30 09:57 UTC
### Steps to reproduce the issue
1) Go to administration
2) Select the administration modules view ( content / administrator module )
3) Disable the module user status
4) Go to de articles view ( content / articles )
5) Now in the ACTIONS button, the submenu does not work. Publish, The options Unpublish, Feature, Unfeature, Archive, Check-in, Trash and Batch are disable.

### Expected result
ACTIONS button with the options Unpublish, Feature, Unfeature, Archive, Check-in, Trash and Batch are are anable.

### Actual result
The ACTIONS button, the submenu does not work. Publish, The options Unpublish, Feature, Unfeature, Archive, Check-in, Trash and Batch are disable.

### System information (as much as possible)
Joomla 4
![unnamed](https://user-images.githubusercontent.com/9007607/187408039-5f25ff40-93f4-41c5-847a-7f24a2bdfc5d.png)
![unnamed](https://user-images.githubusercontent.com/9007607/187408126-617f4ea8-11fe-4d4d-8248-72dc1bd09d5c.png)

### Additional comments
The Actions dropdown requires the following PHP code to work:
HTMLHelper::_('bootstrap.dropdown', '.dropdown-toggle');

And this code is executed ONLY by the User Status making the dropdown accessible in ALL ACTIONS dropdown menu.

**Comment by ReLater** [comment] 2022-08-30 11:03
Confirmed. Several dropdowns don't work at several places in backend if module "User Status" is deactivated. Not only Actions dropdowns.

They don't open on click.

**Comment by ReLater** [comment] 2022-08-30 12:08
As far as I see, any HtmlView.php that uses

`$dropdown = $toolbar->dropdownButton('status-group')`

should get an additional

`HTMLHelper::_('bootstrap.dropdown', '.dropdown-toggle');`

The class `.dropdown-toggle` comes hardcoded from `class DropdownButton extends AbstractGroupButton::prepareOptions(` but I don't think that it is a good idea to place the `HTMLHelper` there(????)

**Comment by brianteeman** [comment] 2022-08-30 12:23
it should be a web asset and not an htmlhelper

**Comment by Fedik** [comment] 2022-08-30 12:27
It not a releas blocker, just a bug

**Comment by brianteeman** [comment] 2022-08-30 13:40
Please test #38644

**Comment by ReLater** [comment] 2022-08-30 13:58
> it should be a web asset and not an htmlhelper

Come on folks. Is that really the point here. Use whatever you want in your Joomla.

But the CSS class for 'status-group' is `.dropdown-toggle` not `.dropdown` like in your PR.

That's the reason why I would prefer it at other code places instead of blindly load not used JS in a JLayout that maybe never is used anywhere.

The output of status-group happens here: https://github.com/joomla/joomla-cms/blob/fa0849e100906520c6f16766af774a6257ef0be2/layouts/joomla/toolbar/dropdown.php#L62-L64

It can be whatever a code before has defined for a button also with other classes than `.dropdown-toggle` or `.dropdown`.

**Comment by Fedik** [comment] 2022-08-30 18:13
Closing, because PR

**Closed as completed by Fedik** 2022-08-30 18:13 UTC
Labels: No Code Attached Yet

**Comment by Open2logic** [comment] 2023-02-21 16:15
This issue is resolved, however other parts of the administration continue to have the issue.

**Comment by Open2logic** [comment] 2023-02-21 16:22
In the administration, Disable the user status module.
Go to home board ..(/administrator/index.php).
We will see the boxes of Site, System, 3drd PArty, etc.
In the upper right part of each box is the icon that shows a submenu that allows you to edit or unpublish.
But this submenu does NOT appear if the User staus module is disabled.

![submenu](https://user-images.githubusercontent.com/9007607/220401576-a0e6ad5a-ceb3-49ff-be22-aadcaf429ea6.jpg)
