### ISSUE TITLE
Upgrading from 4.2.9 to 4.3.0 RC2 Yields Installer Error

### ISSUE THREAD

**Issue by sdwjoomla** [joomla/joomla-cms#40284] opened 2023-04-01 16:27 UTC
### Steps to reproduce the issue
Created new instance of 4.2.9
Installed 4.3.0 RC2 update package

### Expected result
No error message.
Joomla update message

### Actual result
Received message "JInstaller: Install: Error SQL Can't Drop 'asset_id'; check that column/key exists"
![image](https://user-images.githubusercontent.com/72045461/229302883-11c6d7c9-5960-409c-99af-5cea1994b049.png)
### System information (as much as possible)

PHP 8.0.23
Joomla 4.2.9 clean install

**Comment by obuisard** [comment] 2023-04-01 16:30
This is an error caused by the last update database script in case of an installation update from 4.2 or early version of 4.3 before introduction of the guided tours.

I will create a PR to fix this issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40284">issues.joomla.org/tracker/joomla-cms/40284</a>.</sub>

**Comment by richard67** [comment] 2023-04-01 19:15
Closing as having a pull request. Please test #40286 . Thanks in advance.

**Closed as completed by richard67** 2023-04-01 19:15 UTC
Labels: No Code Attached Yet
