### ISSUE TITLE
[3.10] Errors on back-end login page when multi lingual is enabled

### ISSUE THREAD

**Issue by imarklee** [joomla/joomla-cms#30267] opened 2020-08-03 15:11 UTC
### Steps to reproduce the issue
Enable multi lingual on your Joomla site. 

### Expected result
No errors on the back-end login page

### Actual result
At the login page of the back-end, the following errors are shown:

````
Notice: Trying to get property 'metadata' of non-object in /libraries/src/Language/LanguageHelper.php on line 43
````

### System information (as much as possible)
3.10.0-alpha1

### Additional comments
Did not encounter this error in Joomla 3.9.x

**Comment by infograf768** [comment] 2020-08-04 06:50
I can't reproduce the issue on Joomla! 3.10.0-alpha2-dev

**Comment by infograf768** [comment] 2020-08-04 06:57
Which languages had you installed?

**Comment by richard67** [comment] 2020-08-04 07:10
Setting "Information Required".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30267">issues.joomla.org/tracker/joomla-cms/30267</a>.</sub>

**Comment by imarklee** [comment] 2020-08-04 07:23
These are the languages installed at the back end

![languages_admin](https://user-images.githubusercontent.com/892204/89264962-5fc55e80-d666-11ea-8dac-8e623500e37b.png)

**Comment by infograf768** [comment] 2020-08-04 07:26
There is already an error as Arabic is showing twice.
Can you make a new clean install?

**Comment by imarklee** [comment] 2020-08-04 14:38
> There is already an error as Arabic is showing twice.
> Can you make a new clean install?

You are right, as soon as I unpublish those ar-AA, it seems to be fine. Strange that this did not happen to 3.9.x

**Comment by infograf768** [comment] 2020-08-04 14:40
closing as not a bug

**Closed as completed by infograf768** 2020-08-04 14:40 UTC
Labels: No Code Attached Yet
