### ISSUE TITLE
[5.0] Bug in filtering Articles by Tags in Menu Category Blog

### ISSUE THREAD

**Issue by 1inkin** [joomla/joomla-cms#41491] opened 2023-08-28 07:00 UTC
Steps to reproduce the issue

1. Create Tags items for example t1 and t2
2. Create root Category c1 and several subcategories for example c11, c22
3. Create several Articles in each Category (for example a1 in c11, a2 in c22) and assign them one Tags item (for example t1 for a1, t2 for a2)
4. Create a Menu item with Menu Item Type = Category Blog, Choose a Category = root Category (c1) and Tags = t1. Category group parameter # Articles in Category = Show, Empty Categories = Hide
5. Open this Menu in front

Expected result

1. only subcategories are displayed in which the Articles with Tag t1
2. empty subcategories are not displayed that do not contain Articles with Tag t1
3. correct count of Articles is displayed in the category (only with Tag t1)

Actual result

1. all subcategories are displayed, even if there are no Articles with Tag t1 (empty subcategories in this case)
2. incorrect count of Articles is displayed in the category (all Articles, even if there are Articles without Tag t1)

**Comment by alikon** [comment] 2023-08-28 07:09
duplicate of  #38765

**Closed as completed by alikon** 2023-08-28 07:09 UTC
Labels: No Code Attached Yet
