### ISSUE TITLE
[4.0] update from joomla-cms-4.0.0-alpha1 to alpha 2 not possible

### ISSUE THREAD

**Issue by rgmears** [joomla/joomla-cms#19010] opened 2017-12-07 12:03 UTC
### Steps to reproduce the issue
Attempt to update alpha1 to alpha2

### Expected result
update to version 2

### Actual result
Errors:
Warning: array_filter() expects parameter 2 to be a valid callback, class 'JoomlaupdateModelDefault' not found in /opt/lampp/htdocs/j4dev/administrator/components/com_joomlaupdate/Model/UpdateModel.php on line 1315

Warning: Invalid argument supplied for foreach() in /opt/lampp/htdocs/j4dev/administrator/components/com_joomlaupdate/Model/UpdateModel.php on line 1317

### System information (as much as possible)
running on xampp on Linux Mint

### Additional comments
I was directed to use the "dev releases" as the Option. There is no such option.

**Comment by brianteeman** [comment] 2017-12-07 12:07
As with every joomla pre-release there is no upgrade path between pre-releases

**Comment by rgmears** [comment] 2017-12-07 12:15
@C-Lodder asked me to report this.

**Comment by C-Lodder** [comment] 2017-12-07 12:22
@brianteeman I thought you could update alphas via the update manager?

Either way, there shouldn't be a PHP error being thrown.

**Comment by brianteeman** [comment] 2017-12-07 12:37
Functionally you can use the install BUT we never do the update scripts to handle changed files or changed database stuff so it is unlikely to work.

**Comment by mbabker** [comment] 2017-12-07 12:41
Duplicate of #18670 and #19005

**Closed as completed by mbabker** 2017-12-07 12:41 UTC
Labels: No Code Attached Yet

**Comment by rgmears** [comment] 2017-12-07 12:47
Thanks @mbabker 
So, how does one update to alpha 2?

**Comment by mbabker** [comment] 2017-12-07 12:49
One does not update an existing install at this time.

**Comment by rgmears** [comment] 2017-12-07 13:08
So, if one has been working on some things and has to do a fresh install that would mean the altered files would have to be copied over to the new installation.

**Comment by dgrammatiko** [comment] 2017-12-07 19:17
@rgmears if you are supposed to work on the alpha then you should use git. There are plenty articles how to set this up correctly! Also even in this scenario you’ll have to do a new install for the db, but will not affect the files

**Comment by brianteeman** [comment] 2017-12-07 20:45
There is nothing new about this. This has been the practice for 13 years

**Comment by rgmears** [comment] 2017-12-10 14:12
@dgt41 Is this the right place to start: https://github.com/joomla/joomla-cms/tree/4.0-dev

**Comment by stell** [comment] 2017-12-20 18:20
> There is nothing new about this. This has been the practice for 13 years

So let's keep going that way, right? Sounds like an arguments for a change to me.

mbabker:
> For what it is worth, there is zero technical reason why upgrades between anything but stable releases cannot be supported. 

https://github.com/joomla/joomla-cms/issues/13660

**Comment by brianteeman** [comment] 2017-12-20 18:24
Are you volunteering to do the required work?

**Comment by stell** [comment] 2017-12-20 18:28
So it can be done.
