### ISSUE TITLE
media modal is not showing in formfield repeatable

### ISSUE THREAD

**Issue by nielsnuebel** [joomla/joomla-cms#15917] opened 2017-05-09 15:36 UTC
### Steps to reproduce the issue
You need a form.xml with type repeatable. In it a type media.

EXAMPLE:
```xml
<field name="gallery_news"
    type="repeatable"
    icon="list"
    description="KICKCCK_FIELD_NEWS_GALLERY_LABEL"
    label="KICKCCK_FIELD_NEWS_GALLERY_DESC"
    default=""
    maximum="9"
    >
				<fields name="params">
					<fieldset hidden="true" name="list_news_gallery" repeat="true">
						<field  name="gallery_image"
								type="media"
								directory="newsimage"
								label="KICKCCK_FIELD_NEWS_GALLERYIMAGE_LABEL"
								description="KICKCCK_FIELD_NEWS_GALLERYIMAGE_DESC"
								preview="true"
						/>
						<field name="gallery_alt" type="text"
							   size="40" label="KICKCCK_FIELD_NEWS_GALLERY_ALT_LABEL"
							   description="KICKCCK_FIELD_NEWS_GALLERY_ALT_DESC"
						/>
						<field  name="gallery_lightbox"
								type="radio"
								default="1"
								label="KICKCCK_FIELD_NEWS_GALLERY_LIGHTBOX_LABEL"
								description="KICKCCK_FIELD_NEWS_GALLERY_LIGHTBOX_DESC"
						>
							<option value="0">JNO</option>
							<option value="1">JYES</option>
						</field>
					</fieldset>
				</fields>
			</field>
```

If you click on Select Image Button it dosen't open the Modal Window with the com_media component.

I know the type repeatable ist deprecated. The PROBLEM is the ISIS Backend Template.

[Rename these file and it works](https://github.com/joomla/joomla-cms/blob/master/administrator/templates/isis/html/layouts/joomla/form/field/media.php "Rename these file and it works").

[Maybe these file need an update](https://github.com/joomla/joomla-cms/blob/master/media/media/js/mediafield.js)

### System information (as much as possible)
Joomla 3.7

**Comment by C-Lodder** [comment] 2017-05-09 16:06
Problem being is BS2 doesn't support multiple modals being open at once. I believe this was one of the reasons why subform fields we created.

**Comment by nielsnuebel** [comment] 2017-05-09 16:09
The problem is that JQuery live problem with the [DOM.](https://github.com/joomla/joomla-cms/blob/staging/media/media/js/mediafield.js#L195)

I add these CODE to [repeatabel.js](https://github.com/joomla/joomla-cms/blob/staging/media/system/js/repeatable-uncompressed.js#L478)
```
// fix media field in ISIS Template
			$row.find('.field-media-wrapper').each(function(){
				var $el = $(this);
				$el.fieldMedia();
			});
```

**Comment by justinherrin** [comment] 2017-05-26 00:01
I can confirm this issue. It's rather frustrating that things were working perfectly fine in Joomla 3.6.5 and then once update to 3.7.x the "Select" button does not work anymore.

![screen shot 2017-05-25 at 7 43 10 pm](https://cloud.githubusercontent.com/assets/13225615/26475264/ad8f800c-4184-11e7-934e-7b603e6ecfdb.png)

## System Information
Joomla 3.7.2
PHP 7.0.8

Again, this media field inside a repeatable field worked just fine in Joomla 3.6.5.

**Comment by rpasing** [comment] 2017-05-30 14:00
Can confirm this for latest Joomla! 3.7.2, with 3.6 it worked. Above hack by @nielsnuebel (inserting code into repeatable.js) fixed the problem. Shouldn't we create a PR for this?

**Comment by infograf768** [comment] 2017-05-31 07:19
Please do create the PR.

**Comment by ginphreak** [comment] 2017-07-21 13:58
Hi, at wicth line into repeatable.js i had to add nielsnuebel's code? beacuse i add it at the end (before "})(jQuery);") and it not works. Can you help me please? (Sorry for my poor english)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15917">issues.joomla.org/tracker/joomla-cms/15917</a>.</sub>

**Comment by ghost** [comment] 2017-07-21 14:08
closed as having PR #17205<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15917">issues.joomla.org/tracker/joomla-cms/15917</a>.</sub>

**Closed by ghost** 2017-07-21 14:08 UTC
Labels: No Code Attached Yet

**Comment by jinbullsushil** [comment] 2017-08-01 10:19
HI ,
I have the same problem occurred.  Now I have fixed my problem.
Below are the steps 
Go to the below directory
administrator\templates\isis\html\layouts\joomla\form\field
 and remove/rename  **"media.php"**

**Comment by ghost** [comment] 2017-08-01 10:21
@jinbullsushil can you please test #17205?

**Comment by f-liva** [comment] 2018-01-10 14:22
The solution proposed by @jinbullsushil solves the problem perfectly.

Why has the bug not yet been solved officially since the solution was proposed in August?

**Comment by C-Lodder** [comment] 2018-01-10 16:04
@fede91it - A PR has been submitted, so please feel free to test and mark your result.

https://github.com/joomla/joomla-cms/pull/17205

2 successfull tests are required for it to be merged.

Else if it doesn't work, you could submit a new PR to remove that file as suggested by @jinbullsushil

**Comment by muuvmuuv** [comment] 2018-06-11 09:17
The PR #17205 is no longer working with a repeatable field + `modal_article`-field. Tested on Joomla V3.8.8

```
      <!-- Fieldset: Dock -->
      <fieldset name="dock" label="Dock">

        <field name="dock_links" type="repeatable" icon="link" label="Links">
          <fieldset hidden="true" repeat="true" addfieldpath="/administrator/components/com_content/models/fields">
            <field name="name" type="text" label="Name" description="Social Name" filter="text"/>
            <field 
              name="article"
              type="modal_article"
              label="Select an article"
              select="true"
              edit="false"
              clear="true"
            />
          </fieldset>
        </field>

      </fieldset>
      <!-- ./Fieldset: Dock -->
```

**Comment by ghost** [comment] 2018-06-11 11:34
@muuvmuuv can you please open a new Issue as Comments on closed Issues didn't get much Notice.
