### ISSUE TITLE
[4.0] Icons on left Admin-Menu missed

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#17610] opened 2017-08-19 05:17 UTC
### Steps to reproduce the issue
Install latest 4.0-dev, got:
![bildschirmfoto 2017-08-19 um 07 16 15](https://user-images.githubusercontent.com/8235763/29483743-73b5fde4-84ae-11e7-98ec-84fae514a50a.jpg)

### System information
macOS Sierra, 10.12.6
Firefox 55 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by wilsonge** [comment] 2017-08-19 10:37
Duplicate of https://github.com/joomla/joomla-cms/issues/17593 - it's from the conflicts merging in 3.8 :(

**Closed as completed by wilsonge** 2017-08-19 10:37 UTC
Labels: No Code Attached Yet
