### ISSUE TITLE
Front end editing of menu items redirects to backend

### ISSUE THREAD

**Issue by joergenlarsen** [joomla/joomla-cms#9228] opened 2016-02-27 10:15 UTC
#### Steps to reproduce the issue
Enable front end editing of "Modules and menus"
Log into front end as super user
Hover mouse over menu item, and click the edit icon

#### Expected result
A screen in the front end with options to change menu titel, status etc.

#### Actual result
Redirection to the backend

#### System information (as much as possible)
Joomla 3.4.8

**Comment by bertmert** [comment] 2016-02-27 11:39
Cannot reproduce issue with current staging (Joomla 3.5beta). There module edit form opens in frontend.
Seems to be fixed.

**Comment by bertmert** [comment] 2016-02-27 11:41
SORRY! Removed my comment. You're right MENU editing redirects to backend.

**Comment by brianteeman** [comment] 2016-02-27 11:43
It is the menu editing which is a redirect to the admin interface. Which is
by design and the intended behaviour

**Comment by joergenlarsen** [comment] 2016-02-27 11:55
But why does this particular edit redirect to the admin interface? What is the point of enabling front end editing for menus, when you are forced to use the admin interface anyway?

**Comment by brianteeman** [comment] 2016-02-27 12:08
The point is to make it easier for you - you dont have to open admin, go to
menu manager, search for the correct menu item.

Yes it would be better if it was done completely on the frontend - but no
one has written any code to do that (if it is even possible)

On 27 February 2016 at 11:55, joergenlarsen <notifications@github.com>
wrote:

> But why does this particular edit redirect to the admin interface? What is
> the point of enabling front end editing for menus, when you are forced to
> use the admin interface anyway?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9228#issuecomment-189622206>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by joergenlarsen** [comment] 2016-02-27 12:35
It would be great, if it could be fixed. I run a number of community websites where trusted - but non-technical - users create all the content, and I prefer to keep them off the admin interface (which can be overwhelming to some). Thanks to the front-end editing even fairly inexperienced users can do a lot of the website editing, and it would be helpful if the menus too were front-end editable. I hope somebody will look into it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9228">issues.joomla.org/joomla-cms/9228</a>.</sub>

**Comment by GABBAR1947** [comment] 2016-02-29 22:31
I'd like to work on this. Please help me get started by elaborating the issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9228">issues.joomla.org/joomla-cms/9228</a>.</sub>

**Comment by GABBAR1947** [comment] 2016-03-06 12:33
I'm unable to understand this , as no such kind of issue occurs on my system. I get the expected result , as there is no redirection to the backend. Correct me if I'm missing out anything.

**Comment by brianteeman** [comment] 2016-03-06 12:34
Yes you are completely missing everything

On 6 March 2016 at 12:33, Shubham Rathore <notifications@github.com> wrote:

> I'm unable to understand this , as no such kind of issue occurs on my
> system. I get the expected result , as there is no redirection to the
> backend. Correct me if I'm missing out anything.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9228#issuecomment-192883900>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by xtech86** [comment] 2016-03-08 12:04
I can see Joergenlarsen's logic. Brian, we are showing it in the front-end to make it easier for the user, the user then is taken to the backend which is fine and works well making it very simple. But when you want to edit multiple menu items from the front-end busing this nice easy way, it becomes very laborious. 

What Joergenlarsen is trying to say from what I can gather, is that if you edit a menu item from the front-end, once you have finished and click either, save & close or cancel that it should redirect you back to page you were viewing before going to the admin area.

**Comment by brianteeman** [comment] 2016-03-08 12:11
I read it that they expected the editing of the menu to be done on the
front end just as editing the module is done on the front end. (not a bad
idea at all but it needs someone to write that code)

There is currently no need for a redirect on save because the admin
interface for editing the menu item was opened in a new tab

On 8 March 2016 at 12:04, Tony Partridge <notifications@github.com> wrote:

> I can see Joergenlarsen's logic. Brian, we are showing it in the front-end
> to make it easier for the user, the user then is taken to the backend which
> is fine and works well making it very simple. But when you want to edit
> multiple menu items from the front-end busing this nice easy way, it
> becomes very laborious.
>
> What Joergenlarsen is trying to say from what I can gather, is that if you
> edit a menu item from the front-end, once you have finished and click
> either, save & close or cancel that it should redirect you back to page you
> were viewing before going to the admin area.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9228#issuecomment-193755496>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by xtech86** [comment] 2016-03-08 12:34
Correct and I agree. 

I suspect you are then right and the user is expecting it to be like the Module Manager front end editing. Which I can also understand, but with the being in a new tab is kind of pointless as you are still on the same place and it's a single click to close. 

I think this issue can be closed therefore in my opinion.

**Comment by brianteeman** [comment] 2016-03-17 20:17
Closed as expected behaviour<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9228">issues.joomla.org/joomla-cms/9228</a>.</sub>

**Closed by brianteeman** 2016-03-17 20:17 UTC
Labels: No Code Attached Yet
