### ISSUE TITLE
PHP warning from menuitem.php

### ISSUE THREAD

**Issue by BrainforgeUK** [joomla/joomla-cms#17606] opened 2017-08-18 16:53 UTC
### Steps to reproduce the issue

Goto
.../administrator/index.php?option=com_modules

In Search tools select menu type

### Actual result

Warning shown in log / on screen (depending on php settings)
Warning: str_repeat(): Second argument has to be greater than or equal to 0 in W:\webserver\htdocs\Daniel\springs-aquatic.co.uk\libraries\cms\form\field\menuitem.php on line 234

### System information (as much as possible)

PHP 7.0.5
Joomla 3.7.4

**Comment by brianteeman** [comment] 2017-08-19 17:17
Confirmed

**Comment by zero-24** [comment] 2017-08-20 07:28
hmm looks like we need a special case for `$link->level === 0` ?

here: https://github.com/joomla/joomla-cms/blob/staging/libraries/src/Form/Field/MenuitemField.php#L238

**Comment by ghost** [comment] 2017-08-24 05:03
closed as havin Pull Request #17693<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17606">issues.joomla.org/tracker/joomla-cms/17606</a>.</sub>

**Closed as completed by ghost** 2017-08-24 05:03 UTC
Labels: No Code Attached Yet
