### ISSUE TITLE
[4.3] The text of the links of the Footer module should be visible on hovering

### ISSUE THREAD

**Issue by sandewt** [joomla/joomla-cms#41172] opened 2023-07-16 09:31 UTC
### Steps to reproduce the issue

Enable the module Footer.
The module shows the Joomla! copyright information.
Hover on the links, the links should be visible.

### Expected result

![screen shot 2023-07-16 at 09 27 06](https://issues.joomla.org/uploads/1/b4810ae7f4444332dd1bb77846f21732.png)

### Actual result

![screen shot 2023-07-16 at 09 27 17](https://issues.joomla.org/uploads/1/29c2eafc63ed29021962dee33406abaf.png)

### System information (as much as possible)

J4.3

### Additional comments

Related to the Button text color issue pr #40435 and #41153.

**Comment by brianteeman** [comment] 2023-07-19 05:22
Just like your other issue I can not replicate it at all

![image](https://github.com/joomla/joomla-cms/assets/1296369/1029097e-fae5-4dd6-b695-032ea5e81bc4)

**Comment by sandewt** [comment] 2023-07-19 05:40
> Just like your other issue I can not replicate it at all

Strange, I can't explain. The following screenshot shows the same. See: https://cassiopeia.joomla.com/blog


![issue_copyright-3](https://github.com/joomla/joomla-cms/assets/9271775/d40707fe-b0a8-4800-b662-e1d0351b0a95)

**Comment by brianteeman** [comment] 2023-07-19 06:01
see https://gsd.brianstest.site/

**Comment by sandewt** [comment] 2023-07-19 06:18
> see https://gsd.brianstest.site/

Both the Footer module and the Back-to-top Link show a correct display after hovering.

Windows 11, Firefox, Edge and Chrome.

**Comment by brianteeman** [comment] 2023-07-19 06:39
Found it and the reason why I couldnt replicate.

The problem is from your pull request https://github.com/joomla/joomla-cms/pull/40435

As that hasnt been upmerged into 4.4 or 5 yet then I didnt have the faulty css

**Comment by sandewt** [comment] 2023-07-19 09:02
Possible solution:

Change:
```
.footer a {
  color: currentColor;
}
```
to
```
.footer a, .footer a:focus, .footer a:hover {
  color: currentColor;
}
```

**Comment by ChristineWk** [comment] 2023-07-21 12:14
I think, it belongs to this: (on a test-site) and also here:
https://cassiopeia.joomla.com/blog

`a:not(.btn):focus, a:not(.btn):hover {
  color: var(--cassiopeia-color-hover);
}`

![issue-41172](https://github.com/joomla/joomla-cms/assets/15275917/3611368f-c340-4b1f-b39c-f1fa2144fa92)

This will work (in a user.css):

`.footer a, .footer a:focus, .footer a:hover {
  color: currentColor;
}`

**Comment by richard67** [comment] 2023-08-26 11:07
Closing as having a pull request. Please test #41461 . Thanks in advance.

**Closed as completed by richard67** 2023-08-26 11:07 UTC
Labels: No Code Attached Yet, PBF, bug
