### ISSUE TITLE
Impossible to display the entire dropdown list of menus

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-cms#9345] opened 2016-03-08 14:24 UTC
#### Steps to reproduce the issue
Go to the backend, create many menus and try to reach the bottom of the list

#### Expected result
To be able to select the items at the bottom of the list

#### Actual result
Not possible to reach the items at the bottom

#### System information (as much as possible)
J! 3.4.8

#### Additional comments
It's maybe a known issue, but didn't find it...
When you have a lot of menus (essentially for multilingual websites), it is not possible to display them all and so you have to go to "manage" to be able to display the menu items of these menus.

![menu_issue](https://cloud.githubusercontent.com/assets/4682328/13604145/c4a4f8dc-e517-11e5-9447-c66a76bdf5ec.png)

**Comment by brianteeman** [comment] 2016-03-08 14:35
Closed as a duplicate of #8371 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9345">issues.joomla.org/joomla-cms/9345</a>.</sub>

**Closed by brianteeman** 2016-03-08 14:35 UTC

**Comment by brianteeman** [comment] 2016-03-08 14:44
Its the same issue as when you have too many components<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9345">issues.joomla.org/joomla-cms/9345</a>.</sub>

**Comment by brianteeman** [comment] 2016-03-08 14:47
BTW this looks like a good solution https://ugate.wordpress.com/2013/06/28/scrollable-twitter-bootstrap-menus/<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9345">issues.joomla.org/joomla-cms/9345</a>.</sub>

**Comment by brianteeman** [comment] 2016-03-08 20:32
Please see #9347 for a proposed solution<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9345">issues.joomla.org/joomla-cms/9345</a>.</sub>
