### ISSUE TITLE
backgroun url in user.css requires full path.

### ISSUE THREAD

**Issue by rgtr** [joomla/joomla-cms#38947] opened 2022-10-12 11:30 UTC
### Steps to reproduce the issue
in the user css enter something like:
/* setup background image */
.grid_item_bg {
  /* this works */
  background: url('http://127.0.0.1/as_31011_a/images/banners/logo8-125.jpg'); 
  /* this does NOT work */
/*  background: url('../images/banners/logo8-125.jpg'); */
  /* this does NOT work either */
/*  background: url('images/banners/logo8-125.jpg'); */
  background-repeat:no-repeat;
}

### Expected result
to get an image - 

### Actual result
using the ../images/ or images/ does not show an image.

### System information (as much as possible)
Joomla 4.2.3

### Additional comments
for an example ... using the full url.
see here: https://tdocplus.co.uk/dionnevallantyne/ 

Richard

**Comment by brianteeman** [comment] 2022-10-12 11:43
No it doesnt require the full path. It just requires the correct path ;)

The path to the image is the path from the location of the css file that is referencing it. So in your specific case it would be
`url('../../../../../images/banners/bebe_01_s.jpg')`

![image](https://user-images.githubusercontent.com/1296369/195334088-4022219b-3849-4924-89db-756e01ab9f57.png)

Please use the forum for support. 

Can be closed - not a bug

**Comment by ReLater** [comment] 2022-10-12 11:44
`background: url('../images/banners/logo8-125.jpg');`

It depends on where your `user.css` is located.

Example 1: In `JOOMLAROOT/templates/MYTEMPLATE/css/user.css`

`background: url('../../../images/banners/logo8-125.jpg');`

Example 2: In `JOOMLAROOT/media/templates/site/MYTEMPLATE/css/user.css`

`background: url('../../../../../images/banners/logo8-125.jpg');`

**Comment by richard67** [comment] 2022-10-12 11:46
Closing as not a bug. For explanations see previous comments by @brianteeman and @ReLater (thanks guys).

**Closed as completed by richard67** 2022-10-12 11:46 UTC
Labels: No Code Attached Yet

**Comment by rgtr** [comment] 2022-10-13 09:34
Hi all
Thanks for the pathing info.
Richard
