### ISSUE TITLE
Cli finder indexer is giving error

### ISSUE THREAD

**Issue by humblehumanbeing** [joomla/joomla-cms#29590] opened 2020-06-13 02:37 UTC
### Steps to reproduce the issue
Run smart search indexer using cli command "php finder_indexer.php"
It runs for some time.
It exits indexing throwing an HTML page with an error message of "Call to a member function getTag() on null"

### System information (as much as possible)
Joomla! 3.9.18 Stable [ Amani ] 21-April-2020 19:30 GMT
Linux 
MySQL 5.5.5-10.2.32-MariaDB 
PHP 7.4.6

**Comment by softforge** [comment] 2020-06-13 06:56
I just tried this with Joomla 3.9.19 on PHP 7.3 and do not get any issues. If someone has php7.4 it might be worth trying just to see if they can replicate the issue

**Comment by SharkyKZ** [comment] 2020-06-13 10:53
I can't reproduce this issue on PHP 7.4.0 and 7.4.6.

@humblehumanbeing is this on a clean installation or do you have any extensions installed?

**Comment by grantg182** [comment] 2020-06-14 16:10
Ran into this exact issue yesterday with a cron failing. A recent update to SP Page Builder seemed to be the cause for me after I disabled all plugins and indexer worked fine again. Disabling that plugin before indexing, then re-enabling the plugin, solved my issue, and it's a [known issue at Joomshaper](https://www.joomshaper.com/forums/smart-search-sp-page-builder-error-0-call-to-a-member-function-gettag-on-null) - may or may not be relevant to you, but I guess it could be caused by a multitude of plugins.

**Comment by richard67** [comment] 2020-06-14 16:51
Closing as not a core issue, see [https://www.joomshaper.com/forums/smart-search-sp-page-builder-error-0-call-to-a-member-function-gettag-on-null](https://www.joomshaper.com/forums/smart-search-sp-page-builder-error-0-call-to-a-member-function-gettag-on-null).

But thanks for reporting, @grantg182 . It could have been a core issue at a first look, and better reporting one time too much than one time too little.

**Closed as completed by richard67** 2020-06-14 16:51 UTC
Labels: No Code Attached Yet
