### ISSUE TITLE
Can't access menu to add items in website created on launch.joomla.com

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#23317] opened 2018-12-22 11:43 UTC
### Steps to reproduce the issue
Created new website on launch.joomla.com
In Admin panel, clicking on either
a) Menus > All Menu Items, or
b) Menus > Main Menu

### Expected result
Access to menu to create new items or edit existing 'home' item

### Actual result
No access and this message:

An error has occurred.

    500 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.`published`,`a`.`component_id`,`a`.`checked_out`,`a`.`checked_out_time`,`a`.`br' at line 1 

### System information (as much as possible)
Latest joomla.com demo setup.
PHP is 7.0.33 which I have reported to CloudAccess.net. It should be min 7.1

### Additional comments
No

**Comment by Scrabble96** [comment] 2018-12-22 11:46
Sorry, can't see how to edit my post. 
Items b) should be Menus > Main Menu

Similar issues have been reported before, but those seem to be able to get further than I have and actually view menu items in the admin panel. I can't even get that far.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23317">issues.joomla.org/tracker/joomla-cms/23317</a>.</sub>

**Comment by SharkyKZ** [comment] 2018-12-22 14:53
If this is on 4.0, see #23293.

**Comment by Scrabble96** [comment] 2018-12-22 15:45
Yes, it's on 4.0. Any idea when it will be fixed? I can't doing anything until then as I'm using the online demo and not a local installation and have no access to source files.

**Comment by Quy** [comment] 2018-12-22 16:12
Duplicate of #23108. It will be merged when there are 2 successful tests.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23317">issues.joomla.org/tracker/joomla-cms/23317</a>.</sub>

**Closed as completed by Quy** 2018-12-22 16:12 UTC
Labels: No Code Attached Yet
