### ISSUE TITLE
Item description not working in "Tagged Items" menu item

### ISSUE THREAD

**Issue by htmgarcia** [joomla/joomla-cms#6348] opened 2015-03-06 18:06 UTC
Joomla 3.4

Steps to reproduce:
1. Create a menu item type: Tags > Tagged Items
2. Item options > Item description: show
3. Check the frontend. The description is not being displayed.
4. Go to Components > Tags > Options > Tagged item options > Item Description: yes
5. Check the frontend. This time the description is being displayed

Note: be sure the tagged articles has intro text.

**Comment by Harmageddon** [comment] 2015-03-11 12:00
Duplicate of #6354, this issue is already fixed in the current staging branch on GitHub and will be fixed in the next release, which is 3.4.1. Thank you for your report!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6348">issues.joomla.org/joomla-cms/6348</a>.</sub>

**Closed** 2015-03-11 12:00 UTC
Labels: No Code Attached Yet

**Comment by htmgarcia** [comment] 2015-03-11 15:19
Thanks guys! :)
