### ISSUE TITLE
New Router not throwing 404

### ISSUE THREAD

**Issue by joeforjoomla** [joomla/joomla-cms#12822] opened 2016-11-07 21:36 UTC
### Steps to reproduce the issue
Open a link to a real article:
http://joomla37/welcome-to-your-blog.html  -> 200 OK as expected

### Expected result

Open a link to a fake article:
http://joomla37/noexists.html -> 404 page not found

### Actual result
200 OK routed to the home page

### System information (as much as possible)
Joomla 3.7 staging with new router enabled

**Comment by brianteeman** [comment] 2016-11-08 00:26
I can not confirm this

![screen shot 2016-11-07 at 18 26 01](https://issues.joomla.org/uploads/1/904a4d5a9dbde8385610c41f904af485.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12822">issues.joomla.org/tracker/joomla-cms/12822</a>.</sub>

**Comment by joeforjoomla** [comment] 2016-11-08 01:00
What could be the difference?
![no404](https://cloud.githubusercontent.com/assets/17835460/20082572/2177ce9a-a557-11e6-9e52-cf565a9e30af.PNG)

**Comment by wojsmol** [comment] 2016-11-08 01:19
@joeforjoomla Your website is multilingual, @brianteeman tests most likely on the website with one language.

**Comment by joeforjoomla** [comment] 2016-11-08 09:03
Obviously i've tested even without multilanguage enabled... same issue

**Comment by infograf768** [comment] 2016-11-08 09:13
I confirm the issue here.

Conditions
Legacy monolanguage site updated since 1.6. to staging.
**New router set for com_contents.**
default data.

link to an article
**http://localhost:8888/trunkgitnew/single-article.html**
(Displays here Australian Parks)

If I enter
**http://localhost:8888/trunkgitnew/noexists.html**

I am redirected to the Home page. No 404.

**I get a 404 IF I use legacy router.**

**Comment by infograf768** [comment] 2016-11-08 09:14
@Hackwar
Can you look at this?

**Comment by brianteeman** [comment] 2016-11-08 09:16
Sorry (i forgot to turn on the modern router)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12822">issues.joomla.org/tracker/joomla-cms/12822</a>.</sub>

**Comment by infograf768** [comment] 2016-11-12 09:11
@Hackwar 
I guess this one can't be considered as "expected behaviour".

**Comment by Hackwar** [comment] 2016-11-12 09:26
This is actually undefined behavior in our router that can not be fixed in a backwards compatible way. Since that is the case, I opted to go the safe route instead of breaking half the extensions out there and thus making 90% of all URLs throw a 404.

In an ideal world, the router would take a URL in whatever format we have and then convert that URL from whatever format into a non-SEF format. There is very little that the router can actually do to validate an adress. index.php?option=com_content&view=article&id=42 might be a valid article or it might not. The component would later have to throw a 404 in that case. The router could only notice that the URL might be bogus if after all transformations there is still a path left (=a part that is still SEF). That would require that all component routers and all routing rules from third partys properly remove the parts of the URL that they processed. That unfortunately is not the case. So we have 2 choices here: break B/C and throw 404s or not break B/C and have more false positives.

**Comment by joeforjoomla** [comment] 2016-11-12 09:30
Well there must be an alternative solution to not break any B/C and instruct at least the com_content that it must throw a 404 page. It must be found in some way, after all it worked till nowadays.

**Comment by Hackwar** [comment] 2016-11-12 09:32
No, it did not. It showed random articles instead of the homepage, but otherwise it did not properly throw a 404

**Comment by infograf768** [comment] 2016-11-12 09:35
The fact still is that legacy router now works fine for the 404 and not the "modern" router.

**Comment by Hackwar** [comment] 2016-11-12 09:39
That is a false statement.

**Comment by infograf768** [comment] 2016-11-12 09:46
Certainly not. I suggest you test for yourself.
Backend settings for com_content

![screen shot 2016-11-12 at 10 42 22](https://cloud.githubusercontent.com/assets/869724/20236925/0a6b558e-a8c5-11e6-9a9b-073ee53e61ef.png)

Normal article link
![screen shot 2016-11-12 at 10 43 29](https://cloud.githubusercontent.com/assets/869724/20236928/1df5113a-a8c5-11e6-8f4e-bc88790f0ae5.png)

Not existing

![screen shot 2016-11-12 at 10 43 52](https://cloud.githubusercontent.com/assets/869724/20236933/32d60078-a8c5-11e6-957a-cd77e95b290f.png)

**Comment by Hackwar** [comment] 2016-11-12 09:48
test /6-bogus 
That should throw a 404, right? Legacy routing displays the australian park article, while modern routing displays the homepage.

**Comment by joeforjoomla** [comment] 2016-11-12 09:49
I understand what's saying @Hackwar, but @infograf768 is right. The behaviour of Joomla since ages worked as expected throwing 404 when needed, so blaming a new brand routing system that fails is not really good. We have a problem here. @Hackwar please take some more time to analyze a possible solution and improve the modern router

**Comment by joeforjoomla** [comment] 2016-11-12 09:50
No rush after all

**Comment by Hackwar** [comment] 2016-11-12 09:57
I explained the solution and the consequences here: https://github.com/joomla/joomla-cms/issues/12822#issuecomment-260111612
And I also explained why this is a break in B/C. Unfortunately this is a mute discussion as long as you guys simply demand that something works one way and don't accept the implications that come with that. Feel free to look at the code and propose how this could be solved. Just keep in mind that it still needs to fulfill the requirements that I described above.

**Comment by joeforjoomla** [comment] 2016-11-12 18:24
In the content router.php
`/**
	 * Method to get the segment(s) for an article
	 *
	 * @param   string  $segment  Segment of the article to retrieve the ID for
	 * @param   array   $query    The request that is parsed right now
	 *
	 * @return  mixed   The id of this item or false
	 */
	public function getArticleId($segment, $query)
	{
		if ($this->noIDs)
		{
			$db = JFactory::getDbo();
			$dbquery = $db->getQuery(true);
			$dbquery->select($dbquery->qn('id'))
				->from($dbquery->qn('#__content'))
				->where('alias = ' . $dbquery->q($segment))
				->where('catid = ' . $dbquery->q($query['id']));
			$db->setQuery($dbquery);

			return (int) $db->loadResult();
		}

		return (int) $segment;
	}`

when an article ID is not existing you return 0, so int he standard.php would not be possible stop the routing or throw a 404 here:

`else
				{
					if (is_callable(array($this->router, 'get' . ucfirst($view->name) . 'Id')))
					{
						// Hand the data over to the router specific method and see if there is a content item that fits
						$key = call_user_func_array(array($this->router, 'get' . ucfirst($view->name) . 'Id'), array($segment, $vars));

						if ($key)
						{
							// Found the right view and the right item
							$parent = $views[$vars['view']];
							$vars['view'] = $view->name;
							$found = true;

							if ($view->parent_key && isset($vars[$parent->key]))
							{
								$parent_key = $vars[$parent->key];
								unset($vars[$parent->key]);
								$vars[$view->parent_key] = $parent_key;
							}

							$vars[$view->key] = $key;

							break;
						}
					}
				}`

**Comment by Hackwar** [comment] 2016-11-12 18:26
The solution would be what I did in #12875

**Comment by Hackwar** [comment] 2016-11-12 18:28
No, throwing a 404 simply because the last segment was not discovered as an article will not work. Because you can take a plugin and rewrite the pagination for the blog view to use /page-2, etc. instead of ?start=2, which means that that segment might be an article or it might be the page to start from.

**Comment by joeforjoomla** [comment] 2016-11-12 18:32
I understand @hackwar, that's not easy. Obviously it's better having some more false positives that break B/C and all extensions out there. If anyone has some ideas... greatly accepted

**Comment by Hackwar** [comment] 2016-11-12 18:36
As I said, the changes in #12875 are doing exactly what you want. Unfortunately not B/C and thus only for 4.0. You guys could concentrate on that and we could get that one out the door soon.

**Comment by wilsonge** [comment] 2017-03-20 09:42
Please test https://github.com/joomla/joomla-cms/pull/14542

**Closed by wilsonge** 2017-03-20 09:42 UTC
Labels: No Code Attached Yet
