### ISSUE TITLE
[4.0] Missing mail template not handled correctly

### ISSUE THREAD

**Issue by BrainforgeUK** [joomla/joomla-cms#36478] opened 2021-12-29 14:59 UTC
### Steps to reproduce the issue

Try to send mail using a mail template which does not exist.

```
$mailer = new MailTemplate('com_bftest.invalidtemplateid', $language);
$mailer->addRecipient($templateData['emailto'], $templateData['emailtoname']);
$mailer->setReplyTo($templateData['replytoemail'], $templateData['replytoname']);
$mailer->addTemplateData($templateData);
$sent = $mailer->send();
```

### Expected result

Sensible error message saying template does not exist

### Actual result

Load of PHP notices and a 'Message body empty' warning.

### Additional comments

Be better to add a getInstance() static method to MailTemplate which would allow this
```
$mailer = MailTemplate::getInstance('com_bftest.invalidtemplateid', $language);
if (empty($mailer))
{
     ... take some action ...
}
$mailer->addRecipient($templateData['emailto'], $templateData['emailtoname']);
$mailer->setReplyTo($templateData['replytoemail'], $templateData['replytoname']);
$mailer->addTemplateData($templateData);
$sent = $mailer->send();
```
Can do this as a workaround - downside MailTemplate::getTemplate() gets called twice.
```
$test = MailTemplate::getTemplate($templateId, $language);
if (empty($mail))
{
     ... take some action ...
}
$mailer = new MailTemplate('com_bftest.invalidtemplateid', $language);
$mailer->addRecipient($templateData['emailto'], $templateData['emailtoname']);
$mailer->setReplyTo($templateData['replytoemail'], $templateData['replytoname']);
$mailer->addTemplateData($templateData);
$sent = $mailer->send();
```

**Comment by PhilETaylor** [comment] 2021-12-29 23:41
The problem is that, mails can come from anywhere, Admin, Frontend, CLI etc... So the correct thing would be an Exception, but that is too hard on a "user trying to send a contact form, formatted by a non existing mail template) and equally, in /administrator/ a "error" message can be disabled in the admin console, and for CLI an exception...

however to capture all that, the try/catch block has to be in your code. 

therefore I would just say that `$mailer->send()` should return false, with no other error messages

or just throw an Exception and expect 3PD to deal with catching it?

**Comment by PhilETaylor** [comment] 2021-12-30 00:32
Simple approach https://github.com/joomla/joomla-cms/pull/36489

**Comment by richard67** [comment] 2021-12-30 08:07
Closing as having a pull request. Please test #36489 . Thanks in adcance.

**Closed as completed by richard67** 2021-12-30 08:07 UTC
Labels: No Code Attached Yet
