### ISSUE TITLE
[4.0] API content/article

### ISSUE THREAD

**Issue by Razzo1987** [joomla/joomla-cms#27673] opened 2020-01-27 09:11 UTC
### Steps to reproduce the issue

Try to create an article with this data:

```
"title":"La Nigeria prende in consegna l'ex procuratore generale Adoke per un affare di petrolio da 1,3 miliardi di dollari",
"catid":8,
"state":1,
"created":"2020-01-24 08:23:05",
"language":"*",
"metadesc":"ABUJA (Reuters) - Il cane da guardia del crimine finanziario della Nigeria ha accusato l'ex procuratore generale Mohammed Adoke ...",
"metakey":"",
"articletext":"<p>ABUJA (Reuters) - Il cane da guardia del crimine finanziario della Nigeria ha accusato l'ex procuratore generale Mohammed Adoke di aver presumibilmente ricevuto tangenti per facilitare un accordo petrolifero di $ 1,3 miliardi, ha detto l'agenzia in una nota gioved\u00ec.<\/p><div class=\"alert alert-info\" role=\"alert\">Articolo tradotto da <a href=\"http:\/\/feeds.reuters.com\/~r\/reuters\/AFRICATopNews\/~3\/mXLflbrOo7Q\/idAFKBN1ZN0HU-OZATP\" target=\"_blank\">Top Africa News<\/a>.<\/div>"
}
```

### Expected result

Article created and published

### Actual result

I recieve this error:

```
{
   "errors":[
      {
         "title":"Save failed with the following error: Data too long for column 'title' at row 1"
      }
   ]
}
```

### System information (as much as possible)

Nightly of 26/01/2019

### Additional comments

If I use a shorter title, the article is still inserted but is unpublished

**Comment by SharkyKZ** [comment] 2020-01-27 09:21
I can reproduce the issue without API. `title` column in `#__assets` table has 100 character limit. In J3 longer titles were truncated and in J4 the entry is not created.

**Comment by brianteeman** [comment] 2020-01-27 09:22
I am not sure what you are expecting. You tried to submit an article with a title that was too long and correctly received a message that it could not be saved as the title was too long. When you submitted an article with a title that was short enough then the article was saved.

**Comment by wilsonge** [comment] 2020-01-27 09:24
So the publish part is kinda a known issue - I’m not even 100% if it’s a bug. This is how workflows functions right now. State is effectively read only as a property - we’d need to update the workflow_id property.
I’ve written that up a bit more here https://github.com/joomla/joomla-cms/issues/26841

**Comment by alikon** [comment] 2020-01-27 09:31
or simply drop workflow as it is not ready

**Comment by brianteeman** [comment] 2020-01-27 09:33
@alikon I will repeat what I said in Spain. If you believe that it is not ready then where are the issues reported that make that clear. Everything I see is relatively easy to fix.

**Comment by alikon** [comment] 2020-01-27 09:38
https://github.com/joomla/joomla-cms/issues/24536
https://github.com/joomla/joomla-cms/pull/21702#issuecomment-420209156

**Comment by alikon** [comment] 2020-01-27 09:41
it's bad design  it is not a https://en.wikipedia.org/wiki/Finite-state_machine as it should be
and + simply use what it already used and tested like https://symfony.com/doc/current/workflow/workflow-and-state-machine.html
+ don't reinvent all the time the whell

+ https://volunteers.joomla.org/teams/workflow-project-team what they have done ?

**Comment by brianteeman** [comment] 2020-01-27 09:44
such a shame that this wasnt mentioned when it was submitted and then merged. I was the only one really saying it wasn't ready etc

**Comment by alikon** [comment] 2020-01-27 09:49
it was , till someone blocked the discussion 

> This conversation has been locked as resolved and limited to collaborators.

**Comment by brianteeman** [comment] 2020-01-27 10:31
where?

**Comment by alikon** [comment] 2020-01-27 11:02
https://github.com/joomla/joomla-cms/pull/20381
https://github.com/joomla/joomla-cms/issues/21476#issuecomment-411703704
https://github.com/joomla/joomla-cms/issues/21476#issuecomment-411730733

**Comment by brianteeman** [comment] 2020-01-27 11:08
thanks - I was missing the locked one.

18 months since **I said** it wasn't ready and should be reverted then. A lot of work was done on it since then.

My point is that other than **my** closed call for it to be reverted there hasnt been any further discussion in 18 months

**Comment by alikon** [comment] 2020-01-27 11:20
yes a lot of work has been done (after) to let it barely working, but my main concern it's about the performance of a real site with more than 100 articles, plus a team was setup to  create an enhanced  version before beta iirc (so it was clear from the start that wasn't ready)

**Comment by Razzo1987** [comment] 2020-01-27 21:52
> 
> 
> I can reproduce the issue without API. `title` column in `#__assets` table has 100 character limit. In J3 longer titles were truncated and in J4 the entry is not created.

Yes, but `title` column in `#__content` table has 255 character limit...

Also if I try to create the article from the back-end, as you correctly said, I get the same error.

But the strange thing is that going to see in the table `#__content` the article is present (creating the arcticle from the back-end or via API is the same):

![immagine](https://user-images.githubusercontent.com/906604/73217066-848cc680-4157-11ea-9fc7-43e018e704d7.png)

**Comment by Razzo1987** [comment] 2020-01-27 21:56
As regards the aspect of the publication workflow, I partially understood what was said.

What I don't understand is why it is different between creating articles from back end and with API.

As superuser I can safely create an article as already published by the back end:
![immagine](https://user-images.githubusercontent.com/906604/73217443-36c48e00-4158-11ea-8a3d-47dbf370d78c.png)

**Comment by SharkyKZ** [comment] 2020-01-31 17:37
@Razzo1987 try using `condition` property instead of `state` to set article status.

**Comment by SharkyKZ** [comment] 2020-01-31 17:39
What do we do with assets table issue? Increase column length 255 and hope nobody uses longer titles? Truncate the title in code? Add some rollback actions?

**Comment by chmst** [comment] 2020-01-31 21:53
I think, truncating the title in the code for the asset table has no risk, as the title is not used as identifier.

**Comment by korenevskiy** [comment] 2020-02-06 10:56
A 100-character header is not enough. 
We don't make headlines to make it easy to search for an article in the archive. We create headlines to sell products, to write news, to attract people. Thus, the CMS must adapt to the needs, content Creators should not adapt to the CMS, especially when the CMS is at the development stage, we must and can already take into account the requirements of the market.

**Comment by chmst** [comment] 2020-02-06 11:14
Maybe it is a misunderstanding. I meant the title in the table #__assets which is only visible for maintainers in the database. And think that the title there could be truncated. 
In #__content the length of title is 255.

@korenevskiy Do you think this is to short?

**Comment by brianteeman** [comment] 2020-02-06 11:21
> I can reproduce the issue without API. `title` column in `#__assets` table has 100 character limit. In J3 longer titles were truncated and in J4 the entry is not created.

This is the issue. It isn't anything to do with the webservices API

**Comment by alikon** [comment] 2020-04-20 12:15
there are some issues when we have a very long article title like : 
`"La Nigeria prende in consegna l'ex procuratore generale Adoke per un affare di petrolio da 1,3 miliardi di dollari"`

despite the content title of the` #__content ` table field allows 255 chars
https://github.com/joomla/joomla-cms/blob/4.0-dev/installation/sql/mysql/extensions.sql#L162
the`#__assets `table don't allows more than 100 chars
https://github.com/joomla/joomla-cms/blob/4.0-dev/installation/sql/mysql/base.sql#L15

plus the `#__finder_links'` table field route 
https://github.com/joomla/joomla-cms/blob/4.0-dev/installation/sql/mysql/extensions.sql#L262
will add some more chars to the title  length

so even if the title length of an article in theory is 255 in pratice should be less than 200

**Comment by alikon** [comment] 2020-04-20 12:16
a dirty attempt to circumvent is #28734

**Comment by alikon** [comment] 2020-04-21 08:36
for the unpublished status when an article is submitted from the api
if you add ` "transition": 2` to the body of your POST request  something like this
![Screenshot from 2020-04-21 10-29-05](https://user-images.githubusercontent.com/181681/79843795-0426dc00-83bb-11ea-87b1-afb58e92d683.png)

your article will be saved  with the published status

![Screenshot from 2020-04-21 10-32-50](https://user-images.githubusercontent.com/181681/79844216-ad6dd200-83bb-11ea-95ef-9b8edf8c3054.png)


don't forget to apply pr #28734
and ` "transition": 2` will work only if you are using the default workflow stage/transition

**Comment by alikon** [comment] 2020-04-21 08:37
so i'm closing this issue

**Closed as completed by alikon** 2020-04-21 08:37 UTC
Labels: No Code Attached Yet

**Comment by wilsonge** [comment] 2020-05-02 17:21
@alikon wondering if it would be useful to give people a helpful hint in the API if they try to update the state field directly

**Comment by alikon** [comment] 2020-05-03 06:07
maybe  best to wait till the new workflow will land in core, and then reconsider it
