### ISSUE TITLE
[4.0] Edit template files in the backend

### ISSUE THREAD

**Issue by ChristineWk** [joomla/joomla-cms#27832] opened 2020-02-06 23:17 UTC
### Steps to reproduce the issue

Error symptom: Edit template (Cassiopeia) files in the backend -> editor window is only approx. 15 or 20 px wide because the content to be edited has slipped into the right margin of the actual editor window

### Actual result

see screenshot

### System information (as much as possible)

4.0.0-dev from 05feb2020

### Additional comments

It flashes very briefly, then it disappears. Then I only have a small vertical bar with text on the right.
Sorry, I'm not sure, if image has been inserted. 
@richard67 please check

**Comment by ChristineWk** [comment] 2020-02-06 23:20
![backend_cassiopeia_05feb2020](https://user-images.githubusercontent.com/15275917/73987104-a5b39b00-493f-11ea-8f50-83453f6db29a.JPG)

**Comment by ChristineWk** [comment] 2020-02-06 23:22
sorry, I had the wrong button & closed by fault (:-<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27832">issues.joomla.org/tracker/joomla-cms/27832</a>.</sub>

**Comment by richard67** [comment] 2020-02-06 23:23
Can confirm on clean new install of a clean current 4.0-dev. Edited content appears for a short flash in editor area but then ends in the margin right beside it. But others I’ve asked to test could not reproduce it. So it seems it doesn’t happen to everybody.

**Comment by ChristineWk** [comment] 2020-02-06 23:25
@richard67 Thanks :-)

**Comment by richard67** [comment] 2020-02-06 23:35
@ChristineWk I’ve changed category in the issue tracker. Templates (Site) was wrong because you edit the files in the Admin template. It doesn’t matter if you edit site or admin template files I think. And com_templates was not suitable too because the issue is not related to template management functions. It’s an issue of the backend templates’ file editor view.

This just for your info, no problem.

**Comment by richard67** [comment] 2020-02-07 00:19
I’ll see if I can find out more. I’ve replicated the issue on 2 different Linux systems with different browsers. @ChristineWk used Linux, too, as far as I know. Christine please confirm or correct. @N6REJ you used Windows and could not reproduce, right? Maybe again an issue with case-sensitivity of file names having to fit to class names?

**Comment by richard67** [comment] 2020-02-07 00:21
@chmst You could not reproduce, too, right?  Did you use Windows as Webserver for the test?

**Comment by brianteeman** [comment] 2020-02-07 00:22
I can replicate on windows
It is a codemirror issue (disable codemirror and you will see its ok)

**Comment by richard67** [comment] 2020-02-07 00:24
Or case sensitivity in asset file name or path? That fits better to this issue than the class file name thing. I think some asset loading fails on Linux. Need to continue tomorrow with better error logging,

**Comment by richard67** [comment] 2020-02-07 00:25
Ah thanks @brianteeman .

**Comment by brianteeman** [comment] 2020-02-07 00:26
Its 100% a codemirror issue

The issue you observed will happen anywhere that the codemirror editor is being used.

**Comment by richard67** [comment] 2020-02-07 00:27
Thanks Brian, that info helps much. Will investigate tomorrow if nobody is faster.

**Comment by brianteeman** [comment] 2020-02-07 00:40
@fedik can you check this please. 

I am pretty certain this is related to the web assets changes you have recently made

**Comment by N6REJ** [comment] 2020-02-07 03:38
Yeah, I'm on windows 10 x64 pro.  I do have a linux laptop if necessary

**Comment by richard67** [comment] 2020-02-07 09:05
@N6REJ No need, Brian could reproduce it on Windows, too.

**Comment by ChristineWk** [comment] 2020-02-07 11:20
@richard67 Thanks for correcting the category in Issue Tracker. It was late/early :-) I'm on Windows. 
History behind: I wanted to test PR27799 and discovered mentioned above. It was 4.0.0-dev from 20jan2020. Then I removed and installed a completely new installation on 05feb2020.

@brianteeman confirm: It is a codemirror issue (disable codemirror and you will see its ok)

 

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27832">issues.joomla.org/tracker/joomla-cms/27832</a>.</sub>

**Comment by Fedik** [comment] 2020-02-07 13:41
The problem with `node build` somewhere, it does not produce minified version of codemiror css files 
(if  enabled debug mode all will work).
I cannot find where it was :smile: 


@dgrammatiko where the code for minification of codemiror css files? :smiley:

**Comment by brianteeman** [comment] 2020-02-07 13:47
i would have expected it in build/init.es6.js

**Comment by Fedik** [comment] 2020-02-07 13:53
build/init only copying a files (and merge some)

**Comment by Fedik** [comment] 2020-02-07 14:44
I can offer only this #27847

I tried enable minification in build/compliecss but it resets the source files also, makes them empty.

**Comment by richard67** [comment] 2020-02-07 15:22
@Fedik Is PR #27847 an intermediate solution (= workaround), or is it the final solution?
Or in other words: Can this issue be closed?

**Comment by Fedik** [comment] 2020-02-07 15:39
More like workaround, but there nothing "hacky", 
I think, if there no other fixes, then this issue can be closed

**Comment by richard67** [comment] 2020-02-07 15:45
There is no other fix, not yet .. shall we wait a bit maybe?

**Comment by Fedik** [comment] 2020-02-07 15:56
I would close, I have doubt that there will be another one :wink:

**Comment by richard67** [comment] 2020-02-07 15:57
Ok, we can reopen it if protest ;-)

**Comment by richard67** [comment] 2020-02-07 15:58
Closing as there is PR #27847 . Thanks @Fedik 😄 .

**Closed as completed by richard67** 2020-02-07 15:58 UTC
Labels: No Code Attached Yet
