### ISSUE TITLE
Browser page title not displaying correctly after making site multilingual

### ISSUE THREAD

**Issue by talet** [joomla/joomla-cms#12382] opened 2016-10-10 22:09 UTC
### Steps to reproduce the issue
Had site only in english, with some articles/categories/menu item in hindi (google fonts) - which were working fine, displaying browser page titles in both languages correctly.

Installed hindi language pack, created language switcher module, enabled filter & language code plugins, created new main menu in Hindi alongwith a menu module in Hindi, reconnected existing hindi articles and categories to Hindi menu after changing article/category/menu language to Hindi. 

Site outputs pages in both languages seamlesssly. Browser page titles for english pages working as desired, but not hindi pages - which display garbled browser page title. Have also tried setting hindi article, category and menu aliases to be in english instead of hindi - but browser page title doesn't show legible information

### Expected result
Browser page titles should display correctly in both languages.

### Actual result
Browser page titles in English are displaying correctly, but in Hindi output "$ s को$ s" on all pages. So, Hindi pages are not generating legible title, as something seems to be overriding output.

### System information (as much as possible)
PHP Built On	Linux gator4176.hostgator.com 3.12.35.1418868451 #1 SMP Wed Dec 17 20:10:32 CST 2014 x86_64
Database Version	5.5.51-38.2
Database Collation	utf8_unicode_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	5.6.24
Web Server	Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 3.6.2 Stable [ Noether ] 4-August-2016 23:41 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36

### Additional comments
My site is live. Would appreciate any help or guidance. Many thanks

**Comment by infograf768** [comment] 2016-10-11 08:22
Using Tamil here as Content Language, I can't reproduce your issue.
This site is also using unicode alias

![screen shot 2016-10-11 at 10 20 57](https://cloud.githubusercontent.com/assets/869724/19263400/77d9c232-8f9c-11e6-9446-78f99726debf.png)

can you post a screenshot of the issue on your site?

**Comment by talet** [comment] 2016-10-11 09:53
Many thanks for having a look and trying to help. Here is the screenshot

**Comment by talet** [comment] 2016-10-11 09:55
![joomla hindi browser page titles not displaying](https://cloud.githubusercontent.com/assets/20837144/19266392/cf65dbb2-9005-11e6-8fef-93cdd8d742e1.jpg)

**Comment by infograf768** [comment] 2016-10-11 10:13
What are your Global settings for Site Name?
![screen shot 2016-10-11 at 12 11 27](https://cloud.githubusercontent.com/assets/869724/19266881/fa7d27f6-8fab-11e6-9fd4-8f81035d9019.png)

What is the custom name you entered for the HIndi Content Language?
![screen shot 2016-10-11 at 12 09 32](https://cloud.githubusercontent.com/assets/869724/19266904/108b534c-8fac-11e6-8011-7d7ba6d82297.png)

**Comment by brianteeman** [comment] 2016-10-11 13:50
This sounds like a possible conflict with another plugin and not a core Joomla issue. Please try to disable other plugins such as the one you have creating the og: metadata.

Also as this is not a core issue I am closing this. Please use the forum for support http://forum.joomla.org

**Closed by brianteeman** 2016-10-11 13:50 UTC
Labels: No Code Attached Yet

**Comment by talet** [comment] 2016-10-11 19:00
Thanks infograf768. 
Global settings for Site Name are set to after - in Global Configuration
custom name entered for the HIndi Content Language is टेलटाउन
The garbled output shows two $ signs, so it is pulling the local name generated by menu and appending the site name for language, I think, but the output is illegible.

brianteeman
I have tried to raise this on Joomla Forums twice. Received no replies/response/advice.
The only external plugins I was using were content- fast social share, JCE and Google Translate. Have disabled Fast Social Share and Google Translate. No change.

**Comment by infograf768** [comment] 2016-10-25 15:53
Found out your issue:
in `language/hi-IN/hi-IN.ini`

change the string
`JPAGETITLE="% 1 $ s को% 2 $ s"`
to
`JPAGETITLE="%1$s - %2$s"`

Mig will make a new pack asap

**Comment by imanickam** [comment] 2016-10-25 16:33
The next version of the current Hindi language pack (hi-IN_joomla_lang_full_3.3.6v2.zip) has been released.  Refer http://joomlacode.org/gf/project/jtranslation3_x/frs/?action=FrsReleaseBrowse&frs_package_id=6461.

Now the Title is shown as designed.

![screen shot 2016-10-25 at 11 33 52](https://issues.joomla.org/uploads/1/237dc3a61bfba2486d34c33e44809b79.jpg) <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12382">issues.joomla.org/tracker/joomla-cms/12382</a>.</sub>

**Comment by talet** [comment] 2016-10-25 23:51
Many thanks Jean-Marie.

**Comment by talet** [comment] 2016-10-26 00:04
Many thanks Ilagnayeru Manickam. Appreciate the attention and empathy you and Jean-Marie showed.

Kind regards

 

Rajeev Wadhwa

http://taletown.org/en/

**Comment by talet** [comment] 2016-10-26 15:43
Merci.
