### ISSUE TITLE
generated -tag despite set to "no"

### ISSUE THREAD

**Issue by meinolf-mueller** [joomla/joomla-cms#20833] opened 2018-06-22 04:37 UTC
### Hello,
I've set "Show page heading" in Menus > All menu items > Options (right-top button in the screen) > Show Page Heading to "NO".
![image004](https://user-images.githubusercontent.com/40481992/41757567-246275fc-75e3-11e8-89a7-a34faf74e2c9.png)
Within all my menus I've set "Show page heading" to global setting.
![image005](https://user-images.githubusercontent.com/40481992/41757636-8d9a6dea-75e3-11e8-94a7-3173d9a4cd6a.png)
This menu has article-list:
![image006](https://user-images.githubusercontent.com/40481992/41757700-e8a40be2-75e3-11e8-959b-69e9e9b2f9ca.png)
### Expected result
Joomla shouldn't generated an h1-tag containing the menus title
### Actual result
Joomla genertaes h1-tag containing menus title:
![image007](https://user-images.githubusercontent.com/40481992/41757868-12496ad6-75e5-11e8-8a95-29534b456a76.png)
### System information (as much as possible)
I'm using Windows 10, actual version, Joomla 3.3.8 (actual version).
The above issue can be seen using [(https://www.fit-in-mathe-online.de/abschlusspruefungen/realschulabschluss-gleichungen-pflichtteilaufgaben )]
### More information
If I explicitely change "Show page heading" within menu to "No", then the h1-tg is not generated, which means that global setting has no effect.
If you need more information (admin user, acces to the site) don't hesitate to contact me.
Best regards
M. Müller

**Comment by SharkyKZ** [comment] 2018-06-22 05:50
Test with Protostar template please.

**Comment by carlitorweb** [comment] 2018-06-22 12:23
I cant reproduce your issue 

![video_2018-06-22_082357](https://user-images.githubusercontent.com/3956472/41776365-7bcb2ea8-75f5-11e8-87d3-5fc6fb18f46a.gif)

**Comment by carlitorweb** [comment] 2018-06-22 13:04
But, I think there is another issue. When you define a global `Page Heading` and having the local `Page Heading` menu item without value, the global value it is not taken, and the Title of the menu item is put as `Page Heading` in the frontend.

**Comment by ghost** [comment] 2018-06-23 05:05
@carlitorweb can you please open a new Issue for Issue you comment above?

**Comment by ghost** [comment] 2018-06-23 05:07
Closed as unconfirmed Report.

This Issue can always be reopened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20833">issues.joomla.org/tracker/joomla-cms/20833</a>.</sub>

**Closed as completed by ghost** 2018-06-23 05:07 UTC
Labels: No Code Attached Yet
