### ISSUE TITLE
Backend issues after update from 3.7.5 to 3.8.0

### ISSUE THREAD

**Issue by shelvinG** [joomla/joomla-cms#18023] opened 2017-09-20 21:03 UTC
### Steps to reproduce the issue
Some admin features on Joomla backend receive Fatal Errors after upgrading to 3.8.0

1. From Joomla Menu -> Extensions -> Modules gives error 1. below
2. From Joomla Menu -> Selecting any Menu item gives error 2. below

### Expected result
1. access Modules
2. access Menus and Menu items

### Actual result
1. Fatal error: Call to undefined method JModuleHelper::isAdminMultilang() in /home/pagetrad/public_html/toprated/administrator/components/com_menus/controller.php on line 34
2. Fatal error: Call to undefined method JModuleHelper::isAdminMultilang() in ...administrator/components/com_modules/controller.php on line 80

### System information (as much as possible)
Joomla auto update from backend caused the issue
PHP Built On 	Linux s[.........].com 3.12.18-clouder0 #85 SMP Mon Apr 3 10:28:14 EEST 2017 x86_64
Database Version 	5.6.36-82.1-log
Database Collation 	utf8_general_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	5.6.31
Web Server 	Apache
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 3.8.0 Stable [ Amani ] 19-September-2017 14:00 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0

**Comment by mbabker** [comment] 2017-09-20 21:05
Duplicate of https://github.com/joomla/joomla-cms/issues/18003

**Closed as completed by mbabker** 2017-09-20 21:05 UTC
Labels: No Code Attached Yet
