### ISSUE TITLE
Missing Backport Patch in 3.5 B2

### ISSUE THREAD

**Issue by blueforce** [joomla/joomla-cms#9076] opened 2016-02-05 08:53 UTC
I run J! 3.5.0 B2 with PHP 7.0.2
I tryed to start 3pd CLI Scripts via SSH

Fatal error: Call to a member function get() on null in /home/usr/public_html/ROOT/libraries/joomla/session/handler/joomla.php on line 70

obviously the session-patch from 3.4.6/3.4.8 is missing in 3.5..
Bug or feature?

**Comment by wilsonge** [comment] 2016-02-14 18:13
This is a unrelated bug to the session patches of 3.4.8.

I am unable to replicate this report however running any of the core Joomla CLI scripts or the Akeeba Release System CLI Script. Please try again on the bleeding edge version of 3.5 (https://developer.joomla.org/cms-packages/). If you can still reproduce it I will you to give me a copy of the CLI script you are running so I can replicate the issue and try and find a fix (if required).

**Comment by brianteeman** [comment] 2016-03-10 17:13
@blueforce its been a month since @wilsonge asked for more information - is this still an issue or should it be closed now?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9076">issues.joomla.org/joomla-cms/9076</a>.</sub>

**Comment by wilsonge** [comment] 2016-03-12 17:02
OK I just tried this on Akeeba Backup after seeing the initial ticket here: https://www.akeebabackup.com/support/akeeba-backup-3x/24368-cli-php7-compliance.html

With Akeeba Backup 4.5.5 Pro - I wasn't able to replicate the issue either checking for updates or running a backup with staging. The error just makes no sense - it's what we introduced in 3.4.7 and fixed in 3.4.8 (which were both between beta 1 and beta 2) so without any more information I'm going to close this ticket<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9076">issues.joomla.org/joomla-cms/9076</a>.</sub>

**Closed** 2016-03-12 17:02 UTC
Labels: No Code Attached Yet
