### ISSUE TITLE
Module Article - Latest (3.7.0 - 3.7.1 RC2)

### ISSUE THREAD

**Issue by mseidl73** [joomla/joomla-cms#16029] opened 2017-05-15 14:01 UTC
When you click on an entry in such a module, the correct article appears, but the wrong page header appears, the slider is not hidden and the article information is not displayed! This applies to my modules ("News", "Neue Experimente & Synthesen", "Neue Tutorials" and "Neu in der Datenbank"). Article Info is lost. The differences from J 3.6.5 to J 3.7.0 I have marked in the attached pictures.
The cause is somewhere in root\components\com_content. I have on my local installation the said folder from the 3.7.0 deleted and copied from the 3.6.5. Behold, the mistakes are gone! It is also not a faulty update, because I can with a fresh (blank) 3.7.0 the error can reproduce.
I think the Problem is found on line 242 to 243 in root\components\com_content\views\article\view.html.php of 3.7.0

Link to my site: [www.chem-page.de](https://www.chem-page.de "Chem-Page.de")

![screen shot 2017-05-15 at 13 55 58](https://issues.joomla.org/uploads/1/937f689573186f1699395dc96bd91f1e.jpg)![screen shot 2017-05-15 at 13 55 58](https://issues.joomla.org/uploads/1/46a97366eeedc02e1b36bf9d4f5c20c2.jpg)

**Comment by PhilETaylor** [comment] 2017-05-15 14:34
Is this not a duplicate of #16030

**Comment by mseidl73** [comment] 2017-05-16 09:28
Possible. The Problem is locatet in the same file.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16029">issues.joomla.org/tracker/joomla-cms/16029</a>.</sub>

**Comment by ghost** [comment] 2017-07-21 11:39
closed as duplicated Report of #16030 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16029">issues.joomla.org/tracker/joomla-cms/16029</a>.</sub>

**Closed by ghost** 2017-07-21 11:39 UTC
Labels: No Code Attached Yet
