### ISSUE TITLE
Parse error: syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM) in plugins\system\languagefilter\languagefilter.php on line 630

### ISSUE THREAD

**Issue by jsubri** [joomla/joomla-cms#19267] opened 2018-01-03 10:23 UTC
### Steps to reproduce the issue

Staging (3.8.4-dev )with Multilingual Associations

### Expected result
No error message

### Actual result
Can't login, site broken

### System information (as much as possible)
3.8.4-dev 

### Additional comments
modified line 630 
from: $query = $this->app::getRouter()->parse($uri);
to: $query = $this->app->getRouter()->parse($uri);

**Comment by ghost** [comment] 2018-01-03 10:29
Can't confirm. Login works as expected.
### System information
 3.8.4-dev
Multilanguage Site (4 Lang.) & Test English (GB) Sample Data
macOS Sierra, 10.12.6
Firefox 57 (64-bit)
#### MAMP 4.2
- Apache-Server
- PHP 7.0.22
- MySQLi 5.6.35<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19267">issues.joomla.org/tracker/joomla-cms/19267</a>.</sub>

**Comment by infograf768** [comment] 2018-01-03 10:36
It's weird though...
@csthomas 
please look. It comes from
https://github.com/joomla/joomla-cms/pull/19099

**Comment by jsubri** [comment] 2018-01-03 10:38
You need to have "System - Language Filter" enabled to reproduce the error

**Comment by csthomas** [comment] 2018-01-03 10:38
Yes, older php has a problem with that. I start to work on PR

**Comment by joomdonation** [comment] 2018-01-03 11:11
Honestly, I was scared when I saw #19099 merged. Haven't looked much as it but it seems it change existing behavior (you even need to change tests to have tests passed). There was also change in the to language filter plugin which seems not received code review yet, so to be safe, maybe it should go to 3.9.0 instead of to 3.8.4.

**Comment by csthomas** [comment] 2018-01-03 11:18
Please test PR #19268

**Comment by csthomas** [comment] 2018-01-03 11:28
The php code is not correctly parsed by php5:
`$this->app::getRouter()->parse($uri);`
so I changed it to:
```
$app = $this->app;
$app::getRouter()->parse($uri);
```
and now should be OK.

I tested:

```
<?php
        //Enter your code here, enjoy!

class O {
    public $a = null;
    
    function __construct($a) { $this->a = $a;}
    
    function printz() {
        //$this->a::getB()->printz(); // THIS IS NOT PARSED CORECTLY ON PHP 5
        $a = $this->a;
        $a::getB()->printz();
    }
}

class B {
    public function printz() { echo 'OK'; }
}

class A {
    public static function getB() { return new B(); }
}


$o = new O(new A());
$o->printz();
```
at http://sandbox.onlinephpfunctions.com/ on php 5.3 with success.
```

**Comment by brianteeman** [comment] 2018-01-03 11:31
(nite that this error message is only untranslated in PHP <5.5

**Comment by csthomas** [comment] 2018-01-03 12:31
> Fix do not trigger the T_PAAMAYIM_NEKUDOTAYIM anymore on my php 5.6.26 however PR #19268 breaks (B/C) URLs like /index.php/fr/component/content/article/alias123?catid=13 that were working fine on 3.8.3 with modern routing.

@jsubri I moved it to this place. 

The issue is that the link (without its own menu item) with removed IDs on the modern routing returns a  404 error is old and I have nothing to do with it yet:) At now it is only visible.

Yes, PR #19099 changed a way how build is a SEF link now. Early, it was hidden, joomla used Itemid from previous page or home page `Itemid`. Now everything is clearer.

If no menu assigned (to itself or parents) then `/index.php/component/...`, simple rule.

**Comment by csthomas** [comment] 2018-01-03 12:34
If the biggest problem is that this generates 404 then I will add a fix for that. 

Then mentioned link
`/index.php/fr/component/content/article/alias123?catid=13` will be looking like
`/index.php/fr/component/content/article/category13alias/alias123` or depending of the hierarchy
`/index.php/fr/component/content/article/parent-category/category13alias/alias123`

**Comment by csthomas** [comment] 2018-01-03 20:58
I prepared a PR #19280 that fix issue with error 404 for links like `/index.php/fr/component/content/article/alias123?catid=13`

**Comment by Quy** [comment] 2018-01-03 21:44
See PR #19280<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19267">issues.joomla.org/tracker/joomla-cms/19267</a>.</sub>

**Closed as completed by Quy** 2018-01-03 21:44 UTC
Labels: No Code Attached Yet
