### ISSUE TITLE
filter_category_id not working when creating an admin menu link to only list articles of a certain category

### ISSUE THREAD

**Issue by marschland** [joomla/joomla-cms#44305] opened 2024-10-18 10:56 UTC
### Steps to reproduce the issue
Create a menu item in the admin area to only list articles of a certain category chosen in the filter tab which results in a link like this: index.php?option=com_content&view=articles&filter_category_id=1

### Expected result
A list of articles from only the chosen category.

### Actual result
A list of all articles unfiltered.

### System information (as much as possible)
Joomla 5.2.0 fresh install, upgraded from latest J4.

### Additional comments
If I use the filter options in the article listing everything works fine. But when it should filter from a filter provided via URL nothing changes. The set filter from the article list does not change, no matter which URL I use to change the listing.

**Comment by brianteeman** [comment] 2024-10-18 11:19
Please try
administrator/index.php?option=com_content&view=articles&filter[category_id]=1

**Comment by marschland** [comment] 2024-10-18 11:33
Thank you, this is working as expected. 

But: That should be the case when creating a link through the menu item's interface. Now I would have to manually enter every link as a system link and provide the ID of each category by hand. Since the site has around 30 categories whose articles need to be edited by the user, I would have to create 30 system links by hand entering each category ID by hand as well.

It would be great if the filter option could be fixed to create a functional link again.

Thank you again for the quick solution so we can keep working on the project.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44305">issues.joomla.org/tracker/joomla-cms/44305</a>.</sub>

**Comment by brianteeman** [comment] 2024-10-18 11:40
Ah I see what you mean now. 

I can confirm that the the links generated by Joomla when creating an admin menu item do not work correctly any more.

**Comment by brianteeman** [comment] 2024-11-03 18:50
This was caused by the changes made by  @hackwar in #43230 in administrator/components/com_content/src/Model/ArticlesModel.php

@hackwar I can do a PR to revert that change but maybe thats too much. I'd appreciate it if you could take a look. Basically this admin menu can be created with various filters all of which dont work without the code you removed. This is the only admin menu type impacted as none opf the others have a filter option

![Image](https://github.com/user-attachments/assets/f431d564-3d71-4172-acb5-d73155bd292e)

**Comment by webgras** [comment] 2024-11-05 13:28
I have the some problem on a client site. I set the filter, but in the article list, the filter is ignored.
![Image](https://github.com/user-attachments/assets/2cc97431-1691-4e3d-b0d5-4820539efa7a)

**Comment by hytsch** [comment] 2024-11-08 09:20
Too bad this bug was not fixed with 5.2.1. As long as the bug persists, we have to stay with 5.1 and can't use the nice new features of 5.2 ;(

**Comment by brianteeman** [comment] 2024-11-08 09:35
@webgras I can fix it easily by reverting the mentioned pr by @hannes but wanted to wait for his response first

**Comment by Kubik-Rubik** [comment] 2024-11-08 10:15
We only need to add the allowed filters back. I can create a PR for it.

**Comment by brianteeman** [comment] 2024-11-08 10:19
> We only need to add the allowed filters back. I can create a PR for it.

obviously

**Comment by Kubik-Rubik** [comment] 2024-11-08 10:34
PR: https://github.com/joomla/joomla-cms/pull/44426

**Comment by richard67** [comment] 2024-11-08 10:54
Closing as having a pull request. Please test #44426 . Thanks in advance.

**Closed as completed by richard67** 2024-11-08 10:54 UTC
Labels: No Code Attached Yet, bug
