### ISSUE TITLE
[4.0]  [Autum] [A11y] [Contrast] menu

### ISSUE THREAD

**Issue by angieradtke** [joomla/joomla-cms#33614] opened 2021-05-07 06:24 UTC
### Steps to reproduce the issue
![menu](https://user-images.githubusercontent.com/1172403/117406262-1f548300-af0d-11eb-95da-7ddbd95d1c2b.png)

Not  enough contrast 

### Expected result
WCAG 2.0 level AA requires a contrast ratio of at least 4.5:1 for normal text and 3:1 for large text. WCAG 2.1 requires a contrast ratio of at least 3:1 for graphics and user interface components (such as form input borders). WCAG Level AAA requires a contrast ratio of at least 7:1 for normal text and 4.5:1 for large text.
@ciar4n

**Comment by brianteeman** [comment] 2021-05-07 06:36
Duplicate of #33580

**Comment by angieradtke** [comment] 2021-05-07 06:40
@brianteeman you are always faster .-)

**Comment by alikon** [comment] 2021-05-07 06:48
let's continue on  #33580

**Closed as completed by alikon** 2021-05-07 06:48 UTC
Labels: No Code Attached Yet
