### ISSUE TITLE
The system is also accepting .txt file in Image upload section of Articles.

### ISSUE THREAD

**Issue by apurvaduduskar** [joomla/joomla-cms#4771] opened 2014-10-17 12:22 UTC
#### Steps to reproduce the issue
1. Go to Contents -> Article Manager -> Add Articles.
2. Click on Image button.
3. In the Upload file section, click on Choose file.
4. Select a text file.
5. Click on Start upload.
6. Verify the result.

#### Expected result
The system should display a validation message and the file should not be uploaded.

#### Actual result
The system is display a confirmation message and the file is uploaded.

#### System information (as much as possible)
PHP Built On Windows NT 6.2 build 9200
Database Version 5.6.12-log
Database Collation utf8_general_ci
PHP Version 5.4.12
Web Server Apache/2.4.4 (Win64) PHP/5.4.12
WebServer to PHP Interface apache2handler
Joomla! Version Joomla! 3.3.7-dev Development [ Ember ] 01-October-2014 02:00 GMT
Joomla! Platform Version Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent Mozilla/5.0 (Windows NT 6.1; rv:32.0) Gecko/20100101 Firefox/32.0![screen shot 2014-10-17 at 07 22 35](http://issues.joomla.org/uploads/1/bc968925e60ded338d19f7599b9c3a67.jpg)

**Comment by kolvar** [comment] 2015-03-14 12:00
First of, to disallow txt-upload, both have to be removed, the txt-entry in the "Legal Extension (File Types)"-field and the text/plain entry in the "Legal MIME Types"-field.
Second: As far as I could see, there is no context-evaluation in the upload-method that would stop the code from uploading something else than the legal extenstions. Therefore it could be argued, that this is not a bug but simply not implemented. 
Third: When I set the permissions for the given user in the media-options on "Access Administration Interface" => denied and "Create" => allowed, the behaviour seems to be the one intendet in this case (allowing only images)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4771">issues.joomla.org/joomla-cms/4771</a>.</sub>

**Comment by brianteeman** [comment] 2016-03-12 10:46
I know its been a while but I am going to close this as expected behaviour. There are several slideshow type extensions which use this ability to add a text file that defines the slideshow. If we added txt to the list of files that can be uploaded then we break those extensions. 

As stated above if you want to disable txt file upload on your own site then the functionality exists for you to do that.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4771">issues.joomla.org/joomla-cms/4771</a>.</sub>

**Closed** 2016-03-12 10:47 UTC
Labels: No Code Attached Yet
