### ISSUE TITLE
Latest News Module Ignores Global Settings

### ISSUE THREAD

**Issue by jawill** [joomla/joomla-cms#5166] opened 2014-11-22 18:23 UTC
#### Steps to reproduce the issue
If Author, Created Date and Start Date are set to 'Hide' in Global Settings and set to 'Use Article Settings' in the menu item, they are still displayed with the article when the article settings are set to 'Use Global' and the article is accessed through the 'Latest News' module link. If the menu setting is changed to 'Use Global' instead of 'Use Article Setting', the items are hidden when accessing the article through the 'Latest News' module link.

When the category blog article is accessed directly (without going through the Latest News module link), author and the dates are hidden (even when the menu setting is set to 'Use Article Setting'.) 

#### Expected result

Global settings to be used by Latest News Module

#### Actual result

Global settings ignored by Latest News Module

#### System information (as much as possible)

This happens both in the template I am using (TKUltra) and with the included Beez template in the latest 3.x version.

**Comment by n9iels** [comment] 2015-10-10 15:07
Seems like this issue is fixed now. Would you like to confirm this by trying to reproduce your issue for the latest version of Joomla!

**Comment by jawill** [comment] 2015-10-10 19:53
I was use the third party Latest Article Enhanced Module so I had to 
activate the core Latest Article module again on my test system to check 
this.

The first image (articleheader.gif) shows what the header looks like if 
you go to the page (category blog) that the article appears on.  
Everything here looks as expected.  Created date is set to Show in the 
article options and everything else is set to Global.  In Global options 
these items (author and other dates) are all set to Hide.  In the menu 
item, Author and all of the dates are set to Use Article Settings.

The second image (latest article.gif) shows the Latest Article Module.  
When I select this article from the list, it appears like the way you 
see it in the third image.

The third image (articleheaderfromlatest.gif) shows what the article 
header looks like when it is displayed from the Latest Article Module.  
Even though the menu is set to Use Article Settings, the article 
settings are set to Global, and Global is set to Hide. Author displays.

Since I am using a warp based template, I checked this functionality out 
on the protostar template and the fourth image shows the results there.  
The extra information still displays.

One more related problem, the same things happens if you do a Read More 
with Global set to Hide, menu set to Use Article Settings, and the 
article set to Use Global--author and the extra dates set to Use Global 
(which is Hide) still display.

If you have further questions, let me know.

Jim

**Comment by n9iels** [comment] 2015-10-11 10:10
Unless it seems like something went wrong with uploading the screenshot, I tried to reproduce your issue. It made the following steps:

1) Create a latest new module and let is display articles of an category
2) Create a menu item of the type "Category Blog" what shows articles from the same category. On the option tab, I set the following parameters:
![knipsel](https://cloud.githubusercontent.com/assets/2659866/10416264/3414e0f6-7010-11e5-87af-2b20015f5fb5.PNG)
3) I made a article, assign it to the category and set all parameters to use global
4) On the global configuration of the Article manager, I set the following parameters:
![knipsel](https://cloud.githubusercontent.com/assets/2659866/10416269/7c3fa258-7010-11e5-9f5b-ab3d29ac01c9.PNG)

The heading in my article blog looks like this:
![knipsel](https://cloud.githubusercontent.com/assets/2659866/10416270/9bd0a216-7010-11e5-9b5f-08259df1e7ce.PNG)

When I click on the link of the latest new module, the heading is exactly the same and the author is not shown. So unfortunately I can not reproduce your issue.

Are these the right steps to reproduce the issue on your website? If yes, I'm afraid the issue is on your side. Maybe someone on the Joomla! form (http://forum.joomla.org) can help you with a solution.
If not, please tell me witch step I missed :)

**Comment by jawill** [comment] 2015-10-11 11:23
It looks like you are following the exact same steps I did with 
different results.  I will ask in the forum if anyone else gets the same 
results I do.

Jim

**Comment by n9iels** [comment] 2015-10-11 11:31
@zero-24 can you close this issue?
@jawill I hope you will find your answer there. If there are more people with the same problem, feel free to re-op this issue or create a new one

**Comment by zero-24** [comment] 2015-10-11 13:15
Done @n9iels

**Closed** 2015-10-11 13:15 UTC
Labels: No Code Attached Yet
