### ISSUE TITLE
Error: 0 - Class "JRequest" not found when I switched to Joomla 4

### ISSUE THREAD

**Issue by bubi739** [joomla/joomla-cms#41933] opened 2023-09-26 10:12 UTC
Hello, I have the error on my website "Error: 0 - Class "JRequest" not found" when I switched to Joomla 4 and I think it is due to the index.php code:

defined('_JEXEC') or die;
// A code to show the offline.php page for the demo
if (JRequest::getCmd("tmpl", "index") == "offline") {
if (is_file(JPATH_ROOT . "/templates/" . $this->template . "/offline.php")) {
require_once(JPATH_ROOT . "/templates/" . $this->template . "/offline.php");
} else {
if (is_file(JPATH_ROOT . "/templates/system/offline.php")) {
require_once(JPATH_ROOT . "/templates/system/offline.php");
}
}
} else {
// Include Variables
include_once(JPATH_ROOT . "/templates/" . $this->template . '/icetools/vars.php');
?>

Can you help me??  Thanks.

**Comment by Fedik** [comment] 2023-09-26 10:26
Change your
`JRequest::getCmd("tmpl", "index") == "offline"`
to 
`Joomla\CMS\Factory::getApplication()->getInput()->get('tmpl') === 'offline'`

For more help you always can ask on Joomla forum https://forum.joomla.org/

I closing the issue as it is not a bug.

**Closed as completed by Fedik** 2023-09-26 10:26 UTC
Labels: No Code Attached Yet

**Comment by bubi739** [comment] 2023-09-26 10:31
> Change your `JRequest::getCmd("tmpl", "index") == "offline"` to `Joomla\CMS\Factory::getApplication()->getInput()->get('tmpl') === 'offline'`
> 
> For more help you always can ask on Joomla forum https://forum.joomla.org/
> 
> I closing the issue as it is not a bug.

Thank so much!!!!!
