### ISSUE TITLE
Article: Start Featured doesn't work

### ISSUE THREAD

**Issue by hytsch** [joomla/joomla-cms#44578] opened 2024-12-03 20:44 UTC
### Steps to reproduce the issue
Enter a date in the Start Featured field in a published article. Save the article
### Expected result
The date value is saved.
### Actual result
The date value is not saved.

### System information (as much as possible)
j5.2

### Additional comments
By the way, this works with the Finish Publishing field.

**Comment by brianteeman** [comment] 2024-12-03 21:10
duplicate issue

You have to mark the article as featured first

**Comment by richard67** [comment] 2024-12-03 22:43
@hytsch Do you really think it is helpful if you post the same issue again and again, ignoring any explanations how it works and that your expectation is wrong?

See #43816 , #43467 , #43595 .

Closing as duplicate report.

**Closed as completed by richard67** 2024-12-03 22:43 UTC
Labels: No Code Attached Yet

**Comment by HLeithner** [comment] 2024-12-04 07:17
@hytsch I can't replicate your issue, saving works without issues.

![Image](https://github.com/user-attachments/assets/25598a78-00e3-47ce-a08a-04a29c3655b9)

is your site an updated site? it's possible that a database update failed and please check your database table #__content_frontpage that the 2 columns `feature_up` and `feature_down` exists

![Image](https://github.com/user-attachments/assets/03ab93e4-b0fc-45fc-94a7-081e696ac535)

Also please stop creating duplicated reports for an issue, in this case as it's not a bug please contact the forum for help.

**Comment by hytsch** [comment] 2024-12-04 07:30
Thank you, Harald, for your check and advice. I don't know what the problem is yet. (The workflow is certainly to blame for my problem, which was also a misunderstanding because I couldn't understand how it works, even with the best will in the world.) Now I've tested the function again on a fresh J5.2.2: The start feature date is not retained.

![Image](https://github.com/user-attachments/assets/00b7021f-e834-4394-9c60-463747b1d2be)
![Image](https://github.com/user-attachments/assets/42da0b3f-f47f-46a2-90be-e0fbf67728eb)
![Image](https://github.com/user-attachments/assets/3a248b1d-4aa1-4454-ae41-41c905ced74b)
![Image](https://github.com/user-attachments/assets/f9d8a638-f9a8-43a5-bcb9-8070976e065c)
