### ISSUE TITLE
Blank pages in Joomla 3.7 when System - Page Cache is activated

### ISSUE THREAD

**Issue by madesign** [joomla/joomla-cms#15691] opened 2017-04-30 07:41 UTC
I noticed on several of my Joomla projects that in Joomla 3.7. the active Page Cache plugin leads to a blank page.
Installations are using php 7.1.

Michael Anlauf

Photography
Design
Web
SEO
HD Video documental

Berlin
Germany

Skype: madesign
http://www.tucfoto.com

**Comment by wojsmol** [comment] 2017-04-30 07:58
@csthomas Please see if this shoud be fixed by https://github.com/joomla/joomla-cms/pull/15592

**Comment by madesign** [comment] 2017-04-30 08:33
Sorry, i do not understand quit well what i have to do to fix the issue.

**Comment by franz-wohlkoenig** [comment] 2017-04-30 08:50
@csthomas have written a Pull request and @wojsmol is asking him if his PR solve your Issue.

**Comment by madesign** [comment] 2017-04-30 08:56
If i do this i receive this error.
[](http://fuse.linatango.com)

**Comment by alikon** [comment] 2017-04-30 08:59
the fix will be delivered in the next joomla update

**Comment by madesign** [comment] 2017-04-30 09:01
Thank you! Special for the fast response.

**Comment by wojsmol** [comment] 2017-04-30 09:07
@alikon Thi case os solved by https://github.com/joomla/joomla-cms/pull/15592 or other PR?

**Comment by madesign** [comment] 2017-04-30 09:10
as @alikon wrote "the fix will be delivered in the next joomla update"

**Comment by alikon** [comment] 2017-04-30 09:14
@wojsmol to be honest i'm not sure if #15592 and/or other's ...  cause the issue was not so clear
@madesign all merged pull request  will be delivered in the next release ;)

**Comment by madesign** [comment] 2017-04-30 09:19
Well deactivating the the page cache plugin resolves the problem until Joomla will be updated.

**Comment by franz-wohlkoenig** [comment] 2017-04-30 09:20
@madesign please let Issue open until @csthomas answered if his PR solve this Issue too or another PR must be written.

**Comment by madesign** [comment] 2017-04-30 09:23
Ok i will.
So far i have only one site where the error not appear. http://www.cafetindelsur.de php 7.1.2
Tell me if you like to have any info about my configurations.

**Comment by richard67** [comment] 2017-04-30 09:33
This issue here is a duplicate to #15674 . And there it was confirmed that #15592 solves the problem.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15691">issues.joomla.org/tracker/joomla-cms/15691</a>.</sub>

**Comment by madesign** [comment] 2017-04-30 09:40
As i said, when i delete the storage file i receive an error message. Unable to load storage file. Or do i misunderstand something?

**Comment by richard67** [comment] 2017-04-30 09:47
@madesign Replace file libraries/joomla/cache/storage/file.php in your Joomla 3.7.0 by the one from #15592 , then clear browser cache and test again. The problem should be solved. With the 3.7.1 release coming sooner or later, this file will overvwritten then by the version from the release, which also will contain the corrections of #15592 because that is already committed. You can download that file by going to [https://github.com/joomla/joomla-cms/pull/15592/files](https://github.com/joomla/joomla-cms/pull/15592/files) m click the "View" button beside the link to this file, and then in the single file view click the "Raw" button to see the file as it is without any GitHub stuff. Then you save the page in your browser, then you upload this file to the desired path libraries/joomla/cache/storage/file.php.

**Comment by madesign** [comment] 2017-04-30 09:58
Perfect! Thank you so much.

**Comment by richard67** [comment] 2017-04-30 09:59
@madesign Can you test if it works and report the result back here?

**Comment by madesign** [comment] 2017-04-30 10:03
I tested it here on my "playground" site http://fuse.linatango.com with Page Cache plugin activated.
PHP 7.1.2
Joomla! 3.7.0 Stable
The file resolves so far the issue.

**Comment by richard67** [comment] 2017-04-30 10:08
@madesign Btw. I am not sure if it is a good idea to post your phone number as frankly as you did in the desciption of this issue here. There are bots in web collecting numbers and selling them to aggressive marketing guys or even criminals, so don't be surprised when you get many phone calls by people who want to tell you you have won a million in a game which you never joined, but before you get the million you have to send some 50 000 bucks to an account in nigeria or so ;-)

**Comment by richard67** [comment] 2017-04-30 10:12
@madesign Ah, and if the problem is really solved you can close this issue here.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15691">issues.joomla.org/tracker/joomla-cms/15691</a>.</sub>

**Comment by madesign** [comment] 2017-04-30 10:14
The number is for years public on my website. I got 2 or 3 times a call from some foreign companies. Was more amusing then dangerous but thank's for warning.
Yes it resolves the problem. Only i had to copy the content of the site instead of downloading. But maybe a Safari issue.

Thank's a lot for the really fast help here.

**Comment by madesign** [comment] 2017-04-30 10:34
I replaced on all sites where i noticed the problem the cache file and it resolves on all sites the Page Cache Plugin problem!

**Comment by richard67** [comment] 2017-04-30 11:00
@franz-wohlkoenig Can you close this issue here? It is resolved, see discussion above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15691">issues.joomla.org/tracker/joomla-cms/15691</a>.</sub>

**Comment by franz-wohlkoenig** [comment] 2017-04-30 11:01
closed as Issue resolved.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15691">issues.joomla.org/tracker/joomla-cms/15691</a>.</sub>

**Closed by franz-wohlkoenig** 2017-04-30 11:01 UTC
Labels: No Code Attached Yet

**Comment by madesign** [comment] 2017-04-30 13:09
Thank you all for the help!
