### ISSUE TITLE
Filter Type select list not working in Extension Manager

### ISSUE THREAD

**Issue by ManfredHuebner** [joomla/joomla-cms#21035] opened 2018-07-10 13:45 UTC
### Steps to reproduce the issue
Go to Extension Manager. The dropdown list for extension types is not visible, instead a text field without functionality.

### Expected result
I should be able to select all extensions by extension type

### Actual result
A textbox without functionality is displayed

**Comment by mbabker** [comment] 2018-07-10 13:46
Duplicate of #20881

**Closed as completed by mbabker** 2018-07-10 13:46 UTC
Labels: No Code Attached Yet
