### ISSUE TITLE
Error on field types text after update to 3.5.1

### ISSUE THREAD

**Issue by vinespie** [joomla/joomla-cms#10390] opened 2016-05-10 16:18 UTC
#### Steps to reproduce the issue

You must install two websites to compare databases.

Site 1
1) Install joomla version 3.4.8
2) Update via the Joomla! Update component in 3.5.1

Site 2
1) Install joomla version 3.5.1

#### Expected result

Database need to be the same on site 1 and site 2.
For example in table #__banners, type field 'description' must be 'TEXT' in site 1 and site 2.

#### Actual result

Site 1
Table #__banners, type field 'description' is 'MEDIUMTEXT'

Site 2
Table #__banners, type field 'description' is 'TEXT'

#### Additional comments

Probably due to the convertion to utf8mb4, which changes the type of fields in mysql.

Same problems on other table's fields :
#__banners.description
#__banners.metakey
#__banners.params
#__banner_clients.extrainfo
......

**Comment by andrepereiradasilva** [comment] 2016-05-10 16:45
@richard67 is this expected?

**Comment by richard67** [comment] 2016-05-10 16:55
@vinespie @andrepereiradasilva 

This is expected behavior.

When converting character set of text type columns from utf8 to utf8mb4 with updating a pre-3.5.0 to 3.5.0 or later, MySQL automatically performs an extension of these columns to the next larger type, e.g. TINYTEXT becomes TEXT, TEXT becomes MEDIUMTEXT and so on as far as possible.

This should not be surpressed because otherwise data could be lost.

When I discussed this with maintainers and experts when I fixed utf8mb4 conversion things, we decided not to go the way to provide 2 separate joomla.sql scripts for new installation on MySQL with the 2 different charsets, which would have been necessary to have consistence between new installated and updated database for both character sets. We decided instead to go the way with little impact on existing stuff.

@vinespie Please close this issue here as expected behavior.

Or you or someone else try to solve this non trivial problem by making a pull request and proposing the necessary code changes.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10390">issues.joomla.org/joomla-cms/10390</a>.</sub>

**Comment by zero-24** [comment] 2016-05-10 17:15
Set to "closed" on behalf of @zero-24 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10390">issues.joomla.org/joomla-cms/10390</a>

**Comment by zero-24** [comment] 2016-05-10 17:15
Closing as `expected behavior` for the reasons above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10390">issues.joomla.org/joomla-cms/10390</a>.</sub>

**Closed by zero-24** 2016-05-10 17:15 UTC

**Comment by vinespie** [comment] 2016-05-10 17:19
Ok thank you for explanations @richard67
