### ISSUE TITLE
[4.0Alpha] Table Options starts open

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18607] opened 2017-11-17 19:52 UTC
### Steps to reproduce the issue

go to /administrator/index.php?option=com_menus&view=items&menutype=mainmenu

### Expected result

Table Options is closed on page load

![screen shot 2017-11-17 at 19 51 28](https://user-images.githubusercontent.com/400092/32966142-bc06da5a-cbd0-11e7-89c9-d25cf0dffb89.png)

### Actual result

![screen shot 2017-11-17 at 19 51 15](https://user-images.githubusercontent.com/400092/32966128-afc5122a-cbd0-11e7-98d1-384b9a8d561d.png)

### further bug

When you close the table options you get a deprecated JS warning 

`Offsets separated by white space(s) are deprecated, use a comma (,) instead.` from popper.js

**Comment by brianteeman** [comment] 2017-11-17 22:05
Closed as a duplicate of #16346

**Closed as completed by brianteeman** 2017-11-17 22:05 UTC
Labels: No Code Attached Yet
