### ISSUE TITLE
[j3.7.3] Calendar field reset value on the second click

### ISSUE THREAD

**Issue by fuscage** [joomla/joomla-cms#17176] opened 2017-07-19 08:28 UTC
### Steps to reproduce the issue

1) Create a new content (article). 
2) Go to the "Publication" tab and click to the calendar button (Startpublish) and select a date (exemple 01/07/2017)
3) **Click again** on this calendar button (Startpublish) and the value 01/07/2017 is replaced by today...

### Expected result

When I click again on  the calendar button that's not replace the value 01/07/2017 by today

### Actual result

Replace the value 01/07/2017 by today

### System information (as much as possible)

Joomla 3.7.3

**Comment by brianteeman** [comment] 2017-07-19 08:39
I can confirm this but it looks to be a duplicate report of #17171

**Comment by dgrammatiko** [comment] 2017-08-08 19:36
This should be fixed by https://github.com/joomla/joomla-cms/pull/17183

**Comment by Quy** [comment] 2017-08-28 13:08
Unable to reproduce with nightly staging.

**Comment by ghost** [comment] 2017-08-28 13:24
isn't this Issue similaer to #17741?

**Comment by Quy** [comment] 2017-08-28 13:33
I don't think so going by the steps to reproduce.

**Comment by Quy** [comment] 2017-08-28 13:39
I just installed/tested in v3.7.3 and unable to reproduce the issue.

**Comment by ghost** [comment] 2017-08-28 14:28
closed as looks like beeing solved. Can always be reopened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17176">issues.joomla.org/tracker/joomla-cms/17176</a>.</sub>

**Closed as completed by ghost** 2017-08-28 14:28 UTC
Labels: No Code Attached Yet
