### ISSUE TITLE
[3.8.0] Atom feeds no longer work

### ISSUE THREAD

**Issue by rpbikker** [joomla/joomla-cms#18108] opened 2017-09-25 15:29 UTC
### Steps to reproduce the issue
Download an atom link from a Joomla 3.8.0 website. 

### Expected result
An "application/atom+xml" document

### Actual result
Error 500 with text "class Joomla\CMS\Document\Renderer\Feed\JText not found".

### System information (as much as possible)
Joomla 3.8.0, Purity III v 1.20, T3 v 2.6.7, running on Centos 7.4, Apache 2.4.8, PHP 7.1.9.

### Additional comments
I think I found a little mistake in the file libraries/src/Document/Renderer/Feed/AtomRenderer.php. After comparing this file to RssRenderer.php in the same directory, I changed "JText" to "\JText" on lines 68 and 72. This made the atom feeds work for me.

Please review this. I'm not a PHP developer.

**Comment by mbabker** [comment] 2017-09-25 15:30
Duplicate of https://github.com/joomla/joomla-cms/pull/18102 (and already fixed by it)

**Closed as completed by mbabker** 2017-09-25 15:30 UTC
Labels: No Code Attached Yet

**Comment by rpbikker** [comment] 2017-09-25 15:48
l
Bee2reej3Chu
