### ISSUE TITLE
Tags - A-Z Sorting Subtags assignment not correct

### ISSUE THREAD

**Issue by cvogl87** [joomla/joomla-cms#27961] opened 2020-02-17 11:02 UTC
Hi,
if I have my tags sorted A-Z via Column "title" the assignment of the subcategories is not correct anymore.
Joomla Version 3.9.15

**Comment by alikon** [comment] 2020-02-17 19:00
sorry didn't get you
please can you add more infos and/or some screenshots
thanks

**Comment by cvogl87** [comment] 2020-02-18 08:58
Right assignment Subtags to maintags (See Main Tag "Entsorgung" and its 4 Subtags)
![grafik](https://user-images.githubusercontent.com/61145178/74719785-fb881d00-5234-11ea-8bb8-b1edf68effed.png)

After A-Z Title Sorting Subtags of "Entsorgung" are assigned to different other Main Tags
![grafik](https://user-images.githubusercontent.com/61145178/74719854-18bceb80-5235-11ea-8ab3-a9128482c470.png)

**Comment by richard67** [comment] 2020-02-18 13:24
So it seems when sorting by ordering, all is correct, and when sorting by title, they are sorted by title regardless of parent tag.

This mignt be intended behavior, but I agree it is at leastconfusing as e.g. the "- Papiermüll" tag looks as if it was was a child of "Kurse /Workshops / Seminare" when sorting by the title.

@alikon Do you know who is our tag expert who can say if it is intended behavior or not?

**Comment by cvogl87** [comment] 2020-02-18 13:29
Yeah its pretty much confusing.

**Comment by brianteeman** [comment] 2020-02-18 13:48
Does the same thing happen with any other nested list eg categories or menu items

**Comment by cvogl87** [comment] 2020-02-18 14:53
It seems to be the only problem with tags.

**Comment by brianteeman** [comment] 2020-02-18 15:12
actually just checked with categories - same bug

**Comment by richard67** [comment] 2020-02-18 15:18
Is it really a bug? I mean it does what it says: It sorts by the title.

**Comment by cvogl87** [comment] 2020-02-18 15:32
To me its a bug thats harming the usability

**Comment by jwaisner** [comment] 2020-02-24 16:18
@alikon Is the expected behavior or is this truly a bug?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27961">issues.joomla.org/tracker/joomla-cms/27961</a>.</sub>

**Comment by alikon** [comment] 2020-02-24 16:39
For me is not a bug cause the sort is made simply on the title field , and it is like this on the other tables based on the nested set tree
but it's my opinion

**Comment by jwaisner** [comment] 2020-02-24 17:11
I would agree as well. It is doing what it was intended to do. Closing issue as "Expected Behavior"

**Closed as completed by jwaisner** 2020-02-24 17:11 UTC
Labels: No Code Attached Yet

**Comment by richard67** [comment] 2020-02-24 17:31
Agree, too.
