### ISSUE TITLE
User form field type; user not selected if search is performed in pop-up.

### ISSUE THREAD

**Issue by cjcliffe** [joomla/joomla-cms#13306] opened 2016-12-20 15:47 UTC
### Steps to reproduce the issue

1. Open an administrator form that has a User form field on it (i.e. User Notes)
2. Type a user name or keyword into the search box and submit
3. Click one of the resulting users; the dialog is dismissed

### Expected result

The user selected in the pop-up should populate the user form field.

### Actual result

Nothing happens; the form field is left empty and it's necessary to click again (without searching) and select the user.

### System information (as much as possible)

Does not appear browser or system dependent; is happening on multiple development and live systems running with various configurations on the latest Joomla release.

### Additional comments

Is a minor annoyance among our customers but would be nice to get resolved; opening the dialog a second time at least keeps the previous search filter.

**Comment by franz-wohlkoenig** [comment] 2017-02-01 15:04
Searching a User in "user Notes" got a list of Notes for User. Maybe i don't understand your issue, can you please explain?
#### Test on:
Joomla! 3.7.0-staging
macOS Sierra, 10.12.3
Firefox 50.1.0
PHP 7.0.4
MySQLi 5.5.53-0

**Comment by atgbcn** [comment] 2017-02-02 09:51
I've discovered the same problem.

1. Go to Admin, create a new contact (/index.php?option=com_contact&view=contact&layout=edit)
2. click on linked user and a modal dialog appears
3. use the search box to find any user
4. click on any of the users of the obtained list
5. the modal dialog closes and the linked user continues empty
6. click again and now select (no text search) any of the listed users
7. linked user appears now in the field.

Every time you perform a search the first user selection is ignored.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13306">issues.joomla.org/tracker/joomla-cms/13306</a>.</sub>

**Comment by franz-wohlkoenig** [comment] 2017-02-04 07:43
@atgbcn cannot confirm Issue: Tested like written Steps 1 to 5: Modal Dialog closes and User is set in `Linked user`.

#### Test on:
Joomla! 3.7.0-beta1
macOS Sierra, 10.12.3
Firefox 50.1.0
PHP 7.0.4
MySQLi 5.5.53-0

**Comment by atgbcn** [comment] 2017-02-04 09:12
@franz-wohlkoenig my test was done using windows-10 and chrome at my job's computer.

At home I'm testing using

Joomla! 3.6.5 Stable [ Noether ] 1-December-2016 22:46 GMT
macOS Sierra, 10.12.2
Google Chrome 55.0.2883.95 (64-bit)
PHP 5.6.21
MySQL 5.5.52-cll

and it appears the same problem.

I've also tested the issue using 
Firefox 51.0.1 (64-bit)
macOS Sierra, 10.12.2

and it behaves correctly.

I remember testing the issue on windows and Firefox and the problem appeared too.

I'll send you the exact versions of the windows browsers on Monday.

Thanks!

**Comment by franz-wohlkoenig** [comment] 2017-02-04 09:27
#### Test on:

Joomla! 3.7.0-beta1
Windows Server 2008 (remote)
Firefox 47.0.2
Internet Explorer 11
PHP 7.0.4
MySQLi 5.5.53-0

---

Works: Modal Dialog closed, User set in `Linked user`.

**Comment by atgbcn** [comment] 2017-02-04 10:59
@franz-wohlkoenig maybe Joomla! 3.7.0-beta1 has that issue fixed. I'm running the last stable version Joomla! 3.6.5 Stable [ Noether ] 1-December-2016 22:46 GMT

Anyway, I'll send you the windows browser's specs on Monday.

Thanks!

**Comment by atgbcn** [comment] 2017-02-06 10:52
Good morning @franz-wohlkoenig 

I'm running **Windows 10.0.10586** at my office.

I've updated my browsers but I still can reproduce the issue using

**Google Chrome 56.0.2924.87 (64-bit)
IE 11.713.10586.0**

This browser works as expected
**Firefox 51.0.1 (64-bit)**

Thanks!

**Comment by franz-wohlkoenig** [comment] 2017-02-06 11:13
@atgbcn there are more Issues depending on OS and/or Browser > seems this too.

**Comment by alagesanbe08** [comment] 2017-02-13 05:28
hi i have same issue in Google chrome, i find solution for this.

This issue occur because of mootools check.

"index.php?option=com_users&view=users&layout=modal&tmpl=component&required=0&field={field-user-id}&ismoo=0&excluded=WyIiXQ=="

this is request url for user model popup.

input parameter ismoo = 0
administrator/components/com_users/views/users/tmpl/modal.php:
Line No: 39
$isMoo      = $input->getInt('ismoo', 1);//default value of ismoo=1

when search user, form will submit but form search it did't pass ismoo variable so it take default variable ismoo=1.

so solution is

administrator/components/com_users/views/users/tmpl/modal.php:
add following line to form 
<input type="hidden" name="ismoo" value="<?php echo $isMoo; ?>" />
 That it , now its working in Google chrome.


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13306">issues.joomla.org/tracker/joomla-cms/13306</a>.</sub>

**Comment by alagesanbe08** [comment] 2017-02-13 05:31
# \<input type="hidden" name="ismoo" value="<?php echo $isMoo; ?>" /><hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13306">issues.joomla.org/tracker/joomla-cms/13306</a>.</sub>

**Comment by alagesanbe08** [comment] 2017-02-13 05:35
hi, i don't know, how to display php code in value. just echo $isMoo; in value field. sorry for 3 reply.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13306">issues.joomla.org/tracker/joomla-cms/13306</a>.</sub>

**Comment by franz-wohlkoenig** [comment] 2017-02-13 06:40
@zero-24 can you have a look on this?

**Comment by joomdonation** [comment] 2017-02-13 07:07
@alagesanbe08 Thanks, nice find. I had the issue on Joomla 3.6.5 with my custom extensions, applied the fix and the issue is sorted

Your proposed fix has included in stagging, so it will be fixed in 3.7.0, see https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_users/views/users/tmpl/modal.php#L126

(The code is a bit ugly, it should just be echo $isMoo instead of calling $input->get again

**Comment by franz-wohlkoenig** [comment] 2017-02-13 08:12
@cjcliffe @atgbcn can you test 3.7 like @joomdonation wrote?

**Comment by zero-24** [comment] 2017-02-13 09:32
@joomdonation I agree with you here is the PR: https://github.com/joomla/joomla-cms/pull/14047 that should fix that problem :smile:

**Closed by zero-24** 2017-02-13 09:32 UTC
Labels: No Code Attached Yet
