### ISSUE TITLE
No input field for Caption param when inserting image

### ISSUE THREAD

**Issue by Sulpher** [joomla/joomla-cms#35538] opened 2021-09-12 12:12 UTC
I go to Articles > edit article. There is an option 'show caption' but no inputbox to edit the value. A user should switch off the editor and edit the caption.
<img width="1228" alt="Снимок экрана 2021-09-12 в 15 07 42" src="https://user-images.githubusercontent.com/3432048/132987056-68bd31c2-680d-4ac2-ba04-8f300e1cc9ed.png">

A little enhancement with an extra field could help...

Joomla 4.0.2

**Comment by brianteeman** [comment] 2021-09-12 14:47
This is directly from tinymce and is by design as the intention is that you will type the caption in the editor and not the popup.

https://www.tiny.cloud/docs/plugins/opensource/image/#image_caption

Nothing Joomla can do to change that but you may want to raise it as an issue with tinymce

**Comment by richard67** [comment] 2021-09-12 14:56
Closing as not an issue with the CMS core.

**Closed as completed by richard67** 2021-09-12 14:56 UTC
Labels: No Code Attached Yet
