### ISSUE TITLE
PHP-Error /libraries/src/Access/Access.php get property 'rules' of non-object

### ISSUE THREAD

**Issue by hsm-berlin** [joomla/joomla-cms#36783] opened 2022-01-22 12:00 UTC
### Steps to reproduce the issue
I get the following php-errors:
[22-Jan-2022 11:04:18 Europe/Berlin] PHP Notice:  Trying to get property 'rules' of non-object in .../www/libraries/src/Access/Access.php on line 548
[22-Jan-2022 11:04:18 Europe/Berlin] PHP Notice:  Undefined offset: 33 in .../www/libraries/src/Access/Access.php on line 553

### System information (as much as possible)
CentOS 8 | PHP 7.4.27 | MariaDB 10.3.28 | Apache 2.4.37 | Joomla 4.0.6
This Joomla-System was updated from 1.5.x --> 2.5 --> 3.x to 4.x

### Additional comments
No idea what is going on here

**Comment by richard67** [comment] 2022-01-22 12:23
@hsm-berlin Could you switch on debug in the global configuration so you can see the complete call stack and report it back? Thanks in advance.

**Comment by hsm-berlin** [comment] 2022-01-22 13:06
@richard67 I will try it, but this is my production website and the error was not generated by myself. But I check the access-log.

**Comment by richard67** [comment] 2022-01-22 13:14
Since when do you get these errors? Have they started to appear after an update? We need more information.

At a first look it seems there has an extension not been uninstalled properly, so assets (i.e. access rules) were remaining for which no extension exists anymore.

**Comment by richard67** [comment] 2022-01-22 13:53
@hsm-berlin Could you test and report back if the changes here solve your issue? https://github.com/joomla/joomla-cms/pull/36786/files

Of course make a backup of the original PHP file before you modify it or replace it by the modified version from my PR, so you can later revert it if necessary.

Thanks in advance.

**Comment by hsm-berlin** [comment] 2022-01-22 16:01
O.K. I was able to find the link that caused the error. It was a menu entry to an article. The link was missing the .html. After I called the link with .html for the first time, the error was no longer displayed. Therefore, unfortunately, I can no longer test it. If I find the error again, I will test the new code.

**Comment by richard67** [comment] 2022-01-22 16:04
@hsm-berlin You always do all works on the life site, not have a copy on a subdomain there for testing or on a local computer with a webserver? That's very courageous. Do you do at least backups of files and database (with or without the help of well known useful products) before updating the CMS or extensions or installing questionable extensions? If not: Would you mind if we call you "danger seeker"? 😄

**Comment by hsm-berlin** [comment] 2022-01-22 16:23
@richard67 I have a test-system on a local server, but that did not produce this error. So what should I do? O course I make daily backups. ;-) Thanks for your work!

**Comment by richard67** [comment] 2022-01-22 16:26
Anyway, closing as having a pull request of which I am convinced it will solve it if it can be reproduced again, see #36786 . Thanks for reporting.

**Closed as completed by richard67** 2022-01-22 16:26 UTC
Labels: No Code Attached Yet
