### ISSUE TITLE
Weird Update proposed after merging #9118

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#9165] opened 2016-02-19 10:45 UTC
https://github.com/joomla/joomla-cms/pull/9118 has broken correct update proposals in Control Panel.
I have a component com_localise which is set as 4.0.13-dev (modified, this is why I do not update to the available 4.0.14-dev).

It now displays also as a Joomla Update.

![screen shot 2016-02-19 at 08 46 45](https://cloud.githubusercontent.com/assets/869724/13169460/faf5b862-d6e5-11e5-8235-634177cbb4be.png)

Clicking on "Update Now" will load the Joomla Update page where, evidently, no update is proposed.
The Extensions:Update page correcty displays the possible update for the component.

I had to clear the Update cache and then click on Find Updates to get rid of this error.
I am afraid that people updating to 3.5.0 would get the same issue. Any possible solution?

**Comment by brianteeman** [comment] 2016-02-19 10:53
This has been the case for a LONG time

On 19 February 2016 at 10:45, infograf768 <notifications@github.com> wrote:

> #9118 <https://github.com/joomla/joomla-cms/pull/9118> has broken correct
> update proposals in Control Panel.
> I have a component com_localise which is set as 4.0.13-dev (modified, this
> is why I do not update to the available 4.0.14-dev).
>
> It now displays also as a Joomla Update.
>
> [image: screen shot 2016-02-19 at 08 46 45]
> <https://cloud.githubusercontent.com/assets/869724/13169460/faf5b862-d6e5-11e5-8235-634177cbb4be.png>
>
> Clicking on "Update Now" will load the Joomla Update page where,
> evidently, no update is proposed.
> The Extensions:Update page correcty displays the possible update for the
> component.
>
> I had to clear the Update cache and then click on Find Updates to get rid
> of this error.
> I am afraid that people updating to 3.5.0 would get the same issue. Any
> possible solution?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9165>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by andrepereiradasilva** [comment] 2016-02-19 10:53
hum strange. It this really related to https://github.com/joomla/joomla-cms/pull/9118?

**Comment by infograf768** [comment] 2016-02-19 10:56
When I reversed #9118 I did not get the issue (that was before I cleared cache and click find updates).
I have another test site where I could not reproduce.

**Comment by brianteeman** [comment] 2016-02-19 11:02
See #6091 and #5931and #3775

On 19 February 2016 at 10:56, infograf768 <notifications@github.com> wrote:

> When I reversed #9118 <https://github.com/joomla/joomla-cms/pull/9118> I
> did not get the issue (that was before I cleared cache and click find
> updates).
> I have another test site where I could not reproduce.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9165#issuecomment-186170485>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by infograf768** [comment] 2016-02-19 11:06
A bit different here, @brianteeman  as the issue is that it proposes in Control Panel a Joomla update with a component version + the normal proposal for that component update which works OK.

**Comment by andrepereiradasilva** [comment] 2016-02-19 11:06
@infograf768 i think i know what is the issue. a line bad placed inside an if.

**Comment by andrepereiradasilva** [comment] 2016-02-19 11:07
i think this line https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_installer/models/update.php#L146 must be placed outside the if (search).

Can you test?

**Comment by infograf768** [comment] 2016-02-19 11:10
Hmm, the problem is that, by clearing cache, the problem disapeared...
I have to find a way to reproduce.

**Comment by brianteeman** [comment] 2016-02-19 11:16
@infograf768 sorry I should have drunk the coffee before replying - i see what you mean now in your screenshot<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9165">issues.joomla.org/joomla-cms/9165</a>.</sub>

**Comment by andrepereiradasilva** [comment] 2016-02-19 11:32
ok, please tell me when you can reproduce it so we can test the patch.

**Comment by infograf768** [comment] 2016-02-19 11:35
@andrepereiradasilva 
By playing and moving this line around, I got, once only, the same issue I described originally.
Now I can't reproduce anymore.
I feel it must have been a cache issue when that line was indeed in the if search.

It makes sense to move it just before `return $query;`

**Comment by andrepereiradasilva** [comment] 2016-02-19 11:36
my patch revert it to exacly like it was.

I will make a PR with the patch.

**Comment by brianteeman** [comment] 2016-02-19 11:38
Closed as we have a patch #9166 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9165">issues.joomla.org/joomla-cms/9165</a>.</sub>

**Comment by andrepereiradasilva** [comment] 2016-02-19 11:38
@infograf768 Please see https://github.com/joomla/joomla-cms/pull/9166 and test agian if you can

I can't test it because i have no way to repproduce it

**Closed** 2016-02-19 11:38 UTC
Labels: 3.5.0-blocker
