### ISSUE TITLE
Bad redirection when using PHP 8.3.13

### ISSUE THREAD

**Issue by uzielweb** [joomla/joomla-cms#44372] opened 2024-10-29 19:10 UTC
### Steps to reproduce the issue

Extract Joomla 5.2.0 and try to install, or change PHP version to 8.3.13 in any project

### Expected result

proceed to installation as usual or load site as usual

### Actual result

bad redirection and stucks in the same page.

### System information (as much as possible)

Laragon with PHP 8.3.13, Mysql 8, Apache 2.4.62

**Comment by Quy** [comment] 2024-10-30 21:18
Unable to reproduce on Apache. Please post to Joomla forum for support. https://forum.joomla.org/

**Comment by uzielweb** [comment] 2024-11-06 22:47
Use Laragon or any other LAMP, MAMP or WAMP.

Steps to reproduce the issue

Extract Joomla 5.2.0 and try to install, or change PHP version to 8.3.13 in any project
Expected result

proceed to installation as usual or load site as usual
Actual result

bad redirection and stucks in the same page.
System information (as much as possible)

Laragon with PHP 8.3.13, Mysql 8, Apache 2.4.62<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44372">issues.joomla.org/tracker/joomla-cms/44372</a>.</sub>

**Comment by Quy** [comment] 2024-11-07 03:04
Thanks for reporting back. Closing as not a core issue.

**Closed as completed by Quy** 2024-11-07 03:04 UTC
Labels: No Code Attached Yet, Information Required
