### ISSUE TITLE
[4.0] Sidebar overflow issue when opening

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#28260] opened 2020-03-07 09:55 UTC
### Steps to reproduce the issue
From closed, open the sidebar menu. Menu items displayed before sidebar is opened. The issue comes from https://github.com/joomla/joomla-cms/pull/27352 which required `overflow:hidden` to be removed from the sidebar.

(gif slowed down to emphasize)

![mVp8Qlxpfc](https://user-images.githubusercontent.com/2803503/76141149-7b95eb80-6059-11ea-8797-7afe60c3ed5f.gif)

**Comment by jwaisner** [comment] 2020-03-08 20:24
Confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28260">issues.joomla.org/tracker/joomla-cms/28260</a>.</sub>

**Comment by Quy** [comment] 2021-05-07 19:10
Please see if PR #33628 is a fix. Thanks.

**Comment by Quy** [comment] 2021-05-29 22:38
Closing since no longer reproducible.

**Closed as completed by Quy** 2021-05-29 22:38 UTC
Labels: No Code Attached Yet, Information Required
