### ISSUE TITLE
Disabled Update Sites Re-enable themselves on checking for udpates

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#13436] opened 2016-12-31 15:29 UTC
### Steps to reproduce the issue

Install Joomla 3.6.5 (and previous versions) 
Install a load of extensions
Admin -> Extensions -> Update Sites -> Select All -> Click Disable
Admin -> Extensions -> Updates -> Clear Cache
Admin -> Extensions -> Updates -> Find Updates

### Expected result

The disabled update sites should NOT BE CHECKED for updates because they are DISABLED
Expect that they remain disabled

### Actual result

The disabled update sites ARE CHECKED for updates and their state is changed to ENABLED

**Comment by zero-24** [comment] 2017-01-01 18:40
Feel free to change: https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_joomlaupdate/models/default.php#L217-L227

**Comment by PhilETaylor** [comment] 2017-01-01 19:15
I rather be a dad for a few days - sorry - raised gh issues to ensure problems were logged in case someone else had time to fix issues

**Comment by zero-24** [comment] 2017-01-01 19:25
As a next version is to be released in ca. two months you have enough time ;)

**Comment by tonypartridge** [comment] 2017-01-03 06:47
Tested on J3.6.5 cannot replicate on both a fresh install and old install. 

@PhilETaylor could this be related to the Akeeba issue where they were disabling/borking updates? Maybe an extension is enabling all update sites on purge?

**Comment by PhilETaylor** [comment] 2017-01-03 10:41
Yeah I cannot replicate it now on clean Joomla versions - but I have seen this on a LOT of sites in the last few months.

I'll do some digging.

I'll ping @nikosdion here in case he wants to drive by and comment if AT or AB do anything.

**Closed** 2017-01-03 10:42 UTC
Labels: No Code Attached Yet

**Comment by nikosdion** [comment] 2017-01-03 10:57
No, none of my software touches _other extensions'_ update sources. Moreover, none of my software does anything when you request to reload the update sites.

As for @tonypartridge's comment: That's *very* low of you people. There was EXACTLY ONE broken version in May 2016, I [owned up to it](https://www.akeebabackup.com/home/news/1666-bug-ab-4-7-0-removed-update-sites.html) and even offered a free tool to fix that - since Joomla was stalling forever the deployment of version 3.6 which contained the core code to do that. So all I get for working without any sleep to fix a problem is this kind of comments seven months later. And then you wonder why I no longer contribute to this project. I won't accept this kind of comments, especially coming from a project which lets grave bugs linger for YEARS without a resolution and turns away developers like me who waste their time to offer a code fix with stupid comments like "I can't test it so it's not an issue". Whatever. Go learn how to make mass distributed software or shut it.

That said, the default behaviour of Joomla's extension updater (at least up to the introduction of the Update Sites manager which was the last time I looked at that code) was to re-enable all update sites every time you _manually_ fetch updates. I don't know if that behaviour was changed at any point.

Finally, my OWN software will enable its OWN update sites when the user accesses the control panel page of my OWN software. This is by design and only because Joomla is a massively broken pile of crap. Whenever a temporary issue (on either end) would prevent the site from accessing the update site Joomla would simply disable the update site *WITHOUT WARNING*. As a result my users were no longer receiving updates and had no idea that Joomla had *unilaterally and without any warning* disabled updates. We'd then end up in a situation where they were either affected by a bug I had fixed months ago or reported compatibility issues with a Joomla version which was a year newer than their copy of Akeeba Backup, both of which would have been non-issues if Joomla wouldn't disable the darned update sites without warning! So maybe fix your shit before you accuse me of killing update sites. In other words, fix the shit you've been doing FOR YEARS, FOR MILLIONS OF SITES, WITHOUT A PROPER RESOLUTION instead of holding against me an issue that affected a few hundred people and which I fixed within less than 48 hours. I'll let everyone reading this be the judge of who treats their users with respect and provides prompt fixes to serious issues.

I am muting this thread. Don't bother replying.

**Comment by tonypartridge** [comment] 2017-01-03 11:04
wow @nikosdion at no point was I ever having a go or making any negative comment against you. I just remember the above post you linked to above and wondered if that issue had anything to do with it. That is all, I didn't know the code in's and out's, that's it. Nor is Joomla! my 'S**T', it's simply a CMS I use and have recently be helping on the open source side. 

Your contributions to Joomla! have always been appreciated from my perspective as little as it is, I really don't think there was such a need for the above post as no one is saying you had done anything wrong and again just wondering if the two issues could have been linked.

You may have muted the thread, but I've replied anyhow.
