### ISSUE TITLE
Archive search does not work properly

### ISSUE THREAD

**Issue by omd123** [joomla/joomla-cms#12053] opened 2016-09-16 19:20 UTC
### Steps to reproduce the issue
I'm running a local newssite on Joomla 3.6.2 and we do encounter the following issue's.

When we use the standard Joomla search and articles from the archive are presented in the results, we get the following 2 results:

- when we click on a link, it presents an other archived article
- when we click on a link, it gives a 404 page

For the normal content the search works good.

**Comment by brianteeman** [comment] 2016-09-16 19:37
If I remember correctly this has been reported before. I believe the fix for 3.6.2 was to create a menu link (can be hidden) to display archived content<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12053">issues.joomla.org/joomla-cms/12053</a>.</sub>

**Comment by franz-wohlkoenig** [comment] 2017-01-31 13:57
@brianteeman: #13757, #11422, #10864, none of them i can confirm on 3.7-staging.

**Comment by wezetel** [comment] 2017-01-31 14:18
@brianteeman : the fix you mention, was for (archived) articles of categories, which haven't had a menu item associated (issue #9566) which has been fixed by AlexRed with PullRequest #10613

The above mentioned issue is the same I reported under #13757 . Sorry, I didn't find this issue on my search, but both are the same. Even franz-wohlkoenig can't confirm they exist (I provided links)

**Comment by franz-wohlkoenig** [comment] 2017-04-05 17:29
closed as Duplicate of #13757 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12053">issues.joomla.org/tracker/joomla-cms/12053</a>.</sub>

**Closed by franz-wohlkoenig** 2017-04-05 17:29 UTC
Labels: No Code Attached Yet
