### ISSUE TITLE
Cache: Warning: stristr(): Empty needle

### ISSUE THREAD

**Issue by 810** [joomla/joomla-cms#6123] opened 2015-02-18 19:39 UTC
Warning: stristr(): Empty needle in C:\wamp\www\joomla\libraries\joomla\document\html\html.php on line 232

Call Stack

1 0.0010 239568 {main}( ) ..\index.php:0 
2 0.1644 3490824 JApplicationCms->execute( ) ..\index.php:40 
3 1.7878 20343224 JApplicationSite->render( ) ..\cms.php:257 
4 1.7884 20343936 JApplicationCms->render( ) ..\site.php:729 
5 2.2918 24031392 JDocumentHTML->render( ) ..\cms.php:1058 
6 2.2919 24031416 JDocumentHTML->_renderTemplate( ) ..\html.php:477 
7 2.2919 24031960 JDocumentHTML->getBuffer( ) ..\html.php:700 
8 2.2989 24131600 JCache::getWorkarounds( ) ..\html.php:390 
9 2.2990 24132280 JDocumentHTML->mergeHeadData( ) ..\cache.php:484 
10 2.2992 24126584 stristr ( ) ..\html.php:232

**Comment by Fedik** [comment] 2015-02-18 19:54
and?
@810 any more info about how to reproduce?

**Comment by 810** [comment] 2015-02-18 20:14
I get the error with progressive cache on. when i click on back icon browser, i get sometimes this error.

**Comment by laoneo** [comment] 2015-10-05 14:37
What would help to provide a fix is a more detailed test instruction how to reproduce the issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6123">issues.joomla.org/joomla-cms/6123</a>.</sub>

**Comment by brianteeman** [comment] 2015-11-12 16:05
As it has been a long time since the original report and no information on how to replicate the issue I am closing this at this time. It can always be re-opened if further information is provided explaining how to replicate the issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6123">issues.joomla.org/joomla-cms/6123</a>.</sub>

**Closed by brianteeman** 2015-11-12 16:05 UTC
Labels: No Code Attached Yet

**Comment by barb11** [comment] 2015-12-13 16:01
I experienced the same warning 
Empty needle in …\libraries\joomla\document\html\html.php on line 232
on 2 of my websites

I guess you could reproduce it too:
- I am using J2store shopping cart extension
- When “Progressive caching" is the warning appears only on the pages where j2store is, I never saw it on regular Joomla pages.
- When I cleaned cache, it disappear for a while, then it was back again
- When I disabled caching, no warning anymore.

I am using Joomla! 3.4.5 and J2Store 3.2.4

**Comment by 810** [comment] 2015-12-13 16:19
looks like from https://github.com/joomla/joomla-cms/blob/99bf07db9711bf3dd1bcb98a164a82fe51467e9d/libraries/joomla/document/html/html.php#L232

**Comment by ridrotex** [comment] 2016-05-06 07:29
Try to include a plug- cache system
