### ISSUE TITLE
Articles created on the fly are locked by default

### ISSUE THREAD

**Issue by mikeveeckmans** [joomla/joomla-cms#14192] opened 2017-02-22 21:32 UTC
### Steps to reproduce the issue
Create new menu item -> single article -> create article -> create an article and save & close -> save and close the menu item -> go to com_content 

### Expected result
Article ready to edit (checked in)

### Actual result
Article locked (cheked out)

### Additional comments
![2017-02-22_22-28-14](https://cloud.githubusercontent.com/assets/4589318/23233305/c2090fb8-f94e-11e6-9a3d-7b7a3aeb11ae.gif)

**Comment by ot2sen** [comment] 2017-02-22 21:42
@test Can not confirm. Articled saved looks fine here. 3.7.0 beta 3

![screen shot 2017-02-22 at 21 42 44](https://issues.joomla.org/uploads/1/3872aab77ca5d691cd5513f7c9e158d1.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14192">issues.joomla.org/tracker/joomla-cms/14192</a>.</sub>

**Comment by mikeveeckmans** [comment] 2017-02-22 21:44
@ot2sen : you're still in com_menu, go to com_content ;-) <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14192">issues.joomla.org/tracker/joomla-cms/14192</a>.</sub>

**Comment by ot2sen** [comment] 2017-02-22 21:49
@mikeveeckmans hah, sorry getting late. Just testing it full, still ok though. See attached
![screen shot 2017-02-22 at 21 49 00](https://issues.joomla.org/uploads/1/1a4721396dfdcc4f3111767d09ba7452.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14192">issues.joomla.org/tracker/joomla-cms/14192</a>.</sub>

**Comment by coolcat-creations** [comment] 2017-02-22 21:51
@ot2sen you have to set your article overview filter to trashed, then go into the menu item, create an article on the fly and it has automaticly the filters that you set in the article overview list. I just tested myself and confirm the issue.

**Comment by coolcat-creations** [comment] 2017-02-22 21:58
@ot2sen 
- I just tested in Chrome and it worked.
- I tested in Firefox an can reproduce the issue

so in one of these two browsers it´s wrong ;)

**Comment by ot2sen** [comment] 2017-02-22 22:02
Tested using ie11 in this case. Worked.
Let me try see if I can break it in other browsers :)

**Comment by ot2sen** [comment] 2017-02-22 22:05
FF freshly updated. Confirm it get locked
![22-02-2017_ff_locked](https://cloud.githubusercontent.com/assets/790445/23234772/773ccda8-f953-11e6-9fbe-91626cfb1d9d.png)

**Comment by ot2sen** [comment] 2017-02-22 22:14
FF Developer Edition freshly update. Now locked again. Looks like FF engine making some trouble...
![22-02-2017_ffdev_locked](https://cloud.githubusercontent.com/assets/790445/23235132/9c333b32-f954-11e6-84e2-759a1046a675.png)

**Comment by ot2sen** [comment] 2017-02-22 22:16
Finally Chrome, now ok again :)
![22-02-2017_chrome_ok](https://cloud.githubusercontent.com/assets/790445/23235224/fd672b84-f954-11e6-8498-b068f5b8f466.png)

**Comment by ot2sen** [comment] 2017-02-24 13:38
Same in FF for alphas and former betas too.
@andrepereiradasilva perhaps you can see where FF goes wrong here when you know this feature so well? :)

**Comment by franz-wohlkoenig** [comment] 2017-03-02 13:25
This should be solved before Release.

**Comment by Fedik** [comment] 2017-03-12 14:44
please test #14537

**Comment by ot2sen** [comment] 2017-03-12 14:59
Confirmed @Fedik this solved the issue here too for having a lock when using FF. After your #14537 patch this get solved here :)

**Comment by zero-24** [comment] 2017-03-12 16:14
Thanks for the patch @Fedik I'm closing this Issue than 😄

**Closed by zero-24** 2017-03-12 16:14 UTC
Labels: No Code Attached Yet
