### ISSUE TITLE
force language in localize.xml doesn't work

### ISSUE THREAD

**Issue by arrowthemes** [joomla/joomla-cms#11538] opened 2016-08-10 07:27 UTC
#### Steps to reproduce the issue
Unpack a new Joomla Installation
Before running the installation, open installation/localize.xml and set the following on line 3:

`<forceLang>ar-AA</forceLang>`

Run the installation

#### Expected result
The installation should run with the language of choice in <forceLang>

#### Actual result
The installation show your default Language

**Comment by brianteeman** [comment] 2016-08-10 08:42
I just tested it with ar-AA, fr-FR, de-DE and all worked correctly

**Comment by brianteeman** [comment] 2016-08-23 19:48
I am closing this as this time as not a bug. It can always be reopened if further information is provided to show otherwise

**Closed by brianteeman** 2016-08-23 19:48 UTC
Labels: No Code Attached Yet
