### ISSUE TITLE
[4.0] Strange options dropdowns behaviour when in modal

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20497] opened 2018-05-19 21:29 UTC
### Steps to reproduce the issue

Attempt to insert a ARTICLE using the CMS Content dropdown in the editor in admin when editing a **CUSTOM MODULE** 

Click on the options button filter

### Expected result

All dropdowns look good with placeholders

When I select something, I can then use x to remove that something

### Actual result

Some dropdowns missing placeholders/style
Cannot click x on a previously selected filter

![screen recording 2018-05-19 at 10 27 pm](https://user-images.githubusercontent.com/400092/40273194-d455f866-5bb3-11e8-9b8f-43d79b781ff8.gif)

### System information (as much as possible)
79fd949
google chrome

**Comment by dgrammatiko** [comment] 2018-05-19 21:33
I guess this bug exists in 3.x as well

**Comment by PhilETaylor** [comment] 2018-05-19 21:35
> I guess this bug exists in 3.x as well

No.

<img width="1642" alt="screen shot 2018-05-19 at 22 35 02" src="https://user-images.githubusercontent.com/400092/40273257-e83488e2-5bb4-11e8-88e2-f660066afdaa.png">

**Comment by Quy** [comment] 2018-05-30 03:53
I consider this to be a duplicate of #19882 but displayed in the modal.

**Comment by Quy** [comment] 2018-06-05 20:42
Duplicate of #19882, but in modal. Fix in chosen.js will display the placeholders in both places.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20497">issues.joomla.org/tracker/joomla-cms/20497</a>.</sub>

**Closed as completed by Quy** 2018-06-05 20:42 UTC
Labels: No Code Attached Yet, J4 Issue
