### ISSUE TITLE
[4.0] table options

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#17110] opened 2017-07-13 13:36 UTC
The new table options is not working correctly on the menus component

@ciar4n 
<img width="846" alt="screenshotr14-36-19" src="https://user-images.githubusercontent.com/1296369/28168946-a72d552a-67d8-11e7-87df-717d445785df.png">

**Comment by ghost** [comment] 2017-07-13 14:38
Issue confirmed.

**Comment by ciar4n** [comment] 2017-07-13 15:24
Style wise this should be now resolved since  #17097...

![com-menus](https://user-images.githubusercontent.com/2803503/28173750-49bc1016-67e7-11e7-9a42-be33a4fec4b8.png)

There may be an argument for moving the order and list number fields to the Table Options. For some of com_menu views however these are the only 2 fields displayed.

**Comment by C-Lodder** [comment] 2017-07-13 17:31
Can confirm this is still an issue. Also, the "Table Options" button is hidden on mobile.

**Comment by ciar4n** [comment] 2017-07-13 17:54
PR created.. #17117

**Comment by ghost** [comment] 2017-07-13 18:04
closed as having PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17110">issues.joomla.org/tracker/joomla-cms/17110</a>.</sub>

**Closed as completed by ghost** 2017-07-13 18:04 UTC
Labels: No Code Attached Yet
