### ISSUE TITLE
Com-banners is a 503 on PHP8.2

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-cms#40486] opened 2023-04-26 14:45 UTC
### Steps to reproduce the issue
Make sure your site is PHP8.2
Click on components > banners > banners
Click on components > banners > tracks
Click on components > banners > clients

### Expected result
Page loads

### Actual result
503 error.

Please note components > banners > categories loads fine.[systeminfo-2023-04-26T15_45_15+01_00.txt](https://issues.joomla.org/uploads/1/455497a47c7824c7e8c2afdc8f5d8dc7.txt)

**Comment by richard67** [comment] 2023-04-26 14:54
As I can see in your system info, you have debug on (good) but error reporting = default. Could you change error reporting to maximum and check if there is something shown?

**Comment by uglyeoin** [comment] 2023-04-26 15:31
I put it to maximum and I don't see any errors or any debug information.

**Comment by alikon** [comment] 2023-04-27 06:33
unable to replicate on a "clean" 4.3
can you try without extensions ?

**Comment by richard67** [comment] 2023-05-01 14:08
@uglyeoin Does your thumbs up for the previous comment mean that you have successfully tried without 3rd party extensions? Or does it just mean that you have liked the comment? If the issue was caused by a 3rd party extension, please close it, or let us know so we can close it. Thanks in advance.

**Comment by uglyeoin** [comment] 2023-05-01 18:57
I am now not seeing any issues despite being on 8.2 and having done nothing different with extensions.  I can only assume that this was a hosting issue that they have resolved somehow.

**Closed as completed** 2023-05-01 18:57 UTC
Labels: No Code Attached Yet, Information Required

**Comment by uglyeoin** [comment] 2023-05-31 11:27
I can't tell you why this only happened on some com_banners pages, but I believe this may have been a problem with the Engagebox plugin/module/component.

**Comment by woluweb** [comment] 2024-02-14 09:24
Interesting: I have just come across the same problem, ie I had a 503 error page on all com_banners links in the backend.

After investigating a bit I realized that the 503 would only trigger
- if Debug is enabled in Global Configuration
- even if the the "System - Debug" plugin is Disabled

I could reproduce this on the 3 different websites I tested for this:
- Joomla 5.0.2
- PHP 8.2.5
- 10.5.21-MariaDB
- (with or without a *LiteSpeed* server)

(the 3rd one is a test website where I only had 2 extensions installed. I disabled them and still had the same issue)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40486">issues.joomla.org/tracker/joomla-cms/40486</a>.</sub>

**Comment by brianteeman** [comment] 2024-02-14 10:22
If debug is enabled without the plugin you still get all the non minified assets

**Comment by brianteeman** [comment] 2024-02-14 10:24
Also please confirm if it's a litespeed 503 or a joomla 503. If it's the former I have commented elsewhere what to check on your server.

**Comment by uglyeoin** [comment] 2024-02-14 11:07
@brianteeman where can we find the somewhere elsewhere to check?  I use Litespeed server but mine is now working.  I think it may have been firewall related.  Which seems odd, perhaps banners is doing something weird that it didn't like.  It also triggers on the edit overrides page or something.  My host has now added a rule.

**Comment by brianteeman** [comment] 2024-02-14 11:28
Sorry at an airport. It's a setting in litespeed for prams in urls
