### ISSUE TITLE
[com_fields] Contact: Messed Value in "Show User Custom Field"

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#13594] opened 2017-01-15 08:58 UTC
### Steps to reproduce the issue
"Contacts: Edit" > Tab "Display": Field "Show User Custom Field" Text inside Value is messed:
![bildschirmfoto 2017-01-15 um 09 10 46](https://cloud.githubusercontent.com/assets/8235763/21961180/0e477af0-db03-11e6-84ad-ab3b5aee7ec6.JPG)
### System information (as much as possible)
Joomla! 3.7.0-alpha2-nightly
macOS Sierra, 10.12.2
Firefox 50.1.0
PHP 7.0.4
MySQLi 5.5.53-0

**Comment by laoneo** [comment] 2017-01-16 08:02
If you click on it and then release it, the full text is shown. Don't know i this is a bug in the JS library @dgt41, @infograf768 any clue why this can happen.
In the meantime, I created a PR #13607 which fixes that field at all as it is broken.

**Comment by infograf768** [comment] 2017-01-16 10:53
Element style gets a fixed width of 90px.
I get the same error when I create and display a usergroup custom field for any extension.

**Comment by laoneo** [comment] 2017-01-16 12:07
So is this something we can solve?

**Comment by infograf768** [comment] 2017-01-16 17:27
Looked at the js files loaded and did not see any difference.

I could sove it locally by adding 
`min-width: 187px !important;`
in chosen.css
in
```css
.chzn-container-multi .chzn-choices li.search-field input[type="text"] {
  margin: 1px 0;
  padding: 0;
  height: 25px;
  outline: 0;
  border: 0 !important;
  background: transparent !important;
  box-shadow: none;
  color: #999;
  font-size: 100%;
  font-family: sans-serif;
  line-height: normal;
  border-radius: 0;
  min-width: 187px !important;  /// Added here.
}
```
I don't know of any chzn which uses in Joomla a width below 187px.

**Comment by laoneo** [comment] 2017-01-17 06:36
So should we add that rule to the Isis template of what is your suggestion?

**Comment by infograf768** [comment] 2017-01-17 11:00
It certainly would work is we add:
```css
.chzn-container-multi .chzn-choices li.search-field input[type="text"] {
  min-width: 187px !important; 
}
```
in  ROOT/administrator/templates/isis/less/chzn-override.less
and then run generatecss.php cli which will add this in isis both template css files.

But it looks like a hack to me as the issue is likely to be in the implementation of com_fields.
@Bakual @dgt41 
What do you think?

**Comment by Bakual** [comment] 2017-01-17 12:23
I have no clue and it doesn't happen both in Firefox and Chrome her eon my Windows Laptop. So can't comment on it.
The rule certainly looks fishy as always when `!important` is used.

It's certainly not related to com_fields by itself. The formfield in question is a regular list field where only the getOptions method is overriden. The hint is created by `JHtmlFormbehavior::chosen`. So it should happen on each list field with multiple options allowed.

**Comment by gwsdesk** [comment] 2017-03-08 10:59
I experienced this issue as well see https://www.screencast.com/t/dDPWttlRH

**Comment by bertmert** [comment] 2017-03-12 21:23
The reason is that chosen.js calculates the width of the INPUT depending on the width of it's outer container.

https://github.com/joomla/joomla-cms/blob/staging/media/jui/js/chosen.jquery.js#L1340

Because somebody added in template.css of Isis:

```
.control-group .chzn-container {
 width: 100% !important;
 max-width: 220px;
}
```

So: Remove the max-width here and find another selector to limit the width!

I removed the whole CSS block above and the placeholder is no longer truncated.
https://github.com/joomla/joomla-cms/blob/staging/administrator/templates/isis/css/template.css#L7027-L7030

**Comment by bertmert** [comment] 2017-03-12 23:04
The CSS changes have been made here by @ciar4n 
https://github.com/joomla/joomla-cms/pull/13586

**Comment by laoneo** [comment] 2017-03-13 07:12
Unfortunately this pr doesn't solve this issue here, the pr got merged over two months ago and we still have the issue.

**Comment by ciar4n** [comment] 2017-03-13 08:19
Sounds like a very similar issue to https://github.com/joomla/joomla-cms/issues/11835 . Probably related somehow.

**Comment by laoneo** [comment] 2017-03-13 08:46
Guess it is about the same thing.

**Comment by bertmert** [comment] 2017-03-13 09:12
> Unfortunately this pr doesn't solve this issue here, the pr got merged over two months ago and we still have the issue.

I said/meant that PR https://github.com/joomla/joomla-cms/pull/13586 is the reason for misbehavior that we have now!! It must be reverted/corrected/whatever!!

**Comment by laoneo** [comment] 2017-03-13 09:16
Ah ok, tought this PR should solve it. @ciar4n any idea how to fix this one without reverting the behavior in #13586?

**Comment by ciar4n** [comment] 2017-03-13 09:44
I don't think #13586 is causing this as the issue was there for some time before it (#11835).

**Comment by ciar4n** [comment] 2017-03-13 10:00
Just looking in to this. A slightly different issue to #11835. I'll see what I can do but will probably have to revert #13586. Chosen seems to require a set width.

**Comment by laoneo** [comment] 2017-03-13 10:11
Thanks @ciar4n!!

**Closed** 2017-04-02 05:39 UTC
Labels: No Code Attached Yet
