### ISSUE TITLE
Trash icon in trashed items doesn't work as expected

### ISSUE THREAD

**Issue by yannisdran** [joomla/joomla-cms#20258] opened 2018-04-30 08:30 UTC
### Steps to reproduce the issue
1) Trash a published article or category
2) Press 'Search Tool' for selecting status 'Trashed'
3) Press the trash icon left of the item (article or category). Don't select 'empty trash', as this button works as expected.

### Expected result
Item should be trashed for ever

### Actual result
Item returns back to published

### System information (as much as possible)
'1 Article / Category published'

### Additional comments
Haven't tried it with menus, modules or other stuff. Should be checked there as well.

**Comment by brianteeman** [comment] 2018-04-30 08:32
That icon is a status toggle and the tooltip for the icon when in the trashed state says that clicking on it will publish the item

**Comment by infograf768** [comment] 2018-04-30 08:33
"trashed for ever" is not a Joomla concept.
When one hovers the Trash icon, one can see the tip "Publish Item"
![screen shot 2018-04-30 at 10 32 24](https://user-images.githubusercontent.com/869724/39419818-ea75694e-4c61-11e8-8e4f-8e7c5be35966.png)

**Comment by yannisdran** [comment] 2018-04-30 08:56
hmm, right, tooltip says publish item. Then, the icon should be changed for UX purposes, by my humble opinion. It doesn't feel right.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20258">issues.joomla.org/tracker/joomla-cms/20258</a>.</sub>

**Comment by brianteeman** [comment] 2018-04-30 09:05
The icon is indicating the current status - not the action
Just as the green tick indicates the published status

**Comment by infograf768** [comment] 2018-04-30 09:11
I agree though that some of these icons have unexpected actions:
Example: the status with tip `Published but has expired etc.`
When clicking on the icon, it Unpublishes the item. Tip is not an action.

EDIT: Look also the Archived icon which displays the tip `Unpublish item` and not the status. In that case it is the action which is proposed.

**Comment by brianteeman** [comment] 2018-04-30 09:25
@infograf768 we have had several issues and pull requests to change that - all have been ignored

**Comment by brianteeman** [comment] 2018-04-30 09:26
example #16301

**Comment by Bakual** [comment] 2018-04-30 09:54
I'm closing this issue since it's not a bug but in that case the expectation was wrong.

**Closed as completed by Bakual** 2018-04-30 09:54 UTC
Labels: No Code Attached Yet
