### ISSUE TITLE
Joomla 4 Countmodules multiple position not working

### ISSUE THREAD

**Issue by joris85** [joomla/joomla-cms#31569] opened 2020-12-03 16:12 UTC
### Steps to reproduce the issue
/templates/myowntemplate/index.php

php if... ($this->countModules("position1 or position2 or position3")): ?>
<jdoc:include type="modules" name="position1" style="xhtml" />
<jdoc:include type="modules" name="position2" style="xhtml" />
<jdoc:include type="modules" name="position3" style="xhtml" />
en php

### Expected result
Load my module :-)

### Actual result
Nothing is loaded

### System information (as much as possible)
Joomla 4
PHP 7.4

### Additional comments
Documentation on Joomla that describes that it should work:
https://docs.joomla.org/Customising_the_way_modules_are_displayed

**Comment by infograf768** [comment] 2020-12-03 17:07
Try
$this->countModules('position-4') or $this->countModules('position-7') or $this->countModules('position-5')

**Comment by drmenzelit** [comment] 2020-12-03 18:44
<?php if ($this->countModules('position1') || $this->countModules('position2')) : ?>

It is not a bug, it is more a question for the forum. And teh question was posted in Facebook too.

**Comment by chmst** [comment] 2020-12-03 19:31
Closing this as it is not an issue of Joomla.

**Closed as completed by chmst** 2020-12-03 19:31 UTC
Labels: No Code Attached Yet

**Comment by joris85** [comment] 2021-01-26 13:44
Maybe does not looks like a joomla issue but it works in Joomla 3 and not in Joomla 4.
Works in 80 joomla 3 site's :-)
So i can change this on all my sites on the conversion to J4 but i would say it is still a Joomla issue :-)
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31569">issues.joomla.org/tracker/joomla-cms/31569</a>.</sub>

**Comment by joris85** [comment] 2021-01-26 13:45
@chmst <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31569">issues.joomla.org/tracker/joomla-cms/31569</a>.</sub>

**Comment by brianteeman** [comment] 2021-01-26 14:02
Not sure why this was closed as it is a documented method to select the modules

**Comment by Fedik** [comment] 2021-01-26 14:07
It is deprecated feature in Joomla 3
https://github.com/joomla/joomla-cms/blob/648f2f84c7f174e4348c08ddef9dc150ed458f2d/libraries/src/Document/HtmlDocument.php#L595-L597

and removed in Joomla 4.

You have to use what @infograf768 suggest.

**Comment by brianteeman** [comment] 2021-01-26 14:08
Then the documentation needs to be updated and it needs to be added to the faq f deprecated features

**Comment by Fedik** [comment] 2021-01-26 14:09
Yeah, usual problem ;)

**Comment by joris85** [comment] 2021-01-26 18:50
Thanks for the fast support guys!
I will change my code :-)

**Comment by med-rezzouq** [comment] 2022-02-08 14:30
yes actually it is a joomla core issue,
