### ISSUE TITLE
[4.0] Same ID of update servers for language packs

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#35223] opened 2021-08-18 19:09 UTC
### Steps to reproduce the issue

Not sure if this is a problem, but I'll let you know just in case. 

Install stable release 4.0. During installation, select multiple languages (or for example install them later from the list of available language packs). Go to the Update servers page. In my case, ID 2 for all servers for language packs.

It goes without saying that the server is the same, but should it have the same ID in the admin area? 

![Screenshot_1](https://user-images.githubusercontent.com/8440661/129957339-e59ba972-f06e-486c-82ee-f0ee24ffc38c.png)

**UPD**
In Joomla 3 too.

**Comment by richard67** [comment] 2021-08-18 19:57
This is how it works since the beginning of update sites.

The table shows extensions mapped to update sites.

The ID is the one of the update site.

Several extensions can share the same update site.

Official translations all have the same update site.

Closing as expected behaviour.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35223">issues.joomla.org/tracker/joomla-cms/35223</a>.</sub>

**Closed as completed by richard67** 2021-08-18 19:57 UTC
Labels: No Code Attached Yet
