### ISSUE TITLE
Menu association multilanguage switching not working for extension menus - takes you to home menu

### ISSUE THREAD

**Issue by nickanti** [joomla/joomla-cms#7350] opened 2015-07-06 12:17 UTC
#### Steps to reproduce the issue
1. Clean Joomla 4.3.4 install
2. Install and configure multilanguage content
3. Enable item associations in system language plugin
4. Configure menu item associations for an extension (I tested kunena and CB)
5. Try to switch langauges in frontend from an associated menu

#### Expected result
Expected to be taken to associate menu

#### Actual result
Taken to home menu of language instead

#### System information (as much as possible)
Joomla 3.4.3 clean install
PHP Version	5.4.10
Database Version	5.5.29

**Comment by smz** [comment] 2015-07-06 12:52
Sorry for asking, but, have you set "Item Associations" to "Yes" in the "Language Filter" plugin?

**Comment by nickanti** [comment] 2015-07-06 13:00
@smz - Yes I did.
I have updated the description as it seems that switching does not work for menu items pointing to Joomla components.
Tested Kunena and CB<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7350">issues.joomla.org/joomla-cms/7350</a>.</sub>

**Comment by smz** [comment] 2015-07-06 13:15
OK, I suppose you mean "*pointing to* **non** *Joomla components*"...

Will look at this...

In the meanwhile can you please check if you have the same behavior applying #7286?

**Comment by Gitjk** [comment] 2015-07-06 17:13
I can't reproduce that behavior with VirtueMart. All menu associations do work correctly in my case on my bilingual site with Joomla conservative cache enabled.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7350">issues.joomla.org/joomla-cms/7350</a>.</sub>

**Comment by smz** [comment] 2015-07-06 17:18
@Gitjk That makes me fill a little better... :smile: 
I haven't got the time to test with 3rd party extensions, but will definitely do that...

@nickanti: I forgot to mention that if you want to check the behavior with #7286, you should also enable the #7271 patch too (Language Filter)

**Comment by smz** [comment] 2015-07-06 23:20
I made some testing with a local copy of site that uses several different components (*K2 and Ohanah particularly have frontend menu items*).

Original this was a mono-lingual site and I transformed it into a bilingual site with menu items associated.

I couldn't find any problem with Joomla! 3.4.3: all menu items associations do work as expected for all installed components.

I have instead found a problem in my Language Switcher "Code review" (#7286) that unhappily is carried on from a similar modification I did in languagfilter.php. This currently has an impact only in the creation of `rel="alternate"` links, which, for some pages are not created.

As stated above, anyway, no problems with the current Language Switcher and its creation of links for associated menu items.

**Comment by smz** [comment] 2015-07-07 00:27
... and maybe I'm not doing anything wrong: see https://github.com/joomla/joomla-cms/pull/7286#issuecomment-119033207

**Comment by smz** [comment] 2015-07-07 03:49
... and finally, **yes** I was making a mistake.

If you wish #7286 is now a different implementation that should give the same results as the current switcher (*and thus it might be useful to you for checking the behavior with your component*, @nickanti )

**Comment by nickanti** [comment] 2015-07-07 10:46
Update: Seems that issue is in fact due to bad configuration on my part.
I was using a system alias menu item in 2 languages pointing to the same component menu item set to all languages.

I was expecting this to work - but it did not.
I am guessing by design.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7350">issues.joomla.org/joomla-cms/7350</a>.</sub>

**Comment by brianteeman** [comment] 2015-07-07 10:49
Can we close this then?

On 7 July 2015 at 11:46, Nick A. <notifications@github.com> wrote:

> Update: Seems that issue is in fact due to bad configuration on my part.
> I was using a system alias menu item in 2 languages pointing to the same
> component menu item set to all languages.
>
> I was expecting this to work - but it did not.
> I am guessing by design.
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/7350
> <http://issues.joomla.org/tracker/joomla-cms/7350>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/7350#issuecomment-119165690>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by nickanti** [comment] 2015-07-07 10:52
I would say YES Brian.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7350">issues.joomla.org/joomla-cms/7350</a>.</sub>

**Closed** 2015-07-07 10:53 UTC
Labels: No Code Attached Yet

**Comment by smz** [comment] 2015-07-07 10:59
@nickanti No problems! I actually have to thank you as checking for this made me discover a mistake I did in my current PR regarding the language switcher! Talk about serendipity... :smile:
