### ISSUE TITLE
Canonical Links does not use Preferred url

### ISSUE THREAD

**Issue by eSilverStrike** [joomla/joomla-cms#18318] opened 2017-10-12 15:13 UTC
Canonical links have not been working for years now. We need to get this fixed as it is a MAJOR component of SEO. I know this has been discussed before but nothing seems to come of it.

Canonical links should default to preferred URL for the page. All Canonical links seem to do in Joomla for articles and categories is mirror the URL the user visited for the page. The preferred url for the page should be the menu url of the page (or one based on the category if it has a menu item and the article does not). This should be based on the one the Joomle SEF plugin outputs.

For example Google Search  once again has been finding weird urls for my articles like

www.example.com/component/content/article?id=103:article-alias

I have no idea how it was found but that is beside a point. I have a menu item for this article. The url for this menu item should be used for the canonical link, it is not so now Google has 2 copies of the same page but from 2 different urls. (for example the link through the menu for the article is something like www.example.com/menu-alias/article-alias)

We need a fix for this as soon as possible as it has been hurting a lot of Joomla sites.

**Comment by ggppdk** [comment] 2017-10-15 04:29
I have made a PR

I confirm the issue, but i am not sure how common this issue is
since these links usually are not be generated
because the menu items are already been created before website is published

of course there are other cases like this,
like an article SEF url that uses category menu item, and then an article menu item is created
again you have 2 URLs for the same article that define no rel canonical

**Comment by ghost** [comment] 2017-10-15 05:51
closed as having Pull Request #18341

**Closed as completed** 2017-10-15 05:50 UTC
Labels: No Code Attached Yet

**Comment by ghost** [comment] 2017-10-15 05:51
@eSilverStrike please Test #18341

**Comment by eSilverStrike** [comment] 2017-10-15 15:32
Many thanks for looking into this issue but I don't think I have things working correctly on my end since I applied patches #18341 and #18260 to the Joomla 3.8.1 release and didn't see any changes to the canonical link for the article. 

I have a menu item (only 1) pointing to a page. I then visited the page using a different URL as described above and the canonical link still didn't use the menu item url as the link.

> I confirm the issue, but i am not sure how common this issue is since these links usually are not be generated because the menu items are already been created before website is published

I am not sure how google found these links as I have triple checked my site and I don't see it being produce anywhere. That being said Joomla does return the same page for different urls so a canonical (that all points to the same url) should be used so the page is defined as only one url by Google.

Once example I can see this happening is if someone initially had the Joomla SEF plugin disabled and then decided to enable it a later date. If no 301 redirects are setup then Google would have a duplicate content issue as it can always  access the content both ways. A canonical here pointing to the correct url would help this situation.

Links can also be found by Google from other sites pointing back to the Joomla site. Sometimes these links on the other site are incorrect even though they may produce in the end the correct page. A canonical here pointing back to the url used by the menu would help Google determine if it is a duplicate content issue or not.

**Comment by ggppdk** [comment] 2017-10-15 15:40
You mean that you have looked at the html source of the pages ?
`www.example.com/component/content/article?id=103:article-alias`
`www.example.com/menu-alias/article-alias`

which value does rel canonical have for each of them ? (i mean after appling PR 18341)

**Comment by ggppdk** [comment] 2017-10-15 15:51
For all
http://localhost/devel/joomla-cms2/article-category-list/item/72-popular-tags.html
http://localhost/devel/joomla-cms2/component/content/article?id=72:popular-tags
http://localhost/devel/joomla-cms2/popular-tags.html

I get rel canonical
```html
<link href="/devel/joomla-cms2/popular-tags.html" rel="canonical" />
```

**Comment by ggppdk** [comment] 2017-10-15 15:52
Please post your tests at the PR #18341 , not here, as the issue is now closed
