### ISSUE TITLE
[jcomm]

### ISSUE THREAD

**Issue by carollynnb** [joomla/joomla-cms#30978] opened 2020-10-07 06:48 UTC
Good Morning,

I am trying to update my Joomla sites, but some of my sites keeps giving me the following message which I don't know how to fix:

**Joomla\CMS\Filesystem\Folder::create: Infinite loop detected.
File Checksum Failed**

![Joomla Update](https://user-images.githubusercontent.com/72488825/95296725-93488300-0879-11eb-955a-8c7e49b38324.PNG)

Would you mind assisting me with steps is how to fix this problem please? I am using Xneelo for my hosting. 

Kind Regards
Carol-Lynn Burbidge

**Comment by HLeithner** [comment] 2020-10-07 07:18
Hello @carollynnb 

did this happend the first time or also for updates before 3.9.22? Did you retry the update? Did you try to install the update manually with the update file https://github.com/joomla/joomla-cms/releases/download/3.9.22/Joomla_3.9.22-Stable-Update_Package.zip ?

please report back if this worked for you

**Comment by zero-24** [comment] 2020-10-07 07:23
File checksum faild message means that the download is broken. Installing it manually as suggested should be a workaround.

**Comment by carollynnb** [comment] 2020-10-07 08:49
![image](https://user-images.githubusercontent.com/72488825/95308869-b891bd00-088a-11eb-9f49-548649919c19.png)

**Comment by HLeithner** [comment] 2020-10-07 08:56
What is you current installed version?

**Comment by carollynnb** [comment] 2020-10-07 08:58
Joomla! Version | Joomla! 3.9.5 Stable [ Amani ] 9-April-2019 15:00 GMT
-- | --
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

**Comment by HLeithner** [comment] 2020-10-07 09:06
Csn you try to update to any other version plz. Because it seems something is wrong on your hoster. I only want to be sure that it is not 3.9.22.

**Comment by carollynnb** [comment] 2020-10-07 09:15
When I try to update my extensions... It gives me the same message.

**Comment by HLeithner** [comment] 2020-10-07 10:09
Then please contact your provider and check if there are any errors in the logs

**Comment by jwaisner** [comment] 2020-10-07 14:49
Closing as this is not a bug. Please look to the forums for additional assistance if your hosting company cannot assist.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30978">issues.joomla.org/tracker/joomla-cms/30978</a>.</sub>

**Closed as completed** 2020-10-07 14:49 UTC
Labels: No Code Attached Yet
