### ISSUE TITLE
Custom field of type list creation doesn't work properly

### ISSUE THREAD

**Issue by primalinchen** [joomla/joomla-cms#18237] opened 2017-10-04 18:42 UTC
### Steps to reproduce the issue

After Update to Joomla 3.8.1 i've created new custom field of type list in the existing fieldgroup.
Then i've added some list items to this custom field and saved the new custom field.

Then i've opened an existing Article (where the fieldgroup was accessed to).

The new custom field was shown there, but from the list was only last item to see.
Even if this one item was choosen, at save processing there was an error.

**Comment by brianteeman** [comment] 2017-10-04 23:10
and what was the error

**Comment by primalinchen** [comment] 2017-10-05 07:10
The error is, that although in custom field a lot of list-items are created, in the article they are not displayed.
There is only the last of created list-items to see. And even this one can not be selected. The article can not be saved.
It comes error: "Select the list item".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18237">issues.joomla.org/tracker/joomla-cms/18237</a>.</sub>

**Comment by tonypartridge** [comment] 2017-10-05 07:12
Can you provide a screenshot of the created field and the field options?

**Comment by primalinchen** [comment] 2017-10-05 07:48
Of course!![screen shot 2017-10-05 at 07 47 34](https://issues.joomla.org/uploads/1/e115b2972b98b868b2f05aa171c88ebf.png)![screen shot 2017-10-05 at 07 47 34](https://issues.joomla.org/uploads/1/c51dcc7a7a5e5943b55deefc90ca3767.png)![screen shot 2017-10-05 at 07 47 34](https://issues.joomla.org/uploads/1/218d7a9ed57ce7422ca60ff7e3eef7cf.png)![screen shot 2017-10-05 at 07 47 34](https://issues.joomla.org/uploads/1/e0cacc81162389e3b447d7418091175f.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18237">issues.joomla.org/tracker/joomla-cms/18237</a>.</sub>

**Comment by brianteeman** [comment] 2017-10-05 08:56
The problem is that you dont have any values you only have text

A list field must have both values and text

The html specification allows you to have ONE text without a value - example "please select"

**Comment by primalinchen** [comment] 2017-10-05 10:41
Perfect! It works!
But now comes the second question: how can i output the dates from the value field in frontend?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18237">issues.joomla.org/tracker/joomla-cms/18237</a>.</sub>

**Comment by ghost** [comment] 2017-10-05 11:20
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.

**Closed as completed** 2017-10-05 11:20 UTC
Labels: No Code Attached Yet
