### ISSUE TITLE
Menu item type 'Category list' does not show articles with a passed 'end publication' date

### ISSUE THREAD

**Issue by OrlandoLasso** [joomla/joomla-cms#41162] opened 2023-07-14 16:30 UTC
### Steps to reproduce the issue
1. Create a menu item type 'Category list' for a specific Category/language of articles. Assign to a front end user with sufficient authorities to all aspects involved.
2. Put in that category an article status published or unpublished, with an end publishing date in the past.
3. Log in to front end and select this menu item.

### Expected result
The category list should show all articles: published and unpublished. Also those articles that were published in the past using the parameters 'start publishing' and 'end publishing' date, regardless of the fact that the 'end publishing' date has passed meanwhile and the article is no longer visible on the site for visitors.

### Actual result
The category list does not show those articles that have specified an 'end publishing' date in the past, regardless of all other elements/parameters.

### System information (as much as possible)
I think it is a global issue. I tested on Joomla 4.2.9, 4.3.2 and 4.3.3.

### Additional comments
I verified the issue with several regular front end users who has all required authorities and in a setup being used since years for editing and publishing articles in front end. 
Same issue with a super user. So it is not a matter of authorities or access rights.
I can reproduce the issue as often as I want: create a new article, publish it or not=> it shows up in the front end category list.
Except when I fill in the 'End publishing' date with a date in the past=> article desappears from the category list. 
When I remove the 'End publishing' date or put in a later date then today, is it shown again. Regardless of it's status 'published' or 'not published'.

**Comment by brianteeman** [comment] 2023-07-14 16:42
> Same issue with a super user. So it is not a matter of authorities or access rights.

![image](https://github.com/joomla/joomla-cms/assets/1296369/d33cbdf6-403c-4eb1-8e73-a91a93854990)

**Comment by brianteeman** [comment] 2023-07-14 16:44
![image](https://github.com/joomla/joomla-cms/assets/1296369/1ddc7d42-6c95-4fb7-ab7c-e1a9afd2ab77)

Is this the setting you have or did I misunderstand something?

**Comment by OrlandoLasso** [comment] 2023-07-14 16:59
Exactly! Start pubishing date can be in the past or today, or now, doesn't seem to have an impact.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41162">issues.joomla.org/tracker/joomla-cms/41162</a>.</sub>

**Comment by brianteeman** [comment] 2023-07-14 17:12
So if it works for me and it doesnt work for you what is the difference.

**Comment by OrlandoLasso** [comment] 2023-07-14 17:27
Authorities...
Now that I know what is the element that causes the article to show up or not in the list, I tested again with the same user, giving him additionally group 'superuser' or not (as normal). Without superuser, the article is not shown when the end publish date is in the past, with superuser it is shown when the end publish date is in the past.
Without an end publish date, the article is shown, regardless of having superuser or not (tested that again with the same article same category same language same front end user same menu item, status published and not published)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41162">issues.joomla.org/tracker/joomla-cms/41162</a>.</sub>

**Comment by brianteeman** [comment] 2023-07-14 17:29
so this statement was not correct in your original report?

> Same issue with a super user. So it is not a matter of authorities or access rights.

**Comment by brianteeman** [comment] 2023-07-14 17:34
You must have edit permissions to see the unpublished and expired content

**Comment by OrlandoLasso** [comment] 2023-07-14 18:13
You are right :-(
When I give my test user additionally 'editor' user group, he can see also the expired content (regardless of it being published or not)
When I take away again the 'editor' user group, he can only see:
the published articles without 'end publish' date or with an 'end publish' date in the future.
the unpublished articles, without an 'end publish' date or with an end publish date in the future.
he can no longer see the articles, published or not, whith an 'end publish' date in the past.

In my setup, users in the front end can see all articles in the corresponding category of the menu item 'category list', but they have only edit rights to the articles of the category they are authorised too. So in all categories, this menu item shows them only the published articles, in the category they are authorised for, they see also the unpublished articles. Exept those that have an 'end publish' date in the past.
That seems not correct to me. So I assume I am missing an authority. Yet I don't see any difference in authorities between the one article I am using to test with expiration date in the past (red in the screen shot) and the 2 other unpublished articles without expiration date:
![screen shot 2023-07-14 at 18 10 09](https://issues.joomla.org/uploads/1/c1b62a0d73165e2761ead662302ed1dc.jpg)
or any difference with all the other articles in the category he is authorised to edit, regardless of status published or unpublished.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41162">issues.joomla.org/tracker/joomla-cms/41162</a>.</sub>

**Comment by brianteeman** [comment] 2023-07-14 18:52
Sorry I can't help you further here. The problem is clearly a configuration problem and the forum (https://forum.joomla.org) is the best place to resolve this

**Comment by OrlandoLasso** [comment] 2023-07-14 18:55
OK, thank you very much for your time anyway!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41162">issues.joomla.org/tracker/joomla-cms/41162</a>.</sub>

**Comment by obuisard** [comment] 2023-07-14 19:19
Thank you for your report @OrlandoLasso and thank you to Brian @brianteeman to address this issue and help resolving it.

**Closed as completed by obuisard** 2023-07-14 19:19 UTC
Labels: No Code Attached Yet
