### ISSUE TITLE
Protostar: Html broken on login view  with IE11

### ISSUE THREAD

**Issue by 810** [joomla/joomla-cms#9894] opened 2016-04-13 12:14 UTC
#### Steps to reproduce the issue

go to: component/users/?view=login

#### Expected result

correct html (menu should be on the right)

#### Actual result

![proto](https://cloud.githubusercontent.com/assets/876623/14492781/e4d6282a-0181-11e6-9104-6ae1c3bce6ea.jpg)

#### System information (as much as possible)

Stage build

**Comment by brianteeman** [comment] 2016-04-13 12:17
I just took this screenshot of current staging
![screen shot 2016-04-13 at 07 17 45](https://issues.joomla.org/uploads/1/baf849b50f8ba2149f747d7ae0c38a90.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9894">issues.joomla.org/joomla-cms/9894</a>.</sub>

**Comment by MATsxm** [comment] 2016-04-13 12:22
like @brianteeman 
no problems here

**Comment by brianteeman** [comment] 2016-04-13 12:24
At a guess I would think its something either in your install or coming
from kunena which I dont have installed thats causing the problem

On 13 April 2016 at 13:22, Marc-Antoine Thevenet <notifications@github.com>
wrote:

> like @brianteeman <https://github.com/brianteeman>
> no problems here
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9894#issuecomment-209403093>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by 810** [comment] 2016-04-13 12:45
clean stage build
add .httaccess

change global setting:
Search Engine Friendly URS  = yes
Use URL Rewriting = yes
Adds Suffix to URL = no
Unicode Aliases =yes

![proto2](https://cloud.githubusercontent.com/assets/876623/14493551/497f898e-0186-11e6-9f4e-3fcaea459d1d.jpg)

**Comment by brianteeman** [comment] 2016-04-13 12:55
Double checked my sef settings and they are the same

On 13 April 2016 at 13:45, Jelle Kok <notifications@github.com> wrote:

> clean stage build
> add .httaccess
>
> change global setting:
> Search Engine Friendly URS = yes
> Use URL Rewriting = yes
> Adds Suffix to URL = no
> Unicode Aliases =yes
>
> [image: proto2]
> <https://cloud.githubusercontent.com/assets/876623/14493551/497f898e-0186-11e6-9f4e-3fcaea459d1d.jpg>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9894#issuecomment-209412314>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by 810** [comment] 2016-04-13 13:05
ok just found out its only on ie11

**Comment by Bakual** [comment] 2016-04-13 13:06
Can replicate it with IE11.

**Comment by 810** [comment] 2016-04-13 13:07
the aside is in the main div

**Comment by Bakual** [comment] 2016-04-13 13:12
Probably related to https://github.com/joomla/joomla-cms/pull/9607
The default_login layout is the cause.

**Comment by Bakual** [comment] 2016-04-13 13:15
The `if` clauses in https://github.com/matrikular/joomla-cms/blob/staging/components/com_users/views/login/tmpl/default_login.php#L23 should match the one in https://github.com/matrikular/joomla-cms/blob/staging/components/com_users/views/login/tmpl/default_login.php#L35

Now, we got one true and the other false when there is no description text. If you add some text, all works fine.

**Comment by 810** [comment] 2016-04-13 13:20
will send a fix

**Comment by brianteeman** [comment] 2016-04-13 13:21
Glad you found it. Sorry I dont have IE

On 13 April 2016 at 14:15, Thomas Hunziker <notifications@github.com> wrote:

> The if clauses in
> https://github.com/matrikular/joomla-cms/blob/staging/components/com_users/views/login/tmpl/default_login.php#L23
> should match the one in
> https://github.com/matrikular/joomla-cms/blob/staging/components/com_users/views/login/tmpl/default_login.php#L35
>
> Now, we got one true and the other false when there is no description
> text. If you add some text, all works fine.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9894#issuecomment-209434921>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment] 2016-04-13 13:21
[updated title]<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9894">issues.joomla.org/joomla-cms/9894</a>.</sub>

**Comment by brianteeman** [comment] 2016-04-13 14:13
Closed as we have a PR for testing #9896<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9894">issues.joomla.org/joomla-cms/9894</a>.</sub>

**Closed** 2016-04-13 14:14 UTC
