### ISSUE TITLE
Selectbox options (chzn-container) not clickable on android tablets

### ISSUE THREAD

**Issue by n9iels** [joomla/joomla-cms#25522] opened 2019-07-11 14:06 UTC
### Steps to reproduce the issue
1. Use an Android tablet with the latest version of Google Chrome
2. Find a selectbox in the admin interface (for example the filters on the articles page)
3. Try to select an option

### Expected result
The option is selected

### Actual result
The option is not clickable or extremely difficult to select.

### System information (as much as possible)
Joomla! 3.9.10
Android 9.0.0
Google Chrome 75.0.3770.101

### Additional comments
The select boxes are working fine on an iPad with the latest version of iOS. There is also no problem on mobile phones since for the mobile layout the native HTML selectbox is used.

**Comment by brianteeman** [comment] 2019-07-12 10:14
I suspect that it wont be fixable as the chzn library sucks - but can you confirm which version of android

**Comment by n9iels** [comment] 2019-07-12 10:53
Oeps I'm sorry. The tablet is running Android 9.0.0 and Google Chrome 75.0.3770.101 (latest version available in the Play Store as we speak).

I'm afraid that fixing this is indeed a big pain in the ass... Just displaying the native `select` elements on Android tablets might be an option? I have also no idea how this is working in J4, or if we are using that chzn library in that version. If we can't fix it for J3, at least we can try to fix it for J4.

**Comment by brianteeman** [comment] 2019-07-12 10:57
we are not using chzn in j4 

there is also a known issue with that version of chromium which was discovered a few days ago which I suspect might be the cause. That will be fixed in chrome 77

**Comment by Quy** [comment] 2019-12-11 22:51
OK to close?

**Comment by n9iels** [comment] 2019-12-12 16:42
No. I can still reproduce this bug in chrome `78.0.3904.108`.

**Comment by brianteeman** [comment] 2022-01-31 23:08
@zero-24 is there any point in keeping this open. Shouldnt it just be closed as a _known issue cant fix_

**Comment by brianteeman** [comment] 2022-07-24 07:51
This should be closed

**Comment by Fedik** [comment] 2022-07-25 09:46
I closing it, it wont be fixed in 3x, and it is chosen.js bug anyway

**Closed as completed by Fedik** 2022-07-25 09:46 UTC
Labels: No Code Attached Yet
