### ISSUE TITLE
[com_tags] Menu Item "Browser Page Title" Not Working

### ISSUE THREAD

**Issue by j2studio** [joomla/joomla-cms#15562] opened 2017-04-26 04:26 UTC
### Steps to reproduce the issue

Create a menu item of Tags > Tagged Items. Add name to Browser Page Title

### Expected result

Expect to see page title entered but it shows the tags chosen for the menu item.

**Comment by franz-wohlkoenig** [comment] 2017-04-26 04:38
can you give System Information like which Joomla-Version, ...?

**Comment by j2studio** [comment] 2017-04-26 04:48
Oops - sry - Joomla 3.6.5

**Comment by franz-wohlkoenig** [comment] 2017-04-26 07:33
Issue confirmed.
### System information
3.6.5
macOS Sierra, 10.12.4
Firefox 53 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by brianteeman** [comment] 2017-04-26 07:58
Is this a duplicate of #13365

**Comment by franz-wohlkoenig** [comment] 2017-04-26 08:31
closed as Duplicate Report of #13365<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15562">issues.joomla.org/tracker/joomla-cms/15562</a>.</sub>

**Closed by franz-wohlkoenig** 2017-04-26 08:31 UTC
Labels: No Code Attached Yet
