### ISSUE TITLE
Impossible log in

### ISSUE THREAD

**Issue by fedeverdi** [joomla/joomla-cms#8758] opened 2015-12-22 09:10 UTC
Impossible log in after 3.4.7 update... No backend log in and front end log in only if "Remember me" selected...

**Comment by bostmaguy** [comment] 2015-12-22 13:37
I'm having the exact same problem. I had to find my 3.4.5 to 3.4.6 update and manually FTP everything to my site to fix the problem. If I upgrade to 3.4.7, it won't let me log into the backend. I get an invalid security token error message. No error log is being produced on the server either in the admin folder or the root directory.

**Comment by Kubik-Rubik** [comment] 2015-12-22 13:39
Please test this:

Go to your database, select the x_session table (x -> your prefix), select all entries and delete them (not the table!). Then try to login as usual. Does it work again?

**Comment by fedeverdi** [comment] 2015-12-22 14:46
I have just tried it.. but nothing..

**Comment by bostmaguy** [comment] 2015-12-22 16:30
No, it did not work for me. And it took a very long time because there were literally thousands of entries.

**Comment by fedeverdi** [comment] 2015-12-22 16:34
Bootmaguy - TRUNCATE [TABLE] tbl_name

**Comment by bostmaguy** [comment] 2015-12-22 16:40
It still doesn't matter. Deleting all entries in sessions doesn't fix the problem. Uploading the 3.4.5 to 3.4.6 upgrade does.  They should make that available for download since this problem appears endemic and most end users wouldn't know to come here regarding issues.

**Comment by brianteeman** [comment] 2015-12-22 16:45
There is something very wrong if you have thousands of entries in the
session table.

**Comment by bostmaguy** [comment] 2015-12-22 16:50
It's never been purged since the site began life as Joomla 2.5. I also have no idea what "sessions" does but I'll give anything a try at least once.

**Comment by benderis** [comment] 2015-12-23 08:44
So right after upgrade to 3.4.7 from 3.4.6 I got same problem after log out was not be able to login back to joomla . Front and back end no errors just login screen refresh that's it . After truncate sessions table nothing changed . The only thing that I see new session when try to log in , but anyway can't get in to website . So the only way what I was able to log in back to my website to put back /libraries/joomla/session/session.php file back from joomla 3.4.6 . Because it's a private website and I need login there every day . I hope someone will come with a real fix to this problem .

**Comment by creativeprogramming** [comment] 2015-12-23 11:40
@benderis your session storage in Joomla global settings is set to database file or other storage engine?

**Comment by creativeprogramming** [comment] 2015-12-23 11:43
instead of TRUNCATE i usually issue a REPAIR TABLE [prefix__session] to fix when session table with lot of entries get corrupted (it happened sometime)

**Comment by creativeprogramming** [comment] 2015-12-23 11:51
> There is something very wrong if you have thousands of entries in the
session table.

@brianteeman Joomla creates a session not just for logged in users, but also for *guests* (bots included). For a site with session time a 30 minutes and a bit of traffic is easy to have this table with thousands of entries

I think this is another point to fix in 2015, please stop Joomla from creating a session id for a guest user, or at least to save it to db, that was useful for 'counting' online vistiors and to show error messages in a persistent way across submitted pages, but i think you can do better, e.g. 'guest sessions' should  have a shorter lifetime, use a different storage and session_id (this prevents also overlapping issue we had), and can be disabled at all for sites that want to disable them)

**Comment by bostmaguy** [comment] 2015-12-23 12:41
It's definitely the sessions.php file. If you upgrade to 3.4.7 and replace the sessions.php file with the 3.4.6 version, you can once again log into the admin section. Changing the settings of sessions in global configuration before upgrading doesn't make a difference.

**Comment by creativeprogramming** [comment] 2015-12-24 03:41
@bostmaguy is suppose that the issue is that 'register_shutdown_function' is not working well in your php so the session isn't persisted after user login, can you do a quick test to exclude this?

- restore the 3.4.7 session.php file
- edit plugins/user/joomla/joomla.php and add    $session->close(); at line 336:

![2015-12-24_04h37_07](https://cloud.githubusercontent.com/assets/954291/11989087/003b9ffa-a9f8-11e5-8e04-6223d28abe3e.png)

in this way, if the issue is what I suppose, it should work and let you log in in admin section, please let me know

**Comment by creativeprogramming** [comment] 2015-12-24 06:52
@bostmaguy I suppose that the issue is that `register_shutdown_function` is not working well in your php so the session isn't persisted after user login, can you do a quick test to exclude this?

- restore the 3.4.7 session.php file
- edit plugins/user/joomla/joomla.php and add    `$session->close();` at line 236:

![2015-12-24_04h37_07](https://cloud.githubusercontent.com/assets/954291/11989087/003b9ffa-a9f8-11e5-8e04-6223d28abe3e.png)

in this way, if the issue is what I suppose, it should work and let you log in in admin section, please let me know

**Comment by wilsonge** [comment] 2015-12-24 12:20
We've just created a 3.4.8 Release Candidate Package (https://github.com/joomla/joomla-cms/releases/tag/3.4.8-rc). Some of these session issues are not reliable - so just give it a try and see if you come across any issues :)

**Comment by milosmojzis** [comment] 2015-12-24 13:50
Adding $session->close(); did not help.

Applying 3.4.8 RC Package did not help.

Truncating the table x_session did not help.

**Comment by milosmojzis** [comment] 2015-12-24 17:36
Workaround (until the fix will be available): replace the file /libraries/joomla/session/session.php by the file from version 3.4.6.

After that, you will be able to log in into backend again.

**Comment by PhilETaylor** [comment] 2015-12-31 15:20
This can be closed now?

**Comment by PhilETaylor** [comment] 2015-12-31 15:25
Please can you open your /configuration.php file and report here what the setting for 

```	public $session_handler = 'database';```

is on your site you cannot login with pleasE?

**Comment by PhilETaylor** [comment] 2016-01-06 13:53
@fedeverdi are you still having issues after upgrade to Joomla 3.4.8 or can this now be closed?

**Comment by jjsjjs** [comment] 2016-01-24 15:25
Yes it is still here with 3.4.8, I had the same issue on a live site, i still don't know what happened that i could log in again. But i did not know of the session file. So i just turn everything off in the database that could cause me to fail logging in, Like: akeeb secure and IP block plugins. i could still not log in. After a while i could log in. Now just before that i made a backup of the whole site and want to test something locally. But placing the sesion file from 3.4.6 cause the next error : plugins\system\debug\debug.php on line 396. So is it just the file or should we downgrade to 3.4.6 ? Or any other real working solution? As i do not read a good solution yet, So please do not close this thread before a solution is available. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8758">issues.joomla.org/joomla-cms/8758</a>.</sub>

**Comment by wilsonge** [comment] 2016-01-24 15:45
It sounds to me like you have not had a sucessful update. Try replacing the file `libraries/joomla/session/session.php` with https://raw.githubusercontent.com/joomla/joomla-cms/3.4.8/libraries/joomla/session/session.php this one shipped in 3.4.8 and see if things improve.

**Comment by jjsjjs** [comment] 2016-01-24 16:21
Hi, I did but it did not help. same issue.

**Comment by jjsjjs** [comment] 2016-01-24 16:29
of course i could download the whole site again and maybe the error is not there. But then i would not find the cause, on the other hand. I could see if is database related then or not. As i backed up the faulty site and database. If it still does not work, then after that i could make a backup of the live databse and use  it. If it is then solved we know that is there were the fault is, we just do not know exactly the issue.

**Comment by jjsjjs** [comment] 2016-01-24 18:48
ok it must be 100% a file...but what?  i donwloaded the website again (after the live one was working again), i used the database of the one which i could not log in, and now i can log in. so for me it is a mystery.

**Comment by PhilETaylor** [comment] 2016-01-24 18:49
This will not be a Joomla problem.

Please send me your site details using the form at https://fix.myjoomla.com/now and I'll take a look FOR FREE for you so we can get to the bottom of this. 

Kindest regards
Phil.

**Comment by brianteeman** [comment] 2016-01-27 09:53
Can this be closed now?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8758">issues.joomla.org/joomla-cms/8758</a>.</sub>

**Comment by PhilETaylor** [comment] 2016-01-27 09:54
I have not heard anything from @jjsjjs so I guess so...

**Closed** 2016-01-27 10:16 UTC
Labels: No Code Attached Yet

**Comment by jjsjjs** [comment] 2016-01-27 18:19
Sorry had no time before to react on this issue, as the issue is no longer on the live site i guess this has no use. I can't re-call the fault as i donwloaded the site to local because now it is working. It is no database issue. Sorry I'm not allowed to give access as this site is not a personal site but for an Association of Dutch Veterans. I still have a 2nd copy locally which has still this issue. So i hope to find what it is by de-installing first the latest installed extensions.
