### ISSUE TITLE
Directory is ignored in custom field of type media

### ISSUE THREAD

**Issue by RickR2H** [joomla/joomla-cms#41095] opened 2023-06-30 14:42 UTC
### Steps to reproduce the issue
In the media custom field there is an option to select a default Directory. On editing this custom field in the article this predefined directory is ignored. In stead the root of the media folder is opened.

![screen shot 2023-06-30 at 14 39 45](https://issues.joomla.org/uploads/1/f15544ec497580865361831d001f064b.jpg)

### Expected result
Om selecting an image the field opens the selected directory predefined in the field settings.

**Comment by brianteeman** [comment] 2023-06-30 15:46
I can confirm this bug. In my test i used the sampledata/parks and the field opened in the root

![image](https://github.com/joomla/joomla-cms/assets/1296369/8bdc0da2-9cb0-4db8-abf3-0f219e0a04ad)

**Comment by richard67** [comment] 2023-06-30 16:13
Which version? 4.3.2?

**Comment by brianteeman** [comment] 2023-06-30 16:39
i tested on 4.3.2 and 4.4

**Comment by richard67** [comment] 2023-07-01 08:29
@brianteeman Not related to this issue but to your screenshot: Shouldn’t we use a slash as directory separator also on Windows because it’s a PHP path? If not it would need to change all such pathes in any settings when moving the site from a local development environment on Windows to the production server on Linux? What happens when you use a slash in your example? Does it still not work? Of course the folder has to exist.

**Comment by brianteeman** [comment] 2023-07-01 08:46
i just selected from the dropdown - i didnt type anything. actually you can't type in that field

**Comment by richard67** [comment] 2023-07-01 08:59
> i just selected from the dropdown - i didnt type anything. actually you can't type in that field

I see. Well it’s a while ago I have used that field.

**Comment by chmst** [comment] 2023-07-02 15:13
Confirmed - and even more strange here. The download for folder shows only an image folder inside my component.

**Comment by SniperSister** [comment] 2023-08-26 11:31
This was fixed in https://github.com/joomla/joomla-cms/pull/40704, please re-check  @RickR2H

**Comment by richard67** [comment] 2023-08-26 11:33
Closing for reason stated in previous comment. @RickR2H Feel free to re-open if this is wrong.

**Closed as completed by richard67** 2023-08-26 11:33 UTC
Labels: No Code Attached Yet, PBF, bug
