### ISSUE TITLE
[com_finder] smart search do not display tags in the search results

### ISSUE THREAD

**Issue by michaelhq** [joomla/joomla-cms#10122] opened 2016-04-28 15:47 UTC
#### Steps to reproduce the issue

To reproduce this behaviour you have to make a clean fresh install of Joomla 3.5.1.
The behaviour will not occur on a upgraded Joomla installation e.g. 3.4.1, when smart search and tags was used on the older version already.

To have some articles select during the installation process some sample data e.g. "Brochure"

Login to administrator
- activate smart search plugin under plugins
- create a tag under components/tags /e.g. "TagTest", add some description (e.g. “Best Tag Ever”, see image 1) 
- add tag to an existing article (or to all articles, see image 2)
- run smart search index
- check, if the tags and articles are indexed (see image 3)

**Image 1**
![screen shot 2016-04-28 at 10 40 51](https://issues.joomla.org/uploads/1/8990071f922c8323615965d2f6864c6f.png)

**Image 2**
![screen shot 2016-04-28 at 10 40 52](https://issues.joomla.org/uploads/1/01399011b782ad00a915be9438651ccd.png)

**Image 3**
![screen shot 2016-04-28 at 10 40 53](https://issues.joomla.org/uploads/1/b04ff4443f133a3f1e59d06f1ca43469.png)
#### Expected result

With smart search the tags and the articles realted should be found.
#### Actual result

No result with the search on tags (also not with advanced search, see image 4 and 5).
But in the “Search Suggestions“ the tags and tag description are offered as search terms (see image 6)

**Image 4**
![screen shot 2016-04-28 at 10 43 30](https://issues.joomla.org/uploads/1/185b24a3c44f3df3bccb6ce125d9b329.png)

**Image 5**
![screen shot 2016-04-28 at 10 43 32](https://issues.joomla.org/uploads/1/9d913918fccfb16da5d7179a577ad8c8.png)

**Image 6**
![screen shot 2016-04-28 at 10 43 28](https://issues.joomla.org/uploads/1/8cd14f0a15508b5fb1d12e8dbb4584d1.png)
#### System information (as much as possible)

This behaviour was reproduced on three complete different system configurations.

Configuration 1
Database Version: 5.6.26 
Database Collation: utf8_general_ci 
Database Connection Collation: utf8mb4_general_ci 
PHP Version: 5.6.12 
Web Server: Apache/2.4.16 (Win32) OpenSSL/1.0.1p PHP/5.6.12 
WebServer to PHP Interface: apache2handler 
Joomla! Version: Joomla! 3.5.1 Stable [ Unicorn ] 05-April-2016 22:45 GMT 
Joomla! Platform Version: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT 

Configuration 2
PHP Built On: Linux tux183 4.2.0-hoststar #1 SMP Wed Sep 16 16:03:53 CEST 2015 x86_64 
Database Version: 5.5.40 
Database Collation: utf8_general_ci 
Database Connection Collation: utf8mb4_general_ci 
PHP Version: 5.6.19 
Web Server: Apache 
WebServer to PHP Interface: cgi-fcgi 
Joomla! Version: Joomla! 3.5.1 Stable [ Unicorn ] 05-April-2016 22:45 GMT 
Joomla! Platform Version: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT 

Configuration 3
PHP Built On: Linux wsnra118 2.6.32-573.22.1.el6.x86_64 #1 SMP Thu Mar 17 03:23:39 EDT 2016 x86_64 
Database Version: 5.1.73 
Database Collation: utf8_general_ci 
Database Connection Collation: utf8_general_ci 
PHP Version: 5.4.45 
Web Server: Apache/2.2.15 (Red Hat) 
WebServer to PHP Interface: apache2handler 
Joomla! Version: Joomla! 3.5.1 Stable [ Unicorn ] 05-April-2016 22:45 GMT 
Joomla! Platform Version: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT 
#### Additional comments

On Joomla 3.4.1 the tags and the articles must have the same language code as the site. “All” didn’t work with smart search. After the same language was applied to articles smart search brought results and when a tag was found related articles in the same language.

**Comment by chrisdavenport** [comment] 2016-05-04 07:50
Yes, the tags smart search plugin would appear to be, shall we say, "unfinished".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10122">issues.joomla.org/joomla-cms/10122</a>.</sub>

**Comment by michaelhq** [comment] 2016-08-19 08:29
I just upgraded my site from 3.5.1 to 3.6.2 and smart search still do not display any indexed tags. 
Is there a chance that this will be addressed in the next update of Joomla? Would be great! :smile: 

kind regards
Michael<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10122">issues.joomla.org/joomla-cms/10122</a>.</sub>

**Comment by absillitoe** [comment] 2016-09-21 09:56
I just installed smart search on a site I'm developing with the express purpose of using it with tags and I seem to have stumbled on this problem. However, the above title is perhaps misleading in the sense that (as I understand it) the problem is that no content is displayed for the tag which is found in the smart search box. I have quite a few articles tagged on my site with different tags. The desired tag appears in the smart search box, but when I select it, e.g. for the tag "Switzerland" I get the message :

Assuming switzerland is required, the following results were found.

No Results Found

No search results could be found for query: switzerland.

My local configuration is :smile: 

Windows NT DESKTOP-JEKKGHL 6.2 build 9200 (Windows 8 Home Premium Edition) i586
Database Version 	5.5.5-10.1.13-MariaDB
Database Collation 	utf8_general_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	5.6.23
Web Server 	Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.23
WebServer to PHP Interface 	apache2handler
Joomla! Version 	Joomla! 3.6.2 Stable [ Noether ] 4-August-2016 23:41 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT 

Regards,

Alan<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10122">issues.joomla.org/joomla-cms/10122</a>.</sub>

**Comment by xavier-houghton** [comment] 2016-09-30 11:41
Same issue on 3.6.2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10122">issues.joomla.org/joomla-cms/10122</a>.</sub>

**Comment by brianteeman** [comment] 2016-11-04 00:56
Closed as we have a PR for testing - see #12745

**Closed by brianteeman** 2016-11-04 00:56 UTC
Labels: No Code Attached Yet
