### ISSUE TITLE
JS Error  admin\templates\templates.js

### ISSUE THREAD

**Issue by Stevec4** [joomla/joomla-cms#11045] opened 2016-07-07 16:14 UTC
#### Steps to reproduce the issue

Navigate to Extensions >> Manage>> Install 

using IE11 and Edge in protected mode
(firefox and chrome display normally)

#### Expected result
Should see tabs for installing from web - url - folder

#### Actual result
Only sidebar is shown and a JS error is displayed
```
SCRIPT5022: QuotaExceededError
template.js (278,6)

```
#### System information (as much as possible)
Fresh install of 3.6.0 RC2 with Test data
PHP 5.6.22

**Comment by RonakParmar** [comment] 2016-07-08 04:31
I have checked in private window in IE-11 and edge but not able to reproduce the issue, I can see all tabs and working fine for me.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11045">issues.joomla.org/joomla-cms/11045</a>.</sub>

**Comment by AlexRed** [comment] 2016-07-08 07:16
I have checked using IE11 in protected mode (windows 7) but not able to reproduce the issue, I can see all tabs and working fine for me.

System information (as much as possible)
Fresh install of 3.6.0 RC2 with Test data
PHP 7.0.1

**Comment by killoltailored** [comment] 2016-07-08 10:20
I have tested in Windows 8.1 IE 11, but not able to reproduce this bug. It's working fine<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11045">issues.joomla.org/joomla-cms/11045</a>.</sub>

**Comment by Stevec4** [comment] 2016-07-08 10:30
Thanks for checking guys.
Not sure what is going on I can see the tabs (on the same computer / server & browser with J3.5 ) But in 3.6 rc2 the tabs are missing and the js error is posted. 
If its working for everyone else it must be something local.
Steve

**Comment by brianteeman** [comment] 2016-07-08 10:32
Closed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11045">issues.joomla.org/joomla-cms/11045</a>.</sub>

**Closed by brianteeman** 2016-07-08 10:32 UTC
Labels: release-blocker
