### ISSUE TITLE
[4.0]Administrator: Error while installing Languages

### ISSUE THREAD

**Issue by chaudharidivya04** [joomla/joomla-cms#26653] opened 2019-10-19 09:11 UTC
### Steps to reproduce the issue

1. Login as admin to your joomla website.
2.Click on System->Click on Languages present in Manage->Click on Install Languages->Select any language
And finally install it.

### Expected result
Clicking of Install button ,it should start installing that particular Language and give message on successfull installation.

### Actual result
It gives error alert as "Unable to find install package" on click of Install button

### System information (as much as possible)
PHP 7.2
Joomla
![languageInstallationError](https://user-images.githubusercontent.com/56750105/67141154-6a9d3700-f27e-11e9-8510-00493b05f0b0.png)

**Comment by infograf768** [comment] 2019-10-19 09:14
in 4.0, one can only install for the moment 3 languages: French fr-FR, German de-DE and Persian fa-IR.

Not a bug.

**Comment by brianteeman** [comment] 2019-10-19 20:21
@quy this should be closed as a known issue as described by @infograf768

**Closed as completed** 2019-10-20 02:34 UTC
Labels: No Code Attached Yet
