### ISSUE TITLE
Form Field Media, preview="true" not working anymore

### ISSUE THREAD

**Issue by WS-Theme** [joomla/joomla-cms#10800] opened 2016-06-12 15:46 UTC
Normally it was possible to add to the Joomla Form Field Media the Parameter **preview="true"** to show a permanent visible Preview Image of the Field. Now this isn't possible anymore! It always shows the "eye symbol". I personally think this is very useless cause the preview Image is very Important. Not sure how to fix this, it happens in Joomla 3.6 alpha!

Seems also the default Tooltip was replaced with the Bootstrap Popover. Check the 2 Images. The one on Top was with preview="true", the other one was the default. How can we fix this to work again??

![screen shot 2016-06-12 at 10 44 28](https://issues.joomla.org/uploads/1/9f0377ebb00cd582d4dd9db3c0ce9ecf.png)
![screen shot 2016-06-12 at 10 44 28](https://issues.joomla.org/uploads/1/92a88f40ffa70dca24838dc4e5f27335.png)

**Comment by dgt41** [comment] 2016-06-12 16:07
The relative code seems to be there: https://github.com/joomla/joomla-cms/blob/staging/layouts/joomla/form/field/media.php#L144
But you mention popover(?), if so that's the bootstrap version which might not have that option...

**Comment by WS-Theme** [comment] 2016-06-13 08:57
Yes sure, I have also checked this Code! But there seems to be no Variable which can control the Output if Tooltip OR default

**Comment by dgt41** [comment] 2016-06-13 09:09
@WS-Theme that's by design, you can override the layout and create the output that fits you best

**Comment by WS-Theme** [comment] 2016-06-13 09:19
Hi dgt41, sorry but how should this work without modify the Core File. I can use in XML only the basic variables that are provided by this form field. Or am I missing something?? If you could provide a Solution that would be awesome.

In the Joomla Docs for this Field we have only these ... and before Joomla 3.6 it works.

https://docs.joomla.org/Media_form_field_type

**Comment by dgt41** [comment] 2016-06-13 11:19
@WS-Theme This field layout that you are referring to is not YET shipped with Joomla!. Joomla as for 3.5 and unless #10788 is accepted is not providing a bootstrapped version of the field (meaning that the field IS NOT using bootstrap popup for the preview, but instead the mootools tooltip!). Probably you were testing a PR and you forgot to undo the changes. That said tho, if bootstrap layout is accepted the fixed position will not be part of that, so in that case you will have to override the layout

**Comment by brianteeman** [comment] 2016-06-20 21:49
Is there still an issue here or can this be closed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10800">issues.joomla.org/joomla-cms/10800</a>.</sub>

**Comment by dgt41** [comment] 2016-06-21 08:16
@WS-Theme please test #10889

**Comment by brianteeman** [comment] 2016-06-21 08:18
Closed as we have a PR

**Closed by brianteeman** 2016-06-21 08:18 UTC
Labels: No Code Attached Yet
