### ISSUE TITLE
[REGRESSION] Backend Menü on Smartphone doesnt work correct

### ISSUE THREAD

**Issue by snkai** [joomla/joomla-cms#11521] opened 2016-08-08 18:26 UTC
#### Steps to reproduce the issue
Go and login to the backend with a smartphone (iphone or android)
Choose any component of the menu list

#### Expected result
Component load 

#### Actual result
Component doesnt load

#### System information (as much as possible)
Joomla Version: 3.6.2 (update from3.6.0)
PHP-Version: 5.6.9
Smartphone: Galaxy S7 (Chrome - Mozilla 5.0) // iPhone OS Smartphones
Admin Tempalte: ISIS

#### Additional comments
Same issue on demojoomla.com
Same issue on several smartphones and browser

screenshot 1 - menu
screenshot 2 - after choose component on menu, it looks like this
screenshot 3 - switching off the "mobile" menü, will work as workaround, component will open then

![2016-08-08 11_05_54-kontrollzentrum - szenenight - administration](https://cloud.githubusercontent.com/assets/20911275/17491037/1c8e4b1e-5da6-11e6-854f-26505baf0bdd.png)
![screenshot_20160808-111040](https://cloud.githubusercontent.com/assets/20911275/17491041/22125eea-5da6-11e6-945d-88ce86fec21d.png)
![2016-08-08 11_32_53-templates_ stil bearbeiten - szenenight - administration](https://cloud.githubusercontent.com/assets/20911275/17491044/25c0560a-5da6-11e6-996b-dd722f6e3cd2.png)

**Comment by zero-24** [comment] 2016-08-08 18:59
It is not a general problem with mobile as i'm able to use my backend now with my new Windowsphone. OS: Windows10 Browser: Edge.

**Comment by brianteeman** [comment] 2016-08-08 20:39
I can confirm this problem. It is related to the changed made for the scrollable menu #9375
Looks like no one tested it on mobile<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11521">issues.joomla.org/joomla-cms/11521</a>.</sub>

**Comment by brianteeman** [comment] 2016-08-08 20:47
Or possibly #11216 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11521">issues.joomla.org/joomla-cms/11521</a>.</sub>

**Comment by jeckodevelopment** [comment] 2016-08-08 21:39
Issue confirmed.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11521">issues.joomla.org/joomla-cms/11521</a>.</sub>

**Comment by JoomliC** [comment] 2016-08-09 11:21
Issue confirmed, and was there since the first PR to add scrolling...
I open a PR to fix it in a few minutes ;-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11521">issues.joomla.org/joomla-cms/11521</a>.</sub>

**Comment by brianteeman** [comment] 2016-08-09 11:31
Thank you

**Comment by brianteeman** [comment] 2016-08-09 11:38
Closed as we have a pr for testing #11528

**Closed by brianteeman** 2016-08-09 11:38 UTC
Labels: No Code Attached Yet
