### ISSUE TITLE
[4.0] Cassiopeia - Frontend Template - Bug width column

### ISSUE THREAD

**Issue by korenevskiy** [joomla/joomla-cms#28130] opened 2020-02-29 00:55 UTC
### Steps to reproduce the issue
```
@media (min-width: 768px)
.container-bottom-a, .container-bottom-b, .container-top-a, .container-top-b {
    grid-template-columns: repeat(auto-fit,minmax(24%,1fr));
}
@media (min-width: 576px)
.container-bottom-a, .container-bottom-b, .container-top-a, .container-top-b {
    grid-template-columns: 1fr 1fr;
}
```

### Actual result
If the site width is greater than 768, the one module in the position is displayed in 100% of the width. But if the width is less than 768, the one module is output in 50% of the width.

### Expected result
The 50% behavior should be displayed if the number of modules is greater than one. But if the module is one, it should be displayed in full width. Moreover, the opposite is displayed. With a small site width, the module has a width of 50%, and with a huge site width, one module has a width of 100%. Where it is logical that it was the opposite.

**Comment by chmst** [comment] 2020-03-06 12:27
Which position? Can you post a screenshot, please, as I cannot reproduce it?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28130">issues.joomla.org/tracker/joomla-cms/28130</a>.</sub>

**Comment by vijay9908** [comment] 2020-03-06 18:38
I didn't get you, Can you post a gif or a screenshot to reproduce the bug so that I can work on it!

**Comment by jwaisner** [comment] 2020-04-15 14:52
Closing as no reply with needed information to reproduce.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28130">issues.joomla.org/tracker/joomla-cms/28130</a>.</sub>

**Closed as completed by jwaisner** 2020-04-15 14:52 UTC
Labels: No Code Attached Yet, Information Required
