### ISSUE TITLE
Color form field broken with similar named fields

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#15958] opened 2017-05-10 23:56 UTC
### Steps to reproduce the issue

Create 2 fields with similar names.

I have two fields in my template...

```
<field name="hoverbackgroundColor"
                               class="small-input"
                               label="TPL_SERENITY_FONTS_HOVER_BACKGROUND_COLOR_LABEL"
                               description="TPL_SERENITY_FONTS_HOVER_BACKGROUND_COLOR_DESC"
                               type="color"
                               default=''
                        />
                        <field name="hoverColor"
                               class="small-input"
                               label="TPL_SERENITY_FONTS_HOVER_COLOR_LABEL"
                               description="TPL_SERENITY_FONTS_HOVER_COLOR_DESC"
                               type="color"
                               default=''
                        />

```

so, now you have got 2 fields
if you put color in the 2nd and save it returns empty
if you put color in the 1st it saves
if you put color in the 1st and 2nd it changes 2nd to match first!!!

craziest thing I've ever seen.

### Expected result

colors are independant 

### Actual result
see above

### System information (as much as possible)

both 3.6.5 and 3.7

### Additional comments
This worked fine before and does work if the fields are NOT named similarly.  Both are in "repeatable" form fields but I don't see that that is relevant since both repeatable and sub use the same color form field system.

**Comment by Bakual** [comment] 2017-05-11 04:54
I understand you correct that the two fields are named identical? Then that seems to be the expected behaviour to me. The names need to be unique in a form, otherwise one will overwrite the other.

**Comment by brianteeman** [comment] 2017-05-11 08:31
I have updated thew original comment so that the markup is displayed

**Comment by Bakual** [comment] 2017-05-11 10:42
> I have updated the original comment so that the markup is displayed

Ah, didn't see that. The name shouldn't matter then. I do a similar thing in my template all the way.

> This worked fine before and does work if the fields are NOT named similarly. Both are in "repeatable" form fields but I don't see that that is relevant since both repeatable and sub use the same color form field system.

That's most likely related to the repeatable then. I don't know from the top of my head how repeatables are stored. Maybe @Fedik would know more here.

**Comment by Fedik** [comment] 2017-05-11 11:06
> Create 2 fields with similar names.

the names are not similar 😄 

I cannot reproduce it, in the template form all works fine:

![screen 2017-05-11 14 01 40 623x283](https://cloud.githubusercontent.com/assets/1568198/25946134/7e3bce38-3652-11e7-8ad6-02a4fef0554c.png)

however I am not tested in subform since last changes in the color field markup (I try to check later), there was a fix #12994 but no one tested, and now it out of date already

**Comment by N6REJ** [comment] 2017-05-11 17:07
I haven't tried it with subforms yet.  Thats something planned for today or tomorrow.  It's interesting that it only happens if the name is related(?) or perhaps its because they are side-by-side.  Very strange behavior

**Comment by Fedik** [comment] 2017-05-11 18:05
I just checked the subform with the color field in the Isis template and all works there for me

**Comment by Fedik** [comment] 2017-05-11 18:28
@N6REJ  please test that #15974

**Comment by Bakual** [comment] 2017-05-11 18:46
Closing as we have a PR

**Closed by Bakual** 2017-05-11 18:46 UTC
Labels: No Code Attached Yet

**Comment by N6REJ** [comment] 2017-05-12 07:58
I'll check it in the late morning
