### ISSUE TITLE
behavior.keepalive with progressive cache JS error

### ISSUE THREAD

**Issue by n3t** [joomla/joomla-cms#16375] opened 2017-05-30 21:58 UTC
### Steps to reproduce the issue
- enable cache - progressive caching in Global configuration
- Create new contact in com_contact, add an email, enable contact form
- open JS console, to see errors
- go to frontend, open the contact form
- refresh the page for second time

### Expected result
- no JS error

### Actual result
- upon firs load, everything is OK
- upon second load JS error appears
`keepalive.js…:1 Uncaught TypeError: Cannot read property 'uri' of undefined`

### System information (as much as possible)
- Joomla Fresh installation 3.7.2
- Protostar template

### Additional comments
- if you see the html, upon first call there is line 
`<script type="application/json" class="joomla-script-options new">{"system.keepalive":{"interval":840000,"uri":"\/index.php\/en\/component\/ajax\/?format=json"},"joomla.jtext":{"JLIB_FORM_FIELD_INVALID":"Invalid field:&#160"}}</script>`
- upon second load is limited to
`<script type="application/json" class="joomla-script-options new">{"joomla.jtext":{"JLIB_FORM_FIELD_INVALID":"Invalid field:&#160"}}</script>`

**Comment by Melvine9** [comment] 2017-06-02 15:39
Hello,

I have the same issue.
Make click right on the window and show source. This give me the same lines

`<script type="application/json" class="joomla-script-options new">{"system.keepalive":{"interval":1740000,"uri":"\/index.php?option=com_ajax&amp;format=json"},"joomla.jtext":{"JLIB_FORM_FIELD_INVALID":"Champ invalide&#160;:&#160;"}}</script>`

and cause some issue with dropeditor ( lines above)

php 7.1.5
Joomla 3.7.2
[picture](https://img15.hostingpics.net/pics/658386keepalive.png)


Best Regards
Melvine

**Comment by andrepereiradasilva** [comment] 2017-06-02 16:20
Issue confirmed:
- Use latest joomla staging
- Global config: System Cache = ON - Progressive caching
- Go to frontend - not logged, view source, the keepalive code is there 
- Refresh page, view source, the keepalive json code is not there (there is no json at all)

Further info: seems `JHtml::_('behavior.keepalive');` (that introduces that code) is not called in progressive cache mode (in no cache mode or conservative caching works).
In my case the keepalive was called by [mod_login](https://github.com/joomla/joomla-cms/blob/staging/modules/mod_login/tmpl/default.php#L14) (the login box module)

A workaround is to disable progressive caching, but yes, confirmed the issue also.

**Comment by andrepereiradasilva** [comment] 2017-06-02 17:51
Ok, so IMO there are two sides of this issue:
1. The `JHtml::_('behavior.keepalive');` inside the mod_login template file is not being processed when cache in conservative mode.
2. The keepalive js should not give error and always fallback to a default value in case of no json system.keepalive config.

Proposed a PR to try to solve "2." https://github.com/joomla/joomla-cms/pull/16452 - please test.

Reggarding "1." have no idea - maybe someone that understands better the cache system can help.

**Comment by Melvine9** [comment] 2017-06-02 18:15
Thank you very much, I will try

**Comment by franz-wohlkoenig** [comment] 2017-06-03 04:32
closed as having PR #16452 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16375">issues.joomla.org/tracker/joomla-cms/16375</a>.</sub>

**Comment by andrepereiradasilva** [comment] 2017-06-03 09:50
@franz-wohlkoenig the PR does not solve one part of the issue. Imho Should demais open until someone looks at the progressive cache issue

**Comment by franz-wohlkoenig** [comment] 2017-06-03 10:19
reopened<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16375">issues.joomla.org/tracker/joomla-cms/16375</a>.</sub>

**Comment by andrepereiradasilva** [comment] 2017-06-03 13:41
@franz-wohlkoenig maybe the cache issue is the same thing as https://github.com/joomla/joomla-cms/issues/16375 but not sure

**Comment by n3t** [comment] 2017-06-07 00:26
Generelly, is keepalive neccessary in frontend? For example in login form? Or in Contact form. It could compromise security, as for example in contact it will keep user logged in even he leaves computer...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16375">issues.joomla.org/tracker/joomla-cms/16375</a>.</sub>

**Comment by andrepereiradasilva** [comment] 2017-06-07 06:46
Keepalive is used in forms because of the crsf token check. Anyway this issue as describe above is not a keepalive issue. is the progressive cache that makes this behaviour

**Comment by weeblr** [comment] 2017-06-07 06:47
Hi

#11203 does not appear to me as the same thing:

1. The fix does not apply anyway, as it applied to controller and views, which are not used in modules
2. #11203 happens with conservative caching, while this one is with progressive. Progressive being supposed to be more agressive caching, this kind of side effect might happen. Would be good to confirm whether the same happens with only conservative caching enabled or not.
3. Agree that this should not cause a JS error, error should be caught and properly displayed
4. Maybe caching for such modules should simply be disabled by users when progressive caching is enabled?

**Comment by andrepereiradasilva** [comment] 2017-06-07 10:06
> 1. The fix does not apply anyway, as it applied to controller and views, which are not used in modules

Ok, my misunderstanding

> 2. #11203 happens with conservative caching, while this one is with progressive. Progressive being supposed to be more agressive caching, this kind of side effect might happen. Would be good to confirm whether the same happens with only conservative caching enabled or not.

Only progressive cache.

> 3. Agree that this should not cause a JS error, error should be caught and properly displayed

A PR was done to solve the keepalive js issue (better fallback), but since core.js is not loaded it can cause other js issues in other similiar situations.

> 4. Maybe caching for such modules should simply be disabled by users when progressive caching is enabled?

Not sure, this in princpiple would apply to all modules in such situations, right? 
Doesn't seem the solution would be disabling cache in all modules that load a behaviour that loads core.js. There must be something that prevents core.js from being loaded in this scenario.

**Comment by weeblr** [comment] 2017-06-07 10:31
Hi

> There must be something that prevents core.js from being loaded in this scenario.

Yes, it's caching. If the module is cached, then its PHP code is not executed, and thus any instruction such as loading js, css or any other type of action is not executed at all. Note that the same probably happen if the module is supposed to record something in the database for instance.

So basically such a module is not compatible with being cached, which is why it should be disabled IMHO.

Rgds

**Comment by andrepereiradasilva** [comment] 2017-06-07 10:55
> Yes, it's caching. If the module is cached, then its PHP code is not executed, and thus any instruction such as loading js, css or any other type of action is not executed at all. Note that the same probably happen if the module is supposed to record something in the database for instance.

I don't understand how this conservative progressive cache works (never used it), but if php code is not executed, why is keepalive.js rendered?
See https://github.com/joomla/joomla-cms/blob/staging/modules/mod_login/tmpl/default.php#L14

**Comment by weeblr** [comment] 2017-06-07 10:59
Most likely because keepalive is rendered as part of the HTML of the module, inlined. And so it's cached with the rest of the content.

**Comment by andrepereiradasilva** [comment] 2017-06-07 11:01
is `behavior.keepalive` that calls for core.js to be rendered (see https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/html/behavior.php#L709)

**Comment by weeblr** [comment] 2017-06-07 11:06
yes, exactly. Because the PHP part is not executed, the core.js is not linked. But the keepalive settings 

````<script type="application/json" class="joomla-script-options new">{"joomla.jtext":{"JLIB_FORM_FIELD_INVALID":"Invalid field:&#160"}}</script>````

are simply output as part of the HTML and are cached.

**Comment by andrepereiradasilva** [comment] 2017-06-07 11:14
doesn't that part is rendered in the same place as the js scripts, ie, in JDocument head render?
See https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/document/renderer/html/head.php#L236

**Comment by weeblr** [comment] 2017-06-07 11:31
Yes, so maybe it's called by something else (the page itself, another module). But the problem is the wrong configuration snippet?
You would need to be able to reproduce on a standard install, and then step through code to know...

**Comment by stutteringp0et** [comment] 2018-04-17 04:14
I just ran into this, and it affects more than just keepalive.  Any script option I set in a content plugin is also lost.

**Comment by stutteringp0et** [comment] 2018-04-17 07:51
Any script declaration I set remains with caching enabled.

**Comment by brianteeman** [comment] 2022-08-23 10:36
Thank you for raising this issue. 

Joomla 3 is now in security only mode with no further bug fixes or new features.

As this issue doesn't relate to Joomla 4 it will now been closed. 

If we are mistaken and this does apply to Joomla 4 please open a new issue (and reference this one if you wish) with updated details for testing in Joomla 4.
cc @zero-24

**Closed** 2022-08-23 13:47 UTC
Labels: No Code Attached Yet, J3 Issue
