### ISSUE TITLE
Search field size in mod_finder not dependent of field size option

### ISSUE THREAD

**Issue by pl71** [joomla/joomla-cms#4879] opened 2014-10-21 12:28 UTC
#### Steps to reproduce the issue
mod_finder (Smart search module)

#### Expected result
Search field size as per option 'Search Field Size'

#### Actual result
Search field width is hard coded at 150px
mod_finder/tmpl/default.php row 21 - input_medium class

#### Additional comments

Size option to be like drop-down list of the pre-defined BS 2 sizes (.input-medium, .input-large, etc..)
Or to wait BS3 implementation in future Joomla versions.

**Comment by bertmert** [comment] 2015-05-01 16:00
Please see and test PR https://github.com/joomla/joomla-cms/pull/6877

**Comment by roland-d** [comment] 2015-05-02 18:06
Closing this as the issue is fixed in #6873.

**Comment by roland-d** [comment] 2015-05-02 18:06
Sorry, wrong PR, this is another topic.

**Comment by roland-d** [comment] 2015-05-02 18:10
Closing this anyway because we have a PR at #6877

**Closed by roland-d** 2015-05-02 18:10 UTC
Labels: No Code Attached Yet
