### ISSUE TITLE
[4.0] [backend-template] Global Config text filters

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#25887] opened 2019-08-16 08:35 UTC
### Steps to reproduce the issue

1. Go to `administrator/index.php?option=com_config`
2. Click the `Text Filters` tab

Look at the width of the dropdown boxes:

![Screenshot_2019-08-16 Global Configuration - J4 - Administration](https://user-images.githubusercontent.com/2019801/63154725-289b0f00-c009-11e9-9369-1b46dd401e0d.png)

**Comment by alikon** [comment] 2019-08-16 08:40
same on permission
![Screenshot from 2019-08-16 10-39-24](https://user-images.githubusercontent.com/181681/63155081-386b2100-c012-11e9-9520-efd860f81e1d.png)

**Comment by infograf768** [comment] 2019-08-16 08:57
Fix:
Change `$this->formclass   = 'form-no-margin options-grid-form options-grid-form-half';` to `$this->formclass   = 'form-no-margin options-grid-form options-grid-form-full';`
in
`/administrator/components/com_config/tmpl/application/default_permissions.php`
line 18

Same for default_filters.php line 17
`$this->formclass = 'options-grid-form options-grid-form-full';` instead of half

**Comment by infograf768** [comment] 2019-08-16 09:03
Evidently this fix will not work when reducing screen, specially the Permissions one.

**Comment by alikon** [comment] 2019-08-16 09:07
even when you use a more large one (permission apart which it seems to be solved on a  large screen) lol

**Comment by infograf768** [comment] 2019-08-16 17:04
I could make a PR with the code above but as it fails for smaller screen sizes, I am reluctant to do so. It seems that this needs much more attention (as the template in general) when we reduce the real estate...

**Comment by ghazal** [comment] 2019-08-17 10:10
Issue confirmed.

**Comment by brianteeman** [comment] 2019-08-18 09:10
@infograf768 Your fix only addresses the global configuration permissions tab. It doesnt do anything on component configurations. for that you would need to edit administrator\components\com_config\tmpl\component\default.php

**Comment by infograf768** [comment] 2019-08-19 09:30
Closing as we have PR https://github.com/joomla/joomla-cms/pull/25934

**Closed as completed by infograf768** 2019-08-19 09:30 UTC
Labels: No Code Attached Yet, Backend Template
