### ISSUE TITLE
Array to string conversion in /var/www/js/administrator/modules/mod_menu/menu.php 613

### ISSUE THREAD

**Issue by VampiRUS** [joomla/joomla-cms#17128] opened 2017-07-14 01:13 UTC
### Steps to reproduce the issue
Component has submenu item with filter option:
```
<submenu>
	<menu link="option=com_plugins&amp;view=plugins&amp;filter[search]=search"
		view="plugins" img="class:plugin" alt="Plugins">com_component_plugins</menu>
</submenu>
```
### Actual result
Error notice in admin panel:
Notice: Array to string conversion in /var/www/js/administrator/modules/mod_menu/menu.php on line 613

### System information (as much as possible)
Joomla 3.7.3

**Comment by zero-24** [comment] 2017-07-14 07:44
Please tell us the exact PHP Version. As `$parts` should be an array and impode is constructed to move arrays to strings. I'm a bit confused.

**Comment by VampiRUS** [comment] 2017-07-14 09:12
php 5.5.9
if `$link = "index.php?option=com_plugins&view=plugins&filter[search]=search";`
$uri->getQuery(true); 
will return 
```
array (
   'option' => 'com_plugins',
   'view' => 'plugins',
   'filter' =>
   array (
   'search' => 'search',
   ),
   )
```

**Comment by eshiol** [comment] 2017-07-14 09:20
The issue is in administrator/modules/mod_menu/menu.php on line 610
```
				$parts[] = str_replace(array('.', '_'), '-', $value);
```
Try to replace it with
```
				if (!is_array($value))
				{
					$parts[] = str_replace(array('.', '_'), '-', $value);
				}
				else
				{
					foreach ($value as $k => $v)
					{
						$parts[] = $k.'-'.str_replace(array('.', '_'), '-', $v);
					}
				}
```

**Comment by ghost** [comment] 2017-08-26 06:53
@VampiRUS have you tried above Suggestion? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17128">issues.joomla.org/tracker/joomla-cms/17128</a>.</sub>

**Comment by VampiRUS** [comment] 2017-08-30 06:22
@franz-wohlkoenig yes it helps<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17128">issues.joomla.org/tracker/joomla-cms/17128</a>.</sub>

**Comment by ghost** [comment] 2017-08-30 06:34
@VampiRUS as Issue is resolved can you please close the Issue?

**Comment by VampiRUS** [comment] 2017-08-30 12:19
@franz-wohlkoenig this is issue in joomla code, i think it must be fixed there.

**Comment by ghost** [comment] 2017-09-17 11:07
@maintainers any Opinion?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17128">issues.joomla.org/tracker/joomla-cms/17128</a>.</sub>

**Comment by zero-24** [comment] 2017-09-19 20:26
@franz-wohlkoenig just FYI you can't tag `@maintainers` you just tag this org: https://github.com/maintainers ;)

Regarding the topic what about doing the suggested code changes as PR so we can test and merge the fix?

**Comment by ghost** [comment] 2017-09-19 20:28
@zero-24 will try to remember :-)

**Comment by mbabker** [comment] 2017-09-19 20:31
I don't remember what the permissions are on GitHub but you can try pinging @joomla/cms-maintainers

**Comment by zero-24** [comment] 2017-09-19 20:32
IMO you need to be part of that team or owner to be allowed to ping the team ;)

**Comment by mbabker** [comment] 2017-09-19 20:35
I don't remember what the permissions are on who can ping teams or who is in what team off the top of my head.  If the feature works for him then cool, if not, well, blame GitHub 😉

**Comment by ghost** [comment] 2017-10-22 09:18
pinging https://github.com/maintainers & @joomla/cms-maintainers<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17128">issues.joomla.org/tracker/joomla-cms/17128</a>.</sub>

**Comment by infograf768** [comment] 2017-10-22 15:39
@izharaazmi

**Comment by izharaazmi** [comment] 2017-10-23 06:13
This issue is out of context since the merge of #16451. The changes can be see [here](https://github.com/joomla/joomla-cms/pull/16451/files#diff-33d293783aa85ce0987e9f91d747da32L593)

I have also verified the new code and I can confirm that this was not carried over. Hence IMHO, this can be safely closed.  Thanks.

**Comment by ghost** [comment] 2017-10-23 06:44
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17128">issues.joomla.org/tracker/joomla-cms/17128</a>.</sub>

**Closed as completed by ghost** 2017-10-23 06:44 UTC
Labels: No Code Attached Yet
