### ISSUE TITLE
[5.1] Template Manager  -  Some folders not displayed in alphabetical order

### ISSUE THREAD

**Issue by dautrich** [joomla/joomla-cms#40605] opened 2023-05-16 09:43 UTC
### Steps to reproduce the issue

1. Use or create a site with at least one additional frontend template (in addition to Cassiopeia)
2. Login to the backend and move to System - Site Templates
3. Open 'Details and Files' of your additional template
4. Unfold the folders under /media/templates/site/[Your template]

### Expected result
Within each folder, the files should be displayed in alphabetical order

### Actual result
Within each folder, the files are not displayed in alphabetical order:

![Screenshot 2023-05-16 at 11-32-04 Templates Customise (J51_skylar) - Lebenswert Neudorf - Administration](https://github.com/joomla/joomla-cms/assets/7933215/8473b2da-7323-494c-abe9-f67d3b6e467a)

### System information (as much as possible)
Joomla 4.3.1, template 'Skylar_J4' from Joomla51 (Version 1.1.8)

**Comment by richard67** [comment] 2023-05-16 13:21
> Joomla 4.3.1, template 'Skylar_J4' from Joomla51 (Version 1.1.8)

I think the Skylar template is not the problem here as the template manager runs in the administrator (backend).

@dgrammatiko Does the ordering of the files and folders in the template manager somehow depend on the template's XML file? I don't think so, but I thought I ask you, maybe you know it better.

**Comment by dgrammatiko** [comment] 2023-05-16 13:48
AFAIR the order is what comes out of the readdir php function. There shouldn’t be affected by anything in the xml file

**Comment by richard67** [comment] 2023-05-16 13:51
> AFAIR the order is what comes out of the readdir php function. There shouldn’t be affected by anything in the xml file

Yes, that's what I would think, too. It seems readdir doesn't necessarily work in alphabetical order. There is a StackOverflow topic about that, where someone recommends to use scandir instead: https://stackoverflow.com/questions/541510/php-readdir-not-returning-files-in-alphabetical-order .

**Comment by dgrammatiko** [comment] 2023-05-16 16:03
@richard67 actually I was wrong, the output is what comes out from scandir: https://github.com/joomla/joomla-cms/blob/c20185413b05ad94f46ec8fe6d803f5d6d2e8e81/administrator/components/com_templates/src/Model/TemplateModel.php#L412

**Comment by rdeutz** [comment] 2023-08-26 13:39
tried to reproduce the bug but couldn't confirm

**Comment by dautrich** [comment] 2023-09-06 20:52
@rdeutz    Do you think my screenshot is a fake? I see the bug daily when looking into my template.

**Comment by dautrich** [comment] 2024-04-22 10:22
I changed the title of this issue because it still shows under J5.1:

![grafik](https://github.com/joomla/joomla-cms/assets/7933215/8d4126bf-ddf5-489e-9531-4294a4ce36aa)

**Comment by dautrich** [comment] 2024-04-22 10:23
@richard67 @dgrammatiko 
This is not a severe issue, but a bit annoying. Could you pls check again?

**Comment by dgrammatiko** [comment] 2024-04-22 10:31
What's your operating system of the server that this issue occurs?

**Comment by dautrich** [comment] 2024-04-22 10:55
=============
Systeminformationen
=============
php: Linux sh16-23 5.15.0-73-generic #80-Ubuntu SMP Mon May 15 15:18:26 UTC 2023 x86_64
dbserver: mysql
dbversion: 8.0.33-0ubuntu0.20.04.1
dbcollation: utf8mb4_0900_ai_ci
dbconnectioncollation: utf8mb4_0900_ai_ci
dbconnectionencryption: 
dbconnencryptsupported: true
phpversion: 8.3.6
server: Apache
sapi_name: cgi-fcgi
version: Joomla! 5.1.0 Stable [ Kudumisha ] 16-April-2024 16:00 GMT
compatpluginenabled: true
compatpluginparameters: 
useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0

**Comment by Quy** [comment] 2024-04-22 16:26
On the server, browse `/media/templates/site/j51_skylar/css` to see how these files are listed.
If possible, install on a different server to see if it is reproducible.

**Comment by brianteeman** [comment] 2024-04-22 16:31
just to rule something out can you p;ease retest with Joomla in English

**Comment by dautrich** [comment] 2024-04-22 18:19
![grafik](https://github.com/joomla/joomla-cms/assets/7933215/7d095f6d-84dd-4f1f-99ae-5d6724ec19c2)

**Comment by dautrich** [comment] 2024-04-22 18:23
@Quy 
![grafik](https://github.com/joomla/joomla-cms/assets/7933215/441d86c9-0499-439d-be5b-c87529bf2f65)

**Comment by dautrich** [comment] 2024-04-22 18:45
@Quy 
I just tested a different website (but with the same template) on localhost via XAMPP, but I get exactly the identical issue:

![grafik](https://github.com/joomla/joomla-cms/assets/7933215/47c622d7-60d3-4dd5-8139-17605d13028a)


=============
System Information
=============
php: Windows NT DP3450 10.0 build 22631 (Windows 11) AMD64
dbserver: mysql
dbversion: 10.4.32-MariaDB
dbcollation: utf8mb4_general_ci
dbconnectioncollation: utf8mb4_general_ci
dbconnectionencryption: 
dbconnencryptsupported: false
phpversion: 8.2.12
server: Apache/2.4.58 (Win64) OpenSSL/3.1.3 PHP/8.2.12
sapi_name: apache2handler
version: Joomla! 5.1.0 Stable [ Kudumisha ] 16-April-2024 16:00 GMT
compatpluginenabled: true
compatpluginparameters: 
useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0

**Comment by brianteeman** [comment] 2024-04-22 20:59
can you confirm that you only see it with this template?

**Comment by dautrich** [comment] 2024-04-23 06:14
@brianteeman Yes, because it is the only one I use (apart from test sites with Cassiopeia).  Should we try to involve Ciaran Walsh?

**Comment by dgrammatiko** [comment] 2024-04-23 06:39
@dautrich what Brian asked was to try to open the cassiopeia files view and report if those files are displayed properly sorted.

**Comment by dautrich** [comment] 2024-04-23 08:18
I've set Cassiopeia to standard template for all files. Looking at the template files, they are properly ordered.

Having seen this, I also believe that the issue is something related to the Skylar template.

If you don't want to invest any more time in this, I'm going to close this issue.

**Comment by brianteeman** [comment] 2024-04-23 08:22
> If you don't want to invest any more time in this, I'm going to close this issue.

The problem is that no one has reproduced this and as the template youare using it is commercial we dont have access to reproduce it ourselves with that template

**Comment by HLeithner** [comment] 2024-04-23 08:32
I found the issue and will prepare an pr in a couple of minutes.

**Comment by HLeithner** [comment] 2024-04-23 09:07
Please test #43335 closing this.

**Closed as completed by HLeithner** 2024-04-23 09:07 UTC
Labels: No Code Attached Yet, bug
