### ISSUE TITLE
Insert Logo in template protostar - I can not close windows with insert or cancel

### ISSUE THREAD

**Issue by gunthelm2000** [joomla/joomla-cms#9348] opened 2016-03-08 21:24 UTC
#### Steps to reproduce the issue
open Extensions - Templates - protostar Default
open tab Advanced
Logo select
close windows with insert or cancel dont work
the images is nevertheless insert

**Comment by brianteeman** [comment] 2016-03-08 22:21
What version of Joomla? What version of php? What web browser

I cannot replicate this with the current staging or with joomla 3.4.8

On 8 March 2016 at 21:24, gunthelm2000 <notifications@github.com> wrote:

> Steps to reproduce the issue
>
> open Extensions - Templates - protostar Default
> open tab Advanced
> Logo select
> close windows with insert or cancel dont work
> the images is nevertheless insert
> Expected result Actual result System information (as much as possible) Additional
> comments
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9348>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by RonakParmar** [comment] 2016-03-09 09:11
I am not able to replicate this issue.
Here is my system information:

Joomla! Version: Joomla! 3.4.8 Stable [ Ember ] 24-December-2015 19:30 GMT
Joomla! Platform Version: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
PHP Version: 5.4.45-3+deb.sury.org~precise+1
System Linux desktop 3.5.0-54-generic #81~precise1-Ubuntu SMP Tue Jul 15 04:02:22 UTC 2014 x86_64
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9348">issues.joomla.org/joomla-cms/9348</a>.</sub>

**Comment by gunthelm2000** [comment] 2016-03-09 09:50
In Joomla 3.4.8 working correctly, but in 3.5.0 Beta its dont work.

 

Von: RonakParmar [mailto:notifications@github.com] 
Gesendet: Mittwoch, 9. März 2016 10:11
An: joomla/joomla-cms <joomla-cms@noreply.github.com>
Cc: gunthelm2000 <joomla@gunterhellmann.de>
Betreff: Re: [joomla-cms] Insert Logo in template protostar - I can not close windows with insert or cancel (#9348)

 

I am not able to replicate this issue.
Here is my system information:

Joomla! Version: Joomla! 3.4.8 Stable [ Ember ] 24-December-2015 19:30 GMT
Joomla! Platform Version: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
PHP Version: 5.4.45-3+deb.sury.org~precise+1
System Linux desktop 3.5.0-54-generic #81 <https://github.com/joomla/joomla-cms/pull/81> ~precise1-Ubuntu SMP Tue Jul 15 04:02:22 UTC 2014 x86_64

  _____  

This comment was created with the J!Tracker Application <https://github.com/joomla/jissues>  at issues.joomla.org/joomla-cms/9348 <https://issues.joomla.org/tracker/joomla-cms/9348> .

—
Reply to this email directly or view it on GitHub <https://github.com/joomla/joomla-cms/issues/9348#issuecomment-194196113> .  <https://github.com/notifications/beacon/ABsyuVzIpnO4nbguHlx3I5EnPIthW4e_ks5pro6_gaJpZM4HsKnR.gif> 



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by RonakParmar** [comment] 2016-03-09 09:59
Yes, I can re-produce this issue in Joomla! 3.5.0-beta Beta [ Ember ] 06-November-2015 24:00 GMT.
No click of "cancel" not able to close the modal.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9348">issues.joomla.org/joomla-cms/9348</a>.</sub>

**Comment by brianteeman** [comment] 2016-03-09 10:06
Please test in beta6 I can not replicate this

On 9 March 2016 at 09:59, RonakParmar <notifications@github.com> wrote:

> Yes, I can re-produce this issue in Joomla! 3.5.0-beta Beta [ Ember ]
> 06-November-2015 24:00 GMT.
> No click of "cancel" not able to close the modal.
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/9348
> <https://issues.joomla.org/tracker/joomla-cms/9348>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9348#issuecomment-194217410>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by andrepereiradasilva** [comment] 2016-03-09 12:12
beta6? ahead of time?
i only see beta5 https://github.com/joomla/joomla-cms/releases

**Comment by brianteeman** [comment] 2016-03-09 12:23
staging reports as beta 6 ;)

**Comment by arrowthemes** [comment] 2016-03-09 13:41
I can reproduce this issue with Joomla 3.5.0 beta 5. On the pop-up there are two cancel buttons. One right next to the 'insert' button (which doesn't work) and the other one at the modal-footer. This seems to be a change from Joomla 3.4.8 which had one cancel button. Was there a reason why adding a second cancel button was necessary?

**Comment by brianteeman** [comment] 2016-03-09 13:51
Ah I see what you mean about the cancel
@dgt41 any ideas

I still have no problem inserting the logo though

-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by dgt41** [comment] 2016-03-09 14:23
Please test: #9350

**Comment by brianteeman** [comment] 2016-03-09 14:37
Closed as we have a PR for testing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9348">issues.joomla.org/joomla-cms/9348</a>.</sub>

**Closed by brianteeman** 2016-03-09 14:37 UTC
Labels: No Code Attached Yet
