### ISSUE TITLE
Frontend article submission forces captcha

### ISSUE THREAD

**Issue by ron4mac** [joomla/joomla-cms#15666] opened 2017-04-28 15:29 UTC
### Steps to reproduce the issue
- Configure a default captcha in the site config
- Create a menu item Articles/Create New Article
- Access the menu item from the front end

### Expected result
- Article submission form without captcha requirement (if so configured)

### Actual result
- Article submission form with captcha and no way to prevent the captcha from being required

### System information (as much as possible)
Joomla! 3.7.0 Stable [ Amani ] 25-April-2017 15:36 GMT
Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

### Additional comments
There are a number of situations where captcha for frontend article submission may not be needed and is not  desired. A mechanism should be provided, on a menu item basis, to forego the global captcha occurrence.

**Comment by brianteeman** [comment] 2017-04-29 04:26
Unfortunately that will not be possible with the way that captcha is controlled

**Comment by ron4mac** [comment] 2017-04-29 12:22
Disappointing....  Other components are designed with captcha as an option.

**Comment by AlexRed** [comment] 2017-04-29 12:28
I can confirm the problem<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15666">issues.joomla.org/tracker/joomla-cms/15666</a>.</sub>

**Comment by AlexRed** [comment] 2017-04-29 12:40
yes, in 3.6.5 is ok, in 3.7.0 no  :(<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15666">issues.joomla.org/tracker/joomla-cms/15666</a>.</sub>

**Comment by brianteeman** [comment] 2017-04-29 12:48
the request was to have captcha enabled per menu item - or have I misunderstood something

**Comment by ron4mac** [comment] 2017-04-29 12:54
The request was ... however it could be done ... to not force captcha on a frontend article submission just because there is a default captcha plugin set in the global config. Menu item setting was just a possible suggestion.

**Comment by AlexRed** [comment] 2017-04-29 12:57
yes, now captcha is enabled by default in insert/edit article in frontend.
For me you need to reopen the issue

**Comment by brianteeman** [comment] 2017-04-29 13:19
So to be clear you are saying that captcha should be able to be set on for user registration and/or contact forms and/or article submission and that right now if it is enabled it is always enabled for all of those

**Comment by AlexRed** [comment] 2017-04-29 13:27
No.
Install a fresh 3.7.0, enable and configure the plugin "Captcha - ReCaptcha" and set it in the global configuration.
Now in frontend article edit/submission captcha requirement.

Maybe you just wanted Captcha only in contact, but if you enable it in global config now it is in frontend article edit/submission.

**Comment by ron4mac** [comment] 2017-04-29 13:29
Registration and contact forms have the option whether to use captcha or not ... and whether or not there is a default captcha plugin set. For frontend article submission, there is no option.

**Comment by brianteeman** [comment] 2017-04-29 13:42
@ron4mac yes there is


<img width="896" alt="screenshotr14-42-02" src="https://cloud.githubusercontent.com/assets/1296369/25555910/0bd31ee4-2cea-11e7-9802-ca1b01dca493.png">

**Comment by AlexRed** [comment] 2017-04-29 13:42
in Joomla 3.7.0 now the parameter is:
Articles: Options --> Editing Layout -->  Allow Captcha on submit

but if it is "None Selected" it is enabled

**Comment by AlexRed** [comment] 2017-04-29 13:45
ok, if I save it "None Selected" it is ok, no displayed.
The problems seems in the update from 3.6.5 to 3.7.0 this parameter no value by default in "None Selected"

**Comment by ron4mac** [comment] 2017-04-29 13:50
@AlexRed Great! thanks for discovering that.  Problem (mostly) solved!

**Comment by stellainformatica** [comment] 2017-04-29 14:03
I confirm the issue, by default the captcha should not be displayed if the parameter is set to "None Selected", even if the Content's Options has never been saved.
Moreover, who has a template different from Protostar, don't see the captcha and it's not possible to send articles from frontend, but they can't understand why...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15666">issues.joomla.org/tracker/joomla-cms/15666</a>.</sub>

**Comment by infograf768** [comment] 2017-04-29 17:52
I confirm the issue.
It looks like the code checks only if captcha is implemented in the global configuration:
`$captchaSet = $params->get('captcha', JFactory::getApplication()->get('captcha', '0'));`

**Comment by Bakual** [comment] 2017-04-29 18:43
Looks like the code was copied from com_contact, but we have a different default value here and thus it doesn't work. There are two issues here:
* The default value specified in the XML doesn't match the one set in the code ("default" is here the global setting)
* You can't select "- Use Default -" in that option.

The only possible fix is https://github.com/joomla/joomla-cms/pull/15687 which means it will take the global setting by default like in the other places.

Closing as there is a PR to test.

**Comment by Bakual** [comment] 2017-04-30 20:30
Reopening since requested in https://github.com/joomla/joomla-cms/pull/15687#issuecomment-298254410

However I don't think there is a way to solve this.

**Comment by andrepereiradasilva** [comment] 2017-06-07 17:32
made a PR that does not solve this issue in particular (which i also doubt there is a way to solve) but instead gives a little more information to what captcha system is being applied.
See https://github.com/joomla/joomla-cms/pull/16573

**Comment by brianteeman** [comment] 2017-08-18 17:19
Closed

**Closed by brianteeman** 2017-08-18 17:19 UTC
Labels: No Code Attached Yet
