### ISSUE TITLE
[5.0]Issue with ButtonsRegistry.php

### ISSUE THREAD

**Issue by joeforjoomla** [joomla/joomla-cms#41779] opened 2023-09-17 11:01 UTC
### Steps to reproduce the issue
Open an article edit

### Expected result
 Joomla\CMS\Editor\Button\Button::__construct(): Argument #3 ($options) must be of type array, string given, called in /var/www/vhosts/test.storejextensions.org/httpdocs/5x/libraries/src/Editor/Button/ButtonsRegistry.php on line 142

### Actual result

![image](https://github.com/joomla/joomla-cms/assets/17835460/e0a04a45-cba4-4e22-9a63-d5eb67b8d707)

**Comment by Fedik** [comment] 2023-09-17 14:32
I cannot reproduce.
Need more details how you get it.

**Comment by joeforjoomla** [comment] 2023-09-17 20:27
Upgrading from 4.3 to 4.4 to 5.0

PHP 8.1

**Comment by HLeithner** [comment] 2023-09-18 07:16
@joeforjoomla I think we need some more information, like did you have installed any 3rd party buttons? if yes which one?

**Comment by joeforjoomla** [comment] 2023-09-18 08:50
@HLeithner it seems the issue was caused by the button of Convert Forms.

**Comment by HLeithner** [comment] 2023-09-18 09:04
can we get this button somehow to replicate and fix this?

**Comment by joeforjoomla** [comment] 2023-09-18 09:58
Try to install Convert Forms on J4.3, then upgrade to 4.4 and to 5.0

**Comment by joeforjoomla** [comment] 2023-09-18 10:00
![image](https://github.com/joomla/joomla-cms/assets/17835460/c720a649-20e8-473c-a056-c3132afaeacb)

**Comment by Fedik** [comment] 2023-09-18 10:17
It require registration to download

**Comment by Fedik** [comment] 2023-09-18 10:27
I can guess there something like this https://github.com/joomla/joomla-cms/pull/41786
Please test

**Comment by Fedik** [comment] 2023-09-18 14:00
So I closing this one, since the PR is merged. 
Thanks!

**Closed as completed by Fedik** 2023-09-18 14:00 UTC
Labels: No Code Attached Yet, Information Required

**Comment by crimle** [comment] 2023-09-21 13:26
I am encountering this error message as well, but I do not have Convert Forms installed.

Click Content > Articles > New

Error message is:

Joomla\CMS\Editor\Button\Button::__construct(): Argument #3 ($options) must be of type array, string given, called in /home/sites/2a/5/5004ecfce3/jtest/libraries/src/Editor/Button/ButtonsRegistry.php on line 142 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41779">issues.joomla.org/tracker/joomla-cms/41779</a>.</sub>

**Comment by Fedik** [comment] 2023-09-21 13:34
This is fixed in upcoming beta release

**Comment by HLeithner** [comment] 2023-09-21 13:44
@crimle can you please test with https://ci.joomla.org/artifacts/joomla/joomla-cms/5.0-dev/DRONE_PULL_REQUEST/downloads/70471/ version
