### ISSUE TITLE
MOD_LOGGED="Logged-in Users" string isn't passing for translation...

### ISSUE THREAD

**Issue by joaobsantos** [joomla/joomla-cms#7917] opened 2015-09-20 19:57 UTC
Hi guys, sorry to bother but im new at this, i have this problem that in my language translation the 3 strings indicated on the image are not passing, they're returning the string title from __modules in the mysql database. I followed the problem to (/administrator/templates/isis/html/modules.php-line 63). I dont know how to put a jstring with a variable for each module... I think this is a problem becouse even in english we have files for that strings... Thx

![capture](https://cloud.githubusercontent.com/assets/14371776/9982581/1f080a90-5fd9-11e5-90dd-a4422fd2bd37.JPG)

**Comment by mbabker** [comment] 2015-09-20 21:50
If that's the module's title as set in the manager, then that's expected behavior.  Same concept for frontend modules applies to the admin too; the title is user input and isn't translated.

**Comment by joaobsantos** [comment] 2015-09-20 21:55
In previous versions it was translated, and in this version there are translation files for it, in en-GB admin files... the only thing missing is the jtext string....

**Comment by MAT978** [comment] 2015-09-20 22:02
Nope, in previous version they were not "Translatable" except changing manually the Titles as they are admin Modules like Michael said.
Go to: Extensions -> Modules 
then filter 'Administrator'

**Comment by joaobsantos** [comment] 2015-09-20 22:12
ok thanks for your time guys, i see what u mean... have a nice day :D

**Comment by wilsonge** [comment] 2015-09-21 00:30
Closing as issue is solved :)

**Closed by wilsonge** 2015-09-21 00:30 UTC

**Comment by infograf768** [comment] 2015-09-21 07:26
In fact, we DID have this feature in 2.5, but not with this string.
It was:
```
MOD_LOGGED_TITLE="Last Logged-in Users"
MOD_LOGGED_TITLE_1="Last Logged-in User"
MOD_LOGGED_TITLE_MORE="Last %s Logged-in Users"
```
Code used:
```
	public static function getTitle($params)
	{
		return JText::plural('MOD_LOGGED_TITLE', $params->get('count'));
	}
```
result:
![screen shot 2015-09-21 at 09 22 43](https://cloud.githubusercontent.com/assets/869724/9986959/ad3724c2-6042-11e5-928d-fbf1e2c03370.png)

For a reason that ignore, this was changed in 3.x...

**Comment by joaobsantos** [comment] 2015-09-21 08:44
Oh thank u :D Any chance they could revise this?!

**Comment by infograf768** [comment] 2015-09-21 09:54
On it.

**Comment by joaobsantos** [comment] 2015-09-21 10:03
Thank u so much for your time.... have a nice day :D

**Comment by infograf768** [comment] 2015-09-21 10:08
Please test https://github.com/joomla/joomla-cms/pull/7925

**Comment by joaobsantos** [comment] 2015-09-21 11:25
Thank u so much infograf768, you are a life savior... working like a charm... One last question is this now part of joomla installation or only your branch?! im new at programming and github...

**Comment by Bakual** [comment] 2015-09-21 12:08
If the PR gets tested and PLT decides to implement it, it will be part of Joomla. But earliest at 3.5 since it's a new feature.

**Comment by joaobsantos** [comment] 2015-09-21 12:10
ok thx guys... thx for your work... Im hopping to learn more and more about joomla development...
