### ISSUE TITLE
Component is not Ordering with Modules

### ISSUE THREAD

**Issue by brugino** [joomla/joomla-cms#13954] opened 2017-02-06 16:32 UTC
### Steps to reproduce the issue
Image issue 

![issue-breadcrump](https://cloud.githubusercontent.com/assets/24762832/22655552/cbc39a0c-ec90-11e6-85dd-9e45b6c07b6a.JPG)

### Expected result

Image Expected

![issue-breadcrump-expected](https://cloud.githubusercontent.com/assets/24762832/22655583/ec03d0f2-ec90-11e6-9144-ea8ee1dc1fcb.jpg)

### Actual result

![issue-breadcrump](https://cloud.githubusercontent.com/assets/24762832/22655552/cbc39a0c-ec90-11e6-85dd-9e45b6c07b6a.JPG)

### System information (as much as possible)

Joomla 3.6.5

### Additional comments

My idea is not to display the components in the frontend, but to use them as a library of modules and display only the modules.

Very often we find ourselves in difficulty in the display of content that are placed directly into the tmpl component files and then displayed together with other modules.

I think it is much easier to use the content and modules for displaying tmpl and have done by the components only the storage of data in administration work.

Each component must have an associated module for displaying the contents of that part, and I can create different modules of the same component in the categories you selected.

I hope I have expressed my thoughts well

**Comment by tonypartridge** [comment] 2017-02-06 23:06
I'm struggling to see what the problem is here? I see the module is under phoca but this is either a template or a component problem?

Components are designed to be a main view. That's the whole point of them. Then you have modules for ordering content as you wish.

**Comment by brugino** [comment] 2017-02-06 23:42
I apologize for having put the first title that I found before (Phoca Gallery Images). It does not have anything to do with it

It can be seen that the copyright bottom Simple File Manager, this is not a module, but a component 

If I want to order in a way that I view the list of modules in position-2, the component is always positioned at the top, above all modules

What do we need to view components, when we can use the associated modules to display their content?

If I go to the backend to order a component under a module, I can not find to the right in the sort list.

**Comment by mbabker** [comment] 2017-02-06 23:47
The actual component output cannot be ordered through the module manager.  You have to adjust your template for that.  You can assign modules to various positions in the template to make it look like the output is ordered a certain way (i.e. a lot of templates have a position above the component output and below it).

**Comment by brugino** [comment] 2017-02-07 08:02
What I think I would like to see joomla, it is to differentiate the tasks of the various elements.

There is much confusion in the code when both the modules that components, working with the same name and emìntrambi both in administration and in frontend.

I believe that the components must work in backend and frontend modules, so there is no need to intervene every time the template code for structural changes.

This makes much more open and flexible system for all users.

Why do I say this?

I'm finding great difficulty in using a component that has the display of content, and I'm not order these as I would like. In addition there is also a module that takes the contents inserted by the component, but does not allow me to see the content in the same way. They have to re-create the same code of the component in the module.

Copisco also that there may be many to buy, having made no purchases of this kind, I can not run the risk of finding myself in the same issue and have spent some money.

If I know that when I need one of these, I can be sure that it works the way I want. All this also for the benefit of developers who create components and modules to pay.

Management and Data Entry:
-- administrator
   |-- components
       |-- com_mycomponent_helloworld  --|
                                                                   |
Get Data and Visualization:                        |
-- site                                                          |
   |-- modules                                              |
       |-- mod_mymodule_helloworld  ------|

My system is more flexible in the same position and I do not need to make other changes to the code

**Comment by tonypartridge** [comment] 2017-02-07 08:11
In this scenario you want to look at page builders. Joomla! Since it is down to the template solely how it handles the frontend output. Yootheme pro may be what you are looking for.

But this isn't a core issue. The component must always be rendered on its URL for many reasons the layout of the frontend is template driven. To add the component into a module position just isn't practical by the core but you could always look at components anywhere by regular labs.

**Comment by brugino** [comment] 2017-02-07 08:56
> To add the component into a module position just isn't practical by the core

Perhaps the scheme that I created does not make it a good idea, is not the component that goes into the module, but the module through the data entered into the database, which displays the contents inserted by the component.

The component is completely separated from the associated module, the component inserts the data into the database and the module get data and displays them.

**Comment by mbabker** [comment] 2017-02-07 13:32
Joomla's frontend can't be 100% module driven.  The routing system requires a component to direct the task to.  If you really don't want a component active on your page, there are a couple of components floating around out there which are basically stubs to satisfy the requirement of routing to a component without actually doing anything meaningful (like rendering a view, reading from the database, etc.).

**Comment by Bakual** [comment] 2017-02-07 15:23
Closing as this can be achieved with the right 3rd party extensions.

**Closed by Bakual** 2017-02-07 15:23 UTC
Labels: No Code Attached Yet
