### ISSUE TITLE
[4.3.4] Router doesnt use Itemid

### ISSUE THREAD

**Issue by pioada** [joomla/joomla-cms#42125] opened 2023-10-12 11:44 UTC
### Steps to reproduce the issue
I need 2 news categories (each for different school type) and one category to show all news.
I created category "news" with all news and used tags to split them for different school types.
Menu structure:
- News (all)
- School type 1:
- - News of school type 1 (with tag 'School type 1').
- School type 2:
- - News of school type 2 (with tag 'School type 2').

It separates articles well but in "News of school type 1" and "News of school type 2" menu element (category view) all links to articles redirects to "News (all)" menu item.
It looks like Itemid is not used.

### Expected result
All links to articles should keep Itemid (current menu item).
System should try to find link for current Itemid first, and if  not found then search all menus for best fit.

### Actual result
System dont use Itemid, it always takes first menu item with category "news" and redirect to that element. That changes SEF URL, breadcrumbs, etc.

### System information (as much as possible)
Joomla 4.3.4

**Comment by Hackwar** [comment] 2024-03-22 21:43
This is actually expected behavior. The tags don't influence the routing and if you want to achieve what you describe, you have to create 2 subcategories in your news category and link them in the respective menu item. Since this is expected behavior, I'm closing this issue.

**Closed as completed by Hackwar** 2024-03-22 21:43 UTC
Labels: No Code Attached Yet
