### ISSUE TITLE
User Custom Fields [text] for registration form are always disabled regardless of status on the backend.

### ISSUE THREAD

**Issue by chetanmadaan** [joomla/joomla-cms#14744] opened 2017-03-19 07:41 UTC
### Steps to reproduce the issue
Go to Joomla backend >> Users >> Fields and Create a new Field (text, colorpicker or textarea) and add them to the registration form (with or without creating a group).

### Expected result
text fields should only be disabled when the user select them to be disabled but only the editor field seems to be enabled.
![image](https://cloud.githubusercontent.com/assets/3968575/24079064/675d18ba-0c55-11e7-8c66-f3434428e79b.png)

### Actual result
Disabled Fields
![image](https://cloud.githubusercontent.com/assets/3968575/24079066/724fc9fc-0c55-11e7-9cfd-0233e2406f46.png)
Tested in Firefox & Chrome
Editor fields seems to work
text input, color picker & textarea don't.

### System information (as much as possible)
php: Windows NT MY-PC 6.1 build 7601 (Windows 7 Professional Edition Service Pack 1) i586
dbversion: 5.5.5-10.1.21-MariaDB
dbcollation: utf8_general_ci
dbconnectioncollation: utf8mb4_general_ci
phpversion: 5.6.30
server: Apache/2.4.25 (Win32) OpenSSL/1.0.2j PHP/5.6.30
sapi_name: apache2handler
version: Joomla! 3.7.0-beta3 Beta [ Amani ] 21-February-2017 15:03 GMT
platform: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
useragent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

### Additional comments
I created a video of the whole process https://www.dropbox.com/s/717zgayo90d7064/joomla37customfields.mp4?dl=0

This might have already been reported so feel free to merge it or otherwise.
Similar Issue on the forum: https://forum.joomla.org/viewtopic.php?f=706&t=948218

**Comment by Bakual** [comment] 2017-03-19 07:47
That's a permission setting.
You need to make sure the "Public" group has the "Edit Custom Field Value" set to "Allowed" (check "Permissions" tab of your custom field). Then visitors will be able to edit values in that field.

I'm closing this issue since it is a misconfiguration, not a bug.,

**Closed by Bakual** 2017-03-19 07:47 UTC
Labels: No Code Attached Yet

**Comment by chetanmadaan** [comment] 2017-03-19 07:54
Confirmed... Silly me.

Shouldn't that be the default setting?

**Comment by Bakual** [comment] 2017-03-19 12:12
No, by default permissions have to be disabled, not enabled. It depends on the context if it public should be able to edit something, basically it would only be for registration fields and the contact formular where public should be allowed to edit the value. All other cases we expect at least a registered user or even higher rights.

**Comment by ilmoralito** [comment] 2019-12-23 16:13
Thanks bakul, your comment works for me
