### ISSUE TITLE
Path in error message missing

### ISSUE THREAD

**Issue by pl71** [joomla/joomla-cms#43105] opened 2024-03-21 05:28 UTC
### Is your feature request related to a problem? Please describe.
Deleting search component from Joomla 5 installation.
Received the following message (along with successful deinstall):
**`Joomla\Filesystem\File::delete: Failed deleting inaccessible file en-GB.pkg_search.sys.ini`**
![lang-missing](https://github.com/joomla/joomla-cms/assets/4776779/a38ea574-fd50-416e-8460-868d55742828)

### Describe the solution you'd like

I would like to know where the subject file is located - path, folder, whenever you call it.
Nice to also have a button with a copy-to-clipboard function for subject messages.
I am an administrator, but anyway...

### Additional context
J 5.0.3
Edit: Probably a bug? Is it possible component to be fully removed, and after that Joomla to search for some files?
I have no time and capacity for investigation, sorry.
Administrator language is bg-BG 4.3.3 (possible localization bug)

**Comment by Kostelano** [comment] 2024-03-21 08:21
> I would like to know where the subject file is located - path, folder, whenever you call it.

Check here: `SITE\administrator\manifests\packages`. But it's probably no longer there, as the notice says.

**Comment by pl71** [comment] 2024-03-21 09:08
> > I would like to know where the subject file is located - path, folder, whenever you call it.
> 
> Check here: `SITE\administrator\manifests\packages`. But it's probably no longer there, as the notice says.

Yep, there is no such file. Probably this is a component-specific bug and since this search component is no longer maintained in Joomla, there is no reason to investigate. Anyway, two things - 1. This message should contain path information. 2. The message suggests that the subject file exists, but the system has no rights to access/delete it (nice to have different wording here).

**Comment by richard67** [comment] 2024-04-03 09:39
Closing as having a pull request. Please test #43200 . Thanks in advance.

**Comment by richard67** [comment] 2024-04-03 11:51
Re-opening as pull request #43200 has been closed. The issue needs to be fixed in the framework https://github.com/joomla-framework/filesystem . When that has been done, a PR has to be made here for updating the framework dependency in the CMS.

I suggest to leave this issue here open until the latter PR has been created.

**Comment by Quy** [comment] 2024-04-03 13:06
This should be reported in the framework. I would close it as it is not a bug per se, but an improvement. It may take a while for a new release so no point in keeping this around that nothing can be done until then.

**Comment by richard67** [comment] 2024-04-03 13:18
> This should be reported in the framework.

Done. See https://github.com/joomla-framework/filesystem/issues/64 .

> I would close it as it is not a bug per se, but an improvement.

Ok, closing here.

**Closed as completed by richard67** 2024-04-03 13:18 UTC
Labels: No Code Attached Yet, bug
