### ISSUE TITLE
Enable SEF Defaults Pages to Default Template

### ISSUE THREAD

**Issue by nashsclay** [joomla/joomla-cms#28358] opened 2020-03-15 21:04 UTC
### Steps to reproduce the issue
Admin Panel -> Global Configuration -> SEO Settings -> Search Engine Friendly URLs -> Yes
Admin Panel -> Global Configuration -> SEO Settings -> Use URL Rewriting -> Yes
Save Settings
Assing Menu Item to different template other than default
Save Changes
Refresh page, page opens with default template and not choosen other template

### Expected result
Choosen alternate template to open with page

### Actual result
Default template opening with page

### System information (as much as possible)
AWS Server
Linux 4.4.0-1102-aws x86_64
Using Bitnami Software for Joomla

**Comment by ReLater** [comment] 2020-03-15 21:38
I can't reproduce this issue with Joomla 3.9.17-dev or 3.9.16 but I know that there are 3rd party extensions that are the reason for this misbehavior. Mostly system plugins.

**Comment by jwaisner** [comment] 2020-03-17 14:15
Closing at this is not reproducible. Please check the forums as this could be related to a 3rd party extension, not the Joomla core.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28358">issues.joomla.org/tracker/joomla-cms/28358</a>.</sub>

**Closed as completed by jwaisner** 2020-03-17 14:15 UTC
Labels: No Code Attached Yet
