### ISSUE TITLE
[4.0] no sub menu items

### ISSUE THREAD

**Issue by josflachs** [joomla/joomla-cms#19526] opened 2018-02-02 02:21 UTC
I try to create a drop-down menu, but it's not clear how to create sub menu items. As far as I a can tell, there is no way to do that.

**Comment by Quy** [comment] 2018-02-02 03:51
Is this for v3 or v4? Please see if this a duplicate of #18633.

**Comment by ghost** [comment] 2018-02-02 07:00
@Quy Build "alpha 2", so Joomla4.

@josflachs can you please explain your Issue and give required System Informations? As i see there is the same Way to create Submenus as in Joomla 3.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19526">issues.joomla.org/tracker/joomla-cms/19526</a>.</sub>

**Comment by josflachs** [comment] 2018-02-02 08:01
Correct, it was Alpha 2. I downloaded the latest version: https://github.com/joomla/joomla-cms/tree/4.0-dev. I figured out how to create sub-menu items: you have to set the parent id number. That's probably going to be replaced soon, as I cannot see an average user setting menu items by id number. In the latest version I got the menu items are stacked up down, not left - right. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19526">issues.joomla.org/tracker/joomla-cms/19526</a>.</sub>

**Comment by ghost** [comment] 2018-02-04 06:31
closed as duplicate Report #18633

**Closed as completed** 2018-02-04 06:31 UTC
Labels: No Code Attached Yet
