### ISSUE TITLE
[4.0] No Admin Dashboard for System

### ISSUE THREAD

**Issue by 200MPHMEDIA** [joomla/joomla-cms#28287] opened 2020-03-09 12:10 UTC
### Steps to reproduce the issue

Every section of the HOME DASHBOARD as the option to open a specified dashboard for all except the SYSTEM.  Would it not seem logical to INCLUDE a "dashboard" option for the "System?"  Seems irregular to NOT have a quick access to the Dashboard for the System, in the same manner as the others, including a drop down of sub-content.  Submitting this to get hammered with reasons why "it is the way it is."

**Comment by brianteeman** [comment] 2020-03-09 17:07
Sorry - I have read this twice and still don't understand your question

**Comment by Quy** [comment] 2020-03-09 17:26
I assume a dashboard icon here and list submenus under System in the sidebar navigation.

![system-dashboard](https://user-images.githubusercontent.com/368084/76240231-1de7d780-61f0-11ea-9fed-24fa34178b56.jpg)

**Comment by brianteeman** [comment] 2020-03-09 17:39
IF that is the question then the answer is
1. The system link is already a link to the dashboard so no need for another (same with help)
2. If you want a list of every menu item in there it will be a very very long list (which is why its a dashboard in the first place

**Comment by jwaisner** [comment] 2020-03-09 21:17
Closing as expected behavior.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28287">issues.joomla.org/tracker/joomla-cms/28287</a>.</sub>

**Closed as completed by jwaisner** 2020-03-09 21:17 UTC
Labels: No Code Attached Yet

**Comment by ReLater** [comment] 2020-03-10 09:06
I vote for reopening this issue.

> If you want a list of every menu item in there it will be a very very long list (which is why its a dashboard in the first place

Not an argument for me. There are 8 main menu items in the system dashboard. If you install 1, 2, 3 additional components with sub menus the component menu gets long lists, too.

We have scrollable accordions in the sidebar.

Example: It's completely annoying to go to Plugins or Templates via several clicks back and forth via several new pages instead via sidebar. Horrible UIX. It's not my first day with J4 and I'm still searching again and again endlessly instead of testing.

And it's completely inconsistent behavior.

**Comment by brianteeman** [comment] 2020-03-10 09:17
Use the alternative menu then

**Comment by ReLater** [comment] 2020-03-10 09:34
Instead of having a intuitively useable backend as default backend?

There are no good arguments to not expand the System menu item like others.

**Comment by TobsBobs** [comment] 2020-03-10 09:46
I think @ReLater is correct. It's useful.

**Comment by brianteeman** [comment] 2020-03-10 09:48
It is a master of opinion.

The logic was that these are not daily operations.

**Comment by ReLater** [comment] 2020-03-10 10:58
> The logic was that these are not daily operations.

While building up a Joomla page things like Plugins, Templates, Extensions, Install are used a lot. And one have to switch pages back and forth. Building up a Joomla are the first steps for any user, also newbies. That's the reason why I think any "corner" should be findable intuitively and quickly in a consistent way.

Again: I'm not a newbie and all I wanted to do today was testing a plugin pr in a fresh J4. Install patchtester component, apply patch, discover extensions, install, activate plugin and so on. I know why I interrupted the work to ask for reopening this issoe ;-)

**Comment by brianteeman** [comment] 2020-03-10 11:46
You proved my point. None of that is a daily task.

**Comment by mbabker** [comment] 2020-03-10 12:33
I still vehemently disagree with basically hiding a good chunk of the admin under a second level dashboard because “this is not a daily function on the website”.

When I’m in Joomla sites I spend a lot of time in global config, extension manager, plugins, and add-on components like forms or backup.  My time isn’t spent in the user manager, or articles, or modules, or the other spots someone arbitrarily decided was the most important administrative functions.  Can that crap be buried under a second level dashboard instead?

**Comment by brianteeman** [comment] 2020-03-10 12:37
Thats why we have custom menus
