### ISSUE TITLE
Front End Editing won't save

### ISSUE THREAD

**Issue by diananashif** [joomla/joomla-cms#17353] opened 2017-07-30 20:10 UTC
### Steps to reproduce the issue
Login to front end and select an article. click the edit icon to access the content editor.  Make changes, hit save, window blinks and you see the saved edits in the editor.  Next go an view the article and the edits are not there.

FYI before the Joomla update, when I would hit the save button, it would take me back to the article and not stay in the editor.

### Expected result
Edits get saved

### Actual result

no edits saved

### System information (as much as possible)
Joomla 3.7.4 
site is:  [https://standupgirl.com](https://standupgirl.com )

![sug-system-info](https://user-images.githubusercontent.com/10245004/28756692-45ada82e-7528-11e7-86d4-6d46251adc16.png)

### Additional comments
This started after the Joomla core update before 3.7.4.  Was hoping 3.7.4 would fix it but nope,

**Comment by zero-24** [comment] 2017-07-30 20:24
Can you please double check that your have deleted all cached js files? I can not reproduce this on my own site.

**Comment by Bakual** [comment] 2017-07-30 21:48
Please also check with the Protostar template, just to be sure it's not something template specific.
Since you didn't mention any error or success message, did you get one of it?

**Comment by diananashif** [comment] 2017-07-30 21:59
zero-24, all cache was cleaned.  

Bakual.....No I haven't switched to the Protostar because I always have guests using the site.

No error messages either

**Comment by diananashif** [comment] 2017-07-30 22:03
Also you know when you have a spelling error and the word is underlined with red dots and you can right click to select the correct spelling......that is not working anymore either.

One more thing, I have Kunena forum installed and this issue doesn't effect editing a forum post. Only happens with Joomla articles.

**Comment by diananashif** [comment] 2017-07-30 22:32
I switched to Protostar and the issue still happens...........any other suggestions?

**Comment by diananashif** [comment] 2017-07-30 22:54
Update.......after more testing with protostar only on the Real Stories page, you are right, the issue does not happen.  So that does confirm it is a template issue.  

Thank you for helping me today......cheers,
Diana

**Comment by ghost** [comment] 2017-07-31 05:01
closed as no Core Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17353">issues.joomla.org/tracker/joomla-cms/17353</a>.</sub>

**Closed as completed by ghost** 2017-07-31 05:01 UTC
Labels: No Code Attached Yet
