### ISSUE TITLE
[4.0] Using multiple editors with editor-xtd buttons on a single page outputs erratic string

### ISSUE THREAD

**Issue by avjoomla** [joomla/joomla-cms#18519] opened 2017-11-07 16:56 UTC
### Steps to reproduce the issue
On Joomla! 4.0 dev
open administrator/components/com_content/forms/article.xml
add second editor field
```
<field
				name="articletext2"
				type="editor"
				label="COM_CONTENT_FIELD_ARTICLETEXT_LABEL"
				filter="JComponentHelper::filterText"
				buttons="true"
		/>
```
open administrator/components/com_content/tmpl/article/edit.php
add code to display the additional field after
```
<fieldset class="adminform">
					<?php echo $this->form->getInput('articletext2'); ?>
                </fieldset>
```
for example after 
```
<fieldset class="adminform">
					<?php echo $this->form->getInput('articletext'); ?>
				</fieldset>
```
Go to administration of the website, create a new article
### Expected result
the second editor field looks exactly like the first

### Actual result
Under the second editor field you can find an erratic string
Joomla\CMS\Object\CMSObjectJoomla\CMS\Object\CMSObjectJoomla\CMS\Object\CMSObjectJoomla\CMS\Object\CMSObjectJoomla\CMS\Object\CMSObjectJoomla\CMS\Object\CMSObjectJoomla\CMS\Object\CMSObject

Status

Category *
Editor

Featured
 No
Access

Language

Tags

Select Some Options
Version Note
This issue

### System information (as much as possible)
Php 7.1.7 on local Xampp on windows 7
Joomla! 4.0.0-dev Development [ Amani ] 31-March-2017 23:59 GMT
(Hopefully the latest version. I downloaded this morning from Github and no matter which options I choose for the Joomla! Update component, I already get the message that I have the latest version).

### Additional comments
I'm pretty sure, that the problem is related to the editor buttons, which are created as objects of class Joomla\CMS\Object\CMSObjectJoomla. It looks to me, that the erratic string has as many repetitions of this class as the first editor has buttons. When I add a third or forth editor, the string grows even longer.

**Comment by ghost** [comment] 2017-11-09 08:37
@mbabker should this be added to [Projects](https://github.com/joomla/joomla-cms/projects)?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18519">issues.joomla.org/tracker/joomla-cms/18519</a>.</sub>

**Comment by OctavianC** [comment] 2018-01-30 07:05
Seems related to my MR #19454 
Changing this line:
https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Editor/Editor.php#L313
To
```php
$plugin = clone \JPluginHelper::getPlugin('editors', $this->_name);
```
Might solve this.

**Comment by avjoomla** [comment] 2018-01-30 09:13
Hi,
sadly it does not.
Regards,
Aicha

**Comment by mavrosxristoforos** [comment] 2018-03-29 17:10
I can confirm this issue. The `$results` from this line https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Editor/Editor.php#L199 are correct the first time, including only a HTML string to show the editor, but each consecutive time they also contain a few objects `(Joomla\CMS\Object\CMSObject)` (7 in my case) that quite interestingly are some of the buttons of the editor: Module, Menu, Contact, Article, Image, Page Break and Read more...

There's a loop right after this line, that builds a string `$return`.
If that is changed to only return `$results["result"][0]` it does work, but I'm not sure that this is a proper solution...

**Comment by joeforjoomla** [comment] 2018-03-29 17:17
Issue confirmed too...

**Comment by Quy** [comment] 2018-06-07 00:27
Duplicate of #20679 ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18519">issues.joomla.org/tracker/joomla-cms/18519</a>.</sub>

**Comment by ghost** [comment] 2018-06-07 10:03
closed in favor of #20679.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18519">issues.joomla.org/tracker/joomla-cms/18519</a>.</sub>

**Comment by astridx** [comment] 2018-06-24 20:42
@franz-wohlkoenig I made a mistake. This issue is not solved with the PR to this issue https://github.com/joomla/joomla-cms/issues/20679. Can you please reopen this issue again?

**Comment by ghost** [comment] 2018-06-25 04:03
Reopened as stated above.

**Comment by brianteeman** [comment] 2018-10-14 22:52
I can no longer replicate this issue - can only assume it has been resolved elsewhere

**Closed as completed by brianteeman** 2018-10-14 22:52 UTC
Labels: No Code Attached Yet, J4 Issue
