### ISSUE TITLE
behavior.php initializate instanse of class JCaption() but it's function in caption.js

### ISSUE THREAD

**Issue by ivsero** [joomla/joomla-cms#9618] opened 2016-03-27 11:31 UTC
#### Steps to reproduce the issue
https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/html/behavior.php contain the following code:
```php
// Attach caption to document
JFactory::getDocument()->addScriptDeclaration(
	"jQuery(window).on('load',  function() {
	new JCaption('" . $selector . "');
	});"
);
```
but in https://github.com/joomla/joomla-cms/blob/staging/media/system/js/caption.js JCaption - now is function:
```js
var JCaption = function(c) {
    var e, b, a = function(f) {
            e = jQuery.noConflict();
            b = f;
            e(b).each(function(g, h) {
                d(h)
            })
        },
        d = function(i) {
            var h = e(i),
                f = h.attr("title"),
                j = h.attr("width") || i.width,
                l = h.attr("align") || h.css("float") || i.style.styleFloat || "none",
                g = e("<p/>", {
                    text: f,
                    "class": b.replace(".", "_")
                }),
                k = e("<div/>", {
                    "class": b.replace(".", "_") + " " + l,
                    css: {
                        "float": l,
                        width: j
                    }
                });
            h.before(k);
            k.append(h);
            if (f !== "") {
                k.append(g)
            }
        };
    a(c)
};
```
#### Expected result
I expect to see class in caption.js or function call in behavior.php

#### Actual result
As a result some functions doesn't work correctly. We have the following code:
```js
<script language="javascript" type="text/javascript"> 
$(document).ready(function () { 
 
$('a.menu_class3').click(function () { 
$('ul.the_menu3').slideToggle('medium'); 
 
}); 
}); 
</script>
```
Now object $('ul.the_menu3') is null and we see error-message in browser developer console:
```js
TypeError: $(...) is null.
```
When we replace older version of caption.js from Joomla 3.1.5 (where JCaption() - is class) all works correctly.

**Comment by Fedik** [comment] 2016-03-27 11:53
> JCaption - now is function ...
> I expect to see class in caption.js or function call in behavior.php

oh man, I just leave it here 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function

**Comment by Fedik** [comment] 2016-03-27 12:03
And you should not use `$` globally.
The issue is invalid, from my point of view.

**Comment by ivsero** [comment] 2016-03-27 13:30
@Fedik Thank you for links, but I know about "new" operator usage for Function objects in JavaScript.
I'll try to replace code
```js
<script language="javascript" type="text/javascript">
$(document).ready(function () {

$('a.menu_class3').click(function () {
$('ul.the_menu3').slideToggle('medium');

});
});
</script> 
```
on
```js
<script language="javascript" type="text/javascript">
jQuery(document).ready(function () {

jQuery('a.menu_class3').click(function () {
jQuery('ul.the_menu3').slideToggle('medium');

});
});
</script> 
```
and situation has not changed.

**Comment by Fedik** [comment] 2016-03-27 13:54
then please close the issue, because it not Joomla! issue

**Closed** 2016-03-27 13:55 UTC
Labels: No Code Attached Yet
