### ISSUE TITLE
[5.0] Update fontawesome??

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#42028] opened 2023-10-03 13:19 UTC
### Steps to reproduce the issue
Install a clean 4.4 and then set the update component to use https://update.joomla.org/core/nightlies/next_major_list.xml
Perform the update

### Expected result
Everything works and looks the same as a clean install of j5

### Actual result
Problem with some of the icons
### Clean j5
![image](https://github.com/joomla/joomla-cms/assets/1296369/ab06f33c-928b-45d3-9fc2-35746b78381c)
### Updated to j5
![image](https://github.com/joomla/joomla-cms/assets/1296369/b35fb202-3d67-421e-8726-12a79efc5745)

### Additional comments
It is fixed by doing a hard browser refresh **but** that should not be necessary

**Comment by wilsonge** [comment] 2023-10-03 14:39
What's the font awesome version being used in the hash?

**Comment by wilsonge** [comment] 2023-10-03 14:39
Imagine it's going to need a fix similar to https://github.com/joomla/joomla-cms/pull/41841

**Comment by dgrammatiko** [comment] 2023-10-03 18:55
@wilsonge nope, actually I had proposed a solution for this case https://github.com/joomla/joomla-cms/pull/32574

**Comment by brianteeman** [comment] 2023-10-03 19:21
> What's the font awesome version being used in the hash?

it is correct

4.4
![image](https://github.com/joomla/joomla-cms/assets/1296369/0821a8f1-d72e-42bb-b1b2-02a82b1f4716)

5.0
![image](https://github.com/joomla/joomla-cms/assets/1296369/02f91b04-c965-47f3-acb7-7259ad509516)

**Comment by dgrammatiko** [comment] 2023-10-03 19:50
@brianteeman the problem is that the name of the actual font file is the same and it's not hashed inside the font awesome.css...

**Comment by dgrammatiko** [comment] 2023-10-04 10:55
There a patch: #42038

**Comment by richard67** [comment] 2023-10-04 11:32
Closing as having a pull request. Please test #42038 . Thanks in advance.

**Closed as completed by richard67** 2023-10-04 11:32 UTC
Labels: No Code Attached Yet
