### ISSUE TITLE
Configuration file code does not have PHP end tag.

### ISSUE THREAD

**Issue by pranavlawate** [joomla/joomla-cms#10599] opened 2016-05-22 14:47 UTC
#### Steps to reproduce the issue
Complete a Joomla Installation, with configuration file not writable.
Copy the configuration file code shown at the last screen.

#### Expected result
The code displayed should be correct with the required closing tags.

#### Actual result
The code rendered does not have the php end tag ('?>').
Due to this, the site url does not load and shows up a white screen on both frontend and backend.
![screen shot 2016-05-22 at 09 45 45](https://issues.joomla.org/uploads/1/c1eef32dce60258bd0b7948b44519752.png)

#### System information (as much as possible)
Joomla version : 3.5.1
PHP version : 5.6.21
Apache version : Apache/2.4.18 (Fedora)
Server : LAMP

**Comment by Fedik** [comment] 2016-05-22 15:20
Your problem related to the serve configuration I guess. PHP does not nave access to write the file,  on your server setup . You need to correct "write permission" on your server or ask server support.

ps. the closing tag is NOT required.

**Comment by brianteeman** [comment] 2016-05-22 15:43
Closed as not a bug

**Closed by brianteeman** 2016-05-22 15:43 UTC
Labels: No Code Attached Yet
