### ISSUE TITLE
png preview in all media fields not working

### ISSUE THREAD

**Issue by RickR2H** [joomla/joomla-cms#34740] opened 2021-07-08 19:48 UTC
### Steps to reproduce the issue
Go to an article and select a png as intr image

### Expected result
The image sould be displayed

### Actual result
Message: This plugin is not supported

### System information (as much as possible)
WAMP server with PHP8 (Same result on PHP 7.4)

### Additional comments
I made an installation using the git repo on 4 july 2021
At first I thought this was related to my browser as is was a Dutch message.
When you select a JPG <object> becomes <img> tag.

![screen shot 2021-07-08 at 19 46 53](https://issues.joomla.org/uploads/1/cfd330914425627b9d14943676272e77.jpg)

![screen shot 2021-07-08 at 19 43 52](https://issues.joomla.org/uploads/1/22ab0921852d25274d693f260fa49b7c.jpg)

**Comment by chmst** [comment] 2021-07-08 20:49
Confirmed. Also uploading png or PNG is not possible.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34740">issues.joomla.org/tracker/joomla-cms/34740</a>.</sub>

**Comment by brianteeman** [comment] 2021-07-09 16:32
The preview issue is caused by changes in #34634. The png is not being recognised as an image type in `build\media_source\system\js\fields\joomla-field-media.w-c.es6.js` so it falls back to being an `object` which is obviously not correct.

**Comment by brianteeman** [comment] 2021-07-10 16:06
Thsi really should be marked as a release blocker

**Comment by RickR2H** [comment] 2021-07-10 16:16
I agree! This is a major issue!

**Comment by richard67** [comment] 2021-07-10 17:42
@dgrammatiko Can it be the problem is that "png" is also in the default value for the documents extensions and not only the image extensions, e.g. here https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_media/tmpl/file/default.php#L53 or here https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_media/tmpl/media/default.php#L52 , and the documents extensions are checked before the image extensions here https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_media/resources/scripts/components/modals/preview-modal.vue#L34-L45 ?

**Comment by brianteeman** [comment] 2021-07-10 18:05
yes thats it - good spot.

PR on its way

**Comment by brianteeman** [comment] 2021-07-10 18:12
please test #34753

**Comment by richard67** [comment] 2021-07-10 18:20
Closing as having a pull request. Please test #34753 . Thanks in advance.

**Closed as completed by richard67** 2021-07-10 18:20 UTC
Labels: No Code Attached Yet

**Comment by richard67** [comment] 2021-07-10 18:42
> Confirmed. Also uploading png or PNG is not possible.

Uploading PNG works here, I have only the preview issue, and that's solved with PR #34753 .
