### ISSUE TITLE
[4.0] J4 copy template

### ISSUE THREAD

**Issue by rgmears** [joomla/joomla-cms#14409] opened 2017-03-07 18:04 UTC
### Steps to reproduce the issue
Go to templates page and tap on copy template. Add name and save.

### Expected result
The template is copied.

### Actual result
Error messages for both site and administrator templates.

### System information (as much as possible)
Joomla 4

**Comment by C-Lodder** [comment] 2017-03-08 12:13
What's the error?

**Comment by rgmears** [comment] 2017-03-08 13:29
Protostar
Warning
Extension Install: Field 'system_data' doesn't have a default value
Error
Error installing template
Unable to install new template from temporary folder.

Atum
Warning
JInstaller: :Install: File does not exist /home/juxresearch/j4.juxresearch.org/tmp/template_copy_58c006bf11a83/img
Template Install: Could not copy files from the files source.
Error
Error installing template
Unable to install new template from temporary folder.

Both are, however, copied to the tmp folder.

**Comment by rgmears** [comment] 2017-03-08 22:49
I'm not sure about the live installation, but in my local version the less files were missing from media/jui/.
I was having trouble compiling the Protostar css in NetBeans. Copying the files from a J3.6 site fixed the problem.

**Comment by franz-wohlkoenig** [comment] 2017-03-09 07:16
Confirmed Issue:
![bildschirmfoto 2017-03-09 um 08 15 17](https://cloud.githubusercontent.com/assets/8235763/23739719/999c4772-04a0-11e7-8d02-7a328b8048eb.JPG)
#### Test on:
Joomla! 4.0.0-dev
macOS Sierra, 10.12.3
Firefox 52.0 (64-bit)
PHP 7.0.15
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by dgt41** [comment] 2017-03-09 08:00
Protostar will be removed/replaced by a new bootstrap 4 template. To test the copy functionality try to copy the Atum (administrator) template

**Comment by franz-wohlkoenig** [comment] 2017-03-09 08:06
![bildschirmfoto 2017-03-09 um 09 05 12](https://cloud.githubusercontent.com/assets/8235763/23741207/90a0d26c-04a7-11e7-9049-b5626722c7ae.JPG)

**Comment by franz-wohlkoenig** [comment] 2017-03-09 08:07
Can Tester have Info what to test now make Sense or where to Look? Like "Templates" or "Media Manager" not for testing cause ...?

**Comment by dgt41** [comment] 2017-03-09 08:10
@franz-wohlkoenig this is pre-Alpha so expect random failures and glitches all over...
But whatever reported will get fixed, either from the backend or the frontend team

**Comment by franz-wohlkoenig** [comment] 2017-03-09 08:19
got it, thanks @dgt41

**Comment by joomdonation** [comment] 2017-03-11 09:17
Confirmed this issue. Someone good with database skill needs to check the following fields in #__extensions table:
- folder
- params
- custom_data
- system_data

When I look at the data from this table, many records contains empty data for these fields but in the create table command to create this table, these fields are marked as NOT NULL and don't have default value

Maybe @csthomas could help?

**Comment by Bakual** [comment] 2017-03-11 09:32
* **folder** is used for the plugins.
* **params** contains the extension settings (if saved)
* **custom_data** and **system_data** aren't used by core currently. I used the `system_data` column in J2.5 to store compatibility informations to give people a clue what to expect after upgrading to J3. See https://github.com/joomla/joomla-cms/pull/5015. That code could be reimplemented into J3.x of course when J4 is released. I always assumed the `custom_data` is there for extensions to be used for whatever they want to store there.

**Comment by joomdonation** [comment] 2017-03-11 09:38
@Bakual I asked about whether we should set default value for these fields as some records contain empty data for these fields/columns. Since these fields don't have default value (custom_data  in this issue), it causes the issue with saving record - or we will have to add code to set value for this field empty while saving.

**Comment by csthomas** [comment] 2017-03-11 10:08
Take a look at https://github.com/joomla/joomla-cms/pull/14321/files#diff-6c6cf64555b76205d9e9e6451b6d2d3c

It should fix the problem at least in part. Can I ask for RTC (may be another test is required).

**Comment by Bakual** [comment] 2017-03-11 10:30
I never understood why we set "NOT NULL" for an optional field, but I'm not going to argue that anymore :)

The issue is that TEXT fields afaik can't have a default value specified. So the only solution is indeed setting the default value in PHP like @csthomas proposed. Or drop the "NOT NULL" requirement. I'd do the latter but people think for some reason it is important to not have NULL there.

**Comment by csthomas** [comment] 2017-03-11 10:55
> I never understood why we set "NOT NULL" for an optional field

I have this same feeling.

I would set NULL also on every TEXT field, IMO this is the right way.

**Comment by wilsonge** [comment] 2017-03-19 10:48
Should be fixed with the merge of #14750

**Closed by wilsonge** 2017-03-19 10:48 UTC
Labels: No Code Attached Yet
