### ISSUE TITLE
User - Profile plugin erases data when field is disabled from the frontend view

### ISSUE THREAD

**Issue by meichenblatt** [joomla/joomla-cms#9129] opened 2016-02-15 23:31 UTC
#### Steps to reproduce the issue

Enable the user - profile plugin.
Within the plugin, under "User profile fields for registration and administrator user forms" select optional for the "Favorite Book" field.
under "User profile fields for profile edit form", select "disable" for the "Favorite Book" field.
Create a user in the administrator panel and fill in the "Favorite Book" field. 
Go to the front-end, select "edit your profile" and hit submit.
#### Expected result

The "Favorite Book" field should stay the same.
#### Actual result

If you go to the administrator panel the "Favorite Book" field will be empty.

**Comment by brianteeman** [comment] 2016-02-16 11:57
i can confirm this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9129">issues.joomla.org/joomla-cms/9129</a>.</sub>

**Comment by RonakParmar** [comment] 2016-02-23 06:07
I have followed above steps and able to reproduce this issue.
Here is my system information:

Joomla! Version: Joomla! 3.4.8 Stable [ Ember ] 24-December-2015 19:30 GMT
Joomla! Platform Version: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
PHP Version: 5.4.45-3+deb.sury.org~precise+1
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9129">issues.joomla.org/joomla-cms/9129</a>.</sub>

**Comment by bertmert** [comment] 2016-02-23 10:03
Please test https://github.com/joomla/joomla-cms/pull/9196 in-depth.

**Comment by brianteeman** [comment] 2016-02-23 10:04
Closing as we have a Pull Request to test #9196 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9129">issues.joomla.org/joomla-cms/9129</a>.</sub>

**Comment by brianteeman** [comment] 2016-02-24 03:19
Reopened as proposed solution did not resolve the issue and has now been closed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9129">issues.joomla.org/joomla-cms/9129</a>.</sub>

**Comment by franz-wohlkoenig** [comment] 2017-01-29 09:55
Issue exists on Joomla! 3.7.0-staging too.

**Comment by AlexRed** [comment] 2017-03-30 15:09
I can confirm in Joomla! 3.7.0-staging<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9129">issues.joomla.org/tracker/joomla-cms/9129</a>.</sub>

**Comment by gwsdesk** [comment] 2017-04-10 08:03
This might be related with https://issues.joomla.org/tracker/joomla-cms/15194
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9129">issues.joomla.org/tracker/joomla-cms/9129</a>.</sub>

**Comment by zero-24** [comment] 2017-04-14 17:47
closing as @rdeutz did a PR for that. https://github.com/joomla/joomla-cms/pull/15308 Thanks. Please test there!

**Comment by rdeutz** [comment] 2017-04-14 17:53
@zero-24 I fixed something different, I don't think my patch will fix this problem

**Comment by rdeutz** [comment] 2017-04-14 19:46
so fixed this too #15311
closing because we have PR to test

**Closed by rdeutz** 2017-04-14 19:46 UTC
Labels: No Code Attached Yet
