### ISSUE TITLE
Media-Manager deletes all items instead of selected items only

### ISSUE THREAD

**Issue by Mich-es** [joomla/joomla-cms#39226] opened 2022-11-16 14:36 UTC
### Steps to reproduce the issue
Name 5 pictures with 16_xx.jpg
Name 5 pictures with 17_xx.jpg
Upload the 10 pictures into a folder.

In the Media Manager, change to the folder
Search for 16_
Set the check mark
Delete 
![grafik](https://user-images.githubusercontent.com/58422824/202209199-ec144892-3317-493c-882a-92e7641f8fa9.png)

### Expected result

Only the images that I have marked in the search should be deleted - i.e. all with 16_.

### Actual result

All images have been deleted

### System information (as much as possible)
PHP 8.0
J4.2.4

**Comment by brianteeman** [comment] 2022-11-16 17:35
Confirmed

**Comment by ReLater** [comment] 2022-11-18 13:04
> All images have been deleted

And all subfolders if there are some in the directory. While testing I have deleted all images and folders in `images/` by mistake ;-)

From my point of view this should be a release blocker.

**Comment by joomdonation** [comment] 2022-11-19 11:44
@laoneo @dgrammatiko Would be great if you could look at this release blocker issue.

**Comment by chmst** [comment] 2022-11-19 14:05
In all lists this checkbox selects all items. For me it is normal behaviour.

**Comment by brianteeman** [comment] 2022-11-19 14:07
No - the checkbox selects all selected items. Just try it in article manager. Filter by a category. Select all and then delete. Only the items in that category will be deleted.

**Comment by fancyFranci** [comment] 2022-12-12 22:05
Looks like [deleteSelectedItems()](https://github.com/joomla/joomla-cms/blob/485885b0863e82cf6443ae5edf523f80deb49dff/administrator/components/com_media/resources/scripts/store/actions.es6.js#L214) should filter the same way like [browser items()](https://github.com/joomla/joomla-cms/blob/485885b0863e82cf6443ae5edf523f80deb49dff/administrator/components/com_media/resources/scripts/components/browser/browser.vue#L110). Maybe someone is faster in Vue than I am currently.

**Comment by dgrammatiko** [comment] 2022-12-12 22:44
Couple quick observations here:
- There is a missing prop per media item
<img width="1495" alt="Screenshot 2022-12-12 at 23 39 42" src="https://user-images.githubusercontent.com/3889375/207170822-7af602be-2376-4e88-aa54-551b5d57fac0.png">

- The store (search and selectedItems) doesn't ever get updated when anything is selected/typed
<img width="1495" alt="Screenshot 2022-12-12 at 23 40 37" src="https://user-images.githubusercontent.com/3889375/207170930-ee4c3b01-40fb-4211-adec-6d3b9fc51091.png">

**Comment by dgrammatiko** [comment] 2022-12-12 23:06
@fancyFranci there you go: https://github.com/joomla/joomla-cms/pull/39405

**Comment by richard67** [comment] 2022-12-13 07:35
Closing as having a pull request. Please test #39405 . Thanks in advance.

**Closed as completed by richard67** 2022-12-13 07:35 UTC
Labels: No Code Attached Yet, J4 Media Manager, bug
