### ISSUE TITLE
Email Validation (User Registration) - Front end fails

### ISSUE THREAD

**Issue by AMurray2016** [joomla/joomla-cms#18324] opened 2017-10-13 01:07 UTC
### Steps to reproduce the issue
- Registration form loads normally
- Enter the usual details for a new user being registered
- Enter email address (1st time), click/tab to "confirm email" field, the form shows an error as below.

### Expected result
Successful submission with the usual "You will need to validate your email by clicking the link...." message.

### Actual result

Does not submit registration.  Shows error (beneath the first of the two email fields) "Connection failed with status: OK".
This occurs with using Joomla core registration form and also in a third party registration component, Ultimate User Lite edition v 1.8.4 - https://extensions.joomla.org/extensions/extension/access-a-security/site-access/ultimate-user-lite/ as listed on JED.

### System information (as much as possible)
Joomla 3.8.1
PHP 7.0.16

### Additional comments
Don't recall this happening prior to 3.8.x.  I don't know if it's just my system.

I can create users as a Super User in the Administrator.

Also posted on Joomla forum: https://forum.joomla.org/viewtopic.php?f=706&t=955750

Try both registration forms here: https://www.murraywebs.net/dev2/
(links: "Ultimate User Reg" and "Core Joomla Reg") or click "Register" on the login form at foot of the page.

![screen shot 2017-10-13 at 00 42 23](https://issues.joomla.org/uploads/1/e32d2799bc3e671f73c0d74dc06a9435.png)

**Comment by ghost** [comment] 2017-10-13 05:20
Correct Typo in Title.

**Comment by ReLater** [comment] 2017-10-13 06:50
Both of your registration forms are using / calling a non-core component cum_uu (whatever it is) and are using its custom validation. In the email field I see an Ajax call that's the reason for the message:

`data-validation-url="/dev2/component/uu/?task=registration.ajaxCheckEmail&amp;format=json"`

I cannot reproduce the described issue with registration form of Joomla 3.8.1.

**Comment by ghost** [comment] 2017-10-13 09:03
closed as no Core-Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18324">issues.joomla.org/tracker/joomla-cms/18324</a>.</sub>

**Closed as completed by ghost** 2017-10-13 09:03 UTC
Labels: No Code Attached Yet
