### ISSUE TITLE
Own CSS files in Plugins/Modules Backend

### ISSUE THREAD

**Issue by Sh4d0wF1gh7** [joomla/joomla-cms#13611] opened 2017-01-16 13:34 UTC
### Steps to reproduce the issue
Create a own Joomla! module or plugin and add a css/mymodule.css.
Add the stylesheet into the mod_mymodule.php with:
JHTML::stylesheet(JURI::base() . '/modules/mod_mymodule/css/mymodule.css');

### Expected result
Hope that the css file is also loaded in backend to style my fields inserted via mod_mymodule.xml but is not loaded.

### Actual result
CSS file only loaded in frontend.

### System information (as much as possible)
Joomla! 3.6.5

### Additional comments
For public Modules, styling the Backend Template CSS is no option.
Only possible working fact is at the moment creating custom fields to insert CSS or own Styles.

**Comment by SharkyKZ** [comment] 2017-01-17 07:42
I think the issue is with your code and not Joomla. Try this: `JHTML::stylesheet(JURI::root(true) . 'modules/mod_mymodule/css/mymodule.css');`
And it is advised to store media files in media folder.

**Comment by mbabker** [comment] 2017-01-17 13:06
The code's fine.

The `modules/mod_mymodule/mod_mymodule.php` file doesn't get included in the backend editor.  Including that file causes your module to be rendered, that's why you can't include it from the backend.

You should not need to add custom CSS to the backend manager unless you are adding custom fields needing additional styling not offered by the templates.  Personal opinion, but I suggest making use of the admin template theming as much as possible (and with the module manager you're stuck doing just that unless you're adding custom fields) and only adding CSS when you just can't make it work.  Not only is it less of a maintenance overhead for you, but it also keep your extension's management UI fitting in with the rest of the core backend UI so it just feels like a natural part of Joomla.

**Comment by SharkyKZ** [comment] 2017-01-17 13:57
Ignore my previous comment. Misunderstood the issue.

**Comment by Sh4d0wF1gh7** [comment] 2017-01-21 06:16
Hello,
thanks, yes i see, only way are custom fields, but for example, a normal input text field have a other width as for examples the color picker or date picker field. so i thougt, making own width.
or when i have a large label for the field, the field runs out of alignment and is too much right and looks not good.
Think it would be better, if also the module.css is included inside backend view? My personal opinion.

**Comment by franz-wohlkoenig** [comment] 2017-02-05 17:33
@laoneo as this Issue is about com_fields whats your Opinion?

**Comment by mbabker** [comment] 2017-02-05 17:35
This has nothing to do with com_fields.  The custom fields reference is creating your own `JFormField` subclass.

**Comment by franz-wohlkoenig** [comment] 2017-02-05 17:42
thanks @mbabker

**Comment by brianteeman** [comment] 2017-05-21 15:02
I am closing this as the expected behaviour

**Closed by brianteeman** 2017-05-21 15:02 UTC
Labels: No Code Attached Yet
