### ISSUE TITLE
Breadcrumb for Text Separator Menu Item

### ISSUE THREAD

**Issue by rgblogs** [joomla/joomla-cms#7994] opened 2015-10-01 06:22 UTC
#### Steps to reproduce the issue

1. Create a menu item as Text Separator (For example Entertainment)
2. Create a sub menu item linked to Joomla Article or Category (For example Sports)
3. Publish the breadcrumbs module in the front-end.

#### Expected result

The breadcrumbs should be like this:
Home -> Entertainment -> Sports

#### Actual result

Text separator item is missing (see attached image)![screen shot 2015-10-01 at 01 21 44](http://issues.joomla.org/uploads/1/0cda557d97382ad3799c3638b3601a61.png)

**Comment by alikon** [comment] 2015-10-01 07:01
unable to reproduce with current staging works as expected
i've created a menu item as Text Separator (Sports) and submenu item (calcio) with as a Category List
![calcio](https://cloud.githubusercontent.com/assets/181681/10214652/9283ea22-681a-11e5-9f36-15cb5e831b4f.png)

**Comment by rgblogs** [comment] 2015-10-01 08:08
I again tried with clean Joomla 3.4.4. The problem is still there.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7994">issues.joomla.org/joomla-cms/7994</a>.</sub>

**Comment by Fedik** [comment] 2015-10-01 08:12
@rgblogs there was fix already somewhere there #7839 ... please try if it works for you

**Comment by rgblogs** [comment] 2015-10-01 08:17
yes, thanks. so it will be working in 3.4.5 version!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7994">issues.joomla.org/joomla-cms/7994</a>.</sub>

**Comment by infograf768** [comment] 2015-10-01 09:00
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7994">issues.joomla.org/joomla-cms/7994</a>

**Comment by infograf768** [comment] 2015-10-01 09:00
Closing as already solved in core.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7994">issues.joomla.org/joomla-cms/7994</a>.</sub>

**Closed by infograf768** 2015-10-01 09:00 UTC
Labels: No Code Attached Yet
