### ISSUE TITLE
[4.0] Can't Navigate Away from User Mass Mail

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#13915] opened 2017-02-04 18:29 UTC
`administrator/index.php?option=com_users&view=mail`

There's no navigation available.  The only thing I can do is click cancel to go elsewhere.

**Comment by C-Lodder** [comment] 2017-02-05 19:04
This was purposely done. In J3.x all top menu items are disabled, preventing the user from navigating away from the page whilst editing content, unless they specifically cancel. This being the case, it was decided to remove the sidebar as there's no need for it.

**Comment by zero-24** [comment] 2017-02-05 19:10
so this can be closed @C-Lodder ?

**Comment by C-Lodder** [comment] 2017-02-05 19:11
will let @mbabker confirm if he's ok with that first, just incase I'm stupidly missing something.

**Comment by mbabker** [comment] 2017-02-05 19:12
This is an odd page.  It's not really an edit page, so it doesn't need to go through a cancel task to reset things like a regular add/edit page would.  So, I think this one page needs some thinking personally.  For the rest of the add/edit pages, hiding the navigation makes complete sense to me.

**Comment by C-Lodder** [comment] 2017-02-05 19:15
I see where you're coming from, but at the end of the day, it's still editing or creating content. We don't want users to navigate away from the page when doing either unless they specifically "cancel" the task, to prevent accidental loss of work, so IMO, "new" and "edit" would be considered the same

**Comment by brianteeman** [comment] 2017-07-13 19:06
Looking at this one again I think the cancel button to leave the page is perfectly fine

**Comment by brianteeman** [comment] 2018-03-25 11:58
As there have been no other comments I am going to close this as the intended behaviour

**Closed by brianteeman** 2018-03-25 11:58 UTC
Labels: J4 Issue, No Code Attached Yet
