### ISSUE TITLE
[REGRESSION] sort order 

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#9054] opened 2016-02-03 08:31 UTC
#### Steps to reproduce the issue
Log out and clear all cookies
Log back in and go to plugin manager. You will see all the plugins sorted by Type Ascending as shown by the arrow not Type Descending as shown by the dropdown select
![screen shot 2016-02-03 at 02 26 21](https://issues.joomla.org/uploads/1/f590ef07da7d6d52be54f31f6783bfc3.png)

Scroll to the bottom and click 2 on the pagination
![screen shot 2016-02-03 at 02 27 30](https://issues.joomla.org/uploads/1/158ef5fe31ecc247ffda698e35b7505f.png)
Now you will see all the plugins sorted by Type Descending as shown by the arrow AND by the dropdown select

Not tested but I suspect ALL manager views have the same/similar bug where the default value in the dropdown doesnt match the default value in the column headers which is what (i think) is causing the problem - @pe7er I think this was a PR you did?

**Comment by brianteeman** [comment] 2016-02-03 08:57
### Modules
Switches from Position Ascending to Ordering Ascending
### Featured
Switches from ID Descending to Title Ascending
### Contacts
Switches from Title Ascending to ID Descending
### Newsfeeds
Switches from Title Ascending to ID Descending

**Comment by brianteeman** [comment] 2016-02-03 11:05
We have PR for 
Plugins #9060 
Modules #9059 
Contacts #9057 
Newsfeeds #9056 

Thanks @bertmert can you do one for featured as well ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9054">issues.joomla.org/joomla-cms/9054</a>.</sub>

**Comment by bertmert** [comment] 2016-02-03 11:07
See PRs please and test.

**For featured we need a decision first.**

Featured uses function populateState of model ContentModelArticles. There default ordering is hard coded (I don't know why)
parent::populateState('a.id', 'desc');

Shall Featured from now on be ordered also by id descending or by title ascending?

In both cases we have to change the model.or both models.

**Comment by brianteeman** [comment] 2016-02-03 11:09
For featured I would personally go for ordering but I dont really care as long as both settings are the same and we dont get this pagination bug

**Comment by bertmert** [comment] 2016-02-03 11:13
OK, I will see how to manage it.

I just made some quick tests with other PRs. I hope they work.

**Comment by brianteeman** [comment] 2016-02-03 11:14
Already tested them - theyre great

**Comment by bertmert** [comment] 2016-02-03 12:04
See PR for Featured: https://github.com/joomla/joomla-cms/pull/9061

I tried to use ordering ascending as default but another issue occured. No ordering buttons without page reload.
So, it's title ascending as before.

**Comment by brianteeman** [comment] 2016-02-03 12:39
Closing as we have PRs - thanks!!!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9054">issues.joomla.org/joomla-cms/9054</a>.</sub>

**Comment by richard67** [comment] 2016-02-03 13:17
@brianteeman You forgot to close this? ;-)

**Closed** 2016-02-03 13:39 UTC
Labels: No Code Attached Yet

**Comment by pe7er** [comment] 2016-02-06 13:25
@brianteeman I was a week off-the-grid due to the flu.
Yeah, it might have been caused by my PRs. Sorry...

@bertmert Thanks for your PRs!

**Comment by brianteeman** [comment] 2016-02-06 13:31
Hope you are better now -- you must have caught something at Fosdem. See
you next weekend

On 6 February 2016 at 13:25, Peter Martin <notifications@github.com> wrote:

> @brianteeman <https://github.com/brianteeman> I was a week off-the-grid
> due to the flu.
> Yeah, it might have been caused by my PRs. Sorry...
>
> @bertmert <https://github.com/bertmert> Thanks for your PRs!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9054#issuecomment-180764855>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/
