### ISSUE TITLE
[REGRESSION] Template manager file modal

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#9888] opened 2016-04-13 10:08 UTC
#### Steps to reproduce the issue
Current staging only

Go to template manager and templates, select a template and then select new file from the toolbar

#### Expected result
![screen shot 2016-04-13 at 05 07 56](https://issues.joomla.org/uploads/1/bbb4ef3b65f9e7c2657bb56136b72c11.png)

#### Actual result
![screen shot 2016-04-13 at 05 08 15](https://issues.joomla.org/uploads/1/5803ac5581c27acfd77beb86a3f41c85.png)

**Comment by andrepereiradasilva** [comment] 2016-04-13 11:20
something to do with the `modal-body` class it seems

**Comment by andrepereiradasilva** [comment] 2016-04-13 11:58
maybe this one? https://github.com/joomla/joomla-cms/pull/9817/files

**Comment by JoomliC** [comment] 2016-04-13 12:45
@andrepereiradasilva and @brianteeman i've got it!
This issue is not link directly to this, as the issue is due to a wrong selector for modal script: <code>$selector  Unique DOM identifier for the modal. CSS id without #.</code>

There a quick fix for this issue with template edit modals: adding over-flow:hidden to .modal-body class, but this not fix overflow for the modal... I'm searching now where the modal id is set for both buttons folder and file, as modal selector in DOM is isisModal for both, but should be unique : folderModal and fileModal.

So, the srolling script fails as not the good id set as selector...

I'm currently searching for a fix for the template modals ;-)

**Comment by JoomliC** [comment] 2016-04-13 13:50
I've opened a PR only to fix the display issue: https://github.com/joomla/joomla-cms/pull/9897

About the <code>$selector</code> i think there's another issue, as the modal layout always get the same id for each modal ($template-modal) when it should be unique for each modal: collapseModal, folderModal, fileModal, ...

So, the display will be ok, but script used in modal main layout will not have any effect due to the wrong selector DOM identifier for each modal...
Note: i've found this not related issue to the current issue on display, only in the template edition page... (maybe to do the way com_templates manage the modals for buttons... all in the same files, and not in layouts ?...)

**Comment by JoomliC** [comment] 2016-04-14 11:40
Opened a PR (and close https://github.com/joomla/joomla-cms/pull/9897) to fix com_templates PR, as well as display issue.
Now each modal in com_templates template view use JLayouts ;-)
https://github.com/joomla/joomla-cms/issues/9908

**Comment by brianteeman** [comment] 2016-04-14 13:20
Closed as we have a PR for testing - thank @joomlic <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9888">issues.joomla.org/joomla-cms/9888</a>.</sub>

**Closed** 2016-04-14 13:21 UTC
Labels: No Code Attached Yet
