### ISSUE TITLE
[4.0] [Workflow] the function has disappeared in the blog example

### ISSUE THREAD

**Issue by Magnytu2** [joomla/joomla-cms#35129] opened 2021-08-15 09:29 UTC
Hello everyone, the biggest news in Joomla! 4 no longer appears to be present when installing sample data in Blog format. Is it a will or a bug?

In previous RC versions, it was handy to have this example to understand how it works.

I am wrong ?

**Comment by zero-24** [comment] 2021-08-15 09:31
I'm sorry I can not follow you whats the issue you are reporting, what did you do to get the behavior? Could it be that workflow has to be enabled?

**Comment by chmst** [comment] 2021-08-15 09:56
It was intended. The workflow is present but you must enable it in articles options - integration.

**Comment by Magnytu2** [comment] 2021-08-15 10:37
Yes I understand, but the Workflow function was, previously in the RC5 version, installed with the installation of the blog examples.

**Comment by zero-24** [comment] 2021-08-15 12:05
Hmm i can not find any change to the workflow or sampledata introduced between RC5 and 4.0-dev  (https://github.com/joomla/joomla-cms/compare/4.0.0-rc5...4.0-dev) that could cause such change.

Also the last changes to the module (other than an unrelated XML change) are 3-9 month old: 
![image](https://user-images.githubusercontent.com/2596554/129477937-e24dc272-a617-4361-803a-e8a81d88856e.png)

**Comment by richard67** [comment] 2021-08-15 13:00
@Magnytu2 The change not to enable workflow automatically when installing blog sample data was made with PR #31711 . That has been merged on April 17. Release candidate 1 (one) has been released on June 1. So it cannot be right what you say that it was different with previous release candidates. Maybe you meant previous Beta versions?

**Comment by richard67** [comment] 2021-08-15 13:00
@Magnytu2 I suggest you close this issue as expected behaviour. Thanks in advance.

**Comment by Magnytu2** [comment] 2021-08-15 13:05
I know it.  I'm talking about the second phase.  when we install the blog example from the administration.  the blog example integrated the implementation of the workflow

**Comment by richard67** [comment] 2021-08-15 13:06
@Magnytu2 It still does. You can go to the options of com_content and enable workflows in the integration tab after having installed blog sample data.

**Comment by Magnytu2** [comment] 2021-08-15 13:11
it was not necessary to do this in the RC5 version.  Unless I'm wrong.  I find it terribly sad to hide, even in the blog example, the great novelty of Joomla 4. You could do the same for the fields.

**Comment by richard67** [comment] 2021-08-15 13:14
> it was not necessary to do this in the RC5 version.

@Magnytu2 It seems you don't really read what people write and just insist on your wrong meaning. I have clearly told that the change was made with RC 1 and not with RC 5.

**Comment by richard67** [comment] 2021-08-15 13:18
Closing as expected behaviour. It was a deliberate decision not to enable workflow automatically when installing Blog Sample Data.

This has been implemented with pull request #31711 and was released with 4.0 Release Candidate 1 on June 1.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35129">issues.joomla.org/tracker/joomla-cms/35129</a>.</sub>

**Closed as completed by richard67** 2021-08-15 13:18 UTC
Labels: No Code Attached Yet

**Comment by Magnytu2** [comment] 2021-08-15 13:21
So I apologize for the inconvenience. I have over a hundred installations of Joomla! 4 on my computer. And I don't remember having to activate the workflow for the blog example. Sorry.
But I maintain that it is a bad decision. How new to Joomla! 4, will discover this function if it is hidden, even in the example blog. But once again sorry.

**Comment by richard67** [comment] 2021-08-15 13:23
@Magnytu2 No need to say sorry. And I agree that it has to be well documented, if not done yet, and advertised.
