### ISSUE TITLE
Front-end> Notice on Homepage::  Notice: A session had already been started - ignoring session_start() in /home/aasim/httpdocs/lmsbeta/libraries/joomla/session/session.php on line 658

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#5644] opened 2015-01-08 10:22 UTC
-I have seen this notice on homepage so many times.

![screen shot 2015-01-08 at 04 20 13](http://issues.joomla.org/uploads/1/292a90c071d837da0ad9ed1685536b73.png)

**Comment by zero-24** [comment] 2015-01-08 10:49
@aasimali i don't know how i can replicate this issue.

I would sugest to disable error reporting on a live site (should not show the message) and check if it is a Core or component (JomSocial?) issue. If it is a Core issue we need a way to replicate it with the core. :smile:

**Comment by aasimali** [comment] 2015-01-08 10:53
@zero-24 
I know that's difficult to reproduce but I am sure, Its coming from Joomla. The issue is in session.php file at line number 658

As you can see the path: /home/aasim/httpdocs/lmsbeta/libraries/joomla/session/session.php on line 658

**Comment by zero-24** [comment] 2015-01-08 11:02
>I know that's difficult to reproduce but I am sure, Its coming from Joomla.

Sure but it can also come from the 3party component. Here it sounds like a not closed `session_start()` and it don't show the point where the first `session_start()` is called and not closed. 

Can you retest with current staging (3.4-dev)? As we have also file changes in this files so we can be sure that the issue still exists.

**Comment by aasimali** [comment] 2015-01-08 11:26
Yeah! Sure . I'll test it on staging site

**Comment by Bakual** [comment] 2015-01-08 13:53
Indeed sounds like a system plugin is starting a session before Joomla does. So make sure you have disabled all 3rd party (system) plugins when testing.

**Comment by wilsonge** [comment] 2015-01-09 16:48
We haven't changed the sessions pretty much since 1.5. I did a refactor here https://github.com/joomla/joomla-cms/pull/5088. But even that is unlikely to fix your issue - I suspect as has been mentioned a 3rd party service is intialising the session before Joomla. And you can only have one session open at a time so everything falls apart from there.

**Comment by brianteeman** [comment] 2015-01-20 19:43
I am closing this as an unconfirmed report at this time. It can always be re-opened if further information is provided that allows this to be replicated<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5644">issues.joomla.org/joomla-cms/5644</a>.</sub>

**Closed** 2015-01-20 19:44 UTC
Labels: No Code Attached Yet
