### ISSUE TITLE
Archive articles does not display if no menu item for category exists

### ISSUE THREAD

**Issue by b2z** [joomla/joomla-cms#9566] opened 2016-03-24 12:18 UTC
#### Steps to reproduce the issue

SEF should be ON.

1. Create several articles: some of them assign to category that has a menu item, some of them assign to category that DOES NOT have a menu item.
2. Change the state of created articles to "Archive".
3. Proceed to archive articles view.
4. Proceed to every article to read them.

#### Expected result

Archive articles should always open normally.

#### Actual result

Archive articles does not display if no menu item for category exists.

#### System information (as much as possible)

Joomla! 3.5.0

#### Additional comments

On Joomla! 3.4.8 problem does not exist.

**Comment by brianteeman** [comment] 2016-03-24 13:01
I can not confirm this
Steps taken
Clean install with no sample data
Create three articles and make them archived
Publish the archive module
Everything worked perfectly<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9566">issues.joomla.org/joomla-cms/9566</a>.</sub>

**Comment by b2z** [comment] 2016-03-24 13:04
> Publish the archive module
Why module? You should check the archived articles view ;)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9566">issues.joomla.org/joomla-cms/9566</a>.</sub>

**Comment by brianteeman** [comment] 2016-03-24 13:08
Sorry I am confused about
> Proceed to archive articles view.

You mean create a menu item for archived articles? If so then I have done that and it also works perfectly<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9566">issues.joomla.org/joomla-cms/9566</a>.</sub>

**Comment by brianteeman** [comment] 2016-03-24 13:12
Sorry I was wrong - it works from the module

it doesnt work from the menu link - the articles do not open<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9566">issues.joomla.org/joomla-cms/9566</a>.</sub>

**Comment by b2z** [comment] 2016-03-24 13:13
> You mean create a menu item for archived articles? 

Yes I mean a menu item for archived articles.

> If so then I have done that and it also works perfectly

Do you have any created articles that are assigned to category without a menu item?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9566">issues.joomla.org/joomla-cms/9566</a>.</sub>

**Comment by brianteeman** [comment] 2016-03-24 13:16
Confirmed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9566">issues.joomla.org/joomla-cms/9566</a>.</sub>

**Comment by N6REJ** [comment] 2016-03-27 00:30
with SEF OFF http://localhost/embryo/index.php?option=com_content&view=article&id=24:archived-article-1&catid=11&Itemid=161 works.
menu link is http://localhost/embryo/index.php?option=com_content&view=archive&Itemid=159<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9566">issues.joomla.org/joomla-cms/9566</a>.</sub>

**Comment by wezetel** [comment] 2016-04-03 18:32
Is there any workaround available (except disabling SEF)? I see currently no action on this issue. As my starting page contains mainly featured articles from a non-menu linked category, but also from some other (menu linked) categories I had to disable my archive menu. (Would have been easier for me, if I only have one category on my startpage :-( )
For sure I could create a menu item for the 'missing category', but this would 'disturb' the user experience.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9566">issues.joomla.org/joomla-cms/9566</a>.</sub>

**Comment by wezetel** [comment] 2016-04-05 19:05
As long as there is no solution to this issue my idea was to do a redirect with .htaccess, but without success.
All archived articles which are not associated with a menu linked category are featured articles with my menu item 'Aktuell'. In consequence the URL of such items in the archive are displayed as **http://domainname.tld/aktuell/archiv/rest_of_SefURL** . If I remove 'archiv' from the URL in the adressbar of the browser (**http://domainname/aktuell/rest_of_SefURL**) the correct article is displayed.
I'm not an .htaccess expert (far away :-), so I'm not sure, if .htaccess kann handle SEF URLs.
Any help would be appreciated<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9566">issues.joomla.org/joomla-cms/9566</a>.</sub>

**Comment by wezetel** [comment] 2016-04-12 07:32
Found a workaround, which works for me, as I just have one category with no menu link, but to which most archived articles belong to.
I created a menu item of type category list (should also work with category blog, doesn't matter) and set on the tab 'link type' the option 'Display in menu' to 'no'.
As I'm also using the T3 Megamenu (which ignores above setting) I had to assign a custom CSS class (e.g. 'invisible') to this menu item in the Mega Menu Configuration. And finally added a CSS statement in my custom.css: .invisible{display:none}
Small remark: seems to be better to add the addtional menu item not as the first item, as this (at least for my template) has different CSS styling than the rest.
Hope this helps people having the same problem with the current version of Joomla.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9566">issues.joomla.org/joomla-cms/9566</a>.</sub>

**Comment by chmst** [comment] 2016-04-19 14:52
Tahnk you very much, @wezetel for publishing this workaround.

**Comment by wezetel** [comment] 2016-04-19 18:28
Glad I could help!

**Comment by AlexRed** [comment] 2016-05-24 10:05
This pull request should solve the issue, please test it

https://github.com/joomla/joomla-cms/pull/10613
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9566">issues.joomla.org/joomla-cms/9566</a>.</sub>

**Comment by brianteeman** [comment] 2016-05-24 10:43
Closing as we have a PR #10613<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9566">issues.joomla.org/joomla-cms/9566</a>.</sub>

**Closed by brianteeman** 2016-05-24 10:43 UTC
Labels: No Code Attached Yet
