### ISSUE TITLE
Joomla 4 RC 5 - Back Buttons missing in Installer

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#35007] opened 2021-08-01 10:24 UTC
### What needs to be fixed
If you realize during installation that you made a mistake in the informations given before (for example your decision for the admin email, there is no way back.

### Why this should be fixed
It improves the User Experience

### How would you fix it
Back Button and Step indicators.

### Side Effects expected
no

**Comment by Quy** [comment] 2021-08-01 13:39
Related #24556

**Comment by seomarketercomau** [comment] 2021-08-02 09:04
I'm also having the same issue encountered that I want to incorporate [here](https://seomarketer.com.au/ "SEO Marketer"). <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35007">issues.joomla.org/tracker/joomla-cms/35007</a>.</sub>

**Comment by brianteeman** [comment] 2021-08-02 09:08
Please delete the spam

**Comment by harshraj1311** [comment] 2021-08-13 04:26
Can I work on this issue?

**Comment by coolcat-creations** [comment] 2021-10-18 08:51
@harshraj1311 I would very welcome it :)

**Comment by Quy** [comment] 2021-11-20 19:07
Closing as duplicate of #24556.

**Closed as completed by Quy** 2021-11-20 19:07 UTC
Labels: No Code Attached Yet
