### ISSUE TITLE
Not able to login

### ISSUE THREAD

**Issue by edthenet** [joomla/joomla-cms#42212] opened 2023-10-24 15:57 UTC
### Steps to reproduce the issue
- Goto the administrator login page
- fill in your credentials
- press the login button
### Expected result
- The user should be logged in and redirected to the dashboard page
### Actual result
- The user is not logged in and is returned to / stays on the login page

### System information (as much as possible)
- Joomla 4.4.0
- PHP 8.1
max_execution_time 100
memory_limit 256M
post_max_size 32M
upload_max_filesize 32M

### Additional comments
I now have like 30+ Joomla 4 websites, and all are updated. I know my login credentials but i can't login

Websites have Akeeba Backup, Admintools and RS-Firewall
- No messages in the developer console from my browser
- Edited configuration to debug and set error reporting to maximum. No messages. It just returns to the login page again.
- Tried several browsers (Chrome, Safari, Firefox and Edge)
- Removed all Cache
- Tried all instructions on https://docs.joomla.org/How_do_you_recover_or_reset_your_admin_password%3F/nl
- Also tried everything on https://www.itoctopus.com/10-reasons-why-youre-not-able-to-login-to-your-joomla-website

For one of the websites i completely rebuild the website and copied all kind of data straight from the database, but it took me a few days of work to get everything running nicely again. I don't want to do this with every website i've updated until now.

**Comment by richard67** [comment] 2023-10-24 17:18
I think it could be caused by RS-Firewall. Have you contacted their support?

**Comment by OctavianC** [comment] 2023-10-25 07:23
Luckily I'm here. To test if this is caused by RSFirewall!, simply [unpublish it according to our docs](https://www.rsjoomla.com/support/documentation/rsfirewall-user-guide/frequently-asked-questions/i-cannot-access-my-administration-section.html)

Had this happen before - iirc check configuration.php and make sure these have no values:
```php
public $live_site = '';
public $cookie_domain = '';
public $cookie_path = '';
```

**Comment by edthenet** [comment] 2023-10-25 07:49
Nice that everybody is pointing at 3th party extensions, but i also did some testing yesterday.
I also got a mail from Phil Taylor that he already found a solution
When i reinstall the core files from Joomla everything is fixed.
I did not not excluded any of the extentions, so i do think something went wrong with the update mechanism<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42212">issues.joomla.org/tracker/joomla-cms/42212</a>.</sub>

**Comment by richard67** [comment] 2023-10-25 08:39
> Nice that everybody is pointing at 3th party extensions

@edthenet I have only suggested that it COULD be.

> When i reinstall the core files from Joomla everything is fixed.

Happy it could be solved. Might be one of the rare cases when the download was not complete. Or has Phil provided any details on what the problem could have been?

**Comment by Quy** [comment] 2023-11-09 14:33
Closing as no additional details has been provided as requested.

**Closed as completed by Quy** 2023-11-09 14:33 UTC
Labels: No Code Attached Yet, Information Required
