### ISSUE TITLE
[4.3 Beta 1] Upgrades/Updates

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#39817] opened 2023-02-07 18:28 UTC
Its not possible to test the upgraade/update process from a 4.2.x web site as 4.3beta1 has not been added to the test update list
https://github.com/joomla/update.joomla.org/tree/master/www/core/test

**Comment by brianteeman** [comment] 2023-02-07 18:56
Also tried to update a 4.30alpha site using the nightly list and that failed to find an update either.

ping @obuisard

**Comment by brianteeman** [comment] 2023-02-07 19:11
it should work when on nightly though shouldnt it?

**Comment by obuisard** [comment] 2023-02-07 19:15
> it should work when on nightly though shouldn't it?

The nightlies should keep working, yes

**Comment by brianteeman** [comment] 2023-02-07 19:18
tested on two different servers using the nightly update link (https://update.joomla.org/core/nightlies/next_minor_list.xml) on sites running 4.3alpha and neither were offered an update

**Comment by obuisard** [comment] 2023-02-07 19:19
> tested on two different servers using the nightly update link (https://update.joomla.org/core/nightlies/next_minor_list.xml) on sites running 4.3alpha and neither were offered an update

I will double check, I am not on a computer right now

**Comment by ReLater** [comment] 2023-02-09 11:28
I don't know if still related: https://github.com/joomla/joomla-cms/pull/39446

**Comment by obuisard** [comment] 2023-02-12 23:34
After checking this out with Franciska @fancyFranci, it turns out I should have modified our nightly XML files. This is a missing step in our release check list for alpha and beta versions and will complement our task list documentation accordingly.
Thank you Franciska for your help, really appreciated. 
Thank you Brian @brianteeman for mentioning it. Apparently this did not bother many people...
I will close this once it is confirmed it has been fixed for you.

**Closed as completed** 2023-02-16 15:46 UTC
Labels: No Code Attached Yet, Information Required
