### ISSUE TITLE
[4.0] Error reordering modules

### ISSUE THREAD

**Issue by joeforjoomla** [joomla/joomla-cms#19739] opened 2018-02-19 13:20 UTC
### Steps to reproduce the issue
Try to reorder modules

### Expected result
NO errors

### Actual result
Error is thrown: 0 Argument 'where' of event onTableBeforeReorder must be empty or string

![image](https://user-images.githubusercontent.com/17835460/36379710-eec91a18-157f-11e8-9b55-255e9fe484dc.png)

**Comment by brianteeman** [comment] 2018-04-10 15:23
I can confirm that there is a 500 error when re-ordering the modules which looks to be coming from the draggable.js script on article save

**Comment by laoneo** [comment] 2018-04-10 15:47
There is a pr for that #20088.

**Comment by laoneo** [comment] 2018-04-10 15:48
Just for reference, we have a similar issue on the front end #18721.

**Comment by brianteeman** [comment] 2018-04-10 16:39
@laoneo if you find a pr for an issue then please close the issue

**Comment by laoneo** [comment] 2018-04-10 17:41
The pr is for the front end, it doesn't solve it for the back end.

**Comment by dgrammatiko** [comment] 2018-04-10 18:38
Line https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_modules/tmpl/modules/default.php#L22

there is a missing `&` before the `JSession`

**Comment by ReLater** [comment] 2018-04-10 21:50
@dgrammatiko 

> there is a missing & before the JSession

the same with https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_banners/tmpl/banners/default.php#L25
(and there are some more finds with missing ampersands.
But adding the ampersand didn't fix this issue.

**Comment by Quy** [comment] 2018-05-22 20:18
@joeforjoomla I cannot reproduce this. Please try again.

**Comment by carlitorweb** [comment] 2018-05-22 20:44
I get a different error trying re-order

![asd](https://user-images.githubusercontent.com/3956472/40389067-571f9644-5ddf-11e8-9b93-53c2bb1fc658.png)

**Comment by brianteeman** [comment] 2018-06-15 20:05
It would appear that this has been resolved elsewhere

**Closed as completed by brianteeman** 2018-06-15 20:05 UTC
Labels: No Code Attached Yet, J4 Issue
