### ISSUE TITLE
Frontend editing creates new article alias

### ISSUE THREAD

**Issue by JAVesey** [joomla/joomla-cms#6620] opened 2015-03-31 15:27 UTC
#### Steps to reproduce the issue
Login to front-end with account with permission to edit articles.
Edit article or just click "Save"

#### Expected result
Article is saved with advisory notice

#### Actual result
The following warning is displayed:
"Warning
Alias already existed so a number was added at the end. If you want to change the alias, please contact a site administrator"

Article edits are saved (advisory notice displays okay) but "-2" is added to the end of the original alias.

Editing the article's alias in the back-end allows restoration of the original alias.

#### System information (as much as possible)
Joomla 3.4.1
Protostar Template
php 5.3.27
JCK Suite editor

#### Additional comments
Seems to be reproducible by others, as discussed in Forums here:
http://forum.joomla.org/viewtopic.php?f=706&t=881506

**Comment by brianteeman** [comment] 2015-03-31 15:57
I can only replicate this when the menu type is featured articles. Everything is fine when editing a single article or a blog category

**Comment by proweb** [comment] 2015-03-31 16:02
Confirm, Brian right it's bug for featured articles.

**Comment by sovainfo** [comment] 2015-03-31 16:03
Confirmed this, indeed on the featured menu item. With muliple edits the odd number edit produces the message, the even number edits don't. Only the first time the alias is changed to -2.

**Comment by JAVesey** [comment] 2015-03-31 16:20
Thank you guys, I confirm all the the above.  Sorry I wasn't more specific :-(<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6620">issues.joomla.org/joomla-cms/6620</a>.</sub>

**Comment by dneukirchen** [comment] 2015-04-01 21:10
#4316
The "isNew-Check" in line 507 fails, because (int) $input->get('id') returns 0 when editing an article from featured view.

Perhaps we could use $data['"id"] instead of $input->get("id") to solve this problem.

But i didnt spent a lot of time debugging/testing this and i didnt find the reason why this happens only every 2nd save attempt and only when the menu type is featured. 
I will look into this in more detail tomorrow.

**Comment by infograf768** [comment] 2015-04-02 06:30
I confirm that changing to 
`if (in_array($input->get('task'), array('apply', 'save', 'save2new')) && (int) $data['id'] == 0)`
solves the issue here.

**Comment by dneukirchen** [comment] 2015-04-03 08:54
I looked a bit deeper into this... 

In my opinion, there is no good reason to use input->get("id") rather than $data["id"] coming from the controller. 

When you edit an article from the **featured view**, $input->get("id") is null and the "isNew-Check" fails. 

When you edit from an **category blog view** $input->get("id") holds the categoryId and not the articleId... so even if it does not lead to errors in that case... its still the wrong value and could lead to errors and bugs in the future.

So if no one has any objection, i would create the pr to fix this.

P.S. The same applies to $input->getInt('id') in line 487.

**Comment by zero-24** [comment] 2015-04-03 09:37
Thanks @dneukirchen i'm closing here as we have a PR https://github.com/joomla/joomla-cms/pull/6640/files

**Closed by zero-24** 2015-04-03 09:37 UTC
Labels: No Code Attached Yet
