### ISSUE TITLE
if (!is_int($status) || is_int($status) && !isset($this->responseMap[$status]))

### ISSUE THREAD

**Issue by rumours86** [joomla/joomla-cms#16202] opened 2017-05-23 09:02 UTC
if (!is_int($status) || is_int($status) && !isset($this->responseMap[$status]))

https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/application/web.php#L562

maybe
if (!is_int($status) && !isset($this->responseMap[$status]))
or
if (!is_int($status) || (is_int($status) && !isset($this->responseMap[$status])))
or
if (!is_int($status) && !isset($this->responseMap[$status]))

**Comment by PhilETaylor** [comment] 2017-05-23 11:17
That is 3 year old code from @wilsonge  https://github.com/joomla/joomla-cms/commit/a322a43ae96992ca506f899c7294181e0efbc08e

**Comment by wilsonge** [comment] 2017-05-23 11:45
The first one fails because your starting to check for non-integer keys in the responseMap array which starts to lead to odd behaviour.

The third one is the same as the first one. 

The second one is fine - but honestly this code is likely about to get refactored with https://github.com/joomla/joomla-cms/pull/16040 anyhow. So not sure how relevant this is

**Comment by rumours86** [comment] 2017-05-23 12:12
if (is_int($status) && !isset($this->responseMap[$status]))
or
if (!isset($this->responseMap[$status]))

because (!is_int($status) || is_int($status)) === true

**Comment by richard67** [comment] 2017-05-23 14:14
@rumours86 You are wrong because of operator precedence: && comes before ||. Same as in maths with multiplication coming before sum

**Comment by richard67** [comment] 2017-05-23 19:03
@rumours86 See [http://php.net/manual/en/language.operators.precedence.php](http://php.net/manual/en/language.operators.precedence.php "http://php.net/manual/en/language.operators.precedence.php")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16202">issues.joomla.org/tracker/joomla-cms/16202</a>.</sub>

**Comment by richard67** [comment] 2017-05-25 13:00
Does anybody agree with me that we can close this issue? It seems @rumours86 does not reply.
As I have shown in my previous 2 posts, this issue here is caused by a misunderstanding of operators precedence in PHP.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16202">issues.joomla.org/tracker/joomla-cms/16202</a>.</sub>

**Comment by rumours86** [comment] 2017-05-25 13:09
@richard67 i think you right
example https://middle.valyaev.su/1.php

**Comment by richard67** [comment] 2017-05-25 13:10
@rumours86 Could you close this issue in the issue tracker or on github then?

**Closed** 2017-05-25 13:13 UTC
Labels: No Code Attached Yet

**Comment by rumours86** [comment] 2017-05-25 13:16
@richard67 Thanks for clarifying
