### ISSUE TITLE
[com_fields] Placeholder Field in Media Field is useless

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#13929] opened 2017-02-05 11:27 UTC
### Steps to reproduce the issue
Media Fields has a Placeholder Option which is not used in the field.

![image](https://cloud.githubusercontent.com/assets/828371/22625759/46ad25c4-eb9e-11e6-9f0c-1caa4856e441.png)

->

![image](https://cloud.githubusercontent.com/assets/828371/22625769/65ec3fb0-eb9e-11e6-971f-ec335b93e398.png)

**Comment by brianteeman** [comment] 2017-03-10 22:28
The problem is that as far as i can tell the options is generic for all fields so cant be enabled or disabled per field type.

**Comment by franz-wohlkoenig** [comment] 2017-04-05 11:53
closed as similar #14335<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13929">issues.joomla.org/tracker/joomla-cms/13929</a>.</sub>

**Closed by franz-wohlkoenig** 2017-04-05 11:53 UTC
Labels: No Code Attached Yet
