### ISSUE TITLE
Banner tracking creates duplicates for banners instead of increasing impressions counter.

### ISSUE THREAD

**Issue by nemmar** [joomla/joomla-cms#8443] opened 2015-11-15 22:07 UTC
Hi,

I have Joomla 3.4.5 and there is a bug with the Banner Tracking feature. Banner tracking creates duplicates for the banners instead of increasing the banner impressions counter. Each time a specific banner displays I think it's supposed to increase the impressions counter for that banner in the tracking screen, but not create a duplicate banner tracking entry for that same banner.

I had posted a Github issue for this bug with a prior Joomla version and it seems that the bug might still occur in the latest Joomla version. I can't find the old issue post because I guess it was too long ago and it's not showing up in my Github account anymore.

**Comment by wojsmol** [comment] 2015-11-16 01:15
@nemmar 
> I had posted a Github issue for this bug with a prior Joomla version and it seems that the bug might still occur in the latest Joomla version. I can't find the old issue post because I guess it was too long ago and it's not showing up in my Github account anymore.

Do you mean issue https://github.com/joomla/joomla-cms/issues/6617?

**Comment by nemmar** [comment] 2015-11-16 12:54
Hi,
Yes, you are correct. Issue https://github.com/joomla/joomla-cms/issues/6617 that I posted in March is the same issue.

The Banner Manager: Tracks screenshot in that post shows the bug that is still occurring when I test it.

**Comment by wojsmol** [comment] 2015-11-17 16:44
Correction of this error for new records should not be a problem. But I wonder what to do with old records?

**Comment by brianteeman** [comment] 2016-01-28 11:05
I am closing this as it is a duplicate of #6617 - no need to keep creating new issues for the same problem<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8443">issues.joomla.org/joomla-cms/8443</a>.</sub>

**Closed** 2016-01-28 11:05 UTC
Labels: No Code Attached Yet

**Comment by myschkyn** [comment] 2016-05-27 11:00
Hi,

I'd say that the bug refered by @nemmar  is not the same as #6617.

If I track Impressions for a banner I get the following error:
![captura de pantalla 2016-05-27 a las 11 38 07](https://cloud.githubusercontent.com/assets/19607944/15606180/d05fe7a4-240a-11e6-83fa-6d94e776d620.png)

This means the Banner tracking feature creates a duplicate for the banner when tracking impressions. But if I only track clicks, I don't get the error...
