### ISSUE TITLE
Can't open folder with a space in the name

### ISSUE THREAD

**Issue by AlexRed** [joomla/joomla-cms#18287] opened 2017-10-09 11:00 UTC
### Steps to reproduce the issue
Create via FTP a new folder in the images folder. Use for the folder name: test space
Try to open this folder from the edit article page to select an image.

### Expected result
I can go inside the folder with a space in the name

### Actual result
I can't go inside the folder with a space in the name

### System information (as much as possible)
Joomla 3.8.1
PHP 7.0
Browser Firefox 56.0 (64 bit)  and Chrome 61.0.3163.100 (64 bit)

### Additional comments
![space-folder](https://user-images.githubusercontent.com/1362388/31335138-23539060-ace9-11e7-9bd0-65752656c6c2.png)

**Comment by brianteeman** [comment] 2017-10-09 11:12
i woudl say that this is the expected behaviour and is why joomla itself will not allow you to create a folder with a space in it

**Comment by AlexRed** [comment] 2017-10-09 11:29
yes, creating a new folder with a space in it you get the error message, but no error message when try to open it in the media manager.

**Comment by studio42** [comment] 2017-10-09 15:23
AlexRed, Joomla use  a safe pattern to remove any char that can give problems.
Space can break, so Joomla remove it.
test space, is  changed to testspace (no space inside) it's why media manager cannot show inside this folder.

**Comment by simbus82** [comment] 2017-10-11 14:14
Maybe you can add a warning icon near the file/folder name, like some others media managers when a name is wrong or contains not accepted characters.

**Comment by infograf768** [comment] 2017-10-11 14:51
I wonder if we could not use `rawurlencode()` after domain to get the nice `+` or `%20` for spaces, therefore permitting spaces in folders title.

**Comment by brianteeman** [comment] 2017-10-11 15:06
It might work but it might be tricky if you have nested parts that all need encoding

**Comment by Quy** [comment] 2018-05-31 19:50
This is not an issue in J4.

**Comment by under44** [comment] 2018-08-01 07:30
_Joomla 3.8.11._

**When working through xtd-button image.**
I also found problems in folder names where there is a "!" and national symbols (ru, in my case). You can highlight file names with spaces and "!", except for names with national symbols.

**In the media manager in the control panel.**
File names can be highlighted, including names with national symbols.

---

But the main issue is not differences.
Dear developers, is it planned to remove these restrictions for folder names in the future?
This is becoming very sad.

**Comment by Quy** [comment] 2019-06-07 23:21
Since this issue arises when performed outside of Joomla, can this be considered as won't fix?

**Closed as completed** 2019-06-10 06:33 UTC
Labels: No Code Attached Yet

**Comment by rashgang** [comment] 2019-09-19 15:00
Is there a way to fix this in code or any patches available. I am having this issues in my site. How to fix this. I cannot traversing the folder with spaces. but i can go inside folder without spaces.![screen shot 2019-09-19 at 14 59 40](https://issues.joomla.org/uploads/1/34d0109a768934f9c44b14ce7fdbe953.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18287">issues.joomla.org/tracker/joomla-cms/18287</a>.</sub>

**Comment by infograf768** [comment] 2019-09-20 06:00
@rashgang
The simplest way is to change the names of the folders via FTP or CPanel.

**Comment by rashgang** [comment] 2019-09-23 08:07
If i changed it it will affect the image path on frontend.

**Comment by infograf768** [comment] 2019-09-23 08:11
Mass changes in a db dump.
