### ISSUE TITLE
com_config: Repeatable field fieldset with attribute hidden is shown

### ISSUE THREAD

**Issue by tomasduracka** [joomla/joomla-cms#7688] opened 2015-08-12 23:33 UTC
There is no chance to hide fieldset that is used only for repeatable fields purpose at the page option=com_config&view=component. I am following the documentation https://docs.joomla.org/Repeatable_form_field_type, where "hidden" is an attribute of fieldset but without effect.

Expected result

Fieldsets with attribute hidden won't be shown.

Actual result

Fieldsets with attribute hidden are shown.

System information (as much as possible)

joomla 3.4.3

**Comment by bertmert** [comment] 2015-09-17 06:30
The attribute hidden is only for the master modal fieldset of the repeatable field.
Thus you see just the button to open the modal window, when you load the form.
EDIT-> Hm, looks like this attribute has no function/effect at all(??)

What I don't understand: Is this your problem: The modal part is not hidden when you load the form in backend?

hidden is not listed in documentation as option for other fieldsets inside the repeatable. So, I would say that's the expected bahaviour if they ignore this attribute. You have to hide the fields separately.

**Comment by v912485** [comment] 2015-11-09 16:54
I experience the same issue. For the repeatable field type, when used in the config.xml for the admin section in a component, the nested fieldset is not hidden and an extra tab (without any fields) is shown in the configuration screen.

However, when used in the default.xml for any view this issue does not occur.

joomla 3.4.5

**Comment by goslingcools** [comment] 2015-11-14 11:28
I can confirm this issue as well.

The param hidden="true" is ignored/not used in administrator\components\com_config\view\component\tmpl\defaul.php<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7688">issues.joomla.org/joomla-cms/7688</a>.</sub>

**Comment by paul-muckypuddle** [comment] 2016-04-27 08:34
Also experiencing this - works fine in modules but not config.xml of a component, shows an extra empty tab.

**Comment by zero-24** [comment] 2016-04-27 08:39
Can you try the current staging? I guess it should be fixed with this patch for 3.5.2: https://github.com/joomla/joomla-cms/pull/9960

**Comment by paul-muckypuddle** [comment] 2016-04-27 09:08
Will do when I get a chance

**Comment by zero-24** [comment] 2016-05-08 11:08
Set to "closed" on behalf of @zero-24 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7688">issues.joomla.org/joomla-cms/7688</a>

**Comment by zero-24** [comment] 2016-05-08 11:08
The Repeatable field gets replaced by the subform at #7829 So I'm closing here.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7688">issues.joomla.org/joomla-cms/7688</a>.</sub>

**Closed by zero-24** 2016-05-08 11:08 UTC
Labels: No Code Attached Yet
