### ISSUE TITLE
Saving an article "as copy" doesn't set the state to 'Unpublished'

### ISSUE THREAD

**Issue by AndySDH** [joomla/joomla-cms#42158] opened 2023-10-18 09:13 UTC
### Steps to reproduce the issue

- Edit a published article
- Use "the "Save as Copy" feature

### Expected result

- The copied article should be first created as "Unpublished" state, as it's obviously a draft.

### Actual result

- But instead, the copied article already has the "Published" state from the source article.

### System information (as much as possible)

Joomla 4.3.4

### Additional comments

This wasnt't an issue in Joomla 3, where copying an article would first set it as Unpublished (draft)

**Comment by Fedik** [comment] 2023-10-18 09:29
I think it already fixed in https://github.com/joomla/joomla-cms/pull/38810

**Comment by alikon** [comment] 2023-10-18 09:39
it has been reverted with #41790

**Comment by AndySDH** [comment] 2023-10-18 10:16
So since it has been reverted, I guess it has to be still fixed.

**Comment by Quy** [comment] 2023-10-18 11:10
Closing as duplicate of #37351. Thanks.

**Closed as completed by Quy** 2023-10-18 11:10 UTC
Labels: No Code Attached Yet, bug
