### ISSUE TITLE
Module loses chosen options

### ISSUE THREAD

**Issue by sakattack** [joomla/joomla-cms#8464] opened 2015-11-17 17:16 UTC
Ok, so I came acrross a bug that occurs on custom html modules (could be happening to others as well), which results in possible loss of all of module's made choices.

#### Steps to reproduce the issue

1. create a custom html module and add some class suffixes to it, save it and close it.

2. Start the creation of a new custom html module but do not add any class suffixes to it and do not save it.

3. While at the creation screen of the new custom html module, open module manager on a new tab, and then open the custom html module you created on the first step. This module will now have NO class suffixes (or any other choice it may have had). (The suffixes are in the database but are not displayed, if you make the mistake to save the module, they will be lost)

#### System information (as much as possible)

joomla 3.4.5

The problem has been happening for all joomla 3+ versions

**Comment by brianteeman** [comment] 2015-11-18 13:32
I can confirm this following the steps above<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8464">issues.joomla.org/joomla-cms/8464</a>.</sub>

**Comment by bertmert** [comment] 2015-11-19 03:35
I can confirm this for ALL advanced options.
Not for other ones in other tabs.

**Comment by bertmert** [comment] 2015-11-19 04:18
It looks like these lines are overriding
```
$data->params
```
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_modules/models/module.php#L606-L611

Surrounding them with
```
if (empty($data->params))
{
.... lines 606-611
}
```

fixed the issue but I'm not shure if it should be fixed earlier when userState is written, maybe with an additional module id.

**Comment by bertmert** [comment] 2015-11-28 03:56
Please test PR https://github.com/joomla/joomla-cms/pull/8557

**Comment by infograf768** [comment] 2015-11-29 08:11
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8464">issues.joomla.org/joomla-cms/8464</a>

**Comment by infograf768** [comment] 2015-11-29 08:11
Closing as we have a patch https://github.com/joomla/joomla-cms/pull/8557<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8464">issues.joomla.org/joomla-cms/8464</a>.</sub>

**Closed by infograf768** 2015-11-29 08:11 UTC
Labels: No Code Attached Yet
