### ISSUE TITLE
Configuration option "$sitename_pagetitles" has no effect

### ISSUE THREAD

**Issue by friedrico** [joomla/joomla-cms#8134] opened 2015-10-23 18:29 UTC
#### Steps to reproduce the issue
configuration.php contains the following two lines
```
public $sitename = 'MyJoomlaPage';
public $sitename_pagetitles = '2';
```
(the '2' seem to mean "domain name AFTER page title")

Article named "Home" as landing page
#### Expected result
Title of landing page "Home - MyJoomlaPage"

#### Actual result
Title of landing page "Home"

#### System information (as much as possible)
Joomla: 3.4.5
Templates (beez/prototype) don't matter

#### Additional comments

libraries/joomla/document/html/renderer/head.php:111
```php
$buffer .= $tab . '<title> ' .htmlspecialchars($document->getTitle(), ENT_COMPAT, 'UTF-8') . '</title>' . $lnEnd;
```
Should the configuration option not take THERE effect?

**Comment by infograf768** [comment] 2015-10-24 06:47
I can't reproduce this error. I do get here in the browser tab whatever saved in "Include Site Name in Page Titles"

**Comment by friedrico** [comment] 2015-10-24 10:19
So where is the configuration option rendered if not in libraries/joomla/document/html/renderer/head.php line 111?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8134">issues.joomla.org/joomla-cms/8134</a>.</sub>

**Comment by bertmert** [comment] 2015-10-24 11:29
Normaly title is set in view.html.php of components
```
elseif ($app->get('sitename_pagetitles', 0) == 2)
{
 $title = JText::sprintf('JPAGETITLE', $title, $app->get('sitename'));
}
...
$this->document->setTitle($title);
```
head.php afterwards gets expanded title via $document->getTitle()

Check your plugins if somewhere title gets overriden e.g. by setTitle(...). Any extension, override and so on could do that.

**Comment by friedrico** [comment] 2015-10-25 15:32
You were right - Easy Frontend SEO was responsible for overwriting this setting<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8134">issues.joomla.org/joomla-cms/8134</a>.</sub>

**Comment by infograf768** [comment] 2015-10-25 15:35
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8134">issues.joomla.org/joomla-cms/8134</a>

**Comment by infograf768** [comment] 2015-10-25 15:35
Closing as not a joomla bug.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8134">issues.joomla.org/joomla-cms/8134</a>.</sub>

**Closed by infograf768** 2015-10-25 15:35 UTC
Labels: No Code Attached Yet
