### ISSUE TITLE
Issue with confimration email

### ISSUE THREAD

**Issue by ctokepa** [joomla/joomla-cms#42403] opened 2023-11-27 12:17 UTC
### Steps to reproduce the issue
Upon registration when receiving confirmation email in gmail you reveice it as a text and not a clickable link. I have this issue since joomla 3. This happens when SEF links are enabled. If you have those link disabled you have no issue. I use cyrillic language. Maybe this is the issue.![screen shot 2023-11-27 at 12 16 46](https://issues.joomla.org/uploads/1/9cdfba514c7d06471d9f06bae693ec22.png)

### Additional comments

![screen shot 2023-11-27 at 12 16 46](https://issues.joomla.org/uploads/1/62af8a9523652db6580e70729189e9aa.jpeg)

**Comment by toivo** [comment] 2023-11-27 14:58
After the slash / following the domain name, the SEF URL has a full stop which probably makes the URL invalid. The question is where does it come from, do the Cyrillic alphabet somehow cause it to be added or prefixed. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42403">issues.joomla.org/tracker/joomla-cms/42403</a>.</sub>

**Comment by Quy** [comment] 2023-11-27 15:01
It appears to be a period but it is part of the underline of `/`.

**Comment by brianteeman** [comment] 2023-11-27 18:54
@chmst why?

**Comment by toivo** [comment] 2023-11-27 20:47
The purpose of my comment was simply to highlight the existence of the period aka full stop that follows the / character in the SEF URL that breaks the link because it is not obvious. 

This issue was first raised at the forum. The website in question has a menu entry called регистрация (registration) and the period appears in the link only when SEF URLs are enabled.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42403">issues.joomla.org/tracker/joomla-cms/42403</a>.</sub>

**Comment by brianteeman** [comment] 2023-11-27 20:59
@ctokepa 
Is this only happening in gmail? And is gmail being run in english?

If so then the problem may be caused by a security feature in gmail breaking links that contain cyrillic characters as they are often used to fake urls

**Comment by brianteeman** [comment] 2023-11-27 21:00
> The purpose of my comment was simply to highlight the existence of the period aka full stop that follows the / character in the SEF URL that breaks the link because it is not obvious.

As stated by @quy there is no period after the /

**Comment by toivo** [comment] 2023-11-28 06:24
Ok, thank you, guys.  My email client displays contiguous underlines, not cut by the slash character. I should have worn glasses.  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42403">issues.joomla.org/tracker/joomla-cms/42403</a>.</sub>

**Comment by ctokepa** [comment] 2023-11-28 08:28
@brianteeman the language of my gmail is Bulgarian. I think only in gmail because it filters the link. Are there any options on making an exception for activation link because having more users is crutual for the site. And if I am to ask them to copy paste and so on users and income may be lost.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42403">issues.joomla.org/tracker/joomla-cms/42403</a>.</sub>

**Comment by brianteeman** [comment] 2023-11-28 08:33
The only thing I can think of is to try a different setting for "unicode alias"

![image](https://github.com/joomla/joomla-cms/assets/1296369/64d73c8b-6b6c-435b-9f2f-d5041324bbf7)

**Comment by ctokepa** [comment] 2023-11-29 09:04
I have tested it on other clients. I think it is a gmail protection or something. In other mail clients everything is working.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42403">issues.joomla.org/tracker/joomla-cms/42403</a>.</sub>

**Comment by fgsw** [comment] 2024-02-06 09:13
> I think it is a gmail protection or something.

@ctokepa so nothing to test as no core issue?

**Comment by Quy** [comment] 2024-03-15 14:27
Closing as non-core issue.

**Closed as completed by Quy** 2024-03-15 14:27 UTC
Labels: No Code Attached Yet, Information Required
