### ISSUE TITLE
PLG_SYSTEM_JOOA11Y_EMBED_AUDIO

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/joomla-cms#36870] opened 2022-01-27 12:03 UTC
### Steps to reproduce the issue
I am translating new J4.1 strings into Dutch and did find this in de content of the above Languagestring.

Text:
Please ensure to provide a <strong>transcript for all podcasts.</strong> Providing transcripts for audio content is a mandatory Level A requirement. Transcripts support people who are **D/deaf** or hard-of-hearing, but can benefit everyone. Consider placing the transcript below or within an accordion panel.

### Expected result
I think **D/deaf** is a typo but I don't know if it is and if it must be **Deaf** or **deaf**

**Comment by brianteeman** [comment] 2022-01-27 12:24
Well spotted. It's not actually a typo. 

The word deaf is used to describe or identify anyone who has a severe hearing problem. 

We use Deaf with a capital D to refer to people who have been deaf all their lives, or since before they started to learn to talk.

**Comment by richard67** [comment] 2022-01-27 12:51
So the issue should be closed as expected behaviour? Or should the text maybe enhanced to "Deaf or deaf" instead of "D/deaf"?

**Comment by brianteeman** [comment] 2022-01-27 13:39
D/deaf is a common term so should be left as it is for english. Translators are free to handle this as they wish

**Comment by richard67** [comment] 2022-01-27 13:40
Closing as expected behaviour.

**Closed as completed by richard67** 2022-01-27 13:40 UTC
Labels: No Code Attached Yet
