### ISSUE TITLE
Module in module view in Joomla4 (for older module in article)

### ISSUE THREAD

**Issue by maxer77** [joomla/joomla-cms#42565] opened 2023-12-24 12:27 UTC
When Joomla added module to articles feature, firstly was code
{loadmodule mod_custom,[module title]}
Later was changed to
{loadmoduleid [ID}}
Long time ago, I discovered problem with module displays. When old code a module, exists few times ia duplicated. This bug exists only for J4,not for J5 
### Steps to reproduce the issue
1) Create new custom module and add small image for example. Set "Github" for title.
![github1](https://github.com/joomla/joomla-cms/assets/103517402/8eb9d34b-b681-4e9e-9ccc-b1640133616f)
2) To new article, paste this code

> <p>Text 1</p>
> <p>{loadmodule mod_custom,Github}</p>
> <p>Text 2</p>
> {loadmodule mod_custom,Github}
> <p>Text 3</p>
> {loadmodule mod_custom,Github}

### Expected result
![github3](https://github.com/joomla/joomla-cms/assets/103517402/9aac1155-a86a-41e9-b4ed-7c79283e5634)

### Actual result
Double view of module for default template:
![github2](https://github.com/joomla/joomla-cms/assets/103517402/0aacf60f-f0ed-4598-8657-5452deb4e7d6)

### System information (as much as possible)
 10.6.15-MariaDB-cll-lve 
PHP Version 8.1.26
Web Server | LiteSpeed

Joomla! Version | Joomla! 4.4.1 Stable [ Pamoja ] 28-November-2023 16:00 GMT

**Comment by chmst** [comment] 2024-01-06 23:31
I remember this one https://github.com/joomla/joomla-cms/issues/12888 could be a duplicate

**Comment by alikon** [comment] 2024-01-07 07:56
should be fixed by #38582 starting from Joomla! 4.2.3

**Comment by Fedik** [comment] 2024-01-07 09:20
I cannot reproduce it.
Please make sure that one of installed extension does not override ModuleHelper class from libraries/src/Helper/ModuleHelper.php  file.
There some extensions that doing it.

**Comment by Quy** [comment] 2024-02-05 20:41
Closing as not reproducible and no followup response.

**Closed as completed by Quy** 2024-02-05 20:41 UTC
Labels: No Code Attached Yet, Information Required
