### ISSUE TITLE
Link to article in category-list and category-blog with incorrect menu-item-id

### ISSUE THREAD

**Issue by Sieger66** [joomla/joomla-cms#11636] opened 2016-08-17 01:40 UTC
### Steps to reproduce the issue
Joomla! 3.6.2 with articles
Make a new category.
Put one or more articles to this new category.
Make two new article-category-list-menuitems:
A  and  B
both for the same new article-category

Set in article-category-list-menuitem A -> Details-> Template Style -> Beez3

Set in article-category-list-menuitem B -> Details-> Template Style -> protostar

### Expected result

Go to frontend and klick on menuitem A and see article-category-list with Template Beez3
Example:  
/index.php?option=com_content&view=category&id=2&Itemid=**108**

show the link to a article in the list 
/index.php?option=com_content&view=article&id=1:getting-started&catid=2&Itemid=**108**
Klick to this link and see the article with "Beez3"

Klick on menuitem B and see article-category-list with Template protostar
/index.php?option=com_content&view=category&id=2&Itemid=**109**

show the link to the same article in the list: 
/index.php?option=com_content&view=article&id=1:getting-started&catid=2&Itemid=**109**
Klick to this link and see the article with "protostar"

### Actual result

Go to frontend and klick on menuitem A and see article-category-list with Template Beez3
Example:  /index.php?option=com_content&view=category&id=2&Itemid=**108**

show the link to a article in the list 
/index.php?option=com_content&view=article&id=1:getting-started&catid=2&Itemid=**108**
Klick to this link and see the article with "Beez3"

Klick on menuitem B and see article-category-list with Template **protostar**
/index.php?option=com_content&view=category&id=2&Itemid=**109**

show the link to the same article in the list: 
/index.php?option=com_content&view=article&id=1:getting-started&catid=2&Itemid=**108**
Klick to this link and see the article with "**Beez3**"

change the  menuitem in the browser from "108" to "109" and you see the article with protostar

The article come allways with the self view and not always with the view from the menuitem-"Template Style"

The bug is the wrong link (to the single-article) in the article-category-list. 

The menu-item-id in the article-link in the list is always the same

### Additional comments
All menu-item-id and 
/index.php?option=com_content&view=category&id= . . .
only for example and is need to use them from your Joomla if you want to reproduce the issue.

Similar problem is in the category-blog with the links to the single articles

**Comment by schnuti** [comment] 2016-08-17 07:10
As I understand this, you are trying to produce duplicate content.
The links in your two menu items should point to one and the same item including item id.
You can build more complex category trees but if you e.g. add menu items for the singe articles the links should always point to those article menu items.

If you do not have menu items for the articles, the router will find a first best fit. In your case the first menu item that includes the articles category =  108

To me this is expected and wanted behaviour.
If you manipulate the itemid, there are a couple of different results depending on the content of that menu item.

**Comment by Sieger66** [comment] 2016-08-18 14:56
> you are trying to produce duplicate content.

Yes, But it is only a example to reproduce the issue quickly.

For example if you in menu-item A change 
Details  to  Access to "only for joomla group X"

and in the menu-item B change 
Details  to  Access to "only for joomla group Z"
or/and
List Layout -> Oldest First or ...
 
then you have less duplicate content as for example between
Menue-item to featured-articles-blog and
Menue-item to category-blog to category with some articles who are featured-status.

**Comment by schnuti** [comment] 2016-08-18 19:13
Well, it's not a bug, so you have to find a backward compatible solution, code it and create a pull request that might be accepted by the PLT. If you personally need it, you might find a plugin event where you can modify the itemid in the link/URL-query.

I guess Google is the one that tells the world what duplicate content is. I do not really care that much. More important to me is, that the item page (article) looks the same from where ever it's linked. One problem with the current router is that, in some cases, no or a wrong menu item id is found. Your idea doesn't make that issue easier to solve.

**Comment by Sieger66** [comment] 2016-08-21 16:48
Yes i agree with you and this PR can set to Closed.

Maybe with addition of the Label  " Re-evaluate for v4.0 "<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11636">issues.joomla.org/joomla-cms/11636</a>.</sub>

**Comment by brianteeman** [comment] 2016-08-21 16:49
Closed as requested

**Closed by brianteeman** 2016-08-21 16:49 UTC
Labels: No Code Attached Yet
