### ISSUE TITLE
[4b6] un-styled modal button  Components -> Banners -> Tracks -> Export

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#31926] opened 2021-01-08 23:03 UTC
### Steps to reproduce the issue

Joomla 4 admin 
Components -> Banners -> Tracks -> Export 

### Expected result

styled buttons as per the rest of joomla 

### Actual result

<img width="380" alt="Screenshot 2021-01-08 at 23 02 23" src="https://user-images.githubusercontent.com/400092/104073459-a0249c00-5205-11eb-9e83-1e6e70c29b8b.png">

### System information (as much as possible)

safari on macOS

**Comment by chmst** [comment] 2021-01-08 23:36
The buttons are styled as in other modals. Could you please check against batch modals in articles or others? I am on win10, firefox

![modal-buttons](https://user-images.githubusercontent.com/1035262/104075283-95243880-5212-11eb-8571-6d2b20c3be27.PNG)

**Comment by PhilETaylor** [comment] 2021-01-08 23:42
ok you believe what you want to believe. The cancel button is NOT styled. Fact. 

`
<a class="btn btn-secondary" data-dismiss="modal" type="button" onclick="window.parent.Joomla.Modal.getCurrent().close();">Cancel</a>
`

![Screen Recording 2021-01-08 at 11 38 27 pm](https://user-images.githubusercontent.com/400092/104075415-a5381a00-520a-11eb-9d5f-b668a0293fc5.gif)


Here is an example styled close button 

![Screen Recording 2021-01-08 at 11 42 03 pm](https://user-images.githubusercontent.com/400092/104075588-22fc2580-520b-11eb-8329-890456560e53.gif)

**Comment by chmst** [comment] 2021-01-08 23:59
I cannot reproduce this. Mabye someone else.

**Comment by PhilETaylor** [comment] 2021-01-08 23:59
Safari on macOS

**Comment by brianteeman** [comment] 2021-01-09 08:27
It should be a button not an a link<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31926">issues.joomla.org/tracker/joomla-cms/31926</a>.</sub>

**Comment by richard67** [comment] 2021-01-09 11:12
Closing as having a pull request. Please test #31940 . Thanks in advance.

**Closed as completed by richard67** 2021-01-09 11:12 UTC
Labels: No Code Attached Yet
