### ISSUE TITLE
Joomla Global Configuration layout missing

### ISSUE THREAD

**Issue by dfeng99** [joomla/joomla-cms#17790] opened 2017-08-31 03:04 UTC
### Steps to reproduce the issue

Go to the Administrator page http://site/administrator then login as administrator.
click the Global configuration button, the layout is missing.

### Expected result
Should be an ordered layout.

### Actual result

no layout

### System information (as much as possible)
Joomla! 3.7.5 Stable [ Amani ]
PHP 5.6.31
MySQL 5.6.37

### Additional comments

Script layouts/joomla/content/options_default.php gets problem in handling field type DatabaseConnection.
All go well when remark loadTemplate('database') in file administrator/templates/isis/html/com_config/application/default.php around line 101.

**Comment by ghost** [comment] 2017-08-31 04:36
Can't confirm.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17790">issues.joomla.org/tracker/joomla-cms/17790</a>.</sub>

**Comment by dfeng99** [comment] 2017-08-31 05:04
![globalconfiguration](https://user-images.githubusercontent.com/11707571/29907081-03f7767a-8e4c-11e7-929c-b0e8bde13fa9.png)

The Global Configuration gets no layout after upgrade, it did already happened when I run version 3.7.3 and was not fixed in 3.7.5. So I try to figure it out the problem and found the problem as described.

**Comment by ghost** [comment] 2017-08-31 05:18
Disable all non-Core-Extensions, than enable one by one to look if its caused by an Extension. For further Help please ask on the [forums](https://forum.joomla.org/). This repository concerns Joomla coding. For this Reason please close this Issue, thanks.

**Closed as completed** 2017-08-31 05:18 UTC
Labels: No Code Attached Yet
