### ISSUE TITLE
Empty alert msg when draging zip to install screen

### ISSUE THREAD

**Issue by AboutTimeIT** [joomla/joomla-cms#42102] opened 2023-10-09 17:38 UTC
### Steps to reproduce the issue
Download a component via Firefox
Open in Joomla! the extention install page
Open in Firefox the active downloads and drag the just downloaded file directly into the Upload & Install Joomla Extension window

### Expected result
That the extention would be installed

### Actual result
I get an alertbar on top of my screen with no text in it

### System information (as much as possible)
The currently installed Joomla! version is "‎5.0.0-rc2-dev" ‎5.0.0-rc2-dev
Firefox 118.0.1 (64-bits) (most recent version)

See attached screendumps

### Additional comments
Not tested in other browsers so not sure if that would be an issue![screen shot 2023-10-09 at 12 36 17](https://issues.joomla.org/uploads/1/d33fb320d097a5d3650e8cabbbcc5373.jpg)
![screen shot 2023-10-09 at 12 36 20](https://issues.joomla.org/uploads/1/2695c1fec6511f0dad6607eec66526de.jpg)

**Comment by alikon** [comment] 2023-10-09 17:52
did this happened on not dark-mode too?

**Comment by AboutTimeIT** [comment] 2023-10-09 18:25
@alikon yes, it also happens in the lightmode
The extention I tried ti install is not suitable for J5 yet, but thats NOT the problem.
The errormessage is empty, not showing text.
Tried to select text, if some should bein the errorfield, but there's none.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42102">issues.joomla.org/tracker/joomla-cms/42102</a>.</sub>

**Comment by chmst** [comment] 2023-10-09 19:09
Can you install other components, for example the patchtester 4.3.1 from here https://github.com/joomla-extensions/patchtester/releases?

**Comment by richard67** [comment] 2023-10-09 19:16
Does it also happen when you use the green "Or browse for file" button? Or only when using drag and drop? Are there any javascript errors shown in the browser console which could be related?

**Comment by AboutTimeIT** [comment] 2023-10-10 15:37
When installing the patchtester i get the message "Installation of the component was successful."in a green bar on top of the screen (as expected).
But when something goes wrong I just see the red bar with no info in it.
Shouldn't be there a text like "you messed up, please fix it"? soz what I ment is "Something wentr wrong please check" ;-P<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42102">issues.joomla.org/tracker/joomla-cms/42102</a>.</sub>

**Comment by richard67** [comment] 2023-10-10 16:10
> But when something goes wrong I just see the red bar with no info in it. Shouldn't be there a text like "you messed up, please fix it"? soz what I ment is "Something wentr wrong please check" ;-P

@AboutTimeIT Sure. But as we can't reproduce your issue on a clean installation in our environments, @chmst has asked you for testing if Patchtester installation works, and I have also asked you to check if the green "Or browse for file" button works when drag and drop would not work. My question you haven't answered yet. We ask such questions because the answer might help us to locate the source of the problem.

**Comment by richard67** [comment] 2023-10-10 16:21
@AboutTimeIT With which component did you have that problem?

**Comment by AboutTimeIT** [comment] 2023-10-11 12:33
@richard67 Used the green browse button to select the file and install it.
I get the message: "An error has occurred.
0 Call to a member function load() on bool"
This is correct due to the fact that it's NOT an J5 extention, but at least I get an error that tells something.
On the methode I used I just get a red bar on top of the window.

The component I tried to install is https://www.joomill-extensions.com/downloads/pricelist (the free version)
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42102">issues.joomla.org/tracker/joomla-cms/42102</a>.</sub>

**Comment by Quy** [comment] 2024-02-10 04:50
@AboutTimeIT Please advise if this is still an issue as I cannot reproduce it with the component you mentioned.

**Comment by Quy** [comment] 2024-02-16 14:34
Closing as non-reproducible.

**Closed as completed by Quy** 2024-02-16 14:34 UTC
Labels: No Code Attached Yet, Information Required
