### ISSUE TITLE
[5.1 and 5.2] Multilingual Associations broken if the Option "Multilingual Associations" is "Hide"

### ISSUE THREAD

**Issue by newtastic** [joomla/joomla-cms#44224] opened 2024-10-10 13:54 UTC
### Steps to reproduce the issue
Install a fresh Joomla 5.1 or 5.2 (RC4)
Setup a small Multilingual Site (Activate Filter Plugin, create one or two articles)
Go to Content > Articles > Options > Tab "Editing Layout" > Set the Option "Multilingual Associations" to "Hide"
Go now to Components > Multilingual Associations > Click on an Article > Choose a Target Language

### Expected result
See on the left side the Reference Article and on the right side the Target Article.

### Actual result
The Joomla Logo shows infinite and the Browser Console shows this:

Uncaught TypeError: o.querySelector(...) is null
    <anonymous> http://localhost/j5114/media/com_associations/js/sidebyside.min.js?dafb01:4

### System information (as much as possible)
Tested on Joomla 5.1.4 and 5.2 RC4
No additional Extensions

### Additional comments
None

**Comment by fgsw** [comment] 2024-10-10 14:02
Give the issue a meaningful title. Have a look at other issues where a user know by reading the title what the issue is about.

**Comment by brianteeman** [comment] 2024-10-10 16:34
Bug confirmed although I get a different error
```
sidebyside.min.js?0fbb40:4 Uncaught TypeError: Cannot read properties of null (reading 'remove')
    at HTMLIFrameElement.<anonymous> (sidebyside.min.js?0fbb40:4:2277)Understand this error
sidebyside.min.js?0fbb40:4 Uncaught TypeError: Cannot read properties of null (reading 'classList')
    at HTMLIFrameElement.<anonymous> (sidebyside.min.js?0fbb40:4:3342)
```

**Comment by newtastic** [comment] 2024-10-10 17:31
Also tested the same steps with Joomla 4.4.8 and this works like excepted.

**Comment by richard67** [comment] 2024-10-27 15:43
Closing as having a pull request. Please test #44360 . Thanks in advance.

**Closed as completed by richard67** 2024-10-27 15:43 UTC
Labels: No Code Attached Yet, bug
