### ISSUE TITLE
Display also childs when searching a specific tag

### ISSUE THREAD

**Issue by mattiaverga** [joomla/joomla-cms#18461] opened 2017-11-01 08:11 UTC
In backend com_tags when searching for a tag name the list is filtered with only tags which include that string in the name. There's no way to display also child tags of those results.
This is uncomfortable when you have a very high number of tags and you want to view all childs of a specific tag: there's no way to do that, unless you move page by page to the page of that tag.

For example let's say we have
...
- alpha
- beta
  - child 1
  - child 2
- gamma
...

To display all childs of beta I need to move to the exact page of beta in the tag list, because if I search for "beta" I get only beta tag shown.

There should be a way to search for "beta" and then get a list of all childs.

**Comment by infograf768** [comment] 2017-11-01 08:59
We do have the same behavior with categories and menu items, this whatever the Max levels chosen.

**Comment by ghost** [comment] 2017-11-02 09:35
@infograf768 close this Issue as expected Behaviour?

**Comment by tonypartridge** [comment] 2017-11-02 22:31
Hello,

But to keyword search for 'Beta' and then find a sub tag of say 'old' just would not make any sense since I have not searched for old.

Instead you should select a parent Filter i.e. Beta you can scroll the list of tags or type Beta on the list. and it should show all children.

**Comment by ghost** [comment] 2017-11-03 06:29
Closed as expected Behaviour. Can always reopened for further Comments.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18461">issues.joomla.org/tracker/joomla-cms/18461</a>.</sub>

**Closed as completed by ghost** 2017-11-03 06:29 UTC
Labels: No Code Attached Yet
