### ISSUE TITLE
Debug throws "Trying to get property of non-object"

### ISSUE THREAD

**Issue by photodude** [joomla/joomla-cms#8940] opened 2016-01-20 03:01 UTC
Replicate issue:
1. Turn debug with logging on
2. Go to Site side with template protostar
3. Edit article
4. Use editor button for article

Modal throws the following errors
Notice: Trying to get property of non-object in \plugins\system\debug\debug.php on line 1794
Notice: Trying to get property of non-object in \plugins\system\debug\debug.php on line 1795

for line 1794
Call Stack

num | Time | Memory | Function | Location
------------ | ------------- | ------------ | ------------- |------------
1 | 0.0030 | 142712 | {main}( ) | ..\index.php:0
2 | 0.1277 | 2329448 | JApplicationCms->execute( ) | ..\index.php:45
3 | 1.0734 | 10442456 | JApplicationBase->triggerEvent( ) | ..\cms.php:274
4 | 1.0734 | 10442488 | JEventDispatcher->trigger( ) | ..\base.php:106
5 | 1.0734 | 10442800 | JEvent->update( ) | ..\dispatcher.php:160
6 | 1.0735 | 10443080 | call_user_func_array ( ) | ..\event.php:69
7 | 1.0735 | 10443096 | PlgSystemDebug->onAfterRespond( ) | ..\event.php:69
8 | 1.0785 | 10462864 | PlgSystemDebug->display( ) | ..\debug.php:254
9 | 1.0788 | 10463896 | PlgSystemDebug->displayProfileInformation( ) | ..\debug.php:373
10 | 1.0830 | 10480256 | PlgSystemDebug->writeToFile( ) | ..\debug.php:651

for line 1795
Call Stack

num | Time | Memory | Function | Location
------------ | ------------- | ------------ | ------------- |------------
1 | 0.0030 | 142712 | {main}( ) | ..\index.php:0
2 | 0.1277 | 2329448 | JApplicationCms->execute( ) | ..\index.php:45
3 | 1.0734 | 10442456 | JApplicationBase->triggerEvent( ) | ..\cms.php:274
4 | 1.0734 | 10442488 | JEventDispatcher->trigger( ) | ..\base.php:106
5 | 1.0734 | 10442800 | JEvent->update( ) | ..\dispatcher.php:160
6 | 1.0735 | 10443080 | call_user_func_array ( ) | ..\event.php:69
7 | 1.0735 | 10443096 | PlgSystemDebug->onAfterRespond( ) | ..\event.php:69
8 | 1.0785 | 10462864 | PlgSystemDebug->display( ) | ..\debug.php:254
9 | 1.0788 | 10463896 | PlgSystemDebug->displayProfileInformation( ) | ..\debug.php:373
10 | 1.0830 | 10480256 | PlgSystemDebug->writeToFile( ) | ..\debug.php:651

Discovered while testing #8508

**Comment by infograf768** [comment] 2016-01-20 09:37
I can't reproduce these Notices here.
1794 is an empty line
1795 is `if ($app->isSite())`

**Comment by alikon** [comment] 2016-01-20 11:58
@infograf768 to replicate the issue you need to  have enabled log SQL executed query, I'll work for a fix

**Comment by infograf768** [comment] 2016-01-20 18:14
Ok, confirming here.

lines 1797 and line 1798

```

			$alias = $app->getMenu()->getActive()->alias;
			$id    = $app->getMenu()->getActive()->id;

```<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8940">issues.joomla.org/joomla-cms/8940</a>.</sub>

**Comment by alikon** [comment] 2016-01-21 07:28
this can be closed  as there is a PR #8949

**Comment by infograf768** [comment] 2016-01-21 07:37
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8940">issues.joomla.org/joomla-cms/8940</a>

**Comment by infograf768** [comment] 2016-01-21 07:37
Closed as we have https://github.com/joomla/joomla-cms/pull/8949<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8940">issues.joomla.org/joomla-cms/8940</a>.</sub>

**Closed by infograf768** 2016-01-21 07:37 UTC
