### ISSUE TITLE
[4.2.6]SVG Logo/Image not displayed in Cassiopeia

### ISSUE THREAD

**Issue by PhocaCz** [joomla/joomla-cms#39538] opened 2023-01-01 22:18 UTC
### Steps to reproduce the issue

- Go to Site Template Styles - edit Cassiopeia - set SVG logo/image:

![Select image](https://i.imgur.com/bW2yGWK.png)

- Save

### Expected result

SVG logo should be displayed

### Actual result

SVG logo is not displayed

![image](https://i.imgur.com/hcbevRP.png)

Path is correct, if template.css will be disabled, the logo is displayed

![image](https://i.imgur.com/oR6TCLc.png)

### System information (as much as possible)

Joomla 4.2.6
PHP 8.1

**Comment by brianteeman** [comment] 2023-01-02 13:29
should be closed as a duplicate of #39543 

really no point in creating multiple issues for the same problem

**Comment by PhocaCz** [comment] 2023-01-02 13:42
This is no duplicate, even if I set the with and height manually for the SVG, it still does not display the SVG image. These are two different problems

https://github.com/joomla/joomla-cms/issues/39543 - zero is wrongly set but if manually corrected, the SVG ist still not displayed

**Comment by PhocaCz** [comment] 2023-01-02 13:45
Please read carefully the first post:

"Path is correct, if template.css will be disabled, the logo is displayed"

This seems like some problem in template.css

**Comment by brianteeman** [comment] 2023-01-02 18:28
```
img {
  width: 100%;
}
```

not rocket science for someone who has developed as many extensions as you.

**Comment by bembelimen** [comment] 2023-01-02 19:01
>
> not rocket science for someone who has developed as many extensions as you.

Is this needed?

**Comment by PhocaCz** [comment] 2023-01-02 19:45
> not rocket science for someone who has developed as many extensions as you.

This is a problem report
- it might be a Cassiopeia template issue - then it might be valuable information for the Cassiopeia template development team
- also it could be a problem with saving parameters for images path - this could be valuable information for core developers

No comments on repeated personal attacks on users who report some issue. It's a recurring theme that has contributed to the decline in Joomla's popularity, but someone else has to deal with that.

**Comment by brianteeman** [comment] 2023-01-02 19:52
> 
> * it might be a Cassiopeia template issue - then it might be valuable information for the Cassiopeia template development team

You already identified it is an issue in the template with your test removing the css

> * also it could be a problem with saving parameters for images path - this could be valuable information for core developers
> 

Again you identified it as an issue with the template by temoving the css

> No comments on repeated personal attacks on users who report some issue. It's a recurring theme that has contributed to the decline in Joomla's popularity, but someone else has to deal with that.

apologies for letting my frustration get the better

**Comment by PhocaCz** [comment] 2023-01-02 19:59
>You already identified it is an issue in the template with your test removing the css

Yes, but I can't say it's 100% a CSS problem, because that CSS can be built on an HTML parameter that can be wrong.

So, there can be two problems
a) in template.css
b) but even in HTML which doesn't deliver what template.css expects

**Comment by prajwalah28** [comment] 2023-01-08 05:36
in css file
img {
  width: 100%;
}

.brand-logo img {
  width: 100%;
}

**Comment by richard67** [comment] 2023-01-08 17:14
Closing as having a pull request. Please test #39574 . Thanks in advance.

**Closed as completed by richard67** 2023-01-08 17:14 UTC
Labels: No Code Attached Yet, Frontend Template

**Comment by AmyKrizanWang** [comment] 2023-04-20 14:34
> ### Steps to reproduce the issue
> * Go to Site Template Styles - edit Cassiopeia - set SVG logo/image:
> 
> ![Select image](https://camo.githubusercontent.com/760cf2656f1a510c08faeb01854455f3a5b88b01c3ea395ec2ef0df0b8332e53/68747470733a2f2f692e696d6775722e636f6d2f6257327947574b2e706e67)
> 
> * Save
> 
> ### Expected result
> SVG logo should be displayed
> 
> ### Actual result
> SVG logo is not displayed
> 
> ![image](https://camo.githubusercontent.com/87fd9c39a8b2e6df53dc919dcc0401e10fad23ac3383c81633ac0cfc219b8b2b/68747470733a2f2f692e696d6775722e636f6d2f686362657652502e706e67)
> 
> Path is correct, if template.css will be disabled, the logo is displayed
> 
> ![image](https://camo.githubusercontent.com/8c619bf12a1701f452265fc6700a4cfd0b80779fb22325ff2a4465dcc6888f47/68747470733a2f2f692e696d6775722e636f6d2f6f523654434c632e706e67)
> 
> ### System information (as much as possible)
> Joomla 4.2.6 PHP 8.1
> 
> ### Additional comments


Hi there, 
Does anyone have a good solution on how to fix the SVG file not displaying yet? need some help here, please.
Running the J4.3.0 version with the Cassiopeia template, the header and footer logo will not display svg logo.
For the header logo, if I add a "Tagline" description for the SVG file, then the logo will be displayed alone with the Tagline content.

Content > Media > Options >Media added "Allowed Exentions" == svg,SVG
Legal image Extentions (File Types) == svg
Legal MIME Types == image/svg+xml,application/svg+xml

rebooted the apache server, no luck!

Thank you ;-)

**Comment by brianteeman** [comment] 2023-04-20 15:08
unable to replicate this - sorry

**Comment by AmyKrizanWang** [comment] 2023-04-20 20:23
For Header logo fixer:
How to get Joomla4 with Cassiopeia Template to work

J4 dashboard > Content > Media > Create a new Folder "svgs"
ftp upload your svg logo file to this folder
/var/www/html/images/svgs/upload the logo

Topright "Options" in the Media
Allowed Extensions > add > "svg,SVG"
Legal Image Extensions (File Types) > add > "svg"
Legal MIME Types > add > ",image/svg+xml,application/svg+xml"

SAVE

J4 dashboard > System > Templates > Site Template Styles > Cassiopeia - Default >

/images/svgs/header-logo.svg

Tagline (this is a must-step):
i have added 20x The &nbsp entity "                                         "

SAVE

I will update once i have a fixer for the Footer svg file ;-)

**Comment by brianteeman** [comment] 2023-04-20 21:18
@AmyKrizanWang as stated before. I can not replicate this issue. It works perfectly for me without doing anything with the tagline
