### ISSUE TITLE
REGRESSION: date of article and module manager broken in persian language

### ISSUE THREAD

**Issue by farhadst** [joomla/joomla-cms#6207] opened 2015-02-27 07:51 UTC
install joomla 3.4
install persian language
set administrator panel (backend) to persian language
1. create a article, date is ok but when edit article date is broken!
(when backend language set to En, everything is ok)
![article-edit](https://cloud.githubusercontent.com/assets/8976056/6408981/57264512-be72-11e4-8e11-2416745b0f43.jpg)

_______________
2. in module manager and edit module, tabs of "Menu Assignment" "Module Permissions" and "Advanced" is hidden. (but when backend language set to En everything is ok)
![module-edit](https://cloud.githubusercontent.com/assets/8976056/6408985/6032e0e8-be72-11e4-9818-994396d46ceb.jpg)

**Comment by infograf768** [comment] 2015-02-27 07:56
I can't reproduce your jalali date error here with the registered Persian language pack.
![screen shot 2015-02-27 at 08 54 59](https://cloud.githubusercontent.com/assets/869724/6409077/784f9afe-be5e-11e4-9542-0eac09b87f5f.png)

**Comment by farhadst** [comment] 2015-02-27 08:09
Please set backend language to persian and logout joomla, then again login with persian language!

**Comment by infograf768** [comment] 2015-02-27 08:19
Same. no issue for the date.

BUT I confirm the issue for the modules tabs and this is a big regression!

**Comment by brianteeman** [comment] 2015-02-27 08:26
I can confirm that there is an issue with the persian date. 
See how it is displayed within the article view and the article list
I think I saw a similar report with users of the Thai calendar in the forum

![screen shot 2015-02-27 at 02 25 25](http://issues.joomla.org/uploads/1/acca7af3502181a4739c47eca69a3015.png)

![screen shot 2015-02-27 at 02 26 00](http://issues.joomla.org/uploads/1/14b68d45df469a64a506472303d36c5f.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6207">issues.joomla.org/joomla-cms/6207</a>.</sub>

**Comment by infograf768** [comment] 2015-02-27 09:13
date has to be tested with debug OFF as there is no uncompressed jalali calendar_setup

Can't find why modules tabs don't show

**Comment by brianteeman** [comment] 2015-02-27 09:18
My tests were with debug OFF<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6207">issues.joomla.org/joomla-cms/6207</a>.</sub>

**Comment by brianteeman** [comment] 2015-02-27 09:19
The thai language issue was a JS error and unrelated see http://forum.joomla.org/viewtopic.php?f=706&t=874697&p=3272023#p3272023<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6207">issues.joomla.org/joomla-cms/6207</a>.</sub>

**Comment by infograf768** [comment] 2015-02-27 09:35
I found out that the specifc calendar js file for Persian is the reason why module tabs are broken
Although dates did show OK here, I find this js error in that file.

```
Timestamp: 27/02/15 10:02:16
Error: TypeError: C.inputField.form.addEvent is not a function
Source File: http://localhost:8888/trunkgitnew/media/fa-IR/js/calendar-setup.js
Line: 11
```

**Comment by infograf768** [comment] 2015-02-27 09:44
Issue is this chnage
```
-JHtml::_('behavior.formvalidation');
+JHtml::_('behavior.formvalidator');
```
I.e. mootools is no more loaded

The fa-IR js file has to be modified

**Comment by brianteeman** [comment] 2015-02-28 10:27
As the fix is beyond the control of the core of joomla and is something for the Persian Translation Team can this be closed here?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6207">issues.joomla.org/joomla-cms/6207</a>.</sub>

**Comment by Bakual** [comment] 2015-02-28 14:13
I would like to leave that open simply because I doubt the the translators will be able to fix it themself.
At least till we got the attention of someone willing and capable of fixing it. Shouldn't be that hard if you're a bit familiar with MooTools / jQuery.

@dgt41 or @fedik maybe?

**Comment by brianteeman** [comment] 2015-02-28 14:15
Maybe check with the Thai translation team as it looks like they fixed an
identical issue with their non-gregorian calendar

On 28 February 2015 at 14:13, Thomas Hunziker <notifications@github.com>
wrote:

> I would like to leave that open simply because I doubt the the translators
> will be able to fix it themself.
> At least till we got the attention of someone willing and capable of
> fixing it. Shouldn't be that hard if you're a bit familiar with MooTools /
> jQuery.
>
> @dgt41 <https://github.com/dgt41> or @fedik <https://github.com/fedik>
> maybe?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6207#issuecomment-76527629>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Bakual** [comment] 2015-02-28 14:31
Thanks for that info. I've sent them an email to ask what they did.

**Comment by Fedik** [comment] 2015-02-28 14:48
I can confirm error on Module edit, but in content all looks good .

But it very tricky to fix/debug, as they do not provide uncompressed version of calendar.js
and lack of knowledge for Persian language :smile:

**Comment by Bakual** [comment] 2015-02-28 15:03
> and lack of knowledge for Persian language

Aww, comon. It's sure simpler to learn than JavaScript :smiley:

**Comment by dgt41** [comment] 2015-02-28 21:57
https://gist.github.com/dgt41/cfcbe426029726ef63e0
This might be a possible solution. Can somebody test it by replacing the calendar-setup.js with the code of the gist?

**Comment by infograf768** [comment] 2015-03-01 06:47
@test
https://gist.github.com/dgt41/cfcbe426029726ef63e0
Does not solve the issue here.

**Comment by infograf768** [comment] 2015-03-02 07:15
@dht41

If I change ONLY in the original file
`C.inputField.form.addEvent('submit', function() {`
to
`C.inputField.form.addEventListener('submit', function() {`

It looks like working here.

**Comment by farhadst** [comment] 2015-03-02 08:47
@infograf768 
i have change this code in original file (calendar-setup.js)
But does not solve the issue!

in date article problem, when save article after 4time, date is ok:

first
![1](https://cloud.githubusercontent.com/assets/8976056/6437556/b5060234-c0d5-11e4-8f44-fb8e7e1024b5.jpg)

second
![2](https://cloud.githubusercontent.com/assets/8976056/6437560/c65c7afe-c0d5-11e4-9c96-10d8360fa42c.jpg)

Third
![3](https://cloud.githubusercontent.com/assets/8976056/6437571/d70ad8e6-c0d5-11e4-975a-1d13d795c4ac.jpg)

Fourth
![4](https://cloud.githubusercontent.com/assets/8976056/6437574/e2a228e4-c0d5-11e4-99a2-399185029cf9.jpg)

**Comment by Fedik** [comment] 2015-03-02 09:55
@farhadst what browser you use?

@infograf768 it could not work in IE,
 this should be more safe, in theory:

```javascript
var method, event;
if(document.addEventListener){
 method = 'addEventListener';
 event = 'submit';
} else {
 method = 'attachEvent';
 event = 'onsubmit';
}

C.inputField.form[method](event, function() {
```

**Comment by farhadst** [comment] 2015-03-02 10:21
@Fedik 
i have replace this code in original file (calendar-setup.js)
and problem with module tab fix. thanks for this solution.

But does not solve article date!
i check this problem in firefox 35.0.1  &  google chrome 40.0.2214.115 m (64-bit) & IE 11 and cache is disabled!

**Comment by dgt41** [comment] 2015-03-02 14:08
@infograf768 I thought that I changed only that part on that file :)
@Fedik Thanks for the full proof solution!
@farhadst The file calendar.js also got some extra code for jalali, which is quite hard to go through because this file is compressed. What I did in calendar-setup.js was to compare it with the normal of joomla (both compressed and normal), and maybe this is the way to debug this error as well

**Comment by Fedik** [comment] 2015-03-02 14:27
something tells me that it based on https://github.com/farhadi/JalaliJSCalendar :smile:

**Comment by dgt41** [comment] 2015-03-02 14:38
@Fedik I will bet that the problem here is the code to support multiple instances...

**Comment by Fedik** [comment] 2015-03-02 15:54
@dgt41 this simple to check, just leave the calendar only for one field, other set to text, example

**Comment by dgt41** [comment] 2015-03-02 17:04
This is the line that produces the error:
```javascript
C.inputField.value = date.print(C.ifFormat, 'jalali', C.langNumbers);
```

**Comment by dgt41** [comment] 2015-03-02 17:12
I updated the gist: https://gist.github.com/dgt41/cfcbe426029726ef63e0
Please mind that line 36 needs to be either true or false, true means local numbers, names and false means local names but "english" numbers
@farhadst please try it, and see if it works for you with either settings

**Comment by infograf768** [comment] 2015-03-02 18:02
@dgt41 
I confirm that, here, <b>on Firefox</b>, your js does not quite work.
![screen shot 2015-03-02 at 18 54 01](https://cloud.githubusercontent.com/assets/869724/6446780/93b5dcde-c10d-11e4-973f-1ed40ba615c9.png)

if I only modify the line above in the older js, 
If I change ONLY in the original file
`C.inputField.form.addEvent('submit', function() {`
to
`C.inputField.form.addEventListener('submit', function() `
I get
![screen shot 2015-03-02 at 18 57 16](https://cloud.githubusercontent.com/assets/869724/6446856/1eae560e-c10e-11e4-8c00-c23352df8898.png)


Then, If I use 'true" for langNumbers, I get:
![screen shot 2015-03-02 at 19 01 11](https://cloud.githubusercontent.com/assets/869724/6446914/a144ad7a-c10e-11e4-84a4-f14a530b60f3.png)

**Comment by infograf768** [comment] 2015-03-02 18:06
btw, we would not be B/C with langNumbers set to true as anyway the manager will not display the Persian numbers. Only the calendar will. But that is a choice for the Persian language team coordinator.

**Comment by infograf768** [comment] 2015-03-02 18:09
@farhadst 

When testing, you should make sure all cache are deleted, including browser cache. The best even is to logout, quit browser and launch again.

**Comment by dgt41** [comment] 2015-03-02 19:01
One more try here:
The first correction as stated above by @infograf768 (or better with the lines of @Fedik)
And also this:
```javascript
if(dateEl&&parseInt(dateEl.value)!=0&&dateEl.value!=''){
	var date=Date.parseDate(dateEl.value||dateEl.innerHTML,dateFmt,'gregorian');
	//C.inputField.value=date.print(C.ifFormat,'jalali',C.langNumbers);
}
else {
	C.date=new Date();
}
```
Commenting out that line seems to correct the problem of repeated saves. But I don;t know if this is the expected output, format.
@farhadst Can you try this?

**Comment by infograf768** [comment] 2015-03-03 09:12
A correction to my former reports:
Although I get the original display fine, it is then broken when I save and I get weird results of the type shown by @farhadst

**Comment by farhadst** [comment] 2015-03-03 11:25
@dgt41  i replace this js file https://gist.github.com/dgt41/cfcbe426029726ef63e0
problem with module tab fix but in problem article date, after each save, date is reset, for example: if article date is 1/2/2015, after save article, date reset to now (3/3/2015)

@infograf768 i replace  C.inputField.form.addEventListener('submit', function()  to orginal js
problem with module tab fix but date broken after save not solve

@dgt41 when delete this line: //C.inputField.value=date.print(C.ifFormat,'jalali',C.langNumbers)
article date not shown to jalali and shown to Gregorian calendar! and date also reset after each save time.

**Comment by mhehm** [comment] 2015-03-07 16:40
Hi, before of joomla 3.4, calender field convert jalali date to gregorion before submit form, but it does not convert it befor submit.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6207">issues.joomla.org/joomla-cms/6207</a>.</sub>

**Comment by dgt41** [comment] 2015-03-08 01:21
@mhehm @farhadst Can you try this
```javascript

var dateEl=C.inputField||C.displayArea;
var dateFmt=C.inputField?C.ifFormat:C.daFormat;
if(dateEl&&parseInt(dateEl.value)!=0&&dateEl.value!=''){
	if (C.ifFormat && !C.inputField.readOnly)
	{
		date=dateEl.value;
	}
	else if (C.inputField.readOnly)
	{
		var date=Date.parseDate(dateEl.value,dateFmt,'gregorian');
		C.inputField.value=date.print(C.ifFormat,'jalali',C.langNumbers);
	}
}
else {
	C.date=new Date();
}

function H(K) {
```
Or try https://gist.github.com/dgt41/cfcbe426029726ef63e0 (updated!)

**Comment by infograf768** [comment] 2015-03-08 07:15
@test
Editing an existing article, I get:

![screen shot 2015-03-08 at 08 07 57](https://cloud.githubusercontent.com/assets/869724/6544971/4a5688d4-c56a-11e4-96be-29c855ccc098.png)

Creating a new article I get before save:

![screen shot 2015-03-08 at 08 10 27](https://cloud.githubusercontent.com/assets/869724/6544975/aa1bda4e-c56a-11e4-91cd-d833839eb242.png)

After choosing a date, before save:

![screen shot 2015-03-08 at 08 11 42](https://cloud.githubusercontent.com/assets/869724/6544980/cc28bfee-c56a-11e4-8c91-e25724a72d6a.png)

After saving:

![screen shot 2015-03-08 at 08 12 24](https://cloud.githubusercontent.com/assets/869724/6544985/e586c166-c56a-11e4-9d95-42e46be0fa39.png)

In the manager:

![screen shot 2015-03-08 at 08 13 55](https://cloud.githubusercontent.com/assets/869724/6544990/2009bb72-c56b-11e4-9ca2-48a045635ea2.png)

Test fails.

**Comment by infograf768** [comment] 2015-03-08 07:31
Also, when switching to en-GB, I see that the date for publish up that was saved in the db is the jalali date and not the gregorian.

![screen shot 2015-03-08 at 08 28 30](https://cloud.githubusercontent.com/assets/869724/6545015/2e3517f8-c56d-11e4-953d-17528da0366a.png)

**Comment by farhadst** [comment] 2015-03-08 07:41
@mhehm exactly, This convert does not happen!

**Comment by mhehm** [comment] 2015-03-08 09:19
in joomla before joomla 3.4, js file add a function to form submit action that it will convert jalali date to gregorian after click save button on the fly exactly before submit form. it do not work now.

**Comment by dgt41** [comment] 2015-03-08 19:15
@infograf768 @mhehm @farhadst Sorry for this. 
I spent some time to proper solve this
Please test again https://gist.github.com/dgt41/cfcbe426029726ef63e0

Or try the code:
```javascript
jQuery(document).ready(function(){
	jQuery.fn.addEvent = jQuery.fn.bind;

	C.inputField.form.addEvent('onsubmit', function () {
		var dateEl = C.inputField || C.displayArea;
		var dateFmt = C.inputField ? C.ifFormat : C.daFormat;
		if (dateEl && parseInt(dateEl.value) != 0 && dateEl.value != '') {
			console.log(dateEl.value);
			var date = Date.parseDate(dateEl.value || dateEl.innerHTML, dateFmt, 'jalali');
			C.inputField.value = date.print(C.ifFormat, 'gregorian', C.langNumbers);
		}
	});
});
```
I hope this one solves all the problems here!

**Comment by dgt41** [comment] 2015-03-08 22:25
One final thought here:
There IS a problem with binding something to `submit` with jquery and I just found that there is a PR that corrects this #3484.
If that PR [#3484] gets merged this code can be simplified a bit more!

So @Bakual can you see if that can also gets merged? (will save us in the future with similar situations)

**Comment by mhehm** [comment] 2015-03-09 04:01
Hi,
I tested your last code. it work.
thank you.

**Comment by farhadst** [comment] 2015-03-09 06:53
@dgt41 i test this code https://gist.github.com/dgt41/cfcbe426029726ef63e0
and it work
thanks :)

**Comment by infograf768** [comment] 2015-03-09 07:45
Works here too!

@mhem
I suggest you modify the fa-IR pack to add 2 js files.
these would be the exact copy of this calendar-setup.js proposed here + a copy of the existing fa-IR calendar.js (no need to really compress the originals).
Change the names of these copies to, respectively:
calendar-setup-uncompressed.js
and
calendar-uncompressed.js

Therefore jalali date will also work when Debug is on.
Add the copied files in the pack js folder.
your site install.xml would be
```
<media destination="fa-IR">
	    <filename>index.html</filename>
		<filename>js/index.html</filename>
		<filename>js/calendar-setup.js</filename>
		<filename>js/calendar.js</filename>
		<filename>js/calendar-setup-uncompressed.js</filename>
		<filename>js/calendar-uncompressed.js</filename>
	</media>
```

**Comment by infograf768** [comment] 2015-03-09 07:46
@dgt41 
Thanks a lot! I was frightened we would lose fa-IR for Joomla!

**Comment by mhehm** [comment] 2015-03-09 10:22
@infograf768 
I created language package file with this fix and emailed to you.

**Comment by infograf768** [comment] 2015-03-09 10:31
This can now be closed

**Comment by roland-d** [comment] 2015-03-09 10:33
Closed as requested.

**Closed by roland-d** 2015-03-09 10:33 UTC
Labels: No Code Attached Yet

**Comment by mhehm** [comment] 2015-03-24 08:37
Hi, one more issue.
if on page mootools not load, below error appear:
TypeError: C.inputField.form.addEvent is not a function

**Comment by dgt41** [comment] 2015-03-24 13:04
@mhehm have you tried to clean your browser’s cache?

**Comment by infograf768** [comment] 2015-03-24 13:19
Also, on which page does it fails exactly?

**Comment by mhehm** [comment] 2015-03-24 15:07
@dgt41 yes, i cleaned my browser cache.
@infograf768  i see this issue on one of my component. but you can see it on joomla user manager.
edit an user, and see firebug console. for user's created date field.
it is readonly but if you save user, date will get wrong value.The error is for addEvent function that is one of mootools function and because of that joomla is in converting mootools to jquery, in forms that not more load mootools and have a date field, this error appear.

**Comment by dgt41** [comment] 2015-03-24 15:13
@mhehm @infograf768 
Since 3.4.1 PR #3484 is part of joomla so the code for jalali calendar can be simplified a little bit. (hopefully this will also eliminate this addEvent error)
I will provide a gist

**Comment by infograf768** [comment] 2015-03-25 09:51
I confirm the error:
Timestamp: 25/03/15 10:43:45
Error: TypeError: C.inputField.form.addEvent is not a function
Source File: http://localhost:8888/trunkgitnew/media/fa-IR/js/calendar-setup.js
Line: 14

**Comment by dgt41** [comment] 2015-03-25 13:59
@mhehm @infograf768 Here we go then:
on calendar-setup replace the function after line 55 with:
```javascript
	jQuery(document).ready(function() {

		var form_id = "#"+C.inputField.form.id;

		jQuery(form_id).on("submit", function() {
			var dateEl = C.inputField || C.displayArea;
			var dateFmt = C.inputField ? C.ifFormat : C.daFormat;
			if (dateEl && parseInt(dateEl.value) != 0 && dateEl.value != '') {
				var date = Date.parseDate(dateEl.value || dateEl.innerHTML, dateFmt, 'jalali');
				C.inputField.value = date.print(C.ifFormat, 'gregorian', C.langNumbers);
			}
		});
	});
```

This will NOT work as there is a BUG on core-uncompressed.js at line 33:
```javascript
        jQuery(form).submit();
```
NEEDS to be:
```javascript
        jQuery(form).trigger("submit");
```

Once you verify that this also works on your setups I will make a PR for core.js

**Comment by dgt41** [comment] 2015-03-25 14:54
Please also test #6580, to get this bug corrected once for good!

**Comment by mhehm** [comment] 2015-03-25 21:34
@dgt41 I tested your last code with #6580 fix, and it worked for me.
Thanks.

**Comment by infograf768** [comment] 2015-03-26 09:58
Works great here too.
Now commenting in #6580

**Comment by balvard** [comment] 2015-04-09 11:57
Salam
I solved this issue.
in your own component just use this code at beginning of file :
JHtml::_('behavior.framework');
and new language package for persian in joomla 3.4.1 is updated
good luck

**Comment by infograf768** [comment] 2015-04-11 05:48
@dgt41 
What is the last iteration for the fa-IR js files

**Comment by dgt41** [comment] 2015-04-11 11:59
```javascript
	jQuery(document).ready(function() {

		var form_id = "#"+C.inputField.form.id;

		jQuery(form_id).on("submit", function() {
			var dateEl = C.inputField || C.displayArea;
			var dateFmt = C.inputField ? C.ifFormat : C.daFormat;
			if (dateEl && parseInt(dateEl.value) != 0 && dateEl.value != '') {
				var date = Date.parseDate(dateEl.value || dateEl.innerHTML, dateFmt, 'jalali');
				C.inputField.value = date.print(C.ifFormat, 'gregorian', C.langNumbers);
			}
		});
	});
```
But will need 3.4.2 for the proper submit binding

**Comment by Fedik** [comment] 2015-04-11 12:19
@dgt41 `jQuery(C.inputField.form)` could save one line, in theory :wink:

**Comment by dgt41** [comment] 2015-04-11 13:43
@infograf768 To elaborate a little more (previous comment was from my mobile):
The last iteration https://github.com/joomla/joomla-cms/issues/6207#issuecomment-86039978 as you already tested and it works for every possible condition. The problem here was that forms didn’t trigger the submit event and although that PR was actually merged in 3.4.1 there is still a bug as the compressed core.js somehow doesn’t have this code. That is the reason I stated that 3.4.2 will be needed, since @Fedik ’s PR is merged and this code is tested against that!

@Fedik Yes you are right here! I guess trying to figure out why this code didn’t execute in conjunction with #6580 I tried all the possible variations I could think, and this just left hanging there 😃

**Comment by infograf768** [comment] 2015-04-12 07:40
@gdt41
I was not asking for me but for the Persian (fa-IR) Translation Team Coordinator.
Can you send him the full file and reference this?
Here are his coordinates:
http://community.joomla.org/translations/joomla-3-translations.html#fa-ir

Thanks

**Comment by mamool** [comment] 2015-07-01 20:50
Hi
I upgrade my joomla to 3.4.2
after update jalali date has problem same first post 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6207">issues.joomla.org/joomla-cms/6207</a>.</sub>

**Comment by farhadst** [comment] 2015-07-01 21:21
Hi @mamool
i have create a new issue for this problem on joomla 3.4.2
Please follow this #7298
