### ISSUE TITLE
Fatal error: Trait 'Joomla\Plugin\System\Webauthn\PluginTraits\AjaxHandler' not found in ROOTDIR\plugins\system\webauthn\webauthn.php on line 34

### ISSUE THREAD

**Issue by Schrubbii** [joomla/joomla-cms#35686] opened 2021-09-28 04:18 UTC
### Steps to reproduce the issue
Opening frontend of freshly installed 4.0.3

### Expected result
Seeing frontend of Joomla

### Actual result
Error-message displaying ($debug = true in configuration):

Call stack
--
# | Function | Location
1 | () | JROOT\plugins\system\debug\debug.php:174
2 | PlgSystemDebug->__construct() | JROOT\libraries\src\Extension\ExtensionManagerTrait.php:242
3 | Joomla\CMS\Application\CMSApplication->loadPluginFromFilesystem() | JROOT\libraries\src\Extension\ExtensionManagerTrait.php:160
4 | Joomla\CMS\Application\CMSApplication->loadExtension() | JROOT\libraries\src\Extension\ExtensionManagerTrait.php:94
5 | Joomla\CMS\Application\CMSApplication->bootPlugin() | JROOT\libraries\src\Plugin\PluginHelper.php:235
6 | Joomla\CMS\Plugin\PluginHelper::import() | JROOT\libraries\src\Plugin\PluginHelper.php:193
7 | Joomla\CMS\Plugin\PluginHelper::importPlugin() | JROOT\libraries\src\Application\CMSApplication.php:739
8 | Joomla\CMS\Application\CMSApplication->initialiseApp() | JROOT\libraries\src\Application\SiteApplication.php:709
9 | Joomla\CMS\Application\SiteApplication->initialiseApp() | JROOT\libraries\src\Application\SiteApplication.php:224
10 | Joomla\CMS\Application\SiteApplication->doExecute() | JROOT\libraries\src\Application\CMSApplication.php:278
11 | Joomla\CMS\Application\CMSApplication->execute() | JROOT\includes\app.php:63
12 | require_once() | JROOT\index.php:32

### System information (as much as possible)
Using xampp & "Joomla_4.0.3-Stable-Full_Package.zip"

### Additional comments
Just installed it on my localhost (xampp), no error while installation process. Right after when I click frontend, I get that error.
Tried re-installing it 2 times already (dropped database and deleted the entire folder, no difference).

**Comment by PhilETaylor** [comment] 2021-09-28 09:52
https://github.com/joomla/joomla-cms/issues/32922
https://github.com/joomla/joomla-cms/issues/31752

**Comment by joomdonation** [comment] 2021-10-30 11:23
If someone get this issue, please delete/rename the file **administrator/cache/autoload_psr4.php** so that Joomla will re-generate it and the issue should be sorted. Closing this issue for now.

**Closed as completed by joomdonation** 2021-10-30 11:23 UTC
Labels: No Code Attached Yet

**Comment by groovedan** [comment] 2021-11-02 08:11
Even though I deleted the file administrator / cache / autoload_psr4.php, I still get the error message and the site is down ... Are there any other ideas? PHP 7.4, Joomla 4.04. The site ran without any problems until yesterday. No system updates were made either. Thanks very much.

**Comment by joomdonation** [comment] 2021-11-02 08:33
@groovedan If you want (and can), you can send information of your site to my email tuanpn@joomdonation.com. I will try to check it for you (however, I would need super admin and FTP account of your site)

**Comment by loretxt** [comment] 2022-02-06 16:34
Hello everyone, I've the same problem, but autoload_psr4.php is missing on my cache folder. Both frontend and backend are offline with the following message: "Fatal error: Trait 'Joomla\Plugin\System\Webauthn\PluginTraits\AjaxHandler'..."
Any idea? 

Joomla 3.10, PHP 7.4
Thanks!

**Comment by brianteeman** [comment] 2022-02-06 16:37
Are you sue you are running Joomla 3.10?

**Comment by loretxt** [comment] 2022-02-06 16:42
I tried to install Joomla 4 but had issues so I restored a backup with a previous version (3.10). Just checked now, to be sure, version file in /libraries/src folder (file attached):

	 * Major release version.
	 *
	 * @var    integer
	 * @since  3.8.0
	 */
	const MAJOR_VERSION = 3;

	/**
	 * Minor release version.
	 *
	 * @var    integer
	 * @since  3.8.0
	 */
	const MINOR_VERSION = 10;

	/**
	 * Patch release version.
	 *
	 * @var    integer
	 * @since  3.8.0
	 */
	const PATCH_VERSION = 5;
	
Thanks
[Version.php.zip](https://github.com/joomla/joomla-cms/files/8010607/Version.php.zip)
!

**Comment by PhilETaylor** [comment] 2022-02-06 16:43
"so I restored a backup "

but you did not delete all the files specific to Joomla 4...

**Comment by brianteeman** [comment] 2022-02-06 16:44
What he said ⬆️⬆️⬆️

**Comment by loretxt** [comment] 2022-02-06 16:47
mmm right, guess this can possibly be the cause, then. Is there a way to check and find which files I need to delete now?

**Comment by brianteeman** [comment] 2022-02-06 16:48
Not possibly the cause it is **100% the cause.**

**Comment by mrownicki** [comment] 2022-05-24 15:02
Clean install 4.1.3 
Windows machine. 
PHP 7.4 error.
Change to PHP 8.0 error.
Manual Delete file autoload_psr4.php 
working.
I give only feedback

**Comment by tasn146** [comment] 2022-08-30 10:56
I deleted the file administrator / cache / autoload_psr4.php, but still get the error message and the site is down. Changed the PHP version but nothing... The site ran without any problems until yesterday. Any ideas ? Thank you very much.
