### ISSUE TITLE
[4.0] Cant save articles using Mysql (PDO) Driver

### ISSUE THREAD

**Issue by dneukirchen** [joomla/joomla-cms#19767] opened 2018-02-23 15:53 UTC
### Steps to reproduce the issue

use mysql (pdo) database driver in system config
save an article

### Expected result

Saved article + Reordering of existing articles. 

### Actual result

```
Save failed with the following error: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(ORDER BY `ordering`) AS new_ordering,`id` AS `pk__0` FROM mmg7m_content WHERE c' at line 3
```

### System information (as much as possible)

4.0dev

**Comment by mbabker** [comment] 2018-02-23 16:04
In the ExceptionHandler can you add `if ($error instanceof \Joomla\Database\Exception\ExecutionFailureException) { echo $error->getQuery(); }` line?  That'll at least print out the query that it's having issues with instead of trying to blindly chase this one.

**Comment by dneukirchen** [comment] 2018-02-23 16:16
Can do that later. for now: 

The problem is that [MysqlQuery](https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/vendor/joomla/database/src/Mysql/MysqlQuery.php) has no method selectRowNumber (which is called when we [reorder in Table](https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Table/Table.php#L1558)), so it uses [DatabaseQuery::selectRowNumber()](https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/vendor/joomla/database/src/DatabaseQuery.php#L1942) 

and `ROW_NUMBER() OVER` causes the mysql error...

**Comment by mbabker** [comment] 2018-02-23 16:30
https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/database/query.php#L1853

:sigh:  Why are we putting code in a base class that isn't database agnostic?  🤦‍♂️   (At least in this case it's easy to copy the same method from the MySQLi query class, but still...)

**Comment by alikon** [comment] 2018-02-23 19:04
4.0 wrong sync   ? 
on the staging branch is from https://github.com/joomla/joomla-cms/pull/13505
and works so ....

**Comment by mbabker** [comment] 2018-02-23 19:08
> 4.0 wrong sync ?

No.  4.0 uses the Framework's Database package.  There are architectural differences in the two packages.  So in this case the problem is the PDO MySQL query class doesn't extend the MySQLi query class so the method needs to be copied in the appropriate repo.

But that still doesn't address the architectural problem of the concrete implementation in the root query class not being generic/usable for all drivers.  If this can't be done in a reusable way then it needs to be made abstract, which sounds like is the case.

**Comment by mbabker** [comment] 2018-02-23 19:10
Ultimately most of the problem boils down to every change in the CMS repo for the database package never got ported to the Framework (bug fixes or features).  So we've had to do a scramble and try to merge years of PRs into the right repo and clearly some stuff didn't get ported over 100% either because it was done in a mad rush or the architectural differences weren't accounted for.

**Comment by alikon** [comment] 2018-02-23 19:20
Fortunately 4.x should manage less database drivers :smile: 

p.s.
you hit the nail

**Comment by mbabker** [comment] 2018-03-18 16:41
Should be fixed after https://github.com/joomla/joomla-cms/commit/09347f4fee4a6c5c35b81c362dd427c28524686d (more specifically https://github.com/joomla-framework/database/commit/bd0e71ea56d30cf0cd8fa274fdc6aae840ee5acb from upstream)

**Comment by kroonsbe** [comment] 2018-03-19 10:24
When trying to save a testarticle I got below mentioned error. I do not know how to fix this in the Joomla 4.0 environment. Database is setvto MySQL(PDO)because that's the only setting I can do during installation.

Error
[code]Save failed with the following error: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(ORDER BY `ordering`) AS new_ordering,`id` AS `pk__0` FROM si51x_content WHERE c' at line 3[/code]<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19767">issues.joomla.org/tracker/joomla-cms/19767</a>.</sub>

**Comment by csthomas** [comment] 2018-03-19 11:56
A few minutes ago I tested the latest 4.0-dev branch and it works on mysql 5.7 by PDO.

**Comment by kroonsbe** [comment] 2018-03-19 12:00
You have a link to the latest dev. version you used?

**Comment by csthomas** [comment] 2018-03-19 12:07
https://github.com/joomla/joomla-cms/archive/4.0-dev.zip should be the latest version.

**Comment by kroonsbe** [comment] 2018-03-19 13:15
thanks, will try that one.

**Comment by brianteeman** [comment] 2018-04-10 12:32
I am closing this at this time as there has been a lot of work on this and related issues since this was last updated. It can always be re-opened if there is still an issue

**Closed as completed by brianteeman** 2018-04-10 12:32 UTC
Labels: No Code Attached Yet, J4 Issue
