### ISSUE TITLE
JLanguage::parseLanguageFiles should also check with symlinks too

### ISSUE THREAD

**Issue by Hanmac** [joomla/joomla-cms#8961] opened 2016-01-22 14:30 UTC
because it might be that in some configuration the language packs are added via symlink,
parseLanguageFiles should use FilesystemIterator::FOLLOW_SYMLINKS to find them too.

there is the the location where it might need to be added.
https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/language/language.php#L1332

**Comment by bertmert** [comment] 2016-01-23 20:23
I cannot confirm this issue.

Maybe I didn't understand because of missing test instructions.

What I've done:
- Installed Joomla! 3.5.0-beta  —  Staging 2016-01-23 in a folder A
- Moved directories
/language/
/administrator/language/
to a folder B (outside Joomla directory).
- Created SymLinks inside A
/language/ pointing to /B/language
/administrator/language/ pointing to /B/administrator/language/

All worked fine.

Installed additional language in backend. All fine.
Could install extensions and found all ini files in directory B.

**Comment by brianteeman** [comment] 2016-01-25 11:12
I did the same as @bertmert with no problems

Please can you provide further information how to replicate this issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8961">issues.joomla.org/joomla-cms/8961</a>.</sub>

**Comment by Hanmac** [comment] 2016-01-25 12:13
just as i thought i can reproduce it with staging because not `/language/` is the Symlink in my case, but `/language/de-DE`

see like that:
```
joomla-cms-staging/language/de-DE -> ../../language/de-DE/
joomla-cms-staging/administrator/language/de-DE -> ../../../administator/language/de-DE/
```

**Comment by brianteeman** [comment] 2016-01-25 15:08
I retested creating a symlink just for the specific language folder

lrwxr-xr-x   1 brian1  admin    12B 25 Jan 15:07 en-GB -> ../../en-GB/


Again no problems

On 25 January 2016 at 12:13, Hans Mackowiak <notifications@github.com>
wrote:

> just as i thought i can reproduce it with staging because not /language/
> is the Symlink in my case, but /language/de-DE
>
> see like that:
>
> joomla-cms-staging/language/de-DE -> ../../language/de-DE/
> joomla-cms-staging/administrator/language/de-DE -> ../../../administator/language/de-DE/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/8961#issuecomment-174487720>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Hanmac** [comment] 2016-01-25 15:20
@brianteeman hm maybe i am not concrete enough what the problem is ... 
the languages are "found" in most cases, they appear in "Installed - Site" and "Installed - Administrator"

but they do not appear in the User Config or in the Login Formular (if the language is detected, it ask you under which language you want to log in)

**Comment by brianteeman** [comment] 2016-02-17 13:01
Ah - I can replicate it now

Steps to reproduce
1. install two additional languages
2. move one of those language to a folder above the web root and create a symlink to it
`# mv joomla-cms-staging/language/ca-ES/ .`
 `# ln -s ca-ES/ joomla-cms-staging/language/`
3. Login to the front end of the web site and edit the user profile
4. Try and change the Frontend language and it will only show english and the language you did not move in the dropdown list of available languages<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8961">issues.joomla.org/joomla-cms/8961</a>.</sub>

**Comment by andrepereiradasilva** [comment] 2016-02-18 18:39
Can't reproduce this.

Using the latest staging i moved a language to the site root (in my case pt-PT), them made a symlink to it in the `/language/` folder.

Them tested in backoffine and frontend and Portuguese language always appeared.

Have you tested with latest staging?

**Comment by brianteeman** [comment] 2016-02-18 19:00
Yes. You notice it if you follow my test instructions. It is only in the
places that the folder is parsed such as the user profile

**Comment by andrepereiradasilva** [comment] 2016-02-18 20:07
i tested with user profile edit view in frontend. No problems.

**Comment by brianteeman** [comment] 2016-02-18 20:49
I made a small video to show the problem and how to replicate it on a site with en-gb, fr-fr and pt-pt

https://www.dropbox.com/s/6n9zlfo355lryyd/8961.mp4?dl=0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8961">issues.joomla.org/joomla-cms/8961</a>.</sub>

**Comment by andrepereiradasilva** [comment] 2016-02-18 21:12
but are you putting it outside the joomla root dir? Do you have php open_basedir configured?

**Comment by brianteeman** [comment] 2016-02-18 21:25
yes as can be seen in the video

no - its the default mamp setup

On 18 February 2016 at 21:12, andrepereiradasilva <notifications@github.com>
wrote:

> but are you putting it outside the joomla root dir? Do you have php
> open_basedir configured?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/8961#issuecomment-185924093>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by andrepereiradasilva** [comment] 2016-02-18 21:56
i'm sorry but i can't reproduce this.

I have latest staging with 4 languages installed (en-GB, de-DE, ru-RU, and pt-PT).
Default language en-GB for admin and site.

Defined pt-PT and en-GB as content languages published and with home menu item. Have language filter activated and language switcher module published.

I moved directory from `/path/to/www/joomla/language/pt-PT` to `/path/to/www/pt-PT` and created a symlink `/path/to/www/joomla/language/pt-PT` that points to `/path/to/www/pt-PT`.

Opened to site in english, logged in, and went to prodile and them edit profile.
Both en-GB and pt-PT appeared in "Frontend Language (optional)" field has they appear in the language switcher and every else.

**Comment by andrepereiradasilva** [comment] 2016-02-18 22:04
I tried to create the symlink like you did and it didn't work...

You ahve to do it like this: `ln -s /path/to/www/pt-PT/ /path/to/www/joomla/language/pt-PT`

**Comment by brianteeman** [comment] 2016-02-18 22:35
I've messed something up the symlinks were not setup correctly - you were
right on that-  it was only creating a folder because I was not using the
full path

Now that I have reset it up and confirmed that the symlink is correct I
cant replicate it any more

@hanmac please can you double check your symlink - maybe you made the same
mistake as me

On 18 February 2016 at 22:04, andrepereiradasilva <notifications@github.com>
wrote:

> I tried to create the symlink like you did and it didn't work...
>
> You ahve to do it like this: ln -s /path/to/www/pt-PT/
> /path/to/www/joomla/language/pt-PT
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/8961#issuecomment-185942627>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment] 2016-02-18 22:36
Sorry for the confusion<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8961">issues.joomla.org/joomla-cms/8961</a>.</sub>

**Comment by andrepereiradasilva** [comment] 2016-02-18 22:49
@brianteeman no problem

**Comment by brianteeman** [comment] 2016-03-22 14:54
It has been one month since the request for further information and as it cannot be replicated (except when I am being an idiot) I am closing this issue - it can always be reopened if more information is provided<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8961">issues.joomla.org/joomla-cms/8961</a>.</sub>

**Closed by brianteeman** 2016-03-22 14:54 UTC
Labels: No Code Attached Yet
