### ISSUE TITLE
Backend: Menu Manager: dropdown size is too small

### ISSUE THREAD

**Issue by Schmidie64** [joomla/joomla-cms#17532] opened 2017-08-14 12:21 UTC
### Steps to reproduce the issue
-Login in the Backend
-Go to Menus
-Go to Manage
-Create a new Menu(with any data)
-In the "Linked Modules" column click the "Add a module for this menu" button
-This will open an modal window and **sometimes** the size of all dropdown boxes are too small!

### Expected result
-dropdown boxes that fits the content
![screen shot 2017-08-14 at 12 21 18](https://issues.joomla.org/uploads/1/6720664093f031690ef41db9524bbcd0.png)

### Actual result
-dropdown boxes with the width set to 14px.
![screen shot 2017-08-14 at 12 15 33](https://issues.joomla.org/uploads/1/340998dcf4e95f809611d935ffd0495f.png)

### System information (as much as possible)
Windows 10 Version 1703 64Bit
Version 60.0.3112.90
Joomla Version: 3.7.4 (fresh Joomla installation without third party extensions)
Resulution: 1920x1080
PHP Version: 7.0.19-1
Web Server Apache/2.4.25
Database MySQL

### Additional comments
I tested it on some other Browsers (Microsoft Edge, Mozilla Firefox, Google Chrome), this "Bug" only appears on Google Chrome.

**Comment by ghost** [comment] 2017-08-14 12:30
Can't confirm, "Position" and "Status" are shown as expected. 
### System information
3.8-dev
Multilanguage Site
macOS Sierra, 10.12.6
Chrome 60.0.3112.90, Firefox 55 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by Dennisshrt** [comment] 2017-08-14 12:38
I can confirm this issue occurs 4/5 times
System information
Windows 10 64bit
Chrome 60.0.3112.90
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17532">issues.joomla.org/tracker/joomla-cms/17532</a>.</sub>

**Comment by brianteeman** [comment] 2017-08-14 12:41
Could you post a screenshot please so others can see exactly what you are experiencing

**Comment by Dennisshrt** [comment] 2017-08-14 12:45
![screen shot 2017-08-14 at 12 44 51](https://issues.joomla.org/uploads/1/bcb9bc652daed30758af2cc508f7f21c.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17532">issues.joomla.org/tracker/joomla-cms/17532</a>.</sub>

**Comment by brianteeman** [comment] 2017-08-14 12:48
So that looks like a problem with the chosen.js script not firing correctly

**Comment by esedic** [comment] 2017-08-14 19:37
Can't confirm either.
Dropdowns displayed normally.
Tested on Joomla 3.7.4.

**Comment by ghost** [comment] 2017-08-15 04:34
@esedic on which Operating System you test?

**Comment by esedic** [comment] 2017-08-15 06:39
It's a Linux server.
Same goes for localhost on Windows 7.

**Comment by brianteeman** [comment] 2017-08-15 06:50
it sounds to me that either the chosen js is not present or there is a plugin on your site that is preventing it from loading

**Comment by brianteeman** [comment] 2017-08-15 06:51
Can you replicate the problem on localhost with a clean install of joomla with no extensions?

**Comment by widmann-it** [comment] 2017-08-15 18:01
I can not understand the problem

Tested on Joomla 3.8.0 - DEV, PHP 7.0.3, mysql 5.7.11, Win 10 or UwAmp
Tested by Firefox, Edge, Chrome

![grafik](https://user-images.githubusercontent.com/13391650/29328935-7fc3b066-81f4-11e7-99a8-7ed2cf4b0903.png)

Also under the 3.7.4 Stable the same result

![grafik](https://user-images.githubusercontent.com/13391650/29329152-2f146344-81f5-11e7-8897-ef25446a6699.png)

**Comment by brianteeman** [comment] 2017-09-27 23:16
I am closing this issue as something was preventing the chosen.js from loading. Either a faulty installation or some third party extension. There is no issue confirmed with the core

**Closed as completed by brianteeman** 2017-09-27 23:16 UTC
Labels: No Code Attached Yet
