### ISSUE TITLE
RandomImage functionality does not work within 3.8.8

### ISSUE THREAD

**Issue by keithgrimes** [joomla/joomla-cms#20589] opened 2018-05-27 19:56 UTC
### Steps to reproduce the issue
Create a new RandomImage using default settings. 
aka create a folder in images which contains some jpg files.
configure the module to display a random image from this folder. 
When rendering the page displays error

### Expected result
Images are displayed at random from the chosen directory on page refresh

### Actual result
Error: 0 - Using $this when not in object context

### System information (as much as possible)
Joomla 3.8.8

### Additional comments
Having looked at the code the default.php file has been modified between 3.8.7 and 3.8.8 as follows

<?php echo JHtml::_('image', $image->folder . '/' . $image->name, $image->name, array('width' => $image->width, 'height' => $image->height)); ?>

to 

<?php echo JHtml::_('image', $image->folder . '/' . $this->escape($image->name), $this->escape($image->name), array('width' => $image->width, 'height' => $image->height)); ?>

Reverting back to the old version appears to correct the issue. However, I am unclear as to the implications of doing this.

**Comment by Quy** [comment] 2018-05-27 20:16
Duplicate of #20541<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20589">issues.joomla.org/tracker/joomla-cms/20589</a>.</sub>

**Closed as completed by Quy** 2018-05-27 20:16 UTC
Labels: No Code Attached Yet
