### ISSUE TITLE
To have different names in admin contact menu

### ISSUE THREAD

**Issue by horus68** [joomla/joomla-cms#8200] opened 2015-10-29 13:25 UTC
I need to have different translation for admin contact menu component: the main name and the sub-name need to be different. Joomla uses the same string for both names. The string that should be used for this is not in use even if is present in the language string.

com_contact.sys.ini
https://github.com/joomla/joomla-cms/blob/master/administrator/language/en-GB/en-GB.com_contact.sys.ini

COM_CONTACT="Contacts"
COM_CONTACT_CONTACTS="Contacts"
(this one is not in use, only the first one - tested by changing values! )
![2015-10-29 13_19_27-000349-fotografias](https://cloud.githubusercontent.com/assets/3055443/10819493/4e331820-7e40-11e5-988e-2f9281b48479.png)

Please follow the way it works for com_newsfeeds.sys.ini
COM_NEWSFEEDS="News Feeds"
COM_NEWSFEEDS_FEEDS="Feeds"
![2015-10-29 13_19_44-000350-fotografias](https://cloud.githubusercontent.com/assets/3055443/10819502/5988fe6a-7e40-11e5-9098-dac02bb420c7.png)

**Comment by teccrow** [comment] 2015-10-29 13:46
I confirm the issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8200">issues.joomla.org/joomla-cms/8200</a>.</sub>

**Comment by infograf768** [comment] 2015-10-30 08:32
Took some time to find out...
The issue is in the database...
The string `com_contact_contacts` (in the sys.ini) should be the title of the menu

I modified the db
![screen shot 2015-10-30 at 09 23 31](https://cloud.githubusercontent.com/assets/869724/10841255/f7b81a42-7ee7-11e5-9c17-116e35ae0924.png)

and obtained
![screen shot 2015-10-30 at 09 24 42](https://cloud.githubusercontent.com/assets/869724/10841273/3a94a024-7ee8-11e5-9008-76a3f3e56de9.png)

Therefore we have to change joomla.sql
from
```
(8, 'menu', 'com_contact', 'Contacts', '', 'Contacts/Contacts', 'index.php?option=com_contact', 'component', 0, 7, 2, 8, 0, '0000-00-00 00:00:00', 0, 0, 'class:contact', 0, '', 12, 13, 0, '*', 1),
```
to
```
(8, 'menu', 'com_contact_contacts', 'Contacts', '', 'Contacts/Contacts', 'index.php?option=com_contact', 'component', 0, 7, 2, 8, 0, '0000-00-00 00:00:00', 0, 0, 'class:contact', 0, '', 12, 13, 0, '*', 1),

```
and update existing dbs for next release.

**Comment by infograf768** [comment] 2015-10-30 09:35
Patch is here:
https://github.com/joomla/joomla-cms/pull/8212

**Comment by zero-24** [comment] 2015-10-30 11:54
Closing as we have a Patch by @infograf768

**Closed by zero-24** 2015-10-30 11:54 UTC
Labels: No Code Attached Yet
