### ISSUE TITLE
Category meta description showing up also as article meta desc, instead of own article meta desc

### ISSUE THREAD

**Issue by MaghSamana** [joomla/joomla-cms#39664] opened 2023-01-18 18:00 UTC
Hello,

not sure if this is a bug or not, but here's it is.

I recently migrated a Joomla 3.10 site into 4.2 (test environment). I noticed a very weird situation with SEO. 
In Joomla 3.x category meta description showed up normally in the head, and articles under it showed up normally their own meta description in the head. 

This is no longer the case: now the category meta desc. appears as a meta desc. of all articles in it, ignoring their own meta desc.

I had noticed this was happening in Joomla 3.x. ONLY with the meta desc. of a menu item (of a category). Then all articles got the menu item's meta desc. But if the category itself had a meta desc. and the menu item meta desc. was empty, all worked well.

Since this is a SEO issue, and it seriously affects articles' own meta, can someone take a look?

### System information (as much as possible)
Joomla! 4.2.6 Stable
PHP 8.1.14 
(Server: Apache)

**Comment by carlitorweb** [comment] 2023-01-19 00:51
I cant reproduce the problem. Just set a category with a article inside and the metadescription of the article is the one who show up inside the article. Tested with teh default template Cassiopedia

**Comment by MaghSamana** [comment] 2023-01-23 17:03
Any updates on this?

It is a serious SEO problem. I literally had to cancel the migration to Joomla 4 because of this.

**Comment by joomdonation** [comment] 2023-02-20 04:25
@MaghSamana I could not re-procedure the issue, too, with a fresh Joomla 4.2 installation. I created a menu item of **Category Blog** menu item type as you described. But on article details page, It still use article meta description, not category category meta description as you said

Maybe you should try to re-procedure the issue with a fresh installation of Joomla ? If it does not happen with that fresh installation, maybe there is a plugin on your site causes this wrong behavior.

**Comment by joomdonation** [comment] 2023-03-05 07:52
Closing this issue because both of us tried but could not re-procedure the issue. @MaghSamana If you still think that this is a valid issue valid issue, please try to reproduce it with a fresh of Joomla 4 installation and tell us step by step how we can see the issue ourself. If it is possible to reproduce, we would be happy to look at it and get it sorted.

**Comment by smileysit** [comment] 2024-01-01 13:59
Ok I have migrated from J3 to J4 and I am faced with the same scenario, SEO is saying I have duplicate meta descriptions.
This is a bug,
Quoting "When the category does not have a menu item, then its articles' meta description shows up normally.

But when there is a menu item for a category (e.g. category blog), then the category's articles get the category's meta description and not their own."
- - - -
<meta charset="utf-8">
<meta name="rights" content=" Article has correct name ">
<meta name="author" content=" correct " >
<meta name="metatitle" content=" correct ">
<meta name="description" content="** pulled from the category** " />
<meta name="generator" content="Joomla! - Open Source Content Management">
- - - -<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39664">issues.joomla.org/tracker/joomla-cms/39664</a>.</sub>

**Comment by smileysit** [comment] 2024-01-01 23:26
Website #2, same as my comments above.
Joomla 3 to Joomla 4 update and have the same SEO issues.
The articles get the category meta description.

**Comment by smileysit** [comment] 2024-01-01 23:41
Website ##, looking at your showcase websites.
https://showcase.joomla.org/browse-sites/25089.html
meta name="description" content="Home of the World Heritage Port Arthur Historic Site, the Tasman Peninsula hosts an abundance of offerings for your holiday or short break."

the same metadata is pulled from the Category for all the articles under the Mega Menu.

What is the FIX?

**Comment by joomdonation** [comment] 2024-02-24 12:01
Tried again with a fresh Joomla 5 installation and could not confirm the issue. I would suggest you to setup a fresh installation of Joomla and try to see if you can see the issue yourself. If Yes, please tell us step by step what we need to do to see the error so that we can check and fix it.

If we cannot procedure the issue ourself, it's impossible for us to provide the fix.

**Comment by Quy** [comment] 2024-04-16 13:31
Closing due to no response with additional info to reproduce the issue.

**Closed as completed by Quy** 2024-04-16 13:31 UTC
Labels: No Code Attached Yet, Information Required, bug
