### ISSUE TITLE
[com_fields] Text field - filter Phone - dot before field value

### ISSUE THREAD

**Issue by proweb** [joomla/joomla-cms#18566] opened 2017-11-14 09:45 UTC
### Steps to reproduce the issue
Create field `type=text`, `filter=Telephone`
![image](https://user-images.githubusercontent.com/680073/32772780-fdf0078e-c937-11e7-9731-a6f47cbd0065.png)

Then go to article and add phone in that field
![image](https://user-images.githubusercontent.com/680073/32773034-e8c486b8-c938-11e7-8701-f1a41585f038.png)
Then Save it

### Expected result
Field value with my numbers

### Actual result
Field value has DOT before real field value
![image](https://user-images.githubusercontent.com/680073/32773174-53a67590-c939-11e7-941e-7daab927b300.png)

### System information (as much as possible)
=============
System Information
=============
php: Linux proweb 4.4.0-100-generic #123-Ubuntu SMP Thu Nov 2 10:16:13 UTC 2017 x86_64
dbversion: 5.7.20-0ubuntu0.16.04.1
dbcollation: utf8_general_ci
dbconnectioncollation: utf8mb4_general_ci
phpversion: 7.0.22-0ubuntu0.16.04.1
server: Apache/2.4.18 (Ubuntu)
sapi_name: apache2handler
version: Joomla! 3.8.2 Stable [ Amani ] 7-November-2017 15:00 GMT
platform: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36

=============
PHP Settings
=============
safe_mode: false
display_errors: true
short_open_tag: false
file_uploads: true
magic_quotes_gpc: false
register_globals: false
output_buffering: true
open_basedir: 
session.save_path: xxxxxx
session.auto_start: 0
disable_functions: pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wifcontinued,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,
xml: true
zlib: true
zip: true
mbstring: true
iconv: true
max_input_vars: 10000

**Comment by ghost** [comment] 2017-11-14 10:08
Issue confirmed.
### System information
3.8.3-dev
Multilanguage Site
macOS Sierra, 10.12.6
Firefox 56 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by brianteeman** [comment] 2017-11-14 20:38
The relevant code is here
https://github.com/joomla/joomla-cms/blob/54eb5d8cea29b064c2ad2122e15e71d478c60b01/libraries/cms/html/tel.php#L34

Reading that it looks like the expected behaviour but I really cant tell

**Comment by proweb** [comment] 2017-11-15 11:35
So as I see in code:
```
@param   integer  $number       The integers in a phone number with dot separated country code
	 *                                 ccc.nnnnnnn where ccc represents country code and nnn represents the local number.
```

How we should know about it? Where is documentation? In different countries phone nubmers write different. We for example don't use dots in phone number

So how I must to know in which format I need to write phone number if it's nowhere written... Only in code! Very "user-friendly"...

**Comment by brianteeman** [comment] 2017-11-15 12:30
Reading the code it looks like it is an official International Telephone specification. However I agree that it is not a format that would be used in the UK either. To be honest what I would do is just to exclude the filter. Its not needed and it doesnt really help

**Comment by brianteeman** [comment] 2018-04-06 12:36
I am going to close this. The filter is working as intended. Its just not very useful

**Comment by infograf768** [comment] 2018-04-06 13:11
It seems the code in `https://github.com/joomla/joomla-cms/blob/54eb5d8cea29b064c2ad2122e15e71d478c60b01/libraries/cms/html/tel.php#L34` is not applied in this case.

We have there
```
	public static function tel($number, $displayplan)
	{
		$number = explode('.', $number);
		$countrycode = $number[0];
		$number = $number[1];
		if ($displayplan === 'ITU-T' || $displayplan === 'International' || $displayplan === 'int' || $displayplan === 'missdn' || $displayplan == null)
		{
			$display[0] = '+';
			$display[1] = $countrycode;
			$display[2] = ' ';
			$display[3] = implode(str_split($number, 2), ' ');
		}
```
for the default format ITU-T

which should give, if entered as 
`33.4577729624`
the following result
`+33 4577729624`

As it is not the case (tested here: we get `33.4577729624`), I guess we do have an issue with that filter.

I suggest to reopen.

**Comment by fred-the-coder** [comment] 2020-07-19 05:29
I do agree with infograf768.
On top of that, why having a not useful filter??

**Comment by infograf768** [comment] 2020-07-19 10:09
In fact, issue may come from
https://github.com/joomla/joomla-cms/blob/staging/libraries/src/Form/Form.php#L1466-L1544

The result does not come from `public static function tel()` as stated above as I can't find where this method is used in core.

**Comment by infograf768** [comment] 2020-07-19 10:35
I'm reopening this as the filter is not only not working but gives wrong results (3.9.20 / staging)

**Comment by infograf768** [comment] 2020-07-19 15:08
Looks like, unless someone totally rewrites that code, that we should take off the Telephone filter from these files:
```
/plugins/fields/repeatable/params/repeatable.xml:63: 									value="tel">JLIB_FILTER_PARAMS_TEL</option>
/plugins/fields/text/params/text.xml:21: 				<option value="tel">JLIB_FILTER_PARAMS_TEL</option>
/plugins/fields/text/text.xml:40: 					<option value="tel">JLIB_FILTER_PARAMS_TEL</option>
/plugins/fields/textarea/params/textarea.xml:47: 				<option value="tel">JLIB_FILTER_PARAMS_TEL</option>
/plugins/fields/textarea/textarea.xml:68: 					<option value="tel">JLIB_FILTER_PARAMS_TEL</option>
```

**Comment by laoneo** [comment] 2020-07-19 15:48
Not sure why you tagged me, but if the filter is not correct. Then at least remove it in com_fields. Keep in mind about the upgrade of the existing filters, need to be unset in the existing fields.

**Comment by infograf768** [comment] 2020-07-19 16:03
@laoneo 
I tagged you because you introduced these filters in fields a long while ago #14403.
The filter is defined in JForm. I have seen nowhere in code the use of `filter="tel"`
Contact is using a simple text field.

No idea where I would unset the filter (after deleting the option in the plugins). Can you help?

**Comment by laoneo** [comment] 2020-07-19 16:40
Deleting the option would be enough, more difficult is the update of fields which have this filter set in the params on existing sites.

**Comment by infograf768** [comment] 2020-07-20 06:16
I doubt anybody has ever used that filter, taking into account that it is really broken, but would it make sense to add in an sql update some code that would just change `filter="tel"` by `filter="text"` in every occurrence of `fieldparams` in db fields table?

Here the export of such a field.
`(25, 3287, 'com_content.article', 0, 'Telephone field', 'telephone-field', 'Telephone field', '', 'text', '', '', 1, 0, 800, '2020-07-19 14:59:22', 0, '{\"hint\":\"\",\"class\":\"\",\"label_class\":\"\",\"show_on\":\"\",\"render_class\":\"\",\"showlabel\":\"1\",\"label_render_class\":\"\",\"display\":\"2\",\"layout\":\"\",\"display_readonly\":\"2\"}', '{\"filter\":\"tel\",\"maxlength\":\"\"}', '*', '2020-07-19 10:13:47', 800, '0000-00-00 00:00:00', 0, 1);`
 
By using
```
UPDATE `#__fields` SET `fieldparams` = REPLACE(`fieldparams`, '"filter":"tel"', '"filter":"text"');
```
we correct db.

What do you think?

**Comment by laoneo** [comment] 2020-07-20 06:54
Looks good for me. Perhaps you want to add in the update statement a where clause "type='text'".

**Comment by richard67** [comment] 2020-07-20 06:57
> By using
> 
> ```
> UPDATE `#__fields` SET `fieldparams` = REPLACE(`fieldparams`, '"filter":"tel"', '"filter":"text"');
> ```
> 
> we correct db.
> 
> What do you think?

@infograf768 The replacement should work and be safe, since both the search string and the replace string contain the complete name value pair, including the double quotes. We only had problems in past when this was not the case so that substrings were matching, too, where it was not desired.

But maybe the `context` column should be limited to certain values so that we cover only fields used for the core, i.e. add a
```
 WHERE `context` IN ('com_content.article', ...)
```
to the update statement?

**Comment by laoneo** [comment] 2020-07-20 07:03
Please do NOT add the context clause as it belongs to all fields, not only the ones from articles. But the filter is only applied to text fields, so you can limit it there.

**Comment by richard67** [comment] 2020-07-20 07:06
Ok, so a
```
WHERE `type` = 'text'
```
should be added.

**Comment by infograf768** [comment] 2020-07-20 07:07
In fact we also have for repeatable/textarea another format. therefore 
```
`WHERE `type` = 'text'`
```
 is not enough.
`{"fields":{"fields0":{"fieldname":"a form fields name","fieldtype":"textarea","fieldfilter":"tel"}}}`

**Comment by richard67** [comment] 2020-07-20 07:08
Sure, then its an IN list with a few types.

**Comment by infograf768** [comment] 2020-07-20 07:20
@richard67 
for sql update:

**3 types concerned**
text
textarea
repeatable

**2 formats of fieldparams**
filter="tel" => filter="text" 
fieldfilter="tel" => fieldfilter="text"

**Option to delete in 5 files**
```
/plugins/fields/repeatable/params/repeatable.xml:63: 									value="tel">JLIB_FILTER_PARAMS_TEL</option>
/plugins/fields/text/params/text.xml:21: 				<option value="tel">JLIB_FILTER_PARAMS_TEL</option>
/plugins/fields/text/text.xml:40: 					<option value="tel">JLIB_FILTER_PARAMS_TEL</option>
/plugins/fields/textarea/params/textarea.xml:47: 				<option value="tel">JLIB_FILTER_PARAMS_TEL</option>
/plugins/fields/textarea/textarea.xml:68: 					<option value="tel">JLIB_FILTER_PARAMS_TEL</option>

```

Can you do the patch? I'm not familiar with IN

**Comment by richard67** [comment] 2020-07-20 07:22
@infograf768 The 2 formats "filter" and "fieldfilter" can happen with all the 3 types?

**Comment by infograf768** [comment] 2020-07-20 07:28
Looks like `fieldfilter` is only for repeatable
```
/plugins/fields/repeatable/params/repeatable.xml:34: 								name="fieldfilter"
/plugins/fields/repeatable/repeatable.php:69: 			if (isset($formField->fieldfilter))
/plugins/fields/repeatable/repeatable.php:71: 				$child->addAttribute('filter', $formField->fieldfilter);
```

**Comment by richard67** [comment] 2020-07-20 07:33
Is `filter` then only for text and textarea?

**Comment by infograf768** [comment] 2020-07-20 07:34
It looks like indeed

**Comment by richard67** [comment] 2020-07-20 07:38
```
UPDATE `#__fields` SET `fieldparams` = REPLACE(`fieldparams`, '"filter":"tel"', '"filter":"text"') WHERE `type` IN ('text', 'textarea');
UPDATE `#__fields` SET `fieldparams` = REPLACE(`fieldparams`, '"fieldfilter":"tel"', '"fieldfilter":"text"') WHERE `type` = 'repeatable';
```
Does that look right? If yes, please do you do the PR, @infograf768 ... I have too little time now.

**Comment by infograf768** [comment] 2020-07-20 07:40
OK, will do.

**Comment by infograf768** [comment] 2020-07-20 08:18
Closing as we have patch https://github.com/joomla/joomla-cms/pull/30142

Needs sql update for postgresql and sqlazure

**Closed as completed by infograf768** 2020-07-20 08:18 UTC
Labels: No Code Attached Yet
