### ISSUE TITLE
Cassiopeia Style Copy: no CSS issue

### ISSUE THREAD

**Issue by dozentis** [joomla/joomla-cms#37246] opened 2022-03-11 06:51 UTC
### Steps to reproduce the issue
Go to Template Style Site
Open Cassiopeia  - Default
Save as copy 
Assign Style via Menu or just make it default style

### Actual result
No CSS loaded, just HTML on website

### System information (as much as possible)
Joomla 4.1.0 - PHP 8.0.10 Xampp

### Additional comments
But the alternative way works!!!

Go to Template Style Site
Check Cassiopeia  - Default and click "Duplicate"
Assign Style via Menu or just make it default style
CSS loaded, all good!

-> "Save as copy" Cassiopiea Style doesnt load css, but when just duplicated the style the css will be loaded

**Comment by brianteeman** [comment] 2022-03-11 07:18
Issue confirmed

**Comment by brianteeman** [comment] 2022-03-11 08:35
Found the bug. Should have a fix shortly.

**Comment by brianteeman** [comment] 2022-03-11 09:12
Sorry I cant see the fix. The problem is that the inheritable field is not being set.

**Comment by dgrammatiko** [comment] 2022-03-11 13:37
There's a PR: #37248 please test

**Comment by alikon** [comment] 2022-03-11 13:41
closing as there is a pr

**Closed as completed by alikon** 2022-03-11 13:41 UTC
Labels: No Code Attached Yet
