### ISSUE TITLE
menu item alias access level doesn't work.

### ISSUE THREAD

**Issue by ranggasito** [joomla/joomla-cms#24131] opened 2019-03-08 16:22 UTC
### Steps to reproduce the issue
create menu item alias with access level registered or above

### Expected result
the system should redirect to login page / restrict the access from public

### Actual result
public still can access the page.

### System information (as much as possible)
Joomla version 3.9.3
PHP 7.2.15 ubuntu
mysql 5.7.25-0ubuntu0.18.04.2

### Additional comments
in joomla 8 is fine, this happen after I update Joomla to version 3.9.3

**Comment by ReLater** [comment] 2019-03-08 18:09
What is the access level of the parent menu item?

**Comment by ranggasito** [comment] 2019-03-08 19:19
The access level of both parent and item is Registered. I changed the parent item menu type to menu heading and it works properly

**Comment by ggppdk** [comment] 2019-03-08 20:05
Regardless if you configured inside the (type: "menu item alias") menu item to have
a 301 redirection (you will see URL of the target menu item in the address bar)
or if you disabled the redirection (default setting) thus you will get re-routed to the target menu item

in both cases the access level of the the (type: "menu item alias") menu item
will only hide the menu item

if someone has a direct link to it,
then what happens depends on the access level target menu item and of the access levels of its parent menu items

> I changed the parent item menu type to menu heading and it works properly

i have not tested 
but it should not be related
i think you got this to work because the target menu item is under this heading menu item you have selected to be also parent of the menu-item-alias menu item

again i could be wrong
i have not done any extensive tests, just a rough look in the code and some (maybe) related PRs

**Comment by jwaisner** [comment] 2020-03-24 15:12
This was resolved by user. Closing as not a bug.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24131">issues.joomla.org/tracker/joomla-cms/24131</a>.</sub>

**Closed as completed by jwaisner** 2020-03-24 15:12 UTC
Labels: No Code Attached Yet
