### ISSUE TITLE
Frontend language not set correct when edit content

### ISSUE THREAD

**Issue by B3nito** [joomla/joomla-cms#22514] opened 2018-10-06 07:32 UTC
### Steps to reproduce the issue
On a multilanguage site in Persian (or other language) content click on edit article

### Expected result
Article edit is open in you set frontend language in user profile

### Actual result
Editor is persian language, you are not able to understand UI and cannot paste content from translator good.

### System information (as much as possible)
Joomla 3.8.12

**Comment by infograf768** [comment] 2018-10-06 08:36
This is confusing.
What are the languages used in this multilingual site?
Whatever the user default frontend language, what is the language displayed at the time the user edits this article?

**Comment by B3nito** [comment] 2018-10-06 08:38
it is always the language from the content and not the language from the administrator who wants to edit article.

**Comment by infograf768** [comment] 2018-10-06 08:45
When editing in frontend an article in multilang, the interface language will always be the one where the article displays. 

If you are in mydomain.com/fr/ and edit an article, the Interface is in French.
If you are in mydomain.com/en/ and edit an article, the Interface is in English.

A preferred frontend language for a user on a multilingual site is only used to be redirected to it when logging.
The behavior is totally different on a monolanguage site where multiple languages are installed and in that case indeed the UI language will depend on which one was chosen as preferred by the user in the profile.

Closing as not a bug

**Closed as completed by infograf768** 2018-10-06 08:45 UTC
Labels: No Code Attached Yet

**Comment by B3nito** [comment] 2018-10-06 08:54
If you edit article it is completely different from viewing a website. How to change a persian article in frontend when you don't speak persian, please?

**Comment by B3nito** [comment] 2018-10-06 09:05
Can you please reopen as it is a bug, because administration is not visit site.

**Comment by infograf768** [comment] 2018-10-06 09:27
You would have to do it in the administration.
At this time, it is not possible to change the UI language just to edit an article in frontend when this article is only displayed when another language is in use.
Is it possible to implement such a behavior? Not sure at all.

IT is NOT a bug and the title of this Issue is wrong.
It "could be " asking for a new feature, which is quite different.
Please create a new Issue asking for this new feature.

**Comment by B3nito** [comment] 2018-10-06 09:29
That does not make sense at all. As administrator I am not equal to visitor.
