### ISSUE TITLE
adaptive image for "images and links" settings for article [com_content]

### ISSUE THREAD

**Issue by sanek4life** [joomla/joomla-cms#10051] opened 2016-04-22 18:19 UTC
#### Steps to reproduce the issue

![adapt2](https://cloud.githubusercontent.com/assets/3662519/14750864/af6407e8-08cf-11e6-9dc1-c7d3fb1853b0.png)

#### Expected result

adaptive image - resizing an image, depending on the width of the screen

#### Actual result

![adaptive need](https://cloud.githubusercontent.com/assets/3662519/14750861/a88d42f4-08cf-11e6-92fe-9f44d32d7497.png)

#### System information (as much as possible)

Joomla 3.5.1

#### Additional comments

Please, add this code for images:

`style="max-width: 100%; height: auto;"`

**Comment by sanek4life** [comment] 2016-04-22 18:24
code in site like this:

`<img alt="Article Title" src="/images/stories/image-article.jpg" style="max-width: 100%; height: auto;" title="Article Title">`

**Comment by andrepereiradasilva** [comment] 2016-04-22 20:18
add a css class instead

**Comment by brianteeman** [comment] 2016-04-22 22:12
Pull Requests are welcome<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10051">issues.joomla.org/joomla-cms/10051</a>.</sub>

**Comment by SharkyKZ** [comment] 2016-04-22 22:19
Unless I'm missing something, Protostar already has responsive images by default https://github.com/joomla/joomla-cms/blob/staging/templates/protostar/css/template.css#L50.

**Comment by SharkyKZ** [comment] 2016-04-22 22:25
The strangest thing is that you're having this issue on Firefox. Some browsers required `width:100%` to be responsive, but FF always worked properly with `max-width:100%`.
I can reproduce your issue but only in IE11. Works fine on Firefox, Chrome and Edge. The issue appears only when parent element is floating (i.e. image float parameter is set).

**Comment by SharkyKZ** [comment] 2016-04-22 22:43
On IE at least this can be fixed by applying float (`.pull-*`) classes to the image itself rather than to the parent div (`.item-image`).

**Comment by sanek4life** [comment] 2016-04-23 09:22
@SharkyKZ Firefox 45.0.2, Win 10.

Protostar no using responsive images by default.

![testtttt](https://cloud.githubusercontent.com/assets/3662519/14760479/e576ed04-094d-11e6-96aa-c3b60897c118.png)

you need add this code to image for right view:

`style="max-width: 100%; height: auto;`

**Comment by SharkyKZ** [comment] 2016-04-23 10:30
How can it not be using if the code is in template.css?
```
img {
	max-width: 100%;
	width: auto \9;
	height: auto;
	vertical-align: middle;
	border: 0;
	-ms-interpolation-mode: bicubic;
}
```
This looks like a browser bug. I can reproduce this on IE11 but not in FF47.

**Comment by SharkyKZ** [comment] 2016-04-23 10:33
I can reproduce it in FF45. It's fixed in FF47 (or 46). But IE11 issue still remains. Can be solved by applying float classes directly to images.

**Comment by sanek4life** [comment] 2016-04-23 11:25
@SharkyKZ if it fixed, i'm say - OK.

i need option for set  "max-width"

for example:

`<img alt="Article Title" src="/images/stories/image-article.jpg" style="max-width: 300px; height: auto;" title="Article Title">`

max-width: 100%
or
max-width: 200px or 100px or 500px, etc.

**Comment by sanek4life** [comment] 2016-04-26 17:54
firefox 46.0 fix this problem!

**Comment by brianteeman** [comment] 2016-05-08 08:46
Closing - thanks for looking at this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10051">issues.joomla.org/joomla-cms/10051</a>.</sub>

**Closed** 2016-05-08 08:46 UTC
Labels: No Code Attached Yet
