### ISSUE TITLE
Fatal error on front module editing

### ISSUE THREAD

**Issue by micker** [joomla/joomla-cms#6124] opened 2015-02-19 09:02 UTC
After apply this patch #6113
when we try to edit a module in front
Not Found
( ! ) Warning: Creating default object from empty value in ....\components\com_config\config.php on line 25
Fatal error: Call to undefined method stdClass::execute() in ....\components\com_config\config.php on line 28

**Comment by Bakual** [comment] 2015-02-19 09:50
I finally could reproduce it. However it's most likely caused by the patchtester.
The patch itself works fine when I directly apply it using Git. It doesn't work when I apply it using the patchtester. In fact the controllers only contain `Not Found` instead of any PHP code.

My guess is that this is related to the fact that the PR already is merged. The patchtester seems to have issues applying the patch then. Does that make sense @mbabker ?

Closing this issue as it will not be an issue in the actual release.

**Closed by Bakual** 2015-02-19 09:51 UTC
Labels: No Code Attached Yet

**Comment by micker** [comment] 2015-02-19 09:58
ok how to test it by using git ?

**Comment by infograf768** [comment] 2015-02-19 09:59
just install https://github.com/joomla/joomla-cms/archive/staging.zip as the patch is in

**Comment by micker** [comment] 2015-02-19 10:02
like an update ?

**Comment by Bakual** [comment] 2015-02-19 10:09
I would as a new installation, an update may work as well.
Or you just make the changes manually. It's only two lines that changed.

**Comment by micker** [comment] 2015-02-19 11:01
you are my sunshine !!! all is good now
thanks
