### ISSUE TITLE
[staging 3.7.4] 500 JModel: :getName() : Can't get or parse class name.

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#17163] opened 2017-07-18 10:15 UTC
### Steps to reproduce the issue
Create an admin menu.
Create its menu module.
Then delete the admin menu.

=> 500 JModel: :getName() : Can't get or parse class name. 

@izharaazmi

**Comment by infograf768** [comment] 2017-07-18 10:42
This happens when "Check Menu" is enabled.

**Comment by infograf768** [comment] 2017-07-18 10:44
Also, it looks like it has to do with the module having the same name as the admin menu.

**Comment by izharaazmi** [comment] 2017-07-21 06:08
Could not reproduce the issue. The menu module linked is also deleted when
we delete the admin menu. The code is same for site and admin menu delete
function at JTableMenuType::delete();

Please let me know if you still find the issue in latest staging.

**Comment by brianteeman** [comment] 2017-08-20 10:14
@infograf768 can you still replicate this? If not then please close it

**Comment by ghost** [comment] 2017-09-17 11:10
@infograf768 is this a valid Issue?

**Comment by brianteeman** [comment] 2017-10-05 13:22
I am closing this due to a lack of response - it can always be reopened

**Closed as completed by brianteeman** 2017-10-05 13:22 UTC
Labels: No Code Attached Yet
