### ISSUE TITLE
[4b6] UX on Global Configuration Menu, hides items with no visible indication

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#31928] opened 2021-01-08 23:59 UTC
### Steps to reproduce the issue

On a "normal sized" screen, when you visit Joomla Global Configuration, the sub menu on the left "looks" to be rendering at the height of the viewport only. 

This truncates the menu with **NO INDICATION that there are more menu items.** 

If you did not know Joomla, or did not look hard, you would miss that the lower menu items are not visible and cut off.

When you scroll the page, the size of the left menu doesnt change, so the items remain in a small block, with the overflow menu items hidden. 

You can hover and scroll (on a Mac) and then you get a scroll bar indication that there are "more" to look at below the virtual fold of the outlying block.

Easier to explain with a video:

https://user-images.githubusercontent.com/400092/104076217-52ac2d00-520d-11eb-96d3-fff945dca836.mp4

### Expected result

All menu items should be visible at all times
OR 
If you need to hide some, make some way to show they are hidden and can be scrolled to

### Actual result

Described above. 

### System information (as much as possible)

Safari on macOS

### Additional comments

The full menu is this: 

<img width="325" alt="Screenshot 2021-01-09 at 00 00 09" src="https://user-images.githubusercontent.com/400092/104076317-ac145c00-520d-11eb-8c19-6df923b3ce60.png">

**Comment by infograf768** [comment] 2021-01-09 07:19
Can't reproduce here Mac 10.12.6 (16G2136) Safari Version 12.1.2 (12607.3.10)
I always have a scroll bar.

**Comment by brianteeman** [comment] 2021-01-09 10:45
Not a bug. OSx insists on defaulting to not showing scrollbars until hover which is what your video shows.

@infograf768 has probably changed his system preferences
https://www.webnots.com/how-to-customize-scroll-bar-in-mac/

**Comment by PhilETaylor** [comment] 2021-01-09 11:36
Just because you say somethings not a bug doesn't mean it's not a bug

The bug here is the terrible user experience where content is hidden - not the lack of scroll bars

The lack of scroll bars by default just emphasises the problem greater making it a bigger bug

Content is hidden for no reason and a new person to joomla would have no idea it's there

Scrolling within a page element is new to most people, I can't think of any other app or website a "normal" person would come across that 

There is no reason for this block to autosize to the height of the view port is there? It could be just left open at full height to display the content

It is hiding for the sake of hiding

**Comment by PhilETaylor** [comment] 2021-01-09 11:38
It further makes no sense that, if you are on a tiny view port, and you scroll the main page, that the menu continues to be tiny and doesn't expand, retaining its tiny size even though there is now room for it to expand as the main page has scrolled, sometimes to the point that the small truncated menu is now off screen completely

**Comment by PhilETaylor** [comment] 2021-01-09 11:40
> Can't reproduce here Mac 10.12.6 (16G2136) Safari Version 12.1.2 (12607.3.10)
> 
> I always have a scroll bar.

If you have a scroll bar then you have replicated the bug. The bug is the user experience, not the absence of scroll bars.

**Comment by PhilETaylor** [comment] 2021-01-09 11:50
Furthermore, if you load the page when your browser is a small window, and then resize your browser manually to full screen (or just a bigger height) the menu area remains hidden and it's block does not auto expand to fill the new current viewport height, so you are left with a tiny amount of the menu visible on a huge screen.

**Comment by HLeithner** [comment] 2021-01-09 11:51
I tried to make it 100% high which seems to be not possible, at least I was not able to do this with css (keep the scrollbars and expand the view to the viewport), if someone can fix it would make the ui better. Which seems to be easily possible is to remove max-height: 75vw: and overflow hidden. This expands the menu to the complete height (of the menu) and creates a scrollbar on the body element.

**Comment by PhilETaylor** [comment] 2021-01-09 12:04
Also this menu is dynamic in the number of items and installed extensions can be listed in the menu if they have options.

If you were in com_zzz and clicked options then this page would load but you would never see that the ZZZzzz menu item was selected as it would be out of the viewable area. 

The selected menu item is not automatically scrolled into view and remains hidden.

**Comment by Quy** [comment] 2021-01-09 12:58
Revert PR #31092?

**Comment by infograf768** [comment] 2021-01-09 17:31
> @infograf768 has probably changed his system preferences
> https://www.webnots.com/how-to-customize-scroll-bar-in-mac/

Nope.

**Comment by infograf768** [comment] 2021-01-09 17:34
@PhilETaylor 
> If you have a scroll bar then you have replicated the bug. The bug is the user experience, not the absence of scroll bars.

Understand now what you mean.

**Comment by regularlabs** [comment] 2021-04-11 20:40
PR to fix this (I think): #33108

**Comment by richard67** [comment] 2021-04-11 20:40
@regularlabs ~~How can this be with a PR which has been merged before this one here was created?~~ sorry was looking at the wrong one.

**Comment by regularlabs** [comment] 2021-04-11 20:42
~~33108 has not been merged. I just made it!~~
Ok

**Comment by richard67** [comment] 2021-04-11 20:42
@regularlabs sorry was looking at the wrong one.

**Comment by regularlabs** [comment] 2021-04-11 20:43
😉

**Comment by richard67** [comment] 2021-04-11 20:43
Clsoing as having a pull request. Please test #33108 . Thanks in advance.

**Closed as completed by richard67** 2021-04-11 20:43 UTC
Labels: No Code Attached Yet, Backend Template
