### ISSUE TITLE
PHP Warning: Use of undefined constant JPATH_COMPONENT

### ISSUE THREAD

**Issue by brian-j** [joomla/joomla-cms#28993] opened 2020-05-08 13:05 UTC
### Steps to reproduce the issue

Cronjob triggers Smart Search plugin to index the content:
php /home/[...........]/public_html/otherdomain.com/cli/finder_indexer.php

Note that this is an add-on domain (since my provider allows me to host several domains - hence the path includes 'otherdomain.com', and of course the relevant cli directory is under that level).

### Expected result

All batches processed without any errors

### Actual result

Starting Indexer
Setting up Smart Search plugins
Setup 115 items in 0.34 seconds.
JLIB_APPLICATION_ERROR_INVALID_CONTROLLER

Warning: Use of undefined constant JPATH_COMPONENT - assumed 'JPATH_COMPONENT' (this will throw an Error in a future version of PHP) in /home/...../public_html/otherdomain.com/libraries/src/MVC/Controller/BaseController.php on line 232

### System information (as much as possible)

Joomla 3.9.18
PHP 7.2.29

### Additional comments

Note that this is an add-on domain (since my provider allows me to host several domains - hence the path includes 'otherdomain.com', and of course the relevant cli directory is under that level).

This happens either as a cron job, or directly by ssh into the server.

I tried this suggestion from #24607:
Why not adding an additional
define('JPATH_COMPONENT', JPATH_COMPONENT_ADMINISTRATOR);
inside cli script.

That gave me the following error:
Starting Indexer
Setting up Smart Search plugins
Setup 115 items in 0.242 seconds.
JLIB_APPLICATION_ERROR_INVALID_CONTROLLER_CLASS
There was no WARNING: output.

**Comment by ReLater** [comment] 2020-05-08 21:22
See related/same issue https://github.com/joomla/joomla-cms/issues/24607

**Comment by brian-j** [comment] 2020-05-09 14:36
One further comment - the articles being indexed DO have custom fields applied to them, which was why I tried out 24607.

**Comment by SharkyKZ** [comment] 2020-05-12 07:05
I can't reproduce this issue. Do you have any extensions installed?

**Comment by Hackwar** [comment] 2020-06-06 19:09
JPATH_COMPONENT normally points to the current component of the request. Since you are calling a CLI script, there isn't really a component that is being loaded. It seems like you have a third party extension that is not set up to run in a CLI environment. I don't think this is a core Joomla issue.

**Comment by Quy** [comment] 2020-06-07 15:40
Closing as non-core issue.

**Closed as completed by Quy** 2020-06-07 15:40 UTC
Labels: No Code Attached Yet
