### ISSUE TITLE
Joomla 4 - Admin Cpanel - Module/Bootstrap size to 12 or 6 or 4 doesn't work like Joomla 3

### ISSUE THREAD

**Issue by fuscage** [joomla/joomla-cms#43522] opened 2024-05-24 08:59 UTC
### Steps to reproduce the issue
In Joomla 4.4.4, go to the panel administrator, modify all the "bootstrap size" modules (in advanced tab) to have these positions :

[               module size 12              ] => 1 full column
[    module size 6   ][     module size 6   ] => 2 full columns
[    module size 6   ][     module size 6   ] => 2 full columns
[module size 4][module size 4][module size 4] => 3 full columns

### Expected result

[               module size 12              ] => 1 full column
[    module size 6   ][     module size 6   ] => 2 full columns
[    module size 6   ][     module size 6   ] => 2 full columns
[module size 4][module size 4][module size 4] => 3 full columns

### Actual result

[    modal size 12   ][    module size 12   ]  => 2 full columns
[module size 6] [empty space]   [module size 6] [empty space]     => 2 columns (with empty spaces)
[module size 6] [empty space]   [module size 6] [empty space]       => 2 columns (with empty spaces)
[md4]  [empty space][empty space] [md4]  [empty space][empty space]                  => 2 columns (with empty spaces)
[md4]  [empty space][empty space]                           => 2 columns (with empty spaces)

### System information (as much as possible)
joomla 4.4.4

### Additional comments
in joomla 3, I have these positions of modules (in admin cpanel) : 

[               module size 12              ]
[    module size 6   ][     module size 6   ]
[    module size 6   ][     module size 6   ]
[module size 4][module size 4][module size 4]

but in joomla 4.4.4,  I have these positions of modules (with empty spaces) :-(

[    modal size 12   ][    module size 12   ]
[module size 6] [empty space] [module size 6] [empty space]
[module size 6] [empty space] [module size 6] [empty space]
[md4] [empty space] [empty space] [md4] [empty space] [empty space]
[md4] [empty space] [empty space]

Thank you in advance for your assistance

**Comment by brianteeman** [comment] 2024-08-01 12:54
Unfortunately this is as a result of the atum admin template using a masonry style layout for this page

**Comment by coolcat-creations** [comment] 2024-10-08 15:42
Duplicate of #25952

**Comment by chmst** [comment] 2024-10-09 08:23
cosing as duplicate

**Closed as completed by chmst** 2024-10-09 08:23 UTC
Labels: No Code Attached Yet, Backend Template
