### ISSUE TITLE
J4.4: Action log super slow when you have lots of users and actions

### ISSUE THREAD

**Issue by c-schmitz** [joomla/joomla-cms#43406] opened 2024-04-30 10:14 UTC
### Steps to reproduce the issue
We have about 2 million action log entries and  roughly 400k users.
When trying to view the action log then the every page/action in the action log viewer takes >20 seconds to load.

### Expected result
As there are only 20 entries visible in the action log grid I would expect it to be quick to show.

### Actual result
Take 20-30 secons to show the default screen

### System information (as much as possible)
I noticed whenever I try to do any action in the action log viewer the following query is executed:

SELECT `u`.`id` AS `value`,`u`.`username` AS `text`
FROM `jos_users` AS `u`
INNER JOIN `jos_action_logs` AS `c` ON `c`.`user_id` = `u`.`id`
GROUP BY `u`.`id`,`u`.`username`
ORDER BY `u`.`username`

Not sure why this generalized query is run at all.

### Additional comments
Query seems to originate from LogcreatorField->getOptions()
I think that is an extremly costly/inefficient query and it is only used to populate the user field in the filter -  instead that field should be a plain text search field.

**Comment by Hackwar** [comment] 2024-11-28 11:09
The problem is the filter at the top, which loads all users in one gigantic select list.

**Comment by brianteeman** [comment] 2024-11-28 11:31
Instead of it being a LogcreatorField it should be a type of user
Then you can still filter on a specific user without having to load all the users everytime

**Comment by brianteeman** [comment] 2024-11-28 11:43
Please test #44550

**Comment by c-schmitz** [comment] 2024-11-28 11:51
I applied the change in Joomla 4 and it resolved the problem and worked as intended.

**Comment by alikon** [comment] 2024-11-28 11:54
closing as we have a pr https://github.com/joomla/joomla-cms/pull/44550

**Closed as completed by alikon** 2024-11-28 11:54 UTC
Labels: No Code Attached Yet, bug

**Comment by brianteeman** [comment] 2024-11-28 12:03
@c-schmitz Please go to the issue tracker here https://issues.joomla.org/tracker/joomla-cms/44550 and mark your test result by using the blue "Test this" button at the top left corner, selecting your test result and finally submit, so that your test is properly counted. Just a comment here is not enough. Thanks in advance.
