### ISSUE TITLE
Breadcrumb Issue

### ISSUE THREAD

**Issue by Willroz** [joomla/joomla-cms#5806] opened 2015-01-18 01:32 UTC
I was not sure if this falls under the category of 'bug' or 'feature request'. If this is in the wrong place, please direct me to the correct one.

I'm building a website that has a moderately complex menu. All but one of the items in the main nav-bar creates a dropdown. One of the dropdowns has three columns, and each column has a heading. Please see the attached image.

The other screenshot is of the breadcrumb module. As you can see in the image, there is a redundant occurrence of 'About FARA'. I know that this is because the menu structure is what the breadcrumbs module uses to work. 

What I don't know is how to make the redundant one disappear. I have tried using the 'Text Separator', 'Menu Heading', and 'External Links' menu item types, but they all still create the breadcrumb item. I would think that an 'External URL' doesn't make sense to have in the breadcrumb module anyway. Does it?

So, is this a bug or a feature request? Or am I just being thick, and am overlooking something obvious to change this behavior?

#### Steps to reproduce the issue
Create a menu item and try and not have it show in the breadcrumb module.

#### Expected result
No item in breadcrumb

#### Actual result
Item in breadcrumb

#### System information (as much as possible)
See attached screenshot for sys-info. Site is also using T3 framework with the stock T3-BS3 template.

#### Additional comments
![menu-items](https://www.dropbox.com/s/0aw86pewdup5dmo/fara-menu.png?dl=0 "Menu")
![breadcrumbs](https://www.dropbox.com/s/b0jmywqyjisdo05/fara-breadcrumbs.PNG?dl=0 "breadcrumbs")
![sys-info](https://www.dropbox.com/s/8qi8vo7byoyvsai/fara-sys.PNG?dl=0 "sys-info")

For some reason, this doesn't like my images on DropBox, so here's the links:
https://www.dropbox.com/s/8qi8vo7byoyvsai/fara-sys.PNG?dl=0
https://www.dropbox.com/s/0aw86pewdup5dmo/fara-menu.png?dl=0
https://www.dropbox.com/s/b0jmywqyjisdo05/fara-breadcrumbs.PNG?dl=0

**Comment by zero-24** [comment] 2015-01-18 01:43
@Willroz your images looks broken. Please make sure you change your comment on http://issues.joomla.org/tracker/joomla-cms/5806/edit you can upload there via this view too<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5806">issues.joomla.org/joomla-cms/5806</a>.</sub>

**Comment by Willroz** [comment] 2015-01-18 01:47
Thanks, here's another attempt
![screen shot 2015-01-17 at 19 47 14](http://issues.joomla.org/uploads/1/2ab67a1d9e1cdd17dee0d1f2ee93e883.png)![screen shot 2015-01-17 at 19 47 14](http://issues.joomla.org/uploads/1/3ff5b401fc1fabca9074231d0cd3e94f.png)![screen shot 2015-01-17 at 19 47 14](http://issues.joomla.org/uploads/1/ccd3c2ed87de1e0e0d4e997bba0876b3.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5806">issues.joomla.org/joomla-cms/5806</a>.</sub>

**Comment by infograf768** [comment] 2015-01-18 10:47
Unrelated to the issue described but important: Your database collation is wrong. It should be utf8. Please correct with a script like:
http://www.phoca.cz/download/category/17-phoca-changing-collation-tool

**Comment by richard67** [comment] 2015-01-18 12:18
@Willroz Question: The "dropdowns" you get when selecting an item in the "nav bar", do they belong to the same one menu module used for nav bar and all drop downs?

I am almost sure there is a workaround for what you want using one menu without this duplicate "About FARA" by having separate menu modules for the nav bar and the pulldowns.

In general I do not really understand why you want to have this duplicate "About FARA" in red underlined letters as shown in your screenshot when you have the same link in the nav bar. It's useless from my point of view.

Better make some CSS changes for better highlighting the active top menu item in the nav bar if the bad visibility of which one is active in the nav bar was the reason for your requirement. 

You could let this duplicate information also be the title of separate menu modules for your pull-downs displaying the corresponding levels of your menu if you rerally need this layout as shown above.

I think there are ways to implement what you need with the current Joomla!, and if you provide more information about your menu structure and the menu modules you use in the support forum, I think you will quickly get help on how to to do it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5806">issues.joomla.org/joomla-cms/5806</a>.</sub>

**Comment by Willroz** [comment] 2015-01-18 14:45
Thank you for pointing that out. It seems that it was only the tables that were installed with the JCK editor that had the incorrect collation. There were only 7 or 8, the rest were correct. Odd that it appeared that way in the sys-info. 

 

I corrected it with pHpMyAdmin.

 

Thanks again,

Will

**Comment by Willroz** [comment] 2015-01-18 15:41
Hi Richard,

 

Thanks for your reply. Yes, the dropdowns all stem from a single menu. The site is set-up using T3 and the menu is set as the Mega Menu in the T3 framework parameters. All of the columnar formatting is set-up there as well.

 

To answer the second question, I don’t really want it set-up that way. Unfortunately, the organization that pays the bills does. The redundant (and unnecessary)items are there to create the column headers. Not much that I can do to change that. I’m still not done with the CSS changes yet, so please consider this site as a work-in-progress. The visibility of the active item has nothing to do with the breadcrumb issue I cited originally.

 

Aside from that, one of the other reasons for this particular set-up is for the menu to work efficiently when the viewport is small. Having a dropdown, the user must tap on the ‘About’ in the main menu to access the menu items below it. If it is connected to an article (or blog layout, etc.), the user is redirected to that page instead of the dropdown menu items appearing. This becomes somewhat cumbersome and/or frustrating from a user’s perspective. When it is set-up as a text separator or menu header, the dropdown simply opens up. 

 

I’ll agree that the desired layout can probably be achieved by using modules for the individual dropdown columns. I’ll have to look into that as a possible solution. Unfortunately, I think that by choosing that route, I would have to add ten new modules and reorganize the menu structure. I’m not sure if that will make it easy to administer to when the client takes over the site.

 

I’m not sure how this will affect the breadcrumbs either.

 

Thanks,

Will

**Comment by brianteeman** [comment] 2015-01-18 19:21
So is this an actual issue with Joomla or is it a support request that would be better handled on the forum<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5806">issues.joomla.org/joomla-cms/5806</a>.</sub>

**Comment by Willroz** [comment] 2015-01-19 14:26
HI Brian,

 

As I said in my initial comment, I’m not really sure. Any thoughts you have about it are certainly appreciated.

 

Thanks,

Will

**Comment by bradcypert** [comment] 2015-01-20 21:31
Alternatively, since I wouldn't consider this to be an issue and I actually think that's reasonable behavior, check the class on the menu head and add a style like so:

    .your-menu-class-name-here {
        display: none;
    }

That should take care of the name display, obviously replacing the "your-menu-class-name-here" with the actual class name for your template.

**Comment by brianteeman** [comment] 2015-01-20 22:28
I am closing this here - joomla appears to be working as intended<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5806">issues.joomla.org/joomla-cms/5806</a>.</sub>

**Closed** 2015-01-20 22:28 UTC
Labels: No Code Attached Yet
