### ISSUE TITLE
Isis template has probably wrong overrides of com_media

### ISSUE THREAD

**Issue by dziudek** [joomla/joomla-cms#9472] opened 2016-03-18 18:24 UTC
#### Steps to reproduce the issue

I am using in my module the following code to show media selection: 

```php
$form_image .= '<a class="btn gk-modal modal-media" title="'.JText::_('JSELECT').'" href="index.php?option=com_media&amp;view=images&amp;tmpl=component&amp;asset=com_modules&amp;author=&amp;fieldid=jform_params_img&amp;folder=" rel="{handler: \'iframe\', size: {x: 800, y: 500}}">'.JText::_('JSELECT').'</a>';
```

#### Expected result

In Joomla! 3.4.8 the mentioned code displayed the media selection popup and after selecting image and clicking the "Insert" button, text field connected with the popup has been filled.

#### Actual result

Currently the popup is not working - it appears, but clicking the "Insert" button not work. After removing override: **html/com_media/images/default.php** it works again, so the override is somewhat wrong.

#### System information (as much as possible)

Not neccessary - it is a JS code issue.

#### Additional comments

It will affect all extensions which uses this kind of call for the media popup.

Unfortunately original view causes issues in example with other media selectors like logo selector in the protostar template settings - the error with undefined jInsertFieldValue call is raised.

**Comment by brianteeman** [comment] 2016-03-18 18:26
Closing as a duplicate of #9466 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9472">issues.joomla.org/joomla-cms/9472</a>.</sub>

**Closed** 2016-03-18 18:26 UTC
