### ISSUE TITLE
Wrong tag order in the article filters

### ISSUE THREAD

**Issue by impressionestudio** [joomla/joomla-cms#40068] opened 2023-03-10 12:37 UTC
### Steps to reproduce the issue
You need to have created many tags in a random order (not alphabetical) with groups and subgroups (3 levels) in order to see the problem easily. Then go to the articles, open filters and click the tag list.

### Expected result
The list of tags in the filter section of articles should be displayed alphabetically, but should keep groups and subgroups together, otherwise the feature for parent tags is not useful. Now there is no way to tell which parent tags the sub-tags belong to.
Furthermore the unpublished tags should not be visible here.

### Actual result
Now the parent and child tags all appear mixed together.

### System information (as much as possible)
4.2.9-rc1

### Additional comments
Please see the image to understand better.
![Wrong tag order in the article filters](https://demo.impression-estudio.gr/_issue-tracker/tag-order-in-the-article-filters.png "")

**Comment by chmst** [comment] 2023-03-13 20:11
> Furthermore the unpublished tags should not be visible here. 

I think, unpublished tags should be visible https://github.com/joomla/joomla-cms/issues/40069#issuecomment-1466883693

**Comment by N6REJ** [comment] 2023-03-19 06:41
closing as duplicate of #40069

**Comment by brianteeman** [comment] 2023-03-19 06:44
Not a duplicate

**Comment by richard67** [comment] 2023-03-19 19:05
Clearly not a duplicate because the issue happens at 2 different places. But it is not very helpful to use the same title and almost the same description, so a quick reader could think indeed it is a duplicate. Anyway thanks for reporting the issues.

**Comment by brianteeman** [comment] 2023-09-01 14:53
The tags in the filter dropdown are displayed in the order that can be changed in the tags component. 

The query that builds the list is below . It is not possible to break the grouping. 
```
SELECT `a`.`id`,`a`.`title`,`a`.`level`,`a`.`parent_id`
FROM `e11lk_tags` AS `a`
WHERE `a`.`parent_id` > 0 AND `a`.`published` IN (1)
ORDER BY `a`.`lft`
```

In other words I cannot replicate the reported problem so am closing this here. Perhaps it was solved elsewhere

**Closed as completed by brianteeman** 2023-09-01 14:53 UTC
Labels: No Code Attached Yet, bug
