### ISSUE TITLE
Linked text does not appear in bold inside the editor

### ISSUE THREAD

**Issue by orschiro** [joomla/joomla-cms#42833] opened 2024-02-19 09:45 UTC
Hello,

Can someone reproduce this issue that bold text does not appear bold inside the editor?

It does appear bold on the actual page, just not inside the text editor.

It seems to be caused by the Joomla css for that editor. If the text has a link, the text will not become bold.

https://joomla.xxx/media/system/css/editor.min.css

Thanks!

![Screenshot](https://i.imgur.com/3pd4Bpn.png "Screenshot")

**Comment by brianteeman** [comment] 2024-02-19 13:00
Can not confirm

![image](https://github.com/joomla/joomla-cms/assets/1296369/58df4d32-04e4-45c6-9203-945096c56b2e)

**Comment by orschiro** [comment] 2024-02-19 14:48
I was able to reproduce it consistently. 

See this video: https://drive.google.com/file/d/1uohUTK_uFKCHwIDZcbtCEwaUBAHYRhMu/view?usp=drivesdk

It only happens if I select and want to highlight the entire word.

A selection of words works though.

**Comment by brianteeman** [comment] 2024-02-19 14:51
I can see from that screenshot and video that you are not using the tinymce editor that is shipped with Joomla.

**Comment by orschiro** [comment] 2024-02-19 20:29
You're right, I am sorry. I used TinyMCE of Yootheme for that matter. 

But the same applies to core Joomla. 

Can you try the following:

First enter a text and a link. Then mark all text as "Paragraph". After that mark all text as "Bold". But the link part does not get bold.

**Comment by Quy** [comment] 2024-02-19 20:51
I cannot reproduce. Please click `Toggle Editor` to see the generated HTML.

**Comment by brianteeman** [comment] 2024-02-19 21:17
still can not replicate. Sounds like the yootheme implementation of tinymce is broken

**Comment by Quy** [comment] 2024-02-20 18:06
Closing as non-reproducible in core and most likely with Yootheme's implementation.

**Closed as completed by Quy** 2024-02-20 18:06 UTC
Labels: No Code Attached Yet

**Comment by orschiro** [comment] 2024-02-20 18:47
Can you please try the following?

The same happens inside core Joomla. 

See this video: https://drive.google.com/file/d/1lbi92tpxERAi1rEKYDMJ7KiI_6lWgmqD/view?usp=drivesdk

**Comment by brianteeman** [comment] 2024-02-20 18:52
Still not reproducable

![links](https://github.com/joomla/joomla-cms/assets/1296369/58bced6f-992a-4318-8a2d-43b8a55337c6)

**Comment by Quy** [comment] 2024-02-21 16:50
Please use browser's inspector to see if the bold styling has been removed via css on the backend.

**Comment by orschiro** [comment] 2024-02-21 19:30
I am not sure how to do this. 

Like this?

<img width="955" alt="image" src="https://github.com/joomla/joomla-cms/assets/170947/c31d4499-d18f-4b9e-bed6-69f207c3053f">

<img width="960" alt="image" src="https://github.com/joomla/joomla-cms/assets/170947/10402ba2-3082-404d-aa14-d4d93bf19ee7">

**Comment by Quy** [comment] 2024-02-21 22:18
Perfect! On my system, the font-family is `san-serif`, but on yours it is `-apple-....`. This could be the problem. Have you tested on a clean install without Yootheme?


![42833-body](https://github.com/joomla/joomla-cms/assets/368084/3d649f59-8b20-491f-ac75-45d79f2fa75b)

**Comment by orschiro** [comment] 2024-02-22 07:46
Thanks!

Not yet. 

You think Yootheme can cause this problem by somehow changing the font-family?

**Comment by orschiro** [comment] 2024-02-23 08:43
Can the problem the following?

Cassiopeia "overrides" the editor.css file and uses its own

https://joomla.xxx/media/templates/site/cassiopeia/css/editor.min.css

And that works fine.

But without an override Joomla loads this file

https://joomla.xxx/media/system/css/editor.min.css

So I guess the question why the two editor.min.css files (owned by Joomla) are not identical.

**Comment by orschiro** [comment] 2024-02-29 11:35
@Quy @brianteeman could I get your input on my latest comment?

Thank you!
