### ISSUE TITLE
UX - Joomla! 4  - menu group stays closed when a menu group item is active

### ISSUE THREAD

**Issue by PhocaCz** [joomla/joomla-cms#14327] opened 2017-03-04 13:38 UTC
### Steps to reproduce the issue
Go to some extension's view, the left main menu will not display active view
![Menu Group Stays Closed](https://pbs.twimg.com/media/C4T8f1PWAAEA_9M.jpg)

### Expected result
The left main menu does not display active view

### Actual result
The left main menu should display active view. Even Joomla! menu position should be on top. It includes a lot of possible items which is better to manage through the top menu.

### System information (as much as possible)
Joomla! 4, PHP 7, MySQL 5

### Additional comments
Joomla! menu position should be on top. It includes a lot of possible items which is better to manage through the top menu.

**Comment by C-Lodder** [comment] 2017-03-04 22:03
The sidebar menu is being completely rewritten, so this can be closed.

**Comment by PhocaCz** [comment] 2017-03-04 22:36
Hi, thank you for the info.
Is there any info if it will be a left menu or top menu? Is there some discussion about the menu?

**Comment by C-Lodder** [comment] 2017-03-05 09:24
It will most likely be the left still, but we're still waiting for survey's to be sent out and the results back.

**Comment by PhocaCz** [comment] 2017-03-05 10:25
Is the survey somewhere active, online and published? Was it accessible for public Joomla! users?

From my experience, talking with Joomla! users (webdesigners, end users), first, they don't have any idea about how Joomla! 4 will look. Second, they are unpleasantly surprised by the fact that the menu should be moved to left.

It may seem that this is a trivial thing but for conservative users this may mean a disaster. So maybe some public discussion and poll about this topic will be welcomed.

**Comment by dgt41** [comment] 2017-03-05 10:56
> Second, they are unpleasantly surprised by the fact that the menu should be moved to left.

That's not a reason for us not moving to the right direction. Take a look at almost all other cms they do have a side navigation. I expect (or st least I hope) that the menu itself will have a different structure, one that promotes the content management and not something that makes sense to people working only with Joomla! The idea is to improve and also make the product more appealing to new users, keeping the crappy top menu will not bring any new people...

**Comment by C-Lodder** [comment] 2017-03-05 11:59
@PhocaCz - First survey will be out in about a week.

**Comment by PhocaCz** [comment] 2017-03-05 12:14
@C-Lodder
> Take a look at almost all other cms they do have a side navigation

I have never looked at other extensions when building new extension. People just don't want another copy of some other extension, they just want an alternative or new approach. If I would do a copy of an existing extension, I don't see any reason why it should exist.

See the Firefox, they just copied the look from Chrome but what happened? People move from Firefox to Chrome. Why install Firefox when you can use "the same and better" Chrome.

Wordpress is not more popular than Joomla! because of the menu position, there are other reasons. But when we do a copy or Wordpress why to use Joomla! then.

For me, other CMSs are not important but users are. If they feel the UX problems like they installed extension in Joomla! 3 with 2 clicks and in Joomla! 4 they need to do one click more, maybe we should ask them.

I don't say, we need to do 100% the menu on the top (anyway there are both for Joomla! 3 - one main on the top, second submenu on the left), but maybe we should ask the users. If users say in poll, they don't care about the menu position or they like the left position, you have confirmation that your decision was OK. 

In the time of Joomla! we have lost many web designers and their customers because of many fatal errors (like wrong backward compatibility, LTS vs. STS nonsense, options everywhere, complicated ACL, etc. etc.) they were done.

If a web designer has no power more to explain to his/her customers why it was changed again and again and why they need to learn new things again and again, maybe he/she moves with his/her customers to some other and more stable (changeless) CMS. (This happened to Joomla! in 2011)

As I wrote, I really don't know what is the right position and what users want. So this is why I always ask users before doing large change.

The question was if this was discussed well and if there is any output of this discussion?

**Comment by PhocaCz** [comment] 2017-03-05 12:44
> First survey will be out in about a week.

Yes, but which survey? It is public?

**Comment by dgt41** [comment] 2017-03-05 12:47
> If they feel the UX problems like they installed extension in Joomla! 3 with 2 clicks and in Joomla! 4 they need to do one click more, maybe we should ask them.

This is not a way to measure the effectiveness of the menu, simply because the task you are referring is going to executed only few times when somebody creates their site. So in that sense maybe you don't need a menu entry for that at all. Devs perspective is nowhere near to users point of view...

Firefox didn't loose people because they copied chrome, chrome was faster when it started dragging people from ff...

About other cmss and your approach of uniqueness: well I design is called common pattern and if you don't follow that then you either are a genius or an idiot.

The idea as I understand is to make joomla an option for people never used the product before, and keeping something old and ugly won't help towards that goal

**Comment by PhocaCz** [comment] 2017-03-05 12:51
> keeping the crappy top menu will not bring any new people...

Are there any case studies why top menu is "crappy"? (Please don't take this question as offensive, regarding menus, I am not export, so I really honestly ask to get more info about the position of the menu)

In all the Joomla! communities, I am a part, I have never seen some negative comment on the top menu, so I really just ask to get more info about this topic and about the reasons to skip top menu.

**Comment by PhocaCz** [comment] 2017-03-05 13:06
@dgt41 

> This is not a way to measure the effectiveness of the menu, simply because the task you are referring is going to executed only few times when somebody creates their site. So in that sense maybe you don't need a menu entry for that at all. Devs perspective is nowhere near to users point of view...

I am sorry, but this sounds to me like false argument. First I am not asking here from devs perspective but from users perspective we have discussed in our Joomla! community. Mainly I am not developer but a member of many Joomla! communities. Installing extension is not a devs task only. And it is not only about the topic "3 clicks to install extension" - this was only one example. This could happen to other tasks too.

> something old and ugly
I still don't understand what is "old and ugly" regarding top menu

> About other cmss and your approach of uniqueness: well I design is called common pattern and if you don't follow that then you either are a genius or an idiot.

Even the same question. Are there any case studies that top menu does not belong to a common pattern? Should we better use a ribbon instead of left menu? Ribbon just becomes slowly to be a common pattern.

**Comment by mbabker** [comment] 2017-03-05 16:48
Considering the number of administrative dashboard templates which feature a sidebar primary navigation versus a top menu, I think it is safe to assume that at some point someone did the research and testing to determine that was a more effective organization structure for its purpose.

**Comment by PhocaCz** [comment] 2017-03-05 17:15
Hi Michael,

I am really not here to somehow defend the top menu - to use it without compromise. If there is a time to leave this type of menu, then Ok. But I am really interested if there was a discussion about this topic or some poll and if it was public - just to see it - to see other opinions, cons and pros. We are changing some major UX part in CMS which was here from beginning.

I have just published the link to Joomla! 4 test package in our community and we just spoke about it. If it is really better solution regarding UX, etc. If you do more clicks than you have used to do (#14328 - please, this is example), it is not the change you wanted.

I have asked many times for discussion but got no link, nothing. So if this is some secret information in open source project and i get no answer, then I can only add feedback about what SOME users see as negative:

- active menu is not displayed #14327
- you do more clicks as you have used to do (in some cases) #14328
- to save a close you need to do two clicks instead of one #14326

If somebody cares about feedback, here is.

**Comment by mbabker** [comment] 2017-03-05 17:26
The feedback's fine, honestly though I think some of it at first comes across as "whoa, you're making change and I don't like it" (I don't mean that to sound as mean as it might, I promise).  The active menu thing is a legitimate bug at least.

As for the other two items, I don't think the template is a failure if it requires one additional click to perform some actions.  If we were really that concerned about number of clicks to do something, our pages would be far too busy making sure everything is one or two clicks away at the most.  The current template IMO does that in some places and causes the backend to feel really busy and cluttered at times.  The first iteration of the new template tries to clean up some of the screen clutter.  Nobody is calling it a finished and polished product right now, but I honestly feel like some parts of the base design are steps in the right direction.

**Comment by dgt41** [comment] 2017-03-05 19:14
> Are there any case studies why top menu is "crappy"? 

Case studies and surveys conducted with people using **only** Joomla are useless and pointless, I am telling that to the UX team from day one. The results will be very biased and ultimately useless. The problem is that we don't have a strong designer that will come up with fresh ideas for what makes the back end, control panel, edit view, list view and push that design forward. Patching things here and there and this is not gonna give us a fresh new product that most of us waiting for. 
You mention before how bad is to copy other's designs and I am afraid you are totally wrong here. Take as an example Samsung and Apple for the mobiles, or Microsoft and Apple. People accept the innovative design and try to offer that with their products. So in that sense if Joomla stays in it's own silo (thinking we are doing things differently) we honestly doing it the wrong way. One of my requests to the UX team was to explore other CMSs (indie, small ones but new) and take queues from their innovative design, e.g. https://www.leafpub.org (check their list view, the locater, inline editing, etc)

Copying best designs is not **BAD**, as far as it's done right...

**Comment by C-Lodder** [comment] 2017-03-05 20:26
I pushed for a sidebar menu simply because when scanning menu items, it's much easier on the side than on the top. This is fact.

Yes, there are cons of sidebar menu, but there are also cons of a top menu.

Some minor user testing was actually done over a year ago, and the sidebar was favoured. (don't ask for the results as I don't have them anymore)

**Comment by dgt41** [comment] 2017-03-05 20:53
> The problem is that we don't have a strong designer

Let me explain myself here: both @C-Lodder and @ciar4n are top notch designers and ui specialists, the problem is that they are essentially frozen at the moment as they wait for input from the UX team. So by strong designer I mean someone that will say `this process will never work with the current UX team, scarp the UX input and let's to this or that`.

**Comment by franz-wohlkoenig** [comment] 2017-04-04 12:06
closed as sidebar menu is being completely rewritten.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14327">issues.joomla.org/tracker/joomla-cms/14327</a>.</sub>

**Closed by franz-wohlkoenig** 2017-04-04 12:06 UTC
Labels: No Code Attached Yet
