### ISSUE TITLE
[5.0] Ldap client composer

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#40643] opened 2023-05-22 12:02 UTC
### Steps to reproduce the issue
Until Joomla 5.0 (#38209) composer.json referenced joomla/ldap

I am assuming it was removed intentionally?

If it was intentional then there is a problem in libraries\classmap.php which still references it
https://github.com/joomla/joomla-cms/blob/0b5f709d4da914cd4cde910647e518baf737f489/libraries/classmap.php#L418-L419

Amongst presumably other things this results in an error when running the stubgenerator

**Comment by HLeithner** [comment] 2023-05-22 12:24
Yes was intentionally, also missed to add it to the manual b/c breaks... 

I think the stub generator doesn't create this file, it's maintained manually isn't it?

**Comment by brianteeman** [comment] 2023-05-22 12:38
The stub generator parses the classmap.php - no idea how that is maintained - sorry

**Comment by HLeithner** [comment] 2023-05-22 13:06
Seems to be manually https://github.com/joomla/joomla-cms/commit/f5442b32447dae45dc6f3b63c5f786a7b060256c

I will do a pr when nobody else is faster then me later. thanks

**Comment by brianteeman** [comment] 2023-05-23 07:38
I notice that it says deprecated ibn 6.0 but its already been removed?

**Comment by HLeithner** [comment] 2023-05-23 08:22
wrong deprecation for this class, the problem is we can't support it anymore in 5.0 because the dependency doesn't fit iirc.
Also I think only joomla it selft used it in 3 and no longer in 4, all other ldap plugins that I know of use there own ldap lib.

But I will add it to the list of additional deprecation votes for production.

**Comment by brianteeman** [comment] 2023-08-01 19:30
> But I will add it to the list of additional deprecation votes for production.

did anything happen?

**Comment by HLeithner** [comment] 2023-08-01 21:13
Motion PROD2023/004 passed which includes this, I'm closing this as expected change, ok for you?

**Closed as completed by HLeithner** 2023-08-01 21:13 UTC
Labels: No Code Attached Yet

**Comment by brianteeman** [comment] 2023-08-01 21:33
dont you still need to update then classmap then?

**Comment by HLeithner** [comment] 2023-08-01 21:40
true I created a Pr https://github.com/joomla/joomla-cms/pull/41302
