### ISSUE TITLE
Missing grouping label on mod_articles_category

### ISSUE THREAD

**Issue by Nzara** [joomla/joomla-cms#7169] opened 2015-06-13 12:28 UTC
#### Steps to reproduce the issue
* create some categories, let say cat_a, cat_b
* create some articles in these categories, let's say: A, B, C
* create a module of type _Articles - Category_
 * choose option Filtering Options:Category: _all_categories_
 * choose option Grouping Options:Article Grouping: Category
 * choose an appropriate position to make it visible in your template
* view output of module on front end

#### Expected result
Name of Module
<ul>
 <li>
   <div class="grouping">Cat_a</div>
   <ul>
   <li>A</li>
   <li>B</li>
  </ul></li>
  <li>
   <div class="grouping">Cat_b</div>
   <ul>
   <li>C</li>
  </ul></li>
</ul>

#### Actual result
Name of Module
<ul>
 <li><ul>
   <li>A</li>
   <li>B</li>
  </ul></li>
  <li><ul>
   <li>C</li>
  </ul></li>
</ul>

#### Additional comments
After learning php i could work around by creating an overwrite of htm/mod_arcticles_category/default.php. Just insert after line 16:

    <div class="mod-articles-category-group"><?php echo $group_name;?></div>

I feel, this should be part of the core release.

**Comment by benyaminl** [comment] 2015-06-14 09:05
Actually what Joomla version? On 3.4.1 I got no problem with it.

**Comment by wojsmol** [comment] 2015-06-14 12:11
I tested it on Joomla 3.4.1 and 3.4.2 dev from 13.06.2015 with protostar template, issue confirmed.

**Comment by benyaminl** [comment] 2015-06-14 12:34
Nah maybe the template is the problem. I make my own template no problem. Maybe just attach the capture will help allot.
Benyamin Limanto

Sent from BlackBerry®

-----Original Message-----

**Comment by wojsmol** [comment] 2015-06-14 12:58
screenshot below
![Uploading joomla-cms-7169.jpg…]()

**Comment by wojsmol** [comment] 2015-06-14 13:24
after @Nzara chenge
![joomla-cms-7169-after](https://cloud.githubusercontent.com/assets/4176111/8148704/6f25bf7c-12a9-11e5-9d71-52f6056769ed.jpg)

**Comment by zero-24** [comment] 2015-06-14 19:11
@Nzara as you have code can you send your changes as Pull request against staging?

A step by step tutorial can be found here: https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests

Thanks :smile: 

If you have the pull request ready please add the link to the pull here and close this issue :smile: Thanks. Let me know if you have other questions regarding this. Thanks!

**Comment by brianteeman** [comment] 2015-06-19 12:26
Pretty sure that this problem was caused by this bad PR that was committed some time ago https://github.com/joomla/joomla-cms/commit/63864385a62042a6211cf59e0d15bbe3c7d10b3e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7169">issues.joomla.org/joomla-cms/7169</a>.</sub>

**Comment by Nzara** [comment] 2015-06-23 18:28
@zero-24 currently I have neither established a development environment nor do i have experience with the joomla coding standards or with GIT. So it may take some time acquire these. If someone could insert the single line of code given already,  apply coding standards and manage all the git stuff, this would greatly speed up fixing the problem a lot. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7169">issues.joomla.org/joomla-cms/7169</a>.</sub>

**Comment by wojsmol** [comment] 2015-06-23 18:45
@Nzara if @zero-24 will not have anything against it I can prepare the PR today.

**Comment by wojsmol** [comment] 2015-06-23 20:20
@Nzara please test https://github.com/joomla/joomla-cms/pull/7256

**Comment by Bakual** [comment] 2015-06-24 16:59
Closed since we have a PR #7256

**Closed by Bakual** 2015-06-24 16:59 UTC
Labels: No Code Attached Yet
