### ISSUE TITLE
[3.9.20] unable to reset password

### ISSUE THREAD

**Issue by toonetcreation** [joomla/joomla-cms#30141] opened 2020-07-20 07:56 UTC
### Steps to reproduce the issue

- go on login page on website fron-end
- click on forgotten password
- type your email
- you will receive email via link/token
- click on this link and then you get this error message : **Password reset code is invalid or was used previously!**

### Expected result

Normally, a new page is diplayed to choose a new password.

### Actual result

**Password reset code is invalid or was used previously!**

### System information (as much as possible)

os : Linux
Joomla : 3.9.20
php : 7.4.7
database : 5.5.5-10.2.32-MariaDB
cache disabled
Gzip enabled
server apache
Joomla Platform 13.1.0 Stable

**Comment by matrikular** [comment] 2020-07-20 09:01
Cannot confirm this issue.

Password reset process works as expected for me.


Setting | Value
-- | --
PHP Built On | Linux m32s20-6-25db.ispgateway.de 3.18.117-pvops-xen-x64 #1 SMP Tue Aug 7 13:41:39 CEST 2018 x86_64
Database Type | mysql
Database Version | 5.6.19-67.0-log
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.3.6
Web Server | Apache/2.4.41
WebServer to PHP Interface | fpm-fcgi
Joomla! Version | Joomla! 3.9.20 Stable [ Amani ] 14-July-2020 15:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0

**Comment by richard67** [comment] 2020-07-20 09:11
Maybe a permission problem? Which group does the user belong to? And which access levels are set for the menuitem (if some) for the password change form (= edit user form)?

**Comment by toonetcreation** [comment] 2020-07-20 09:55
I have no menuitem created for reset password page. is it mandatory?
Users are registered on main group call  **Enregistré**
Righs are like this, see below :
![screen shot 2020-07-20 at 09 55 43](https://issues.joomla.org/uploads/1/24bf9e91798e180cc639c2881bcdd961.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30141">issues.joomla.org/tracker/joomla-cms/30141</a>.</sub>

**Comment by richard67** [comment] 2020-07-20 09:57
> I have no menuitem created for reset password page. is it mandatory?

No, it's not mandatory. But it would have been an explanation maybe if it was there and had wrong access levels.

**Comment by toonetcreation** [comment] 2020-07-20 09:58
here is the page.
I'm using JooCart 3rd party extension also.

LOGIN with reset link :
https://www.vet-library.com/my-account/account/login.html

Password page :
https://www.vet-library.com/my-account/account/forgotten.html<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30141">issues.joomla.org/tracker/joomla-cms/30141</a>.</sub>

**Comment by toonetcreation** [comment] 2020-07-20 10:42
@richard67 ok thanks.
maybe this is linked to my 3rd party extension JooCart?
but weird, becuase previously was working fine :-/<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30141">issues.joomla.org/tracker/joomla-cms/30141</a>.</sub>

**Comment by richard67** [comment] 2020-07-20 12:52
@toonetcreation Is there an update available for JooCart? Maybe you don't have the latest version.

**Comment by brianteeman** [comment] 2020-07-20 13:16
This really should be a topic for the forum.

**Comment by toonetcreation** [comment] 2020-07-20 13:18
@richard67 JooCart i up to date

@brianteeman yes why not, at the beginning I was sure it was a bug due to 3.9.20 update.

**Comment by richard67** [comment] 2020-07-20 13:28
@toonetcreation You are running PHP 7.4, @matrikular could not reproduce it on PHP 7.3, that's one difference I see. Is there a way for you to test on a copy of your website if that still happens after having uninstalled JooCart? If so, try and report back the result here. If it's JooCart causing it, try to contact their support and close this issue here since definitely not a Joomla Core issue in this case. In any case it could be interesting to know: Has the PHP version recently upgraded from a lower minor version (7.x with x lower than 4) to 7.4? If so, that would be useful information here or in a forum post.

In any case, if you don't think anymore that it's a bug in Joomla core, please close this issue, possibly with a link to a post in the Joomla CMS support forum [https://forum.joomla.org/](https://forum.joomla.org/) if you opened a post there.

**Comment by toonetcreation** [comment] 2020-07-20 14:40
@richard67 thank you so much for feedback and your advice. I will try what you said and I come back here to give you the news. thanks again

**Comment by richard67** [comment] 2020-07-20 18:58
We'll wait a bit and if no new information after a while (some week or so) we'll close the issue. I set the "information required" label to have a reminder. Thanks in advance.

**Comment by N6REJ** [comment] 2020-07-21 00:17
I'm 99.9% sure this is caused by gzip.  Please turn it off and try again.

**Comment by matrikular** [comment] 2020-07-21 06:42
@N6REJ if you're talking about the Gzip Page Compression parameter in the global configuration, I've had that enabled.

**Comment by N6REJ** [comment] 2020-07-21 06:48
@matrikular ok, all I know is ALOT of the times, its gzip that causes issues

**Comment by toonetcreation** [comment] 2020-07-21 07:08
I have disavbled Gzip Page Compression in global configuration and same problem.

**Comment by Quy** [comment] 2020-07-21 16:41
> Password reset code is invalid or was used previously!

This error message is not from Joomla! core. Please check with extension provider.

**Comment by toonetcreation** [comment] 2020-07-22 14:19
problem solved : was due to error in 3rd party extension.
thanks again for your help

**Comment by toonetcreation** [comment] 2020-07-22 14:21
problem solved : was due to error in 3rd party extension.
thanks again for your help

**Closed as completed** 2020-07-22 14:21 UTC
Labels: No Code Attached Yet, Information Required
