### ISSUE TITLE
Very slow website when upgrading to Joomla 3.8.x

### ISSUE THREAD

**Issue by Folamour** [joomla/joomla-cms#19188] opened 2017-12-27 19:43 UTC
### Steps to reproduce the issue

hi we have 14.361 articles and 25 categories, our blog is 8 year old, since release 3.8.x our page load went from 4.5 sec to 9 sec. (so we restore the site to 3.7.5)

issue faced on 3.8.0, 3.8.1,3.8.2, 3.8.3

### Expected result

more article you have, slower is your page load since release 3.8.x

**Comment by ghost** [comment] 2017-12-27 19:56
Please ask help on the [forums - Migrating and Upgrading to Joomla! 3.x](https://forum.joomla.org/viewforum.php?f=710). This repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.

**Closed as completed** 2017-12-27 19:56 UTC
Labels: No Code Attached Yet

**Comment by frostmakk** [comment] 2017-12-27 20:20
This issue has nothing to do with upgrading Joomla.
It has to do with Joomla 3.8 being slower on large sites than 3.7 was, possibly due to the use of DISTINCT in components\com_content\models\articles.php

**Comment by mbabker** [comment] 2017-12-27 20:26
Given the initial issue report and the very vague "possibly due to the use of..." comment, right now there isn't really much that can be done to investigate or confirm a bug report, let alone fix it.  Without good information on how to create an environment where the issue can be reproduced and what the symptoms of the issue are, there isn't anything we can do.

Sorry, but "after upgrade my site is slower" just isn't a detailed enough report to really say anything but what the initial response you got was.

**Comment by frostmakk** [comment] 2017-12-27 21:48
Not my site. Just a bystander. I'll try to be a little less vague.
DISTINCT can be very slow. It was added to articles.php in 3.8.0
Is it required? Can it be done differently? or simply removed?

**Comment by Folamour** [comment] 2017-12-27 23:30
Thread Created on Joomla.org, Thanks a lot ! my previous thread was not in the correct category, 

Btw can remove too Distinct ? so i can do a retry to upgrade.

Thanks,

f.
