### ISSUE TITLE
Update sites turn disable themselves

### ISSUE THREAD

**Issue by DavidBoggitt** [joomla/joomla-cms#20543] opened 2018-05-23 05:41 UTC
### Steps to reproduce the issue

?

### Expected result

Update sites don't turn themselves off

### Actual result

Update sites do turn themselves off!

### System information (as much as possible)

J3.8.x (I've seen it for a while!)

### Additional comments

See this forum post:

https://forum.joomla.org/viewtopic.php?f=708&t=962228

I quite expect this post to be closed as it's probably not a bug, but it is very weird behaviour and a pain in the butt when trying to keep a site updated!

**Comment by brianteeman** [comment] 2018-05-23 08:18
Are you talking about extension update sites or the core joomla update site?

**Comment by DavidBoggitt** [comment] 2018-05-23 08:46
Extension update sites.

**Comment by Quy** [comment] 2018-05-23 11:44
Are the same ones being disabled or randomly?

**Comment by DavidBoggitt** [comment] 2018-05-23 12:33
I honestly haven't looked that closely, I've just noticed some disabling themselves so I'm not alerted to updates, even though I know they are available.  I could try and keep a record! :)

**Comment by brianteeman** [comment] 2018-05-23 12:55
iirc the update site will be disabled if your site cannot reach it.

**Comment by zero-24** [comment] 2018-05-23 17:45
> iirc the update site will be disabled if your site cannot reach it.

Yes this is the case. And the reason is that when the developer took that domain down the checks does not time out ;) I would call that expected behavior.

**Comment by brianteeman** [comment] 2018-05-23 17:55
I was going to suggest that we periodically recheck disabled sites as that would address the issue of an extension site being temporarily unavailable. However that has the downside of re-enabling a site that you have deliberately disabled.  So I don't think there is anything we can do.

**Comment by zero-24** [comment] 2018-05-23 17:57
> So I don't think there is anything we can do.

.. beyond that what we already do. By showing a big warning message when a site is disabled on the update screen ;)

**Comment by brianteeman** [comment] 2018-05-23 17:58
Closing as there is nothing we can do in the core

**Closed as completed by brianteeman** 2018-05-23 17:58 UTC
Labels: No Code Attached Yet
