### ISSUE TITLE
Meta Tag validation error in validator.w3.org

### ISSUE THREAD

**Issue by johnoros** [joomla/joomla-cms#14435] opened 2017-03-09 11:05 UTC
### Steps to reproduce the issue

Follow this link
https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.joomlage.com%2F

### Expected result
To not have the error with the meta tag created by joomla cms

### Actual result
A document must not include both a meta element with an http-equiv attribute whose value is content-type, and a meta element with a charset attribute.
From line 18, column 2; to line 18, column 70
com/" />↩	<meta http-equiv="content-type" content="text/html; charset=utf-8" />↩	<met

### System information (as much as possible)
Joomla 3.6.5

**Comment by C-Lodder** [comment] 2017-03-09 11:36
`<meta http-equiv="content-type" content="text/html; charset=utf-8" />` is only added when `JFactory::getDocument()->setHtml5(true);` is defined in the template's `index.php`. 

So, it would seem the template you mentioned has NOT set HTML to true and have manually included `<meta charset="utf-8">` in the `<head>`.

This is not a core issue, but simply a matter of the template not using the correct methods.

**Comment by rdeutz** [comment] 2017-03-09 13:01
not a bug, I am closing this

**Closed by rdeutz** 2017-03-09 13:01 UTC
Labels: No Code Attached Yet
