### ISSUE TITLE
Tag not taken into account with 'fast' input

### ISSUE THREAD

**Issue by b92** [joomla/joomla-cms#4948] opened 2014-10-28 18:41 UTC
The tags may not be taken into account if the input is made with focus changed too fast.

#### Steps to reproduce the issue

- Create Joomla Tags (for the example: red, yellow)
- Create an article
- Start the input for the tag. For example type 'red' and click very fast somewhere else to change the input focus.
Note: reproduce or not reproduce may depend of your speed (the tags need to be NOT selected into the list to reproduce it).

The result is: you will have the tag into 'real' text instead of the value usually found and display (the little 'box' with the cross). 

When you save the article, even if the Tag seems to be fill in, for the user, it will be not saved.

#### Expected result

- Correct tag (for full input, like 'red')
or - No text dislayed at all for partial input like 'yell' (for the yellow tag) (like for a wrong input which do not fit to any tag)

#### Actual result

Only text not used during saving.

#### System information (as much as possible)

Joomla 3.3.6
Browers used for the tests: Chrome 36 / Firefox 24 & 33 / IExplorer 11 on Windows 7 & 8.1

#### Additional comments

This effect ‘only’ appends if the text corresponds to an existing tag or to the beginning of an existing tag. If the text does not correspond to a tag, nothing is displayed when losing the focus (correct).

May be some changes to be made into the funtion ajaxfield() from /librairies/cms/html/tags.php ... for Joomla & Jquery developers.

**Comment by alikon** [comment] 2016-05-08 08:36
i'm unable to reproduce, probably this was fixed in the meantime<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4948">issues.joomla.org/joomla-cms/4948</a>.</sub>

**Comment by brianteeman** [comment] 2016-05-08 08:37
Thank you for creating this but it would appear that this has been resolved elsewhere in the code base. If this is not correct then this can be re-opened<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4948">issues.joomla.org/joomla-cms/4948</a>.</sub>

**Closed** 2016-05-08 08:37 UTC
Labels: No Code Attached Yet
