### ISSUE TITLE
[com_fields] Only show the field value in user profle

### ISSUE THREAD

**Issue by Flowman** [joomla/joomla-cms#16098] opened 2017-05-18 02:40 UTC
### Steps to reproduce the issue
Create some custom fields for a user.
Go to the user profile page in frontend.

### Expected result
Custom fields should render with the field template.

### Actual result
Costum fields does only show the field value.
![image](https://cloud.githubusercontent.com/assets/212680/26184181/db0b38de-3bb5-11e7-9c28-ac8cdffd3b2b.png)

### System information (as much as possible)
Joomla 3.7.0
PHP 7.1.4
Nginx 1.12

### Additional comments
I noticed there is no code in the profile view to render the jcfields.

**Comment by franz-wohlkoenig** [comment] 2017-05-18 04:52
didn't get the Point, cause in Screenshot there is Label and Value. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16098">issues.joomla.org/tracker/joomla-cms/16098</a>.</sub>

**Comment by sharphosting** [comment] 2017-05-18 04:55
The point is that the value should be rendering with the template for that field, but is displaying the raw value instead. As @Flowman stated in "Expected Result".

**Comment by franz-wohlkoenig** [comment] 2017-05-18 05:05
@sharphosting thanks for hint, got it.

**Comment by laoneo** [comment] 2017-05-18 06:06
The problem is that this view is different than every other front end view in Joomla. probably nobody knows the reason for it. But what it does it [renders the fields based on a form](https://github.com/joomla/joomla-cms/blob/staging/components/com_users/views/profile/tmpl/default_custom.php). The problem is that I think it is not possible to rewrite that thing in Joomla 3 because of some unknown side effects.

**Comment by Flowman** [comment] 2017-05-18 06:39
We could do the same as for com_contacts [/components/com_contact/views/contact/tmpl/default_user_custom_fields.php](https://github.com/joomla/joomla-cms/blob/staging/components/com_contact/views/contact/tmpl/default_user_custom_fields.php)

I know it is not the exact same thing but something similar could be achieved.

**Comment by laoneo** [comment] 2017-05-18 07:37
The problem is that it uses a JForm instance while the contact layout is only on fields. Would mean every plugin which doesn't support the display events would not be shown in the profile anymore.

**Comment by jwaisner** [comment] 2020-03-12 13:51
@Flowman Does this still exist in the latest J3?

**Comment by chmst** [comment] 2021-02-28 15:16
No answer since 2017, closing for now.

**Comment by brianteeman** [comment] 2021-02-28 16:16
**#PROD2020/024 - There shall be no indiscriminate closing of Issues or Pull Requests**

Closing of Issues and Pull requests PR's shall NOT be done without underlying rationale and individual reasoning in the Issue or PR. Elapsing of a time period, inactivity of the submitter are examples that do NOT constitute valid reasons in and by themselves.

**Comment by laoneo** [comment] 2021-03-02 05:56
Can you test this on J4? Not sure if it got fixed there.

**Comment by brianteeman** [comment] 2022-08-25 20:40
Thank you for raising this issue.

Joomla 3 is now in security only mode with no further bug fixes or new features.

I have verified that this is resolved in Joomla 4 and this will now been closed.

![image](https://user-images.githubusercontent.com/1296369/186764489-39527daa-57c6-4b04-bf16-f27b0d9018dc.png)

cc @zero-24

**Comment by richard67** [comment] 2022-08-25 20:43
Closing for the reason stated above. Thanks for reporting.

**Closed by richard67** 2022-08-25 20:43 UTC
Labels: No Code Attached Yet
