### ISSUE TITLE
J 3.5.1 is cutting dead default language other than english

### ISSUE THREAD

**Issue by radik10** [joomla/joomla-cms#10248] opened 2016-05-05 06:26 UTC
#### Steps to reproduce the issue
install (clean install - not upgrade) J 3.5.1, install Slovak language (maybe other) and make slovak lang. default in joomla language settings. Leave in user account (for backend language settings) "default language". Log out from backend, login again (leave in administration login panel "language - default") - Joomla will ignore (cut dead) slovak language (as default lang.) and will use english instead of slovak in backend administration. 

#### Expected result
login with slovak language in administration backend

#### Actual result
loged with english language in administration backend

#### System information (as much as possible)
DB: 5.5.25a 
PHP: 5.4.4 
j 3.5.1 (clean install)
same in latest chrome and latest firefox - so it is problem of Joomla

**Comment by ot2sen** [comment] 2016-05-05 07:04
Could not reproduce the issue by following the steps.
Result here is admin in Slovak 
![screen shot 2016-05-05 at 02 03 55](https://issues.joomla.org/uploads/1/cba43bb8cd67a1b08f9097c2d57016d0.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10248">issues.joomla.org/joomla-cms/10248</a>.</sub>

**Comment by brianteeman** [comment] 2016-05-05 07:22
Same as @ot2sen I had no problem using the slovak language<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10248">issues.joomla.org/joomla-cms/10248</a>.</sub>

**Comment by brianteeman** [comment] 2016-05-05 08:16
As two of us have been unable to replicate this issue it sounds like something specific to your eb site and not an issue with the core of Joomla so I am closing this here. If you still have issues please use the forum for support http://forum.joomla.org<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10248">issues.joomla.org/joomla-cms/10248</a>.</sub>

**Closed** 2016-05-05 08:16 UTC
Labels: No Code Attached Yet
