### ISSUE TITLE
XTD buttons not working in Joomla 4x on Custom field type Editor

### ISSUE THREAD

**Issue by umiha** [joomla/joomla-cms#39277] opened 2022-11-22 12:08 UTC
### Description of the bug
When using Joomla Custom field type Editor with Editor-None, Codemirror, then Joomla editor-xtd buttons are not working. When I click on any of buttons (except Read More) they are not working. For example if I click Media the screen gets grey transparent overlay but modal window doesn't show up.
Additional information - on main tab Content those xtd buttons works. They only not working on Joomla Custom fields.

### Steps to reproduce the issue
1. Joomla 4x
2. Create Joomla Custom field (type Editor), and assign it to All categories
3. Open some new or existing Article, then go to tab "Fields"
4. Find previously created custom field, and click on Joomla editor-xtd buttons bellow text area
5. You will see that modal windows is not opening, and you can not do anything with those buttons

### Expected result
When clicking on Joomla editor-xtd buttons then modal window popup should show up so you can choose for example to insert Article (link), Media (image), Menu (link), etc.

### Actual result
You will see that modal windows is not opening, and you can not do anything with those buttons

### Screenshot
![screen shot 2022-11-22 at 12 04 29](https://issues.joomla.org/uploads/1/37f64d1f6d563f40845c97cc8f22ffd1.png)

### System information (as much as possible)
My Desktop
OS: macOS Monterey
Browser: Chrome ver. 107, but same in Firefox and Safari

CMS
Joomla 4.2.5
Linux server
PHP 7.4

**Comment by brianteeman** [comment] 2022-11-22 12:10
Please check your browser console for any javascript errors

**Comment by umiha** [comment] 2022-11-22 12:24
Hi, I checked, but there is no javascript errors in the browser console.
Also on Network tab of browser developer tools I don't see any request with 404 status.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39277">issues.joomla.org/tracker/joomla-cms/39277</a>.</sub>

**Comment by brianteeman** [comment] 2022-11-22 12:31
Confirmed

**Comment by dgrammatiko** [comment] 2022-11-22 20:40
There should be an older issue for this one but anyways I will try to explain what is happening, what is actually wrong in the Joomla codebase and the 3 possible ways to fix this. The default editor is rendered in the first tab of the article edit form. In that tab also ALL the modals are rendered (echoed from PHP if you prefer). The tab `Fields` that has the second instance of the editor has ONLY the buttons (bellow the none/codemirror). The problem (is not unique to this case, it also happens in the toolbar and other places where the modal could be under a hidden div/section/etc) is that the modal when it's being called will never appear because one of the parent elements has a `display:none`, it is hidden, so you only get the backdrop. Great stuff!

How to solve it? There are some nasty hacks and some nice ways (you pick your poison):
- Use JS to move the modal to the end of the document. This is hacky, it is complicated and prone to bugs and it's what Joomla is doing at the moment for the toolbar buttons that open a modal, ie: https://github.com/joomla/joomla-cms/blob/06038e5b820f09fbb9490c5ecd5c326efdcc612d/build/media_source/com_contenthistory/js/admin-history-versions.es6.js#L6-L11
- Resurrect my PR: https://github.com/joomla/joomla-cms/pull/37330 which adds a simple mechanism to enqueue chinks of HTML that should be rendered at the end of the body. This is completely B/C, it requires minimal changes and it's clean, the dev decides where to render the modal.
- Cancel the Bootstrap Modal altogether, because it's (almost) 2023 and all browsers support the native DIALOG element. This, depending how it would be implemented, might have 0 to major B/C breaks.

Pick your poison...

**Comment by OctavianC** [comment] 2022-11-23 14:48
I think I found a 4th one, please see #39287 :)

**Comment by umiha** [comment] 2022-11-23 21:06
Hi, just to mention, there can be variable number of editors on a single page on article, when using custom fields.
You can have some fixed number of custom fields type Editor,
and also variable number of editors when using editors within Subform field with repeatable option.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39277">issues.joomla.org/tracker/joomla-cms/39277</a>.</sub>

**Comment by richard67** [comment] 2022-11-23 22:46
Closing as having a pull request. Please test #39295 . Thanks in advance.

**Closed as completed by richard67** 2022-11-23 22:46 UTC
Labels: No Code Attached Yet, bug

**Comment by umiha** [comment] 2022-11-24 15:13
I have tested this, #39287 and #39295, and both works for me. Great job!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39277">issues.joomla.org/tracker/joomla-cms/39277</a>.</sub>
