### ISSUE TITLE
Joomla 3.6.5 Global Configuration Text Filter - not working

### ISSUE THREAD

**Issue by FCPeggy** [joomla/joomla-cms#13581] opened 2017-01-13 14:16 UTC
Global Configuration / Text Filters / SuperUser - set to "No Filtering"
Text editor keeps stripping html code even though NO FILTERING is set.
Is this a known issue / bug?

**Comment by zero-24** [comment] 2017-01-15 13:47
Can you confirm that it is the TinyMCE? Please confirm the settings of the plugin where you can enable that.

**Comment by FCPeggy** [comment] 2017-01-15 17:44
Hi,
Yes it is TinyMCE with the text filter set to off for Superadmin level.
Do you need anything more?
I am using Joomla 3.6.5.
Thank you,
Peggy

**Comment by richard67** [comment] 2017-01-16 19:11
It possibly also needs to remove html elements (e.g. iframe, if you need that) from the "Prohibited Elements" value and add some to the "Extended Valid Elements" value in the TinyMCE plugin's settings.

For example I have following defined as extended valid elements:

a[class|id|title|href|hreflang|rel|target|type|onclick|style],audio[class|id|title|preload|autoplay|controls],div[class|id|itemprop|itemscope|itemtype|style],img[class|id|itemprop|src|border|alt|title|hspace|vspace|width|height|align|onmouseover|onmouseout|name|style],meta[class|id|itemprop|content],source[class|id|src|type],span[class|id|itemprop|style],track[class|id|default|kind|label|src|srclang],video[class|id|title|poster|preload|autoplay|controls|width|height]

Unfortunately you have to define all allowed properties of a tag again if you add it to the extended valid elements, even ig these properties would not have been stripped off before (e.g. img[class|id|...]) just if you want to allow an additional property (e.g. itemprop) for an image.

For more information, just do a web search for "tinymce extended valid elements". <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13581">issues.joomla.org/tracker/joomla-cms/13581</a>.</sub>

**Comment by FCPeggy** [comment] 2017-01-16 21:24
Hi, I am not at your skill level.

My issue is that this did not happen in previous builds and now it is.  It
should not need this type of adjustment for everyone using Joomla 3.6.5 for
web design.

Will there be a fix to this in 3.7?

Is this a bug and should it not be treated as a bug for version 3.6.5?

I appreciate your help.
Cheers,
Peggy

**Comment by franz-wohlkoenig** [comment] 2017-02-05 18:31
Test on: Joomla! 3.7.0-latest staging, TinyMCE-Options: `Use Joomla Text Filter: On`, Global Options: `Text Filters > Super users: No Filtering`.

`<italic>` became in Source-Code `&lt;italic&gt;`, using Buttons works.

**Comment by Dweezledap** [comment] 2017-02-15 02:30
I'm having the same issue. It does not matter whether I use JCE, TinyMCE, or no editor. My admin directory is password protected and I'm the only person using the backend. Where could I find this in the source code to make a temporary change? The only other option I can think of is to add the code directly to the database.

**Comment by brianteeman** [comment] 2017-05-21 09:49
@franz-wohlkoenig that will always happen if you enter code in wysiwyg view. Plus thats not a real tag so it will probably be stripped and replaced with a p tag anyway

**Comment by AboQusai** [comment] 2017-06-10 10:48
Well, let me talk frankly. I have been searching all over to solve this issue but with no success.
One critical thing I would like to say. It is for security of the website all of this strong stand against the HTML tags was taken. However, trying to solve this issue from our side has in fact harmed the security of the website a lot because we tried to loosen every possible restriction in order to see our Iframe works.

**Comment by zero-24** [comment] 2017-06-10 17:33
> However, trying to solve this issue from our side has in fact harmed the security of the website a lot because we tried to loosen every possible restriction in order to see our Iframe works.

But this sounds like you fond the solution now?

**Comment by AboQusai** [comment] 2017-06-10 21:09
Absolutely not. I think no solution is available. I have went through many documents and reached a confidence that this is simply not allowed for the current version 3.7.2 (or it might be a bug?).

**Comment by AboQusai** [comment] 2017-06-10 21:15
By the way, it has nothing to do with Editor Type you choose. It applies to all editors including the (none).  Accordingly, it is linked to Joomla itself.

**Comment by pjkundert** [comment] 2017-07-10 12:08
This is still happening in Joomla 3.7.3, with TinyMCE.  Both TinyMCE and Global configurations have been confirmed to allow iframe.  This seems like a serious defect.

**Comment by brianteeman** [comment] 2017-07-10 12:19
I can not confirm that. 

## Test 1
I set the tinymce plugin to "Use Joomla Text Filter"
and then with a superuser which has the default setting of "No filtering" set in the global configuration I was able to insert and save an iframe as expected

## Test 2
I set the tinymce plugin to NOT "Use Joomla Text Filter" (which is the default)
and then I remove iframe from the list of "Prohibited Elements"
I was able to insert and save an iframe as expected

**Comment by pjkundert** [comment] 2017-07-18 13:43
It appears to be limited to the editor (TinyMCE, in my case); I was able to add the iframe only by disabling the editor (setting the Global "Default Editor" to Editor - None).

**Comment by brianteeman** [comment] 2017-12-25 15:16
There is no bug

What you are probably NOT doing is setting the tinymce option "use joomla text filter" to off for the correct (or all groups). The options are set per group. eg by default we have groups 1, 2 and 3.

Closed as not a bug

**Closed by brianteeman** 2017-12-25 15:16 UTC
Labels: No Code Attached Yet
