### ISSUE TITLE
[4.3.4] Undefined array key "en-GB" and Attempt to read property "sef" \plugins\system\languagefilter\languagefilter.php on line 226

### ISSUE THREAD

**Issue by peterhulst** [joomla/joomla-cms#41798] opened 2023-09-18 21:19 UTC
### Steps to reproduce the issue
- Have all content languages unpublished
- Enable the plugin language filter with default settings
- Site language en-GB

### Expected result
Correct display website display

### Actual result
A lot of warnings:
Warning: Undefined array key "en-GB" in ...\plugins\system\languagefilter\languagefilter.php on line 226
Warning: Attempt to read property "sef" on null in ...\plugins\system\languagefilter\languagefilter.php on line 226

### System information (as much as possible)
Joomla 4.3.4
PHP 8.0.28, PHP 8.1.23

### Additional comments
When disable the plugin language filter the warnings disappear.

**Comment by richard67** [comment] 2023-09-19 20:07
Cannot be that the content language for en-GB is missing? I don’t mean the language packs or extensions, I mean the content languages, that’s an extra point in the manage area of the system panel. That’s where the sef property should come from which is mentioned in the error message.

**Comment by peterhulst** [comment] 2023-09-20 07:19
Hello Richard, you are right: the en-GB was unpublished. After publishing it, the error disappeared. 
Is it an idea that a hint is displayed instead many error messages in case this happens?
Thanks for yout help.
Regards

**Comment by richard67** [comment] 2023-09-20 08:01
> Is it an idea that a hint is displayed instead many error messages in case this happens? Thanks for your help. Regards

@peterhulst Well, I would indeed expect a useful alert instead of an uncaught exception when you enable the language filter and the content language is not published.

I think that's a bug.

On a multilingual site there is also a module shown in the administrator (in the default Atum template it's shown at the top) called "Multilingual Status" or so. That opens a modal which shows what's missing on a multilingual site, and it should show that the content language is not published.

**Comment by peterhulst** [comment] 2023-09-20 21:29
Thank you for the comment.

**Comment by brianteeman** [comment] 2023-09-30 08:04
When you unpublish all the content languages you already get a nice error message

![image](https://github.com/joomla/joomla-cms/assets/1296369/48ddea74-72c4-40fa-b9b5-2849027783ac)

**Comment by peterhulst** [comment] 2023-10-04 20:01
Thank you Brian! 
Indeed this message is very clear.
Regards,
Peter

**Comment by richard67** [comment] 2023-10-04 20:06
Well that's the nice error message when you unpublish the site languages. But when you have them unpublished and enable the language filter, we have the PHP warnings.

So should we leave this issue open and hope someone fixes that, too? Or shall we close it as expected behaviour?

**Comment by Hackwar** [comment] 2024-04-08 09:06
I created a PR. Please test #43232. Since we have a PR, I'm closing this issue.

**Closed as completed by Hackwar** 2024-04-08 09:06 UTC
Labels: No Code Attached Yet, bug
