### ISSUE TITLE
Be able to change timezone for actionlogs exports

### ISSUE THREAD

**Issue by tntmartin** [joomla/joomla-cms#29492] opened 2020-06-08 15:25 UTC
### Steps to reproduce the issue
User go to User Actions Log in the backend and choose "Export Selected as CSV"

### Expected result
CSV file shows time in GMT no matter Timezone settings in Joomla or PHP.

**Comment by PhilETaylor** [comment] 2020-06-08 17:01
already dismissed as a `won't fix` by @mbabker here https://github.com/joomla/joomla-cms/issues/22629 and work done here https://github.com/joomla/joomla-cms/pull/22751

**Comment by mbabker** [comment] 2020-06-09 00:53
It was a purposeful design decision to allow the CSV files to be parsed consistently by machine tools and not need to worry about things like timezone offset.  Otherwise, the timestamps must include timezone offset to be usable.

Also note that any changes to the existing data format can only be made in major versions as changes to the data format could be considered a B/C break (treat the resulting CSV as you would a REST API endpoint basically), so if a change is going to be entertained it needs to go into 4.0 and it needs to be decided pretty quickly as technically the beta phase should not be introducing new breaks.

**Comment by tntmartin** [comment] 2020-06-10 09:48
Thanks for the reply!

**Comment by brianteeman** [comment] 2020-06-19 22:18
This should be closed as intended behaviour

**Closed as completed** 2020-06-20 02:22 UTC
Labels: No Code Attached Yet
