### ISSUE TITLE
[5.0] [com_fields] Showon Attribute doesn't accept correct syntax on Joomla 5

### ISSUE THREAD

**Issue by AndySDH** [joomla/joomla-cms#41788] opened 2023-09-18 12:58 UTC
### Steps to reproduce the issue

- Go to Content -> Fields
- Edit an existing field or create a new one
- Go to Options tab
- Edit the "Showon Attribute" field.
- Try to set it so that the field depends on another field being NOT EMPTY (without needing a specific value).
> To show a field when another field (e.g. foo) has been selected (when that other field is not empty), use showon="foo!:" (without a value specified).

This is described in the documentation here:
https://docs.joomla.org/Form_field#Common_attributes
and here:
https://help.joomla.org/proxy?keyref=Help50:Fields:_Edit&lang=en#Options

### Expected result

I should be able to save the field options.

### Actual result

Upon saving, I get this error:

"Invalid field: Showon Attribute"

It seems like the form is expecting something after the colon, eg "foo!:2" (for saying when it's NOT 2), but as documented, the syntax for NOT EMPTY is simply "foo!:" and should work.

Now it no longer works.

### System information (as much as possible)

‎5.0.0-beta1

### Additional comments

This works correctly in the current and latest version Joomla 4. 

It broke in Joomla 5.

**Comment by richard67** [comment] 2023-09-18 14:48
Could be caused by #41460 . @MagnusSinger Could you check. Thanks in advance.

**Comment by AndySDH** [comment] 2023-09-18 14:51
Yes it is definitely related

**Comment by MagnusSinger** [comment] 2023-09-21 14:20
Sure I'll check it ASAP

**Comment by richard67** [comment] 2023-09-25 11:33
There are other problems with that rule, too, see my comment here: https://github.com/joomla/joomla-cms/pull/41460#issuecomment-1733480282 .

**Comment by richard67** [comment] 2023-09-25 11:58
Am working on a fix, see #41918 . But I have to test it myself first. So it's still draft. When it is ready we can close this issue.

**Closed as completed** 2023-09-25 15:01 UTC
Labels: No Code Attached Yet, bug
