### ISSUE TITLE
Linking menu item alias to another alias

### ISSUE THREAD

**Issue by crystalenka** [joomla/joomla-cms#14644] opened 2017-03-15 16:50 UTC
### Steps to reproduce the issue
1. Create a new menu item (type: alias).
2. Link to another menu item, which is also an alias.
3. Attempt to save.

### Expected result
Error message of some sort

### Actual result
Successful save! The user thinks it works because there is no indication it shouldn't, but it will be a broken link in the front-end.

### System information (as much as possible)
N/A

### Additional comments
There should be some indication that one cannot link to another alias (because routing breaks and the link is borked). Some ideas:

1. (ideal scenario) Menu item aliases appear in the menu but cannot be selected AND are marked as alias. For example:

- Home
- Products 
- - All Products (_alias_)

2. (MVP) When trying to save, an error should occur to warn the user that this link will not work and that they need to select the original menu item.

**Comment by brianteeman** [comment] 2017-03-15 18:14
i can confirm this on 3.6.5 but not on 3.7 - can you please check with 3.7 as the way you can select menu items to alias to has changed and is no longer a select list but a modal popup and from my test the modal popup did not display any menu items that were alliases

**Comment by brianteeman** [comment] 2017-03-17 12:20
@crystalenka can you confirm that this is no longer an issue in Joomla 3.7 so that this can be closed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14644">issues.joomla.org/tracker/joomla-cms/14644</a>.</sub>

**Comment by franz-wohlkoenig** [comment] 2017-04-03 11:15
In 3.7 creating a Alias-Menu in Modal-Window "Select or Change Menu Item" a existing Alias-menu isn't shown.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14644">issues.joomla.org/tracker/joomla-cms/14644</a>.</sub>

**Comment by Quy** [comment] 2017-04-16 04:14
Unable to reproduce in 3.7.

**Comment by franz-wohlkoenig** [comment] 2017-04-16 05:47
closed as unconfirmed Report. @crystalenka please feel free to reopen.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14644">issues.joomla.org/tracker/joomla-cms/14644</a>.</sub>

**Closed by franz-wohlkoenig** 2017-04-16 05:47 UTC
Labels: No Code Attached Yet
