### ISSUE TITLE
joomla contact form subject field size

### ISSUE THREAD

**Issue by JoomlaTema** [joomla/joomla-cms#28711] opened 2020-04-17 20:31 UTC
### Steps to reproduce the issue
Joomla 3.9.16 default contact form you can not change subject input area size whic is longer than name and e mail input sizes.It is not possible to make all the same size by css. The html of subject input is
`<input type="text" name="jform[contact_subject]" id="jform_contact_emailmsg" value="" class="required" size="60" required="required" aria-required="true">`
But no luck any of codes below does not work even if you created an override.
`.contact-form #jform_contact_emailmsg {width: auto!important;}`
That problem seems to related to size="60" in components\com_contact\models\forms\contact.xml
### Expected result
`.contact-form #jform_contact_emailmsg {width: auto!important;}`should work 

### Actual result

`.contact-form #jform_contact_emailmsg {width: 100%;} `

### System information (as much as possible)
Joomla 3.9.16 default contact form

### Additional comments
That problem seems to related to size="60" in components\com_contact\models\forms\contact.xml

**Comment by ReLater** [comment] 2020-04-18 19:42
What is your exact expectation if you set `width: auto !important`  and remove the `size`?

That doesn't mean that the field is growing while you enter a long email address (as far as I've tested your issue with several browsers).

And the size has no influence on the length of the entered text. And it can be easily overruled by CSS (width, max-width, min-width).

**Comment by JoomlaTema** [comment] 2020-04-18 21:31
I just want to be able to style it using css. So main problem is that subject field is much longer than name and e mail fields just above it. I want them to have the same sizes. I couldnt be able to achieve it via css or contact form override until changing xml file.

**Comment by ReLater** [comment] 2020-04-18 23:17
I'm sorry but I can't reproduce this issue.
A CSS like

```
.contact-form input,
.contact-form textarea {
width: 95%;
max-width: 560px;
}
```
gives in Firefox 75.0 (64-Bit):

![19-04-_2020_01-14-48](https://user-images.githubusercontent.com/20780646/79673595-74770700-81db-11ea-9bcb-2bf6ef1d6b50.jpg)

![19-04-_2020_01-15-10](https://user-images.githubusercontent.com/20780646/79673602-7f319c00-81db-11ea-91d4-661feab9f29e.jpg)

**Comment by JoomlaTema** [comment] 2020-04-19 00:29
Well That should be protostar (bootstrap v2) I am using t3 blank template (bootstrap v3). I do not want to give a spesific width in pixels for both text fields because of mobile screens. The width vlue of name and  mail box is auto when I make **subject** width auto like them it does not align because it is 60 in size in XML see attached images. Protostar has a spesific width value of 206 px.

![1](https://user-images.githubusercontent.com/14791155/79675976-40f1a800-81ee-11ea-96f0-720c3adee912.jpg)


![2](https://user-images.githubusercontent.com/14791155/79676108-4b13a680-81ee-11ea-912e-ad6be7ad6cbd.jpg)



![3](https://user-images.githubusercontent.com/14791155/79676167-4fd85a80-81ee-11ea-9eda-5e4ffe280e30.jpg)

**Comment by ReLater** [comment] 2020-04-19 11:49
> Well That should be protostar (bootstrap v2) I am using t3 blank template (bootstrap v3)

Then you are here at the wrong place to post your issue. github.com/joomla/joomla-cms is only for core issues, not 3rd party extensions.

Because your issue is not reproducable with Joomla core: Please close here and ask in a forum like https://forum.joomla.org/

BTW: I'm using Bootstrap 4 menawhile in Joomla 3 and can't reproduce the issue. And used  BS3 for a long time and could also adapt the contact form without issues.

**Comment by JoomlaTema** [comment] 2020-04-19 13:36
I think that is a core issue because the default size of subject area is 60 when the others (name and e mail inputs) are 30. When you try to use `width:auto; ` command for all input areas it does not work. You can recreate the issue  with protostar also (see screenshot). The Screenshot of protostar using width auto for input areas.  If I give a spesific width like 80% it will cause problems on smalll screens if I give 600 px it will be okay for desktop but may cause problem on small screens again. So they all should be the same size in default for those who do not want to use a spesific size in pixels.
![Untitled-1](https://user-images.githubusercontent.com/14791155/79689208-f27af280-825b-11ea-8039-f0ad38b137e5.jpg)

**Comment by gerryfrancis** [comment] 2020-04-19 16:28
@JoomlaTema Your CSS rule to set width to 100% will not work:

`.contact-form #jform_contact_emailmsg {width: is 100%;}`

Please try this:

`.contact-form #jform_contact_emailmsg {width: 100%;}`

**Comment by JoomlaTema** [comment] 2020-04-19 17:26
My code is already like this `.contact-form #jform_contact_emailmsg {width: 100%;}` just mistyped above.

**Comment by gerryfrancis** [comment] 2020-04-19 17:37
@JoomlaTema Have you checked for `@media` queries that possibly overwrite your width size when browsing on small screens?

**Comment by chmst** [comment] 2020-04-20 13:26
I've just set up a fresh Joomla 3.9.16. All input fields have the same width.
So there must be something in your template - and override of the contact form or an override of a input field which causes a difference. 
You better ask in the forum. This is not a issue of Joomla 3.9

**Comment by alikon** [comment] 2020-04-20 13:56
closed as no core issue

**Closed as completed by alikon** 2020-04-20 13:56 UTC
Labels: No Code Attached Yet
