### ISSUE TITLE
Cannot upload images in articles after Joomla 4.2.4 update

### ISSUE THREAD

**Issue by Gideon-jouweb** [joomla/joomla-cms#39117] opened 2022-11-01 06:21 UTC
### Steps to reproduce the issue
Create new article. Go to Images & Links. No image upload functionality visible.

### Expected result
Able to upload images

### Actual result
No image uploader in article image upload

### System information (as much as possible)
Joomla 4.2.4![screen shot 2022-11-01 at 06 20 21](https://issues.joomla.org/uploads/1/85f3c74ef8943beb7b73a3813913901d.jpg)

### Additional comments
See attached

**Comment by Gideon-jouweb** [comment] 2022-11-01 07:02
I used Upload and update -  This happened with 2 sites. The sites where I used direct update did ot have this issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39117">issues.joomla.org/tracker/joomla-cms/39117</a>.</sub>

**Comment by crimle** [comment] 2022-11-01 09:03
Same issue here (on any of my 70 Joomla 4.3.4 websites). The buttons [Select] [Upload] [Delete] are missing. You can write path & filename of the image manually, but this is unbearable.
[screen shot 2022-11-01 at 09 03 33](https://issues.joomla.org/uploads/1/2a4d4558e0dba0312d4279b5f9f21af1.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39117">issues.joomla.org/tracker/joomla-cms/39117</a>.</sub>

**Comment by brianteeman** [comment] 2022-11-01 09:18
1. Are you using JCE? (I ask because it overrides the joomla functionality for this field)
2. Are there any errors in your browser console?

**Comment by Gideon-jouweb** [comment] 2022-11-01 09:30
Yes, I am using JCE. 
No, there are no errors.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39117">issues.joomla.org/tracker/joomla-cms/39117</a>.</sub>

**Comment by Gideon-jouweb** [comment] 2022-11-01 09:31
I just switched to the default editor and issue remains.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39117">issues.joomla.org/tracker/joomla-cms/39117</a>.</sub>

**Comment by richard67** [comment] 2022-11-01 09:39
> I just switched to the default editor and issue remains.
> 
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/39117](https://issues.joomla.org/tracker/joomla-cms/39117).

Maybe switching the editor is not enogh to get rid of the override. Could you try if uninstalling JCE and then installing it again helps? Or maybe JCE just needs an update?

**Comment by crimle** [comment] 2022-11-01 09:58
I can confirm that the issue has a relation to JCE 2.9.31. I re-installed the former version JCE 2.9.30 and the issue has gone.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39117">issues.joomla.org/tracker/joomla-cms/39117</a>.</sub>

**Comment by crimle** [comment] 2022-11-01 10:04
The issue has already been reported to Ryan. There is a JCE Pro 2.9.32 Beta 2 and the final JCE Pro 2.9.32 will probably be released soon. I think the issue here can be resolved.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39117">issues.joomla.org/tracker/joomla-cms/39117</a>.</sub>

**Comment by richard67** [comment] 2022-11-01 10:05
Closing as not a core issue. Thanks @crimle for reporting. @Gideon-jouweb Feel free to re-open this issue (or ping us here if you can't do that) if you think closing was wrong.

**Closed as completed by richard67** 2022-11-01 10:05 UTC
Labels: No Code Attached Yet
