### ISSUE TITLE
Cookie-based Redirect to 404s in language filter

### ISSUE THREAD

**Issue by andypillip** [joomla/joomla-cms#7047] opened 2015-05-27 10:20 UTC
#### Steps to reproduce the issue

Assuming a multi-language site with DE as default language and EN as secondary.

1. Activate SEF
2. Activate URL Rewriting
3. Activate Language Filter's _Remove URL Language Code_
4. Navigate to a German Menu item (f.e. ////ueber-uns.html)
5. Switch to English
6. Navigate back (in history, by means of back button)

#### Expected result

You should land on /ueber-uns.html in German.

#### Actual result

You get redirected to /en/ueber-uns.html instead, which results in a 404.

#### System information (as much as possible)

Joomla! 3.4.1 with everything up to date.

#### Additional comments

Another side effect is that after you switched to a language different to the default language once, following any links (f.e. on Google) to pages in the default language will result in a 404.

**Comment by infograf768** [comment] 2015-05-27 15:41
>Actual result

>You get redirected to /en/ueber-uns.html instead, which results in a 404.

I can't reproduce this issue (Firefox).

**Comment by infograf768** [comment] 2015-05-27 15:47
BTW, you should test on staging, not 3.4.1

**Comment by MyBookings** [comment] 2015-06-02 15:45
I can confirm this bug - having the exact same problem. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7047">issues.joomla.org/joomla-cms/7047</a>.</sub>

**Comment by ritsnuno** [comment] 2015-06-03 17:08
Hello, 
we have the exact same issue. In this case, we use English as default and we have Portuguese (PT) as the alternative. 

For example: if the default language for the user is Portuguese, the website will be in that language and, if the user clicks on an external link that goes to the default article language: www.ourwebsite.com/somearticle it tries to open with www.ourwebsite.com/pt/somearticle, which it doesn't exist because we created a portuguese alias for that same menu item and article (because of SEO).

Our Joomla is version 3.4.1, with the language filter on with: automatic language change; item associatios; remove URL language code; cookie session.

For translating, we are using Falang component.

**Comment by infograf768** [comment] 2015-06-04 07:28
Test can't be done with Falang, but with native core multingual feature.
If you use falang, please contact the falang developer.

**Comment by smz** [comment] 2015-06-27 00:18
Can you please test if after applying #7271 you still have this issue?

**Comment by smz** [comment] 2015-06-28 17:28
This has the `Language & Strings` label, but should probably have `Mult language` instead...

**Comment by zero-24** [comment] 2015-06-28 19:24
Fixed @smz <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7047">issues.joomla.org/joomla-cms/7047</a>.</sub>

**Comment by brianteeman** [comment] 2016-05-08 09:46
Hi you created this issue sometime ago but have not provided any code for people to evaluate. As no one else has shown any interest in providing the code and you have not then I am closing this issue at this time. If code is provided (a pull request) it can always be re-examined.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7047">issues.joomla.org/joomla-cms/7047</a>.</sub>

**Closed** 2016-05-08 09:47 UTC
Labels: No Code Attached Yet
