### ISSUE TITLE
[del 30862]

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#30862] opened 2020-10-02 07:01 UTC
[del]

**Comment by brianteeman** [comment] 2020-10-02 07:22
The sort order is alphabetical so it is expected that the order changes

**Comment by infograf768** [comment] 2020-10-02 07:24
Unrelated to RTL. Not a bug. Closing.

**Comment by gostn** [comment] 2020-10-02 07:24
thanks @brianteeman, closing

**Closed as completed by infograf768** 2020-10-02 07:24 UTC
Labels: No Code Attached Yet

**Comment by gostn** [comment] 2020-10-02 07:25
> ´article´, ´module´have same icon.

shouldn't this be solved?

**Comment by brianteeman** [comment] 2020-10-02 07:27
Yes

**Comment by infograf768** [comment] 2020-10-02 07:27
Please create a new issue for that.

**Comment by gostn** [comment] 2020-10-02 07:33
#30863
