### ISSUE TITLE
[4.0] Searchtools JS error

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#29060] opened 2020-05-14 06:59 UTC
### Steps to reproduce the issue

1. Installa fresh copy of J4 (without sample data)
2. Go to `administrator/index.php?option=com_content&view=articles`
3. You your browser console

**_Note:_** This also occurs on some other list views

### Expected result

No JS errors

### Actual result

> TypeError: e is null --- searchtools.min.js:1:6704

or in debug mode:

> TypeError: filteredByCaption is null --- searchtools.js:285:11

**Comment by infograf768** [comment] 2020-05-14 07:13
Can't reproduce Macintosh/Firefox

**Comment by C-Lodder** [comment] 2020-05-14 07:15
@infograf768 This was a fresh clone and installation of the J4 repo

**Comment by infograf768** [comment] 2020-05-14 07:22
This happens only when there are no articles.
When I install sample data, no more js error

This should help solving the issue.

**Comment by C-Lodder** [comment] 2020-05-14 07:23
Yeah just updated the test instructions

**Comment by infograf768** [comment] 2020-05-14 07:37
Can you check patching with this?
```
diff --git a/build/media_source/system/js/searchtools.es6.js b/build/media_source/system/js/searchtools.es6.js
index 1019da0..a61ac40 100644
--- a/build/media_source/system/js/searchtools.es6.js
+++ b/build/media_source/system/js/searchtools.es6.js
@@ -296,5 +296,7 @@
       if (activeFilterCount === 0) {
         const filteredByCaption = document.getElementById('filteredBy');
-        filteredByCaption.parentNode.removeChild(filteredByCaption);
+        if (filteredByCaption !== null) {
+          filteredByCaption.parentNode.removeChild(filteredByCaption);
+        }
       }
 ```

and run npm

**Comment by infograf768** [comment] 2020-05-14 07:50
Closing as PR https://github.com/joomla/joomla-cms/pull/29066

**Closed as completed by infograf768** 2020-05-14 07:50 UTC
Labels: No Code Attached Yet
