### ISSUE TITLE
[4.0] Vague 'An error has occurred.' error message from SqlField.

### ISSUE THREAD

**Issue by BrainforgeUK** [joomla/joomla-cms#36177] opened 2021-12-01 15:58 UTC
### Steps to reproduce the issue

Create a SqlField form item with an error - e.g mistype column name

### Expected result

Sensible error message

### Actual result

Vague 'An error has occurred.' error message

### Additional comments

Changing SqlField.php line 293 to include something like this would help:

'
			try
			{
				$items = $db->loadObjectList();
			}
			catch (ExecutionFailureException $e)
			{
				Factory::getApplication()->enqueueMessage(Text::_('JERROR_AN_ERROR_HAS_OCCURRED'), 'error');
				Factory::getApplication()->enqueueMessage($e->getMessage(), 'error');
				Factory::getApplication()->enqueueMessage($this->query->__toString(), 'error');
			}'

**Comment by zero-24** [comment] 2021-12-01 16:03
If anything a publication of the SQL query should be behind a JDEBUG check. It was an intention to not display information that are in the most cases not usefull to the people seeing it. The best case would be to put it into an log file and not into the public site.

**Comment by brianteeman** [comment] 2023-08-31 08:26
Closing as intended behaviour

**Closed as completed by brianteeman** 2023-08-31 08:26 UTC
Labels: No Code Attached Yet, bug
