### ISSUE TITLE
Toolbar buttons on IE 10 throwing JS error???

### ISSUE THREAD

**Issue by digitalgarage** [joomla/joomla-cms#5901] opened 2015-01-28 08:29 UTC
#### Steps to reproduce the issue

Not sure if this is just me or if others are getting the same thing.

Using the beta of 3.4 from github on a Windows 7 - IE 10 VM.  Go to Article Manager and click new.  

It should go to a new article but on IE 10 it appears to be throwing a JS error.  

![screen shot 2015-01-28 at 02 27 22](http://issues.joomla.org/uploads/1/f22788c9dca0d86dce7c70e9f35ce755.png)

Other versions seem unaffected.

#### Expected result

Expected result would be opening a new article in Article Manager

#### Actual result

Actual result is a JS error and nothing happens.

#### System information (as much as possible)

Latest J3.4 download from Github.

**Comment by losedk** [comment] 2015-01-28 09:48
Confirmed

**Comment by Fedik** [comment] 2015-01-28 11:28
looks like problem with `fireEvent` .. 
before it was by mootools, and as there no mootools anymore, IE use native one,

just a quick guess ... unfortunately I have no IE for check this theory

**Comment by Bakual** [comment] 2015-01-28 12:49
Tracked it down to commit https://github.com/joomla/joomla-cms/commit/68b58f3d5e7d76e580c2d8bb22305674b19b9d02 (PR https://github.com/joomla/joomla-cms/pull/4888)

Something for @dgt41 to look at.

**Comment by dgt41** [comment] 2015-01-28 13:23
@Bakual from a quick search I think this is more related to core.js
http://stackoverflow.com/questions/17720431/javascript-dispatchevent-is-not-working-in-ie9-and-ie10

I'll try to post a more descriptive answer and maybe a pr later on when I'll get back to my desk

**Comment by Bakual** [comment] 2015-01-28 13:51
I think the comment from Fedik is correct. `fireEvent` previously was provided by MooTools, it then broke because MooTools is no longer there due to your PR.

If you can do a PR to fix this, that would be awesome!

What I find disturbing is that apparently nobody tested creating any item on IE10 since about 2 months, including an alpha release. :disappointed:

**Comment by dgt41** [comment] 2015-01-28 15:10
This was the solution mootools used back to 2010:
http://jsbin.com/uvesu3/8/edit?js,output
Here is the talk:
https://mootools.lighthouseapp.com/projects/2706/tickets/976-resolve-fireevent-issues-with-ie9

This is the proposed code:
```javascript
	if (typeof HTMLElement != 'undefined') {
		HTMLElement.prototype.fireEvent = Element.prototype.fireEvent;
	}
```
After line 31 in core-uncompressed.js
The only problem I don’t have IE9 to test it 😕
@digitalgarage can you try this code with IE9?

**Comment by Fedik** [comment] 2015-01-28 17:21
please test #5914

**Comment by zero-24** [comment] 2015-01-28 17:22
Closing as we have a PR by @Fedik Thanks! https://github.com/joomla/joomla-cms/issues/5914<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5901">issues.joomla.org/joomla-cms/5901</a>.</sub>

**Closed by zero-24** 2015-01-28 17:22 UTC
Labels: No Code Attached Yet

**Comment by dgt41** [comment] 2015-01-28 17:49
@Fedik thanks!
