### ISSUE TITLE
After blocking user in BE you are logged out

### ISSUE THREAD

**Issue by kentanilsson** [joomla/joomla-cms#8237] opened 2015-11-02 10:13 UTC
#### Steps to reproduce the issue
Login to BE
Go to user list
Block one user , "Enabled" or "select" and use Block button

#### Expected result
Updated list

#### Actual result
Logged out from BE

#### System information (as much as possible)
Database Version	5.5.46-0ubuntu0.12.04.2
Database Collation	latin1_swedish_ci
PHP Version	5.5.30-1+deb.sury.org~precise+1
Web Server	Apache/2.4.12 (Ubuntu)
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 3.4.5 Stable [ Ember ] 22-October-2015 21:30 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/45.0.2454.101 Chrome/45.0.2454.101 Safari/537.36

**Comment by zero-24** [comment] 2015-11-02 10:30
I can not confirm this behavior on 3.4.5 or current 3.5.0-dev can you retest with a new admin session?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8237">issues.joomla.org/joomla-cms/8237</a>.</sub>

**Comment by infograf768** [comment] 2015-11-02 11:53
Also
"Database Collation latin1_swedish_ci"
is wrong. Should be utf8

**Comment by kentanilsson** [comment] 2015-11-02 15:06
Retested with a fresh admin session - new login. When setting the block status on the list is refreshed OK but setting it off I'm logged out.

**Comment by zero-24** [comment] 2015-11-02 15:09
Do you have any 3party plugin installed? Please disable them for testing.

**Comment by kentanilsson** [comment] 2015-11-02 15:32
Oh my - yes we have a lot , some 150 plugins in the list for that site I discovered the problem. Well , I have no time with that now. Tested on another site but that has similar plugins installed. Not working. And a third one with  limited plugins installed and that is working ok.

**Comment by brianteeman** [comment] 2015-11-02 15:35
So clearly the issue is with one of the plugins you have installed on the
two broken site and not installed on the one working site

On 2 November 2015 at 15:32, kentanilsson <notifications@github.com> wrote:

> Oh my - yes we have a lot , some 150 plugins in the list for that site I
> discovered the problem. Well , I have no time with that now. Tested on
> another site but that has similar plugins installed. Not working. And a
> third one with limited plugins installed and that is working ok.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/8237#issuecomment-153053656>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by kentanilsson** [comment] 2015-11-02 15:37
Yes , thank you - I realise that . It will take a while to filter that out.

**Comment by brianteeman** [comment] 2015-11-02 15:38
Closing as not joomla core

**Closed by brianteeman** 2015-11-02 15:38 UTC
Labels: No Code Attached Yet
