### ISSUE TITLE
[com_fields] Custom fields not shown in edit form, if Show Article Options is disabled

### ISSUE THREAD

**Issue by n3t** [joomla/joomla-cms#15473] opened 2017-04-22 02:06 UTC
### Steps to reproduce the issue
1. Define some custom fields for articles
2. Go to com_content configuration and disable option "Show Article Options" (set to No)
3. Edit any article

### Expected result
Custom fields page should be visible

### Actual result
Custom fields page is not visible

### Additional comments
IMO fields should be displayed, even when Options are hidden. Fields are not Options, it is more Content then options.

**Comment by franz-wohlkoenig** [comment] 2017-04-22 06:25
@n3t Confirmed: Set in "Articles: Options" > Tab "Editing Layout" "Show Article Options" to "Hide" and in Article Tab "Field" is also hidden.

**Comment by brianteeman** [comment] 2017-04-25 11:04
I can confirm this but I dont see where the code is for the fields to be injected - @laoneo can you point me in the right direction and I can have a go at fixing it

**Comment by n3t** [comment] 2017-04-25 13:59
Should be layout `joomla.edit.params` - condition  `if ($displayData->get('show_options', 1))`.
Value `show_options` is set in edit view of article.

There are two possible solutions IMO: 
- fieldset name `options` should be rendered separately, influenced by condition above, and all othe fieldsets in `foreach` cycle should not be influenced by the condition. 
- Or do not set `show_options` value but `ignore_fieldsets` in article edit view

**Comment by laoneo** [comment] 2017-04-26 05:47
@n3t has right. I think it doesn't sound like a easy one line fix. Needs some toughts. Basically it needs a different way of loading.

**Comment by Bakual** [comment] 2017-04-26 06:15
I think just adding the respective fieldsets to the `ignore_fieldsets` if "show_options" is set would actually be the correct way.
But the way it is currently done (the parameter is checked in the JLayout) I fear this isn't really possible to do in a B/C way. The intention of this parameter is to actually hide **all** options rendered by that JLayout, which includes fields.

**Comment by zero-24** [comment] 2017-04-26 08:18
> The intention of this parameter is to actually hide all options rendered by that JLayout, which includes fields.

But is this than not expected behavior? As the same is true for 3rd party extensions that adds tabs. If you disable that option they are not showed.

**Comment by brianteeman** [comment] 2017-04-26 08:22
@zero-24 the expected behaviour is that the tab called "Article Options" is controlled by that option and no other tab

**Comment by AlexRed** [comment] 2017-05-19 10:28
I can confirm the problem on Joomla! 3.7.2-Dev (nightly Build)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15473">issues.joomla.org/tracker/joomla-cms/15473</a>.</sub>

**Comment by franz-wohlkoenig** [comment] 2017-06-08 07:58
Struggled again about this Issue.

**Comment by laoneo** [comment] 2017-06-13 08:49
Can you guys please test #16661 carefully if there are no side effects. Because when this one gets in, only the fieldsets with the name basic are not loaded anymore.

**Comment by brianteeman** [comment] 2017-06-13 09:03
Closed as we have a pr for testing

**Closed by brianteeman** 2017-06-13 09:03 UTC
Labels: No Code Attached Yet
