### ISSUE TITLE
[Router][3.8.5] - Bug menu item aliases are renderable.

### ISSUE THREAD

**Issue by tonypartridge** [joomla/joomla-cms#19624] opened 2018-02-08 22:03 UTC
### Steps to reproduce the issue

Create Menu Structure as follows:

My Test - (Alias: my-test) Type: single article

My Primary Test (Alias: my-primary-test) Type: Menu Item Alias and Points to: My Test 

Access the My Primary Test via the frontend and you are redirected to my-test.html Perfecto. 

Access the Menu Item Alias via it's alias directly:

/my-primary-test.html

The above renders the article from My Test. It shouldn't it should redirect the user to my-test.html

I hope you can follow that!

**Comment by brianteeman** [comment] 2018-02-08 22:09
Cant confirm

**Comment by tonypartridge** [comment] 2018-02-08 22:18
Create a menu structure similar to the below, home and the about items are all that matter for this test. 
<img width="397" alt="screenshot 2018-02-08 22 15 57" src="https://user-images.githubusercontent.com/1400982/36001282-bddb9d50-0d1d-11e8-9f55-365aaa9da973.png">

Menu Item Alias is root and the article is a sub menu item.

About Single Article should only be accessible under:

/home/about

But if you access

/abouta

It renders the article from /home/about 

This happens with new and old router.

**Comment by csthomas** [comment] 2018-02-08 22:48
This is a duplicate of https://github.com/joomla/joomla-cms/issues/19340

**Comment by brianteeman** [comment] 2018-02-08 23:51
In my test they were both at the same level as per your original description.  Will test again in the morning.

**Closed as completed** 2018-02-11 00:26 UTC
Labels: No Code Attached Yet

**Comment by Quy** [comment] 2018-09-29 16:06
Please test PR #22432
