### ISSUE TITLE
update server outdated XML

### ISSUE THREAD

**Issue by Pawel-Panek** [joomla/joomla-cms#43643] opened 2024-06-11 14:41 UTC
The version numbers in https://update.joomla.org/core/nightlies/next_minor_list.xml and the links from https://update.joomla.org/core/nightlies/next_minor_extension.xml are no longer up to date with latest versions as published on https://developer.joomla.org/nightly-builds.html.

Please update the versioning and the package download links. Thanks.

**Comment by richard67** [comment] 2024-06-11 18:26
@Pawel-Panek Joomla 5.1 does not use these XML files anymore, it uses TUF (the update framework), and this can be checked here: https://update.joomla.org/cms/targets.json .

Furthermore, the version can never be the same as the nightlies as the latter are one the next dev version. E.g. for 5.1 the latest release was 5.1.1 and the nightlies for 5.1 have 5.1.2-dev.

**Comment by richard67** [comment] 2024-06-11 18:27
Closing as expected behaviour due to the reasons stated in my previous comment. Feel free to reopen this issue or ask us to do it if you think this is wrong.

**Comment by brianteeman** [comment] 2024-06-11 18:40
@richard67 this is referring to the nightlies which Cloud Access provides access to on their joomla platform
https://update.joomla.org/cms/targets.json   does not have any information for the nightly builds

**Comment by brianteeman** [comment] 2024-06-11 18:49
Not trying to be obtuse here but that is not correct, If it was correct then this line should not be present in the nightly build xml

**https://update.joomla.org/core/nightlies/next_minor_list.xml**
`<extension name="Joomla" element="joomla" type="file" version="5.1.1-dev" targetplatformversion="5.0" detailsurl="https://update.joomla.org/core/nightlies/next_minor_extension.xml"/>`

**https://update.joomla.org/core/nightlies/next_minor_extension.xml**
```
<update>
<name>Joomla! 5.1 Nightly Build</name>
<description>Joomla! CMS</description>
<element>joomla</element>
<type>file</type>
<version>5.1.1-dev</version>
<infourl title="Joomla! Nightly Builds">https://developer.joomla.org/nightly-builds.html</infourl>
<downloads>
<downloadurl type="full" format="zip">https://developer.joomla.org/nightlies/Joomla_5.1.1-dev-Development-Update_Package.zip</downloadurl>
</downloads>
<tags>
<tag>stable</tag>
</tags>
<supported_databases mysql="8.0.13" mariadb="10.4" postgresql="12.0"/>
<php_minimum>8.1.0</php_minimum>
<maintainer>Joomla! Production Department</maintainer>
<maintainerurl>https://www.joomla.org</maintainerurl>
<targetplatform name="joomla" version="5.[0]"/>
</update>
```

If these entries are incorrect then they should be removed

How is @Pawel-Panek and others supposed to get the nightly packages

**Comment by richard67** [comment] 2024-06-11 18:52
I see. The nightlies XML are indeed outdated => @LadySolveig @bembelimen Could you check?

**Comment by richard67** [comment] 2024-06-11 18:54
Maybe the issue should reported there: https://github.com/joomla/update.joomla.org/issues

**Comment by Pawel-Panek** [comment] 2024-06-14 06:46
@richard67 please feel free to close the issue here and reopen in update.joomla.org repo.

@brianteeman thank you for picking up on this. This is exactly what we need. Our systems try to follow up on version changes but we need to have a reliable source of information about new packages. 

One issue with next_mirror_list.xml is that it doesn't mention 4.4.6 so we can't deploy this package.

The other is with 5.x branch. We also would like to have a way to download -dev versions, like 5.1.2-dev which isn't linked in https://update.joomla.org/cms/targets.json .

**Comment by richard67** [comment] 2024-06-16 13:26
I've made a pull request with one possible way to fix it: https://github.com/joomla/update.joomla.org/pull/365

If that PR gets accepted as it is, you would have to use "next_patch_list.xml" instead of "next_minor_list.xml" for getting the 4.4.6-dev and 5.1.2-dev nightlies. For the 5.2 nightlies you would use "next_minor_list.xml", and for the 6.0 nightlies you would use "next_major_list.xml".

@Pawel-Panek Could you work with that?

**Comment by Pawel-Panek** [comment] 2024-06-17 17:39
Yes, that looks good. Thank you!

**Comment by richard67** [comment] 2024-06-17 17:54
The PR for the nightly build update site XML has been merged meanwhile. Now it needs a final step to make the URLs show up on https://developer.joomla.org/nightly-builds.html . I‘ve pinged someone who can do that.

**Comment by Pawel-Panek** [comment] 2024-07-17 07:02
Please update https://update.joomla.org/core/nightlies/next_patch_extension.xml with URL for 5.1.3-dev download.

On this list https://update.joomla.org/core/nightlies/next_patch_list.xml we can see 5.1.3-dev but it's not present in next_patch_extension.

**Comment by LadySolveig** [comment] 2024-07-17 08:52
Thank you for reporting again @Pawel-Panek 💚 Prepared PR https://github.com/joomla/update.joomla.org/pull/374

**Comment by Quy** [comment] 2024-10-18 16:51
OK to close?

**Comment by richard67** [comment] 2024-10-26 16:20
Solved with https://github.com/joomla/developer.joomla.org/pull/55 and https://github.com/joomla/update.joomla.org/pull/383 .

Now the custom update URLs are shown at https://developer.joomla.org/nightly-builds.html as follows:
- Next patch is for updating to 4.4 and 5.2 nightlies.
- Next minor is for updating to 5.3 nightlies.
- Next major is for updating to 6.0 nightlies.

**Closed as completed by richard67** 2024-10-26 16:20 UTC
Labels: No Code Attached Yet
