### ISSUE TITLE
Login after Logout not work

### ISSUE THREAD

**Issue by widmann-it** [joomla/joomla-cms#11169] opened 2016-07-18 05:51 UTC
Since 3. 6 there are problems with the Login again.
#### Actual result
Action:
Users in the Frontend announcing and again Cancel, the user once more Announce and there comes the announcement "The inquiry was rejected, because the Sicherheitstoken is invalid. Please, update the side and then try it once more. " earlier it was thus one with F5 a de side new store was able, now this is not any more Mglich, moreover one must close the browser or extinguish the Cachespeicher of the browser. 

#### System information (as much as possible)
Linux  2.6.32-042stab113.11 #1 SMP Fri Dec 18 17:32:04 MSK 2015 x86_64
Datenbankversion 	5.5.49-0ubuntu0.12.04.1
Datenbankzeichensatz 	utf8_general_ci
Datenbankverbindungszeichensatz 	utf8mb4_general_ci
PHP-Version 	7.0.8
Webserver 	Apache
PHP-Interface für den Webserver 	cgi-fcgi
Joomla!-Version 	Joomla! 3.6.0 Stable [ Noether ] 12-July-2016 21:14 GMT
Joomla!-Plattform-Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
Browsererkennung 	Mozilla/5.0 (Windows NT 10.0; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0

**Comment by bertmert** [comment] 2016-07-18 06:35
Joomla 3.6.0
Confirmed.
Frontend. Logged in as SuperUser via login module. Logged out without further actions.
Tried to log in again
```
Warning
Your session has expired. Please log in again.
```
Tried to log in again > success.

**Comment by sovainfo** [comment] 2016-07-18 07:26
Can't reproduce. Suggest to check other tabs. After the refresh it is possible to login again. No need for closing browser.

Note: Not using any browser caching other than from the browser itself. Not using any server caching!

**Comment by andrepereiradasilva** [comment] 2016-07-18 07:45
Confirmed.

**Comment by infograf768** [comment] 2016-07-18 08:30
Please test using staging as there was an issue with logout, now solved in staging.

**Comment by bertmert** [comment] 2016-07-18 21:57
> Please test using staging as there was an issue with logout, now solved in staging.

Solves this issue here, too.

**Comment by infograf768** [comment] 2016-07-19 05:46
@widmann-it 
Can you confirm so that we close this Issue?

**Comment by widmann-it** [comment] 2016-07-26 06:02
Hello, can continue to duplicate the problem. It does not matter which browser (Firefox, Chrome, IE) is used. Once the user wants to log in and log out again he gets the message with the session ID. The problem bewteht not only with the 3.6 I am already stumbled several times over. Only this time, it is so that the system can be used not at all more. And the detour via the reload of the browser can indeed be no solution.

**Comment by brianteeman** [comment] 2016-07-28 14:02
@widmann-it did you test with the latest staging as requested?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11169">issues.joomla.org/joomla-cms/11169</a>.</sub>

**Comment by widmann-it** [comment] 2016-08-03 04:34
Yes, is not work, when the Systemcache is the same problem as before

**Comment by widmann-it** [comment] 2016-08-03 04:39
Testet by 3.6.1 RC2

**Comment by widmann-it** [comment] 2016-08-04 19:36
Testet by 3.6.1 
Once the cache function is enabled, the message comes with the token

**Comment by brianteeman** [comment] 2016-08-04 20:06
@widmann-it can you please confirm if you can replicate this with a clean install of joomla with no extensions and a default template

**Comment by falzueta** [comment] 2016-08-04 21:37
Confirmed in 3.6.0
Solved with 3.6.1 upgrade<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11169">issues.joomla.org/joomla-cms/11169</a>.</sub>

**Comment by brianteeman** [comment] 2016-08-05 15:31
I am closing this for the same reason as #11307<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11169">issues.joomla.org/joomla-cms/11169</a>.</sub>

**Closed** 2016-08-05 15:31 UTC
Labels: No Code Attached Yet
