### ISSUE TITLE
Tags - Popular Module is broken on multilingual sites

### ISSUE THREAD

**Issue by JoeJoomla** [joomla/joomla-cms#12919] opened 2016-11-17 02:56 UTC
### Steps to reproduce the issue
Create tags in Tag Component in multiple languages
Create Articles with tags on a multilingual site
Create Tags - Popular modules for each language and assign to appropriate menu items

### Expected result
In the case of a multilingual site, English & French, when you switch between the languages the module should display English tags for the English language and French tags for the French language.

### Actual result
In the multilingual site both English and French modules are displaying all tags regardless of the language ignoring the language assignments.

### System information (as much as possible)
Joomla 3.6.4
DB version 5.6.33
PHP 5.6.27

**Comment by infograf768** [comment] 2016-11-17 05:55
com_tags has a specific parameter for that. You have to set it to `Current` for filtering to work.
![screen shot 2016-11-17 at 06 54 27](https://cloud.githubusercontent.com/assets/869724/20377882/cf8c743a-ac92-11e6-823f-6babddc18bc0.png)

**Comment by JoeJoomla** [comment] 2016-11-17 14:59
Thank you infograf768,
You are correct, I didn't know about that parameter setting.
Switching to 'Current' does make the tag menu links switch correctly in the module now.
I have an issue with the links, they all give me a 404 but I suppose this is a different issue.

**Comment by Bakual** [comment] 2016-11-17 15:08
Closing as the issue is solved.

**Closed by Bakual** 2016-11-17 15:08 UTC
Labels: No Code Attached Yet

**Comment by jatitoam** [comment] 2016-11-17 15:56
Hi guys and sorry for insisting on a closed issue.

Joe asked me about this a couple days ago and I really thought it was a bug, and even if there's a way to make it work I still think it's a usability bug since it doesn't work just as the other modules where language filter works out of the box.

Would it be acceptable of I send a PR to make it work like that?  Only talking about the language parameter.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12919">issues.joomla.org/tracker/joomla-cms/12919</a>.</sub>

**Comment by Bakual** [comment] 2016-11-17 18:08
It would have to be backward compatible, meaning the behavior has to be the same as today and only optionally do the new behavior.
Since you already can do that optionally, there is probably no point doing a PR.
You cna do one for 4.0 to change behavior.

**Comment by jatitoam** [comment] 2016-11-17 20:49
I definitely understand backwards behavior, however I need to insist about usability, and I have one last proposal for considering both:

1. Adding a "Enable language filter" (separate) option
2. Make it default "no" for current Joomla installations that are just being updated
3. Make it default "yes" for new Joomla installations<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12919">issues.joomla.org/tracker/joomla-cms/12919</a>.</sub>

**Comment by andrepereiradasilva** [comment] 2016-11-17 20:54
as @Bakual said PR are welcomed.
- For 3.x branch (staging) you MUST to respect B/C
- For 4.x branch (4.0-dev) you should try to respect B/C (as possible)

**Comment by infograf768** [comment] 2016-11-18 07:08
> Make it default "no" for current Joomla installations that are just being updated

That would not be B/C

**Comment by Bakual** [comment] 2016-11-18 07:18
Why adding a separate parameter that does exactly the same thing as the "Current" option in the existing parameter?
If you want to make it more intuitive for users, just remove the current parameter for 4.0 and let it always filter by the current language.

**Comment by jatitoam** [comment] 2016-11-18 12:02
You are right, on a second thought a second parameter will be misleading, I was just assuming that the current one did more than just language filtering.

My point here is that the parameter is very hidden and it's causing a UX issue for the whole com_tags because it behaves totally the opposite way as the other Joomla components and modules.

So if we left the current selection for current installs ("All") - to avoid breaking B/C, and set a new selection for new installs ("Current") at least we could fix the component without having to wait until 4.0.

**Comment by brianteeman** [comment] 2016-11-18 12:09
Maybe it can be solved by modifying and clarifying the text?

**Comment by jatitoam** [comment] 2016-11-18 12:10
The text is not so confusing, but the default behavior is (in combination with a very hidden option).
It's not a critical issue I admit, but just a point where we could improve.
