### ISSUE TITLE
[j5.1] Excluding Menu entries from Cache not possible

### ISSUE THREAD

**Issue by GabeTheApe** [joomla/joomla-cms#43337] opened 2024-04-23 09:46 UTC
### Steps to reproduce the issue
System Configuration > System
- set cache to "on - advanced caching"

Article
- create an Article

Menu
- create Menu Entry with created Article

Plugins System - Pagecache
- add Menu entry in the list of "exclude Menu entries"

call page

change Article content

call or reload page again
### Expected result
the page should load the new content

### Actual result
the page still loades the old content or the cache needs to be cleared.

### System information (as much as possible)
Joomla 5.1

### Additional comments
Some Articles need to be excluded from the Cache, because they have varying content.

**Comment by richard67** [comment] 2024-04-23 14:01
@joomdonation Could that be fixed in a similar way as you did with PR #42871 for the exclude URLs?

**Comment by joomdonation** [comment] 2024-04-23 14:29
@richard67 To be able to give an understandable explanation, I would have to read the code again. But the short answer is No, this could not be fixed in the similar way with the other PR I did (that PR fixed a bug in System - Page Cache plugin, but there is no bug in that plugin related to this issue)

Basically, the System Cache (cache is set to on - advanced caching under Global Configuration) is not aware of  (or not depend on) the settings from System - Page Cache plugin.

What's happening here is that the page is not being cached by System - Page Cache plugin when the menu item is excluded (that's why I said there is no bug earlier). But Joomla has another tier of caching when the page is displayed - handled in display method of DisplayController,  independent with System - Page Cache plugin. That's why the cached content is still  being displayed for this case.

This might be a won't fix issue. I wonder if you still need to turn on System - Cache when the System - Page Cache is already in used? The whole page is cached already, so look like by enabling both, we have cache on cache.

**Comment by brianteeman** [comment] 2024-04-23 16:19
> This might be a won't fix issue.

We should just kill the cache plugin. It works as intended but not as users expect. Resulting in confusion and complaints

**Comment by Hackwar** [comment] 2024-04-26 18:17
The caching in the global configuration is a different caching than the page cache plugin. The page cache plugin is a vastly more agressive caching and only usefull for static websites. As Brian wrote, this is working as intended, even though not as expected, and is not a bug.

**Closed as completed by Hackwar** 2024-04-26 18:17 UTC
Labels: No Code Attached Yet
