### ISSUE TITLE
Error 404 page

### ISSUE THREAD

**Issue by rgmears** [joomla/joomla-cms#10091] opened 2016-04-25 19:17 UTC
#### Steps to reproduce the issue
Create a Custom Module. Assign it to "footer" position in Protostar template.

Add an image. 

Mis-type a URL > go to Error 404 page.

#### Expected result
The image should display. 

#### Actual result
But it doesn't.

#### System information (as much as possible)
Joomla 3.5.1, Protostar template

#### Additional comments
If, in Firebug, you add ../ before the image code the image displays.

**Comment by brianteeman** [comment] 2016-04-25 19:21
Can not confirm - I did exactly what you said with an image from /images in the footer position
![screen shot 2016-04-25 at 14 21 48](https://issues.joomla.org/uploads/1/752ae689f7f4c7308901bb36bf932392.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10091">issues.joomla.org/joomla-cms/10091</a>.</sub>

**Comment by rgmears** [comment] 2016-04-25 20:30
I have two sites with identical error.php files. One does what yours does @brianteeman. The other looks like this:
![Uploading Error_page_no_image.png…]()

**Comment by brianteeman** [comment] 2016-04-25 20:35
I would start by looking to see what is different between the two sites. But as even you cannot reproduce it 100% i am closing this as not a bug and suggesting you use the forum for support

**Closed by brianteeman** 2016-04-25 20:35 UTC

**Comment by rgmears** [comment] 2016-04-25 20:57
Okay. Any idea why I cannot upload an image on this site?

I fudged it with CSS. Two images; one displays the other doesn't depending on the page.
