### ISSUE TITLE
Menu Item for Logout redirects to wrong url if joomla is installed in subfolder

### ISSUE THREAD

**Issue by ahahu** [joomla/joomla-cms#39887] opened 2023-02-18 18:40 UTC
### Steps to reproduce the issue
- Run Joomla instance in subfolder "/joomla"
- Create menu items of type "Login" and "Logout"
- Set "Logout Redirection Page" to any public page of your site
- Open the frontend on "https://yoursite.com/login.html and login to the frontend
- Click menu item "Logout"

### Expected result
Logout should be successful and redirect to the selected logout redirection page 
The /logout.html should redirect to something like /index.php?option=com_users&task=user.logout....&return=...

### Actual result
the logout.html redirects to /joomla/index.php?option=com_users&task=user.logout....&return=... which results in a 404 because the /joomla prefix should not be there
The user is not logged out

### System information (as much as possible)
Joomla 4.2.8, PHP 8.0.27
Linux ms11720 3.10.0-1160.62.1.el7.x86_64 #1 SMP Tue Apr 5 16:57:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Shared Hoster

### Additional comments
I was able to fix this by changing the setRedirect in function menuLogout in file joomla/components/com_users/src/Controller/UserController.php from:
`        $this->setRedirect('index.php?option=com_users&task=user.logout&' . Session::getFormToken() . '=1&return=' . base64_encode($url));
`
to this
`
        $this->setRedirect(Route::_('index.php?option=com_users&task=user.logout&' . Session::getFormToken() . '=1&return=' . base64_encode($url), false));
`

**Comment by brianteeman** [comment] 2023-02-18 18:42
> Set RewriteBase to "/joomla" in .htaccess file in folder /joomla

that was wrong and not needed

**Comment by ahahu** [comment] 2023-02-18 20:05
Ok, I was just stating how the site is setup. I removed the RewriteBase and the error is still the same. So I removed this step in the reproduction description.

**Comment by brianteeman** [comment] 2023-02-18 20:24
Your problem is that you have installed joomla in a subdirectory but you have the domain name pointing to the parent folder.

Either move the installation to the parent folder or change the server config to point to the correct folder and not to the parent

**Comment by joomdonation** [comment] 2023-02-19 05:22
I could not re-procedure the issue on my local installation where Joomla is running on a sub-folder, too. However, while it could be wrong setup, we should still use `Route::_` to get the redirect URL. Ping @Hackwar for taking a look.

**Comment by brianteeman** [comment] 2023-02-22 22:45
@joomdonation it seems that its about 50/50 the usage of `Route::_` with setRedirect

**Comment by joomdonation** [comment] 2024-02-24 11:28
Just checked again and found that the Route::_ call is already applied to the URL, see https://github.com/joomla/joomla-cms/blob/4.4-dev/components/com_users/src/Controller/UserController.php#L206, so the issue is fixed now. I'm closing this.

**Closed as completed by joomdonation** 2024-02-24 11:28 UTC
Labels: No Code Attached Yet, bug
