### ISSUE TITLE
srcset problem

### ISSUE THREAD

**Issue by hotthemes** [joomla/joomla-cms#17988] opened 2017-09-19 16:12 UTC
### Steps to reproduce the issue
`$template_path = $this->baseurl.'/templates/'.$this->template;
<img src="<?php echo $template_path."/images/image.png" srcset="<?php $template_path."/images/image@2x.png 2x" alt="">`

### Expected result
`<img src="/joomla/templates/my_template/images/image.png" srcset="/joomla/templates/my_template/images/image@2x.png 2x" alt="">`

### Actual result (wrong path for srcset)
`<img src="/joomla/templates/my_template/images/image.png" srcset="//joomla/joomla/templates/my_template/images/image@2x.png 2x" alt="">`

### System information (as much as possible)
Attached[systeminfo-2017-09-19T18-07-30+02-00.txt](https://issues.joomla.org/uploads/1/ae68bd4e020781f8b4d4700a2c133b71.txt)

**Comment by mbabker** [comment] 2017-09-19 16:13
Duplicate of https://github.com/joomla/joomla-cms/pull/17978

**Closed as completed by mbabker** 2017-09-19 16:13 UTC
Labels: No Code Attached Yet

**Comment by hotthemes** [comment] 2017-09-19 16:15
I don't know how to add code here (!) but HTML output for srcset has Joomla base url included twice.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17988">issues.joomla.org/tracker/joomla-cms/17988</a>.</sub>
