### ISSUE TITLE
Joomla 3.6.0. New menu item 'Unpublished' icon remains sticky if specific language is selected when creating menu item.

### ISSUE THREAD

**Issue by Gitjk** [joomla/joomla-cms#11148] opened 2016-07-15 18:21 UTC
#### Steps to reproduce the issue
Within a bilingual/multilingual site create a new menu and add a new menu item with one of the available languages selected. Set it to 'Published'. Save the menu item. In the 'Menu Items' list, the status of the menu item shows as 'unpublished' and clicking it doesn't change it's status, but the message says "1 menu item successfully published."

Afterwards, when you edit the menu item again, select 'All' from the language drop-down and save it again, the green 'published' icon shows correctly and clicking it changes it's status normal.

#### Expected result
Green 'published' icon after the first 'Save'

#### Actual result
Red sticky 'unpublished' icon after the first 'Save'

#### System information (as much as possible)
Joomla 3.6.0
Database Version 	5.5.36
Database Collation 	utf8_general_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	5.4.27
Web Server 	Apache/2.4.9 (Win32) OpenSSL/0.9.8y PHP/5.4.27 
Firefox: 47.0.0.1

**Comment by infograf768** [comment] 2016-07-17 06:50
Can't reproduce the issue here

**Comment by brianteeman** [comment] 2016-08-03 19:08
Unable to reproduce

@Gitjk are you still having this problem?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11148">issues.joomla.org/joomla-cms/11148</a>.</sub>

**Comment by Gitjk** [comment] 2016-08-03 20:05
Sorry, I have postponed to try a few more tests because other things have had priority. Will try to look at this again tomorrow. If I don't supply additional information by the end of this week, just close the topic.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11148">issues.joomla.org/joomla-cms/11148</a>.</sub>

**Comment by Gitjk** [comment] 2016-08-04 21:46
Hmm, today I can't reproduce the above issue either. When I wrote the above, it was reproducible with every attempt to add a menu item.
I have no clue what might have caused the issue.

Please close this one for now.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11148">issues.joomla.org/joomla-cms/11148</a>.</sub>

**Comment by brianteeman** [comment] 2016-08-04 21:48
Ok Closing as requested<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11148">issues.joomla.org/joomla-cms/11148</a>.</sub>

**Closed** 2016-08-04 21:48 UTC
Labels: No Code Attached Yet
