### ISSUE TITLE
Number of visitors is abnormally high after an update to 3.8.4

### ISSUE THREAD

**Issue by hannes01** [joomla/joomla-cms#19511] opened 2018-02-01 08:31 UTC
### Steps to reproduce the issue
Update Joomla to 3.8.4
Check the number of visitors.

### Actual result
The number of visitors is abnormally high. 
For example it shows 34 000 visitors, although there are 10 visitors based on Google Analytics.

### System information (as much as possible)
Joomla 3.8.4
PHP 7.0

### Additional comments
Received an error message after the update:

![screen shot 2018-02-01 at 08 28 42](https://issues.joomla.org/uploads/1/53472fdf44627a4b46a843a5b46a2e2f.jpg)

Disabling cache did not change the situation.

Thread in Joomla forum: https://forum.joomla.org/viewtopic.php?p=3511468#p3511468

Thank you.

**Comment by ghost** [comment] 2018-02-01 08:45
Thanks @hannes01 for reporting and Link to Forum-Thread.

**Comment by joomdonation** [comment] 2018-02-01 08:47
Could you please access to System - Global Configuration, look at System tab, check to see what's the value of Session Handle? If it is Database, then it might related to this PR https://github.com/joomla/joomla-cms/pull/19165/

**Comment by hannes01** [comment] 2018-02-01 08:49
Hi,

thanks for the answer. Currently the Session Handler is PHP:

![screen shot 2018-02-01 at 08 49 42](https://issues.joomla.org/uploads/1/960b8d67061221a388a0830c47024e36.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19511">issues.joomla.org/tracker/joomla-cms/19511</a>.</sub>

**Comment by central4all** [comment] 2018-02-01 08:54
I have the same / similar problem with members,
After updating to version 3.8.4. since then the users online module is malfunctioning,
it shows 2 or 3 times more logged users than what it was before.
I tried to change Session Lifetime nothing changed,
Session Handler is DB , i changed it to PHP and again back to DB because nothing change again


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19511">issues.joomla.org/tracker/joomla-cms/19511</a>.</sub>

**Comment by joomdonation** [comment] 2018-02-01 08:55
Try to look at this line https://github.com/joomla/joomla-cms/blob/staging/libraries/src/Application/CMSApplication.php#L160 from your Joomla installation, change 5 to 2, then check it again

That's the only change from 3.8.3 to 3.8.4 I know could cause this issue

**Comment by joomdonation** [comment] 2018-02-01 08:56
To be more clear, change the code in that line from

```php
if ($handler !== 'database' && $time % 5 === 0)
```
To
```php
if ($handler !== 'database' && $time % 2 === 0)
```

**Comment by hannes01** [comment] 2018-02-01 09:03
Thank you for the suggestion. I changed the code but unfortunately it did not fix it.

**Comment by joomdonation** [comment] 2018-02-01 09:06
Did you also change Session Lifetime after update? 60 is a high value, maybe change it to a lower number like 15 would help

**Comment by mbabker** [comment] 2018-02-01 09:13
1) As noted in the merged pull request, this is the trade off of the performance fix put in place to keep this query from being arbitrarily executed on every even numbered second.

2) If you are really reliant on these modules reporting accurate numbers, you will need a cron job to force garbage collection of expired metadata and/or sessions.  With the referenced pull request applied this cleanup will not run at all when using the database handler because of the mixed storage/purpose of the session table and the frequency of cleanup when other handlers are in use is reduced from once every 2 seconds to once every 5 seconds (in effect, you go from running this query a max of 30 times per minute to 12 times per minute).

**Comment by hannes01** [comment] 2018-02-01 09:28
Thank you. No, the session lifetime is the same as before. It was increased to 60 about a year ago, because members of the site complained about a too short session... I just tried with 20, but the issue remains...

I'm sorry mbabker, as English is not my first language and I'm not a developer, this information is a bit confusing for me :) You are saying that I should create a cron job? I know how to create one in Cpanel but unfortunately I can't come up with a command.

**Comment by central4all** [comment] 2018-02-01 10:13
I am like you hannes,
none of these is helpful

**Comment by sandewt** [comment] 2018-02-01 11:38
I have checked the number of guests at this moment on my site.
There is a huge increase !!!
So I can confirm this issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19511">issues.joomla.org/tracker/joomla-cms/19511</a>.</sub>

I use the DATABASE  session handler !!!

**Comment by joomdonation** [comment] 2018-02-01 11:56
@mbabker Is **onAfterResponse** a correct event trigger? Look like a typo, **onAfterRespond** is correct event trigger

Could someone please change this line https://github.com/joomla/joomla-cms/blob/staging/libraries/src/Application/CMSApplication.php#L163 to

'onAfterRespond',

Then check to see whether the issue sorted?

**Comment by joomdonation** [comment] 2018-02-01 12:21
Please test PR https://github.com/joomla/joomla-cms/pull/19514 . It should fix this issue

**Comment by hannes01** [comment] 2018-02-01 12:34
Hello,

thanks! I tried it and the counter went from 35 000 to 1500. This can actually be a realistic number as I stated a Facebook campaign and it reflects the number visitors within 1 hour.
I will keep an eye on it, but indeed it seems to be fixed now.

Can others confirm?

**Comment by central4all** [comment] 2018-02-01 13:12
mine is already  'onAfterResponse',   
but is not working

**Comment by central4all** [comment] 2018-02-01 13:13
respond instead of responce ?
is this the error ?

**Comment by joomdonation** [comment] 2018-02-01 13:24
Change from **onAfterResponse** to **onAfterRespond**

**Comment by central4all** [comment] 2018-02-01 13:36
@i did it but nothing look fixed,
i have problem with number of users not with the visitors.
Maybe another typo ?

https://image.prntscr.com/image/99vT7QW0QAW_FzxEtm6zPA.png

**Comment by Quy** [comment] 2018-02-01 15:45
See PR #19514.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19511">issues.joomla.org/tracker/joomla-cms/19511</a>.</sub>

**Closed as completed by Quy** 2018-02-01 15:45 UTC
Labels: No Code Attached Yet

**Comment by csthomas** [comment] 2018-02-01 18:12
For DB session garbage collection may not be called at all.

See http://php.net/manual/pl/session.configuration.php#115842

You can check that by putting that code in your template index.php.
```
<?= ini_get('session.gc_probability'); ?>
```

If `ini_get('session.gc_probability');` is equal to 0 then php won't clear your database table `#__session`.

**Comment by timstohr** [comment] 2018-02-16 16:24
Hi Tuan and others, having the same problem. My user session table has grown to a staggering 700 Mb with 66.000 entries. The logged in users have gone from at maximum 100 simultaneously logged in to 1000 and growing. The admins who are logged in are now over 20 even though there is only one admin account. Anything to do about it?

**Comment by ghost** [comment] 2018-02-16 17:35
@timstohr please look at #19548 #19585

**Comment by Quy** [comment] 2018-02-16 17:37
@timstohr Please test #19687
