### ISSUE TITLE
Portuguese, Portugal - Translation for Joomla 5.x  missing in install languages

### ISSUE THREAD

**Issue by Pinkeltje** [joomla/joomla-cms#44124] opened 2024-09-22 06:50 UTC
### Steps to reproduce the issue
Go to Install languages, search for Portuguese

### Expected result

Portuguese, Portugal
Portuguese, Brazil 

### Actual result
Only Portuguese, Brazil  is shown

### Additional comments
Not found in [https://update.joomla.org/language/translationlist_5.xml](url)

**Comment by brianteeman** [comment] 2024-09-22 10:19
Unfortunately there is no Portuguese,Portugal language pack for Joomla 5

cc @tecpromotion

**Comment by Pinkeltje** [comment] 2024-09-22 15:44
@brianteeman sorry? It can be downloaded from joomla.org
![Screenshot_20240922_174253_Firefox](https://github.com/user-attachments/assets/8f0a7948-e8c8-431d-b97a-30d803024c32)

**Comment by brianteeman** [comment] 2024-09-22 15:59
Did you click on that link?

**Comment by Pinkeltje** [comment] 2024-09-22 16:39
Ok. See it now.

**Comment by fgsw** [comment] 2024-09-23 04:44
@Pinkeltje If the issue is solved, close it.

**Closed as not planned** 2024-09-23 05:23 UTC
Labels: No Code Attached Yet
