### ISSUE TITLE
Can't install Joomla 3.5.0 beta4

### ISSUE THREAD

**Issue by stellainformatica** [joomla/joomla-cms#9326] opened 2016-03-07 09:37 UTC
#### Steps to reproduce the issue
Start the installation process of a Joomla 3.5.0 beta4

#### Expected result
Installation successful

#### Actual result
Installation stops at step 2 Database
I click on the Next button but the screen remain the same, doesn't go to the step 3

#### System information (as much as possible)
I've tested in localhost:
Versione PHP 	5.4.25 
Mysql 	5.5.36 
Web Server 	Apache/2.4.7

**Comment by AlexRed** [comment] 2016-03-07 09:41
I can confirm the problem, 
I can't install Joomla 3.5 Beta4

PHP 5.5.15
MySQL 5.6.20
Apache/2.4.10<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9326">issues.joomla.org/joomla-cms/9326</a>.</sub>

**Comment by ot2sen** [comment] 2016-03-07 09:55
Worked fine here.
Successfully installed the 3.5 beta 4 earlier today (used the zip download)

PHP 7.0.3
MySQL 5.6.28

**Comment by wilsonge** [comment] 2016-03-07 10:07
Guys can you just confirm are you updating via Extension Manager or via Joomla Update (Testing Channel). I'm aware of some 500 errors when updating through Extension Manager - which I'm investigating - am not aware of anything with Joomla Update

**Comment by stellainformatica** [comment] 2016-03-07 10:07
I tested with the tar.gz, but also with the zip I have the same problem<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9326">issues.joomla.org/joomla-cms/9326</a>.</sub>

**Comment by stellainformatica** [comment] 2016-03-07 10:09
Hi wilsonge, the tracker is a about a fresh new install, not an update.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9326">issues.joomla.org/joomla-cms/9326</a>.</sub>

**Comment by andrepereiradasilva** [comment] 2016-03-07 10:24
i think this is for a clean install of 3.5.0 beta4

**Comment by wilsonge** [comment] 2016-03-07 11:30
Ty. I could do it when i packed the beta last night - but will try and set up something with your PHP/MySQL configuration and see what I can do!

**Comment by andrepereiradasilva** [comment] 2016-03-07 11:43
i used latest staging and installed correctly.

Database Version	5.5.5-10.0.24-MariaDB
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	5.6.18

Note that if i don't have a database created before install, the install process blocked at step 2.
But if we have a database created before install and use it on install it worked fine.

@stellainformatica @AlexRed did you create a new database on install or do you have it created before?

**Comment by brianteeman** [comment] 2016-03-07 11:45
YES that is a change with 3.5beta4 - you must have a database already
created

On 7 March 2016 at 11:43, andrepereiradasilva <notifications@github.com>
wrote:

> i used latest staging and installed correctly.
>
> Database Version 5.5.5-10.0.24-MariaDB
> Database Collation utf8_general_ci
> Database Connection Collation utf8mb4_general_ci
> PHP Version 5.6.18
>
> Note that if i don't have a database created before install, the install
> process blocked at step 2.
> But if we have a database created before install and use it on install it
> worked fine.
>
> @stellainformatica <https://github.com/stellainformatica> @AlexRed
> <https://github.com/AlexRed> did you create a new database on install or
> do you have it created before?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9326#issuecomment-193217227>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by wilsonge** [comment] 2016-03-07 11:47
OK - we need to fix that. I installed earlier creating the database during install and it's certainly not intended :/

**Comment by andrepereiradasilva** [comment] 2016-03-07 11:52
probably it was introduced here https://github.com/joomla/joomla-cms/commit/0652e05cf820879ebb252baac9dc4dd805064780

**Comment by ghazal** [comment] 2016-03-07 12:00
Database Version 	5.7.9
Database Collation 	utf8_general_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	7.0.2 
I confirm that it's mandatory to create the database prior to installation in this version.

**Comment by andrepereiradasilva** [comment] 2016-03-07 12:08
i can confirm that adding the line (https://github.com/joomla/joomla-cms/pull/9311/files#diff-75c0b0b456cd757b4e1376ce8821682cR857) before solves the problems @wilsonge

**Comment by andrepereiradasilva** [comment] 2016-03-07 12:22
See https://github.com/joomla/joomla-cms/pull/9328

**Comment by Bakual** [comment] 2016-03-07 12:32
Closing as we have a PR #9328

**Closed by Bakual** 2016-03-07 12:32 UTC
Labels: 3.5.0-blocker, No Code Attached Yet
