### ISSUE TITLE
Article editor - cannot link to an anchor on start page

### ISSUE THREAD

**Issue by o-joomla-issues** [joomla/joomla-cms#43332] opened 2024-04-22 21:07 UTC
### Steps to reproduce the issue
Edit article
Add link per link icon with target like /#my-startpage-anchor

### Expected result
&lt;p&gt;Some link to an &lt;a href="**/#my-startpage-anchor**"&gt;anchor&lt;/a&gt;&lt;/p&gt;

### Actual result
&lt;p>Some link to an &lt;a href=**"#my-startpage-anchor**"&gt;anchor&lt;/a&gt;&lt;/p&gt;
⇨ Leading slash removed, link will not work on any sub-page/url
### System information
Joomla! ‎5.1.0
PHP 8.3.4 as fpm-fcgi on nginx

### Additional comment
Trailing slash also gets removed when adding link manually in html source code w/ tyinmce editor turned off.

**Comment by richard67** [comment] 2024-04-22 21:12
Same as #43324 ? Or only similar?

**Comment by brianteeman** [comment] 2024-04-22 21:27
@richard67 different issue

**Comment by brianteeman** [comment] 2024-04-22 21:32
Is this something that used to work? There have been quite a few changes in 5.1 which may have created this https://github.com/joomla/joomla-cms/pulls?q=is%3Apr+trailing+slash+is%3Amerged

**Comment by o-joomla-issues** [comment] 2024-04-23 09:51
Just checked, same problem in Joomla 3.10.12<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43332">issues.joomla.org/tracker/joomla-cms/43332</a>.</sub>

**Comment by chmst** [comment] 2024-04-24 08:04
@o-joomla-issues I cannot replicate your problem with tinyMCE. j 5.1.0, 

I write your link in html-mode, save and the result is

`<p>Some link to an <a href="../#my-startpage-anchor">anchor</a></p>`

**Comment by o-joomla-issues** [comment] 2024-04-24 08:38
Where does the .. come from? .. is different from / and might not lead to the start page.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43332">issues.joomla.org/tracker/joomla-cms/43332</a>.</sub>

**Comment by chmst** [comment] 2024-04-24 19:14
I used tinyMCE entered your code into an article and saved. Tthis was the result after saving the article therefore comes from tinyMCE.

**Comment by o-joomla-issues** [comment] 2024-04-25 06:24
That's odd. With all Joomla versions I manage, it never adds dots. Maybe we have different settings for URL rewrite.
But either - removing leading slash or adding dots - is an issue as it breaks links.
TincMCE should not change links in any way.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43332">issues.joomla.org/tracker/joomla-cms/43332</a>.</sub>

**Comment by brianteeman** [comment] 2024-08-19 17:26
Have you tried setting tinymce to use absolute instead of relative urls?

![image](https://github.com/user-attachments/assets/9fcad56a-f6bd-446e-8b1a-0586f3933a9f)

**Comment by Quy** [comment] 2024-09-19 19:57
Closing due to no response.

**Comment by o-joomla-issues** [comment] 2024-10-17 07:36
URLs: Absolute will add domain name to URL which is a no-go and does not solve the issue.

**Comment by Quy** [comment] 2024-11-07 05:05
Closing as this is the expected behavior with TinyMCE. Please use CodeMirror or Editor None to prevent the forward slash being removed.

**Closed as completed by Quy** 2024-11-07 05:05 UTC
Labels: No Code Attached Yet, Information Required
