### ISSUE TITLE
Drag and drop sorting messes up on large menu

### ISSUE THREAD

**Issue by osignell** [joomla/joomla-cms#4303] opened 2014-09-19 11:08 UTC
#### Steps to reproduce the issue
1. create a site with a big menu (2500 items on our site)
2. Drag and drop a menu item in the backend to reorder
3. Drag and drop another menu item in the backend to reorder this as well

#### Expected result

Both items get reordered as planned.

#### Actual result

One of the moved items is not placed in the correct position
OR
the whole submenu level is messed up and the items are in wrong order.

#### System information (as much as possible)

Apache/PHP 5.5/Jomla 3.3.3

#### Additional comments

The drag and drop triggers an AJAX request that starts a fairly long-running series of SQL queries (10-15 seconds). If the second reordering is performed while the queries are still running, the final result is not always correct.

The queries are of the type:

UPDATE #__menu SET lft = 4239, rgt = 4250, level = 3 path = 'something/something....

**Comment by janich** [comment] 2015-02-10 12:20
The same seems to be happening with ordering sub-categories some levels down. 
Commenting out /media/jui/js/sortablelist.js:65 (//root.hideSameLevelChildrenNodes) fixes it here, maybe it's related? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4303">issues.joomla.org/joomla-cms/4303</a>.</sub>

**Comment by tomaszs** [comment] 2016-01-29 11:59
I've posted a bug that can be related. Subitems loose parents while drag and drop<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4303">issues.joomla.org/joomla-cms/4303</a>.</sub>

**Comment by fatica** [comment] 2016-03-10 18:35
I'd like to second the performance issue presented in the comments.  We have a site with over 3,000 menu items.  Duplicating menu items, or re-organizing menu items is getting slower and slower.  Since our users can create menu items, we will run into a point where this needs to be re-written.  We experience this issue on every system we are running.  Each is a flavor of Unbuntu, some running Apache, some running Nginx.  The issue is the same on all systems. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4303">issues.joomla.org/joomla-cms/4303</a>.</sub>

**Comment by Kubik-Rubik** [comment] 2016-05-08 14:13
Hi! You created this issue sometime ago but have not provided any code for people to evaluate. As no one else has shown any interest in providing the code and you have not then I am closing this issue at this time. If code is provided (a pull request) it can always be re-examined.

**Closed by Kubik-Rubik** 2016-05-08 14:13 UTC
Labels: No Code Attached Yet

**Comment by tomaszs** [comment] 2016-05-09 06:06
@Kubik-Rubik  What code do you expect? It's not a dev issue, but user issue....
