### ISSUE TITLE
Button clear in SearchTools causes js error

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#18177] opened 2017-09-30 21:30 UTC
### Steps to reproduce the issue
Open the articles overview in backend (or any other list view).
Enter something in the Search input field, then click the clear button

### Expected result
The search inpuut is reset and the list view is refreshed

### Actual result
Nothing happens - see screen
![screen shot 2017-09-30 at 21 28 11](https://issues.joomla.org/uploads/1/31645afffcf9e389d717fdf07652f02f.png)

### System information (as much as possible)
Branch 4.0-dev

**Comment by brianteeman** [comment] 2017-09-30 23:22
Sounds like a duplicate of #17195

**Comment by ghost** [comment] 2017-10-01 05:18
closed as duplicate Report #17195<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18177">issues.joomla.org/tracker/joomla-cms/18177</a>.</sub>

**Closed as completed by ghost** 2017-10-01 05:18 UTC
Labels: No Code Attached Yet
