### ISSUE TITLE
Redirect error 500 in update Joomla 3.8.4 with component JU Form

### ISSUE THREAD

**Issue by goncatin** [joomla/joomla-cms#19499] opened 2018-01-31 10:53 UTC
### Steps to reproduce the issue
Component JUForm 1.1.7
Install Joomla 3.8.3 and set actions after submission to show message.
Test form
Update to Joomla 3.8.4
Test form

### Expected result

Redirect to same page after form submission

### Actual result

Redirect to index.php/es/component/juform and error 500

### System information (as much as possible)

PHP  7.0.27
Joomla! 3.8.4 Stable [ Amani ] 30-January-2018 15:00 GMT 
MySQL  5.5.58-0+deb7u1-log 

### Additional comments

No configuration changes after joomla update

**Comment by ghost** [comment] 2018-01-31 11:08
please have a look at #19497 #19496 if your Issue is an duplicate Report.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19499">issues.joomla.org/tracker/joomla-cms/19499</a>.</sub>

**Comment by csthomas** [comment] 2018-01-31 11:23
@goncatin In global configuration please enable "Debug System" to Yes and set "Error Reporting" to maximum,

Additional you can check `error_log` or similar file at your joomla root directory.

**Comment by goncatin** [comment] 2018-01-31 11:42
If I dissable the SEF URL the form works, but doesn't show the modules linked to the original menu item, so I think is the same issue that [Your text to link here...](https://github.com/joomla/joomla-cms/issues/19497 "#19147")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19499">issues.joomla.org/tracker/joomla-cms/19499</a>.</sub>

**Comment by OctavianC** [comment] 2018-01-31 11:53
I've just tested it (using JUForm Lite) - and the issue is fixed by reverting #19099 or applying my patch #19498

Before patch (3.8.4):
- Menu item (form) placed at: `http://localhost/j384/index.php/test-form`
- Submitting redirects you to: `http://localhost/j384/index.php/component/juform/` which throws an error

After patch:
- Menu item (form) placed at: `http://localhost/j384/index.php/test-form`
- Submitting redirects you to: `http://localhost/j384/index.php/test-form`

**Comment by goncatin** [comment] 2018-01-31 11:55
I confirm that, OctavianC, applying your patch works fine.

**Comment by ghost** [comment] 2018-01-31 12:06
@goncatin so this is a duplicate Report of #19497; please close this Issue.

**Closed as completed** 2018-01-31 12:10 UTC
Labels: No Code Attached Yet
