### ISSUE TITLE
[4.0] Atum dashboard: module sizes don't fit

### ISSUE THREAD

**Issue by drmenzelit** [joomla/joomla-cms#33314] opened 2021-04-25 17:13 UTC
### Steps to reproduce the issue
Pull last changes on an existent J4 installation
PR #33045 introduced changes in the bootstrap size of the dashboard modules. An update script is missing.
The dashboard looks weird:

![grafik](https://user-images.githubusercontent.com/9153168/116002380-c413be00-a5f9-11eb-83af-f770e0ecf797.png)

**Comment by richard67** [comment] 2021-04-25 17:16
We had discussed that in PR #33045 . Making an SQL update script for that could be not so easy because in some case, not only the value of some property in the json params changes, there is a new property added in some case. It can also be done with SQL updates, but they are a bit tricky, and some people might not be happy with it.

I will see what I can do.

**Comment by ChristineWk** [comment] 2021-04-25 18:00
@drmenzelit 

Confirmed. I thought, that my backend is broken :-)
Because above view I saw (think yesterday also) & after installing back to Nightly from today.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33314">issues.joomla.org/tracker/joomla-cms/33314</a>.</sub>

**Comment by richard67** [comment] 2021-04-25 18:02
It's only an issue when updating from a previous 4.0 beta or pulling changes or files from latest nightly and not making a new installation. When making a new installation, it should be ok.

**Comment by ChristineWk** [comment] 2021-04-25 18:07
@richard67 

Aha. Thks for clarification :-)

**Comment by richard67** [comment] 2021-04-25 18:09
Anyway we should fix that because people are already working with Beta 7 and will update to next Beta 8 or RC 1, whatever it will be, and not be happy if their dashboard looks like that.

**Comment by rjharishabh** [comment] 2021-04-26 08:21
> @drmenzelit
> 
> Confirmed. I thought, that my backend is broken :-)

Same with me

**Comment by richard67** [comment] 2021-04-27 08:19
Am working on a fix.

**Comment by richard67** [comment] 2021-04-27 14:39
Closing as having a pull request. Please test #33370 . Thanks in advance.

**Comment by richard67** [comment] 2021-04-27 14:54
Re-opening as the PR doesn't work the all supported database versions.

**Comment by richard67** [comment] 2021-04-27 16:05
New pull request is #33375 . Please test. Thanks in advance.

**Closed as completed by richard67** 2021-04-27 16:05 UTC
Labels: No Code Attached Yet, J4 Issue
