### ISSUE TITLE
string.truncate fails to match closing tags with numerals

### ISSUE THREAD

**Issue by MarkRS-UK** [joomla/joomla-cms#6149] opened 2015-02-22 22:26 UTC
Truncated text from articles containing an html element with numerals (currently only "h"(eader) exists) and another html element whose closing tag is removed in the truncation, will produce invalid html.
This is because the regex in string.truncate fails to match closing tags with numerals.

#### Steps to reproduce the issue
Put text like ```<h1>Title</h1><p>Enough text to get truncated</p>``` at the beginning of an article that is then displayed with string.truncate.

#### Expected result
The html ```<h1>Title</h1><p>Partial text</p>...```    is produced

#### Actual result
The html ```<h1>Title</h1><p>Partial text</p></h1>...```  is produced.
This is invalid in that it produces a second, unmatched, closing h1 tag.

#### System information (as much as possible)
The incorrect code is in line 100 in /libraries/cms/html/string.php.
The match string is `#</([a-z]+)>#iU` when it should be `#</([a-z][a-z0-9]*)>#iU`
to match closing tags with numerals.
This renders correct html in the above example.
If we wanted to cover the case where a closing tag like ```</h1 >``` was being matched, the pattern should be `#</([a-z][a-z0-9]*)\b(?:[^>]*?)>#iU`

#### Additional comments
This error, of course, afflicts truncateComplex too, since it calls truncate.
This code is called anywhere where a short extract from html is displayed, six different views in core components (content, tags, finder, newsfeed).

**Comment by MarkRS-UK** [comment] 2015-02-22 22:33
That'll teach me to preview before submitting.
Take out the % characters from the following strings to get the actual html.

The example html string is <%h%1%>Title<%/%h%1%><%p%>Enough text to get truncated<%/%p%>

Expected text <%h%1%>Title<%/%h%1%><%p%>Short text<%/%p%>...

Actual text <%h%1%>Title<%/%h%1%><%p%>Enough text to get truncated<%/%p%><%/%h%1%>...

Why doesn't gitHub have "code" markdown?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6149">issues.joomla.org/joomla-cms/6149</a>.</sub>

**Comment by MarkRS-UK** [comment] 2015-02-22 22:37
If we wanted to cover the case where a closing tag like <%/%h%/ %> (ie with one or more spaces before the closing > ) was being matched, the pattern should be #</([a-z][a-z0-9])\b(?:[^>]*?)>#iU<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6149">issues.joomla.org/joomla-cms/6149</a>.</sub>

**Comment by MarkRS-UK** [comment] 2015-02-22 22:53
Text fixed on gitHub, but that's not reflected here.
Click the black cat icon at the top of the Joomla issue tracker page to see the gitHub page that looks much better.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6149">issues.joomla.org/joomla-cms/6149</a>.</sub>

**Comment by Erftralle** [comment] 2015-02-28 12:59
Confirmed.

To reproduce the problem I created a new menu entry to show a list of my archived articles and configured it to show the intro text with a limit of 20 chars. This of course assumes that archived articles are available having an intro text containing the sample text mentioned above.

I think when searching for patterns like ```h1``` in the opening tags they should be searched in the closing tags as well.
I confirm, that the patterns suggested by @MarkRS-UK are working fine for me.
I would prefer the second one (```#</([a-z][a-z0-9]*)\b(?:[^>]*?)>#iU```), as it seems to be more robust.

@MarkRS-UK, you should open a pull request for this issue.

**Comment by zero-24** [comment] 2015-02-28 19:20
@MarkRS-UK

>Text fixed on gitHub, but that's not reflected here.

you need to use: http://issues.joomla.org/tracker/joomla-cms/6149/edit else the tracker will sync back the changes :smile: 

As you hvae code you can easy submit a pull request. If you donÄt know how see here: https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests

Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6149">issues.joomla.org/joomla-cms/6149</a>.</sub>

**Comment by zero-24** [comment] 2015-03-12 23:18
Closing as we have a pull request here: http://issues.joomla.org/tracker/joomla-cms/6394 Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6149">issues.joomla.org/joomla-cms/6149</a>.</sub>

**Closed by zero-24** 2015-03-12 23:18 UTC
Labels: No Code Attached Yet
