### ISSUE TITLE
Maximum upload size caps at 128mb

### ISSUE THREAD

**Issue by kstry-kingdom** [joomla/joomla-cms#16439] opened 2017-06-01 17:30 UTC
### Steps to reproduce the issue
Changing the max upload size from the global configuration to anything above 128mb does not apply within the media manager.

### Expected result
Media Manager upload should reflect value from within media configuration

### Actual result
Media Manager upload reflects configuration value while it is <= 128.00mb

### System information (as much as possible)
Joomla 3.7.1 and 3.7.2 on a handful of websites at this time.  
PHP 5.6.30
Apache 2.4.7

### Additional comments
php.ini was checked and is not bottlenecking the upload size
![0](https://cloud.githubusercontent.com/assets/18486102/26692381/6e898142-46ce-11e7-9327-b911fd8c3f45.png)
![100](https://cloud.githubusercontent.com/assets/18486102/26692382/6e8e2c7e-46ce-11e7-9b2c-f30749b2e892.png)
![200](https://cloud.githubusercontent.com/assets/18486102/26692380/6e887022-46ce-11e7-92ae-4164ebc453fb.png)

**Comment by richard67** [comment] 2017-06-01 18:12
What are your php limits, the upload_max_filesize and post_max_size? Maybe the media manager checks for these and uses one of them (or minimum of both) as hard limit?
Is just an idea, I haven't checked that yet.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16439">issues.joomla.org/tracker/joomla-cms/16439</a>.</sub>

**Comment by kstry-kingdom** [comment] 2017-06-01 18:36
php.ini was checked.  post_max_size and upload_max_filesize are both 400mb.

**Comment by ggppdk** [comment] 2017-06-01 18:41
> php.ini was checked. **post_max_size** and **upload_max_filesize** are both 400mb.

besides post_max_size and upload_max_filesize 
you also need to check the setting:   **memory_limit**

**Comment by kstry-kingdom** [comment] 2017-06-01 18:47
> besides post_max_size and upload_max_filesize 
> you also need to check the setting: memory_limit

memory_limit is set to 256m

**Comment by ggppdk** [comment] 2017-06-01 19:01
> memory_limit is set to 256m

Please go to Joomla Backend Menu:
System / System Information / PHP information

1 out of the 3 upload_max_filesize , upload_max_filesize , memory_limit should be 128 MB

**Comment by kstry-kingdom** [comment] 2017-06-01 19:15
Wow, so sorry for the bother.  These sites were using different php.ini files from our normal.  It was indeed the memory_limit causing the low upload size.  Thank you for your help.  Out of curiosity, why is Joomla using this instead of upload_max_filesize?

**Comment by Bakual** [comment] 2017-06-01 19:20
Closing as not a bug

**Closed by Bakual** 2017-06-01 19:20 UTC
Labels: No Code Attached Yet
