### ISSUE TITLE
languagefilter plugin ignores 'detect_browser' setting, when SEF is off

### ISSUE THREAD

**Issue by apr456** [joomla/joomla-cms#18561] opened 2017-11-13 11:33 UTC
### Steps to reproduce the issue
Set "Language selector for new visitors" to "Site language" in languagefilter plugin settings

### Expected result
Site shows in default site language

### Actual result
Joomla still uses language detection

### System information (as much as possible)
Joomla 3.8.1

### Patch:
```php
--- a/plugins/system/languagefilter/languagefilter.php	2017-10-04 10:52:44.000000000 +0300
+++ b/plugins/system/languagefilter/languagefilter.php	2017-11-13 14:30:25.623546066 +0300
@@ -351,7 +351,7 @@
 		{
 			$lang_code = $this->getLanguageCookie();
 
-			if (!$lang_code && $this->params->get('detect_browser', 1))
+			if (!$lang_code && $this->params->get('detect_browser', 0) == 1)
 			{
 				$lang_code = JLanguageHelper::detectLanguage();
 			}
```

**Comment by infograf768** [comment] 2017-11-14 06:59
I can't reproduce the issue, although the code could indeed be modified.

**Comment by Quy** [comment] 2017-12-01 02:00
I can't reproduce it either. The modified code performs the same logic as the old code.

**Comment by ghost** [comment] 2017-12-01 08:26
closed as unconfirmed Report. Issue can always be reopened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18561">issues.joomla.org/tracker/joomla-cms/18561</a>.</sub>

**Closed as completed by ghost** 2017-12-01 08:26 UTC
Labels: No Code Attached Yet
