### ISSUE TITLE
[4.0] Multiple alerts on multilingual associations

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#20575] opened 2018-05-25 09:52 UTC
Open a new article of a multilingual site. Got to Tab Associations.
There are as many alerts as you have content languages. 

### Expected result
One info-alert for content languages 

### Actual result
As many alerts as languages

### System information
Joomla V4.0 dev. 
The message is used in media/com_associations/js/associations.edit.js: Joomla.showAssociationMessage = function(),
![screen shot 2018-05-25 at 09 54 56](https://issues.joomla.org/uploads/1/298741b9017790c388c0cec63fe963fc.png)

**Comment by ghost** [comment] 2018-05-25 11:54
changed Title to make clear its about 4.0

**Comment by infograf768** [comment] 2018-05-25 12:38
Issue confirmed. 
@dgrammatiko 
This happened when you modified the file to not use JQuery

**Comment by infograf768** [comment] 2018-05-25 13:09
I think I found the reason:
`Joomla.showAssociationMessage = function()` is adding the message for each Control group.

Can you set debug on (which will use the non minified js version) and then edit `/media/com_associations/js/associations-edit.js`
and replace the function with this code:

```
	Joomla.showAssociationMessage = function()
	{
		var controlGroup = document.querySelectorAll('#associations .control-group');

		for (var i = 0, l = controlGroup.length; i < l; i++) {
			controlGroup[i].style.display = 'none';
		}
		
		var associations = document.getElementById('associations');

		if (associations) {
			var html = document.createElement('div');
			html.classList.add('alert')
			html.classList.add('alert-info')
			html.id = 'associations-notice';
			html.innerHTML = Joomla.JText._('JGLOBAL_ASSOC_NOT_POSSIBLE');

			associations.insertAdjacentElement('afterbegin', html);
		}
	}
```

**Comment by chmst** [comment] 2018-05-25 13:15
Yes, works! Great :)

**Comment by dgrammatiko** [comment] 2018-05-25 13:56
Sorry there are **no div ALERTS anymore**, use `joomla-alert` Also we have a helper to create alerts...

**Comment by chmst** [comment] 2018-05-25 14:16
That's another scope. Here it is a loop in the js over content languages. But thank you for the hint. @infograf768 would you make a PR?

**Comment by dgrammatiko** [comment] 2018-05-25 14:29
@chmst NOPE. Please **do not** use Bootstrap classes that will not be included in J4. We already have our own components for alerts, use that!!!

**Comment by infograf768** [comment] 2018-05-25 14:44
@dgrammatiko 
It was not my intention to make a PR. I just checked were the error was in the js (which still uses div alerts).
As I would not know how to code `<joomla-alert` in a js, please do PR yourself.

**Comment by infograf768** [comment] 2018-07-25 15:37
I have a patch ready using `joomla-alert`. Waiting for @dgrammatiko to correct a bug when compiling the js files.

**Comment by infograf768** [comment] 2018-07-28 09:52
@chmst 
Closing as we have a PR
https://github.com/joomla/joomla-cms/pull/21281

**Closed as completed by infograf768** 2018-07-28 09:52 UTC
Labels: No Code Attached Yet, J4 Issue
