### ISSUE TITLE
Joomla 3.9.19 post update error

### ISSUE THREAD

**Issue by senolsengul** [joomla/joomla-cms#29408] opened 2020-06-03 14:05 UTC
### Steps to reproduce the issue

Hello there,
3.9.19 articles do not open after the update, we get an error message as follows

Errro message: Unclosed string at position: 2784

**Comment by frankazoid** [comment] 2020-06-03 14:37
upgraded 6 sites today - have no issues like that<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29408">issues.joomla.org/tracker/joomla-cms/29408</a>.</sub>

**Comment by HLeithner** [comment] 2020-06-03 15:12
@senolsengul do you use a content builder or template framework?

**Comment by richard67** [comment] 2020-06-03 15:25
@senolsengul Could you check in "Extensions - Manage - Database" if there are database problems shown? If so: Which? And could you check e.g. with phpMyAdmin the value of column `converted` or table `#__utf8_conversion`(replace `#__`by your table prefix) and report back the result? And of course alsdo answer @HLeithner 's question about page builder or template framework. Thanks in advance.

**Comment by senolsengul** [comment] 2020-06-03 15:29
The issue is related to the theme used. We have resolved the issue for now.
Problem is resolved when Turn off Javascripts Compress in theme settings

Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29408">issues.joomla.org/tracker/joomla-cms/29408</a>.</sub>

**Comment by richard67** [comment] 2020-06-03 15:35
@senolsengul Just to be safe and sure you don't have problems anymore: Could you check in "Extensions - Manage - Database" if there are database problems shown, and report back the result?

**Comment by senolsengul** [comment] 2020-06-04 13:29
Thanks @richard67 

Database checked and no problem <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29408">issues.joomla.org/tracker/joomla-cms/29408</a>.</sub>

**Comment by richard67** [comment] 2020-06-04 13:40
@senolsengul So would you say the issue is solved or it is not a Joomla core issue? If so, please close this issue here or ping me here then I can close it for you.

**Comment by richard67** [comment] 2020-06-04 21:33
Meanwhile it turned out in the support forum that it is indeed an issue of the Helix Template's js compression. According to following post in the Joomla Support Forum they are working on a fix: [https://forum.joomla.org/viewtopic.php?t=980412&p=3606170#p3606339](https://forum.joomla.org/viewtopic.php?t=980412&p=3606170#p3606339)

**Comment by richard67** [comment] 2020-06-04 21:35
Closing as not a Joomla core issue.

**Closed as completed by richard67** 2020-06-04 21:35 UTC
Labels: No Code Attached Yet
