### ISSUE TITLE
[4.0] Upload image in popup

### ISSUE THREAD

**Issue by micker** [joomla/joomla-cms#18762] opened 2017-11-20 20:34 UTC
### Steps to reproduce the issue
on alpha 2
use image button in tinymce, or image field in image link tabs 

### Expected result

we will upload image by drag drop

### Actual result

no image upload in popup mode
if i use upload button it works
without popup  all works

### System information (as much as possible)
PHP Built On | Windows NT DESKTOP-8O7K24V 10.0 build 16299 (Windows 10) AMD64
-- | --
Database Version | 5.7.14
Database Collation | latin1_swedish_ci
Database Connection Collation | utf8_general_ci
PHP Version | 7.0.10
Web Server | Apache/2.4.23 (Win64) PHP/7.0.10
WebServer to PHP Interface | apache2handler
Joomla! Version | Joomla! 4.0.0-dev Development [ Amani ] 31-March-2017 23:59 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

**Comment by ghost** [comment] 2017-11-21 16:23
Can't confirm.

Apply Images per Drag and Drop works in Front- and Backend.
### System information
4.0.0-dev
Multilanguage Site (4 Lang.) & Sample Data
macOS Sierra, 10.12.6
Firefox 57 (64-bit)
#### MAMP 4.2
- PHP 7.0.22
- MySQLi 5.6.35

**Comment by micker** [comment] 2017-11-21 16:42
Did you test un popup ?

**Comment by ghost** [comment] 2017-11-21 17:11
Test per drag'n'drop from local Harddisk to tinyMCE.

**Comment by dgrammatiko** [comment] 2017-11-21 18:51
@micker can't confirm this as well

**Comment by FB1960** [comment] 2017-11-27 14:04
@micker  I see the same error, but with different browsers (Firefox and Edge); when I press the "insert" button, I see the error; if I use the "Images and links" tab, and press the "select" button of the intro or article image, nothing happens: no popup, and no error displayed. The only way to insert an image inside an article is using drag and drop.
Only Chrome/62.0.3202.94 works fine.

**Comment by TobsBobs** [comment] 2017-11-27 19:28
Hi,

i have the same issue. Nothing happens when you press insert. But there is an error see on picture.
I used the Joomla 4 alpha 2.

![fehler](https://user-images.githubusercontent.com/816779/33285006-4fb84b84-d3b1-11e7-830d-e0b1a0f62c33.png)


Setting | Value
-- | --
 
PHP Built On | Windows NT TOBSBOBS 10.0 build 16299 (Windows 10) i586
Database Version | 5.5.5-10.1.19-MariaDB
Database Collation | latin1_swedish_ci
Database Connection Collation | utf8_general_ci
PHP Version | 7.0.13
Web Server | Apache/2.4.23 (Win32) OpenSSL/1.0.2h PHP/7.0.13
WebServer to PHP Interface | apache2handler
Joomla! Version | Joomla! 4.0.0-alpha2 Alpha [ Amani ] 19-November-2017 16:34 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0


I think this bug #18884 not the same as this one. @FB1960 meant another bug. He does not want to upload but to insert a picture.

**Comment by dgrammatiko** [comment] 2017-11-27 19:35
ok, there is a missing polyfill for promises, for sure, but that shouldn't be the problem on latest firefox

**Comment by TobsBobs** [comment] 2017-11-27 22:44
So, I got the latest branch. If I test under google chrome then I get the following error message

![fehlerchrome](https://user-images.githubusercontent.com/816779/33293297-a50ddaf2-d3cc-11e7-814a-140e4f26339a.png)

In Firefox, I get the following error message

![fehler firerfox](https://user-images.githubusercontent.com/816779/33293575-908aa9e2-d3cd-11e7-912c-b1c54912b621.png)

No picture inserted

**Comment by infograf768** [comment] 2017-11-28 09:43
I can't reproduce anymore using pop-up or drag and drop on latest 4.0 branch (Firefox Quantum).

**Comment by FB1960** [comment] 2017-11-28 11:56
News: now also Google Chrome (62.0.3202.94 64 bit) does not work on my side. Probably today was updated, and now generates error, like Firefox and Edge. @TobsBobs I see exaclty the error messages you see, and no picture inserted inside the article.

**Comment by TobsBobs** [comment] 2017-11-28 12:38
I think the bug here is about upload and not about inserting a picture in an article. This #18884 should not closed.

**Comment by FB1960** [comment] 2017-11-28 14:55
TobsBobs, Probably you are right. According to comments, @franz-wohlkoenig could I re-open the #18884?

**Comment by TobsBobs** [comment] 2017-11-28 15:02
I think yes. It´s better re-open #18884. Thanks @FB1960

**Comment by ghost** [comment] 2017-11-29 12:40
reopened #18884

**Comment by ghost** [comment] 2017-12-12 08:32
@micker: according to @laoneo closing this Issue, please open a new one at https://github.com/joomla-projects/media-manager-improvement.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18762">issues.joomla.org/tracker/joomla-cms/18762</a>.</sub>

**Closed as completed by ghost** 2017-12-12 08:32 UTC
Labels: No Code Attached Yet
