### ISSUE TITLE
Isis: Two Factor Authentication tab content wrong display when User Profile plugin enabled

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#7695] opened 2015-08-15 06:52 UTC
While doing this PR ( https://github.com/joomla/joomla-cms/pull/7694 ), I remarked the following:
Enable the User Profile plugin.
Enable one or both of the Two Factor Authentication plugins.
Edit a user in backend.

The Two Factor Authentication fields are displayed UNDER the profile fields (when clicking on User Profile tab) and the Two Factor Authentication tab is useless.

![screen shot 2015-08-15 at 08 44 44](https://cloud.githubusercontent.com/assets/869724/9287820/f589f05a-4329-11e5-8252-86094fb81cfd.png)

No problem in hathor as it uses sliders.

The only solution I found is to move the whole authentication block of code BEFORE  the block `foreach ($fieldsets as $fieldset)` which would display the Authentication tab just after Account Details thus pushing Basic Settings and User Profile further right.

Any other solution?

@nikosdion

**Comment by nikosdion** [comment] 2015-08-15 18:33
See other PR

**Comment by infograf768** [comment] 2015-08-16 06:10
@nikosdion
? 
We have to solves this. This is a bug imho.

**Comment by nikosdion** [comment] 2015-08-16 06:33
No, Jean-Marie, this does *NOT* happen with either Joomla! 3.4.3 or the staging branch of the CMS. This bug is something you caused with your other PR and I agree that it has to be fixed. My recommendation to fix the issue #7695 is to NOT apply #7694 

Please close this issue.

**Comment by infograf768** [comment] 2015-08-16 06:42
@nikosdion
As far as I can test, this bug is unrelated to the other PR as it happens without it. I suggest you test.
(BTW: I have proposed another solution for the other PR).

**Comment by nikosdion** [comment] 2015-08-16 06:48
As I implied above, I am currently looking at *FIVE* different sites, four running Joomla! 3.4.3 and one on the staging branch and none of them displays the behaviour you mentioned. Is it possible that you are using a third party User Profile fields plugin which cocks up the Javascript or HTML on the page? Because that would explain what you're seeing.

Try installing a blank Joomla! 3.4.3 site and test it.

**Comment by infograf768** [comment] 2015-08-16 07:11
I did not have any 3rd party extension.

Installed a brand new staging/master.
Enabled both plugins:
Profile plugin and 2factor authentication plugin
edit user

I do confirm the issue.
See this movie:
https://www.dropbox.com/s/k1nfism4u0bwhkf/2factor.mp4?dl=0

**Comment by infograf768** [comment] 2015-08-16 07:25
I do confirm I do not get the issue on a 3.4.3 site.

**Comment by nikosdion** [comment] 2015-08-16 07:58
I don't know what you are doing wrong but there really is no such issue.

Two more tests.

1. New Joomla! 3.4.1 site and upgraded it to 3.4.3. Cannot reproduce. So it's not an upgrade issue.

2. Brand new Joomla! 3.4.3 site installation. Cannot reproduce. So it's not an issue in 3.4.3.

I am following your instructions to only enable the user profiles and the two factor authentication plugins. No other change made to the default installation.

What you describe would only make sense if the tooltip class produced invalid HTML. This would mean that the very next thing after the user profile fields –the Authentication Method drop-down of the Two Factor Authentication tab– would be screwed up. That *could* lead to what you are seeing but as I'm tired of saying this DOES NOT happen out of the box. 

Could it be a browser extension you are using? Or something that has to do with the ancient OS X version you're still using? I'm trying with Firefox, Chrome and Safari on Mac OS X Yosemite and really, seriously can't reproduce this.

I've spent more than two hours on this. It's a Sunday morning and I'm supposed to be on vacation. Sorry, I can't waste any more time chasing windmills.

**Comment by infograf768** [comment] 2015-08-16 09:02
As I said, this happens on staging, NOT on 3.4.3.
Will test on Yosemite.

**Comment by infograf768** [comment] 2015-08-16 09:28
Same on Yosemite.

**Comment by Fedik** [comment] 2015-08-16 09:45
I can confirm this behavior on latest `master` installation

**Comment by infograf768** [comment] 2015-08-16 09:49
Ah... thanks. I thought I was getting totally insane... :smiley:

**Comment by Fedik** [comment] 2015-08-16 09:54
*Two Factor Authentication* has Tab:

![screen 2015-08-16 12 51 37 564x193](https://cloud.githubusercontent.com/assets/1568198/9292810/a1e795c8-4415-11e5-8b91-0dfcf1c923ab.png)


but in some reason does not have a "tab content" section:

![screen 2015-08-16 12 51 19 398x89](https://cloud.githubusercontent.com/assets/1568198/9292815/b6c68eea-4415-11e5-81f0-3b77622182b4.png)

Something went wrong with the user form rendering, in backend.

**Comment by Fedik** [comment] 2015-08-16 09:56
ah, it inside "#profile" :smile: 
![screen 2015-08-16 12 55 51 497x205](https://cloud.githubusercontent.com/assets/1568198/9292831/2d0db164-4416-11e5-8ab6-55c5e17a13eb.png)

so, seems just broken the form markup

**Comment by infograf768** [comment] 2015-08-16 10:00
I think I found why it was working before:
We had 2 </div> in the dob.php field which was causing other issues. This was rightfully solved

in /layouts/plugins/user/profile/fields/dob.php
If I add a </div> line 18, then this issue is solved (but we get back the original dob issue).

**Comment by Fedik** [comment] 2015-08-16 10:13
seems bug was introduced somewhere here #4103 and then #7340 ?

**Comment by infograf768** [comment] 2015-08-16 10:16
Yep, these were solving the dob issue, but was not tested in the present case where 2factorauth was on.

**Comment by infograf768** [comment] 2015-08-16 10:17
@Bakual 
Could you look into this?

**Comment by Fedik** [comment] 2015-08-16 10:20
this seems fix the problem:
```php
// Closing the opening .control-group and .control-label div so we can add our info text on own line ?>
</div></div><div class="controls"><?php echo $text; ?></div>
```
means we close 2 previous div, add "text" and then open these 2 div again..

but I not very understand how to test it with  #7340

**Comment by infograf768** [comment] 2015-08-16 10:25
I tested this:
adding `</div>` line 21 of /layouts/plugins/user/profile/fields/dob.php (end of file), i.e. the dob is no more displayed in all tabs in frontend and works OK for here.

**Comment by Fedik** [comment] 2015-08-16 10:29
current code is:
```php
</div><div class="controls"><?php echo $text; ?></div>
<div class="control-group"><div class="control-label">
```
it close 1 `div` (line 18) and then open 2 `div` (line 20)
but before open 2 `div` we should close equivalent amount of `div`:
```php
</div></div><div class="controls"><?php echo $text; ?></div>
<div class="control-group"><div class="control-label">
```
:wink:

**Comment by infograf768** [comment] 2015-08-16 15:37
Can you make a PR?

**Comment by Fedik** [comment] 2015-08-16 15:49
@infograf768 there it is #7698 :wink:

**Closed** 2015-08-17 07:28 UTC
Labels: No Code Attached Yet
