### ISSUE TITLE
JHTML::calendar generates an error with date format m-d-Y

### ISSUE THREAD

**Issue by sakiss** [joomla/joomla-cms#8636] opened 2015-12-09 18:10 UTC
This code produces an error
```
JHTML::calendar(
 '12-30-2015',
'something',
'something',
 '%m-%d-%Y'
);
```

This happens only with the date format %m-%d-%Y.
If you change the date format (e.g. %Y-%m-%d) and supply a date relative to that, works fine.

After some debugging i found out:
1. No matter what date is supplied the value becomes 01-01-1970 
2. The error is generated by a code in the title of the text input
```
title="' . ($inputvalue ? static::_('date', $value, null, null) : '') 
```

file: libraries/cms/html/html.php
function: calendar
joomla version: 3.4.5

**Comment by Bakual** [comment] 2015-12-09 19:38
The `$value` needs to be always in english format (`2015-12-30`).
The `$format` may be a different non-english format. It specifies how the date will be displayed.

Closing as working as intended.

**Closed by Bakual** 2015-12-09 19:38 UTC

**Comment by sakiss** [comment] 2015-12-10 11:03
Thanks!
