### ISSUE TITLE
White screen after click find update button!

### ISSUE THREAD

**Issue by farhadst** [joomla/joomla-cms#6833] opened 2015-04-24 06:35 UTC
After update joomla to 3.4.1
in <b>Extension manager - Update</b> page
when click on <b>Find Updates</b> button
shown white screen! (test on firefox 37.0.2 and chrome 42)
i have replace administrator folder but does not matter!

Extension manager - Update page
![find update1](https://cloud.githubusercontent.com/assets/8976056/7313625/30ae5b60-ea71-11e4-826f-9a97fbe8bed9.jpg)

after click!
![find update2](https://cloud.githubusercontent.com/assets/8976056/7313632/481b7580-ea71-11e4-96ab-28ba8a301a9d.jpg)

**Comment by OctavianC** [comment] 2015-04-24 07:52
Go to `System` > `Global Configuration`, click on the `Server` tab and set `Error Reporting` to `Development`. Save you new config and re-test the `Find Updates` button. There should be an error message showing now.

**Comment by farhadst** [comment] 2015-04-24 08:06
error:
Fatal error: Call to undefined method InstallerModelUpdate::getDisabledUpdateSites() in /home/.../domains/.../public_html/administrator/components/com_installer/controllers/update.php on line 93

**Comment by infograf768** [comment] 2015-04-24 08:09
Looks like your update went wrong. as the method exists and we can't reproduce your issue.

**Comment by zero-24** [comment] 2015-04-29 21:27
Moving to `Information required` until we get feedback by @farhadst. If he can fix the issue by reset the files.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6833">issues.joomla.org/joomla-cms/6833</a>.</sub>

**Comment by farhadst** [comment] 2015-04-30 07:03
@zero-24 can u explain more!

**Comment by zero-24** [comment] 2015-04-30 08:03
ok :smile: 

- Download the last Joomla 3.4.2 Package
- extract it
- remove the folder `instalation`
- copy and replace all files over your current installation (e.g. via FTP)
- notice: all core hacks (changes at core files) will be removed if you use a customised core template you can remove the `templates` folder also.
- afterthis please clean your cache (Browser and Joomla) and try again :smile:

**Comment by OctavianC** [comment] 2015-04-30 08:08
You can also use the `Extensions` > `Extension Manager` to install the latest Joomla! package - it works if `upload_max_filesize` and `post_max_size` (in `php.ini`) are set correctly (Joomla! package is ~11MB, so you'll need a value of `16M` for both of them to be on the safe side).

**Comment by farhadst** [comment] 2015-05-01 10:17
@zero-24 i think u speaking about specific file, in first post i say replace admin folder and important folder but it doesn't work! :)

i have install joomla 3.4.1 and replace database table by old site and its work fine!

**Comment by zero-24** [comment] 2015-05-01 10:23
>@zero-24 i think u speaking about specific file, in first post i say replace admin folder and important folder but it doesn't work! :)

I guess you have also to restore/replace the libraries folder.

But the savest way i think is to replace all files as maybe also other files are not updated because of a wrong update ;)

**Comment by farhadst** [comment] 2015-05-02 08:35
@zero-24 i have replace all folder by joomla 3.4.1 but doesn't work! :|

**Comment by farhadst** [comment] 2015-05-02 08:38
@OctavianC i have install latest joomla package as extension manager but problem dosen't fix!

**Comment by bertmert** [comment] 2015-05-02 14:08
The model was found. Otherwise error message would be another.

So open file
/administrator/components/com_installer/**models**/update.php
and search for
public function getDisabledUpdateSites()
(line 148)

**Comment by farhadst** [comment] 2015-05-02 14:28
@bertmert i found <code>public function getDisabledUpdateSites()</code> in update.php line 148

**Comment by ggppdk** [comment] 2015-05-11 17:25
I have seen this before, and the answer is somewhat the only remaining logical conclusion,

-- the desire model file is never loaded, and it was not load because:

using:
  JTable::getInstance('update');

-- does not guarantee that the correct file will be loaded (please take a look at the getInstance function),
instead if some other extensions has already loaded any file like
/any_extension/models/update.php

then the using: JTable::getInstance('update');
will not load any new file

If i remember correctly, this can be with doing this:
  JTable::getInstance('update', $prefix='InstallerModel');

thus forcing getInstance() to load and use the correct file

**Comment by ggppdk** [comment] 2015-05-11 17:27
I forgot to say that the /any_extension/models/update.php,
could have been loaded by a system plugin already

**Comment by mbabker** [comment] 2015-05-11 17:31
Are you talking model or table classes at this point?  Those are two totally different things loaded in different ways.

**Comment by ggppdk** [comment] 2015-05-11 20:10
I am guessing by looking at code, and by having possilbly the same problem in the past,
i will try to make a test run to see if it is the same case as i had experienced before, when 2 extensions tried load a model file:

*/*/models/item.php

and the second one had failed because it used:
  JTable::getInstance('item');

but by the words of 'farhadst',
- the only conclusion is that the correct model file is not loaded, since he made sure that he has an up to date model file in his site

**Comment by mbabker** [comment] 2015-05-11 20:21
Calling `JTable::getInstance()` doesn't load a model class, it loads a table class.  That's where I'm getting confused by your comments; you're referring to file paths that would load model classes and your `JTable::getInstance('update', $prefix='InstallerModel');` line is a bad example where you're specifying a model class name while trying to load a JTable object.

If you're trying to load `JTableUpdate`, then `JTable::getInstance('update');` is just fine as the second param defaults to `JTable` in that method.  If you're trying to load `InstallerModelUpdate`, then you should be calling `JModelLegacy::getInstance('Update', 'InstallerModel');` and you pretty much need to specify both parameters unless you're in the context of a controller class.

**Comment by ggppdk** [comment] 2015-05-12 04:53
@mbabker 
yes you are right,
i tested,
this is called exactly:
  JModelLegacy::getInstance('Update', 'InstallerModel'); 

so the problem must be that some 3rd party extension has already loaded a custom class file
that contains class:  InstallerModelUpdate
because in this case JModelLegacy::getInstance will not try to load a file again, 
and that can also explain why the function does not exist

**Comment by OctavianC** [comment] 2015-05-12 09:47
@farhadst if you're still having issues, can you please edit `administrator/components/com_installer/controllers/update.php` and just after the following lines:
```php
// Find updates.
/** @var InstallerModelUpdate $model */
$model = $this->getModel('update');
```

Add the following:
```php
$class = new ReflectionClass($model);
var_dump($class->getName());
var_dump($class->getFileName());
die();
```

Let me know what messages are showing up now after you click the `Find Updates` button.

**Comment by farhadst** [comment] 2015-05-12 10:49
@OctavianC i have replace following code after this line $model = $this->getModel('update');
and this not work 

@mbabker i found all update.php and rename but problem not fix

**Comment by OctavianC** [comment] 2015-05-12 10:52
And what message are you getting now? If you're not seeing a different message (there should be some strings there instead of the Fatal Error), I'm guessing you have some PHP Code caching module on your server and it's still using the old update.php file.

**Comment by farhadst** [comment] 2015-05-12 10:58
Fatal error: Call to undefined method InstallerModelUpdate::getDisabledUpdateSites() in /home/.../domains/.../public_html/administrator/components/com_installer/controllers/update.php on line 96

**Comment by OctavianC** [comment] 2015-05-12 11:03
It's still the same error - this means that the code I've supplied is not ran. Either it's PHP Caching or you have added it to the wrong function (`$model = $this->getModel('update');` appears in multiple lines, that's why I added the three lines so you can better identify it).

**Comment by farhadst** [comment] 2015-05-12 11:16
yes, i have replace code in wrong line
i get this error after correct:
public_html/plugins/system/egoltupdate/update-j3.php

and when rename this file (update-j3.php) get this error:

Warning: require_once(public_html/plugins/system/egoltupdate/update-j3.php): failed to open stream: No such file or directory in public_html/plugins/system/egoltupdate/egoltupdate.php on line 26 Fatal error: require_once(): Failed opening required 'public_html/plugins/system/egoltupdate/update-j3.php' (include_path='.:/usr/local/php5/lib/php') in /public_html/plugins/system/egoltupdate/egoltupdate.php on line 26

**Comment by OctavianC** [comment] 2015-05-12 11:24
There you have it - you have a System Plugin that's loading a different model. You'll have to disable the plugin "Egolt Update" for this to work... you can also contact the plugin's developers and let them know about this. They'll probably need to rename some files or classes in their plugin to fix this.

**Comment by brianteeman** [comment] 2015-05-12 11:30
Now that we can see that this is an extension and not the core of joomla (great detective work) I am closing this here

**Closed by brianteeman** 2015-05-12 11:30 UTC
Labels: No Code Attached Yet

**Comment by farhadst** [comment] 2015-05-12 11:31
i have disable plugin and get this error now
string(20) "InstallerModelUpdate" string(106) "public_html/administrator/components/com_installer/models/update.php"

**Comment by OctavianC** [comment] 2015-05-12 11:34
Revert the changes you did to the `update.php` file. Good luck! This issue has been resolved.

**Comment by farhadst** [comment] 2015-05-12 11:35
@OctavianC 
after disable plugin, i have delete 3 line code 
$class = new ReflectionClass($model);
var_dump($class->getName());
var_dump($class->getFileName());
die();

and error fix
thanks :)

**Comment by novinfard** [comment] 2015-11-28 08:48
Hello,

It's about the new method of getDisabledUpdateSites in Joomla! 3.X version which break the Egolt Update Plugin. We've solved the problem:
http://www.egolt.com/blog/256-important-update-on-all-products

Just download again and install the new version of your extension.

Thanks for the bug reporting.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6833">issues.joomla.org/joomla-cms/6833</a>.</sub>
