### ISSUE TITLE
Module manager. Cannot delete modules when module extension disabled.

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#15857] opened 2017-05-06 17:06 UTC
### Steps to reproduce the issue
- Joomla 3.7.0
- Create a Banner module in module manager.
- Go to Extensions > Manage > Manage
- Disable  extension "Banner - Module"
- Go to module manager.
- Try to trash the Banner module for deletion in next step. Not possible in list view but if you open the module and set Status = Trashed.
- In list view set Status filter: Trashed
- Try to delete the module (Empty trash). Still not possible.

### Expected result 
- It should be possible
a) to change Status of modules to trashed in list view
b) to delete trashed modules
even if module extension is disabled.

**Comment by PhilETaylor** [comment] 2017-05-08 13:07
I would say this is expected behaviour.

Disabling an extension should disable all its use.

**Comment by bertmert** [comment] 2017-05-08 13:39
Maybe an expected behavior but an obstructive and not logical one.
If I delete a banner module in module manager the extension itself doesn't participate anyhow. At least a deletion should be possible if the module is trashed already.
I simply don't understand the sense of this blockage and why Joomla is forcing a single workflow while purging a system. What "catastrophe" could happen when I delete a module of an disabled extension compared with an enabled one?
A simple info like we see it already would be sufficient.

**Comment by brianteeman** [comment] 2017-12-22 20:54
i am closing this for the reason stated by @PhilETaylor above. The module clearly display as being disabled and how to enable it if needed

**Closed by brianteeman** 2017-12-22 20:54 UTC
Labels: No Code Attached Yet
