### ISSUE TITLE
Saving a new menu item - alias already exists - chosen article still remains?

### ISSUE THREAD

**Issue by Oberaffe** [joomla/joomla-cms#18568] opened 2017-11-14 11:38 UTC
### Steps to reproduce the issue
Is it possible to prospectively change the following: 
accordingly to the actual state the chosen article is automatically removed in case of saving a new menu item after having chosen an article while the system notices that the alias already exists. 
Is it possible to solve it the way that only the alias has to be changed while the chosen article still remains?

**Comment by brianteeman** [comment] 2017-11-14 13:26
I can confirm this behaviour and it would be good if it could be fixed

**Comment by tonypartridge** [comment] 2017-11-15 00:46
So if the Alias exists the selected article is forgotten on save is that right?

**Comment by tonypartridge** [comment] 2017-11-15 01:25
ok recreated, so the issue is because the settings are component related and not menu item related. 

We should probably try and generalise a solution to pre-fill all previous data opposed to just some few bits like we are right now...

**Comment by jwaisner** [comment] 2020-03-11 20:02
@Oberaffe can this still be reproduced on the latest version of J3?

**Comment by brianteeman** [comment] 2020-03-11 20:25
Yes

**Comment by brianteeman** [comment] 2022-08-23 12:03
Thank you for raising this issue. 

Joomla 3 is now in security only mode with no further bug fixes or new features.

I have verified that this issue is resolved in Joomla 4 so it will now been closed. 

If we are mistaken and this does still apply to Joomla 4 please open a new issue (and reference this one if you wish) with updated details for testing in Joomla 4.
cc @zero-24

**Closed as completed** 2022-08-23 13:45 UTC
Labels: No Code Attached Yet
