### ISSUE TITLE
Update notifications

### ISSUE THREAD

**Issue by madesign** [joomla/joomla-cms#18279] opened 2017-10-08 09:49 UTC
### Steps to reproduce the issue
Since 3.8.x is available each of my sites I didn't updated send me several times each day a update notification. That happens every day. Did not happen before where I got only a notification once. That's a really unpleasant behavior.
And there are several reasons not to update a site.

### Expected result
One update notification and that's it.

### Additional comments

**Comment by brianteeman** [comment] 2017-10-08 09:57
Closed. It is the expected and intended behaviour. The only correct fix for this is to update your site.

**Closed as completed by brianteeman** 2017-10-08 09:57 UTC
Labels: No Code Attached Yet

**Comment by Hils** [comment] 2017-10-08 10:31
One update notification email is definitely enough in my view. Where was this decided please?

**Comment by madesign** [comment] 2017-10-08 12:43
That's the notice i get when I want update "Before you update Joomla, ensure that the installed extensions are available for the new Joomla version." Now you tell me I have to update by all means? 3.9. for example had the image source bug which could damage your whole layout. Sorry, the versions before a update notification only appears once not several times each and every day. If you have 20 - 30 sites it's a pain in the ass. Sorry, your answer is not acceptable.

**Comment by zero-24** [comment] 2017-10-08 18:25
> 3.9. for example [...]

Just to be sure there is no 3.9 just 3.8.x ;) When you get pointed to 3.9 than something else is wrong.

> [...] had the image source bug which could damage your whole layout. 

That is what beta/RC versions are for. If you want to be sure copy a live site throw the beta / rc in and report any issues here.

> That's the notice i get when I want update "Before you update Joomla, ensure that the installed extensions are available for the new Joomla version." 

That is just a general notice so the users don't blame joomla to broke their sites with a update because of a outdated version of the extension.

> Sorry, the versions before a update notification only appears once not several times each and every day.

This is not true ;) The general feature is not new and this mail was send always after the timeout. Maybe there is more traffic on your site now?

> If you have 20 - 30 sites it's a pain in the ass. Sorry, your answer is not acceptable.

There are a few solutions:
1) Pre Test the complexed sites before the update and report any issues etc. Than update when there is a release out.
2) set the timeout timer higher. (longer time between the update mail to be send)
3) disable the plugin on 29 sites and let only the site with the highest traffic send you the mail.

The reason why we want the plugin to behave exactly like this is that there are much webmaster with just one website and not that deep knowledge of updates or when they are released. In the past we had some updates where you need to update in a few hours else you can expect your site to be hacked.

If you are an agency and have other places to look for updates for all of your sites. Great. Disable the plugin on your own risk.

But I'm with @brianteeman here this is expected and intended behavior.

**Comment by madesign** [comment] 2017-10-08 18:38
Sorry, 3.8 of course. I meant all sites below 3.8. (3.7.5 for example) sending me several times each day a notification every day. Come on, several times each day? What nonsense is that? I deleted all the mails but must be hundred already. That was different before and is for me some kind of force people to update even when you have reason not to do it. Also it makes not sense deactivating update notification to avoid it. Sorry, that's not a good solution you offer. You just could say deactivate at all and check from time to time the official Joomla site for updates. I noticed it before that you have a problem to admit when you did something wrong. I also work in support for a theme (YOOtheme) company and my gosh how many complains we got with the 3.8 image bug from Joomla. Would be less if the people not update immediately.

**Comment by zero-24** [comment] 2017-10-08 18:46
> Come on, several times each day? What nonsense is that?

When you only have absolute max 6 hours to update before you get hacked what other way do you suggest ;)

> That was different before and is for me some kind of force people to update even when you have reason not to do it.

You should always use the last version. Else you are on your own risk anyway and can disable the plugin..

>  I also work in support for a theme (YOOtheme) company [...]

Great. Please test the RC Version that got published on a copy of the most critical site. And maybe also on a very complex site too. So this kind of bugs can be fixed before the final release. Should be worth after the first bug that got fixed pre release.

> Would be less if the people not update immediately.

Would be much more people to get hacked. Not a great option.

> Also it makes not sense deactivating update notification to avoid it. Sorry, that's not a good solution you offer. You just could say deactivate at all and check from time to time the official Joomla site for updates.

I know, that is the reason why i suggested also better ways to fix that problem ;) And also offered that option at the last of the list.

**Comment by madesign** [comment] 2017-10-08 18:54
Not if the latest version are damaging your layout or is not compatible with an extension which you self warn to take attention to. Special if it's a customer site. Ok i give up. It seams you don't even read my posts. Last chance. It makes no sense to send me a update notification several times each day every day. I think to no one except you try to annoy people. That's very disappointing.

**Comment by zero-24** [comment] 2017-10-08 19:10
I understand your problem that a update broken your or clients sites. But why did this happen? Because there is a change in the cms that broken a configuration / extension / template framework / (some other thing).

Yes this can happen and happen from time to time as we are all humans that do mistakes.

So how to workaround this fact?

To me only testing comes up. To accept a change to the core at least 2 persons need to confirm that this changes works. But even that two person can't test any extension or template framework in any configuration.

For that reason there are RC and beta versions published. If you are an extension developer or template framework developer / user. Just do a quick test on a copy of a live site by installing the update. And if you find any kind of issue report it to us so we can fix it before the release hits stable state.

Just imagine that a simple 5 - 10 minutes test of your site / extension / template framework can save you hours or days of support work?

>  I think to no one except you try to annoy people.

I don't understand why you are attacking me personally. I'm here for your to explain why we did something how we did it. I'm open to good suggestions and have never attacked you personally so why do you that than?

**Comment by madesign** [comment] 2017-10-08 19:18
Sorry didn't know you are the fragile type. How ever I meant annoying with the notifications not you. It leads know where anyway because I have the strong impression you can't except customers (don't know of for free software customers is the right term) can have a problem with your product. That's some kind of arrogance I guess. Please don't answer. I don't want get a other useless notification.

**Comment by zero-24** [comment] 2017-10-08 19:25
>  I have the strong impression you can't except customers (don't know of for free software customers is the right term) can have a problem with your product. 

I have told you that I can fully understand the problem and just asked you for a better fix or proposal. So we can discuss a solution.
