### ISSUE TITLE
com_ajax issues

### ISSUE THREAD

**Issue by riccardoughi** [joomla/joomla-cms#8408] opened 2015-11-12 21:51 UTC
I think line 56 in ajax.php file  should be:

if ($moduleObject->id != -1)

and not:

if ($moduleObject->id != 0)

Thank you.

**Comment by Bakual** [comment] 2015-11-13 08:02
Can you elaborate what the issue is you are seeing and why you think that line needs to be changed?
And since you already propose a code change, can you do a Pull Request? Seehttps://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests for how to do that (it's simple!)

**Comment by drjjw** [comment] 2015-11-13 11:40
OK, that's done:

https://github.com/joomla/joomla-cms/pull/8416/files

**Comment by Bakual** [comment] 2015-11-13 14:08
Looks like you posted in the wrong issue ;)

**Comment by riccardoughi** [comment] 2015-11-17 14:28
If the module.id is verified ( != 0) I receive this also if module is published for my home page:

"LogicException: Module mod_k2_k_content is not published, you do not have access to it, or it's not assigned to the current menu item"

Putting "if ($moduleObject->id != -1)" avoid verification, but I investigate a little bit more and may be I have found the real issue. In getModuleList() in libreries/cms/module/helper.php at line 370:

Itemid = $app->input->getInt('Itemid');

The problem is that "Itemid" in home page doesn exist !

Thank you

**Comment by Bakual** [comment] 2015-11-17 14:40
The URL for the homepage should have an implied Itemid imho.

**Comment by riccardoughi** [comment] 2015-11-19 08:39
Ok, thank you.

**Comment by vieuxcampus** [comment] 2016-01-14 08:25
I get the same issue as riccardoughi. Com_ajax gives the same error message when called from the home page.
ie http://localhost   ->doesnot work
http://localhost/blog  ->works  (blog is the homepage menu title which is not added to the referrer call)
How can I get this fixed ?
thanks <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8408">issues.joomla.org/joomla-cms/8408</a>.</sub>

**Comment by C-Lodder** [comment] 2017-04-05 08:23
@brianteeman - can this be closed? No testing instructions provided and cannot replicate the issue. Have never had any problems with com_ajax myself having used it serveral times

**Comment by brianteeman** [comment] 2017-04-05 08:28
Nothing to do with me

**Comment by franz-wohlkoenig** [comment] 2017-04-05 08:30
closed as unconfirmed Report.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8408">issues.joomla.org/tracker/joomla-cms/8408</a>.</sub>

**Closed by franz-wohlkoenig** 2017-04-05 08:30 UTC
Labels: No Code Attached Yet
