### ISSUE TITLE
[3.9.23] SMTP mail sends PHP mail as fallback or unable to start mail function

### ISSUE THREAD

**Issue by toivo** [joomla/joomla-cms#31482] opened 2020-11-25 11:24 UTC
### Steps to reproduce the issue
Use the Mailer option 'SMTP'
Global Configuration - Server - Mail Settings - Send Test Mail

### Expected result
The test email is sent and received.

### Actual result
Message on remote Linux site:
"Warning - The email was sent to xxx@xxx.xx but using PHP Mail as a fallback. You should check that you have received the test email."

Windows localhost site:
Note: Could not start mail function
Error: Test mail could not be sent

### System information (as much as possible)
PHP 7.4.12

### Additional comments
Test mail used to work in 3.9.22.  The Windows 10 workstation also has Joomla 4 Beta6-dev of 25 November, where the mail test works perfectly all right using the same Gmail SMTP settings as the 3.9.23 localhost site.

Forum topic "Mail test: Warning - The email was sent but using PHP Mail as a fallback" at https://forum.joomla.org/viewtopic.php?f=728&t=983212

**Comment by softforge** [comment] 2020-11-25 11:39
I can confirm this. I took a working 3.9.22 site that used sendmail. I tested the mail and it did the test as usual. I then updated the site to 3.9.23 and tried to send the test mail again and I recieved this
The email was sent to xxx@xxxxxxxxxx.com but using PHP Mail as fallback. You should check that you've received the test email.

The only change was the updating of Joomla from 3.9.22 to 3.9.23

I am using php 7.4.11 on that server

**Comment by HLeithner** [comment] 2020-11-25 12:48
The reason for this is the new security feature to not display the smtp (and all other) passwords again in the configuration.

This means you have to reenter your password to test it normal operation should work fine.

**Comment by Fedik** [comment] 2020-11-25 13:01
then I think "Send Test Mail" should pick stored PW from config then, automatically, if user send empty

**Comment by softforge** [comment] 2020-11-25 13:02
I can confirm its definitely sending via SMTP when private messages etc are being sent but its just falling back on the SMTP test<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31482">issues.joomla.org/tracker/joomla-cms/31482</a>.</sub>

**Comment by HLeithner** [comment] 2020-11-25 13:04
> then I think "Send Test Mail" should pick stored PW from config then, automatically, if user send empty

The feature of "Send Test Mail" is that you can test new configurations without saving them ;-)

**Comment by Fedik** [comment] 2020-11-25 13:12
yeap, but it also used for test existing configuration ;) 
It need to support both cases somehow

**Comment by HLeithner** [comment] 2020-11-25 13:20
of course ;-) 

maybe @zero-24 can help with this.

**Comment by zero-24** [comment] 2020-11-25 21:21
> of course ;-) 
> 
> maybe @zero-24 can help with this.

I can not help with this IIRC Viktor did the initial code? As you know I'm no JS guy.

**Comment by HLeithner** [comment] 2020-11-25 21:25
jsst remove the password that get send to the ajax request so we need a secure way to get it back for this function

**Comment by propellerhuvud** [comment] 2020-11-26 10:20
I came across this too yesterday, with a slightly different text response after sending the test mail.
"Varning
Mailet har nu skickats till xxx@xxx.xx med PHP Mail. Du bör kontrollera att du har tagit emot testmailet."
-> In English:
"Warning
The email was sent to xxx@xxx.xx using PHP Mail. You should check that you have received the test email."

The Swedish translation mentions nothing about PHP Mail being a fallback?! - and therefore I assume that SMTP wasn't used for proper transport of the test mail, but instead it was sent via PHP Mail.

Many web hosts in Sweden close down sites that are using PHP Mail to prevent spam, therefore sending via SMTP becomes crucial for these clients. Hope this finds a solution in the near future.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31482">issues.joomla.org/tracker/joomla-cms/31482</a>.</sub>

**Comment by HLeithner** [comment] 2020-11-26 22:15
It's only the test message and not normal messages. We hopefully have a fix for 3.9.24

**Comment by Fedik** [comment] 2020-11-28 09:32
please test #31515

**Comment by richard67** [comment] 2020-11-28 09:36
Closing as having a pull request for this issue. Please test #31515 .

**Closed as completed by richard67** 2020-11-28 09:36 UTC
Labels: No Code Attached Yet
