### ISSUE TITLE
[4.0] Frontend-login password visibility button click error

### ISSUE THREAD

**Issue by himanshu007-creator** [joomla/joomla-cms#32692] opened 2021-03-14 17:36 UTC
### Steps to reproduce the issue
try to login to frontend of joomla and try to click just below the password visibility button.

![ss](https://user-images.githubusercontent.com/65963997/111078066-ca524d00-8519-11eb-9ab5-9810aae9a110.gif)

same happens if you click near username, it shows "Please fill in this field" 

### Expected result
It should not trigger the button as button is not being clicked

### Actual result
It triggers the button to action!!

### System information (as much as possible)

joomla 4 beta 7 
PHP 8 

### Additional comments
empty response message field should be <code>visibility:  hidden </code> instead of <code>display: none</code>
I would like to work on this issue.

**Comment by brianteeman** [comment] 2021-03-14 18:14
> empty response message field should be visibility: hidden instead of display: none

It is NOT visibility:hidden or display:none

**Comment by himanshu007-creator** [comment] 2021-03-14 18:21
> > empty response message field should be visibility: hidden instead of display: none
> 
> It is NOT visibility:hidden or display:none

Okay👍🏽. But still, message should not be visible and at the same time hold the place ( similar to visibility:hidden ).
Clicking creates problem when done on right of username heading and after that just below the visibility button.

**Comment by chmst** [comment] 2021-03-14 21:44
@himanshu007-creator is right, if the password is empty - the screen jumps.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32692">issues.joomla.org/tracker/joomla-cms/32692</a>.</sub>

**Comment by chandanXP** [comment] 2021-03-15 14:08
@himanshu007-creator, yes on clicking inputs, the other elements in the form should not be misplaced or moved on a same clicking event<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32692">issues.joomla.org/tracker/joomla-cms/32692</a>.</sub>

**Comment by sksuryan** [comment] 2021-03-15 18:19
I think this is a bootstrap thing, since you have interacted with the form, the form expects you to enter something. I don't think we can or should change this behavior because it is tied to a bootstrap class. 
Further, the same thing doesn't exist for the form in the sidebar and you can actually try to login, it will process your request and then return an error that `Empty password not allowed` which I guess shouldn't be allowed in the first place and could be prevented using form validation as above.

*classic "it's not a bug, it's a feature" example here ;)*

**Comment by usmanikram** [comment] 2021-03-16 17:26
The same issue is also with adminsitrator login frontend.

![Login Issue](https://user-images.githubusercontent.com/1428373/111352826-7032c280-86a6-11eb-8209-728f5ce5979b.PNG)

**Comment by Nitesh639** [comment] 2021-03-24 04:36
can anyone guide me how I work on my local computer?

**Comment by drmenzelit** [comment] 2021-03-24 07:09
@Nitesh639 are you a GSoC student? If yes, please join the students channel in glip.

**Comment by Nitesh639** [comment] 2021-03-26 05:13
@drmenzelit Yes mam.

**Comment by brianteeman** [comment] 2021-05-20 23:10
Please test #34066

**Comment by richard67** [comment] 2021-05-20 23:18
Closing as having a pull request. Please test #34066 . Thanks in advance.

**Comment by rdeutz** [comment] 2021-05-29 08:26
Re-open, because PR was closed

**Comment by richard67** [comment] 2023-02-11 10:20
Closing as having a pull request. Please test #39838 . Thanks in advance.

**Closed as completed by richard67** 2023-02-11 10:20 UTC
Labels: No Code Attached Yet
