### ISSUE TITLE
[4.0] buildSefRoute regression

### ISSUE THREAD

**Issue by joeforjoomla** [joomla/joomla-cms#19829] opened 2018-03-04 13:07 UTC
### Steps to reproduce the issue
Trying to manage the Itemid inside a generic component router is no more possible. Indeed the buildSefRoute function of the SiteRouter has been modified so that the menu item is instantiated BEFORE the component router is executed, instead of AFTER has always been.

### Expected result
Routing system still works for extensions managing the Itemid inside the component router 'build' method and extending the RouterBase class

### Actual result
Menu alias is no more resolved being the component router executed AFTER the buildSefRoute get an instance of the current menu based on the current $query['Itemid']

Links are no more:
www.mysite.com/menualias/element

but:
www.mysite.com/component/mycomponent/element?Itemid=1111
### System information (as much as possible)

Joomla 4.0

**Comment by Hackwar** [comment] 2018-03-05 09:19
That is not a regression. First of all, Joomla 4.0 does allow breaks in backwards compatibility. Second of all, you are supposed to modify the Itemid of your component in the preprocess method of your router. Simply said, the explanation of @csthomas is right here (In #18924)

**Comment by joeforjoomla** [comment] 2018-03-05 11:31
Yes @Hackwar you are right. Indeed this is what i did.
But there should not be a sort of documentation about the new preprocess method?
As an extension developer should i guess what's changing in J4? Why nobody says nothing?

**Comment by infograf768** [comment] 2018-03-05 11:33
> Why nobody says nothing?

I guess because nothing is written in stone.

**Comment by Hackwar** [comment] 2018-03-05 11:44
Considering that the preprocess method has been a part of Joomla since 3.3, it isn't exactly new... And as @infograf768 wrote, 4.0 has not been released yet, so I wouldn't call it a big problem that the docs are not complete yet.

**Comment by wilsonge** [comment] 2018-08-18 18:54
I've added a docs required tag to the original PR (i'm slowly working by way through all those tags and puttings them into the J4 upgrade docs/relevant other docs). Closing this issue as a result

**Closed as completed by wilsonge** 2018-08-18 18:54 UTC
Labels: No Code Attached Yet, J4 Issue
