### ISSUE TITLE
Tooltip for image field in article shows wrong path

### ISSUE THREAD

**Issue by Harmageddon** [joomla/joomla-cms#6799] opened 2015-04-18 16:06 UTC
#### Steps to reproduce the issue
1. Create or edit an article in backend.
2. In the tab "Images and links", set two different images for intro and fulltext image.
3. Move your mouse over the fulltext image field. 

#### Expected result
The path for the fulltext image should be displayed when hovering over the respective field. 

#### Actual result
Instead, the tooltip always shows the path for the intro image.

#### Additional comments
Reported by user Cartho on joomla-bugs.de ([original post](http://www.joomla-bugs.de/forum/index.php/topic,667.0.html "Post on joomla-bugs.de")), confirmed by @zero-24 and me. The JavaScript for this behavior comes from /libraries/cms/form/field/media.php (JFormFieldMedia class), but I wasn't able to fix it yet.

**Comment by dgt41** [comment] 2015-04-18 17:06
There is #5871 which corrects this problem but will not be available before 3.5, unless @phproberto decides otherwise.

**Comment by Harmageddon** [comment] 2015-04-18 18:38
@dgt41 Thank you, I didn't know this PR. I just applied it and the bug here is not really fixed, but the tooltip for the path is removed completely in Isis instead. I'm not sure if this is desireable. Also, as you wrote, the bug still exists in Hathor.

**Comment by dgt41** [comment] 2015-04-18 18:44
@Harmageddon I just tested it again here and it looks ok:
![screen shot 2015-04-18 at 9 41 39](https://cloud.githubusercontent.com/assets/3889375/7216778/d3731c6c-e613-11e4-839e-3df08cabbb56.png)

Also in article (multiple media fields):
![screen shot 2015-04-18 at 9 43 27](https://cloud.githubusercontent.com/assets/3889375/7216787/0e93d700-e614-11e4-98d1-437c61da9840.png)

But yes the mootols is still wrong

**Comment by Harmageddon** [comment] 2015-04-18 19:05
@dgt41 I re-tested and commented on the PR.

**Comment by dgt41** [comment] 2015-04-18 19:21
@Harmageddon I had a quick look at the code and I have to say that tips don’t respect the current field because the code behind them doesn’t care about the field id, so the tip in a multiple fields page will always show the first field...

**Comment by brianteeman** [comment] 2015-06-30 10:05
Note this is also true on ANY page that has two media fields as reported #7285<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6799">issues.joomla.org/joomla-cms/6799</a>.</sub>

**Comment by gunjanpatel** [comment] 2015-07-25 05:34
So, do we have code fix for this issue? I guess Yes as far as I read the above conversation. But we have that for Joomla 3.5 series.
In summery, We have fix for this issue and it should be in "Confirmed" status. We should change it "pending" and close this issue in reference with the patch link?  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6799">issues.joomla.org/joomla-cms/6799</a>.</sub>

**Comment by Bakual** [comment] 2015-08-06 19:14
The issue is basically coming from this line: https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/form/field/media.php#L260
The ID is given there hardcoded into the JavaScript code. Since that code is only loaded once per pageload and is supposed to work for all instances of the field, this obviously fails and takes the path of the first media field.
The fix is to either determine the field ID in the JavaScript code (or pass it when called) or have that code added multiple times.
Either way should work and will fix it in staging.

**Comment by dgt41** [comment] 2015-08-06 20:08
@gunjanpatel It’s half solved, meaning the code for media layouts that used jquery+bootstrap is working fine but the old one with mootools still buggy. @Bakual is right with the comment above. Now someone needs to code that as well...

**Comment by luisorozoli** [comment] 2015-10-16 07:13
@gunjanpatel @Bakual @dgt41 Do you know if this issue will be fix for the version 3.5?? Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6799">issues.joomla.org/joomla-cms/6799</a>.</sub>

**Comment by dgt41** [comment] 2015-10-16 13:55
@luisorozoli @Harmageddon @gunjanpatel can you test #8100 ?

**Comment by gunjanpatel** [comment] 2015-10-19 05:10
Thanks @dgt41 for fix. Tested and works fine.

**Comment by zero-24** [comment] 2015-10-19 06:38
Closing as we have a now RTC PR here: #8100 Thanks.

**Closed by zero-24** 2015-10-19 06:38 UTC
Labels: No Code Attached Yet
