### ISSUE TITLE
[com_fields] List all Categories - no category fields output

### ISSUE THREAD

**Issue by pepperstreet** [joomla/joomla-cms#19861] opened 2018-03-08 00:39 UTC
### Steps to reproduce the issue

Create custom fields for one or multiple **Categories**. 
Create some fields for any **automatic** display option. For instance AFTER TITLE. 
Create some fields for **manual** display through plugin syntax in category description. 
BTW, you have to memorize the field ID and insert the plugin syntax by hand. No Editor button!  
Create a menuItem of type "**List all categories**". Show descriptions.

### Expected result

Category fields should display on the listing, for each category.
Either through automatic-display, or plugin-syntax.

### Actual result

No fields display.

### System information (as much as possible)

Joomla 3.8.5

### Additional comments

Related issue: The editor button for fields modal is not displayed! 

Related views are: 
../components/com_content/views/categories/tmpl/default.php
../layouts/joomla/content/categories_default.php
../components/com_content/views/categories/tmpl/default_items.php
../components/com_content/views/categories/view.html.php

CC: @laoneo (mention as requested on a related facebook group comment)

**Comment by laoneo** [comment] 2018-03-08 08:31
The events are missing completely. If this gets implemented, then probably not before 3.9 or 4.0.

**Comment by brianteeman** [comment] 2018-03-08 09:18
Closed as a duplicate of #18457

**Comment by pepperstreet** [comment] 2018-03-09 01:01
@laoneo 
Thanks for checking the issue and your short explanation. You've mentioned the VIEW.HTML on facebook, is this the file which should have the "triggers"? I am not that firm in API and coding, but a very long time user of Joomla. I just noticed the almost empty file and compared it with the usual blog view.html. A big difference.
BTW, the latter one seem to have dispatcher lines in the view layout **and** also in the view.html file?! Which confused me even more ;)

@brianteeman 
This is no duplicate of #18457 , which refers to a different menuItem type "Category list". 
My topic refers to the "List all Categories". Please, re-open it.

**Comment by pepperstreet** [comment] 2018-03-23 02:25
@brianteeman 
This is no duplicate of #18457 , which refers to a different menuItem type "Category list". 
My topic refers to the "List all Categories". Please, re-open it. 
TIA

**Closed** 2020-12-18 10:25 UTC
Labels: J4  Re-evaluate, New Feature, No Code Attached Yet
