### ISSUE TITLE
Wrong javascript on custom field buttons with text containing '

### ISSUE THREAD

**Issue by jlainezs** [joomla/joomla-cms#7895] opened 2015-09-16 14:48 UTC
This bug may affect all field types. I've tested with JFormFieldMenutype and in a JFormFieldContent 

#### Steps to reproduce the issue
* Set multiple languages and for the backend enable one which uses ' (Català, French or any other). I will use Català.
* Change the user language to this language.
* Go to Menú.
* Open any menú ítem (I'm using a menu item which points to a single article).
* Inspect the browser's Javascript error console and you'll find an error (see attach error1).
* On the file ca-ES/ca-ES.com_menus.ini look for the language constant (COM_MENUS_ITEM_FIELD_TYPE_LABEL) and remove the ' on the value.
* Refresh the admin screen and now the javascript error changes (see attach error2). Pls. note, that text is different.
* On the file ca-ES/ca-ES.com_content.ini look for COM_CONTENT_CHANGE_ARTICLE and remove the ' on the value.
* Refresh and no javascript errors are shown (last screenshot).

#### Expected result
no javascript error

#### Actual result
javascript error which blocks the click of the top buttons.

#### System information (as much as possible)
* Joomla! 3.4.4 Stable [ Ember ] 8-September-2015 21:30 GMT 
* Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
* Database version MySQL 5.6.17
* Database collation utf8_general_ci 
* Català Language Pack 3.4.2.1
* PHP 5.6.10
* FireFox 40.0.3
* Windows 10

#### Additional comments
This bug disables the buttons on the top of the page, so is not possible to do any change on the menu items.
![screen shot 2015-09-16 at 09 48 00](http://issues.joomla.org/uploads/1/2a5ba620ff2e181a4840bb576d440286.jpg)
![screen shot 2015-09-16 at 09 48 00](http://issues.joomla.org/uploads/1/53d6a1dde10533edeec8ddf83c3ba585.jpg)![screen shot 2015-09-16 at 09 48 00](http://issues.joomla.org/uploads/1/22888311ff801aa0bb5c1bc95e251130.jpg)

**Comment by Devportobello** [comment] 2015-09-16 15:28
Related here: https://github.com/joomla/joomla-cms/issues/7880

**Comment by infograf768** [comment] 2015-09-16 16:17
I ave already informed the Catalan Translation Team Coordinator of this problem. Expect a new pack soon. The issue is now solved in core. https://github.com/joomla/joomla-cms/pull/7845

**Comment by infograf768** [comment] 2015-09-16 16:18
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7895">issues.joomla.org/joomla-cms/7895</a>

**Comment by infograf768** [comment] 2015-09-16 16:18
Closing as this has been solved in core. See https://github.com/joomla/joomla-cms/pull/7845<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7895">issues.joomla.org/joomla-cms/7895</a>.</sub>

**Closed by infograf768** 2015-09-16 16:18 UTC
Labels: No Code Attached Yet
