### ISSUE TITLE
JFilterInput::isSafeFile() fail on very deep $_FILES array

### ISSUE THREAD

**Issue by Fedik** [joomla/joomla-cms#6397] opened 2015-03-11 18:44 UTC
I have complex form with multiple files upload, in diferent groups,
and in call $app->input->files j3.4 produce 100 warnings:
```
Warning: strstr() expects parameter 1 to be string, array given in libraries/joomla/filter/input.php on line 433
Warning: explode() expects parameter 2 to be string, array given in libraries/joomla/filter/input.php on line 442
Warning: array_reverse() expects parameter 1 to be array, null given in libraries/joomla/filter/input.php on line 443
Warning: array_pop() expects parameter 1 to be array, null given in libraries/joomla/filter/input.php on line 444
Warning: array_map(): Argument #2 should be an array in libraries/joomla/filter/input.php on line 445
Warning: in_array() expects parameter 2 to be array, null given in libraries/joomla/filter/input.php on line 453
Warning: in_array() expects parameter 2 to be array, null given in libraries/joomla/filter/input.php on line 453
Warning: in_array() expects parameter 2 to be array, null given in libraries/joomla/filter/input.php on line 453
Warning: in_array() expects parameter 2 to be array, null given in libraries/joomla/filter/input.php on line 453
Warning: in_array() expects parameter 2 to be array, null given in libraries/joomla/filter/input.php on line 453
```
all these related how `JFilterInput::isSafeFile() ` works.

**how to reproduce** 
it a bit tricky :smile:
simplest way, make fake _FILES, in way how _FILES looks in my form.:
```php
$_FILES = array(
	'jform' => array(
		'name' => array(
			'document' => '',
			'files' => array(
				'files0' => array(
					'file' => ''
				),
				'files1' => array(
					'file' => ''
				),
				'files2' => array(
					'file' => ''
				),
				'files3' => array(
					'file' => ''
				)
			),
			'images' => array(
				'images0' => array(
					'file' => ''
				),
				'images1' => array(
					'file' => ''
				)
			)
		),
		'type' => array(
			'document' => '',
			'files' => array(
				'files0' => array(
					'file' => ''
				),
				'files1' => array(
					'file' => ''
				),
				'files2' => array(
					'file' => ''
				),
				'files3' => array(
					'file' => ''
				)
			),
			'images' => array(
				'images0' => array(
					'file' => ''
				),
				'images1' => array(
					'file' => ''
				)
			)
		),
		'tmp_name' => array(
			'document' => '',
			'files' => array(
				'files0' => array(
					'file' => ''
				),
				'files1' => array(
					'file' => ''
				),
				'files2' => array(
					'file' => ''
				),
				'files3' => array(
					'file' => ''
				)
			),
			'images' => array(
				'images0' => array(
					'file' => ''
				),
				'images1' => array(
					'file' => ''
				)
			)
		),
		'error' => array(
			'document' => 4,
			'files' => array(
				'files0' => array(
					'file' => 4
				),
				'files1' => array(
					'file' => 4
				),
				'files2' => array(
					'file' => 4
				),
				'files3' => array(
					'file' => 4
				)
			),
			'images' => array(
				'images0' => array(
					'file' => 4
				),
				'images1' => array(
					'file' => 4
				)
			)
		),
		'size' => array(
			'document' => 0,
			'files' => array(
				'files0' => array(
					'file' => 0
				),
				'files1' => array(
					'file' => 0
				),
				'files2' => array(
					'file' => 0
				),
				'files3' => array(
					'file' => 0
				)
			),
			'images' => array(
				'images0' => array(
					'file' => 0
				),
				'images1' => array(
					'file' => 0
				)
			)
		),
	)
);
$app = JFactory::getApplication();
$files = $app->input->files->get('jform');
echo '<pre>';
print_r($files['document']);
echo '</pre>';
```

**expected result**
just output from print_r  $files['document']
```
Array
(
    [name] => 
    [type] => 
    [tmp_name] => 
    [error] => 4
    [size] => 0
)
```

**actual result**
1000 PHP warnings
and only then output from print_r

**Comment by Fedik** [comment] 2015-03-11 18:50
quick thought,
maybe better move
```php
// Scan the files in the array
if (!empty($this->data))
{
	foreach ($this->data as $name => &$descriptor)
	{
		$descriptor['safe'] = JFilterInput::isSafeFile($descriptor);
	}
}
```
from `JInputFiles::__construct()`, to `JInputFiles::get()`, and  test only requested files?

**Comment by wilsonge** [comment] 2015-03-14 16:42
@nikosdion can you take a look please :)

**Comment by nikosdion** [comment] 2015-03-15 10:04
This code cannot be moved into get() for obvious reasons. If it's not obvious: get() would be called every single time you access the files descriptors which could be several dozen times in a page load. Calling a very slow operation dozens of times will lead into problems. Moreover, moving the code around doesn't change much, does it?

That said, I want to know exactly what your form looks like. The code you gave above doesn't help me at all in replicating the issue, let alone fixing it :(

**Comment by Fedik** [comment] 2015-03-15 14:25
ok, here is the form that anyone can use for test:
```xml
<?xml version="1.0" encoding="utf-8"?>
<form>
  <field type="text" name="title" label="JGLOBAL_TITLE"  />
  <field type="textarea" name="text" label="Text" />
  <field type="file" name="document"  label="Document" />
  <fields name="files">
    <fields name="files0">
        <field type="file" name="file"  label="File 1" />
    </fields>
    <fields name="files1">
        <field type="file" name="file"  label="File 2" />
    </fields>
    <fields name="files2">
        <field type="file" name="file"  label="File 3" />
    </fields>
  </fields>
  <fields name="images">
    <fields name="images0">
        <field type="file" name="file"  label="Images 1" />
    </fields>
    <fields name="images1">
        <field type="file" name="file"  label="Images 2" />
    </fields>
  </fields>
</form>
```

**Comment by nikosdion** [comment] 2015-03-16 08:28
Do you have an installable extension where I can test this behaviour? I can’t put this XML in any core component’s XML file and have it actually render the fields (the core components’ code is a bloody mess…).

**Comment by Fedik** [comment] 2015-03-16 09:15
unfortunately I cannot send original, 
I will try think something, need some time

but if you just run the code from my first comment (somewhere in template :smile: ), you will see everything :wink:

Other thing, I saw in the code, when you call `$app->input->files` you have no chance to pass options to `JFilterInput::isSafeFile` that called in `JInputFiles::__construct()` as `JFilterInput::isSafeFile($descriptor)`  
that can force some extension developer use $_FILES directly, instead of `$app->input->files` and use `JFilterInput::isSafeFile($_FILES, $options)` one more time, 
In theory move this to `JInputFiles::get()` could fix this problem also,  we could try use some static caching, or something, for  improve performance (a bit)

**Comment by Devportobello** [comment] 2015-03-16 09:58
You can use 'raw' as filter to let you pass if unsafe then apply your filter (about your second point)
$input->files->get(name, default, filter);

Moreover, in backend, i got some issue when installing custom component wich contain some class (in dir: eg: admin/class) so filter on '<?php' break install, did i need to use a dir 'package' or some other thing?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6397">issues.joomla.org/joomla-cms/6397</a>.</sub>

**Comment by nikosdion** [comment] 2015-03-16 10:00
I was able to reproduce this issue by modifying the com_helloworld example component from the Joomla! developers' documentation. I have now made the Pull Request gh-6454 which solves this issue, along with testing instructions.

@Fedik can you please test my patch with your component as well?

**Comment by Fedik** [comment] 2015-03-16 10:07
@nikosdion :+1:  yes, I will

**Comment by brianteeman** [comment] 2015-03-16 10:26
Closing in favour of #6454 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6397">issues.joomla.org/joomla-cms/6397</a>.</sub>

**Closed** 2015-03-16 10:26 UTC
Labels: No Code Attached Yet

**Comment by cheesegrits** [comment] 2015-03-19 23:14
This fix breaks simple usage of ...

`<input type="file" name="foo[]" />`
`<input type="file" name="foo[]" />`

See my comment on the PR
