### ISSUE TITLE
Joomla 3.336 generating url addresses that I have not created

### ISSUE THREAD

**Issue by desaby** [joomla/joomla-cms#6435] opened 2015-03-15 07:00 UTC
#### Steps to reproduce the issue
I do not know how to reproduce the issue. I do not know where we get this strange bug, but Joomla generates strange url addresses. Set to exist url Joomla add parts of other existing addresses and receives a long combination which leads to a completely different page
/Someone url addresses sre in Cyrillic /
Example:
**Original page:**
www.loto-bilety.com/zolotoy-klyuch-proverity-bilet-862-tirazh-07-02-2015.html
**Wrong URL:**www.loto-bilety.com/zolotoy-klyuch-proverity-bilet-863-tirazh-14-02-2015/13-%D0%B7%D0%BE%D0%BB%D0%BE%D1%82%D0%BE%D0%B9-%D0%BA%D0%BB%D1%8E%D1%87/35-zolotoy-klyuch-proverity-bilet-862-tirazh-07-02-2015.html

Furthermore all pages load with or without .html at the end.
See pics from google wemaster tool
#### Expected result
Аassigned address

#### Actual result
Combination of URL addresses

#### System information (as much as possible)
Joomla 3.36, All SEO settings set to YES
Ubuntu Server Edition
Apache: 	2.4.10-1-beget-reuseport
mysql: 	percona 5.6.21-70.0-1-beget
PHP: 	5.5.20

**Comment by brianteeman** [comment] 2015-03-15 10:23
Resetting level based on documented standards https://docs.joomla.org/Bug_and_Issue_Tracker_Priority<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6435">issues.joomla.org/joomla-cms/6435</a>.</sub>

**Comment by bertmert** [comment] 2015-03-15 15:16
"Joomla 3.36"
Current stable version is Joomla 3.4.0. Please update first and retry.

"All SEO settings set to YES"
Normally "Unicode Aliases" shouldn't be set.

13-%D0%B7%D0%BE%D0%BB%D0%BE%D1%82%D0%BE%D0%B9-%D0%BA%D0%BB%D1%8E%D1%87
is just an url encoded
13-золотой-ключ
It's a category view.

Did you test several browsers?

"See pics from google wemaster tool"
Don't see any images but
I made a search at Google and used search string
site:loto-bilety.com
Couldn't find any indexed url encoded links ... like any other user. So, who cares?

"Furthermore all pages load with or without .html at the end."
Expected behaviour.

**Comment by Kubik-Rubik** [comment] 2015-03-15 16:27
This is a known behavior (IDs are crucial for the routing decision, no the aliases). Such URLs can happen if they are set incorrectly somewhere (maybe by an extension etc.) but should not influence your ratings. As @bertmert said, the are not even in the index of the search engine.

Because of the mentioned reasons I will close this issue. Thank you for reporting it!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6435">issues.joomla.org/joomla-cms/6435</a>.</sub>

**Closed** 2015-03-15 16:27 UTC
Labels: No Code Attached Yet
