### ISSUE TITLE
Copy reference to target not working in 3.7.1

### ISSUE THREAD

**Issue by appnweb** [joomla/joomla-cms#16168] opened 2017-05-21 14:10 UTC
### Steps to reproduce the issue

Open an article in the "Multilingual Assciations" component, select a target language that is not already associated and hit the "Copy reference to target" button.

### Expected result

A new article should be created with same settings as the reference except for the language wich sould be the chosen target. It should be associated with the reference article and thus appear on the right side just after being created.

### Actual result

The target article is created correctly but it's not associated to the reference so it just appears quickly on the right side and then disappears.

### System information (as much as possible)

Joomla 3.7.1
Tested on PHP 5.5.9 and 7.0.7

### Additional comments

The function was working correctly on the same websites with version 3.7.0.

**Comment by brianteeman** [comment] 2017-05-21 14:34
Confirmed that this isnt working
Console shows the following javascript error
```
Uncaught TypeError: Cannot read property 'removeFragment' of undefined
    at extension_properties.js:46

```
![lang](https://cloud.githubusercontent.com/assets/1296369/26284777/bd96c5ca-3e3a-11e7-93d2-f12e558f103b.gif)

**Comment by infograf768** [comment] 2017-05-21 18:36
will look tomorrow. if confirmed, this a release blocker

**Comment by brianteeman** [comment] 2017-05-21 19:06
agreed it is a release blocker

**Comment by PhilETaylor** [comment] 2017-05-21 19:27
neither `removeFragment` or `extension_properties.js` are Joomla code.

**Comment by infograf768** [comment] 2017-05-21 19:30
Indeed, I do not get any js error here.
The copy indeed appears in the target and then the target gets empty again.
The copied file can be chosen when using Select Target

**Comment by brianteeman** [comment] 2017-05-21 19:31
looks like those errors are chrome errors - testing on firefox now

**Comment by PhilETaylor** [comment] 2017-05-21 19:31
Looks like this is related to the fix I did for the race condition

**Comment by brianteeman** [comment] 2017-05-21 19:34
same behaviour in MS Edge 
![edge](https://cloud.githubusercontent.com/assets/1296369/26286772/ddadf480-3e64-11e7-8068-f1f350694540.gif)

**Comment by appnweb** [comment] 2017-05-21 20:16
As for Firefox, I already tested and had the same result.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16168">issues.joomla.org/tracker/joomla-cms/16168</a>.</sub>

**Comment by PhilETaylor** [comment] 2017-05-21 20:38
I can replicate the issue. 

Enable debug mode (to load uncomressed js) and then remove my lines of 

```js
// Load Target Pane AFTER reference pane has loaded to prevent session conflict with checkout
		document.getElementById('target-association').setAttribute('src', document.getElementById('target-association').getAttribute('data-url'));
```

and then try EVERYTHING - what breaks?

Im no expert in this extension, I was just asked to fix the race condition, which was https://github.com/joomla/joomla-cms/pull/15948 and https://github.com/joomla/joomla-cms/issues/15945

It seems by removing the JS part of that PR, the race condition still doesn't happen (WTF!, its relying on NOT loading an iframe on launch), and the copy to reference still works... strange.

Please test that, Im already asleep (on pills) and so this is as far as I can get tonight.

**Comment by infograf768** [comment] 2017-05-22 06:34
Please test https://github.com/joomla/joomla-cms/issues/16178

Closing as we have a patch

**Closed by infograf768** 2017-05-22 06:34 UTC
Labels: No Code Attached Yet, release-blocker
