### ISSUE TITLE
Redirect Issue - & is converted to &amp

### ISSUE THREAD

**Issue by theret** [joomla/joomla-cms#11518] opened 2016-08-08 13:51 UTC
#### Steps to reproduce the issue
http://cdl.joomlademos.co.uk
login with : mcr_brighton / mcr_brighton

#### Expected result
http://cdl.joomlademos.co.uk/index.php?option=com_content&view=featured&Itemid=1207

#### Actual result
http://cdl.joomlademos.co.uk/index.php?option=com_content&amp;view=featured&amp;Itemid=1207

#### System information (as much as possible)
Joomla 3.6.3
Database Version 5.6.30-log
Database Collation utf8_unicode_ci
Database Connection Collation utf8mb4_general_ci
PHP Version 5.6.24 

#### Additional comments
I am using a plugin that redirects users to a specific page based on user/user groups.
The plugin is using this bit to redirect :  if($itemid) $app->redirect(JRoute::_($menuitem->link.'&Itemid='.$itemid));

The problem is that for some reason the '&' is replaced with '&amp;' in the output...

**Comment by rdeutz** [comment] 2016-08-08 13:55
try to change 
JRoute::_($menuitem->link.'&Itemid='.$itemid) 
to 
JRoute::_($menuitem->link.'&Itemid='.$itemid, false)

**Comment by theret** [comment] 2016-08-08 14:13
Fixed it. Thanks ;)

**Comment by rdeutz** [comment] 2016-08-08 14:14
Cheers, closing it then, not a bug

**Closed by rdeutz** 2016-08-08 14:15 UTC
