### ISSUE TITLE
JError not working in com_content for unpublished articles after updating to joomla 3.4.1

### ISSUE THREAD

**Issue by adeshpandey** [joomla/joomla-cms#6875] opened 2015-05-01 07:57 UTC
Recently we have updated one of our joomla portal form 3.3.3 to 3.4.1 and suddenly the `JError` inside model stopped working, It took some time to figure it out but we have ended up by replacing `JError` with `JFactory::getApplication()->enqueueMessage(JText::_('COM_CONTENT_ERROR_ARTICLE_NOT_FOUND'), 404)` and got it working but I thought we should file an issue for joomla so that anyone else who faces the same issue can get helped by himself.

**Comment by zero-24** [comment] 2015-05-01 08:21
@adeshpandey can you please describe in more detail what the issue is?

>the JError inside model stopped working

into a custom component, the core? what issues do you have? Is this a site only issue or a issue that you can produce on different sites? Can you reproduce it also with a clean 3.4.1 install?

**Comment by adeshpandey** [comment] 2015-05-01 08:29
Its in the core component com_content, Let me see if I can reproduce with clean setup.

**Comment by Webdongle** [comment] 2015-05-01 15:26
How did you update ?
Is it possible that the update did not update the necessary files ?

Please compare the file you edited with the original in the 3.4.1 full package zip.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6875">issues.joomla.org/joomla-cms/6875</a>.</sub>

**Comment by brianteeman** [comment] 2015-06-21 10:10
After 6 weeks without any update or reply I am closing this at this time<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6875">issues.joomla.org/joomla-cms/6875</a>.</sub>

**Closed** 2015-06-21 10:10 UTC
Labels: No Code Attached Yet
