### ISSUE TITLE
[Tiny MCE] The View of select/upload images popup window

### ISSUE THREAD

**Issue by Orsey** [joomla/joomla-cms#13831] opened 2017-01-31 15:59 UTC
Could you change TinyMCE editor`s images select/upload window as it is shown at the attached image?

<h2>Standard view</h2>
<img src="http://i.piccy.info/i9/19c92219806466699d2ef9f1a533356c/1485877652/60376/1070305/added_image_admin_old.jpg"/>

<h2>New view</h2>
<img src="http://i.piccy.info/i9/37a8bc8465266b93f5ab3b39ab10c4e0/1485877622/83484/1070305/added_image_admin.jpg"/>

**Comment by infograf768** [comment] 2017-02-01 09:11
Closing as duplicate of https://issues.joomla.org/tracker/joomla-cms/13820<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13831">issues.joomla.org/tracker/joomla-cms/13831</a>.</sub>

**Closed by infograf768** 2017-02-01 09:11 UTC
Labels: No Code Attached Yet
