### ISSUE TITLE
Image link is broken in Offline page if accessed not from root

### ISSUE THREAD

**Issue by AndySDH** [joomla/joomla-cms#14164] opened 2017-02-21 13:38 UTC
### Steps to reproduce the issue

- Set an "Offline Image" in Global Configuration
- Set the site Offline
- I assume SEF URLs must be on for this to happen
- Try to visit the website by accessing a Menu Link or a Category Link (anything but the root homepage)

### Expected result

- The offline image should be displayed with "/images/path/name_of_the_image.jpg" with leading slash so that it always refers to the root

### Actual result

- The offline image is displayed without the leading slash ("images/path/name_of_the_image.jpg") so the path turns into "link_path/images/name_of_the_image.jpg" resulting in a broken link.

**Comment by PhilETaylor** [comment] 2017-03-04 21:06
Which template are you using to replicate this with ?

**Comment by AndySDH** [comment] 2017-03-05 09:54
To me it also happened with the default protostar template.

**Comment by nileshprasad137** [comment] 2017-03-08 16:24
I am not able to reproduce this issue using "default protostar" template or "Beez3" template on Joomla 3.6.5.
![capture](https://cloud.githubusercontent.com/assets/16336390/23712499/2dd76ff0-0449-11e7-8182-d1347dec6486.PNG)
![capture2](https://cloud.githubusercontent.com/assets/16336390/23712691/b125f6ec-0449-11e7-9f9a-8bde36c1bb53.PNG)


.

**Comment by brianteeman** [comment] 2017-03-13 11:01
I cannot confirm this either

**Comment by franz-wohlkoenig** [comment] 2017-04-04 18:05
closed as unconfirmed Report. @AndySDH please reopen if closed too early.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14164">issues.joomla.org/tracker/joomla-cms/14164</a>.</sub>

**Comment by AndySDH** [comment] 2017-04-05 09:57
I tested this further. I noticed this happens with sh404sef installed. Apparently it's because, with sh404sef installed, the browser path is kept in the URL bar when the site is offline, while with default Joomla, it redirects to the browser path in the URL bar to the root. 
Since the path is redirect to the root, the image is displayed correctly.

However, it is still technically wrong to have the image code without the leading slash. It's more correct to directly specify so start from the root. Adding the leading slash fixes the problem with sh404sef enabled and doesn't harm anything for the default Joomla.

**Comment by franz-wohlkoenig** [comment] 2017-04-05 10:28
reopened for Discussion.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14164">issues.joomla.org/tracker/joomla-cms/14164</a>.</sub>

**Comment by brianteeman** [comment] 2017-05-21 14:47
I am closing this as the core is working correctly and it is an extension that is breaking the behaviour. If you really want to see the core being changed then please submit a pull request with the changes for consideration

**Closed by brianteeman** 2017-05-21 14:47 UTC
Labels: No Code Attached Yet
