### ISSUE TITLE
[4.0] Cannot edit module on frontend

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18598] opened 2017-11-17 19:01 UTC
### Steps to reproduce the issue

Install [4.0Alpha] 
Login to frontend using the login form on the front page
Click the EDIT MODULE icon in the top right of the login form module 

### Expected result

I can edit the module

### Actual result

![screen shot 2017-11-17 at 19 00 59](https://user-images.githubusercontent.com/400092/32964010-ac2dbd26-cbc9-11e7-95b5-f0096a3afcb2.png)

**Comment by ghost** [comment] 2017-11-18 09:47
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18598">issues.joomla.org/tracker/joomla-cms/18598</a>.</sub>

**Comment by wilsonge** [comment] 2017-11-18 21:25
Duplicate of https://github.com/joomla/joomla-cms/issues/18691

**Closed as completed by wilsonge** 2017-11-18 21:25 UTC
Labels: No Code Attached Yet
