### ISSUE TITLE
All text prints in Black. Images print OK

### ISSUE THREAD

**Issue by rgtr** [joomla/joomla-cms#14021] opened 2017-02-11 12:20 UTC
### Steps to reproduce the issue

http://unaccountablescotland.org.uk/index.php/2-uncategorised/35-test-print-colours

Click Options Icon on top right side. Select Print

### Expected result

To get a pdf or color print with different text colors

### Actual result

ALL Text print prints black

### System information (as much as possible)

Joomla 3.6.5, Windows 7, Chrome latest.

### Additional comments

Happens on several other sites.....

Richard@TDOC.net

**Comment by tonypartridge** [comment] 2017-02-11 17:06
Hello,

This isn't s core issue. It is intended by design by the template. The idea being to print friendly the page to help the environment and so on. 

Edit your print.css of the template as you see fit.

Many thanks
Tony

**Comment by Bakual** [comment] 2017-02-11 18:16
Closing as not a bug

**Closed by Bakual** 2017-02-11 18:16 UTC
Labels: No Code Attached Yet

**Comment by rgtr** [comment] 2017-02-12 11:11
Tony, 
Thanks for your very useful comment.

However, Protostar has only two css files showing: offline.css and template.css

The next problem is that the template.css has absolutely no commenting - so altho i have some basic knowledge - indeed i used to write software [see tdoc.com] - some guide as to what to do would be good - viz which line nos address the preview....

When I use the inspect function in Chrome, the change has already occurred and one cannot see what is happening.

In my view this probably renders protostar unusable. 

Commenting is required asap.

Richard<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14021">issues.joomla.org/tracker/joomla-cms/14021</a>.</sub>

**Comment by tonypartridge** [comment] 2017-02-12 11:16
Again this isn't a bug, commenting maybe required ASAP but GITHub is for Joomla! issues not help and support. Nonetheless check your template.css file and you will clearly see:

`@media print {
	* {
		text-shadow: none !important;
		color: #000 !important;
		background: transparent !important;
		box-shadow: none !important;
	}
	a,
	a:visited {
		text-decoration: underline;
	}
	a[href]:after {
		content: " (" attr(href) ")";
	}
	abbr[title]:after {
		content: " (" attr(title) ")";
	}
	.ir a:after,
	a[href^="javascript:"]:after,
	a[href^="#"]:after {
		content: "";
	}
	pre,
	blockquote {
		border: 1px solid #999;
		page-break-inside: avoid;
	}
	thead {
		display: table-header-group;
	}
	tr,
	img {
		page-break-inside: avoid;
	}
	img {
		max-width: 100% !important;
	}
	@page {
		margin: 0.5cm;
	}
	p,
	h2,
	h3 {
		orphans: 3;
		widows: 3;
	}
	h2,
	h3 {
		page-break-after: avoid;
	}
}`

media print 

means when printing apply this CSS. I've never used Protostar as a template and when I write mine I use print.css opposed to inline in the template.css.

Handle it as you see fit, but it's not a core issue.

**Comment by rgtr** [comment] 2017-02-12 11:35
Tony, 
Thanks 

Found that at line 112. - had to import into jedit to get line nos - but no probs.

the only color is "color: #000 !important;" so have commented that line out /* ... */
so now i have:

@media print {
	* {
		text-shadow: none !important;
		/* color: #000 !important; */
		background: transparent !important;
		box-shadow: none !important;
	}

and hey presto - that is fixed

thanks a million.

richard

had to remember that Chrome is very persistent - so had to test in opera with its vpn setting on .... ace as it clears this type of thing.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14021">issues.joomla.org/tracker/joomla-cms/14021</a>.</sub>
