### ISSUE TITLE
Changes to JInput getString cause issues

### ISSUE THREAD

**Issue by joeforjoomla** [joomla/joomla-cms#16812] opened 2017-06-22 13:07 UTC
### Steps to reproduce the issue
Changes to the cleanTags method in root/libraries/joomla/filter/input.php
causes issues when using:
$input->getString() method.

Some characters such as < and > are not passing anymore getting stripped out

This should be at least documented somewhere, if the getString result is now different than before.
### Expected result
string>passed>ok

### Actual result
stringpassedok

**Comment by joeforjoomla** [comment] 2017-06-22 13:08
And more importantly: how can i get a string like 'string>passed>ok using JInput if getString is no more usable?

**Comment by joeforjoomla** [comment] 2017-06-22 13:18
This could lead to unexpected results because characters '<' and '>' included in a string can't get saved anymore when using getString().

**Comment by mbabker** [comment] 2017-06-22 13:36
Looking at the last changes in `JFilterInput`, this case works fine at https://github.com/joomla/joomla-cms/commit/685f55ea9686e4651b91097ad1bd4dcba4f9dafb but is broken at https://github.com/joomla/joomla-cms/commit/495dcc7e27720e50cd59bdcb73d4f61f1c274db8

Unless there is some necessity for the added filtering, this is not only a bug, but a release blocker.

// @rdeutz

**Comment by joeforjoomla** [comment] 2017-06-22 13:38
We have experimented issues especially when using getString for token such as OAuth, etc
If the string contains a '>' or '<' now it gets stripped out and things don't work anymore.

**Comment by wojsmol** [comment] 2017-06-22 14:15
@csthomas Plese check this also.

**Comment by joeforjoomla** [comment] 2017-06-22 14:17
Merge this issue to the 3.7.3 branch please.

**Comment by rdeutz** [comment] 2017-06-22 14:47
@joeforjoomla only PR can be based on a branch.  I have created unit tests so that we can see we a code change passes. #16816

**Comment by joeforjoomla** [comment] 2017-06-22 14:49
Thanks @rdeutz ... sorry for my ignorance

**Comment by rdeutz** [comment] 2017-06-22 14:50
All good we all are learning constantly :-)

**Comment by joeforjoomla** [comment] 2017-06-22 14:59
:) that's true

**Comment by wilsonge** [comment] 2017-06-22 15:24
Did all these cases pass before? Like I'm pretty sure that one of these cases is a "known failure" for ages (see my 18 month old issue at https://github.com/joomla-framework/filter/pull/15)

**Comment by rdeutz** [comment] 2017-06-22 15:35
If I revert 495dcc7 a string like "string>passed>ok" is working fine, with my added test cases we have 28 errors without revert and 21 after revert.

**Comment by csthomas** [comment] 2017-06-22 15:35
My PR changed that.
character `>` now is removed but previous was not
`<` was always removed (previous too) and the first or more words followed, example for tests `ala < ma kota >` 
or `ala > < ma kota`

Method `getString` and `getHtml` works very similar. 
`getString` additional replaces all html entities to utf8 encoded characters.

They use the same `cleanTags()` method and tries to return valid html code.

For me there is some misunderstanding with `getString()`, because it validates source as html code.

Now `getString()` tries to remove forbidden tags and html attributes.
Can someone explain me what should be the difference between `getString` and `getHtml`?

**Comment by mbabker** [comment] 2017-06-22 16:05
I think part of the problem is it's arbitrarily treating `<` and `>` as HTML tag indicators and not accounting for a scenario where the brackets may be used in other contexts.  So I don't think we can arbitrarily just say "if you know your string may contain these characters, you cannot use the string filter"; they are not exclusive to HTML output.

**Comment by joeforjoomla** [comment] 2017-06-22 17:01
I think that both < and > should never be removed by an arbitrary string using getString. They are 2 normal characters in a generic string context after all, no reason to remove them.
It would be more logical to remove them in a getHtml method because they could be recognized as invalid HTML markup.

**Comment by joeforjoomla** [comment] 2017-06-24 16:04
Reference this PR #16842

**Comment by franz-wohlkoenig** [comment] 2017-06-24 16:20
closed as having PR #16842<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16812">issues.joomla.org/tracker/joomla-cms/16812</a>.</sub>

**Closed by franz-wohlkoenig** 2017-06-24 16:20 UTC
Labels: No Code Attached Yet, release-blocker
