### ISSUE TITLE
Possibility to assign the template during Batch process

### ISSUE THREAD

**Issue by MATsxm** [joomla/joomla-cms#12044] opened 2016-09-15 15:03 UTC
### Steps to reproduce the issue

On a multilingual site.
Batch (Copy) some Menus from a language to another.
Params are correctly copied except you will have to reopen every articles to assign the right dedicated Template.
### Expected result

It would be great if during the batch process, it would be possible to assign also the template.

Thoughts?

**Comment by brianteeman** [comment] 2016-09-15 15:50
Its nothing to do with it being a multilingual site. You might want to assign a menu item to a different template on a monolingual site as well

**Comment by MATsxm** [comment] 2016-09-15 15:54
yes... this is not the point

**Comment by franz-wohlkoenig** [comment] 2017-02-01 13:20
Workaound #13194

**Comment by franz-wohlkoenig** [comment] 2017-04-06 06:25
closed as Duplicate of #13194 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12044">issues.joomla.org/tracker/joomla-cms/12044</a>.</sub>

**Closed by franz-wohlkoenig** 2017-04-06 06:25 UTC
Labels: No Code Attached Yet

**Comment by MATsxm** [comment] 2017-04-06 11:06
@franz-wohlkoenig yes... duplicate as this was #12044
