### ISSUE TITLE
Install From Web - Clear button always disabled

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#41966] opened 2023-09-28 09:18 UTC
### Steps to reproduce the issue

1. Go to administrator/index.php?option=com_installer&view=install
2. Navigate to the "Install From Web" tab
3. Type something in the "Search" box
4. Press `Enter` or click the search button

### Expected result

Text remains in the input box and "Clear" button becomes enabled

### Actual result

Text is emptied from the input and "Clear" button is still disabled.
It's always disabled, so can never be used.

**Comment by brianteeman** [comment] 2023-09-28 13:38
Confirmed

**Comment by brianteeman** [comment] 2024-01-25 22:18
Sorry - just realised that this bug is in code in the other repo https://github.com/joomla/install-from-web-server

**Comment by Hackwar** [comment] 2024-04-02 11:10
I created a copy of this issue in the right repo and mentioned you guys. Since this is the wrong repo for this, I'm closing this issue.

**Closed as completed by Hackwar** 2024-04-02 11:10 UTC
Labels: No Code Attached Yet, bug
