### ISSUE TITLE
[4.0]  com_contact email 

### ISSUE THREAD

**Issue by angieradtke** [joomla/joomla-cms#34865] opened 2021-07-22 09:47 UTC
The new form-control css -classes are really great. They give us the possibility to improve the UX significantly.
Unfortunately there is a small problem with the email-field. 
Even if the input is not a valid email address the field gets the css-classes

`class="form-control validate-email required valid form-control-success"`

**Comment by Quy** [comment] 2021-07-22 22:39
I am not able to reproduce. Please advise an invalid email address to test.

**Comment by angieradtke** [comment] 2021-07-23 08:44
i f we type in mail@   without a mailending it is validated true

**Comment by brianteeman** [comment] 2021-07-23 08:59
Can not replicate

With a valid email address I have 
`<input type="email" inputmode="email" name="jform[contact_email]" class="form-control validate-email required valid form-control-success" id="jform_contact_email" value="" size="30" autocomplete="email" required="" aria-invalid="false">`

With an invalid email address eg `mail@` I have
![image](https://user-images.githubusercontent.com/1296369/126759737-aeae80e2-3273-4648-8f7c-45e9009cb232.png)

`<input type="email" inputmode="email" name="jform[contact_email]" class="form-control validate-email required form-control-danger invalid" id="jform_contact_email" value="" size="30" autocomplete="email" required="" aria-invalid="true">`

**Comment by angieradtke** [comment] 2021-07-23 09:17
Type in a.radtke@gjgjhh  something behind the @

**Comment by brianteeman** [comment] 2021-07-23 09:38
> a.radtke@gjgjhh

that is a valid email address on internal networks

**Comment by brianteeman** [comment] 2021-08-04 07:43
This should be closed as it is working correctly and the issue is that the user expected the validation to be different than it is

**Comment by angieradtke** [comment] 2021-08-04 08:01
This not my main expertise, but I saw 
https://help.xmatters.com/ondemand/trial/valid_email_format.htm

@wilsonge

**Comment by brianteeman** [comment] 2021-08-04 08:31
This comes up every few years. It is perfectly valid to have an email address in the form user@localdomain
There is a reason there are standards and we shouldnt try to re-invent them

**Comment by brianteeman** [comment] 2022-02-15 09:24
This should be closed for the reasons stated above

**Closed as completed** 2022-02-15 10:15 UTC
Labels: No Code Attached Yet
