### ISSUE TITLE
[5.1] SEf.php Trailing slashes options 

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#43069] opened 2024-03-17 11:36 UTC
**The new sef plugin options completely break the ability to preview an article or do an accessibility check on article**

### Steps to reproduce the issue
In global configuration make sure you have sef urls on and that you have an ,htaccess file

![image](https://github.com/joomla/joomla-cms/assets/1296369/67454394-b001-4c61-9c2a-5ecaff5175e6)

Go to the sef plugin and configure the two new options as shown in the image below

![image](https://github.com/joomla/joomla-cms/assets/1296369/5d533a72-b96c-470d-977d-26f439b1a3b3)

Go to an article and try to preview it or do an accessibility check

![image](https://github.com/joomla/joomla-cms/assets/1296369/47a0a521-09c3-4ae5-a5c6-59c578c9bb1e)

### Expected result
it works

### Actual result
![image](https://github.com/joomla/joomla-cms/assets/1296369/cdb1ddf6-68de-422a-82a9-9b108d200c43)

### Additional comments
This is a release blocker and the second fatal error wioth this plugin - clearly it needs more extensive testing

**Comment by brianteeman** [comment] 2024-03-17 11:45
all these changes to sef have caused multiple problems that have either had to be reverted, fixed or have yet to be discovered. These changes clearly need much more testing in the real world, and not just following the limited testing instructions in the prs. They should all be reverted and bumped to 6.0

**Comment by Fedik** [comment] 2024-03-17 12:28
hm, I still have it working, you testing on beta or on recent branch?
maybe it already fixed by https://github.com/joomla/joomla-cms/pull/43063 ?

**Comment by SniperSister** [comment] 2024-03-17 13:01
I'm unable to reproduce the issue.

Latest 5.1.x dev branch, SEF plugin enabled, "force Trailing slash"-option enabled, preview and accessibility screen both work as expected. I've tested it with enabled and disabled language filter plugin and enabled and disabled SEF mode.

**Comment by brianteeman** [comment] 2024-03-17 13:15
https://github.com/joomla/joomla-cms/assets/1296369/1f97761b-ef58-44d4-9daa-0533c3f4d1d7

**Comment by brianteeman** [comment] 2024-03-17 13:17
> I'm unable to reproduce the issue.
> 
> Latest 5.1.x dev branch, SEF plugin enabled, "force Trailing slash"-option enabled, preview and accessibility screen both work as expected. I've tested it with enabled and disabled language filter plugin and enabled and disabled SEF mode.

"force Trailing slash" should be "without traling slash" for the error

**Comment by brianteeman** [comment] 2024-03-17 13:27
Found how you can replicate it and the cause

1. Install the sample testing data
2. Create a new article in the category "uncategorised" 
3. Save article
4. Preview article - its broken
5. change the category to "blog"
6. Save article
7. Preview article - its working
8. change the category to "uncategorised"
9. Save article
10. Preview article - its broken

The problem is because there is no menu that would display any article in the "uncategorised" category. Confirm that this is the cause by

Create a new menu item  of type category list for the category "uncategorised".
Repeat steps 2 to 10 above. 
Everything works
Unpublish the menu item and you are back to getting the errors

**Comment by Fedik** [comment] 2024-03-17 14:02
hmhm, it still works for me.
I have article in "uncategorised", preview works, 
the iframe URL is not "sef" like `/en?view=article&id=76:test-nomenu-route&catid=2` (that another issue), but it works

**Comment by SniperSister** [comment] 2024-03-17 14:06
> The problem is because there is no menu that would display any article in the "uncategorised" category. Confirm that this is the cause by

I can reproduce the issue, however it remains the same after disabling the newly introduced option. I even switched back to the 5.0 branch and it shows the same behavior. Are we sure it's related?

**Comment by brianteeman** [comment] 2024-03-17 14:19
it only happens with this one option as shown in this video


https://github.com/joomla/joomla-cms/assets/1296369/cf82cf14-10eb-443d-8f2c-45a723561965

**Comment by SniperSister** [comment] 2024-03-17 17:27
Ok, finally I was able to reproduce the issue!

In the described scenario, the preview URL in the iframe without the enforced removal for a site residing in the domain root looks like this: ```/?view=article&id=73:uncategorized-article&catid=2```

After the removal is enforced, the leading slash is gone and the URL, that before was relative to the domain root, is now relative to the current context, which in this case is the administration URL, causing the browser to load ```administrator/?view=article&id=73:uncategorized-article&catid=2```

I see two potential fixes:
a) use an absolute URL while generating the iframe URLs in the backend - we are talking about roughly 10 places
b) don't apply the rule when generating frontend rules from a backend context

Any preferences?

**Comment by SniperSister** [comment] 2024-03-17 17:56
> Revert this code. You are proposing band aids and not solutions. 

I disagree. Especially option b, excluding the rule in non-site apps, is a commonly used pattern in the existing SEF plugin and a gazilion other places within the CMS.

> We can't afford to break urls on a live site.

We don't break live sites. It's a new feature that is not enabled by default. A user has to actively make the decision to use it.

**Comment by brianteeman** [comment] 2024-03-17 17:57
you asked for my preference and I gave it.

**Comment by SniperSister** [comment] 2024-03-17 17:58
> you asked for my preference and I gave it.

Perfectly fine! It's a valid opinion! :)

**Comment by brianteeman** [comment] 2024-03-17 18:31
another possibility  is to adopt drupal's experimental policy. that would allow the code to be merged knowing that it may cause unkown issues and will not be tied to a b/c policy etc. 

because of the different structure in joomla then they could be marked in the ui like below
![image](https://github.com/joomla/joomla-cms/assets/1296369/66eda51b-0fbd-46bc-aae1-615f458b4ecd)

reference https://www.drupal.org/about/core/policies/core-change-policies/experimental/policy-and-list

This would allow time for the previously mentioned test suite to be created before the code is removed from the experimental list

**Comment by SniperSister** [comment] 2024-03-17 18:35
> This would allow time for the previously mentioned test suite to be created before the code is removed from the experimental list

That's a great idea :) like it!

**Comment by brianteeman** [comment] 2024-03-17 19:06
would also be suitable for #42850

**Comment by Hackwar** [comment] 2024-03-17 20:19
Closing since we have a fix with #43074.

**Closed as completed by Hackwar** 2024-03-17 20:19 UTC
Labels: No Code Attached Yet

**Comment by brianteeman** [comment] 2024-03-17 20:30
@SniperSister I see that neither of your proposed solutions have been applied

**Comment by Hackwar** [comment] 2024-03-18 08:32
Feel free to propose a different PR. Looking at the proposed solutions, I don't really want the router to work differently in the backend than in the frontend, since that would mean the URLs in mails, etc. would be different. I also don't want to change the code at different places because it would mean all other code out there would have to change as well. So I did the third option and solved the problem by not deleting the leading slash when we actually only want to remove the last trailing slash.
