### ISSUE TITLE
Language Plugin: Language Suffix Persists After Removing It in Settings Bug Feature 5.2

### ISSUE THREAD

**Issue by Stuartemk** [joomla/joomla-cms#44350] opened 2024-10-24 03:30 UTC
> El complemento languagefilter permite ocultar el sufijo de idioma para el idioma predeterminado, pero no para todos los idiomas. Este es el comportamiento esperado, ya que de lo contrario no podría proporcionar un enlace a contenido en un idioma específico. Dado que este es el comportamiento esperado, voy a cerrar este.
> 
> Give me an example
> 
> On a single language site the language switching module doesn't make sense, and on a multilingual site, the categories are translated and associated for the articles, so any url is unique, so for example if you share a url https://mysite.com/recipes/bread what you want is for it to take you to https://mysite.com/recipes/bread
> 
> But if you share https://mysite.com/recetas/pan you want it to take you to https://mysite.com/recetas/pan
> 
> So each url is unique
> 
> I don't find any sense to what you say on a multilingual site, however, if you give me a good example maybe your answer will help in that case, but if we evaluate the possibilities then there are more possibilities of use in the way I give you the example. 

 _Originally posted by @Stuartemk in [#44341](https://github.com/joomla/joomla-cms/issues/44341#issuecomment-2434168658)_

**Comment by brianteeman** [comment] 2024-10-24 10:59
You are assuming that every url will be unique because the names will be different in different in each langauge. That is absolutely not something that can be assumed.

For example all of the following are valid in multiple languages
https://mysite.com/cuisine
https://mysite.com/chef
https://mysite.com/cafe
https://mysite.com/hotel

**Comment by Hackwar** [comment] 2024-10-24 12:26
As @brianteeman wrote, URLs are not unique in each language. Since this still isn't a bug, but expected behavior, I'm still closing this one.

**Closed as completed by Hackwar** 2024-10-24 12:26 UTC
Labels: No Code Attached Yet
