### ISSUE TITLE
[4.0] Create a single article from Menu is not working

### ISSUE THREAD

**Issue by fvdn** [joomla/joomla-cms#23393] opened 2018-12-30 08:19 UTC
### Steps to reproduce the issue
Menu->Main menu->New->Select->Articles->Single Article->Create

### Expected result
The possibilty to make an article

### Actual result
Can only fill the field "Title"
Save button and Save&Cloce button dont work
Only the"Close" button is working.

### System information (as much as possible)
J4 alpha 7

**Comment by infograf768** [comment] 2018-12-30 08:55
Confirmed.
Error:

TypeError: i is null[Learn More]   modal-fields.min.js:1:1856

**Comment by wojsmol** [comment] 2018-12-30 09:46
@infograf768 This is duplicate of https://github.com/joomla/joomla-cms/issues/23260

**Comment by infograf768** [comment] 2018-12-30 10:36
Indeed. Closing

**Closed as completed by infograf768** 2018-12-30 10:36 UTC
Labels: No Code Attached Yet, J4 Issue

**Comment by fvdn** [comment] 2018-12-30 10:41
@all, this item already exists, see: https://github.com/joomla/joomla-cms/issues/23260<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23393">issues.joomla.org/tracker/joomla-cms/23393</a>.</sub>
