### ISSUE TITLE
PHPMail is rejected by the mail server with Error when using PHP 8.X

### ISSUE THREAD

**Issue by RobWilkinsonUK** [joomla/joomla-cms#39473] opened 2022-12-22 13:59 UTC
### PHPMail is rejected by the mail server with an "overlength date field" error when using PHP 8.X. Using PHP 7.4 does not produce the error

Steps to reproduce the issue
Set mail as PHPMail in Global Configuration and set PHP to 8.X

goto "Forgot Logon" and try to get a new password.

Email will be rejected

**Comment by brianteeman** [comment] 2022-12-22 14:00
which EXACT version of php please

**Comment by RobWilkinsonUK** [comment] 2022-12-22 14:03
Both 8.0 and 8.1

**Comment by RobWilkinsonUK** [comment] 2022-12-22 14:04
PHP Mail successfuly sends a "test" email.
SMTP mail works successfully

**Comment by RobWilkinsonUK** [comment] 2022-12-22 14:06
Here is the error messge received:
________________________________________________
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:

  [Rob@RobWilkinson.US](mailto:Rob@RobWilkinson.US)
    This message has been rejected because it has
    an overlength date field which can be used
    to subvert Microsoft mail programs
    The following URL has further information
    http://www.securityfocus.com/frames/?content=/templates/article.html%3Fid%3D61

**Comment by brianteeman** [comment] 2022-12-22 14:56
Sounds like a configuration issue on the server with php 8
Possibly there is no default timezone set
This is something you would need to check with your host

**Comment by RobWilkinsonUK** [comment] 2022-12-22 16:39
I will do that (Check with Hostgator) but why would it work for SMTP Mail and not PHPMail because of that?
Regards,
Rob

**Comment by RobWilkinsonUK** [comment] 2022-12-22 16:50
And why would there be success sending a test email but a rejected mail for the logon email?
REgards,
ROb

**Comment by RobWilkinsonUK** [comment] 2022-12-22 19:13
Hi BrianL
Having reflected on this I have a question. if a mail server is relying on there to be a valid date in the message and Joomla/phpmail is not providing that valid date, why is that not a bug? Is it not a part of the protocol? Either the host mail server, as you suggest, is not following the protocol or joomla/php mail is not.
Regards,
Rob

**Comment by brianteeman** [comment] 2022-12-22 19:23
IF my guess was correct then the problem is with the php confiuguration on the server which is not something joomla or phpmail can do anything about. My guess is based purely on other reports online of this same issue which are not using joomla and in some cases no using phpmail. But were all related to a new version of php which strongly suggests the date value in the php configuration.

**Comment by RobWilkinsonUK** [comment] 2022-12-22 22:06
Hi Brian:
To me it would be strange if there was a mail server dependency for Joomla to work properly or qually if there is a PHP configuration dependency. If such a dependency exists then it ought to be prominently identified somewhere.
Regards,
Rob

**Comment by brianteeman** [comment] 2022-12-23 10:27
I am only making a suggestion for you to investigate further - not interested in a debate

**Comment by RobWilkinsonUK** [comment] 2022-12-23 16:00
My apologies. I thought we were having a technical discussion.

**Comment by joomdonation** [comment] 2022-12-23 16:24
@RobWilkinsonUK Base on the error message, I guess there is something wrong with Date header of the email sent from your site somehow. Normally, value for that Date header is something like **Fri, 23 Dec 2022 23:14:20 +0700**, it is returned by this PHP code in PHPMailer library (which Joomla is using for sending email)

```php
public static function rfcDate()
{
	//Set the time zone to whatever the default is to avoid 500 errors
	//Will default to UTC if it's not set properly in php.ini
	date_default_timezone_set(@date_default_timezone_get());

	return date('D, j M Y H:i:s O');
}
```

Maybe there is something wrong with PHP setting on the server (could be related to `date.timezone` setting in php.ini) and it causes the above code does not return datetime in expected format. 

So in this case, you should contact your hosting provider, ask them to check to see what's wrong with the mail sent from your site. If they said something wrong with Date header of the email as I guessed above, ask them to see what's the value set by Joomla in that email and what's wrong. Ask them to check `date.timezone` setting to see if it is valid and get back to us with their response. Without their answers, it's hard for us to know what's wrong to find a solution

(It is very likely it is an issue with the server because there are many users use Joomla on PHP 8 already, so if this is an issue from Joomla itself, we would have received many  bug reports)

**Comment by brianteeman** [comment] 2023-01-02 19:59
Did you get any response from your host about the php version having a timezone set or not?

**Comment by brianteeman** [comment] 2023-02-06 08:25
I guess this can be closed now

**Comment by RobWilkinsonUK** [comment] 2023-02-06 12:18
I guess, Brian. I worked around it using smtp.Regards RobSent from my iPadOn Feb 6, 2023, at 5:25 AM, Brian Teeman ***@***.***> wrote:﻿
I guess this can be closed now

**Comment by joomdonation** [comment] 2023-02-07 15:41
Closing as state above. Thanks @RobWilkinsonUK for the feedback and thanks @brianteeman for keep monitoring the issue.

**Closed as completed by joomdonation** 2023-02-07 15:41 UTC
Labels: No Code Attached Yet, Information Required
