### ISSUE TITLE
Contact custom repeatable field migration J3 -> J4

### ISSUE THREAD

**Issue by web-tiki** [joomla/joomla-cms#38909] opened 2022-10-06 08:34 UTC
### Steps to reproduce the issue
Install joomla 3 (3.10.11). In contact component there are the contact custom fields : 
![2022-10-06 09_46_12-Contacts - Joomla test - Administration — Firefox Developer Edition](https://user-images.githubusercontent.com/8065876/194260339-cda43d4a-74dd-473d-8e89-02bd15bff3bd.png)

Create a repeatable custom field in contact component : 
![Firefox_Screenshot_2022-10-06T07-59-02 895Z](https://user-images.githubusercontent.com/8065876/194265043-9beca9bc-8fe7-44f5-90a5-8bf34d6d8e19.png)

Upgrade to joomla 4 (4.2.3) :
![Firefox_Screenshot_2022-10-06T08-16-11 762Z](https://user-images.githubusercontent.com/8065876/194260711-6b54d893-00c5-487d-a25a-f37b6c2f5f5a.png)

During migration there is a 500 error : 
![Firefox_Screenshot_2022-10-06T08-17-28 095Z](https://user-images.githubusercontent.com/8065876/194260845-602e8c85-9657-4f04-8da1-38edb4863216.png)

When connecting to admin, the fields for contact component have disapeared from the menu : 
![2022-10-06 10_17_57-Window](https://user-images.githubusercontent.com/8065876/194260990-70c9e4ec-0a0c-43e5-b0f1-7eb16ce92fa2.png)

### Expected result
No error during migration to joomla 4.
After migrating to J4, the contact custom fields and fields group should be in the menu like in this fresh J4 instalation :  
![2022-10-06 10_24_55-Window](https://user-images.githubusercontent.com/8065876/194261410-bcc16fed-a2ac-4ad2-b6eb-6107884252f8.png)

### Actual result

When connecting to admin, the fields for contact component have disapeared from the menu : 
![2022-10-06 10_17_57-Window](https://user-images.githubusercontent.com/8065876/194260990-70c9e4ec-0a0c-43e5-b0f1-7eb16ce92fa2.png)

### System information
The test was made on a laragon local environement with php 7.4.30
![2022-10-06 10_38_03-Window](https://user-images.githubusercontent.com/8065876/194264282-0a7580bc-5922-4878-8c35-cc73d267ca9a.png)

### Additional comments
According to this discussion : https://github.com/joomla/joomla-cms/discussions/36944
the issue is related to the repeatable field. The field migration can be done by going from J3 to J4.0.3 then to 4.1 then to 4.2

**Comment by nikosdion** [comment] 2022-10-06 10:51
Nope, my PR has nothing to do with it.

The Repeatable field no longer exists in Joomla 4. It has been replaced by the Subform field. However, neither the definition nor the data stored by the two field types is compatible with each other. During the migration the repeatable fields will just disappear.

There was a further issue (probably caused by a third party plugin) during the migration as the screenshot shared. This means that Joomla never finished its migration which explains why parts of it are broken.

I would recommend removing the migrated site's files and database data (important!), restore it from a backup, disable all third party system plugins and run the migration again. The only observable artefact will be that the repeatable field is no longer working, as expected, this is something which was happening since the early 4.0 betas long before my PR.

**Comment by web-tiki** [comment] 2022-10-10 08:09
@nikosdion Thank you for all this information.
I will do more tests and try with another development environment without OPcache. 
I followed the changes with the repeatbable field from J3 to J4 as I use it extensively. I didn't have this issue on other sites as don't usually use them with the contact component.
Also I use your "rather well-known backup extension" almost everyday. Thank you :)

**Comment by web-tiki** [comment] 2022-10-20 13:08
The issue doesn't seem to be related to OPCache as is is disabled on my laragon system.
I have reproduced the same issue on a different server / environement without laragon and with php 7.3.
More system info : 
![2022-10-20 15_06_50-Window](https://user-images.githubusercontent.com/8065876/196957082-a76869e0-9569-42e2-9150-3ead3d3436e3.png)

**Comment by joomdonation** [comment] 2022-11-18 04:17
Closing because this is an duplicate issue. @web-tiki If you still have this problem, see https://github.com/joomla/joomla-cms/issues/37177#issuecomment-1319515680 for a reason and a workaround while waiting for official solution.

**Closed as completed by joomdonation** 2022-11-18 04:17 UTC
Labels: No Code Attached Yet

**Comment by richard67** [comment] 2022-11-19 08:37
There is a pull request now which solves this issue: #39245 . Please test it and report back your test results in the issue tracker using the blue "Test this" button. When the pull request has 2 good tests, it will be marked to be merged and then can be part of the next release. Thanks in advance.
