### ISSUE TITLE
Error with drag and drop installer - NULL

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-cms#15143] opened 2017-04-06 22:20 UTC
### Steps to reproduce the issue
Create a zip file which plainly won't install in Joomla!
Use the new drag and drop installer (which is a great addition btw)
Drag the file into the dotted lines and release.

### Expected result
An error message saying it doesn't work for example the following:

Warning

JInstaller: :Install: File does not exist /home/*****/******/tmp/install_58e6bb5c4cd59/com_*****/******.class.php
Component Update: Failed to copy site files.
JInstaller: :Install: File does not exist /home/*****/******/tmp/install_58e6bb5c4cd59/com_*****/******.class.php
×
Error

Error installing component

### Actual result
It has a popup error saying "null".  This is not good feedback, if it must popup like that (some would find it intrusive) then it should contain relevant information.  I'd prefer it to be styled a little better too, but the priority should be the error message.  If you want to style it nicely this is pretty good https://limonte.github.io/sweetalert2/

### Additional comments
I tried this several times in several browsers.  The first few times I got the null error message, then I got the correct error message without the popup, and then I got a success message.  I'm quite confused but this is still very concerning.

1. "Null" Error appears in popup for drag and drop, but is normal for upload button.
2. Error does not appear in popup, appears in normal place.  Same file, not sure why.  Also reports success and two different errors.  Bit concerning.
3. Success message appears in popup, but it cannot have been sucessful, I am deliberately installing half an extension.
 ![screen shot 2017-04-06 at 22 19 27](https://issues.joomla.org/uploads/1/47cb5cda6e183ab83e3b38a946c145a2.png)
[systeminfo-2017-04-06T17-11-26-05-00.txt](https://issues.joomla.org/uploads/1/3fd3b4205af0138fdef0c57f8537835d.txt)![screen shot 2017-04-06 at 22 19 27](https://issues.joomla.org/uploads/1/26006ae2a0fadc9d34af2c1ea3f5c3ac.png)![screen shot 2017-04-06 at 22 19 27](https://issues.joomla.org/uploads/1/61f7e0a651df48501d66ddc18ef432ee.png)

The only difference I could see is that I tried using the old method inbetween, could that have triggered some sort of a half fix ?

**Comment by brianteeman** [comment] 2017-04-07 09:42
I could not confirm this

When trying to install a random zip file on my computer using drag and drop I got the following messages as I would expect

<img width="815" alt="screenshotr10-41-34" src="https://cloud.githubusercontent.com/assets/1296369/24794799/e651bb8e-1b7e-11e7-903a-c82c8dc79782.png">

**Comment by uglyeoin** [comment] 2017-04-07 11:22
@brianteeman because I have provided screenshots can we find a way to request more testers?  Somehow there is a way to get this to occur.  As stated, I got a variety of different results, but I can't understand what caused the differences.  What browser were you using?

**Comment by franz-wohlkoenig** [comment] 2017-04-07 11:27
Cannot confirm, got same Result as @brianteeman. Tested on:
### System information
Joomla! 3.7.0-beta4 (nightly Build)
macOS Sierra, 10.12.4
Firefox 52 (64-bit), Chrome 57, Safari 10.1
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by brianteeman** [comment] 2017-04-07 12:37
it could even be an issue with the specific zip file you are using. @uglyeoin

**Comment by asika32764** [comment] 2017-04-07 12:44
@uglyeoin What is the sha version did you test it?

I have fixed the error message in https://github.com/joomla/joomla-cms/pull/15135/files#diff-5222eed747ee078c931aff7cd5f37b59R131 , all error sucess result will redirect and show flash messages.

The alert will only appear if request get failure with status which is not 200, could you check is it the php upload limit issue?

**Comment by asika32764** [comment] 2017-04-07 12:51
Cannot confirm with zip file larger than upload limit, see:

![p-2017-04-07-001](https://cloud.githubusercontent.com/assets/1639206/24800717/dc404520-1bd3-11e7-8f80-5a1d65f31c4b.jpg)

Also I disabled the Apache and make a fail request, the alert is the HTTP status text but not NULL:

![p-2017-04-07-002](https://cloud.githubusercontent.com/assets/1639206/24800742/f6f80038-1bd3-11e7-836d-093d82b7cbd9.jpg)

**Comment by uglyeoin** [comment] 2017-04-07 12:57
@brianteeman I would include it but it's half of a commercial extension.  Using the same file I got differing results so I'm not entirely sure what is going on.  Will come back if I find more information and will ask some people I know to see if they can achieve the same result.

**Comment by uglyeoin** [comment] 2017-04-07 12:58
It was not due to the PHP size as I had installed the full extension so it would have been below that.  We can rule out that as the variable.

**Comment by asika32764** [comment] 2017-04-07 13:00
Maybe you can get the console screenshot to let us know the Ajax error message, HTTP status and response.

**Comment by uglyeoin** [comment] 2017-04-07 13:05
@asika32764 that will only work if it performs in the way it originally did and it does not seem to be any more.  

However, I have still raised a secondary issue (probably should raise another ticket) where the component says: 

**Installation successful. Next find ****** in the Components menu, and finish the installation process.**

and

**"Error

Error installing component**

and

**Warning

JInstaller: :Install: File does not exist /home/*********/********/tmp/install_58e78df3c616a/com_*******/component.class.php
Component Update: Failed to copy site files.**

**Comment by uglyeoin** [comment] 2017-04-07 13:10
@brianteeman maybe if there is an XML file present that is a difference between your test and mine.  Just trying to work out what variables are different.  My site is on Siteground not localhost.

**Comment by Quy** [comment] 2017-04-08 23:35
When the uploaded file is larger than the maximum upload size, the joomla logo spinner displays indefinitely:
![spinner](https://cloud.githubusercontent.com/assets/368084/24833283/c9679b60-1c78-11e7-8e7f-fb4d41c3534b.jpg)
in the error log file:
> PHP Warning:  POST Content-Length of 9722217 bytes exceeds the limit of 8388608 bytes in Unknown on line 0

in the web console:
>TypeError: res.data is undefined

Tested in Firefox 52.0.2 Windows 10 with the latest staging version as of 4/8.

**Comment by asika32764** [comment] 2017-04-09 03:10
This error caused by `post_max_size` not `upload_max_size`

However, php only raise a warning so Joomla cannot catch it.

The select file upload will also appear a non-standard warning message, see:

![p-2017-04-09-001](https://cloud.githubusercontent.com/assets/1639206/24834353/11332030-1d15-11e7-876a-4d0ba0205f24.jpg)

**Comment by Quy** [comment] 2017-04-24 22:45
Cannot replicate with RC4.

**Comment by Quy** [comment] 2017-05-19 16:38
Unable to reproduce in v3.7.1. 

@uglyeoin With your test file, are you able to upload it without the error in v3.6.5 and not in v.3.7.1?

**Comment by uglyeoin** [comment] 2017-05-20 15:40
I can try that, but given the error was inconsistent anyway I'm a tad confused.  Surely using the same file should heed the same results.  Maybe it part installs or something.  Will test and come back to you.

**Comment by brianteeman** [comment] 2017-05-22 09:17
I am closing this at this time - it can always be re-opened if reproducable

**Closed by brianteeman** 2017-05-22 09:17 UTC
Labels: No Code Attached Yet
