### ISSUE TITLE
Reloading com_config with stuttering effect

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#37697] opened 2022-04-29 21:36 UTC
### Steps to reproduce the issue
Reload the view com_config when no description text are visible
https://github.com/joomla/joomla-cms/pull/37671#issuecomment-1110443357

### Expected result
Loading as usual, with out any description and without stuttering

### Actual result
descriptions are visible for a moment when the view ist reloaded

### System information (as much as possible)
4.x

**Comment by brianteeman** [comment] 2022-04-29 22:53
The problem is that descriptions are hidden by running js to add a d-none. So the description is rendered and then hidden once the js has been run.

It should be fixed by adding the d-none into the markup and not in the js.

In other words the description is currently visible by default and then hidden by js once the js has loaded
It should be hidden by default and then only toggled in the js when the button is clicked

**Comment by toivo** [comment] 2022-04-30 00:49
Shouldn't the descriptions be displayed on mouse hover action?  Those descriptions are useful and necessary, they should be displayed by default or on mouse hover action, otherwise they are useless.  If they serve some accessibility function I am not privy to, it should be stated clearly.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37697">issues.joomla.org/tracker/joomla-cms/37697</a>.</sub>

**Comment by toivo** [comment] 2022-04-30 01:24
Oops, please ignore the above comment. Just found the prominent Toggle Inline Help button...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37697">issues.joomla.org/tracker/joomla-cms/37697</a>.</sub>

**Comment by brianteeman** [comment] 2022-04-30 07:23
Please test #37699

**Closed as completed** 2022-04-30 08:18 UTC
Labels: No Code Attached Yet, Backend Template, good first issue
