### ISSUE TITLE
Language flags links in article list not removing default lang code when requested

### ISSUE THREAD

**Issue by Giuse69** [joomla/joomla-cms#26480] opened 2019-10-04 22:06 UTC
### Steps to reproduce the issue
A multilingual site with "Remove URL language" options set to YES in _system - language filter_ plugin to remove default language tag from URL.
SEF enabled in global configuration.
Create an article in default language (es. "en"), an article in non default language (es. "it") and associate them.
Create a menu item "Article list" to show articles.
Select NON default language in front-end (it).
In the article list, after the article title, there is the language flag with a link that points to associated article in the default language (en).

### Expected result
The URL of the language flag link does NOT contain the default language tag in the URL (no "/en") since the system plugin requires that.

### Actual result
The URL of the language flag link DOES contain the default language tag ("<site>/**en**/...")

### System information (as much as possible)
Joomla 3.9.12
Linux

**Comment by brianteeman** [comment] 2019-10-04 23:09
and what is the actual link displayed in the urlbar AFTER you have clicked the language flag

**Comment by Giuse69** [comment] 2019-10-05 07:04
After click, the joomla router redirects 301 to correct url without the default language flag. it seems to me that already the displayed link should take into account the system language setting.
Same behavior in single article page (just found now that)
Thanks

**Comment by richard67** [comment] 2019-10-05 08:54
As far as I understand the router it is by design. The router needs the language code in the link so it knows where to redirect to, then the language code is removed at the end if it is the default language. So I don’t think this can be easily changed.

**Comment by brianteeman** [comment] 2019-10-05 08:56
This is working as intended. If you search hard enough you will see several other discussions on this which go into more detailed explanation

**Comment by richard67** [comment] 2019-10-05 09:18
That was what I tried to say, that it works as intended. Thanks for confirming my understanding.

**Comment by Giuse69** [comment] 2019-10-05 09:34
Yes, but it is inconsistent: the language flag links in the language switcher module work better and default language tag is stripped **before** displaying the link.
The same flag link in the page body does not and relies on later router redirect.

**Comment by ReLater** [comment] 2019-10-05 13:08
Duplicate: https://github.com/joomla/joomla-cms/issues/23144

And all related PRs failed.

**Comment by Giuse69** [comment] 2019-10-05 13:25
I don't think so: that PR was about mod_language: with current Joomla 3.9.12 I see that problem solved: the lang mod switcher presents ULR without def lang code, can you please confirm?
Current Issue is not for mod_language but for the body where a flag link appears close to article title, in single article view or in article list view.

**Comment by Giuse69** [comment] 2019-10-06 09:33
Also href in the `<head>` is already set correctly _without_ the default language, so in this issue I am proposing to aling the construction of the flag link in the page as it is already done in mod_language and in href. Hope that now is more clear.

**Comment by infograf768** [comment] 2019-10-08 08:36
Clear enough. Looking into this.

**Comment by infograf768** [comment] 2019-10-08 08:50
Deleted my former post.
There is no change for the switcher. The sef prefix does not display in the switcher ONLY when the page is already in the default language AND it is the Home Page.
As @ReLater said, we failed solving this (and not sure at all it is even possible).

**Comment by Giuse69** [comment] 2019-10-09 18:22
Not what I see in my sites.
An example: English and Italian languages, default English with associated articles.
I go to an article in Italian and this is what I see:

page URL = _https://site/**it**/foto/notizie/2040-confronto_
flag link in lang switcher = _https://site/photo/news/2041-comparison_
href in head = _href="https://site/photo/news/2041-comparison"_
flag link in the article ("also available in") = https://site/**en**/photo/news/2041-comparison

I added ** around lang tags

**Comment by infograf768** [comment] 2019-10-10 06:41
I absolutely can't reproduce the link you get in the switcher when hovering the flag (en-GB is default). Same in J4.
 
Page url: 
`http://localhost:8888/installmulti/trunkgitnew/fr/catblogfrench/article-fr-fr`

Link for the English flag in the switcher: 
`http://localhost:8888/installmulti/trunkgitnew/en/catblogenglish/article-en-gb`

Alternate in head: 
`<link href="http://localhost:8888/installmulti/trunkgitnew/catblogenglish/article-en-gb" rel="alternate" hreflang="en-GB" />`

LInk in the info-block of the article:
`http://localhost:8888/installmulti/trunkgitnew/en/catblogenglish/article-en-gb`

I can here modify the flag link in the article info-block to get rid of the sef prefix.
I modified the file `/layouts/joomla/content/info_block/associations.php`

```
<?php
/**
 * @package     Joomla.Site
 * @subpackage  Layout
 *
 * @copyright   Copyright (C) 2005 - 2019 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('JPATH_BASE') or die;

$default_lang          = JComponentHelper::getParams('com_languages')->get('site', 'en-GB');

// Get default lang prefix param from languagefilter plugin
$plugin                = JPluginHelper::getPlugin('system', 'languagefilter');
$params                = new JRegistry($plugin->params);
$remove_default_prefix = $params->get('remove_default_prefix', 0);
?>

<?php if (!empty($displayData['item']->associations)) : ?>
<?php $associations = $displayData['item']->associations; ?>

<dd class="association">
	<?php echo JText::_('JASSOCIATIONS'); ?>
	<?php foreach ($associations as $association) : ?>
		<?php $link = JRoute::_($association['item']); ?>
		<?php if ($remove_default_prefix && $association['language']->lang_code === $default_lang) : ?>
			<?php $link = preg_replace('|/' . $association['language']->sef . '/|', '/', $link, 1); ?>
		<?php endif; ?>
		<?php if ($displayData['item']->params->get('flags', 1) && $association['language']->image) : ?>
			<?php $flag = JHtml::_('image', 'mod_languages/' . $association['language']->image . '.gif', $association['language']->title_native, array('title' => $association['language']->title_native), true); ?>
			&nbsp;<a href="<?php echo $link; ?>"><?php echo $flag; ?></a>&nbsp;
		<?php else : ?>
			<?php $class = 'label label-association label-' . $association['language']->sef; ?>
			&nbsp;<a class="<?php echo $class; ?>" href="<?php echo $link; ?>"><?php echo strtoupper($association['language']->sef); ?></a>&nbsp;
		<?php endif; ?>
	<?php endforeach; ?>
</dd>
<?php endif; ?>
```

Here is the modified file that you can test:

[associations.php.zip](https://github.com/joomla/joomla-cms/files/3710677/associations.php.zip)

Not sure of the eventual consequences though.

**Comment by infograf768** [comment] 2019-10-11 05:53
@ReLater 
What do you think about this patch?

**Comment by Giuse69** [comment] 2020-03-04 19:50
Hi, instead of modifying associations.php, why not simply modify helper.php at the end with code

`if ($remove_default_prefix && isset($languages[$default_lang]->link))
{
$languages[$default_lang]->link = preg_replace('|/' . $languages[$default_lang]->sef . '/|', '/', $languages[$default_lang]->link, 1);
self::setLanguageCookie($default_lang);
}`
?

**Comment by Bakual** [comment] 2020-03-07 19:24
I'm closing this issue as it is intended behavior and not a bug.

**Closed as completed by Bakual** 2020-03-07 19:24 UTC
Labels: No Code Attached Yet
