### ISSUE TITLE
Wrong Joomla System info regarding PHP memory 

### ISSUE THREAD

**Issue by taantrik** [joomla/joomla-cms#7001] opened 2015-05-21 02:50 UTC
This is what PHPinfo() states.
![screenshot_1](https://cloud.githubusercontent.com/assets/10177180/7740580/87a46d3a-ff91-11e4-8144-a27409f4c4df.jpg)
This is what a test script (please google   with "phpmeminfo.php joomla" term) states:
![screenshot_2](https://cloud.githubusercontent.com/assets/10177180/7740611/e02256a2-ff91-11e4-8379-71b522bc09c9.jpg)
Joomla System info in backend gives wrong info regarding PHP memory. Here is screenshot:
![screenshot_3](https://cloud.githubusercontent.com/assets/10177180/7740634/24cd86aa-ff92-11e4-9ed2-43044393824a.jpg)

**Comment by bertmert** [comment] 2015-05-21 05:17
Cannot confirm. I've made some tests changing memory_limit online (.htaccess and php_value) and local (XAMPP, php.ini). Always got correct informations.

Joomla gets it's PHP informations via PHP function

```
phpinfo(INFO_GENERAL | INFO_CONFIGURATION | INFO_MODULES);
```

Maybe you started your script (whatever it is) from the wrong directory?

> please google with "phpmeminfo.php joomla" term

Sorry, I found nothing relevant.

**Comment by Bakual** [comment] 2015-05-21 06:40
Did you run your script from the administrator folder? It may be that you have different memory limits depending on the folders when there are overriding rules in custom php.ini files and such.

As said by @bertmert the information is retrieved directly by `phpinfo()` and just displayed a bit different. So I don't see how that could be wrong.

Closing as not a core issue and likely related to some server configuration. Feel free to reopen this issue if you found that it's indeed caused by Joomla core.

**Closed by Bakual** 2015-05-21 06:40 UTC
