### ISSUE TITLE
copy Article, Menus as you can do with Modules with one click

### ISSUE THREAD

**Issue by lenusch** [joomla/joomla-cms#15161] opened 2017-04-07 20:28 UTC
Actually for Articles and Menus you have to use the Batch Tool to copy Item. 
In Modules Area its easier with the extra Button on top. 
But what about a custom Icon within the Menu / Article row which easily let you copy the Content. 
Please see Screenshot. 
This would make things easier. ![screen shot 2017-04-07 at 20 28 43](https://issues.joomla.org/uploads/1/d790616c2523453949eafecb114d3e35.jpg)

**Comment by brianteeman** [comment] 2017-08-18 17:23
I am closing this. It would be unusual to want to create an exact duplicate of an article. It would be more likely to open an existing one, make some edits and then click on Save as Copy.

**Closed by brianteeman** 2017-08-18 17:23 UTC
Labels: No Code Attached Yet
