### ISSUE TITLE
Client-side form validation (JHTML::_('behavior.formvalidation');) not working on tablet devices

### ISSUE THREAD

**Issue by achapetta** [joomla/joomla-cms#4205] opened 2014-09-01 22:28 UTC
Client-side form validation (JHTML::_('behavior.formvalidation');) is not working on tablet devices. 

No validation error appears on tablets devices when a submit button is clicked and the input element is empty even when the necessary classes are specified. As a result, the form proceeds with processing without an error. The validation should display an error message such as "Please fill out this field." when the submit button is clicked and the textbox is empty.

The system being used is an iPad (3rd generation). I used both Chrome and Safari to test the error. I'm currently running Joomla 3.3.3.

**Comment by rajeshrajkumar9** [comment] 2015-04-11 11:43
Hello,

I have contact form in joomla 2.5 website in which i would like to validate User inputs / data should be sanitized from hazardous characters and validated in the server-side.So i would like to know the necessary customization of the particular file.

he Contact form is available under Contact Us menu. As Name, Subject, Message fields are not validated properly, if IFRAME is injected in these fields form gets submitted successfully.

Yes, it is from component com_contact i want to validate from server side.
The path is com_contact/model/contact.xml

<?xml version="1.0" encoding="UTF-8"?>
<form>
<fieldset name="contact" addrulepath="components/com_contact/models/rules" label="COM_CONTACT_FORM_LABEL">
<field name="contact_name"
type="text"
id="contact-name"
size="30"
description="COM_CONTACT_CONTACT_EMAIL_NAME_DESC"
label="COM_CONTACT_CONTACT_EMAIL_NAME_LABEL"
filter="string"
required="true"
/>
I want to validate the contact_name in this field

**Comment by JohnnyDevNull** [comment] 2015-04-29 11:17
I can confirm to this that the form validation for safari on IOS and the chrome on android is broken, because they doesn't support the native html5 form validatoin.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4205">issues.joomla.org/joomla-cms/4205</a>.</sub>

**Comment by roland-d** [comment] 2015-11-08 18:35
Hello @achapetta 

Thank you for your contribution.

The last comment here was on 29th April. So the question is, Is this issue/pull request still valid?
If no reply is received within 4 weeks we will close this issue.

Thanks for understanding! <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4205">issues.joomla.org/joomla-cms/4205</a>.</sub>

**Comment by brianteeman** [comment] 2015-12-17 11:12
Closed due to lack of response for further information - it can always be reopened if that is provided<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4205">issues.joomla.org/joomla-cms/4205</a>.</sub>

**Closed by brianteeman** 2015-12-17 11:12 UTC
Labels: No Code Attached Yet
