### ISSUE TITLE
Resizing WYSWIG editor goes under the buttons.

### ISSUE THREAD

**Issue by aDaneInSpain** [joomla/joomla-cms#8886] opened 2016-01-12 17:06 UTC
This gif best shows the issue.

https://gyazo.com/188e81f4729a9e2650a8773459b6548d

**Comment by dgt41** [comment] 2016-01-13 12:08
should be easy to fix by setting the index of the div class, will come with some code

**Comment by aDaneInSpain** [comment] 2016-01-13 12:16
The question is if it should be allowed to _cover_ the buttons? IMO it should either push the buttons somewhere else or be prevented from being resized passed them.

**Comment by dgt41** [comment] 2016-01-13 12:32
Hmm, you are right

**Comment by brianteeman** [comment] 2016-02-15 17:55
@dgt41 have you been able to find a solution to this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8886">issues.joomla.org/joomla-cms/8886</a>.</sub>

**Comment by dgt41** [comment] 2016-02-15 18:27
@brianteeman there's nothing to solve here :) The solution is to simply disable the option for resizing in the plugin. Tinymce is clever enough to deal with responsive templates so will always take the parent div width. the problem is that when you enable this option, the editor can grow above the parent div dimensions and this will be trivial to fix (especially without breaking every known template out there!)

**Comment by brianteeman** [comment] 2016-02-15 18:49
Are you saying it should be closed then?

**Comment by brianteeman** [comment] 2016-03-12 11:37
Based on comments above i am going to close this as expected behaviour. If a user wants to prevent this on their own site then thy can disable editor resizing in the editor plugins<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8886">issues.joomla.org/joomla-cms/8886</a>.</sub>

**Closed** 2016-03-12 11:38 UTC
Labels: No Code Attached Yet
