### ISSUE TITLE
infinite loop: Default menu item (home) set to category blog which has non public access level

### ISSUE THREAD

**Issue by Hg347** [joomla/joomla-cms#11697] opened 2016-08-20 20:27 UTC
There is an infinite loop when attempting to load a joomla url, if
- the site is in offline mode
- the default link destination is a category with restricted access level (non-public)
### Steps to reproduce the issue
1. Set your site to  "Offline mode" in Joomla config
2. create category with access level "registered"
3. create a menu with menu item 
4. let menu item point to category blog with category created at step 1
5. set menu item as default
6. open website in browser as unregistered visitor
### Expected result

There are several alternatives to solve this:
1. abort attempt to set the default page to an restricted item
   present an error message to the user.
2. detect this misconfiguration on page load and abort it with "Forbidden" 403 error
### Actual result
- The result is a long loading time which ends in firefox error: "error: redirect error"
  "Die aufgerufene Website leitet die Anfrage so um, dass sie nie beendet werden kann."
- If the website is not in offline mode, the result is "404 - Category not found"
- If the default destination is an article instead of a category, the error is
  short text on the offline site " Error You are not authorised to view this resource."
- In online mode of joomla, the error is "You are not authorised to view this resource."
### System information (as much as possible)

Joomla 3.6.2, Apache 2.4.20, PHP 7.0.6 (cgi-fcgi),
User Agent Mozilla/5.0 (Firefox 48.0)
### Additional comments

Would be nice to have a common error handling and error message in all cases:
- online / offline joomla site
- restricted article as default destination
- restricted category as default destination

**Comment by brianteeman** [comment] 2016-08-27 22:03
Confirmed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11697">issues.joomla.org/joomla-cms/11697</a>.</sub>

**Comment by franz-wohlkoenig** [comment] 2017-01-31 08:34
Looks like Issue is solved cause on 3.7-staging got `403 -  You are not authorised to view this resource.`

**Comment by brianteeman** [comment] 2017-05-21 09:14
I am closing this at this time as it has been reported to have been fixed elsewhere - if that is not the case it can always be reopned

**Closed by brianteeman** 2017-05-21 09:14 UTC
Labels: No Code Attached Yet
