### ISSUE TITLE
[5.0] Bug in list of articles of Tag

### ISSUE THREAD

**Issue by 1inkin** [joomla/joomla-cms#41493] opened 2023-08-28 07:16 UTC
### Steps to reproduce the issue
1. create tags Tag1 and Tag2
2. create an articles with both tags Tag1 and Tag2
3. create menu Tagged Items with both tags Tag1 and Tag2 with Match Type = All
4. create Popular Tags Module
5. Joomla Global Configuration parameter SEF = Yes
6. on frontend page of menu Tagged Items select some tag in Popular Tags Module

### Expected result
the page with articles of the selected tag is displayed

### Actual result
a page with no articles found is displayed

**Comment by alikon** [comment] 2023-08-28 07:26
please stop open the same issue twice 
duplicate of #41179

**Closed as completed by alikon** 2023-08-28 07:26 UTC
Labels: No Code Attached Yet
