### ISSUE TITLE
Login-Logout and hidden menus

### ISSUE THREAD

**Issue by BurtNL** [joomla/joomla-cms#11183] opened 2016-07-18 21:51 UTC
I am experiencing issues with menus which are set to 'Registered' and which are not hidden after logging out.
Some of my menus are only visible for registered users, so after logging in those menus will become visible.
When the user logs out the menus should be hidden again, but that is not the case anymore.

#### Steps to reproduce the issue
Install a fresh Joomla 3.6.0 with standard demo content.
Create a menu Login, set to Guest, connect to Users->login form.
Create a menu TEST, set to Registered, attach any article.
Create a menu Logout, set to Registered, connect to Users->logout, set Options to Home.

Visit the frontend, the menu Home and Login should be visible.
Then login, the menus TEST and Logout should become visible.
Then logout and check which menus are still visible.
Home and Login should become visible, but TEST and Logout are still visible.

I noticed the same issue with an updated Joomla 3.5.1 website to Joomla 3.6.0.
In 3.5.1 it worked perfectly, in 3.6.0 it seems to be broken.

**Comment by ggppdk** [comment] 2016-07-19 00:20
That would happen if **access levels** are not assigned to correct **usergroups**

Visit
users / access levels
- is "public"  access level assigned to "public" usergroup ?
- is "guest"  access level assigned to "guest" usergroup ?
- is "registered"  access level assigned to "registered" usergroup  **and to which other groups???**

**Comment by BurtNL** [comment] 2016-07-19 05:19
Thanks ggppdk for your reply.

is "public" access level assigned to "public" usergroup ? **YES**
is "guest" access level assigned to "guest" usergroup ? **YES**
is "registered" access level assigned to "registered" usergroup and to which other groups??? **Manager, Registered, Super Users
**

All settings are 'as is' after installing a fresh J 3.6.0.
An updated J 3.5.1 (with same access levels as above) is showing the same problem now after update to J 3.6.0, was good before.

I also checked Global Configuration > Users, where Guests are set to the Guest User Group.


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11183">issues.joomla.org/joomla-cms/11183</a>.</sub>

**Comment by brianteeman** [comment] 2016-07-20 17:50
Can you please check and see what the setting is for Guest User Group is in the User:Options 
It should be guest<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11183">issues.joomla.org/joomla-cms/11183</a>.</sub>

**Comment by BurtNL** [comment] 2016-07-20 19:40
@brianteeman The setting in System > Global Configuration > Users > Guest User Group = Guest

![screen shot 2016-07-20 at 14 35 38](https://issues.joomla.org/uploads/1/671ace36be35db35b56aac70c96496d7.png)

And the menu settings are these:

![screen shot 2016-07-20 at 14 36 00](https://issues.joomla.org/uploads/1/80905b9cb7cb7e831ba1b04213e8d104.png)

In the Options of the menu Login, in Choose Login Redirection Type, I have tried the options Menu Item and Internal URL.
On the frontend it gives me the same problem as stated in my first post.

Just tried it with a new fresh install of J3.6.0, standard demo content, all other settings 'as is', same result.
In my case not working properly.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11183">issues.joomla.org/joomla-cms/11183</a>.</sub>

**Comment by infograf768** [comment] 2016-07-28 18:54
can you test with a clean install of staging?

**Comment by brianteeman** [comment] 2016-08-15 14:35
@BurtNL can you please respond to the question above or this will be closed in a few weeks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11183">issues.joomla.org/joomla-cms/11183</a>.</sub>

**Comment by BurtNL** [comment] 2016-08-17 16:59
This issue is solved due to the update to 3.6.2.
In 3.5.1 all worked fine with hidden menu's, usergroups and access levels. After the update to 3.6.0 this became broken, as I reported in the first post. Yesterday I updated to 3.6.2 and now everything is working like I expected, as in 3.5.1. And I haven't changed any setting regarding this issue, all is like I already had set in 3.5.1. @roland-d and JUG010 spend some time on this as well yesterday at the JUG. Thanks!

So this issue may be closed.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11183">issues.joomla.org/joomla-cms/11183</a>.</sub>

**Comment by andrepereiradasilva** [comment] 2016-08-17 17:03
so please close it, the issue is yours :)

**Comment by brianteeman** [comment] 2016-08-17 17:52
Closed

**Closed by brianteeman** 2016-08-17 17:52 UTC
Labels: No Code Attached Yet
