### ISSUE TITLE
Uninstall Weblinks

### ISSUE THREAD

**Issue by coolman01** [joomla/joomla-cms#5903] opened 2015-01-28 09:11 UTC
#### Steps to reproduce the issue
In extension manager uninstall weblinks

#### Expected result

All weblinks files (except search) unistalled

#### Actual result

Main files uninstalled, weblinks "package" not unistalled

#### System information (as much as possible)
PHP Built On	Windows NT RESOLVE-2010 6.1 build 7601 (Windows 7 Business Edition Service Pack 1) i586
Database Version	5.5.32
Database Collation	utf8_general_ci
PHP Version	5.4.19
Web Server	Apache/2.4.4 (Win32) OpenSSL/0.9.8y PHP/5.4.19
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 3.4.0-beta1 Beta [ Ember ] 27-January-2015 20:00 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

**Comment by brianteeman** [comment] 2015-01-28 10:26
Was this a site you upgraded to 3.4beta 1 or a fresh install<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5903">issues.joomla.org/joomla-cms/5903</a>.</sub>

**Comment by coolman01** [comment] 2015-01-28 11:45
An Upgrade from 3.6

**Comment by brianteeman** [comment] 2015-01-28 15:30
Is this the error message that you get

Warning
Package Uninstall: Missing manifest file<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5903">issues.joomla.org/joomla-cms/5903</a>.</sub>

**Comment by coolman01** [comment] 2015-01-28 15:31
Yes

**Comment by brianteeman** [comment] 2015-01-28 19:20
Marking as confirmed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5903">issues.joomla.org/joomla-cms/5903</a>.</sub>

**Comment by wilsonge** [comment] 2015-01-28 19:41
Raising priority to urgent so it is a blocker for 3.4. Should be fixed before RC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5903">issues.joomla.org/joomla-cms/5903</a>.</sub>

**Comment by mbabker** [comment] 2015-01-28 19:51
Anyone care to take a guess why [this check](https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_admin/script.php#L1244-L1254) is saying the weblinks.php file doesn't exist (which is how the package manifest would be removed)?  And yes, the package manifest is in the update package.

**Comment by wilsonge** [comment] 2015-01-29 01:42
@mbabker isn't that check for when we are updating the CMS and won't get called when you uninstall weblinks through extension manager after updating to beta?

**Comment by mbabker** [comment] 2015-01-29 01:44
The issue is the manifest is not present, hence the error message @brianteeman posted.  I did a test update on a local 3.3.6 install and found that the manifest was not in place.  The only possible ways for that to happen is the file not included in the package or the file being deleted by the update script.

**Comment by mbabker** [comment] 2015-01-29 02:00
Making things more intriguing, I've tested 2 updates via the update component and both of those don't place the weblinks manifest in the filesystem.  I tried an update through the Extension Manager's Install from URL option and it showed up.

**Comment by mbabker** [comment] 2015-02-11 13:57
I just realized why this is failing.  The update server is serving the Full install package versus the update package.  The full package doesn't have the weblinks package manifest since weblinks isn't installed for new installations.

**Comment by mbabker** [comment] 2015-02-11 14:29
The update server has been updated to serve the update package now versus the full package.  Please test updates and uninstalling weblinks now.

When updating, please ensure the package URL displayed on the update screen indicates it is the update package.  If it still says full, your site is pulling from a CDN node that has not yet refreshed.

**Comment by infograf768** [comment] 2015-02-11 17:28
@test

Works fine now.
Remains to get it on JED.

**Closed** 2015-02-11 17:28 UTC
Labels: No Code Attached Yet
