### ISSUE TITLE
[4.0] Administrator: Misleading tooltip for status in modules list (administrator) 

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#26660] opened 2019-10-19 09:55 UTC
### Steps to reproduce the issue
In backend insert a custom administrator modul and put in a start date. After saving the tooltip of the status in the modules list will show a start and! a finish date although a finished date was not specified.

**Comment by infograf768** [comment] 2019-10-21 08:46
Confirmed
<img width="391" alt="Screen Shot 2019-10-21 at 10 36 57" src="https://user-images.githubusercontent.com/869724/67189596-cb4b8180-f3ee-11e9-86e2-171e462550f0.png">

It is the same issue for admin modules and site modules.

**Comment by infograf768** [comment] 2019-10-21 08:59
This is due to a WIP with date set to NULL. We are not going to use `getNullDate()` anymore.
making PR now.

**Comment by infograf768** [comment] 2019-10-21 09:24
Please test https://github.com/joomla/joomla-cms/pull/26751

Closing as we have a patch

**Closed as completed by infograf768** 2019-10-21 09:24 UTC
Labels: No Code Attached Yet
