### ISSUE TITLE
Use of stems in finder index in contrast to fulltext search

### ISSUE THREAD

**Issue by StefanLindner** [joomla/joomla-cms#17085] opened 2017-07-12 09:13 UTC
### Steps to reproduce the issue

1. Install second language german
2. make german the default language
3. Create two articles. Place the word "Heiter*keit*" in the first one and "Heiter*ung*" in the second one. Both words have the stem "heiter".
4. configure finder indexer to use stem and snowball
5. install a stemmer implementation for php
6. Build finder index
7. Type "Heiter" into finder's search field. You will see "Heiter*keit*" and "Heiter*ung*" as proposal.
8. Ich you search for "Heiter*keit*" you will also find the article with "Heiter*ung*"
9. But if you search for "Heiter" you will not find any of the above created articles
10. If you use a fulltext search in contrast (joomla's search component)and you search for "heiter" you will find both
11. If you use a fulltext search and search for "Heiter*keit*" you will only find on article, but not the one including "Heiter*ung*"

### Expected result

Using finder for searching should find both articles if searchd for stem "Heiter"
Using finder should not find "Heiter*ung*" if searching for "Heiter*keit*"

### Actual result

No results for search

### System information (as much as possible)

Joomla only.

### Additional comments

Is this the intedend behavior of the finder component? Means: it's not a but, it's the intended behavior? If it is _not_ the intende behavior, the fix dould be done with one line of code in file administrator/components/com_finder/helpers/indexer/query.php

#### Findex Index

search for "Heiter": no results
search for "Heiter*keit*": finds "Heiter*keit*" and "Heiter*ung*" both words fully marked as result

#### Search

search for "Heiter": finds "Heiter*keit*" and "Heiter*ung*" in both words only "Heiter" marked as result
search for "Heiter*keit*": finds only "Heiter*keit*"

**Comment by brianteeman** [comment] 2017-07-12 16:19
> install a stemmer implementation for php

What stemmer did you install?

**Comment by StefanLindner** [comment] 2017-07-13 08:14
For PHP 5 we use pecl's stem from https://pecl.php.net
```sh
pecl install stem
```

For PHP 7 pecl no longer provides a stem implementation. In this case we build it like this:
```sh
mkdir /tmp/stem && cd /tmp/stem && \
curl -s -L http://pecl.php.net/get/stem-1.5.1.tgz | tar xzf - && \
cd stem-1.5.1 && \
curl -s -L "https://bugs.php.net/patch-display.php?bug_id=71091&patch=feature-support-php5-and-php7&revision=1457366472&download=1" | patch -p1 && \
sed "s/821813b35d88263c9b8b43b5202ca67a/$(md5sum stem.c | cut -d ' ' -f1)/" ../package.xml > package.xml && \
yes yes | pecl install package.xml && \
cd /tmp && \
rm -Rf stem && \
echo "extension=stem.so" > /etc/php.d/stem.ini
```<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17085">issues.joomla.org/tracker/joomla-cms/17085</a>.</sub>

**Comment by Hackwar** [comment] 2018-05-21 08:50
#20391 will fix this (partially). Can this issue be assigned to me, so that I can include this in one of the future improvements for com_finder?

**Comment by brianteeman** [comment] 2018-05-21 09:02
@Hackwar we can only assign people who are part of the maintainers team - limitation of github :(

**Comment by Hackwar** [comment] 2018-06-03 20:01
After some considerations, I would say that this is the way it is supposed to work. In this specific situation, I expect that the stemmer identified the "-er" of "Heiter" as a suffix that can be removed and thus it wont find any results. Thus I would say that this is intended behavior.

**Comment by ghost** [comment] 2018-06-04 03:56
closed as expected Behaviour as stated above. Issue can always reopened for ongoing Discussion.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17085">issues.joomla.org/tracker/joomla-cms/17085</a>.</sub>

**Closed as completed by ghost** 2018-06-04 03:56 UTC
Labels: No Code Attached Yet
