### ISSUE TITLE
[bug] Administrator Menu Item: Components Menu Container

### ISSUE THREAD

**Issue by Dave-LeDev** [joomla/joomla-cms#20308] opened 2018-05-06 23:45 UTC
### Steps to reproduce the issue
1) Create new Administrator Menu Item
2) Menu Item Type: Components Menu Container
3) Toggle the "All" button, rendering all Component Items hidden
4) Toggle any Component Items to Show
5) Save

### Expected result
All items are hidden except those that were manually toggled to "Show".

### Actual result
All items are marked as "Show". The only way to get desired result is to select "None" from the "Expand: All, None| Show: All, None" section.

### System information (as much as possible)
J! 3.8.7

### Additional comments
Not a big bug, but can be annoying. At least there's a work-around.

**Comment by ghost** [comment] 2018-05-14 04:34
Can someone please answer on this issue as its open since 10+ Days having Staus "New"?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20308">issues.joomla.org/tracker/joomla-cms/20308</a>.</sub>

**Comment by infograf768** [comment] 2018-05-14 07:49
@izharaazmi 
Can you look?

**Comment by infograf768** [comment] 2018-05-14 08:04
Hmm, In fact I do not understand what is the error.
Can you post a screenshot of the Components Menu Container?
Is it similar to this?
<img width="568" alt="screen shot 2018-05-14 at 10 03 13" src="https://user-images.githubusercontent.com/869724/39985204-22b6759e-575e-11e8-9184-1a59fefcca8f.png">

**Comment by izharaazmi** [comment] 2018-05-14 08:57
I cannot reproduce this issue on current staging. The toggles working as expected saving appropriate values and rendering only selected items. Please let me know if I am missing something.

**Comment by infograf768** [comment] 2018-05-14 08:58
Same for me. It works fine.

**Comment by ghost** [comment] 2018-05-14 09:17
Any Comment on above Replies @Dave-LeDev?

Thanks for Comments @infograf768 @izharaazmi.

**Comment by Quy** [comment] 2018-05-18 14:08
Closing for now as non-reproducible.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20308">issues.joomla.org/tracker/joomla-cms/20308</a>.</sub>

**Closed as completed by Quy** 2018-05-18 14:08 UTC
Labels: No Code Attached Yet
