### ISSUE TITLE
Custom Fields for Users Are Getting Cleared After Password Reset

### ISSUE THREAD

**Issue by faisalshehzaddnc** [joomla/joomla-cms#44141] opened 2024-09-26 07:44 UTC
### Steps to reproduce the issue

1. Go to the user login page on the Joomla site.
2. Click on the "Forgot your password?" link and initiate the password reset process.
3. Enter the required details (username or email) and submit the form.
4. The user receives a password reset email.
5. After resetting the password, log in with the new password.
6. Go to the user profile and check the custom fields.

### Expected result

1. After the password reset, custom fields should retain their previous values, and no data should be lost.
2. The user should be able to log in with the new password, and all custom fields should display correctly.

### Actual result

1. After the password reset is completed, the user’s custom fields are getting cleared and appear blank.
2. Data entered in custom fields prior to the password reset is lost and is not showing on the admin panel for the user.

### System information (as much as possible)

1. Joomla Version: 5.1.3
2. PHP Version: 8.2
3. Database Version: MYSQL 8.0
4. Web Server: Apache
5. Browser: Chrome

### Additional comments

1. This issue persists even with custom fields set to non-mandatory.
2. There are no errors displayed during the process.
3. A clean Joomla installation has been tested, and the issue still occurs.

**Comment by Hackwar** [comment] 2024-09-29 08:10
Hello @faisalshehzaddnc, thank you for reporting this. We are taking this very seriously, however I just tested this on a current 5.2 and I can not reproduce this. I did the following:
1. Created a customfield named "test".
2. Edited a non-Superadmin user and filled that field with "testvalue"
3. In the frontend went through the password forgotten process
4. Logged in with the users new password

Afterwards the value was still correctly in the database and was also displayed in the profile. You wrote that you had a clean install. Can you check that again? Did you retrieve the install package from joomla.org or is that a third party distribution? Do you maybe still have something else installed in the system? I'm going to ask someone else to test this again, but if we can't reproduce this, I'm going to close this issue again. (I added the tag "Release Blocker" after I read your issue and removed it again after I was unable to reproduce it.)

**Comment by alikon** [comment] 2024-09-29 08:20
i can't reproduce too on current 5.2

**Comment by Hackwar** [comment] 2024-09-29 08:21
Thank you @alikon. I'm going to close the issue then. @faisalshehzaddnc if you still have this issue and you are very sure that this is truely a bug in Joomla, please open a new issue.

**Closed as completed by Hackwar** 2024-09-29 08:21 UTC
Labels: No Code Attached Yet, Information Required
