### ISSUE TITLE
Unable to uninstall language pack

### ISSUE THREAD

**Issue by Sulpher** [joomla/joomla-cms#28107] opened 2020-02-27 11:24 UTC
### Steps to reproduce the issue

- Install any extra language pack.
- Attempting to uninstall that language pack.

### Expected result

The language package must be removed.

### Actual result
![photo_2020-02-23_17-26-52](https://user-images.githubusercontent.com/3432048/75440334-a6eb4d00-596c-11ea-8a33-945cbd708a3c.jpg)

An error message occurs.
As a result, I can install a new language and cannot uninstall it.
There is no content with the new language.

### System information (as much as possible)
Joomla 3.9.15

### Additional comments

**Comment by ot2sen** [comment] 2020-02-27 11:26
Filter by pkg instead. You will need to uninstall the package rather than
the parts of it.

**Comment by brianteeman** [comment] 2020-02-27 11:27
You are attempting to uninstall a language

As the error says - that language is part of a pack which does not allow you just uninstall the language

If you change the filter to package
or remove the filter and search for the language name

You will then see the package for the language you wish to uninstall.

Closed as not a bug

**Closed as completed by brianteeman** 2020-02-27 11:27 UTC
Labels: No Code Attached Yet

**Comment by Sulpher** [comment] 2020-03-06 13:14
Thank you @ot2sen and @brianteeman for your replies.
I think the problem is in Spanish localization.

You were mentioned about pkg and I see it on the example of Russian:

![Screen Shot 2020-03-06 at 15 59 35](https://user-images.githubusercontent.com/3432048/76085862-eb599700-5fc3-11ea-9759-5f549052613d.png)

French:
![Screen Shot 2020-03-06 at 16 05 58](https://user-images.githubusercontent.com/3432048/76086563-61123280-5fc5-11ea-9b3c-53d286b193a8.png)


Well, now I install Spanish: (es-ES)
![Screen Shot 2020-03-06 at 15 58 37](https://user-images.githubusercontent.com/3432048/76085876-f57b9580-5fc3-11ea-8037-b170c85a6fd1.png)

And here is what I see:
![Screen Shot 2020-03-06 at 15 58 59](https://user-images.githubusercontent.com/3432048/76085892-00362a80-5fc4-11ea-8835-24f7fd56054f.png)

There is no pkg that could be uninstalled.

If it is an issue related to the official es-ES localization, maybe should we report es-ES localization team about this issue?

**Comment by infograf768** [comment] 2020-03-06 13:18
please filter by package and not ‘span’

if there is a problem it could be in the package xml and not the name

**Comment by Sulpher** [comment] 2020-03-06 13:23
@infograf768 thank you for your tip. 
There are 3 languages:
English en-GB (default)
Russian ru-RU
Spanish es-ES

However, there is no pkg for Spanish:
![Screen Shot 2020-03-06 at 16 20 20](https://user-images.githubusercontent.com/3432048/76087117-8b182480-5fc6-11ea-800e-4eab078643d7.png)

But Spanish is available for use:
![Screen Shot 2020-03-06 at 16 21 53](https://user-images.githubusercontent.com/3432048/76087160-a5ea9900-5fc6-11ea-993b-bfe8d46260c6.png)

So, my assumption is that the problem is in Spanish localization which comes without pkg file, but I am not sure.

**Comment by Sulpher** [comment] 2020-03-06 13:26
Btw, I also noticed Russian localization comes as a language (Site) and the pkg, but there is no 3rd item in the list - language (Administrator).

But according to English and French, the localization package should consist of  3 items. I've been reported the Russian Language team about this fact.

**Comment by infograf768** [comment] 2020-03-06 14:44
Re-install Spanish through languages installer

**Comment by Sulpher** [comment] 2020-03-06 14:47
It takes the same effect (I just been checked out).

**Comment by infograf768** [comment] 2020-03-08 07:53
Looks like the Spanish package has a wrong name
`joomla_language_full`
we will inform the Spanish TT about that.
Russian is fine.
