### ISSUE TITLE
Sort order by tagged items broken

### ISSUE THREAD

**Issue by benschi11** [joomla/joomla-cms#6250] opened 2015-03-02 01:38 UTC
**Steps to reproduce the issue**
Create a MenuItem of type "Tagged Items". Set sort order to "published date" and "asc".

**Expected result**
The list should be ordered according to this settings (published date asc).

**Actual result**
The default sort order (fallback) is used (order by title asc)

**System information (as much as possible)**

PHP Version 
5.5.22
MySQL Version 
5.6.23

**Additional comments**

**Comment by Erftralle** [comment] 2015-03-06 23:29
Confirmed.

I think #6329 and #6331 are dealing with the same problem.

The reason for that are the recent changes in #5675.
By replacing
```
$params = $app->getParams();
```
with
```
$params = JComponentHelper::getParams('com_tags');
```
in the frontend Tag model the menu item options are not merged any longer to the ```$params``` so that  only the component options are used.

@zero-24
Maybe we could replace the actual code with:
```
    // Load the parameters.
    if ($app->isAdmin())
    {
      $params = JComponentHelper::getParams('com_tags');
    }
    else
    {
      $params = $app->getParams();
    }

    $this->setState('params', $params);
```
That should solve the current issue as well as the issue in #5675.

**Comment by benschi11** [comment] 2015-03-06 23:46
Works for me :+1:

**Comment by phproberto** [comment] 2015-03-07 00:45
Please check and comment in: https://github.com/joomla/joomla-cms/pull/6354

I'm closing this issue now that we have a pull request

**Closed by phproberto** 2015-03-07 00:45 UTC
Labels: No Code Attached Yet
