### ISSUE TITLE
cached breadcrumbs on smart search results page

### ISSUE THREAD

**Issue by rompec** [joomla/joomla-cms#17945] opened 2017-09-12 13:38 UTC
```
#### Steps to reproduce the issue
create menu item - type smart search
create breadcrumbs module on every page
turn system cache on (conservative)
search "something" 
see the breadrcrumbs on the results page
search "somethingelse" on the results page

#### Expected result
breadcrumbs: .../search/somethingelse

#### Actual result
breadcrumbs:  .../search/something

#### System information (as much as possible)

PHP built | Linux vm1567 2.6.32-042stab112.15 #1 SMP Tue Oct 20 17:22:56 MSK 2015 x86_64
-- | --
Verze databáze | 5.5.57-0+deb8u1
Porovnávání databáze | utf8_unicode_ci
Database Connection Collation | utf8mb4_general_ci
Verze PHP | 5.6.30-0+deb8u1
Webový server | Apache
Rozhraní mezi Webovým serverem a PHP | cgi-fcgi
Verze Joomla! | Joomla! 3.7.5 Stable [ Amani ] 14-August-2017 12:09 GMT
Verze platformy Joomla! | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0


#### Additional comments


```

**Comment by ghost** [comment] 2017-09-12 13:57
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17945">issues.joomla.org/tracker/joomla-cms/17945</a>.</sub>

**Comment by mbabker** [comment] 2017-09-12 15:23
It's an issue with the breadcrumb module in general.  You basically have to leave the caching disabled on that module for breadcrumbs to display correctly.  Part of the issue is its data is dynamic based on what is actually displayed on the page; the module is configured to cache the output based on the active menu item ID.  Since multiple pages can be shown under one menu item, that logic does not work for breadcrumbs.

One of the other strategies (modes) in [`Joomla\CMS\Helper\ModuleHelper::moduleCache()`](https://github.com/joomla/joomla-cms/blob/staging/libraries/src/Helper/ModuleHelper.php#L519) may be more appropriate for this module, or it may require expanding the system to be able to put in support for a custom strategy.  Or we may just have to disable the cache for the breadcrumb module in general.

**Comment by brianteeman** [comment] 2017-10-05 13:07
Closing as answered by @mbabker

**Closed as completed by brianteeman** 2017-10-05 13:07 UTC
Labels: No Code Attached Yet
