### ISSUE TITLE
Engine (not editor) clears  html tag

### ISSUE THREAD

**Issue by volandku** [joomla/joomla-cms#12784] opened 2016-11-06 11:53 UTC
### Actual result

In some cases Joomla remove <a> when non-semantic-code inside

### System information (as much as possible)
Joomla 3.7.0dev php 5.5

### Additional comments
like this
http://paste.ubuntu.com/23435876/

**Comment by zero-24** [comment] 2016-11-06 14:21
Can you please a bit more information how to reproduce the issue?

**Comment by volandku** [comment] 2016-11-06 14:49
Insert this code in item (TinyMCE - source code or No Editor), save it.
As result - same code, except tag a, it have been removed

**Comment by zero-24** [comment] 2016-11-06 15:43
I cna't reproduce the problem. Please doube check the Text Filter Settions for your User Group.

![image](https://cloud.githubusercontent.com/assets/2596554/20039164/e65158a8-a43f-11e6-9c97-7f343dae0f78.png)

**Comment by ggppdk** [comment] 2016-11-06 16:13
I tested with default text-filters for super-user,
- it works with no-editor and code mirror
- but with TinyMCE the **JS code cleanup removes the A tag** , it seems that TinyMCE tries to remove block elements from A Tags and fails in some cases removing the A tag itself ?

http://stackoverflow.com/questions/14597219/how-to-configure-tinymce-to-allow-block-level-elements-inside-anchor-a-tag

**Comment by zero-24** [comment] 2016-11-06 16:15
For tinymce can you try to disable the editor checking via the plugin?

**Comment by zero-24** [comment] 2016-11-06 16:15
The editor text filter i mean

**Comment by ggppdk** [comment] 2016-11-06 16:25
It is disabled already, but it is not relevant, in my case it is the code cleanup feature and not the disallowed tag that is causing the removal of the A tag

I tested here
https://www.tinymce.com/

and the <a> tag is also removed, during code cleanup

@volandku 
is the problem the removal of the A tag ?
or is the problem something else ?

**Comment by volandku** [comment] 2016-11-06 16:36
I found it on client site.
All filters are disabled.
After I downgrade it to 3.6.4 and all works fine

**Comment by ggppdk** [comment] 2016-11-06 16:49
@volandku

Same cleanup (a tag removed) happens in J3.6.4
so i repeat the question that you have not answered:

> is the problem the removal / deletion of the A tag ?

**Comment by volandku** [comment] 2016-11-06 16:53
I test it again on new test site.
Cant confirm without TinyMCE, but still confirm with TinyMCE

**Comment by mbabker** [comment] 2016-11-06 16:55
If it's TinyMCE specific there is either an issue in our implementation or a bug in their code.

**Comment by volandku** [comment] 2016-11-06 16:57
Well on first client site there was this bug in any editor (evem without) on 3.7.0
Was no this bug on 3.6.4

May be matters it was upgraded 1.5 -> 2.5 -> 3.4 -> 3.6 -> 3.7

Filters for superadmin was setted to none

**Comment by mbabker** [comment] 2016-11-06 17:00
The only way it would matter on the upgrade path is if old files were not correctly removed.

**Comment by ggppdk** [comment] 2016-11-06 17:01
> If it's TinyMCE specific there is either an issue in our implementation or a bug in their code.

it is tinyMCE issue, and not Joomla implementation,

because I tested here
https://www.tinymce.com/

The a tag is lost , basically tinyMCE tries to move block elements out of the A tag, in this case it fails and removes the A Tag ...

Maybe we should is change the defaults of Joomla plugin for tinyMCE:
to prevent TinyMCE from doing the cleanup:

e.g. 
Allowed child elements for a:

> a[div|h4span|b|i|u|sup|sub|img|#text]"

**Comment by mbabker** [comment] 2016-11-06 17:03
1) Report this as an issue to TinyMCE then
2) If it's a configurable behavior, then it might be acceptable.  But then I have to ask, should we really allow invalid HTML constructs to be saved?  OK the stuff might "work", but doesn't make it right.

**Comment by dgt41** [comment] 2016-11-06 17:08
>  If it's a configurable behavior, then it might be acceptable. 

It is, by assigning something like `span[lang|dir|class|[xml:lang]]` in extended elements. I did that in https://github.com/joomla/joomla-cms/pull/11367
But I will agree that INVALID HTML SHOULD NOT BE ALLOWED, at least by default!

**Comment by ggppdk** [comment] 2016-11-06 17:19
2 comments
- removal of Anchor TAG is known TinyMCE bug if inside the A tag you have no Text node (see https://github.com/tinymce/tinymce/issues/2991),
- blocks elements inside Anchor are valid in HTML5, right ?

Explanation:
the block tags are moved outside the anchor during cleanup,
and then you have an A tag without any inner content

if you add "hello" just after A you will see that the A tag is not lost and it will be around hello

@volandku 
I link to an issue above:
you can use
> valid_children : '+a[div]',

but there is not parameter in the Joomla content plugin for doing this

**Comment by ggppdk** [comment] 2016-11-06 17:33
Please see this:
http://html5doctor.com/block-level-links-in-html-5/

Wrapping Anchor around block elements is useful, the alternative is to use SPAN and CSS, but since HTML5 allows, it makes no sense for Joomla not allow it by default

**Comment by brianteeman** [comment] 2016-11-06 17:40
It doesn't matter what links you share to prove it should be ok. If tinyMCE
doesn't allow it (and you said it does not) then there is NOTHING we can do
about it.

**Comment by ggppdk** [comment] 2016-11-06 17:43
I will make a PR (1 line of code),
it is just a matter of our default configuration allowing block elements inside anchor

**Comment by ggppdk** [comment] 2016-11-06 17:55
I have made a PR

**Comment by ggppdk** [comment] 2016-11-06 17:57
@dgt41 

This is related ? https://github.com/joomla/joomla-cms/issues/9323

Related in terms of "HTML code cleanups"

**Comment by Fedik** [comment] 2016-11-06 17:59
we should not promote invalid HTML, if User need it then he/she should do it himself

**Comment by ggppdk** [comment] 2016-11-06 18:01
> we should not promote invalid HTML, if User need it then he/she should do it himself 

yes agreed but what is invalid the block elements inside anchor are valid

**Comment by brianteeman** [comment] 2016-11-13 10:16
> I have made a PR

Where?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12784">issues.joomla.org/tracker/joomla-cms/12784</a>.</sub>

**Comment by ggppdk** [comment] 2016-11-13 10:47
Here is the PR: https://github.com/joomla/joomla-cms/pull/12792 **HTML5 allows block elements inside anchors, modify TinyMCE default behaviour for this**

**Comment by brianteeman** [comment] 2016-11-13 10:50
Thanks now I can close this as we have a PR

**Closed by brianteeman** 2016-11-13 10:50 UTC
Labels: No Code Attached Yet
