### ISSUE TITLE
[J4 & J3] Next/previous year & month commands not working correctly in datepicker filter (backend)

### ISSUE THREAD

**Issue by spinoops** [joomla/joomla-cms#39365] opened 2022-12-06 15:30 UTC
### Steps to reproduce the issue
When the commands next/previous for year & month are clicked, the datepicker popup is suddenly closed and apply the POST request for filter. **It happens only in the filter of items lists.**

![date-arrows](https://user-images.githubusercontent.com/42632993/205933414-b854a1a4-b48b-4f4c-86c1-be8a470161a4.png)

### Expected result
The popup should not closed when we pass the next/previous month or year. It should close only when we click the day button.

### Actual result
The **problem occurs only in the filters of items lists**. If we use the datepicker in the edition of an item (calendar field), it works fine.

### System information (as much as possible)
Joomla 4.2.4 and PHP 7.4. 
Chrome/Firefox/Brave
Atum Default admin template (J4)

### Additional comments
It seems the problem occurs in Joomla 3 and Joomla 4.

**Comment by brianteeman** [comment] 2022-12-06 20:00
Which component is this happening in? I cant remember core ever having a datepicker for a list filter.

**Comment by spinoops** [comment] 2022-12-07 06:38
> Which component is this happening in? I cant remember core ever having a datepicker for a list filter.

It's Component Creator (https://www.component-creator.com). I leave them an issue but they told me it's a Joomla Core field and not related to their components.

**Comment by joomdonation** [comment] 2022-12-07 15:14
I don't have experience with Component Creator. However, base on what you describe here, I think it happens because somewhere in that field definition, you have `onchange="this.form.submit();"` .

Then when you click on next/previous button, the value of the input changes, and the form is submitted.

I would say that this is expected behavior. So there is nothing for us to fix here. Somehow, you will have to find a workaround for this problem, for example remove `onchange="this.form.submit();"`  and use a separate button to submit the form.....

**Comment by spinoops** [comment] 2022-12-07 16:05
> I don't have experience with Component Creator. However, base on what you describe here, I think it happens because somewhere in that field definition, you have `onchange="this.form.submit();"` .
> 
> Then when you click on next/previous button, the value of the input changes, and the form is submitted.
> 
> I would say that this is expected behavior. So there is nothing for us to fix here. Somehow, you will have to find a workaround for this problem, for example remove `onchange="this.form.submit();"` and use a separate button to submit the form.....

Ah yes, I have checked the field definition and this is the problem.

Is there an hide/close event on the Joomla datepicker ? 

I tried the boostrap version : 

`$('#mydateinputid').datepicker()
            .on('hide', function(e) {
                document.adminForm.submit();
            });`

But it just changes the appearance of the datepicker and nothing else.

**Comment by joomdonation** [comment] 2022-12-07 16:07
> Is there an hide/close event on the Joomla datepicker ?

Honestly, I don't know. Maybe @dgrammatiko or @Fedik could give you the answer.

**Comment by brianteeman** [comment] 2022-12-07 17:39
Simply put the datepicker is not designed to be used as a filter field in a list view.

I would recommend that you download the free version of dpcalendar and look at how they have done list view date filters

**Comment by joomdonation** [comment] 2022-12-09 08:30
Closing because this is not a core issue. It's up to to developer to decide how to handle this development further.

**Closed as completed by joomdonation** 2022-12-09 08:30 UTC
Labels: No Code Attached Yet
