### ISSUE TITLE
Custom fields in multi language website

### ISSUE THREAD

**Issue by uruk-hai-21** [joomla/joomla-cms#18396] opened 2017-10-23 15:01 UTC
### Steps to reproduce the issue
1. Install 2 or more language
2. Create 2 or more multi language field group and its relative fields
    * ![Field groups](https://i.imgur.com/ySRxGCu.png "Field group")
    * ![Fields](https://i.imgur.com/HUV3ALw.png "Fields")
3. Create a multi language article
    * ![multi language article](https://i.imgur.com/5epn4uZ.png "multi language article")

### Expected result
In front end, the article show only the custom field relative to selected language

### Actual result
In front end, the article show the custom fields of all languages
* English language selected:
![English article](https://i.imgur.com/HINlXLn.png "English article")

* Italian language selected:
![Italian article](https://i.imgur.com/LElGOM1.png "Italian article")

### System information (as much as possible)
Joomla 3.8.1

**Comment by brianteeman** [comment] 2017-10-23 15:07
That is not how multilanguage works. 

You need a separate article for each language

**Comment by AlexRed** [comment] 2017-10-23 15:23
I can confirm the problem, if the article is in language = All
it show the custom fields of all languages<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18396">issues.joomla.org/tracker/joomla-cms/18396</a>.</sub>

**Comment by uruk-hai-21** [comment] 2017-10-23 15:27
I don't think it should work as you say.
Then, why is it possible to set the language in the custom fields?

if it works for modules it should also works for custom fields:
* ![Module](https://i.imgur.com/zKEpXlj.png)

* ![Load position](https://i.imgur.com/HhzCi28.png)

* ![English](https://i.imgur.com/WeaLpTd.png)

* ![Italian](https://i.imgur.com/AZFAYlI.png)

**Comment by Bakual** [comment] 2017-10-23 20:53
The language set in a custom field refers to the language of the article. A "french" field will only show in french (or "All") articles.

**Comment by Bakual** [comment] 2017-10-23 20:53
Closing as not an issue.

**Comment by uruk-hai-21** [comment] 2017-10-24 00:45
In my opinion, the language set in a custom field should be referred to the language of page visited in front end (www.example.com/it/, www.example.com/en/), it should work like any other Joomla component.

**Comment by Bakual** [comment] 2017-10-24 06:17
That doesn't make any sense for a custom field. Remember that custom fields are always tied to an entitiy, they don't appear on its own.
Imagine a custom field tagged for french in an article tagged for english. The custom field would never show.
As it is, a french field will only show up in forms for french (or "All") articles, and thus what you see in the form will also match what you will see in frontend.

**Comment by infograf768** [comment] 2017-10-24 06:45
In fact, I wonder about another scenario:

We have custom fields tagged to a specific Content language as described above.
They are displayed depending on the item language when the article IS tagged to a Content Language, which is perfectly fine as rightfully explained by @Bakual .

BUT they also display when the Item is tagged to ALL languages.

Imho, we should be able to prevent that if we wish and only allow fields tagged to ALL languages to display on ALL items, whatever their language, including items tagged to ALL languages.

**Comment by infograf768** [comment] 2017-10-24 07:06
Further possible improvement:
Allow or not the display of a field in frontend per item.

Something like

![displayfield](https://user-images.githubusercontent.com/869724/31929047-a282789e-b89a-11e7-83bb-b66434979256.png)

**Comment by Bakual** [comment] 2017-10-24 08:02
If I set a field to "All" languages, I would expect it to show in articles of all languages. I think that we agree.
If I set a field to "French" language, personally I expect it to also show in articles tagged to "All", not only for french ones. I guess that depends on usecase what the expected behavior is.

As for not displaying a field in frontend, I would not do that. We can already use categories to show/hide fields differently. And if that doesn't work one could simply leave the field empty and make sure empty fields are not rendered in frontend (layout overrides can achieve that if it's not already the case).

**Comment by uruk-hai-21** [comment] 2017-10-24 09:25
In my opinion, doesn't make any sense to tie custom fields to articles. If I want that a custom field will be shown in an article of all languages, I will set the custom field to "All" and not to "French".

**Comment by Bakual** [comment] 2017-10-24 11:24
I'm not sure what you want to achieve then by adding eg an italian and french field to the article when the article is tagged "All". Neither would ever show.
Fields don't show depending on the active language. You've got a misconception there.

**Comment by uruk-hai-21** [comment] 2017-10-24 13:23
For convenience, I want to achieve the translation of a page (or an article in general) using only one article.

If I have 10 language installed:
1. I should create 10 articles,
2. I should associate each articles,
3. I should open, edit, save and close each articles,
4. If I have to change an information see point 3.

Using the custom fields like contents of article I will create only one article. Obviously this method will be used if SEO and SEF are not important for the project.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18396">issues.joomla.org/tracker/joomla-cms/18396</a>.</sub>

**Comment by Bakual** [comment] 2017-10-24 13:41
> For convenience, I want to achieve the translation of a page (or an article in general) using only one article.

That's obviously not the intended usage of custom fields and thus I'm not surprised this doesn't work.

**Comment by uruk-hai-21** [comment] 2017-10-24 14:44
This is your opinion, it would be nice to know the opinions of other users.

**Comment by infograf768** [comment] 2017-10-24 15:51
@Bakual 
I was expecting the same behavior as modules when they are for example loaded with `{loadposition xxx}` in article.

**Comment by infograf768** [comment] 2017-10-24 16:11
@ajejebrazorf01 
Although the multilang feature is not designed to only use items tagged to All languages, you may be able to reach your goal by using custom modules and include them in an article.
This would mean one custom module per language obviously, which does not save much work time. As I did not test, I am unsure about the way associations would work with the switcher as there will not be any association possible.

**Comment by uruk-hai-21** [comment] 2017-10-24 23:16
@infograf768 
good workaround!

**Comment by ggppdk** [comment] 2017-10-25 04:18
The language "ALL" is about where something appears
- it is not about "which" language content it will include

thus using article language 'All' to decide to show all fields really seems wrong

Only fields marked with language 'ALL' should appear in all article (regardless if their language is ALL or any other)

The way that it is now, effectively forbids using articles with language 'All' if you also have fields with specific languages

**Comment by infograf768** [comment] 2017-10-25 05:23
> Only fields marked with language 'ALL' should appear in all article (regardless if their language is ALL or any other)

Yep, that is exactly what I tried to say above.

**Comment by ggppdk** [comment] 2017-10-25 05:55
>>    Only fields marked with language 'ALL' should appear in all article (regardless if their language is ALL or any other)

> Yep, that is exactly what I tried to say above.

In this case the criteria is working in the wrong direction 
to write more clearly

The language property of field should work the same way as the language setting of articles

- only articles with language 'ALL' appear regardless of language context
- only fields with language 'ALL' should appear in all articles regardless of the language of the article

**Comment by uruk-hai-21** [comment] 2017-10-27 09:57
So, this is an issue or not?

**Comment by AlexRed** [comment] 2017-10-27 10:06
issue for me

**Comment by uruk-hai-21** [comment] 2017-10-31 18:54
@Bakual 
@brianteeman 

After gathered feedback of other users, is it possible to have a revision of your judgment?

**Comment by Bakual** [comment] 2017-10-31 19:02
I reopened it now.

**Comment by infograf768** [comment] 2017-10-31 19:08
thanks for reopening. now, how can we modify the code to reach what it should be

**Comment by Bakual** [comment] 2017-10-31 19:30
I'd say somewhere in the FieldsHelper::getFields method. But I'd have to try it myself as well.

**Comment by infograf768** [comment] 2017-11-01 09:36
I think I found it:
Add after line 113 of `/administrator/components/com_fields/helpers/fields.php`
which is 
```
		if (JLanguageMultilang::isEnabled() && isset($item->language) && $item->language != '*')
		{
			self::$fieldsCache->setState('filter.language', array('*', $item->language));
		}
```
an elseif
```
		elseif (JLanguageMultilang::isEnabled() && isset($item->language) && $item->language == '*')
		{
			self::$fieldsCache->setState('filter.language', '*');
		}
```
to get

```
		if (JLanguageMultilang::isEnabled() && isset($item->language) && $item->language != '*')
		{
			self::$fieldsCache->setState('filter.language', array('*', $item->language));
		}
		elseif (JLanguageMultilang::isEnabled() && isset($item->language) && $item->language == '*')
		{
			self::$fieldsCache->setState('filter.language', '*');
		}
```

Please folks, test that code. If it works fine I will make a PR.
@ajejebrazorf01 
@AlexRed 
@ggppdk
@Bakual

**Comment by uruk-hai-21** [comment] 2017-11-01 14:13
If I set the language of article to ALL, in backend the custom field (with a setted language) tab disappear

**Comment by infograf768** [comment] 2017-11-01 14:39
Not sure I understand.
this is how it should work:

article set to All : only fields set to All should display.
article set to a specific language: only fields set to All AND fields set to the specific language will display.

this would mimic the modules behavior.

if you get that, then new code is fine and I will make PR.

**Comment by uruk-hai-21** [comment] 2017-11-01 15:10
Custom fields already works fine in backend. The issue is in frontend: see my first comment.

**Comment by AlexRed** [comment] 2017-11-01 16:13
@infograf768 in my test your code is ok.
I can confirm:
article set to All : only fields set to All should display.
article set to a specific language: only fields set to All AND fields set to the specific language will display.

**Comment by infograf768** [comment] 2017-11-01 16:22
will make pr as it looks like @ajejebrazorf01 did not understand that the change in code corrects display in frontend as explained.

**Comment by infograf768** [comment] 2017-11-01 16:23
we may though make sure when we invoke multilang that the app is site

**Comment by uruk-hai-21** [comment] 2017-11-02 02:59
@infograf768 
I'm doing tests and weird things happen:

# Test 1 v.1 (original code)

Steps to reproduce
--
* Create the custom fields:
![](https://screenshots.firefoxusercontent.com/images/c501652a-94f8-4f43-9eb6-7d323d328ddc.png)
* Create 3 articles: first setted to all, second to italian, third to english
![](https://screenshots.firefoxusercontent.com/images/01d99800-2a1e-41b3-a823-48ceabd44f37.png)
* Create a new "Category blog" Menu Item Type (for each language)

Result
--
* In Category blog view everything is shown correctly:
![](https://screenshots.firefoxusercontent.com/images/8cd86772-0abf-448c-a03e-6f9a527d5ea8.png)
_-_-_-_-_-_-_-_-_-_
![](https://screenshots.firefoxusercontent.com/images/979d231d-3163-4670-8d50-b707af5ac667.png)
* In the article view it is also shown the custom field of the other language:
![](https://screenshots.firefoxusercontent.com/images/6be95399-f4a8-4f23-8532-c5ebe71d9995.png)
_-_-_-_-_-_-_-_-_-_
![](https://screenshots.firefoxusercontent.com/images/387fe227-7d89-4614-9a5e-b183a5f0b5db.png)

---

# Test 1 v.2 (original code)

Steps to reproduce
--
* Disable the italian and english articles:
![](https://screenshots.firefoxusercontent.com/images/dec56d26-aa6f-4363-81d6-dab8cd07d3ee.png)

Result
--
* In Category blog view and article view it is also shown the custom field of the other language:
![](https://screenshots.firefoxusercontent.com/images/a314679d-a380-4e3c-948a-8a5cf1e7f67a.png)
_-_-_-_-_-_-_-_-_-_
![](https://screenshots.firefoxusercontent.com/images/a54d0a9a-02f2-4da6-b4f5-402e7abf054d.png)

---

# Test 2 (changed code)

Steps to reproduce
--
* Create the custom fields:
![](https://screenshots.firefoxusercontent.com/images/c501652a-94f8-4f43-9eb6-7d323d328ddc.png)
* Create an article setted to all languages

Result
--
In backend:
* in the article setted to all languages disappear the italian and english custom fields tabs:
![](https://screenshots.firefoxusercontent.com/images/86f82fbc-e2ec-4184-a710-7b5623cfba5e.png)

In frontend:
* for example in the english article view disappear the english custom fields:
![](https://screenshots.firefoxusercontent.com/images/5c127703-b7c6-4916-a815-2ef31477acfa.png)

**Comment by infograf768** [comment] 2017-11-02 08:34
All is fine as you describe for new code.
Do NOT confuse the active language and the item language.
You may display an item (here an article) tagged to ALL languages when the Active language is English or Italian.
In this case, the new code will only display the field(s) tagged to ALL languages, which is what we want.

Your original issue:
```
Expected result

In front end, the article show only the custom field relative to selected language
Actual result

In front end, the article show the custom fields of all languages.
```
This for your article tagged to ALL languages.

But the expected result should NOT be `the custom field relative to selected language` (active language).

What it should do is display 
for articles tagged to ALL, only fields tagged to ALL, independently of the Active language.
for Articles tagged to a specific language, fields tagged to ALL as well as fields tagged to the specific language.

It solves the real issue which is that on frontend, with the old code, you are getting, for any article tagged to ALL languages, ALL fields, irrespective of their language.

Obviously, as fields tagged to ALL languages will always be displayed (whatever the active language), one should not use custom fields of type text or textarea (except if they contain a content in every language used on the site...)

My PR will contain detailed screenshots.

**Comment by infograf768** [comment] 2017-11-02 09:12
Closing as we have a patch
https://github.com/joomla/joomla-cms/pull/18474

**Closed as completed by infograf768** 2017-11-02 09:12 UTC
Labels: No Code Attached Yet
