### ISSUE TITLE
Joomla 4.2.2 refusing update to 4.2.3 with PHP 8.1.11

### ISSUE THREAD

**Issue by Jotinha-jrb** [joomla/joomla-cms#38890] opened 2022-10-02 09:38 UTC
### Steps to reproduce the issue
I've tried to update 2 web sites (2 different domains) from 4.2.2 to 4.2.3 with PHP 8.1.11 and it did not work.
On my test environment (XAMPP for Windows) with PHP 8.1.6 and 8.1.10 it worked perfectly.
So, I guess the issue comes with the new version of PHP, the only one I can use on my hosting server.

**Comment by richard67** [comment] 2022-10-02 15:11
What means "it did not work"? Do you have any error messages? If not, try it with error reporting set to maximum and debug on in global configuration. What error message do you get then and is there a call stack shown?

And do you have any 3rd party extensions which could cause it fail?

Without any additional info your issue helps us nothing.

**Comment by Jotinha-jrb** [comment] 2022-10-02 15:59
Yes, the error message was: see screenshot below.
Debug and Error reporting set to maximum.
I've made the same updates in 2 web sites (2 different domains) in my own test environment with PHP 8.1.6 and 8.1.10 and they succeed perfectly.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38890">issues.joomla.org/tracker/joomla-cms/38890</a>.</sub>

**Comment by Jotinha-jrb** [comment] 2022-10-02 16:00
![screen shot 2022-10-02 at 16 00 56](https://issues.joomla.org/uploads/1/7eb1edc85952683bb090cd38b0ff9bf9.png)
Sorry! Here's the screenshot.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38890">issues.joomla.org/tracker/joomla-cms/38890</a>.</sub>

**Comment by Webdongle** [comment] 2022-10-02 20:07
If it works with php 8.1.6 and php 8.1.0 what is different about php 8.1.11 that causes that error?

**Comment by Jotinha-jrb** [comment] 2022-10-03 10:01
Sorry, I just don't know!

The installation of Joomla 4.2.2 "online" was made from backup to the empty public_html of the domain carmen-duran.com

And the discussion in the Joomla Forum (Update 4.2.2 to 4.2.3 failed!) is a real jungle for me, any Expert has a different point of view, but till now nobody gave me a clear tip what's really going on with that damn update.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38890">issues.joomla.org/tracker/joomla-cms/38890</a>.</sub>

**Comment by richard67** [comment] 2022-10-03 10:18
Up to now I also have no idea yet. When you switch on debug in your global configuration in backend, part site, is there some stack trace shown in addition?

**Comment by richard67** [comment] 2022-10-03 10:19
Or is there something in the server logs (if necessary ask your provider how to access them if you don’t know)?

**Comment by richard67** [comment] 2022-10-03 10:22
What you could do if you urgently need to update your live site is do make a local copy, update that and then move that (files and database) to the live site.  Ut then you should maybe make a subdomain on your hosting and keep a copy of your site with own files and db on that subdomain so we later still can reproduce the issue and not need to wait until the next Joomla release for an update being available again.

**Comment by Webdongle** [comment] 2022-10-03 11:56
@sozzled tested on wamp with a vanilla J4.2.2 on php 8.1.11 with full success https://forum.joomla.org/viewtopic.php?f=812&t=996780&p=3672563#p3672531

**Comment by richard67** [comment] 2022-10-05 12:55
@Jotinha-jrb User jotabe309 in the support forum, is that you? If so, wy haven't you reported here that your problem is solved meanwhile, liiktated in the forum here https://forum.joomla.org/viewtopic.php?f=812&t=996780&p=3672563#p3672665 ? It's not really helpful to open issues and then not post updates when a problem was solved.

So or so I think it is not a core issue since other users successfully updated from 4.2.2 to 4.2.3 wittt PHP 8.1.11.

Closing as not a core issue.

**Closed as completed by richard67** 2022-10-05 12:55 UTC
Labels: No Code Attached Yet, Information Required

**Comment by Jotinha-jrb** [comment] 2022-10-11 08:45
Sorry, I'm new here and simply forgot to close it immediately.
