### ISSUE TITLE
Installation fails J4.02

### ISSUE THREAD

**Issue by kamzar1** [joomla/joomla-cms#35477] opened 2021-09-04 05:34 UTC
Alpine 3.14 Linux
Nginx 1.20.1
php7.4.23/php7.4-fpm/Mariadb
At least dependencies shown in technical-requirements installed, including those of PHP additional modules.
https://serveraddress//installation/index.php
shows:
https://docs.joomla.org/J4.x:FatalError#/media/File:Joomla-j4-fatal.png
Sorry, there was a problem we could not recover from.
The server returned a "500 - Whoops, looks like something went wrong."

../installation/configutaion.php: $debug = true;

yet nothing happens.

Nginx access logs shows the access, no errors logged.

**Comment by richard67** [comment] 2021-09-04 08:55
@kamzar1 Which version of MariaDB?

**Comment by tholden92** [comment] 2021-09-04 09:48
You need to append some custom code to get debug of installation. Just google debug joomla installation and you will find it

**Comment by tholden92** [comment] 2021-09-04 09:48
Using Redis?

**Comment by kamzar1** [comment] 2021-09-04 15:16
Mariadb 10.6.4
All php db plugins loaded. Mysqli pdo pgsql redis...
Strange thing is the 500 on joomla, which is not a real nginx 500.
Also nginx makes no error log, despite being set on highest verbosity.
In same environment, other php (phpinfo) applications run with no issues, phpmyadmin ...
I think the installation page should be kept minimum to catch up with such exceptions,  rather going to full modus of pre  loading bunch of includes, libraries, classes!

**Comment by tholden92** [comment] 2021-09-04 15:43
I have the same problem with Redis configured as PHP session store. Here is the url to my issue about this

https://github.com/joomla/joomla-cms/issues/35471

**Comment by PhilETaylor** [comment] 2021-09-04 17:28
I think this can be closed as https://github.com/joomla/joomla-cms/issues/35471#issuecomment-913008465 says:

> One issue is the include ../ In my case it rendered the server root incorrectly, so those included couldn't locate the files. Somehow i managed to fix the document root by multiple nginx and php-fpm configuration.

**Comment by chmst** [comment] 2021-09-04 17:40
thanks

**Closed as completed by chmst** 2021-09-04 17:40 UTC
Labels: No Code Attached Yet

**Comment by PhilETaylor** [comment] 2021-09-05 18:14
For anyone coming back here in the future, the documentation for installing Joomla on Nginx based servers is here https://docs.joomla.org/Nginx

**Comment by kamzar1** [comment] 2021-09-07 09:21
Issue persists.
Thanks to @PhilETaylor and this hint:
[35471](https://github.com/joomla/joomla-cms/issues/35471#issuecomment-913198259)
`/installation/includes/framework.php and set const JDEBUG = true; on line 16`
I finally got some verbosity, rather the general 500 page.
The php simplexml was missing:

![simplexml](https://user-images.githubusercontent.com/71010840/132319745-f6e22b89-f1ff-468b-8776-928ad97df49a.png)

After fixing that, it tries to connect to local host mysql. As in this case DB is remote, I am stuck in the next step.
I thought, mysql stuff (including address to connect) will be fetched in coming steps, rather the immediate presumption that it must be localhost!
How to proceed from here?

![dblocal](https://user-images.githubusercontent.com/71010840/132319763-561e7886-a03c-49f9-915d-7f6f6ec386b2.png)

**Comment by PhilETaylor** [comment] 2021-09-07 09:31
Remove the configuration.PHP you created when debugging.

**Comment by richard67** [comment] 2021-09-07 09:31
> After fixing that, it tries to connect to local host mysql. As in this case DB is remote, I am stuck in the next step.
> I thought, mysql stuff (including address to connect) will be fetched in coming steps, rather the immediate presumption that it must be localhost!
> How to proceed from here?

@kamzar1 Check if there is a configuration.php file in your Joomla root and if so, remove it. Close your browser to get rid of old session cookie. Then try again. The installation procedure should start from beginning. When coming to the page to enter database server and so on, make sure to use the right (remote) host name, database name and a database user who has the full privileges for that database (normally that should not be root but a dedicated user for that database). Because your database is on a remote host, the installation will not be started. Scroll up and you will see information about a text file in the installation folder which you have to remove to proof you have access to the webserver. Follow the instructions and then just click again the button to continue at the bottom. Then the installation will connect to the database and all should work.

**Comment by kamzar1** [comment] 2021-09-07 11:45
Wonderful 👍 
Thanks @richard67 & @PhilETaylor 
Installation page is now alive and kicking!
Indeed, previously I had made a real configuration.php out of config-dist in order to get some debug info.
Should I close this issue or @PhilETaylor decides?

**Comment by richard67** [comment] 2021-09-07 11:51
@kamzar1 The issue is already closed.
