### ISSUE TITLE
[4.0] component config form not saving when validation fails on empty field

### ISSUE THREAD

**Issue by Ruud68** [joomla/joomla-cms#34102] opened 2021-05-22 14:16 UTC
### Steps to reproduce the issue
In order to be able to reproduce this follow the below instruction (otherwise I had to create a component that needed to be installed).

1. in ./administrator/components/com_content/config.xml add the following field:

`<field name="email" type="text" pattern=".*@.*\..*" label="TESTFIELD" description="" />`

2. in the back-end of the j4 site goto articles options
3. leave the TESTFIELD empty
4. click [save] button

### Expected result
Configuration should save (TESTFIELD is empty and NOT required)

### Actual result
save action throws error:

The form cannot be submitted as it's missing required data.
Please correct the marked fields and try again.
![screen shot 2021-05-22 at 14 10 06](https://issues.joomla.org/uploads/1/8487f342f9bbf24abe774d2e4fe90d5b.jpg)

### System information (as much as possible)
J4 dev 8 (nightly)
PHP 8.05
mysql 8.0.25

### Additional comments
saving with this field and (empty) value works correct in J3

**Comment by brianteeman** [comment] 2021-05-22 14:20
Could you check that the problem is not the pattern. ie its trying to check if the empty value matches the regex in the pattern

**Comment by Ruud68** [comment] 2021-05-22 14:25
the pattern works in J3 (saving with empty value gives no error) and gives this behavior in J4, so the issue is not in the pattern, but in the handling of the pattern

**Comment by brianteeman** [comment] 2021-05-22 14:32
I am surprised it works in j3 because the pattern is a validation rule and an empty field doesnt match the pattern

**Comment by brianteeman** [comment] 2021-05-22 14:41
anyway if you use type=email then the browser does it for you

**Comment by Ruud68** [comment] 2021-05-22 14:45
> anyway if you use type=email then the browser does it for you

sure, but this is an example of what seems like a B/C. There are patterns developers use that are not in the type list :)

**Comment by brianteeman** [comment] 2021-05-22 14:53
unless I am very much mistaken html5 pattern validation is done by the browser not joomla

**Comment by Ruud68** [comment] 2021-05-22 15:16
You are mistaken (sorry), issue is in validate.js
it validates against the pattern only when length of the field is not 0
if length is zero it checks if it is required (which it isn't)
then it should return true, but it return false (where the validation in J3 correctly returns a true)

because it returns a false, the error is thrown.

So somebody with knowledge of JS should have a look at line 685 of file ./media/system/js/fields/validate.js

**Comment by PhilETaylor** [comment] 2021-05-23 13:01
`pattern=".*@.*\..*"`

Is this only a test or are you using something with this regex in real life? It would not be valid, as `phil@myInternalServer` is a valid email address and would fail that pattern.

**Comment by Ruud68** [comment] 2021-05-23 13:16
> `pattern=".*@.*\..*"`
> 
> Is this only a test or are you using something with this regex in real life? It would not be valid, as `phil@myInternalServer` is a valid email address and would fail that pattern.

this is just a simple test to show the B/C issue with J4 form field validation :) #noworries

**Comment by joomdonation** [comment] 2021-05-23 14:01
Closing as there is PR https://github.com/joomla/joomla-cms/pull/34124.

**Closed as completed by joomdonation** 2021-05-23 14:01 UTC
Labels: No Code Attached Yet
