### ISSUE TITLE
Home Dashboard error

### ISSUE THREAD

**Issue by xhorizont** [joomla/joomla-cms#35680] opened 2021-09-27 08:44 UTC
Loged into backend when selecting Home Dashboard in language other then English I get error:

array_unshift(): Argument #1 ($array) must be of type array, null given

**Comment by brianteeman** [comment] 2021-09-27 08:45
Which language?

**Comment by xhorizont** [comment] 2021-09-27 09:47
Slovenian

**Comment by infograf768** [comment] 2021-09-27 09:55
I can't reproduce the error here.

**Comment by xhorizont** [comment] 2021-09-27 12:15
I'm using PHP8

**Comment by brianteeman** [comment] 2021-09-27 12:21
Same here and no problem.

Can you enable debug mode and see if there are more details in the error such as a stack trace.

**Comment by xhorizont** [comment] 2021-09-27 12:32
Is it possible to do something with language file. This is error from RSComment and only happens with Slovenian language:

<html>
<body>
<div class="rscomment-top-actions" style="box-sizing: border-box; color: rgb(33, 37, 41); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="pull-right" style="box-sizing: border-box;"><span class="rsc_my_comments" style="box-sizing: border-box;"><a class="hasTooltip" href="javascript:void(0);" title="**This will show all of your comments.**" data-toggle="modal" data-target="#rscomments-mycomments" data-bs-toggle="modal" data-bs-target="#rscomments-mycomments" style="box-sizing: border-box; color: rgb(13, 110, 253); text-decoration: none; transition: color 400ms ease 0s, background-color 400ms ease 0s;"><i class="fa fa-comments" style="box-sizing: border-box; -webkit-font-smoothing: antialiased; display: inline-block; font-style: normal; font-variant: normal; text-rendering: auto; line-height: 1; font-family: &quot;Font Awesome 5 Free&quot;; font-weight: 900;"></i><span> </span>**Moji komentarji**<span> </span></a></span><span class="rsc_subscr" style="box-sizing: border-box;"><a href="javascript:void(0)" class="hasTooltip" title="**Naroči se**" data-rsc-task="subscribeform" style="box-sizing: border-box; color: rgb(13, 110, 253); text-decoration: none; transition: color 400ms ease 0s, background-color 400ms ease 0s;"><i class="fa fa-envelope" style="box-sizing: border-box; -webkit-font-smoothing: antialiased; display: inline-block; font-style: normal; font-variant: normal; text-rendering: auto; line-height: 1; font-family: &quot;Font Awesome 5 Free&quot;; font-weight: 900;"></i><span> </span>**Naroči se**</a></span></div><div class="clearfix" style="box-sizing: border-box;"></div></div><div class="rscomments-comments-list" style="box-sizing: border-box; color: rgb(33, 37, 41); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="container" style="box-sizing: border-box; width: 1213.49px; padding-right: 15px; padding-left: 15px; margin-right: auto; margin-left: auto; max-width: 1320px;"><h1 class="error-code" style="box-sizing: border-box; margin: 0px 0px 1rem; font-weight: 500; line-height: 1.2; font-size: 6rem;">0</h1><h2 class="error-message" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 3rem; font-weight: 500; line-height: 1.2; font-size: 1.5rem;">array_unshift(): Argument #1 ($array) must be of type array, null given</h2><a href="http://mojster.ts.telekom.si/index.php" class="btn btn-secondary" style="box-sizing: border-box; color: rgb(255, 255, 255); text-decoration: none; transition: color 0.15s ease-in-out 0s, background-color 0.15s ease-in-out 0s, border-color 0.15s ease-in-out 0s, box-shadow 0.15s ease-in-out 0s; display: inline-block; font-weight: 400; line-height: 1.5; text-align: center; vertical-align: middle; cursor: pointer; user-select: none; background-color: rgb(108, 117, 125); border: 1px solid rgb(108, 117, 125); padding: 0.375rem 0.75rem; font-size: 1rem; border-radius: 0.25rem;"><span class="fas fa-home" aria-hidden="true" style="box-sizing: border-box; -webkit-font-smoothing: antialiased; display: inline-block; font-style: normal; font-variant: normal; text-rendering: auto; line-height: 1; font-family: &quot;Font Awesome 5 Free&quot;; font-weight: 900;"></span><span> </span>**Domača stran**</a><div class="error-debug mt-3" style="box-sizing: border-box; margin-top: 1rem !important;">

Call stack
--
# | Function | Location
1 | () | JROOT/libraries/src/Language/Text.php:212
2 | array_unshift() | JROOT/libraries/src/Language/Text.php:212
3 | Joomla\CMS\Language\Text::plural() | JROOT/components/com_rscomments/helpers/rscomments.php:1458
4 | RSCommentsHelper::humanReadableDate() | JROOT/components/com_rscomments/views/rscomments/tmpl/default_item.php:53
5 | include() | JROOT/libraries/src/MVC/View/HtmlView.php:429
6 | Joomla\CMS\MVC\View\HtmlView->loadTemplate() | JROOT/components/com_rscomments/views/rscomments/tmpl/default_items.php:13
7 | include() | JROOT/libraries/src/MVC/View/HtmlView.php:429
8 | Joomla\CMS\MVC\View\HtmlView->loadTemplate() | JROOT/components/com_rscomments/views/rscomments/tmpl/default.php:83
9 | include() | JROOT/libraries/src/MVC/View/HtmlView.php:429
10 | Joomla\CMS\MVC\View\HtmlView->loadTemplate() | JROOT/components/com_rscomments/helpers/rscomments.php:1167
11 | RSCommentsHelper::showComments() | JROOT/components/com_rscomments/helpers/rscomments.php:1074
12 | RSCommentsHelper::showRSComments() | JROOT/plugins/content/rscomments/rscomments.php:116
13 | plgContentRSComments->onContentAfterDisplay() | JROOT/libraries/src/Plugin/CMSPlugin.php:285
14 | Joomla\CMS\Plugin\CMSPlugin->Joomla\CMS\Plugin\{closure}() | JROOT/libraries/vendor/joomla/event/src/Dispatcher.php:486
15 | Joomla\Event\Dispatcher->dispatch() | JROOT/libraries/src/Application/EventAware.php:111
16 | Joomla\CMS\Application\WebApplication->triggerEvent() | JROOT/components/com_content/src/View/Article/HtmlView.php:249
17 | Joomla\Component\Content\Site\View\Article\HtmlView->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:692
18 | Joomla\CMS\MVC\Controller\BaseController->display() | JROOT/components/com_content/src/Controller/DisplayController.php:125
19 | Joomla\Component\Content\Site\Controller\DisplayController->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:730
20 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:146
21 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT/components/com_content/src/Dispatcher/Dispatcher.php:55
22 | Joomla\Component\Content\Site\Dispatcher\Dispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:389
23 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/SiteApplication.php:206
24 | Joomla\CMS\Application\SiteApplication->dispatch() | JROOT/libraries/src/Application/SiteApplication.php:245
25 | Joomla\CMS\Application\SiteApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:278
26 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/includes/app.php:63
27 | require_once() | JROOT/index.php:32

</div></div></div>
</body>
</html>

**Comment by brianteeman** [comment] 2021-09-27 12:35
From the stack trace you have provided the problem is 100% coming from rscomments and as you say it works fine in english then yes you are almost certainly correct that its an issue with the language file for rscomments.

I've never used rscomments but I am guessing you have a module on your home dashboard to display the latest comments. If so you could try and unpublish that admin module.

**Comment by xhorizont** [comment] 2021-09-28 09:23
IS it posible that it has something to do with my server setup. 
I have PHP 8.0.10, mysql  Ver 15.1 Distrib 10.3.31-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2 and Server version: Apache/2.4.41 (Ubuntu)
Server built:   2021-09-23T16:58:57

**Comment by brianteeman** [comment] 2021-10-03 08:07
I doubt it very much but as I have not seen the code from rscomments I cannot say 100%

What I can say 100% is that this is not an issue with the core of joomla

**Comment by chmst** [comment] 2021-10-03 08:10
Closing this as it is not Joomla core. @xhorizont the forum.joomla.org is is a better place for such questions.

**Closed as completed by chmst** 2021-10-03 08:10 UTC
Labels: No Code Attached Yet
