### ISSUE TITLE
Custom Fields Issues Saving - Video Included

### ISSUE THREAD

**Issue by johnnydevs** [joomla/joomla-cms#27231] opened 2019-12-10 12:26 UTC
### Steps to reproduce the issue

I have configured a number of custom fields for my contacts, they are all type text.

When I create a new contact and click save, the page refreshes with a success message but some of the fields are empty, even though the data exists in the database.

### Expected result

The data in the database should be displayed in the contact editing form, and not randomly disappear when on save.

### Actual result

As I continue to delete content from the form inputs and save, the missing data will reappear in the form. Very strange behavior.

See video here [https://streamable.com/x4tb6](https://streamable.com/x4tb6)

### System information (as much as possible)

Joomla 3.9.13

Third party plugins / components I have installed;

- easyblog
- sp page builder
- dropfiles
- admin tools
- akeeba backup
- Regular Labs - Cache Cleaner

### Additional comments

I've reinstalled the Joomla core files and ran extensions > manage > fix. Still the same issue.

I have also noticed that If I have a custom field type sql, and the multiple setting is set to yes, the same thing happens when I choose more than two selections. i.e, on the third selection and save, all my previous selections disappear from the form but they are visible in the database. I'm not sure if this is related, but it seems to be.

**Comment by brianteeman** [comment] 2019-12-10 18:03
From the video the issue is with a field labelled email
The form that these fields are on already has an email field (on the first tab).
Do they perhaps have the same fieldname?

**Comment by johnnydevs** [comment] 2019-12-11 09:08
> From the video the issue is with a field labelled email
> The form that these fields are on already has an email field (on the first tab).
> Do they perhaps have the same fieldname?

@brianteeman Good guess, but no the field names are different.

On the first tab the field name is `jform[email_to]` and on the custom field tab the field name is `jform[com_fields][email]`

Any other ideas?

**Comment by ReLater** [comment] 2019-12-11 11:33
Which browser?
Any "clever" AddOns installed that "help" to fill browser forms?

**Comment by johnnydevs** [comment] 2019-12-11 12:00
@ReLater Using Chrome browser, but I've also tried FFox and Edge, same issue. Also tried incognito mode. I really thought the duplicate email field would be the issue!

I've updated my question with some more details including installed third party plugins / components.

**Comment by HLeithner** [comment] 2019-12-11 13:19
I tried to replicate this issue without success, can you please try to replicate this issue on joomla.com or with a clean installation without any 3rd party addon?

**Comment by johnnydevs** [comment] 2019-12-11 14:14
@HLeithner I'm not able to replicate this issue on a fresh install. Where do I go from here?

**Comment by HLeithner** [comment] 2019-12-11 14:18
Use your existing site and disable all 3rd party extensions/modules/plugins. If it works then one of the extensions seams to make a problem.

**Comment by Quy** [comment] 2019-12-13 00:04
Closing as not a core issue. Please ask in Joomla! Forum if you need help. https://forum.joomla.org/<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27231">issues.joomla.org/tracker/joomla-cms/27231</a>.</sub>

**Closed as completed by Quy** 2019-12-13 00:04 UTC
Labels: No Code Attached Yet
