### ISSUE TITLE
[4.0] Delete orphans

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#31867] opened 2021-01-05 15:01 UTC
In the multilingual associations component there are two delete buttons

![image](https://user-images.githubusercontent.com/1296369/103661529-bc56dd80-4f66-11eb-89b0-bae64d6e545c.png)

If you click on delete all you get a confirmation dialog

If you click on delete orphans the action is performed without any further confirmation.

Is that the intended behaviour?

**Comment by infograf768** [comment] 2021-01-05 17:34
```
$app->enqueueMessage(
			Text::_($count > 0 ? 'COM_ASSOCIATIONS_DELETE_ORPHANS_SUCCESS' : 'COM_ASSOCIATIONS_DELETE_ORPHANS_NONE'),
			'message'
		);
```

**Comment by infograf768** [comment] 2021-01-05 17:40
<img width="846" alt="Screen Shot 2021-01-05 at 18 38 45" src="https://user-images.githubusercontent.com/869724/103679690-75c4ab80-4f85-11eb-9dbb-54ba33665a4a.png">


<img width="849" alt="Screen Shot 2021-01-05 at 18 38 57" src="https://user-images.githubusercontent.com/869724/103679635-60e81800-4f85-11eb-88fc-162105b80e07.png">

**Comment by brianteeman** [comment] 2021-01-05 18:09
I have absolutely no idea what the meaning of your two posts is other than to confirm what I wrote

**Comment by chmst** [comment] 2021-01-05 22:45
@brianteeman you wrote If you click on delete orphans the action is performed without any further confirmation.

@infograf768 posted screens where deleting orphans is confirmed. 

Seems that I missed something?

**Comment by infograf768** [comment] 2021-01-06 08:49
@brianteeman and @gostn
> If you click on delete orphans the action is performed without any further confirmation.

We DO have a confirmation as demonstrated above by the code and the screenshots, message depending if there were orphans to delete and deletion occurred or not.

I also wonder, as @chmst does, if I have missed something.
Would it be that you expect a js pop-up confirmation of the action before performing it?
If that is the case, it is totally unnecessary. The action is performed in the same way as Rebuilding menu Items or Rebuilding Update Sites or Deleting Cache or Clearing Update Cache.

**Comment by brianteeman** [comment] 2021-01-06 08:49
OK it was lost in translation then.

When you click on Delete All Associations you are asked to confirm that you want to do this
![image](https://user-images.githubusercontent.com/1296369/103748473-1786df80-4ffc-11eb-8665-1fbf3a2ea26a.png)

When you click on Delete Orphans you do not

**Comment by infograf768** [comment] 2021-01-06 08:53
As I said above

> If that is the case, it is totally unnecessary. The action is performed in the same way as Rebuilding menu Items or Rebuilding Update Sites or Deleting Cache or Clearing Update Cache.

We never need the choice to stop performing the action.
Closing as not a bug

**Closed as completed by infograf768** 2021-01-06 08:53 UTC
Labels: No Code Attached Yet

**Comment by brianteeman** [comment] 2021-01-07 16:54
> We never need the choice to stop performing the action.

Why not. Its a permanent action. How is it different to delete associations?

**Comment by infograf768** [comment] 2021-01-07 17:03
The only thing it does is clean up db of remains of wrong associations entries. Basically, if one has played with associations and deleted some, one may sometimes have wrong remains. This gets rid of them for ever. It is useless to choose not to.
