### ISSUE TITLE
[4.0] unstyled modal closed button (hardly used)

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20499] opened 2018-05-19 21:38 UTC
### Steps to reproduce the issue

install from 4.0-dev at 79fd949
login as super admin to admin
go to user notes and try and add a new user note
next to user click the select user button

### Expected result

styled modal CLOSE button like the others in joomla

### Actual result

unstyled CANCEL button
<img width="167" alt="screen shot 2018-05-19 at 22 37 13" src="https://user-images.githubusercontent.com/400092/40273273-330a3e98-5bb5-11e8-8290-1ed6a7cfcf52.png">

(for comparison here is the one from the select category modal) 
<img width="130" alt="screen shot 2018-05-19 at 22 37 53" src="https://user-images.githubusercontent.com/400092/40273279-4ab1f7fc-5bb5-11e8-86d7-d4caa33c2590.png">

### System information (as much as possible)
79fd949
google chrome

**Comment by Quy** [comment] 2018-05-23 19:53
Not reproducible

![cancel](https://user-images.githubusercontent.com/368084/40447664-33f7d2ea-5e88-11e8-8144-e2a5bf81626a.jpg)

**Comment by PhilETaylor** [comment] 2018-05-23 19:54
Seriously you need to stop closing issues just because you - ONE - person cannot replicate an issue!

**Comment by PhilETaylor** [comment] 2018-05-23 19:57
Your button is unstyled. 

I can STILL replicate this - watch this video - compare the close/cancel buttons on the select user and select category modals - they are styled different - the one is different to all the rest of joomla! 

![screen recording 2018-05-23 at 08 56 pm](https://user-images.githubusercontent.com/400092/40447865-ce180c62-5ecb-11e8-93cf-bd1759a91ee7.gif)

**Comment by PhilETaylor** [comment] 2018-05-23 19:59
see the difference: -HUGE difference! 

<img width="894" alt="screen shot 2018-05-23 at 20 58 46" src="https://user-images.githubusercontent.com/400092/40447990-277c1280-5ecc-11e8-833d-0c8d83c65fa9.png">

**Comment by Quy** [comment] 2018-05-23 20:09
> Seriously you need to stop closing issues just because you - ONE - person cannot replicate an issue!

Sorry. Please advise which other issues that should have not been closed prematurely. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20499">issues.joomla.org/tracker/joomla-cms/20499</a>.</sub>

**Comment by PhilETaylor** [comment] 2018-05-23 20:11
one earlier today ... got lost in all my gdpr emails... cant find it now.

**Comment by ghost** [comment] 2018-05-24 04:24
i prefer closing Issues if not confirmed as they always can be reopened if needed. So Danger of open but abandoned Issues is in this Way less.

**Comment by PhilETaylor** [comment] 2018-05-24 10:21
However the issue Im thinking was confirmed by @franz-wohlkoenig and then closed by @Quy with no explanation at all, apart from he could not replicate it himself. He did not state which git ref/branch/version he tested with or anything - just a abrupt `cant reproduce` and then he hit closed. Hardly the right way to reject CONFIRMED issues.

**Comment by Quy** [comment] 2018-05-24 11:11
I provided screenshots for the 2 "can't reproduce" so it is more than just "2 words" without context and the other one I referenced it to another issue. Please advise which one(s) should be reopened.

Thanks for the feedback. I will provide testing information for future closed issues.

**Comment by Quy** [comment] 2018-07-11 18:46
Please test #21079<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20499">issues.joomla.org/tracker/joomla-cms/20499</a>.</sub>

**Closed as completed by Quy** 2018-07-11 18:46 UTC
Labels: No Code Attached Yet, J4 Issue
