### ISSUE TITLE
Check that some special characters do not delete field data in database on saving.

### ISSUE THREAD

**Issue by learncss** [joomla/joomla-cms#13304] opened 2016-12-20 15:33 UTC
### Steps to reproduce the issue
Add λ in a text field.

### Expected result
Wipes data from fields for article in the database.

### Actual result
Wipes data from fields for article in the database.

### System information (as much as possible)
Joomla on Linux with MySQL

### Additional comments
I haven't tested this on the new custom fields feature in Joomla, but the plugin I created and have been using for years for custom fields has this issue. When I save the article it blanks out every custom field I have in the article and I have to redo them all. I found the same thing happened when I copied and pasted from PDF files sometimes. The typesetters replace = < > and other math symbols with larger symbols. When you copy and paste they just show up as a space, but if you save the article then it will wipe out the database fields like λ does. I have to paste into Sublime Text first to see if there are any of them because that’s the only way they will show up. I replace them with the characters in Sublime then paste into Joomla.

**Comment by Bakual** [comment] 2016-12-20 18:14
> I haven't tested this on the new custom fields feature in Joomla

Please try to reproduce the issue with core, otherwise it may as well be an error in your plugin that causes this.

**Comment by brianpeat** [comment] 2016-12-20 19:05
I just tested this with a sample text field in the 3.7 build and the λ symbol and all text from the field are still there when I save the article.

**Comment by franz-wohlkoenig** [comment] 2017-02-01 14:57
Confirming @brianpeat: Saved "Add λ in a text field." in an Textfield, Value is saved after saving Article. Looks like there is no Issue.
#### Test on:
Joomla! 3.7.0-staging
macOS Sierra, 10.12.3
Firefox 50.1.0
PHP 7.0.4
MySQLi 5.5.53-0

**Comment by Bakual** [comment] 2017-02-01 15:24
Closing as not being able to reproduce in core.

**Closed by Bakual** 2017-02-01 15:24 UTC
Labels: No Code Attached Yet
