### ISSUE TITLE
[4.4] Override issue in child template

### ISSUE THREAD

**Issue by vtheod** [joomla/joomla-cms#42931] opened 2024-03-01 09:23 UTC
### Steps to reproduce the issue

If I make some overrides in child template's html/layouts folder, the overrides are not working.

### Expected result

Overrides should work

### Actual result

Overrides doesn't work

### System information (as much as possible)

PHP version: 8.2.16
Web Server: Apache
Joomla version:  ‎4.4.3

**Comment by chmst** [comment] 2024-03-06 15:08
In general, layout overrides work very well. 
Could you please describe your problem in detail?
Or ask in forum.joomla.org, this is a better place for this kind of issues.

**Comment by dgrammatiko** [comment] 2024-03-08 18:09
@chmst I guess it’s all about https://github.com/joomla/joomla-cms/pull/39308 and the parent issue https://github.com/joomla/joomla-cms/issues/39306

**Comment by Quy** [comment] 2024-03-08 18:17
@dgrammatiko OK to close this one as it is a duplicate of #39306?

**Comment by dgrammatiko** [comment] 2024-03-08 18:24
@Quy dont ask me ask @vtheod

**Comment by alikon** [comment] 2024-03-12 18:43
if I understand correctly
not a core issue

**Closed as completed by alikon** 2024-03-12 18:43 UTC
Labels: No Code Attached Yet, Information Required
