### ISSUE TITLE
formbehavior.chosen: Form validation tries to focus hidden select dropdown list

### ISSUE THREAD

**Issue by tranduyhung** [joomla/joomla-cms#3464] opened 2014-04-16 14:57 UTC
In Joomla 3 if we use JHtml::_('formbehavior.chosen', 'select') and make a dropdown list required and not select an option when submit the form, we get error message "Please select an item in the list" on top left of the screen instead of getting it right below the dropdown list.

The reason is Chosen library makes focus on the hidden  element instead of the Chosen's . In the below screenshot I used Firebug to show  element, as you can see it had a red error border that was added by form validation.

![01](https://cloud.githubusercontent.com/assets/503262/2720960/1c0e7dfa-c576-11e3-9df5-04a3744d1e3d.png)

**Comment by zero-24** [comment] 2015-01-02 15:01
@tranduyhung 

I just see this but can't see/find this with our current code base. Can you have a look that this is still a issue in staging?

DL: https://github.com/joomla/joomla-cms/archive/staging.zip

Thanks.

**Comment by roland-d** [comment] 2015-05-05 13:38
@tranduyhung Thank you for your contribution however I no longer believe this is an issue in the current stable release of Joomla. As @zero-24 said, he can't reproduce it either so I will close this issue. If you feel the issue still exists feel free to re-open.

**Closed by roland-d** 2015-05-05 13:38 UTC
Labels: No Code Attached Yet
