### ISSUE TITLE
Fix the calendar to work in the subform field when in a menu item type declaration xml file

### ISSUE THREAD

**Issue by seanjermey** [joomla/joomla-cms#15842] opened 2017-05-05 18:59 UTC
### Steps to reproduce the issue

~~~~
  <field name="items" type="subform"  multiple="true"  label="Subform Field" >
    <form>
      <field name="something"  type="calendar" label="Calendar" />
    </form>
  </field>
~~~~

Add the XML code above to the file `components/com_content/views/article/tmpl/default.xml` after this line 35 - https://github.com/joomla/joomla-cms/blob/staging/components/com_content/views/article/tmpl/default.xml#L35

Then make a new menu item of type article, go to the options tab, add a new subform instance and click the calendar button

### Expected result

Calendar panel to open

### Actual result

Calendar panel fails to open

**Comment by Fedik** [comment] 2017-05-05 19:23
It seems was changed before 3.7 release in #15487

**Comment by tonypartridge** [comment] 2017-05-06 07:13
that patch is after the 3.7 release and due to be fixed in 3.7.1 I believe.

**Comment by Fedik** [comment] 2017-05-06 08:41
@tonypartridge I meant, it was broken in #15487, sorry for confusing 😉

**Comment by Fedik** [comment] 2017-05-06 09:26
@seanjermey please test #15848

**Comment by seanjermey** [comment] 2017-05-08 09:07
Hi @Fedik, I have tested #15848 

This resolves the issue for subform elements that exist on load, but not for newly instanced elements.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15842">issues.joomla.org/tracker/joomla-cms/15842</a>.</sub>

**Comment by Fedik** [comment] 2017-05-09 20:34
@seanjermey so, all is good for you, or you got some problem?

**Comment by laoneo** [comment] 2017-05-09 20:37
@seanjermey can you list the steps that we can reproduce the case where it is not working?

**Comment by seanjermey** [comment] 2017-05-10 07:58
Hi @Fedik @laoneo, i have re-tested and its working, not sure what i did wrong 1st time. Probably a Monday morning thing! Thanks for resolving! 

I look forward to the update so i can add the feajavascript:ture im working on!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15842">issues.joomla.org/tracker/joomla-cms/15842</a>.</sub>

**Comment by franz-wohlkoenig** [comment] 2017-05-10 08:05
@seanjermey if this issue is solved, please close it, thanks.

**Closed** 2017-05-10 08:12 UTC
Labels: No Code Attached Yet
