### ISSUE TITLE
After update to 4.3.0 an error has occurred: 0 Class "Joomla\Plugin\Authentication\Cookie\Extension\Cookie" not found

### ISSUE THREAD

**Issue by Gratia-Mira** [joomla/joomla-cms#40479] opened 2023-04-25 07:59 UTC
### Steps to reproduce the issue

Update Joomla from 4.2.9 to 4.3.0.

### Expected result

Installation goes well.

### Actual result

For some websites, the update goes wrong. The following error occurs: 0 Class "Joomla\Plugin\Authentication\Cookie\Extension\Cookie" not found

### System information (as much as possible)

Joomla 4.3.0
linux
PHP 8.1

### Additional comments
I just wanted to report it because I didn't find any after searching the issues. But it is probably already known.
[Description of the error in the Joomla forum](https://forum.joomla.org/viewtopic.php?f=808&t=1001208&sid=96029a4f490d1e6d7432f344a41514b1)

**Comment by obuisard** [comment] 2023-04-25 19:34
Thank you for reporting this error.
It probably related to the issue we have documented here https://docs.joomla.org/J4.x:Error_setCookie().
Please test that the workaround fixes your issue (change the cookie lifetime from 'Year' to 'Session' in the System plugin 'Language filter').<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40479">issues.joomla.org/tracker/joomla-cms/40479</a>.</sub>

**Comment by brianteeman** [comment] 2023-04-25 20:01
It is a different issue. This is the same as the one that I had at #40226

**Comment by sandewt** [comment] 2023-04-26 06:29
Open the file: `\Joomla\administrator\cache\autoload_psr4.php`

Do you miss the following line?
`'Joomla\\Plugin\\Authentication\\Cookie\\' => [JPATH_PLUGINS . '\authentication/cookie/src'],`

Then remember me was checked. The error message is then caused by the missing line.

![Schermafbeelding 2023-04-26 082344](https://user-images.githubusercontent.com/9271775/234487519-8723b01f-9e0b-4c5a-9ca9-df2fc42383c6.png)

**Comment by sandewt** [comment] 2023-04-26 08:17
> At the backend login, it displayed the following message at the end.

No idea. 

Advice: don't show the whole path to the joomla.php file on the internet, `/plugins/authentication/joomla/joomla.php` is enough information about the location. You can edit your comment.

**Comment by ryhcu404** [comment] 2023-04-29 13:39
We're having a very similar issue when upgrading to 4.3.0 on a relatively fresh install (late last year) of Joomla 4 on Ubuntu:

> Class "Joomla\Plugin\System\GuidedTours\Extension\GuidedTours" not found

After disabling that plugin, the error changed to the "Content\Contact" plugin, then after disabling that one to the "EmailCloak" plugin.

Deleting/recreating the autoload_psr4.php file did not help, nor did a manual load of the 4.3.0 update tar.gz file.

**Comment by Gratia-Mira** [comment] 2023-05-03 07:45
The error still exists in Joomla 4.3.1:
`Failed to open the required file '/plugins/authentication/joomla/joomla.php'.`

Are there any further advices?

**Comment by Gratia-Mira** [comment] 2023-05-03 07:48
> UPDATE: I restored both database and files backup (4.2.9) and _still_ had the issue even though we had not had issues prior on 4.2.9! I was able to finally stabilize the site by disabling the following extensions:

Probably nothing new: Some servers have a messy backup process. They do not delete the files beforehand, but only overwrite them. In this case, with this difficulty, you have to delete the data manually beforehand and then restore the backup (I also had to do this).

**Comment by ryhcu404** [comment] 2023-05-04 13:41
> Some servers have a messy backup process. They do not delete the files beforehand
You were on the right track. Not to hijack this thread, but I found the problem for my site:

The website is on a load balanced pair of servers. One site is rsync'd to the other--**except for the two cache directories**. So, the secondary server needed to have it's cache dirs cleared out to resolve the errors. This also explains why we were only seeing the issue about 50% of the time. Should have known!

**Comment by Gratia-Mira** [comment] 2023-05-09 20:16
Is there any news about this case?

**Comment by pklinke** [comment] 2023-05-19 15:48
Same issue "Class "Joomla\Plugin\Authentication\Cookie\Extension\Cookie" not found" here still after restore with kickstart!!

Still no solution?

**Comment by Gratia-Mira** [comment] 2023-05-19 18:25
I have found my mistake. It was a plugin for authentication that has been outdated since Joomla 4.3. I just [rewrote it](https://gitlab.com/gratia-mira-opensource/e-mail-oder-benutzername) and everything works. 
Apparently, however, the error described by @pklinke is still open, but no longer occurs with me.

I will therefore leave the ticket open.

**Comment by alikon** [comment] 2023-05-27 06:54
since the issue reported at beginning of this thread, has been solved, i'm closing this issue, and ask to open a proper and detailed new issue for those that still have the problem

**Closed as completed by alikon** 2023-05-27 06:54 UTC
Labels: No Code Attached Yet
