### ISSUE TITLE
Installing a new component on 3.7 results in component not found until Admin Cache is cleared.

### ISSUE THREAD

**Issue by Joomv** [joomla/joomla-cms#15588] opened 2017-04-26 12:45 UTC
### Steps to reproduce the issue
Install a component (I've tried ACL Manager and Admin Tools)
Go to component in backend

### Expected result
You see the component

### Actual result
You get a 404 Component not found.

### Additional comments
Clearing the admin cache fixes this issue, but surely it should not be happening.

**Comment by PhilETaylor** [comment] 2017-04-26 12:49
Is this related in anyway to #15560

**Comment by brianteeman** [comment] 2017-04-26 12:49
what are your cache settings

**Comment by Joomv** [comment] 2017-04-26 12:58
@PhilETaylor - No.
@brianteeman happens with cache on and off.

To clarify this is in the backend.  Just did it again with another component, same deal.

**Comment by PhilETaylor** [comment] 2017-04-26 12:59
I cannot reproduce sorry - I have been installing extensions into Joomla 3.7.0 all day :)

**Comment by mbabker** [comment] 2017-04-26 13:09
Well, this might be a bug in core.  If the install/update routine isn't clearing the `_system` cache group this issue can manifest itself.  I'm not going to reopen it just yet, but if someone wants to do a quick investigation, that'd be what you need to check.

**Comment by brianteeman** [comment] 2017-04-26 13:10
not if cache is not enabled though surely?

**Comment by mbabker** [comment] 2017-04-26 13:11
Well with cache disabled clearly.  But the project properties for the most part all have cache enabled so the part about needing a cache clear might be valid.

**Comment by brianteeman** [comment] 2017-04-26 13:13
Rowan said it happened with cache off

**Comment by brianteeman** [comment] 2017-04-26 13:16
OK might as well re-open then

**Comment by AlexRed** [comment] 2017-04-26 13:52
I can confirm the problem with "System Cache" ON conservative.
After install extension go immediately in the extension page and 404 Component not found
![error-cache](https://cloud.githubusercontent.com/assets/1362388/25437965/e7681d40-2a8f-11e7-8159-9f2e7e16a490.png)

**Comment by mbabker** [comment] 2017-04-26 14:06
FWIW I've basically seen this same thing with the caching in reverse almost.  With cache enabled, disable a component.  The component's still accessible.

**Comment by alikon** [comment] 2017-04-30 06:44
please test #15606 as it is clearing cahce

**Comment by franz-wohlkoenig** [comment] 2017-04-30 06:55
closed as having PR #15606<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15588">issues.joomla.org/tracker/joomla-cms/15588</a>.</sub>

**Closed by franz-wohlkoenig** 2017-04-30 06:55 UTC
Labels: No Code Attached Yet
