### ISSUE TITLE
JInputFiles get() silently discards unsafe files

### ISSUE THREAD

**Issue by julienV** [joomla/joomla-cms#8903] opened 2016-01-14 17:23 UTC
#### Steps to reproduce the issue
Enable zip extension in backend media manager.
* upload a zip containing an extension (considered unsafe by JFilterInput::isSafeFile)
* upload a zip containing a text file (considered safe)

#### Expected result
* first upload should show an error of some kind to the user
* second upload should succeed

#### Actual result
* the first upload fails, but there is no error to be seen...
* the uploads works, there is a success message

#### System information (as much as possible)
joomla 3.4.8

#### Additional comments
https://github.com/joomla/joomla-cms/blob/master/libraries/joomla/input/files.php#L87
This is the issue: returning default is ok if there was nothing uploaded, not when there was indeed an issue.
Either the results array should be returned with error key set (but the regular php errors don't match that case), or an exception should be raised.
The latter is probably better but i am not sure about backwards compatibility

**Comment by flash1452** [comment] 2016-03-04 12:28
@brianteeman 
I would love to hear your suggestion on this because i think raising an exception would be a good thing to do.

**Comment by franz-wohlkoenig** [comment] 2017-01-29 09:34
Issue remains on Joomla! 3.7.0-staging.

**Comment by AlexRed** [comment] 2017-03-29 08:25
I can confirm the problem on 3.7.0-stagin<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8903">issues.joomla.org/tracker/joomla-cms/8903</a>.</sub>

**Comment by zero-24** [comment] 2017-04-21 21:22
Closing as there is a PR: #15466

**Comment by zero-24** [comment] 2017-04-21 21:22
Please test there.

**Closed by zero-24** 2017-04-21 21:22 UTC
Labels: No Code Attached Yet

**Comment by julienV** [comment] 2017-04-21 22:17
the references pr doesn't fix the global issue, it only fixes it when using the com_media controller, but not the use of this code by 3rd party.

**Comment by zero-24** [comment] 2017-04-21 22:19
I don't see a way to do this without throwing an error which is IIRC not B/C and needs to be done in 4.0 Can you do a PR for that against the 4.0 repo and the the PR i have added?
