### ISSUE TITLE
Email Cloaking fires when @ in filename (image)

### ISSUE THREAD

**Issue by formfranska** [joomla/joomla-cms#39786] opened 2023-02-04 10:08 UTC
### Steps to reproduce the issue
I'm note sure how to phrase this correctly but I was told to report it in this post: https://forum.joomla.org/viewtopic.php?p=3683408#p3683408

### Expected result
Please view comments from people in the post.

**Comment by LukasHH** [comment] 2023-02-04 11:17
The problem is that the behavior came with the last PR. It should detect mail addresses set as placeholders, in title attributes or written freely in the text and protect against spam bots.
https://github.com/joomla/joomla-cms/pull/39508

I can't think of an idea now how to distinguish this when the filename is in the form of an email address.

**Comment by LukasHH** [comment] 2023-02-04 23:11
I have checked it again. It is the pattern that was not present in 4.2.6 and was included again due to Issue https://github.com/joomla/joomla-cms/issues/39422.

I think the easiest thing to do would be to change the file name and, if possible, to generally avoid using special characters in file names.

**Comment by formfranska** [comment] 2023-02-05 09:53
@LukasHH 
Thank you! Yes, for sure. I changed the filename immediately and it solved the issue for me. I normally check file names and never use weird characters in them but for some reason I had missed this one that was generated in ADOBE Illustrator.

So only reason I posted about it here was because people in that thread in the Forum told me to. For me, the issue is solved.

**Comment by brianteeman** [comment] 2023-02-05 10:01
is it not recommended practice to use @ in filenames when creating retina images?

this does sound like an undesirable breaking change in a patch release

@roland-d @fancyFranci

**Comment by richard67** [comment] 2023-02-11 13:55
The same issue has been reported again with #39832 , and as stated there in the initial post at the end, it seems to be common practice for some image and vector graphics editors to add an "@" to the file name. I'll close the other issue as duplicate, so let's continue discussion here.

**Comment by richard67** [comment] 2023-02-11 13:59
I've allowed myself to change the title of this issue so it contains "Email Cloaking" which makes it easier to be found when people search for it, since "Email Cloaking" is the well known name of that feature.

**Comment by roland-d** [comment] 2023-02-15 10:05
Thank you for the tag @brianteeman 

As Brian pointed out it does seem to be common practice to use @ in filenames for retina images.

@LukasHH Could you check if we can improve the regex so that retina images are not affected?

**Comment by LukasHH** [comment] 2023-02-15 22:33
from the theory I have found something how to exclude something if src is included in the context.
`'~<[^<]*(?<!\/(src))>(*SKIP)(*F)|([\w\.\'\-\+]+\@(?:[a-z0-9\.\-\p{L}]+\.)+(?:[a-zA-Z0-9\-\p{L}]{2,24}))~iu'`
[regex Example](https://regex101.com/r/6rdGKu/1)
But this must still be tested in Joomla, whether it has not other side effects. I will try to find a PR.

**Comment by roland-d** [comment] 2023-02-16 07:33
@LukasHH Thank you.

**Comment by LukasHH** [comment] 2023-02-20 17:50
A first local test shows me that it doesn't seem to work after all.
My idea in this line:
https://github.com/joomla/joomla-cms/blob/61235c3a31fa245f087e3df534857f5a2d21c812/plugins/content/emailcloak/emailcloak.php#L474
by adding "src" in the first part so that the pattern is not applied in this example.
`$pattern = '~<[^<]*(?<!\/(src))>(*SKIP)(*F)|' . $searchEmail . '~i';`

In the [regex editor](https://regex101.com/r/6rdGKu/1) it works, but in Joomla it runs into a timeout for me.

**Comment by LukasHH** [comment] 2023-02-24 19:42
@formfranska @crystalenka please test the PR https://github.com/joomla/joomla-cms/pull/39932

**Comment by richard67** [comment] 2023-02-24 19:44
Closing as having a pull request. Please test #39932 . Thanks in advance.

**Closed as completed by richard67** 2023-02-24 19:44 UTC
Labels: No Code Attached Yet, bug

**Comment by formfranska** [comment] 2023-02-25 08:53
> @formfranska @crystalenka please test the PR #39932

Sorry, Not sure exactly what I'm supposed to do. I wasn't able to copy the text from your test article https://github.com/LukasHH/other-test/blob/main/email_cloaking_test_source.html (couldn't scroll all the way down). Complete newbie in github. Sorry 😅
