### ISSUE TITLE
[3.9] Feature Request: Add Tos / Privacy / Imprint Links to Offline Site

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#20595] opened 2018-05-28 12:16 UTC
### Is your feature request related to a problem? Please describe.
In GDPR / DSGVO you have to have a Privacy Policy, On German Websites an Imprint is always obligatory. It would be good to have the possibility to give access to those contents on an "offline" site.

### Describe the solution you'd like
Selection in the Configuration which Article is ToS / Privacy Policy and Imprint an make it available Offline

**Comment by brianteeman** [comment] 2018-05-28 12:24
Can you not do that with a template override of the offline page?

**Comment by coolcat-creations** [comment] 2018-05-28 12:25
I thought that if literally every EU-directed website needs a privacy policy on the offline page it should be core? Not?

**Comment by brianteeman** [comment] 2018-05-28 12:29
I can't see why you would need a privacy policy for an offline site.

Maybe you would still need an impressum but that's something unique to Germany iirc

**Comment by coolcat-creations** [comment] 2018-05-28 12:31
Of course you need a privacy policy - in the moment someone visits the hosting saves log data?

**Comment by brianteeman** [comment] 2018-05-28 12:38
Those are server logs not site logs. There is no personal identifiable information in there (as confirmed by German law).

**Comment by rdeutz** [comment] 2018-05-28 13:10
A lot of people see it different. If you have the IP and the time than you have in theory the possibility to make a connection to a real person.

**Comment by coolcat-creations** [comment] 2018-05-28 13:17
Yes I also see it like that...

**Comment by PhilETaylor** [comment] 2018-05-28 14:09
If you are going to add links to these, then "these" need to exist somewhere, and you cannot view "these" if they are Joomla content because the site is offline! 

You would be changing the whole definition of "offline" (which technically already is not "offline" enough as a lot needs to be instantiated to get to the "offline" message. 

Also are we now saying that these three "Articles" are going to be mandated to be completed by all Joomla sites from now on? Would they be Joomla articles? would they just be a url link configured in global config? Links to where exactly as the site could be "offline" for technical reasons... so links to off domain articles?

I think this opens up a whole new ballgame, and is not a quick fix. 

The quick fix is for local template developers to style their offline pages to suit their requirements (and laws)

**Comment by brianteeman** [comment] 2018-05-28 14:25
The issue of IP address being pii has already been tested in the european court of justice. The conclusion was that it is only pii if the person logging the data has a legal way to determine who is the user of the ip address. As 99.99999% of joomla web site owners will never have that legal right then it is not pii on its own.

Reference https://www.whitecase.com/publications/alert/court-confirms-ip-addresses-are-personal-data-some-cases

> The CJEU decided that a dynamic IP address will be personal data in the hands of a website operator if:
> 1. there is another party (such as an ISP) that can link the dynamic IP address to the identity of an individual; and
> 2. the website operator has a "legal means" of obtaining access to the information held by the ISP in order to identify the individual.

**Comment by mbabker** [comment] 2018-05-28 14:30
Offline mode, as half baked as it is (and nothing has changed since https://magazine.joomla.org/issues/issue-feb-2011/item/378-how-offline-is-joomla-offline-mode was written), is not intended to be able to display select portions of your website.  I've tried masochistically in the past to make it behave in a semi-offline-but-display-select-content-from-select-sources mode in the past, it's possible but definitely not suggested for day to day use.

If you really need these policy documents to be available while Joomla is in offline mode, you need to serve them as static HTML files on your server.

**Comment by rdeutz** [comment] 2018-05-28 17:54
I think an overwrite is the best way to go, don't see how we can support this without making offline mode to a low level cms online mode. I am for closing this one.

**Comment by brianteeman** [comment] 2018-05-28 20:55
Closed for the reasons stated above

**Closed as completed by brianteeman** 2018-05-28 20:55 UTC
Labels: No Code Attached Yet
