### ISSUE TITLE
Cannot access to Backend and Frontend

### ISSUE THREAD

**Issue by joomleb** [joomla/joomla-cms#40031] opened 2023-03-05 20:30 UTC
Hi guys, 
PHP 7.4.33 + Joomla 4.2.8
After a J3 upgrade, apparently gone well I suddenly have no access to Joomla 4.2.8 Frontend and Backend when logging (tested with different users). I have back this Error message:

An error has occurred.
0 Call to undefined method Joomla\CMS\Application\AdministratorApplication::isAdmin()

Call stack

1 | () | JROOT/plugins/authentication/accesslogging/accesslogging.php:57
2 | plgauthenticationAccessLogging->onUserAuthenticate() | JROOT/libraries/src/Authentication/Authentication.php:175
3 | Joomla\CMS\Authentication\Authentication->authenticate() | JROOT/libraries/src/Application/CMSApplication.php:816
4 | Joomla\CMS\Application\CMSApplication->login() | JROOT/libraries/src/Application/AdministratorApplication.php:337
5 | Joomla\CMS\Application\AdministratorApplication->login() | JROOT/administrator/components/com_login/src/Controller/DisplayController.php:82
6 | Joomla\Component\Login\Administrator\Controller\DisplayController->login() | JROOT/libraries/src/MVC/Controller/BaseController.php:672
7 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:143
8 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT/administrator/components/com_login/src/Dispatcher/Dispatcher.php:45
9 | Joomla\Component\Login\Administrator\Dispatcher\Dispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:355
10 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:143
11 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:186
12 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:294
13 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:61
14 | require_once() | JROOT/administrator/index.php:32

Please, Do you have any suggestion ?
What am I missing ?

**Comment by richard67** [comment] 2023-03-05 20:39
Switch on debug in configuration.php then you should see a call stack which tells you which 3rd party is xtension causes this error. Closing this issue here as it is definitely caused by a 3rd party extension and not by the CMS. Please use the support forum for such questions.

**Closed as completed by richard67** 2023-03-05 20:39 UTC
Labels: No Code Attached Yet

**Comment by joomleb** [comment] 2023-03-05 20:44
@richard67 
following the [Brian tutorial here](https://www.youtube.com/watch?v=ZO9nmdsLlFw), what I reported is the debug report.

Please, the .../plugins/authentication/accesslogging/accesslogging.php:57  Which 3rd party extension is it from?

**Comment by richard67** [comment] 2023-03-05 20:46
Google for it. It is not from the CMS core.

**Comment by joomleb** [comment] 2023-03-05 20:55
Yes, sure, I tried it by typing:
"Joomla /plugins/authentication/accesslogging/accesslogging.php"
But there are no results.

Please, Do you have any idea on how I can process to discover it ?
I'm not using much 3rd party extension, thinking it has to be related with login I have 2 suspects:
Admin Tools, Seblod

**Comment by richard67** [comment] 2023-03-05 20:56
The xml file inside the plugin‘s folder should tell who the author is. Maybe there are also copyright statements in the PHP files or that plugin providing such information.

**Comment by joomleb** [comment] 2023-03-05 21:22
@richard67 
You're right, what a fool I was!

It is the "Authentication - WAP Admin Access Logging" by "SiteGuarding.com" I was testing before the update to J4.
[Through phpMyAdmin](https://ostraining.com/blog/joomla-cms/how-to-disable-a-joomla-plugin-via-phpmyadmin/) I disabled it and the bug has been solved.

Thank You very much for help on understanding it !
