### ISSUE TITLE
appscdn.joomla.org certificate expired

### ISSUE THREAD

**Issue by mbunkus** [joomla/joomla-cms#7614] opened 2015-08-02 14:00 UTC
The certificate for https://appscdn.joomla.org has expired roughly two weeks ago. This means that trying to retrieve content via https won't work. This will cause the web installer to fail if the Joomla installation is accessed via TLS even if the fix mentioned in #4878 is applied.

**Comment by PhilETaylor** [comment] 2015-08-02 19:32
@mbabker is this something you with your old hat on can escalate to the right person? 

Only a few million sites effected haha

**Comment by mbabker** [comment] 2015-08-02 19:37
I gave it to someone who still wears a badge :wink:

**Comment by PhilETaylor** [comment] 2015-08-02 19:37
Thanks - hopefully they can address it - or maybe you should name them to "encourage" them :)

**Comment by mbabker** [comment] 2015-08-02 19:38
Easy, @joomla/owners since that's the PLT.

**Comment by PhilETaylor** [comment] 2015-08-02 19:39
As this has already been escalated to the right person/team and is not a Joomla code issue - this Github Issue should be closed right?!

Transparency in action - not: 
![screen shot 2015-08-02 at 20 39 06](https://cloud.githubusercontent.com/assets/400092/9027681/98841aca-3956-11e5-816e-b786c8927f9e.png)

**Comment by mbabker** [comment] 2015-08-02 19:47
That's a GitHub thing.  It doesn't expose internal teams (and inherently membership) as public.  Useful though to ping an entire team in an org you're a member of for action though.

**Comment by Bakual** [comment] 2015-08-02 20:01
It has been raised already in the leadership chat. Unfortunately not everyone is allowed to create tickets to Rochen (I can't) and we don't even know yet if Rochen or Vic has to pay any bill or what the issue is.

**Comment by Bakual** [comment] 2015-08-02 20:01
Closing as it is indeed not related to code. But thanks for raising the issue.

**Closed by Bakual** 2015-08-02 20:01 UTC

**Comment by Bakual** [comment] 2015-08-06 06:11
Certificate is again valid now.

**Comment by masbaehr** [comment] 2022-04-25 18:15
Happened again on 23.4.2022 ;-)

**Comment by PhilETaylor** [comment] 2022-04-25 18:21
forked to https://github.com/joomla/joomla-cms/issues/37655 to gain attention from those that might be able to fix this
