### ISSUE TITLE
Collapse submenu items in backend menu overview

### ISSUE THREAD

**Issue by jduerscheid** [joomla/joomla-cms#38335] opened 2022-07-28 17:29 UTC
## Feature Request ##

Let the Menu item in the Backend View List make collapseable. 

### Problem that I want to solve ##

During maintaining website which an very large number of menuitems it is really difficult to find the korrekt menu-item, even if they have the same name, like an contact Page for every different part of the website. So you can filter by level or name, but the problem is, you are not able to see the context. 

### Idea to solve it ###

make the menu-items which has ab child collapsable, so you can close all the areas which are not necessary to see during your actual task. I think this will be make it easier to maintain websites with 50+ menu-items.

Sorry for the first to short version of the issue

**Comment by brianteeman** [comment] 2022-07-28 17:39
### Steps to reproduce the issue



### Expected result



### Actual result



### System information (as much as possible)



### Additional comments

**Comment by richard67** [comment] 2022-07-28 19:23
From talks in the German Glip channel i know that this issue is a feature request for the menu item list view. From the few words in the description this is absolutely not clear.

**Comment by chmst** [comment] 2022-07-29 07:20
Large category trees are indeed a challenge. You suggest a tree appearance and this could be better than now but is a big task. 
I could imagine an additional filter for the parent category instead.

**Comment by jduerscheid** [comment] 2022-07-29 07:31
Yes category tree’s are although sometimes a bit stupid. But I think if you solve this problem for menu tree’s it will be easy to adopt for categories. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38335">issues.joomla.org/tracker/joomla-cms/38335</a>.</sub>

**Comment by brianteeman** [comment] 2022-07-29 08:18
Is tthis the type of thing you are looking for?

https://codepen.io/brianteeman/pen/abYVYYd

**Comment by brianteeman** [comment] 2022-07-29 08:19
![menu](https://user-images.githubusercontent.com/1296369/181716366-641ed111-3c98-4853-880c-b72c83a4639d.gif)

**Comment by brianteeman** [comment] 2022-07-29 08:50
It shouldnt be too hard to create as we already have all the information about the level and the parents in the row as data attributes

**Comment by jduerscheid** [comment] 2022-07-29 13:34
Hey Brian, yes, this is the desired behavior<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38335">issues.joomla.org/tracker/joomla-cms/38335</a>.</sub>

**Comment by jduerscheid** [comment] 2022-07-29 13:38
> It shouldnt be too hard to create as we already have all the information about the level and the parents in the row as data attributes

Yes the information about the level is allready in the <tr> element

**Comment by brianteeman** [comment] 2022-09-07 21:33
https://user-images.githubusercontent.com/1296369/188985820-83fc3988-b9f7-416f-984a-565abbdacb7b.mp4

@obuisard any interest?

**Comment by obuisard** [comment] 2022-09-07 21:55
I really like the concept.
2 things that come to mind (but I am sure it was thought out already, I just want to make sure it is written here):
- we need an icon for the 'open' state and an icon for the 'closed' state,
- we need to test how it will affect pagination (depends on the implementation)

**Comment by brianteeman** [comment] 2022-09-08 06:37
pagination will be tricky when you get groups split by pagination. Thats one of the reasons I wanted to see if there was interest in the concept before continuing

**Comment by obuisard** [comment] 2022-09-08 14:07
This behavior (open/close of parent) is expected from users, and I do think it can bring some ease of use to the view. 
However, if we go that route, that behavior should be extended to all the views that have trees (tags, categories to name a few) for consistency. If a solution could be found that would also allow third party extensions to use it as well, it would be a great addition to the user interface.

**Comment by jduerscheid** [comment] 2023-09-02 21:49
I just added the code to add this feature to Joomla 5. I hope somebody will test this feature.

**Comment by richard67** [comment] 2023-09-02 21:53
Closing as having a pull request. See #41557  .

**Closed as completed by richard67** 2023-09-02 21:53 UTC
Labels: Feature, No Code Attached Yet
