### ISSUE TITLE
Old ,since J1.6, issue with Blog-article view

### ISSUE THREAD

**Issue by FrankVo** [joomla/joomla-cms#6365] opened 2015-03-08 16:48 UTC
#### Steps to reproduce the issue
Go to http://snel3.webzo4all.nl and click on** Kolommen-test** in menu and than on **´Click here---> Kolommen-test´**![screen shot 2015-03-08 at 11 46 01](http://issues.joomla.org/uploads/1/7bea2aae74b807894b0108d276a13c28.png)
The second menu item ´Kolommen´-test 2 will show same issue.

#### Expected result
Render the articles also in vertical columns. 
Articles should also shown tied to eachother. 
So, not only in the two options in Blog-settings; ´from left to right´and ´down´. 
This because with i.e. two columns and random-lenght of articles, big white spaces will apear because since J1.6 the rendering is in rows instead of also in columns.
In that cause the blog-options should be extended with one extra option. ´vertcal tied articles´

#### Actual result
Articles in two columns with white space because of different length of the single articles in same category

#### System information (as much as possible)
Joomla 3.4 Core function of Blog-view (com_content)
Shown in a Core Joomla template

#### Additional comments
This is an old issue since release J1.6. In many fora is this issue called as an enoying issue. We just want an extra option in Blog settings. The use of this option is limited we realize that, but for some customers with websites which are migrated from 1.5 to 3.4 it is/was very usefull to have a least a choise. We are aware of bootstrap/responsive impact, but still, make it at least possible as a choise in blog-settings.

**Comment by brianteeman** [comment] 2015-03-08 17:18
Does Multi Column Order - Down not do what you want?


![screen shot 2015-03-08 at 12 17 56](http://issues.joomla.org/uploads/1/84091e08cdbdb1621f0ca801bfc728d3.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6365">issues.joomla.org/joomla-cms/6365</a>.</sub>

**Comment by bertmert** [comment] 2015-03-08 18:07
I think this is a feature request.

Also Joomla 1.5 displayed blog items in rows without vertical adjustments. Headlines always starting at the same height. Joomla 1.5 used TABLEs. Since 1.6 DIV rows. Thar's the only difference.

Maybe you used template overrides plus masonry effects? Or a CCK plus additional extensions? Or special templates (there are some for all Joomla versions)?

Masonry is not a bootstrap plugin and not implemented in Joomla core.

**Comment by FrankVo** [comment] 2015-03-08 19:07
An override in JA Purity in an old J1.5, so indeed it was already an issue is the solution that should be done in Joomla Core. Also in the new Purity iii their is no override.
Let us not lose energy on what, why and because, but try tot make a n solution in Core Joomla.

I know that some 3rd aprty exteions has solutions, but that is not what my issue is. I think Joomla should make this possible in an option inside the blog-settings. Being straight forward....it is very ugly to leave it this way (with white spaces) because customers ask for this kind of article-blog possibilties with full displayed article in blogview.

Besides that, I think a standard change in the core-layout shouldn´t be that difficult.

**Comment by FrankVo** [comment] 2015-03-08 19:13
@brianteeman 
Sorry, but I explained that the core blog-solution (even in Core Joomal templates) not gives a solution. Just that is my statement. In he pull down should be another option.
In by the way...why not make this possibe ??

-Use Global
-Down
-Accross
-Masonry (tied up article vertical)

I am a bit flabbergasted that I have to explain this issue in this forum.

**Comment by brianteeman** [comment] 2015-03-08 19:19
Sorry but I really dont understand you

On 8 March 2015 at 19:13, FrankVo <notifications@github.com> wrote:

> @brianteeman <https://github.com/brianteeman>
> Sorry, but I explained that the core blog-solution (even in Core Joomal
> templates) not gives a solution. Just that is my statement. In he pull down
> should be another option.
> In by the way...why not make this possibe ??
>
> -Use Global
> -Down
> -Accross
> -Masonry (tied up article vertical)
>
> I am a bit flabbergasted that I have to explain this issue in this forum.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6365#issuecomment-77768411>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by mbabker** [comment] 2015-03-08 19:24
What you're recommending requires a fair bit of custom JavaScript.  Standard HTML/CSS behavior makes it so that the row is the height of the largest item in it (so if you have two items with varying length, the longest one will define the height for the full row).  It takes JavaScript to alter the appearance to make it look as you suggest (or even put different elements of different sizes into a container that appears to be the same size).  I think this type of behavior really does belong at the template override level and not something that is feasible to offer in core because of the amount of customization it would take to accomplish it.

**Comment by dgt41** [comment] 2015-03-08 19:30
As @FrankVo and @mbabker told you already this needs javascript. Best option is masonry as already stated in previous comment:
try http://masonry.desandro.com
All you need is to include some css the js library and some js to initialize it. Also some id’s for the div you want to reposition. It is not very hard to accomplish and you can do all of that in template override!

**Comment by Bakual** [comment] 2015-03-08 20:08
I wouldn't do that in core. It would very likely break templates and only complicates things. Also it would add yet another unneeded dependency into core.
It can be done easy using a template override if needed.

Closing as expected behavior.

**Closed by Bakual** 2015-03-08 20:08 UTC
Labels: No Code Attached Yet
