### ISSUE TITLE
Itemid 101 added to frontpage links automatically since Joomla 3.7

### ISSUE THREAD

**Issue by akfaisel** [joomla/joomla-cms#17431] opened 2017-08-07 02:18 UTC
### Steps to reproduce the issue
1. Login to backend
2. Go to Module Manager and create a new Login Module
3. Position it and set it to show on home page.

### Expected result
When hovered over _Forgot Password_ Itemid is not supposed to be added to the link.
http://www.yoursite.com/component/users/?view=reset

### Actual result
Starting from Joomla 3.7, this gets added automatically and the component area is not shown.
http://www.yoursite.com/component/users/?view=reset&Itemid=101

### System information (as much as possible)
Joomla 3.7

### Additional comments
NA

**Comment by tonypartridge** [comment] 2017-08-07 06:24
This happens because you haven't created a menu item for it. Since Joomla needs a menu item it loads in the homepage menu item.

It's not a bug, it's how Joomla! Works otherwise it wouldn't know what modules to load. You just need to create a login type men item.

**Comment by ghost** [comment] 2017-08-07 06:28
closed as expected Behaviour.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17431">issues.joomla.org/tracker/joomla-cms/17431</a>.</sub>

**Closed as completed by ghost** 2017-08-07 06:28 UTC
Labels: No Code Attached Yet

**Comment by akfaisel** [comment] 2017-08-07 09:28
I have been using Joomla since 2009 and I have never created menu item for it. 

This is happening since J3.7 and it cannot be a expected behavior.

Before J3.7, Itemid=101 will not be added.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17431">issues.joomla.org/tracker/joomla-cms/17431</a>.</sub>

**Comment by mbabker** [comment] 2017-08-07 11:54
The Itemid may not have been explicitly added to the URL when generating it before 3.7, but when visiting the URL you gave without the Itemid the system internally would end up resolving the default menu item anyway if it couldn't find a menu item for your requested page.  So the only thing that has changed is the Itemid that would be resolved when visiting a page is now more proactively included when building URLs.

**Comment by arvindpdmn** [comment] 2018-04-06 06:55
I discovered this yesterday when moving to v3.8.6. The code that does this is in `libraries\src\Component\Router\Rules\MenuRules.php` in `preprocess` method:



	// If not found, return language specific home link
	$default = $this->router->menu->getDefault($language);
	
	if (!empty($default->id))
	{
		$query['Itemid'] = $default->id;
	}
