### ISSUE TITLE
Terms of Service article is not linked to TOS label

### ISSUE THREAD

**Issue by dalethion** [joomla/joomla-cms#13973] opened 2017-02-08 16:18 UTC
### Steps to reproduce the issue
1. Enable User - Profile plugin and allow user registration.
2. Set Terms of Service to required.
3. Select article linking to Terms of Service.
### Expected result
The Terms of Service article is linked to the TOS label, displays in popup.
### Actual result
TOS article is not linked.
### System information (as much as possible)
PHP Built On	Linux hobitv2 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64
Database Version	5.5.54-0ubuntu0.14.04.1
Database Collation	latin1_swedish_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	5.5.9-1ubuntu4.20
Web Server	Apache/2.4.7 (Ubuntu)
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 3.6.5 Stable [ Noether ] 1-December-2016 22:46 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
### Additional comments
Further investigation reveals that in `plugins/user/profile/profile.php` `$tosarticle` has the correct value, and the field attribute article is correctly set on the tos field. However, in `plugins/user/profile/field/tos.php ` `$tosarticle` is always empty.
I was able to reproduce the bug on a fresh Joomla install on the same system.

**Comment by franz-wohlkoenig** [comment] 2017-02-08 17:01
Confirmed on 3.6.5, on 3.7-beta2 no Issue.

**Comment by AlexRed** [comment] 2017-02-10 08:37
The problem is solved, you can try in localhost the 3.7.0 Beta2 version.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13973">issues.joomla.org/tracker/joomla-cms/13973</a>.</sub>

**Comment by zero-24** [comment] 2017-02-10 10:20
Closed as it is fixed with the next update. Thanks.

**Closed by zero-24** 2017-02-10 10:20 UTC
Labels: No Code Attached Yet

**Comment by thebasix** [comment] 2017-02-24 11:36
How to fix this on 3.6.5?

**Comment by zero-24** [comment] 2017-02-24 11:39
Please try this: https://github.com/joomla/joomla-cms/pull/12611

**Comment by thebasix** [comment] 2017-02-24 11:51
I updated from 3.6.2 to 3.6.5 and now TOS Label is not link anymore (modal is not displayed on clicking the lable)

This pull request is not a solution. Any suggestions?

**Comment by AlexRed** [comment] 2017-02-24 17:10
try this: https://docs.joomla.org/J3.x:Update_from_3.6.x_to_3.6.5_Profile_fields
