### ISSUE TITLE
?format=html is appended to the URL

### ISSUE THREAD

**Issue by Merl06** [joomla/joomla-cms#39181] opened 2022-11-09 08:37 UTC
### Steps to reproduce the issue
Good afternoon!

I use Joomla ‎4.2.4 (Multi-language) + Language filter (languagefilter) + standard SEF (I don't use anything third-party)

As a result, links of the form are generated: domain.ru/page.html and domain.ru/en/page.html
but if you go, by clicking on the language switcher, to the en version of the site - then back - then it redirects to a URL of the form

domain.ru/page?format=html (although, obviously, this URL does not appear anywhere)

I found out that this problem occurs if you enable the "Remove language code from URL" option in the language filter.

**Comment by snegicodes** [comment] 2022-11-17 17:41
I would like to work on this issue, can you assign me this one please?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39181">issues.joomla.org/tracker/joomla-cms/39181</a>.</sub>

**Comment by snegicodes** [comment] 2022-11-17 17:41
I would like to work on this issue, can you assign me this one please?

**Comment by bembelimen** [comment] 2022-11-17 17:50
Just work on it and create a pull request when you have fixed it.

**Comment by Merl06** [comment] 2022-11-18 04:20
I will be glad if you solve this problem. After all, it did not occur to me
alone, I just reported it.


чт, 17 нояб. 2022 г. в 19:50, Benjamin Trenkle ***@***.***>:

**Comment by drmenzelit** [comment] 2022-11-19 13:34
@Merl06 the comment from @bembelimen was related to the question from @snegicodes . We don't asign issues, if someone has an idea how to solve it, she/he can create a pull request.

**Comment by snegicodes** [comment] 2022-11-19 17:12
@Merl06 Actually I am not facing the issue myself, so can you please provide me with the steps to reproduce the bug?

**Comment by Merl06** [comment] 2022-11-19 18:20
install two languages, enable the "language filter" plugin and the
"language switching" module.
In the "language filter" plugin, enable the "Delete default language code"
option. the problem appears when you switch to a version of the material in
which the language is set to the default content language, instead of the
suffix appears "?format=html " the problem only appears if you click on the
language identifier, which is set by default in the "language switching"
module

сб, 19 нояб. 2022 г. в 19:12, Sarthak Negi ***@***.***>:

**Comment by Ltamann** [comment] 2022-12-03 11:28
I tested overwriting mod_language.
The problem seems to come from when we select the "remove language code from url" all our default language websites don't get the language tag /en/ or /ru/ in the url but thelanguage switcher add that url to its link. This is causing a redirect from Joomla and possibly the redirect adds the ?format=html.
In mod_language we can remove the /en/ from the url and the link will be OK. BUT the language selection brakes. Libraries/src/Language does not recognize the selected language and does not write the changes into the cookies.
So this doesn't work - the language switcher currently requires the language tag in all urls. The only solution we see at this moment without changing core code is to generate custom redirects for each affected url.
Needs a solution - it's not good for SEO to use internal links that create redirects.
Tip you can remove baseurl in mod_language - the active language do not need a baseurl.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39181">issues.joomla.org/tracker/joomla-cms/39181</a>.</sub>

**Comment by Ltamann** [comment] 2022-12-03 11:37
It's definitely a problem with the joombla redirect and not the language switcher!

To test, copy the link with the code lang_your.domain.com/en/xxxxx.html directly into the browser and you will get the same result your.domain.com/xxxxx.?format=html.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39181">issues.joomla.org/tracker/joomla-cms/39181</a>.</sub>

**Comment by Ltamann** [comment] 2022-12-03 12:39
Its not perfect but if you add this to mod_language default.php it seems to do the job.
Add it under each  "php foreach ($list as $language)" loop
The only thing to have in mind is that the prefix of your language has to be the standard prefix so for en_GB is has to be en!   

 $config =& JFactory::getConfig();
     $defaultlang = substr($config->get( 'language' ), 0, 2);
            if (!$language->link == '/'.$defaultlang.'/') {
            if (substr($language->link, 0, 3) == '/'.$defaultlang) {
                $language->link = substr($language->link, 3); 
                }
            }<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39181">issues.joomla.org/tracker/joomla-cms/39181</a>.</sub>

**Comment by Merl06** [comment] 2022-12-03 12:39
I don't have the necessary experience and knowledge to fix this, so I'm
asking for help...

сб, 3 дек. 2022 г. в 13:37, Ltaman ***@***.***>:

**Comment by Ltamann** [comment] 2022-12-03 14:09
Hi Merl06
1. make a copy of yor page - use the copy for the test offline or online on a subdomain.
2. make an override of mod_language - there are many toturials online (https://www.joomlart.com/tutorials/joomla-4-tutorials-how-to-create-override-for-modules-components-and-layout)
4. open and edit : your template/html/mod_language/mod_languages/default.php
5. enter my code under both < ? php foreach ($list as $language) : ?> 
6. the code has to be inside < ?php CODE  ?>
Test It

**Comment by Ltamann** [comment] 2022-12-03 15:13
Adding my code to mod_languages solves the multianguage menu but crawling the side there are other url get requests with ?format=html.
Joomla docs is pointing to the SEF router:

https://docs.joomla.org/URLs_in_Joomla<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39181">issues.joomla.org/tracker/joomla-cms/39181</a>.</sub>

**Comment by Merl06** [comment] 2022-12-04 03:08
Dear Ltaman, thank you for helping me solve this problem. I followed your
advice and did everything as you wrote, but I did not get the result,
unfortunately ....

сб, 3 дек. 2022 г. в 17:13, Ltaman ***@***.***>:

**Comment by Ltamann** [comment] 2022-12-04 08:30
Dear Merl06,

first try if you have the same ?format=html problem we are talking about.
Do the following:
Open a random page of your Site in your main language like: https://www.xxxx.com/myarticle.html
add your default language code to the url (if english=en): https://www.xxxx.com/en/myarticle.html
The page should open like this https://www.xxxx.com/myarticle?formalt=html

If this is happening than you can do this:
Check your Setting;
1. For Joomla ‎4.2.5 tested
2. Language filter (languagefilter)  enable the "Remove language code from URL" in Language filter plugin
![Captura de pantalla 2022-12-04 084829](https://user-images.githubusercontent.com/2974923/205480145-a8755fb0-dbaa-4213-911b-3c05c06a4f8d.png)
3.  My  System ->Global Configuration SEO settings:
![image](https://user-images.githubusercontent.com/2974923/205481125-5b11716e-f629-4eb8-883e-78bf18632291.png)
5. Set templetes default language, tested with es :
![image](https://user-images.githubusercontent.com/2974923/205480082-0d697d04-ac25-46b4-bf5d-3533f184aa90.png)
6. for any testing you have to disable all cache functions, if not you will see only the cached version of your site / if you use Jommla without thirtparty cache plugins turn off:  System ->Global Configuration -> Server -> System Cache = OFF
- clear the cache:  Home Dashboard -> cache -> clear cache
- turn off Plugin System-Page cache
7. As first step change only this code in ../plugins/system/languagefilter/languagefilter.php add line 451
![image](https://user-images.githubusercontent.com/2974923/205480212-d0a37806-df2f-461d-9e81-94c8b9bba292.png)

test again: https://www.xxxx.com/en/myarticle.html should open like https://www.xxxx.com/myarticle.html 

If not try to disabel all other plugins thirtparty plugins and/or switch for testing to joombla standart template.

Keep in mind that the changes in  ../plugins/system/languagefilter/languagefilter.php will by overwritten by any new joomla update.

**Comment by Merl06** [comment] 2022-12-04 14:48
Dear Ltaman, thank you very much. Your advice with 451 lines works fine, I
think this fix will be useful for many Joomla users

вс, 4 дек. 2022 г. в 10:31, Ltaman ***@***.***>:

**Comment by ptdev** [comment] 2023-07-19 15:28
Hi,

This issue is still present on Joomla 4.3.3.

It's a small issue but really affects the consistency of a website's URL structure.

The fix posted above seems to be working but involves manually editing a core file which is not ideal.

Are there any predictions for an official fix?

**Comment by sergeytolkachyov** [comment] 2023-08-11 06:07
I have had the same issue. But I disable a url suffix in global params and added this redirect to htaccess
`RedirectMatch 301 "(.*)\.html$" "$1"`
The all of my pages transfered from `site.ru/page.html` to `site.ru/page`.

**Comment by Slava287** [comment] 2023-11-06 09:38
Hi there is a solution for joomla 5?  Then the above solution is not working<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39181">issues.joomla.org/tracker/joomla-cms/39181</a>.</sub>

**Comment by capogr** [comment] 2023-12-20 20:13
Big SEO problem with this one still no official fix?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39181">issues.joomla.org/tracker/joomla-cms/39181</a>.</sub>

**Comment by Hackwar** [comment] 2024-02-05 10:20
I just checked this and can not reproduce this. Can someone provide a copy of a site where this is happening to debug this?

**Comment by Slava287** [comment] 2024-02-05 20:24
> I just checked this and can not reproduce this. Can someone provide a copy of a site where this is happening to debug this?
Since the problem was not solved and generated many new duplicates, I had to switch to a version without .html. Once I removed the suffix, the problem was solved.

**Comment by Slava287** [comment] 2024-02-05 20:24
> I just checked this and can not reproduce this. Can someone provide a copy of a site where this is happening to debug this?

Since the problem was not solved and generated many new duplicates, I had to switch to a version without .html. Once I removed the suffix, the problem was solved.

**Comment by Hackwar** [comment] 2024-03-29 10:50
Since I did not get any further feedback on this and I can't replicate this, I'm closing this one.

**Comment by mediaket** [comment] 2024-06-03 18:17
Hi there :)

The problem persists in joomla 5.1.0 and joomla 5.1.1. The solution provided here resolves the problem, but you have to repeat the same operation each time you update Joomla.

Thank you.

Screenshot:

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39181">issues.joomla.org/tracker/joomla-cms/39181</a>.</sub>

**Comment by Slava287** [comment] 2024-06-03 23:59
> Since I did not get any further feedback on this and I can't replicate this, I'm closing this one.

Hello. There is a website where this problem exists, how can I contact you?

**Comment by Hackwar** [comment] 2024-06-04 07:12
Write me at info@joomlager.de

**Comment by Hackwar** [comment] 2024-06-04 08:43
I was able to replicate this. Reopening the issue.

**Comment by Slava287** [comment] 2024-06-05 15:44
Should we expect a solution in the near future? The problem has simply existed for a long time. Please also pay attention to the problem of tags, I created a topic. The problem is the most serious because it greatly affects SEO.

**Comment by Hackwar** [comment] 2024-06-05 16:35
It depends. Either someone else picks this up or I have to find the time to work on this and to be honest, my volunteer time right now is rather limited. It might take until 5.3 to fix this.

**Comment by Slava287** [comment] 2024-06-05 17:08
I understand you perfectly, thank you for your work!

**Comment by Hackwar** [comment] 2024-08-20 08:43
Can you please check #43858? The PR is not perfect yet, but it should solve your issue in the longterm. As I wrote, it will probably be part of 5.3. It wont be ready in time for 5.2.

**Closed as completed by Hackwar** 2024-08-20 08:43 UTC
Labels: No Code Attached Yet, bug

**Comment by Slava287** [comment] 2025-01-23 22:51
Hello. Joomla! 5.2.3 Stable. This doesn't work.

**Comment by cyb3rx** [comment] 2025-02-07 16:10
Hello!
I just encountered the same problem, exactly as described before me.
When is this expected to be resolved?
I see it has been going on for almost 3 years, is it really that big of a deal that it takes so long to resolve?

**J5.2.2**



Thx!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39181">issues.joomla.org/tracker/joomla-cms/39181</a>.</sub>

**Comment by fgsw** [comment] 2025-02-07 16:19
> I see it has been going on for almost 3 years, is it really that big of a deal that it takes so long to resolve?

@cyb3rx The mentioned Pull Request #43858 hasn't the needed 2 successfully test so it can't be merged. You can help and test the Pull Request.

**Comment by cyb3rx** [comment] 2025-02-07 16:24
> > I see it has been going on for almost 3 years, is it really that big of a deal that it takes so long to resolve?
> 
> [@cyb3rx](https://github.com/cyb3rx) The mentioned Pull Request [#43858](https://github.com/joomla/joomla-cms/pull/43858) hasn't the needed 2 successfully test so it can't be merged. You can help and test the Pull Request.

ok, what can I do?

**Comment by fgsw** [comment] 2025-02-07 16:43
> ok, what can I do?

#### How i test

- Created a free site by [launch.joomla.org](https://launch.joomla.org)
- update the installation with the prebuilt package of the Pull Request:

![Image](https://github.com/user-attachments/assets/6d849c1b-e6d8-4957-b9e8-8fe163325fbd)
- read the ```Testing Instructions``` of the Pull Request

#### After successfully test

open https://issues.joomla.org/tracker/joomla-cms/43858 and 

- login with your github-account
- click button "Test this"
- mark "Tested successfully"

Now the test count as successfull.
