### ISSUE TITLE
Joomla 4 - Wrong alert on SQL FILE (CREATE TABLE IF NOT EXISTS)

### ISSUE THREAD

**Issue by fredhob** [joomla/joomla-cms#36595] opened 2022-01-07 08:36 UTC
### Steps to reproduce the issue

Install an extension with an install sql file contain the command "CREATE TABLE IF NOT EXISTS"

### Expected result

No alert on Joomla administration

### Actual result

Alert in SQL alerts => "Table 'IF' does not exist. (From file 1.0.0.sql.)

### System information (as much as possible)

Joomla 4.0.5

**Comment by brianteeman** [comment] 2022-01-07 08:41
Joomla is correct

https://dev.mysql.com/doc/refman/8.0/en/create-table.html

**Comment by HLeithner** [comment] 2022-01-07 09:09
The SQL file is shipped with the extension and the error message is generated by the SQL server. The extension dev has to fix the SQL query.

I'm closing this since not a core issue.

**Comment by richard67** [comment] 2022-01-07 21:11
@HLeithner I think you misunderstood. The error is from the database checker, I think, and the SQL script is a schema update of a 3rd party extension, as you can see by the script name. The database checker does not understand the optional IF NOT EXISTS keywords in a CREATE TABLE statement before the table name, but it is valid SQL for both MySQL and MariaDB. It’s just the database checker (MySQL change item) which currently doesn’t understand that. I am working on a PR to change that, but it might take a bit time. Nevertheless right. Ow it is expected (but undocumented) behavior.

**Comment by richard67** [comment] 2022-01-07 21:14
@brianteeman As you can see in the docs you have linked and could see in the equivalent docs for MariaDB, the optional keywords IF NOT EXISTS before the table name are valid SQL for these databases (as well as PostgreSQL). The author of the issue just hasn’t posted the complete statement. He has omitted the table name.

**Comment by richard67** [comment] 2022-01-07 21:15
We should never have made the db checker check also 3rd party extensions in J4. Just my 5 ct.

**Comment by brianteeman** [comment] 2022-01-07 21:20
>The author of the issue just hasn’t posted the complete statement. He has omitted the table name.

Your ability to read invisible ink is obviously better than mine :)

**Comment by HLeithner** [comment] 2022-01-07 21:21
ok in this case please fix it ;-)

**Comment by richard67** [comment] 2022-01-07 21:25
Hmm, I might have to correct myself. The MySQL change item handles that, too: https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Schema/ChangeItem/MysqlChangeItem.php#L213-L227

So it seems the SQL statement in the SQL script really is incomplete.

**Comment by richard67** [comment] 2022-01-07 21:26
@fredhob Could you post here the complete SQL statement from that file 1.0.0.sql so we can see what the error is? Thanks in advance.

**Comment by richard67** [comment] 2022-01-07 21:27
I was maybe confused by a similar recent issue with other optional keyword which was really not supported by the checker.

**Comment by HLeithner** [comment] 2022-01-07 21:36
ok no problem thanks for rechecking, in this case I close it until @fredhob provides a complete sql script so we can reproduce the error.

**Closed as completed by HLeithner** 2022-01-07 21:36 UTC

**Comment by fredhob** [comment] 2022-01-10 07:32
Ok i understand the "problem" in my sql script, no space between EXISTS and the table name:

CREATE TABLE IF NOT EXISTS`#__table`

And Joomla 4 don't like it<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36595">issues.joomla.org/tracker/joomla-cms/36595</a>.</sub>

**Comment by richard67** [comment] 2022-01-10 07:38
> Ok i understand the "problem" in my sql script, no space between EXISTS and the table name:
> 
> CREATE TABLE IF NOT EXISTS`#__table`
> 
> And Joomla 4 don't like it

Thanks for reporting back. Joomla is right at this point, without the space it's not valid syntax. The database may be tolerant with that and not throw an SQL error, depending on server settings, but we should not try to adapt our database checker to such tolerance of invalid SQL.
