### ISSUE TITLE
[4.0] com_media not possible to upload an avif image

### ISSUE THREAD

**Issue by hans2103** [joomla/joomla-cms#30666] opened 2020-09-17 08:13 UTC
### Steps to reproduce the issue

Go to the blog [AVIF has landed](https://jakearchibald.com/2020/avif-has-landed/) by Jake Archibald and download an AVIF image.

> AVIF is a new image format derived from the keyframes of AV1 video. It's a royalty-free format, and it's already supported in Chrome 85 on desktop. Android support will be added soon, Firefox is working on an implementation, and although it took Safari 10 years to add WebP support, I don't think we'll see the same delay here, as Apple are a member of the group that created AV1.

- Login Joomla 4.0 Administrator > Content > Media
- Try to upload the AVIF image

### Expected result

The file should be uploaded

### Actual result

<img width="785" alt="Schermafbeelding 2020-09-17 om 10 11 46" src="https://user-images.githubusercontent.com/639822/93438987-49016100-f8ce-11ea-9dbc-054438790126.png">

### Requested change

The media manager should be adjusted to allow uploading AVIF images.

**Comment by richard67** [comment] 2020-09-17 08:33
@hans2103 Have you added ".avif" to both the list of allowed file types "Legal Extensions (File Types)" and the list of allowed images "Legal Image Extensions (File Types)" in the media manager's options? And if "Check MIME Types" is switched on in the options, which is the default, have you also added "image/avif" to the list of allowed MIME types "Legal MIME Types"?

**Comment by hans2103** [comment] 2020-09-17 08:44
Joomla Administrator > Content > Media > Options
- _Legal Extensions (File Types)_ => added `,avif,AVIF`
- _Check MIME Types_ = YES (by default)
- _Legal Image Extensions (File Types)_ => added `avif`
- _Legal MIME Types_ => added 'image/avif`

Tried to upload an AVIF image. 
The result:

<img width="1116" alt="Schermafbeelding 2020-09-17 om 10 35 07" src="https://user-images.githubusercontent.com/639822/93447417-abf4f700-f8d2-11ea-805e-10803d991db7.png">

Concluding two things:
- there is no English translation for this text variable
- it is not possible to upload an avif image

**Comment by SharkyKZ** [comment] 2020-09-17 19:20
The MIME type is `image/heif`.

**Comment by SharkyKZ** [comment] 2020-09-17 19:31
For missing string issue see PR https://github.com/joomla/joomla-cms/pull/30671.

**Comment by hans2103** [comment] 2020-09-18 08:37
Added MIME type `image/heif`. Uploading an AVIF image is not possible with the same error message as mentioned earlier

**Comment by SharkyKZ** [comment] 2020-09-18 08:42
Can you post a link to the image for testing?

**Comment by hans2103** [comment] 2020-09-18 08:51
I've been using one of the avif images downloaded from the article mentioned in the description of this issue
- article => https://jakearchibald.com/2020/avif-has-landed/
- used image => https://jakearchibald.com/c/f1-good-a14c8cc5.avif

**Comment by richard67** [comment] 2020-09-18 17:02
What happens if you switch off "Check MIME Types" in media manager options?

**Comment by SharkyKZ** [comment] 2020-09-18 17:05
It's recognized as having `application/octet-stream` MIME type. There's PR https://github.com/joomla/joomla-cms/pull/25351 for improving MIME detection but I don't think it's going to help in this case.

**Comment by richard67** [comment] 2020-09-18 17:09
Yes, but I wanted to know what happens when the MIME type check is switched off.

**Comment by SharkyKZ** [comment] 2020-09-18 17:21
It works without MIME check.

**Comment by richard67** [comment] 2020-09-18 17:22
So the MIME check is the broken thing? Maybe it just can't handle that new format yet? Maybe our dependency needs an update for that?

**Comment by richard67** [comment] 2020-09-19 09:51
The MIME type is determined in the MediaHelper class here:

https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Helper/MediaHelper.php#L65

For images, following functions are used if available, one after the other:
- exif_imagetype
- getimagesize
- mime_content_type
- finfo_open

The availability of these functions depends on PHP version and available PHP extensions, and if avif images are included in the corresponding extensions or in case of mime_content_type in the magic file may depend on the particular PHP extension's version.

**Comment by Quy** [comment] 2020-10-25 22:04
Please test PR  #31233 using mimetype `application/octet-stream`.

**Comment by hans2103** [comment] 2020-10-27 10:43
PR https://github.com/joomla/joomla-cms/pull/31233 has already been merged. 
@Quy what should I change in the settings to get an .avif file being uploaded?
The mentioned error remains

**Comment by Quy** [comment] 2020-10-27 11:44
I am not at a computer to double check. Add avif to filetype and image extension settings. For the mime type please add the avif file manually to the images folder and click the info icon to see its mime type value to use for the mime type setting.

**Comment by Quy** [comment] 2021-01-08 17:43
Using `application/octet-stream` works for me.

![avif](https://user-images.githubusercontent.com/368084/104047081-ea6e3480-5195-11eb-9c64-1ce314ec24e9.png)

**Comment by morsssss** [comment] 2021-01-16 02:06
Thanks, @brianteeman , for letting me know about this.

I imagine the problem is that Joomla doesn't support AVIF, because PHP-GD doesn't support AVIF - which is because libgd doesn't include AVIF support?

If so, I'm working on that right now. You can follow my progress (and I very much hope there will be good news soon) at https://github.com/libgd/libgd/issues/557 .

**Comment by morsssss** [comment] 2021-02-26 22:24
Just wanted to let you know that this PR is almost out of review. I expect it to be merged soon!

**Comment by morsssss** [comment] 2021-03-04 03:23
And... it's merged.

**Comment by richard67** [comment] 2021-03-04 08:46
Thanks @morsssss for that PR there and for keeping us up to date.

So the next step is that they make a new release, then we can maybe pull it into the CMS (if no B/C breaks).

@morsssss Could you have an eye on it and let us know here when they've made a new release? If not, it's not a problem, just let us know then someone else will watch it hopefully. But if you can: Thanks in advance, that would really be a help.

**Comment by morsssss** [comment] 2021-03-06 14:15
Yes - definitely!

I'm following the progress [here](https://github.com/libgd/libgd/milestone/2).

**Comment by Quy** [comment] 2021-03-10 17:26
GD 2.3.2 released: https://github.com/libgd/libgd/releases/tag/gd-2.3.2

**Comment by alikon** [comment] 2021-03-10 17:34
on my php 7.4.9 is 2.3.0 for example

**Comment by richard67** [comment] 2021-03-10 17:42
@alikon It needs to fetch gd-2.3.2 with a composer update. Could you make the PR?

**Comment by alikon** [comment] 2021-03-10 17:45
i didn't think it is a composer matter
but correct me if i'm wrong :smiley:

**Comment by alikon** [comment] 2021-03-10 17:46
did you mean this one ? https://github.com/joomla/joomla-cms/blob/4.0-dev/composer.json#L83

**Comment by richard67** [comment] 2021-03-10 17:51
@alikon I think so, but I might also be wrong.

**Comment by morsssss** [comment] 2021-03-10 17:52
TIL over the weekend: PHP core maintainers told me that PHP's version of gd diverged from libgd long ago. I looked at [the source](https://github.com/php/php-src/tree/master/ext/gd), and, sure enough, it's true. It's quite different from libgd. It's even full of PHP-specific functions like `zend_error()`.

Reading the last couple of comments, I looked at a [sample PHP version of a GD file from v7.4.0](https://github.com/php/php-src/blob/PHP-7.4.0/ext/gd/libgd/gd_webp.c). It, too, has `zend_error()`.

I haven't been working with PHP much for the last few years. Do you know whether the external libgd is necessary at all? I do see it in the composer file @alikon just mentioned. I just don't know how it's used.

`libavif`, on the other hand, should be required.

So, as far as I can tell, the next steps here are:
* propagate the new AVIF support from libgd into PHP's fork. This mostly involves `gd_avif.c`.
* Get PHP's `getimagesize()` function to recognize AVIF. The good news is that there's already [a PR for that](https://github.com/php/php-src/pull/5127).

**Comment by morsssss** [comment] 2021-06-18 17:24
Just wanted to provide you all with an update.

[My PR](https://github.com/php/php-src/pull/7026) to propagate AVIF support into PHP's bundled gd library has been approved and merged. This should be included when PHP 8.1 [is released in November](https://wiki.php.net/todo/php81). It'll be available in beta in July!

[My followup PR](https://github.com/php/php-src/pull/7091) to provide AVIF support in `getimagesize()` and `imagecreatefromstring()` is nearing approval as well.

So: it's good news!

**Comment by dgrammatiko** [comment] 2021-07-02 13:10
@morsssss I created a package that adds support for Avif (amongst other things) to any Joomla 4 site:

https://responsive-images.dgrammatiko.dev/faq/index.html

code:
https://github.com/ttc-freebies/plugin-responsive-images/tree/4.0.0

**Comment by morsssss** [comment] 2021-07-02 21:52
@dgrammatiko hey, that's excellent!

You didn't need to wait for support in PHP? Do you use libgd or Imagick independently?

**Comment by Stuartemk** [comment] 2021-09-16 15:06
4.0.3 native ready for images AVIF?

**Comment by dgrammatiko** [comment] 2021-09-16 15:12
> 4.0.3 native ready for images AVIF?

Not yet: https://github.com/joomla/joomla-cms/blob/a181a6891413c076e87e73d8100203bd37e4fdd2/administrator/components/com_media/config.xml#L80

You can use https://responsive-images.dgrammatiko.dev though to get AVIF, WebP and srcsets for free

**Comment by morsssss** [comment] 2021-09-16 16:09
In any case, as far as I know, full AVIF support will be released in PHP 8.1.

And, yes, @dgrammatiko 's plugin :)

**Comment by brianteeman** [comment] 2023-04-10 10:57
is this resolved with https://github.com/joomla/joomla-cms/pull/35752/ ??

**Comment by richard67** [comment] 2023-08-17 13:30
Closing as having a pull request. Please test #41381 . Thanks in advance.

**Closed as completed by richard67** 2023-08-17 13:30 UTC
Labels: No Code Attached Yet, Information Required, bug
