### ISSUE TITLE
Public menu item to restricted content gives 404

### ISSUE THREAD

**Issue by virusyscorp** [joomla/joomla-cms#5466] opened 2014-12-18 13:18 UTC
#### Steps to reproduce the issue
Clean install 3.3.6 w/ English sample content - make both category and page in it with registered permissions. Make new public menu item to category.

#### Expected result
When user is NOT logged in, menu item should lead to login page. 

#### Actual result

Menu item leads to 404 Category not found when user NOT logged in. Works fine when user IS logged in.

#### System information (as much as possible)
J3.3.6 clean install

#### Additional comments
This used to work in J2.5 - you were presented with a login page when trying to access restricited content.

**Comment by oyeaussie** [comment] 2015-03-30 08:48
Any update on this issue? we ran into the same issue due to parent category permission which did not allow the group (public), so if we access a direct sub-menu without login, it would give us 404. Instead redirecting to login page would help.

**Comment by pe7er** [comment] 2016-05-07 10:51
I was able to reproduce the issue with Joomla **3.6.0-dev** with default test data:
1. Category "Park Blog" access level set to registered
2. Articles in "Park Blog" set to public
3. Menu item of type Category Blog with access level public:

On front-end: > All Front End Views > clicking on "Article Category Blog" will result in a 404 error.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5466">issues.joomla.org/joomla-cms/5466</a>.</sub>

**Comment by pe7er** [comment] 2016-05-07 10:56
Not sure how to solve this. The 404 is triggered in libraries/legacy/view/category.php because $category is empty:
    public function commonCategoryDisplay()
    {
    if ($category == false)
        {
        return JError::raiseError(404, JText::_('JGLOBAL_CATEGORY_NOT_FOUND'));
        }

That library is called from components/com_content/views/category/view.html.php
    public function display($tpl = null)
    {
    parent::commonCategoryDisplay();
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5466">issues.joomla.org/joomla-cms/5466</a>.</sub>

**Comment by andrepereiradasilva** [comment] 2016-05-13 00:46
i think the category false comes from https://github.com/joomla/joomla-cms/blob/staging/components/com_content/models/category.php#L337

**Comment by rdeutz** [comment] 2016-08-15 21:24
Closing this here because we have a PR #11624

**Closed by rdeutz** 2016-08-15 21:24 UTC
Labels: No Code Attached Yet
