### ISSUE TITLE
[4.0] Custom Element styling

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#28626] opened 2020-04-10 14:48 UTC
Elements like alerts appear to import styling upstream from the custom-element repo and then proceed to mostly override that styling locally. The result is at least twice as much CSS as is required.

https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/templates/atum/scss/vendor/joomla-custom-elements/joomla-alert.scss#L12

Styling should be applied upstream on the custom-elements repo **OR** remove the import and style locally.. not both.

**Comment by brianteeman** [comment] 2020-04-10 14:53
agree 100% it should be one or the other and not both

**Comment by ciar4n** [comment] 2020-04-10 16:09
~~One option....  #28627~~

**Comment by ciar4n** [comment] 2020-04-10 17:16
Turns out there is 2 different styles of alert. The second style overriding the first depending on where it is rendered. :unamused:

So regarding the alerts, it is not as bad but still weird.

**Comment by wilsonge** [comment] 2020-04-10 23:22
Do we really need two styles of alert. I have to admit the stuff in the sample data install that is inline does look a bit weird. But feels like there should be a better way of handling it somehow

**Comment by brianteeman** [comment] 2020-04-10 23:39
Well we do need inline alerts to satisfy #27391

**Comment by brianteeman** [comment] 2023-02-24 23:19
Is this a duplicate of #22842

**Comment by Hackwar** [comment] 2024-11-26 17:55
I'm deciding that this is a duplicate of #22842 and thus will close this ticket.

**Closed as completed by Hackwar** 2024-11-26 17:55 UTC
Labels: No Code Attached Yet, Information Required, bug
