### ISSUE TITLE
Calendar doesn't use languagestrings

### ISSUE THREAD

**Issue by MatthiasHazeleger** [joomla/joomla-cms#18984] opened 2017-12-05 12:59 UTC
### Steps to reproduce the issue
Create an XML calendar field, use a languagestring as format in the format field.

Example:

format="DATE_FORMAT_LC3"

### Expected result
Date shown in the given format.

Example:

Tuesday, 05 December 2017

### Actual result
The given languagestring.

Example:

DATE_FORMAT_LC3

### System information (as much as possible)
- Joomla v3.8.1 Stable
- PHP v7.1.9
- Apache

### Additional comments
The 'translateformat' field doesn't really do anything useful, the documentation says it changes the shown date format using "a" language string, but that languagestring is already the default format. It would be useful if a language string could be given to it.

**Comment by infograf768** [comment] 2017-12-05 13:31
@Bakual please explain this user the difference between a calendar field and a date field. :)

**Comment by Bakual** [comment] 2017-12-05 14:40
The `translateformat` attribute does automatically use a localised dateformat. You can only customise if it should show also the time or not.
The `format` attribute is ignored if `translateformat` is enabled. Also the `format` attribute can't be translated. It wouldn't make sense anyway since you need a different format when reading and when storing the date.

**Comment by Bakual** [comment] 2017-12-05 14:40
Closing as expected behavior

**Closed as completed by Bakual** 2017-12-05 14:40 UTC
Labels: No Code Attached Yet
