### ISSUE TITLE
News Feed not working in 3.4

### ISSUE THREAD

**Issue by hcfd1455** [joomla/joomla-cms#7528] opened 2015-07-22 18:45 UTC
#### Steps to reproduce the issue
Create a new Newsfeed
Components>Newsfeeds>Feeds Create New
Use the following newsfeed link: http://feeds.feedburner.com/GoogleAppsUpdates?format=rss

Create New Menu Item>Newsfeed>Single Newsfeed. Select the previously created feed. 
View the newly created menu item

#### Expected result

Should pull the feed the way it is pulled in a 2.5 site like the following: 
http://new25.cloudaccess.host/index.php/news

#### Actual result

Creates a list of links like the following: 
http://new30.cloudaccess.host/index.php/news

Each of those links results in a blank page with the following in the url:
tag:blogger.com,1999:blog-5817251852531867331.post-8534696159248712488

#### System information (as much as possible)
Windows 7 Professional Service Pack 1
Intell Core i5-3210M CPU @ 2.5GHz
RAM 4GB
64-bit Operating System

#### Additional comments
This has been tested and works fine on 2.5. It semi worked on 3.0 taking you directly to the link: http://feeds.feedburner.com/GoogleAppsUpdates?format=rss rather than pulling in the feed. 

I then upgraded and tested on a 3.2.7 site and this is when the feed broke. As far as I can tell, 3.2.7 is when this feature broke.

**Comment by brianteeman** [comment] 2015-07-22 19:12
I can confirm newsfeeds have issues as described above with that feed
I tested with http://feeds.joomla.org/JoomlaAnnouncements and it worked perfectly

**Comment by Bakual** [comment] 2015-07-22 19:32
http://feedvalidator.org/check.cgi?url=http%3A%2F%2Ffeeds.feedburner.com%2FGoogleAppsUpdates%3Fformat%3Drss shows the feed as valid, but has a lot of recommendations for improving interoperability.
Interesting enough it shows the feed as an Atom 1.0 feed despite the URL indicating requesting an RSS feed.

I guess it's related to those things somehow.

**Comment by vdespa** [comment] 2015-07-24 19:45
First of all, it makes no sense to compare it to the 2.5.x because parser has been completely redone. 

Now, the issue with Atom it that is each entry has two fields which are relevant for us: content and summary. Now this particular feed does not have a summary, it only has content.

The atom parser (JFeedParserAtom) relies on "summary" to get its content - which IMHO is wrong.

Substitute summary with content it will work. But this looks like an backward incompatible change to me. 
https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/feed/parser/atom.php#L202<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7528">issues.joomla.org/joomla-cms/7528</a>.</sub>

**Comment by Crispness** [comment] 2015-09-05 20:35
Definitely working on 2.5.28 and not working on the upgraded version of same site on 3.4.3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7528">issues.joomla.org/joomla-cms/7528</a>.</sub>

**Comment by websiteknitter** [comment] 2015-09-22 18:57
I would love for this to get fixed because I have multiple websites without RSS feeds right now :/ In the meantime could somebody tell me what the file path is to find the RSS Feed/Syndicate files because I migrated a site from 2.5 to 3.3.4 a few weeks ago and that RSS feed is still working. I would love to look and see what the differences are between the two files to see if I could create a fix.

**Comment by Bakual** [comment] 2015-09-22 19:09
Valentin linked the file above and also the reason why it fails.

**Comment by brianteeman** [comment] 2016-04-06 11:20
After 6 months without any activity I am closing this at this time.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7528">issues.joomla.org/joomla-cms/7528</a>.</sub>

**Closed** 2016-04-06 11:20 UTC
Labels: No Code Attached Yet

**Comment by dougba** [comment] 2016-04-29 14:49
A lack of activity is not a resolution. This thread should remain open until the issue is resolved.

**Comment by vdespa** [comment] 2016-05-04 19:01
@dougba 

If an issue was not solved in 6 months it shows that this issue is not that important for the community.

If this issue is important for you, feel free to propose a solution and submit a Pull Request for testing. Keeping tons of issues opened is not a solution. It just makes the bug fixing process harder to manage.

**Comment by dougba** [comment] 2016-05-06 19:50
I don't see any relationship between the amount of time an issue remains unsolved and it's importance.
I would propose a solution if I was a coder (I'm not).
This bug prevents feeds from displaying properly on many websites (ours included).
It was working until a Joomla update broke it.
I need it fixed or I need to drastically modify our site.

**Comment by vdespa** [comment] 2016-05-06 20:09
@dougba This issue is almost one year old and this shows that there are not enough people affected by this. If you feel strong about an issue and want to get it fixed, hire a Joomla! developer to fix it.

Meanwhile, since I have already invested some time in this, let us try to solve it. I have a solution for this. Check my comment from Jul 24, 2015.

If you think you can answer my question, I am willing to submit a patch to be tested.
