### ISSUE TITLE
Backend Category Selection give hour glass or busy effect

### ISSUE THREAD

**Issue by GinzaVualzong** [joomla/joomla-cms#16222] opened 2017-05-23 19:25 UTC
### Steps to reproduce the issue
On New Article, select a category

### Expected result
Selecting a category in new article should not give any busy effect. 

### Actual result
Hour glass or busy kind of effect seen. This was not seen previously before J3.7.1

### System information (as much as possible)
I have seen this effect after the 3.7.1 release.

**Comment by sozzled** [comment] 2017-05-23 21:02
I was not able to reproduce the reported fault.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16222">issues.joomla.org/tracker/joomla-cms/16222</a>.</sub>

**Comment by GinzaVualzong** [comment] 2017-05-23 21:12
Ok then the issue must be local<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16222">issues.joomla.org/tracker/joomla-cms/16222</a>.</sub>

**Comment by brianteeman** [comment] 2017-05-23 21:24
i am going to close this at this time as it would appear to be a problem with your specific install. If you need any further assistance then please use the forum https://forum.joomla.org

**Closed by brianteeman** 2017-05-23 21:24 UTC
Labels: No Code Attached Yet
