### ISSUE TITLE
Cannot Order A list of articles in a category

### ISSUE THREAD

**Issue by RobWilkinsonUK** [joomla/joomla-cms#32465] opened 2021-02-19 22:13 UTC
### System information (as much as possible)
Joomla! 3.9.24 
Windows 10
PHP Built On	Linux us52.siteground.us 3.12.18-clouder0 #1 SMP PREEMPT Mon Sep 21 14:18:04 EEST 2020 x86_64
Database Type	mysql
Database Version	5.7.32-35-log
Database Collation	utf8mb4_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	7.3.27
Web Server	Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 3.9.24 Stable [ Amani ] 12-January-2021 15:00 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36

### Additional comments
When I click on a link in the breadcrumbs to display a category the list option is selected but I am unable to order the item by anything other than the order in which the articles were entered.

**Comment by ReLater** [comment] 2021-02-20 00:38
Maybe some screenshots or more detailed "Steps to reproduce the issue" can help to understand the issue. I don't understand what you are talking about.

**Comment by RobWilkinsonUK** [comment] 2021-02-20 12:32
Hi:
![Screenshot](https://user-images.githubusercontent.com/77022135/108595415-bf0e6600-734d-11eb-99d9-422db7125b92.png)

Sorry. I should have been more forthcoming.  You will see from this link that it is a list from the category "2021 Candidates" and the list is in the order they were entered. http://northpennvotes.org/index.php/14-2021-candidates. I am trying to get it alphabetical order by name

No matter where I go to change the order of that list by title. Attached are some screen shots from efforts to change the order.
 I am technical and proficient in Java but not PHP. But I am sure that I could help debug if you need me to. The site is a live site, So I don't want to stray too far with it.
 
 Regards,
Rob

**Comment by brianteeman** [comment] 2021-02-20 13:13
It is probably due to a bug in your template which produces this javascript error when you click on the title
```
Uncaught TypeError: Cannot set property 'value' of undefined
    at Object.e.tableOrdering (core.js?a9b3631d7ca9065548b61b66fafd2ef4:1)
    at HTMLAnchorElement.onclick (14-2021-candidates:129)
```

You can confirm if I am correct and it is the template by temporarily switching to the default protostar template and see if the sort works

**Comment by RobWilkinsonUK** [comment] 2021-02-20 14:02
Hi Brian:
I switched to the prostar template and confirmed that the list sort order was by title and got the same result I am afraid. 
The uncaught error in that is in your email,  how did you generate that.? I inspected the console in chrome and did not see any javascript error when I displayed the page.
Regards,
Rob

**Comment by RobWilkinsonUK** [comment] 2021-02-20 14:03
![screenshot2](https://user-images.githubusercontent.com/77022135/108598226-6c877680-735a-11eb-83e0-a7e6076e6537.png)
Sorry , I forgot to include a new screenshot.

**Comment by RobWilkinsonUK** [comment] 2021-02-20 14:15
Brian:

I have narrowed it down further and fixed the issue.

I was getting to the list directly via the breadcrumbs. I had no actual menu for that category list.

As soon as I created a menu for that list, both the menu item and the breadcrumb link worked!

I confirmed that removal of the menu item altered the behaviour of the breadcrumb link to not recognise the ssort.

Regards,
Rob

**Comment by brianteeman** [comment] 2021-02-21 09:39
This should now be closed as resolved

**Closed as completed** 2021-02-21 09:44 UTC
Labels: No Code Attached Yet
