### ISSUE TITLE
Readmore don't with Featured Articles

### ISSUE THREAD

**Issue by Joomron** [joomla/joomla-cms#39097] opened 2022-10-28 20:07 UTC
### Steps to reproduce the issue
Install Joomla 4
Create an article with a read more button in it.
Mark this article as Featured Articles
The home menu item type must be Featured Articles

### Expected result
On your homepage, you will see article type --> Featured Articles
The read more button in the article does not create a SEF url

### Additional comments
I have tested it with 3 different hosting parties and this problem occurs everywhere.
This issue does not happen with blog rendering.

**Comment by brianteeman** [comment] 2022-10-28 21:09
Not what you want to hear but this is apparently the intended behaviour as it is assumed that you will have a menu link that will link directly to the containing category.

I reported this myself #37253 but no action.

What you can do is to create a menu item "List all Categories.."

![image](https://user-images.githubusercontent.com/1296369/198733039-8233d281-3e75-4a8f-b49f-1ff3f9573add.png)

Then you can set that to "do not display in the menu"

![image](https://user-images.githubusercontent.com/1296369/198733130-6c8a4be2-b08d-4953-9d51-d57b2e7b5b24.png)

**Comment by crystalenka** [comment] 2022-10-29 07:57
I agree that this should be fixed.

**Comment by brianteeman** [comment] 2022-10-29 08:14
There is a bit more information about this on my original report #37253

**Comment by chmst** [comment] 2022-10-29 08:19
https://github.com/joomla/joomla-cms/pull/35228 will work on this and re-test. Maybe this solves the problem for featured articles

**Comment by brianteeman** [comment] 2022-10-29 08:22
@chmst that pr has been stagnant for so long I forgot about it. Taking a quick look at it again I can see that it no longer uses its own controller for featured content so I think you may be correct and that would resolve it.

**Comment by Hackwar** [comment] 2022-11-05 21:39
As @brianteeman wrote, this is intended behavior. Closing this one.

**Closed as completed by Hackwar** 2022-11-05 21:39 UTC
Labels: No Code Attached Yet

**Comment by crystalenka** [comment] 2022-11-06 05:20
Just because it's intended behavior doesn't mean it can't be improved. It is confusing for the end user. 

Can you please explain why this is the intended behavior?

**Comment by brianteeman** [comment] 2022-11-06 11:00
@crystalenka I assume that if the pr @chmst refers to is ever merged then this problem will not be present.
