### ISSUE TITLE
[4 Alpha 12] Tabs Separator is Missing When we Going Right to Left

### ISSUE THREAD

**Issue by lalitkumarjoomdev** [joomla/joomla-cms#26704] opened 2019-10-19 13:34 UTC
### Steps to reproduce the issue
 Menus: Edit Item

### Actual result
https://www.screencast.com/t/fHCR6L0DRQl

### System information (as much as possible)
Window 10
PHP v7.2.19

**Comment by brianteeman** [comment] 2019-10-19 15:39
Please supply a report that does not require installing flash

**Comment by lalitkumarjoomdev** [comment] 2019-10-21 12:51
Hello,

See here: https://www.screencast.com/t/mHphpijgpJjz
Note: Please pay attention to the tab's separator styling in the video.

Thanks,
Lalit

**Comment by Quy** [comment] 2019-12-02 22:25
Unable to reproduce using the latest nightly build. https://developer.joomla.org/nightly-builds.html

![26704](https://user-images.githubusercontent.com/368084/69999871-8eef6300-150e-11ea-9730-3fddc9999fb2.gif)

**Comment by brianteeman** [comment] 2019-12-03 00:02
@quy I get this - page display is the selected tab and the other is the one on hover
![image](https://user-images.githubusercontent.com/1296369/70005062-2cbf4e00-1560-11ea-86c2-e32bee62fd1b.png)

![image](https://user-images.githubusercontent.com/1296369/70005080-38ab1000-1560-11ea-9777-a4fc71258f92.png)

**Comment by infograf768** [comment] 2019-12-03 08:01
Can't reproduce.
Clean Joomla! 4.0.0-beta1-dev 
Firefox Macintosh.
same result as @Quy

**Comment by Quy** [comment] 2019-12-08 16:55
@lalitkumarjoomdev Please test again with the nightly build. https://developer.joomla.org/nightly-builds.html

@brianteeman Are you zooming in for the screenshot?

Please advise which browser you are using.

**Comment by Quy** [comment] 2019-12-09 04:58
This is reproducible with Alpha 12, but not with the nightly build.

**Comment by Quy** [comment] 2020-01-12 19:27
@brianteeman Can you please do a clean install and test again as I cannot reproduce this?

**Comment by chmst** [comment] 2020-02-04 07:57
Can't reproduce.
Clean Joomla! 4.0 dev
Firefox Macintosh.
same result as @Quy

**Comment by Quy** [comment] 2020-02-04 15:43
Closing due to non reproducible/response. Please test with the nightly build and advise browser if still an issue. Thanks.

**Closed as completed by Quy** 2020-02-04 15:43 UTC
Labels: No Code Attached Yet, Information Required
