### ISSUE TITLE
Issues related to menu routing

### ISSUE THREAD

**Issue by ztj1993** [joomla/joomla-cms#17052] opened 2017-07-10 11:57 UTC
Note: the following is about software translation!

Hypothesis:
There is one category: OS
There are two tag: Windows，Linux

### Steps to reproduce the issue
Please note the menu order!

**New Menu Item:**
Alias: windows
Menu Item Type: Articles » Category Blog
Choose a Category: OS
Tags: Windows

**New Menu Item:**
Alias: linux
Menu Item Type: Articles » Category Blog
Choose a Category: OS
Tags: Linux

**New Menu Item:**
Alias: os
Menu Item Type: Articles » Category List
Choose a Category: OS

### Expected result
http://domain/index.php/windows/articleid-1.html
http://domain/index.php/linux/articleid-2.html
--- or ---
http://domain/index.php/os/articleid-1.html
http://domain/index.php/os/articleid-2.html

### Actual result
http://domain/index.php/windows/articleid-1.html
http://domain/index.php/windows/articleid-2.html

### System information (as much as possible)
Joomla 3.7.0 + 

### Additional comments
As mentioned above, the routing is confusing and does not meet the expected results.

**Comment by mbabker** [comment] 2017-07-10 12:28
It's expected behavior (even if it's not really clear or friendly).  The actual menu item is for the category blog, and you've created 3 menu items for the same category.  The tags selection is designed to create an additional filter for that view, but on its own doesn't affect routing.

**Comment by ghost** [comment] 2017-07-10 12:38
closed as expected Behaviour. It can always reopened for further Discussion.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17052">issues.joomla.org/tracker/joomla-cms/17052</a>.</sub>

**Closed as completed by ghost** 2017-07-10 12:38 UTC
Labels: No Code Attached Yet

**Comment by ztj1993** [comment] 2017-07-10 13:09
@mahagr  Even if all three are (Category, Blog), then the path of the article is all (windows/articleid-1.html);

Whether I can be so understanding, namely the first menu must be no label the menu list; if not, then the logic is wrong, because I cannot make use of (Linux) (Windows) of the menu path.

**Comment by ztj1993** [comment] 2017-07-10 13:11
@mbabker My translation may not be accurate, should not be used (routing), and use (path) a bit more accurate.

**Comment by mbabker** [comment] 2017-07-10 13:38
It is a routing issue.  When you have multiple menu items configured to show the same content (in this case, your OS category using the category blog view), when links are generated the system uses the first menu item that matches the configuration.  So in your case, Joomla generates all of the URLs as `/os/1-article.html` but you can manually input `/windows/1-article.html` and `/linux/1-article.html` to get to the same content since you have menu items configured with each of those paths.
