### ISSUE TITLE
Language Overrides: Hyphen stripped from HTML attribute

### ISSUE THREAD

**Issue by michaelmaass** [joomla/joomla-cms#20871] opened 2018-06-26 10:41 UTC
![joomla-language-override-html-attribute-hyphen-stripped](https://user-images.githubusercontent.com/1157704/41906502-4bb3ef9c-793e-11e8-8fa8-002fcc4bf056.jpg)
### Steps to reproduce the issue

In the Joomla! backend go to "Extensions > Language(s) > Overrides", and click on "New" to create a new override. Into the field labeled "Language Constant" enter 

`TEST_CONSTANT`

Into the field labeled "Text" enter the following HTML markup code which includes a valid attribute:

`<span data-type="abc">A</span>`

Click on "Save".

### Expected result

`<span data-type="abc">A</span>`

### Actual result

`<span datatype="abc">A</span>`

Mind: `datatype` as opposed to the originally entered `data-type` with a hyphen.

### System information (as much as possible)

Joomla! 3.8.8

### Additional comments

The hyphen is silently stripped from the attribute name. As far as I can see this is wrong and should be fixed.

I think it is important to mention that the hyphen in a **class** name — or elsewhere in the text — is not stripped. The following is left untouched when the override is saved:

`<span class="my-class">A</span>`

Similar for plain text:

`Swimming-Pool`

Whatever "corrects" the value does not just strip hyphens but seems to make a distinction between HTML *attribute* names and other strings.

According to the W3C documentation a hyphen in an HTML attribute name is valid:
https://www.w3.org/TR/2011/WD-html5-20110525/elements.html#embedding-custom-non-visible-data-with-the-data-attributes
So a "syntax correction" — if that is what happens here — would not be appropriate.

(As a workaround the text can be entered manually into the *.ini file, of course.)

**Comment by mbabker** [comment] 2018-06-26 11:23
Duplicate of https://github.com/joomla/joomla-cms/issues/20579

**Closed as completed by mbabker** 2018-06-26 11:23 UTC
Labels: No Code Attached Yet

**Comment by michaelmaass** [comment] 2018-06-26 11:40
@mbabker 

So the same "agent" is filtering the input of Joomla articles and removes the hyphen there as well?

If so, my report might be a duplicate. Sorry for that. I searched for issues in the Language department.

**Comment by mbabker** [comment] 2018-06-26 11:42
Yes.  The filtering library handles all input filtering and sanitization, regardless of whether you're editing a language override or an article.

**Comment by michaelmaass** [comment] 2018-06-26 11:45
But I am logged in as a Super Administrator and the Filter Type is set to "No Filtering" when that happens.

![no-filtering](https://user-images.githubusercontent.com/1157704/41909388-325b3916-7947-11e8-8026-7d3e1e12c2a7.jpg)

**Comment by mbabker** [comment] 2018-06-26 11:48
That setting applies to how text in WYSIWYG editor fields (such as article editing) is filtered.  There are still other code paths that will result in input being filtered and sanitized separate from that setting.  In your case, the issue was because of a general bug in the filtering library.

**Comment by michaelmaass** [comment] 2018-06-26 11:50
OK, thank you very much for the explanation. :-)
