### ISSUE TITLE
Joomla 3.4 RC: Installation of (crosstec) Template fails

### ISSUE THREAD

**Issue by Bolzman** [joomla/joomla-cms#6155] opened 2015-02-23 11:13 UTC
Installed J3.4RC with german language file (V 3.3.6) using php 5.5.18 / mySQL 5.2.16.

In Extension Manager, choosing to install a tpl_name.zip, using the button upload and install results in a blank page. The Joomla icon appears and it seems like something is happening, the URL changes into http://DOMAINNAME.de/administrator/index.php?option=com_installer&view=install, but the page stays empty. Checking the installed templates basis, nothing has happened so far.

#### Expected result
new installed template

#### Actual result
blank page, no template installed

#### System information (as much as possible)
J3.4RC with german language file (V 3.3.6) using php 5.5.18 / mySQL 5.2.16
OS X Safari 7.x as well as OS X Firefox 35.x
Two different templates from Crosstec.

#### Additional comments
Do not think, it is an issue with the template files, but did not verify with templates from other vendors.

**Comment by zero-24** [comment] 2015-02-23 11:25
@Bolzman please contact Crosstec.

I tryed: BaryonicTemplate from here:
https://crosstec.de/de/downloads/kostenlose-downloads/templates-für-joomla®.html

And get:
Strict Standards: Declaration of RokInstaller::getInstance() should be compatible with JInstaller::getInstance($basepath = '/www/htdoc...', $classprefix = 'JInstaller...', $adapterfolder = 'adapter') in /tmp/install_XXXXX/installer/RokInstaller.php on line 365

looks like there is a error with the last changes on the installer code.

**Comment by zero-24** [comment] 2015-02-23 11:29
and / or http://www.rockettheme.com as the file that throw the error is by http://www.rockettheme.com

```php
/**
 * @package   Installer Bundle Framework - RocketTheme
 * @version   4.1.27 December 31, 2014
 * @author    RocketTheme http://www.rockettheme.com
 * @copyright Copyright (C) 2007 - 2014 RocketTheme, LLC
 * @license   http://www.gnu.org/licenses/gpl-2.0.html GNU/GPLv2 only
 *
 * Installer uses the Joomla Framework (http://www.joomla.org), a GNU/GPLv2 content management system
 */
```

**Comment by wilsonge** [comment] 2015-02-24 10:34
@mbabker is this related to the JInstaller changes you made?

**Comment by mbabker** [comment] 2015-02-24 13:21
The strict standards error is because I added optional arguments to JInstaller::getInstance.  Otherwise, would have to work with the actual extension to determine if those changes are the specific reason.

**Comment by crosstec** [comment] 2015-02-24 21:33
Hi,
Rocket released 4.1.28, I think they fixed this issue in that version.

Regards,
Markus<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6155">issues.joomla.org/joomla-cms/6155</a>.</sub>

**Comment by rdeutz** [comment] 2015-02-25 07:23
so we can close this one?

**Comment by tristandb** [comment] 2015-02-25 11:35
Doesn't seem to be fixed. Installed Rocket/Gantry 4.1.28 this morning (2 hours ago). Installing returns the same message as @zero-24. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6155">issues.joomla.org/joomla-cms/6155</a>.</sub>

**Comment by crosstec** [comment] 2015-02-25 13:27
hm, ok, then let's debug this on the crosstec side. Please contact me at info [at] crosstec [dot] de

Regards,
Markus<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6155">issues.joomla.org/joomla-cms/6155</a>.</sub>

**Comment by brianteeman** [comment] 2015-03-05 23:03
Setting to information required. Please post back if this is not resolved and is an issue I'm the core. If not this will be automatically closed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6155">issues.joomla.org/joomla-cms/6155</a>.</sub>

**Comment by erikharden** [comment] 2015-03-06 05:40
I see this issue has status "information required". What information do you need from me? Still waiting for the fix..





Med vänliga hälsningar


Erik Hårdén

___________________________

web: erikharden.se

twitter: EHardenAB

**Comment by zero-24** [comment] 2015-03-06 08:34
@erikharden 
based on @crosstec message:

>hm, ok, then let's debug this on the crosstec side. Please contact me at info [at] crosstec [dot] de

**Comment by erikharden** [comment] 2015-03-06 08:40
No need to, I believe you when you say it’s an installer error. Just don’t agree on the ”information required”-status. Do you have any estimate on when you are going to fix the momentum-template? If not, please close this issue and I’ll install manually.



Med vänliga hälsningar 


Erik Hårdén

______________________________ 

web: erikharden.se 

tel: 08-55 92 1337 

mail: info@erikharden.se 

twitter: @erikharden 




Har du full koll på din Joomla-hemsida? Om inte - teckna supportavtal för Joomla!

**Comment by brianteeman** [comment] 2015-03-06 09:18
You are getting confused. This is the issue tracker for Joomla not for
crosstec.

I am leaving this information required so that you or crosstec can confirm
that it was indeed an issue with the template from crosstec and not with
the core of joomla. When it is confirmed that it is a crosstec issue we
will close the issue here. If it not a crosstec issue and is indeed an
issue with the core fo joomla then it will need further investigation here
at Joomla

On 6 March 2015 at 08:40, Erik Hårdén <notifications@github.com> wrote:

> No need to, I believe you when you say it’s an installer error. Just don’t
> agree on the ”information required”-status. Do you have any estimate on
> when you are going to fix the momentum-template? If not, please close this
> issue and I’ll install manually.
>
>
>
> Med vänliga hälsningar
>
>
> Erik Hårdén
>
> ______________________________
>
> web: erikharden.se
>
> tel: 08-55 92 1337
>
> mail: info@erikharden.se
>
> twitter: @erikharden
>
>
>
>
> Har du full koll på din Joomla-hemsida? Om inte - teckna supportavtal för
> Joomla!
>
> On Fri, Mar 6, 2015 at 9:34 AM, zero-24 <notifications@github.com> wrote:
>
> > @erikharden
> > based on @crosstec message:
> >>hm, ok, then let's debug this on the crosstec side. Please contact me at
> info [at] crosstec [dot] de
> > ---
> > Reply to this email directly or view it on GitHub:
> > https://github.com/joomla/joomla-cms/issues/6155#issuecomment-77523809
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6155#issuecomment-77524446>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by erikharden** [comment] 2015-03-06 09:40
Hi! Oh, I see, sorry about that. Well, it's not a Joomla-issue. I dont have time to investigation further right now, so if it's okay with you you may close this issue :)





Med vänliga hälsningar


Erik Hårdén

___________________________

web: erikharden.se

twitter: EHardenAB

**Comment by brianteeman** [comment] 2015-03-06 09:49
Closed as requested

**Closed by brianteeman** 2015-03-06 09:49 UTC
Labels: No Code Attached Yet

**Comment by k4lch** [comment] 2015-12-01 15:57
Tried to install templates from rocket themes the gantry 4 failed but tried the gantry 5 template and it installed
