### ISSUE TITLE
smart search $

### ISSUE THREAD

**Issue by tgv604** [joomla/joomla-cms#8034] opened 2015-10-08 06:09 UTC
#### Steps to reproduce the issue
- enable smart search & smart search module
- index content so it's not empty
- search for "$" (single dollar sign)

#### Expected result
some search results

#### Actual result
javascript loop resulting in massive memory leak and eventual browser crash

#### System information (as much as possible)

browser = firefox
OS = Win 10

**Comment by zero-24** [comment] 2015-10-08 08:29
I can confirm this behavior. Chorme on Win 7.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8034">issues.joomla.org/joomla-cms/8034</a>.</sub>

**Comment by Fedik** [comment] 2015-10-08 09:22
looks like here same problem,
it happen when just try to open the search page with `$` search, eg: `/search?q=%24`

**Comment by dgt41** [comment] 2015-10-08 17:41
Not quite a solution but to prevent the fatal error we can modify  line 155 of /components/com_finder/controller.php to 
```php
		if (empty($this->query->search) || $this->query->search == '$')
```
Of course this way no results are sent back :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8034">issues.joomla.org/joomla-cms/8034</a>.</sub>

**Comment by alikon** [comment] 2015-10-14 17:44
confirm issue with  ```%``` char too
can we consider something like search as fatal error prevent solution ?
> Search term must be a minimum of 3 characters and a maximum of 200 characters.

**Comment by dgt41** [comment] 2015-10-14 20:31
Nicola, as far as I remember even a 3 char word like `$do` ends up with fatal error

**Comment by Fedik** [comment] 2015-10-15 15:30
please test #8097

**Comment by zero-24** [comment] 2015-10-15 16:06
Closing as we have a pull thanks

**Closed by zero-24** 2015-10-15 16:06 UTC
Labels: No Code Attached Yet
