### ISSUE TITLE
[5.2] admin template broken

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#43932] opened 2024-08-16 21:16 UTC
### Steps to reproduce the issue
checkout 5.2 and npm i

the fieldsets are being rendered without the required class of "options-form"

### Expected result
![image](https://github.com/user-attachments/assets/c223b162-e58c-47e3-936c-cffe14da8400)

### Actual result

![image](https://github.com/user-attachments/assets/4b64d93e-6358-4a87-9d62-346276d790dc)

**Comment by chmst** [comment] 2024-08-17 09:10
caused by the property $formclass here #43358

**Comment by Fedik** [comment] 2024-08-17 09:19
This need to be public instead of protected: https://github.com/joomla/joomla-cms/blob/501596103b485f363625a04d61428b72f18b8f1a/administrator/components/com_config/src/View/Application/HtmlView.php#L74
and:
https://github.com/joomla/joomla-cms/blob/501596103b485f363625a04d61428b72f18b8f1a/administrator/components/com_config/src/View/Application/HtmlView.php#L81

**Comment by chmst** [comment] 2024-08-17 09:33
closing as there is a PR #43932

**Closed as completed by chmst** 2024-08-17 09:33 UTC
Labels: No Code Attached Yet
