### ISSUE TITLE
[4.0][plugin] blog sample data  error in stemmer

### ISSUE THREAD

**Issue by alikon** [joomla/joomla-cms#31564] opened 2020-12-03 07:47 UTC
### Steps to reproduce the issue
click on install  Blog Sample Data 

### Expected result
sample blog data created

### Actual result
![image](https://user-images.githubusercontent.com/181681/100979520-26352f00-3544-11eb-9115-ca5ce005f741.png)

### System information (as much as possible)

php 8

**Comment by chmst** [comment] 2020-12-03 10:15
You probably are installing italian sample data (from J3.9.23?). Can you see which language string is concerned? How many articles or items were added to the database until the error happened? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31564">issues.joomla.org/tracker/joomla-cms/31564</a>.</sub>

**Comment by chmst** [comment] 2020-12-03 11:00
~~Please test #31566. I cannot test with php 8. It works with php 7.4. as before.~~  Was not the solution  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31564">issues.joomla.org/tracker/joomla-cms/31564</a>.</sub>

**Comment by chmst** [comment] 2020-12-07 09:01
@alikon The problem is the same if saving a tag in com_tags. 

It is caused in stemmerFactory %  must be %s but this is in the vendor library


![screen shot 2020-12-07 at 08 56 21](https://issues.joomla.org/uploads/1/c3a8f0f9708148416dbce16ba3091fc0.png)
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31564">issues.joomla.org/tracker/joomla-cms/31564</a>.</sub>

**Comment by infograf768** [comment] 2020-12-07 09:10
https://github.com/wamania/php-stemmer/commit/3fbc6c94faef96550f66074e4923342e7d68c44e

**Comment by infograf768** [comment] 2020-12-07 09:16
Don't we have to modify "wamania/php-stemmer": "^2.0", to 2.1 in composer.json as it is already modified in composer.lock
```
"name": "wamania/php-stemmer",
            "version": "v2.1",
            "source": {
                "type": "git",
                "url": "https://github.com/wamania/php-stemmer.git",
                "reference": "02ca30d47bd4a4e5f75e4900a71bea61334c9917"
            },
```

**Comment by infograf768** [comment] 2020-12-07 09:37
in fact the 2.1 pack does not contain the fix

**Comment by ghazal** [comment] 2020-12-13 11:54
@chmst Thanks. This works.


> in fact the 2.1 pack does not contain the fix

Confirmed. Left a note in their comments.

**Comment by HLeithner** [comment] 2020-12-13 13:40
In the meantime we should change our composer deps to dev for php-stemmer

**Comment by wamania** [comment] 2020-12-19 21:14
Hi there
Release 2.1.1 done with the fix

**Comment by brianteeman** [comment] 2020-12-19 21:37
Awesome thanks

**Comment by rdeutz** [comment] 2020-12-20 14:16
closing because we have a PR to fix the problem. #31732

**Closed as completed by rdeutz** 2020-12-20 14:16 UTC
Labels: No Code Attached Yet, PHP 8.x
