### ISSUE TITLE
[4.0] The 'Tag' field (custom element) has zero width when inside hidden tab

### ISSUE THREAD

**Issue by minitek** [joomla/joomla-cms#19070] opened 2017-12-14 19:23 UTC
### Steps to reproduce the issue
When entering a tag field in a xml file (not in the first fieldset):
```
<field 
name="tag_id" 
type="tag" 
label="Select tags"
multiple="true"
/>
```

### Expected result
The 'Tags' custom element should be displayed

### Actual result
The custom element has zero width

### System information (as much as possible)

PHP Version | 7.1.10
Web Server | Apache/2.4.28 (Win32) OpenSSL/1.0.2l PHP/7.1.10
Joomla! Version | Joomla! 4.0.0-dev Development [ Amani ] 31-March-2017 23:59 GMT

**Comment by minitek** [comment] 2017-12-14 19:25
https://docs.joomla.org/Tag_form_field_type

**Comment by ghost** [comment] 2017-12-14 19:25
Please explain how to reproduce the issue and give System Informations, thanks.

**Comment by minitek** [comment] 2017-12-14 19:32
I have updated the original post.

**Comment by dgrammatiko** [comment] 2017-12-14 20:47
The new UI for the tags is something that 3 teams (accessibility, design and js team) are working together to accomplish.
There won't be a select element anymore, since we're gonna utilise custom elements here as nothing out in the wild fulfils the project needs (either fall sort on accessibility or limiting options on design, or the js code is so generic that the size is horrific). Anyways you can test yourself an early (buggy) draft: https://codepen.io/dgt41/pen/KvbbdE

So all I wanted to point out is that almost all fields in J4 will eventually become custom elements, either wise we will never fulfil our promise for fully accessible CMS! By the way help is always welcome...

**Comment by minitek** [comment] 2017-12-15 15:53
The custom elements are a great idea, but in this case the field is rendered from the XML definition. The "multiple" attribute should work for the "Tag" field the same way it works for the "Category" field in Joomla 4.
PS. Sure I would like to help with the custom elements development. Where do I sign up?

**Comment by minitek** [comment] 2017-12-15 16:17
I got it.
It seems that it needs a bootstrap class, otherwise the field is there but has no width.
For example:
`class="col-md-12"`

**Comment by minitek** [comment] 2017-12-15 16:32
I think that the field should have the default width of 240px if no class attribute is added to the field.

**Comment by dgrammatiko** [comment] 2017-12-15 18:10
Ping us here: https://volunteers.joomla.org/teams/javascript-working-group

**Comment by astridx** [comment] 2020-03-01 18:17
I just tried that. I can no longer confirm the issue. Could it be that the problem has been resolved in the meantime and this issue can be closed?

**Comment by minitek** [comment] 2020-03-01 22:31
Yes. The problem seems to be resolved.

**Comment by astridx** [comment] 2020-03-01 23:09
Thank you for your feedback @minitek

**Closed as completed** 2020-03-01 23:10 UTC
Labels: No Code Attached Yet, J4 Issue, Information Required
