### ISSUE TITLE
[4.0] No way to go back in the new installer to fix the db / An error has occurred while processing your request

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/joomla-cms#19198] opened 2017-12-28 14:00 UTC
### Steps to reproduce the issue

When the wrong information is entered in the database fields, the installer shows this error: 

**An error has occurred while processing your request.
2002 No such file or directory**

And, there is no way to go back, fix the error and continue the installation.

If you try to, access again to the first installation page at the root folder, then you get this error: **Error displaying the error page**. So, the only way to restart the installation is deleting all files and start from the scratch.

### Expected result

An easy way to fix the entered information in the configuration fields of the installer.

### Actual result

**An error has occurred while processing your request**

... no way to go back and fix the error.

### System information (as much as possible)

J4 A2 - PHP 7.1

**Comment by ghost** [comment] 2017-12-28 14:02
changed Title to start with "[4.0] ".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19198">issues.joomla.org/tracker/joomla-cms/19198</a>.</sub>

**Comment by mbabker** [comment] 2017-12-28 14:04
Duplicate of https://github.com/joomla/joomla-cms/issues/18557

**Closed as completed by mbabker** 2017-12-28 14:04 UTC
Labels: No Code Attached Yet
