### ISSUE TITLE
IE8: Content overlaps in breadcrumbs module

### ISSUE THREAD

**Issue by Disaron** [joomla/joomla-cms#6078] opened 2015-02-13 09:08 UTC
Joomla! 3.3.6 "Protostar" template

Content overlaps in breadcrumbs module in IE8, when path longer than field width. See screenshot
![overlap](https://cloud.githubusercontent.com/assets/7919663/6184930/09b97316-b379-11e4-85ce-db5d295fa3b3.png)

**Comment by brianteeman** [comment] 2015-11-12 16:00
Sorry that no one ever replied to this

Are you still having this issue in the latest version of Joomla?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6078">issues.joomla.org/joomla-cms/6078</a>.</sub>

**Comment by Disaron** [comment] 2015-11-17 12:11
Hi. Yes it still present in 3.4.5 release.

**Comment by brianteeman** [comment] 2015-11-17 12:32
Removed info required status<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6078">issues.joomla.org/joomla-cms/6078</a>.</sub>

**Comment by roland-d** [comment] 2016-05-19 09:36
@Disaron I may sound like a broken record but some changes were made to deal with long texts. Is this issue still present for you in version 3.5.1?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6078">issues.joomla.org/joomla-cms/6078</a>.</sub>

**Comment by kalpesh681** [comment] 2016-07-06 05:50
To reproduce the issue, I have create article and menu item with long title and checked in front side breadcrumb module works fine for me.
Please correct me if i have done anything wrong. 

System Info : Windows 10
Browser Info : IE-8 
Please see the screenshot
![screen shot 2016-07-06 at 00 50 43](https://issues.joomla.org/uploads/1/2c4460bf2272d02eecb448f00268f006.jpg)

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6078">issues.joomla.org/joomla-cms/6078</a>.</sub>

**Comment by Disaron** [comment] 2016-07-06 13:01
@kalpesh681 if you tell me, how you install IE8 on windows 10 and make him render border-radius CSS attribute, all of us will be great for you. )))

@roland-d, yes it still present on 3.5.1, but it doesn`t matter because IE8 is RIP.

**Comment by andrepereiradasilva** [comment] 2016-07-06 13:04
> @roland-d, yes it still present on 3.5.1, but it doesn`t matter because IE8 is RIP.

I agree it's RIP (finally!). But is still officially suported by joomla 3.x series ... https://docs.joomla.org/Joomla_Browser_Support

**Comment by kalpeshtailored** [comment] 2016-07-13 05:30
@Disaron I mean to say that Its compatible IE8 emulation mode in Windows 10.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6078">issues.joomla.org/joomla-cms/6078</a>.</sub>

**Comment by Disaron** [comment] 2016-07-13 07:00
@kalpesh681 well as I see emulation is not correct. Microsoft...

**Comment by rdeutz** [comment] 2016-08-17 19:49
closing this because this will only gets fixes if someone has a very boring moment

**Closed by rdeutz** 2016-08-17 19:49 UTC
Labels: No Code Attached Yet
