### ISSUE TITLE
[4.2x] Featured or unfeatured dates do not save using front end editor

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#39330] opened 2022-11-29 13:51 UTC
### Steps to reproduce the issue
Log into front end of website
Create or edit an article
Change 'featured' from 'No' to 'Yes'
Save
Add a 'Start featured' or 'Finished featured' date, or both
Save

### Expected result
Featured dates are saved

### Actual result
Featured dates are not saved

### System information (as much as possible)
Joomla 4.2.5
PHP 8.0.25 
Editor: Tinymce

First noticed during a client training session today with users at 'Manager' level
Re-tested back in the office with Superuser access on front end
Same result

**Comment by alikon** [comment] 2022-11-29 15:34
can you have a look at this pr #38975

**Comment by joomdonation** [comment] 2022-11-30 08:17
Actually, the dates are saved properly. You can check the article from backend to confirm that. The issue here is that the saved dates are not being shown in the frontend edit article form because of bug in our code. PR https://github.com/joomla/joomla-cms/pull/38975 solves this issue, so I'm closing this issue.

**Closed as completed by joomdonation** 2022-11-30 08:17 UTC
Labels: No Code Attached Yet

**Comment by mbiolsi** [comment] 2023-09-29 18:26
Has there been a regression here? I am experiencing this with J! 4.3.4 on PHP 8.1.19. I can select the date but when I save the article the dates disappear and the articles are not being marked as featured if in the date range. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39330">issues.joomla.org/tracker/joomla-cms/39330</a>.</sub>
