### ISSUE TITLE
Menu Item (Save failed with the following error:) Joomla 3.3.6

### ISSUE THREAD

**Issue by nassausky** [joomla/joomla-cms#5565] opened 2014-12-30 23:30 UTC
#### Steps to reproduce the issue
1) Open a menu to edit in backend
2) Choose an item in the menu
3) Choose a different Parent Item.
4) Click Save & Close

#### Expected result
Menu item should now be moved to correct position.

#### Actual result
A warning displays without listing the error number as shown below:

Warning
Save failed with the following error:

#### System information (as much as possible)
Brand new fresh clean install of Joomla 3.3.6 from Softaculous. 

System Information
Setting	Value
 
PHP Built On	Linux serv01.siteground142.com 2.6.32.59-sg3 #9 SMP Wed Sep 26 03:29:25 CDT 2012 x86_64
Database Version	5.5.32-31.0-log
Database Collation	utf8_general_ci
PHP Version	5.3.29
Web Server	Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 3.3.6 Stable [ Ember ] 01-October-2014 02:00 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

#### Additional comments

Used phpMyAdmin and noticed in the xxx_menu table the nested field values were out of wack negative values. Something should be done to A) prevent that from happening and/or B) to fix it during a repair database

**Comment by rdeutz** [comment] 2015-01-02 17:24
Setting the prio to medium because the problem can't be reproduced<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5565">issues.joomla.org/joomla-cms/5565</a>.</sub>

**Comment by JoomliC** [comment] 2015-01-30 11:34
A user of my extension has the same similar issue, with articles, categories, contact... all core and third parties components...
Menu item saving for this user is working.
I don't know where the issue could come from, but for this user, it's not in Joomla 3, but 2.5.28...

When error reporting on, in already article saving, i've got this notice : 
 Strict Standards: Declaration of JParameter::loadSetupFile() should be compatible with that of JRegistry::loadSetupFile() in /home/meilleu3/public_html/tresques/libraries/joomla/html/parameter.php on line 512 
Don't know if it could be a similar issue withthe one of this issue on j3 here...?!?...

If i find where the problem is, i will inform you...
Cyril

**Comment by brianteeman** [comment] 2015-03-14 10:19
After considerable time without update or further information I am closing this - it can always be re-opened<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5565">issues.joomla.org/joomla-cms/5565</a>.</sub>

**Closed** 2015-03-14 10:19 UTC
Labels: No Code Attached Yet

**Comment by revnoah** [comment] 2015-07-16 17:45
I have encountered this problem as well, as did the client and previous developer back in March. It is very persistent and the menu item ordering is extremely fragile. Both the front and backend display the menu items in the incorrect order, even though their parent's are set correctly. Rebuilding the menu fails, copying menu items fails. I can save the menu items sometimes and not others, and I have also seen a negative value in the *rgt* column of the menu table. Updating to 3.4.3 and rebuilding the cache didn't throw any errors but it didn't solve the problem either. It is failing on Ubuntu locally and CentOS on the live production server.

The notes above mention a need for additional information. My temporary workaround for the frontend output (because the site is already live) has been to write a custom module that uses a basic query for selecting and ordering the menu items, and a recursive function to output the links in the same unordered list.
