### ISSUE TITLE
am i being thick - why not just change your code to use the correct relative path?

### ISSUE THREAD

**Issue by durian808** [joomla/joomla-cms#37257] opened 2022-03-13 12:37 UTC
am i being thick - why not just change your code to use the correct relative path?

_Originally posted by @brianteeman in https://github.com/joomla/joomla-cms/issues/37241#issuecomment-1065572391_

**Comment by brianteeman** [comment] 2022-03-13 12:40
The code change you proposed is wrong. 
The other bugs you linked to are not related.
The problem is that the code in the plugin is wrong. It will never have worked if for example the site was installed in a subdirectory.

Joomla should not change its code to account for bad code by a third party

My comment referred to the code in the plugin that should be changed not the code in Joomla

**Comment by richard67** [comment] 2022-03-13 12:58
Closing due to reasons explained in the previous comment.

**Closed as completed by richard67** 2022-03-13 12:58 UTC
Labels: No Code Attached Yet

**Comment by durian808** [comment] 2022-03-13 13:02
Then why was the function adding JPATH_ROOT to the beginning of the path?  It's because the authors of the function realized that a leading "/" might be passed.  That's good, that's defensive programming.  It points out the fact that is_dir() and is_file() have a new behavior with a new version of PHP, and this was not something the original authors knew about.

What we have here is the admin UI of Virtuemart spitting out a warning.  Isn't it bad coding in Joomla that Joomla isn't giving an understandable error – i.e. rejecting the input with an understandable error message – instead of relying on a PHP function to spit out a cryptic warning?

I'm concerned that there are many instances of is_dir() and is_file() being used in the Joomla core, and this issue may pop up again and again, resulting in Joomla spitting out this PHP warning in lots of extensions.  Wouldn't it be prudent to examine all the code and make appropriate modifications?

And what about my treatment in #37241?  I was not treated very well.  Do you want people to report bugs?  I mean I was honestly reporting what I thought was something Joomla should not be doing, and I was treated very poorly.

thanks

**Comment by richard67** [comment] 2022-03-13 13:08
@durian808 In #37241 you were the one who first started to become offending in your comment here https://github.com/joomla/joomla-cms/issues/37241#issuecomment-1065559712 :

> You need to look more closely at this, or get out of the way so another developer can do that.

And in the further discussion you continued in this style, e.g.

> No, no, no. Look... If you guys can't understand this, then get a developer in here who does.

I have not seen any place where people have treated you in the same way.

So maybe you should think about your way to communicate with people.

**Comment by durian808** [comment] 2022-03-13 13:13
No, Mr. Grammatiko was first.

Anyway... @brianteeman 

Then why was the function adding JPATH_ROOT to the beginning of the path? It's because the authors of the function realized that a leading "/" might be passed. That's good, that's defensive programming. It points out the fact that is_dir() and is_file() have a new behavior with a new version of PHP, and this was not something the original authors knew about.

What we have here is the admin UI of Virtuemart spitting out a warning. Isn't it bad coding in Joomla that Joomla isn't giving an understandable error – i.e. rejecting the input with an understandable error message – instead of relying on a PHP function to spit out a cryptic warning?

I'm concerned that there are many instances of is_dir() and is_file() being used in the Joomla core, and this issue may pop up again and again, resulting in Joomla spitting out this PHP warning in lots of extensions. Wouldn't it be prudent to examine all the code and make appropriate modifications?
