### ISSUE TITLE
[3.7.0beta1] Installer Arabic Unitag WhiteScreen issue

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#13861] opened 2017-02-02 21:16 UTC
### Steps to reproduce the issue

On first page of installer - select Arabic Unitag

### Expected result

screen loads perfect

### Actual result

white screen of death until you scroll 

http://screenshot.myjoomla.io/2W1n3K123w2Z

### System information (as much as possible)

Google Chrome

**Comment by AlexRed** [comment] 2017-02-03 07:59
I can't confirm it. All ok for me in select Arabic Unitag on Chrome 56 (linux)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13861">issues.joomla.org/tracker/joomla-cms/13861</a>.</sub>

**Comment by zero-24** [comment] 2017-02-03 18:05
We have just reproduced this. It is just a Mac Problem together with chrome. It can also be reproduced on other sites not using joomla as it is because of a rendering bug in chrome on mac

@PhilETaylor please try to reszise your browser window (that let chrome rerender the page) and it is working again. (we have just verified it here on a mac with chrome)

Thanks 👍

**Comment by PhilETaylor** [comment] 2017-03-27 16:00
Yes its a mac/chrome issue - doesnt mean it should not be fixed/investigated though - or are you saying its best to blame the browser and just close this?

**Comment by zero-24** [comment] 2017-03-27 17:42
Thanks for the feedback @PhilETaylor 

Saddy i have no Mac on myown even i don't have an idea why this happen or how this could be fixed. Do you have some ideas?

**Comment by PhilETaylor** [comment] 2017-03-30 14:13
This StackOverflow article describes the same issue and proposes some fixes... none look nice.

http://stackoverflow.com/questions/34184377/chrome-shows-blank-page-on-rtl-language-site-until-window-is-resized

**Comment by PhilETaylor** [comment] 2017-03-30 14:18
Wordpress also has this issue https://core.trac.wordpress.org/ticket/40147

**Comment by brianteeman** [comment] 2017-03-30 14:21
So it's a browser issue and not something we can do anything about then -
sadly?

**Comment by PhilETaylor** [comment] 2017-03-30 14:22
As the stackoverflow article states - there is much that can be done to overcome this issue - the question is do we want to bother ...

**Comment by brianteeman** [comment] 2017-08-18 21:27
Closed as we have a PR #16552

**Closed by brianteeman** 2017-08-18 21:27 UTC
Labels: No Code Attached Yet
