### ISSUE TITLE
Articles “suspended”, with "special" access, are visible (on the home page) to all registered users (not super users).

### ISSUE THREAD

**Issue by danpdanp** [joomla/joomla-cms#18174] opened 2017-09-30 19:43 UTC
### Steps to reproduce the issue
Create articles with "special" (super user) access and publish it on the home page (highlighted articles of all categories). So suspend it ("suspended")

### Expected result
The item suspended (or its preview, if it's "read more") is only visible to "super users" ("special" access)

### Actual result
The suspended item (or its preview, if it's "read more") is also visible to users who do not have the privileges of "super user" and "special" access

### System information (as much as possible)
Active PHP on Linux web-lnx23.ergonet.host 3.10.0-327.36.3.el7.x86_64 # 1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64
Database Version 5.5.5-10.1.18-MariaDB
Collation database utf8_general_ci
Collation database connection utf8mb4_general_ci
PHP version 7.0.8
Apache Web Server
WebServer cgi-fcgi PHP interface
Joomla! Joomla! 3.8.0 Stable [Amani] 19-September-2017 14:00 GMT
Joomla Platform Version! Joomla Platform 13.1.0 Stable [Curiosity] 24-Apr-2013 00:00 GMT

**Comment by ggppdk** [comment] 2017-10-01 05:45
Can you test with protostar template ?

**Comment by danpdanp** [comment] 2017-10-01 05:58
Yes, the problem also occurs with the protostar![screen shot 2017-10-01 at 05 58 04](https://issues.joomla.org/uploads/1/0f18babc9f1987150ded81bb44934229.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18174">issues.joomla.org/tracker/joomla-cms/18174</a>.</sub>

**Comment by infograf768** [comment] 2017-10-01 06:07
I can't reproduce the issue here on staging

**Comment by infograf768** [comment] 2017-10-01 06:08
BTW, what do you mean by "suspended"?

**Comment by ggppdk** [comment] 2017-10-01 06:11
> Yes, the problem also occurs with the protostarscreen shot 2017-10-01 at 05 58 04

Go to menu Users / Access levels
and edit the view access level "Suspended" (also do same for "Special" )
which user groups have it ?

**Comment by danpdanp** [comment] 2017-10-01 07:53
"Suspended" is not an access level. In the Italian version of Joomla, articles are pending to be "published", "cessated", "suspended" (unpublished). The problem occurs either by the "unpublished" items, visible on their home page with a level of access that did not divide to allow sight.
Specification: 
The problem does not occur when the "Unauthorized links" parameter is set everywhere to "no" (as expected) but occurs when that parameter, in the "Home" menu item options ( articles highlighted in all categories) is set to "Use article settings", and in the article, as well as in the general article options, is set to "no".
Sorry for my english.
thanks

**Comment by ggppdk** [comment] 2017-10-01 08:30
Unpublished articles shown ?
Can the registered users also edit them ?

**Comment by danpdanp** [comment] 2017-10-01 08:44
Registered users can only see the article on the home page, or the article's intro (if "read more" is set) but can not see the full article (click "read more") or change it Article. I still apologize for inaccuracies and omissions, but it is difficult for me to write in English. Thanks for your patience

**Comment by ghost** [comment] 2017-10-01 08:46
@danpdanp you can use a translator like google translate which can help as here are also not-native-Speakers.

**Comment by danpdanp** [comment] 2017-10-01 10:40
By experience, I know that the Italian-English translator is unreliable, especially for technical texts.
However, I still try to post this text, fully translated by Google Translator.
Below, I carry the original in Italian.
I will try to be as schematic as possible.
To reproduce the error:
- in the General Item Options, set the "Unauthorized Link" parameter to "No"
- in the "Featured Articles of All Categories" (Home Page) default menu item options, set the "Unauthorized Link" parameter to "Use Item Settings"
- create an article with "Special" access (for Super users), set the item "Unauthorized links" to "A global (No)" in the article options; in the "Status" options, select "Suspended" (other options are "Published", "Filed" and "Cached")
- login to the site as a user who does not have Super user privileges (eg "Registered").
You should not be able to see the article in the Home Page with the word "Suspended", instead the article (or its introduction, if the "Read" setting) is displayed.

Per esperienza, so che il traduttore di Google italiano-inglese è poco affidabile, in particolare per testi di tipo tecnico.
Provo comunque a postare il presente testo, integralmente tradotto dal traduttore di Google.
Di seguito, riporto l'originale in italiano.
Cercherò di essere il più schematico possibile.
Per riprodurre l'errore:
- nelle Opzioni generali degli articoli, impostare il parametro "Link non autorizzati" su "No"
- nelle Opzioni della voce di menù predefinita "Articoli in evidenza di tutte le categorie" (Home Page), impostare il parametro "Link non autorizzati" su "Utilizza impostazioni articolo"
- creare un articolo con "Accesso" "Special" (per i Super users), impostare nelle opzioni dell'articolo il parametro "Link non autorizzati" su "Una globali (No)"; nelle opzioni di "Stato", selezionare "Sospeso" (le altre opzioni sono "Pubblicato", "Archiviato" e "Cestinato")
- fare il login al sito come un utente non in possesso dei privilegi di Super user (es: "Registrato").
Non si dovrebbe essere in grado di vedere l'articolo in Home Page con la dicitura "Sospeso", invece l'articolo (o la sua introduzione, se è stato impostato il "Leggi tutto") viene mostrato.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18174">issues.joomla.org/tracker/joomla-cms/18174</a>.</sub>

**Comment by infograf768** [comment] 2017-10-05 07:29
If I have understood well, I still can't reproduce the issue.
Article Unpublished and access set to Special will only display here when a superUser will log in (protostar)

![unpublished_special](https://user-images.githubusercontent.com/869724/31215429-b594f730-a9af-11e7-9df2-5d9fa4eb1113.gif)

**Comment by danpdanp** [comment] 2017-10-05 07:49
L'errore consiste nel fatto che un utente non appartenente al gruppo "Super users" (o "Special") può vedere, in Home Page, l'articolo sospeso, che ha accesso "Super users".
Ciò accade soltanto se il parametro "Link non autorizzati" nelle opzioni della voce di menu predefinita "Home" è impostata su "Utilizza impostazioni articolo". Ovviamente il parametro "Link non autorizzati" è impostato su "No" sia nelle opzioni generali sia in quelle dell'articolo.
Il problema non si presenta se il parametro "Link non autorizzati" è impostato ovunque su "No".

The error is that a user who does not belong to the "Super users" (or "Special") group can see, on Home Page, the article being suspended, which has "Super users" access.
This only occurs if the "Unauthorized links" parameter in the default Home menu item options is set to "Use article settings". Obviously, the "Unauthorized Link" parameter is set to "No" both in the general and article options.
The problem does not occur if the "Unauthorized links" parameter is set to "No" anywhere.

**Comment by infograf768** [comment] 2017-10-05 08:15
Settings of `Show Unauthorized links`

Articles general Options set to NO
Specific Article set to NO
Featured menu item set to `Use Article Settings`

I still can't reproduce the issue, a registered user does not see the article.

**Comment by danpdanp** [comment] 2017-10-05 11:52
So this is a problem of my joomla installations (it occurs in four sites I manage) and not the recent upgrade, but I can not understand that. If you can help me anyway ...
Thank you

**Comment by ghost** [comment] 2017-10-05 11:57
@danpdanp please ask further help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.

**Closed as completed** 2017-10-05 11:57 UTC
Labels: No Code Attached Yet
