### ISSUE TITLE
[com_fields] json_decode() warning with checkbox/radio field type

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#14589] opened 2017-03-13 22:05 UTC
### Steps to reproduce the issue
Create a new field of checkboxes type.
Add a checkbox values.
Click Save & Close button.
Edit this field.
Click Save & Close button.

In the PHP error log:
```
PHP Warning:  json_decode() expects parameter 1 to be string, array given in \administrator\components\com_fields\models\field.php on line 159

PHP Warning:  json_decode() expects parameter 1 to be string, array given in \administrator\components\com_fields\models\field.php on line 160
```
### System information (as much as possible)
PHP 5.6.3

**Comment by yvesh** [comment] 2017-03-13 23:55
@Quy Latest staging? And can you add a screenshot how your checkbox configuration field looks like?

ping @laoneo

**Comment by Quy** [comment] 2017-03-14 01:02
Yes, latest staging as of today.
![checkboxes](https://cloud.githubusercontent.com/assets/368084/23881316/0f759876-0817-11e7-975c-91ab6a1c6124.jpg)

**Comment by laoneo** [comment] 2017-03-15 07:30
I can't reproduce the issue. Did you had some old data as the field configuration got updated from repeatable to subform field.

**Comment by Quy** [comment] 2017-03-15 15:14
This is a clean install with no data. Also tested on PHP 7.0.16 and got the same warning in the error log.

**Comment by laoneo** [comment] 2017-03-16 08:41
@yvesh could you reproduce the issue?

**Comment by yvesh** [comment] 2017-03-16 10:39
@laoneo Yep i can confirm it.. It's not shown because of the redirect.. But he's right it's in the logs

[16-Mar-2017 11:38:06 Europe/Berlin] PHP Warning:  json_decode() expects parameter 1 to be string, array given in /Users/g0ne/projects/joomla/joomla-cms/administrator/components/com_fields/models/field.php on line 160
[16-Mar-2017 11:38:06 Europe/Berlin] PHP Stack trace:
[16-Mar-2017 11:38:06 Europe/Berlin] PHP   1. {main}() /Users/g0ne/projects/joomla/joomla-cms/administrator/index.php:0
[16-Mar-2017 11:38:06 Europe/Berlin] PHP   2. JApplicationCms->execute() /Users/g0ne/projects/joomla/joomla-cms/administrator/index.php:51
[16-Mar-2017 11:38:06 Europe/Berlin] PHP   3. JApplicationAdministrator->doExecute() /Users/g0ne/projects/joomla/joomla-cms/libraries/cms/application/cms.php:265
[16-Mar-2017 11:38:06 Europe/Berlin] PHP   4. JApplicationAdministrator->dispatch() /Users/g0ne/projects/joomla/joomla-cms/libraries/cms/application/administrator.php:156
[16-Mar-2017 11:38:06 Europe/Berlin] PHP   5. JComponentHelper::renderComponent() /Users/g0ne/projects/joomla/joomla-cms/libraries/cms/application/administrator.php:98
[16-Mar-2017 11:38:06 Europe/Berlin] PHP   6. JComponentHelper::executeComponent() /Users/g0ne/projects/joomla/joomla-cms/libraries/cms/component/helper.php:369
[16-Mar-2017 11:38:06 Europe/Berlin] PHP   7. require_once() /Users/g0ne/projects/joomla/joomla-cms/libraries/cms/component/helper.php:394
[16-Mar-2017 11:38:06 Europe/Berlin] PHP   8. JControllerLegacy->execute() /Users/g0ne/projects/joomla/joomla-cms/administrator/components/com_fields/fields.php:29
[16-Mar-2017 11:38:06 Europe/Berlin] PHP   9. JControllerForm->save() /Users/g0ne/projects/joomla/joomla-cms/libraries/legacy/controller/legacy.php:710
[16-Mar-2017 11:38:06 Europe/Berlin] PHP  10. FieldsModelField->save() /Users/g0ne/projects/joomla/joomla-cms/libraries/legacy/controller/form.php:744
[16-Mar-2017 11:38:06 Europe/Berlin] PHP  11. json_decode() /Users/g0ne/projects/joomla/joomla-cms/administrator/components/com_fields/models/field.php:160


P.S.: For me when there is no custom field published you should show a warning (enquo a message) that they have to publish the plugins first.. No one will get that else wise :-)

**Comment by laoneo** [comment] 2017-03-20 07:54
Guess this one can be closed as we have a pr.

**Comment by zero-24** [comment] 2017-03-20 08:53
PR is https://github.com/joomla/joomla-cms/issues/14681

**Closed by zero-24** 2017-03-20 08:53 UTC
Labels: No Code Attached Yet
