### ISSUE TITLE
[com_fields] field tag displays when the Content - Fields plugin is disabled

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#13931] opened 2017-02-05 11:33 UTC
### Steps to reproduce the issue
Create a custom field for Articles.
Edit an article and fill the value.
Make sure the Button - Fields plugin is enabled.
With the editor, use the new Button "Fields" to enter the field just created into the editor area.
It will display `{field #}` (where # is the id of the field) in the editor area.

If the new Content - Fields plugin is enabled, the value of the field will display in frontend.
BUT, if disabled, then this tag `{field #}` will display in frontend although it should not. 

@laoneo @Bakual

**Comment by Bakual** [comment] 2017-02-05 12:00
That is expected behavior. If the plugin responsible for a given tag isn't enabled, then no code will parse for that tag and it can't be replaced. So it will stay in the article as it is.
It's the same behavior with the "Load Module" plugin.

**Comment by mbabker** [comment] 2017-02-05 15:30
Unless someone is going to turn this into a feature request for a post processing step that ensures all placeholder/shortcode type stuff is removed then this can be closed as noted above.

**Comment by infograf768** [comment] 2017-02-05 15:38
closing then as behaviour, in current code implementation, can't deal with it.
a suggestion though: maybe that content plugin could be enabled by default.
whatcdonyou think?

**Closed** 2017-02-05 15:38 UTC
Labels: No Code Attached Yet

**Comment by Bakual** [comment] 2017-02-05 16:00
> maybe that content plugin could be enabled by default.

It could, yes. I left it disabled because I think most sites will not need it and it has a minor performance implication since it's going to run on each article (like each content plugin). But if people think it should be enabled by default, then I'm not going to argue 😄

**Comment by franz-wohlkoenig** [comment] 2017-02-05 16:23
enabled by default: +1

**Comment by infograf768** [comment] 2017-02-05 16:30
also, i think the button field should only display in editor bar if this content plugin IS enabled.

**Comment by Bakual** [comment] 2017-02-05 18:38
> also, i think the button field should only display in editor bar if this content plugin IS enabled.

Just keep it consistent with the "Load Module" plugins.

**Comment by mbabker** [comment] 2017-02-05 18:41
> also, i think the button field should only display in editor bar if this content plugin IS enabled.

I wouldn't.  That couples the button to a specific implementation of the plugin.  Nothing stops anyone from forking the core content plugins supporting those shortcode syntax things and adapting them to do something different.

**Comment by infograf768** [comment] 2017-02-06 08:38
See https://github.com/joomla/joomla-cms/pull/13946 (had not read @mbabker comment yet)

> Nothing stops anyone from forking the core content plugins supporting those shortcode syntax things and adapting them to do something different.

In that case they should imho also fork the existing xtd-button. 
Displaying the module and fields button when the only things they will show when rendered would be `{whatever}` is worse
