### ISSUE TITLE
[4.0] Media Folders lost its design

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#14039] opened 2017-02-12 17:01 UTC
### Steps to reproduce the issue
Open "Media":
![media-manager-j4](https://cloud.githubusercontent.com/assets/8235763/22864187/098151a2-f14d-11e6-857f-67138509d53e.jpg)
### System information (as much as possible)
Joomla! 4.0-nightly builds
macOS Sierra, 10.12.3
Safari 10.0.3
PHP 7.0.15
MySQLi 5.6.35
Mamp 4.1.1

**Comment by tonypartridge** [comment] 2017-02-13 18:45
I suspect not much work is going on with the media component since it's planned a full overhaul in 3.8 which will be merged to 4.0.

**Comment by wilsonge** [comment] 2017-02-13 23:39
As Tony says - this is deliberate for now as there's work being done on a full media manager overhaul :)

**Comment by wilsonge** [comment] 2017-03-19 09:57
Closing as this is a duplicate of #14741

**Closed by wilsonge** 2017-03-19 09:57 UTC
Labels: No Code Attached Yet
