### ISSUE TITLE
[4.0] showon attribute does not work on List field with multiple="true"

### ISSUE THREAD

**Issue by boddunan** [joomla/joomla-cms#35486] opened 2021-09-06 04:34 UTC
### Steps to reproduce the issue
1. Create a component with the config.xml 
2. Add a list field with multiple=true and layout="joomla.form.field.list-fancy-select". Example:
```
<field name="social_auth_providers" type="list" default="facebook,twitter,google" multiple="true" layout="joomla.form.field.list-fancy-select" label="Social" description="Social">
  <option value="facebook">Facebook</option>
  <option value="google">Google</option>
  <option value="twitter">Twitter</option>
  <option value="linkedin">LinkedIn</option>
</field>
```

3. Add another field with showon attrbute. Example: showon="social_auth_providers:facebook" where social_auth_providers is the name of the list field. Example:
```
<field name="facebook_oauth_id" type="text" showon="social_auth_providers:facebook" label="Facebook" description="Facebook"/>
```

### Expected result
The second field is shown when the option with the value facebook is selected in the list field.

### Actual result
The second field is not shown

### System information (as much as possible)
Joomla 4.0.2

### Additional comments
This works fine in Joomla 3.10

**Comment by sozzled** [comment] 2021-09-06 06:24
Works for me with J! 4.0.2.  Well, I've only tried it with the field type of **radio** not **list**.

**Comment by Bakual** [comment] 2021-09-06 07:50
Does it work if you remove the `multiple="true"`? I'm not sure it's supposed to work with multiple.

**Comment by boddunan** [comment] 2021-09-06 09:47
Joomla 4: It works when the list is single selection (no multiple=true), it does not work with multiple=true.
Joomla 3: Works for both

**Comment by denisritchiee** [comment] 2021-09-06 10:29
[Beginner.pdf](https://issues.joomla.org/uploads/1/851ba01907683c80ba49824cc5c04895.pdf)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35486">issues.joomla.org/tracker/joomla-cms/35486</a>.</sub>

**Comment by Bakual** [comment] 2021-09-06 12:38
@Fedik @dgrammatiko Did any of you change the showon JS code for J4? Could that be the issue here?

**Comment by dgrammatiko** [comment] 2021-09-06 12:55
> Did any of you change the showon JS code for J4?

Yes, the showon is completely rewritten in J4 as vanilla JS (no jQuery) but I think the problem comes from the field, eg probably the choices.js part or the parent Custom Element. The first one I wrote the code for the other was @Fedik (I think, might be wrong)

**Comment by Fedik** [comment] 2021-09-06 14:13
@boddunan does it work if remove layout attribute? when use generic `<select>`

**Comment by boddunan** [comment] 2021-09-06 14:24
No, removing the layout attribute shows a multi-select list box. Selecting options does not show other fields.

**Comment by Fedik** [comment] 2021-09-06 15:38
thanks for checking, 
so it seems the bug in shwoon js, need to look how it handle multiple values

**Comment by dgrammatiko** [comment] 2021-09-06 15:58
If someone can test replacing this https://github.com/joomla/joomla-cms/blob/cabe4068210e9512a6d5d3ccca46db91ce771b0b/build/media_source/system/js/showon.es6.js#L138-L156 with
(updated, it seems I don't even know the HTML elements anymore 😂. Thanks @Fedik )
```js
            // If checkbox or radio box the value is read from properties
            if (originField.getAttribute('type') && ['checkbox', 'radio'].includes(originField.getAttribute('type').toLowerCase())) {
              if (!originField.checked) {
                // Unchecked fields will return a blank and so always match
                // a != condition so we skip them
                return;
              }

              itemval = document.getElementById(originId).value;
            } else if (originField.nodeName === 'SELECT' && originField.multiple) {
              itemval = Array.from(originField.querySelectorAll('option:checked')).map(el => el.value);
            } else {
              // Select lists, text-area etc. Note that multiple-select list returns
              // an Array here s0 we can always treat 'itemval' as an array
              itemval = document.getElementById(originId).value;
              // A multi-select <select> $field  will return null when no elements are
              // selected so we need to define itemval accordingly
              if (itemval === null && originField.tagName.toLowerCase() === 'select') {
                itemval = [];
              }
            }

```

The solution should be either that or something similar (I can't test this atm)

**Comment by Fedik** [comment] 2021-09-06 16:22
that will not work, there no field type="select" :wink: 
should be `element.nodeName === 'SELECT'`

**Comment by johnnymgo** [comment] 2021-09-06 22:38
Hello,
Today I came across the same problem. Showon in Joomla 4 doesn't work for field list when it has 'multiple' attribute (as mentioned before) and also doesn't work for field of type 'checkboxes'.

**Comment by anibalsanchez** [comment] 2021-10-01 19:41
Same issue here. 

I almost submitted a new issue! I wrote this description:

### Steps to reproduce the issue

1. Check the banners config.xml: www/administrator/components/com_banners/config.xml
1. The config has the fields save_history (radio) and history_limit (number) showon="save_history:1"
1. When you go to the config form, you can enable "Enable Versions" and it shows the "Maximum Versions" associated field
1. Change the save_history (radio) to save_history (list), `type="list"`, it still works OK
1. Remove the layout to save_history (list), `layout="joomla.form.field.radio.switcher"`, it still works OK
1. Add the `multiple="true"` to the save_history (list), the shown conditional field doesn't work.

```xml
		<field
			name="save_history"
			type="list"
			label="JGLOBAL_SAVE_HISTORY_OPTIONS_LABEL"
			default="0"
			multiple="true"
			>
			<option value="0">JNO</option>
			<option value="1">JYES</option>
		</field>
```

### Expected result

The `shownon` behaviour must support the `multiple` attribute (as it worked before on Joomla 3)

### Actual result

The `shownon` behaviour doesn't support the `multiple` attribute.




<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35486">issues.joomla.org/tracker/joomla-cms/35486</a>.</sub>

**Comment by dgrammatiko** [comment] 2021-10-01 19:53
@anibalsanchez can you test https://github.com/joomla/joomla-cms/issues/35486#issuecomment-913743547

**Comment by dgrammatiko** [comment] 2021-10-02 09:29
Please test https://github.com/joomla/joomla-cms/pull/35723

**Comment by anibalsanchez** [comment] 2021-10-02 09:32
@dgrammatiko The comment was almost there. I was writing about the array name just when you submitted the PR. ;-)

**Comment by alikon** [comment] 2021-10-02 09:34
closing as we have a pr #35723

**Closed as completed by alikon** 2021-10-02 09:34 UTC
Labels: No Code Attached Yet
