### ISSUE TITLE
Notice: Indirect modification of overloaded property due to emailcloak.php

### ISSUE THREAD

**Issue by Sulpher** [joomla/joomla-cms#38976] opened 2022-10-17 06:48 UTC
I discovered some notices in 3rd party extension which occurs due to emailcloak.php. 
Below is a quote from a component developer @nikosdion:

> 
> The core plugin needs a fix. It assumes there is a property called text in all content objects, regardless of which extension they belong to, and it tries to cloak any emails in them. Since this is triggered `onContentPrepared` it executes literally everywhere. It doesn't matter if you have an article, Joomla contact object, a banner, a product in an e-commerce extension or a ticket in a helpdesk extension. It will try to do something with the very likely non-existent property text.
> 
> Since the ticket object is not a dumb `stdClass` object but a concrete object which implements a `magic __get` method, PHP complains that trying to pass it by reference (see line 86 of the plugin) will not have any effect which is a very correct warning.
> https://github.com/joomla/joomla-cms/blob/4.2-dev/plugins/content/emailcloak/emailcloak.php
> 
> The simple solution is that the Joomla email cloaking plugin should actually check there is something to do before trying to do it. Line 53 should read:
> 
> `if (is_object($row) && property_exists($row, 'text')) {`

Joomla 4.2.3

**Comment by nikosdion** [comment] 2022-10-17 06:58
I opened a draft PR because I'd need to create a demo module or component to give you reproduction.

Do we really need reproduction instructions for such an obvious mistake? @laoneo I'd like your input before I spend time towards that.

**Comment by laoneo** [comment] 2022-10-17 07:13
Testing instructions can also be to change a file in the core CMS for a test. Did that many time, like that you don't have to make an extra component to illustrate the issue.

I'm with you that no error should be thrown, when the text property doesn't exist. On the other side it would be good , at least to log something when the property doesn't exist. Because this is the "default" behavior that the plugins require  a text attribute.

If I'm not wrong then the loadmodule plugin needs to be fixed as well.

**Comment by nikosdion** [comment] 2022-10-17 09:20
@laoneo Good points here. I will go through the content plugins later today to see where this is happening and fix it.

When there is no "text" property we can reasonably assume that it is a custom content type which may not have textual content. Otherwise we'd need to force content to implement a specific Interface instead of being a stdClass so we can have a method, let's call it getTextPropertyName, to return the name of the text content node(s) where content plugins apply. This can be made b/c but I think that's a discussion we can have for Joomla 5 or even Joomla 6 as it requires a lot of changes in the core as well.

For now, I think that checking if a concrete `text` property exists is fine and _can_ be upgraded in the future if we decide we really want to.

**Comment by nikosdion** [comment] 2022-10-17 14:17
I updated the PR and provided a reproduction plugin so you can see how easily our content plugins get thrown off.

**Comment by richard67** [comment] 2022-10-17 18:19
@nikosdion Does your PR solve this issue so it can be closed?

**Comment by nikosdion** [comment] 2022-10-18 06:40
@richard67 Yep, it does solve the issue once merged. It also solves the same issue in another two core plugins, killing two (three?) birds with one stone 😄

**Comment by richard67** [comment] 2022-10-18 06:42
@nikosdion We usually close issues not when the PR which solves them is merged, we close them already when the PR has been created. That's why I asked. So I can close the issue now.

**Comment by richard67** [comment] 2022-10-18 06:43
Closing as having a pull request. Please test #38977 . Thanks in advance.

**Closed as completed by richard67** 2022-10-18 06:43 UTC
Labels: No Code Attached Yet
