### ISSUE TITLE
Module Tabs

### ISSUE THREAD

**Issue by yarntoad** [joomla/joomla-cms#15601] opened 2017-04-26 20:43 UTC
### Steps to reproduce the issue

This issue deals with module workflow. When you open a module and save/close, which ever tab you saved the module on is the tab presented when you open the next module and it has caused a few issues for our site. The issue I have found is that when you open an existing module and apply that module to a menu item and then save/close the module while still on the "Menu Assignment" tab, when you open another module the module tab goes right to where you last saved, in this case the "Menu Assignment" tab. This seemed handy at first but then I realized I was loosing all of my custom code in my custom modules because the module was opening right to the Menu Assignment tab and the first tab was toggled from Code Only to the WYSIWYG mode. Causing of course, the loss of my custom html code.  

### Expected result

I would expect to always open a custom module, or any module for that matter, directly to the first tab, the "Module" tab. Showing if the Module was toggled on Code or on the WYSIWYG. 

### Actual result

When you open a module, the module opens to which ever tab you had up when you clicked save last. So if the module is toggled to the WYSIWYG you do not see it and you save, loosing your custom code. 

### System information (as much as possible)

Running Joomla 3.7 and have seen same behavior in Chrome and Firefox.

**Comment by dgt41** [comment] 2017-04-26 20:48
How about changing your workflow and always clicking the tab with the content before clicking save?
This feature is not new to Joomla, but since 3.7 is working as intended

**Comment by Bakual** [comment] 2017-04-26 21:08
The only thing that has changed with 3.7.0 is that now the "stored" tab isn't persistent anymore. If you close the browser, it will reset.
The idea of the code is that when you press "Save" (not "Save & Close") you stay on the active tab and don't jump back to the first.
Imho, it may be improved to store the state per item (eg take into account the item ID) and not globally for all items of the same view.

**Comment by yarntoad** [comment] 2017-04-27 13:00
Thanks for the details and we'll change our workflow accordingly. Thanks for all your hard work!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15601">issues.joomla.org/tracker/joomla-cms/15601</a>.</sub>

**Comment by franz-wohlkoenig** [comment] 2017-04-27 13:01
@yarntoad if this Issue is resolved, please close it. Thanks.

**Closed** 2017-04-27 13:02 UTC
Labels: No Code Attached Yet

**Comment by PhilETaylor** [comment] 2017-05-03 10:22
Please test https://github.com/joomla/joomla-cms/pull/15748
