### ISSUE TITLE
Installation error: Select the database type: none

### ISSUE THREAD

**Issue by shamsbd71** [joomla/joomla-cms#18935] opened 2017-12-01 07:07 UTC
### Steps to reproduce the issue
installation screen : Select the database type. * on  Database Configuration

### Expected result
Database Configuration should show the `db_type` properly.

### Actual result
Now showing any db type, so cant proceed further.

![image](https://user-images.githubusercontent.com/1936565/33471645-50286cf2-d6a9-11e7-8069-1d5c9ce3f8e0.png)

### System information (as much as possible)
Joomla: Joomla_4.0.0-alpha2-Alpha-Full_Package.zip
OS: mac
Env: AMPPS 3.7
PHP: 7.1

**Comment by DavidBoggitt** [comment] 2017-12-01 07:17
Duplicate of https://github.com/joomla/joomla-cms/issues/18783 (I had the same thing!)

**Comment by tonypartridge** [comment] 2017-12-01 07:52
You need to use nd_mysqli basically at present it you can select it within your php configuration on your server. Or PDO of course.

**Comment by ghost** [comment] 2017-12-01 08:24
closed as duplicate Report #18783 

Thanks for Hint @DavidBoggitt

**Closed as completed** 2017-12-01 08:24 UTC
Labels: No Code Attached Yet

**Comment by Fedik** [comment] 2017-12-01 08:28
#18660 this also related

**Comment by ghost** [comment] 2017-12-01 08:31
@Fedik should i reopen this Issue?

**Comment by Fedik** [comment] 2017-12-01 08:32
no, I just made a note, and added cross reference to active issue 😉
