### ISSUE TITLE
Remember me and mod_logged

### ISSUE THREAD

**Issue by aduranterres** [joomla/joomla-cms#11754] opened 2016-08-23 10:31 UTC
### Steps to reproduce the issue
Log in to front end marking "Remember me".
Close browser.
In a different browser, in backend, mod_logged, click to log the user out so it does not show in the list.
Open browser again and go to site. User is logged in.

### Expected result

User shows in mod_logged user list, as he is logged again.

### Actual result

User does not show up in mod_logged user list

### System information (as much as possible)

New Joomla 3.6.2 for testing.

### Additional comments

It seems session table in database is not updated with the user info, leaving entry as guest.

This may be related to [#11541](https://issues.joomla.org/tracker/joomla-cms/11541) , although I have not investigated it.

**Comment by RonakParmar** [comment] 2016-08-23 11:59
I have followed above steps and able to reproduce this issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11754">issues.joomla.org/joomla-cms/11754</a>.</sub>

**Comment by zero-24** [comment] 2016-08-23 12:12
Moving to confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11754">issues.joomla.org/joomla-cms/11754</a>.</sub>

**Comment by zero-24** [comment] 2016-08-23 12:13
Btw can this also be reproduced on staging?

**Comment by bertmert** [comment] 2016-08-23 14:41
Maybe related? Maybe the same reason?
https://github.com/joomla/joomla-cms/issues/11756

**Comment by BurtNL** [comment] 2016-08-23 19:53
Another similar case as this reported issue.
Login as admin in backend.
Login as user in frontend, don't check 'Remember me'.
Go to the backend again, logout the user by clicking the red X. The user disappears from the list of logged in users.
Go to the frontend again, the user is still logged in.

The behaviour I see is also some kind of similar as reported in #11756.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11754">issues.joomla.org/joomla-cms/11754</a>.</sub>

**Comment by bertmert** [comment] 2016-08-24 05:06
FYI:
... 11756 was closed because "expected behavior with keepalive forms".

**Comment by andrepereiradasilva** [comment] 2016-10-05 14:24
same issue than https://github.com/joomla/joomla-cms/issues/11756 and https://github.com/joomla/joomla-cms/issues/11866?

if so i think it can be closed right?

**Comment by aduranterres** [comment] 2016-10-05 16:56
Hi.

I don't think it is related to these issues. Those are about logout.

This one is about "remeber me" option not changing session table.

When you log in normally in front end, session table will have row with guest=0, userid=user id of logged user.

When you log in with "remember me" and then you close the browser, clean session table, and go back to the site:
- you are correctly logged in
- but the session table is not updated, and there is not row with guest=0, userid=user id of logged user.

As the mod_logged module checks the session table to know logged in users, it does not show the ones logged through "remember me".

So, problem is not with mod_logged, but instead with "remember me" not updating session table when login by cookie happens.

Please let me know if I can provide any more info.

**Comment by mbabker** [comment] 2016-10-05 16:57
Please test with the 3.6.3 RC.  We made a couple of changes (after one of the security improvements from 3.6.1) related to how the metadata in this table is populated.

**Comment by aduranterres** [comment] 2016-10-06 15:18
Thank you. I just tested with 3.6.3 RC2 and it is now working fine.

**Closed** 2016-10-06 15:20 UTC
Labels: No Code Attached Yet
