### ISSUE TITLE
joomla backend get slow with a lot of menu items

### ISSUE THREAD

**Issue by benshaty** [joomla/joomla-cms#9516] opened 2016-03-22 11:25 UTC
Hi,
I have a joomla site with ~3000+ menu items.
#### Steps to reproduce the issue
when i get into the template manager / module manager
the SQL query takes ~40 sec.
![screen shot 2016-03-22 at 06 16 52](https://issues.joomla.org/uploads/1/8db111000510c0e04c51fc2cd2ea16aa.png)
![screen shot 2016-03-22 at 06 16 52](https://issues.joomla.org/uploads/1/cec4eddcf41aa8f5582363917bcef40c.png)

ifound that the SQL has GROUP BY command that take ~10 sec. to process.
if i remove it and add "DISTINCT" after the select the query take ~0.05 sec.

sql query that take 10 sec.

SELECT a.id    AS value, a.title AS text, a.alias, a.level, a.menutype, a.type, a.template_style_id, a.checked_out 
FROM   XXXXXXX_menu AS a 
       LEFT JOIN `XXXXXXX_menu` AS b 
              ON a.lft > b.lft 
                 AND a.rgt < b.rgt 
WHERE  a.published != -2 
GROUP  BY a.id, a.title, a.alias, a.level, a.menutype, a.type, a.template_style_id, a.checked_out, a.lft 
ORDER  BY a.lft ASC 

fixed sql

SELECT DISTINCT a.id AS value, a.title AS text, a.alias, a.level, a.menutype, a.type, a.template_style_id, a.checked_out 
FROM   XXXXXXX_menu AS a 
       LEFT JOIN `XXXXXXX_menu` AS b 
              ON a.lft > b.lft 
                 AND a.rgt < b.rgt 
WHERE  a.published != -2 

ORDER  BY a.lft ASC 

Is it possible to fix this SQL?

**Comment by brianteeman** [comment] 2016-03-22 11:31
Is it possible for you to provide a database dump of just the #__menu
table? This will really help people to test without having to create a
gazillion menu items

**Comment by brianteeman** [comment] 2016-03-22 11:46
Reset priority to documented standards https://docs.joomla.org/Priority<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9516">issues.joomla.org/joomla-cms/9516</a>.</sub>

**Comment by ggppdk** [comment] 2016-03-23 10:36
GROUP BY should be used when there is need to calculate an aggregate value via an aggregate function such as COUNT(), MAX() etc,

in this case i do not see any aggregate function inside the SQL query
- database server should treat this as DISTINCT, but as i have seen in my own code, MySQL does not do it (maybe newer versions do it?)

now if the PHP code 
- does not have an if statement to add an aggregate function (someone should check the PHP code)
- and since as we can see that SELECT clause is same as GROUP BY clause , the GROUP BY should be replaced with DISTINCT giving a big performance difference

**Comment by benshaty** [comment] 2016-03-27 05:26
brianteeman - i sent you the menu dump in an Email.
thanks in advance

**Comment by brianteeman** [comment] 2016-03-27 08:06
Got it thanks

**Comment by brianteeman** [comment] 2016-03-27 11:40
Thanks for sending the data
The first thing you may need to do is to increase the limit change max_input_vars in php.ini. 
It will need to be at least 50 higher then the total number of menu items

**Comment by benshaty** [comment] 2016-03-27 13:23
didn`t work :(

**Comment by brianteeman** [comment] 2016-03-27 13:55
No that won't make it faster but it will prevent errors due to the large
number of variables that are loaded

**Comment by benshaty** [comment] 2016-03-31 05:31
hi brianteeman,
did you find something?

**Comment by brianteeman** [comment] 2016-03-31 07:29
@alikon do you think you will be able to take a look at this - I can confirm the slow queries and I have the db dump if it will help<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9516">issues.joomla.org/joomla-cms/9516</a>.</sub>

**Comment by alikon** [comment] 2016-03-31 09:11
I will look at it but i need more clear info on how to replicate.... Can you help me ...

**Comment by brianteeman** [comment] 2016-03-31 09:28
I will email you a database dump with 3000+ menu items

You will need to ensure that you have php_max_vars set to greater than the
number of menu items or joomla will fail

Then to see the issue try to open any module for editing and you will see
the delay. This is due to the way a module can be assigned to a menu item
and in this case we have 3000+

**Comment by benshaty** [comment] 2016-03-31 12:47
hi,
about the Joomla! Issue Tracker - CMS.
can you change the category from mssql to mysql?
i don`t know how and i think it`s relevent.
thanks :)

**Comment by roland-d** [comment] 2016-03-31 12:49
As per your request I changed the category. Since there is no MySQL category, I set it to SQL.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9516">issues.joomla.org/joomla-cms/9516</a>.</sub>

**Comment by benshaty** [comment] 2016-03-31 12:50
thanks :)

**Comment by zero-24** [comment] 2016-03-31 18:51
This can be closed as we have a PR by @alikon here: #9689

**Comment by brianteeman** [comment] 2016-03-31 21:24
Closed as we have a PR for testing #9689 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9516">issues.joomla.org/joomla-cms/9516</a>.</sub>

**Closed by brianteeman** 2016-03-31 21:24 UTC
Labels: No Code Attached Yet

**Comment by brianteeman** [comment] 2016-04-01 08:40
@benshaty please can you test the changes made in #9689 - I had amazing results with it with your data set<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9516">issues.joomla.org/joomla-cms/9516</a>.</sub>

**Comment by benshaty** [comment] 2016-04-01 09:28
Thanks. 
I'll check it on Sunday and update.  



נשלח מסמארטפון ה-Samsung Galaxy שלי.

<div>-------- הודעה מקורית --------</div><div>מאת: Brian Teeman <notifications@github.com> </div><div>תאריך:01/04/2016  11:40  (GMT+02:00) </div><div>אל: joomla/joomla-cms <joomla-cms@noreply.github.com> </div><div>עותק: Ben Shaty <benshaty@gmail.com> </div><div>נושא: Re: [joomla/joomla-cms] joomla backend get slow with a lot of menu
  items (#9516) </div><div>
</div>@benshaty please can you test the changes made in #9689 - I had amazing results with it with your data set

This comment was created with the J!Tracker Application at issues.joomla.org/joomla-cms/9516.
