### ISSUE TITLE
Disable front end login for superuser.

### ISSUE THREAD

**Issue by danish1023** [joomla/joomla-cms#10043] opened 2016-04-22 12:50 UTC
###Issue
Disable front-end login for super user.

### I did

I have changed the permission of superuser Site login to Denied but still able to login.

#### Expected result

Not able to logged in

#### Actual result

Able to login

**Comment by mbabker** [comment] 2016-04-22 13:21
IIRC the super user ACL setting "wins" over the denied setting so if you're trying to ACL limit a user or group you'd need to assign them non super user ACL.

**Comment by brianteeman** [comment] 2016-04-22 13:29
Yes thats correct - Super User is treated like a root user that can do anything.

Closing as this is the intended behaviour<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10043">issues.joomla.org/joomla-cms/10043</a>.</sub>

**Closed** 2016-04-22 13:29 UTC
Labels: No Code Attached Yet
