### ISSUE TITLE
Logic bug: Categories Options is tied up with Articles Options

### ISSUE THREAD

**Issue by jlilio** [joomla/joomla-cms#5842] opened 2015-01-21 02:50 UTC
#### Steps to reproduce the issue
Content -> Category Manager -> Options -> Permissions (leads you to Articles Manager Options).

Thus, as a use case, at present it is not possible to create a certain group (e.g., Secretariat) inheriting permission, for instance from Manager, but should only be able to create/edit articles but not allowed to create new categories. This group needs administration back-end permission (as they will handle management of other components as well).

#### Expected result
Be able to create a group that can be allowed to create/edit articles (of specific categories) but should be denied to create or edit categories.

#### Actual result
A Categories Options that is not tied up with the Articles Options

#### System information (as much as possible)
Joomla! 3.3.6 Stable [ Ember ] 01-October-2014 02:00 GMT 

#### Additional comments
N/A

**Comment by Bakual** [comment] 2015-01-21 07:03
If you click the "Options" button on the top right, you get to the components options.
However you are referring to the category options, Those are accessed when you edit a category and you can edit the ACL in the "Permissions" tab of that category edit form just fine.

I'm closing this as not a bug.
If you need help setting up the ACL, feel free to request support in the Joomla forums (http://forum.joomla.org/),

**Comment by Bakual** [comment] 2015-01-21 08:47
Reopening since I am stupid and can't read.

**Comment by jlilio** [comment] 2015-01-21 17:52
Thanks for reading my email and reopening the issue tracking for this Thomas. Much appreciated. 

Indeed, for a large organization (such as a university with several thousands of students) with many groups having different permission settings, the ability to restrict most of these groups from creating new categories is essential.

The suggested method of disabling from global setting, did not work. It disabled "Create" on both Articles and Categories.

There is reason to believe that correcting the logic by separating the Options (especially Permissions) for Category from Articles will correct the experienced challenge and will provide better granularity for these two integral and complementary yet distinct part of the CMS.

**Comment by brianteeman** [comment] 2015-01-21 18:31
I would recommend that for a complex ACL implementation you abandon the
idea of inheriting in this way. Instead I would look at adopting role based
ACL. Its much easier when you get your head around it. Have a search for
articles in the JCM and for videos recorded at JAB by Sander Potjer and
Randy Carey. They both explain role based ACL very well

**Comment by jlilio** [comment] 2015-01-22 10:02
Hi Brian, thanks for pointing me into this direction. While I wasn't able to watch the entire video, I found time to communicate with Sander. He's very accommodating.

In the absence of certain functionality in the Joomla core and for enhancing capabilities, 3rd party extensions are the way to go. I have used many of them over the years for my projects, both paid and free. I asked Sander if his ACL Manager will allow me to prevent certain groups from creating categories while still allowing them to create new articles. He shared [this link](https://www.aclmanager.net/blog/releases/341-acl-manager-240-released-enhanced-joomla-acl) to me. I subscribed to get his extension today, a no-brainer really.

Having said that, still, I am hoping that the ability to prevent groups from creating new categories will make its way to the core. Forget about the many other complex things that goes along with ACL (which I may have incorrectly implied). By addressing just specifically this, such small improvement will surely matter in the long haul (i.e., to prevent newbies and unauthorized persons from messing up the categories structure). I hope you will all agree with me that this is essential for a CMS.

**Comment by zero-24** [comment] 2015-05-09 13:11
Moving to `Needs Review` so a Maintainer can decide if this should included in the Core or not. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5842">issues.joomla.org/joomla-cms/5842</a>.</sub>

**Comment by wilsonge** [comment] 2016-05-07 10:17
Hi you created this issue sometime ago but have not provided any code for people to evaluate. As no one else has shown any interest in providing the code and you have not then I am closing this issue at this time. If code is provided (a pull request) it can always be re-examined.

I definitely think this is valid and maybe we can consider this for a GSOC project in the future<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5842">issues.joomla.org/joomla-cms/5842</a>.</sub>

**Closed** 2016-05-07 10:17 UTC
Labels: No Code Attached Yet
