### ISSUE TITLE
Batch: If category is not selected we always move intead of copy the item

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#7371] opened 2015-07-07 20:21 UTC
#### Steps to reproduce the issue

- Go to the Article Manager
- create on entry e.g. with language "All"
- select that article
- open the batch modal
- change only the "language" and set to "copy" but don't change the category (should be the same categoy but ony another language)
- run the batch

#### Expected result (I'm not 100% sure if this is realy the expected)

the article gets copied to the same category with the changed language

#### Actual result

the article stay at the same category but change the language but it is not copied.

#### Additional comments

Original reported here: http://www.joomla-bugs.de/forum/index.php/topic,679.0.html

**Comment by Bakual** [comment] 2015-07-07 20:42
If you don't select a category, the copy/move selection actually does nothing. See the description on top of the batch modal:
> If a category is selected for move/copy, any actions selected will be applied to the copied or moved articles. Otherwise, all actions are applied to the selected articles.

So the current behavior is the intended behavior.

**Comment by brianteeman** [comment] 2015-07-07 20:47
That doesn't make it the correct behaviour or that it cannot be improved <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7371">issues.joomla.org/joomla-cms/7371</a>.</sub>

**Comment by Bakual** [comment] 2015-07-07 20:56
> That doesn't make it the correct behaviour or that it cannot be improved

Yeah, it's not the most obvious behavior or user interface (depending how you look at it).
Currently it's the intended behavior, maybe not the expected :smile: 

To improve, we either should improve the UI to make it more clear that the copy/move is tied to the category select, or change the behavior.

**Comment by brianteeman** [comment] 2015-07-08 08:57
I am re-opening this - as @bakual says above 
> To improve, we either should improve the UI to make it more clear that the copy/move is tied to the category select, or change the behavior.

If it is open then hopefully someone will take on that task. Closing it everytime it is brought up will never get it resolved

**Comment by Bakual** [comment] 2015-07-08 09:33
For reference a discussion we had earlier: https://github.com/joomla/joomla-cms/issues/6642

**Comment by brianteeman** [comment] 2015-07-10 21:14
Would it make more sense if it was required to set the copy/move and category<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7371">issues.joomla.org/joomla-cms/7371</a>.</sub>

**Comment by brianteeman** [comment] 2015-07-10 21:14
I think if it did do that then it would match the expectation of the user within the limitations of the code.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7371">issues.joomla.org/joomla-cms/7371</a>.</sub>

**Comment by Bakual** [comment] 2015-07-11 18:12
> Would it make more sense if it was required to set the copy/move and category

Making the category required would mean you can no longer batch change items from different categories in the same batch. Which would limiting the current function.

In the earlier issue an idea was to raised that copy/move would be hidden if no category is selected.
I'm not a huge fan of that but it may be a viable approach. Maybe not hide it but disable it?

**Comment by brianteeman** [comment] 2015-08-05 15:35
Please see #7637 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7371">issues.joomla.org/joomla-cms/7371</a>.</sub>

**Closed** 2015-08-05 15:35 UTC
Labels: No Code Attached Yet
