### ISSUE TITLE
Frontend menu mey disappear after 3.7.0 update

### ISSUE THREAD

**Issue by wojsmol** [joomla/joomla-cms#15671] opened 2017-04-28 17:06 UTC
### Steps to reproduce the issue
Update the page using menutype = menu or menutype = main as the site menu to 3.7.0
### Expected result
The menu is shown on the frontend
### Actual result
The menu is not visible on the frontend
### Additional comments
cc @rdeutz because it is caused by PR https://github.com/joomla/joomla-cms/pull/13619

**Comment by brianteeman** [comment] 2017-04-28 17:11
I dont understand how you have a menu of menutype either main or menu as Joomla doesnt let you create a menu with a menutype of main or mennu

> Please change the Menu type. The terms 'menu' and 'main' are reserved for Backend usage.

**Comment by wojsmol** [comment] 2017-04-28 17:25
@brianteeman The problem occurs when menu with menutype menu or main is created in Joomla! version which did not prohibit it.

**Comment by PhilETaylor** [comment] 2017-04-28 17:25
Today I debugged a site that started seeing frontend menu items in the components menu in the admin! This only happened on update to Joomla 3.7.0

On investigating #__menu those menu items were of menutype "main" ...

Therefore Im **guessing**, that in some earlier version of Joomla we allowed it... and in 3.7.0 something 'changed'

**Comment by wojsmol** [comment] 2017-04-28 17:27
@PhilETaylor see https://github.com/joomla/joomla-cms/issues/13619 this is the cheange.

**Comment by izharaazmi** [comment] 2017-04-29 00:16
> Im guessing, that in some earlier version of Joomla we allowed it... and in 3.7.0 something 'changed'

Truth is exactly the opposite.

Knowing this fact, this issue should not be caused by said change. I/we need to investigate deeper.

**Comment by wojsmol** [comment] 2017-04-29 01:08
@izharaazmi Menu disappear only on legacy web sites see @PhilETaylor. I also diagnose this problem for someone one of Polish group about Joomla! on Facebook. Result: menutype = menu and we have the problem described above.

**Comment by mydutchtouch** [comment] 2017-04-29 01:14
I can confirm the menu on frontend disappears. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15671">issues.joomla.org/tracker/joomla-cms/15671</a>.</sub>

**Comment by wojsmol** [comment] 2017-04-29 01:28
@mydutchtouch Do you remember on what version of Joomla! site was installed?

**Comment by mydutchtouch** [comment] 2017-04-29 01:35
I upgraded today from 3.6.5 to 3.7. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15671">issues.joomla.org/tracker/joomla-cms/15671</a>.</sub>

**Comment by wojsmol** [comment] 2017-04-29 01:53
I will ask otherwise. When more or less this website was created?

**Comment by mydutchtouch** [comment] 2017-04-29 02:09
Website was created 3 months ago using a template. Not sure how old the template is. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15671">issues.joomla.org/tracker/joomla-cms/15671</a>.</sub>

**Comment by wojsmol** [comment] 2017-04-29 09:56
@izharaazmi Any idea how to detect which elements should be in the backend menu? In the current situation where we can not trust menutype for updated websites. The simplest solution is a https://github.com/joomla/joomla-cms/pull/13619 rever and adding a problem description and manual solution to the 3.7.0 Release FAQ.

**Comment by izharaazmi** [comment] 2017-04-29 09:59
Can you please explain more as how to reproduce your issue here so that I
can come up with the real culprit and solution. As of now I am unable to
reproduce and hence can't fix anything. Thanks.

**Comment by wojsmol** [comment] 2017-04-29 10:33
1. Install Joomla! 3.6.5 with sample data
2. Change the menutype of any frontend menu link in `#__menu`   to `menu` or ` main`..
3. Make backup of the website database.
4. Make updates to 3.7.0 with com_joomlaupdate.
5. Result link from 2 in components admin menu.

**Comment by wojsmol** [comment] 2017-04-29 13:31
@izharaazmi I updated the description in the previous comment to be 100% understandable. Sorry for the previous version. I was really in a hurry.

**Comment by alikon** [comment] 2017-04-30 05:57
you cannot create a menutype  with (`main`, `menu`) in 3.6.5
![menutype](https://cloud.githubusercontent.com/assets/181681/25562016/048c6f10-2d7a-11e7-963f-5f10ec1b0c5d.PNG)

**Comment by alikon** [comment] 2017-04-30 06:17
so i guess  we should replace this from #13619
```sql
UPDATE `#__menu` SET `menutype` = 'main', `client_id` = 1  WHERE `menutype` = 'main' OR `menutype` = 'menu';
```

to this one

```sql
UPDATE `#__menu` , `#__menu_types` 
SET `#__menu`.`menutype` = 'menu_main_is_reserved'
    ,`#__menu_types`.`menutype` = 'menu_main_is_reserved'
WHERE `#__menu`.`menutype` = 'main' 
AND `#__menu`.`menutype` = `#__menu_types`.`menutype`;
```

cause the only the term `main`  is reserved now

**Comment by wojsmol** [comment] 2017-04-30 06:52
@alikon Yes we cent create main or menu in 3.6.5 but earlier it was possible. Can you create a PR with your changes?

**Comment by franz-wohlkoenig** [comment] 2017-04-30 09:51
closed as having PR #15695<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15671">issues.joomla.org/tracker/joomla-cms/15671</a>.</sub>

**Closed by franz-wohlkoenig** 2017-04-30 09:51 UTC
Labels: No Code Attached Yet

**Comment by richard67** [comment] 2017-06-07 18:51
New PR is #16577 . Please test as soon as I have updated the testing instructions there.
Btw. does anybody know which Joomla version can be used to create a menu type "main" or "menu" for the site (frontend)? Does that work on a 3.6.5? Would be good to know for easy testing instructions.

**Comment by richard67** [comment] 2017-06-07 20:08
PR #16577 is ready. Please test.

**Comment by richard67** [comment] 2017-06-18 11:53
@wojsmol Please test #16577 ([issue tracker link see here](https://issues.joomla.org/tracker/joomla-cms/16577)).
