### ISSUE TITLE
PlgContentEmailcloak::_cloak(): Argument #1 ($text) cannot be passed by reference 

### ISSUE THREAD

**Issue by xillibit** [joomla/joomla-cms#36501] opened 2021-12-31 10:26 UTC
### Steps to reproduce the issue

You need to have one or more articles as featured on the home page

Update with last changes from 4.0-dev branch github, go to the frontend you will see the issue :

![image](https://user-images.githubusercontent.com/876395/147818071-3a58ba12-4a01-4896-8b21-a744452c8641.png)

This change is causing the issue : https://github.com/joomla/joomla-cms/commit/c604191d6f11ee08bf3bfd9edd719e7c492194b5#diff-f16f36bed93f14aa31addbb48b984a3e77da598e5ebd014e7a5157409b6d3087

### Expected result

No error

### Actual result

PlgContentEmailcloak::_cloak(): Argument #1 ($text) cannot be passed by reference 

### System information (as much as possible)

Joomla! 4.0.6-dev
Php 8.0.14 and 8.1.1
MySQL 5.7.36

**Comment by richard67** [comment] 2021-12-31 13:32
Similar to what is described in the (unrelated) PR #36503 , I think that the error is only thrown on PHP 8, so I set the corresponding label.

**Comment by xillibit** [comment] 2021-12-31 13:35
On Php 7.4.27 and 7.3.33 : 

![image](https://user-images.githubusercontent.com/876395/147825978-58210293-7942-4c69-b244-9dd06c1bbc73.png)

**Comment by richard67** [comment] 2021-12-31 13:36
Hmm, ok.

**Comment by PhilETaylor** [comment] 2021-12-31 16:20
I dont see how this was caused by my change - we have always passed `$row->text` or `$row` to the `_cloak` method

**Comment by xillibit** [comment] 2021-12-31 16:26
If i remove the articles featured on the home page the error disappear

**Comment by alikon** [comment] 2021-12-31 16:36
i confirm @xillibit  findings latest changes come from #36442

**Comment by PhilETaylor** [comment] 2021-12-31 16:36
Im looking into it already - but fail to see the root cause as the code is technically the same.

**Comment by PhilETaylor** [comment] 2021-12-31 16:38
ah I see... PR incoming

**Comment by PhilETaylor** [comment] 2021-12-31 16:41
fixed by https://github.com/joomla/joomla-cms/pull/36505

**Comment by richard67** [comment] 2021-12-31 16:49
Closing as having a pull request. Please test #36505 . Thanks in advance.

**Closed as completed by richard67** 2021-12-31 16:49 UTC
Labels: No Code Attached Yet
