### ISSUE TITLE
Custom fields doesn't work with accents

### ISSUE THREAD

**Issue by dpaya** [joomla/joomla-cms#15287] opened 2017-04-13 15:37 UTC
### Steps to reproduce the issue
Content->Fields->New->Type=List

Add values to List Values

Text 
Value 
 
Manuel Gómez Padilla
 
Manuel Gómez Padilla
		

Victor Rico
 
Victor Rico
		
### Expected result

Fields in edit article 

### Actual result
Warning: SimpleXMLElement::__construct(): Entity: line 2: parser error : Entity 'oacute' not defined in /j7/libraries/joomla/form/form.php on line 72
Warning: SimpleXMLElement::__construct(): le=&quot;1&quot; validate=&quot;options&quot;&gt;&lt;option value=&quot;Manuel Gómez Padilla&quot;&gt;Manuel G&amp;oacute; in /j7/libraries/joomla/form/form.php on line 729
Warning: SimpleXMLElement::__construct(): ^ in /j7/libraries/joomla/form/form.php on line 729

### System information (as much as possible)
Database Version	5.7.17-0ubuntu0.16.04.1
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	7.0.15-0ubuntu0.16.04.4
Web Server	Apache/2.4.18 (Ubuntu)
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 3.7.0-rc2 Release Candidate [ Amani ] 12-April-2017 08:18 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/57.0.2987.98 Chrome/57.0.2987.98 Safari/537.36

### Additional comments
![screen shot 2017-04-13 at 15 44 23](https://issues.joomla.org/uploads/1/737b0012490d0439f0e68bdfd5268b99.png)
In Fields when I add a text with accents in the list of values in the article edition the fields doesn't show because there is a problem with simpleXML.
![screen shot 2017-04-13 at 15 45 35](https://issues.joomla.org/uploads/1/1024d3003c1804630dab1a4676dbe0ec.png)![screen shot 2017-04-13 at 15 45 58](https://issues.joomla.org/uploads/1/8cf9cecbd0f312f8d50957787704280c.png)

**Comment by brianteeman** [comment] 2017-04-13 15:42
i can confirm this issue on list fields

**Comment by brianteeman** [comment] 2017-04-13 15:57
Same problem with checkbox fields

**Comment by esedic** [comment] 2017-04-13 18:25
Looks like XML string needs to be decoded.
If you change line 728 in file libraries/joomla/form/form.php from
`$data = new SimpleXMLElement($data);`
to
`$data = new SimpleXMLElement(html_entity_decode($data, ENT_QUOTES, "utf-8"));`
warning is gone.

**Comment by zero-24** [comment] 2017-04-13 19:20
@esedic can you send this fix as PR against the staging repo?

**Comment by esedic** [comment] 2017-04-13 20:18
Done.

**Comment by zero-24** [comment] 2017-04-13 20:28
Thanks. Closing as we have a PR by @esedic

**Closed by zero-24** 2017-04-13 20:28 UTC
Labels: No Code Attached Yet
