### ISSUE TITLE
Multilingual Associations does not respect the number of results per page

### ISSUE THREAD

**Issue by walturbo** [joomla/joomla-cms#17136] opened 2017-07-14 15:10 UTC
### Steps to reproduce the issue

Access the Multilingual Associations component, select filters Articles and Italiano (IT) in my case. If the problem does not occur, try selecting from the CATEGORIES filter and then again ARTICLES.

### Expected result

25 results per page

### Actual result

All the results

**Comment by infograf768** [comment] 2017-07-15 16:21
I can reproduce the issue ONLY when first selecting Categories and then Articles.
If I change again the number of articles to display, it works fine.

**Comment by ghost** [comment] 2017-07-19 05:43
@infograf768: Is this an Issue which needs a PR or expected Behaviour?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17136">issues.joomla.org/tracker/joomla-cms/17136</a>.</sub>

**Comment by infograf768** [comment] 2017-07-19 06:15
Needs a PR

**Comment by alikon** [comment] 2019-04-10 18:59
correct me if i'm wrong but the same behaviour happens when you switch from article to cetagories 
isn'it?

**Comment by brianteeman** [comment] 2022-08-23 16:58
Same problem as #38411

**Comment by brianteeman** [comment] 2022-08-23 19:36
Please update the tag to be J4 issue

**Comment by Hackwar** [comment] 2024-09-29 18:56
I can not recreate this issue. Can someone else check if this is still an issue? Otherwise we can close this issue.

**Comment by coolcat-creations** [comment] 2024-10-09 10:21
@Hackwar can't reproduce either

**Comment by fgsw** [comment] 2024-10-09 10:43
@Hackwar Can't confirm on ‎5.2.0-rc4-dev, but had to re-login after changing the default list limit (different to i.e. Articles view which use the changed list limit without re-login).

**Comment by Hackwar** [comment] 2024-11-26 18:00
Since we have 3 people who can't reproduce it, I'm closing this issue for now. If you still encounter this problem, please open a new ticket and reference this one.

**Closed as completed by Hackwar** 2024-11-26 18:00 UTC
Labels: No Code Attached Yet, J4 Issue, Information Required, bug
