### ISSUE TITLE
[com_fields] Show Value of "Automatic Display: Use Global"

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#13350] opened 2016-12-23 13:01 UTC
### Steps to reproduce the issue
Open a Field, go Tab "Options": "Automatic Display" don't show Value of "Use Global"
![field-use-global](https://cloud.githubusercontent.com/assets/8235763/21454315/cb8ba508-c917-11e6-8f07-a639cb075409.jpg)

### Expected result
Show i.E "Use Global (After Title)"

### Actual result
Show "Use Global"

### System information (as much as possible)
Joomla! 3.7.0-alpha1
PHP 7.0.4
MySQLi 5.5.53-0+deb7u1

**Comment by Bakual** [comment] 2016-12-23 13:21
Hehe, people already expect that little feature to work everywhere :smile: 

It doesn't work here because the global value is set in the "System - Fields" plugin. So the standard lookup in the component options (com.fields in this case) doesn't work.
There are two possible solutions:
* Create a custom formfield for the "Automatic Display" parameter which then looks up the correct global value in the plugin params
* Move the global value to com_fields component settings. However since com_fields currently doesn't have any own settings that needs a bit of redesign.

**Comment by franz-wohlkoenig** [comment] 2016-12-23 13:58
You're right, cause that little feature helps ;-) 

I can live with it as it is an expected behavior. Thanks for suggested solutions, buth they are a way above my knowledge.

**Comment by Bakual** [comment] 2016-12-23 14:01
I can do it for sure. That is no problem. Lets keep this issue open.

@laoneo Do you think we will move that parameter around or is it save to create a custom field here?

**Comment by laoneo** [comment] 2016-12-23 15:00
Correctly it would belong to each component options. For example on in the articles component it would belong to the "Article" settings. It will become interesting when we start to implement custom fields for categories. Then you basically need two settings one of categories and one for articles. At the moment I don't have a valid clue where to put it correctly and how to implement it. What I know is that the setting in the system plugin is on the wrong place.

**Comment by Bakual** [comment] 2016-12-23 15:16
It gets a bit tedious if you have to add it to each component.

**Comment by brianpeat** [comment] 2017-01-25 17:32
I agree that putting it in the plugin is the wrong place. No regular user would ever stumble on that. I think even though it's more work, it really should be added to every component that can use fields. Let's not half ass this thing, the end users won't react well to it, trust me.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13350">issues.joomla.org/tracker/joomla-cms/13350</a>.</sub>

**Comment by laoneo** [comment] 2017-01-26 08:06
For me I would put it also on every component. If a component doesn't implement it, then we still can inherit it from the plugin.

**Comment by Bakual** [comment] 2017-01-26 08:31
If it's only that single parameter, then I agree. But I foresee there will be more in future.

**Comment by franz-wohlkoenig** [comment] 2017-01-26 08:37
@Bakual you foresee right.

**Comment by brianpeat** [comment] 2017-01-27 00:55
The problem is, if we leave it as is, ALL components get the same global, so you can't set one component to always put the fields under the title and another to put them after the article. It also sets up a bad experience for users. It's like "Hey, ALL the other global settings are in the component, but we put these in the plugin where you'll never find them"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13350">issues.joomla.org/tracker/joomla-cms/13350</a>.</sub>

**Comment by Bakual** [comment] 2017-01-27 06:58
Sure, but what happens if we add another parameter? Global functionality would be broken until all extensions update their options. Which is certainly not a good experience either. And then most likely not all extensions add it at the same position. It will become a big mess. Architecturally it's wrong as well as they are com_fields (or more precise fields plugin) options. The extension doesn't do anything with it.

**Comment by franz-wohlkoenig** [comment] 2017-01-27 07:06
It makes wondering why in one part of Joomla are "Options (Global)", on other not. Users cant know why (Devs. know). I understand, that its not possible now, but it should be a goal.

**Comment by Bakual** [comment] 2017-01-27 07:38
Showing the global value from the plugin options (eg "Use Global (Show)") is possible. It just needs an own formfield for the parameter but that is easy to do.
We could also add a hint as to where to find the global setting (eg add it in the tooltip of the parameter).

**Comment by franz-wohlkoenig** [comment] 2017-01-27 08:18
Its helping to show "Use Global ("Value") where its possible, thanks @Bakual.

**Comment by laoneo** [comment] 2017-01-27 09:26
For 3.7 I guess we make it simple and do remove the from global option, it just confuses too many people.  PR #13773 defaults the value to "before display" and removes the option from the plugin.

**Comment by laoneo** [comment] 2017-01-27 09:26
What yuo guys think?

**Comment by franz-wohlkoenig** [comment] 2017-01-27 09:28
better remove than show Options they look different to other Joomla-Parts.

**Comment by Bakual** [comment] 2017-01-27 19:18
Yeah that works as well. Closing as we have a PR

**Closed by Bakual** 2017-01-27 19:18 UTC
Labels: No Code Attached Yet
