### ISSUE TITLE
Increment on non-alphanumeric string

### ISSUE THREAD

**Issue by tavaba** [joomla/joomla-cms#44151] opened 2024-09-29 06:23 UTC
### Steps to reproduce the issue
1. From Joomla Administration page, set Server > Error Reporting to 'Maximum'
2. Create a new Article > Click "Save"

### Expected result
The article is saved.

### Actual result
Error message on the browser:
PHP Deprecated:  Increment on non-alphanumeric string is deprecated in C:\inetpub\joomla\administrator\components\com_content\src\Model\ArticleModel.php on line 349

### System information (as much as possible)
Windows 10
IIS
php 8.3.11 (non-threadsafe)

**Comment by richard67** [comment] 2024-09-29 07:16
Which Joomla version?

**Comment by richard67** [comment] 2024-09-29 07:50
And are you using the standard English administrator language? Or another language? If the latter: Does the issue still happen when changing to English?

**Comment by tavaba** [comment] 2024-09-29 08:39
My Joomla version is 4.4.8
The language is English.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44151">issues.joomla.org/tracker/joomla-cms/44151</a>.</sub>

**Comment by brianteeman** [comment] 2024-09-29 09:13
duplicate of #43896 ?

**Comment by Quy** [comment] 2024-09-29 15:18
Closing as duplicate of #43896. Thanks for the report.

**Closed as completed by Quy** 2024-09-29 15:18 UTC
Labels: No Code Attached Yet

**Comment by Quy** [comment] 2024-10-01 05:27
Please test PR #44173. Thanks.
