### ISSUE TITLE
[4.0] npm failure

### ISSUE THREAD

**Issue by alikon** [joomla/joomla-cms#32135] opened 2021-01-24 08:34 UTC
### Steps to reproduce the issue

Running npm ci on current 4.0-dev

### Expected result
no error

### Actual result

```
The /templates/system/incompatible.html page was created successfully!

> joomla@4.0.0 build:bs5 /var/www/html/bs5
> node build/build-modules-js/build-bootstrap-js.es6.js

Building ES6 Components...
TypeError: rimraf.rm is not a function
    at /var/www/html/bs5/build/build-modules-js/build-bootstrap-js.es6.js:122:18
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! joomla@4.0.0 build:bs5: `node build/build-modules-js/build-bootstrap-js.es6.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the joomla@4.0.0 build:bs5 script.
npm ERR! This is probably not a problem with npm. 


```

### System information (as much as possible)
node v12.18.2
npm  v6.8.0

### Additional comments
probably https://github.com/joomla/joomla-cms/blob/f65400bb0beab4b775c85b552d944b44ddc7d815/build/build-modules-js/build-bootstrap-js.es6.js#L122 need v14.14.0
https://nodejs.org/api/fs.html#fs_fs_rm_path_options_callback

**Comment by dgrammatiko** [comment] 2021-01-24 12:04
Thanks @alikon, should be ok with https://github.com/joomla/joomla-cms/pull/32143

**Comment by ghazal** [comment] 2021-01-24 12:05
Environment
macOS Catalina
php 8.0
Bitnami stack

Versions
npm  version 6.14.9
node version 15.4.0
Composer version 2.0.8

Methods
git clone --depth=1 -b 4.0-dev https://github.com/joomla/joomla-cms/
composer install
npm ci


I did exactly this:

> Running npm ci on current 4.0-dev

**I can't reproduce the error mentioned.
Everything works OK.**

NB: lots of warnings like this though (randomly picked up):

> 90 │   atum-bg-dark-70:                 adjust-color($base-color, $hue: +4%, $lightness: -6%),
>    │                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>    ╵
>     administrator/templates/atum/scss/_variables.scss 90:36                              @import
>     administrator/templates/atum/scss/vendor/joomla-custom-elements/joomla-tab.scss 4:9  root stylesheet
> 
> DEPRECATION WARNING: $hue: Passing a unit other than deg (7%) is deprecated.
> 
> To preserve current behavior: $hue / 1%

> See https://sass-lang.com/d/color-units

If you need another test with same parameters or different parameters, I'd be happy to oblige.

**Comment by richard67** [comment] 2021-01-24 12:07
@ghazal As you can read above, the problem is related to node version 12 (or anything else below 14), you have tested with 15.

**Comment by richard67** [comment] 2021-01-24 12:07
Closing as having a pull request. Please test #32143 . Thanks in advance.

**Closed as completed by richard67** 2021-01-24 12:07 UTC
Labels: No Code Attached Yet

**Comment by ghazal** [comment] 2021-01-24 12:08
@richard67 
Tks but I knew. Just wanted to notify that it worked with this version.
