### ISSUE TITLE
Article links not open under correct parent item

### ISSUE THREAD

**Issue by yanc1985** [joomla/joomla-cms#7641] opened 2015-08-06 08:17 UTC
#### Steps to reproduce the issue
create single article menu item (menu1 - article: perdemo)

in "perdemo1", link to other article "subdemo" .

go to fontend, click the link to "subdemo" 

#### Expected result

the link should be http://xxxx.com/menu1/xx-catagory/yy-subdemo

#### Actual result

the link should be http://xxxx.com/xx-catagory/yy-subdemo

#### System information (as much as possible)
joomla 3.4

#### Additional comments
The Expected result is base on my knowledge in  joomla 2.5, since the Actual Result now redirect to "Home" page, then I can't show the related modules in the orginal menu item...

**Comment by Bakual** [comment] 2015-08-06 08:33
It depends what the homepage menu item is. If that one is a "better" fit for the linked article, then that menu item is taken. Since you are starting from a single article menu item, chances are indeed high that the home menu item is a better fit.

To solve this, you could create a "hidden" menu item (in a menu you don't assign to a module and thus never show). It should work if you do one to the category of the linked article. Then that should be a better fit than the homepage and this menuitem is taken.

**Comment by brianteeman** [comment] 2016-01-28 12:19
I am closing this at this time - its kind of a weird but expected behaviour in the current code base.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7641">issues.joomla.org/joomla-cms/7641</a>.</sub>

**Closed** 2016-01-28 12:19 UTC
Labels: No Code Attached Yet
