### ISSUE TITLE
Components menu won't scroll down

### ISSUE THREAD

**Issue by kkstf** [joomla/joomla-cms#7567] opened 2015-07-27 17:58 UTC
In my administrator backend, I hover over Components link and all my installed components drop down in the menu as expected. But I have so many Components installed that they fill the entire dropdown menu.Some of the components go below the fold. Unfortunately, I am unable to scroll down to see the Components that are below the fold (in my case, those components starting with letters after the letter "R"). I tried Chrome and Firefox.
Any fixes for this other than resizing the browser to get the mobile menu?
Thanks!

**Comment by brianteeman** [comment] 2015-07-27 17:59
You could remove some components :-p

On 27 July 2015 at 18:58, kkstf <notifications@github.com> wrote:

> In my administrator backend, I hover over Components link and all my
> installed components drop down in the menu as expected. But I have so many
> Components installed that they fill the entire dropdown menu.Some of the
> components go below the fold. Unfortunately, I am unable to scroll down to
> see the Components that are below the fold (in my case, those components
> starting with letters after the letter "R"). I tried Chrome and Firefox.
> Any fixes for this other than resizing the browser to get the mobile menu?
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/7567>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by kkstf** [comment] 2015-07-27 18:09
That's true, but I like to support Joomla developers :)

**Comment by justinherrin** [comment] 2015-07-27 18:12
It's not a permanent solution, but in the mean time you can always zoom-out on your browser window to see more of the Components drop down items, select the one you need, and zoom back in.

**Comment by kkstf** [comment] 2015-07-27 18:13
Thanks Justin, I never knew I could zoom until now...

**Comment by wilsonge** [comment] 2015-07-29 16:46
I'm closing this issue as a duplicate of #5131

**Closed by wilsonge** 2015-07-29 16:46 UTC
Labels: No Code Attached Yet
