### ISSUE TITLE
Custom fields reset on request new password

### ISSUE THREAD

**Issue by kens1n** [joomla/joomla-cms#22521] opened 2018-10-06 14:26 UTC
### Steps to reproduce the issue

Request new password /?option=com_users&view=reset

### Expected result

custom fields not deleted

### Actual result

custom fields deleted

### System information (as much as possible)

joomla 3.8, php 5.6

### Additional comments

thats bug fix /plugins/system/fields/fields.php

function onUserAfterSave

add 'request' in array to this place in code

$task = JFactory::getApplication()->input->getCmd('task');

if (in_array($task, array('activate', 'block', 'unblock', 'request')))
{
    return true;
}

**Comment by ReLater** [comment] 2018-10-07 14:38
I can't reproduce this issue with J 3.8.12 (only core with testing sample data) and an user in group Registered. Maybe if you provide more detailed testing instructions.
Is there any other extension that uses the Joomla users, e.g. VirtueMart or something?

**Comment by Quy** [comment] 2018-10-20 16:13
Closing until additional information is provided.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22521">issues.joomla.org/tracker/joomla-cms/22521</a>.</sub>

**Closed as completed by Quy** 2018-10-20 16:13 UTC
Labels: No Code Attached Yet
