### ISSUE TITLE
(4.0alpha2) No option for MySQL(i) when installing

### ISSUE THREAD

**Issue by Thomsterdam** [joomla/joomla-cms#19347] opened 2018-01-10 15:31 UTC
### Steps to reproduce the issue

On SiteGround I am trying to install Joomla 4 Alpha 2, using Joomla_4.0.0-alpha2-Alpha-Full_Package.zip. 

### Expected result
After starting the installation, on getting to the Database Configuration screen, I would like to select a MySQLi database (but cannot), see screenshot.
After making a PostgreSQL database,
 I want to specifiy 
- host name, 
- database name, 
- database username
- password
- table prefix

### Actual result
The only database option is PostgreSQL, no option for MySQL(i)
I only get the installation options 
- host name, 
- database username, 
- password 
- database table name 
- table prefix 
(no database name).

### System information (as much as possible)
PHP 7.2.1
database info from configuration.php that is created during installation (lines 14 to 20, edited for securitiy):
	public $dbtype = 'postgresql';
	public $host = 'localhost';
	public $user = 'thomster_test4jo';
	public $password = '[password edited out]';
	public $db = 'thomster_joom4test';
	public $dbprefix = 'mos6u_';
	public $live_site = '';

### Additional comments
location of installation: http://joomla4.tomhiemstra.nl/installation/index.php
screenshot: http://joomla4.tomhiemstra.nl/images/Werkblad_1_012.png

**Comment by mbabker** [comment] 2018-01-10 15:34
Duplicate of #18660 and a plethora of other items.

**Closed as completed by mbabker** 2018-01-10 15:34 UTC
Labels: No Code Attached Yet
