### ISSUE TITLE
Unsubstituted variables

### ISSUE THREAD

**Issue by galamarco** [joomla/joomla-cms#35517] opened 2021-09-09 11:40 UTC
### Steps to reproduce the issue
I'm using a new installation of Joomla 4.0.2 without other extension.
I send an email test from administrator/index.php?option=com_config --> "send test email" and I receive an email where the variables are not replaced in either the subject or the body of the email. See image below.
![](https://bramantehouse.it/images/articoli/2021-09/screenshot_38.png)

In administrator/index.php?option=com_mails&view=templates the email text is the default. I think this text is wrong.

### Expected result
If I send an email text variables will be replaced.

### Actual result
variables are not replaced:

> Object: "Prova email da **%s**"
> Text: "Questa è una email di prova inviata utilizzando **"%s"**. Le tue impostazioni email sono corrette!"

### System information (as much as possible)
Joomla 4.0.2
PHP: 7.4.23
MySql: 10.3.31-MariaDB-cll-lve

Marco

**Comment by PhilETaylor** [comment] 2021-09-09 11:47
What happens if you use English Languages?

**Comment by PhilETaylor** [comment] 2021-09-09 21:00
Out of the box, in english, it works for me. 

```
Content-Type: text/plain; charset=utf-8
Date: Thu, 9 Sep 2021 20:59:34 +0000
From: joomla <phil@phil-taylor.com>
MIME-Version: 1.0
Message-ID: <DhUPtInQdGEkNhqwrdCIN1vLyc2uXXjopBLYOyQ0ic@localhost.localdomain>
Received: from localhost.localdomain by mailhog.example (MailHog)
          id hWigenrpBJ-MjZfab76kKfWODdSizbBUrOSnHjArqs8=@mailhog.example; Thu, 09 Sep 2021 20:59:34 +0000
Return-Path: <phil@phil-taylor.com>
Subject: Test mail from joomla
To: joomla <phil@phil-taylor.com>

This is a test mail sent using "SMTP". Your email settings are correct!

```

**Comment by PhilETaylor** [comment] 2021-09-09 21:03
Confirmed in Italian language I get the same bug:

```
Content-Transfer-Encoding: 8bit
Content-Type: text/plain; charset=utf-8
Date: Thu, 9 Sep 2021 21:02:04 +0000
From: joomla <phil@phil-taylor.com>
MIME-Version: 1.0
Message-ID: <c34CUn4bNkVqT4lXoghtJXoNcSlQOPbPJYxogoGKTA@localhost.localdomain>
Received: from localhost.localdomain by mailhog.example (MailHog)
          id A7Qu-WOZpUFN1ZZkZR7gKeJNEY1-YWmbpQllSNrL97g=@mailhog.example; Thu, 09 Sep 2021 21:02:04 +0000
Return-Path: <phil@phil-taylor.com>
Subject: Prova email da %s
To: joomla <phil@phil-taylor.com>

Questa è una email di prova inviata utilizzando "%s". Le tue impostazioni email sono corrette!

```

In english its:

```
COM_CONFIG_SENDMAIL_BODY="This is a test mail sent using \"{METHOD}\". Your email settings are correct!"
```

In Italian language pack its

```
COM_CONFIG_SENDMAIL_BODY="Questa è una email di prova inviata utilizzando \"%s\". Le tue impostazioni email sono corrette!"
```

So a bug in the language pack... now who to page? @infograf768 ?

**Comment by richard67** [comment] 2021-09-10 21:20
The translation team coordinators for Joomla 4 translations are listed here for each language: https://downloads.joomla.org/language-packs/translations-joomla4

**Comment by PhilETaylor** [comment] 2021-09-11 11:52
That page should also publish their GitHub handles so that they can be pulled into issues like this. I have emailed stellainformatica@gmail.com  with a link to this page, but this should be closed as it cannot be resolved in this repo.

**Comment by richard67** [comment] 2021-09-11 11:54
Closing as not an issue with the CMS core but with the Italian translation. The translation team has been notified. Thanks for reporting.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35517">issues.joomla.org/tracker/joomla-cms/35517</a>.</sub>

**Closed as completed by richard67** 2021-09-11 11:54 UTC
Labels: No Code Attached Yet
