### ISSUE TITLE
[4.0] Debug Bar UI is not usable, all is grey and messy

### ISSUE THREAD

**Issue by simbus82** [joomla/joomla-cms#26762] opened 2019-10-22 11:59 UTC
### Steps to reproduce the issue
Enable debug bar on Joomla 4 Alpha 12
Watch some data in the debugbar.

### Expected result
A refined UI, with a super-rapid view of which process take more time and more ram.
Same for Queries, really easy to check duplicates, overall impact, etc.
Like Joomla 3
![image](https://user-images.githubusercontent.com/1375730/67282842-dd065500-f4d2-11e9-8c34-a6f73ce64523.png)
![image](https://user-images.githubusercontent.com/1375730/67283181-76356b80-f4d3-11e9-91fe-39f82228ad54.png)

### Actual result
Good waterfall view, but unusable UI: fonts really little, no interactions, no overall bars.
Queries section impossible to examine. All is grey and messy.
![image](https://user-images.githubusercontent.com/1375730/67283249-9e24cf00-f4d3-11e9-8910-b6a7ed1f32a4.png)
![image](https://user-images.githubusercontent.com/1375730/67283285-b1379f00-f4d3-11e9-8467-faff30f6fa98.png)

### System information (as much as possible)
Apache 2.4
PHP 7.2
All J4 requirements.

### Additional comments
Probably some styles are not loaded

**Comment by SharkyKZ** [comment] 2019-10-22 13:42
It looks as intended. But improvements are welcome. But one advantage of debug bar in 4.0 is that it's significantly faster than what's in 3.x.

**Comment by simbus82** [comment] 2019-10-22 14:23
Ah ok!
Yes, yes! It's really fast, it's true! I like a lot the new "features" of bar. 
I found a "my" missing feature:
![image](https://user-images.githubusercontent.com/1375730/67295753-dcc48480-f4e7-11e9-927d-80cbfec26251.png)
The position is really bad :-)

So we can try to style it?

**Comment by brianteeman** [comment] 2019-10-22 15:30
> So we can try to style it?

Of course. Pull requests would be welcome

**Comment by Fedik** [comment] 2019-10-29 06:54
>  All is grey 

it perfectly fit to default template :)

**Comment by Quy** [comment] 2019-12-24 01:26
Closing as expected behaviour. Please open PRs for improvements.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26762">issues.joomla.org/tracker/joomla-cms/26762</a>.</sub>

**Closed as completed by Quy** 2019-12-24 01:26 UTC
Labels: No Code Attached Yet
