### ISSUE TITLE
Cannot access protected property Joomla\CMS\Menu\MenuItem::$params

### ISSUE THREAD

**Issue by ced1870** [joomla/joomla-cms#30463] opened 2020-08-24 13:06 UTC
### Steps to reproduce the issue

try to access the params of a menu item using $item->params->get(...)
the item is loaded using 
$items = $menu->getItems('menutype', $params->get('menutype'));

### Expected result
to get the param value

### Actual result
site crash

### System information (as much as possible)
it was working in joomla 3, does not work in joomla 4 beta 3

I see in the mod_menu that it uses that :
$itemParams   = $item->getParams();

but doing this, it will break all existing layouts from extension where the $item->param is used to get the values.

This is a BIG problem and the $item->params->get('value') shall work in any cases as before

### Additional comments
this problem totally crashes the page as soon as the module is published

**Comment by SharkyKZ** [comment] 2020-08-24 15:21
This has been deprecated since 3.7.0. The removal in 4.0 has been documented https://docs.joomla.org/Potential_backward_compatibility_issues_in_Joomla_4#JMenuItem.

Closing as expected behavior.

**Closed as completed by SharkyKZ** 2020-08-24 15:21 UTC
Labels: No Code Attached Yet
