### ISSUE TITLE
[J4] Media field inside Subform field does not save correctly

### ISSUE THREAD

**Issue by regularlabs** [joomla/joomla-cms#35226] opened 2021-08-19 14:13 UTC
Create a subform field that includes a media field. And set the 'Repeatable' setting to No.

In an article, select an image in that field and save the article.

The media field disappears from the article edit form.
But the image does show on the frontend in the fields section.

Save the article again and the field re-appears, but the field is now empty.

If you now save the article again (with the field left empty), the field disappears again.
And on the frontend it now displays a broken image (image tag with no src).

**Comment by drmenzelit** [comment] 2021-12-29 10:19
@regularlabs can you test again on the last J4 version? Some weeks ago a PR for subforms problems was merged and maybe it solved this problem too

**Comment by regularlabs** [comment] 2021-12-29 11:02
In current life version of J4?
Things seem to only have gotten worse 😁
Now I can't even choose any image vi the media manage popup on any custom fields of type Media.
It only shows folders. Not the files.

**Comment by drmenzelit** [comment] 2021-12-29 11:11
I can confirm the issue: the media field dissapears after saving the article.

@Fedik do you maybe have an idea?

**Comment by brianteeman** [comment] 2021-12-29 11:54
possibly related https://github.com/joomla/joomla-cms/issues/32663

**Comment by Fedik** [comment] 2021-12-29 15:55
Works for me (except preview is incorrect):
```xml
<field name="field-name2" type="subform" label="SUBFORM">
  <form>
    <field name="name" type="media" label="Media"/>
  </form>
</field>
```
![Screenshot_2021-12-29_17-53-11](https://user-images.githubusercontent.com/1568198/147680312-9bbdd7d8-c428-4091-bcde-707a5d73026b.png)

**Comment by drmenzelit** [comment] 2021-12-29 17:36
@Fedik I have tested on a freshly installed 4.0.6-dev version and the media field dissapears after saving the article

**Comment by crystalenka** [comment] 2022-11-15 07:35
Is this still a problem? I cannot reproduce in 4.2

**Comment by Quy** [comment] 2023-03-07 22:59
@regularlabs Please check again as I cannot reproduce the issue in v4.2.8. Thanks.

**Comment by regularlabs** [comment] 2023-03-08 16:44
15 months later. Didn't know this was still open. Seems to work for me.

**Comment by Quy** [comment] 2023-03-08 16:50
Closing as no longer a bug. Thank you for confirming.

**Closed as completed by Quy** 2023-03-08 16:50 UTC
Labels: No Code Attached Yet, Information Required, bug
