### ISSUE TITLE
How to include a reference to a custom class inside a Joomla 3.8 library

### ISSUE THREAD

**Issue by javitineo** [joomla/joomla-cms#18781] opened 2017-11-21 15:35 UTC
### Steps to reproduce the issue
Hi, i had some code inside the authentication  class in Joomla 3.7.3
When i upgrade to joomla 3.8.2 i'm trying to add this code in the same place but it doesnt run:
the code is:
include_once(dirname($_SERVER['DOCUMENT_ROOT']) . DIRECTORY_SEPARATOR .ROOT_PATH."/usuario/TUsuario.php");
$usuario= new TUsuario();
$usuario->.....etc

the error that appear  are "cannot redeclare class",  "Class 'Joomla\CMS\Authentication\TUsuario' not found in ...../libraries/src/Authentication/Authentication.php".
I suppose there is a new way of doing this kind of including, could anybody help me please?.
Thanks

### Expected result
Do custom tasks inside the function authenticate()

### Actual result
error of custom class not found

### System information (as much as possible)
Joomla 3.8.2
Php 5.6
This way of doing the include runs in Joomla 3.7.3

**Comment by javitineo** [comment] 2017-11-21 15:38
[code.txt](https://issues.joomla.org/uploads/1/219331c16f20806f41e081a5d9d0dfd3.txt)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18781">issues.joomla.org/tracker/joomla-cms/18781</a>.</sub>

**Comment by mbabker** [comment] 2017-11-21 15:59
What you're doing is in essence core hacking.  I don't think anyone here is going to give information on how to successfully do that in an update safe way (because there isn't one).

Use the plugin system the way it was designed to add your custom logic, do not core hack the core authentication handler.

Closing, not a core issue.

**Closed as completed by mbabker** 2017-11-21 15:59 UTC
Labels: No Code Attached Yet
