### ISSUE TITLE
[4.0] Saving existing banner fails

### ISSUE THREAD

**Issue by phalouvas** [joomla/joomla-cms#19016] opened 2017-12-08 05:01 UTC
### Steps to reproduce the issue
In Joomla 4.0 open an existing banner. Modify anything (e.g. title) and save. 

### Expected result
Save banner.

### Actual result
You get message:
0 Call to a member function load() on boolean 

### System information (as much as possible)
Joomla 4.0

### Additional comments
The problem is identified in file: administrator\components\com_banners\Table\BannerTable.php
I attach a patch that fixes the issue: 
[BannerTable.txt](https://github.com/joomla/joomla-cms/files/1541443/BannerTable.txt)

**Comment by ghost** [comment] 2017-12-08 06:18
Issue confirmed,<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19016">issues.joomla.org/tracker/joomla-cms/19016</a>.</sub>

**Comment by anuragteapot** [comment] 2017-12-08 06:56
The issue is present.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19016">issues.joomla.org/tracker/joomla-cms/19016</a>.</sub>

**Comment by C-Lodder** [comment] 2017-12-08 10:11
Please update the title to have `[4.0]` at the beginning

**Comment by ghost** [comment] 2017-12-21 12:29
closed as having Pull Request #19119

**Closed as completed** 2017-12-21 12:29 UTC
Labels: No Code Attached Yet
