### ISSUE TITLE
[4] Smart Search stop with message: An Error Has Occurred Category must have a title. 

### ISSUE THREAD

**Issue by Stuartemk** [joomla/joomla-cms#35977] opened 2021-11-06 06:27 UTC
### Steps to reproduce the issue

Since the first version of joomla 4 I have tried to index my site and the same error occurs. I have tried making combinations between raising and lowering the table limit and the batch of processes and the error is always the same. The most frustrating thing is that there are no more details of the error, I already looked in the indexer log and it does not give more details. I already checked my menus, my article categories, the articles, the modules, and everything has the correct categories, I have searched from the joomla backen and from the database, there are no empty categories without names.
Indexing stops at about 75%
It throws me 314 pages of 20 results which in total are 6280 results, and neither raising nor lowering the values of the limit of tables and processing batches THE amount of results does not vary, nor are they more nor less.

### Expected result

Complete 100% indexing

In case of error receive more details in the backend error modal screen, in case of error receive more details in the indexer error log.

### Actual result

Smart Search stop with message: An Error Has Occurred Category must have a title. 

### Additional comments
These are the details of the log

2021-11-06T05:07:16+00:00	ERROR 201.141.24.207	-	Category must have a title.
2021-11-06T05:07:16+00:00	ERROR 201.141.24.207	-	Category must have a title.

**Comment by Hackwar** [comment] 2021-12-26 21:38
The error message is misleading and indeed needs to be fixed. The problem is, that a finder plugin tries to add a taxonomy with an empty title. This could be an author of an article which couldn't be loaded and thus is working with an empty string or something similar.

**Comment by richard67** [comment] 2022-01-20 17:04
Closing as having a pull request. Please test #36759 . Thanks in advance.

**Closed as completed by richard67** 2022-01-20 17:04 UTC
Labels: No Code Attached Yet
