### ISSUE TITLE
Compact list of tagged items -1054 Unknown column 'Array' in 'where clause'

### ISSUE THREAD

**Issue by bellu** [joomla/joomla-cms#19079] opened 2017-12-15 16:38 UTC
### Steps to reproduce the issue
Create a menu item using a "Compact list of tagged items", set a tag and then navigate to the page.

### Expected result
See the list of articles that are tagged with the selected tag.

### Actual result
An SQL error, "1054 Unknown column 'Array' in 'where clause'".

### System information (as much as possible)
PHP version 5.4.27
Database Version 5.5.32 MariaDB
Joomla Version 3.8.3

### Additional comments
I see that the link created is -> index.php?option=com_tags&view=tag&layout=list&id[0]=20 .
If i remove the array, and try to navigate to -> index.php?option=com_tags&view=tag&layout=list&id=20, it works normally.

**Comment by Quy** [comment] 2017-12-15 17:04
Unable to reproduce. It should be an array since more than one tag can be selected.

**Comment by tonypartridge** [comment] 2017-12-18 03:23
@quy it should, but it looks from that url that we are adding an id as array into the url. When the Id should be a comma separated list to have multiples. id[0]= should be id=

**Comment by Quy** [comment] 2017-12-18 04:52
Multiples are not comma separated list as seen here:
`index.php?option=com_tags&view=tag&layout=list&id[0]=2&id[1]=3&id[2]=4&Itemid=474`

Here it is for a single tag:
`index.php?option=com_tags&view=tag&layout=list&id[0]=2`

**Comment by Quy** [comment] 2017-12-23 06:44
@franz-wohlkoenig @brianteeman Can you reproduce? If not, please close. Thanks.

**Comment by ghost** [comment] 2017-12-23 06:47
Can't reproduce but i'm not on MariaDB.

**Comment by mbabker** [comment] 2017-12-23 15:13
> Can't reproduce but i'm not on MariaDB.

Shouldn't need to be.  The error message looks like it would be a PHP "Array to string conversion error" type thing, so should be database platform agnostic.

**Comment by ghost** [comment] 2017-12-23 15:23
@tonypartridge: Can't reproduce. 

Thanks for Info, @mbabker.
### System information
 3.8.4-dev
Multilanguage Site (4 Lang.) & Test English (GB) Sample Data
macOS Sierra, 10.12.6
Firefox 57 (64-bit)
#### MAMP 4.2
- Apache-Server
- PHP 7.0.22
- MySQLi 5.6.35

**Comment by ghost** [comment] 2017-12-24 07:09
closed as unconfirmed Report.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19079">issues.joomla.org/tracker/joomla-cms/19079</a>.</sub>

**Closed as completed by ghost** 2017-12-24 07:09 UTC
Labels: No Code Attached Yet
