### ISSUE TITLE
Deinstallation from NewsFeeds & Banners caused issues in Extension -> Manage -> Database

### ISSUE THREAD

**Issue by BastianWie** [joomla/joomla-cms#8739] opened 2015-12-19 13:25 UTC
#### Steps to reproduce the issue
- Uninstall NewsFeeds & Banners from Joomla 3.4.6
- Visit Extension -> Manage -> Database and you got an error that the database isn´t up to date. The following DBs do have problems:

    Table 'test_newsfeeds' should not have column 'filename'. (From file 3.0.0.sql.)
    Table 'test_newsfeeds' does not have column 'description'. (From file 3.0.0.sql.)
    Table 'test_newsfeeds' does not have column 'version'. (From file 3.0.0.sql.)
    Table 'test_newsfeeds' does not have column 'hits'. (From file 3.0.0.sql.)
    Table 'test_newsfeeds' does not have column 'images'. (From file 3.0.0.sql.)
    Table 'test_banners' does not have column 'created_by'. (From file 3.0.0.sql.)
    Table 'test_banners' does not have column 'created_by_alias'. (From file 3.0.0.sql.)
    Table 'test_banners' does not have column 'modified'. (From file 3.0.0.sql.)
    Table 'test_banners' does not have column 'modified_by'. (From file 3.0.0.sql.)
    Table 'test_banners' does not have column 'version'. (From file 3.0.0.sql.)

Additional to that the following errors will be shown:

Error
Table 'dbtest.test_newsfeeds' doesn't exist SQL=SHOW COLUMNS IN `test_newsfeeds` WHERE Field = 'filename'
Table 'dbtest.test_newsfeeds' doesn't exist SQL=SHOW COLUMNS IN `test_newsfeeds` WHERE field = 'description'
Table 'dbtest.test_newsfeeds' doesn't exist SQL=SHOW COLUMNS IN `test_newsfeeds` WHERE field = 'version'
Table 'dbtest.test_newsfeeds' doesn't exist SQL=SHOW COLUMNS IN `test_newsfeeds` WHERE field = 'hits'
Table 'dbtest.test_newsfeeds' doesn't exist SQL=SHOW COLUMNS IN `test_newsfeeds` WHERE field = 'images'
Table 'dbtest.test_banners' doesn't exist SQL=SHOW COLUMNS IN `test_banners` WHERE field = 'created_by'
Table 'dbtest.test_banners' doesn't exist SQL=SHOW COLUMNS IN `test_banners` WHERE field = 'created_by_alias'
Table 'dbtest.test_banners' doesn't exist SQL=SHOW COLUMNS IN `test_banners` WHERE field = 'modified'
Table 'dbtest.test_banners' doesn't exist SQL=SHOW COLUMNS IN `test_banners` WHERE field = 'modified_by'
Table 'dbtest.test_banners' doesn't exist SQL=SHOW COLUMNS IN `test_banners` WHERE field = 'version'

#### Expected result
The uninstallation from NewsFeeds and Banners shouldn´t produce the issue above.

#### Actual result
See error message above

#### System information (as much as possible)
- Joomla 3.4.6

**Comment by brianteeman** [comment] 2015-12-19 14:06
Closed as a duplicate of #8691<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8739">issues.joomla.org/joomla-cms/8739</a>.</sub>

**Closed by brianteeman** 2015-12-19 14:06 UTC
Labels: No Code Attached Yet
