### ISSUE TITLE
[4.0] Could not open update site #1 "Joomla! Core"

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18712] opened 2017-11-19 17:28 UTC
### Steps to reproduce the issue

Go to Joomla Update in the extensions meu

### Expected result

No errors

### Actual result

![screen shot 2017-11-19 at 17 27 34](https://user-images.githubusercontent.com/400092/32993370-f438a028-cd4e-11e7-9631-0eaa42f4a53c.png)

Update: Could not open update site #1 "Joomla! Core", URL: https://update.joomla.org/core/test/next_major_list.xml

### System information (as much as possible)

http://screenshot.myjoom.la/2e0Q1D0y1q2q

**Comment by zero-24** [comment] 2017-11-19 17:29
@wilsonge ;)

**Comment by MarceloGhelman** [comment] 2018-02-07 17:39
It sometimes happen access issues on my server that cause that error, nothing to do with Joomla.
The problem is the result status: "No updates available" and "You already have the latest Joomla version".
Worst, the Control Panel shows "Joomla is up to date".
The massage should be "Cannot check for Joomla updates".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18712">issues.joomla.org/tracker/joomla-cms/18712</a>.</sub>

**Comment by brianteeman** [comment] 2018-03-25 13:51
@MarceloGhelman your issue is unrelated to this one as this is for the unreleased J4

**Comment by brianteeman** [comment] 2018-03-25 13:54
Closing this here. Its not a core bug just a missing xml file https://github.com/joomla/update.joomla.org/issues/94

**Closed as completed by brianteeman** 2018-03-25 13:54 UTC
Labels: No Code Attached Yet, J4 Issue
