### ISSUE TITLE
"Please select the database type" testing Joomla_3.4.4-rc installation

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/joomla-cms#7797] opened 2015-09-02 09:51 UTC
Hi,

I have just downloaded and tested to install Joomla_3.4.4-rc.

Following the usual path, I am unable to install it, stopped with "Please select the database type".

Database Type * is MySQLi

When you move from Step 2 and Step 3, it is validated OK (installation/model/database, line 114).

However, when you finally click on Step 3/Next, it is checked again, $options->db_type is empty and the installation fails.

### System Information
 
* Database Version 	5.5.44-0ubuntu0.14.04.1
* Database Collation 	latin1_swedish_ci
* PHP Version 	5.5.9-1ubuntu4.11
* Web Server 	Apache/2.4.7 (Ubuntu)
* User Agent 	Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:40.0) Gecko/20100101 Firefox/40.0

**Comment by brianteeman** [comment] 2015-09-02 09:58
Confirmed I get exactly the same
https://www.dropbox.com/s/mle2lpakn1exngf/rc-install.gif

**Comment by Bakual** [comment] 2015-09-02 10:03
@wilsonge Looks like a release blocker

**Comment by AlexRed** [comment] 2015-09-02 10:05
I can confirm the problem

**Comment by Bakual** [comment] 2015-09-02 10:33
Reverting #7381 solves the issue for me.

**Comment by infograf768** [comment] 2015-09-02 10:46
>Reverting #7381 solves the issue for me.

same here.

**Comment by Kubik-Rubik** [comment] 2015-09-02 12:29
Thank you @anibalsanchez for reporting this issue. I will provide a PR with a fix in some minutes.

**Comment by anibalsanchez** [comment] 2015-09-02 12:35
Thank you @Kubik-Rubik for your future PR!

**Comment by Fedik** [comment] 2015-09-02 12:45
please take a look #7799

**Comment by Kubik-Rubik** [comment] 2015-09-02 12:47
Please test provided PR #7799, I will close this issue now.

**Closed by Kubik-Rubik** 2015-09-02 12:47 UTC
Labels: No Code Attached Yet

**Comment by anibalsanchez** [comment] 2015-09-02 13:48
@test OK - Joomla_3.4.4-rc with this patch can be installed
