### ISSUE TITLE
TinyMCE plugin's setting "Valid elements" crash formatting in editor

### ISSUE THREAD

**Issue by xakepok** [joomla/joomla-cms#17927] opened 2017-09-10 18:41 UTC
#### Steps to reproduce the issue

Go "Administrator area" -> plugins -> TinyMCE plugin, and insert any tag (or any text) in field "Valid elements".
Go to editor in any component's settings, where exist Tiny MCE editor.
Edit text in editor and save (or click Initial code button).

#### Expected result

Normal formatting code.

#### Actual result

Formatting in editor is crash.

#### System information (as much as possible)

Joomla 3.7.5.

#### Additional comments

If field "Valid elements" in plugin's settings is empty, plugin works normal.

**Comment by brianteeman** [comment] 2017-09-10 18:52
i cannot replicate this - what are you typing in the field
please post a screenshot so we can see what you mean by "Formatting in editor is crash.~"

**Comment by xakepok** [comment] 2017-09-10 19:01
0) I create my component for Joomla, he's good working.
1) One of any view's component in admin panel have editor field. I wan't add video in my editor.
2) I go TinyMCE settings and add 'iframe' in field "Valid elements".
3) After this actions i back to editor in view, editing this (add bold-style text or add image). It's correctly show in editor.
4) But after click on save button, text in editor show as simple text, without formatting, has no images and strong elements. Just text.

**Comment by brianteeman** [comment] 2017-09-10 19:09
ah i see your problem now. if you enter anything in the "valid elements" field then they are the only valid elements. in your case you want to add iframe to the current valid elements so you should enter it in the Extended Valid Elements field which ADDS anything entered there to the standard list of valid elements

**Comment by xakepok** [comment] 2017-09-10 19:12
It's translation problem (I use russian language) or global problem?

**Comment by brianteeman** [comment] 2017-09-10 19:13
i have no idea what it says in russian but it is correct in english

**Comment by xakepok** [comment] 2017-09-10 19:19
In russian language field's label is bad.
First field is good.
2'th and 3'th field's label is not corrrectly. It's not meaning.
2'th field good label - is "Разрешено использовать только следующие теги"
3'th field - "Кроме запрещённых разрешить следующие теги"
![2017-09-10_22-14-45](https://user-images.githubusercontent.com/17578621/30252133-8380656a-9675-11e7-86f6-ee0c3ceb45af.png)

**Comment by brianteeman** [comment] 2017-09-11 21:55
@infograf768 can you notify the russian translator please

@mbabker we need an easy process for this

**Comment by brianteeman** [comment] 2017-09-13 16:51
Closing as not a bug in the joomla core. Hopefully the translators wil make the correction

**Closed as completed by brianteeman** 2017-09-13 16:51 UTC
Labels: No Code Attached Yet
