### ISSUE TITLE
[4.0] Disabled toolbar action still triggered on click

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#29105] opened 2020-05-15 07:01 UTC
### Steps to reproduce the issue

1. Go to `administrator/index.php?option=com_content&view=articles`
2. Click one of the checkboxes for any published article to select it
3. Click on the `Actions` toolbar button
3. Click `Publish` from the dropdown

### Expected result

Should not do anything

### Actual result

Executes the action and display an error alert

![actions](https://user-images.githubusercontent.com/2019801/82021116-3f4ac100-9682-11ea-82ea-13f1ea2ad25b.gif)

### Additional Notes

`pointer-events: none;` is being set to the button child, however this has no efect as the click event is occuring on the custom element (parent)

**Comment by adj9** [comment] 2020-05-16 11:01
Confirmed the error. 
A warning should be issued<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29105">issues.joomla.org/tracker/joomla-cms/29105</a>.</sub>

**Comment by C-Lodder** [comment] 2020-05-16 12:24
@adj9 A warning _shouldn't_ be issued. If the dropdown item _appears_ to be disabled, the user shouldn't be allowed to click it

**Comment by brianteeman** [comment] 2020-05-18 23:56
This is a very common problem and the only way it can be fixed on a list element is with javascript to remove the href. 

Note that if that is done then you will need to add `aria-disabled="true"`

**Comment by SharkyKZ** [comment] 2020-05-19 07:37
This is done intentionally:

https://github.com/joomla/joomla-cms/blob/2e095fbbae1026a1811ceed686aeff8f00cc4775/build/media_source/com_content/js/admin-articles-workflow-buttons.es6.js#L155-L163

Is it a bad idea?

**Comment by SharkyKZ** [comment] 2020-07-24 07:59
Looks like the issue is no longer relevant. Now all buttons are enabled.

**Closed as completed** 2020-10-21 00:01 UTC
Labels: No Code Attached Yet
