### ISSUE TITLE
Multilanguage menu item association creating issues

### ISSUE THREAD

**Issue by stellainformatica** [joomla/joomla-cms#12026] opened 2016-09-13 08:13 UTC
### Steps to reproduce the issue
Create a multilanguage site, with 2 languages i.e. english (default) and italian
Create an article for each language and associate them.
Create 2 menu items type Articles » Single Article (calling them i.e. "User area en" and "User area it") and connect them to the article created for each language, and associate these menu items.
Create a menu item type Users » Login Form for each language (calling i.e. "Access User Area en" and "Access User Area it") and set the parameter Menu Item Login Redirect to the menu item created before.

### Expected result
When  a user logs in clicking on the "Access User Area en" menu item, he should be redirected to the "User area en" page.
The same for the other language.

### Actual result
The user that logs in with "Access User Area en" is redirected go to the correct page "User area en"
The user that logs in with "Access User Area it" is redirected to the "User area en" page (default language), not "User area it".

### System information (as much as possible)
Joomla 3.6.2

### Additional comments
The behaviour is the same with more languages, all redirects to the default language.
If you don't associate the menu items "User area en" and "User area it", it works fine, so may be it's a bug in associations.

**Comment by infograf768** [comment] 2016-09-13 08:56
Confirmed.
Same issue if using the login module(s).

**Comment by infograf768** [comment] 2016-09-13 09:02
Ok, found out:

This behaviour is normal IF the parameter Automatic Language Change is set to Yes in the languagefilter plugin.
In this case, when set to Yes, and the items linked to are associated, login redirect will display the associated item in the default user language.

Not a bug.

**Comment by zero-24** [comment] 2016-09-14 16:31
So we can close here @infograf768 ?

**Comment by infograf768** [comment] 2016-09-14 18:17
i would, yep.

**Comment by zero-24** [comment] 2016-09-14 20:02
Closing as expected behavior. Thanks

**Closed by zero-24** 2016-09-14 20:02 UTC
Labels: No Code Attached Yet
