### ISSUE TITLE
[4.0] Drag n Drop Images in TinyMCE kills site

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#27477] opened 2020-01-11 13:25 UTC
Well not exactly kills it but it will do eventually

In Joomla 3 a drag and drop image plugin was added so that you could add images to your content more easily and the images would be saved automatically in a specified folder on your server.

In Joomla 4 that isnt working at all

Instead the native tinymce drag and drop image is used. This is a problem because this saves the image as a base64 blob in the database. Obviously this is not desirable as a user uploading a large image will see it take a long time to save the article and very quickly the database will get huge. It is also really slow to render an image this way.

**Comment by richard67** [comment] 2020-01-11 14:00
@brianteeman Do you think this is a release blocker? To me it seems it could be one.

**Comment by jwaisner** [comment] 2020-01-11 17:45
I would say this is a release blocker. We definitely don't want to impact DB performance as well as size if it is being loaded this way.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27477">issues.joomla.org/tracker/joomla-cms/27477</a>.</sub>

**Comment by HLeithner** [comment] 2020-01-11 17:46
@bembelimen is this a regression of the tinymce 4.0 update? Can you have a look at this?

**Comment by infograf768** [comment] 2020-01-12 08:00
Setting as release blocker

**Comment by brianteeman** [comment] 2020-01-12 16:05
Setting paste_data_images to false will prevent this happening but it still wont fix the non working joomla drag and drop plugin

**Comment by bembelimen** [comment] 2020-02-11 22:26
There are several reasons for this broken behavior:
- Plugin is called "jdragndrop" (https://github.com/joomla/joomla-cms/blob/4.0-dev/plugins/editors/tinymce/tinymce.php#L508) but the real name is "jdragdrop" (https://github.com/joomla/joomla-cms/blob/4.0-dev/build/media_source/plg_editors_tinymce/js/plugins/dragdrop/plugin.es6.js#L2)
- TinyMCE has an own uploader, which has to be overwritten (https://github.com/joomla/joomla-cms/blob/4.0-dev/plugins/editors/tinymce/tinymce.php#L531-L533 + https://www.tiny.cloud/docs/configure/file-image-upload/) or probably we don't need such a plugin.
- com_media changes its API completly in J! 4 (https://github.com/joomla/joomla-cms/blob/4.0-dev/plugins/editors/tinymce/tinymce.php#L513), so the call is wrong, also the return value.

**Comment by Fedik** [comment] 2020-02-15 11:40
okau, I have tried to do something, but I "hit a wall"

does [com_media API](https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_media/src/Controller/ApiController.php) designed to be used by other extensions or? 
if so, can someone explain how to, please

I have spend a couple hours for reverse engendering of this "thing", and only got much of negative feedback :smile: 
It turns out, more easy to write an own upload handler (server side) than use com_media API.

I managed to make upload work, but in response I have path `path: "local-0:/blabla-image.jpg"`, and it not possible to add in to TinyMCE as is, because it not a real path.

Any tips are welcome

**Comment by Fedik** [comment] 2020-02-15 11:47
ah, okay, I see

https://github.com/joomla/joomla-cms/blob/24265b1d085494beb1dafb3e6be32e3d1d50a16b/administrator/components/com_media/src/Controller/ApiController.php#L26-L29

**Comment by Fedik** [comment] 2020-02-15 12:47
To be able to fix this issue someone need to write an upload handler. 
Or we just copy old one? https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_media/controllers/file.json.php :smiley:

**Comment by brianteeman** [comment] 2020-02-15 12:58
Seriously - the all singing all dancing new media manager doesnt have an upload handler

rm -rf /com_media

npm i upploadjs.org

https://uppload.js.org

**Comment by Fedik** [comment] 2020-02-15 13:11
> Seriously - the all singing all dancing new media manager doesnt have an upload handler

I had similar thoughts :smile:

**Comment by dgrammatiko** [comment] 2020-05-03 22:08
I'll post a patch tomorrow

**Comment by dgrammatiko** [comment] 2020-05-06 07:37
PR: https://github.com/joomla/joomla-cms/pull/28928

**Comment by richard67** [comment] 2020-05-06 07:44
@dgrammatiko Shall I close this issue because there is PR #28928 ?

**Comment by dgrammatiko** [comment] 2020-05-06 07:51
Yes😉

**Comment by richard67** [comment] 2020-05-06 07:57
Closing as having PR, see above.

**Closed as completed by richard67** 2020-05-06 07:57 UTC
Labels: No Code Attached Yet
