### ISSUE TITLE
Joomla Smart Search results inconsistent with language tag 

### ISSUE THREAD

**Issue by nozaro33** [joomla/joomla-cms#34519] opened 2021-06-15 03:35 UTC
### Steps to reproduce the issue

I'm not sure if this issue is specified toward Chinese, but Joomla Smart Search produces different results if I use the english language tag at end of URL, see example below: 

https://zerowastetraveldiary.com/finder?q=%E9%9B%A8%E6%B0%B4%E5%9B%9E%E6%94%B6&l=en
https://zerowastetraveldiary.com/finder?q=%E9%9B%A8%E6%B0%B4%E5%9B%9E%E6%94%B6

https://zerowastetraveldiary.com/finder?q=%E7%92%B0%E4%BF%9D&l=en
https://zerowastetraveldiary.com/finder?q=%E7%92%B0%E4%BF%9D

I encountered a similar issue with J4, but was ignored as Chinese wasn't an available language at that time 

### Expected result

Results should be the same

### Actual result

Results are different

### System information (as much as possible)

Joomla 3.9.27
MYSQL  5.6.39
PHP 7.4.2

### Additional comments

Maybe this is by design? if so than please close this issue!

**Comment by richard67** [comment] 2021-06-15 05:58
Ping @Hackwar

**Comment by richard67** [comment] 2021-06-15 07:04
It can be that it's intended behaviour because different languages might use different stemmers (if some). Waiting for @Hackwar to confirm or correct me.

**Comment by brianteeman** [comment] 2021-06-15 07:12
Please go to the component options and disable the stemmer and see if you still get the same incorrect results

![image](https://user-images.githubusercontent.com/1296369/122008830-5db54b80-cdb1-11eb-9284-355da2a8bffa.png)

**Comment by nozaro33** [comment] 2021-06-15 07:33
Hi @brianteeman  thanks for the tip, after disabling stemmer it still produces the same incorrect results.

**Comment by brianteeman** [comment] 2021-06-15 08:00
I didnt think it would make a difference but its good to confirm that it it is nothing to do with a stemmer

**Comment by Hackwar** [comment] 2022-01-17 16:06
Simply said, this is by design, yes. Smart Search searches the index that is either marked as '*' (no specific language given) or the currently used language. If your content is set to be english and the site is using chinese, then it wont find any content that is specifically marked as english. Thus this can be closed as expected behavior.

**Comment by drmenzelit** [comment] 2022-01-17 16:12
Closing this as it is expected behavior

**Closed as completed by drmenzelit** 2022-01-17 16:12 UTC
Labels: No Code Attached Yet
