### ISSUE TITLE
?Itemid=101 on user contact form page URL

### ISSUE THREAD

**Issue by ketihar** [joomla/joomla-cms#12731] opened 2016-11-03 13:50 UTC
### Steps to reproduce the issue
Users->Manage->New            Create new user (eg user1)
Components->Contacts->        Create contact for the new user
Content->Articles->Options    Check "Show Author" and "Link Author"
Create article with this user
Go to frontend, on user1 article and click on Author Link "user1"
Now see the contact form url

### Expected result
Link without ?Itemid=101
index.php/component/contact/contact/2

### Actual result
You will see index.php/component/contact/contact/2-user1?Itemid=101

### System information (as much as possible)
Database Version 5.7.14
Database Collation utf8_general_ci
Database Connection Collation utf8mb4_general_ci
PHP Version 7.0.10
Web Server Apache/2.4.23 (Win64) PHP/7.0.10
WebServer to PHP Interface apache2handler
Joomla! Version Joomla! 3.7.0-dev Development [ Noether ] 18-October-2016 16:37 GMT
Joomla! Platform Version Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

**Comment by SharkyKZ** [comment] 2016-11-03 13:58
Duplicate of #12603. Test #12629 please.

**Comment by ketihar** [comment] 2016-11-03 14:54
I test  #12629. Now i get:
component/contact/contact/user3?Itemid=101

The  ?Itemid=101  is still there

**Comment by infograf768** [comment] 2016-11-04 09:18
@ketihar
To test correctly #12629 you have to create a menu item of type contact category for the category of the contact (which can be hidden).

**Comment by ketihar** [comment] 2016-11-04 10:29
Sorry for missing that.. I test #12629 successfully.

**Comment by franz-wohlkoenig** [comment] 2017-02-01 09:19
@ketihar so this Issue can be closed?

**Closed** 2017-02-03 18:32 UTC
Labels: No Code Attached Yet

**Comment by Meavin** [comment] 2018-04-14 14:49
Dear Ketihar,

Could you please let me know the steps little brief on how to romove "itemid" from author liked contact from in joomla3.8? Please help me with the solution If possibly little soon.

Thank you in advance!
