### ISSUE TITLE
Can't login after setting lifetime to 15000000

### ISSUE THREAD

**Issue by ThomasFinnern** [joomla/joomla-cms#13933] opened 2017-02-05 13:25 UTC
### Steps to reproduce the issue
Backend: Goto System -> Global Configuration -> System -> Session Settings -> Session lifetime
Logout / login

### Expected result
Login works

### Actual result
Login stays on same form without error message

### System information (as much as possible)
PHP Version 	7.1.1 
Joomla! Version 	Joomla! 3.7.0-beta2 dev [ Amani ] 2-February-2017 18:53 GMT 

### Additional comments
Recover: Change value in configuration.php to example 15000

maybe value to big for ? int ?

**Comment by bertmert** [comment] 2017-02-05 19:44
Addition:
Sometimes I can login but when I try to navigate in administration then Joomla kicks me out

**Comment by laoneo** [comment] 2017-02-06 08:56
Same happens to me.

**Comment by bertmert** [comment] 2017-02-06 18:57
The strange thing is that I can enter a lifetime of `52560000` and all works fine but not with `15000000`.

**Comment by ThomasFinnern** [comment] 2017-02-07 09:04
Probably the input is somewhere cut to a smaller integer. So if the value get big enough on the lower int the session time get usable again

**Comment by PhilETaylor** [comment] 2017-02-11 16:07
If you are setting your lifetime to stupid values then what do you expect. 

No reasonable well written web app needs a lifetime of 15000000!!!

If you want to persist a user session for a long time then there are better ways of doing it! 

PHP 7.1 has made some major session changes, maybe this is a bug in PHP 7.1 - its surely not a Joomla bug...

**Comment by bertmert** [comment] 2017-02-11 17:48
In field lifetime it's possible to enter high values. This shoudn't be possible then. It's not obvious for users that they will be locked out from administration if they set some values.

> its surely not a Joomla bug, maybe this is a bug in PHP 7.1...

Same strange problem with PHP 5.6
`52.560.000` works (~100 years).
`15.000.000` not (~25 years).

**Comment by PhilETaylor** [comment] 2017-02-11 17:56
Quite frankly Joomla cannot be held responsible for idiots setting a 25 year session lifetime!

**Comment by PhilETaylor** [comment] 2017-02-11 18:28
Ok I can replicate this and have found the root cause being the `time` column in the #__session table being a VARCHAR(14) ... fml... 

After changing this to a int(11) with a session lifetime in configuration.php as 15000000 the session issue goes away. 

After changing this to a bigint(20) with a session lifetime in configuration.php as 15000000 the session issue goes away. 

I have only tested MySQL database storage - I have no mssql/etc setups. 

Please test. Then we can ask someone like @mbabker if this even needs addressing, and if so which column type is best (for MySQL)

**Comment by ThomasFinnern** [comment] 2017-02-12 20:29
Sorry for inputting  stupid values. I was not interested in the dimension, I just wanted to stay longer online and slightly remember value 15000. As i was not sure i remember it right i thought just add some zeros than it will stay longer ...
May be a sanitize of the input may be the right solution
Thanks for your patience and effort

**Comment by PhilETaylor** [comment] 2017-03-04 20:56
> Please test. Then we can ask someone like @mbabker if this even needs addressing, and if so which column type is best (for MySQL)

**Comment by ThomasFinnern** [comment] 2017-03-04 21:02
We may leave the database as it is. We just have to check if the value is to big. Then use biggest possible value.
Where would be the place to check the input ?

**Comment by tonypartridge** [comment] 2017-03-20 09:57
What about just setting max value of: 1500000 in the lifetime field. Quick simple, and no one should need anything bigger than this?

/administrator/components/com_config/model/form/application.xml

**Comment by brianteeman** [comment] 2017-03-20 10:12
Do you know what the maximum is? Won't it be dependant on the server?


On 20 Mar 2017 9:57 a.m., "Tony Partridge" <notifications@github.com> wrote:

What about just setting max value of: 1500000 in the lifetime field. Quick
simple, and no one should need anything bigger than this?

/administrator/components/com_config/model/form/application.xml

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/joomla/joomla-cms/issues/13933#issuecomment-287715777>,
or mute the thread

**Comment by tonypartridge** [comment] 2017-03-20 10:19
@brianteeman of course I don't. I am just proposing to set a Joomla! maximum, what we think as a CMS is right. We suggest 15 minutes. You shouldn't need a session to be bigger than 60minutes in reality. 

I am just suggesting we look at setting a max limit, or hey just change the column.

**Comment by ThomasFinnern** [comment] 2017-03-20 16:45
@PhilETaylor commented on Feb 11 :  root cause being the time column in the #__session table being a VARCHAR(14) ...
2^14 = 16384 is the max the variable can hold. I don't know where the user input should be checked for a too big value to suggest a proper solution.
When the column was designed the designer did think about a useful value probably.  If you have a local developer website you don't want to login on the next day. In a book was recommended to set this value to 1500. 
My recommendation is to cut every value above 16384 and set it to 16383. This solution has no side effects as values below 16384 behave like before. Thats why i recommend it

**Comment by tonypartridge** [comment] 2017-03-20 16:46
@ThomasFinnern

Great so I suggest we set it to 16383 as a max value on input. Which we can do with a single file change

**Comment by franz-wohlkoenig** [comment] 2017-04-05 11:51
@tonypartridge can you make a PR?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13933">issues.joomla.org/tracker/joomla-cms/13933</a>.</sub>

**Comment by brianteeman** [comment] 2017-08-18 21:14
Closed as we have a PR #17609

**Closed by brianteeman** 2017-08-18 21:14 UTC
Labels: No Code Attached Yet

**Comment by csthomas** [comment] 2018-06-26 12:25
Maybe there is someone who can test the session improvements at #19708 for mysql. After database column `time` will be changed to an integer, joomla should work better.
