### ISSUE TITLE
Joomla3.4 installer defaults to English (Australian)

### ISSUE THREAD

**Issue by Bodge-IT** [joomla/joomla-cms#6387] opened 2015-03-11 07:50 UTC
#### Steps to reproduce the issue
Run installer
Check language selection in configuration page 1

#### Expected result
English(United Kingdom)

#### Actual result
English(Australia)

#### System information (as much as possible)
Clean install on WAMP server
Windows 7
Using Akeeba Kickstart 3.5.2 to load installer

**Comment by brianteeman** [comment] 2015-03-11 09:44
What language is your browser set to?

**Comment by Bodge-IT** [comment] 2015-03-11 10:05
Hi Brian,
[cid:image001.png@01D05BE3.37FBB150]

Browser is Firefox 36.01

Cheers
Gary

**Comment by brianteeman** [comment] 2015-03-11 10:08
sorry that image didnt show<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6387">issues.joomla.org/joomla-cms/6387</a>.</sub>

**Comment by Bodge-IT** [comment] 2015-03-11 10:09
Hi Brian,
Just tested on Chrome and that works OK…English(UK) as expected…

Let me dig some more
Cheers
Gary

**Comment by brianteeman** [comment] 2015-03-11 10:12
I just tested firefox 36.1 on OSX
By default firefox is en-US
Run installer and the installer chose en-US
Changed the browser default language to en-GB
Run installer and the installer chose en-GB
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6387">issues.joomla.org/joomla-cms/6387</a>.</sub>

**Comment by Bodge-IT** [comment] 2015-03-11 10:13
Think this is down to me…

My language setting in Firefox was en [en].

I assumed that was English but when I checked in the list there is also an en [en-gb]

Now when I run the installer, it works as expected.

Sheepish.
Gary

**Comment by infograf768** [comment] 2015-03-11 10:13
In firefox, if browser preferred language is set to English [en] , I guess Joomla will pick the first alpha-ordered English available language which is en-AU.

To get for sure en-GB (English UK) the preferred language has to be en-GB.

![screen shot 2015-03-11 at 11 12 08](https://cloud.githubusercontent.com/assets/869724/6594236/a1efce80-c7df-11e4-948c-e80873548b68.png)

**Comment by brianteeman** [comment] 2015-03-11 10:13
When firefox is set to the default language of just (en) then the joomla installer will chose the first english language on the list which is en-AU

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6387">issues.joomla.org/joomla-cms/6387</a>.</sub>

**Comment by brianteeman** [comment] 2015-03-11 10:19
Closing as not a bug as Firefox is doing exactly what would be expected of it<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6387">issues.joomla.org/joomla-cms/6387</a>.</sub>

**Closed** 2015-03-11 10:19 UTC
