### ISSUE TITLE
Searchbox out of container section

### ISSUE THREAD

**Issue by kalpeshtailored** [joomla/joomla-cms#11070] opened 2016-07-11 11:04 UTC
#### Steps to reproduce the issue
» Go to the front-end with latest joomlacms
» Click on Joomla link in Popular Tags module 
» View on small device screen

#### Expected result
» Search box must be responsive with all resolution

#### Actual result
» Search box coming outside of the container

![screen shot 2016-07-11 at 06 00 18](https://issues.joomla.org/uploads/1/6aecd5454b266d1c7fdcc79f2d806717.png)

**Comment by killoltailored** [comment] 2016-07-11 11:06
Tested successfully with Joomla Version: Joomla! 3.6.0-rc
Issue found in all responsive view<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11070">issues.joomla.org/joomla-cms/11070</a>.</sub>

**Comment by RonakParmar** [comment] 2016-07-11 11:12
I have checked in Mozilla FireFox 47.0.1 with 320×480 screen and able to reproduce this issue.
Joomla Version: Joomla! 3.6.0-rc 
I have also checked in Chrome Version 49.0.2623.110 (64-bit) in Nexus 5 emulator having issue, in Nexus 4 and Nexus 7 works fine.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11070">issues.joomla.org/joomla-cms/11070</a>.</sub>

**Comment by hardiktailored** [comment] 2016-07-12 11:41
I found that issue too clicking popular tags articles.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11070">issues.joomla.org/joomla-cms/11070</a>.</sub>

**Comment by NeerajTailored** [comment] 2016-07-15 11:25
I have tested it successfully search box issue in responsive view.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11070">issues.joomla.org/joomla-cms/11070</a>.</sub>

**Comment by gautamtailored** [comment] 2016-07-19 04:58
I have also been facing this issue in portrait device's width in between 320px - 365px.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11070">issues.joomla.org/joomla-cms/11070</a>.</sub>

**Comment by franz-wohlkoenig** [comment] 2017-01-30 16:59
Issue exists also on 3.7-staging.

**Comment by rvbgnu** [comment] 2017-06-03 16:00
Hi @kalpeshtailored , is the issue with the `search box` ? Because it seems to me that it more on the filter field `Enter part of the Title`. Then it is an issue with the protostar template.

**Comment by franz-wohlkoenig** [comment] 2017-06-03 16:02
set Status on "Information Required".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11070">issues.joomla.org/tracker/joomla-cms/11070</a>.</sub>

**Comment by rvbgnu** [comment] 2017-06-11 22:30
Please see and test PR with a fix #16627<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11070">issues.joomla.org/tracker/joomla-cms/11070</a>.</sub>

**Closed** 2017-06-11 22:32 UTC
Labels: No Code Attached Yet
