### ISSUE TITLE
[4.0] Language packs not installed during install

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#28735] opened 2020-04-20 16:50 UTC
### Steps to reproduce the issue

install j4.
during install choose "english us" instead of "english uk"

### Expected result
Us language pack installed, uk NOT

### Actual result
only UK installed

### System information (as much as possible)

current 4.0-dev

**Comment by richard67** [comment] 2020-04-20 16:53
@N6REJ Sorry to say, but this is expected behavior right now. You have to do the additional step at the end of the installation and install the en-US language. But this will not work for J4 yet. There is already an open issue for that, will search it.

**Comment by richard67** [comment] 2020-04-20 16:56
@N6REJ Dont find it now. @infograf768 Could you confirm if my comment above is right? And do you know if we have some issue for that, installation of the language previously selected for the installation at the end of installation and setting it to default?

**Comment by Bakual** [comment] 2020-04-20 17:05
Afaik, the only language available for J4 are french and persian (I think). en-US isn't one of them and thus I expect it to fail anyway.

**Comment by richard67** [comment] 2020-04-20 17:07
German, too, is available. But not en-US.

**Comment by richard67** [comment] 2020-04-20 17:09
Anyway, the assumption that the language selected for running the installation determines which language(s) are installed and used later is wrong.

**Comment by N6REJ** [comment] 2020-04-20 17:23
> Anyway, the assumption that the language selected for running the installation determines which language(s) are installed and used later is wrong.

thats counter-intuitive.

**Comment by richard67** [comment] 2020-04-20 17:28
Maybe, but that's how it works with a regular installation package, as far as I remember also for J3. It might be different when using a localized package.

And I've seen it often with setup programs on Windows that you can select the language for the setup process and the one later to be installed independently, so that seems at least not to be completely uncommon.

**Comment by N6REJ** [comment] 2020-04-20 17:29
so, do we want to close it as "not a bug" ?

**Comment by richard67** [comment] 2020-04-20 17:46
We can wait a bit for feedback.

**Comment by ChristineWk** [comment] 2020-04-20 17:50
Found this here: https://issues.joomla.org/tracker/joomla-cms/24481<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28735">issues.joomla.org/tracker/joomla-cms/28735</a>.</sub>

**Comment by richard67** [comment] 2020-04-20 18:12
@ChristineWk Yeah, you found it. That was the one I had in mind.

**Comment by richard67** [comment] 2020-04-20 18:14
Closing as partly no bug (we simply don't have an en-US language pack working for J4 yet) and partly a duplicate of #24481 .<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28735">issues.joomla.org/tracker/joomla-cms/28735</a>.</sub>

**Closed as completed by richard67** 2020-04-20 18:14 UTC
Labels: No Code Attached Yet

**Comment by brianteeman** [comment] 2020-04-20 20:39
Its always been a bug. I keep raising this but no one is interested in it except english speakers like me and george who it doesnt effect

**Comment by richard67** [comment] 2020-04-20 20:56
@brianteeman So do you suggest to re-open this one here? Or is it sufficient to have #24481 open?

**Comment by richard67** [comment] 2020-04-20 21:01
At least the title should be changed when re-opening this, because it's not a but that currently the en-US language pack isn't ready for J4.

**Comment by gerryfrancis** [comment] 2020-04-21 06:23
From the view of an average Joomla! user: I was not aware that en-US is not included, although I do not need it anyway. But I recommend to integrate it, as the U.S. are probably the biggest market for Joomla!, and the Internet was invented there, too. Some beginners in the U.S. maybe do not even know that they are using the "wrong" language for their sites.

**Comment by richard67** [comment] 2020-04-21 06:35
@gerryfrancis We are talking about Joomla 4 here. It is work in progress on the way to beta, and for being able to test multilanguage aspects we are able to use some language packs which are for Joomla 3. The infrastructure for Joomla 4 language packs is currently being built up. So the current status is an intermediate solution, and as such it should be discussed, and not as if it was the final status of Joomla 4.

**Comment by gerryfrancis** [comment] 2020-04-21 06:47
@richard67 Oops, sorry about that, I have missed the [4.0] label on this one. ;)

**Comment by infograf768** [comment] 2020-04-21 07:06
Folks, it is NOT a bug, whatever some says. 
It just was never implemented when installing languages packs directly from specific managers in administration and J installation.
Therefore you can call that an oversight or a missing feature but certainly not a bug.

Indeed the ideal would be to make sure, **if a pack corresponding to the installation language is available, and is not already included in the distro,** to install it when installing Joomla. 

Also, the ideal would be:
1. If the user does not chose to install other languages, to automatically set that pack as default admin and site language.
2. If the user chooses to install other languages, to keep proposing what we have now, i.e. choosing the admin and site language among installed packs, possibly highlighting the one corresponding to the installation language.

I question though adding en-US in core. For historical reasons (from Mambo times), en-GB has always been the default core language and US imperialism is not accepted here 😄 , (British imperialism being a thing of the past 😸 ), biggest market or not...

One could say that it should be replaced by something called International English, but there is no country code and nor common vocabulary independent of en-GB or en-US and en-AU, etc. for Intl English.

If someone is interested to implement this new functionality in Joomla 4, code is welcomed.

**Comment by astridx** [comment] 2020-04-22 05:41
> @infograf768 Also, the ideal would be:
If the user does not chose to install other languages, to automatically set that pack as default admin and site language.


I would not do something automatically.  I would ask him.
 
What do you think ?

**Comment by infograf768** [comment] 2020-04-22 05:43
> I would not do something automatically. I would ask him.

Why not. I am always in favor of user decision.

**Comment by richard67** [comment] 2020-04-22 05:44
Hmm, for the case that only one language is installed, there is no need to ask. And it needs a default language for admin and one for site also in this case. So for me it is ok like it is descibed above.

**Comment by infograf768** [comment] 2020-04-22 05:58
BTW @astridx 
we have a bug when installing languages and going back to the list, then not installing another language.

![buginstalllang](https://user-images.githubusercontent.com/869724/79945713-b8356f00-846e-11ea-8631-68bd835d4074.gif)

**Comment by infograf768** [comment] 2020-04-22 06:11
@astridx 
Also, if you volunteer to code installing a language pack corresponding to the installation language, I suggest you add French to the installation languages in 4.0 as we can install French in J4 from the repo.
Although it is the 3.x version, here is a zip which is enough to test such code.
[fr-FR.zip](https://github.com/joomla/joomla-cms/files/4514099/fr-FR.zip)

**Comment by astridx** [comment] 2020-04-22 06:32
> @richard67 Hmm, for the case that only one language is installed, there is no need to ask. And it needs a default language for admin and one for site also in this case. So for me it is ok like it is descibed above.

I am not sure if I understand everything correct. 

It could be, that a German make the installation for a French Customer. In this case he maybe make the installation in German, but he do not like to install German for the Website.
That is why I would ask.

**Comment by richard67** [comment] 2020-04-22 06:42
Ah, ok, then I misunderstood. I thought you meant asking for the default languages at the end. This would not be necessary if only one language is installed, that's what I meant.

But your scenario is that only one language shall be installed, but not the one which was the installation running with. That needs of course a way to ask the user if the installation language shall be installed or not.
