### ISSUE TITLE
No feedback when database password is too short

### ISSUE THREAD

**Issue by yolknet** [joomla/joomla-cms#42479] opened 2023-12-06 20:19 UTC
In the third step of a new Joomla 5(.0.1) installation you can enter database credentials. It looks like you can enter any password of any length. Untill the next screen. Apparantly the database password should have been at least 12 characters. 

![step-2](https://github.com/joomla/joomla-cms/assets/10888068/10b46ae8-b33e-4bb3-922e-4e1887ca3ebf)

It would be more logic when this check happens where I enter the password. And you can't continue the installation untill you have a database password of 12 characters

**Comment by Quy** [comment] 2023-12-06 21:29
Closing as duplicate of #34873. Thanks for the report.

**Closed as completed by Quy** 2023-12-06 21:29 UTC
Labels: No Code Attached Yet
