### ISSUE TITLE
[4.0] Tooltip doesn't support positioning

### ISSUE THREAD

**Issue by SharkyKZ** [joomla/joomla-cms#28246] opened 2020-03-06 07:59 UTC
### Steps to reproduce the issue

Go to any list view with filter in backend.
Hover over search input.

### Expected result

Tooltip is positioned properly.

### Actual result

Tooltip is cut off:

![Screenshot_2020-03-06 Articles Featured - Joomla - Administration](https://user-images.githubusercontent.com/7325021/76063744-01019900-5f91-11ea-93b5-dc14dd515eb0.png)

**Comment by brianteeman** [comment] 2020-03-06 08:07
It's a zindex issue on the header

**Comment by SharkyKZ** [comment] 2020-03-06 08:16
No, that's not the issue. I intentionally scrolled down before making the screenshot to showcase that tooltip falls out of viewport. Bootstrap tooltips/popovers don't have this issue.

**Comment by brianteeman** [comment] 2020-03-06 08:56
Whatever is the cause it used to work correctly. it is such an obvious issue it would never habe been merged like this. So there is a change somewhere since this was merged

**Comment by SharkyKZ** [comment] 2020-03-06 09:12
No, it was always like this. These tooltips can't position themselves based on available space. Not sure if this can be done with CSS alone. I just want to point out that we'll start running into this issue more often if the intention is to replace BS tooltips with these.

**Comment by SharkyKZ** [comment] 2020-03-06 09:13
Also, a more specific selector should be used. Have you seen https://github.com/joomla/joomla-cms/pull/25161#issuecomment-500624356?

**Comment by brianteeman** [comment] 2020-03-06 10:05
As can be seen at the time it was committed in alpha 10 it happily sat on top of the header which it will not do now as it goes behind the header which is a bigger issue that it not being in the viewport

![image](https://user-images.githubusercontent.com/1296369/76073531-a4eb4480-5f91-11ea-83f2-1bc3e4c5fb61.png)

**Comment by C-Lodder** [comment] 2020-03-06 10:45
Brian, try scrolling down a little bit more so that the search input is inline with the top of the viewport.
If I remember the code for this, it's just basic CSS. There's no JS involved, so it won't change direction based on available space. BS tooltips (popperJs) do this but I don't think core uses them anymore

**Comment by brianteeman** [comment] 2020-03-06 10:48
yes it is just basic css - on purpose

Personally I dont care about the viewport - you can always scroll

What I do care about though is that a recent change has resulted in the info being hidden permanently

![image](https://user-images.githubusercontent.com/1296369/76077125-09110700-5f98-11ea-8dfb-e3f16a4516d7.png)

**Comment by C-Lodder** [comment] 2020-03-06 11:03
Without actually firing up the page, I can't actually see any z-index issues based on looking at the SCSS. The tooltip has a higher z-indez than the header.

**Comment by brianteeman** [comment] 2020-03-06 12:35
While I wrote z-index that might not be the problem but it was easy to use as a description of the problem

**Comment by brianteeman** [comment] 2020-03-07 14:06
Resolved with #28258

**Comment by SharkyKZ** [comment] 2020-03-07 14:29
That is completely unrelated. This issue is not resolved.

**Closed as completed** 2021-03-25 17:43 UTC
Labels: No Code Attached Yet
