### ISSUE TITLE
Error 500 when Facebook link is used

### ISSUE THREAD

**Issue by starterfirm** [joomla/joomla-cms#41010] opened 2023-06-22 11:17 UTC
### Steps to reproduce the issue
Take Joomla 4 page
Post it on Facebook
Click link

Example:
https://www.szablon.starterfirm.eu/

### Expected result
Display posted page
https://www.szablon.starterfirm.eu/?fbclid=IwAR2rmIpdPXkjWM3xRBSOXXItQbbC1BYJ2BvwDfqV7oZZuggyz0DEO6Zu-mo

### Actual result
Server 500 error

### System information (as much as possible)
Joomla 4.3.2
PHP 8.2.5
YooTHEME 4.0.7

### Additional comments
Disabling / removing htaccess file doesn't change anything.

**Comment by brianteeman** [comment] 2023-06-22 11:55
please use the forums for support

**Comment by toivo** [comment] 2023-06-22 12:38
The following forum topic discussed the issue and recommended it to be reported here: [Error 500 when Facebook link is used](https://forum.joomla.org/viewtopic.php?f=814&t=998394) 

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41010">issues.joomla.org/tracker/joomla-cms/41010</a>.</sub>

**Comment by starterfirm** [comment] 2023-06-22 12:52
Yes, I'm aware of that topic. I've provided the solution :)

But I believe this is something affecting all Joomla 4 sites's URLs being posted on the biggest social media platform in the world. Shouldn't it be unnecessary to tweak htaccess file on clean Joomla installation, to be able to provide working link to a website?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41010">issues.joomla.org/tracker/joomla-cms/41010</a>.</sub>

**Comment by brianteeman** [comment] 2023-06-22 13:25
it is not all joomla 4 web sites. this is one of mine https://brianstest.site/trips?fbclid=IwAR32mAst_bz65pViQhxTd48VDtPlG8p58Z_JY9RlLJhtteI769UgR47oC3k

**Comment by brianteeman** [comment] 2023-06-22 13:43
The problem is nothing to do with Joomla
The problenm is because you are using lightspeed as a web server and the lightspeed cache on the server is not configured correctly. Probably something to do with the drop query string configuration

**Comment by Fedik** [comment] 2023-06-22 16:54
I am closing this because it is not a core issue, but something with server/site setup.

**Closed as completed by Fedik** 2023-06-22 16:54 UTC
Labels: No Code Attached Yet
