### ISSUE TITLE
Can't Choose Menu Item Type After Update

### ISSUE THREAD

**Issue by thedesignduck** [joomla/joomla-cms#7322] opened 2015-07-02 17:46 UTC
#### Steps to reproduce the issue
Menu Manager > New Menu Item > (Menu Item Type) SELECT

#### Expected result
The pop up window should load to choose the type of menu item. 

#### Actual result
The pop up flickers, but doesn't stay open.

#### Additional comments
Just updated to 3.4.3 - it worked this morning, prior to update. I cleared cache in joomla and on browser. Tried it in IE, Firefox and Chrome. All the same results. Even on my Android phone.

**Comment by zero-24** [comment] 2015-07-02 20:21
working good to me using chrome on 3.4.3. can you try to check if you have Javascript errors? maybe clear the cache again?

**Comment by waader** [comment] 2015-07-02 20:33
works for me using firefox and ie11 on 3.4.3.

**Comment by henisa** [comment] 2015-07-03 08:11
Got the same problems, Even when I duplicate a menu item I can's select an article. Pop up shows up and closes automatically. Only if I start the debug record mode of Firefox I can select the options.....?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7322">issues.joomla.org/joomla-cms/7322</a>.</sub>

**Comment by brianteeman** [comment] 2015-07-03 08:13
Does this only happen in Firefox? Which exact version of firefox and
operating system

On 3 July 2015 at 09:11, henisa <notifications@github.com> wrote:

> Got the same problems, Even when I duplicate a menu item I can's select an
> article. Pop up shows up and closes automatically. Only if I start the
> debug record mode of Firefox I can select the options.....?
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/7322
> <http://issues.joomla.org/tracker/joomla-cms/7322>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/7322#issuecomment-118270451>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by infograf768** [comment] 2015-07-03 08:15
Mac, firefox 38.0.5 
new 3.4.3 install: no issue here.

**Comment by smz** [comment] 2015-07-03 14:18
Win 8.1, FF 39.0 (and 38.0.5), Chrome 43.0.2357.130 m: unable to replicate the issue...

**Comment by henisa** [comment] 2015-07-03 20:56
I Am home now, tested on a mac with latest osx and chrome 43.0.2357.130 (64-bit) same issue. popup closes directly after opening.

At home i can't reproduce  ' Only if I start the
 debug record mode of Firefox I can select the options.....? '

I have tried on windows 8.1 and firefox 39.0 no changes. Still a problem.

**Comment by smz** [comment] 2015-07-03 22:18
I'm starting suspecting some Chrome/FF extension may be involved...
Can you test with a bare Chrome/FF configuration (disabling all plugins/add-ons)?

**Comment by henisa** [comment] 2015-07-03 22:18
I have put a backup of the 3.4.2 version of joomla and it works. Strange. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7322">issues.joomla.org/joomla-cms/7322</a>.</sub>

**Comment by henisa** [comment] 2015-07-05 20:46
I have tested it with no plugins, no changes.

**Comment by smz** [comment] 2015-07-06 12:07
At this point I'm out of clues...

Only thing I'm noting is that you're using MariaDB **and** "Database Collation latin1_swedish_ci". It would be strange that this has anything to do with the issue, but I've seen a lot of strange things happening in my IT life...

It would be nice if the OP @thedesignduck could drop in and give similar information to see if there is anything in common...

**Comment by smz** [comment] 2015-07-06 12:13
BTW, I just updated an old "live" site (*it was born on Joomla 3.0, and then updated to 3.2, 3.3.6 and finally at 3.4.3*) that uses various 3rd part extension (*K2, some JSN stuff, Ohanah, and some developed in house*) and it works perfectly...

**Comment by illambias** [comment] 2015-07-09 13:53
I can reproduce exactelly the same problem. Clean joomla 3.4.3 installed, import (via redMigrator) of an old 1.5 site (articles, menus, users). Impossible to select a Menu Item Type. The popup flickers.

All browsers give the same result, with or without plugins. Only tested on linux based OS.

Ping me if you need more informations, configurations etc.

If someone has a clue, it would be more than welcome !

**Comment by dimitargsg** [comment] 2015-07-09 14:02
I am experiencing the same problem as the one reported here. The site was upgraded from Joomla 1.5 to 3 with RedMigrator. The upgrade was completed successfully, but I can not select menu item at all - exactly as @thedesignduck  reported. I reproduced the problem with all browsers I have - Chrome, Firefox, Konqueror, Opera. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7322">issues.joomla.org/joomla-cms/7322</a>.</sub>

**Comment by brianteeman** [comment] 2015-07-09 15:24
@thedesignduck was your site also upgraded previously with redmigrator? If
so then it looks like we have a common cause.

**Comment by thewebtailors** [comment] 2015-07-09 21:07
Had the same issue. Disabling all RedMigrator extensions fixed it for me.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7322">issues.joomla.org/joomla-cms/7322</a>.</sub>

**Comment by brianteeman** [comment] 2015-07-09 21:15
Thanks - I just installed redmigrator and can confirm the issue reported here. 

As this is not a joomla core issue I am closing this. Please report the issue to redcomponent.com<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7322">issues.joomla.org/joomla-cms/7322</a>.</sub>

**Closed** 2015-07-09 21:15 UTC
Labels: No Code Attached Yet

**Comment by microtribe** [comment] 2015-10-01 06:23
Thanks @brianteeman and @thewebtailors. I didn't use redmigrator but I had it installed. Uninstalling most of it and disabling the rest solved my issues too. Thank you thank you!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7322">issues.joomla.org/joomla-cms/7322</a>.</sub>

**Comment by thedesignduck** [comment] 2016-02-03 01:59
Funny thing... I never got the email alerts for all of your replies! BUT... I had the same problem with a 3.4.8 install... Googled the same thing I typed in July... found my own post and all of your replies. And it worked. It was redcomponent. THANK YOU ALL! :)

**Comment by hatimashi** [comment] 2016-03-10 14:54
I'm also confirm that RedMigrator Problem. Every component must be disabled especialy RedCore
