### ISSUE TITLE
[4.0] Fliers option is enable in article

### ISSUE THREAD

**Issue by pinak3748** [joomla/joomla-cms#35126] opened 2021-08-15 05:59 UTC
### admin dashboard -> site information -> article(badge)

After clicking article(badge)  it will redirect to the article page but the filters option is enabled in advance.
This only happens if we navigate to the article page through dashboard if you go through sidebar article link it's working fine.

### Expected result

![after](https://user-images.githubusercontent.com/59458280/129468705-0c7eb449-11ac-421b-a62a-f329d1217158.jpg)

### Actual result
![before](https://user-images.githubusercontent.com/59458280/129468706-ff1da55e-bc0c-49c2-a942-35a1048d21bc.jpg)

### System information (as much as possible)
os -> windows 10
browser -> brave
php8
version -> joomla 4.0 rc7

**Comment by brianteeman** [comment] 2021-08-15 12:04
That is correct and it is the intended behaviour. The module is displaying a count of published articles. Therefore the link should also display only published articles

**Comment by pinak3748** [comment] 2021-08-15 13:00
I didn't see that there was a selected dropdown I think it blend with other  their should be some change in slected filters option and other

**Comment by richard67** [comment] 2021-08-15 19:09
@pinak3748 You can see by the "Clear" button being enabled that there is a filter active. Please check and close this issue if you can confirm this. Thanks in advance.

**Closed as completed** 2021-08-16 03:14 UTC
Labels: No Code Attached Yet
