### ISSUE TITLE
J 3.8.10 Extension manager 'Search Tools' filter by type

### ISSUE THREAD

**Issue by jflash** [joomla/joomla-cms#20907] opened 2018-06-28 10:16 UTC
### Steps to reproduce the issue
Update your site to 3.8.10, go to backend: Extensions - Manage - Manage. Try set search tools 'by type' - this field is without dropdown, just empty field.

### Expected result
In third field from left need to be dropdown '- Select type -'

### Actual result
Type field is empty

### System information (as much as possible)
Tried in two servers: Joomla 3.9.10. PHP 5.6.26 / 7.2.4. DB 5.6.33 / 5.5.5-10.2.15-MariaDB-log. Server  Linux / FreeBSD

### Additional comments

![screen shot 2018-06-28 at 10 14 59](https://issues.joomla.org/uploads/1/802f9f9e6daef2ea7faa016032289671.png)

**Comment by jeckodevelopment** [comment] 2018-06-28 10:29
Confirmed.
After 3.8.10 update from a 3.8.8 fresh installation in test environment.

**Comment by Sandra97** [comment] 2018-06-28 10:47
Duplicate of #20881

**Comment by jflash** [comment] 2018-06-28 10:48
More tests: under fresh 3.8.10 this field works, but after old site update from 3.8.8 to 3.8.10 does not.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20907">issues.joomla.org/tracker/joomla-cms/20907</a>.</sub>

**Comment by jflash** [comment] 2018-06-28 10:58
OK, someone was faster, it is duplicate of #20881 
After update is missing file type.php in folder /administrator/components/com_installer/models/fields/<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20907">issues.joomla.org/tracker/joomla-cms/20907</a>.</sub>

**Comment by brianteeman** [comment] 2018-06-28 10:58
Yes we know. In the original report and subsequent fix it has been identified that a file is being removed by the update process that should not be and that's why it is not an issue on a new install.

**Closed as completed by brianteeman** 2018-06-28 10:58 UTC
Labels: No Code Attached Yet
