### ISSUE TITLE
[4.0] #__ucm_history is still presented in utf8mb4 conversion SQL

### ISSUE THREAD

**Issue by Denitz** [joomla/joomla-cms#30224] opened 2020-07-30 04:59 UTC
### Steps to reproduce the issue

Try to perform utf8mb4 conversion via com_installer

### Expected result

Finished.

### Actual result

Error: `Table 'XXX.jos_ucm_history' doesn't exist`

**Comment by richard67** [comment] 2020-07-30 06:47
Confirmed. Error was introduced by PR #29217 , which renamed that table to `#__history`. I will make a pull request soon for fixing it.

@Denitz Thanks for reporting.

**Comment by richard67** [comment] 2020-07-30 06:53
@Denitz How did you start the conversion via com_installer? Just am asking because I never did that directly, and it may be helpful information for other users, too, and also help with testing the correction which I will provide.

**Comment by Denitz** [comment] 2020-07-30 07:02
@richard67 I had and old beta2 version installed, today I updated it to beta3 and see the schema error about conversion.

Check the value in `#__utf8_conversion` table, I have `converted` as `4 `.

If it's `5`, Joomla thinks that it was converted. Try to set to `4` manually and re-check schema.

**Comment by richard67** [comment] 2020-07-30 07:07
I see.

**Comment by richard67** [comment] 2020-07-30 07:09
@Denitz Are you a coder, and do you want to provide fixes for these 2 issues? Or shall I do it?

**Comment by richard67** [comment] 2020-07-30 07:39
@Denitz Ok, I made PR #30227 . Is still work in progres because I have to complete testing instructions.

What surprises me is that you still have the `#__utf8_conversion`. This table will not be present on a new J4 since Beta 1 was released, and on a J4 updated from 3.10 the table will be removed if the conversion was successful.

Did your old Beta 2 have some update history? Or was it a new installation of Beta 2?

**Comment by Denitz** [comment] 2020-07-30 07:55
@richard67 To be honest, I only remember that I installed the beta versions on this host. Potentially, I can have this table left from the previous unknown version. Anyway, see that conversion is still checked if the table is presented and there can be such a situation.

And imho,  `#__history` is the too common table name, it's used by `com_contenthistory` and `#__content_history` sounds more informative even though it's not 100% related to `com_content` items only.

**Comment by richard67** [comment] 2020-07-30 08:05
@Denitz Am just working on a realistic test scenario. As soon as my PR is ready for testing I'll close this issue, that's how we usually do it here. Regarding naming of that table: That was not my idea, see PR #29217 . I agree with you about the too common name. I would have called it `#__content_history`, if I had something to decide. But now we should not rename that table again because that would cause complications with updates.

**Comment by richard67** [comment] 2020-07-30 09:01
Closing as having a pull request. Please test #30227 .

**Closed as completed by richard67** 2020-07-30 09:01 UTC
Labels: No Code Attached Yet

**Comment by Denitz** [comment] 2020-07-30 09:15
@richard67  Unfortunately, I can't trace the utf8_conversion table, probably it was left from 3.x upgraded to 4.x alfa or beta

> a J4 updated from 3.10 the table will be removed if the conversion was successful.

What if not? It means that the table can still be presented?

PS. How it occurred that such a table name was approved :(

**Comment by richard67** [comment] 2020-07-30 09:29
> What if not? It means that the table can still be presented?

If the update fails, the table is still present.
 
> PS. How it occurred that such a table name was approved :(

I think you are referring to the `#__history` table, right? As I said, not my decision, that came with PR #29217 .
