### ISSUE TITLE
#__contentitem_tag_map slowing down loading

### ISSUE THREAD

**Issue by hans2103** [joomla/joomla-cms#7124] opened 2015-06-05 09:37 UTC
According to this screenshot taken from New Relic page to display the transaction I notice that #__contentitem_tag_map is slowing down the creation of the page. 

![schermafdruk 2015-06-05 11 30 37](https://cloud.githubusercontent.com/assets/639822/8003361/31445b0c-0b77-11e5-9ac5-718c7f9afd30.png)

Two remarkable things:
- this website doesn't use tags.
- problem occurs on a 404 page.

**Comment by alikon** [comment] 2015-06-05 16:40
How many articles /categories do yuo have ?

**Comment by ggppdk** [comment] 2015-06-05 18:34
So despite not having any tags,
the tags SELECT query takes:
  33%  *  1.81 seconds = 0.59 seconds  ?

Can you also use the Joomla Debug option ?
- and from it copy paste here 
the real SQL query and 
the function Call stack

the above will answer questions:
- which is the SQL query, is it core Joomla, or some 3rd party plugin/module, or a joomla module ?
- is it 1 SELECT query or multiple SELECT queries ?

**Comment by brianteeman** [comment] 2015-06-19 08:28
@hans2103 Please can you provide the requested informaton<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7124">issues.joomla.org/joomla-cms/7124</a>.</sub>

**Comment by hans2103** [comment] 2015-06-19 12:15
sorry... totally missed the request. Will do

**Comment by hans2103** [comment] 2015-06-25 08:44
Problem only occurs on a 404 page. Joomla can't find the page, therefor it will try non existing tags... so it seems. 

SQL statement copied from New Relic.
> SELECT `m`.`tag_id`, `t`.*FROM `t?hu_contentitem_tag_map` AS m INNER JOIN `t?hu_tags` AS t ON `m`.`tag_id` = `t`.`id`WHERE `m`.`type_alias` = ? AND `m`.`content_item_id` = ? AND `t`.`published` = ? AND t.access IN (?, ?, ?)




![schermafdruk 2015-06-25 10 39 16](https://cloud.githubusercontent.com/assets/639822/8350503/a911efc8-1b26-11e5-95e9-92f59dd6a395.png)
![schermafdruk 2015-06-25 10 43 35](https://cloud.githubusercontent.com/assets/639822/8350571/153c9950-1b27-11e5-92a3-54ceb5bd33dc.png)

![schermafdruk 2015-06-25 10 40 34](https://cloud.githubusercontent.com/assets/639822/8350505/a918c2bc-1b26-11e5-835d-13ce2f8a4096.png)

**Comment by PhilETaylor** [comment] 2015-07-10 21:09
Is your database prefix really ```t?hu_``` ??? with a question mark in it?

**Comment by brianteeman** [comment] 2015-07-10 22:24
I cant replicate this. With debug on I dont see any queries for tags on a 404 page. As the 404 page uses the error.php from your template I am wondering if there is something in that file in your template<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7124">issues.joomla.org/joomla-cms/7124</a>.</sub>

**Comment by hans2103** [comment] 2015-07-11 21:29
@brianteeman I will check

**Comment by pe7er** [comment] 2016-05-07 13:13
I can't reproduce the problem either. Joomla's debug does not show any queries on a 404 page. 
The issue has not been followed up since last year so I'll ask to close it.
Thanks @hans2103 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7124">issues.joomla.org/joomla-cms/7124</a>.</sub>

**Comment by zero-24** [comment] 2016-05-07 13:14
Set to "closed" on behalf of @zero-24 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7124">issues.joomla.org/joomla-cms/7124</a>

**Comment by zero-24** [comment] 2016-05-07 13:14
Closing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7124">issues.joomla.org/joomla-cms/7124</a>.</sub>

**Closed by zero-24** 2016-05-07 13:14 UTC
Labels: No Code Attached Yet

**Comment by hans2103** [comment] 2016-05-07 13:15
check
