### ISSUE TITLE
Test Email sending fails without message

### ISSUE THREAD

**Issue by vihuarar** [joomla/joomla-cms#10614] opened 2016-05-24 13:17 UTC
#### Steps to reproduce the issue
1. Enter to backend
2. Enter to system, configuration, server
3. configure mail settings...
4. clic the bottom "Sent Test Mail"

#### Expected result
Joomla sends a test mail...

#### Actual result
When you click the "Sent Test Email"... nothing happens

#### System information (as much as possible)
see screenshot
![screenshot from 2016-05-24 08 12 27](https://cloud.githubusercontent.com/assets/1976384/15505175/e27eb742-2187-11e6-84c9-475c25187802.png)

**Comment by Twincarb** [comment] 2016-05-24 14:55
A quick look at your picture, and when you have SMTP selected your still showing "Sendmail Path" this should only be showing when "Sendmail" is selected.

The same issue is showing with FTP and Proxy, when they are selected as No the boxs should below should be hidden.

I can see your using Joomla! 3.5.1 and when I am on the screen your showing and use the test mail button it all works correctly, there is a green success bar which shows below the "Save" "Save and Close" "Cancel" message.

Is your server executing JavaScript correctly?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10614">issues.joomla.org/joomla-cms/10614</a>.</sub>

**Comment by andrepereiradasilva** [comment] 2016-05-24 18:21
did you clear your browser cache?

**Comment by vihuarar** [comment] 2016-05-26 21:46
@Twincarb you give me a clue... this is the screenshot of the console... in the google chrome...

Is not an loading error of a javascript... so its not a server issue....

@andrepereiradasilva I also cleaned the cache... but everything is still the same... I dont understand how is related the cache with this issue...

![screenshot from 2016-05-26 16 43 48](https://cloud.githubusercontent.com/assets/1976384/15591170/1af6a942-2361-11e6-99e8-6a8dc973326f.png)

**Comment by andrepereiradasilva** [comment] 2016-05-26 21:54
jMediaRefreshImgpathTip is a mootools function used by the image selector field in the global configuration (the offline image) so that error is not related to the mail send.
See https://github.com/joomla/joomla-cms/blob/staging/media/media/js/mediafield-mootools.js#L50

> @andrepereiradasilva I also cleaned the cache... but everything is still the same... I dont understand how is related the cache with this issue...

The sendmail js has changed in 3.5.0 and in 3.5.1 so you need to clear the browser cache to update it.
See https://github.com/joomla/joomla-cms/commits/staging/media/system/js/sendtestmail-uncompressed.js

Anyway you problem doesn't seem to be an issue with joomla core, maybe some extension you have is originating that error.

I can't reproduce it.

So test with joomla (latest staging) clean install in a dev server (install as normal https://github.com/joomla/joomla-cms/archive/staging.zip) and see if you still have the error.

**Comment by conconnl** [comment] 2016-07-02 22:47
I have tested this on 3 different websites on different servers and different Mail configurations.
None of the websites describes the issue your are experiencing.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10614">issues.joomla.org/joomla-cms/10614</a>.</sub>

**Comment by vihuarar** [comment] 2016-07-03 16:01
So.. I think you can close this issue...  it should be a third party library installed who is in conflict with the Joomla core..

Thanks!

**Comment by brianteeman** [comment] 2016-08-03 10:31
Closed as requested<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10614">issues.joomla.org/joomla-cms/10614</a>.</sub>

**Closed** 2016-08-03 10:31 UTC
Labels: No Code Attached Yet
