### ISSUE TITLE
Extensions Manage Link is Wrong

### ISSUE THREAD

**Issue by rgblogs** [joomla/joomla-cms#7850] opened 2015-09-09 17:48 UTC
#### Steps to reproduce the issue

In Joomla Back end administrator, clicking on Extensions -> Manage, goes to Extensions Install (not manage).

#### Expected result

Either name of link should change or URL.

**Comment by zero-24** [comment] 2015-09-09 17:50
@brianteeman confirmed. maybe we should change the language string?

**Comment by Bakual** [comment] 2015-09-09 18:47
Good catch. It was "Extension Manager" in 3.4.3 and since we removed "Manager" from the manager views, we would have been left with a menu "Extensions" -> "Extensions" which has been thought as less ideal. Maybe that's still the better approach than what we have now?

**Comment by justinherrin** [comment] 2015-09-09 22:19
How about a new language string of "Install & Manage"? So it would be "Extensions" -> "Install & Manage". And the link would still go to the usual Install view.

**Comment by auditorj** [comment] 2015-09-10 01:58
@justinherrin  I think "Manage" does include Install, Update, etc., might change the "Manage" to "Administration"? since administration include manage?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7850">issues.joomla.org/joomla-cms/7850</a>.</sub>

**Comment by justinherrin** [comment] 2015-09-10 02:42
@auditorj as I typically don't mind the word "Administration", I would not recommend using it here in this situation. I can see it causing too much confusion considering Joomla's use of the word to describe its admin area.

**Comment by rgblogs** [comment] 2015-09-10 03:39
I think we can change the word "Manage" (in left menu) to Remove or Uninstall because from current Manage option, we can only uninstall and disable it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7850">issues.joomla.org/joomla-cms/7850</a>.</sub>

**Comment by auditorj** [comment] 2015-09-10 05:49
@justinherrin I see, it does create a lot of confusion. Having "Manage" on the drop down menu,and another "Manage" on the side menu might be redundant, maybe we can think of other word that describes manage, i guess :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7850">issues.joomla.org/joomla-cms/7850</a>.</sub>

**Comment by oorzaak** [comment] 2015-10-10 13:52
I agree with rgblogs in that the title of the side menu Manage (effectively: Extensions > Manage > Manage) is causing troubles. I think the title Manage in the drop down menu item Extensions > Manage is consistent with other back end menu items and it effectively takes the user to a section of the back end where he can manage extensions. 
Additionally, when clicking on Extensions > Manage the user is taken to the page Extensions > Manage > Install. Which gives a first impression that the meaning of "Manage" is limited to "Install". Maybe it would be better to introduce, on this level, a page with quick link icons to all items in the left menu.

**Comment by zero-24** [comment] 2015-10-10 19:13
@brianteeman can you have a look here? Looks like a language decision need to be made :smile: Thanks.

**Comment by marijkestuivenberg** [comment] 2015-10-11 19:45
I think this issue can be closed when #8058 is committed

**Closed** 2015-10-11 20:36 UTC
Labels: No Code Attached Yet
