### ISSUE TITLE
[4.0] Large DOM size of the smart search

### ISSUE THREAD

**Issue by socke300** [joomla/joomla-cms#35366] opened 2021-08-25 13:34 UTC
### Steps to reproduce the issue

1. Install Joomla with branch 4.0-dev
2. Create a large amount (10.000+) of articles with [Overload](https://github.com/nikosdion/overload)
3. Create a smart search *Content->Site Modules->New->Smart Search* *, select a position*
4. Open advance smart search
5. Open the author field
6. You can also open the chrome lighthouse function and use the performance tool

### Expected result

The dome size should be much smaller.

### Actual result

![grafik](https://user-images.githubusercontent.com/60921761/130797844-105ef42f-221c-4fad-b550-70a287e4af8a.png)

### System information (as much as possible)

Tested on branch 4.0-dev with 25.000 articles.

### Additional comments

Perhaps only 20-40 authors should be displayed and if one scrolls down further, more should be loaded. It would also be good to search for authors.

**Comment by PhilETaylor** [comment] 2021-08-25 14:03
This is a duplicate of something I reported ages ago

**Comment by PhilETaylor** [comment] 2021-08-25 14:04
Found it https://github.com/joomla/joomla-cms/issues/32900

**Comment by alikon** [comment] 2021-08-25 14:11
close as duplicate of #32900

**Closed as completed by alikon** 2021-08-25 14:11 UTC
Labels: No Code Attached Yet
