### ISSUE TITLE
redirect loop after deleted content ID 1

### ISSUE THREAD

**Issue by wallstudios** [joomla/joomla-cms#6293] opened 2015-03-04 05:56 UTC
#### Steps to reproduce the issue
I had the default "getting started" article published on the home page while developing.

I first set it to be not featured but it still displayed on homepage.
I then moved to trash but it still showed.
I then emptied the trash.
from then I could not load the home page at all. Redirect loop issue

I went into phpmyadmin and assigned an article the ID of 1 and saved.

can now load home page.

tested on default template and had same issue so not template related.

#### Expected result

Not have a featured article on homepage
be able to delete article without issue.

#### Actual result

redirect loop

#### System information (as much as possible)
PHP Built On 	Linux 3.12.35.1418868451 #1 SMP Wed Dec 17 20:10:32 CST 2014 x86_64
Database Version 	5.5.40-36.1
Database Collation 	utf8_unicode_ci
PHP Version 	5.4.37
Web Server 	Apache
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 3.4.0 Stable [ Ember ] 24-February-2015 23:00 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

**Comment by pcmitsis** [comment] 2015-03-04 18:34
@wallstudios Can you verify the problem with the latest code from the staging branch because i followed your steps but i could not find any problem. I emptied the trash and i was able to access the homepage of joomla without any posts (including th ID 1) successfully!

**Comment by wallstudios** [comment] 2015-03-04 22:56
@pcmitsis I set up a demo account (https://wallstudios.demojoomla.com/index.php) and went through the same steps as before.
with the default install (no sample content) the getting started homepage link goes to the article id1 now if I delete that the site can't find it and then redirects to a 404 which is trying to redirect to the home page. hence the loop.

on the demo site it shows a 404 message. but on my dev site it just looped.
If the homepage menu is set to "Featured" it will work. 

So it may simply need to not have the default home link set to an article.

**Comment by brianteeman** [comment] 2015-03-05 09:44
Or just change the home page link to an existing piece of content. Surely it is expected behaviour if you have a menu link to something that doesnt exist that you get an error<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6293">issues.joomla.org/joomla-cms/6293</a>.</sub>

**Comment by wallstudios** [comment] 2015-03-05 22:35
@brianteeman yes of course it is expected to have a 404 if you are trying to go to a page that doesn't exist. No issue with that.  But I wouldn't expect a home page link it to be an article link by default. And that could just be me and not an issue.
I guess the only thing that needs to be done if anything is confirm that when you install 3.4 and select no sample content that the "Home" menu isn't directly linked to a content item but maybe to the "featured" option. 
That way if articles are removed the home page doesn't break.

**Comment by brianteeman** [comment] 2015-03-11 10:58
As the behaviour on an install without sample data IS to do exactly what you are suggesting I am closing this

**Closed by brianteeman** 2015-03-11 10:58 UTC
Labels: No Code Attached Yet
