### ISSUE TITLE
Multiple editor instances causes unexpected behaviour

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15014] opened 2017-03-30 20:14 UTC
### Steps to reproduce the issue

install from joomla-cms/staging @ f45c0da5ba84ef7538e13879a1b096ed9e05c24d
Add a custom field, of type "editor"
Edit content item
Click the Read More TinyMCE Button 
Click the Read More TinyMCE Button 
Click the Read More TinyMCE Button 
Click the Read More TinyMCE Button 

### Expected result

A read more `<hr id="system-readmore" />` appears in the TinyMCE as a red dashed line in the editor on the Content type

Subsequently clicking the read more button should give a popup with 
![screen shot 2017-03-30 at 21 11 01](https://cloud.githubusercontent.com/assets/400092/24524114/65870564-158d-11e7-8f1d-6b2d7b54be61.png)
 

### Actual result

Multiple read more dashed lines get added to the editor
![screen shot 2017-03-30 at 21 11 34](https://cloud.githubusercontent.com/assets/400092/24524138/78fb6da6-158d-11e7-9fca-b37b1ccff689.png)

### Additional STEPS to replicate unexpected behaviour

So now you have clicked many times on read more in tinymce on the editor on the content tab, now go to the Fields tab, and in your custom field editor click read more in that editor 

Note that ONE red dashed line is added (in the source code a `<hr id="system-readmore" />` is added)

Note that Subseqently clicking this read more button correctly gives the popup warning above 

### Additional comments

PR #14520 can be improved to fix this

**Comment by franz-wohlkoenig** [comment] 2017-04-01 10:21
Added a custom Field Type "Editor", opened an Article, could only one Time use Button "Read more" in Article Content; so i can't confirm.

**Comment by PhilETaylor** [comment] 2017-04-01 11:36
Maybe you should actually read the issue reported then !

**Comment by franz-wohlkoenig** [comment] 2017-04-01 11:44
have read issue report. As far as i understand it i tried to get same behavior as reported. So if we want to solve Issue can you help me to understand?

**Comment by PhilETaylor** [comment] 2017-04-01 12:01
did you apply PR #14520  ?

**Comment by PhilETaylor** [comment] 2017-04-01 12:09
ok on a totally different mac I installed from joomla-cms/staging with commit 9bf372640f973ea934d232342218702328167729

add a custom editor field - keep defaults but enable SHOW BUTTONS

You DONT need to apply #14520 

Then you can replicate the above issue

Without the show buttons enabled on the custom editor field this problem is not replicate-able.

**Comment by franz-wohlkoenig** [comment] 2017-04-01 12:31
Thanks for Info, understand now more, will try later.

**Comment by franz-wohlkoenig** [comment] 2017-04-02 07:37
Test on latest staging (includes 9bf3726), in com_field "Editor" `Show Buttons` set on `Yes` > can only Click one Time on `Read More`-Button of Field-Editor.

**Comment by franz-wohlkoenig** [comment] 2017-05-29 05:29
@PhilETaylor does this issue exist on latest Staging? Tried to get same behavior as reported, but works as expected (only one Read More-Line possible).
### System information
3.7.3-dev (latest nightly build)
Multilanguage Site
macOS Sierra, 10.12.5
Firefox 53 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by brianteeman** [comment] 2017-05-29 08:34
Looks like this has been resolved. I am closing this at this time. @PhilETaylor if you can still reproduce this then it should be reopened

**Closed by brianteeman** 2017-05-29 08:34 UTC
Labels: No Code Attached Yet
