### ISSUE TITLE
Repeatable form field does not respect field "size" statement

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#9182] opened 2016-02-20 20:20 UTC
#### Steps to reproduce the issue
Create a "repeatable" form field.
create a field containing the "size="8"

#### Expected result
input box will be 8 chars wide

#### Actual result
input box is some magical width

#### System information (as much as possible)

sample code...
```xml
<field name="googleFonts"
					type="Repeatable"
					icon="list"
					label="TPL_SERENITY_FONT_SELECTOR"
					default='{
"Elements":["body","H1","H2","H3","H4","H5","H6","p","a","i","ul","li"],
"Font":["Helvetica","Royal"],
"Css":["16px"],
"Size":["blah"]
}'>
					<fieldset hidden="true" name="googleFonts_modal" repeat="true">
						<field name="Elements"
							label="TPL_SERENITY_FONT_ELEMENTS_LABEL"
							rows="2"
							cols="1"
							filter="html"
							type="textarea" />
						<field name="Font"
							label="TPL_SERENITY_FONT_"
							size="6"
							type="text"
							filter="raw"
						/>
						<field name="Css"
							label="TPL_SERENITY_FONT_CSS_LABEL"
							type="text"
							filter="raw"
						/>
						<field name="Size"
							label="TPL_SERENITY_FONT_SIZE_LABEL"
							size="8"
							type="text" />
					</fieldset>
				</field>
```
result:
![image](https://cloud.githubusercontent.com/assets/1850089/13198982/16a5e31e-d7dd-11e5-8168-31139c774c04.png)

**Comment by brianteeman** [comment] 2016-02-20 22:23
Off the top of the head it is not 8 characters wide because of the default bootstrap styling<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9182">issues.joomla.org/joomla-cms/9182</a>.</sub>

**Comment by brianteeman** [comment] 2016-02-21 11:07
Double checked now that I am at a PC. It is nothing to do with it being a repeatable field. The same is true for all fields and as I suspected it is because of bootstrap. If you use a non-bootstrap admin template (eg hathor) then you will see that the size=8 is honoured.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9182">issues.joomla.org/joomla-cms/9182</a>.</sub>

**Comment by brianteeman** [comment] 2016-02-21 12:01
I am closing this as expected behaviour<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9182">issues.joomla.org/joomla-cms/9182</a>.</sub>

**Closed by brianteeman** 2016-02-21 12:01 UTC

**Comment by N6REJ** [comment] 2016-02-21 21:41
brian did you verify thats true in hathor?  and if it is true in BS then why do we have it since bs is our default template?  I would expect the size to be changed to reflect the sizing... this really should not be difficult

**Comment by mbabker** [comment] 2016-02-21 21:48
CSS rules can affect the width of elements and make attributes like this not work as intended.

**Comment by brianteeman** [comment] 2016-02-21 21:58
yes i verified it in hathor

On 21 February 2016 at 21:49, Michael Babker <notifications@github.com>
wrote:

> CSS rules can affect the width of elements and make attributes like this
> not work as intended.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9182#issuecomment-186925497>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by N6REJ** [comment] 2016-02-22 17:46
ok guys... tyvm... appreciate the info.. sorry for the false alarm.
Bear
