### ISSUE TITLE
[4.0] Installation: "Check to delete installion folder" did not function

### ISSUE THREAD

**Issue by vickythomas** [joomla/joomla-cms#25610] opened 2019-07-17 13:53 UTC
### Steps to reproduce the issue
I installed J4 alpha 10 to test.  Got to congratulations screen.  Checked "Check if you wish to delete installation folder on completion" then checked 'complete and open site'.  I was returned to the same screen. 
So, then, I manually removed the installation folder. 
On congratulations screen, checked the box again and then selected "complete and open admin".  I was taken to admin. When in admin, I chose preview button to view site, was shown URL/subfolder/installation/index.php  (pointing to absent installation folder) so got a 404.
When I type in just URL/subfolder ow ... it changes to URL/subfolder/installation/index.php and 404.
If I remove 'installation/' from URL, I do see the live site correctly.

### Expected result
I expected the installation folder to be deleted and the URL to not have 'installation/' inserted in it when trying to open the site.

### Actual result
When I type in just URL/subfolder now ... it changes to URL/subfolder/installation/index.php and 404.
If I remove 'installation/' from URL, I do see the live site correctly.

### System information (as much as possible)
Database Version 	5.6.44
Database Collation 	latin1_swedish_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	7.2.19
Web Server 	Apache/2.4.39 (cPanel) OpenSSL/1.0.2s mod_bwlimited/1.4
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 4.0.0-alpha10 Alpha [ Amani ] 29-June-2019 11:07 GMT

**Comment by brianteeman** [comment] 2019-07-17 14:13
Thank you for testing and reporting this.

It is a known issue that it does not get deleted and will be fixed at a later date. During development stages of Joomla its always possible to continue with this file present as it allows testers to easily reset their installation by just deleting the configuration.php file and reinstalling without having to upload joomla again

**Comment by vickythomas** [comment] 2019-07-17 14:24
OK. Thanks for that explanation Brian.

**Comment by brianteeman** [comment] 2019-07-17 14:26
@franz-wohlkoenig please close this - the reference for the issue is #18765

**Comment by Quy** [comment] 2019-07-17 14:27
Duplicate #18765<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25610">issues.joomla.org/tracker/joomla-cms/25610</a>.</sub>

**Closed as completed by Quy** 2019-07-17 14:27 UTC
Labels: No Code Attached Yet, J4 Issue
