### ISSUE TITLE
[4.0] Global Configuration Text Filters tab UI is not proper at administrator side

### ISSUE THREAD

**Issue by bhavikDigitalWebInfosoft** [joomla/joomla-cms#15477] opened 2017-04-22 09:18 UTC
### Steps to reproduce the issue
Goto->administrator->System->Global Configuration->Text Filters tab

### Expected result
UI should be well format 

### Actual result
UI is not proper, please see attached screen dump.

### System information (as much as possible)
Joomla! 4.0.0-dev Development [ Amani ] 31-March-2017 23:59 GMT 
PHP 5.6.28
Ubuntu 12.04
Firefox 52.0.2 (64-bit)

### Additional comments
![screen shot 2017-04-22 at 09 18 31](https://issues.joomla.org/uploads/1/7f766cfb6a21ef4492d0c67e3429a6d6.png)

**Comment by brianteeman** [comment] 2017-04-22 09:20
Closed as a duplicate of #15423 - this is not specific to J4 and is something introduced in 3.7

**Closed by brianteeman** 2017-04-22 09:20 UTC
Labels: No Code Attached Yet
