### ISSUE TITLE
JFactory::getDbo(),setQuery #__ prefix not replace in some query

### ISSUE THREAD

**Issue by serkamikadze** [joomla/joomla-cms#7162] opened 2015-06-12 12:09 UTC
#### Steps to reproduce the issue
// setQuery() not replace #__ to table prefix in this query
$query="SHOW TABLE STATUS LIKE '#__table'";
#### Expected result

$query=="SHOW TABLE STATUS LIKE 'table_prefix_table'";

#### Actual result
$query=="SHOW TABLE STATUS LIKE '#__table'";

#### Additional comments
I use $db->getPrefix() and query like this
$query="SHOW TABLE STATUS LIKE '".$db->getPrefix()."table'";

**Comment by mbabker** [comment] 2015-06-12 13:19
Looking through our unit tests, it looks like this is intended behavior.  In this use case, the table name is a quoted search value and it looks like replacePrefix was designed to not replace the prefix in this case.  So your workaround would be correct here.

**Comment by Bakual** [comment] 2015-06-12 13:21
Closing as expected behavior based on @mbabker comment

**Closed by Bakual** 2015-06-12 13:21 UTC
Labels: No Code Attached Yet
