### ISSUE TITLE
TAGS Dropdown display: Missing Data

### ISSUE THREAD

**Issue by hytsch** [joomla/joomla-cms#38940] opened 2022-10-12 06:56 UTC
### Steps to reproduce the problem
We create tags (approx. 100). We open a post and want to assign tags to it.

### Expected result
In the dropdown 'Tags' all tags should be displayed.

### Actual result
Only a few (approx. 10 of >100) tags are listed in the 'Tags' dropdown.

### System information (as far as possible)
J4.2.3, PHP 8.1

### Additional comments
The error did not exist in version 4.1.5. It must be related to the changes in 4.2.

**Comment by chmst** [comment] 2022-10-12 07:04
Are the tags in the sourcecode and not displayed or are they not found? Maybe you can add a screenshot?

**Comment by richard67** [comment] 2022-10-12 11:10
Isn't that dropdown a fancy select (not at my desk now to check that) shows only a limited number of values but fetches more when you start to type a tag name?

**Comment by brianteeman** [comment] 2022-10-12 11:30
Depends on the option in the component to show nested or ajax tags

**Comment by richard67** [comment] 2022-10-12 11:39
Are the following issues related or is this here even a duplicate of one of these two? #38763 #37927

**Comment by brianteeman** [comment] 2022-10-12 11:44
probably

**Comment by hytsch** [comment] 2022-11-15 19:44
we open a new issue with screenshots. #39219

**Comment by richard67** [comment] 2022-11-15 21:34
@hytsch And what to do with this issue here? Close it?

**Comment by chmst** [comment] 2022-11-15 21:39
yes ... closing in favour of an new one https://github.com/joomla/joomla-cms/issues/39219

**Closed as completed by chmst** 2022-11-15 21:39 UTC
Labels: No Code Attached Yet
