### ISSUE TITLE
Menu Item creation userbility bug

### ISSUE THREAD

**Issue by B3nito** [joomla/joomla-cms#22495] opened 2018-10-04 14:27 UTC
### Steps to reproduce the issue
1) Create a new menu item, set up parent item, language and level.
2) select menu item type

### Expected result
3) Save and finished

### Actual result
3) All settings from 1) are gone you have to repeat everything.

### System information (as much as possible)
Joomla 3.8.12

**Comment by SharkyKZ** [comment] 2018-10-04 14:33
Duplicate of #22150.

**Closed as completed** 2018-10-04 14:35 UTC
Labels: No Code Attached Yet
