### ISSUE TITLE
[3.8]JHtml/JHTML no more B/C and now case sensitive?

### ISSUE THREAD

**Issue by joeforjoomla** [joomla/joomla-cms#17804] opened 2017-08-31 14:57 UTC
### Steps to reproduce the issue
Call the JHtml class in a case sensitive manner

echo JHTML::_( 'form.token' );

and 

echo JHtml::_( 'form.token' );

### Expected result
Class is loaded in both cases

### Actual result

Class is loaded only as JHtml but no more as  JHTML throwing an error
![jhtml_not found](https://user-images.githubusercontent.com/17835460/29929991-6b25823a-8e6d-11e7-89ce-d6857b5bd7b9.JPG)

**Comment by wojsmol** [comment] 2017-08-31 15:05
@laoneo This is probably namespacing issue.

**Comment by joeforjoomla** [comment] 2017-08-31 15:06
This caused a B/C break in several extension still using JHTML flavor to call that class

**Comment by mbabker** [comment] 2017-08-31 15:16
`JHTML` has been the incorrect way to call the class name for quite some time (since at least 2.5.0 the class has been named as `JHtml` and in an autoloaded path).  In fact you can only use the full uppercase variant if something else has already loaded it into the system either with a manual include or the correctly cased `JHtml`.

The problem is the autoloader is case sensitive, as is the case with most autoloaders (PHP itself could care less about the casing).  The autoloader would never be able to parse the string `JHTML` and autoload the correct file because of how it processes camel casing.

**Comment by joeforjoomla** [comment] 2017-08-31 15:18
Is there some solutions to avoid a B/C break or all those extensions using JHTML will require a mandatory update?

**Comment by mbabker** [comment] 2017-08-31 15:24
Revert the namespacing PR and force a hard B/C break at 4.0.  Literally the only option if you want to account for everyone who has been Doing It Wrong™.  You can't alias a single class name with multiple casing variants, PHP considers the class already declared and has an issue with it.

I did some digging.  Between 1.5 and 1.6 is when the casing changed.  And at some point in 1.7 (before 2.5) is when the autoloader was added.  So the all uppercase variants haven't been "right" for years, but if you were either making a call after manually including the class or made a call after something else had loaded JHtml into memory then that's why the full uppercase variation works.

**Comment by joeforjoomla** [comment] 2017-08-31 15:25
You right... but definitely what's the planned answer?

**Comment by ggppdk** [comment] 2017-08-31 15:44
this is surely ok for J4.0
but for J3.8 too ?

now 50% or more of current version of extensions is using JHTML in some of their files or everywhere

and for extensions that have been updated 
probably there are custom templates that are using JHTML

**Comment by joeforjoomla** [comment] 2017-08-31 15:49
You right @ggppdk i think it would be a massive B/C break out there... i've just found six extensions using JHTML

Would not be possible to add a class alias in J3.8 to preserve JHTML working and remove it in J4.0?

**Comment by laoneo** [comment] 2017-08-31 15:50
I'm going to make a pr with this variant in the next days. Glad we found it.

**Comment by joeforjoomla** [comment] 2017-08-31 15:52
Thank you @laoneo ... let me know when ready and will test it again

**Comment by C-Lodder** [comment] 2017-08-31 16:02
Good shout. I've seen hundreds of users on JSE defining this class in uppercase.

**Comment by joeforjoomla** [comment] 2017-08-31 19:14
As a side note, the same issue could happen with JURI/JUri

**Comment by esedic** [comment] 2017-09-01 10:38
Is it the same with getDBO/getDbo?

**Comment by joeforjoomla** [comment] 2017-09-01 11:30
I dont think that's the case for getDBO/getDbo, it's a function call not a class name managed by the autoloader

**Comment by laoneo** [comment] 2017-09-02 09:26
Please test #17834 which should fix the issue. All kind of upper/lower case mixes should now be supported for class aliases in `JLoader`.

**Comment by ghost** [comment] 2017-09-02 09:27
closed as havin Pull Request #17834 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17804">issues.joomla.org/tracker/joomla-cms/17804</a>.</sub>

**Closed as completed by ghost** 2017-09-02 09:27 UTC
Labels: No Code Attached Yet
