### ISSUE TITLE
Extensions: Install not working with multiple Uploads.

### ISSUE THREAD

**Issue by lenusch** [joomla/joomla-cms#15160] opened 2017-04-07 20:15 UTC
### Steps to reproduce the issue

Extensions: Install if i drag and drop something. 

### Expected result

this drag and drop uploader suggests that i can upload multiple files. 
I tried and it didn't worked as expected.

### Actual result

It just installed randomly one of the two Packages. 
I tried with PLugin and Componente. 
This would be awesome to have the formular turn into some upload prozess one by one. 
Mostly if i start new Projekt, i install all my favorite components at once. 

### System information (as much as possible)
Joomla 3.7 Rc1

**Comment by PhilETaylor** [comment] 2017-05-05 17:10
Not a bug. Simply just not a feature of Joomla.

**Comment by franz-wohlkoenig** [comment] 2017-05-09 06:12
@lenusch i set your Issue as "Feature Request". If this is not your Intention, please close Issue as this is no core-feature like @PhilETaylor wrote, thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15160">issues.joomla.org/tracker/joomla-cms/15160</a>.</sub>

**Comment by Quy** [comment] 2017-05-16 03:39
Per the instructions `Drag and drop file here to upload.` and `Or browse for file`, I read it to be select/upload one file at a time.

**Comment by franz-wohlkoenig** [comment] 2017-05-16 04:54
closed as no Core-Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15160">issues.joomla.org/tracker/joomla-cms/15160</a>.</sub>

**Closed by franz-wohlkoenig** 2017-05-16 04:54 UTC
Labels: No Code Attached Yet
