### ISSUE TITLE
More query time for large number of categories

### ISSUE THREAD

**Issue by akfaisel** [joomla/joomla-cms#8884] opened 2016-01-12 06:30 UTC
#### Steps to reproduce the issue

I have like 16000 entries in my categories table. While adding or editing a category from backend, it takes a lot of time and the time from debug is 261642.9 ms which is around 4 minutes to load the page.
#### Expected result

Faster loading time
#### Actual result

It takes a lot of time and the time for querying is 261642.9 ms which is around 4 minutes to load the page.
#### System information (as much as possible)

Debugging the system, most of the query time is spent in the following query.

``` php
SELECT DISTINCT a.id AS value, a.title AS text, a.level, a.published, a.lft

  FROM (
SELECT id,title,level,published,parent_id,extension,lft,rgt

  FROM jos_categories

  WHERE (extension = 'com_content' OR parent_id = 0) 
  AND published IN (0,1)) AS a

  LEFT JOIN `jos_categories` AS b 
  ON a.lft > b.lft 
  AND a.rgt < b.rgt

  ORDER BY a.lft ASC
```
#### Additional comments

Take a look at the screenshot for more info.
![screen shot 2016-01-12 at 00 38 20](https://issues.joomla.org/uploads/1/6f00d3d12b5d6fc8346c88fb1d6aac37.png)

**Comment by akfaisel** [comment] 2016-01-12 06:33
Here is the dump of the categories table - http://www.filedropper.com/joscategories

Please replace the file content with your table prefix. I have used **jos**
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8884">issues.joomla.org/joomla-cms/8884</a>.</sub>

**Comment by ggppdk** [comment] 2016-01-12 07:25
This is the form field 'categoryedit'
**administrator/components/com_categories/models/fields/categoryedit.php**
- that is used to create the category parent form field (parent_id)

Looking at the PHP code the query has a sub-query (used in FROM of main query) and a left join with the table itself 
- at least the left-join is not needed as it does nothing in **any possible configuration** for the field (and someone correct) also the subquery can be **converted** but it causes no performance problems as it has no joins in any configuration
- the performance issue must be from this left join **but i have not tested**, and the left join can be removed

```
$query->from('(' . (string) $subQuery . ') AS a')
	->join('LEFT', $db->quoteName('#__categories') . ' AS b ON a.lft > b.lft AND a.rgt < b.rgt');
```

**can become**:
```
$query->from('(' . (string) $subQuery . ') AS a')
	;//->join('LEFT', $db->quoteName('#__categories') . ' AS b ON a.lft > b.lft AND a.rgt < b.rgt');
```

**Comment by akfaisel** [comment] 2016-01-12 09:32
This is amazing. But I don't understand the purpose of the join but it is working.

**Comment by ggppdk** [comment] 2016-01-12 09:51
Why did you close this ? it is a real issue and it still needs to be fixed, i will make a PR when i get some more time so that more people can test and hopefully it will be accepted too

**Comment by ggppdk** [comment] 2016-01-12 09:54
@akfaisel 
Also how much speed difference did it make, give some info

**Comment by rdeutz** [comment] 2016-01-12 12:29
the left join is for getting child categories, not sure if you can remove it entirely. Wondering how many articles the site has?

**Comment by akfaisel** [comment] 2016-01-12 12:56
The time for querying has come down from 261642.9 ms to 200 ms and the page loads so fast.

I'm sorry for closing the issue; I shall reopen it.

The issue is not with number of articles but with CATEGORIES. You can also try with the SQL dump I've provided. After installing the dump, just go to Add or Edit Category and it will take at least 4 mins for loading the page.

**Comment by rdeutz** [comment] 2016-01-12 12:59
@akfaisel I have never seen a site with so many categories, what I have seen is a problem with a lot articles that's the reason I am asking. So how many articles you have?

**Comment by ggppdk** [comment] 2016-01-12 18:53
> the left join is for getting child categories, not sure if you can remove it entirely. Wondering how many articles the site has?

well you are talking about the join that produces the 'p' table alias and it is that is a different Join:
```
if ($oldCat != 0 && ($this->element['parent'] == true || $jinput->get('option') == 'com_categories'))
{
	$query->join('LEFT', $db->quoteName('#__categories') . ' AS p ON p.id = ' . (int) $oldCat)
		->where('NOT(a.lft >= p.lft AND a.rgt <= p.rgt)');
	...
}
```
and it is activated in this case of "edit category" and not in the case of "add new category"

i speak of the join that produces the 'b' table alias , in this case it does nothing, because
1. it is left join and not an inner join so it does not limit the returned rows of the query itself
2. the table alias that it creates is 'b' but is not used anywhere in the query other than the join itself

@akfaisel the original query that you posted looks like its from "add new category"
if you you also test with "edit category" 
- does it make the same difference ?
- is anything broken ?

**Comment by stAn47** [comment] 2016-03-31 15:47
nested set model that is used to calculate rgt/lft in core joomla is exponentially slower on inserts or any changes to the tree structure compared to the adjacent model using parent_ids. i've seen sites (on j3) completely crashed upon wrong rgt/lft values at these tables due to various mysql events such as concurret inserts without locks/transactions or caused by bugs in previous joomla versions JTableNested being used too fast (inside foreach)

i already suggested to get rid of the "nested set model" but it would mean lot's of code to get reversed to the old-stable joomla 1.5

mysql itself compared to commercial solutions and my knowledge does not natively support the nested set model. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8884">issues.joomla.org/joomla-cms/8884</a>.</sub>

**Comment by franz-wohlkoenig** [comment] 2017-01-29 08:39
@ggppdk is a PR coming for testing?

**Comment by ggppdk** [comment] 2017-01-29 16:45
@franz-wohlkoenig 
Some reading my comments could make a PR, unfortunately , currently, i don't have time to do it

**Comment by franz-wohlkoenig** [comment] 2017-01-29 17:05
@ggppdk thanks for Info.

**Comment by rvbgnu** [comment] 2017-06-03 14:41
Hi @akfaisel is this is still relevant?
@ggppdk @franz-wohlkoenig

**Comment by franz-wohlkoenig** [comment] 2017-06-03 15:26
set Status on "Information Required".

**Comment by franz-wohlkoenig** [comment] 2017-06-22 08:33
If this PR get no Response, it will be closed at 23th July 2017.

**Comment by ggppdk** [comment] 2017-06-22 20:56
@franz-wohlkoenig @rdeutz
i have made a PR ...

**Comment by zero-24** [comment] 2017-06-22 20:57
thanks @ggppdk

**Closed** 2017-06-22 20:57 UTC
Labels: No Code Attached Yet

**Comment by franz-wohlkoenig** [comment] 2017-06-23 03:54
thanks @ggppdk
