### ISSUE TITLE
The very first version of an existing, first edited article is not in the version-list.

### ISSUE THREAD

**Issue by hgh-esn** [joomla/joomla-cms#6638] opened 2015-04-03 06:54 UTC
#### Steps to reproduce the issue
Activate versioning for articles in backend: articles > options > layout
Go into the article-manager. 
**Select an existing article** that **never** has been edited before.
Click the versions button.
You see that there is no entry of any existing version !!!!

Change the article and save/close it.
Open the article in editor again.
Open versions again.
You now see an version-entry of the last saved article-version, but !! the very first version of the existing article is not in the list. 

Result: **You can not recover to the very first article-version** anymore.

#### Expected result

When opening an article for edit, that has no act. versions, the article-code has to be inital-saved as the first version.
 

#### Actual result

!! The very first version of an existing first edited article is not in the version-list. 

#### System information (as much as possible)

Reported with joomla 3.4.1.
May be also in older and coming up versions.

**Comment by hgh-esn** [comment] 2015-04-03 07:10
Sorry for that !<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6638">issues.joomla.org/joomla-cms/6638</a>.</sub>

**Comment by zero-24** [comment] 2015-04-03 07:13
>Sorry for that !

@hgh-esn Does it work now?

If not an easy way to fix it would be theoretical the following:
- enable content history
- open the article
- save it
- open it again
- also the first should be there

**Comment by n9iels** [comment] 2015-04-03 07:14
When I do the following:
- Create a new article
- Save the article
- Change the article
- Save the article
There are two version of the article. One that contains the article when creating, and one when save the second time.

This only happen when you change an article that was already existing before version management was implemented (or created via the example data of Joomla!). Because the first version is made on the first save of the Article. So in my opinion it is not necessary to fix this.
Or are there people who are thinking different about this?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6638">issues.joomla.org/joomla-cms/6638</a>.</sub>

**Comment by hgh-esn** [comment] 2015-04-03 07:20
> This only happen when you change an article that was already existing before version management was implemented 

exact.
> So in my opinion it is not necessary to fix this. Or are there people who are thinking different about this?

Veto !
How do you get back to the to the very first version again?

**Comment by zero-24** [comment] 2015-04-03 07:30
@hgh-esn 

>How do you get back to the to the very first version again?

The very first version needs to be saved with content history enabled than you can also go back to this version ;)

**Comment by hgh-esn** [comment] 2015-04-03 07:36
> Does it work now? 

No, that was for deleting the label. by me.

>If not an easy way to fix it would be theoretical the following:
> -----------------------------------------------------------------------------
>enable content history
>open the article
>save it
>open it again
>also the first should be there

That could be only a temp. workaround, because it is not suported by an automatically process.
When doing this by hand, the chance is there, that it will be forgotten !

**Comment by zero-24** [comment] 2015-04-03 07:54
>No, that was for deleting the label. by me.

hehe this is `automagic` you don't do something wrong here :smile:

**Comment by zero-24** [comment] 2015-04-03 07:56
I move this here to `Needs Review` so the PLT can decide whether this should be implement or not. Thanks for your report!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6638">issues.joomla.org/joomla-cms/6638</a>.</sub>

**Comment by hgh-esn** [comment] 2015-04-03 08:14
thanks a lot

**Comment by bertmert** [comment] 2015-04-06 21:41
Just another faster workaround via Batch button:
- Filter all Articles by a single Access Level, e.g. Public
- Set Display # to All
- Select/Check all displayed articles.
- Click Batch button
- Set Access Level like above (Public).
- Click Process.

- Go on the same way with other Access Levels.

**Comment by Bakual** [comment] 2015-04-07 06:27
Closing as working as intended.
The version only is created during saving. Since the article has been created when versioning was disabled, there will not be a version saved.
When you enable the versioning, it will only start saving the versions. It will not go back and save existing versions.

**Closed by Bakual** 2015-04-07 06:27 UTC
Labels: No Code Attached Yet

**Comment by hgh-esn** [comment] 2015-04-07 07:24
> Closing as working as intended.

sorry guys, that is a wrong design!

Where is the problem to make a inital background-save, when opening an article to edit if no version-entry already exists?

**Comment by hgh-esn** [comment] 2015-04-07 07:32
> Just another faster workaround via Batch button:

bertmert, thanks for that workaround.
The is even more better than doing this explicitly, when editing an article. But so you create also a version-entry for articles, which will - may be - never being changed/saved in the future. Big websites may get a space-problem in database..

**Comment by Bakual** [comment] 2015-04-07 07:49
> Where is the problem to make a inital background-save, when opening an article to edit if no version-entry already exists?

The code to achieve this would be quite complex. You would need to query the database to see if a version exists and then initialise a store of the version. All that in the background without changing anything in the actual article (not even the modified info) when opening (?) the article.
This would be a completely different way of storing versions than we currently do.
