### ISSUE TITLE
Article Alias Can Contain Invalid Characters

### ISSUE THREAD

**Issue by eSilverStrike** [joomla/joomla-cms#19120] opened 2017-12-21 14:58 UTC
### Steps to reproduce the issue
1) Create a new article and give it the following alias:

this-is-a-“test”

2) Save the Article

3) Curly quotes are still in the alias. They should have been removed (like straight quotes are).  This results in a 404 error with Joomla when someone tries to view the article by links Joomla generates to view the article by using the alias.

### Expected result
The curly quotes should be removed. Happens with curly single quote as well (maybe others???)

### Actual result
Curly quotes are not removed

### System information (as much as possible)
Joomla 3.8.3
Microsoft-IIS/8.0 
PHP 7.1.1
Happens both in Firefox and Edge (haven't check other browsers as I don't think that is the issue)

**Comment by ghost** [comment] 2017-12-21 15:01
Can't confirm: 
![bildschirmfoto 2017-12-21 um 16 00 52](https://user-images.githubusercontent.com/8235763/34261046-2646d1d4-e668-11e7-9d6e-5cf04cd64eaf.jpg)
### System information
 3.8.4-dev
Multilanguage Site (4 Lang.) & Test English (GB) Sample Data
macOS Sierra, 10.12.6
Firefox 57 (64-bit)
#### MAMP 4.2
- PHP 7.0.22
- MySQLi 5.6.35

**Comment by C-Lodder** [comment] 2017-12-21 15:12
@franz-wohlkoenig - Try adding the quote in the actual `Alias` field as opposed to having it automatically geneerated rom the title.

**Comment by ghost** [comment] 2017-12-21 15:36
@C-Lodder done: copied "this-is-a-“test”" in alias and save got in Alias "this-is-a-test".

**Comment by brianteeman** [comment] 2017-12-21 15:43
Can not confirm

I entered this
<img width="667" alt="screenshotr15-41-13" src="https://user-images.githubusercontent.com/1296369/34262898-95be0968-e665-11e7-80a9-48c06bba7926.png">

And on save it was sanitized as this
<img width="656" alt="screenshotr15-41-36" src="https://user-images.githubusercontent.com/1296369/34262897-95a0ea2c-e665-11e7-9222-f5c9cc39e0aa.png">

**Comment by C-Lodder** [comment] 2017-12-21 15:46
@franz-wohlkoenig / @brianteeman I assume you're both on Apache as opposed to IIS

**Comment by eSilverStrike** [comment] 2017-12-21 16:26
Added a bit more info to original post. 

I just tested on a completely different website (Joomla 3.8.3) and host (which uses Linux and Apache, PHP 7.0.26)  and the same thing happened...

I was assuming it was and IIS only issue but this now appears not to be the case.

Also this was happening on previous versions of Joomla.

**Comment by brianteeman** [comment] 2017-12-21 16:38
Do you have any plugins installed - perhaps for seo?

**Comment by ghost** [comment] 2017-12-21 16:38
@C-Lodder 
### System information
 3.8.4-dev
Multilanguage Site (4 Lang.) & Test English (GB) Sample Data
macOS Sierra, 10.12.6
Firefox 57 (64-bit)
#### MAMP 4.2
- Apache-Server
- PHP 7.0.22
- MySQLi 5.6.35

**Comment by eSilverStrike** [comment] 2017-12-21 16:48
Both sites have components and plugins installed. Some well know ones like JEvents which I am sure do some SEO but I assume it would only affect their own component.

The only 3rd party component that I can think of that both sites have installed is the JCE Editor.

**Comment by brianteeman** [comment] 2017-12-21 16:50
Sorry I have no idea. It clearly doesnt happen in the joomla core as we havent been able to replicate it so it must be an extension

**Comment by ghost** [comment] 2017-12-21 17:02
closed as no Core-Issue.

@eSilverStrike Please ask further help on the [forums](https://forum.joomla.org/). 

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19120">issues.joomla.org/tracker/joomla-cms/19120</a>.</sub>

**Comment by eSilverStrike** [comment] 2017-12-21 17:29
Okay thanks.

**Comment by Bakual** [comment] 2017-12-21 17:34
Enable "Unicode Alias" in the global configuration, and you can reproduce it.

Reopening.

**Comment by brianteeman** [comment] 2017-12-21 17:38
Good spot @bakual

**Comment by ghost** [comment] 2017-12-21 17:39
Issue confirmed. Thanks for Hint, @Bakual

**Comment by Bakual** [comment] 2017-12-21 17:40
However I don't get a 404. Maybe because I have only legacy routing active.

**Comment by eSilverStrike** [comment] 2017-12-21 17:48
Confirmed as well. Issue happens when I have Unicode Aliases enabled. If disabled the curly quotes are removed from the alias.

**Comment by tonypartridge** [comment] 2017-12-21 23:56
@eSilverStrike do you have Modern routing enabled or legacy?

**Comment by eSilverStrike** [comment] 2017-12-22 00:19
Legacy is enabled.

**Comment by astridx** [comment] 2020-03-05 17:54
I just tested this issue. I think the problem is solved.

1. I have set unicode alias and am using legacy routing.
2. I have created an article with title this-is-a-“test”.
3. I did not receive a 404 error message in the front end. I could open the article.

![Global Configuration   test   Administration](https://user-images.githubusercontent.com/9974686/76009805-1be0f880-5f12-11ea-8bba-a53999ef31be.png)
![Articles  Edit   test   Administration](https://user-images.githubusercontent.com/9974686/76009806-1c798f00-5f12-11ea-8be7-45bbbb513009.png)
![Screenshot from 2020 03 05 18 48 59](https://user-images.githubusercontent.com/9974686/76009808-1d122580-5f12-11ea-8ef2-17ba4b1e5a61.png)

@eSilverStrike Can you confirm that the problem is solved?

**Comment by brianteeman** [comment] 2020-03-05 18:12
@astridx and with modern routing?

**Comment by astridx** [comment] 2020-03-05 18:57
For me, modern routing is also OK in the front end with and without id.
Which only surprises me. The IDs are displayed both times. I am not yet familiar with routing and therefore do not know whether it is related to other settings.

![Screenshot from 2020-03-05 19-54-02](https://user-images.githubusercontent.com/9974686/76015181-2227a280-5f1b-11ea-9a0e-3a9534f68d59.png)

**Comment by infograf768** [comment] 2020-03-06 07:05
Curly quotes, like any UTF8 characters, are transformed to percent encodings when unicode alias is set.

IN the browser it looks like
<img width="857" alt="Screen Shot 2020-03-06 at 08 02 03" src="https://user-images.githubusercontent.com/869724/76060107-d3acef00-5f80-11ea-90cc-46d1d7b808ae.png">

But the real result is in this case is `en/catblogenglish/testarticle-with-%E2%80%9Ccurlyquotes%E2%80%9D`

Closing as not a bug.

**Closed as completed by infograf768** 2020-03-06 07:05 UTC
Labels: No Code Attached Yet
