### ISSUE TITLE
Error in com_content after upgrading Joomla from version 5.1.4 to 5.2.0

### ISSUE THREAD

**Issue by danielcorrea** [joomla/joomla-cms#44285] opened 2024-10-16 18:32 UTC
### Steps to reproduce the issue
After the update, the frontend is functioning correctly, but the backend is experiencing a limitation: the content component only allows articles to be listed. When attempting to edit an article or create a new one, the following error appears: "0 COM_MEDIA_ERROR_ACCOUNT_NOT_FOUND".

As mentioned in issue #44277, the error might be related to the TinyMCE editor. However, even after disabling it, Joomla did not resume normal operation.

Although the error prefix suggests a connection to the Media component, I tested it, and it appears to be functioning correctly. Furthermore, I found no error logs in either the Apache logs or Joomla’s internal logs.

### System information (as much as possible)
php: Linux 6.1.0-18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64
dbserver: mysql
dbversion: 11.3.2-MariaDB-1:11.3.2+maria~deb12
dbcollation: utf8mb4_general_ci
dbconnectioncollation: utf8mb4_general_ci
dbconnectionencryption: TLSv1.3 (TLS_AES_256_GCM_SHA384)
dbconnencryptsupported: true
phpversion: 8.2.16
server: Apache/2.4.57 (Debian)
sapi_name: fpm-fcgi
version: Joomla! 5.2.0 Stable [ Uthabiti ] 15-October-2024 16:00 GMT
compatpluginenabled: true
compatpluginparameters: 
useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36

### Additional comments
URL ERROR: https://domain.com/administrator/index.php?option=com_content&view=article&layout=edit

**Comment by danielcorrea** [comment] 2024-10-16 19:06
An additional piece of information that might help understand the issue: I have Phoca Download installed, and when attempting to create a new entry, the same error occurs.
URL: https://domain.com/administrator/index.php?option=com_phocadownload&view=phocadownloadfile&layout=edit

I disabled Phoca, including its components and plugins, but the error persists.

**Comment by brianteeman** [comment] 2024-10-17 12:31
This appears to be the result of the changes made in [#43579](https://github.com/joomla/joomla-cms/pull/43579)

I can replicate the bug and if I revert the changes in that PR the bug is cleared.

Hope that helps someone to resolve the bug

**Comment by Jan-at-tetronik** [comment] 2024-10-17 12:34
Thanks Brian! :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44285">issues.joomla.org/tracker/joomla-cms/44285</a>.</sub>

**Comment by Fedik** [comment] 2024-10-17 14:13
Please follow the comment https://github.com/joomla/joomla-cms/issues/44277#issuecomment-2419663737
That should fix it for now.

**Comment by Fedik** [comment] 2024-10-17 14:15
I close this as duplicate of https://github.com/joomla/joomla-cms/issues/44285

**Closed as completed by Fedik** 2024-10-17 14:15 UTC
Labels: No Code Attached Yet

**Comment by Fedik** [comment] 2024-10-19 10:16
Please test https://github.com/joomla/joomla-cms/pull/44313
