### ISSUE TITLE
Message area does not collapse when message is dismissed

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-cms#12155] opened 2016-09-23 15:59 UTC
### Steps to reproduce the issue

Go to admin install something so you generate a message.  When the message arrives dismiss it.  The success message collapses.  I think the error message collapses too.  The information messages do not collapse.
### Expected result

The success message collapses.  I think the error message collapses too.  
The information message collapses like the other two.
### Actual result

The information messages do not collapse.

Here is a video of me doing this.  https://dl.dropboxusercontent.com/u/40004789/joomla-admin.mp4

**Comment by brianteeman** [comment] 2016-09-26 14:53
It is not an issue with the information message type. The problem is that when you have more than one message the "collapse" only happens on dismissing the first one

**Comment by uglyeoin** [comment] 2016-09-26 18:56
Ah I see, this is unusual behaviour though right?  We should try to "fix" it?  The average user will see this as a mistake in my opinion so a UX fail.  Or is this something that's unfixable?

**Comment by brianteeman** [comment] 2016-09-27 04:25
Yes it is a bug - i was just correcting your description of the issue

**Comment by Achal-Aggarwal** [comment] 2016-10-19 20:03
I think it is an issue even when you have one notification. I was able to reproduce it with one error message.
https://drive.google.com/file/d/0B3rA3UKTXpVsc1hOQmJJTG95OUU/view<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12155">issues.joomla.org/tracker/joomla-cms/12155</a>.</sub>

**Comment by infograf768** [comment] 2016-10-20 07:20
@Achal-Aggarwal 
That JED message is very specific. It is not displayed in the same <div>, i.e. `system-message-container`
There is no `Close` button for it.

**Comment by Achal-Aggarwal** [comment] 2016-10-20 14:09
@infograf768 
I can see that the message is wrapped under system-message-container only and there is a close button to close it.
<img width="1437" alt="screen shot 2016-10-20 at 7 35 43 pm" src="https://cloud.githubusercontent.com/assets/3330262/19563153/a44ecddc-96fc-11e6-86e8-82f3122715bc.png">

If I am mistaken then I guess we should fix that message as well. It is bad user experience if as a user I click on close and message does get closed but leave empty white space for nothing.

Due to limited Ui knowledge I am not sure how to fix this, but give me few hours to see what's wrong there.

**Comment by Achal-Aggarwal** [comment] 2016-10-20 18:28
It is so weird. Below change solves the problem and I don't have any idea why.

diff --git a/administrator/templates/isis/html/layouts/joomla/system/message.php b/administrator/templates/isis/html/layouts/joomla/system/message.php
index 9234171..006f5ba 100644
--- a/administrator/templates/isis/html/layouts/joomla/system/message.php
+++ b/administrator/templates/isis/html/layouts/joomla/system/message.php
@@ -13,7 +13,7 @@ $msgList = $displayData['msgList'];

 $alert = array('error' => 'alert-error', 'warning' => '', 'notice' => 'alert-info', 'message' => 'alert-success');
 ?>
-<div id="system-message-container">
+<div id="system-message-container">.
        <?php if (is_array($msgList) && $msgList) : ?>
                <?php foreach ($msgList as $type => $msgs) : ?>
                        <div class="alert <?php echo isset($alert[$type]) ? $alert[$type] : 'alert-' . $type; ?>">

**Comment by infograf768** [comment] 2016-10-23 06:04
i was speaking of the jed message, not the error message. it closes fine here

**Comment by C-Lodder** [comment] 2017-05-22 09:33
Just FYI to those who didn't see the other issue regarding this. It's to do with the Javascript here: https://github.com/joomla/joomla-cms/blob/staging/administrator/templates/isis/js/template.js#L297

**Comment by weeblr** [comment] 2017-06-03 16:18
Looking into this, #jab17<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12155">issues.joomla.org/tracker/joomla-cms/12155</a>.</sub>

**Comment by weeblr** [comment] 2017-06-03 16:52
Hi @C-Lodder 

can you point us at which other issue is related to this exactly??

Thsnks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12155">issues.joomla.org/tracker/joomla-cms/12155</a>.</sub>

**Comment by C-Lodder** [comment] 2017-06-03 16:56
The issue come from the code in the issue above. Been a while since I properly debugged this, but it's something to do with replacing `span10` with `span12` (and vice versa). I fixed this by doing the markup properly, but cannot remember exactly. Enjoy :)

**Comment by brianteeman** [comment] 2018-08-18 11:37
Looks like this has been resolved elsewhere as it can no longer be reproducced

**Closed by brianteeman** 2018-08-18 11:37 UTC
Labels: J3 Issue, No Code Attached Yet
