### ISSUE TITLE
JavaScript included before jquery

### ISSUE THREAD

**Issue by denverkurt** [joomla/joomla-cms#13077] opened 2016-12-04 08:12 UTC
i insert loadposition into content
as a result - JavaScript of module included before jquery

This problem constantly appears on various websites with Joomla![screen shot 2016-12-04 at 02 11 23](https://issues.joomla.org/uploads/1/1e21a6df388a063628bb3369435d8860.png)

**Comment by ggppdk** [comment] 2016-12-04 08:26
This is not a joomla bug, but a bug in the module

-- it is the Job of the module to load jQuery, before its own JS code that uses it,
(that is if jQuery is needed by some module)

This is done by calling (first):
```php
JHtml::_('jquery.framework');
```

In this case the module assumes that someone else has already loaded jQuery
(or the module just calls the above in wrong order)

----

Propably you have an older version of the module,
if you have latest version then report this to the module authors, they will fix it

**Comment by mbabker** [comment] 2016-12-04 17:26
Closing as not a bug.  As indicated, you need to ensure you've told Joomla to load jQuery if you need it; Joomla itself doesn't automatically load it.

**Closed by mbabker** 2016-12-04 17:26 UTC
Labels: No Code Attached Yet
