### ISSUE TITLE
Select type drop-down box is missing

### ISSUE THREAD

**Issue by fr56** [joomla/joomla-cms#20895] opened 2018-06-27 14:22 UTC
### Steps to reproduce the issue
In backend: Extensions>Manage>Manage. Click on Search Tools.

### Expected result
Select Type is one of the drop-down menus displayed

### Actual result
An empty box is displayed where the Select Type drop down should have been.

### System information (as much as possible)
Joomla 3.8.10
Isis template

### Additional comments
It's ok when using Hathor template.
This was originally reported by Alex2015 on the Joomla forum
https://forum.joomla.org/viewtopic.php?f=9&t=963139

**Comment by mbabker** [comment] 2018-06-27 14:23
Duplicate of #20881

**Closed as completed by mbabker** 2018-06-27 14:23 UTC
Labels: No Code Attached Yet
