### ISSUE TITLE
Html select element not working in Firefox when logged in on the front end and module edit is on

### ISSUE THREAD

**Issue by oorzaak** [joomla/joomla-cms#7685] opened 2015-08-12 07:12 UTC
#### Steps to reproduce the issue
You should have some kind of content that includes (a form with) a html select element. For testing you could create a custom html module containing just a select element with two options. [Edit: See next post for demo code]
Set Mouse over Edit icons to Modules and menus (in System > Global configuration)
Then, using Firefox (Windows or Mac) log into the front end as an admin and navigate to your module. Click the select element and try to select the second option.

#### Expected result
You would expect to be able to select the second option.

#### Actual result
The drop-down list containing the option items disappears as soon as you try to hover over it.

#### System information (as much as possible)
Joomla 3.4.3
Consistent on several templates: Protostar, T3 blank template, Helix framework. 
Firefox on both Windows and Mac are affected, other browsers (IE11, Chrome, Safari) are ok.

#### Additional comments
Maybe not very urgent and avoidable by using an other browser - once you know in which circumstances this issue will occur. But it can be quite annoying.
[This first post is edited after feedback from other users]

**Comment by oorzaak** [comment] 2015-08-12 07:16
Sorry, my demo code for a simple html select element was not processed as code by the issue tracker. I'll make a new attempt:

&lt;select name="test"&gt; 
 &lt;option value="1"&gt;Test 1&lt;/option&gt;
 &lt;option value="2"&gt;Test 2&lt;/option&gt;
&lt;/select&gt;<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7685">issues.joomla.org/joomla-cms/7685</a>.</sub>

**Comment by infograf768** [comment] 2015-08-12 08:48
Firefox, Macintosh, Protostar: I do not confirm this issue here:

![screen shot 2015-08-12 at 10 46 51](https://cloud.githubusercontent.com/assets/869724/9220006/8a065414-40df-11e5-852b-3db842687a4c.png)

**Comment by oorzaak** [comment] 2015-08-12 09:11
Thanks for testing. Are you sure that you did log in on the front end?

**Comment by infograf768** [comment] 2015-08-12 09:22
Yep.

**Comment by oorzaak** [comment] 2015-08-12 09:32
Thx. Strange as this issue was reported as reproduced before submitting it here by someone on http://forum.joomlacommunity.eu

**Comment by oorzaak** [comment] 2015-08-12 09:33
More specific: http://forum.joomlacommunity.eu/showthread.php?p=123085#post123085 (in Dutch language)

**Comment by MartijnMaandag** [comment] 2015-08-12 09:54
I can confirm this in FF 40.0 and a clean install of Joomla - Protostar<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7685">issues.joomla.org/joomla-cms/7685</a>.</sub>

**Comment by infograf768** [comment] 2015-08-12 10:14
My version of Firefox is 39.03. Test done on 3.4.4-dev.

**Comment by oorzaak** [comment] 2015-08-12 11:14
@infograf768 I think that this issue occurs when you are logged in at the front end as admin. In that case you will get an "Edit module" link, I think that is has something to do with this link. 

So maybe you were logged in but not as admin?

And if you can reproduce it if you are logged in as admin, I should added this info to the "Steps to reproduce".

**Comment by infograf768** [comment] 2015-08-12 11:23
I was logged as super user (admin). Edit module and menus was not implemented.
I now implemented it and, after logout-login (important!), I can reproduce the issue.

As soon as I set "Mouse-over Edit Icons for" to None, the problem disapears.

**Comment by oorzaak** [comment] 2015-08-12 11:30
Thanks, I didn't think of the option of disabling the Edit module and menus link.

I edited my first post adding this information.

**Comment by infograf768** [comment] 2015-08-12 15:00
Updated title to fit<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7685">issues.joomla.org/joomla-cms/7685</a>.</sub>

**Comment by justinherrin** [comment] 2015-08-12 15:07
I too can confirm this issue when tested with Firefox 39.0.3 and 40.0 on Mac using Protostar.

Oddly, there is some instances where things work okay...

![select-functionality-firefox](https://cloud.githubusercontent.com/assets/13225615/9227507/e8806f14-40e1-11e5-8fea-a21aca7dd97f.png)

When I visit a page with a form (either the User Profile page or Submit an Article page) the styles from the Chosen javascript file get added to the test dropdowns in my Custom HTML module and work as expected in Firefox.

Which maybe that is a separate issue of why does the Chosen styles apply to my custom drop down elements?

**Comment by infograf768** [comment] 2015-08-12 15:23
BTW, if I edit the html module concerned in frontend, the dropdown works ok in the real module. So it seems it is not only related to profile editing but any page showing an edit field.

**Comment by zero-24** [comment] 2015-08-13 11:19
>Oddly, there is some instances where things work okay...

This is because it is loaded for the edit view but not generaly with:

```
JHtml::_('formbehavior.chosen', 'select');
```

edit.php (Frontend User Edit View): https://github.com/joomla/joomla-cms/blob/staging/components/com_users/views/profile/tmpl/edit.php#L14

**Comment by dgt41** [comment] 2015-08-13 11:57
@infograf768 just remove this line: https://github.com/joomla/joomla-cms/blob/staging/media/system/js/frontediting-uncompressed.js#L125 and selects will work again.

**Comment by justinherrin** [comment] 2015-08-13 13:06
PR #7689 by @dgt41 fixes this issue.

**Comment by Bakual** [comment] 2015-08-13 13:44
Closing as we have a PR: https://github.com/joomla/joomla-cms/pull/7689

**Closed by Bakual** 2015-08-13 13:44 UTC
Labels: No Code Attached Yet
