### ISSUE TITLE
Very slow in Category view list when I added arround 30 custom fields for article

### ISSUE THREAD

**Issue by wilsontse88** [joomla/joomla-cms#17627] opened 2017-08-19 17:08 UTC
I would like to ask....why the category list view page loading time is very slow (around 10sec even i have only 10 article in category list) .

I have added around 30 custom fields for 1 article. Anyone can tell me how to solve it ??

### Steps to reproduce the issue

I added 30 custom fields for one specific category article for category list views

### Expected result
normal loading speed for category list view

### Actual result

Very slow loading in category view page e.g over 10 sec for only 10 article list in category page

### Additional comments
![screen shot 2017-08-20 at 12 59 54 am](https://user-images.githubusercontent.com/8359718/29488761-08a9f2ee-8544-11e7-8525-b6461ad48763.png)

**Comment by wojsmol** [comment] 2017-08-19 23:21
Please test with only English characters.

**Comment by wilsontse88** [comment] 2017-08-20 03:52
How about if I need to use Chinese Characters ??

**Comment by wilsontse88** [comment] 2017-08-20 04:58
I used the English Characters for the custom field and I duplicated the article to 200 copied and try to load in Category list view. Unluckily, the loading time over 1 min in the page.  does the custom field cannot over 30 items for article ??

**Comment by tonypartridge** [comment] 2017-08-20 08:00
Can you enable a Joomla! Debug mode and provide the link so we can see the output?

**Comment by wilsontse88** [comment] 2017-08-20 11:00
Sorry I can't provide the link because this is in the internal network.

But i enabled it  and it shows nothing.....

Just load over 1 min if all custom field enabled.

It made me frustrated.......

**Comment by wojsmol** [comment] 2017-08-20 13:49
@laoneo any idea about coses of this?

**Comment by ggppdk** [comment] 2017-08-20 15:43
> Just load over 1 min if all custom field enabled

trying displaying less articles in category view, e.g. with pagination
or unpublish some of the fields and retry
or both the above

Debug statistics are really needed to know more

**Comment by wilsontse88** [comment] 2017-08-20 15:48
@ggppdk ...

if with pagination, this is normal time.

But, how if I need to show all this category article in this page ?

can solve this problem if the article with custom field (over 20 custom fields) ??

I build the another new joomla3 and with 30 custom fields in article.

This situation is appeared again.  if no  custom field for article, this is normal speed in show all article.

If enable custom field , the loading time is slow.....


this is my information in developer in chrome...
![screen shot 2017-08-20 at 11 47 28 pm](https://user-images.githubusercontent.com/8359718/29496287-0ed4e692-8602-11e7-858b-260c5b7c6ef8.png)


anyone can solve it ??

thx

**Comment by brianteeman** [comment] 2017-08-20 15:53
Please enable Joomla debug in global configuration and post the results. They will be at the bottom of the page

**Comment by wilsontse88** [comment] 2017-08-20 16:07
Here are some information from debug mode

![screen shot 2017-08-20 at 11 59 42 pm](https://user-images.githubusercontent.com/8359718/29496399-893d49c2-8604-11e7-8219-67c067b1c112.png)

**Comment by wilsontse88** [comment] 2017-08-20 16:15
Here is some part screen for database queries

![screen shot 2017-08-21 at 12 14 12 am](https://user-images.githubusercontent.com/8359718/29496459-c571a82e-8605-11e7-9aee-29b4fabd7726.png)

**Comment by tonypartridge** [comment] 2017-08-20 16:18
That's not the issue. You need to look down through the queries and which ones take the longest time, these are the ones which matter.

**Comment by wilsontse88** [comment] 2017-08-20 16:24
@tonypartridge 

there a plenty of record .....and these queries are around 4.x ms ~ 0.6ms .........then ...is it related to over 30 custom field for 1 article ??

**Comment by tonypartridge** [comment] 2017-08-20 16:31
That query is fetching all customfields for that 1 article which takes 3.41ms so over 30 articles that would be 103ms which is nothing. 

You need to find where the query gets slow. They are usually backgrounder with red on the time.

Are you on Joomla! 3.7.5?

**Comment by wilsontse88** [comment] 2017-08-20 16:34
@tonypartridge 

YES, I updated to Joomla 3.7.5

do you mean this kind of information?

![screen shot 2017-08-21 at 12 33 55 am](https://user-images.githubusercontent.com/8359718/29496609-7d8da67c-8608-11e7-9573-51608868d480.png)

**Comment by wilsontse88** [comment] 2017-08-21 02:07
http://wilwil.net/dev/alex/staff-list
http://wilwil.net/dev/alex/administrator/

admin: admin  for the admin page.

Here is my another sample joomla and article also have 30 custom fields.

In this category list view, it also need to around 10sec for the categories list...

**Comment by ghost** [comment] 2017-08-21 04:29
please delete Account-Details for Security-Reasons.

**Comment by wilsontse88** [comment] 2017-08-21 06:03
@franz-wohlkoenig 

What you mean ?? 

which location of  "Account Detail"?

**Comment by ghost** [comment] 2017-08-21 06:32
> http://wilwil.net/dev/alex/administrator/
> admin: admin for the admin page.

**Comment by wilsontse88** [comment] 2017-08-21 06:36
I just want to anyone to check / verify  what I setting is wrong for this situation (Category view is very slow)

**Comment by tonypartridge** [comment] 2017-08-21 08:33
@laoneo Can you take a look at this? It appears the category view is generating a query for every single article to fetch the field values??

Surely we should be able to get these in a single query since we have the article IDs rather than doing them individually?

**Comment by laoneo** [comment] 2017-08-21 08:47
It is like that as we don't have batch events (you remember, we were discussing it at JDay UK). So there is not much we can do here, to not break BC. But having 10 extra queries should not cause such of an overhead. As you already pointed out before, there must be some queries which are causing the delay, which should be visible from the debug console.

What I would try to is to test it on a fresh joomla installation, perhaps there are other extensions interfering.

**Comment by tonypartridge** [comment] 2017-08-21 08:55
Very good point @laoneo I've just done a comparison on his site. it's only using 51.2ms for the 128 queries for the article fields, infact the DB Queries are not using much at all in the grand scheme of things.

@wilsontse88 can you disable the Joomla! Email cloak plugin?

And also you need to upgrade to PHP7. Since you are on 5.3...........

**Comment by wilsontse88** [comment] 2017-08-21 09:00
@laoneo   @tonypartridge  

 I tried to fresh joomla installation in my another webhosting server. And I  create around 30 custom fields for 1 category article.  

If i disabled the custom fields,  the loading is backed to normal.
If i enabled these custom field, the loading is 5 times compared to before. (Even my category list view is only show the title , and without intro image fields)

For the previous Joomla, my company server is set on php 5.3 and I cannot upgrade on this php version.

**Comment by tonypartridge** [comment] 2017-08-21 09:04
It’s mainly down to the email cloak plugin which I have disabled on your
site. The problem is each article is parsed so when you have custom fields
these are also parsed by the content plugins. The email cloak has some
complex regex to find the matches which really slows things down. You
should get up to a usable speed with this disabled.

But you NEED to upgrade to PHP7 asap since 5.3 is absolute and slow in
comparison to PHP7 which offers massive improvements. You can run PHP7
along side existing versions with FPM. Your head of IT / Systems should be
able to do this, otherwise you will start having support issues in the very
near future.

Many thanks
-- 
Tony Partridge

On 21 August 2017 at 10:00:39, wilsontse88 (notifications@github.com) wrote:

@laoneo <https://github.com/laoneo> @tonypartridge
<https://github.com/tonypartridge>

I tried to fresh joomla installation in my another webhosting server. And I
create around 30 custom fields for 1 category article.

If i disabled the custom fields, the loading is backed to normal.
If i enabled these custom field, the loading is 5 times compared to before.
(Even my category list view is only show the title , and without intro
image fields)

For the previous Joomla, my company server is set on php 5.3 and I cannot
upgrade on this php version.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/joomla/joomla-cms/issues/17627#issuecomment-323687574>,
or mute the thread

**Comment by wilsontse88** [comment] 2017-08-21 09:19
@tonypartridge 

Oh...that really have improvement when I disabled the "Email Cloak plugin". !!!!!!1

But I would like to ask that ...does it any problem or another issue will appear if I disable this plugin??

**Comment by tonypartridge** [comment] 2017-08-21 09:50
If your website is public facing and you have email addresses then I would
advise you use the regular labs email cloak plugin. Otherwise, no it has no
effect. The idea of the plugin is to wrap emails in html/js so bots cannot
pick them up in simple terms.

Many thanks
-- 
Tony Partridge

On 21 August 2017 at 10:19:57, wilsontse88 (notifications@github.com) wrote:

@tonypartridge <https://github.com/tonypartridge>

Oh...that really have improvement when I disabled the "Email Cloak plugin".
!!!!!!1

But I would like to ask that ...does it any problem or another issue will
appear if I disable this plugin??

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/joomla/joomla-cms/issues/17627#issuecomment-323692184>,
or mute the thread

**Comment by tonypartridge** [comment] 2017-08-21 22:38
Can we get a close on this?

**Comment by wilsontse88** [comment] 2017-08-22 01:35
Excuse me, I would like to ask...does it normal if the page loading time around 5~7sec . even i stop the email cloaking plugin?

I will clone the joomla for the external hosting later..... and hope all of you can help me to check it.

**Comment by ghost** [comment] 2017-08-22 04:37
closed as stated above. @wilsontse88 please ask further help on the [forums](https://forum.joomla.org/). This repository concerns Joomla coding.


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17627">issues.joomla.org/tracker/joomla-cms/17627</a>.</sub>

**Closed as completed by ghost** 2017-08-22 04:37 UTC
Labels: No Code Attached Yet

**Comment by ggppdk** [comment] 2017-08-22 05:05
@wilsontse88 

> Excuse me, I would like to ask...does it normal if the page loading time around 5~7sec . even i stop the email cloaking plugin?

- When you upgrade both server and PHP version from 5.3 to PHP 7 you will get , much lower load times
- Plus you should enable Joomla progressive / conservative caching

About email cloak plugin, it surely needs improving, even if this means making some trade-off
