### ISSUE TITLE
Sidebar div pushed up against content title

### ISSUE THREAD

**Issue by ChristopherRaymond** [joomla/joomla-cms#6178] opened 2015-02-25 14:47 UTC
#### Steps to reproduce the issue
Login to Admin --> Articles

#### Expected result

http://awesomescreenshot.com/0564hitm99

#### Actual result

http://awesomescreenshot.com/0c64hijg15

#### System information (as much as possible)

MAC v 10.6.8
Firefox v 35.0.1
Chrome v 40.0.2214.111

#### Additional comments

CSS fix:

.j-sidebar-container {
    margin: -2px 0 0 -1px;
}

**Comment by brianteeman** [comment] 2015-02-25 14:59
The problem appears to be that you have changed the admin template
See screenshot http://awesomescreenshot.com/0914hj3ucf


On 25 February 2015 at 14:47, ChristopherRaymond <notifications@github.com>
wrote:

> Steps to reproduce the issue
>
> Login to Admin --> Articles
> Expected result
>
> http://awesomescreenshot.com/0564hitm99
> Actual result
>
> http://awesomescreenshot.com/0c64hijg15
> System information (as much as possible)
>
> MAC v 10.6.8
> Firefox v 35.0.1
> Chrome v 40.0.2214.111
> Additional comments
>
> CSS fix:
>
> .j-sidebar-container {
> margin: -2px 0 0 -1px;
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6178>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by ChristopherRaymond** [comment] 2015-02-25 15:07
That is correct Brian. I disabled the "Display Header" within the Template Manager for the ISIS admin template.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6178">issues.joomla.org/joomla-cms/6178</a>.</sub>

**Comment by brianteeman** [comment] 2015-02-25 15:09
Found it

In template manager select styles and then Isis
In the advanced tabs scroll down to Display Header
You have the setting at No. Change it back to the default Yes<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6178">issues.joomla.org/joomla-cms/6178</a>.</sub>

**Comment by brianteeman** [comment] 2015-02-25 15:10
Looks like we posted at the same time ;)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6178">issues.joomla.org/joomla-cms/6178</a>.</sub>

**Comment by brianteeman** [comment] 2015-02-25 15:14
I did a quick test of your change and it seems to be good in both scenarios

Since you seem to know where the issue is, can you create a Pull Request?
See https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests for how to do it. We can help you if you have questions.
This way it can be tested.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6178">issues.joomla.org/joomla-cms/6178</a>.</sub>

**Comment by ChristopherRaymond** [comment] 2015-02-25 15:17
Typically I disable that header. Perhaps only a handful do as well. No worries thanks Brian.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6178">issues.joomla.org/joomla-cms/6178</a>.</sub>

**Comment by ChristopherRaymond** [comment] 2015-02-25 19:25
Since you seem to know where the issue is, can you create a Pull Request?
See https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests for how to do it. We can help you if you have questions.
This way it can be tested.

Sorry Brian had to disconnect for a little and take care of something. I will create a pull request for this. Thx.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6178">issues.joomla.org/joomla-cms/6178</a>.</sub>

**Comment by JoomliC** [comment] 2015-02-26 00:55
I don't think the best way to solve this is to change margin, which will not give a good design if header is enabled.

My question is : don't you think that if an option is supposed to hide the header (title + joomla logo) it is supposed to not display the title ?

Maybe it would be better to remove those line in index.php : 
<pre>					// Show the page title here if the header is hidden
					if (!$displayHeader) : ?>
						<h1 class="content-title"><?php echo JHtml::_('string.truncate', $app->JComponentTitle, 0, false, false); ?></h1>
					<?php endif; ?></pre>
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6178">issues.joomla.org/joomla-cms/6178</a>.</sub>

**Comment by ChristopherRaymond** [comment] 2015-02-26 14:32
@JoomliC I understand your point. I prefer the title to still be present, although a case could be made for removing it completely if the title+header option is disabled.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6178">issues.joomla.org/joomla-cms/6178</a>.</sub>

**Comment by ChristopherRaymond** [comment] 2015-02-27 19:28
Okay submitted the pull request #6222 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6178">issues.joomla.org/joomla-cms/6178</a>.</sub>

**Comment by JoomliC** [comment] 2015-03-02 01:16
I think we can close here, as we have a PR in process : https://github.com/joomla/joomla-cms/pull/6222
Thanks @ChristopherRaymond ! ;-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6178">issues.joomla.org/joomla-cms/6178</a>.</sub>

**Comment by brianteeman** [comment] 2016-03-11 14:49
@JoomliC @ChristopherRaymond I'm a little confused has this been resolved?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6178">issues.joomla.org/joomla-cms/6178</a>.</sub>

**Comment by JoomliC** [comment] 2016-03-13 00:08
@brianteeman Me too...
The issue reported is not solved, but the PR was opened and closed for one reason i didn't really understand (i think it was an error : https://github.com/joomla/joomla-cms/pull/6222#issuecomment-88533655), as @ChristopherRaymond was doing its best to understand how to use generatecss.php, and to finalize his PR with a minor padding-bottom fix (even if i think that if option is supposed to show/hide Header, i still wonder why the title is displayed if the header is set to Hide...).

Maybe wait a few days if @ChristopherRaymond want you to reopen PR #6222 and want to update the PR (two files changed to be reverted, and only one line to be added to Isis template.less before to process generatecss.php)...

My two-penn'orth : a logic and easy way to fix this issue is to remove code from index.php to display nothing when Header is set to Hide (we don't display a container, so seems logic to not display a part of its content, no ?) : https://github.com/joomla/joomla-cms/pull/6222#issuecomment-76564753
;-)
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6178">issues.joomla.org/joomla-cms/6178</a>.</sub>

**Comment by roland-d** [comment] 2016-05-17 20:04
@JoomliC A few days have past, and no reply to this. Would you mind doing the PR so we can get this fixed? Thank you.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6178">issues.joomla.org/joomla-cms/6178</a>.</sub>

**Comment by JoomliC** [comment] 2016-05-18 17:22
@roland-d Yes i can, but my proposal is to fix logic, not display: https://github.com/joomla/joomla-cms/issues/6178#issuecomment-76102122
I can do one or the other (removal or a bit more margin if header disabled) but don't know what would be the accepted change (my proposal seems logical based on the option purpose : to hide all the header, and no keep parts of it. But if logic, then we miss the page title somewhere, and the current structure of the Isis template does not allow easy flexibility...

**Comment by JoomliC** [comment] 2016-05-18 17:43
@roland-d To be clear, to screenshots ;-)

Current issue, when Isis Option "**Display Hearder**" to on <code>No</code>:
![capture d ecran 2016-05-18 a 19 38 43](https://cloud.githubusercontent.com/assets/2385058/15368864/527ccc66-1d30-11e6-8fcb-d0b2fd54270b.png)


**1. Removal of page title** (but even if logic with option purpose, the page title will miss... so maybe not so good):
![capture d ecran 2016-05-18 a 19 36 30](https://cloud.githubusercontent.com/assets/2385058/15368810/0cfc0eae-1d30-11e6-857d-96aa235c0c90.png)


**2. Keep page title, but additional styling for sidebar** (and correct html placement of page title):
![capture d ecran 2016-05-18 a 19 35 38](https://cloud.githubusercontent.com/assets/2385058/15368903/7e10b32e-1d30-11e6-86eb-f4772fb3c161.png)
But in case 2 and current state: no space benefit to hide header...

So 1 or 2 , ;-)

**Comment by roland-d** [comment] 2016-05-20 13:22
@JoomliC Thank you for the clear explanation. I have tested the option and how it looks etc. Now I have a good understanding of the whole issue. Let's go with option 1 because option 2 makes no sense if you decide to hide the bar it shouldn't show up somewhere else. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6178">issues.joomla.org/joomla-cms/6178</a>.</sub>

**Comment by JoomliC** [comment] 2016-05-20 15:40
This issue could be closed, as we have a new PR : https://github.com/joomla/joomla-cms/pull/10563
;-)

And +1 with option 1 👍

**Comment by roland-d** [comment] 2016-05-20 15:41
Closing this in favor for #10563

**Closed by roland-d** 2016-05-20 15:41 UTC
Labels: No Code Attached Yet
