### ISSUE TITLE
Add option to disable updating "midifed" and "modified by" fields values in "content" table

### ISSUE THREAD

**Issue by yild** [joomla/joomla-cms#10872] opened 2016-06-20 10:01 UTC
ATM any article modification by any user change 'modified' and 'modified by' fields - actualy every 'save' operation do this.

I think useful option would be to allow administrators to disable (disable/enable - default enabled) this function for groups like:

changing article:
	article content, article title;
	additional settings on content tab (from backend side) 'featured', 'language', 'category' and so on;
	publishing tab (all fields);
	and so on;
	
In addition this settings should be used with batch operations, maybe even ad a checkbox "Don't change 'modified' date/time and 'modified by'" on batch operations form.

### What for:

Currently if i.e. admin change article category, article it's marked as modified - 'modified' field populates with datetime when we hit 'save' button - but did we change article itself ? Does it contents changed or title? No...
Same goes for 'options' tab, changing single option require to use 'save' that will set new 'modified', 'modified by' values.
Alternative is to do some operations at DB level... that's annoying and sometimes dangerous (ie permissions).

**Comment by brianteeman** [comment] 2016-06-20 10:25
I disagree - you *have* modified the article

On 20 June 2016 at 11:01, yild <notifications@github.com> wrote:

> ATM any article modification by any user change 'modified' and 'modified
> by' fields - actualy every 'save' operation do this.
>
> I think useful option would be to allow administrators to disable
> (disable/enable - default enabled) this function for groups like:
>
> changing article:
> article content, article title;
> additional settings on content tab (from backend side) 'featured',
> 'language', 'category' and so on;
> publishing tab (all fields);
> and so on;
>
> In addition this settings should be used with batch operations, maybe even
> ad a checkbox "Don't change 'modified' date/time and 'modified by'" on
> batch operations form.
> What for:
>
> Currently if i.e. admin change article category, article it's marked as
> modified - 'modified' field populates with datetime when we hit 'save'
> button - but did we change article itself ? Does it contents changed or
> title? No...
> Same goes for 'options' tab, changing single option require to use 'save'
> that will set new 'modified', 'modified by' values.
> Alternative is to do some operations at DB level... that's annoying and
> sometimes dangerous (ie permissions).
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/10872>, or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8SWqRBTH93047En1ecpRjURJBbagks5qNmUJgaJpZM4I5i0s>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by mbabker** [comment] 2016-06-20 12:26
The modified column isn't something that tracks specifically the article text's modification date.  It is a column that's updated anytime anything with the associated record (in the case of articles that'd be the article text, metadata, images/URLs fields, etc.) is updated and the user who performed the last update is also noted.

**Comment by yild** [comment] 2016-06-20 14:37
Yes I know that this is a table record mark 'record was modified ... modified by' but how this correspond to sort (i.e.) articles by modified date, list modified articles in 'articles - category' module by modified date?
That mean that any insignificant to visitors modification by 'staff' is marked as recent change.

I'm not saying that last modified date and by who isn't useful - especial when you want to find someone who 'broke' something...

Maybe add new field to store only 'content' modifications.
That way we can have 'admin' info - last record modification info, and visitors could see 'content' modification info.

Just a thought.

**Comment by mbabker** [comment] 2016-06-20 14:51
To me that's excessive for a core feature to have arbitrary tracking of modification times based on a set of fields.  If it's something you really need I'd suggest a plugin to track this personally (and yes I know even going that route you couldn't alter the core component/module behaviors to use that instead).

Then again according to some I only use Joomla as a developer so take my feedback with a grain of salt.

**Comment by brianteeman** [comment] 2016-07-28 14:24
I am closing this. The feature is working as intended and it is going to create an incredibly complex system to achieve what you want by excluding some fields and not other fields and allow the configuration of that in a manner to satisfy all possibilities<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10872">issues.joomla.org/joomla-cms/10872</a>.</sub>

**Closed** 2016-07-28 14:24 UTC
Labels: No Code Attached Yet
