### ISSUE TITLE
[4.0] Character counter short-and-sweet hides meta description when too long in database

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#35018] opened 2021-08-01 23:17 UTC
During migration of some "living" J3 pages clones to J4 I recognized that some fields `Meta Description` in articles look empty. But they aren't empty tells me the browser inspector. The character counter that is activated (not overridable and not configurable) for all core fields of `name="metadesc"` stupidly hides the text and stupidly shows a message "`160 characters remaining of 160 characters`".

This happens whenever a database field `metadesc` of an article has more than 160 characters.

### Steps to reproduce the issue
- Create an article. Enter 160 Characters in field `Meta Description`.
- Save.
- Go into databse table `#__content` edit the article entry by copying the `metadesc` to double length or so.
- Inspect the article again:

![02-08-_2021_01-07-42](https://user-images.githubusercontent.com/20780646/127788008-61cc9a13-ab45-4148-a6cc-7ce090b7e3bc.jpg)

### Expected result
- A character counter shouldn't cut _**existing**_ text and not hide **_existing_** text. Users must have a possibility to correct their Meta Descriptions (and only if they want to). Therefore they must see it in full length.
- A core-side limitation of the length without the possibility of configuration is a no-go. No one knows whether the default length of 160 characters is also recommended for the future.
- There is only the possibility to manipulate the JLayout textarea.php, but not in a flexible way.

### Actual result
- See image and description above

**Comment by brianteeman** [comment] 2021-08-02 06:46
This is actually not because of the shortandsweet javascript

The field has a maxlength of 160 defined in the xml

**Comment by coolcat-creations** [comment] 2021-08-02 11:01
Thats not good, there are different recommendations for the desc and the administrator should be able to set an own limit or disable the limit. Last year there were even recommendations for 270 chars - now we are back to 156.

**Comment by ReLater** [comment] 2021-08-02 14:24
> This is actually not because of the shortandsweet javascript

Believe me that I have tested that in detail before I post statements like above. When the character counter is disabled then you see the whole text. If enabled you see **_nothing_**. But you see whole text in browser inspector.

Used current Firefox

Follow my test instructions. Go to articles.xml. Remove `charcounter="true"`. Let the rest like it is. Then open the article in BE.

![02-08-_2021_16-22-21](https://user-images.githubusercontent.com/20780646/127876831-6b918e81-6c13-4466-828b-e3a0f893bd5e.jpg)

**Comment by ReLater** [comment] 2021-08-02 15:15
> Last year there were even recommendations for 270 chars - now we are back to 156.

There were also tests that made clear that the recommendations differ extremely between mobile and desktop search views and from search engine to se.

We use our custom, half-assed and ugly char counter plugin on all sites (but not a11y). Therefore a global override of textarea.php is not a problem for us to get rid of the core counter. But at least existing texts shouldn't be cropped or invisible; for any user. And the global override is not a practicable solution for all sites and users.

**Comment by brianteeman** [comment] 2021-08-02 15:27
retested without charcount=true and the ability to type text stops after 160 chars

**Comment by ReLater** [comment] 2021-08-02 15:34
> and the ability to type text stops after 160 chars

That's not what I'm talking about. I talk about existing meta descriptions, not newly created ones. In my test scenario you get the old description, _**you see it**_ and can save the article without changing it. Length not cropped.

**Comment by ReLater** [comment] 2021-08-02 15:36
Sometimes I wonder why we have to provide testing instructions...

**Comment by brianteeman** [comment] 2021-08-02 15:54
unsubscribe

**Comment by dgrammatiko** [comment] 2021-08-03 14:54
There's a PR upstream: https://github.com/rikschennink/short-and-sweet/pull/5

I can't fix it in this repo as the bug is not in our codebase 🤷‍♂️

**Comment by ChristineWk** [comment] 2021-08-03 21:09
Unfortunately can't be of any help because I don't understand enough about it. Thanks for your investigation @dgrammatiko

**Comment by rikschennink** [comment] 2021-08-04 07:34
Merged the upstream PR, couldn't reproduce the issue, so should it remain, please provide a plain HTML test case and I'm happy to investigate.

**Comment by dgrammatiko** [comment] 2021-08-04 08:26
@rikschennink thanks for merging the PR!

@ReLater please test https://github.com/joomla/joomla-cms/pull/35039

**Comment by alikon** [comment] 2021-08-04 08:40
closing

**Closed as completed by alikon** 2021-08-04 08:40 UTC
Labels: No Code Attached Yet
