### ISSUE TITLE
TemplateName fieldtype

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#9850] opened 2016-04-11 14:04 UTC
In the Templates Styles menu are two search filters
Location and Template

When location is set to admin the template filter only shows the admin templates
When location is set to site the template filter only shows the site templates

BUT
When location is not set the template filter only shows the site templates it should display all the templates

**Comment by Bakual** [comment] 2016-04-11 14:24
It shows styles from admin and site for me as expected. Am I missing something to reproduce the issue?

**Comment by brianteeman** [comment] 2016-04-11 14:27
What does it show when NO location is set

On 11 April 2016 at 15:24, Thomas Hunziker <notifications@github.com> wrote:

> It shows styles from admin and site for me as expected. Am I missing
> something to reproduce the issue?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9850#issuecomment-208371712>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by SharkyKZ** [comment] 2016-04-11 16:26
Can't reproduce this on 3.5.1. Shows all template styles.

**Comment by polakluk** [comment] 2016-04-11 17:07
Hi, I checked this on 3.5.1. and @brianteeman  is right. It does only show Admin templates. See the attached screen
![bug](https://cloud.githubusercontent.com/assets/1931353/14435507/85a8361e-0018-11e6-945e-f5486b992be3.png)

**Comment by brianteeman** [comment] 2016-04-11 17:07
Weird I cant replicate it now either<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9850">issues.joomla.org/joomla-cms/9850</a>.</sub>

**Comment by brianteeman** [comment] 2016-04-11 17:09
Sorry I am an idiot I retested the wrong site ;(


The issue is exactly as shown in the screenshot from @polakluk<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9850">issues.joomla.org/joomla-cms/9850</a>.</sub>

**Comment by polakluk** [comment] 2016-04-11 17:36
So, the fix is easy:
in file administrator/components/com_templates/helpers/templates.php, 2 lines have to be changes:

line 80:
from
public static function getTemplateOptions($clientId = '*')
to
public static function getTemplateOptions($clientId = null)

line 86
from:
if ($clientId != '*')
to
if ($clientId != null)

The other way to fix this is to set filter.client_id to '*' by default at all places in code which is, in my opinion, a bit of a overkill for this. What do you think?

I can create pull-request once I get back home.

**Comment by brianteeman** [comment] 2016-04-11 17:37
Whatever you think is best

**Comment by andrepereiradasilva** [comment] 2016-04-11 17:39
See https://github.com/joomla/joomla-cms/pull/9853

**Comment by Bakual** [comment] 2016-04-11 17:46
Ah, misunderstood the issue. I see it now as well.

**Comment by Bakual** [comment] 2016-04-11 17:47
Closing as we hace a PR

**Closed by Bakual** 2016-04-11 17:47 UTC
Labels: No Code Attached Yet
