### ISSUE TITLE
[4.0] Error in articles

### ISSUE THREAD

**Issue by ced1870** [joomla/joomla-cms#24735] opened 2019-04-27 09:33 UTC
### Steps to reproduce the issue

Try to go in the articles

### Expected result

no error

### Actual result

error

### System information (as much as possible)

Joomla 4 alpha 8, PHP 7.3.1

### Additional comments

I have removed all external plugins and extensions. When I click on the articles menu I get this error 

An error has occurred.

    0 Argument 1 passed to Joomla\Utilities\ArrayHelper::getColumn() must be of the type array, bool given, called in C:\wamp64\www\joomla4-1\administrator\components\com_content\Model\ArticlesModel.php on line 519 

And I can not access anything in the articles

**Comment by ced1870** [comment] 2019-04-27 09:34
PS : if I go directly to /index.php?option=com_content&view=article&layout=edit, no error
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24735">issues.joomla.org/tracker/joomla-cms/24735</a>.</sub>

**Comment by ReLater** [comment] 2019-04-27 10:30
I can't reproduce the issue with [nightly build](https://developer.joomla.org/nightly-builds.html) of today: Joomla_4.0.0-alpha9-dev, built: Saturday, 27 April 2019 02:00:48 UTC

![27-04-_2019_12-27-37](https://user-images.githubusercontent.com/20780646/56848356-4a507900-68e8-11e9-9b43-5dec8765958d.jpg)

**Comment by ced1870** [comment] 2019-04-27 11:38
thanks for checking
I have jjust resinstalled the core files, with no luck ... I will investigate and let you know

**Comment by brianteeman** [comment] 2019-04-28 08:59
Not core files - you need to make sure the database is up to date as well

**Comment by ced1870** [comment] 2019-04-28 09:18
thanks Brian :) that was it.

**Comment by alikon** [comment] 2019-04-28 09:26
closing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24735">issues.joomla.org/tracker/joomla-cms/24735</a>.</sub>

**Closed as completed by alikon** 2019-04-28 09:26 UTC
Labels: No Code Attached Yet, J4 Issue
