### ISSUE TITLE
Cannot login to Jooml backend as an administrator - infinite login loop

### ISSUE THREAD

**Issue by vovkss** [joomla/joomla-cms#22128] opened 2018-09-11 12:43 UTC
I've installed Joomla and started configuring the site. 
After changing the Administrator user's name (not login name!) I could no longer login into the site's backend (domain.name/administrator). 

Entering correct credentials just lead to the login page again. 
However, Joomla reacted to incorrect credentials - in this case, a message was displayed: "Username and password do not match or you do not have an account yet." 

I've searched the internet for this problem and found many different reasons, double-checked all suggestions and nothing helped. In particular, the required modules were enabled, tried disabling .htaccess, etc. 

In a HTTP debugger I've noticed that there were multiple session cookie names at the same time. 

After some digging, I've found the file `libraries/src/Session/Session.php` and line 920: 

			$this->_handler->setName(md5($options['name']));

The debugger showed that `$options['name']` is _already_ an md5-hash calculated elsewhere (`CMSApplication.php`, line 738: `'name'      => \JApplicationHelper::getHash($this->get('session_name', get_class($this)))`). 

I removed `md5` and everything works fine now, i.e. changed `libraries/src/Session/Session.php`, line 920 to: 

			$this->_handler->setName($options['name']);

**Comment by mbabker** [comment] 2018-09-11 12:50
While inefficient, double md5 hashing would not be creating your particular issue.  I honestly feel like your change is more of a coincidence that things "work fine now" than actually fixing a bug, and if there were a bug related to that operation it would be something that could be consistently reproduced (and have been reported before now).

**Comment by PhilETaylor** [comment] 2018-09-15 20:53
more like the cookie_* vars in the /configuration.php file had been incorrectly set and not left as blank strings. 99% of the time this login loop with no error message is due to that.

**Comment by Quy** [comment] 2018-10-13 00:13
Closing for now. If this is still an issue, please advise.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22128">issues.joomla.org/tracker/joomla-cms/22128</a>.</sub>

**Closed as completed by Quy** 2018-10-13 00:13 UTC
Labels: No Code Attached Yet
