### ISSUE TITLE
UX problem during installation

### ISSUE THREAD

**Issue by mozaffar** [joomla/joomla-cms#35273] opened 2021-08-21 04:38 UTC
### Steps to reproduce the issue
1. Start to install joomla 4
2. In admin personal info step, enter invalid password (e.g. short length password)
3. Click save and next
4. Enter DB information
5. Click Save and next

### Expected result
It is expected to display an error for password and scroll to the error

### Actual result
Displays the error but stay at the end of page an does not scroll to top

### System information (as much as possible)
Linux Fedora 34, Apache

**Comment by PhilETaylor** [comment] 2021-08-21 06:27
duplicate of https://github.com/joomla/joomla-cms/issues/29325

**Comment by richard67** [comment] 2021-08-21 10:34
Closing as duplicate report. See #29325 .<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35273">issues.joomla.org/tracker/joomla-cms/35273</a>.</sub>

**Closed as completed by richard67** 2021-08-21 10:34 UTC
Labels: No Code Attached Yet
