### ISSUE TITLE
Cannot move admin menu items during Batch process

### ISSUE THREAD

**Issue by Sulpher** [joomla/joomla-cms#28925] opened 2020-05-04 09:41 UTC
### Steps to reproduce the issue
I've created admin menu and added a few menu items.
Now I want to move these items to another admin menu.
I am checking a few menu items and clicking on "Batch" button.

![Screen Shot 2020-05-04 at 12 36 52](https://user-images.githubusercontent.com/3432048/80953508-5bd63600-8e04-11ea-9002-26d24b0ff2fd.png)
![Screen Shot 2020-05-04 at 12 37 04](https://user-images.githubusercontent.com/3432048/80953512-5e389000-8e04-11ea-8165-31d183488de4.png)
![Screen Shot 2020-05-04 at 12 37 15](https://user-images.githubusercontent.com/3432048/80953518-609aea00-8e04-11ea-8e8d-e9a076776b63.png)

### Expected result
There should be a button to confirm the action.

### Actual result
There is just "Cancel" button. I cannot finalize the process of moving.

### System information (as much as possible)

Joomla 3.9.18

**Comment by infograf768** [comment] 2020-05-04 10:43
Confirmed

It looks like a published admin menu item gets `""` (empty) for the variable `$published` instead of `> 0`, i.e. 1
code is
`<?php if ((strlen($menuType) && $menuType != '*' && $clientId == 0) || ($published > 0 && $clientId == 1)): ?>`

**Comment by zero-24** [comment] 2022-01-31 22:42
Closing as there is a PR: #36907 by @brianteeman thanks!

**Closed as completed by zero-24** 2022-01-31 22:42 UTC
Labels: No Code Attached Yet
