### ISSUE TITLE
joomla admin broken

### ISSUE THREAD

**Issue by mikajaxxx** [joomla/joomla-cms#35697] opened 2021-09-28 22:46 UTC
### Steps to reproduce the issue
install joomla 4
log into administrator 
admin panel is broken with some js errors in console.

the attachment is clear![screen shot 2021-09-28 at 22 46 18](https://issues.joomla.org/uploads/1/d24662ec8c79b5a12d210e9b29f1dfaf.jpg)

### Expected result
admin panel must working

### Actual result
admin panel is broken

### System information (as much as possible)
joomla 4.0.3
openlitespeed server
php 7.3 last update

### Additional comments
After  a few ctl+f5 suddenly it works but by repeating ctl+ f5 it will brokes again

**Comment by brianteeman** [comment] 2021-09-28 22:59
This is a server problem regarding pre-compressed content

**Comment by mikajaxxx** [comment] 2021-09-28 23:13
Could you please tell me what we should to do ?
i am using directadmin + openlitespeed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35697">issues.joomla.org/tracker/joomla-cms/35697</a>.</sub>

**Comment by mikajaxxx** [comment] 2021-09-28 23:33
I am running joomla 3 , prestashop & wordpress on the same server with no problem<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35697">issues.joomla.org/tracker/joomla-cms/35697</a>.</sub>

**Comment by brianteeman** [comment] 2021-09-28 23:38
Yes this is a change in Joomla 4. The change and explanation is made here #23385

https://github.com/joomla/joomla-cms/blob/66df66db732c42a8cbba7faead8ccf18621069a3/htaccess.txt#L134-L166

**Comment by mikajaxxx** [comment] 2021-09-28 23:43
what we should do to solve this on openlitespeed?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35697">issues.joomla.org/tracker/joomla-cms/35697</a>.</sub>

**Comment by dgrammatiko** [comment] 2021-09-29 08:46
@mikajaxxx could you try the solution from https://github.com/wp-media/wp-rocket/issues/2767 and report back?

**Comment by mikajaxxx** [comment] 2021-09-29 15:52
@dgrammatiko Ofcourse. but no improvement! 
also i realized if i turn on debug, problem temporary solved but two js files related to debug widget not working! (screen shot attached)
I think gzip compression for admin panel must be removed right now! stability have much more priority than Speed! Speciall![screen shot 2021-09-29 at 15 52 33](https://issues.joomla.org/uploads/1/2cd29fb711d4c7c1caf4c3ca20076f16.jpg)y for admin Area.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35697">issues.joomla.org/tracker/joomla-cms/35697</a>.</sub>

**Comment by dgrammatiko** [comment] 2021-09-29 16:47
> I think gzip compression for admin panel must be removed right now!

Gzip is by default disabled for PHP and for static assets unless you rename the htaccess.txt to `.htaccess`. The problem is not Gzip here, it's a misconfiguration of the server and there are 2 different solutions:
- comment the part for pre gzipped files
- fix your server to serve correctly the **existing** gzipped files

**Comment by mikajaxxx** [comment] 2021-09-29 17:45
@dgrammatiko The serer is running on Openlitespeed ( fast & famous web services) also i have no problem with other cms including j3. teh only problem is j4 & my server support gzip very well.
could you please clearfy where i should comment pre gzipped files??? in which section of joomla and which lines? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35697">issues.joomla.org/tracker/joomla-cms/35697</a>.</sub>

**Comment by dgrammatiko** [comment] 2021-09-29 17:54
Brian already shared the part of htaccess that controls the behaviour: https://github.com/joomla/joomla-cms/issues/35697#issuecomment-929700648

I'll say again that the problem is your server's settings. Apache, NGINX support pre gzipped static assets, and as far as I checked also Litespeed so your server is wrongly configured.

**Comment by brianteeman** [comment] 2021-09-29 18:07
https://fossies.org/linux/openlitespeed/dist/docs/ServTuning_Help.html#enableGzipCompress

**Comment by jwaisner** [comment] 2021-10-01 05:34
As this is not a bug but an issue with the server configuration I will close this report.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35697">issues.joomla.org/tracker/joomla-cms/35697</a>.</sub>

**Closed as completed by jwaisner** 2021-10-01 05:33 UTC
Labels: No Code Attached Yet
