### ISSUE TITLE
J4.2.4 - Error renaming to existing categories from menu modal

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#39150] opened 2022-11-04 11:38 UTC
### Steps to reproduce the issue
Create at least two Categories 
Create a Menu item and link it with Category Blog to one of the Categories
In the Menu item click on "edit" next to the Category Field and rename the category and its alias to the other existing category

### Expected result
The expected result is that you cannot save and close this because a error message should appear and prevent the dialog from Save and close because the category name / alias is taken. Sometimes the error even shortly appears before the modal closes. But it's going to fast to recognize. On a fast Server you don't see an error at all.

### Actual result
In this Video it looks like renaming was successful but it isn't because the category name is taken:
https://vimeo.com/767253215/034c0e05a6

### System information (as much as possible)
Joomla 4.2.4
PHP 8.0

### Additional comments
It was an UX Flaw during Joomla4Kids Week

**Comment by chmst** [comment] 2022-11-05 10:18
Confirmed. The modal must remain open when a message is active. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39150">issues.joomla.org/tracker/joomla-cms/39150</a>.</sub>

**Comment by heelc29** [comment] 2022-11-07 15:55
Please test #39173

**Comment by alikon** [comment] 2022-11-07 16:08
closing as we have a pr to test #39173

**Closed as completed by alikon** 2022-11-07 16:08 UTC
Labels: No Code Attached Yet, bug

**Comment by wojtekxtx** [comment] 2022-11-07 22:59
@alikon As #39173 is not merged, this issue is not completed. Do not close issues when related PR has not been merged/closed w/o merging.

Use [linking](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) to relate issues to PRs. This way once all linked PRs gets merged, all issues linked from within gets closed alltogether.

**Comment by brianteeman** [comment] 2022-11-07 23:13
no -

**Comment by wojtekxtx** [comment] 2022-11-07 23:17
@brianteeman what?

**Comment by alikon** [comment] 2022-11-08 08:06
@wojtekxtx we close an issue when there is a pull request

please test it #39173
thanks in advance

**Comment by wojtekxtx** [comment] 2022-11-08 08:09
@alikon linking was introduced by GitHub for a reason. Not because they had to for the sake of introducing..... btw its very useful in scenerios like here.

Your current way of doing things is, well, stupid.

**Comment by coolcat-creations** [comment] 2022-11-08 08:27
@wojtekxtx it was always done like that in Joomla, but I like the way you describe more, maybe there is a way to change this process in Joomla because this way, when a PR got closed, weh still know the issue still exists. @bembelimen

**Comment by brianteeman** [comment] 2022-11-08 08:46
If a pr is closed without merging the original issue is always reopened.

If an issue is closed as a duplicate it is always linked to the original.

This way discussion on the fix only occurs in one place

**Comment by brianteeman** [comment] 2022-11-08 09:08
If a pr is closed without merging the original issue is always reopened.

If an issue is closed as a duplicate it is always linked to the original.

This way discussion on the fix only occurs in one place
