### ISSUE TITLE
[4.0] TypeError: Cannot read property 'style' of null

### ISSUE THREAD

**Issue by roland-d** [joomla/joomla-cms#17915] opened 2017-09-09 20:21 UTC
### Steps to reproduce the issue
1. Enable Inspector in Chrome
2. Go to the Control Panel in Joomla
3. Wait for the popup notifications to show
4. Check the Console tab of the Inspector
5. The error is shown there

### Expected result
No errors

### Actual result
Error is shown:
Uncaught TypeError: Cannot read property 'style' of null
    at HTMLDocument.<anonymous> (flying-focus.min.js?7a338ea4a2cd5df7edb93e870b062de1:1)
    at HTMLElement.connectedCallback (joomla-alert.min.js?7a338ea4a2cd5df7edb93e870b062de1:1)
    at Object.e.renderMessages (core.min.js?7a338ea4a2cd5df7edb93e870b062de1:1)
    at onSuccess (extensionupdatecheck.js?7a338ea4a2cd5df7edb93e870b062de1:47)
    at XMLHttpRequest.o.onreadystatechange (core.min.js?7a338ea4a2cd5df7edb93e870b062de1:1)
flying-focus.min.js?7a338ea4a2cd5df7edb93e870b062de1:1 

The error is a little different in FireFox:
TypeError: l is null[Learn More]  flying-focus.min.js:1:2227
	<anonymous> http://joomla.dev/media/vendor/flying-focus-a11y/js/flying-focus.min.js:1:2227
	connectedCallback http://joomla.dev/media/system/webcomponents/joomla-alert.min.js:1:4749
	r.prototype.connectedCallback http://joomla.dev/media/system/js/polyfills/webcomponents/webcomponents-ce.min.js:1:4754
	f http://joomla.dev/media/system/js/polyfills/webcomponents/webcomponents-ce.min.js:1:1326
	<anonymous> http://joomla.dev/media/system/js/polyfills/webcomponents/webcomponents-ce.min.js:1:10423
	e.renderMessages http://joomla.dev/media/system/js/core.min.js:1:3348
	onSuccess http://joomla.dev/media/plg_quickicon_extensionupdate/js/extensionupdatecheck.js:47:9
	e.request/o.onreadystatechange http://joomla.dev/media/system/js/core.min.js:1:7584

### System information (as much as possible)
Joomla 4.0 Revision: ab82c24a3af3fc26120882bdba3a45d0b555c408
Chrome / FireFox
MacOS 10.12.6 (Sierra)
PHP 7.1.6

@dgt41 Something for you?

**Comment by dgrammatiko** [comment] 2017-09-09 20:57
I think there is already an open issue for this somewhere. FWIIW i proposed to remove this `sugar on top of a broken implementation` with a polyfill for CSS4 `:focus-ring`: https://github.com/joomla/joomla-cms/pull/15906

**Comment by brianteeman** [comment] 2017-09-09 20:58
Closed as a duplicate of 17100

**Comment by dgrammatiko** [comment] 2017-09-09 21:18
@brianteeman 17100 was a different bug

**Comment by roland-d** [comment] 2017-09-10 05:54
Re-opening since it is a different bug. The patch for #17100 is already in the codebase when I saw this happen.

**Comment by C-Lodder** [comment] 2017-09-21 13:52
PR: https://github.com/joomla/joomla-cms/pull/18048

**Comment by ghost** [comment] 2017-09-21 14:59
closed as having Pull Request #18048<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17915">issues.joomla.org/tracker/joomla-cms/17915</a>.</sub>

**Closed as completed by ghost** 2017-09-21 14:59 UTC
Labels: No Code Attached Yet
