### ISSUE TITLE
Media module doesn't display images after upload

### ISSUE THREAD

**Issue by okynnor** [joomla/joomla-cms#36745] opened 2022-01-19 19:20 UTC
### Steps to reproduce the issue

Go to the Images module 
Upload an image
It will show up once -- sometimes
but notice that other priorly uploaded images do not display anymore. 
Also if close image module and return, the last uploaded images won't show anymore too. 

### Expected result

Show all images uploaded now and before

### Actual result

no images gets displayed

see this video: https://recordit.co/CpmzcoOXgL

### System information (as much as possible)

Joomla 4 version 4.0.6
Joomla is running side a Docker container

**Comment by pritam825** [comment] 2022-01-19 20:07
@okynnor I have checked, I haven't faced any issue, I am able to see the photos, can you please reinstall and check again, thanks :)

**Comment by drmenzelit** [comment] 2022-01-21 07:26
You are talking about the media manager, not an image module. I can't reproduce the problem, but I don't have a Docker container. Can you please check the browser console for errors or blocked content? You can also try deleting browser cache and another browser.

**Comment by okynnor** [comment] 2022-01-21 21:38
Yup!  The console says: 

index.php:1 
        
       Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at onSuccess (media-manager.min.js?0b09178863807435515ca0fbe2f2bcb351159642:1:110463)
    at XMLHttpRequest.o.onreadystatechange (core.min.js?17121a112ecec3d656efe5c5f493429c9acf2179:1:6186)

**Comment by okynnor** [comment] 2022-01-21 21:38
I have tried already clearing the cache on all three browsers to no avail, namely Edge, Chrome, Safari. 

Yup, the console says: 

`   Uncaught SyntaxError: Unexpected token < in JSON at position 0
at JSON.parse (<anonymous>)
at onSuccess (media-manager.min.js?0b09178863807435515ca0fbe2f2bcb351159642:1:110463)
at XMLHttpRequest.o.onreadystatechange (core.min.js?17121a112ecec3d656efe5c5f493429c9acf2179:1:6186)`

Let me know if you know what's going on.

**Comment by Quy** [comment] 2022-01-21 22:37
You maybe experiencing #33062 or #36053. 

Enable Debug System.
Go to the Media Manager.
Clear the browser's cache.
Upload an image.
In console, please advise the error.

**Comment by okynnor** [comment] 2022-01-22 01:50
Done.  If there's a location that I can go to fetch you the Joomla debug logs in an Ubuntu 18.04 (Dockerized) please advise. 

Please see the result in the attached short video. 


https://recordit.co/5bpgp1gFpz

`Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at onSuccess (media-manager.js?0b09178863807435515ca0fbe2f2bcb351159642:9807:45)
    at XMLHttpRequest.xhr.onreadystatechange (core.js?17121a112ecec3d656efe5c5f493429c9acf2179:712:34)`

**Comment by Quy** [comment] 2022-01-22 02:37
Are there other images in the images directory? Can you backup/clear the images directory and upload an image? This to determine if there is a corrupt image affecting the listing of images.

**Comment by okynnor** [comment] 2022-01-26 03:50
@Quy By following your suggestion, I was able to regain image upload functionality.  Because I use Xen Orchestra and XCP-NG, I was able to take a snapshot prior to deleting all images.  

`https://recordit.co/JORJXRXBGL`. Proof that the site is able to upload images again.

Now I have to restore the website, is there a way to find out which image is the offending image?

**Comment by Quy** [comment] 2022-01-26 05:01
Sorry I don’t know a quick way to find the culprit. Please try uploading via FTP or your hosting control panel 5 to 10 images at a time and browse the Media Manager. When the issue arises, then you can narrow down the offending  image in the batch.

**Comment by okynnor** [comment] 2022-01-26 05:16
Thank you @Quy.

**Comment by Quy** [comment] 2022-01-30 22:40
Closing as this an issue with a corrupt image as reported in #33062. Please report with any details of the corrupt image. Thanks.

**Closed as completed by Quy** 2022-01-30 22:40 UTC
Labels: No Code Attached Yet, Information Required
