### ISSUE TITLE
Two flags si_LK.gif and si_lk.gif after update Joomla from 3.4.8 to 3.5.0 on linux server

### ISSUE THREAD

**Issue by pitu-sk** [joomla/joomla-cms#9597] opened 2016-03-25 18:46 UTC
#### Steps to reproduce the issue

Update Joomla from 3.4.8 to 3.5.0 on linux server and look for images in /media/mod_languages/images directory with flags

#### Expected result

You can see only si_lk.gif file in /media/mod_languages/images directory for language Sinhala - SRI LANKA.

#### Actual result

You can see both old si_LK.gif and new si_lk.gif files (flags)  in /media/mod_languages/images directory

#### System information (as much as possible)

php: Linux apache24-php55-4 3.14.27-031427-generic #201412170558 SMP Wed Dec 17 11:00:01 UTC 2014 x86_64
dbversion: 5.5.45-MariaDB-log
dbcollation: utf8_general_ci
dbconnectioncollation: utf8mb4_general_ci
phpversion: 5.5.21
server: Apache
sapi_name: apache2handler
version: Joomla! 3.5.0 Stable [ Unicorn ] 21-March-2016 22:00 GMT
platform: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:45.0) Gecko/20100101 Firefox/45.0

#### Additional comments

I discovered problem when I sync files from case-sensitive Linux server to non-case-sensitive Windows PC.

**Comment by andrepereiradasilva** [comment] 2016-03-25 19:12
yes the lowercase has added in https://github.com/joomla/joomla-cms/commit/f283733779fc9cac17901c8718b9e70d0fb5b3f3

Joomla didn't remove the old (with uppercase) for Backward Compatibility (BC).

Is not an error but you can delete the uppercase one. Joomla will not put it there again.

**Comment by Bakual** [comment] 2016-03-25 19:17
Closing since it's expected behavior.

**Closed by Bakual** 2016-03-25 19:17 UTC
