### ISSUE TITLE
New Joomla! routing system also handles old URLs witch contains article ID

### ISSUE THREAD

**Issue by sonqor** [joomla/joomla-cms#19539] opened 2018-02-02 13:36 UTC
### Steps to reproduce the issue
Hello.
I have enabled new Joomla! routing system feature witch remove IDs from articles URL. But I recognize that old URLs also working after it. For example my article alias is:

`how-to-play-shadowfiend-in-dota2`

and it works fine without article ID. 
**But the problem is that links below still working:**

`?view=article&id=254:how-to-play-shadowfiend-in-dota2`
`?id=254:how-to-play-shadowfiend-in-dota2`

witch `254` is my article ID.

This problem causes Google Webmaster Tools generates multiple warnings about duplicate meta tags. Also it affects site SEO and URL listing in search engines like Google.

Is there any option in Joomla! to fix this problem?
Thanks.

**Comment by ghost** [comment] 2018-02-02 13:38
@csthomas?

**Comment by ggppdk** [comment] 2018-02-02 14:00
It is not a bug
It was done deliberately so that existing links will not break, when someone enables the new routing

The way to address this is with proper rel-canonical

Then about adding new configuration to give out 404 error for old URLs
i do not know if it is needed, i guess it might be useful in new websites

**Comment by ghost** [comment] 2018-02-02 14:11
thanks for Info @ggppdk 

Closed as expected Behaviour.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19539">issues.joomla.org/tracker/joomla-cms/19539</a>.</sub>

**Closed as completed by ghost** 2018-02-02 14:11 UTC
Labels: No Code Attached Yet

**Comment by ggppdk** [comment] 2018-02-02 14:21
@sonqor 

please read discussion here:
https://github.com/joomla/joomla-cms/issues/14848
