### ISSUE TITLE
Problem with tags

### ISSUE THREAD

**Issue by djmilenko** [joomla/joomla-cms#39105] opened 2022-10-29 17:09 UTC
I have several sites on Joomla4, and they all have the same error with tags:

If a tag has more than 20 articles, only page 1 is displayed normally, and all others throw out an error.
One website has a fresh version of Joomla4, and the other sites are updated on Joomla4.

Php version is 7.4, and 8.0.

![screen shot 2022-10-29 at 17 07 51](https://issues.joomla.org/uploads/1/a39822870fd5545ed2c9745ca695d112.png)

**Comment by richard67** [comment] 2022-10-30 12:41
I can confirm the issue. I've reproduced on a clean, current 4.2-dev without any .htaccess and without url rewriting but with sef urls on, and Blog sample data installed.

I have created some 33 copies of the "Millions" article and then used batch processing to assign the "Millions" tag to all of these copies, so I have 34 articles tagged with that tag.

Then I clicked in frontend on the tag in one of these articles to get the tagged items list view.

URL is `index.php/component/tags/tag/millions`.

The page looks fine and I get pagination for the tagged items list.

Clicking on the arrow button for going to the next pages results in a 404.

URL is `index.php/component/tags/millions?Itemid=101&start=20`.

So somehow the `tag` between the `tags` and the `millions` part of the URL's path gets lost when paging.

Adding that in the browser's URL field results in the correct page being shown.

**Comment by wojtekxtx** [comment] 2022-10-30 14:57
> somehow the tag between the tags and the millions part of the URL's path gets lost when paging.

This is what it looks like from no-IT guy. As we all have ( solid ) IT exp, we can use IT jargon......... info regarding tag is not stored/transmitted properly; in other words USMS ( User Session Management System ) is poorly designed / maintained.

**Comment by richard67** [comment] 2022-10-30 15:02
Additional info: With SEF URLs switched off in global configuration, everything is fine, i.e. no 404 when paging.
URLs are `index.php?option=com_tags&view=tag&id=2:millions` on the first and then `index.php?option=com_tags&view=tag&id=2:millions&Itemid=101&limitstart=20` on the 2nd page.

**Comment by wojtekxtx** [comment] 2022-10-30 15:04
@richard67 many thanks :) You have just prove me right :)

**Comment by richard67** [comment] 2022-10-30 15:05
@wojtekxtx Your comments are not really helpful.

**Comment by wojtekxtx** [comment] 2022-10-30 15:06
> @wojtekxtx Your comments are not really helpful.

@richard67 They are not helpful **to you**. Dont speak on behalf of others please.

**Comment by Hackwar** [comment] 2022-10-31 21:34
#39114 should fix this. Please help testing that.

**Comment by richard67** [comment] 2022-11-02 10:26
Closing as having a pull request. Please test #39114 . Thanks in advance.

**Closed as completed by richard67** 2022-11-02 10:26 UTC
Labels: No Code Attached Yet
