### ISSUE TITLE
Textarea with a lot characters produce error

### ISSUE THREAD

**Issue by tobias-wedel** [joomla/joomla-cms#14700] opened 2017-03-17 16:54 UTC
### Steps to reproduce the issue

I build my own plugin and i need to save a lot (And i mean a lot!) text in a textarea. It seems that if i save to much text that this error occur: **Error decoding JSON data: Control character error, possibly incorrectly encoded**

I tried it with different extensions like modules and put a lot of text in a textarea. This error occur always.

### System information (as much as possible)
Joomla 3.6.5

**Comment by brianteeman** [comment] 2017-03-17 16:57
How much is a lot? Is it more than the size of the database field?

**Comment by tobias-wedel** [comment] 2017-03-17 17:02
I just checked it out and it seems that its more than the size of the database field. It cuts the params value. Is there a way to handle the size?

**Comment by tonypartridge** [comment] 2017-03-19 07:53
Hello,

You will need to setup your own table and extend JForm to use this new form and save to The new database.

It sounds like you may be better using a component and having the plugin interact with the component if your saving that much data.

Many thanks
Tony

**Comment by brianteeman** [comment] 2017-03-20 09:25
Closed as its not a bug

**Closed by brianteeman** 2017-03-20 09:25 UTC
Labels: No Code Attached Yet
