### ISSUE TITLE
[4.0] Clear button on list pages doesn't work

### ISSUE THREAD

**Issue by roland-d** [joomla/joomla-cms#17916] opened 2017-09-09 20:27 UTC
### Steps to reproduce the issue
1. Go to the Articles list
2. Click on the Clear button next to the search box
3. Nothing happens and console shows an error

### Expected result
Clear clears the search box and refreshes the page

### Actual result
Search box is not cleared and page doesn't refresh but an error is shown in the console

TypeError: t.querySelector(...) is null[Learn More]  searchtools.min.js:1:3800
	checkFilter http://joomla.dev/media/system/js/searchtools.min.js:1:3800
	clear/< http://joomla.dev/media/system/js/searchtools.min.js:1:3983
	forEach self-hosted:267:13
	clear http://joomla.dev/media/system/js/searchtools.min.js:1:3932
	init/< http://joomla.dev/media/system/js/searchtools.min.js:1:3181

### System information (as much as possible)
Joomla 4.0 Revision: ab82c24a3af3fc26120882bdba3a45d0b555c408
Chrome / FireFox
MacOS 10.12.6 (Sierra)
PHP 7.1.6

@dgt41 Something for you?

**Comment by brianteeman** [comment] 2017-09-09 20:31
Closed as a duplicate of an issue of mine

**Closed as completed by brianteeman** 2017-09-09 20:31 UTC
Labels: No Code Attached Yet
