### ISSUE TITLE
[4.0] Alert error on Permissions page

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#23824] opened 2019-02-08 15:27 UTC
### Steps to reproduce the issue

1. In IE11, go to `/administrator/index.php?option=com_config`
2. Click the permissions tab
3. Select an option from one of the dropdowns and wait for it to save

You'll see a blue alert which then triggers a JS error:

> Unable to get property 'removeChild' of undefined or null reference ....  joomla-alert-es5.min.js (1,4541)

**Comment by Arpit-24** [comment] 2019-04-05 12:24
I am unable to reproduce this issue. Possibly got fixed somewhere. Can you recheck?

**Comment by brianteeman** [comment] 2019-05-23 12:21
I am unable to reproduce this issue - can be closed as it was probably resolved elsewhere. Can always be reopened

**Closed as completed** 2019-05-23 12:23 UTC
Labels: No Code Attached Yet, J4 Issue
