### ISSUE TITLE
Cannot access site template params from admin back-end

### ISSUE THREAD

**Issue by thalueng** [joomla/joomla-cms#28956] opened 2020-05-06 03:37 UTC
### Steps to reproduce the issue
// access from administrator component
$app = CMSApplication::getInstance('site'); // Joomla\CMS\Application\SiteApplication
$template = $app->getTemplate(true); // throws exception

### Expected result
return site template

### Actual result
throws exception

### System information (as much as possible)
J3.9.18

### Additional comments
finds the template, but throws exception when verifying the template really exists.
"file_exist" in SiteApplication.php (line 544/561) should check against JPATH_SITE.'/templates' instead of JPATH_THEMES.

work around: create (empty) index.php in folder /administrator/templates/my-site-template-name/

**Comment by ReLater** [comment] 2020-05-06 11:15
> access from administrator component

> return site template

How should the backend know which params of several possible site templates/styles you  want?

**Comment by thalueng** [comment] 2020-05-06 11:42
Well, the active template. The code finds everything correctly, just replace JPATH_THEMES as I suggested.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28956">issues.joomla.org/tracker/joomla-cms/28956</a>.</sub>

**Comment by ReLater** [comment] 2020-05-06 11:47
> Well, the active template.

If you have several templates and/or styles: What is the active template when you are in the back-end?
It depends on the active page (menu item) in the front-end which template or style is active.

That's what I don't understand.

**Comment by thalueng** [comment] 2020-05-06 11:48
Maybe I should add that the 2 lines of code I posted finds the active site template without any issues, when called from the front-end, since JPATH_THEMES points to /templates. But when called from the back-end, JPATH_THEMES points to /administrator/templates. As it's an instance of SiteApplication, everythings works for the back-end as well (it finds the template in the db), up to the point when the code checks whether the template found does exist on the file system. It's there were it should check against /templates/, but it does check against JPATH_THEMES which points to /administrator/templates/.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28956">issues.joomla.org/tracker/joomla-cms/28956</a>.</sub>

**Comment by ReLater** [comment] 2020-05-06 11:49
> Well, the active template. The code finds everything correctly, just replace JPATH_THEMES as I suggested.

Provide a pr if you think so: https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests

**Comment by brianteeman** [comment] 2020-05-06 11:52
> Maybe I should add that the 2 lines of code I posted finds the active site template without any issues,

But not the active style which is the important thing? A template can have many styles and the params are for the style not for the template

**Comment by ReLater** [comment] 2020-05-06 11:52
> Maybe I should add that the 2 lines of code I posted finds the active site template without any issues, when called from the front-end,

I think you mean the template marked as "Standard". But these params can be completely irrelevant. There are cases where the Standard template is never used in the front-end.

**Comment by thalueng** [comment] 2020-05-06 17:23
True, but in my case I just use one template in the front-end. If I read the code correctly then getTemplate tries to identify the menu item and the template active for that menu item. If it can't figure it out, then the template active for the home item is selected and returned. Called from front-end ok, called from back-end throw exception with conclusion that the template does not exist in the file system. Certainly not what I would expect.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28956">issues.joomla.org/tracker/joomla-cms/28956</a>.</sub>

**Comment by joomdonation** [comment] 2022-11-12 10:36
The problem here is that we use JPATH_THEMES to check for existence of the template. Unfortunately, JPATH_THEMES  is coupled with the active application, mean administrator app in this case, result in the template does not exist error

We also could not changed the code to JPATH_SITE.'/templates' as you suggested because Joomla allows custom defined constants.

So while the issue is valid, I'm afraid of it will be a won't fix issue for the time being. Please use the workaround you found or any working custom code (I also write custom code myself to detect the template).

**Closed as completed by joomdonation** 2022-11-12 10:36 UTC
Labels: No Code Attached Yet
