### ISSUE TITLE
[4b6] Fight over whose admin message is displayed 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#31985] opened 2021-01-10 17:15 UTC
### Steps to reproduce the issue

Install Joomla 4 in PHP 7.2
Login to admin console 

### Expected result

Two messages 
 - PHP Version Warning 
 - Joomla asking for permission to send statistics

OR

One message at a time - not both trying to render and one trumping the other

### Actual result

Watch the video of me repeatedly hitting refresh in the browser - Note the flash of red on page load (that's the PHP version warning) 
I have a very fast browser, but on slow computers/browsers this might be more of a render jump.

https://user-images.githubusercontent.com/400092/104130129-0412a600-5367-11eb-88fc-cb4b441a38db.mp4

### System information (as much as possible)

safari on macOS 

### Additional comments

An informational message should never delete a red warning/error message! 

One I click [Never] send the stats the stats notice disappears (correctly) and no PHP version warning is visible.

only after a hard page refresh do I get the PHP version warning

<img width="1312" alt="Screenshot 2021-01-10 at 17 14 11" src="https://user-images.githubusercontent.com/400092/104130188-518f1300-5367-11eb-986d-745d84728980.png">

**Comment by infograf768** [comment] 2021-01-11 10:33
Confirmed. It can also be tested by keeping the stats plugin displaying `Joomla asking for permission to send statistics` and modifying any item status in a manager in order to get a message.

We do not get the issue in J3

<img width="779" alt="Screen Shot 2021-01-11 at 11 32 03" src="https://user-images.githubusercontent.com/869724/104169988-b5194f00-5400-11eb-888f-6d2e85282f81.png">

**Comment by infograf768** [comment] 2021-01-11 11:09
@Fedik 
I have the feeling that the stats plugin alert display closes other alerts and would need some js tweaks.
The layout is using `<joomla-alert ` contrary to J3 where the layout is a simple div.
Any idea?

**Comment by Fedik** [comment] 2021-01-11 11:58
Hard to say, need to look, 
`<joomla-alert` is a custom element from [joomla-projects/custom-elements](https://github.com/joomla-projects/custom-elements/blob/master/src/js/alert/alert.js) 

~~The message is a lang string `PLG_QUICKICON_PHPVERSIONCHECK_UNSUPPORTED` from `quickicon/phpversioncheck` plugin.~~

I suspect or message markup is broken, or something with script, or even styling. 

It only Safari, or other browsers also?

**Comment by infograf768** [comment] 2021-01-11 15:23
All browsers here.

**Comment by infograf768** [comment] 2021-01-11 15:25
But, as i said, the issue is not special to the php version check. It is present in every manager when an action results in a message and the stats plugin is present.

**Comment by wilsonge** [comment] 2021-01-11 15:39
My best guess is that the JS API in core.js is removing any messages enqueued by the PHP API (haven't looked at the code - just guessing from my phone)

**Comment by Fedik** [comment] 2021-01-11 16:22
yeah, well it stats-message.js
https://github.com/joomla/joomla-cms/blob/3a5984d03366f707ef842ee48051af194f68848f/build/media_source/plg_system_stats/js/stats-message.es6.js#L73-L77

It remove all content, and insert own message, 
On fast local server you even do not notice any blinking.

I will make PR, later.

**Comment by wilsonge** [comment] 2021-01-11 16:38
Oh ffs. so we just need to move it to the Joomla.renderMessages function in core.js then

**Comment by Fedik** [comment] 2021-01-11 17:06
It not really possible to use Joomla.renderMessages here, as the stats plugin render whole message with own markup for this fancy styling.

I have updated stats-message.js a bit, please test #32011

**Comment by richard67** [comment] 2021-01-11 17:18
Closing as having a pull request. Please test #32011 . Thanks in advance.

**Closed as completed by richard67** 2021-01-11 17:18 UTC
Labels: No Code Attached Yet
