### ISSUE TITLE
Fatal error: JViewBase cannot implement JView 

### ISSUE THREAD

**Issue by iyanee** [joomla/joomla-cms#6325] opened 2015-03-05 19:02 UTC
#### Steps to reproduce the issue

After updating to Joomla 3.4 or 3.3 (not clear) 

Global Configuration delivers a blank page

#### Expected result

regular Global Configuration Page

#### Actual result

after setting 

public $error_reporting = 'maximum';

following error is displayed

Fatal error: JViewBase cannot implement JView - it is not an interface in /var/customers/webs/xxx/xxx/xxx/libraries/joomla/view/base.php on line 18 

#### Additional comments

site online since years...

rest of the page seems to work smoothly.

It is not certain if it happened when updating to joomla 3.3.x or 3.4
since the first automated update a few days ago didn't throw an error, but when checking today. the info was joomla 3.3.xxx (can't recall the number) and no automated update was offered. so I downloaded the newest update .zip today and installed it via extension - install. No error was thrown, but the blank page on calling Global configuration still occurs.

**Comment by mbabker** [comment] 2015-03-05 19:06
It seems as though you may have some leftover files in place from a 2.5 to 3.x migration (JView was a class in 2.5 and is an interface in 3.x).  If at all possible, suggest you access your account via SSH and run the `cli/deletefiles.php` script (it must be done from a command line interface).  Otherwise you'll need to use an FTP client and ensure all of the files listed at https://github.com/joomla/joomla-cms/blob/3.4.0/administrator/components/com_admin/script.php#L313-L1244 have been removed from your site.

**Comment by iyanee** [comment] 2015-03-06 09:34
Thanx for the fasst reply.

I did run the  cli/deletefiles.php script in commandline via ssh.
I  checked if files are removed -> positive
I cleared cache etc.

The problem with the Global configuration is still there.

I reinstalled the latest update -> problem still occurs.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6325">issues.joomla.org/joomla-cms/6325</a>.</sub>

**Comment by iyanee** [comment] 2015-03-06 12:12
additional info:

in system - control panel 
it says

Maintenance

    Joomla! is up-to-date	
    Unknown extensions...	
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6325">issues.joomla.org/joomla-cms/6325</a>.</sub>

**Comment by iyanee** [comment] 2015-03-09 14:32
Anybody any idea?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6325">issues.joomla.org/joomla-cms/6325</a>.</sub>

**Comment by Bakual** [comment] 2015-03-09 16:01
Can you please post your request on our support forums (http://forum.joomla.org/)
This sounds more like a messed up update than a bug in the core.

I'm closing this issue as it's not a bug.

**Closed by Bakual** 2015-03-09 16:01 UTC
Labels: No Code Attached Yet

**Comment by iyanee** [comment] 2015-03-09 18:39
Hello Thomas.

I woulkd love to do so, but my Ip-address was locked. (banned) for 
whatever reasons I do not know.

A friend forwared the regarding informations to the forum, but I have no 
feedback yet at all.

walk in beauty

Iyánéé
Matthias W. Kamp

Am 09.03.2015 um 17:01 schrieb Thomas Hunziker:

**Comment by sovainfo** [comment] 2015-03-09 19:32
Request an Unban at http://community.joomla.org/index.php?option=com_rsform&formId=3
