### ISSUE TITLE
Isis template not loading under PHP 7.2.x (Joomla 3.8.6)

### ISSUE THREAD

**Issue by AMurray2016** [joomla/joomla-cms#19921] opened 2018-03-15 22:09 UTC
### Steps to reproduce the issue
--- Live Hosting ----
On Hosting provider (SiteGround) I go to the PHP selector in cPanel and choose the version PHP 7.2.3 for the specific folder my site is in.  Save the setting, then go to www.murraywebs.biz/dev/administrator
Login screen is shown normally.  
Login works OK.
Once logged in, it loads an unstyled Isis admin screen, with not all options and links available (no main menu etc).

Same issue on my local PC:
--Localhost--
Using WAMPServer 3.1.1.
Switch PHP to 7.2.x
Restart server etc
Isis template loads with no styling (just black text on white screen)

### Expected result
Should load Isis template normally under PHP 7.2.x.

### Actual result
No styling.   The login screen is normal, but on logging on, the screen  turns tot he black text on white screen.

The same issue occurs on my local PC (localhost running WAMPServer 3.1.1).  I have PHP 7.15, 7.2.0, 7.2.2 on this system and same issue occurs when any of the PHP 7.2.x versions are selected, so it seems not just my live host.

### System information (as much as possible)

This was occurring in Joomla 3.8.5 and 3.8.6

Site Ground Hosting (shared hosting)
PHP 7.2.3
Have a choice of PHP versions:

PHP 5.5.38
PHP 5.6.34 - System Default
PHP 7.0.28
PHP 7.1.15
PHP 7.2.3

Using LetsEncrypt SSL.

### Additional comments
When I switch the PHP version back go 7.1.5, and refresh the screen, the Isis administrator template loads normally, so I have concluded it is a problem with  PHP 7.2.x
![screen shot 2018-03-15 at 21 37 15](https://issues.joomla.org/uploads/1/d9a4cd0eac73fe54fcf9b7de88df6005.png)![screen shot 2018-03-15 at 21 37 15](https://issues.joomla.org/uploads/1/367f1fae52bd0c864653372046d9f1ce.png)![screen shot 2018-03-15 at 21 37 16](https://issues.joomla.org/uploads/1/e412b9cc3827f4681c62d4aa36518642.png)

**Comment by mbabker** [comment] 2018-03-15 22:17
Cannot duplicate on PHP 7.2 on either my local AMP stack or my SiteGround account.

**Comment by brianteeman** [comment] 2018-03-16 00:27
Cannot duplicate

**Comment by SharkyKZ** [comment] 2018-03-16 08:02
Have you tried a fresh installation? The issue is most likely with 3rd party extensions.

**Comment by SharkyKZ** [comment] 2018-03-16 08:07
And enable error reporting.

**Comment by ggppdk** [comment] 2018-03-16 08:54
As said above enable error reporting, since what you need to post here is the actual PHP fatal error

Possibly you are using a Joomla extension that 
- either needs a PHP extension that does not get loaded when you switch to PHP 7.2.x
- or it has other PHP 7.2.x incompatible code

**Comment by ot2sen** [comment] 2018-03-16 09:03
It looks like you are using a plugin to modify how your admin template works, the KL Admin skin listen in your screenshot. This plugin could well be the cause of your problem. Try disable it.

**Comment by brianteeman** [comment] 2018-03-16 19:53
I am going to close this for now as "not joomla core". If you find that disabling the KL Admin skin doesnt make a difference it can always be reopened

**Closed as completed by brianteeman** 2018-03-16 19:53 UTC
Labels: No Code Attached Yet

**Comment by AMurray2016** [comment] 2018-03-17 02:59
I found the cause of the error; LOGMAN by Joomlatools.com.  Disabling Logman allowed the control panel to load correctly - both on live and localhost.

I will raise a ticket with them about this.

Thanks all for the suggestions.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19921">issues.joomla.org/tracker/joomla-cms/19921</a>.</sub>
