### ISSUE TITLE
[4.0] UAL Email Notification problems

### ISSUE THREAD

**Issue by fr56** [joomla/joomla-cms#35028] opened 2021-08-02 14:25 UTC
### Steps to reproduce the issue
J4 RC5. 
Enable IP Logging in User Actions Log (UAL) Options.
Set up your user to receive Email Notifications from UAL.
Create or save an article (or some other action that triggers the notifications), and check your mail.

### Expected result (as seen on J3)
<html><body>
<h1>
	Latest User Actions</h1>
<h2>
	This is the latest action performed by a user on your website.</h2>

Action | Date | Extension | Name | IP Address
-- | -- | -- | -- | --
User admin updated the article Test | 2021-07-31 14:50:07 UTC | Users | Super User | 84.208......

</body>
</html>

### Actual result
<p>Latest User Actions</p>
------
This is the latest action performed by a user on your website.

Action | Date | Extension | Name
 User < a href="https://...........com/administrator/index.php?option=com_users&task=user.edit&id=1" >admin< /a > updated the article < a href="https://.........com/administrator/index.php?option=com_content&task=article.edit&id=25" >Test< /a  > | 2021-08-02 12:34:14 UTC | Articles | Administrator

### System information (as much as possible)
Joomla 4 RC5
PHP 8.0.8
MySQLi 5.7.33-cll-lve 

### Additional comments
There are two bugs (compared to J3):
1. The formatting is missing. thus HTML codes for editing user and article is displayed instead of showing the user and article names as clickable words (spaces added around <> for readability), and the whole thing looks like a mess.
2. The IP address is not displayed.

**Comment by brianteeman** [comment] 2021-08-02 18:06
duplicate of #33586 ?

**Comment by fr56** [comment] 2021-08-02 19:11
Yes, definetly. Except for the IP address bit.

But since this was reported already in May, shouldn't it be fixed soon? Preferably before J4 release?

**Comment by RickR2H** [comment] 2021-08-03 10:48
@fr56 It will be fixed as soon as someone is willing to spent time in writing a patch 😉

**Comment by fr56** [comment] 2021-08-03 17:20
@RickR2H Yes, I'm sure it will, didn't mean to be naggy 😉

**Comment by Quy** [comment] 2023-02-14 18:57
Closing in favor of #39190 and #39851 to separate these issues with additional info.

**Closed as completed by Quy** 2023-02-14 18:57 UTC
Labels: No Code Attached Yet
