### ISSUE TITLE
Upgrade email incorrect

### ISSUE THREAD

**Issue by gwsdesk** [joomla/joomla-cms#19880] opened 2018-03-10 06:50 UTC
The upgrade email message is not correct. Please see the message. Joomla versions are incorrect. In this case the site runs Joomla 3.8.2 and the message I receive is as follows (actual domain replaced):

> "This email IS NOT sent by Joomla.org. It is sent automatically by your own site,
**Joomla 3.8.2** - https://website.com/ 
>
> ================================================================================
UPDATE INFORMATION
================================================================================
>
> Your site has discovered that there is an updated version of Joomla! available for download.
>
> **Joomla! version currently installed:        3.8.3**
> Joomla! version available for installation: 3.8.4
>
> This email is sent to you by your site to remind you of this fact.
> The Joomla! project will never contact you directly about available updates of Joomla! on your site.
>
> ================================================================================
UPDATE INSTRUCTIONS
================================================================================
>
> To install the update on Joomla 3.8.2 please click the following link. (If the URL is not a link, copy & paste it to your browser).
>
> Update link: https://website.com/administrator/index.php?option=com_joomlaupdate"

Besides the fact that it is not providing the accurate information in the "Update block" (J3.8.3 instead of J3.8.2) I wonder why this does not recognize current version Joomla 3.8.5 available

**Comment by infograf768** [comment] 2018-03-10 09:13
I can't reproduce.
Installed a clean 3.8.2 site.
Received mail containing
```

================================================================================
UPDATE INFORMATION
================================================================================

Your site has discovered that there is an updated version of Joomla! available for download.

Joomla! version currently installed:        3.8.2
Joomla! version available for installation: 3.8.5

This email is sent to you by your site to remind you of this fact.
The Joomla! project will never contact you directly about available updates of Joomla! on your site.

================================================================================
UPDATE INSTRUCTIONS
================================================================================

To install the update on 382 please click the following link. (If the URL is not a link, simply copy & paste it to your browser).

Update link: http://localhost:8888/Joomla_3.8.2/administrator/index.php?option=com_joomlaupdate

```

**Comment by PhilETaylor** [comment] 2018-03-10 21:07
Joomla has a long history of not displaying the correct update occassionally. Cache?

**Comment by ggppdk** [comment] 2018-03-10 21:21
Current version number is coming from fiel
`libraries/src/Version.php`

So if you view the above file, and search for 
`const PATCH_VERSION =`

which is the `PATCH_VERSION` number ?

**Comment by gwsdesk** [comment] 2018-03-11 02:26
@ggppdk 
> const MAJOR_VERSION = 2;

**Comment by Quy** [comment] 2018-03-11 02:42
@gwsdesk Please advise `PATCH_VERSION`.

**Comment by ggppdk** [comment] 2018-03-11 06:24
@gwsdesk 

it is good that you provided full copy of the email,

please look at the bottom of this answer,
and see **language string** and notice the `[SITENAME]` - `[URL]` replacements

**your sitename is**  `Joomla 3.8.2` ?



So i ask 
- is this email from a testing website, since sitename is 'Joomla 3.8.2' ?
- also (maybe) it also has $live_site variable set in configuration PHP , which will effect JUri::base() ?

```
PLG_SYSTEM_UPDATENOTIFICATION_EMAIL_BODY="This email IS NOT sent by Joomla.org. It is sent automatically by your own site,
[SITENAME] - [URL] 

================================================================================
UPDATE INFORMATION
================================================================================

Your site has discovered that there is an updated version of Joomla! available for download.

Joomla! version currently installed:        [CURVERSION]
Joomla! version available for installation: [NEWVERSION]

This email is sent to you by your site to remind you of this fact.
The Joomla! project will never contact you directly about available updates of Joomla! on your site.
```

**Comment by brianteeman** [comment] 2018-03-11 09:47
@ggppdk the issue is not the first line it is the middle of the email stating the current and next version. that is nothing to do with the site name

**Comment by gwsdesk** [comment] 2018-03-11 09:48
const PATCH_VERSION = 5;

@ggppdk yes this is from our Testing website where we test upgrades from Joomla 3.8.2 to Joomla 3.8.5 (we do test on a multitude of domains several upgrade scenarios as member of the CMS Release team ;-) and (edited post: We never set "live-site variable")

@brianteeman you are correct

**Comment by brianteeman** [comment] 2018-03-11 09:51
not tezted the code but i think the issue is that once a site realises there is a new version available that is stored and it doesnt check again to see if there is an even newer version avialable. not checked the code as i havent had my coffee yet but it would make sense logically that this is what is happening

**Comment by ggppdk** [comment] 2018-03-11 10:09
@brianteeman 

that is exactly what i am talking about
people can create testing websites,
forgeting to change DB, or having live_site configuration variable set,
or even using same logs and tmp folders

anyway i do not say it is related or not,
and i do not say that the above settings are the same between the 2 websites, but the above are things that should be checked

Also the fact that it is a testing website is not mentioned in the description text of the first post of this issue

about "caching" usage in the plugin, it seems stops the code from running until "cache" time expires (last run time is stored in DB), and it does not seem to be using any caching to resend the same message

**Comment by gwsdesk** [comment] 2018-03-11 15:35
@ggppdk It is totally irrelevant if we call this "testsite" or "Joomla 3.8.2" or "Mysite" or "GoOANDHAVEIT" see the point? Nothing is releavant about testsite or not. It is an installed Joomla 3.8.2 website where this is happening and whatever the name of the site in the browser (!) who cares!

Your replies to this issue are completely irrelevant I am sorry. Brian put the finger on it and that has nothing to do if it is "testsite" or "livesite" Would it make a difference for you if it woud have happened on our major business site gws-desk.com live-site and if so why? Nonsense imho

Why do I have to change tmp or log files or "change DB" Why should I do that? I am not getting your logic here. I have an installed 3.8.2 website with a correct configuration and I get an incorrect upgrade message...so what has changing tmp/logs/description of the site has to do with this? Nothing...And uhhhh caching on this "Whatevername Site" is disabled so all kind of weird relations being indicated here ...Totally irrelevant

**Comment by ggppdk** [comment] 2018-03-11 15:50
@gwsdesk 

Read the source, and do not guess,
that is what i do,

i almost never reported a bug here never without identifying where the bug is
i was trying to help here, but just forget it

forget it completely please

enough with attacks
i am sick of it

**Comment by gwsdesk** [comment] 2018-03-11 16:06
@ggppdk I am sorry but I am not aware that you have been attacked. I did not attack you nor did anybody in this thread I believe?

I posted an issue not knowing why this is happening which I am entitled to I believe on issues.joomla.org. I experience something and I post my experience and document it. I am kind of surprised being accused of attacking you. I just disagree with your observation...If you feel offended by me not agreeing to your reactions I feel sorry for you. I never intended (nor did I for sure) attack you..... weird frustration mate!

**Comment by ggppdk** [comment] 2018-03-11 16:36
> anyway i do not say it is related or not,
and i do not say that the above settings are the same between the 2 websites, but the above are things that should be checked

and ABOUT TMP AND LOG  folders THEY WERE ONLY AN EXAMPLE of things that sometimes not being changed when creating a testing copy, related or not related
**irrelevant**

what might be relevant is that we have 2 websites that might have an effect to each other

you were just easy to use words like non-sense, **and who said the site name matters ?** 
yes who said this ?
i mentioned it to point that the site is testing website , which was not mentioned in the original description
did i say that it sitename text "matters" ?

If you search bug reports opened by me
you will see how detail there are and pointing exactly where the problem is
suggesting fixes or even making PRs

my comments are after read the source code !
and most times after running tests too

and what is most relevant to a bug is getting people to look at it, regardless of what they post
i am sure people will find why this is happening without any more comments by me

**Comment by infograf768** [comment] 2018-03-11 16:37
com_installer Options define the cache timeout.
Changing the settings to a lower value may also solve the issue.
<img width="554" alt="screen shot 2018-03-11 at 17 21 15" src="https://user-images.githubusercontent.com/869724/37255731-e0677178-2550-11e8-9658-f40d54e037bd.png">
<img width="524" alt="screen shot 2018-03-11 at 17 36 43" src="https://user-images.githubusercontent.com/869724/37255865-dde21960-2552-11e8-96af-6dd26f362ca9.png">


Could you try setting it to new value and test again on the same site?

Note: GRR, someone took off the tip in 4.0 explaining that this setting is also used for the update plugin...

**Comment by gwsdesk** [comment] 2018-03-11 16:47
@infograf768 I will test as requested JM thanks for the clear suggestions

@ggppdk I am a tester I do not code. I can install many more websites as "whetevernameitwillbe" (J3.8.2) and none of them have anything in relation since I can install them on any (different) server(s) in many different server configurations and the same issue will happen so they cannot have an effect on each other. Oh yes and I know how you contribute and I am very thankful for your assists. Acknowledged!

Cheers, Leo

**Comment by ReLater** [comment] 2018-03-14 19:50
Today I opened a test page (cleanly configured) for the first time after a longer time (I'm the only visitor) and received an update email (for 3.8.6)

> Joomla! version currently installed: 3.7.2
> Joomla! version available for installation: 3.7.3

Both versions are wrong ;-) 

But sorry, who cares about things like this as long as the subject of the email is correct?

**Comment by PhilETaylor** [comment] 2018-03-14 19:53
A lot has happened since Joomla 3.7.x

I suggest this is closed, because we are not going to go back and fix old versions of Joomla reporting old versions of Joomla. 

If you can replicate this in Joomla 3.8.5/6 then I would say that this is then a valid report and people would invest more time in debugging/researching/replicating the issue. 

At the moment no one is reporting an issue in a recent version of Joomla - just very very very old versions.

**Comment by ReLater** [comment] 2018-03-14 19:57
> A lot has happened since Joomla 3.7.x

It was a 3.8.don't-remember.

> I suggest this is closed

I completely agree.

**Comment by PhilETaylor** [comment] 2018-03-14 20:00
$currentVersion is derived from 

```
$jVersion       = new JVersion;
$currentVersion = $jVersion->getShortVersion();
```

So thats impossible to get wrong unless you have a bad JVersion class file. 

The new version is got from 

```

		$updater = JUpdater::getInstance();
		$results = $updater->findUpdates(array(700), $cache_timeout);

		$model = JModelLegacy::getInstance('Update', 'InstallerModel');
		$model->setState('filter.extension_id', 700);
		$updates = $model->getItems();

		$update = array_pop($updates);
                $newVersion = $update->version;

```

So this is probably a cache time out issue, or a corrupt database where the extension_id of Joomla is no longer 700... the hard coded extension id for Joomla (when people do crazy crap like migrations and other messing direct with extensions table.

**Comment by brianteeman** [comment] 2018-03-23 22:46
closed as not reproduced it can always be re-opened if further information is provided.

**Closed as completed by brianteeman** 2018-03-23 22:46 UTC
Labels: No Code Attached Yet
