### ISSUE TITLE
you cannot remove the position from a menu module once you have given it one

### ISSUE THREAD

**Issue by shoulders** [joomla/joomla-cms#13613] opened 2017-01-16 19:16 UTC
### Steps to reproduce the issue
create a menu module, assign a menu position and then save. when you go back into the module you can remove the module position. It will not let you select 'none' as it does not exist.

### Expected result
Be able to selecy the position type 'none' and save it.

### Actual result
You cannot select none, the position does not exist.

### System information (as much as possible)
Joomla 3.6.5
Database Version 	5.5.5-10.1.13-MariaDB 
Database Collation 	utf8_general_ci 
Database Connection Collation 	utf8mb4_general_ci 
PHP Version 	5.6.21 
Web Server 	Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.21 
WebServer to PHP Interface 	apache2handler 
Joomla! Version 	Joomla! 3.6.5 Stable [ Noether ] 1-December-2016 22:46 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT 
User Agent 	Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0 

### Additional comments
The only way to get a menu module with no position is to delete it and then recreate it. There are many frameworks out there that need you to have modules with no position set, including menu modules

**Comment by shoulders** [comment] 2017-01-16 19:17
create a menu module, assign a menu position and then save. when you go back into the module you **can remove** the module position. It will not let you select 'none' as it does not exist.

This should read **cannot remove**<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13613">issues.joomla.org/tracker/joomla-cms/13613</a>.</sub>

**Comment by Twincarb** [comment] 2017-01-16 20:01
Is this a Joomla issue or a feature that would live in a template. The CMS will only allow you to asign or reasign to a position in the template, so the logic is correct that you can't select none unless that is a valid position in the template.

It would only need to be added as a position to the xml file and not added into the template index.php itself.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13613">issues.joomla.org/tracker/joomla-cms/13613</a>.</sub>

**Comment by shoulders** [comment] 2017-01-16 20:10
I have just checked that this is the case for other modules and it is. I have just gone to an older version of joomla 3.3.6 and you can remove module positions there. There is a cross. Please see the attached image.![screen shot 2017-01-16 at 20 10 45](https://issues.joomla.org/uploads/1/25f04cdaf5f53f386f8d02f450fef17d.jpg)

This is definately a needed feature.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13613">issues.joomla.org/tracker/joomla-cms/13613</a>.</sub>

**Comment by shoulders** [comment] 2017-01-16 20:13
just for clarity when you have clicked the cross it gives you the following option.
![screen shot 2017-01-16 at 20 13 24](https://issues.joomla.org/uploads/1/5914f565ceec0018e53cfd5962046766.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13613">issues.joomla.org/tracker/joomla-cms/13613</a>.</sub>

**Comment by SharkyKZ** [comment] 2017-01-17 06:29
Duplicate of #13243. This is fixed in 3.7.

**Closed** 2017-01-17 07:01 UTC
Labels: No Code Attached Yet

**Comment by boomsya** [comment] 2018-11-27 10:54
bug returned in 3.9.0
The is no delete button (X)

in HTML I have see:
"allow_single_deselect":true
but is no X button

**Comment by boomsya** [comment] 2018-11-27 11:42
![111111](https://user-images.githubusercontent.com/8008462/49079769-37a71a80-f24a-11e8-9b88-496c12629e28.jpg)

**Comment by SharkyKZ** [comment] 2018-11-27 11:45
@boomsya this will be fixed in 3.9.1. See #23052.
