### ISSUE TITLE
Cassiopeia: Top margin of system message container

### ISSUE THREAD

**Issue by Tom582** [joomla/joomla-cms#40639] opened 2023-05-21 13:30 UTC
Hi,

Sorry for adding this new cassiopeia issue here, but the cassiopeia repository has been archived a while ago and I would like to report a new issue related to cassiopeia.

### Steps to reproduce the issue

1. Login at the frontend of a Joomla website running cassiopeia in order to create a joomla-alert
2. A green alert is displayed to confirm a successful login
3. Close the alert by clicking on the green X
4. After the alert has been closed the contents of the main section is offset by 1em with respect to its original state before the login
5. Press F5 in the browser window in order to remove the additional offset and have the original contents of the main section restored

### Expected result
After closing the alert by clicking on the green X, the original contents of the main section should be restored without any extra offset

### Actual result
See step 4 mentioned above

### System information (as much as possible)

- OS: Linux
- Joomla! Version 4.3.1
- PHP Version 8.0.28
- Template cassiopeia override
- Server mysql 5.7.41

### Additional comments
More explanations on this issue can be found in the [Joomla forum](https://forum.joomla.org/viewtopic.php?f=815&t=1001794)

Regards
Tom

**Comment by sandewt** [comment] 2023-05-21 15:40
Sorry Tom, but the link to the forum does not redirect correctly.
![Schermafbeelding 2023-05-21 173907](https://github.com/joomla/joomla-cms/assets/9271775/6e6a90a7-ffd7-406a-af55-cea922569ef5)

**Comment by Tom582** [comment] 2023-05-21 16:59
You are right :-(. Actually, I had noticed that issue and was struggeling with the URL command, but wanted to submit the issue before lunch. So I did not try to find and fix the root cause. I should have read the github editor user's manual. I hope, this time it does work correctly:

More explanations on this issue can be found in the [Joomla forum](https://forum.joomla.org/viewtopic.php?f=815&t=1001794)

Thanks
Tom

**Comment by chmst** [comment] 2023-05-22 05:33
Confirmed. But should be solved with #40539 which removes the login message.

**Comment by brianteeman** [comment] 2023-05-22 06:49
@chmst the login message given as just an example of a problem with all alerts. You can see the same for example when you send an email using the contact form

**Comment by brianteeman** [comment] 2023-05-22 21:18
The problem is created because dismissing the alert does not remove the <noscript> version of the alert and this gets a margin-top of 1em

**Comment by richard67** [comment] 2024-10-10 12:18
Closing as having a pull request. See #44222 .

**Closed as completed by richard67** 2024-10-10 12:18 UTC
Labels: No Code Attached Yet, Frontend Template, bug
