### ISSUE TITLE
Media Folders issue after Joomla 3.5 update

### ISSUE THREAD

**Issue by luludigi** [joomla/joomla-cms#9761] opened 2016-04-06 14:56 UTC
#### Steps to reproduce the issue

We just did some Joomla site update from 3.4.8 to 3.5.
After the update I notice the media folders are stuck in the expanded view mode and it won't collapse when you click on the folder icon. The folders stay in the expand view for all folders no matter what I do, and some folders won't even show up on the scree expect the icons (see screenshot attached). This happen to every Joomla site I upgraded to 3.5.

#### Expected result

It should expand/collapse when we click on the "folder icon".

#### Actual result

It will no longer collapse.

#### System information (as much as possible)

Joomla 3.5 with current updated Linux stacks.

#### Additional comments

Some folder name disappeared on the left column view (see screenshot).

**Comment by brianteeman** [comment] 2016-04-06 14:58
Looks like you didnt attach the screenshot

**Comment by luludigi** [comment] 2016-04-06 14:59
![screen shot 2016-04-06 at 09 59 04](https://issues.joomla.org/uploads/1/3c4fc15ee6cd07b2607ca4899c962627.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9761">issues.joomla.org/joomla-cms/9761</a>.</sub>

**Comment by brianteeman** [comment] 2016-04-06 15:04
I can confirm this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9761">issues.joomla.org/joomla-cms/9761</a>.</sub>

**Comment by luludigi** [comment] 2016-04-06 18:52
FYI - this issue still exist after update to Joomla 3.5.1 today.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9761">issues.joomla.org/joomla-cms/9761</a>.</sub>

**Comment by brianteeman** [comment] 2016-04-06 19:17
As it was never reported before that isnt surprising <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9761">issues.joomla.org/joomla-cms/9761</a>.</sub>

**Comment by Fedik** [comment] 2016-04-06 19:35
can confirm,  even for 3.4.8 :smile:

**Comment by brianteeman** [comment] 2016-04-06 19:41
It does work in 3.4.8 although its a but tricky. You have to move the mouse until it is NOT a hand - see movie
![mediaman](https://cloud.githubusercontent.com/assets/1296369/14330315/eb94dfac-fc37-11e5-92b6-11471c5eb7a2.gif)

**Comment by Fedik** [comment] 2016-04-06 19:44
hm, yes

**Comment by brianteeman** [comment] 2016-04-06 19:50
Took me a while to see it myself

**Comment by brianteeman** [comment] 2016-05-07 15:57
Thank you for submitting this issue/pull request. The media manager is currently being completely rewritten and I have notified the development team about this issue for their consideration. I am closing this here at this time.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9761">issues.joomla.org/joomla-cms/9761</a>.</sub>

**Closed** 2016-05-07 15:58 UTC
Labels: No Code Attached Yet

**Comment by Burnardo** [comment] 2016-12-21 10:53
Sorry to start again on this older issue...
Joomla 3.6.5. and I still have this issue: unable to unfold or collapse media folders.
In my situation the "hand" does not change to an "arrow" as the movie shows. Therefore I am unable to collapse or unfold media folders.

I use to be able, and had to be very precise with moving the mouse around on or in the vicinity of the folder image.
Now there is simply no position on hovering anymore where this occurs.

Might there be a CSS change involved, that simply reduces or completely removed this "hover area" in which the function change should occur?

Kind regards,
Ben<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9761">issues.joomla.org/tracker/joomla-cms/9761</a>.</sub>
