### ISSUE TITLE
Update to 3.10.0  --  ERROR: Could not open archive part file ...

### ISSUE THREAD

**Issue by TerraD** [joomla/joomla-cms#35215] opened 2021-08-18 11:55 UTC
### Steps to reproduce the issue
I updated today from 3.9.28 to 3.10.0 After I started the upgrade process I got the message
```ERROR: Could not open archive part file /www/MyDomain.ch/MyDomain.ch/tmp//Joomla_3.10.0-Stable-Update_Package.zip for reading. Check that the file exists, is readable by the web server and is not in a directory made out of reach by chroot, open_basedir restrictions or any other restriction put in place by your host.```

### Solution
I quickly found the solution to this problem by google:
1. **Login to Joomla Back office** of the website;
2. Go to **System > Global Configuration > Server** tab;
3. **Insert the (correct) absolute path for Temp directory** of a website to *Path to Temp Folder* field, in my case: `/MyDomain.ch/tmp` instead of `/www/MyDomain.ch/MyDomain.ch/tmp/`

### Expected result
Update from 3.9.28 to 3.10

### Actual result
Update aborted with above error message

### System information (as much as possible)
n.a.

### Additional comments
I surely never changed that value for a long time - while doing regular updates... So I just wonder: how was I able to run all the upgrades in the past????

**Comment by zero-24** [comment] 2021-08-18 12:00
I think its also interesting to see the version 3.7.4 in the error message `/www/MyDomain.ch/MyDomain.ch/tmp//Joomla_3.7.4-Stable-Update_Package.zip`

Would it be possible that you can send me a full backup of the 3,9,28 site to tobias.zulauf@community.joomla.org so this can be debugged?

**Comment by RickR2H** [comment] 2021-08-18 14:49
@zero-24 I've had the same issue. In my case the cache was enabled and set to Progressive cache in the configuration. After disabling and cleaning the cache, the update worked... <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35215">issues.joomla.org/tracker/joomla-cms/35215</a>.</sub>

**Comment by zero-24** [comment] 2021-08-18 14:55
> @zero-24 I've had the same issue. In my case the cache was enabled and set to Progressive cache in the configuration. After disabling and cleaning the cache, the update worked...
> 

hmm would be interesting to know what caching settings @TerraD has then but trying to debug the issue on a backup would help to understand why it fails cause caching should not break the upgrade.

**Comment by TerraD** [comment] 2021-08-18 15:12
The version was a wrong scopy/paste action from the solution I found with Google:
`/www/MyDomain.ch/MyDomain.ch/tmp//Joomla_3.7.4-Stable-Update_Package.zip` should correctly be 
`/www/MyDomain.ch/MyDomain.ch/tmp//Joomla_3.10.0-Stable-Update_Package.zip`. I will try to correct that yet in my first post.

**Comment by TerraD** [comment] 2021-08-18 15:19
The cache was disabled.

![2021-08-18_17-17-39-254](https://user-images.githubusercontent.com/3796066/129924995-43e957b9-6607-403b-9e1c-ca1490c8d9d7.png)

**Comment by RickR2H** [comment] 2021-08-18 15:27
Mmm then is must be something else I did. Just to be complete:

Ass far as I recall: After the error I disabled the cache, cleaned all the Joomla cache and browser cache. Then I and went to the Joomla update component and clicked "Check for updates" Then I was able to update.

Hope this helps...

**Comment by zero-24** [comment] 2021-08-18 15:30
Ok thanks thats why I asked for a backup so i can try to reproduce and debug the issue

**Comment by RickR2H** [comment] 2021-08-18 15:31
@zero-24 Check 😉

**Comment by RickR2H** [comment] 2021-08-18 16:17
@zero-24 Managed to find a backup and could reproduce the error locally whis this backup. Hope this helps. Send via WeTransfer.

**Comment by zero-24** [comment] 2021-08-18 16:33
Thanks will take a look into that.

**Comment by zero-24** [comment] 2021-08-19 00:39
Hmm on the backup I have got I could not reproduce the issue that was reported. @TerraD can you provide a backup too?

**Comment by TerraD** [comment] 2021-08-19 08:11
> 
> 
> Hmm on the backup I have got I could not reproduce the issue that was reported. @TerraD can you provide a backup too?

Will do

**Comment by TerraD** [comment] 2021-08-19 08:52
Testmail to to make sure this answer does not get published on GitHub...


Am 19.08.2021 um 02:39 schrieb Tobias Zulauf:

**Comment by TerraD** [comment] 2021-08-19 09:18
I don't know ho to send PN on GitHub. So I sent an email with a 
TresorIt-link to Tobias's published Email. Hope that arrives.

--

**Comment by zero-24** [comment] 2021-08-19 09:26
Yes thanks it reached me will take a closer look into it this afternoon. There is no PN feature in GitHub ;)

**Comment by zero-24** [comment] 2021-08-20 22:18
Hmm I have just installed the site and upgraded it successfully without any issues to Joomla 3.10 while the correct folder was set for my local system by that kickstarter script so it was correct at the time.

When you set the path can you check whether there are any issues reported on System -> System Information -> Permissions?

Thanks

**Comment by TerraD** [comment] 2021-08-21 11:31
> .. When you set the path...

I'm not sure if I should try to change my Temp Path again for your latest question. In my case, before the update to 3.10.0 there was a wrong path in the 'Path to Temp Folder' /www/dog-cart-thurgau.ch/dog-cart-thurgau.ch/tmp/ (so double error: domain name double and '/' at the end). I corrected this and then the upgarade to 3.10.0 was successful!

In the attached screenshot you see my current permissions. The Log folder seems interesting: it has the same structure as the Temp Folder had before and it is marked as 'Writeable'!

![2021-08-21_12-48-39-657](https://user-images.githubusercontent.com/3796066/130319735-07fb8096-3508-453a-8f19-056a9374354a.png)

For a test I changed now 'Path to Temp Folder' to /dog-cart-thurgau.ch/tmp/ and the permissions page will still say it is writeable - however last week I was _not able to update_ with that path: '/dog-cart-thurgau.ch/tmp//Joomla_3.10.0-Stable-Update_Package.zip' was marked as error. So I changed it for my update to /dog-cart-thurgau.ch/tmp

**May I suggest, that it would be good programming practice to allow the user to enter paths with _and_ without the trailing slash!** Due to bad experiences I make all my programs fault-tolerant regarding this issue... (30 years ago you could deduce from MS documentation that the trailing slash is part of the path. But recent MS routines do not indicate that there is still such a rule...)

**Comment by zero-24** [comment] 2021-08-21 11:50
> May I suggest, that it would be good programming practice to allow the user to enter paths with and without the trailing slash! Due to bad experiences I make all my programs fault-tolerant regarding this issue... 

Good idea can you send a PR to take care of this similiar to your programs, so we dont have to reinvent the weel?

**Comment by zero-24** [comment] 2021-08-21 11:51
We might can also extend the validation or filter rule to make sure its set correctly.

**Comment by TerraD** [comment] 2021-08-21 14:42
?PR

**Comment by zero-24** [comment] 2021-08-21 17:43
> ?PR

Pull request on GitHub ;-)

**Comment by TerraD** [comment] 2021-08-22 07:38
Tnx, will send PR

**Comment by TerraD** [comment] 2021-08-22 07:44
Do I need to send a second PR regarding the non-existent Log folder that is considered to be writeable?

**Comment by zero-24** [comment] 2021-08-22 07:52
You can when you have code to handel it correctly.

**Comment by TerraD** [comment] 2021-08-22 08:19
Oh, PR requires a solution... Supposed it to be kind of feature request. I don't have code in PHP for this.

And I have neither for the Slash problem! I have a simple rule: Whenever I handle path-strings I assume them to be with a Slash; but I'll always handle the situation when the user does not supply one!

**Comment by brianteeman** [comment] 2023-09-01 15:54
As Joomla 3 is now end of life and no longer supported I am closing this

**Closed as completed by brianteeman** 2023-09-01 15:54 UTC
Labels: No Code Attached Yet, bug
