### ISSUE TITLE
since 3.7 calendar field doesn't display entirely in a scroll table

### ISSUE THREAD

**Issue by fuscage** [joomla/joomla-cms#20201] opened 2018-04-19 08:19 UTC
### Steps to reproduce the issue
click on the calendar field in a table responsive (with scrool bar) (cf picture in attachment)

With old calendar field:

![screen shot 2018-04-19 at 08 23 04](https://issues.joomla.org/uploads/1/4905eb7861e5a4c502e93a6ce95bd8a0.png)

With new calendar field :

![screen shot 2018-04-19 at 08 22 36](https://issues.joomla.org/uploads/1/9d5e5c8a78578a53fb86f5591dc7e1e0.png)

### Expected result
calendar visible entirely 

### Actual result
calendar not visible entirely 

### System information (as much as possible)
joomla 3.8

### Additional comments
Do you have an idea to have the same result than the old calendar field? 
may be something to change in the css?
Thanks

**Comment by infograf768** [comment] 2018-04-19 08:20
I see no picture here.

**Comment by infograf768** [comment] 2018-04-19 08:27
You are using here a 3rd party extension where the calendar is displayed in a list.
This is not a Joomla issue. Please ask for help in the forums.

**Comment by fuscage** [comment] 2018-04-19 08:30
Ok, can you give me the url ?
Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20201">issues.joomla.org/tracker/joomla-cms/20201</a>.</sub>

**Comment by ghost** [comment] 2018-04-19 09:23
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla-Core coding. For this Reason closing this Issue, thanks.

**Comment by fuscage** [comment] 2018-04-19 11:12
It is sad that in this case, there is a willingness to perfect the scope of the calendar : https://github.com/joomla/joomla-cms/pull/19944
and not in this case...
what a pity

**Comment by ciar4n** [comment] 2018-04-19 11:48
@franz-wohlkoenig I'd suggest reopening this.  I am not so sure this is a 3PD issue. We are basically saying the calendar cant be placed in a table.

**Comment by ghost** [comment] 2018-04-19 12:18
reopened as stated above.

**Comment by dgrammatiko** [comment] 2018-04-19 14:29
>  We are basically saying the calendar cant be placed in a table.

Isn’t also subform build with tables? I think in that case the calendar works pretty decent, so I have no clue what the css used in such case

**Comment by ggppdk** [comment] 2018-04-20 14:09
if you have a CSS rule like:
```css
... div {
    position: relative;
    overflow-y: scroll;
}
```

e.g. in this case something like
```css
td > div {
    position: relative;
    overflow-y: scroll;
}
```

and it matches the outer container of the calendar you will get this effect
because the calendar is placed inside 
```html
<div class="field-calendar">
   <div style="direction: ltr; position: absolute; box-shadow: rgba(0, 0, 0, 0.67) 0px 0px 70px 0px; min-width: 0px; padding: 0px; display: block; left: auto; top: auto; z-index: 1060; border-radius: 20px;" class="js-calendar">
  ...
  </div>
</div>
```

**there is no CSS rules for .field-calendar,**
and if something override the defaults you will get issue like this

Indeed it is not a bug but, some inline CSS for outer container .field-calendar would help ?

**Comment by ggppdk** [comment] 2018-04-20 14:17
Actually there is no guaranteed fix for this
even if you add CSS for .field-calendar that will be hard to override (e.g. inline)

Still someone can place the calendar inside a box with relative positioning, with a limited height and overflow hidden or scroll

Only guaranteed fix would be to have the calendar popup placed under body,

but then you (might) have other problems trying to keep the calendar positioned at the place that it was opened that will even depend on browser, still i think it is worth doing

**Comment by dgrammatiko** [comment] 2018-04-20 18:28
> Actually there is no guaranteed fix for this

Well there is: web components and shadow DOM. But not for J3 :(

**Comment by jwaisner** [comment] 2020-03-13 19:44
Closing this as it has been confirmed as not a bug in J3.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20201">issues.joomla.org/tracker/joomla-cms/20201</a>.</sub>

**Closed as completed by jwaisner** 2020-03-13 19:44 UTC
Labels: No Code Attached Yet
