### ISSUE TITLE
[4.0] Help TOC is not rebuilding correctly

### ISSUE THREAD

**Issue by particthistle** [joomla/joomla-cms#32419] opened 2021-02-14 14:12 UTC
The Joomla 4 Help index is missing a number of help documents.
- https://docs.joomla.org/Category:Help_screen_4.0 shows 235 pages.
- The help index in Beta 8 currently shows 86 pages.

When you attempt to rebuild the list manually, there's an error, but rebuilding the list manually should not be something expected of end users - the helptoc.json I would think is provided to users in the Joomla package and when they update their websites.

### Steps to reproduce the issue
To view the index go to Help > Joomla! Help in the Joomla 4 administrator dashboard.
![image](https://user-images.githubusercontent.com/5515866/107724674-86143700-6d38-11eb-86a7-90323d715271.png)

Two examples of missing items are help pages on Mail Templates (eg https://docs.joomla.org/Help4.x:Mail_Templates) and Workflow (eg https://docs.joomla.org/Help4.x:Workflows_List)

To attempt to rebuild the index execute `php build/helpTOC.php` (which needs NPM and Composer run to install dependencies)

### Expected result

The help index should match the number of Joomla 4 help items available (235 at time of raising the issue).

### Actual result

The help index currently only has 86 help pages in the index.
~Running the index build command `php build/helpTOC.php` returns an error if you have not got NPM installed.~

### System information (as much as possible)

Issue exists in Joomla version, ‎4.0.0-beta8-dev

### Additional comments

After discussion, the issue has transformed considerably. There is nothing wrong with the build/helpTOC.php process directly.

The problem is that there's a significant number of language strings missing for the additional pages. A PR will follow.

Previous related issues:
https://github.com/joomla/joomla-cms/issues/19308 Issue initially raised
https://github.com/joomla/joomla-cms/issues/29788 Variation raised
https://github.com/joomla/joomla-cms/pull/29804 PR for 29788, but may not have been fully tested before merging?

**Comment by brianteeman** [comment] 2021-02-14 14:21
The script is a command line script and based on your screenshot you are trying to run it in the browser.

I have just run the script at the command line and it runs without error and generates 86 pages.

Why do you expect there to be more pages

**Comment by brianteeman** [comment] 2021-02-14 14:31
https://github.com/joomla/joomla-cms/blob/4a6f30eb2a419976a2a3aaa6c73a89f56e1f0343/build/helpTOC.php#L139-L141

**Comment by brianteeman** [comment] 2021-02-14 14:47
In summary. If there is no language string found then it is not included

**Comment by particthistle** [comment] 2021-02-16 06:38
The issue has three parts to it now...

### ~Part 1: Abstract Method error in PHP stops the index being generated.~
Command line failed for me too, giving the same error message as showed at the top of the browser screen shot.
`Error: Class MediawikiCli contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Joomla\CMS\Application\CMSApplicationInterface::getName)`

I've tested it via PHP 7.4.9 and 7.3.21 - both threw the error. PHP 5.6 doesn't throw the error, but also doesn't rebuild the toc.json file for me.

![image](https://user-images.githubusercontent.com/5515866/108020653-ec6ac380-7070-11eb-9e7b-c8d7aebcaa4e.png)

### Part 2: What's the language string that is being looked at?
So from your note @brianteeman I've looked at the code closer and the TOC is created by:

- opening /administrator/language/en-GB/com_admin.ini
- looking for strings with "COM_ADMIN_HELP" as their prefix
- processing those strings into the TOC.

So I've manually done that to see what I could see.

86 of 89 current strings are included in the current Help TOC. These three did not make it into the TOC (or the TOC that I'm currently seeing via nightly builds).

```
COM_ADMIN_HELP_COMPONENTS_ACTIONLOGS="Action Logs"
COM_ADMIN_HELP_COMPONENTS_SEARCH="Search"
COM_ADMIN_HELP_SITE_MAINTENANCE_PURGE_EXPIRED_CACHE="Cache: Clear Expired Cache"
```

So based on what the script does, if it works as expected, then the TOC is generating correctly (except for these three items).

### Part 3: Why should there be 235 items?

There should be 235 items (or a subset greater than 86), as that's how many help screens are available in JDOCs on different parts of Joomla 4. At a quick glance, Workflow and Mail Templates are two new Joomla 4 features missing from the TOC which then generated the issue.

The missing part therefore may not be an issue with the tool that generates the TOC, but instead requires a PR to add more COM_ADMIN_HELP strings into /administrator/language/en-GB/com_admin.ini in order to cover what's missing from https://docs.joomla.org/index.php?title=Category:Help_screen_4.0

**Comment by particthistle** [comment] 2021-02-16 09:06
### Update
Part 1 is now resolved: To run the build/helpTOC.php command, additional dependencies are required. As a typical end user will not need to run this command, no further action is required at this time.

Part 2 will be revisited after the PR to fix Part 3 has been merged to check that the new strings are added to the TOC.

Part 3 hope to be resolved with an additional PR to add the missing language strings to the com_admin.ini.

Thanks for having me take a closer look @brianteeman and for the clarifying conversation in BFH @richard67 & @alikon

@ceford - Will be in discussion on Glip more as you're the most across the Help Screens creation process.

**Comment by wilsonge** [comment] 2021-02-16 23:03
> To run the build/helpTOC.php command, additional dependencies are required. As a typical end user will not need to run this command, no further action is required at this time

Actually the part about additional dependencies is probably not true. In fact what's more likely is that you're running a very dated version of the code - https://github.com/joomla/joomla-cms/pull/29804

Although indeed to run build scripts you will need more than is in the standard nightlies.

Part 2 is just a fix to the language strings to point to the correct pages (e.g. the clear cache is trying to ping https://docs.joomla.org/Help4.x:Cache:_Clear_Expired_Cache based on that lang string you pasted but the page is actually at https://docs.joomla.org/Help4.x:Site_Maintenance_Purge_Expired_Cache)

Indeed part 3 is just create the language strings :)

**Comment by brianteeman** [comment] 2021-02-21 09:41
This should be closed as the issue is resolved and @particthistle now knows what to do to add additional articles to the helpTOC

**Comment by richard67** [comment] 2021-02-21 09:45
Closing due to reasons stated in previous comment. Feel free to re-open if you think this is wrong.

**Comment by brianteeman** [comment] 2021-05-31 09:07
Please re-open as it would appear that no one has added the additional articles to the helpTOC

**Comment by richard67** [comment] 2021-05-31 09:10
> Please re-open as it would appear that no one has added the additional articles to the helpTOC

@brianteeman Do you know who can do that? Maybe @ceford ?

**Comment by ceford** [comment] 2021-05-31 11:09
What is this list for? I have always assumed it to be the main topics. Even at 86 items it is quite long. At 235 it would be a very long scroll to Users. Also, I think individual plugins need individual links - at the moment they all share one link. That would be another 96+. Redesign or leave at 86?

**Comment by brianteeman** [comment] 2021-05-31 11:53
Right now there are major gaps - such as mail templates

**Comment by alikon** [comment] 2024-04-10 17:43
please test #43250

**Closed as completed by alikon** 2024-04-10 17:43 UTC
Labels: No Code Attached Yet, bug
