### ISSUE TITLE
[4.3.3] Display list of articles of Tag

### ISSUE THREAD

**Issue by 1inkin** [joomla/joomla-cms#41186] opened 2023-07-18 15:19 UTC
### Steps to reproduce the issue
1. create tags Tag1 and Tag3
2. create some articles for tags
3. create a Menu1 type Tagged Items for Tag1
4. create Popular Tags Module
5. in the frontend in the Popular Tags Module select Tag1

### Expected result
opened a page with a list of articles of Tag1 as like for Tag3

### Actual result
opened a page of Menu1

### Additional comments
![screen shot 2023-07-18 at 15 18 08](https://issues.joomla.org/uploads/1/c14bc0ccb373f27addf3b64928c1d2e9.jpg)
![screen shot 2023-07-18 at 15 18 18](https://issues.joomla.org/uploads/1/3a2162860dc937a973bc48118a06909b.jpg)

**Comment by brianteeman** [comment] 2023-07-18 15:22
please dont open multiple issues for then same thing

**Comment by richard67** [comment] 2023-07-19 09:10
Duplicate report to #41179 ?

**Comment by 1inkin** [comment] 2023-08-25 07:59
I think the original problem is the same, but slightly different methods of detection<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41186">issues.joomla.org/tracker/joomla-cms/41186</a>.</sub>

**Comment by brianteeman** [comment] 2023-09-01 22:02
I'm not really sure what you are asking for here.

**Comment by Hackwar** [comment] 2024-03-28 09:27
I'm sorry, but as far as I can understand you, this is expected behavior. If you click on a tag, you get the menu item which displays content for that tag, not for another tag. Since the screenshots are not available anymore, I also don't see any other way to interpret that. Closing this issue.

**Closed as completed by Hackwar** 2024-03-28 09:27 UTC
Labels: No Code Attached Yet, Information Required
