### ISSUE TITLE
[3.9.10][4.0][upgrade]After upgrade Global Configuration displays only 'Site' tab

### ISSUE THREAD

**Issue by toivo** [joomla/joomla-cms#31583] opened 2020-12-04 16:30 UTC
### Steps to reproduce the issue
Install Joomla 3.9.10 Alpha4-dev.
Download Joomla 4.0 Beta6-dev.
Apply PR#31575 to the upload package.
Components - Joomla! Update - Upload & Update, choose file, click 'Upload & Install'

### Expected result
Global Configuration displays all tabs.

### Actual result
Only 'Site' tab is displayed.

### System information (as much as possible)
Windows 10, Wampserver 3.2.4, Apache 2.4.43a, MySQL 8.0.20, PHP 7.4.13
Joomla 3.9.10 Alpha4-dev Full of 4 December, Joomla 4.0 Beta6-dev Update of 4 December (PR#31575 applied)

### Additional comments
After logout and login all the tabs are displayed.  Even if this is the case, users upgrading to Joomla 4 need to be able to access all the tabs in Global Configuration straightaway.

**Comment by toivo** [comment] 2020-12-20 12:19
Tested 3.10.0-alpha4-dev upgrade to 4.0.0-beta6-dev using Nightly Builds of 20 December with PHP 8.0.0.  
This issue remains the same:  System - Setup - Global Configuration displays only the Site tab.

**Comment by richard67** [comment] 2021-06-02 13:47
I could reproduce this problem once but it seems it was related to JS and old json stuff in session data, because after a log out and closing of the browser it was ok.

Maybe @dgrammatiko remembers more details?

**Comment by Quy** [comment] 2021-07-17 20:49
Please test PR #34813

**Closed as completed by Quy** 2021-07-17 20:49 UTC
Labels: No Code Attached Yet
