### ISSUE TITLE
Error in path management on local windows system!

### ISSUE THREAD

**Issue by knut32** [joomla/joomla-cms#11994] opened 2016-09-09 06:03 UTC
### Steps to reproduce the issue
Actually see it in the DJ Mega Menu modul:
Here in Joomla 3.6.2
![joomla_36](https://cloud.githubusercontent.com/assets/20967164/18376938/a6079ee2-7663-11e6-846e-b7c56067e893.jpg)

And same modul in Joomla 3.5
![joomla_35](https://cloud.githubusercontent.com/assets/20967164/18376941/b228f09a-7663-11e6-860a-9a8c653ea8b9.jpg)

**Comment by Bakual** [comment] 2016-09-09 06:17
Can you tell us what server you are using on your Windows? XAMPP, MAMP, IIS?
And did you ask the developer of that module? It would help to know what formfield / code he is using there.

**Comment by Bakual** [comment] 2016-09-09 06:23
Found it. It's the `JFormFieldFolderlist` and I can reproduce it with XAMPP.

**Comment by knut32** [comment] 2016-09-09 06:30
I use neigher XAMPP nor IIS. Use Apache, php and mysql installed by myself :)

**Comment by knut32** [comment] 2016-09-09 06:36
Found it. Search for JFormFieldFolderlist and found that:

[https://github.com/joomla/joomla-cms/issues/11308](url)

**Comment by Bakual** [comment] 2016-09-09 09:07
Indeed. There is also already a PR which should fix it: https://github.com/joomla/joomla-cms/pull/11288
Can you please test that one?

I'm closing this issue since we have a PR.

**Closed by Bakual** 2016-09-09 09:07 UTC
