### ISSUE TITLE
Search is not working on 3.7.0-alpha2

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/joomla-cms#13569] opened 2017-01-12 08:42 UTC
### Steps to reproduce the issue

1. Install the latest build, E.g blog option
2. Search in the homepage module 
3. It shows the results and an error: "Error. An error has occurred."

### Expected result

No error

### Actual result

"Error. An error has occurred."

### Additional comments

From the Glip channel:

* Tomasz Narloch (csthomas) shared a link
I suspect https://github.com/joomla/joomla-cms/pull/13348

* Tomasz Narloch (csthomas)
After `git revert 7c547687af` error disappears

**Comment by infograf768** [comment] 2017-01-12 08:45
@Bakual 

Can you look into this?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13569">issues.joomla.org/tracker/joomla-cms/13569</a>.</sub>

**Comment by anibalsanchez** [comment] 2017-01-12 08:48
Ole Ottosen uploaded this image
![modified](https://cloud.githubusercontent.com/assets/385780/21882766/49370652-d8ac-11e6-80fc-a42b8850d85e.png)

**Comment by Bakual** [comment] 2017-01-12 09:04
I can't replicate this on my testing installation. Also tried to install fresh.

Do you have any special setting that I need to reproduce this?

**Comment by anibalsanchez** [comment] 2017-01-12 09:06
Database Version 	5.7.16-0ubuntu0.16.04.1 
PHP Version 	7.0.8-0ubuntu0.16.04.3 
Web Server 	Apache/2.4.18 (Ubuntu) 
Joomla! Version 	Joomla! 3.7.0-alpha2 dev

**Comment by infograf768** [comment] 2017-01-12 09:11
I confirm the issue here

**Comment by anibalsanchez** [comment] 2017-01-12 09:12
I've re-installed a fresh build... and the issue remains.

**Comment by Bakual** [comment] 2017-01-12 09:14
I'm testing on XAMPP so far, but I don't think its related to any software version. The PR in question does pretty standard stuff.

**Comment by infograf768** [comment] 2017-01-12 09:14
I am using MAMP. php 5.4.4

**Comment by infograf768** [comment] 2017-01-12 09:15
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INTEGER) = a.id LEFT JOIN #__fields AS f ON f.id = fv.field_id WHERE ((LOWER(a.' at line 4

**Comment by Bakual** [comment] 2017-01-12 09:43
Can you try if it works with https://github.com/joomla/joomla-cms/pull/13571?

Closing this since we have a PR

**Closed by Bakual** 2017-01-12 09:43 UTC
Labels: No Code Attached Yet
