### ISSUE TITLE
[com_fields] values equal to defaults are not saved

### ISSUE THREAD

**Issue by Denitz** [joomla/joomla-cms#18546] opened 2017-11-10 08:25 UTC
### Steps to reproduce the issue
Create custom user text field with default value `Joomla`.
Edit user, see `Joomla` in field input.
Save user.

### Expected result
`Joomla` field value record in `#__fields_values` table.

### Actual result
No field value record in `#__fields_values` table.

### Additional comments
This behavior is really frustrating:
User sees data, clicks save and is sure that the field was saved with this value.
Next admin can change default value and user will see this another new value once he edit profile again.

Besides having custom field value missed creates problems with loading fields data: the value doesn't exist and we can't know was that item (e.g. user profile or an article) updated with fields data or not.

Custom field's default value should be treated as default field value if there is no value saved before.
Once an item is saved, this value should be stored in `#__fields_values` table just as usual regular value.

**Comment by AndySDH** [comment] 2017-11-10 13:58
Issue confirmed. I noticed this too a long time ago but figured it was intended and didn't think much of it as I don't make use of default values.

But yeah, thinking about it, I 100% agree with you that the expected result that you describe would definitely be the preferred behavior.

**Comment by tonypartridge** [comment] 2017-11-14 00:59
I have to agree that would make sense, since it’s default value not global value.

**Comment by effrit** [comment] 2017-11-27 16:25
Completely agree!
It also produce search/filtering problem.

**Comment by Arkadiy-Sedelnikov** [comment] 2017-11-27 16:33
If you change the default value of the field will change all the field values in the articles, which was equal to the default value. It is not correct. It should not be.

**Comment by ghost** [comment] 2017-11-27 17:30
closed as having Pull Request #18891

**Closed as completed** 2017-11-27 17:29 UTC
Labels: No Code Attached Yet
