### ISSUE TITLE
Template Layout for Category Blog not working correctly

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#16926] opened 2017-06-30 14:01 UTC
### Steps to reproduce the issue
Create a Layout override for Category Blog
Create an Alternative Menu item Type for the new Layout

### Expected result
The new Layout should be selectable in Content Options and in the Options of Categories

### Actual result
The Layout is only selectable when 
There is no underscore in the name 
and
There is no xml file for the Alternative menu item

The Alternative Layout should be selectable when it has an Alternative Menu item Type

### Additional comments
Spotted by sagaranvekar in https://forum.joomla.org/viewtopic.php?f=713&t=952306

**Comment by brianteeman** [comment] 2017-06-30 14:05
Underscores have a specific meaning in layouts as they indicate that they are a aublayout.. see the default blog layout for an example of what I mean. So I would suggest it is expected behaviour that a file with am underscore is not displayed as an available layout.

**Comment by Webdongle** [comment] 2017-06-30 14:45
@brianteeman 
Yep thought that might be the case with underscores.  But the inability to select a Layout Override in Content Options and in a Category should be there even if there is an alternative Menu item Type for it.

**Comment by brianteeman** [comment] 2017-06-30 14:58
not sure but that part sounds like an existing issue that we have a PR for testing see #16755

**Comment by Webdongle** [comment] 2017-06-30 15:45
It may be linked but I think it is a separate issue.  Creating a Alternative Layout menu item for a Category blog  Override prevents the blog override being selected.  But The same is not true for an Alternative menu Item of an Article Layout Override.  I will test with the patch for the other issue and see.

This one looks like it's going to be complicated.

**Comment by Webdongle** [comment] 2017-06-30 17:29
Closing in favour of #16755

**Comment by franz-wohlkoenig** [comment] 2017-06-30 17:37
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16926">issues.joomla.org/tracker/joomla-cms/16926</a>.</sub>

**Closed by franz-wohlkoenig** 2017-06-30 17:37 UTC
Labels: No Code Attached Yet

**Comment by Sieger66** [comment] 2017-07-02 18:27
@Webdongle 
`Steps to reproduce the issue
Create a Layout override for Category **Blog**`
I dont know your Issue 16926 come from the same bug as is noticed in the Pull Request(PR) 16755.
PR 16755 is a new feature and sollution to make it easy to use an 
Alterative-Article-Layout-Override 
in a article-category-list-menuitem

This Alternative Layout is working for the view of a single Article
(view after if you click on a article of the article-category-list)

In PR 16755 it is only a little inconsistence of the "Alternative Layout for Article"-field.
But the rest works as expected.

But if i understand your issue right do you want a Alternative-Category-Blog-Layout-Override.

A quick solution for this:

Version 1:
This for a category of articles in alternative-blog-view:
After you have make a correct override (without xml-file) in templates/templat_name/html/com_content/category/
then you can go in backend to:
Content -> Categories -> (yourCategorie) -> Options -> Layout - select your Alternative-Layout-Override
for this categorie and save it. It make for me no sense to have an xml-file for this because the view comes from the categorie and not from a menuitem how works with the xml.

Version 2:
This for a Alternative Menu item Type for category of articles in blog-view:
After you have make a correct override (with xml-file) in templates/templat_name/html/com_content/category/
then you can go in backend to:
Menus -> (yourMenu) -> New -> Select -> Articles -> (yourOverride)
to create a menuitem with this Layout.

Version 3 :
If you need the same Layout for both then you can make two layouts(copy)
one layout with xml and one without xml with the "same" in it.
For example: 
my-blog-layout-duplikat.php
my-blog-layout-duplikat.xml  
my-blog-layout-duplikat_children.php  
my-blog-layout-duplikat_item.php 
my-blog-layout-duplikat_links.php   

my-blog-layout.php
my-blog-layout_children.php  
my-blog-layout_item.php  
my-blog-layout_links.php

**Comment by Webdongle** [comment] 2017-07-02 21:31
> Version 1:
This for a category of articles in alternative-blog-view:
After you have make a correct override (without xml-file) in templates/templat_name/html/com_content/category/
then you can go in backend to:
Content -> Categories -> (yourCategorie) -> Options -> Layout - select your Alternative-Layout-Override
for this categorie and save it. It make for me no sense to have an xml-file for this because the view comes from the categorie and not from a menuitem how works with the xml.

But the problem is that once an xml file is created then the option for that layout disappears in categories.

your version 2 ... same   But the problem is that once an xml file is created then the option for that layout disappears in categories

Your version 3 same But the problem is that once an xml file is created then the option for that layout disappears in categories

**Comment by Sieger66** [comment] 2017-07-02 22:34
> But the problem is that once an xml file is created then the option for that layout disappears in categories.

This is  intended read #9464

> Your version 3 same But the problem is that once an xml file is created then the option for that layout disappears in categories

You dont need this in  categories because you have the self layout in and can choose
my-blog-layout.php
my-blog-layout_children.php
my-blog-layout_item.php
my-blog-layout_links.php
