### ISSUE TITLE
Backend and frontend broken in 4.1!

### ISSUE THREAD

**Issue by rbuelund** [joomla/joomla-cms#37099] opened 2022-02-20 08:51 UTC
### Steps to reproduce the issue
Updated a site from 3.10.5 to 4.0.6. Changed to Cassiopeia template from protostar. Evrything was working.
Updated the site to 4.1 and repaired database

### Expected result
Everything should work fine

### Actual result
Backend and frontend templates broken - no styling anymore.

### System information (as much as possible)
PHP 7.4

**Comment by rbuelund** [comment] 2022-02-20 08:52
It actually seems that bootstrap is not loaded anymore, after update to 4.1 !?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37099">issues.joomla.org/tracker/joomla-cms/37099</a>.</sub>

**Comment by Fedik** [comment] 2022-02-20 09:04
You probably missed DB update:
```sql
UPDATE `#__template_styles` SET `inheritable` = 1 WHERE `template` = 'atum' AND `client_id` = 1 OR `template` = 'cassiopeia' AND `client_id` = 0;
```

Please check this issue #37057 
Comments
This https://github.com/joomla/joomla-cms/issues/37057#issuecomment-1045004836
Or this https://github.com/joomla/joomla-cms/issues/37057#issuecomment-1046013495
should help

**Comment by Fedik** [comment] 2022-02-20 11:00
Closing as duplicate of  #37057

**Closed as completed by Fedik** 2022-02-20 11:00 UTC
Labels: No Code Attached Yet
