### ISSUE TITLE
hreflang links missing in header

### ISSUE THREAD

**Issue by v912485** [joomla/joomla-cms#13359] opened 2016-12-23 17:12 UTC
### Steps to reproduce the issue
Have a multi-lingual installation with language filter installed and enabled
Install custom component
Create 2 menus for each language
Create a menu item for the component in each menu and set the appropriate language for the menu items
Associated the menu items of the two languages

### Expected result
Alternate links are generated in the header of the page such as:
```<link href="http://example.com/es/my-page" rel="alternate" hreflang="es" />```

### Actual result
These links are missing for the different languages

### System information (as much as possible)
Joomla! 3.6.5 Stable

### Additional comments
The hreflang links are generated fine for normal article pages.

**Comment by infograf768** [comment] 2016-12-23 17:22
Which component is that?

**Comment by v912485** [comment] 2016-12-23 17:47
BreezingForms, JComments and my own custom built components are the ones where I have noticed it so far.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13359">issues.joomla.org/tracker/joomla-cms/13359</a>.</sub>

**Comment by infograf768** [comment] 2016-12-24 06:53
Please install a test site with https://github.com/joomla/joomla-cms/archive/staging.zip
Install as multilang and then your components and test again.

**Comment by infograf768** [comment] 2016-12-24 07:42
Hmm, I confirm the issue with JComments when `sef` is on when using staging.
`$active_link` is NOT equal to `$current_link`, therefore `$associations` is not checked.
It works fine when sef is off.

@andrepereiradasilva 
can you have a look at this please?

**Comment by v912485** [comment] 2016-12-24 10:24
Given that it's now confirmed, do I still need to test with staging?
Yes, I also have sef enabled.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13359">issues.joomla.org/tracker/joomla-cms/13359</a>.</sub>

**Comment by infograf768** [comment] 2016-12-24 10:31
No need indeed to test in staging until we find a solution, if possible.
At this time I think that the issue is with the component itself (JComment in my tests)

I get here on a staging test site
`'/sqltest/trunkgitnew/index.php/fr/comments-list-fr?view=comments'` for `$active_link`
and
`'/sqltest/trunkgitnew/index.php/fr/comments-list-fr'` for `$current_link`

any core component gets these fine and equal
Example: a contact list categories gets
`'/sqltest/trunkgitnew/index.php/fr/list-contacts-categories-fr'`
for both variables.

**Comment by franz-wohlkoenig** [comment] 2017-02-06 13:08
Issue also on latest 3.7-staging.

**Comment by ethernidee** [comment] 2018-01-30 14:05
Having 3 menu items for different languages (all associated) is a problem, when you decide to unpublish/move to trash any item and even article/category for that item.

languagefilter inserts the following links:

    <link href="https://domain.tld/?id=10" rel="alternate" hreflang="en-GB" />

?id=10 is category ID. Seems like only removing association at all helps in this case.

**Comment by infograf768** [comment] 2018-01-30 16:04
Moving to trash or Deleting?

**Comment by infograf768** [comment] 2018-01-30 16:06
Also @ethernidee 
Your issue has nothing to do with this one which deals with hreflang.

**Comment by ethernidee** [comment] 2018-01-30 19:03
I've tried unpublishing and moving to trash. Updated previous comment, parser consumed html link. Deleting association from both category and menu item works. Simple unpublishing/moving to trash does not work (still generates garbage hreflang and language switcher flag link).

**Comment by infograf768** [comment] 2018-01-31 07:26
I can't reproduce your issue. Testing on 3.8.4.
When an associated item is Unpublished or Trashed (not even deleted), the corresponding hreflang is not present in Source.
It still appears as Associated though in the manager until deleted.

**Comment by ethernidee** [comment] 2018-01-31 12:14
Did you try to unpublish/delete item with default site language and navigate to associated item in another language?

**Comment by infograf768** [comment] 2018-02-02 09:04
Yes, for menu items, but see further as your case looks different.
Example here for a menu item
Categories_gb is unpublished but still associated to Catégories(fr)
![screen shot 2018-02-02 at 09 36 30](https://user-images.githubusercontent.com/869724/35724064-c74217b4-07fc-11e8-823b-c58732265a45.png)

Then, in frontend, I display Catégories(fr)
![screen shot 2018-02-02 at 09 41 39](https://user-images.githubusercontent.com/869724/35724240-51e64f70-07fd-11e8-9da5-2c83b18951f5.png)

No hreflang
<img width="1052" alt="screen shot 2018-02-02 at 09 42 59" src="https://user-images.githubusercontent.com/869724/35724304-834ff7a0-07fd-11e8-888d-c67ac2d0991a.png">

As home pages are associated by default I do get the hreflang there
<img width="1088" alt="screen shot 2018-02-02 at 09 44 49" src="https://user-images.githubusercontent.com/869724/35724399-d9d4058a-07fd-11e8-9aa4-841462bd090f.png">

-------------------
But I found an error when there is no specific menu item and an associated category is unpublished.
That may be your case.
![screen shot 2018-02-02 at 09 51 24](https://user-images.githubusercontent.com/869724/35724613-ac94192e-07fe-11e8-81f1-7408dd276069.png)

In that case I evidently get a 404 for the unpublished category and its articles when switching via the module (IN 3.8.4. This will be corrected in 3.8.5 by https://github.com/joomla/joomla-cms/pull/19512 , BUT also a wrong hreflang when I display Catégorie (fr-fr) 
```
<link href="http://localhost:8888/installmulti/trunkgitnew/fr/catégories-fr/9-categorie-fr-fr.html" rel="alternate" hreflang="fr-FR" />
	<link href="http://localhost:8888/installmulti/trunkgitnew/en/component/content/category.html?id=8" rel="alternate" hreflang="en-GB" />
```
After merging https://github.com/joomla/joomla-cms/pull/19512 I will get the same you had , i.e. 
```
<link href="http://localhost:8888/installmulti/trunkgitnew/fr/catégories-fr/9-categorie-fr-fr.html" rel="alternate" hreflang="fr-FR" />
	<link href="http://localhost:8888/installmulti/trunkgitnew/en/?id=8" rel="alternate" hreflang="en-GB" />
```

Therefore I confirm the bug for hreflang

**Comment by infograf768** [comment] 2018-02-02 09:06
@andrepereiradasilva 
Do you see a way to solve this issue.

**Comment by ethernidee** [comment] 2018-02-02 10:47
@infograf768, thanks for investigation.
I've tried creating 3 categories in different languages and three menu items for them, then unpublished/deleted to trash 1 category or 1 menu item, or category and item at the same time. Mainly, the one of default site language.
Let's say it's "News" with blog layout. Then whenever I navigate to any of the rest 2 menu items I see 3 hreflang with ?id=... for unpublished/removed one. Trying to access it gives 404.
Moreover, language switcher plugin displays 3 flags (it's ok) and link for default site language is the same as for hreflang.

**Comment by infograf768** [comment] 2018-02-03 09:40
I am working on a patch.

**Comment by infograf768** [comment] 2018-02-03 11:07
Please test https://github.com/joomla/joomla-cms/pull/19551

Closing as we have a PR

**Closed by infograf768** 2018-02-03 11:07 UTC
Labels: No Code Attached Yet

**Comment by infograf768** [comment] 2018-02-04 12:23
@ethernidee 
Please test https://github.com/joomla/joomla-cms/pull/19551
