### ISSUE TITLE
No back button or re-enter password superuser on installation

### ISSUE THREAD

**Issue by yolknet** [joomla/joomla-cms#42478] opened 2023-12-06 20:10 UTC
When installing a new Joomla 5.0.1 the first step is to fill out the password of the superuser:

![step-1](https://github.com/joomla/joomla-cms/assets/10888068/19219150-7486-4c0a-80c4-a3d229565d63)

Although the password is less than 12 characters I'm able to proceed to the next step. After filling out the database credentials I run into the following error:

![step-2](https://github.com/joomla/joomla-cms/assets/10888068/9fd02f48-5027-4b14-b530-0601b2f0dcac)

The installation stops, but what should I do next? There is no back button, no field to re-enter the password and according to the message under the progress bar the installation is running. The only thing I can do is refresh the screen and start all over again with the name of the site.

**Comment by Quy** [comment] 2023-12-10 15:11
Closing as duplicate of #42289.

**Closed as completed by Quy** 2023-12-10 15:11 UTC
Labels: No Code Attached Yet
