### ISSUE TITLE
Custom errorpage (error.php) not loaded if modern router is on

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#14315] opened 2017-03-03 01:25 UTC
### Steps to reproduce the issue
With protostar, type in an non existing URL -> you will be redirected to the error.php layout
https://gyazo.com/1b40c0383c7447be93fd83fcf03e03d0

Turn on modern router and type in an non existing URL -> you will be redirected to the Home page.
https://gyazo.com/7e599085b034c0cef9aebceaebb68d07

**Comment by infograf768** [comment] 2017-03-03 08:06
Known issue. We were told it would be solved until 4.0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14315">issues.joomla.org/tracker/joomla-cms/14315</a>.</sub>

**Comment by coolcat-creations** [comment] 2017-03-03 20:20
So you can´t enable the new router until it´s fixed?
That´s not a minor issue for SEO ?

**Comment by coolcat-creations** [comment] 2017-03-03 23:03
Can you please reopen it since this bug is also in Legancy mode when logged in. If you have no choice to avoid this behaviour thats a huge loss. 

Logged in: 
https://gyazo.com/ca8f6ce436e33469e8cabf7d20341a5d

https://gyazo.com/5b5a19351fe30a4c77a85e6e472d1fd0

**Comment by Hackwar** [comment] 2017-03-04 11:14
As far as I can see, you are being redirected when opening the false URL in legacy routing. The issue still is the same as in #12822 and thus this one should (again) be closed.

**Comment by coolcat-creations** [comment] 2017-03-04 13:55
Ok, i thought it was closed because "it will not be fixed". I think this is a real problem and has to be fixed. Not just until 4.x

**Comment by mbabker** [comment] 2017-03-04 16:56
Closing, duplicate of #12822

**Closed by mbabker** 2017-03-04 16:56 UTC
Labels: No Code Attached Yet
