### ISSUE TITLE
[4] Regression means you have to click twice to modify passwords in widget

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33703] opened 2021-05-09 14:08 UTC
### Steps to reproduce the issue

Find this widget anywhere in Joomla.  One example is the db password in global config. 

System -> Global config -> server tab

<img width="939" alt="Screenshot 2021-05-09 at 15 07 05" src="https://user-images.githubusercontent.com/400092/117575104-5034e380-b0d8-11eb-81d0-ae316aefe8d6.png">

### Expected result

Click ONCE on modify to enable the field and allow changes.

### Actual result

Click TWICE on modify  to enable the field and allow changes.

### System information (as much as possible)

safari on mac, no console errors.

**Comment by himanshu007-creator** [comment] 2021-05-09 15:54
I would like to work on this issue.
My approach:-
The <code>Modify </code> button is used to toggle locked state of the input. The problem is caused by button not having the <code>locked</code> class initially. So when the <code>Modify</code> button is clicked for the first time, it adds the locked state to input. And after that the normal toggle behavior is experienced.
Just adding <code>locked </code> class to input initially will solve this issue.

**Comment by richard67** [comment] 2021-05-09 16:55
Closing as having a pull request. Please test #33708 . Thanks in advance.

**Closed as completed by richard67** 2021-05-09 16:55 UTC
Labels: No Code Attached Yet
