### ISSUE TITLE
error in page landing identifier 

### ISSUE THREAD

**Issue by pr410** [joomla/joomla-cms#12601] opened 2016-10-27 20:36 UTC
### Steps to reproduce the issue
Please Go on this Link: https://volunteers.joomla.org/joomlers 
and click on home -- Joomlers -- My Profile

### Expected result
when a user clicks on my profile link, it's hard for the user to identify on a navigation bar that on which page the user is.
Identifier must be able to stay on the respective page. 
### Actual result
Page Identifier lands from my profile to joomlers. 

### Additional comments
 
https://volunteers.joomla.org/joomlers

**Comment by andrepereiradasilva** [comment] 2016-10-27 20:42
please report in https://github.com/joomla/joomla-websites

**Comment by zero-24** [comment] 2016-10-27 20:53
@sanderpotjer please tanke a look here.

As itvis no core issue i'm closing here.

**Closed by zero-24** 2016-10-27 20:53 UTC

**Comment by pr410** [comment] 2016-10-27 21:05
hi,

I have done that.

https://github.com/joomla/joomla-cms/issues/12601

[https://avatars1.githubusercontent.com/u/22744355?v=3&s=400]<https://github.com/joomla/joomla-cms/issues/12601>

error in page landing identifier · Issue #12601 · joomla/joomla-cms<https://github.com/joomla/joomla-cms/issues/12601>
github.com
Steps to reproduce the issue Please Go on this Link: https://volunteers.joomla.org/joomlers and click on home -- Joomlers -- My Profile Expected result when a user clicks on my profile link, it...





Thanks


________________________________

**Comment by pr410** [comment] 2016-10-27 21:07
but the issue is not fixed,

it's not a core issue. However, it would be nice to fix this minor issue please.

**Comment by sanderpotjer** [comment] 2016-10-27 21:15
@pr410 the issue is closed over here, because this is the repository for the Joomla CMS itself. I moved the issue to the repository for volunteers.joomla.org: https://github.com/joomla/volunteers.joomla.org/issues/61

**Comment by zero-24** [comment] 2016-10-27 21:20
:+1:
