### ISSUE TITLE
Manual sort articles in backend will delete Article-Tags

### ISSUE THREAD

**Issue by dieseitenwerkstatt** [joomla/joomla-cms#18317] opened 2017-10-12 12:49 UTC
### Steps to reproduce the issue
- Create some tags
- Create some articles and tag them randomly with the created tags
- switch article sort to manually (the arrows on the left)
- sort articles through drag and drop functionality

### Expected result
- articles should be sorted and the tags should not be deleted in the article

### Actual result
- articles are sorted but loose most of their tags (not all)

### System information (as much as possible)
Joomla 3.8.x

### Additional comments
Maybe similar to #18086, where batch function delets also the tags

**Comment by ghost** [comment] 2017-10-12 13:03
Similar https://github.com/joomla-extensions/weblinks/issues/368

**Comment by dieseitenwerkstatt** [comment] 2017-10-12 14:18
Thanks, i searched for something like this but didn't find. Do i have to close this or how will this be handled?

**Comment by ghost** [comment] 2017-10-12 15:02
@Puckmeister They are now referenced to each other so Dev. can easier look into it.

**Comment by brianteeman** [comment] 2017-10-12 16:50
Confirmed the issue
As soon as you reorder the article the record in the #__contentitem_tag_map table is deleted

@franz-wohlkoenig please set the issue level to urgent

**Comment by ghost** [comment] 2017-10-12 18:00
Level at Issue Tracker is now "Urgent".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18317">issues.joomla.org/tracker/joomla-cms/18317</a>.</sub>

**Comment by alikon** [comment] 2017-10-12 18:47
i suspect some issue from namespace & Observers 
cause i've just  dirty fixed again this issue #18320  with #17730
so ping @laoneo

**Comment by tonypartridge** [comment] 2017-10-12 20:54
I did also have a quick look at a fix but couldn’t see anything obvious

**Comment by ggppdk** [comment] 2017-10-12 22:35
Tags are deleted with any batch action too

**Comment by infograf768** [comment] 2017-10-13 07:28
> Tags are deleted with any batch action too

https://github.com/joomla/joomla-cms/issues/18086

**Comment by ggppdk** [comment] 2017-10-13 08:51
@infograf768  right there is issue #18086 
That issue is about batch changing category, 
but testing reveals that any batch actions also deletes the tags not only changing category

This seems to be related to namespacing, as the new classname
Joomla\CMS\Table\Content
instead of
Content

which prevents correct UCMtype calculation, 
i think i can make a PR

**Comment by ghost** [comment] 2017-10-13 13:59
closed as having Pull Request #18328

**Closed as completed** 2017-10-13 13:59 UTC
Labels: No Code Attached Yet
