### ISSUE TITLE
com_fields custom editor field page break not working

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#14990] opened 2017-03-29 15:34 UTC
### Steps to reproduce the issue

install joomla-cms/staging @ 4ba67b7de454befe851da3d120773d0bbd4855ea
(Tested WITH and WITHOUT PR #14520 applies - makes no difference)

Add a single Editor custom field with name "editor" and otherwise default configuration

Create a new article, go to the editor on the fields tab, 

Click Page Break

Click Insert Page Break

### Expected result

That a page break is inserted into the customfields editor on the Fields tab.

### Actual result

a whole webpage loads inside the modal, the modal stays open

![screen shot 2017-03-29 at 16 32 32](https://cloud.githubusercontent.com/assets/400092/24462983/5585248e-149d-11e7-9788-d85474028b36.png)

### System information (as much as possible)

https://gist.github.com/PhilETaylor/8db083650eb2e64aa59d02452103036c

### Additional comments

MAY be related to 
#14520 
#14935

**Comment by AlexRed** [comment] 2017-03-29 15:45
I can confirm the problem<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14990">issues.joomla.org/tracker/joomla-cms/14990</a>.</sub>

**Comment by Bakual** [comment] 2017-03-29 15:54
#14520 does fix that one for me as well and it also only happens with TinyMCE (Codemirror is fine).
Make sure to have "Show Buttons" enabled in the editor fields plugin as that seems to be an issue with TinyMCE as well.

**Comment by PhilETaylor** [comment] 2017-03-29 15:56
Why should I (a dump user) have to enable "Show buttons" to get a feature to work as expected? 

This is a "out of the box" installation of Joomla. The features should work without me going and fudging my settings.

**Comment by PhilETaylor** [comment] 2017-03-29 16:11
> #14520 does fix that one for me as well and it also only happens with TinyMCE (Codemirror is fine). Make sure to have "Show Buttons" enabled in the editor fields plugin as that seems to be an issue with TinyMCE as well.

Simply stating that something works for you, under a totally different set of circumstances, doesnt mean that the reported issue is fixed or invalid... it means you did not test what was reported as an issue! 

So, testing with 4ba67b7de454befe851da3d120773d0bbd4855ea, with #14520 applied, an editor called editor, a clean cache, **I CAN STILL REPLICATE THE REPORTED ISSUE!**

**Comment by PhilETaylor** [comment] 2017-03-29 16:15
I can confirm that with CodeMirror enabled (instead of TinyMCE) this issue doesn't happen.

**Comment by Bakual** [comment] 2017-03-29 17:07
> Why should I (a dump user) have to enable "Show buttons" to get a feature to work as expected?

I haven't said you should have to, I asked you to try if that helps so we can narrow down the issue.
I agree with you that the default value for this parameter should be "Yes", as I would expect the buttons to be enabled by default. But that's a completely different issue (and an easy one to sovle actually)

> Simply stating that something works for you, under a totally different set of circumstances, doesnt mean that the reported issue is fixed or invalid... it means you did not test what was reported as an issue!

I can't follow you. I have tested exactly the same (actually also additional scenarios) and was able to reproduce the exact issue you mentioned and the PR fixed it for me. I'm now trying to find out why it didn't fix it for you as I can't reproduce the issue anymore after applying said PR.
While doing so I found an additional issues like the "Show Buttons" parameter not behaving correctly which I thought may be related to the difference between your setting and mine.

**Comment by PhilETaylor** [comment] 2017-03-30 12:54
ok I have manually applied every change in #14520 to f45c0da5ba84ef7538e13879a1b096ed9e05c24d and I can still replicate the reported issue

Im 100% convinced #14520 doesnt resolve this reported issue

**Comment by Bakual** [comment] 2017-03-30 18:28
Closing as we have a PR #14520

**Closed by Bakual** 2017-03-30 18:28 UTC
Labels: No Code Attached Yet

**Comment by PhilETaylor** [comment] 2017-03-30 20:07
This is fixed by #14520 @ 96603d295c396c173cb22825576af8d6ca4bdf0c - confirmed
