### ISSUE TITLE
Browser title no longer working after last Joomla update.

### ISSUE THREAD

**Issue by MaghSamana** [joomla/joomla-cms#28950] opened 2020-05-05 19:55 UTC
Hello,
I have some menu items that are configured to have a Page title and also a Browser title. After last Joomla update, I noticed the Browser title was ignored and the Page title was instead used as Browser title.

Did anyone else have this problem? Is that a bug?

### System information (as much as possible)
Joomla! 3.9.18 with PHP 7.3.17

**Comment by ReLater** [comment] 2020-05-06 11:43
I cannot confirm your find with Joomla 3.9.19-dev (current staging).

**Comment by MaghSamana** [comment] 2020-05-06 21:16
That's the configuration I've had. Used to work normally. Suddenly, the Browser page title got replaced by the Page Heading. Nothing else had changed, except Joomla's recent update.


![Untitled-1 copy](https://user-images.githubusercontent.com/46110970/81229019-d1562800-8ff7-11ea-8367-cfad16a68eac.png)

**Comment by ReLater** [comment] 2020-05-06 22:15
Yes, I understand but cannot reproduce it. I've also tested with my own site (3.9.18) where I have nearly in any menu item different `Browser Page Title` and `Page Heading` entries.

I tested with menu item types:
Articles » Featured Articles
Articles » Single Article
Articles » List All Categories
Articles » Category Blog

Firefox, Chrome

**Comment by gerryfrancis** [comment] 2020-05-07 09:02
@MaghSamana I wonder if your case has something to do with some special characters. Maybe the page heading is a fallback when the browser page title cannot be read/processed correctly.

**Comment by MaghSamana** [comment] 2020-05-07 12:29
Found the issue: it was a cache problem from a disabled component (EFFSEO). I still don't know why with the Joomla update the cache of the disabled component was mixed in, but once cleared the problem stopped.

Gerryfrancis: I've been using special characters a lot, so I can say for sure that Joomla system handles them fine.

**Comment by gerryfrancis** [comment] 2020-05-07 12:57
@MaghSamana Great that you have found the solution, and thanks for letting us know. Please close here, thank you.

**Comment by richard67** [comment] 2020-05-07 16:55
Closing as issue is solved in 3rd party component.

**Closed as completed by richard67** 2020-05-07 16:55 UTC
Labels: No Code Attached Yet
