### ISSUE TITLE
RSS uses creation date in stead of start date

### ISSUE THREAD

**Issue by stimpsonjcat** [joomla/joomla-cms#41033] opened 2023-06-23 13:56 UTC
### Steps to reproduce the issue
Create an article. Set the start date to now, set the created date to something in the past. Save the article.

### Expected result

The start date should be in the pubDate field of the rss feed.

### Actual result

The created date is in the rss

### System information (as much as possible)

Joomla 4.3.2

### Additional comments
The startdate is the actual date on which an article is published / visible on the site. Feed readers look at the pubDate to determine the published date. If you plan an article days or weeks in advance and create and publish other articles after this article, the feed reader won't pick up the initial article, since it thinks it's older than the other articles, even though the sort order in the feed is correct (by published up date).

**Comment by Quy** [comment] 2023-06-24 16:23
Duplicate #35954?

**Comment by stimpsonjcat** [comment] 2023-06-24 19:44
I see this was first reported in 2018… https://github.com/joomla/joomla-cms/pull/21684
 it was noted as a bug several times, pushed to Joomla 4, but still hasn't been fixed. Is it so difficult?

**Comment by webmasterpaca** [comment] 2023-11-02 10:04
Hi,
I have a same problem<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41033">issues.joomla.org/tracker/joomla-cms/41033</a>.</sub>

**Comment by Hackwar** [comment] 2024-11-26 17:39
This is indeed a duplicate of #35954. Because of that I'm closing this ticket. You are welcome to create a PR to fix this.

**Closed as completed by Hackwar** 2024-11-26 17:39 UTC
Labels: No Code Attached Yet, Information Required, bug
