### ISSUE TITLE
There should be consistency in spelling for color plugin type

### ISSUE THREAD

**Issue by jaisheela** [joomla/joomla-cms#26946] opened 2019-11-02 12:16 UTC
### Steps to reproduce the issue
1) Goto systems menu
2) click on Plugins
3) Click on filter options
4) Select plugin type as fields
5) Choose Fields - Colour

Now check the spelling , somewhere it is written color and someplace colour

### Expected result

Spelling should be consistent

### Actual result

Not consistent

**Comment by astridx** [comment] 2019-11-02 18:32
I can confirm this when I filtered for `elements`

![Plugins   test   Administration](https://user-images.githubusercontent.com/9974686/68075385-622d1c00-fda7-11e9-8ca8-7dd58fea878e.png)

**Comment by infograf768** [comment] 2019-11-03 07:51
The default fields plugin is named `Fields - Colour` in **English en-GB**. It would be named `Fields - Color` in American **English en-US**
The elements are NOT translatable and use the file name which is coming from the code value.
Closing as not a bug.

**Closed as completed by infograf768** 2019-11-03 07:51 UTC
Labels: No Code Attached Yet
