### ISSUE TITLE
Menu title is limit to 49 characters lenght

### ISSUE THREAD

**Issue by mariantanase** [joomla/joomla-cms#44354] opened 2024-10-25 07:31 UTC
### Steps to reproduce the issue
Hi,
I want to create a new menu in joomla, but when I save it, the title cuts me off after **49 characters**.
My title that should be :
`Sezione Principale Generale del Gruppo Territoriale di competenza di zona B`
but it only keeps 
`Sezione Principale Generale del Gruppo Territori`

How to avoid menu title limit ?
Thanks

### System information (as much as possible)
Joomla 5.2.0

**Comment by fgsw** [comment] 2024-10-25 07:43
Can't confirm:

![Image](https://github.com/user-attachments/assets/4c2cf410-3c34-4b54-92cc-a7b1988ea702)
![Image](https://github.com/user-attachments/assets/0a56bea6-56f4-4797-b898-eb14b2772c20)

**Comment by mariantanase** [comment] 2024-10-25 07:43
I've notice on the tabel **_menu_types** , the **title** is `varchar(48)` type.

**Comment by mariantanase** [comment] 2024-10-25 07:44
No menu item, I mean menu title

**Comment by fgsw** [comment] 2024-10-25 07:45
> No menu item, I mean menu title

Sorry, my fault.

**Comment by chmst** [comment] 2024-10-25 07:45
confirmed for menuType.

**Comment by mariantanase** [comment] 2024-10-25 07:47
can be changed from `varchar(48)` to `varchar(255)` manually on db, without broken something ?

**Comment by chmst** [comment] 2024-10-25 07:49
@mariantanase it is true that the menutype title is cut - due to database structure. (no idea why we have this restriction)
![Image](https://github.com/user-attachments/assets/192a1172-5555-4377-93f4-7de274aa3910)

For publishing your menu, the titel of the module ist displayedm nit the menutype. So it should be possible to shorten your menuType name?

**Comment by mariantanase** [comment] 2024-10-25 07:53
> [@mariantanase](https://github.com/mariantanase) it is true that the menutype title is cut - due to database structure. (no idea why we have this restriction) ![Image](https://github.com/user-attachments/assets/192a1172-5555-4377-93f4-7de274aa3910)
> 
> For publishing your menu, the title of the module ist displayed, not the menutype. So it should be possible to shorten your menuType name?

Unfortunately, I have many menus with the title longer than 48 characters. 48 limit is too short for me...

**Comment by richard67** [comment] 2024-10-25 10:57
The title of the menu types is only shown in backend when selecting or filtering menus by menu type. It has no meaning in the frontend. Therefore I would just suggest to use shorter titles e.g. by using abbreviations for words which are common for many menu types.

If we now increase it so it fits your needs, the next user will even want longer titles, and at the end we will end with mediumtext.

That would not really make sense.

So my opinion is to leave it as it is, but that’s only my personal opinion, others may be different.

**Comment by mariantanase** [comment] 2024-10-25 12:09
> The title of the menu types is only shown in backend when selecting or filtering menus by menu type. 

I'll notice that.
> It has no meaning in the frontend. Therefore I would just suggest to use shorter titles e.g. by using abbreviations for words which are common for many menu types.

Thanks!

**Comment by fgsw** [comment] 2024-10-27 05:08
Can be closed as @mariantanase give also a ThumbsUp at "So my opinion is to leave it as it is, but that’s only my personal opinion, others may be different." https://github.com/joomla/joomla-cms/issues/44354#issuecomment-2437489399

**Closed as completed** 2024-10-27 15:44 UTC
Labels: Feature, No Code Attached Yet
