### ISSUE TITLE
Module search in admin panel in cyrilic language (tested on Ukrainian)

### ISSUE THREAD

**Issue by boomsya** [joomla/joomla-cms#18745] opened 2017-11-20 11:36 UTC
### Steps to reproduce the issue
1. goto /administrator/index.php?option=com_modules
2. in module name filter type "Увійти"
3. click Enter button

### Expected result
1. Must be finded 1 module "Увійти до системи"

### Actual result
1. no modules finded

### System information (as much as possible)
web server xampp-win32-7.0.13
joomla 3.8.1

### Additional comments
![joomla](https://user-images.githubusercontent.com/8008462/33016578-bf2d4de4-cdf7-11e7-9d09-d5b0c7fa9603.jpg)

**Comment by infograf768** [comment] 2017-11-20 16:17
I can't reproduce
<img width="883" alt="screen shot 2017-11-20 at 17 16 11" src="https://user-images.githubusercontent.com/869724/33028568-93be82f8-ce16-11e7-8870-871df1d54908.png">

**Comment by boomsya** [comment] 2017-11-20 18:37
very strange. In Joomla 3.6.5 no problems (on hosting web server)
i will try to debug filering procedure

**Comment by ghost** [comment] 2017-12-26 08:37
If this Issue get no Response, it will be closed at 26th January 2018.

**Comment by boomsya** [comment] 2018-01-17 09:33
are your serious?
here second example with problem on next site on paid web hosting with joomla 3.8.3
![12](https://user-images.githubusercontent.com/8008462/35035537-5df0ca50-fb7a-11e7-84f9-cb88747d2b8f.png)

**Comment by ghost** [comment] 2018-01-26 08:17
This has been closed as stated above – it can always be reopened.

**Closed as completed** 2018-01-26 08:17 UTC
Labels: No Code Attached Yet
