### ISSUE TITLE
bug JTableMenu: :_getNode  adding components [FIX]

### ISSUE THREAD

**Issue by spiritdead** [joomla/joomla-cms#7199] opened 2015-06-19 05:04 UTC
Advertencia
exception 'UnexpectedValueException' with message 'JTableMenu: :_getNode(1, ) failed in /path/libraries/joomla/table/nested.php:1522
...

solution
adding this in the installation or upgrade,etc
```sql
INSERT INTO `prefix_menu` (`id`, `menutype`, `title`, `alias`, `note`, `path`, `link`, `type`, `published`, `parent_id`, `level`, `component_id`, `checked_out`, `checked_out_time`, `browserNav`, `access`, `img`, `template_style_id`, `params`, `lft`, `rgt`, `home`, `language`, `client_id`) VALUES
(1, '', 'Menu_Item_Root', 'root', '', '', '', '', 1, 0, 0, 0, 0, '0000-00-00 00:00:00', 0, 0, '', 0, '', 0, 137, 0, '*', 0)
```

plz can solve this ?

**Comment by zero-24** [comment] 2015-06-19 07:49
@spiritdead I'm not sure how to reproduce? Can you give us a detailed instructions how to test / reproduce the issue?

**Comment by PhilETaylor** [comment] 2015-07-01 14:12
All installations of Joomla already have a Menu_Item_Root entry in the #__menu table - so this "fix" is "fixing" something that is not a Joomla bug but a bug caused by database inconsistency, possibly with a 3rd party migration tool or something else that fudges the menu table.

Googling leads me to articles about Joomla 1.5 to 1.6 migrations going wrong and this was then the fix - see: http://forum.joomla.org/viewtopic.php?t=632543

I recommend closing this issue as its a non-issue for Joomla core.

**Closed** 2015-07-06 07:23 UTC
Labels: No Code Attached Yet, Test instructions missing
