### ISSUE TITLE
#__assets table, column title has wrong length for it (50 is the current limit  and "100" in the "title" column)

### ISSUE THREAD

**Issue by uzielweb** [joomla/joomla-cms#42283] opened 2023-11-04 05:00 UTC
### Steps to reproduce the issue
If you use any tool, like a cli, a custom component or whatever, #__assets table in the "name" column has wrong length for it (50 is the current limit  and "100" in the "title" column),  The ideal length is 255, I suggest because this is the default Joomla Article 

### Expected result

No messages, only insertions in database assets

### Actual result

message VARCHAR is too long

### System information (as much as possible)

PHP 8.2, MariaDB 10 / Mysql 8, Apache, Joomla 5.0.0

**Comment by richard67** [comment] 2024-01-24 21:04
I will create a pull request on weekend.

**Comment by uzielweb** [comment] 2024-04-25 20:04
Any update from this?

**Comment by richard67** [comment] 2024-04-25 20:13
Well, I was working on it but then had other things to do. I also don't think I will make a pull request soon.

**Comment by uzielweb** [comment] 2024-06-06 12:42
I checked the installation files for Joomla 5.1.1 and still as same :( 
I think this now can be possible because Joomla 5 uses Mysql8
name and title columns needs more characters to correspond to Joomla Content tables as well.
`--
-- Table structure for table `#__assets`
--

CREATE TABLE IF NOT EXISTS `#__assets` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Primary Key',
  `parent_id` int NOT NULL DEFAULT 0 COMMENT 'Nested set parent.',
  `lft` int NOT NULL DEFAULT 0 COMMENT 'Nested set lft.',
  `rgt` int NOT NULL DEFAULT 0 COMMENT 'Nested set rgt.',
  `level` int unsigned NOT NULL COMMENT 'The cached level in the nested tree.',
  `name` varchar(50) NOT NULL COMMENT 'The unique name for the asset.\n',
  `title` varchar(100) NOT NULL COMMENT 'The descriptive title for the asset.',
  `rules` varchar(5120) NOT NULL COMMENT 'JSON encoded access control.',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_asset_name` (`name`),
  KEY `idx_lft_rgt` (`lft`,`rgt`),
  KEY `idx_parent_id` (`parent_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;
`

**Comment by Hackwar** [comment] 2024-11-19 18:22
This is a duplicate of #42671. Since the other discussion had more interaction, I'm closing this one.

**Closed as completed by Hackwar** 2024-11-19 18:22 UTC
Labels: No Code Attached Yet, bug
