### ISSUE TITLE
3.7: Fatal error due to #11225

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#12095] opened 2016-09-20 07:03 UTC
### Steps to reproduce the issue

Load the articles manager
Fatal error: Can't use method return value in write context in ROOT/administrator/components/com_content/models/articles.php on line 329

**Comment by infograf768** [comment] 2016-09-20 07:13
Looks like it would be solved by using ! instead of empty? I.e.
```
if (JPluginHelper::isEnabled('content', 'vote'))
		{
			$orderCol  = !($this->state->get('list.fullordering', 'a.id')) ? 'a.id' : $this->state->get('list.fullordering', 'a.id');
			$orderDirn = '';
		}
```

**Comment by alikon** [comment] 2016-09-20 11:06
#11225 has been tested on 3.6.x branch not on 3.7 branch I'll look at it
with the 3.7...

**Comment by sovainfo** [comment] 2016-09-20 16:21
Seriously?

> $orderCol  = !($this->state->get('list.fullordering', 'a.id')) ? 'a.id' : $this->state->get('list.fullordering', 'a.id');

for 
`
$orderCol  = $this->state->get('list.fullordering', 'a.id');
`

**Comment by infograf768** [comment] 2016-09-20 16:27
What we have now and causes the Fatal error is:

```
		if (JPluginHelper::isEnabled('content', 'vote'))
		{
			$orderCol  = empty($this->state->get('list.fullordering', 'a.id')) ? 'a.id' : $this->state->get('list.fullordering', 'a.id');
			$orderDirn = '';
		}
```

**Comment by sovainfo** [comment] 2016-09-20 16:29
Indeed, should never have been accepted!

**Comment by ggppdk** [comment] 2016-09-20 16:31
How many people test with PHP 5.3 and 5.4 ?
empty() in these versions, works on variable only

**Comment by infograf768** [comment] 2016-09-20 16:33
My test was on php 5.4.4

**Comment by mbabker** [comment] 2016-09-20 16:39
All you need is the line @sovainfo pointed out, `$orderCol = $this->state->get('list.fullordering', 'a.id');`.  If you have to check if the state's value is empty after you've pulled from the object then you've royally screwed something up along the way.  If it can't be empty don't allow an empty value to be saved to the state!

**Comment by ggppdk** [comment] 2016-09-20 16:57
@infograf768 
> My test was on php 5.4.4

yes i understood that because you got the error,
but i meant not your test , i meant the 2 human "acceptance" tests on every PR

**Comment by alikon** [comment] 2016-09-20 17:02
@infograf768 i'm unable to reproduce on `PHP Version	5.5.30` 

just want to remember  that still **minimum Requirements for Joomla! 3.x is 	5.3.10**

and yes should be `$orderCol = $this->state->get('list.fullordering', 'a.id');` my mistake 
i'll fix it

**Comment by sovainfo** [comment] 2016-09-20 17:16
People are known to make mistakes, procedures are in place to avoid mistakes getting into the product.  That doesn't mean every mistake is caught! Luckily, this one was.

Of the almost 500 $this->state->get statements in the product a few also use escape() around it. Don't know whether it needs it.

**Comment by zero-24** [comment] 2016-09-20 17:19
Closing as there is a PR. Thanks!

**Closed by zero-24** 2016-09-20 17:19 UTC
Labels: No Code Attached Yet
