### ISSUE TITLE
[del 31086]

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#31086] opened 2020-10-14 08:27 UTC
[del]

**Comment by infograf768** [comment] 2020-10-14 08:35
Can't reproduce here
<img width="1094" alt="Screen Shot 2020-10-14 at 10 31 39" src="https://user-images.githubusercontent.com/869724/95963915-8cd18280-0e08-11eb-8da6-fdb45ee85d95.png">

**Comment by gostn** [comment] 2020-10-14 08:36
thanks for info, closing as no issue.

**Closed as completed by gostn** 2020-10-14 08:36 UTC
Labels: No Code Attached Yet

**Comment by gostn** [comment] 2020-10-14 08:42
Additional Info: New Menu show all global setting. The menu with missing showing setting was by ´Blog sample data´.

**Comment by SharkyKZ** [comment] 2020-10-14 08:54
I can reproduce the issue. It happens when configuration hasn't been saved yet. Related issue https://github.com/joomla/joomla-cms/issues/30782.

**Comment by infograf768** [comment] 2020-10-14 08:55
> Additional Info: New Menu show all global setting. The menu with missing showing setting was by ´Blog sample data´.

Made clean install.
Confirmed. Same issue for Blog Layout tab concerning `Featured Articles`
Please create a new issue.

**Comment by infograf768** [comment] 2020-10-14 08:56
or is  #30782 enough?
