### ISSUE TITLE
[BUG][J4][4.1.5] Smart Search randomly changes format of URL

### ISSUE THREAD

**Issue by PhocaCz** [joomla/joomla-cms#38251] opened 2022-07-10 21:00 UTC
### Steps to reproduce the issue
- Enable Smart Search module and display a link to Smart Search component (Advanced Search parameter)
- Create a menu link to Smart Search component
- Click on this link in module or search something. This link randomly changes from its SEF format (menu link to component) to NO SEF format
See GIF:

![smart search](https://i.imgur.com/RjVgiOj.gif)

### Expected result
- immutable link

### Actual result
- changing link

### System information (as much as possible)
Joomla 4.1.5
PHP 8.1.6
SEF enabled

**Comment by Fedik** [comment] 2022-07-10 21:07
Does it worked in prev version?
There was a fix for something similar #36750, merged to 4.1.5

**Comment by PhocaCz** [comment] 2022-07-10 21:20
Unfortunately, I don't know, I installed fresh Joomla 4.1.5 and never tested smart search before that.

**Comment by PhocaCz** [comment] 2022-07-10 21:53
It looks like this is some Router problem as the URL is always the same:

index.php?option=com_finder&view=search&f=1&Itemid=101

When the module is displayed on search view (component smart search), then the SEF URL is wrong, when it is displayed outside search view, then everything is OK.

**Comment by Fedik** [comment] 2022-07-11 16:08
I cannot reproduce. 
Do you have set "Set ItemID" in the module that not linked to Search page, maybe?

**Comment by PhocaCz** [comment] 2022-07-11 22:16
This is my settings:

![image](https://i.imgur.com/G5dlw1T.png)

I just solved it when hiding the module for the search view: https://www.phoca.cz/apis/ (I will try to recreate the pate from scratch, maybe it can help :idea: )

**Comment by Hackwar** [comment] 2023-02-27 20:51
I can't replicate this. Do you maybe have an old override in your template? This was an issue with wrong markup in the layout.

**Comment by Hackwar** [comment] 2023-03-09 11:32
Closing as there has been no response in 10 days and I'm rather sure that this has been fixed in core in the past.

**Closed as completed by Hackwar** 2023-03-09 11:32 UTC
Labels: No Code Attached Yet, Information Required, bug
