### ISSUE TITLE
guest links not viewed in admin by administrator

### ISSUE THREAD

**Issue by web54** [joomla/joomla-cms#29606] opened 2020-06-14 08:04 UTC
### Steps to reproduce the issue
create a user in only administrator group
create a menu item with guest access in a frontend menu
login as the administrator

### Expected result

menu itemshould be seen

### Actual result

menu item is not seen

### System information (as much as possible)

j3.9.19

### Additional comments

issue reproduced several times in several sites.
found after been authorised with only administrator access to help a joomla webdesigner.

**Comment by SharkyKZ** [comment] 2020-06-14 08:25
Your expectation is wrong. See ACL tutorial https://docs.joomla.org/J3.x:Access_Control_List_Tutorial.

**Comment by SharkyKZ** [comment] 2020-06-14 08:26
Closing as expected behavior.

**Comment by web54** [comment] 2020-06-14 12:31
should be reopen :
you have not understand that it should be seen in ADMIN VIEW ( to be edited for example)

**Comment by SharkyKZ** [comment] 2020-06-14 12:36
OK, issue confirmed. Reopening.

**Comment by ggppdk** [comment] 2020-06-14 13:19
There had been a few discussions / issues opened about this before.

One of these discussions had been opened by me.
please read it here:

**[4.0] [RFC] Viewing access levels inconsistently mixed with create / edit ACL** 
https://github.com/joomla/joomla-cms/issues/17913

This 'issue' that you describe here,
applies not only to menu management
but in all (almost all ?) backend views

Users **that can edit a record are not able to list it in backend views** if they do not have the access level of the record

**It was decided that only for super-admins** all records regardless of access level will be visible
and that nothing more will be done for other usergroups about this.

The source of the problem is that originally the access levels were meant for frontend views
but then sometime at J1.6? or J1.7 ? (i do not remember) it started to be used in backend views, and then eventually all (?) backend views were using this.

My suggestion for **simple implementation and for being performance-wise**
was to add an '**access_manage**' property to the records and use this instead of using 'access' for listing records in "management views"

Another open issue for this is
https://github.com/joomla/joomla-cms/issues/23182

I really do not have something more to add.

**Comment by joomdonation** [comment] 2022-11-16 09:06
I just checked it on latest Joomla 4 installation, **Administrator** user group has **Configure ACL & Options** permission set to Allowed for com_menus, so administrators will be allowed to view all menu items, including the one with Guest access level

Therefore, I would say this issue is invalid now and close this issue. If you can still see the issue with Joomla 4, please feel free to re-open the issue. Thanks !

**Closed as completed by joomdonation** 2022-11-16 09:06 UTC
Labels: No Code Attached Yet
