### ISSUE TITLE
[4.4 rc]  batch modal bug

### ISSUE THREAD

**Issue by JoomlaBelarus** [joomla/joomla-cms#42049] opened 2023-10-05 07:31 UTC
### Steps to reproduce the issue

I have  many articles. In administrator side, articles i have 50art per page, and when i want to add some tag in the bottom of list - i chech it, and push button Actions-> Bath. But i dont see modal window. For that - i check needed articles, go to top of page, and push button Bath.    
![image](https://github.com/joomla/joomla-cms/assets/111335878/c5d33a11-136b-4c06-a320-d88f54b05a02)
![image](https://github.com/joomla/joomla-cms/assets/111335878/04e2dfd8-bb1a-41bb-8b58-9979ea28dc5e)

**Comment by Quy** [comment] 2023-10-05 14:40
I am unable to reproduce. Are there errors in the browser console?

**Comment by Quy** [comment] 2023-10-18 22:24
Closing as non-reproducible.

**Closed as completed by Quy** 2023-10-18 22:24 UTC
Labels: No Code Attached Yet, Information Required

**Comment by Jan-dax** [comment] 2023-10-19 09:11
Yesterday i updated site  to 4.4 stable.And now ok with modal window in Action-batch
