### ISSUE TITLE
Cannot configure meta robots for com_tags

### ISSUE THREAD

**Issue by Ptacku** [joomla/joomla-cms#6720] opened 2015-04-09 11:38 UTC
#### Steps to reproduce the issue
While it is possible to configure meta robots for the page generated for a specific tag, there currently is no way set a default value for meta robots for content generated by com_tags other than the site-global defaults.

For SEO purposes this would be badly needed, as content generated by com_tags usually should be marked "noindex, follow" to avoid duplicate content.

#### Expected result
Request for enhancement: Provide a configuration option to set meta robots for com_tags generated content.

#### System information (as much as possible)
Tested with Joomla 3.3.6

**Comment by zero-24** [comment] 2015-04-09 11:41
@spacemonkey 

>Tested with Joomla 3.3.6

Please try 3.4.1 we have fix a lot of bugs since 3.3.6. 

http://www.joomla.org/announcements/release-news/5587-joomla-3-4-1-released.html

**Comment by Ptacku** [comment] 2015-04-09 11:55
I just did, but I cannot find such a config option on 3.4.1 either.

There are the site-global settings and the settings for a specific tag. But there is no way to configure meta robots for all com_tags generated content.

**Comment by zero-24** [comment] 2015-04-09 12:09
Ok sorry i have missunderstand you :smile: 

>There are the site-global settings and the settings for a specific tag. But there is no way to configure meta robots for all com_tags generated content.

Hmm i just check we dont hat similiar for com_content have we? I have not see it.

**Comment by Ptacku** [comment] 2015-04-09 12:21
Since com_content is more or less the "main thing" of the whole system, I'd consider the site-global defaults sufficient in this case. Also it can be configured for content attached to a menu item on the menu item level.

But feel free to add such a config option on com_content level as well ;-)

**Comment by zero-24** [comment] 2015-04-09 12:31
Thanks now i understand. :smile: Moving to Confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6720">issues.joomla.org/joomla-cms/6720</a>.</sub>

**Comment by bertmert** [comment] 2015-04-12 13:13
At the moment I recommend to use 
```
JFactory::getDocument()->setMetadata('robots', 'noindex, nofollow');
```
in template overrides if you want to make sure that robots meta tag is set like you want.

Why? Try this:

- Install current staging Joomla.
- Go to menu manager and set menu filter to "All Front End Views" 
- Search for word "tag" and unpublish 3 com_tags menu items.
- Goto Components > Tags and open tag "Yellow"
- Set field "Robots" to "noindex,follow" and save.
- Front end: Open "Popular Tags" of menu "All Modules".
- Click tag "Yellow".
- Open HTML source code of page.

Expected:
```
<meta name="robots" content="noindex,follow" />
```

Actual:
No robots meta tag at all.

This is a bug, incomplete code in view.html.php..

if you use menu items, single tag views inherit robots from menu settings. No chance to override them via tag settings. **This is different from bahavior of com_content article.** There the setting in article itself always rules.

Because I found another issue concerning author meta tags in com_tags I started a PR to fix it and will also fix the robots thing described above.

Afterwards you can take over @Ptacku to find friends for your idea ;-)

**Comment by Ptacku** [comment] 2015-04-12 14:26
Currently I've implemented what I need by a simple onContentPrepare plugin, which merely checks if it is called in com_tags context and then calls JFactory::getDocument()->setMetadata() as described above.

This works fine for me and I can live with that. Still it would be nice if Joomla could do this out-of-the-box one day.

**Comment by bertmert** [comment] 2015-04-13 13:13
Even if issue described by me above still exists I've closed my PR https://github.com/joomla/joomla-cms/pull/6752 and efforts.
com_tags is somehow "strange" ;-)

**Comment by brianteeman** [comment] 2016-05-08 15:41
Thank you for your contribution but it has been decided that this is not something that will be changed in the core of Joomla.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6720">issues.joomla.org/joomla-cms/6720</a>.</sub>

**Closed** 2016-05-08 15:41 UTC
Labels: No Code Attached Yet
