### ISSUE TITLE
[4.2] Broken link to help page when updating Joomla

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#35668] opened 2021-09-25 10:22 UTC
### Steps to reproduce the issue
Go to `administrator/components/com_joomlaupdate`, make the `extract.php` file readable and hidden (tested on a local host in Windows).

Go to Control Panel - System - Joomla Update, select manual package installation, try installing nightly build.

It is logical that we will get an error.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/134767930-c127c292-ae71-4e62-bf19-eb9f9437a6b1.png)

![Screenshot_2](https://user-images.githubusercontent.com/8440661/134767956-5b8a1f82-fb70-4a78-a6e1-67e5f8e90e1e.png)

A link to help leads to a broken page.

**Comment by Kostelano** [comment] 2022-04-25 16:01
The link is now working correctly, the problem is closed.

**Comment by Kostelano** [comment] 2022-06-08 10:48
I will reopen the problem because it has re-discovered itself in testing the PR https://github.com/joomla/joomla-cms/pull/38002.

**Comment by nikosdion** [comment] 2022-06-08 10:57
I can confirm this issue. It's because Joomla still has not copied over the documentation I contributed in https://github.com/joomla/joomla-cms/pull/35388 to the Joomla documentation wiki.

**Comment by nikosdion** [comment] 2022-06-08 11:11
Technically, there are two separate problems.

One is that since this is still a beta the `https://help.joomla.org/proxy?keyref=Help42:JHELP_COMPONENTS_JOOMLA_UPDATE&lang=en` (note the `Help42` key reference) leads nowhere. I feel that when Joomla releases a _beta_ the help screens should work.

The other problem is that the existing page, `https://help.joomla.org/proxy?keyref=Help41:JHELP_COMPONENTS_JOOMLA_UPDATE&lang=en`, does not contain the troubleshooting information.

I can help with the latter, if I find what I need to edit in the Wiki. I cannot help with the former, though. That's something the project infrastructure team needs to work on. Pinging @roland-d because as a release lead you should be aware.

**Comment by Kostelano** [comment] 2022-06-08 11:17
> One is that since this is still a beta the https://help.joomla.org/proxy?keyref=Help42:JHELP_COMPONENTS_JOOMLA_UPDATE&lang=en (note the Help42 key reference) leads nowhere. I feel that when Joomla releases a beta the help screens should work.

Damn, exactly. That's why I closed the issue once NOT getting a 404 page anymore. It was version 4.0 already released.

**Comment by nikosdion** [comment] 2022-06-08 11:30
I added the troubleshooting to the Joomla docs. Nobody told me not to after asking repeatedly, so I take it as a permission to do so myself 🤷🏽‍♂️

**Comment by brianteeman** [comment] 2022-06-08 11:33
#37682 
#36713

**Comment by nikosdion** [comment] 2022-06-08 11:35
So, it's not just us wondering... This is really a can being kicked further down the road every single time.

**Comment by brianteeman** [comment] 2022-06-08 11:37
and as you can see at least one of those was marked as a release blocker in january

**Comment by nikosdion** [comment] 2022-06-08 11:38
🤦🏽‍♂️

**Comment by roland-d** [comment] 2022-06-08 12:22
@nikosdion Thank you for the ping. Anybody can always add anything to the wiki, so thank you for updating the page.

I see the other issues has been pushed back several times, I will see what I can do about the links etc.

**Comment by wilsonge** [comment] 2022-06-30 18:00
I've put in the general alias from 4.2 to 4.x namespace into the wiki. That's actually one of the few things that has to be done in the php source with cpanel access btw ;)

**Closed as completed** 2023-02-01 12:22 UTC
Labels: No Code Attached Yet
