### ISSUE TITLE
After upgrading form 3.5.1 to 3.6 "Search"  and Login Modules don't work

### ISSUE THREAD

**Issue by ssvt** [joomla/joomla-cms#11122] opened 2016-07-14 14:11 UTC
#### Steps to reproduce the issue
I updated from Joomla 3.5.1 to 3.6 on Siteground servers with PHP 7.08

#### Expected result
Search should provide results. Login should login to user account.

#### Actual result
Search function did not work. Also, the system Login module didn't work. In both cases the page just site there. 

#### System information (as much as possible)
PHP Built On 	Linux m03.siteground.biz 3.12.18-clouder0 #73 SMP Wed May 18 13:32:34 EEST 2016 x86_64
Database Version 	5.6.28-76.1-log
Database Collation 	utf8_general_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	7.0.8
Web Server 	Apache
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 3.6.0 Stable [ Noether ] 12-July-2016 21:14 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 6.3; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0  

#### Additional comments
Reverting to PHP 5.6..23 corrected both problems (keeping Joomla 3.6) on the two sites I tested.

**Comment by brianteeman** [comment] 2016-07-14 14:25
I cannot confirm this. All my sites are in php 7 with SiteGround

**Comment by gsmela** [comment] 2016-07-14 14:41
I actually tested this on two very different sites. The one I first noticed has a number of extensions including AdminToolsPro. The other is a simple site on a different Siteground server with no extensions other than Akeeba backup and Admin Tools. I disabled all in both cases and the issue remains unless I revert to PHP 5.6.23. Not sure what else to try.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11122">issues.joomla.org/joomla-cms/11122</a>.</sub>

**Comment by brianteeman** [comment] 2016-07-14 15:40
Did you clear all the cache?
Did you check your site cache settings?
Did you contact siteground support to check for a server issue?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11122">issues.joomla.org/joomla-cms/11122</a>.</sub>

**Comment by gsmela** [comment] 2016-07-14 15:56
Yes Brian and thanks for responding.

I've cleared the cache within Joomla and through cPanel and I have 
disabled site cache. I've even tried using the Protostar template for 
testing and disabling the extensions & plugins.
On one site I am using RSForms Pro along with Akeeba Backup & Admin 
Tools Pro. On the other site it is very simple - no extensions and on a 
different Siteground server with the same result (so not likely a server 
issue). Siteground support says it thinks it is an extension issue. I do 
have a few sites that are working properly so I'm stumped.

**Comment by dextercowley** [comment] 2016-07-18 00:06
The Logout Redirection feature in the Login module appears to be broken in version 3.6. You can reproduce using the default sample data in a clean Joomla 3.6 install as follows:

1. Create a new article called Logout.
2. Create a new menu item for this article.
3. In the Login Form module, change the Logout Redirection Page to this new menu item.
4. Login to the front end and then log out.
Expected: You should be redirected to the Logout article menu item.
Actual: You are redirected to a page with no component (only modules).

This change is caused by a change to the file UsersControllerUser, line 165: 
if (is_numeric($return))
The variable $return is a string URL, so this statement is false and the redirect statement is not executed. I don't know why that code was changed, but it appears to be wrong.

**Comment by brianteeman** [comment] 2016-07-18 00:09
The logout redirection is a known bug which I believe has already been
resolved

**Comment by andrepereiradasilva** [comment] 2016-07-18 00:09
See https://github.com/joomla/joomla-cms/pull/11093

**Comment by DrZen33** [comment] 2016-07-18 03:26
Thank you dextercowley
I can confirm the exact same behaviour on my website.
Never had a problem like this before.
I upgraded from Joomla 3.5.1 to 3.6.0 and now when members log out of an Article or Forum page, they are greeted with a blank screen below menus.

**Comment by brianteeman** [comment] 2016-07-23 09:56
@gsmela I hope you have resolved the issue by now and it was an issue with an extension. I am closing this but it can always be reopened if needed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11122">issues.joomla.org/joomla-cms/11122</a>.</sub>

**Closed** 2016-07-23 09:56 UTC
Labels: No Code Attached Yet

**Comment by DrZen33** [comment] 2016-07-23 10:28
I am not a programmer, so have no knowledge on this side.
Why are you closing this thread when nothing has been done to fix the problem?

**Comment by brianteeman** [comment] 2016-07-23 11:26
Because the logout redirect issue has already been resolved on another issue and will be in the 3.6.1 release

**Comment by DrZen33** [comment] 2016-07-24 03:49
Thank you for that explanation. Now I understand :+1:
