### ISSUE TITLE
[4.0] fancy-select display issues

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#28196] opened 2020-03-03 09:12 UTC
### Steps to reproduce the issue
Display the articles manager.
Depending on the window size, we may or not get the full dropdown list

### Middle size

<img width="1212" alt="Screen Shot 2020-03-03 at 10 03 20" src="https://user-images.githubusercontent.com/869724/75759883-92290380-5d36-11ea-9451-8b69c32e5f5d.png">

### large size

<img width="1657" alt="Screen Shot 2020-03-03 at 10 03 54" src="https://user-images.githubusercontent.com/869724/75759898-98b77b00-5d36-11ea-8af2-54393144b0b4.png">

### Modal xtds
![Screen Shot 2020-03-03 at 10 11 47](https://user-images.githubusercontent.com/869724/75760360-71ad7900-5d37-11ea-9757-5db639de9506.png)

Also, the `Press to select` div reduces drastically the space available for the title of the items in the list, forcing it to go to next line. Example above for categories

**Comment by Quy** [comment] 2020-03-03 09:39
See #23451 for the width issue.

**Comment by Quy** [comment] 2020-03-18 16:50
I cannot reproduce the first issue.

**Comment by brianteeman** [comment] 2021-04-09 21:43
I am unable to replicate this in the current bs5 atum release

**Comment by Fedik** [comment] 2021-04-11 16:06
The drop-down position (opens UP or DOWN) depend from the element position on the viewport,
By default the dropdown will opens DOWN,
but if the element is close to the bottom edge of the viewport, it will opens UP.

However there possible glitches as on the screenshots when the viewport height is very small.
In 99% cases it can be fixed by scrolling up a bit, manualy :)

**Closed as completed** 2022-06-28 07:46 UTC
Labels: No Code Attached Yet
