### ISSUE TITLE
[4.0]Private message: Drop-down is not appearing clear in Filter options #bug

### ISSUE THREAD

**Issue by flavia-b** [joomla/joomla-cms#26924] opened 2019-11-02 09:39 UTC
### Steps to reproduce the issue
Login to Joomla admin with one user
Go to the private message section.
Click on Filter Options
Hover on dropdown or click on the dropdown

### Expected result
The dropdown should have a placeholder and a collapsible arrow.

### Actual result
It's not easy to understand whether the filter option is a text input or dropdown. Also, there is no placeholder to the filter to identify what the dropdown consists of. 

![screen shot 2019-11-02 at 09 37 47](https://issues.joomla.org/uploads/1/3b5361560184df88293497c646b22685.png)

**Comment by alikon** [comment] 2019-11-02 09:44
see  #26902, duplicate of #26897

**Closed as completed** 2019-11-02 09:45 UTC
Labels: No Code Attached Yet
