### ISSUE TITLE
Old archived articles are sort before in the Last Articles in single Contact page

### ISSUE THREAD

**Issue by AlexRed** [joomla/joomla-cms#15856] opened 2017-05-06 14:18 UTC
### Steps to reproduce the issue
Create the contact for the admin user,
Create some article by the admin, some archived and some not.
In Contacts: Options --> Show User Articles --> Show

### Expected result
In the admin contact page, under the mail form, all the article are sorted by data, the new articles first.

### Actual result
Old archived articles are sort first in the admin contact page, under the mail form.

### System information (as much as possible)
3.7.1dev

### Additional comments
![articles-archived](https://cloud.githubusercontent.com/assets/1362388/25773091/52039b7a-326f-11e7-8e9c-fe4808e3f2a5.png)

**Comment by franz-wohlkoenig** [comment] 2017-05-09 05:18
Issue confirmed. Default order for Contact looks like by ID, but archived first. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15856">issues.joomla.org/tracker/joomla-cms/15856</a>.</sub>

**Comment by brianteeman** [comment] 2017-05-11 09:26
Closed as we have a PR see #15962

**Closed by brianteeman** 2017-05-11 09:26 UTC
Labels: No Code Attached Yet
