### ISSUE TITLE
Joomla 3.5 : Bug with plugin languagefilter

### ISSUE THREAD

**Issue by rikoooo** [joomla/joomla-cms#9729] opened 2016-04-04 13:44 UTC
#### Steps to reproduce the issue
Hi there,

I have noticed a bug since Joomla 3.5.0, when the plugin languagefilter is enabled on a multi-language website it's impossible for the user to set the frontend language parameter (there is no value in the field), the field is empty. And because the site language is not an optional field the user cannot save his profil page.

How to reproduce the bug : 

I have two languages installed : English and French

Users Options :
1/ Frontend User Parameters : Set to Show
2/ Frontend Language : Set to Show
3/ Plugin languagefilter : Enabled

![Bug](http://www.rikoooo.com/snap069.jpg "Snapshot of the bug")

I have discovered this bug on my production website and I could reproduce it on a fresh new installed Joomla 3.5 without any component third parties.

Thank you,

Erik

**Comment by MATsxm** [comment] 2016-04-04 14:00
Not able to reproduce
![screen shot 2016-04-04 at 08 58 01](https://issues.joomla.org/uploads/1/8d0902f864220da21f605eef8e37309e.png)

could you be please more specific with your step by step process for your "How to reproduce"
Thanls<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9729">issues.joomla.org/joomla-cms/9729</a>.</sub>

**Comment by rikoooo** [comment] 2016-04-04 14:07
How to reproduce the bug :

I have two languages installed : English and French

Users Options :
1/ Frontend User Parameters : Show
2/ Frontend Language : Show

Plugin :
3/ Plugin languagefilter : Enabled<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9729">issues.joomla.org/joomla-cms/9729</a>.</sub>

**Comment by infograf768** [comment] 2016-04-04 14:10
This is a custom stuff as I can't reproduce either.
See your text under Confirm email:
![screen shot 2016-04-04 at 16 09 58](https://cloud.githubusercontent.com/assets/869724/14250661/ba2024c2-fa7f-11e5-952e-0c391452f972.png)

**Comment by rikoooo** [comment] 2016-04-04 14:16
Here is on my fresh installed Joomla 3.5.0, I can reproduce the bug<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9729">issues.joomla.org/joomla-cms/9729</a>.</sub>

**Comment by rikoooo** [comment] 2016-04-04 14:17
![Fresh Joomla 3.5.0](http://www.rikoooo.com/snap070.jpg "Fresh Joomla 3.5.0")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9729">issues.joomla.org/joomla-cms/9729</a>.</sub>

**Comment by andrepereiradasilva** [comment] 2016-04-04 14:19
@infograf768 @rikoooo @MATsxm

i came across this weeks ago.
Yes, it's a bug.

Just disable the homepage menu item for one of the languages and that language will disappear from the selector.

**Comment by MATsxm** [comment] 2016-04-04 14:22
Same parameters here and it works on 3.5.1 rc2
Content languages are both enabled?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9729">issues.joomla.org/joomla-cms/9729</a>.</sub>

**Comment by infograf768** [comment] 2016-04-04 14:23
@andrepereiradasilva 
Indeed, but ONLY the language which has no Home page, which is normal, not a bug, as that language will also not appear in the switcher.
Displaying the multilangstatus module in back-end will show what is wrong with THAT language.

**Comment by andrepereiradasilva** [comment] 2016-04-04 14:27
ok, i see. So, i can't have a user profile frontend interface language (joomla language variables) without having the version of the site in that language, right?

**Comment by rikoooo** [comment] 2016-04-04 14:33
Heuu.. I have the same problem when I want to edit a user from the back-end (Users: Edit Profile, Basic settings)

**Comment by MATsxm** [comment] 2016-04-04 14:36
@rikoooo 
could you please send usa screenshot of  your mod_ multi languages status
![3eaf9f88533e7455971c341eb4b3cf5f](https://cloud.githubusercontent.com/assets/1972717/14251420/ee642e10-fa50-11e5-8132-13048e22be7d.png)

**Comment by infograf768** [comment] 2016-04-04 14:43
@andrepereiradasilva 
The preferred site language on a multilingual site is used when login and automatic change is set to Yes in the languagefilter. 
It is used specially when the page on which one logs is associated to another page via the item displayed: it can be a menu, a category, an article. It is also used for the Home pages (these do not need to be associated, they are automatically)
See here the improvements I made which are waiting for tests: https://github.com/joomla/joomla-cms/pull/9724 which adds to these conditions that there are no redirects in the login module and login menu items. In that case it is no more the preffered site language of the user which counts.

Since 3.5.0, the list of languages to choose from is taken from the existing Published Content Languages, and not the installed languages.

On a monolanguage site, the use is just for the UI.

**Comment by andrepereiradasilva** [comment] 2016-04-04 14:57
ok i see. Will test https://github.com/joomla/joomla-cms/pull/9724 when i have more time.
Sorry for thinking this was a bug. Sometimes the languages complexity (so many variables at play) can be a bit overwhelming.

**Comment by infograf768** [comment] 2016-04-04 14:58
It is indeed complex. :)

**Comment by rikoooo** [comment] 2016-04-04 15:05
As of me, I still don't know what I have to do ? Here is my language statut
![snap071](https://cloud.githubusercontent.com/assets/18264052/14252341/2a813a42-fa87-11e5-8715-8d0d3f208956.jpg)

Like I said, before joomla 3.5 everything was ok,..

Thanks

**Comment by infograf768** [comment] 2016-04-04 15:12
It is obvious that the Home pages do not exist for both Content Languages.

A multilingual site needs a specific menu per Content Language with its Home set to the content language.

**Comment by infograf768** [comment] 2016-04-04 15:21
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9729">issues.joomla.org/joomla-cms/9729</a>

**Comment by infograf768** [comment] 2016-04-04 15:21
Closed as not a bug. Please get help on the forums.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9729">issues.joomla.org/joomla-cms/9729</a>.</sub>

**Closed by infograf768** 2016-04-04 15:21 UTC
Labels: No Code Attached Yet
