### ISSUE TITLE
Incorrect redirect after created Item in new custom menu.

### ISSUE THREAD

**Issue by Orsey** [joomla/joomla-cms#16046] opened 2017-05-16 10:04 UTC
### Steps to reproduce the issue
I created New menu.
I go to list items of new menu.
I created new item in this menu (type: external link).
I Clicked "Save & Close"

### Expected result
After saving I must recive list of items in my new custom menu. 

### Actual result
I see list of items in main menu (not my new custom menu). This main menu was created with install Joomla. The problem is that I was redirected to incorrect page (standart main menu). 

### System information (as much as possible)
PHP Built On:	Linux web478.default-host.net 3.10.0-427.36.1.lve1.4.47.el7.x86_64 #1 SMP Sun May 7 18:31:43 EDT 2017 x86_64
Database Version:	5.7.16-10-log
Database Collation:	utf8_general_ci
Database Connection Collation:	utf8mb4_general_ci
PHP Version:	7.1.3
Joomla! Version:	Joomla! 3.7.0 Stable [ Amani ] 25-April-2017 15:36 GMT
Joomla! Platform Version:	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

### Additional comments
After edit items in new menu, and click "Save & Close" proble was not agane.

**Comment by franz-wohlkoenig** [comment] 2017-05-16 10:52
closed as duplicate of #15447<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16046">issues.joomla.org/tracker/joomla-cms/16046</a>.</sub>

**Closed** 2017-05-16 10:53 UTC
Labels: No Code Attached Yet
