### ISSUE TITLE
Malformed menuitem allows article and category creation - Require category selction if Create Article in specific category in selected

### ISSUE THREAD

**Issue by LivioCavallo** [joomla/joomla-cms#17708] opened 2017-08-24 18:35 UTC
### Steps to reproduce the issue
In J!3.7.5 one can save a Create Article menu item, settting "Default Category" to Yes and NOT filling the "Choose a Category" field.

### Expected result
Joomla! refuses to save menu item.

### Actual result
Joomla! saves the menu item.
In frontend, using that menu with such a setting, forces to save the article in a newly created category with name '1' !

### System information (as much as possible)
J!3.7.5 (and probably all previous versions)

### Additional comments
Bug detected thanks by @infograf768  while testing PR #17674 .

We need a way to make 'catid' (Choose a Category) form field param required (\components\com_content\views\form\tmpl\edit.xml) when enable_category param (Default/Specific category) is active.
A new "requiredon:..." attribute, working like "showon:..." ?
A way to require validation of that attribute in the backend from ?

**Comment by ggppdk** [comment] 2017-08-25 04:07
Regardless of the parameter being required

proper behaviour would be that 
setting "Default category" to Yes and not selecting a category
- should behave like "Default category" is OFF,

i mean code (when possible) should anticipate bad configuration
and work in a proper way, regardless of user input

**Comment by LivioCavallo** [comment] 2017-08-25 07:06
I agree with your suggested behaviour (it's now merged in #17674).
Anyway I think that the "Selected category" should be 'required' if Default category is ON and the user should be blocked on saving or at least receive an alert saying that without selecting a category there won't be any constraints on the category, as if 'enable_category' is OFF.

**Comment by infograf768** [comment] 2017-08-25 07:56
> A new "requiredon:..." attribute, working like "showon:..." ?

I like this idea.

**Comment by infograf768** [comment] 2017-08-25 08:02
btw, the issue is in any J version, including staging.

**Comment by alikon** [comment] 2019-07-05 07:31
@infograf768  is this still an issue ?

**Comment by infograf768** [comment] 2019-07-05 07:36
yes

**Comment by infograf768** [comment] 2019-07-05 07:47
let me have a look at this a bit. I think that we could set the field as required when Default Category is set to Yes

**Comment by infograf768** [comment] 2019-07-05 09:15
hmm, not so simple...

**Comment by infograf768** [comment] 2019-08-09 07:48
Closing as we have a patch.
Please test https://github.com/joomla/joomla-cms/pull/25798

**Closed as completed by infograf768** 2019-08-09 07:48 UTC
Labels: No Code Attached Yet
