### ISSUE TITLE
Adding code to create databases breaks the installation script

### ISSUE THREAD

**Issue by Texpaok** [joomla/joomla-cms#19939] opened 2018-03-19 08:09 UTC
### Steps to reproduce the issue
Add the following code to the extension's xml file:

install
sql
file charset="utf8" driver="mysql"sql/install.sql/file
/sql
/install
uninstall
sql
file charset="utf8" driver="mysql">sql/uninstall.sql</file
/sql
/uninstall
updat>
	schemas
		<schemapath type="mysql">sql/updates</schemapath>
	/schemas
/update

### Expected result

Create the database as Joomla 3 does.

### Actual result

Databases are created but the file specified into <scriptfile></scriptfile> tags is not launched, so the extension is not installed.
If I remove that code the installation file is launched and everything is installed, but databases are not created.

### System information (as much as possible)

Setting 	Value
 
PHP Built On 	Linux joomla-test 3.13.0-95-generic #142-Ubuntu SMP Fri Aug 12 17:05:16 UTC 2016 i686
Database Version 	5.7.19-0ubuntu0.16.04.1
Database Collation 	utf8mb4_unicode_ci
Database Connection Collation 	utf8_general_ci
PHP Version 	7.0.22-0ubuntu0.16.04.1
Web Server 	Apache/2.4.18 (Ubuntu)
WebServer to PHP Interface 	apache2handler
Joomla! Version 	Joomla! 4.0.0 Alpha 2 Development [ Amani ] 19-November-2017 23:59 GMT
User Agent 	Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0

**Comment by SharkyKZ** [comment] 2018-03-19 08:47
Can't reproduce this on current 4.0-dev. I suggest you try with latest build as well.

**Comment by Texpaok** [comment] 2018-03-19 10:12
Hi SharkyKZ,

Thank you very much for your help. Finally it was an issue related with the info stored into database.

Regards,
Jose<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19939">issues.joomla.org/tracker/joomla-cms/19939</a>.</sub>

**Comment by C-Lodder** [comment] 2018-03-19 10:12
@Texpaok If it has been resolved, please close this issue

**Closed as completed** 2018-03-19 10:16 UTC
Labels: No Code Attached Yet
