### ISSUE TITLE
close after create menu item moves to default menu

### ISSUE THREAD

**Issue by c3ph3us** [joomla/joomla-cms#15447] opened 2017-04-21 12:09 UTC
3.7 rc4
1) go to menu ( non default) 
2) create item 
3) close 
4) you are moved to default instead one you was creating item for / or you hit add menu item 

expected behavior: 
 - go back to same menu where you  have hit add / or to menu for which the item was created for

this is annoying as every time i want to make a new item(for same menu) i need to change menu type  or change menu type in item create window

**Comment by franz-wohlkoenig** [comment] 2017-04-21 12:31
confirmed. I suppose "default" means "Home" (yellow Star).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15447">issues.joomla.org/tracker/joomla-cms/15447</a>.</sub>

**Comment by infograf768** [comment] 2017-04-21 13:11
nope, he is talking about the usual maimenu type, and i do confirm the behavior.

**Comment by c3ph3us** [comment] 2017-04-27 18:41
@infograf768  there is no need for you to confirm 

- select menu 
- add item
- close 
- you are on other menu 

https://youtu.be/1YIfVPYaRdA

**Comment by franz-wohlkoenig** [comment] 2017-04-28 04:59
@c3ph3us " This video is unavailable."

**Comment by Devportobello** [comment] 2017-05-17 15:31
Dunno if this is a related issue but when you do this steps : 

- select menu
- add item
- save and new

 in the item "Menu" rollback to the menu with default home item

**Comment by AlexRed** [comment] 2017-05-19 10:24
I can confirm the problem on Joomla! 3.7.2-Dev (nightly Build)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15447">issues.joomla.org/tracker/joomla-cms/15447</a>.</sub>

**Comment by franz-wohlkoenig** [comment] 2017-05-19 10:41
@infograf768 is this Something you can look at?

**Comment by franz-wohlkoenig** [comment] 2017-05-28 17:38
looks like this Issue is the one with the most duplicated Reports.

**Comment by brianteeman** [comment] 2017-05-30 21:19
closed as we have a PR for testing #16374

**Closed by brianteeman** 2017-05-30 21:19 UTC
Labels: No Code Attached Yet
