### ISSUE TITLE
MOD_STATUS_MESSAGES not defined in en-GB.mod_status.ini

### ISSUE THREAD

**Issue by remotehelp** [joomla/joomla-cms#8959] opened 2016-01-22 08:34 UTC
MOD_STATUS_MESSAGES that defined in /administrator/modules/mod_status/tmpl/default.php not present in /administrator/language/en-GB/en-GB.mod_status.ini

**Comment by infograf768** [comment] 2016-01-22 08:36
It is a plural form and exists as
```
MOD_STATUS_MESSAGES_0="%d Messages"
MOD_STATUS_MESSAGES_1="%d Message"
MOD_STATUS_MESSAGES_MORE="%d Messages"
```

**Comment by infograf768** [comment] 2016-01-22 08:38
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8959">issues.joomla.org/joomla-cms/8959</a>

**Comment by infograf768** [comment] 2016-01-22 08:38
Closing as not a bug.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8959">issues.joomla.org/joomla-cms/8959</a>.</sub>

**Closed by infograf768** 2016-01-22 08:38 UTC

**Comment by remotehelp** [comment] 2016-01-22 11:28
@infograf768 - for me title show as "MOD_STATUS_MESSAGES", why? "plural" does not work?
