### ISSUE TITLE
Content field `publish_up` not being set when publishing previously unpublished article

### ISSUE THREAD

**Issue by ron4mac** [joomla/joomla-cms#8740] opened 2015-12-19 14:52 UTC
When publishing a content article (at least from admin) that has previously been unpublished,`publish_up` is not being set to the current date/time. Visually, this causes a bad date to be shown for articles displayed with published dates. And logically, it can cause issues for extensions that rely on that date being appropriately set.

v3.4.6

#### Steps to reproduce the issue
Create a new article in an unpublished state.
From the admin Article Manager, click on publish widget or select article and use 'Publish' from toolbar.
Database field `publish_up` remains set to '000-00-00 00:00:00'.

#### Expected result
`publish_up` should be set to the current date/time

#### Actual result
Database field `publish_up` remains set to '000-00-00 00:00:00'.

#### System information (as much as possible)
Joomla! version 3.4.6
mysqli 5.5.45-MariaDB

**Comment by sovainfo** [comment] 2015-12-19 15:41
Maybe you can elaborate on what you think is wrong with what is happening. Because that is exactly what should happen, that is the way it is designed.

**Comment by bertmert** [comment] 2015-12-19 16:50
Confirmed.
When you open an unpublished new article, set it to published and save: field  *Start Publishing* is filled correctly. That's the expected behavior.
But not if you publish an unpublished article by clicking status change button in articles list or with button *Publish*

**Comment by brianteeman** [comment] 2015-12-20 13:29
Closed as we have a PR #8745 please test<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8740">issues.joomla.org/joomla-cms/8740</a>.</sub>

**Closed by brianteeman** 2015-12-20 13:29 UTC
Labels: No Code Attached Yet
