### ISSUE TITLE
1.an article showing its title (ariticle setting)  2.a category of articles NOT showing its title; (not working)

### ISSUE THREAD

**Issue by WilkoRietveld** [joomla/joomla-cms#10907] opened 2016-06-22 20:38 UTC
#### Steps to reproduce the issue

Create an article from which you want to show the article title use article settings
Create a group of articles from which you do not want to show the article title use general article options / setting 
If you turn the option “show title” on or off you will not be able to get a opposite setting for on of the two items. Try to control this by using the general article options in opposite, won’t work.(with me 3.5.1)

#### Expected result
different settings should exist next to each other. 

#### Actual result
not working 

#### System information (as much as possible)
standard Joomla 3.1.5 install

**Comment by JamalTailored** [comment] 2016-07-11 10:00
I have tested this same issue in staging branch and not able to reproduce. It means there is no issue in staging branch.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10907">issues.joomla.org/joomla-cms/10907</a>.</sub>

**Comment by gunjanpatel** [comment] 2016-07-12 04:27
Set to "closed" on behalf of @gunjanpatel by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10907">issues.joomla.org/joomla-cms/10907</a>

**Comment by gunjanpatel** [comment] 2016-07-12 04:27
Closing as unable to reproduce the issue in staging branch. We can always open if someone is able to reproduce it with staging. 

Thank you @WilkoRietveld for your contribution.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10907">issues.joomla.org/joomla-cms/10907</a>.</sub>

**Closed by gunjanpatel** 2016-07-12 04:27 UTC
Labels: No Code Attached Yet
