### ISSUE TITLE
New feature/Tweak for Metadata

### ISSUE THREAD

**Issue by kairoen** [joomla/joomla-cms#12043] opened 2016-09-15 09:41 UTC
Joomla is great for SEO for content, and you can use Joomla core to maintain and tweak the content. But the UI is not that consistent and easy to understand for the user. This is just a suggestion on how to tweak the UI to the user understand what Joomla can do for the site.

I have made a mock-up for a menutem:
![screen shot 2016-09-15 at 04 33 33](https://issues.joomla.org/uploads/1/c040ef6649578b5228fdbaa78c4c849d.jpg)

* moved "Browser Page Title" to the "Metadata" pane
* Renamed the "Metadata" pane to "SEO"
* Added a counter for characters, words in "Meta description", "Meta Keywords" and "Browser Page Title"
* Preview in Google SERP for the menuitem

The preview (Google SERP) should be updated once the content of the fields is filled (Ajax)

Also, there should be a tool-tip on give the user more information about what to insert in each fields.
The same window should also be set in article mode, since there are a option to set SEO.

With these small tweaks, the user will understand more on how to use Joomla to maintain these important tasks to optimize the content for search engines.

**Comment by brianteeman** [comment] 2016-09-23 09:53
1. Browser page title is much more than just seo so I prefer it where it is

2. There are several extensions that provide this sort of Meta testing and counts

**Comment by kairoen** [comment] 2016-10-07 11:19
SEO is a important issue no matter what kind of website you have. So depending on 3.party extensions for this simple issue, sound a but strange to me. Even less extensions, more secure the Joomla site will be. 

So, what is "Browser Page Title" used as? For me (and my clients), the key is only for SEO purpose<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12043">issues.joomla.org/tracker/joomla-cms/12043</a>.</sub>

**Comment by brianteeman** [comment] 2016-10-07 14:26
It might only be SEO for you but it semantically defines the content. 
For example if you are only concerned about "seo" then you would need to ensure that the title is less than a certain length. But if you are more concerned about defining the content then that restriction is not relevant



But thats just my 2c - feel free to submit a PR with your suggested code for peer review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12043">issues.joomla.org/tracker/joomla-cms/12043</a>.</sub>

**Comment by franz-wohlkoenig** [comment] 2017-01-31 13:49
@kairoen is there a PR coming to test?

**Comment by franz-wohlkoenig** [comment] 2017-05-16 04:55
closed as Duplicate of #15833<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12043">issues.joomla.org/tracker/joomla-cms/12043</a>.</sub>

**Closed** 2017-05-16 04:56 UTC
Labels: No Code Attached Yet
