### ISSUE TITLE
No layout edit if need reset password account via module

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#39300] opened 2022-11-24 12:56 UTC
### Discussed in https://github.com/joomla/joomla-cms/discussions/39282

<div type='discussions-op-text'>

<sup>Originally posted by **Mika17420** November 22, 2022</sup>
if a user connects via the module and if joomla params for reset password on first login. There is no redirect to the layout=edit page. You have to click on any link to see the page appear</div>

**Comment by Mika17420** [comment] 2022-12-16 07:52
does anyone have a solution for this problem?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39300">issues.joomla.org/tracker/joomla-cms/39300</a>.</sub>

**Comment by chmst** [comment] 2022-12-16 08:02
Related https://issues.joomla.org/tracker/joomla-cms/38788

**Comment by Hackwar** [comment] 2024-11-24 22:58
This actually is a duplicate of #38788, so I'm closing this one.

**Closed as completed by Hackwar** 2024-11-24 22:58 UTC
Labels: No Code Attached Yet, bug
