### ISSUE TITLE
Upload svg to media manager has bugged tooltip

### ISSUE THREAD

**Issue by pnkr** [joomla/joomla-cms#31229] opened 2020-10-25 09:54 UTC
### Steps to reproduce the issue
Navigate to content media
Upload an svg
hover over the uploaded file

### Expected result
Highlight the file

### Actual result
opens a tooltip with some code inside

### System information (as much as possible)
Joomla Version: 4.0.0-beta5-dev
PHP Version	7.3.21
Database Type	mysql
Database Version	5.7.30-cll-lve
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci

### Additional comments

I have attached a screenshot to show the problem.

**Comment by pnkr** [comment] 2020-10-25 09:56
![screen shot 2020-10-25 at 09 55 52](https://issues.joomla.org/uploads/1/542afda651207dc66cd8885d20d400cb.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31229">issues.joomla.org/tracker/joomla-cms/31229</a>.</sub>

**Comment by infograf768** [comment] 2020-10-25 10:54
Could not figure how you uploaded a svg via media manager (yep, I added it in Options). Had to do manually, but I confirm the issue when there is an .svg present.

<img width="835" alt="Screen Shot 2020-10-25 at 11 38 16" src="https://user-images.githubusercontent.com/869724/97104755-9e434600-16b6-11eb-8b9b-fb6c203c038f.png">

This comes directly from the mediamanager.min.js code
`[e._v(" :title=\"translate('COM_MEDIA_TOGGLE_SELECT_ITEM')\">\n  ")]`

EDIT: figured out how to upload: use `image/svg` as MIME type and not `image/svg+xml` ;)

**Comment by infograf768** [comment] 2020-10-25 11:19
@Fedik @dgrammatiko

**Comment by brianteeman** [comment] 2020-10-25 11:26
the problem is in the mime type detection
If you click on the info for the file it will be incorrectly saying mime type false

**Comment by infograf768** [comment] 2020-10-25 11:30
<img width="700" alt="Screen Shot 2020-10-25 at 12 29 26" src="https://user-images.githubusercontent.com/869724/97105764-c71b0980-16bd-11eb-837b-89939abdd8b1.png">

**Comment by brianteeman** [comment] 2020-10-25 11:30
ok - false cause then - that must have been an issue with my svg

**Comment by dgrammatiko** [comment] 2020-10-25 12:26
@infograf768 chenge https://github.com/joomla/joomla-cms/blob/7be3d99df7205fe972cade24764e2c157b39caa7/administrator/components/com_media/resources/scripts/components/browser/items/item.es6.js#L19 to  `const imageExtensions = ['jpg', 'jpeg', 'png', 'gif', 'svg'];` and ,magic will happen

**Comment by pnkr** [comment] 2020-10-25 12:44
> Could not figure how you uploaded a svg via media manager (yep, I added it in Options). Had to do manually, but I confirm the issue when there is an .svg present.
> 
> <img alt="Screen Shot 2020-10-25 at 11 38 16" width="835" src="https://user-images.githubusercontent.com/869724/97104755-9e434600-16b6-11eb-8b9b-fb6c203c038f.png">
> 
> This comes directly from the mediamanager.min.js code
> `[e._v(" :title=\"translate('COM_MEDIA_TOGGLE_SELECT_ITEM')\">\n ")]`
> 
> EDIT: figured out how to upload: use `image/svg` as MIME type and not `image/svg+xml` ;)

Well from media manager at option menu, if you set:

1. Legal Extensions (File Types) add svg,SVG
2. Legal MIME Types add image/svg+xml

you are ready to upload  an svg file.

**Comment by infograf768** [comment] 2020-10-25 12:50
> Legal MIME Types add image/svg+xml

As i wrote above, that did not work here. got 403.
image/svg did work

**Comment by dgrammatiko** [comment] 2020-10-25 12:51
Test https://github.com/joomla/joomla-cms/pull/31233

**Closed as completed** 2020-10-25 13:06 UTC
Labels: No Code Attached Yet
