### ISSUE TITLE
Joomla cache calls usleep on first call of cache->get

### ISSUE THREAD

**Issue by stAn47** [joomla/joomla-cms#10706] opened 2016-06-01 12:30 UTC
#### Steps to reproduce the issue
applications that are using joomla's cache handler: 

$cache = JFactory::getCache('my_key','callback');
$cache->setCaching(true);
$cache->call( array( 'MyClass', 'MyFunction' ),$param1,$param2,$param3);

the cache handlers in joomla do usleep on a first round even when the key hasn't yet been created within the cache handlers. 

related joomla core files with usleep: 
\libraries\joomla\cache\storage\file.php
\libraries\joomla\cache\cache.php
+ other handlers 

original code in file.php
[code]
usleep(100);
$data_lock = @flock($_fileopen, LOCK_EX);
[/code]
suggested code (to usleep only after the first round): 
[code]
$data_lock = @flock($_fileopen, LOCK_EX);
				if ($data_lock === false) {
				  usleep(100);
				}
[/code]

since locking is handled in the handler (file and others) i do not see the point to delay script with usleep in the main cache class: 
\libraries\joomla\cache\cache.php

#### Expected result
adding Nx 2x 100 microsends to the page load depending on N number of times of calling the cache function while having an empty cache. 

#### Actual result
slow site, lower SEO

#### System information (as much as possible)
php 5.5 on joomla 3.5.1

**Comment by brianteeman** [comment] 2016-06-01 12:35
Reset priority according to documented standards https://docs.joomla.org/Priority<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10706">issues.joomla.org/joomla-cms/10706</a>.</sub>

**Comment by zero-24** [comment] 2016-06-01 12:55
As you have allready code you can submit them as pull request with test instructions :smile: 

If you need help please see here: https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests

**Comment by csthomas** [comment] 2016-06-08 09:39
IMHO the problem is that the flock function can not lock not existed file.
* Below I've changed flag for fopen to create file if not exists.
* If the cache file can not be created then return false immediately.
 
For storage file.php you can test below solution (Joomla 3.5.1):
```
diff --git a/libraries/joomla/cache/storage/file.php b/libraries/joomla/cache/storage/file.php
index 94bf0a2..c1f5f89 100644
--- a/libraries/joomla/cache/storage/file.php
+++ b/libraries/joomla/cache/storage/file.php
@@ -275,17 +275,15 @@ class JCacheStorageFile extends JCacheStorage
 
                $looptime  = $locktime * 10;
                $path      = $this->_getFilePath($id, $group);
-               $_fileopen = @fopen($path, "r+b");
+               $_fileopen = @fopen($path, "w+b");
 
-               if ($_fileopen)
+               if (!$_fileopen)
                {
-                       $data_lock = @flock($_fileopen, LOCK_EX);
-               }
-               else
-               {
-                       $data_lock = false;
+                       return false;
                }
 
+               $data_lock = @flock($_fileopen, LOCK_EX);
+
                if ($data_lock === false)
                {
                        $lock_counter = 0;
```
If that resolve the problem I can create PR.

**Comment by csthomas** [comment] 2016-06-09 08:42
I have created a PR.

#### To discuss
Method **lock** in *libraries/joomla/cache/cache.php* also try to lock if storage handler fails.
It may be unnecessary. Any thoughts?

**Comment by zero-24** [comment] 2016-07-30 20:36
Set to "closed" on behalf of @zero-24 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10706">issues.joomla.org/joomla-cms/10706</a>

**Comment by zero-24** [comment] 2016-07-30 20:36
Closing as we have a PR for testing. Thanks @csthomas<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10706">issues.joomla.org/joomla-cms/10706</a>.</sub>

**Closed by zero-24** 2016-07-30 20:36 UTC
Labels: No Code Attached Yet

**Comment by csthomas** [comment] 2016-08-24 10:26
PR #10767 is waiting for tests. Is anyone interested?
