### ISSUE TITLE
Password and confirm password are not mandatory and Login does not allow empty passwords.

### ISSUE THREAD

**Issue by dj985** [joomla/joomla-cms#6865] opened 2015-04-30 04:47 UTC
#### Steps to reproduce the issue
-Go to create new user view
-Create a new user, keep blank password & confirm password fields and click over the save button
-If we keep these two fields blank and save the user, The user account is getting created but that user cannot login because password field is mandatory.
![screen shot 2015-04-29 at 23 46 30](http://issues.joomla.org/uploads/1/6d07cd3d4cd15fe9fe9e6073ba893864.)

#### Expected result

Succesfully Logged in

#### Actual result

Empty passwords are not allowed.

#### Additional comments

![screen shot 2015-04-29 at 23 46 36](http://issues.joomla.org/uploads/1/255880cf52734caa7eb486494822f95e.)![screen shot 2015-04-29 at 23 46 38](http://issues.joomla.org/uploads/1/e2aacab2d94f21f9ebaef5dd4e3016ec.)![screen shot 2015-04-29 at 23 46 39](http://issues.joomla.org/uploads/1/fe9c92a9cb39199e472bcdb6e4fe3880.)

**Comment by brianteeman** [comment] 2015-04-30 06:26
Unfortunately your screenshots have not uploaded successfully.

I am really not sure what you are saying though. Of course a user account without a password cannot work. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6865">issues.joomla.org/joomla-cms/6865</a>.</sub>

**Comment by OctavianC** [comment] 2015-04-30 07:32
I think he's saying that you can save a new user in the backend (Users > Users Manager > Add New User) without supplying a password. Although this seems to be the case, actually a randomly generated password is sent to the newly created user's email inbox. I'm guessing @dj985 didn't use a valid email address during testing to notice this.

**Comment by brianteeman** [comment] 2015-04-30 11:49
Closing as expected behaviour<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6865">issues.joomla.org/joomla-cms/6865</a>.</sub>

**Closed** 2015-04-30 11:49 UTC
Labels: No Code Attached Yet
