### ISSUE TITLE
Problems with checkout system

### ISSUE THREAD

**Issue by smehrbrodt** [joomla/joomla-cms#13120] opened 2016-12-07 17:28 UTC
When editing an article, it gets the status "Checked out". That prevents any other user to edit the same article at the same time.
The status will be reset when closing the article.
However, when closing the window/tab with the edit form, the checked out status is not being reset.

This can lead to many checked out articles, and users not knowing what causes this.

Maybe we can add some warning message, or release the lock before closing the window.

**Comment by brianteeman** [comment] 2016-12-07 17:31
As far as I am aware it is not possible to prevent someone closing a
browser tab/window and force the display of a message. Even if it was I'm
not convinced it would be a good idea.

**Comment by smehrbrodt** [comment] 2016-12-07 17:36
> As far as I am aware it is not possible to prevent someone closing a browser tab/window and force the display of a message.

It is possible: https://developer.mozilla.org/de/docs/Web/API/WindowEventHandlers/onbeforeunload

> Even if it was I'm not convinced it would be a good idea. 

As I said, it must not be that we display a warning message, a ping to the Joomla backend "please release this content" would be enough.

**Comment by PhilETaylor** [comment] 2016-12-07 19:00
This feature is performing EXACTLY as it was developed to - there is no bug, if you check out an item then its checked out until you check it back in by closing the article or saving it. 

If you close the browser then it quite rightly remains checked out. This is by design.

**Comment by brianteeman** [comment] 2016-12-07 19:20
That link to mozilla.org shows that even if possible it is only supported by a small number of the browsers we use making it functionally useless.

I am closing this at this time as expected behaviour. It could be re-opened if you find a solution that will work with all supported browser.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13120">issues.joomla.org/tracker/joomla-cms/13120</a>.</sub>

**Closed** 2016-12-07 19:20 UTC
Labels: No Code Attached Yet

**Comment by dgt41** [comment] 2016-12-07 20:09
@smehrbrodt could you use https://github.com/joomla/joomla-cms/pull/4773 as your base and provide  a ~working~ solution?

**Comment by smehrbrodt** [comment] 2016-12-08 10:13
> That link to mozilla.org shows that even if possible it is only supported by a small number of the browsers we use making it functionally useless.

That page is called WebAPI - not Firefox API. It's just hosted by mozilla. And the page states that it works in all major browsers, even in IE since version 4.

> If you close the browser then it quite rightly remains checked out. This is by design.

What benefit does one have by that "design" decision?

The problem is, that there is no easy way to just "view" an article in the backend - to do that, you need to go to the edit view. And if you just cared about viewing, you usually do not care to save or close the article using the Joomla buttons - but might just close the window/tab.

Maybe another possibility would be to take the lock only when starting to actually edit something? Or have the locks automatically been reset after a period of inactivity? Or something else?
There must be some solution for this.

**Comment by brianteeman** [comment] 2016-12-08 10:15
Check the links at the bottom and it shows all the browsers it does not
work on including mobile
