### ISSUE TITLE
Joomla 4.0 iframe doesn't show title of embedded calendar

### ISSUE THREAD

**Issue by Peter620327** [joomla/joomla-cms#38460] opened 2022-08-14 16:01 UTC
### Expected result; calendar title showing up
This is how it is working fine in joomla 3.0: see attended file 'Joomla 3.0 iframe - Show Title.JPG'
![screen shot 2022-08-14 at 15 53 55](https://issues.joomla.org/uploads/1/c80046bbc5d4a618ae0e3115e2072d5c.jpg)

### Actual result: calendar title not showing up
This is what happens on local host/joomla 4.0: see attended file 'Joomla 4.0 iframe - Show Title.JPG'
![screen shot 2022-08-14 at 15 53 58](https://issues.joomla.org/uploads/1/5c7d2624bdd0bca1c23d5ba89a9b50dd.jpg)

### System information (as much as possible)
Joomla 3.0 online
Joomla 4.0 localhost

**Comment by brianteeman** [comment] 2022-08-14 20:33
Your screenshots are showing that the problem is that the data inside the iframe does not contain the desired title.

Everything inside the iframe is coming from the source site and not from joomla. Joomla can only display the information it is given.

Perhaps the data in the iframe doesnt provide the title because you are on localhost?

For any further support please use the forums

**Comment by chmst** [comment] 2022-08-15 11:54
Closing as this is not a Joomla issue

**Closed as completed by chmst** 2022-08-15 11:54 UTC
Labels: No Code Attached Yet
