### ISSUE TITLE
onChangeState for Update Sites not present.

### ISSUE THREAD

**Issue by UWiX-nl** [joomla/joomla-cms#13279] opened 2016-12-19 08:45 UTC
### Steps to reproduce the issue
1. Go to Backend->Extensions->Manage->Update Sites and (un)publish an update site in the listing.
2. Try to catch the event using OnContentChangeState in a Plugin (why this event? 'cause every other changestate works through this event - so it's expected to use this one ;-) ).

### Expected result
The plugin function should be triggered.

### Actual result
No result because the trigger does not exists for (un)publishing Update sites.

### System information (as much as possible)
PHP Version 7.0.9
Web Server Apache 2.4.23 (Win32)
Joomla! version 3.6.5
User Agent Mozilla/5.0 (Windows NT 6.3; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0 

### Additional comments
Suggestion to add a trigger event to administrator/components/com_installer/models/updatesites.php called OnUpdateSiteChangeStage. Add the following code at line 109 (in the function publish):

  $context = $this->option . '.' . $this->name;
  JEventDispatcher::getInstance()->trigger('onUpdateSiteChangeState', array($context, $eid, $value));

The event name onContentChangeState is not logical because this new event must be started from within a System plugin (if I am correct).

**Comment by rvbgnu** [comment] 2017-06-03 14:00
Duplicate of #13278
@nibra

**Comment by franz-wohlkoenig** [comment] 2017-06-25 12:40
closed as duplicate Report.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13279">issues.joomla.org/tracker/joomla-cms/13279</a>.</sub>

**Closed by franz-wohlkoenig** 2017-06-25 12:40 UTC
Labels: No Code Attached Yet
