### ISSUE TITLE
J3.6.0, currently active language (language switch) ignored, when revisiting home page URL without language code

### ISSUE THREAD

**Issue by maofree** [joomla/joomla-cms#11143] opened 2016-07-15 10:28 UTC
#### Steps to reproduce the issue
I've upgraded 2 sites to the last 3.6.0 and both have the same errors
the url for the logo link is done with this code
$this->baseurl
the site is this and it has 2 languages
http://www.anticotravaglio-monteriggioni.com
the italian homepage is
http://www.anticotravaglio-monteriggioni.com/osteria-gelateria/it/
instead the english is
http://www.anticotravaglio-monteriggioni.com/osteria-gelateria/en/
if I push on the flags languiages all is ok instead if I push on the logo no, it goes always on the default language.
if I push on the enaglish language and then I push on the logo I will get the italian language
so I think there is a cookie problem that doesn't remeber the selected language by the visitor.

on the 3.5.1 all was ok
with $this->baseurl the url is
http://www.anticotravaglio-monteriggioni.com/osteria-gelateria/
but after the url will be redirect to the right one following the current language

the same problem appears when I set only the domain
http://www.anticotravaglio-monteriggioni.com
the final url will be always
http://www.anticotravaglio-monteriggioni.com/osteria-gelateria/it/

thanks

**Comment by infograf768** [comment] 2016-07-15 10:39
I tested your site and can't reproduce your issue.
When I am on the English (en-GB) Home page, the logo link gets to the same page.
When I am on the Italian (it-IT), I load the Italian home page OK when clicking on the logo.

**Comment by maofree** [comment] 2016-07-15 10:42
Hi
I try again but if I set italian language all is ok (it is the default one)
instead if I set the english one and I go to another page and then I push on the logo I return to the italian language
I'm using firefox, on linux and widows I get the same result, on the past 3.5.1 it was, 15 minutes ago

**Comment by maofree** [comment] 2016-07-15 10:44
ok with chorme it is ok
so the bug is on firefox

**Comment by infograf768** [comment] 2016-07-15 10:45
I used Firefox for my tests

**Comment by maofree** [comment] 2016-07-15 10:49
on firefox now I have cleaned the cache
I get the same problem but inverted now the default language seems in english
from italian language pushing on the logo I go to english language
it is so strange
in chrome is ok (cleaning the cache too)

**Comment by maofree** [comment] 2016-07-15 10:51
with opera is ok

**Comment by brianteeman** [comment] 2016-07-15 11:00
Tested on my android tablet and all worked as expected<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11143">issues.joomla.org/joomla-cms/11143</a>.</sub>

**Comment by maofree** [comment] 2016-07-15 11:30
http://www.saharizanzibar.net
here with firefox 47.0.1 I get the same error
only with these two sites upgraded 1 hour ago

instead this one is with 3.5.1 and it is ok with firefox
http://www.casavacanze-poderecappella.com

**Comment by infograf768** [comment] 2016-07-15 13:09
Please use the forum for support http://forum.joomla.org as we can't reproduce your issues.
@brianteeman
I guess this can be closed.

**Comment by maofree** [comment] 2016-07-15 14:42
Hi
in the forum I can't find any type of help.
I've asked to another developer, and he says the same thing.
with firefox on a pc, the language change, if EN is set and he push on the logo or set  http://www.anticotravaglio-monteriggioni.com the language change to ITA
instead on this one all is
http://www.casavacanze-poderecappella.com/holiday-rental-siena/it/

he can reproduce this issue, so I think you can do it also.
The settings on my firefox are the same of yesterday the only thing changed if the Joomla's version

I've tested from another pc usign teamviewer, I get the same error, so I reproduce it from 3 different pc, from different OS and different LAN

please please please
can you ask to another guys to test?
do you know if something is changed about the language code? like rewrite url?

**Comment by maofree** [comment] 2016-07-15 14:45
probably your defaul language is EN, so from IT it should go to EN pushing on the logo
howvere you should reproduce this error from all site with multilang

trust me it is a bug

please please  please ;(

**Comment by maofree** [comment] 2016-07-15 14:54
Hi
Asked to another guy to check this issue from his pc
he says the same thing, with firefox the language change to the default one when he presses on the logo

they are all from Italy

**Comment by andrepereiradasilva** [comment] 2016-07-15 16:13
could be redirect cache related to this? https://github.com/joomla/joomla-cms/pull/8894

**Comment by ggppdk** [comment] 2016-07-15 16:14
@andrepereiradasilva 

it is exactly that !
- i have tested and confirmed it

**Comment by andrepereiradasilva** [comment] 2016-07-15 16:15
See https://github.com/joomla/joomla-cms/pull/8894#issuecomment-213825388

**Comment by ggppdk** [comment] 2016-07-15 16:32
See picture, indeed the browser is instructed to cache the redirect

![redirect](https://cloud.githubusercontent.com/assets/5092940/16880994/9c313686-4ac0-11e6-98b7-35c0ddb2948e.png)

@maofree 

It was decided that visitors and search engines should always be redirected **to the same language URL when the home page**
- at 1st visit of a your home page url, it has no language code in it,
- server (joomla) decides a language for the visitor according to configuration and browser settings
- a redirection happens to the home page URL with language code, the browser is instructed to always request the language-based URL, instead of the bare home page URL 

thus the language cookie is not used

The above is an intended behaviour change , that was considered worthable because of SEO ?

The current language cookie will be used if you append to yout home page URL:
?aaa=45
- the above will bypass browser cache ...  

switch language and a larger number to the above home page URL and press enter,
you will see that the current language is respected

**Comment by maofree** [comment] 2016-07-15 21:14
Hi
thanks for your info
so this problem came out from the 3.5.2, in fact the other sites are on joomla 3.5.1
The change made on joomla has problem with firefox's cache

**Comment by infograf768** [comment] 2016-07-16 04:47
as there are as many advices as users on this, we could add a prameter in the plugin to let choose between a 303 and a 301, default to 301.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11143">issues.joomla.org/joomla-cms/11143</a>.</sub>

**Comment by maofree** [comment] 2016-07-16 07:47
hi
I've a question:
looking that post
with 303 redirect google will store both URLs in index
domain-name.com/contact -> domain-name.com/en/contact
with 301 redirect only the last one

so the better choice is 301
and you said
301 is correct for multilang. This was changed in 3.4.
so why in the 3.6.0 with firefox there are problems?
is it possible to alert firefox to change its cache behavior? the other browsers work well

thanks
bye

**Comment by andrepereiradasilva** [comment] 2016-07-16 09:02
IMHO we could mantain the 301 redirect, but we could also use HTTP headers to not allow browsers to cache it.
This way we force browsers to always ask the server the location of the 301 redirect.

example: http://stackoverflow.com/questions/12192590/how-to-do-a-non-cached-301-redirect/19003320#19003320

**Comment by chrisdavenport** [comment] 2016-07-16 09:55
301 is a permanent redirect and caches will retain it.  You can provide HTTP headers that tell caches how long they should retain it, but telling a cache not to retain it at all is probably a contradiction since it's supposed to be permanent.

303 is a redirect to a different resource, which I don't think is appropriate here.

307 is probably the best choice since it is a temporary redirect and will likely not be cached by default.  However, sending HTTP header directives would allow you to tell caches just how long they should retain it before considering it stale and it would be perfectly reasonable to tell caches not to retain it at all.

https://tools.ietf.org/html/rfc7231#section-6.4.2

**Comment by andrepereiradasilva** [comment] 2016-07-16 10:21
"307 Temporary Redirect" is basicly the same thing as "302 Found".
See https://tools.ietf.org/html/rfc7238#section-1

**Comment by ggppdk** [comment] 2016-07-16 10:37
I now that this is closed, but maybe rename title of it to:

J3.6.0, currently active language (language switch) ignored, when revisiting home page URL without language code

**Comment by maofree** [comment] 2016-07-16 10:38
renamed

**Comment by chrisdavenport** [comment] 2016-07-16 10:38
@andrepereiradasilva Indeed.  Depends whether we need to change a POST to a GET.  Either way, I don't think 301, 303 or 308 are appropriate.

**Comment by andrepereiradasilva** [comment] 2016-07-16 10:54
so we are left with 302, which, that i know of, does not cache.

**Comment by andrepereiradasilva** [comment] 2016-07-16 22:45
please test https://github.com/joomla/joomla-cms/pull/11161

**Comment by maofree** [comment] 2016-07-16 23:31
Hi  andrepereiradasilva
I've tested that changes replacing languagefilter.php
it seems ok but it generates a new bug, the language flags disappear with the horizontal menu (this happen pushing some times on the menu voices and switching the current language)

![111](https://cloud.githubusercontent.com/assets/653230/16897819/1a456300-4bbe-11e6-9309-5470cb44872d.png)

bye

**Comment by ggppdk** [comment] 2016-07-16 23:37
Flags disappear is probably not related to the issue or the fix of it !!
it is because of you template / extensions / configuration that you have in you in your website

**Comment by maofree** [comment] 2016-07-16 23:38
this new issue happens when I use the new file, with the default one it is ok

**Comment by maofree** [comment] 2016-07-16 23:40
Give me a moment to replace the last one to reproduce this error by yourself

**Comment by maofree** [comment] 2016-07-16 23:42
go to the site and look at it
test it only for 5 minutes, then I return to the previous one

**Comment by maofree** [comment] 2016-07-16 23:43
All modules are disappears from the site

**Comment by dgt41** [comment] 2016-07-16 23:43
@maofree is sh404sef installed in you site?

**Comment by maofree** [comment] 2016-07-16 23:44
no

**Comment by dgt41** [comment] 2016-07-16 23:44
and all langs are properly configured? content, menus etc?

**Comment by maofree** [comment] 2016-07-16 23:46
yes
if you want i can give you the access to the admin

**Comment by maofree** [comment] 2016-07-16 23:46
without the new rows all modules are visible

**Comment by maofree** [comment] 2016-07-16 23:48
```
			// Don't cache the redirect in browser.
			$this->app->setHeader('Expires', 'Wed, 17 Aug 2005 00:00:00 GMT', true);
			$this->app->setHeader('Last-Modified', gmdate('D, d M Y H:i:s') . ' GMT', true);
			$this->app->setHeader('Cache-Control', 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0', false);
			$this->app->setHeader('Pragma', 'no-cache');
			$this->app->sendHeaders(); ```

**Comment by ggppdk** [comment] 2016-07-16 23:50
@maofree 
> go to the site and look at it

i didn't say that it does not happen
i just say that this is not happening because of patch

I assume that you did you disable any caching , including the system cache plugin before testing

**Comment by maofree** [comment] 2016-07-16 23:53
the joomla's cache is disabled and now also jch optimize
I try to remove those new rows from that file

**Comment by maofree** [comment] 2016-07-16 23:58
ok tested
the new issue is due from because to that file are removed these lines
with the follow code the modules are visible

```
			$this->app->setLanguageFilter(true);

			// Detect browser feature.
			$this->app->setDetectBrowser($this->params->get('detect_browser', '1') == '1');
```

however the language problem continue to be present like before

**Comment by andrepereiradasilva** [comment] 2016-07-17 00:00
did you before clean all browser cache and cookies?
Try to use new private window, for instance,

**Comment by maofree** [comment] 2016-07-17 00:01
yes cleaning the browser's cache it seems to work well

**Comment by ggppdk** [comment] 2016-07-17 00:01
In order to test the patch you need:
- your site cache OFF
- clean browser cache
- your site should not have a transparent proxy in front of it

**Comment by maofree** [comment] 2016-07-17 00:04
now it works, that code fix this problem

can you add this lines to this file at line 78?

```
			$this->app->setLanguageFilter(true);

			// Detect browser feature.
			$this->app->setDetectBrowser($this->params->get('detect_browser', '1') == '1');
```
https://github.com/andrepereiradasilva/joomla-cms/blob/963c58ccd4184232d3e88f0897666a60059341a3/plugins/system/languagefilter/languagefilter.php

because from here now they are not present

**Comment by mbabker** [comment] 2016-07-17 00:05
You need to apply the changes from https://github.com/joomla/joomla-cms/pull/10344 in addition to whatever you're testing if you're doing anything with the languagefilter plugin.

**Comment by maofree** [comment] 2016-07-17 00:08
ok understood

**Comment by ggppdk** [comment] 2016-07-17 00:08
@maofree 
so the new issue you reported was because you applied 1 and half patches
)))

**Comment by infograf768** [comment] 2016-07-17 06:37
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11143">issues.joomla.org/joomla-cms/11143</a>

**Comment by infograf768** [comment] 2016-07-17 06:37
Closed as we have a patch

https://issues.joomla.org/tracker/joomla-cms/11161<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11143">issues.joomla.org/joomla-cms/11143</a>.</sub>

**Closed by infograf768** 2016-07-17 06:37 UTC

**Comment by maofree** [comment] 2016-07-28 17:28
Hi
Today I got a google's notification about hreflang tag of that site
from webmaster tool I see 6 hreflang tags but in the site there are only 3 hreflang tags (in the source code).
It reports 3 hreflang tags have errors
Is it due from this fix or is it due from another thing?

![1111](https://cloud.githubusercontent.com/assets/653230/17222568/50216f70-54f9-11e6-8428-f13ebcb36805.png)

thanks
bye
