### ISSUE TITLE
Changes to Isis template breaking buttons

### ISSUE THREAD

**Issue by joeforjoomla** [joomla/joomla-cms#12559] opened 2016-10-25 21:58 UTC
### Steps to reproduce the issue
Use a default class btn-default for configuration buttons not working anymore

### Expected result
Normal buttons layout red/green

### Actual result
Broken buttons layout, all btn-default

### System information (as much as possible)
This is caused by changes to the following styles in the Isis template, now missing:

.btn-danger:hover,
.btn-danger:focus,
.btn-danger:active,
.btn-danger.active,
.btn-danger.disabled,
.btn-danger[disabled] {
	color: #fff;
	background-color: #942a25;
	*background-color: #802420;
}

and

.btn-success:hover,
.btn-success:focus,
.btn-success:active,
.btn-success.active,
.btn-success.disabled,
.btn-success[disabled] {
	color: #fff;
	background-color: #378137;
	*background-color: #2f6f2f;
}

In Joomla 3.7 they turned to the following, missing additional pseudo classes and breaking the  cascade overrides in some cases:

.btn-danger:hover,
.btn-danger:focus {
  background-color: #802420;
  color: #fff;
  text-decoration: none;
}

.btn-success:hover,
.btn-success:focus {
  background-color: #2f6f2f;
  color: #fff;
  text-decoration: none;
}
### Additional comments
Revert back to the full pseudo classes selectors.

![buttons_broken](https://cloud.githubusercontent.com/assets/17835460/19705787/c150d5cc-9b0e-11e6-8b54-c7a046fb473e.PNG)

**Comment by ciar4n** [comment] 2016-10-26 08:16
Could you detail how to replicate these buttons? The issue isn't present with any of the standard Joomla field types.

**Comment by joeforjoomla** [comment] 2016-10-26 09:44
It happens with some extension depending on the CSS overrides. When buttons have the class 'btn-default' they lose the color, because of the changes reported above.

**Comment by ciar4n** [comment] 2016-10-26 09:55
Could you give an example of such an extension?

**Comment by joeforjoomla** [comment] 2016-10-26 10:05
I found happening for all extensions adding using javascript the following 'btn-default' class to the buttons:

$('input[type=radio]~label').addClass('radio btn btn-default');

**Comment by ciar4n** [comment] 2016-10-26 10:23
The standard way for creating such buttons is with the following xml...

```
<field name="myradiovalue" type="radio" default="0" label="Select an option" description="" class="btn-group">
  <option value="0">1</option>
  <option value="1">2</option>
</field>
```

If you have an extension that uses an alternative method, I would need access to test it or at least a detailed description on how to replicate the buttons.

**Comment by C-Lodder** [comment] 2016-10-26 11:08
`btn-default` is not used in Bootstrap 2, it's used on Bootstrap 3 and above. To create a button group in Joomla, you should use the method provided in the comment above. If your extension doesn't do their, they **they** need to fix their extension.

**Comment by brianteeman** [comment] 2016-10-26 11:24
> I found happening for all extensions adding using javascript the following 'btn-default' class to the buttons:

Please as we provide an example

**Comment by brianteeman** [comment] 2016-10-26 11:24
Dam autocorrect.

Please provide a sample extension

**Comment by mbabker** [comment] 2016-10-26 17:18
3.6 does not have style rules for a `btn-default` class (though it is used in a handful of elements, I presume for forward compatibility with Bootstrap 3).  The highlighted CSS changes are unrelated to this class.  Presumably if anything the `btn` class definitions have changed, though 100% intended with the re-skinning of the template included in 3.7.

Without providing a sample extension or at a minimum a form definition (and apparently overriding style declarations) where the issue can be replicated, there is no bug to address here.

**Comment by brianteeman** [comment] 2016-11-02 14:21
> Without providing a sample extension or at a minimum a form definition (and apparently overriding style declarations) where the issue can be replicated, there is no bug to address here.

@joeforjoomla please respond to this request from @mbabker - otherwise this will have to be closed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12559">issues.joomla.org/tracker/joomla-cms/12559</a>.</sub>

**Comment by brianteeman** [comment] 2016-11-14 20:17
@joeforjoomla this will be closed in 7 days<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12559">issues.joomla.org/tracker/joomla-cms/12559</a>.</sub>

**Comment by brianteeman** [comment] 2016-12-09 12:28
Kept it open for another month but as there has been no response there is no option but to close this. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12559">issues.joomla.org/tracker/joomla-cms/12559</a>.</sub>

**Closed** 2016-12-09 12:28 UTC
Labels: No Code Attached Yet
