### ISSUE TITLE
[5.0] After updating from 4.4.0 - Error: 0 Class "JPlugin" not found

### ISSUE THREAD

**Issue by FrankReisenhofer** [joomla/joomla-cms#42409] opened 2023-11-28 09:59 UTC
### Steps to reproduce the issue

Perform an update from Joomla 4.4.0 to 5.0.0

### Expected result
No errors should occur. Instead I got 0 Class "JPlugin" not found

### Actual result
Es ist ein Fehler aufgetreten.
0 Class "JPlugin" not found
Call Stack
#	Function	Location
1	()	JROOT/plugins/system/uikit3/uikit3.php:4
2	require_once()	JROOT/libraries/src/Extension/ExtensionManagerTrait.php:217
3	Joomla\CMS\Application\CMSApplication->loadPluginFromFilesystem()	JROOT/libraries/src/Extension/ExtensionManagerTrait.php:160
4	Joomla\CMS\Application\CMSApplication->loadExtension()	JROOT/libraries/src/Extension/ExtensionManagerTrait.php:99
5	Joomla\CMS\Application\CMSApplication->bootPlugin()	JROOT/libraries/src/Plugin/PluginHelper.php:232
6	Joomla\CMS\Plugin\PluginHelper::import()	JROOT/libraries/src/Plugin/PluginHelper.php:192
7	Joomla\CMS\Plugin\PluginHelper::importPlugin()	JROOT/libraries/src/Application/CMSApplication.php:765
8	Joomla\CMS\Application\CMSApplication->initialiseApp()	JROOT/libraries/src/Application/AdministratorApplication.php:321
9	Joomla\CMS\Application\AdministratorApplication->initialiseApp()	JROOT/libraries/src/Application/AdministratorApplication.php:174
10	Joomla\CMS\Application\AdministratorApplication->doExecute()	JROOT/libraries/src/Application/CMSApplication.php:306
11	Joomla\CMS\Application\CMSApplication->execute()	JROOT/administrator/includes/app.php:58
12	require_once()	JROOT/administrator/index.php:32

### Additional comments

The issue is similar to https://github.com/joomla/joomla-cms/issues/41641. But even cleaning the cache did not solve the issue.

**Comment by HLeithner** [comment] 2023-11-28 10:13
@FrankReisenhofer this is not a bug, the plugin your using needs an update by the vendor please update the plugin, if no update is available you can try and replace in line 4 in `plugins/system/uikit3/uikit3.php` the `JPlugin` to `\Joomla\CMS\Plugin\CMSPlugin`. Maybe this is enough for the plugin to work again.

I'm closing this because it's not an core issue.

**Closed as completed by HLeithner** 2023-11-28 10:13 UTC
Labels: No Code Attached Yet

**Comment by FrankReisenhofer** [comment] 2023-11-28 12:07
@HLeithner Thanks for your quick reply and help. I addressed the issue to the developer.
