### ISSUE TITLE
last letter truncated in the titles of search results

### ISSUE THREAD

**Issue by galamarco** [joomla/joomla-cms#36718] opened 2022-01-17 13:10 UTC
### Steps to reproduce the issue
- Please write some articles with a log and small title.
- Go to search an article and you will see a title of article with last letter truncated.
![This is an image](https://toniasquino.scossaditerremoto.it/images/articoli/202201/screenshot_31.png)

I thought it was a template bug and I [reported the problem to Yootheme](https://yootheme.com/support/question/150198 "test") but the support verified that even with the Cassiopea template the code output is incorrect and for this reason the title is shown without the last letter.
I try to change template in Cassiopea and the problm is the same. 

The problem does not happen with short titles

### Expected result
Titles in search results must be integers

### Actual result
The last character of the search results title with a long title is deleted

### System information (as much as possible)
Joomla 4.0.5
PHP 7.4.27
db mysql 10.3.32-MariaDB-cll-lve

### Additional comments
You che see the problem on [this page](https://toniasquino.scossaditerremoto.it/index.php?searchword=1995&searchphrase=all&Itemid=113&option=com_search "this page") where first result have a title without the last character.
If you open the article you will see that the last word has an extra letter.

**Comment by richard67** [comment] 2022-01-17 18:20
@galamarco Is this issue about the (old) search component, com_search? Or is it for the new Smart Search, com_finder?

If it is for com_search, it could be a duplicate of #34724 , and the issue should be opened in the search repository here: https://github.com/joomla-extensions/search/issues .

**Comment by brianteeman** [comment] 2022-01-17 18:25
based on the url it is the old com_search

**Comment by richard67** [comment] 2022-01-17 18:30
> based on the url it is the old com_search

Thanks, I saw it now, too.

**Comment by Quy** [comment] 2022-01-17 19:51
Thank you for the report. Please post your issue to https://github.com/joomla-extensions/search/issues.

**Closed as completed by Quy** 2022-01-17 19:51 UTC
Labels: No Code Attached Yet

**Comment by woluweb** [comment] 2022-11-18 12:50
a fix has been proposed on https://github.com/zzella/search/commit/f11bd86c29504bd9f9268f4fa2c4161559f77cbd
I have tested it successfully :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36718">issues.joomla.org/tracker/joomla-cms/36718</a>.</sub>

**Comment by woluweb** [comment] 2022-11-18 12:59
cfr https://github.com/joomla-extensions/search/issues/7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36718">issues.joomla.org/tracker/joomla-cms/36718</a>.</sub>
