### ISSUE TITLE
Menu-item type alias doesn't respect levels

### ISSUE THREAD

**Issue by Pinkeltje** [joomla/joomla-cms#43938] opened 2024-08-17 10:59 UTC
### Steps to reproduce the issue
Create a menu like this:

![2024-08-17 Screenshot 542](https://github.com/user-attachments/assets/f5817961-21ab-4d73-be6d-9fc63633079b)

Create a menu module like this:

![2024-08-17 Screenshot 543](https://github.com/user-attachments/assets/962fa92a-7298-4a91-8304-754568426ecd)

![2024-08-17 Screenshot 544](https://github.com/user-attachments/assets/db2e66b6-c832-4013-a41b-94ddc7e0b919)

### Expected result

Menu visible on all pages

### Actual result

Menu only visible on homepage

![2024-08-17 Screenshot 545](https://github.com/user-attachments/assets/30a5cf26-2a57-4c56-8741-6e0b026076c2)

Menu invisible on page created with menu-item alias

![2024-08-17 Screenshot 546](https://github.com/user-attachments/assets/2d6ecdef-e30e-46f0-a2ed-61bbb79a24ab)

Tested with multiple aliasses, i.e. Community Builder, Kunena so it's not related to the extension used.

### System information (as much as possible)
Joomla 5.1.2
Default Cassiopeia
PHP 8.2.12

**Comment by brianteeman** [comment] 2024-08-17 15:52
You cannot assign a module to an alias menu item. Only the modules assigned to the  real menu item will be displayed so I would say this is this intended behaviour.

**Comment by Pinkeltje** [comment] 2024-08-18 06:42
Can be closed

**Closed as completed** 2024-08-18 06:43 UTC
Labels: No Code Attached Yet
