### ISSUE TITLE
[4.0] - Questionable 'Itemid' on article links in Category List & Blog views

### ISSUE THREAD

**Issue by pjdevries** [joomla/joomla-cms#36608] opened 2022-01-08 14:50 UTC
### Problem identified

When having more than one multi-item menu-item (`Category Blog` or `Category List`) for the same category, the links to the single items (title, edit, ...) have a questionable `Itemid`, in my humble opinion. From what I can see, it's always the `Itemid` of the first menu-item matching the category. However, I would think it would have the `Itemid` of the active menu-item for the multi item view. To me it makes sense that, when navigating from a multi item view to a single item view, the active menu-item for the single item view would be that of the multi item view one navigated away from. 

### Proposed solution

Add the id of the active menu-item for the multi item view as the `Itemid` in the links for single item views.

### Open questions

Is there a logical explanation for the way it is implemented now? Am I missing the obvious?

**Comment by brianteeman** [comment] 2022-01-08 17:18
It's pretty much always been this way. I _think_ the logic is that however you get to the article the same itemid is used and therefore the same page layout etc. Your proposal would result in the same article being displayed with two different itemid AND how would something like search present the article

**Comment by pjdevries** [comment] 2022-01-09 13:56
Thanx for the input @brianteeman. Yes you are right, my proposal _would_ result in an article possibly being displayed with different `Itemid`'s and possibly with different layout's as a result. But if that is the intention, then it's o.k., isn't it? 

I think you're also right in that it has always been this way, because I ran into it before. It may well even date back to Mambo times :) Let me clarify why I'm bringing it up now. I'm not sure since when, but we have the possibility for front end content management these days. I spent some time trying this myself, to see if it is usable "out of the box". My initial conclusion is: it isn't. 
- One of the problems I ran into, which has been fixed since then, was not being able to create new articles as a regular registered user. 
- Another problem was not being able to filter articles on logged in user. Logged in users would see everybody's articles, although they would only be able to edit their own, provided the ACL is configured correctly. I was already working on a plugin, adding a custom menu-item tab including a filter switch to remedy this and was happy to discover that you created PR #36555 to solve this issue in Joomla! 4.2 for a slightly different, but similar reason. 
- A third problem I ran into, is the one I'm addressing with this issue. Assume a site with a category blog or list view for a certain category. Assume the articles in that category can be managed by registered users with the proper permissions. It makes sense to have two different menu-items pointing at the same category, but with different settings (think of your PR). As it is now, this results in the problem outlined above.

So what do you, and others, think? Do you agree it's useful to try to think of a solution for this issue? True, I haven't figured out how to handle search results, but that's no reason not to address the issue, don't you think?

**Comment by brianteeman** [comment] 2022-01-09 14:06
I wrote a plugin that will fix that for you https://extensions.joomla.org/extension/authoring-a-content/content-submission/clean-edit/

**Comment by pjdevries** [comment] 2022-01-10 09:28
@brianteeman I don't see how that plugin solves the issue I'm trying to draw attention to. I guess my explanation is not clear enough, but I don't know how to improve that. Furthermore, if nobody else experiences this as an issue, I'll let it be and solve it on a project by project basis.

**Comment by Hackwar** [comment] 2022-02-02 22:55
I can guarantee you, that we will not implement what you want in Joomla in the core. We would get literally thousands of people complaining about duplicate content (regardless of "duplicate content" even existing or not) and we would make a giant step backwards in our development. I also don't see how editing an article would be dependent on the menu item. Either you have edit rights to an asset or you don't. It shouldn't depend on the display configuration.

All that said, you can get the behavior you want by writing a plugin which replaces the rules in the content router with your own behavior.

**Comment by richard67** [comment] 2022-02-02 23:00
Closing as expected behavior due to reasons stated in the previous comment.

**Closed as completed by richard67** 2022-02-02 23:00 UTC
Labels: No Code Attached Yet
