### ISSUE TITLE
 Date of birth shows everywhere 

### ISSUE THREAD

**Issue by emilushi** [joomla/joomla-cms#7332] opened 2015-07-03 16:18 UTC
In both 3.3 and 3.4 there is a small bug i saw on the contact page.

I you fill date of birth of a user in profile settings and then show the profile to contact page by connecting a user to a single contact (where the display settigns is set Tabs) the date of birth will show everywhere.
Below you can find the screenshot:
![joomla](https://cloud.githubusercontent.com/assets/3394343/8502414/eeb384bc-21af-11e5-9087-11e0a7d4b7bd.png)

**Comment by infograf768** [comment] 2015-07-03 16:54
Confirmed here

**Comment by infograf768** [comment] 2015-07-03 17:13
same issue with sliders

**Comment by infograf768** [comment] 2015-07-04 06:15
Looks like it is at least partly related to https://github.com/joomla/joomla-cms/pull/4103

**Comment by Bakual** [comment] 2015-07-04 08:29
Can you try https://github.com/joomla/joomla-cms/pull/7340

For me, the whole profile is also wrong aligned afterwards.
Even when I remove the date of birth. So it's not related and a different issue.

**Comment by zero-24** [comment] 2015-07-05 17:47
Closing as we have a fix by @Bakual here: #7340

**Closed by zero-24** 2015-07-05 17:47 UTC
Labels: No Code Attached Yet
