### ISSUE TITLE
Calendar form field doesn't allow inputting seconds

### ISSUE THREAD

**Issue by paul-muckypuddle** [joomla/joomla-cms#16084] opened 2017-05-17 14:26 UTC
### Steps to reproduce the issue

1. Open the Article Edit screen, click the Publishing tab
2. Click the Start Publishing field and select any date
3. Click outside the field to close the calendar window
4. Click the Start Publishing field and manually change the '00' seconds to any other valid value
5. Click outside the field - the seconds part of the value reverts to '00'

### Expected result

Calendar field retains keyed in seconds value

### Actual result

Calendar field shows '00' as the seconds value

### System information (as much as possible)

Joomla 3.7.1
PHP 5.6

### Additional comments

See video at http://support-media.muckypuddle.me/kVJy

**Comment by brianteeman** [comment] 2017-05-19 17:21
I can confirm this. The same is also true if you just select the today value where you will then be shown a value with seconds that is reset to 0 on save
![aa](https://cloud.githubusercontent.com/assets/1296369/26259217/e300bd42-3cbf-11e7-9689-c2c680cbbdad.gif)

**Comment by dgt41** [comment] 2017-05-19 17:22
it's by design, or we need one more dropdown there

**Comment by brianteeman** [comment] 2017-05-19 17:24
how can it be by design to show a value of 18:20:36 in the field and then change that field to 18:20:00 when it is saved

**Comment by brianteeman** [comment] 2017-05-19 17:25
pretty sure neither of us are asking for a dropdown to select the seconds. just that the entered value is not changed

**Comment by bertmert** [comment] 2017-05-19 17:26
> or we need one more dropdown there

If that's the only way: Yes, please. I want to see the time as saved in the database (where the seconds are correctly saved (like entered)).

**Comment by paul-muckypuddle** [comment] 2017-05-19 18:03
What @brianteeman said: not fussed about a dropdown, must be able to retain an entered value

**Comment by joomla-ua** [comment] 2017-06-29 04:47
I confirm the bug in Joomla 3.7.2!!!

**Comment by infograf768** [comment] 2017-06-29 09:22
In fact, the correct seconds value is duely saved in the db.
Therefore it is just a matter of displaying it correctly in the calendar field.

**Comment by joomla-ua** [comment] 2017-06-29 10:13
Calendar field ignore seconds.

**Comment by brainforgeUK** [comment] 2017-07-01 21:07
In article edit correct seconds flashes up when item saved, then returns :00
Adding my own component to otherwise clean Joomla 3.7.2 installation - chasing what I thought was my bug and then found same thing happens in article edit! Argh!!

**Comment by joomla-ua** [comment] 2017-07-04 13:50
Joomla 3.7.3 bug not fixed :(

**Comment by denysdesign** [comment] 2017-07-26 12:06
Perfect!
Joomla! 3.7.4 bug not fixed :-(

Guys, the error affects the time of publication! For news sites this is very critical!!!

**Comment by paul-muckypuddle** [comment] 2017-08-23 10:49
Not seen any movement on this for a couple of months, can anyone point me in the right direction of where the issue may lie in the JS? Happy to have a crack with some pointers.

**Comment by dgrammatiko** [comment] 2017-08-23 11:05
> can anyone point me in the right direction of where the issue may lie in the JS

Yes. I can do that. So the problem is that we have dropdowns for hours, minutes and am/pm, therefore we don't really listening for the changes for the seconds. There might be a way to set the seconds if user typed it, but I haven't looked at it, you are more than welcome to fiddle with the code: https://github.com/joomla/joomla-cms/blob/e2d77287432c8dc0af8fbe3e1a3925ed59e0096f/media/system/js/fields/calendar.js#L169-L195

**Comment by paul-muckypuddle** [comment] 2017-08-23 11:23
Thanks @dgt41, will try to have a look this evening.

**Comment by paul-muckypuddle** [comment] 2017-08-24 14:57
Plopped a fix up (PR #17703), only after spending 90 minutes researching another datetime issue I 'found' that's already been fixed! So it goes.

**Comment by brianteeman** [comment] 2017-08-24 15:16
Closed as we have a PR

**Closed by brianteeman** 2017-08-24 15:16 UTC
Labels: No Code Attached Yet
