### ISSUE TITLE
Link title not working on featured article

### ISSUE THREAD

**Issue by hfittipaldi** [joomla/joomla-cms#27016] opened 2019-11-07 19:34 UTC
### Steps to reproduce the issue
Set "Linked Titles" on general options to "no"
Set "Linked Titles" on a featured article option to "yes"

### Expected result
Feateured article with link on its title

### Actual result
No link at all

### System information (as much as possible)

Setting | Value
-- | --
PHP Built On | Windows NT MAQUINA03 10.0 build 18362 (Windows 10) AMD64
Database Type | mysql
Database Version | 5.7.21
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.3.9
Web Server | Apache/2.4.33 (Win64) OpenSSL/1.1.0g PHP/7.1.32
WebServer to PHP Interface | apache2handler
Joomla! Version | Joomla! 3.9.13 Stable [ Amani ] 5-November-2019 15:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36

**Comment by mohitm15** [comment] 2019-11-13 12:37
@hfittipaldi Can you mention which file you're talking about?

**Comment by infograf768** [comment] 2019-11-16 08:05
Once the article parameter is set to Yes, the parameter "Use Article Settings" has to be set in the featured menu item.

<img width="451" alt="Screen Shot 2019-11-16 at 09 23 05" src="https://user-images.githubusercontent.com/869724/68990386-c2fe2f00-0852-11ea-9ad5-79a1814aec85.png">

Closing as not a bug

**Closed as completed** 2019-11-16 08:24 UTC
Labels: No Code Attached Yet
