### ISSUE TITLE
Please add "autocomplete" tag for registration/login/com_contact page

### ISSUE THREAD

**Issue by sanek4life** [joomla/joomla-cms#6998] opened 2015-05-20 16:58 UTC
#### Steps to reproduce the issue
Front pages:

Joomla - login page
Joomla - registation page
Joomla - com_contact page

#### Expected result
 < input type="email" name="customerEmail" autocomplete="email"/ > 
![registration page](https://images-blogger-opensocial.googleusercontent.com/gadgets/proxy?url=http%3A%2F%2F1.bp.blogspot.com%2F-QmdGI-Jc8Xg%2FVQaXQMMdH8I%2FAAAAAAAAAyw%2FK8tEbb_iXfw%2Fs1600%2Fautocomplete.png&container=blogger&gadget=a&rewriteMime=image%2F* "registration page")

#### Actual result
< input name="jform[email2]" class="validate-email required" id="jform_email2" value="" size="30" required="required" aria-required="true" type="email" >

#### System information (as much as possible)
Joomla 3.4.1

#### Additional comments
A lot of websites rely on forms for important goals completion, such as completing a transaction on a shopping site or registering on a news site. For many users, online forms mean repeatedly typing common information like their names, emails, phone numbers or addresses, on different sites across the web. In addition to being tedious, this task is also error-prone, which can lead many users to abandon the flow entirely. In a world where users browse the internet using their mobile devices more than their laptops or desktops, having forms that are easy and quick to fill out is crucial! Three years ago, we announced the support for a new “autocomplete” attribute in Chrome, to make form-filling faster, easier and smarter. Now, Chrome fully supports the "autocomplete" attribute for form fields according to the current WHATWG HTML Standard. This allows webmasters and web developers to label input element fields with common data types, such as ‘name’ or ‘street-address’, without changing the user interface or the backend. Numerous webmasters have increased the rate of form completions on their sites by marking up their forms for auto-completion.

For example, marking up an email address field on a form to allow auto-completion would look like this (with a full sample form available):

< input type="email" name="customerEmail" autocomplete="email"/ >

Making websites friendly and easy to browse for users on mobile devices is very important. We hope to see many forms marked up with the “autocomplete” attribute in the future. For more information, you can check out our specifications about Label and name inputs in Web Fundamentals. And as usual, if you have any questions, please post in our Webmasters Help Forums.

[http://googlewebmastercentral.blogspot.ru/2015/03/helping-users-fill-out-online-forms.html](http://googlewebmastercentral.blogspot.ru/2015/03/helping-users-fill-out-online-forms.html "http://googlewebmastercentral.blogspot.ru/2015/03/helping-users-fill-out-online-forms.html")

**Comment by brianteeman** [comment] 2015-05-25 14:50
To be clear the problem is NOT that autocomplete is not enabled, it is enabled by default.
The problem is that the value for name does not match the expected value for an autocompletion<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6998">issues.joomla.org/joomla-cms/6998</a>.</sub>

**Comment by brianteeman** [comment] 2015-06-19 11:52
I just tested this again
Register Page - autocomplete working perfectly on the name field in Google Chrome
Contact form- autocomplete not working

I tried the suggestion of adding `autocomplete="name"` to the contact form but it had no effect<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6998">issues.joomla.org/joomla-cms/6998</a>.</sub>

**Comment by sanek4life** [comment] 2015-06-21 12:53
this is new standart for web, for Html forms! If before you never write your name at this field, probably you no have effect. This new parameter for situation, when you meet another site with this "autocomplete" field.

browser Google Chrome full support this "autocomplete" parameter, and probably another browsers add support or support now this parameter.

Autocomplete increase user registrations, for example - on smartphones people no like write again and again his name or e-mail, at registration forms on websites...

If you sell something via e-commerce, this "Autocomplete" fields can increase sales in your e-shop.

please, just add this "autocomplete" parameter.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6998">issues.joomla.org/joomla-cms/6998</a>.</sub>

**Comment by sudo-web** [comment] 2015-10-26 10:55
Hey folks,
How do I get a (this) pull request merged to an existing issue?
In this case to [#6998](http://issues.joomla.org/tracker/joomla-cms/6998)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6998">issues.joomla.org/joomla-cms/6998</a>.</sub>

**Comment by zero-24** [comment] 2015-10-26 10:58
Closing as we have a Pull Request that implement it here: https://github.com/joomla/joomla-cms/pull/8149 Thanks to @sudo-web

**Closed by zero-24** 2015-10-26 10:58 UTC
Labels: No Code Attached Yet
