### ISSUE TITLE
Toggle button for menu assignment in template manager not working in 3.4.0

### ISSUE THREAD

**Issue by Wtimbr** [joomla/joomla-cms#6342] opened 2015-03-06 15:23 UTC
#### Steps to reproduce the issue
(i)Update to 3.4.0
(ii) Go to Template Manager > Select a Template
(iii) move to tab 3 "menus Assignment"
(iv) press Toggle Selection
->> nothing happens

#### Expected result
Selection boxes should be selected or unselected on toggle event. Now one has to manually select everything.

#### Actual result
Firebug gives following error report:

ReferenceError: $$ is not defined
http://localhost/samplesite/administrator/index.php?option=com_templates&view=style&layout=edit&id=12/html/body/div[2]/section/div/div/form/div[2]/div/div[3]/div[2]/ul/li[2]/div/button onclick 
Toggle Selection				
Line 1

#### System information (as much as possible)
PHP Built On 	Windows NT DESKTOP 6.1 build 7601 (Windows 7 Home Premium Edition Service Pack 1) AMD64
Database Version 	5.6.17
Database Collation 	latin1_swedish_ci
PHP Version 	5.5.12
Web Server 	Apache/2.4.9 (Win64) PHP/5.5.12
WebServer to PHP Interface 	apache2handler
Joomla! Version 	Joomla! 3.4.0 Stable [ Ember ] 24-February-2015 23:00 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:36.0) Gecko/20100101 Firefox/36.0

**Comment by waader** [comment] 2015-03-06 15:27
@Wtimbr Can you test with latest staging. I could not reproduce this problem.

**Comment by Wtimbr** [comment] 2015-03-06 15:30
@waader  Sure, can you lend me a hand where to find it?

**Comment by waader** [comment] 2015-03-06 15:31
https://github.com/joomla/joomla-cms
On the right you have the "Download ZIP" - Button.

**Comment by losedk** [comment] 2015-03-06 15:38
The issue was fixed in #6276

**Comment by Wtimbr** [comment] 2015-03-06 15:41
@waader Issue seems resolved in stager version. Cant reproduce it<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6342">issues.joomla.org/joomla-cms/6342</a>.</sub>

**Comment by brianteeman** [comment] 2015-03-07 09:24
Closing as fixed elsewhere<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6342">issues.joomla.org/joomla-cms/6342</a>.</sub>

**Closed** 2015-03-07 09:24 UTC
