### ISSUE TITLE
Custom Joomla template overide not working in J4 and J5

### ISSUE THREAD

**Issue by radik10** [joomla/joomla-cms#44569] opened 2024-12-03 03:15 UTC
### Steps to reproduce the issue
Create some new override for, e.g. for features articles. Call it "custom1" and create it in "/templates/cassiopeia/html/com_content/featured" as "custom1.php", "custom1_item.php", "custom1_links.php"
This "custom1" style is not available for menu - see attached image. In Joomla 3 this kind of override worked correctly.

### Expected result
Have for menu (featured articles) 2 design options to choose from

### Actual result
There is only 1 option (default, from Joomla install)

### System information (as much as possible)
Joomla 4.4.9 and 5.2.2, PHP 8.1

### Additional comments
![not working template overide](http://joomla.r-art.sk/Joomla-4-and-5---missing-custom-templates-(overide)-for-menu.png "")
![not working template overide](http://joomla.r-art.sk/Joomla-4-and-5---missing-custom-templates-(overide)-for-menu-2.png "")

**Comment by Hackwar** [comment] 2024-12-03 05:54
For this to show up, you have to also create a layout XML. This was also the case in joomla 3. This is not a bug and thus I'm closing this.

**Closed as completed by Hackwar** 2024-12-03 05:54 UTC
Labels: No Code Attached Yet

**Comment by radik10** [comment] 2024-12-04 04:19
Creating XML file is not helpful, even if you copy and rename some from original Joomla XML files. Sorry, but did you try to create some override (with different name) before closing this? Please try to create some for featured and blog articles in J4 and J5. Thank you. Joomla doesn't see newly created template overrides. If it worked in the past, it doesn't  mean that it works now.
And in Joomla docs (https://docs.joomla.org/J4.x:Template_Layouts) is no clear explanation how to use template overrides with different names. Especially how to create XML - its content.
Thank you for the answer.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44569">issues.joomla.org/tracker/joomla-cms/44569</a>.</sub>
