### ISSUE TITLE
Deprecated strftime

### ISSUE THREAD

**Issue by fontanil** [joomla/joomla-cms#44087] opened 2024-09-16 09:37 UTC
### Steps to reproduce the issue

Joomla! 5.2.0-beta3-dev PHP 8.1 open a page using the calendar (here in Localise for J5)

### Expected result

no message

### Actual result
 
Deprecated: Function strftime() is deprecated in /home/www/developpement/joaktree2/libraries/src/Form/Field/CalendarField.php on line 323
![Capture d’écran 2024-09-16 113639](https://github.com/user-attachments/assets/5ece8ba4-678c-44b6-8e0b-b097943f41b5)

### System information (as much as possible)

Joomla! 5.2.0-beta3-dev PHP 8.1.2 9

### Additional comments
The message is not displayed on a 5.1.4 website, PHP 8.2.5

**Comment by fontanil** [comment] 2024-09-16 09:38
Code
            if ($this->filterFormat) {
                $date  = \DateTimeImmutable::createFromFormat('U', strtotime($value));
                $value = $date->format($this->filterFormat);
            } else {
                $value = strftime($this->format, strtotime($value));
            }

**Comment by Hackwar** [comment] 2024-09-16 09:39
This is a duplicate of #43947.

**Closed as completed by Hackwar** 2024-09-16 09:39 UTC
Labels: No Code Attached Yet

**Comment by fontanil** [comment] 2024-09-16 09:43
Sorry, I didn't see it.
