### ISSUE TITLE
Article intro and fulltext images missing

### ISSUE THREAD

**Issue by kristopulos** [joomla/joomla-cms#37317] opened 2022-03-19 12:50 UTC
### Steps to reproduce the issue
I used postman with link:
api/v1/content/articles/1 and returned JSON was without images (both intro and fulltext).

Also alt, caption an class are missing.

In normal joomla site both appeared. Strange thing is when i use link like this: 
api/v1/content/articles?page[limit]=4 it returns both images (intro and fulltext) with alt, caption and class.

### Expected result
I should return json with images (intro and full)

### Actual result
No data in json attributes->data->images field

### System information (as much as possible)
Joomla 4.1
PHP 8, MySql 5.7.19

**Comment by alikon** [comment] 2022-03-21 07:04
Unable to reproduce 
![image](https://user-images.githubusercontent.com/181681/159217323-773a271a-54c3-4e6d-95bf-cbebfca6e6c3.png)

**Comment by Quy** [comment] 2022-05-06 22:57
Closing as non-reproducible.

**Closed as completed by Quy** 2022-05-06 22:57 UTC
Labels: No Code Attached Yet, Information Required, Webservices
