### ISSUE TITLE
Issue in System - Page Cache in redirect

### ISSUE THREAD

**Issue by ribo72** [joomla/joomla-cms#15593] opened 2017-04-26 14:31 UTC
### Steps to reproduce the issue
Issue in System - Page Cache in redirect
Please check this problem and test it. https://forum.joomla.org/viewtopic.php?f=710&t=949609#p3471238

**Comment by PhilETaylor** [comment] 2017-04-26 14:54
duplicate of #15579 ???

**Comment by AlexRed** [comment] 2017-04-26 14:56
I can confirm the problem.
Also I need to disable the plugin "System - Page Cache" in some my multilanguage site to avoid white page<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15593">issues.joomla.org/tracker/joomla-cms/15593</a>.</sub>

**Comment by ribo72** [comment] 2017-04-26 15:23
It s similar issue with redirect from/ to/lang, The only difference is the redirect from http to https with force https and when you use http it is not redirect but it give blank page when you use "System - Page Cache" . When you disable "System - Page Cache" you avoid white page too and http redirect properly to htpps.

**Comment by AlexRed** [comment] 2017-04-26 15:38
yes, also for me same problem with System - Page Cache in multilanguage site in https

**Comment by HamThorne** [comment] 2017-04-26 16:39
I do not have a multi-language site but I do redirect to https via .htaccess.

I was getting the same blank page (confirmed in both Firefox Developer and Chrome) until I turned off System Cache. Now the pages display fine. 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15593">issues.joomla.org/tracker/joomla-cms/15593</a>.</sub>

**Comment by philippegm** [comment] 2017-04-26 18:37
I have the same problem with upgrade to 3.7 with multi langage website
I have trying with a new 3.7 site with 2 langages and the problem is same when I activate System - Page Cache
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15593">issues.joomla.org/tracker/joomla-cms/15593</a>.</sub>

**Comment by joeforjoomla** [comment] 2017-04-26 19:27
I've also found that now an empty page cache file is always created even if there are no contents to cache at all. On the second reload of a page this causes a blank page.

**Comment by dvdp** [comment] 2017-04-27 12:57
+1 ....

**Comment by kimler01** [comment] 2017-04-28 08:51
similar issue with redirect from http to https with force https and when you use http it is not redirect anymore. I switched off the page cache and its working fine...

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15593">issues.joomla.org/tracker/joomla-cms/15593</a>.</sub>

**Comment by PhilETaylor** [comment] 2017-04-28 09:07
Also had this from a client:

> Post 3.7.0 upgrade, I am wondering if anyone else has noticed sites that will load the home page featured articles on the first load, but when refreshed the "featured articles" do not display.
> 
> Turning off caching in the system prefs certainly cures the issue, but it's probably not a real fix.
> 
> I can't see any reports of it in issue tracking at Joomla, or other searches.
> 
> I'm not sure it happens on all sites, but I have spotted it on 3 of mine so far.
> 
> Any ideas, or others you know who have seen this behaviour?
>

**Comment by sn3ka** [comment] 2017-04-29 02:09
Same issue here: Blank page but only for the home page, any other url is working fine.
Looks like the cache is messing up with the language redirection based on the browser language detection.

I kept the plugin enabled but I just added the Main home in the Exclude Menu Items text area.

**Comment by franz-wohlkoenig** [comment] 2017-04-29 08:19
closed as related to #15674<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15593">issues.joomla.org/tracker/joomla-cms/15593</a>.</sub>

**Closed by franz-wohlkoenig** 2017-04-29 08:19 UTC
Labels: No Code Attached Yet
