### ISSUE TITLE
joomla backend get slow with a lot of menu items

### ISSUE THREAD

**Issue by benshaty** [joomla/joomla-cms#10997] opened 2016-07-03 11:24 UTC
like my error that have been fiuxed ( #9516)
i have the same query error with the modules.
is it posibe to find the query and fix it with DISTINCT?

in the menus.php  the fix that you sent me (line150~):
$query = $db->getQuery(true)
/*->select('a.id AS value,  cancel this line*/  
->select('DISTINCT(a.id) AS value,   // add this line
a.title AS text, 
a.alias, 
a.level, 
a.menutype, 
a.type, 
a.published, 
a.template_style_id, 
a.checked_out, 
a.language, 
a.lft')
->from('#__menu AS a')
->join('LEFT', $db->quoteName('#__menu') . ' AS b ON a.lft > b.lft AND a.rgt < b.rgt');

**Comment by roland-d** [comment] 2016-07-03 11:27
@benshaty Please test #8863 perhaps that solves your issue.

**Comment by benshaty** [comment] 2016-07-03 11:33
it`s not that.
there is that query that i posted that uses:
->select('a.id AS value,
instead we changed it to:
select('DISTINCT(a.id) AS value,

and then the system started to work perfectly.
you can check this ( #9516) and see all the problem.
thanks in advance

**Comment by ggppdk** [comment] 2016-07-03 12:40
@benshaty 
i am confused by the title of this thread,

- you say "menus" in the title and then in your description you say about "modules"
- in the title you say "slow" and in the text you say "query ERROR", but there is not error

(ok i think everybody understand you mean performance)

----

Now which exactly view do you mean ?
- the modules listing in the modules manager

----

**That the query can not remove group by**
- because it has some aggregate calculation that calculates the number of assigned pages, **which is also a sortable column**
- to optimized it and remove **group by** we would need to **remove the "Pages" column**  ... or make it non-sortable and then break the query into 2 queries


There is another query that might be worth optmizing (may give some benefits in various views) and which can be optimized:

@alikon 

1 more case of unneeded group by that can be replaced with DISTINCT:
- no aggregate function is used
- the group by clause is the same as select

https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_modules/helpers/modules.php#L189-L195

**Comment by benshaty** [comment] 2016-07-03 15:23
in my site i have more then 3000~ menu items. 
and more then 1000~ modules.
in march i had the same performance issue.
the SQL query that sort the menu items in "Menu Assignment" was fixed with this code:
    ->select('DISTINCT(a.id) AS value,
and then all the template and menus workd fast. (#9689)
now i have the same issue with the modules manager.

**Comment by prathumwan** [comment] 2016-08-16 06:32
Hi, news about this issue?
Think I got the same problem. 10000~ menu items per language, 1000~ modules per language. Why is that query on menu table running before showing modules overview in backend modules manager? What information is taken from menu table that isn't availible from modules table? Is it just for search tools / select page option?

![joomla queries menu table before showing admin view modules](https://cloud.githubusercontent.com/assets/16284417/17689901/291ea9c2-63b5-11e6-97f7-e0636200707c.PNG)

**Comment by ggppdk** [comment] 2016-08-16 09:37
@benshaty 
@prathumwan 

Please test #11627

The effect that you see is due to the creation of search filter "Select page"
- which in this case retrieves all menu items

Similar performance issue will have pages that retrieve ALL menu items using the menus helper class

**Comment by prathumwan** [comment] 2016-08-17 09:36
Ok will test #11627 

I tried to figure out why the effects of this query are so extreme. I changed slightly this and that and found that the join to the language table is the cause of the performance drop.

The change from LEFT JOIN to a simple JOIN reduced the duration for about 10000 menu items from 70 seconds to 0.35 seconds! Ok, so far so good (I thought). The simple JOIN of course did not deliver the records which had an no corresponding language field in the menu table. I added the missing records by hand to language table, and the result is amazing: LEFT JOIN and simple JOIN deliver the identical result now, but the LEFT JOIN is still at the **same slow speed!**

![mysql menu query left join to languages](https://cloud.githubusercontent.com/assets/16284417/17731596/206cc7da-6498-11e6-9491-46fb7b4c3cec.png)

I don't know what reason cause this behavior, but good to know.

**Comment by ggppdk** [comment] 2016-08-17 09:49
so you have not tested #11627 yet ?

about
> The change from LEFT JOIN to a simple JOIN reduced the duration for about 10000 menu items from 70 seconds to 0.35 seconds

if you (incorrectly) filter out many records (in some way) then of course you will less records to participate in the query and get performance improvement, that LEFT JOIN needs to be LEFT

please test #11627

**Comment by prathumwan** [comment] 2016-08-17 10:26
ok great, just finished.
#11627 works well, can't see any difference.

The speed is back. Amazingly if you switch of the language plugin the speed is back also. There must be a MySQL issue with this double left join query usage.

![mysql menu query left join with 10997](https://cloud.githubusercontent.com/assets/16284417/17733180/92a0a6e4-649f-11e6-915c-d2bea2f72d6a.png)

**Comment by ggppdk** [comment] 2016-08-18 07:52
@benshaty 

Please test PR #11627

and also see comment (about which **backend screens get a benefit**):
https://github.com/joomla/joomla-cms/pull/11627#issuecomment-240649371

Also this PR for menu item edit form
https://github.com/joomla/joomla-cms/pull/11628

**Comment by andrepereiradasilva** [comment] 2016-08-21 21:47
can we close this sicne we have two PR?

**Comment by brianteeman** [comment] 2016-08-21 22:16
Closed as requested

**Closed by brianteeman** 2016-08-21 22:16 UTC
Labels: No Code Attached Yet
