### ISSUE TITLE
Don't need a comma in shortcode "+ module"

### ISSUE THREAD

**Issue by viocassel** [joomla/joomla-cms#9116] opened 2016-02-13 13:35 UTC
When in the editor, use the button "**+ module**", then at the end of the shortcode appears not need a comma.
![qdgs3oz](https://cloud.githubusercontent.com/assets/3341562/13027834/1fb9d7f8-d26f-11e5-883a-2f456057b732.png)

**Comment by joomline** [comment] 2016-02-13 13:40
Yes, I also have this bug.

**Comment by dgt41** [comment] 2016-02-13 13:48
@viocassel this is NOT a bug:
For the load position:
```php
	/**
	 * Loads and renders the module
	 *
	 * @param   string  $position  The position assigned to the module
	 * @param   string  $style     The style assigned to the module
	 *
	 * @return  mixed
	 *
	 * @since   1.6
	 */
	protected function _load($position, $style = 'none')
```

and for the load module:
```php
	/**
	 * This is always going to get the first instance of the module type unless
	 * there is a title.
	 *
	 * @param   string  $module  The module title
	 * @param   string  $title   The title of the module
	 * @param   string  $style   The style of the module
	 *
	 * @return  mixed
	 *
	 * @since   1.6
	 */
	protected function _loadmod($module, $title, $style = 'none')
```
or both here:
https://github.com/joomla/joomla-cms/blob/staging/plugins/content/loadmodule/loadmodule.php#L122-L163

So both functions can accept one more parameter, style. When empty a null is passed. This was by design NOT a bug

**Comment by Ilya-Zhulin** [comment] 2016-02-13 14:27
Ho-ho-ho! The code should consider if next parameter exists, isn't it? Functions which you show allow to keep last parameter empty. Why do you argue?

**Comment by dgt41** [comment] 2016-02-13 14:33
@Ilya-Zhulin to put it simple if empty the value will be none: `protected function _loadmod($module, $title, $style = 'none')`, so why spent processing power to take that coma off? It doesn't make any sense...

**Comment by Ilya-Zhulin** [comment] 2016-02-13 14:57
No problem! If it is hard to devs, we can delete it by self.. Every time, time by time... And.. somewhere in Joomla! 3.5.9 somebody put this if condition...
If you mean that style is neccessary - put 'none' it to code automatically if the style field is empty. To finish frase bu comma - that really doesn't make sense

**Comment by dgt41** [comment] 2016-02-13 15:37
If you are willing to make that change here is the code:
```javascript

		moduleIns = function(type, name) {
if (jQuery("#extra_class").val().length)
{
extraVal =  "," + jQuery("#extra_class").val();
} else {
extraVal =  "";
}
			parent.window.jInsertEditorText("{loadmodule " + type + "," + name + "," + jQuery("#extra_class").val() + "}", "' . $editor . '");
			parent.window.jModalClose();
		}
		modulePosIns = function(position) {
if (jQuery("#extra_class").val().length)
{
extraVal =  "," + jQuery("#extra_class").val();
} else {
extraVal =  "";
}
			parent.window.jInsertEditorText("{loadposition " + position +  extraVal  + "}", "' . $editor . '");
			parent.window.jModalClose();
		}

```

should replace these lines: https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_modules/views/modules/tmpl/modal.php#L49-L57

**Comment by Ilya-Zhulin** [comment] 2016-02-13 15:43
Yes, we did it. This post was to remind developers to change it in release.

**Comment by dgt41** [comment] 2016-02-13 15:44
@Ilya-Zhulin I don't see the PR

**Comment by Ilya-Zhulin** [comment] 2016-02-13 15:52
ah.. You need PR... Sorry, this id **for** devs, not **from** devs. Somewhere I learn JS enough to make pull request for this

**Comment by richard67** [comment] 2016-02-14 13:38
@viocassel @joomline @Ilya-Zhulin If you find some time, please test this PR [https://issues.joomla.org/tracker/joomla-cms/9117](https://issues.joomla.org/tracker/joomla-cms/9117 "https://issues.joomla.org/tracker/joomla-cms/9117") made by @dgt41 and set the test result in the issue tracker.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9116">issues.joomla.org/joomla-cms/9116</a>.</sub>

**Comment by richard67** [comment] 2016-02-14 13:39
@viocassel ... and if all works you can close this issue here :smiley: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9116">issues.joomla.org/joomla-cms/9116</a>.</sub>

**Comment by viocassel** [comment] 2016-02-14 17:21
I have tested this. Everything works fine :smile:

**Closed** 2016-02-14 17:21 UTC
