### ISSUE TITLE
Multilingual Installation Broken on current staging

### ISSUE THREAD

**Issue by drmenzelit** [joomla/joomla-cms#13734] opened 2017-01-24 11:57 UTC
Do a clean install of current staging with the following options

Sample Data None
Install Language packages - French
Activate the multilingual feature - Yes
Install localised content - Yes
Enable the language code plugin - Yes
Go to /administrator and confirm that the login is offering you english and french

Login and clickon the Multilingual Status on the bottom left

You will see this error This site is set as a multilingual site. One or more of the Default Home pages for the published Content languages are missing although the Language Filter plugin is enabled AND/OR one or more Language Switcher modules are published.

Go to Extensions->Languages->Content Languages You will just see English as a content Language - you should see english and french

**Comment by infograf768** [comment] 2017-01-24 13:28
I can't reproduce your issue.
Please check that the French language pack has been installed.
If not, try to install it from Extensions->Manage-> Install Languages.
If it installs OK. I suggest you test again with a brand new staging.

**Comment by coolcat-creations** [comment] 2017-01-24 14:23
Can´t reproduce either... sorry

**Comment by ot2sen** [comment] 2017-01-24 15:39
Couldn't reproduce at first either. But my language in installer did switch
to the default browser 'Danish'.
A new try selecting en-GB in installer and then issue occur after
installation using same steps. Could it be the English version of
the installer having issues?

On Tue, Jan 24, 2017 at 3:23 PM, coolcat-creations <notifications@github.com

**Comment by ot2sen** [comment] 2017-01-24 16:13
With more people seeing the issue in English it is something worth looking into.
Video documented here:
https://www.youtube.com/watch?v=x0AsCQaeng0

**Comment by infograf768** [comment] 2017-01-24 19:42
my test was done using en-GB

**Comment by ot2sen** [comment] 2017-01-24 20:23
yeah, there are mixed results on when this happens.
Could this occur when the language server return unavailable?

Did 3 different tests da-DK, da-DK and en-GB.
1. Language server failed to respond and an error was shown at the language install page. (when using the back arrow at that page you are not given the option to try again. It considers the install as finalised)
2. Everything went fine, couldn´t reproduce the issue.
3. All steps went fine - but - issue reproduced getting error notice in multilingual status, and missing french in content languages.

Wondering if a temporary lack of response from the language server could initiate this issue, and not return an error?

**Comment by infograf768** [comment] 2017-01-25 13:23
if no response form language server, the pack would not be installed. that's why i asked if it was installed or not when the content language was not created.
can you check that?

**Comment by ot2sen** [comment] 2017-01-25 13:38
Pack was installed and can be seen in admin and in the filesystem. Content language missing.
The en-GB folder has 262 files and fr-FR has 217, but I guess that is just difference of 36x vs 37.
![25-01-2017_en_and_fr_installed_butbroken](https://cloud.githubusercontent.com/assets/790445/22292499/dd11a1e8-e30b-11e6-83e9-c81f4eaf60c0.png)

**Comment by infograf768** [comment] 2017-02-04 06:41
Looked at our code.
If a packs is installed but the content language is not published, we do throw an error:
INSTL_DEFAULTLANGUAGE_COULD_NOT_CREATE_CONTENT_LANGUAGE="Joomla was unable to automatically create the %s content language."
Did any of you got the error?

For that, the content language has to first be created. In any case it does not look like it is server dependent.
The method to create it is in installation/model/language.php addLanguage() . No specific error is displayed here.

**Comment by franz-wohlkoenig** [comment] 2017-02-05 09:49
Installed today Multilingual Site (4 Lang.) without Issues.
#### Test on:
Joomla! 3.7.0-latest staging
macOS Sierra, 10.12.3
Firefox 50.1.0
PHP 7.0.4
MySQLi 5.5.53-0

**Comment by franz-wohlkoenig** [comment] 2017-04-05 14:19
closed as "unconfirmed Report".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13734">issues.joomla.org/tracker/joomla-cms/13734</a>.</sub>

**Closed by franz-wohlkoenig** 2017-04-05 14:19 UTC
Labels: No Code Attached Yet
