### ISSUE TITLE
I have created an article but when I push "Save" appears white page, seems that it doesn't charge.and the article not is saved. 

### ISSUE THREAD

**Issue by Apayan** [joomla/joomla-cms#7573] opened 2015-07-28 10:53 UTC
#### Steps to reproduce the issue
I have created an article but when I push "Save" appears white page, seems that it doesn't charge.and the article not is saved.
I have change the user permision with CHMOD to 7777 but the problem persist.

**Comment by Bakual** [comment] 2015-07-28 11:22
White page means a fatal error occured. You need to enable the error reporting to see what happend. Maybe also check the PHP error log.
It may be caused by a faulty plugin.

Please use the forum (http://forum.joomla.org/) if you need more assistance figuring out the root of your issue. It isn't an issue coming from the core CMS. Closing because of that.

**Closed by Bakual** 2015-07-28 11:22 UTC
Labels: No Code Attached Yet

**Comment by Apayan** [comment] 2015-07-28 12:04
Thanks, I will try it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7573">issues.joomla.org/joomla-cms/7573</a>.</sub>
