### ISSUE TITLE
[3.9.4RC] Invalid controller on clicking username with debug language

### ISSUE THREAD

**Issue by roland-d** [joomla/joomla-cms#24164] opened 2019-03-11 18:56 UTC
### Steps to reproduce the issue
1. Enable Debug language in Global Configuration
2. Enable the `Action Log - Joomla` plugin
3. Go to Global Configuration
4. Click Save & close
5. Go to User -> User Action Log
6. Notice a line like:
`**User ??admin?? changed settings of the application configuration** `
7. Click on the `??admin??` username
8. Error page is shown:
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/359377/54149855-7185e080-4437-11e9-963a-d1340b4902e3.png">

### Expected result
The user edit page is shown

### Actual result
An error page is shown

### System information (as much as possible)
Clean Joomla 3.9.4 RC installation
PHP 7.2.15
Apache 2.4.38

**Comment by alikon** [comment] 2019-03-11 19:02
confirm

**Comment by HLeithner** [comment] 2019-03-11 19:03
Thats more or less expected behavior because the link is also translated.

The question is why is it needed...

**Comment by infograf768** [comment] 2019-03-12 09:37
I have a possible patch for that
```
diff --git a/administrator/components/com_actionlogs/helpers/actionlogs.php b/administrator/components/com_actionlogs/helpers/actionlogs.php
index 71221c4..a7f9a07 100644
--- a/administrator/components/com_actionlogs/helpers/actionlogs.php
+++ b/administrator/components/com_actionlogs/helpers/actionlogs.php
@@ -209,5 +209,14 @@
 			}
 
-			$message = str_replace('{' . $key . '}', Text::_($value), $message);
+			if (strpos($value, 'JOOMLA_TYPE') || strpos($value, 'JOOMLA_APPLICATION'))
+			{
+				$value = Text::_($value);
+			}
+			else
+			{
+				$value = $value;
+			}
+
+			$message = str_replace('{' . $key . '}', $value, $message);
 		}
 ```
To get:
<img width="558" alt="Screen Shot 2019-03-12 at 10 35 00" src="https://user-images.githubusercontent.com/869724/54189670-91a6b580-44b2-11e9-9c1c-50197b069c79.png">

@HLeithner 
Shall I make a PR?

**Comment by HLeithner** [comment] 2019-03-12 13:02
@infograf768 no, in my opinion its not a bug, the string get translated and marked as translated with **.

thx for the report I'm closing this.

**Closed as completed by HLeithner** 2019-03-12 13:02 UTC
Labels: No Code Attached Yet

**Comment by roland-d** [comment] 2019-03-12 13:04
@HLeithner Why doesn't it happen then in the userlisting?

**Comment by HLeithner** [comment] 2019-03-12 13:06
which userlisting do you mean?

**Comment by infograf768** [comment] 2019-03-12 16:40
Well, my proposed patch works fine because it prevents the links from being passed through `Text::_`
The issue is that the code does not use sprintf.

Without patch, when debug lang is on, the links are of the type
`<a href="??http://localhost:8888/installmulti/trunkgitnew/administrator/index.php?option=com_users&amp;task=user.edit&amp;id=800??">??admin??</a>`

which evidently breaks them.

<img width="720" alt="Screen Shot 2019-03-12 at 17 37 01" src="https://user-images.githubusercontent.com/869724/54218409-cedc6900-44ed-11e9-8039-dc97c609f5b0.png">

**Comment by infograf768** [comment] 2019-03-12 16:50
@roland-d 
in the user manager as elsewhere in core we use `Text::sprintf` with variables for this kind of links.

**Comment by roland-d** [comment] 2019-03-12 17:16
@infograf768 Thank you for the explanation, that does explain why it works in the User Manager. A patch to fix the broken link is welcome if you ask me. Having a known broken page isn't very nice :)

**Comment by alikon** [comment] 2019-03-12 18:25
> A patch to fix the broken link is welcome if you ask me.

for me too, but don't want to waste @infograf768 time for a pr with 0 chances to be considered

**Comment by HLeithner** [comment] 2019-03-12 18:27
every PR will be considered but the draft seams wrong to me.

**Comment by roland-d** [comment] 2019-03-12 18:30
@HLeithner Can you elaborate on what is wrong with it rather than just stating it is wrong.

**Comment by alikon** [comment] 2019-03-12 18:35
i would prefer to discuss this argument when  even a draft PR will be submitted and not based on an copy&paste  snippet ... btw, this is not a high priority issue imo

**Comment by HLeithner** [comment] 2019-03-12 18:38
@roland-d sorry I talked to jean-marie directly that's the reason I didn't mentioned it here.

I think strpos on a hardcoded string seams wrong, can a plugin also add a url here? strpos() without === should be checked twice. Also if it is really needed to translate the url or only use the sprintf option.

So yes if jean-marie writes a PR we can discuss about it but to be honest we have so many thing to fix in j4 that a wrong url in a debug screen shouldn't be the first priority.

**Comment by alikon** [comment] 2019-03-12 18:45
got your point .... and make sense to me, even in a j4 perspective only :smiley: 
lack of resources is the real issue

**Comment by infograf768** [comment] 2019-03-13 05:59
Found the correct solution. Making patch now.

**Comment by infograf768** [comment] 2019-03-13 06:20
Please test
https://github.com/joomla/joomla-cms/pull/24178
