### ISSUE TITLE
syntax error, unexpected '||' (T_BOOLEAN_OR) com_joomlaupdate

### ISSUE THREAD

**Issue by Stuartemk** [joomla/joomla-cms#26587] opened 2019-10-14 08:47 UTC
### What needs to be fixed
Update 3.9.12 to 3.10
Check again to update say to test update 3.10 to 4
Fatal error: An error has occurred.
0 syntax error, unexpected '||' (T_BOOLEAN_OR)

/public_html/administrator/components/com_joomlaupdate/views/default/tmpl/default.php:67

### Why this should be fixed
Error say in line 67 but its in line 65

### How would you fix it
			<?php if (!isset($this->updateInfo['object']->downloadurl->_data)

Change to

			<?php if ((!isset($this->updateInfo['object']->downloadurl->_data)

**Comment by richard67** [comment] 2019-10-14 10:11
The 3.10 branch is not up to date compared to 3.9.x = staging. Normally, after each new release of 3.9.x, the staging branch is merged into the 3.10 branch. This has not happened since last release 3.9.12, and so you can't update from 3.9.12 to 3.10. I am sure @wilsonge or @HLeithner can confirm that.

**Comment by richard67** [comment] 2019-10-14 10:17
So I would recommend to close this issue as expected behavior. @HLeithner please confirm.

**Comment by Stuartemk** [comment] 2019-10-14 10:22
> So I would recommend to close this issue as expected behavior. @HLeithner please confirm.

@richard67 

Thanks for your comment. Regardless, what I reported is a bug, regardless of whether it is not an update, and that the 3.10 full version is installed. The error is there in the com_joomlaupdate component, being a simple repair I found the solution and that's why I shared it, although the solution It is simple does not mean that the error is not serious because for a single parenthesis, simply and simply the component does not work without that solution.

**Comment by HLeithner** [comment] 2019-10-14 10:31
@richard67 I merged 3.9.12 into 3.10.0 -> https://github.com/joomla/joomla-cms/commits/3.10-dev

**Comment by richard67** [comment] 2019-10-14 10:38
@HLeithner I see, but file `/public_html/administrator/components/com_joomlaupdate/views/default/tmpl/default.php`in staging does not contain the error @Stuartemk mentioned above. Could you check if there has been made a change in staging which is missing yet in 3.10? Or has there been made a change in 3.10 later which will not be changed by a merge of staging into 3.10? Maybe @zero-24 could have a look on it, too, because he recently fixed the Joomla Update version checks?

Sure you are right that it is a bug in 3.10, @Stuartemk , I only want to clarify if it has been already fixed or not in staging.

**Comment by Stuartemk** [comment] 2019-10-14 11:12
> @HLeithner I see, but file `/public_html/administrator/components/com_joomlaupdate/views/default/tmpl/default.php`in staging does not contain the error @Stuartemk mentioned above. Could you check if there has been made a change in staging which is missing yet in 3.10? Or has there been made a change in 3.10 later which will not be changed by a merge of staging into 3.10? Maybe @zero-24 could have a look on it, too, because he recently fixed the Joomla Update version checks?
> 
> Sure you are right that it is a bug in 3.10, @Stuartemk , I only want to clarify if it has been already fixed or not in staging.

Confirmed.
I just downloaded Joomla_3.10.0-dev-Development-Full_Package.zip

I did the clean installation and just opening joomlaupdate there is the error.

Please, before dismissing a bug report and considering it as an expected behavior, just look at the code so that you notice the error, especially you lower the mood of volunteers by dismissing the reports right and left. Regards.

**Comment by HLeithner** [comment] 2019-10-14 11:13
There was a merge conflict, it's possible that I broke it. I will check the file and create a pr later.

**Comment by richard67** [comment] 2019-10-14 11:25
@Stuartemk Sorry for misunderstanding. I did not want to dismiss, I just wanted to clarify. You know, I am only a volunteer contributor like you are, not a maintainer, so I only can say my opinion in a discussion, and like every human being I can also be wrong. That's why I've pinged a maintainer to have a look on it. But now it seems it will be fixed soon, thanks for reporting the issue.

**Comment by zero-24** [comment] 2019-10-15 17:46
Please see: https://github.com/joomla/joomla-cms/pull/26603 cc @HLeithner closing here as there is the mention patch,

**Closed as completed by zero-24** 2019-10-15 17:46 UTC
Labels: No Code Attached Yet
