### ISSUE TITLE
Unable to open 2nd tier sub folders in Images folder

### ISSUE THREAD

**Issue by GinzaVualzong** [joomla/joomla-cms#16223] opened 2017-05-23 19:33 UTC
### Steps to reproduce the issue
if you open images folder either from New Article using Tiny MCE or Media Manager, one cannot open the 2nd tier folder or sub folder. Eg. Images/Folder01/Folder02: you cannot open folder02

### Expected result
the 2nd tier sub folders should open with its content. 

### Actual result
By opening the 2nd tier sub folder, it will take you to the main images folder. 
Eg Images/Folder01/Folder02 is the directory. If you try to open Folder02, it will take you to the main folder - Images. 

### System information (as much as possible)
I have noticed this from J3.7.1 onward. It doesn't happened in previous releases.

**Comment by sozzled** [comment] 2017-05-23 21:09
Unable to reproduce the fault either by using **Media Manager** or *TinyMCE* (e.g. /images/sampledata/parks)

Works as expected.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16223">issues.joomla.org/tracker/joomla-cms/16223</a>.</sub>

**Comment by GinzaVualzong** [comment] 2017-05-23 21:15
This must be local issue again. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16223">issues.joomla.org/tracker/joomla-cms/16223</a>.</sub>

**Comment by brianteeman** [comment] 2017-05-23 21:24
i am going to close this at this time as it would appear to be a problem with your specific install. If you need any further assistance then please use the forum https://forum.joomla.org

**Closed by brianteeman** 2017-05-23 21:24 UTC
Labels: No Code Attached Yet
