### ISSUE TITLE
PHP fatal error continuous reporting

### ISSUE THREAD

**Issue by aaleksanyants** [joomla/joomla-cms#7366] opened 2015-07-07 10:31 UTC
In my server's error_log file I see similar error reports like the one given below:

[07-Jul-2015 03:06:20 America/Chicago] PHP Fatal error:  Call to a member function getItemTags() on a non-object in /home/[username]/public_html/[joomla_dir]/templates/beez3/html/com_weblinks/category/default_items.php on line 132

**Comment by smz** [comment] 2015-07-07 12:27
confirmed: a remnant Weblinks... must be eliminated.
A PR is on its way...

**Comment by mbabker** [comment] 2015-07-07 12:37
Just for reference (before too much time is spent on a PR), it was decided that weblinks stuff that was "owned" by the template would stay in the repo as it's a template specific thing (overrides, CSS rules, etc.).  So, the fix here needs to be ensuring the overrides are working correctly with the current weblinks code, and if for some reason that code is getting triggered without using the weblinks component, figure out WTF is calling it and fix that problem too.

**Comment by smz** [comment] 2015-07-07 12:41
@mbabker Got it!
Actually I was wondering the same: the override should not be called at all if the component is not installed in the first place, so I'm starting to think that something has changed in the "enucleated" component that reander the (old) override incompatible.

@aaleksanyants can you confirm that you have Weblinks installed in your site?

**Comment by smz** [comment] 2015-07-07 13:00
... and in my test site (Weblinks **not* installed) I'm not seeing that error for none of the menu items I have configured (*not exhaustive but fairly complete*)

@aaleksanyants can you figure out for which menu item you are getting that error?

**Comment by aaleksanyants** [comment] 2015-07-07 13:18
Unfortunately I cannot provide any additional information because I did not get it online by myself, I just provided the content of my error_log file...

**Comment by smz** [comment] 2015-07-07 13:21
... but do you have Weblinks installed in your site?

**Comment by aaleksanyants** [comment] 2015-07-07 13:31
Yes I have, it remains there from v. 2.5...

**Comment by aaleksanyants** [comment] 2015-07-07 13:32
moreover, its language files are still included in current joomla version...

**Comment by smz** [comment] 2015-07-07 13:33
OK, thanks! I will try to figure out if there is something wrong in current implementation...

@mbabker Michael, am I correct assuming that a 2.5 installation upgraded to current code has weblinks automatically upgraded to latest code?

**Comment by zero-24** [comment] 2015-07-07 14:12
>@mbabker Michael, am I correct assuming that a 2.5 installation upgraded to current code has weblinks automatically upgraded to latest code?

@smz no atm it is absulutly broken. On of the issues you can find here: https://github.com/joomla-extensions/weblinks/issues/25

There is a RC Version (https://github.com/joomla-extensions/weblinks/releases/tag/3.4.1-rc2) but no final package packaged to fix it.

**Comment by smz** [comment] 2015-07-07 15:24
Thanks, @zero-24 !

So, if I'm getting it right...
- The behavior described in this issue is *somehow* expected because with Joomla! update we deliver an updated Beez override which is not compatible with old Weblinks code.

- Automatic Weblinks update is not performed

- **In theory** it should be updated via "Extension Manager" -> "Update", but...

- Code delivered that way is neither compatible, and...

- New compatible code is only available by **manually** installing the RC version from https://github.com/joomla-extensions/weblinks/releases/tag/3.4.1-rc2

Is that the "state of things"?

**Comment by zero-24** [comment] 2015-07-07 19:59
>Is that the "state of things"?

Yes the "state of things" but not expected. If the PLT release a new final version we use the normal updater for weblinks too.

>The behavior described in this issue is somehow expected because with Joomla! update we deliver an updated Beez override which is not compatible with old Weblinks code.

I'm not sure as the line is also there in the new repo:
https://github.com/joomla-extensions/weblinks/blob/master/src/com_weblinks/site/views/category/tmpl/default_items.php#L131

But If you can reproduce this please try to install the RC Version and test again. If there is still the same issue we need to fix it in the new repo to include it with the next final version.

For the beez overrides I'm not sure how the PLT try to handle it.

The last state i remember we will not ship it with the extension. So if the issue is at the beez overrides only we need to fix the CMS if it is in the weblinks code than there ;)

**Comment by smz** [comment] 2015-07-07 21:14
OK, I'll try and see if I can reproduce this...

Now, if I'm not mistaken, this should be something happening between Joomla! 3.0 (*first version with Beez3*) and 3.4.0 (*first version without Weblinks*).

Joomla 2.5 should not be involved as at the time we had Beez5 and Beez_20, right?

**Comment by smz** [comment] 2015-07-08 01:11
First test results:

##### Testing methodology
- Started using a Joomla 3.3.6 test site (PHP 5.4.39, error_reporting = E_ALL)
- Configured 2 Web Links in a single category, both tagged with the same tag.
- Created two Weblink menu items: one for the specific Weblinks category and one for all categories
- Added a Weblink module on the home page
- At a second time I upgraded Joomla to 3.4.3
- Finally I upgraded com_weblinks to version 3.4.1-rc2

##### Testing results:
- No problems with J! 3.3.6
- No problems after upgrading to J! 3.4.3
- No problems after upgrading to Weblinks 3.4.1-rc2

##### Additional notes
The involved line has been added with commit https://github.com/joomla/joomla-cms/commit/b4f4143e46204751a4608efa38500ca3636b4129 on 24 Jun 2013 and thus introduced with Joomla! 3.1.2

At this point I really don't know what else I can do for trying to trigger that error...

**Comment by smz** [comment] 2015-07-08 01:22
I'm just wondering what @aaleksanyants update path has been... Directly from 2.5 to 3.4.3 and then switched to the Beez3 template? I'm afraid I should test that too...  :unamused:

**Comment by smz** [comment] 2015-07-08 02:30
Guys, it's getting harder and harder...

- Installed Joomla 2.5.28
- Got a message stating that support for that version is terminated. I know, :cry: 
- Weblinks are working: time to upgrade to 3.4.3
- Gone to Joomla Update
- No update is proposed... curious... :open_mouth: 
- Got an enlightenment :sunglasses: and switched to STS as upgrade path
- Here it is, 3.4.3! :smile: (*strange that it is proposed as an STS...* :confused:)
- Clicked on update... nothing happens: just a "*Please wait while your files are installed*" message or something similar... :disappointed: 
- Let's try through Extensions Manager...
- Crap, nope, file too big: 9420863 bytes and I have a max of 8M :weary: 
- Increase max POST size to 16M (*luckily I can...*)
- Retried and got this: "*There was an error uploading this file to the server*" :angry: 
- Put the file in /tmp by hand and retried
- Got an error stating that the file does not contain a valid XML. :astonished: 
- Unzipped the file in /tmp
- Retried.
- Halleluya, it seems to work! :sweat_smile: 
- "Maximum execution time of 60 seconds exceeded in \libraries\joomla\database\database\mysqli.php on line 382  :cold_sweat: 
- **Site screwed up** :scream:
- Throwing the towel :raised_hands:

**Comment by infograf768** [comment] 2015-07-08 06:06
> moreover, its language files are still included in current joomla version...

That is normal as there is no way for now to get specific weblinks language packs per language. Therefore it was decided to let these in current core (so they are included in core language packs) although they may not be used by people not installing weblinks.

**Comment by brianteeman** [comment] 2016-03-10 14:20
I am going to close this at this time. Pretty certain that it is the result of having an outdated version of weblinks and that component has now been updated and would show up in the list if extensions to update. It can always be reopened if thats not the case.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7366">issues.joomla.org/joomla-cms/7366</a>.</sub>

**Closed by brianteeman** 2016-03-10 14:20 UTC
Labels: No Code Attached Yet
