### ISSUE TITLE
[4.0b7] bizarre calendar field display

### ISSUE THREAD

**Issue by Magnytu2** [joomla/joomla-cms#32409] opened 2021-02-13 15:40 UTC
Whether in Edge or Firefox, the display of the calendar field during editing is capricious.

![Capture d’écran 2021-02-13 à 16 36 59](https://user-images.githubusercontent.com/26197929/107854115-1a09ff80-6e1a-11eb-8154-a632b56e949e.png)

**Comment by brianteeman** [comment] 2021-02-13 18:04
This is caused by the three column layout which will hopefully be removed.

**Comment by Quy** [comment] 2021-02-13 18:26
PR #31810

**Comment by chmst** [comment] 2021-02-16 21:46
Please test #32441.  
Closed as we have a PR

**Comment by brianteeman** [comment] 2021-02-16 22:13
@chmst 32441 is unrelated

**Comment by chmst** [comment] 2021-02-17 09:49
thx, you are right.

**Comment by Quy** [comment] 2021-02-17 20:29
Fixed in PR #32422. Thanks for reporting.

**Closed as completed by Quy** 2021-02-17 20:29 UTC
Labels: No Code Attached Yet
