### ISSUE TITLE
Error type not displayed on menu items

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#6761] opened 2015-04-13 18:19 UTC
When your creating a menu item ( single contact in my case ) and you leave the "contact" empty, and hit save you will get the single word "ERROR" in pink.
![capture](https://cloud.githubusercontent.com/assets/1850089/7122205/74345708-e1df-11e4-9b5b-328e1d6ef3e0.JPG)
if you happen to be on another tab ( say linktype ) when you hit save, you will have no indication as to what the problem is nor what you need to do about it.

to test: create new menu item of type "single contact", go to "link type tab" change show title to no, hit save.
you'll get the error... nothing is indicative of where the error might be.

**Comment by brianteeman** [comment] 2015-04-14 10:11
Closing as a duplicate of #6654 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6761">issues.joomla.org/joomla-cms/6761</a>.</sub>

**Closed** 2015-04-14 10:11 UTC
Labels: No Code Attached Yet
