### ISSUE TITLE
New router: Article routing broken for multilanguage contents

### ISSUE THREAD

**Issue by joeforjoomla** [joomla/joomla-cms#13633] opened 2017-01-18 10:37 UTC
### Steps to reproduce the issue
Install a brand new and clean Joomla 3.7 alpha package.
Install for example 4 languages during the installation process including sample contents for the 4 languages.
Verify that everything works fine for article links.
Enable modern routing
Check that articles with a specific language assigned have still valid links.

### Expected result

Link as: http://joomla37dev/index.php/de/12-kategorie-de-de/9-beitrag-de-de
Link to the category: http://joomla37dev/index.php/de/12-kategorie-de-de

### Actual result

Link is: http://joomla37dev/index.php/de/?view=article&id=9:beitrag-de-de
Link to the category: http://joomla37dev/index.php/de/?view=category&id=12

### System information (as much as possible)

![37routing](https://cloud.githubusercontent.com/assets/17835460/22060761/73a9d480-dd72-11e6-8157-3dae82922224.PNG)

**Comment by AlexRed** [comment] 2017-01-19 14:43
by sure "SEO Settings" in Global Configuration are enabled<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13633">issues.joomla.org/tracker/joomla-cms/13633</a>.</sub>

**Comment by joeforjoomla** [comment] 2017-01-20 13:40
Yes 'SEO settings' are enabled, the problem is due to the new router.... indeed not a great work as i've already said. When installing a brand new Joomla with multilanguage, the main language home page menu item is for a category blog, but all other languages have home page menu item for featured articles. This causes the new router failing, because as everybody know it won't resolve anymore on the featured article view. So the multilanguage installation should be fixed at least to create all menu items poiting to a category to make happy even the new router, otherwise it's tricky for a normal user.

**Comment by franz-wohlkoenig** [comment] 2017-02-05 16:59
Issue stay on latest 3.7-staging. Installed a clean Mulilang-Site, 4 Lang.

With `Modern` also with `Remove IDs from URLs` URLs look like @joeforjoomla wrote.

**Comment by Hackwar** [comment] 2017-03-04 11:04
This is the same issue as in #13978 and should therefor be closed.

**Comment by infograf768** [comment] 2017-03-04 11:23
> When installing a brand new Joomla with multilanguage, the main language home page menu item is for a category blog, but all other languages have home page menu item for featured articles. 

Wrong. All home pages are set to Featured articles.
It may be a good idea indeed to change this to use a Category blog, or, even better, add a hidden Category type menu item in the same menus.
Not sure we can do that in time for RC1

**Comment by franz-wohlkoenig** [comment] 2017-04-05 14:51
closed cause Decision of #14919 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13633">issues.joomla.org/tracker/joomla-cms/13633</a>.</sub>

**Comment by brianteeman** [comment] 2017-04-05 14:53
please dont close this. its a valid issue and will need to be resolved for 3.8

**Comment by infograf768** [comment] 2017-04-06 10:13
Changed title to reflect in which conditions the issue may appear<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13633">issues.joomla.org/tracker/joomla-cms/13633</a>.</sub>

**Comment by Hackwar** [comment] 2017-04-06 11:11
Could someone explain to me again what the issue is here? Because if you are referring to the original poster, then this is expected behavior. Featured Articles is not a menu item that can lead to a category view or an article view. (And no, the new router is not supposed to be 100% backwards compatible. Just because the old router somehow worked, doesn't mean that it was right that way.) If you mean that we should change the default menu item type of newly created languages, then please drop the whole (new) routing stuff out of this discussion and describe it as that accordingly.

**Comment by mbabker** [comment] 2017-05-31 09:56
Can someone describe the issue here?  Myself and another person have tested upgrades of live multilingual sites to 3.8 and the routing in all cases matched expectations and we did not see broken routing.

**Comment by infograf768** [comment] 2017-06-02 09:42
@mbabker 
All depends on your expectations.
What do you get as urls when you install joomla with default multilingual?

**Comment by mbabker** [comment] 2017-06-02 09:56
I haven't done a test scenario through a new installation.  So I don't know what it's generating before and after.  I do know based on other test scenarios with production multilingual sites, we weren't seeing issues.  So I'm still not sure if this is a router issue or the way the data is constructed by the install app right now, hence the reason I'm asking to make sure I'm clear what the issue is so I know what we need to direct resources to.

**Comment by infograf768** [comment] 2017-06-02 12:12
I will asap post details after testing with 3.8.
The issue, as stated in posts above, was at that time that, if one did not have a specific category menu item (even hidden), we were getting weird results when linking to an item belonging to such category and also to the category itself.
Test with a featured menu item as home and NO menu item to any category or categories. Enable links on articles titles as well as category in the Details part. Click on these links.

**Comment by mbabker** [comment] 2017-06-02 13:28
Thank you.

**Comment by brianteeman** [comment] 2017-08-18 21:49
Closed as this is now in #16496

**Closed by brianteeman** 2017-08-18 21:49 UTC
Labels: No Code Attached Yet
