### ISSUE TITLE
Keepalive doesn't work when in Debug-Mode

### ISSUE THREAD

**Issue by mtomzig** [joomla/joomla-cms#40426] opened 2023-04-19 15:13 UTC
### Steps to reproduce the issue
When a form with keepalive is opend in frontend or backend (eg. plugin form) and the system debug is active the session ends some timer after the lifetime set in the config.

It doesn't matter if the debug mode is activated before or after the form was openend. But as soon as debug mode is activated and I wait some time (and do no other things with the Joomla instance) the session will be destroyed.

In the server log I see that the AJAX-Calls for keeping the session alive were coming periodically, but the session will be destroyed nonetheless.

I haven't found the exact timing yet. But it seams that the session is destroyed about 30 minutes if the session lifetime is set to 15 minutes.

No other window/tab was opend but the page with the form itself.

### Expected result
The session should be still alive after the session lifetime is over.

### Actual result
The session was destroyed and the form can't be used anymore because there is a new session token.

### System information (as much as possible)
Tested on Unix based server (QNAP-NAS)
with Joomla 4.2.9 and 4.3.0 with MariaDB in PDO or MySQLi-Mode
Firefox-Browser

**Comment by brianteeman** [comment] 2023-09-01 11:13
I am unable to replicate this

**Comment by Hackwar** [comment] 2024-04-02 11:52
I just tested this as well and can also not replicate this. I fear this is an issue in your setup and not a bug in Joomla. Since we also didn't get any similar reports, I'm closing this issue. Thank you for reporting.

**Closed as completed by Hackwar** 2024-04-02 11:52 UTC
Labels: No Code Attached Yet, bug
