### ISSUE TITLE
com_joomlapudate passing wrong adapter to preflight and postflight scripts

### ISSUE THREAD

**Issue by prh47bridge** [joomla/joomla-cms#39148] opened 2022-11-03 23:55 UTC
I don't know if this is limited to my system or a more general problem.

When I updatee an extension with a preflight or postflight script, the updatee will fail complaining that the script has been passed a LibraryAdapter instead of a PackageAdapter. However, if I install the updatee by downloading the package and installing it in the normal way (i.e. as if it was a fresh install rather than an update), everything works fine.

I have two such extensions - Akeeba Backup and JCH Optimize, both of which experience this problem. The developer of one of these extensions suggested that this was a database issue - that the extension was recorded in the database as a library instead of as a package. However, I have checked the database and both are showing as packages. Neither includes a library.

Extension updates worked fine for these extensions when I initially upgraded to Joomla 4. They have stopped working at some point since then.

I am running Joomla 4.2.4 using PHP 8.1.12.

Any assistance with resolving this issue would be much appreciated.

**Comment by richard67** [comment] 2022-11-04 07:25
@nikosdion Is this the same issue as #38956 ?

**Comment by nikosdion** [comment] 2022-11-04 07:47
@richard67 Yup! This is the same problem. In my issue I have explained why it happens, at least to the point where I could reproduce it. As @prh47bridge said and I had also explained in my ticket, this only happens when you try to update a package _together with a non-package extension_ in the same request.

This must've been happening for years but nobody noticed because there was no type hinting in the installation scripts. Even if someone implements `\Joomla\CMS\Installer\InstallerScriptInterface` they will not see the problem as it only type hints InstallerAdapter. When a developer type hints the accurate adapter type, e.g. `\Joomla\CMS\Installer\Adapter\PackageAdapter`, the problem becomes evident. Eventually this _will_ happen and people will complain that Joomla does not let them update any extension.

**Comment by richard67** [comment] 2022-11-04 07:59
Closing as duplicate report. See #38956 . Thanks for reporting.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39148">issues.joomla.org/tracker/joomla-cms/39148</a>.</sub>

**Closed as completed by richard67** 2022-11-04 07:59 UTC
Labels: No Code Attached Yet
