### ISSUE TITLE
[4.0] Flex kills long page titles 

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#16296] opened 2017-05-28 16:19 UTC
A picture is worth a thousand words
![screen shot 2017-05-28 at 18 16 17](https://cloud.githubusercontent.com/assets/869724/26530266/17d4d512-43d2-11e7-99e9-66359ca4c3f4.png)

**Comment by brianteeman** [comment] 2017-05-28 16:38
closed as a duplicate of #15683

**Closed by brianteeman** 2017-05-28 16:38 UTC
Labels: No Code Attached Yet
