### ISSUE TITLE
[4b6] ROOT appears in breadcrumbs

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#31925] opened 2021-01-08 22:43 UTC
### Steps to reproduce the issue

Install Joomla 4 beta 6 

Create an article called test, make it featured so it shows up on the home page. 

Save that article to create it. 

Edit that article, then in TinyMCE go to CMS Content -> Article and select the same "test" article. save the article.

Go to the frontend and see this

<img width="608" alt="Screenshot 2021-01-08 at 22 41 57" src="https://user-images.githubusercontent.com/400092/104072234-b9781900-5202-11eb-8fcb-f54fbacb503b.png">

(ok I added an image too - you don't need that)

Click test (next to the image in my screenshot)

### Expected result

Breadcrumbs of 

`Home / Uncategorised / test`

### Actual result

`Home / ROOT / Uncategorised / test`

(url is http://0.0.0.0/index.php?view=article&id=1:test&catid=2) 

<img width="505" alt="Screenshot 2021-01-08 at 22 43 07" src="https://user-images.githubusercontent.com/400092/104072301-e5939a00-5202-11eb-8e9a-76cf3be9068c.png">

**Comment by chmst** [comment] 2021-01-08 23:17
Seems that this is your localhost. On windows and online, breadcrumbs are comme il faut. 
Url: index.php?view=article&amp;id=1&amp;catid=2

Or do you have special settings? This is a new installation without any configuration.

![breadcrumbs](https://user-images.githubusercontent.com/1035262/104074546-b3893480-5210-11eb-818b-cce4b507ae18.PNG)

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31925">issues.joomla.org/tracker/joomla-cms/31925</a>.</sub>

**Comment by PhilETaylor** [comment] 2021-01-08 23:29
How strange. 

I have just deleted everything and started from scratch. 

I get the same. ROOT is in the breadcrumb.

PHP 8.x to be sure.

**Comment by PhilETaylor** [comment] 2021-01-08 23:31
Maybe a PHP 8 issue
Maybe related to https://github.com/joomla/joomla-cms/issues/31473

**Comment by chmst** [comment] 2021-01-08 23:45
Yes, confirmed. I had tested in php 7.6 and have the same issue as you with php8

**Comment by bembelimen** [comment] 2021-01-13 04:49
The problem is here: https://github.com/joomla/joomla-cms/blob/4.0-dev/components/com_content/src/View/Article/HtmlView.php#L304-L309 I think, sadly I have currently no PHP 8 to confirm, so probably @chmst could you check if the "if" statement is broken in PHP 8 (or why "ROOT" is not excluded with ```$category->id > 1```?

**Comment by chmst** [comment] 2021-01-13 13:01
Please test #32027

**Comment by richard67** [comment] 2021-01-13 13:08
Closing as having a pull request. Please test #32027 . Thanks in advance.

**Closed as completed by richard67** 2021-01-13 13:08 UTC
Labels: No Code Attached Yet, PHP 8.x
