### ISSUE TITLE
Stupidly slow saving with 1100 usergroups

### ISSUE THREAD

**Issue by tonypartridge** [joomla/joomla-cms#19804] opened 2018-03-01 09:57 UTC
So a client has a site which has 1,100 usergroups. This is used for course management they restrict access to courses based on user groups and they have 3-6 users groups per client of theirs. 

this means when saving a page it takes around 3-4minutes to finish processing in the browser whilst it does it's user group checks from what I can gather, Javascript is not my forte. This makes managing the site very hard and tiresome. 

Can we disable validating usergroups via JS? Maybe as a global config option? Since we can handle this serverside and surely we already do as a fall back should anyone has JS disabled as an example.

**Comment by GCLW** [comment] 2018-03-02 14:30
I'm guessing it is more because you have a category with 100,000+ articles in it and when you save a new article every single one of those articles has to get its "ordering" field incremented by 1 so the new article will display first.

**Comment by tonypartridge** [comment] 2018-03-02 14:32
Not’s not articles we only have 5. Same with the Global configuration, stupidly slow.

**Comment by ggppdk** [comment] 2018-03-03 06:08
@tonypartridge 

hhmm
there is no validation for ACL rule fields (you have  12 of every usergroup)
the above is because the 'select' field of the rules have 'novalidate' CSS class (i also remember discussion when this was suggested and added)

so it must be something else

I tested global config using 1020 groups,

after global config form is saved
-- the page reloads

at that point (but also when i first open global config form) i see very slow page load time (browser trying to execute JS and render HTML) 

is the above the issue for you ?

**Comment by ggppdk** [comment] 2018-03-03 06:17
To create about 1000 usergroups with some nesting try adding a new task inside groups controller
`/administrator/components/com_users/controllers/groups.php`

then open URL:
`/administrator/index.php?option=com_users&task=groups.creategroups`

```php
public function creategroups()
{
	$db = JFactory::getDbo();
	$vals = array();
	$n = 1000;

	for ($i = 0; $i < 10; $i++)
	{
		$parent_id = !$i ? 1 : 1000 + $i - 1;
		$query = 'INSERT INTO #__usergroups '
				. ' (id, title, parent_id)'
				. ' VALUES (' . (1000 + $i) . ', ' . $db->q('Test group ' . uniqid()) . ', ' . $parent_id . ')';
		$db->setQuery($query)->execute();
	}

	for ($i = 0; $i < $n; $i++)
	{
		//$vals[] = '(0, ' . $db->q('Test group ' . uniqid()) . ', ' . (1000 + (int) ($i % 10)) . ')';
		$vals[] = '(0, ' . $db->q('Test group ' . uniqid()) . ', 1009)';
	}

	$query = 'INSERT INTO #__usergroups '
			. ' (id, title, parent_id)'
			. ' VALUES ' . implode($vals, ',');
	$db->setQuery($query)->execute();

	$table = JTable::getInstance('Usergroup', 'JTable', array());
	$table->rebuild();

	JFactory::getApplication()->enqueueMessage('Added 10 + ' . $n . ' usergroups', 'notice');
}
```

**Comment by Fedik** [comment] 2018-03-03 17:13
> Can we disable validating usergroups via JS?

As @ggppdk noted It is disabled, at least should be. 
There can be 100 other script which tried to do something with inputs in the form.

**Comment by tonypartridge** [comment] 2018-03-03 18:03
I’ll run some test, but when I remove usergroup display in the form it’s fast again.. they do have a load of access levels too.

**Comment by Fedik** [comment] 2018-03-03 19:32
@tonypartridge please add more detail:
- which component?
- which form?
- whether there any non-core plugins involved?

**Comment by Fedik** [comment] 2018-03-04 11:20
I have made test on Article form (with 1000 user groups), and validation took only ~40ms, however whole submit ~400ms, but still not 3-4 minutes:

![screen 2018-03-04 13 09 55 461x326](https://user-images.githubusercontent.com/1568198/36944922-1748111e-1fae-11e8-9f4f-79ec27d66455.png)

But the initial rendering take a loooot, mainly because choosen.js.
And Global Configuration form become inaccessible due slow rendering.

Anyway.
Only good solution is to detach the rule field from the main form, make editing in the modal or in another window. Otherwise this issue will stay forever :wink:

**Comment by tonypartridge** [comment] 2018-03-04 11:22
Try it with access levels of 1000 one to every group too?

**Comment by Fedik** [comment] 2018-03-04 11:28
> Try it with access levels of 1000 one to every group too?

nope, I missed this part sorry :wink: 
but, it not affected by validation, 
Can be due:
`jQuery("#permissions-sliders select").attr("disabled", "disabled");`  and `permissions.js`

Anyway there only one good solution, I already wrote.
if someone brave enough to do it, that would be cool :wink:

**Comment by dgrammatiko** [comment] 2018-03-04 14:18
@Fedik let's do that in J4, also making this modal means one less tab which is also another win (simplification)! 👍

**Comment by tonypartridge** [comment] 2018-03-04 14:46
Great idea for J4 massive performance boost for large ACL sites.

**Comment by coolcat-creations** [comment] 2022-08-18 13:43
is this a duplicate of #30101 ?

**Comment by brianteeman** [comment] 2022-08-18 14:28
ooks like they are the same although this one is the oldest

**Comment by rummybocom** [comment] 2024-05-06 18:00
https://rummybo.com<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19804">issues.joomla.org/tracker/joomla-cms/19804</a>.</sub>

**Comment by Hackwar** [comment] 2024-09-29 19:24
I've tested this with 1000+ usergroups and 1000+ viewlevels on Joomla 5.2 and while we have a noticeable delay because of the number of usergroups and thus the input vars send to the server and all that, the delay is maybe around 5 seconds, not minutes and not something unexpected for such a large number. I expect the improvement to come from the removal of chosen in most select fields. I think this is an acceptable situation right now and thus will close this issue here. If you disagree with this, please report back and we can open this issue again.

**Closed as completed by Hackwar** 2024-09-29 19:24 UTC
Labels: No Code Attached Yet, bug, Performance
