### ISSUE TITLE
Menu Manager: Menus:: Column name are missing for all the resolution below the Small tablet landscape (800x600)

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#5587] opened 2015-01-02 06:57 UTC
-log into the Joomla back-end using tablet
-Check the column names.
-Refer screenshot for the same.
![screen shot 2015-01-02 at 00 55 33](http://issues.joomla.org/uploads/1/759fe86bcb832dc366d93ca691a03308.png)

**Comment by aasimali** [comment] 2015-01-02 09:24
**'Search' & 'Clear Text' button are also missing**<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5587">issues.joomla.org/joomla-cms/5587</a>.</sub>

**Comment by zero-24** [comment] 2015-01-02 09:53
ATM it is expected. So we need a UI/UX decision here.

That say: `Hide Option X on phone` and/or `Show Option X on phone`.  The technical thing is minimal here. (just adding or remove the `hidden-phone` class for the headings and cloums)

The labels are hide atm as they have the `hidden-phone` label but the colums not have this class see:
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_menus/views/menus/tmpl/default.php

Same for:
>'Search' & 'Clear Text' button are also missing

see: https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_menus/views/menus/tmpl/default.php#L52
and https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_menus/views/menus/tmpl/default.php#L56<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5587">issues.joomla.org/joomla-cms/5587</a>.</sub>

**Comment by brianteeman** [comment] 2015-01-02 09:53
This is by design - hence the hidden-phone class on the menu titles

**Comment by brianteeman** [comment] 2015-01-02 09:57
If you can think of a way to make the labels fit in the small display then
great lets add them -

As you can see by removing the class `hidden-phone` they don't fit right now

On 2 January 2015 at 09:53, zero-24 <notifications@github.com> wrote:

> ATM it is expected. So we need a UI/UX decision here.
>
> That say: Hide Option X on phone and/or Show Option X on phone. The
> technical thing is minimal here. (just adding or remove the hidden-phone
> class for the headings and cloums)
>
> The labels are hide atm as they have the hidden-phone label but the
> colums not have this class see:
>
> https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_menus/views/menus/tmpl/default.php
>
> Same for:
>
> 'Search' & 'Clear Text' button are also missing
>
> see:
> https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_menus/views/menus/tmpl/default.php#L52
> and
> https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_menus/views/menus/tmpl/default.php#L56
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/5587
> <http://issues.joomla.org/tracker/joomla-cms/5587>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5587#issuecomment-68516715>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by zero-24** [comment] 2015-01-02 10:04
>As you can see by removing the class `hidden-phone` they don't fit right now

Yes. I thinking about do we need all the options on mobile or should we hide a (the) option(s) then?

**Comment by brianteeman** [comment] 2015-01-02 10:05
Personally I see no harm in having the data displayed if it fits easily - I
can live without the headers

On 2 January 2015 at 10:04, zero-24 <notifications@github.com> wrote:

> As you can see by removing the class hidden-phone they don't fit right now
>
> Yes. I thinking about do we need all the options on mobile or should we
> hide a (the) option(s) then?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5587#issuecomment-68517181>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by aasimali** [comment] 2015-01-02 11:10
@zero-24 @brianteeman 
I have 2 suggestion...
1. We can trim label name
2. Show only important option (may be three, hide the rest option for mobile) and display a usable message about hiding the column. So that, user can login to the site using large screen device to play with the remaining option.

**Comment by brianteeman** [comment] 2015-01-02 11:14
1. As mentioned before - editing the text in english is NOT an option as it
might not be possible to trim the text in all other languages
2. Is that really necessary - KISS

On 2 January 2015 at 11:11, Aasim Ali <notifications@github.com> wrote:

> @zero-24 <https://github.com/zero-24> @brianteeman
> <https://github.com/brianteeman>
> I have 2 suggestion...
> 1. We can trim label name
> 2. Show only important option (may be three, hide the rest option for
> mobile) and display a usable message about hiding the column. So that, user
> can login to the site using large screen device to play with the remaining
> option.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5587#issuecomment-68519992>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by aasimali** [comment] 2015-01-02 11:20
Okay! But I am still confused, why we hidden the options in mobile view. We can keep all the option with full column name without trimming the label. Because in case of responsiveness, there will a vertical scroller.
![resposive](https://cloud.githubusercontent.com/assets/10045599/5595677/6e6aeb3c-929f-11e4-91c8-5b7031ed187c.png)

**Comment by brianteeman** [comment] 2015-01-02 11:41
Wrong screenshot

**Comment by aasimali** [comment] 2015-01-02 11:54
Oops!  I have removed that screenshot.

**Comment by aasimali** [comment] 2015-01-02 15:41
@brianteeman 
I have deleted wrong screenshot! Actually, I was talking about 'horizantal scroller'.

![menu](https://cloud.githubusercontent.com/assets/10045599/5597174/cf57628a-92c3-11e4-8588-30c1b04503ef.png)

**Comment by brianteeman** [comment] 2016-01-18 12:54
Closed as parts are by design and parts are no longer relevant in current release<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5587">issues.joomla.org/joomla-cms/5587</a>.</sub>

**Closed by brianteeman** 2016-01-18 12:54 UTC
Labels: No Code Attached Yet
