### ISSUE TITLE
Button - Menu does not do as expected

### ISSUE THREAD

**Issue by joris85** [joomla/joomla-cms#18538] opened 2017-11-09 11:28 UTC
### Steps to reproduce the issue

Enable the button - menu 
Edit an article
Select some text you want to link to a menu item
Click on the button Menu that is appeard after enabling plugin.
Choose a menu item and click on it.
instead of making my selected text linked it replaced my selected text for menu item name.

### Expected result
If i have selected any text it should make that text linked instead of replacing.

### Actual result
My text is deleted and my menu item name is linkable placed instead of it.

### System information (as much as possible)
Joomla 3.8
PHP 7
Chrome on mac

**Comment by ghost** [comment] 2017-11-09 11:37
@infograf768 guess its expected Behaviour #11721?

**Comment by brianteeman** [comment] 2017-11-09 12:06
Agree with @joris85 this is not expected

**Comment by joris85** [comment] 2017-11-09 14:01
Thanks Brian :-) 
Is there someone who can fix this issue?

**Comment by infograf768** [comment] 2017-11-09 15:10
It was conceived this way. It is expected.
It works the same for the Articles button.

**Comment by brianteeman** [comment] 2017-11-09 15:12
Doesn't mean it's the correct expected behaviour

**Comment by infograf768** [comment] 2017-11-09 15:13
What I mean is that if that effect is desired, then it has to be modified also for other buttons: articles, menu, contact.

**Comment by joris85** [comment] 2017-11-09 16:21
Well who desired that?
The user experience is that your text disappears.
So if you ask me desired or not it is not user friendly and not working as a normal customer could expect.
I think this feature is awesome but will not show this my customer before it is working like you expect. Even for me it is not working good.

I select a text, choose a menu to link to, it is replacing that text so i need to edit the link. Halfway you need to place your cursor to stay it a link and after you typed you need to delete the stuff in front and back of the created link. 
If that is desired than i desire other user experience i think :-D

I wish you all a great day!

**Comment by infograf768** [comment] 2017-11-10 07:20
@joris85 
This is the way it has been working for these xtd from the first one (article) created a long time ago.
I am absolutely not opposing this improvement which has to be done via JS.
I personally would not know how to make such a patch.

@dgt41 
Can you devise a solution? I guess it is in the modal js

**Comment by dgrammatiko** [comment] 2017-11-10 07:41
> Select some text you want to link to a menu item

To be able to make that text link we need to move all the xtd buttons to native tinymce plugins. This is a limitation on the current architecture but we started already creating native plugins for j4 (check the image button)

**Comment by infograf768** [comment] 2017-11-10 07:43
@dgt41 
I guess the OP idea is that it would work whatever the editor chosen.

**Comment by dgrammatiko** [comment] 2017-11-10 08:20
@infograf768 there is a way, I guess I need to try it: the xtd plugins always replace the selected text, so if the code is aware that there is some text selected (eg sent an event with the selected text, or empty if nothing is selected) then with a simple if statement we can recompile the desired output. There are couple of gotchas with this approach:
- j3 still supports ie8, meaning we need to use jquery
- j4 will come with an event bus so the events need to be future proof

Let me play around with this idea the next days and I will come up with my findings

**Comment by infograf768** [comment] 2017-11-10 08:22
@dgt41 
Thanks for looking.

**Comment by joris85** [comment] 2017-11-10 11:38
@dgt41 
That sounds awesome! i hope you will have good findings :-)

@infograf768 
The fact that it is working from the beginning of time with the article is probobly the reason why i always disable all the buttons :-D

My end users have no experience with website's so Wordpress it sometimes a better solution for them. But for me Joomla is a better solution haha
I think that if the focus of joomla would be frontend super easy and backend flexible, joomla would be more powerfull and easy than Wordpress.

**Comment by ghost** [comment] 2017-12-26 08:30
@dgt41 any Progress on this Issue?

**Comment by joris85** [comment] 2017-12-26 08:55
Yeah i would  like to know to (:
Is this maybe fixed in 3.8.4?

**Comment by Quy** [comment] 2018-05-25 02:32
Duplicate of #17665<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18538">issues.joomla.org/tracker/joomla-cms/18538</a>.</sub>

**Closed as completed by Quy** 2018-05-25 02:32 UTC
Labels: No Code Attached Yet
