### ISSUE TITLE
[5.0] Dark Mode: tabs

### ISSUE THREAD

**Issue by micker** [joomla/joomla-cms#41823] opened 2023-09-20 06:57 UTC
need to update the tabs in editor, options etc
![image](https://github.com/joomla/joomla-cms/assets/2539440/35cbd2e6-367c-4be9-8112-455706467d47)
![image](https://github.com/joomla/joomla-cms/assets/2539440/fdd90f33-f701-47f3-ba81-3ad896382e74)

**Comment by wilsonge** [comment] 2023-09-20 11:54
![image](https://github.com/joomla/joomla-cms/assets/1986000/09373ea3-5a63-41f0-b5cc-4cfd22450e09)

Article edit for completeness

**Comment by roland-d** [comment] 2023-09-20 12:17
@wilsonge When I go to Options via Template manager I see the same as Micker. This is on Firefox/Linux
![image](https://github.com/joomla/joomla-cms/assets/359377/a71b7e80-3e13-41eb-8470-4a5a2c83d1c6)

**Comment by wilsonge** [comment] 2023-09-20 12:23
I am testing on Chrome and Firefox on Ubuntu 22.04 :)

**Comment by Quy** [comment] 2023-09-20 13:08
I cannot reproduce it with Chrome & Firefox on Windows. Is this happening with the other settings?

**Comment by wilsonge** [comment] 2023-09-20 13:18
I just chatted to @roland-d and for some reason after a full browser cache clear everything worked

**Comment by micker** [comment] 2023-09-20 13:20
yes confirmed for me sorry

**Comment by wilsonge** [comment] 2023-09-20 13:27
Going to keep this open. @HLeithner you might want to look at bumping the asset version for that file to avoid this happening to others on upgrade. Looks like the atum override is currently pinned to the version of custom elements rather than the Joomla version. If not dark mode will bite us elsewhere at some point

**Comment by HLeithner** [comment] 2023-09-20 13:39
which assets do you mean and where is it pinned?

**Comment by Fedik** [comment] 2023-09-20 13:52
The template assets version is auto, and generated with this https://github.com/joomla/joomla-cms/blob/a71afdb5eb7d423ac8804f27d1cc9168848be403/libraries/src/Version.php#L255C1-L255C1

Addittionaly it regenerates every time joomla updated.

Such issue may only happen when "mediaversion refresh" is disabled in debug plugin.
Or testing on git branch, without cleaning cache :wink:

**Comment by wilsonge** [comment] 2023-09-20 13:55
That's the template one. The version for the joomla-tab.css is 0.2.0 - I can't find any hardcoded reference to that so assume that comes from the version in package.json of custom-elements we use. Assume that link is buried somewhere in the build scripts

**Comment by Fedik** [comment] 2023-09-20 14:23
yeah, joomla-tab comes from https://www.npmjs.com/package/joomla-ui-custom-elements

**Comment by wilsonge** [comment] 2023-09-20 14:48
The JS yes. The CSS comes from this https://github.com/joomla/joomla-cms/blob/4.3-dev/build/media_source/templates/administrator/atum/scss/vendor/joomla-custom-elements/joomla-tab.scss SCSS file but is still versioned as 0.2.0 anyway. Which is why on upgrade we're getting issues.

**Comment by HLeithner** [comment] 2023-09-20 16:12
so maybe the logic for the version could be improved

**Comment by wilsonge** [comment] 2023-09-20 16:16
Yes hence I've reopened this issue. Otherwise we might hit it again outside of dark mode specific issues. It's unlikely that I'll have time to work on it before the RC's though

**Comment by Fedik** [comment] 2023-09-20 16:23
Since it is an override, we can also overide the asset defination,
Add:
```json
{
      "name": "webcomponent.joomla-tab",
      "type": "style",
      "uri": "vendor/joomla-custom-elements/joomla-tab.min.css",
},
```
In to Template assets `administrator/templates/atum/joomla.asset.json`

**Comment by Fedik** [comment] 2023-09-20 16:35
This should help https://github.com/joomla/joomla-cms/pull/41841, please test

**Comment by HLeithner** [comment] 2023-09-20 16:35
the thing is it should go automatically in auto mode for overrides?

**Comment by HLeithner** [comment] 2023-09-20 16:35
and auto is not so cool as it sounds ;-)

**Comment by Fedik** [comment] 2023-09-20 16:38
Yes and no,
When you overide only file, then it will keep vendor version, defined in the asset.
When you overide asset with new version, then it use new version

> and auto is not so cool as it sounds 

Why? It pretty safe, it refreshes on every joomla update, 
addittionaly when you push "clean all cache" in backend, it also will force a new media version

**Comment by HLeithner** [comment] 2023-09-20 16:40
> Why? It pretty safe, it refreshes on every joomla update,
> addittionaly when you push "clean all cache" in backend, it also will force a new media version

* It doesn't check the file, if it changes I would expect this. For development it a pain point.
* the hash is too long (unneeded traffic)
* I would like to have a "development" or "random" mode in addition

**Comment by dgrammatiko** [comment] 2023-09-20 16:45
What @Fedik did is fine and actually should be promoted as a best practice, ie: if you're about to override a static asset then it should be defined in the template's json.

This could be automated, ie check the files in the js/css and create the respected entries

**Comment by Fedik** [comment] 2023-09-20 17:18
Here it goes:
- https://github.com/joomla/joomla-cms/pull/41843

**Comment by dgrammatiko** [comment] 2023-09-20 18:14
@Fedik could you also reduce the version string here: https://github.com/joomla/joomla-cms/blob/1739c464fa05c4267eceb6dd04967c7633880203/build/build-modules-js/versioning.es6.js#L62-L64

**Comment by wilsonge** [comment] 2023-09-20 18:25
Can we focus on the issue which is to use the Joomla version string for the css file from atum used for the tabs styling :)

**Comment by HLeithner** [comment] 2023-09-20 18:26
> Can we focus on the issue which is to use the Joomla version string for the css file from atum used for the tabs styling :)

that's already fixed in https://github.com/joomla/joomla-cms/pull/41841

**Closed as completed** 2023-09-20 18:26 UTC
Labels: No Code Attached Yet
