### ISSUE TITLE
Updating to Joomla 3.4.5 - JFolder::create: Infinite loop detected

### ISSUE THREAD

**Issue by rita0407** [joomla/joomla-cms#8355] opened 2015-11-09 08:40 UTC
#### Steps to reproduce the issue
The updating to 3.4.5 is giving me the warning of "JFolder::create: Infinite loop detected". 

#### Expected result

Updating to new joomla version (not an expert, ... hope not to complicate :smile: )

#### Actual result
Warning of "JFolder::create: Infinite loop detected".

All the extensions are updated

#### System information (as much as possible)

My test web is located on: myweb.com/joomla_1
System : Path to Log Folder: /var/www/vhosts/myweb.com/httpdocs/joomla_1/logs
Server: /httpdocs/joomla_1/tmp

**Comment by brianteeman** [comment] 2016-01-28 11:26
Have you resolved this?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8355">issues.joomla.org/joomla-cms/8355</a>.</sub>

**Comment by brianteeman** [comment] 2016-02-19 12:39
I am closing this at this time - if more information to replicate the issue is provided it can always be reopened<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8355">issues.joomla.org/joomla-cms/8355</a>.</sub>

**Closed by brianteeman** 2016-02-19 12:39 UTC
Labels: No Code Attached Yet

**Comment by AlexanderSk** [comment] 2017-02-13 10:17
Update on this issue as i just had this error message after a website transport.
error on any website update: Warning of "JFolder::create: Infinite loop detected".

Issue: on the transfer the log and tmp folder where left to the uld urls.
Solution: Make sure the urls are valid and in the System Information ->Folder Permissions are both Writeable.

**Comment by RogerKamena** [comment] 2018-01-19 00:39
hey guys, 

as further developments and solutions are shared about this, don't forget to also share on the Joomla forums. There is an old thread here I've updated with this discussion about Folder::create: Infinite loop detected here https://forum.joomla.org/viewtopic.php?f=470&t=282892&start=30
