### ISSUE TITLE
[4.0] plg_system_redirect is not checked in when opened in modal

### ISSUE THREAD

**Issue by dneukirchen** [joomla/joomla-cms#19798] opened 2018-02-28 10:01 UTC
### Steps to reproduce the issue

Imo this is low priority, but i want it to be documented. 

This issue came up during removal of inline scripts in https://github.com/joomla-projects/joomla-es6/pull/82

1) If enabled, disable plg_system_redirect
2) Go to com_redirect
3) Click on link `Redirect System Plugin` in alert and see the plugin edit modal
4) Close the button using the modal close button

### Expected result

Plugin checked in

### Actual result

Plugin checked out

### System

current 4.0@dev

### Additional comments

Why are we doing is this way? We should drop the modal and just show a link to the plugin edit page (perhaps with a redirectBack url param) or use ajax to just enable the plugin when user clicks a button...

**Comment by brianteeman** [comment] 2018-02-28 10:10
wont this be the same with all modals? Or is there something different about this one

**Comment by dneukirchen** [comment] 2018-02-28 10:20
This particular issue only affects com_plugins. 

If we have other places where we open plugin edit page in a modal window, those are probably affected as well.

I did not check other edit-modals...

**Comment by infograf768** [comment] 2018-02-28 10:34
In present 4.0-dev, I do not get any Message in Redirect, and I even have no Input field for Collect URLS...

<img width="686" alt="screen shot 2018-02-28 at 11 32 23" src="https://user-images.githubusercontent.com/869724/36783073-3f656678-1c7b-11e8-9e83-8d0d1715d96a.png">

**Comment by brianteeman** [comment] 2018-02-28 10:37
The input fields is resolved by #19296 iirc

**Comment by dneukirchen** [comment] 2018-02-28 10:39
@infograf768 

> 2) Go to com_redirect

not the plugin

**Comment by dgrammatiko** [comment] 2018-02-28 10:42
@dneukirchen one way to solve this, without going to far down the architectural changes needed, is to bind the close event of the modal to press the cancel button in the form (or simple submit the form with `article.cancel` task or whatever task is needed to basically close the edit view)

**Comment by infograf768** [comment] 2018-02-28 10:45
@dneukirchen 
As I said, I do not get any message anymore in present 4.0-dev, including in com_redirect

<img width="933" alt="screen shot 2018-02-28 at 11 40 41" src="https://user-images.githubusercontent.com/869724/36783503-7e590712-1c7c-11e8-968d-f514561aeedb.png">

**Comment by infograf768** [comment] 2018-02-28 10:49
Will try a full clean install

**Comment by infograf768** [comment] 2018-02-28 10:51
Same. Looks like other stuff is broken.

**Comment by dneukirchen** [comment] 2018-02-28 10:59
> bind the close event of the modal to press the cancel button in the form

thats what old code was doing... before someone broke it.

TBH: for me it was the first time that i even noticed that there is something clickable in the alert. I saw it in code... not in the ui. why not just show a plain old link to the plugin edit page? 

If we want to do something "fancy" (but again: i dont see the need) we can show enable (ajax) and configure (plain old link) buttons in the alert.

**Comment by infograf768** [comment] 2018-02-28 11:05
@dgt41 
Looks like #19776 has broken a lot of stuff. For example joomla-alert.

**Comment by dgrammatiko** [comment] 2018-02-28 11:13
Great! Expected as well!

**Comment by infograf768** [comment] 2018-02-28 11:15
Concerning joomla-alert its css is apparently wrong
```
oomla-alert {
    display: block;
    min-width: 250px;
    padding: .5rem 1.25rem;
    margin-bottom: 1rem;
    border: 1px solid transparent;
        border-top-color: transparent;
        border-right-color: transparent;
        border-bottom-color: transparent;
        border-left-color: transparent;
    opacity: 0;
    border-radius: .25rem;
    transition: opacity .15s linear;
```
Opacity should be 100

**Comment by dgrammatiko** [comment] 2018-02-28 11:17
Just run :

node build.js --compilejs 

and you'll be fine again

**Comment by infograf768** [comment] 2018-02-28 11:20
I never run in front of danger...

**Comment by dgrammatiko** [comment] 2018-02-28 11:24
@infograf768 there you go: https://github.com/joomla/joomla-cms/pull/19799
would be easier if you used chrome in the 4 alpha

**Comment by Quy** [comment] 2019-06-09 01:50
Unable to reproduce. Please confirm.

**Closed as completed** 2019-06-09 14:42 UTC
Labels: No Code Attached Yet, J4 Issue
