### ISSUE TITLE
[4] Database Password help text should be under the field not on top

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33528] opened 2021-05-03 23:14 UTC
### Steps to reproduce the issue

Global Config -> system

### Expected result

Database Password help text should be under the field not on top to be consistent with everywhere else

### Actual result
Database Password help on top

<img width="880" alt="Screenshot 2021-05-04 at 00 12 53" src="https://user-images.githubusercontent.com/400092/116944531-95d35580-ac6d-11eb-955e-1f74707a489a.png">

**Comment by YatharthVyas** [comment] 2021-05-04 04:56
Edit: This seems to be an issue with all type="password" fields that have a description without rules=""
In such cases, an extra description is displayed on top of the field. I'm working on a fix 

<hr/>
Original message: 

It appears as if the person who wrote this code has intentionally taken extra efforts to hide the description from coming below it so they could place it above. Are you sure this was unintentional and needs to be fixed? (Maybe they kept it above the field because the message is an important warning and needs extra emphasis?)

This can be fixed by removing the `hiddenDescription` attribute and the markup above. I'd be happy to submit a PR for this if this issue can be confirmed.

https://github.com/joomla/joomla-cms/blob/3cebcc73cd03f015807444ce69e52da0f58c8932/administrator/components/com_config/forms/application.xml#L206

```
<field
	name="password"
	type="password"
	label="COM_CONFIG_FIELD_DATABASE_PASSWORD_LABEL"
	description="COM_CONFIG_FIELD_DATABASE_PASSWORD_DESC"
	filter="raw"
	autocomplete="off"
	size="30"
	hiddenDescription="true"
	lock="true"
/>
```

**Comment by Quy** [comment] 2021-05-04 20:31
Please test PR #33536

**Closed as completed by Quy** 2021-05-04 20:31 UTC
Labels: No Code Attached Yet
