### ISSUE TITLE
php 7.1 Changes to the order of "Articles: Featured" are not changed/saved.

### ISSUE THREAD

**Issue by nrgeen** [joomla/joomla-cms#15566] opened 2017-04-26 09:18 UTC
### Steps to reproduce the issue
Set the Menu-Layout-Options for the "Articles: Featured" site to:
Category Order = No Oder
Article Order = Featured Articel Order

### Expected result
If I change the order in the article overview, it should be saved and the change should be applied to the start page.

### Actual result
If I change the order in the article overview, the order is initially accepted but not saved. The article on the start page remains in the old position and does not change the position.

### System information (as much as possible)
- PHP Built On 	Linux alfa3089 4.4.40-040440-generic #201701060808 SMP Fri Jan 6 13:09:52 UTC 2017 x86_64
- Database Version 	5.7.16
- Database Collation 	latin1_german1_ci
- Database Connection Collation 	utf8mb4_general_ci
- PHP Version 	7.1.4
- Web Server 	Apache
- WebServer to PHP Interface 	cgi-fcgi
- Joomla! Version 	Joomla! 3.7.0 Stable [ Amani ] 25-April-2017 15:36 GMT
- Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
Tested with Chrome and Firefox:
- User Agent	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
- User Agent 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:53.0) Gecko/20100101 Firefox/53.0

**Comment by brianteeman** [comment] 2017-04-26 09:26
> If I change the order in the article overview, it should be saved and the change should be applied to the start page.

Are you changing the order in the article list or the featured article list?

It should be from the featured article list

### not here
<img width="645" alt="screenshotr10-25-12" src="https://cloud.githubusercontent.com/assets/1296369/25427527/c3378138-2a6a-11e7-9e6e-b8eff20ba202.png">

### here

<img width="748" alt="screenshotr10-25-30" src="https://cloud.githubusercontent.com/assets/1296369/25427538/ce05612a-2a6a-11e7-9768-76c8b718b61f.png">

**Comment by nrgeen** [comment] 2017-04-26 09:52
Sorry, that was not accurate enough.
I've made the change, as shown by you, from the featured article list.

**Comment by franz-wohlkoenig** [comment] 2017-04-28 07:17
@nrgeen Can't confirm Issue. Changing order in featured article list is shown in Menu.

**Comment by jkrokar** [comment] 2017-04-28 13:57
Hi,

reordering is not working. You can move the items but new order is not saved.

![](http://www.kastela.org/tmp/articlereorder.jpg "Feature order")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15566">issues.joomla.org/tracker/joomla-cms/15566</a>.</sub>

**Comment by DanRV** [comment] 2017-04-28 15:07
I am experiencing this problem.  In the Featured Articles list screen I move articles up or down to order them, but my order is not saved and not reflected on the home page.

I was able to set the order in phpMyAdmin by manually entering order numbers into the ordering field in the content_frontpage table, but ordering in the Featured Articles list is not working - not being saved.  Joomla 3.7 and PHP 7.1.3.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15566">issues.joomla.org/tracker/joomla-cms/15566</a>.</sub>

**Comment by HoozeMe** [comment] 2017-04-29 21:20
It seems to be an issue with the php version.
J3.7 + php5.6 --> works
J3.7 + php7.0 --> works
J3.7 + php7.1 --> the response when reorder the featured articels is an server errer (500)
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15566">issues.joomla.org/tracker/joomla-cms/15566</a>.</sub>

**Comment by HoozeMe** [comment] 2017-04-29 21:44
... I should add the notice: the error 500 is only seen in the network analysis (firefox). the behavior in the backend is as described in the comments above: reordering - but nothing is saved.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15566">issues.joomla.org/tracker/joomla-cms/15566</a>.</sub>

**Comment by DanRV** [comment] 2017-04-29 23:17
Confirmed.  When I saw your post I rolled back to PHP 7.0 and reordering featured articles is working again.  Thank you for posting that.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15566">issues.joomla.org/tracker/joomla-cms/15566</a>.</sub>

**Comment by jkrokar** [comment] 2017-05-02 12:56
Some for me. Workaround is reverting of PHP version to 7.0.
Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15566">issues.joomla.org/tracker/joomla-cms/15566</a>.</sub>

**Comment by brianteeman** [comment] 2017-05-14 16:14
added php 7.1 to the title

**Comment by ghazal** [comment] 2017-05-17 17:34
Looks like the error still exists in 3.7.1 - and PHP 7.1

**Comment by oorzaak** [comment] 2017-06-08 11:07
Just experienced this issue in J.3.7.2 on php 7.1 as well. Changing to php 7.0 solved it - or should I say it is a workaround.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15566">issues.joomla.org/tracker/joomla-cms/15566</a>.</sub>

**Comment by Joso** [comment] 2017-09-03 17:17
Hi, I have this issue on my site Joomla 3.7.5 and php 7.0.18.  How can I solve it?

**Comment by ghazal** [comment] 2017-09-04 10:41
The feature works here with PHP 7.1.7.

**Comment by brianteeman** [comment] 2018-01-05 23:47
Cant replicate in php 7.2 

@mbabker can I close this if it is a php bug?

**Comment by Quy** [comment] 2018-02-01 18:24
No issues with PHP 7.1.13 and v3.8.4.

**Comment by brianteeman** [comment] 2018-08-18 17:00
Closed as a non joomla bug

**Closed by brianteeman** 2018-08-18 17:00 UTC
Labels: J3 Issue, No Code Attached Yet
