### ISSUE TITLE
Why is the name of the component in the XML file always lowercase?

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#26221] opened 2019-09-08 20:43 UTC
It's not an important question, but I'm interested. Why is the name of the component in the XML file always lowercase? For example here:

https://github.com/joomla/joomla-cms/blob/9fa42b863e3da5b4fcec91cb230c7202d837cbf1/administrator/components/com_content/content.xml#L3

As a language string it should have to be capitalized, right? Is there a reason I do not see or has grown historically?

**Comment by infograf768** [comment] 2019-09-09 10:32
Grown historically.
In 1.5, it was not translatable. We had for example: 
```
<install type="component" version="1.0.0">
<name>Module Manager</name>
<author>Joomla! Project</author>
```
In 1.6 was introduced the Translation of the extensions name and, logically, lowercase was used and strtoupper in the JText for core extensions.
```
<?xml version="1.0" encoding="utf-8"?>
<!-- $Id: modules.xml 20196 2011-01-09 02:40:25Z ian $ -->
<extension type="component" version="1.6.0" method="upgrade">
	<name>com_modules</name>
	<author>Joomla! Project</author>
```

I am closing this as it is not a bug. ;)

**Closed as completed** 2019-09-09 10:32 UTC
Labels: No Code Attached Yet

**Comment by astridx** [comment] 2019-09-09 10:50
@infograf768 Many thanks.
