### ISSUE TITLE
Wrong loadRowList param description i driver.php

### ISSUE THREAD

**Issue by artur-stepien** [joomla/joomla-cms#7240] opened 2015-06-22 10:34 UTC
$key is a numeric index of a field in $row array not a field/column name. $row variable is an array indexed starting from zero. So $key is unique . Using column name in this param can result in unexpected results.

This mistake is in here:  libraries/joomla/database/driver.php

Here is my pull request:
https://github.com/joomla/joomla-cms/pull/7239

**Comment by zero-24** [comment] 2015-06-22 10:45
@artur-stepien since we using now our own Issue Tracker (http://issues.joomla.org/tracker/joomla-cms) you don't need to open a extra Issue if you have a Pull Request.

So I closing here as we have allready your pull request #7239 :+1: Thanks :smile:

**Closed by zero-24** 2015-06-22 10:45 UTC
Labels: No Code Attached Yet

**Comment by artur-stepien** [comment] 2015-06-22 10:49
So I suppose from now on I should just describe Pull Requests as they where Bug Reports or Feature Request?

**Comment by zero-24** [comment] 2015-06-22 10:57
Yes :smile: 

If you have code please open only a pull request and put all information to test there.
If you have a issue (without code to fix it) please open a issue with all information to reproduce.

If you have a new Feature with code please open a pull request.
If you have a feature request (without code) please open a issue with all information.

**Comment by artur-stepien** [comment] 2015-06-22 10:58
Nice :D

**Comment by artur-stepien** [comment] 2015-06-22 11:02
This trackers has few problems. NO code formatting in comments. And I had like 5-6 times problems with MySQL connection while trying to post comment. So it is work in progress?

**Comment by zero-24** [comment] 2015-06-22 11:10
@artur-stepien 

Code formatting is like github see: https://guides.github.com/features/mastering-markdown/ and https://help.github.com/articles/github-flavored-markdown/
For Syntax highlighting see: https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting

`And I had like 5-6 times problems with MySQL connection while trying to post comment.`

I can confirm that but now it is gone. I never experienced that bevor :smile:

**Comment by artur-stepien** [comment] 2015-06-22 11:12
It would be nice to add this markdown links near editor. There can be more questions like mine :)
