### ISSUE TITLE
Wrong order by date - compact list of tagged items

### ISSUE THREAD

**Issue by scheibye** [joomla/joomla-cms#6984] opened 2015-05-18 19:02 UTC
#### Steps to reproduce the issue
**Backend** 
Create some articles 
Assign a tag to the articles 
Create a menu item "Compact List of Tagged items"
Assign the same tag to your menu item that you have assigned to your articles
Tag Options --> Order By "Created Date" (the same applies to "Modified date" or "Published Date") 

#### Expected result
**Frontend**
The list in the frontend should be ordered by date.

#### Actual result
**Frontend**
The list order had no noticable logic.

#### System information (as much as possible)
PHP Built On	Linux timeout4you.dk 3.13.0-49-generic #83-Ubuntu SMP Fri Apr 10 20:11:33 UTC 2015 x86_64
Database Version	5.5.43-0ubuntu0.14.04.1
Database Collation	utf8_general_ci
PHP Version	5.5.9-1ubuntu4.9
Web Server	Apache/2.4.7 (Ubuntu)
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 3.3.6 Stable [ Ember ] 01-October-2014 02:00 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.152 Safari/537.36

**Comment by BuddhiEash** [comment] 2015-05-19 05:25
Yes i can confirm this issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6984">issues.joomla.org/joomla-cms/6984</a>.</sub>

**Comment by BuddhiEash** [comment] 2015-05-19 05:31
Update to my comment: But i can see a some logic there.Because you have mentioned it seems there's no logic.But i created articles such as "Test 1,Test 2,Test article,Test article 1".In front-end i could see the always the order was Test 1,Test 2,Test article,Test article 1.So i think there's a some priority to numerical values.If there's no any logic, the articles always should be shuffled.But it's not.Anyhow it gets always same order.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6984">issues.joomla.org/joomla-cms/6984</a>.</sub>

**Comment by bertmert** [comment] 2015-05-25 10:46
Confirmed.
- Tagged 4 articles with different creation dates.
- Menu item settings:
- - Tag options > Order: Created Date, ascending
- - List Layouts > Show Date: Created

![tags-ordering](https://cloud.githubusercontent.com/assets/11038612/7796081/e0dd2d40-02db-11e5-9966-b50fce2a8b13.jpg)
---------------------------------------------
Menu item type *Tags » Tagged Items* orders correctly.

**Comment by bertmert** [comment] 2015-05-25 10:56
I'll provide a PullRequest.

**Comment by bertmert** [comment] 2015-05-25 11:16
See PR https://github.com/joomla/joomla-cms/pull/7033 and test please.

**Comment by zero-24** [comment] 2015-05-25 12:29
Closing as we have a pull request. https://github.com/joomla/joomla-cms/pull/7033 Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6984">issues.joomla.org/joomla-cms/6984</a>.</sub>

**Closed by zero-24** 2015-05-25 12:29 UTC
Labels: No Code Attached Yet
