### ISSUE TITLE
Why are the custom callback filters not executed in the InputFilter::clean method?

### ISSUE THREAD

**Issue by GeoTimber** [joomla/joomla-cms#27419] opened 2020-01-06 15:24 UTC
### Is your feature request related to a problem? Please describe.

I expected to find the custom callback filters to be included in the InputFilter class in the clean method but I can only find them in the Form class under the filterField method

### Describe the solution you'd like

Move the callback filter check to InputFilter::clean method

### Additional context

This would allow us to call
```php
$myValue = JFactory::getApplication()->input->get( 'myvalue', false, 'myCustomFilter::filter');
```

in our controllers to get our custom filter working to return our value ,which is not possible at the moment.

**Comment by Fedik** [comment] 2020-01-06 15:27
it works:
```php
$myValue = myCustomFilter::filter($app->input->get( 'myvalue', false, 'raw'));
```

**Comment by GeoTimber** [comment] 2020-01-06 15:40
Fair enough but that is not the same, I have not knowledge about the 'default' value in my myCustomFilter::filter method and may destroy it in my filter.

It will work, I just can't see why it is not in the InputFilter class.

**Comment by mbabker** [comment] 2020-01-06 15:47
The `InputFilter` class by design does not support callbacks.  Why a set of non-standard filters was introduced into the `Form` class to me makes no sense (in a couple of cases this implies that someone confused filtering logic with validation logic as at least the "TEL" case should be a validation rule and not a filtering rule (and strangely enough there does exist a "tel" validation rule 🤦‍♂)).

**Comment by joomdonation** [comment] 2022-11-12 09:55
As @mbabker pointed out, our InputFilter class does not support callbacks, so please use the workaround provided by @Fedik in earlier comment. There is nothing we can do here, so I'm closing this issue.

**Closed as completed by joomdonation** 2022-11-12 09:55 UTC
Labels: No Code Attached Yet
