### ISSUE TITLE
Update 3.10 to Joomla_4.0.0-alpha12-dev-Development-Update_Package.zip

### ISSUE THREAD

**Issue by Stuartemk** [joomla/joomla-cms#26588] opened 2019-10-14 09:08 UTC
### Steps to reproduce the issue

Update 3.10 to Joomla_4.0.0-alpha12-dev-Development-Update_Package.zip

### Expected result

Work normal

### Actual result

Backend: Error: Unknown asset "template.atum.ltr": Call to undefined method Joomla\CMS\Application\AdministratorApplication::isSite()

Frontend: Error: Unknown column 'm.publish_up' in 'where clause': Call to undefined method Joomla\CMS\Application\SiteApplication::isSite()

### System information (as much as possible)

Mysql 5.7.27
Php 7.2.19

**Comment by sakiss** [comment] 2019-10-14 09:31
You cannot update 3.x to 4.x.
Joomla 4 is a new system.

**Comment by Stuartemk** [comment] 2019-10-14 09:47
> You cannot update 3.x to 4.x.
> Joomla 4 is a new system.

@sakiss  https://developer.joomla.org/news/764-joomla-3-10-and-joomla-4-0.html

**Comment by richard67** [comment] 2019-10-14 10:16
For the same reason as stated here [https://github.com/joomla/joomla-cms/issues/26587#issuecomment-541593594](https://github.com/joomla/joomla-cms/issues/26587#issuecomment-541593594) , you can't update yet from a 3.10. But for testing purpose it is currently still possible to update from e.g. 3.9.12 to 4.0.0-alpha12-dev. The update has to be done with the "Upload & Update" tab ot the Jooma Update Component. You have to download the update zip container before. During the update there will be a few times warmings about misssing administrator template, but after successful end of the update and first login to the admin area and navigating first time to somewhere else than the starting screen, these warning will not appear anymore because the new template will be used, and you can use the backend and frontent in the normal way.

**Comment by richard67** [comment] 2019-10-14 10:17
So I would recommend to close this issue as expected behavior. @wilsonge please confirm.

**Comment by Stuartemk** [comment] 2019-10-14 10:53
> For the same reason as stated here [#26587 (comment)](https://github.com/joomla/joomla-cms/issues/26587#issuecomment-541593594) , you can't update yet from a 3.10. But for testing purpose it is currently still possible to update from e.g. 3.9.12 to 4.0.0-alpha12-dev. The update has to be done with the "Upload & Update" tab ot the Jooma Update Component. You have to download the update zip container before. During the update there will be a few times warmings about misssing administrator template, but after successful end of the update and first login to the admin area and navigating first time to somewhere else than the starting screen, these warning will not appear anymore because the new template will be used, and you can use the backend and frontent in the normal way.

@richard67  My friend, you say that for testing purposes the update should be done for example from a clean installation from 3.9.12 to 4.0.0-alpha12-dev, without first doing a previous update from 3.9.12 to 3.10? I don't think that is correct since in the oficial joomla page it is mentioned that version 3.10 is the bridge to go from 3.x to 4.x

I installed 3.9.12 clean and updated with Joomla_4.0.0-alpha12-dev-Development-Update_Package.zip, without going through a previous update from 3.9.12 to 3.10,

Error: The template for this display is not available.

He then asked for credentials confirmation and showed, let's say normal backend and frontend.

**Comment by richard67** [comment] 2019-10-14 11:03
@Stuartemk Yes, you understood me right, that's what I say. The official page describes the situation how it will be when 4.0 and 3.10 have been released. For now we are testing updates to 4.0-dev as described in this issue here: #25467 . The description was made by the release lead for 4.0, so if that is wrong don't blame me ;-) The "Error: The template for this display is not available." message coming several times during the update process is also expected, see description in that issue, and it is also expected that you have to enter additionally credentials 2 times, at beginning andat finalisation of the update. Then when logging in to backend, this error message comes 1 final time, but after you started to navigate around in backend it will not come again and all tille be ok, because the new template has been set as default with the fist login.

**Comment by Stuartemk** [comment] 2019-10-14 11:22
> @Stuartemk Yes, you understood me right, that's what I say. The official page describes the situation how it will be when 4.0 and 3.10 have been released. For now we are testing updates to 4.0-dev as described in this issue here: #25467 . The description was made by the release lead for 4.0, so if that is wrong don't blame me ;-) The "Error: The template for this display is not available." message coming several times during the update process is also expected, see description in that issue, and it is also expected that you have to enter additionally credentials 2 times, at beginning andat finalisation of the update. Then when logging in to backend, this error message comes 1 final time, but after you started to navigate around in backend it will not come again and all tille be ok, because the new template has been set as default with the fist login.

All that you describe is correct in relation to the behavior of the direct update from 3.9.12 to 4.x.

From the above I have nothing to say but that is correct.

Where I don't see it right is that the update from 3.9.12 to 4.x is done, what is the point of 3.10? However, going from 3.9.12 to 4.x is functional, while going from 3.9.12 to 3.10 and then to 4.x the backend and the frontend no longer work.

Thanks for your time.

**Comment by richard67** [comment] 2019-10-14 11:34
@Stuartemk I think we have an intermediate solution right now, and I think that before 3.10 and 4.0 RC will be released, the official update path will be established, that's at least what I know. The reason for 3.10 will be that there will be a kind of compatibility layer so extensions can be used on 3.10 but be made ready for 4.0 too.

I think we both agree that the current situation with official documentation telling about how it will be but not about how it is now is not optimal and so confusing testers, and we should be happy to have volunteer testers and not make them run away. I will see where I can discuss with maintainers so we can solve this soon.

Anyway, a big thank you to you that you are testing, and if I appeared unfriendly or unpatient in some way then sorry, that was really not my intention. I only have not much time here at work for writing, maybe that was the reason.

**Comment by Stuartemk** [comment] 2019-10-14 23:11
@richard67 

Apparently the error was caused by a third-party plugin for a Deprecated statement:  isSite (), instead of isClient (´site´)

You can close this Issue

**Closed as completed** 2019-10-14 23:22 UTC
Labels: No Code Attached Yet
