### ISSUE TITLE
article Publishing time not set to 00:00:00

### ISSUE THREAD

**Issue by vdneut** [joomla/joomla-cms#17829] opened 2017-09-01 19:11 UTC
### Steps to reproduce the issue
Create new article and enter title
Select Publishing tab
Select Start Publishing date from date picker 
Remove time part of the date/time field
Press Save

### Expected result
Start Publishing field shows: 2017-09-03 00:00:00

### Actual result
Start Publishing field shows: 2017-09-03 21:04:00

### System information (as much as possible)
Joomla! 3.7.5 Stable [ Amani ] 14-August-2017 12:09 GMT

### Additional comments
After saving and removing the time form the field it DOES show 00:00;00 as expected.
Problem only when initial save is done.

**Comment by ghost** [comment] 2017-09-02 09:01
Issue confirmed.

Also if copy "00:00:00" inside `Start Publishing` Time is set like "10:59:09".

**Comment by dgrammatiko** [comment] 2017-09-02 09:20
@vdneut does https://github.com/joomla/joomla-cms/pull/17703 solve the problem?

**Comment by dgrammatiko** [comment] 2017-09-02 09:22
edit: 
> Remove time part of the date/time field

That will not reset the time, you need to **set** it manually e.g. `00:00:00`

**Comment by ghost** [comment] 2017-09-02 09:25
@dgt41 i used latest staging for Test, as #17703 is merged it don't help in this Case.

**Comment by dgrammatiko** [comment] 2017-09-02 09:31
@franz-wohlkoenig read my previous comment, atm deleting the time is not reseting it, if that's a bug then let's make a PR...

EDIT: my feeling is that in a calendar field that time is required if none is provided then current time is used, I don't remember the actual, but I bet this is the current functionality

**Comment by ghost** [comment] 2017-09-02 09:42
@dgt41 i manually appended 00:00:00 and it gets resetted by actual Time ([Comment](https://github.com/joomla/joomla-cms/issues/17829#issuecomment-326732202))

I would also expect that empty time is removed by "10:04:09" and not by "00:00:00".

**Comment by vdneut** [comment] 2017-09-02 23:12
Previous behavior was: if you remove time string like 12:12:12 in any case, the time was allways set to 00:00:00. I'm sure because I do this every week for > 5 years now. It also makes sence as having only a date, one would expect the time would be midnight.

**Comment by ghost** [comment] 2017-09-03 04:57
@vdneut thanks for Info, didn't know that.

**Comment by jimbrooking** [comment] 2017-10-24 00:26
At my site setting publishing end date to something, and leafing created and start publishing dates clear, then saving, causes end publishing date to get hosed. This is a Medium-High impact error as we use an ent date on most of our articles (30-60/month). Please see pefore/after screen shots.
![screen shot 2017-10-24 at 00 25 12](https://issues.joomla.org/uploads/1/219b8a42ed18d4185ba3a653f7124a0e.jpg)![screen shot 2017-10-24 at 00 25 14](https://issues.joomla.org/uploads/1/e0b77c3d6e01a1fed44ee67094e07f14.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17829">issues.joomla.org/tracker/joomla-cms/17829</a>.</sub>

**Comment by infograf768** [comment] 2017-10-24 07:25
@jimbrooking I can't reproduce this.
![dateendpublishing](https://user-images.githubusercontent.com/869724/31929675-30c96692-b89d-11e7-90fd-068095055f49.gif)

**Comment by jimbrooking** [comment] 2017-10-24 13:26
It appears that you are using the TinyMCE Editor. TinyMCE does not exhibit the problem. JCE (version 2.6.19) is where my problem lies. Should this be taken up with the JCE people instead of Joomla?

Thanks for checking.

**Comment by ghost** [comment] 2017-10-24 13:31
closed as no Core-Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17829">issues.joomla.org/tracker/joomla-cms/17829</a>.</sub>

**Closed as completed by ghost** 2017-10-24 13:31 UTC
Labels: No Code Attached Yet
