### ISSUE TITLE
New Random Image Module Error

### ISSUE THREAD

**Issue by twister65** [joomla/joomla-cms#17656] opened 2017-08-21 14:40 UTC
### Steps to reproduce the issue
Log in as administrator
Extensions -> Modules 
New -> Random Image
Set Title, Image Folder, and Position
Save

### Expected result
Creation of a new random image module

### Actual result
![random_image_module](https://user-images.githubusercontent.com/26852967/29523724-37ae81b8-868e-11e7-9800-fc5b5a0d4373.png)

### System information (as much as possible)
Joomla-cms-staging (21/08/2017)
PostgreSQL 9.5.6
PHP 7

### Additional comments
ERROR: null value in column "ordering" violates not-null constraint DETAIL: Failing row contains (94, 0, Images, , , null, position-7, 0, 1970-01-01 00:00:00, 1970-01-01 00:00:00, 1970-01-01 00:00:00, 1, mod_random_image, 1, 1, {"type":"jpg","folder":"images\/space","link":"","width":"","hei..., 0, *).

**Comment by ghost** [comment] 2017-08-21 15:13
Can't confirm.
### System information
3.8-dev
Multilanguage Site
macOS Sierra, 10.12.6
Firefox 55 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by twister65** [comment] 2017-08-21 15:15
System information (as much as possible)

Joomla-cms-staging (21/08/2017)
**PostgreSQL 9.5.6**
PHP 7

**Comment by alikon** [comment] 2017-08-21 15:16
@franz-wohlkoenig   you can test on mysql   too  but need setting 'ONLY_FULL_GROUP_BY' in the mysql side

**Comment by twister65** [comment] 2017-08-21 15:22
@alikon , it's not this issue, you are referring to : 
https://github.com/joomla/joomla-cms/issues/17582

**Comment by twister65** [comment] 2017-08-21 15:47
If you set Title, Image Folder, Position, and **Ordering** : it works !
The default value of ordering column in the insert query is NULL.
Ordering Column can't be NULL (NOT NULL) in the __modules table.

**Comment by twister65** [comment] 2017-08-21 16:53
When you create a new module, the ordering is not pre-filled, whatever module you choose.
Before, with Joomla!3.7.5, ordering was a combobox (text now) and pre-filled.

**Comment by brianteeman** [comment] 2017-08-22 06:58
@franz-wohlkoenig its a postgres issue - you are on mysql ;)

**Comment by ghost** [comment] 2017-08-22 07:03
@brianteeman i wanted to make clear its working on mysql :-)

**Comment by twister65** [comment] 2017-08-22 09:05
![new module - call stack](https://user-images.githubusercontent.com/26852967/29557563-ca92d268-8729-11e7-840a-2e2ca2510f15.png)

**Comment by twister65** [comment] 2017-08-22 10:58
@infograf768 , please check the ordering combobox in the new module, it disappeared (only text, we can't select, ordering has a null value by default).
Do a non-regression test for https://github.com/joomla/joomla-cms/pull/17215.

**Comment by Schmidie64** [comment] 2017-08-22 11:58
@Icampus
I also couldn't reproduce this item with MySQL its definitely an PostSQL Bug.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17656">issues.joomla.org/tracker/joomla-cms/17656</a>.</sub>

**Comment by twister65** [comment] 2017-08-22 12:26
@infograf768 , I can't see "Language Filtering" in Menus -> Options -> Custom Administrator Menus (PR #17215 ).

**Comment by twister65** [comment] 2017-08-22 12:30
With MySQL, you can't select "Ordering" in the New Module page. There is no error message, but it doesn't work too.

**Comment by twister65** [comment] 2017-08-23 01:39
There were libraries missing : moduleorder.php, moduleposition.php...
I installed the last staging and it works now.
You can close this issue.

**Comment by ghost** [comment] 2017-08-23 04:27
closed as stated above. @twister65 glad you have solve the Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17656">issues.joomla.org/tracker/joomla-cms/17656</a>.</sub>

**Closed as completed by ghost** 2017-08-23 04:27 UTC
Labels: No Code Attached Yet
