### ISSUE TITLE
Plugin privacy content in the new user registration not at the end

### ISSUE THREAD

**Issue by robysev74** [joomla/joomla-cms#27215] opened 2019-12-06 16:51 UTC
### Steps to reproduce the issue
I inserted the plugin - privacy content to have in the new user registration the acceptance of the privacy policy only that I can't move it to the end after the user profile plugin. I was thinking of solving with sorting but I can't do it, it doesn't let me see all the plugins and therefore I can't. Does anyone have any idea how this can be done?
ps: I have attached an image of the plugin, I can't tell it to put it at the end .... any idea or solution?

**Comment by SharkyKZ** [comment] 2019-12-06 17:03
Duplicate of https://github.com/joomla/joomla-cms/issues/22168.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27215">issues.joomla.org/tracker/joomla-cms/27215</a>.</sub>

**Closed as completed by SharkyKZ** 2019-12-06 17:03 UTC
Labels: No Code Attached Yet
