### ISSUE TITLE
[J3.10.12] Error: 0 Call to a member function get() on null

### ISSUE THREAD

**Issue by jweaver0312** [joomla/joomla-cms#41154] opened 2023-07-13 15:31 UTC
### Steps to reproduce the issue
Try to reinstall Joomla Core Files through Joomla Update

### Expected result
No error, should reinstall Core files

### Actual result
Error: 0 Call to a member function get() on null

### System information (as much as possible)
LiteSpeed Web Server on Cloudlinux

### Workaround
Download Upgrade Package Zip and use that to install

**Comment by jweaver0312** [comment] 2023-07-13 15:32
Workaround, do it manually.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41154">issues.joomla.org/tracker/joomla-cms/41154</a>.</sub>

**Comment by zero-24** [comment] 2023-07-13 16:39
Do you have a stack trace? What PHP Version you are running? That is an 3.10.11 that raises this error right? There was a similiar issue that @coolcat-creations had but that was on 3.10.11 and updated from there.

Did the issue come up with the updated package too?

**Comment by jweaver0312** [comment] 2023-07-13 16:44
The issue shows on 3.10.12 with PHP Version 8.2.5

Call to a member function get() on null
/home/mycoo660/domains/sprintswac.tk/public_html/iconnect/3/administrator/components/com_joomlaupdate/models/default.php:302
Call stack
#	Function	Location
1	()	JROOT/administrator/components/com_joomlaupdate/models/default.php:302
2	JoomlaupdateModelDefault->download()	JROOT/administrator/components/com_joomlaupdate/controllers/update.php:48
3	JoomlaupdateControllerUpdate->download()	JROOT/libraries/src/MVC/Controller/BaseController.php:702
4	Joomla\CMS\MVC\Controller\BaseController->execute()	JROOT/administrator/components/com_joomlaupdate/joomlaupdate.php:18
5	require_once()	JROOT/libraries/src/Component/ComponentHelper.php:402
6	Joomla\CMS\Component\ComponentHelper::executeComponent()	JROOT/libraries/src/Component/ComponentHelper.php:377
7	Joomla\CMS\Component\ComponentHelper::renderComponent()	JROOT/libraries/src/Application/AdministratorApplication.php:101
8	Joomla\CMS\Application\AdministratorApplication->dispatch()	JROOT/libraries/src/Application/AdministratorApplication.php:159
9	Joomla\CMS\Application\AdministratorApplication->doExecute()	JROOT/libraries/src/Application/CMSApplication.php:225
10	Joomla\CMS\Application\CMSApplication->execute()	JROOT/administrator/index.php:51<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41154">issues.joomla.org/tracker/joomla-cms/41154</a>.</sub>

**Comment by zero-24** [comment] 2023-07-13 16:47
Does the same issue come up with PHP 8.1 or 8.0? There are a few known issues with PHP 8.2

**Comment by jweaver0312** [comment] 2023-07-13 16:53
Same issue when using PHP 8.0 and PHP 8.1

**Comment by coolcat-creations** [comment] 2023-07-14 15:09
Thats nothing to do with my issue, my issue happened before the update I disabled all 3rd party but the issue is still there.

**Comment by zero-24** [comment] 2023-07-14 17:03
Can you look into the PHP error log whether there is an error when looking for an update before? When you can also try is to reset the updater table via: Extensions -> Manage -> Updates -> Clear Cache.

**Comment by jweaver0312** [comment] 2023-07-14 17:17
Not sure about before when updating to 3.10.12, but currently (after the update) when re-attemtping to install Core files the following entries are made into the PHP Error Log

2023-07-13 11:26:25.069720 [NOTICE] [3623041] [T0] [127.0.0.1:47418#APVH_www.sprintswac.tk:443] [STDERR] PHP Warning:  Attempt to read property "downloadurl" on null in /home/mycoo660/domains/sprintswac.tk/public_html/iconnect/3/administrator/components/com_joomlaupdate/models/default.php on line 301\n
2023-07-13 11:26:25.069752 [NOTICE] [3623041] [T0] [127.0.0.1:47418#APVH_www.sprintswac.tk:443] [STDERR] PHP Stack trace:\n
2023-07-13 11:26:25.069758 [NOTICE] [3623041] [T0] [127.0.0.1:47418#APVH_www.sprintswac.tk:443] [STDERR] PHP   1. {main}() /home/mycoo660/domains/sprintswac.tk/public_html/iconnect/3/administrator/index.php:0\n
2023-07-13 11:26:25.069763 [NOTICE] [3623041] [T0] [127.0.0.1:47418#APVH_www.sprintswac.tk:443] [STDERR] PHP   2. Joomla\CMS\Application\CMSApplication->execute() /home/mycoo660/domains/sprintswac.tk/public_html/iconnect/3/administrator/index.php:51\n
2023-07-13 11:26:25.069767 [NOTICE] [3623041] [T0] [127.0.0.1:47418#APVH_www.sprintswac.tk:443] [STDERR] PHP   3. Joomla\CMS\Application\AdministratorApplication->doExecute() /home/mycoo660/domains/sprintswac.tk/public_html/iconnect/3/libraries/src/Application/CMSApplication.php:225\n
2023-07-13 11:26:25.069774 [NOTICE] [3623041] [T0] [127.0.0.1:47418#APVH_www.sprintswac.tk:443] [STDERR] PHP   4. Joomla\CMS\Application\AdministratorApplication->dispatch($component = *uninitialized*) /home/mycoo660/domains/sprintswac.tk/public_html/iconnect/3/libraries/src/Application/AdministratorApplication.php:159\n
2023-07-13 11:26:25.069780 [NOTICE] [3623041] [T0] [127.0.0.1:47418#APVH_www.sprintswac.tk:443] [STDERR] PHP   5. Joomla\CMS\Component\ComponentHelper::renderComponent($option = 'com_joomlaupdate', $params = *uninitialized*) /home/mycoo660/domains/sprintswac.tk/public_html/iconnect/3/libraries/src/Application/AdministratorApplication.php:101\n
2023-07-13 11:26:25.069787 [NOTICE] [3623041] [T0] [127.0.0.1:47418#APVH_www.sprintswac.tk:443] [STDERR] PHP   6. Joomla\CMS\Component\ComponentHelper::executeComponent($path = '/home/mycoo660/domains/sprintswac.tk/public_html/iconnect/3/administrator/components/com_joomlaupdate/joomlaupdate.php') /home/mycoo660/domains/sprintswac.tk/public_html/iconnect/3/libraries/src/Component/ComponentHelper.php:377\n
2023-07-13 11:26:25.069805 [NOTICE] [3623041] [T0] [127.0.0.1:47418#APVH_www.sprintswac.tk:443] [STDERR] PHP   7. require_once() /home/mycoo660/domains/sprintswac.tk/public_html/iconnect/3/libraries/src/Component/ComponentHelper.php:402\n
2023-07-13 11:26:25.069809 [NOTICE] [3623041] [T0] [127.0.0.1:47418#APVH_www.sprintswac.tk:443] [STDERR] PHP   8. Joomla\CMS\MVC\Controller\BaseController->execute($task = 'download') /home/mycoo660/domains/sprintswac.tk/public_html/iconnect/3/administrator/components/com_joomlaupdate/joomlaupdate.php:18\n
2023-07-13 11:26:25.069817 [NOTICE] [3623041] [T0] [127.0.0.1:47418#APVH_www.sprintswac.tk:443] [STDERR] PHP   9. JoomlaupdateControllerUpdate->download() /home/mycoo660/domains/sprintswac.tk/public_html/iconnect/3/libraries/src/MVC/Controller/BaseController.php:702\n
2023-07-13 11:26:25.069821 [NOTICE] [3623041] [T0] [127.0.0.1:47418#APVH_www.sprintswac.tk:443] [STDERR] PHP  10. JoomlaupdateModelDefault->download() /home/mycoo660/domains/sprintswac.tk/public_html/iconnect/3/administrator/components/com_joomlaupdate/controllers/update.php:48\n
2023-07-13 11:26:25.069828 [NOTICE] [3623041] [T0] [127.0.0.1:47418#APVH_www.sprintswac.tk:443] [STDERR] PHP Warning:  Attempt to read property "_data" on null in /home/mycoo660/domains/sprintswac.tk/public_html/iconnect/3/administrator/components/com_joomlaupdate/models/default.php on line 301\n
2023-07-13 11:26:25.069836 [NOTICE] [3623041] [T0] [127.0.0.1:47418#APVH_www.sprintswac.tk:443] [STDERR] PHP Stack trace:\n
2023-07-13 11:26:25.069850 [NOTICE] [3623041] [T0] [127.0.0.1:47418#APVH_www.sprintswac.tk:443] [STDERR] PHP   1. {main}() /home/mycoo660/domains/sprintswac.tk/public_html/iconnect/3/administrator/index.php:0\n
2023-07-13 11:26:25.069854 [NOTICE] [3623041] [T0] [127.0.0.1:47418#APVH_www.sprintswac.tk:443] [STDERR] PHP   2. Joomla\CMS\Application\CMSApplication->execute() /home/mycoo660/domains/sprintswac.tk/public_html/iconnect/3/administrator/index.php:51\n
2023-07-13 11:26:25.069865 [NOTICE] [3623041] [T0] [127.0.0.1:47418#APVH_www.sprintswac.tk:443] [STDERR] PHP   3. Joomla\CMS\Application\AdministratorApplication->doExecute() /home/mycoo660/domains/sprintswac.tk/public_html/iconnect/3/libraries/src/Application/CMSApplication.php:225\n
2023-07-13 11:26:25.069891 [NOTICE] [3623041] [T0] [127.0.0.1:47418#APVH_www.sprintswac.tk:443] [STDERR] PHP   4. Joomla\CMS\Application\AdministratorApplication->dispatch($component = *uninitialized*) /home/mycoo660/domains/sprintswac.tk/public_html/iconnect/3/libraries/src/Application/AdministratorApplication.php:159\n
2023-07-13 11:26:25.069908 [NOTICE] [3623041] [T0] [127.0.0.1:47418#APVH_www.sprintswac.tk:443] [STDERR] PHP   5. Joomla\CMS\Component\ComponentHelper::renderComponent($option = 'com_joomlaupdate', $params = *uninitialized*) /home/mycoo660/domains/sprintswac.tk/public_html/iconnect/3/libraries/src/Application/AdministratorApplication.php:101\n
2023-07-13 11:26:25.069918 [NOTICE] [3623041] [T0] [127.0.0.1:47418#APVH_www.sprintswac.tk:443] [STDERR] PHP   6. Joomla\CMS\Component\ComponentHelper::executeComponent($path = '/home/mycoo660/domains/sprintswac.tk/public_html/iconnect/3/administrator/components/com_joomlaupdate/joomlaupdate.php') /home/mycoo660/domains/sprintswac.tk/public_html/iconnect/3/libraries/src/Component/ComponentHelper.php:377\n
2023-07-13 11:26:25.069922 [NOTICE] [3623041] [T0] [127.0.0.1:47418#APVH_www.sprintswac.tk:443] [STDERR] PHP   7. require_once() /home/mycoo660/domains/sprintswac.tk/public_html/iconnect/3/libraries/src/Component/ComponentHelper.php:402\n
2023-07-13 11:26:25.069930 [NOTICE] [3623041] [T0] [127.0.0.1:47418#APVH_www.sprintswac.tk:443] [STDERR] PHP   8. Joomla\CMS\MVC\Controller\BaseController->execute($task = 'download') /home/mycoo660/domains/sprintswac.tk/public_html/iconnect/3/administrator/components/com_joomlaupdate/joomlaupdate.php:18\n
2023-07-13 11:26:25.069940 [NOTICE] [3623041] [T0] [127.0.0.1:47418#APVH_www.sprintswac.tk:443] [STDERR] PHP   9. JoomlaupdateControllerUpdate->download() /home/mycoo660/domains/sprintswac.tk/public_html/iconnect/3/libraries/src/MVC/Controller/BaseController.php:702\n
2023-07-13 11:26:25.069944 [NOTICE] [3623041] [T0] [127.0.0.1:47418#APVH_www.sprintswac.tk:443] [STDERR] PHP  10. JoomlaupdateModelDefault->download() /home/mycoo660/domains/sprintswac.tk/public_html/iconnect/3/administrator/components/com_joomlaupdate/controllers/update.php:48\n

**Comment by zero-24** [comment] 2023-07-14 17:29
Hmm that sounds like to be an issue of the update not beeing recived correctly. Does that solve itself when you are deleting the #__updates table so the update will be fetched again?

**Comment by jweaver0312** [comment] 2023-07-15 02:16
You mean delete the _updates table from the database?

**Comment by zero-24** [comment] 2023-07-15 08:45
Hmm Yes i had an empty #__updates table in mind not deleting it. Please reach out to me via tobias.zulauf[at]community[DOT]joomla[DOT]org so we can coordinate a meeting where we can take a look into the site and debig the issue. As I can not reproduce the issue on my end its hard to diagnose the issue while that problem does not come up to me.

**Comment by jweaver0312** [comment] 2023-07-15 15:20
I will write to you soon, but I just wanted to mention that for some reason as well, the error only occurs when Joomla Update is set to default.

**Comment by zero-24** [comment] 2023-07-18 10:55
Have you reached out to me already? Havn't saw a mail from you till now.

**Comment by Hackwar** [comment] 2023-07-26 19:29
We are not fixing bugs for Joomla 3 anymore, which is why I'm closing this issue.

**Closed as completed by Hackwar** 2023-07-26 19:29 UTC
Labels: No Code Attached Yet
