### ISSUE TITLE
fatal error non-object login.ph

### ISSUE THREAD

**Issue by ymages** [joomla/joomla-cms#7826] opened 2015-09-06 00:13 UTC
in my server error_log I get many lines with : 
PHP Fatal error: Call to a member function get() on a non-object in /components/com_users/models/login.php on line 62

the line 62 -> if ($return = $input->$method->get('return', '', 'BASE64'))

any idea of what could be wrong ?

thank you

#### System information (as much as possible)
Joomla 3.4.3
PHP 5.5.28
Apache 2.4.16
MySQL 5.5.42-cll

#### Additional comments

it should be ?

if (!empty($method) && isset($input->$method) && is_object($input->$method) && $return = $input->$method->get('return', '', 'BASE64')

**Comment by mbabker** [comment] 2015-09-06 00:35
`$method` is set a few lines before that and should always have a value (see https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/input/input.php#L334), the extra checks should be absolutely unnecessary.  It seems traffic is hitting your site with invalid HTTP requests as `$_SERVER['REQUEST_METHOD']` is a pretty standard value to be set when running PHP applications via web request.

**Comment by ymages** [comment] 2015-09-06 00:38
Thanks a lot for your fast reply

And from my side there is nothing to do, I’ve got hundreds of error lines

**Comment by laoneo** [comment] 2015-10-05 14:20
Please provide some testing instructions that we can try to reproduce the issue.

**Comment by ameiri** [comment] 2015-11-24 12:40
On my system this happens due to some clients accessing the website using the HEAD method. This is [valid HTTP](http://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html "HTTP 1.1 RFC"), as far as I understand things, however there is no php superglobal for `HEAD` (as opposed to `GET` and `POST`).
JINPUT has a `__get()` magic method to get input objects. When `$method == 'GET'`, `$input->$method` results in said superglobal being accessed. However when `$method == 'HEAD'` this fails. The following final line from the method (file libraries/joomla/input/input.php) shows that something is missing:
```
// TODO throw an exception
```
I am new to php and to Joomla, but I fail to see the reason for accessing request inputs in this manner. It seems to me that in components/com_users/models/login.php the line:
```php
if ($return = $input->$method->get('return', '', 'BASE64')
```
could (should?) be replaced with:
```php
if ($return = $input->get('return', '', 'BASE64'))
```

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7826">issues.joomla.org/joomla-cms/7826</a>.</sub>

**Comment by ameiri** [comment] 2015-11-24 12:53
Just some links to the code I referenced above:
[The __get() magic method](https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/input/input.php#L114 "JInput::__get()")
[The TODO comment](https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/input/input.php#L139 "TODO comment in JInput::__get()")
[The line where I think a fix could be made (same line where this error occurs)](https://github.com/joomla/joomla-cms/blob/staging/components/com_users/models/login.php#L62 "Possible fix here?")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7826">issues.joomla.org/joomla-cms/7826</a>.</sub>

**Comment by brianteeman** [comment] 2016-05-08 17:17
Hi you created this issue sometime ago but no code has been provided for people to evaluate. As no one has shown any interest in providing a pull request I am closing this at this time. If code is provided (a pull request) it can always be re-examined.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7826">issues.joomla.org/joomla-cms/7826</a>.</sub>

**Closed** 2016-05-08 17:17 UTC
Labels: No Code Attached Yet

**Comment by YaegerDesign** [comment] 2017-01-26 18:30
I have gotten this same error a few times recently:
`PHP Fatal error:  Call to a member function get() on a non-object in /path/to/site/components/com_users/models/login.php on line 62`

However, it seems to have just started in 2017.
