### ISSUE TITLE
Breadcrumbs show the wrong result with caching

### ISSUE THREAD

**Issue by cdekok** [joomla/joomla-cms#9521] opened 2016-03-22 14:37 UTC
#### Steps to reproduce the issue
Add breadcrumbs and turn on caching
Visit 1 article
Visit another article it will show the first page title

#### Expected result
Show the 2nd article title

#### Actual result
Shows the 1st article title

#### Additional comments
There already have been some issues about this and a PR https://github.com/joomla/joomla-cms/pull/3269
Which was closed because of a file rename 0_o

Other people with the same issue:
http://forum.joomla.org/viewtopic.php?f=708&t=893447
https://developer.joomla.org/joomlacode-archive/issue-33093.html
https://github.com/joomla/joomla-cms/issues/5188

**Comment by brianteeman** [comment] 2016-03-22 14:40
Which caching option are you selecting?
Do you have the caching in the breadcrumbs module set to OFF<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9521">issues.joomla.org/joomla-cms/9521</a>.</sub>

**Comment by cdekok** [comment] 2016-03-22 14:42
@brianteeman File caching, when disabling the breadcrumb module cache it works fine.
But it should not have this option if it won't work properly with caching.

**Comment by brianteeman** [comment] 2016-03-22 14:46
You are probably correct that the option should not be there as it can
never work.

On 22 March 2016 at 14:42, Chris de Kok <notifications@github.com> wrote:

> @brianteeman <https://github.com/brianteeman> File caching, when
> disabling the breadcrumb module cache it works fine.
> But it should not have this option if it won't work properly with caching.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9521#issuecomment-199844855>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by andrepereiradasilva** [comment] 2016-03-22 14:50
This is an old issue that it seems never got resolved.

I had to disable caching in all breadcrumb modules in all sites a long time ago to avoid this issue.

I agree with @cdekok and @brianteeman this should be resolved in future releases.

**Comment by Twincarb** [comment] 2016-03-22 21:35
Would it be sufficient to remove the option from Joomla breadcrumbs module for caching, as the same issue can be created by using breadcrumbs from other authors.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9521">issues.joomla.org/joomla-cms/9521</a>.</sub>

**Comment by brianteeman** [comment] 2016-03-22 21:37
There is nothing we can do about external modules

**Comment by Twincarb** [comment] 2016-03-22 22:10
am I looking at this to simply in, mod_breadcrumbs.xml 

change line 80 to hidden
change line 81 to 0
change line 91 to hidden
change line 92 to 0

and then a check in the db to check that the settings are as above? which would cover both new installs and current installs.
I am happy giving the PR a go.
				<field 
79 					name="cache" 
80 					type="list" 
81 					default="1" 
82 					label="COM_MODULES_FIELD_CACHING_LABEL" 
83 					description="COM_MODULES_FIELD_CACHING_DESC"> 
84 					<option 
85 						value="1">JGLOBAL_USE_GLOBAL</option> 
86 					<option 
87 						value="0">COM_MODULES_FIELD_VALUE_NOCACHING</option> 
88 				</field> 
89 				<field 
90 					name="cache_time" 
91 					type="text" 
92 					default="900" 
93 					label="COM_MODULES_FIELD_CACHE_TIME_LABEL" 
94 					description="COM_MODULES_FIELD_CACHE_TIME_DESC" /> 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9521">issues.joomla.org/joomla-cms/9521</a>.</sub>

**Comment by andrepereiradasilva** [comment] 2016-03-22 22:16
Sure, please make a PR

I have doubts it should be hidden - what will happen in sites with caching already enabled in breadcrumbs - can they change it if it's hidden?

Also if i have a site with no categories i would like to cache the breadcrumb.

But agree with putting a default value of 0 (no caching).

**Comment by brianteeman** [comment] 2016-03-22 22:22
I think that realistically all we can do is to change the default value for
NEW installs to no caching. NOTE you might need to check the sample data
sql as well to see if it is saved there as well.

**Comment by Twincarb** [comment] 2016-03-22 22:28
My logic was that by default the use of caching breadcrumbs has no value, but if as you suggest there are occasions when caching breadcrumbs can work then the easy way is to set the default to no caching and a tooltip to say "Caching can have undesirable results with dynamic content sites. Recommended state is disabled." Not making any change to it's visibility.

Applying the above logic wouldn't need a db check or change. Although it may be beneficial to do a db check to see if the module is installed but not enabled and if so adjust the defaults to '0'.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9521">issues.joomla.org/joomla-cms/9521</a>.</sub>

**Comment by brianteeman** [comment] 2016-03-23 09:54
Closed as we have a PR #9540<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9521">issues.joomla.org/joomla-cms/9521</a>.</sub>

**Closed by brianteeman** 2016-03-23 09:54 UTC
Labels: No Code Attached Yet

**Comment by BruTaLysT** [comment] 2020-10-14 08:15
Am I allowed to open this topic again? I just realised that breadcrumbs with cache disabled now have issues if Global settings -> System Cache -> On - Conservative caching is set. This is somehow still caching the Breadcrumbs which results in faulty behaviour. I can't remember this happening when i built the website a few months ago. So probably slipped in a recent joomla update? Running Joomla! 3.9.22 @ PHP 7.3.23

Can we confirm this is the case? Hope i'm not the only one ;)

**Comment by cdekok** [comment] 2020-10-14 09:01
@BruTaLysT it makes sense or add a new bug report, I totally forgot about this looking at the PR it just sets the default caching to 0, but it would still be an issue if you enable the caching, the option should be removed totally from the xml if it's not possible to cache.

https://github.com/joomla/joomla-cms/pull/9540/files#diff-97eba7afd05c20c8b482df557f810eb9c9867d36aa161bab73e7c46b9fb43e46L81

**Comment by Twincarb** [comment] 2020-10-14 09:36
imo it's a new issue so long as the following are set in the module:
Caching. No Caching.
Cache Time. 0.
The original issue was caused by "caching being enabled by default" which was solved by setting the defaults to caching disabled for the module, which works for new sites but doesn't prevent anyone from changing it.
The reason it wasn't removed is if would prevent a site that cached the module to change the setting in the future, and depending on the site format the breadcrumbs can be cached safely.

**Comment by BruTaLysT** [comment] 2020-10-14 09:53
@Twincarb, Indeed that's the case. No Caching / Cache Time 0 are set on the Breadcrumbs module. The Global Configuration cache setting somehow overrides the module's cache setting and still manages to cache the Breadcrumbs. Could this also be the case for other modules specifically set to NOT cache? I just tested this with a News website I manage. Certain modules should not cache or they display the wrong information. While Global config is set to 'On - Conservative caching' these modules indeed do NOT cache. They seem to work correctly. So this is possibly only a breadcrumbs thing?
