### ISSUE TITLE
Joomla\CMS\Cache\Storage\FileStorage::_deleteFolder JFolder: :delete: Could not delete folder

### ISSUE THREAD

**Issue by alagesanbe08** [joomla/joomla-cms#18517] opened 2017-11-07 11:22 UTC
### Steps to reproduce the issue
This warning  show only for Guest user, When enable conservative cache
![global_configuration_-_j2store_-_administration](https://user-images.githubusercontent.com/4928582/32491029-298fd124-c3db-11e7-9b28-9823d14787c0.png)

it show warning like this
![english_home](https://user-images.githubusercontent.com/4928582/32491083-5ce6f2e6-c3db-11e7-98bb-0cc326189abd.png)

For other user, no warning message 

### System information (as much as possible)
PHP Built On: Linux joomlatools 4.2.0-27-generic 32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64
Database Version: 5.5.47-0ubuntu0.14.04.1
Database Collation: utf8_general_ci
PHP Version: 7.1.2
Web Server: Apache/2.4.18 (Ubuntu)
Joomla! Version: Joomla! 3.8.1 Stable
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:56.0) Gecko/20100101 Firefox/56.0

**Comment by mbabker** [comment] 2017-11-07 11:50
The caching layer is usually disabled when a user is logged in for the frontend facing content (actual component and module output).  So it's expected that only non-logged in users would see it.

As for the source of the issue, I'd suggest starting with validating the permissions on your server are correct.

**Comment by alagesanbe08** [comment] 2017-11-07 12:07
i am using vagrant and also checked with 777 permission but no luck :)

**Comment by landed1** [comment] 2017-11-07 12:09
I also have this issue and checked the folder permissions are correct. I am going to be playing with the path in the config a little as I saw some other issues that mentioned that. I am running php 7.
I do have old config lines that are memcache related from when I used memcache on older php version I will try to remove some of them.

**Comment by landed1** [comment] 2017-11-07 13:14
I have tried setting a manual path in config, and also creating a new custom cache directory and changing the path to that. The line of code that gives the error is happening in a plugin onContentPrepare and is 

$cache = JFactory::getCache();
$cache->clean('com_content');

Is it possible the frequency of this getting called is triggering the issue? I did not see this looping for example but I am trying to understand why that folder might be unavailable, though it is consistent so probably not a latency/write issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18517">issues.joomla.org/tracker/joomla-cms/18517</a>.</sub>

**Comment by csthomas** [comment] 2017-11-07 14:57
> Is it possible the frequency of this getting called is triggering the issue? 

Yes.
File cache cleaning does not use any file locking mechanism.

If we have 2 simulated requests and the first one is cleaning the cache directory `/cache/*` and the second one is creating a new cache file at `/cache/com_content/xxxxxxxx.php` then `clean()` will cause an error because it can not delete folder `/cache/com_content/` because there is still a file.

**Comment by ggppdk** [comment] 2017-11-11 04:56
>  Yes. File cache cleaning does not use any file locking mechanism.
> If we have 2 simulated requests and the first one is cleaning the cache directory /cache/* and the second one is creating a new cache file at /cache/com_content/xxxxxxxx.php then clean() will cause an error because it can not delete folder /cache/com_content/ because there is still a file.

I have encountered this in our component, it is indeed due to locked files inside
the component cache subfolder inside `/cache/com_somecomponent/somefile.php`

But,
besides having 2 simultaneous requests,
it can occur also due to a module trying to clean the component cache
(i decided to remove that code cleaning as it is was not really needed)

----

So it is similar to report by @landed1 

> The line of code that gives the error is happening in a plugin onContentPrepare and is
> $cache = JFactory::getCache();
> $cache->clean('com_content');

Does it make sense to remove the generated warning ?

**Comment by alikon** [comment] 2019-07-05 08:25
expected behaviour<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18517">issues.joomla.org/tracker/joomla-cms/18517</a>.</sub>

**Closed as completed by alikon** 2019-07-05 08:25 UTC
Labels: No Code Attached Yet

**Comment by nguyenlong89** [comment] 2020-05-09 03:48
Can you explain more @landed1:
I am using J3.9.16 but I don't know where that code is located
> $cache = JFactory::getCache();
> $cache->clean('com_content');
