### ISSUE TITLE
Fatal error upgrading from 2.5

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#17967] opened 2017-09-16 08:59 UTC
### Steps to reproduce the issue
I only reproduced this once when upgrading a site from 2.5 to 3 under php 5.6 and mysql 5.7
After the upgrade which is by default to 3.5.1 (iirc) then there is a fatal error and several files from the 2.5 install are still present. This is the same as reported in #11117

The fix for that was introduced in 3.6 (iirc) #11282 however that obviously doest help if the update is to 3.5.1 and not 3.6

@zero-24

**Comment by zero-24** [comment] 2017-09-16 11:23
Thanks. I'm going to take a look into that later thanks.

**Comment by zero-24** [comment] 2017-10-02 18:42
The issue should be fixed with the changes to the update server proposed in #18192 please test and report back. Thanks.

**Comment by mbabker** [comment] 2017-10-02 18:50
The issue is not fixed.  It is merely bypassed.

**Comment by zero-24** [comment] 2017-10-02 18:59
I'm happy to test any code fix that helps here without hacking the menu system or rewrite com_joomlaupdate. 😄

**Comment by wojsmol** [comment] 2017-10-13 07:43
@mbabker @zero-24 Please see [this forum topic](https://forum.joomla.org/viewtopic.php?f=710&t=955737) very similar to issue reported by @brianteeman.

**Comment by wojsmol** [comment] 2017-10-13 07:56
@franz-wohlkoenig Plese re-open temporally for better visibility.

**Comment by ghost** [comment] 2017-10-13 09:17
reopened as stated above.

**Comment by Webdongle** [comment] 2017-10-13 11:01
update 2.5.28 to 3.5.1 used to work seamlessly (with the remember me plugin disabled)).
I used to be able to do it on localhost with xampp.  Now I use xampp with php7 ... I use wamp.  But now I get errors.  Could this be a database issue ? because wamp is msql not msqli ?

**Comment by mbabker** [comment] 2017-10-13 11:19
AFAIK 2.5 isn't PHP 7 compatible so you probably need to be on a 5.6 version to do that upgrade.

**Comment by wojsmol** [comment] 2017-10-13 11:22
@mbabker In forum topic php 5.6 don't work also.

**Comment by mbabker** [comment] 2017-10-13 11:29
Then it's an extension issue because I took the effort to ensure 2.5.28 was PHP 5.6 friendly before issuing the release and closing the branch.

**Comment by wojsmol** [comment] 2017-10-13 11:34
@mbabker Give me a moment to test same thing.

**Comment by wojsmol** [comment] 2017-10-13 11:51
@mbabker I can't reproduce this, but see [this post](https://forum.joomla.org/viewtopic.php?p=3497671#p3497671) - in the method 2 all 3rd party extensions are disabled.

**Comment by Webdongle** [comment] 2017-10-13 12:09
@mbabker 
I will rephrase
> I used to be able to do it on localhost with xampp. Now I use xampp with php7 ... I use wamp. But now I get errors. Could this be a database issue ? because wamp is msql not msqli ?

When I used xampp with php5 the update 2.5.28 to 3.5.1 used to work seamlessly.  I now have xampp with php7 so I now also have wamp to use php5.  But  the update 2.5.28 to 3.5.1 fails on wamp.   I ask again ... **Could this be a database issue ? because wamp is msql not msqli ?**

**Comment by mbabker** [comment] 2017-10-13 12:20
No.  Both 2.5 and 3.x support both `mysql` and `mysqli` as long as the underlying PHP engine dependencies are met.  And as of 3.5.0 there is code in the database driver factory to detect if you are running PHP 7 with `mysql` set as the driver and attempt to auto-convert to `mysqli` if it is available on your platform, so even that configuration shouldn't be problematic.

**Comment by wojsmol** [comment] 2017-10-13 12:25
@Webdongle https://github.com/joomla/joomla-cms/issues/17967#issuecomment-336435008 I tested this case on JAMP (paid alternative to XAMP and similar solutions -there  is a free trial) and this is working.

**Comment by Webdongle** [comment] 2017-10-13 12:25
@mbabker 

> Then it's an extension issue because I took the effort to ensure 2.5.28 was PHP 5.6 friendly before issuing the release and closing the branch

Does that mean that the 2.5.28 stable full zip install (or updates) has changed after it was released ?

**Comment by mbabker** [comment] 2017-10-13 12:33
No.  PHP 5.6 support was finalized before 2.5.28 was released.

**Comment by wojsmol** [comment] 2017-10-13 12:54
For clarity I tested on:
php 5.6.20
mysql and mysqli extensions loaded but dbtype set to mysql
Client API library version 	mysqlnd 5.0.11-dev - 20120503
Windows 8.1

**Comment by Webdongle** [comment] 2017-10-13 13:04
Just tested on Uniform server and update ran smoothly.  
Brought to login screen
Logged in
Brought to http://localhost/j2528b/administrator/index.php?option=com_joomlaupdate&view=default&layout=complete
> Your site has been successfully updated. Your Joomla version is now 3.5.1. 

But a message above it

> An error has occurred.

Cleared cache
![update 03](https://user-images.githubusercontent.com/1115202/31547472-5edd9c64-b01f-11e7-93b6-415872275775.JPG)

**Comment by Webdongle** [comment] 2017-10-13 16:07
Could it be a time out issue ?

Further testing
The update 2.5.28 to 3.5.1 fails with
> Database Version 	5.7.19
Database Collation 	utf8_general_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	5.6.31 
Web Server 	Apache/2.4.27 (Win64) PHP/5.6.31 

    Server: MySQL (127.0.0.1 via TCP/IP)
    Server type: MySQL
    Server version: 5.7.19 - MySQL Community Server (GPL)
    Protocol version: 10
    User: root@localhost
    Server charset: UTF-8 Unicode (utf8)
    Apache/2.4.27 (Win64) PHP/5.6.31
    Database client version: libmysql - mysqlnd 5.0.11-dev - 20120503 - $Id:   76b08b24596e12d4553bd41fc93cccd5bac2fe7a $
    PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation 





> The update 2.5.28 to 3.5.1 succeeds with
> Database Version 	5.6.34
> Database Collation 	utf8_general_ci
> Database Connection Collation 	utf8mb4_general_ci
> PHP Version 	5.6.28
> Web Server 	Apache 

    Server: Uniform Server (127.0.0.1 via TCP/IP)
    Server type: MySQL
    Server version: 5.6.34 - MySQL Community Server (GPL)
    Protocol version: 10
    User: root@localhost
    Server charset: UTF-8 Unicode (utf8)
     Apache
    Database client version: libmysql - mysqlnd 5.0.11-dev - 20120503 - $Id: 76b08b24596e12d4553bd41fc93cccd5bac2fe7a $
    PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation

**Comment by mbabker** [comment] 2017-10-13 16:09
A time out issue would be more reliant on PHP configuration settings, not just running different versions.  We'd need more of the PHP configuration to consider something timing out, or PHP error logs if there's anything helpful.

It could also be possible (not sure how likely but we can entertain it for a second) that there is an issue with MySQL 5.7 and Joomla 2.5.

**Comment by wojsmol** [comment] 2017-10-13 16:24
@mbabker In the topic I link there is FPA report. See also [this topic](https://forum.joomla.org/viewtopic.php?f=710&t=954187) in both cases there are wired database structure issues.

**Comment by Webdongle** [comment] 2017-10-13 18:29
@mbabker 
Update log for 2.5.28 to 3.5.1 update that stuck on /finalising
`#
#<?php die('Forbidden.'); ?>
#Date: 2017-10-13 10:29:23 UTC
#Software: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

#Fields: datetime	priority clientip	category	message
2017-10-13T10:29:23+00:00	INFO ::1	update	Finalising installation.
2017-10-13T10:29:24+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__users` DROP INDEX `usertype`;.
2017-10-13T10:29:24+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__session` DROP INDEX `whosonline`;.
2017-10-13T10:29:24+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: DROP TABLE IF EXISTS `#__update_categories`;.
2017-10-13T10:29:25+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__contact_details` DROP `imagepos`;.
2017-10-13T10:29:25+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__content` DROP COLUMN `title_alias`;.
2017-10-13T10:29:25+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__content` DROP COLUMN `sectionid`;.
2017-10-13T10:29:25+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__content` DROP COLUMN `mask`;.
2017-10-13T10:29:25+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__content` DROP COLUMN `parentid`;.
2017-10-13T10:29:26+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__newsfeeds` DROP COLUMN `filename`;.
2017-10-13T10:29:26+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__menu` DROP COLUMN `ordering`;.
2017-10-13T10:29:26+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__session` DROP COLUMN `usertype`;.
2017-10-13T10:29:26+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__users` DROP COLUMN `usertype`;.
2017-10-13T10:29:26+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__updates` DROP COLUMN `categoryid`;.
2017-10-13T10:29:26+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: UPDATE `#__extensions` SET protected = 0 WHERE `name` = 'com_search' OR `name` =.
2017-10-13T10:29:26+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: DELETE FROM `#__extensions` WHERE `extension_id` = 800;.
2017-10-13T10:29:28+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__assets` ENGINE=InnoDB;.
2017-10-13T10:29:28+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__associations` ENGINE=InnoDB;.
2017-10-13T10:29:29+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__banners` ENGINE=InnoDB;.
2017-10-13T10:29:30+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__banner_clients` ENGINE=InnoDB;.
2017-10-13T10:29:31+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__banner_tracks` ENGINE=InnoDB;.
2017-10-13T10:29:32+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__categories` ENGINE=InnoDB;.
2017-10-13T10:29:33+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__contact_details` ENGINE=InnoDB;.
2017-10-13T10:29:35+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__content` ENGINE=InnoDB;.
2017-10-13T10:29:36+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__content_frontpage` ENGINE=InnoDB;.
2017-10-13T10:29:37+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__content_rating` ENGINE=InnoDB;.
2017-10-13T10:29:38+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__core_log_searches` ENGINE=InnoDB;.
2017-10-13T10:29:40+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__extensions` ENGINE=InnoDB;.
2017-10-13T10:29:40+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__finder_filters` ENGINE=InnoDB;.
2017-10-13T10:29:42+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__finder_links` ENGINE=InnoDB;.
2017-10-13T10:29:43+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__finder_links_terms0` ENGINE=InnoDB;.
2017-10-13T10:29:44+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__finder_links_terms1` ENGINE=InnoDB;.
2017-10-13T10:29:47+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__finder_links_terms2` ENGINE=InnoDB;.
2017-10-13T10:29:48+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__finder_links_terms3` ENGINE=InnoDB;.
2017-10-13T10:29:50+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__finder_links_terms4` ENGINE=InnoDB;.
2017-10-13T10:29:51+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__finder_links_terms5` ENGINE=InnoDB;.
2017-10-13T10:29:52+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__finder_links_terms6` ENGINE=InnoDB;.
2017-10-13T10:29:53+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__finder_links_terms7` ENGINE=InnoDB;.
2017-10-13T10:29:54+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__finder_links_terms8` ENGINE=InnoDB;.
2017-10-13T10:29:55+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__finder_links_terms9` ENGINE=InnoDB;.
2017-10-13T10:29:56+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__finder_links_termsa` ENGINE=InnoDB;.
2017-10-13T10:29:56+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__finder_links_termsb` ENGINE=InnoDB;.
2017-10-13T10:29:57+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__finder_links_termsc` ENGINE=InnoDB;.
2017-10-13T10:29:58+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__finder_links_termsd` ENGINE=InnoDB;.
2017-10-13T10:29:59+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__finder_links_termse` ENGINE=InnoDB;.
2017-10-13T10:30:00+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__finder_links_termsf` ENGINE=InnoDB;.
2017-10-13T10:30:01+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__finder_taxonomy` ENGINE=InnoDB;.
2017-10-13T10:30:03+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__finder_taxonomy_map` ENGINE=InnoDB;.
2017-10-13T10:30:04+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__finder_terms` ENGINE=InnoDB;.
2017-10-13T10:30:05+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__finder_terms_common` ENGINE=InnoDB;.
2017-10-13T10:30:06+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__finder_types` ENGINE=InnoDB;.
2017-10-13T10:30:10+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__languages` ENGINE=InnoDB;.
2017-10-13T10:30:13+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__menu` ENGINE=InnoDB;.
2017-10-13T10:30:14+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__menu_types` ENGINE=InnoDB;.
2017-10-13T10:30:14+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__messages` ENGINE=InnoDB;.
2017-10-13T10:30:15+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__messages_cfg` ENGINE=InnoDB;.
2017-10-13T10:30:16+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__modules` ENGINE=InnoDB;.
2017-10-13T10:30:18+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__modules_menu` ENGINE=InnoDB;.
2017-10-13T10:30:19+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__newsfeeds` ENGINE=InnoDB;.
2017-10-13T10:30:21+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__overrider` ENGINE=InnoDB;.
2017-10-13T10:30:22+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__redirect_links` ENGINE=InnoDB;.
2017-10-13T10:30:23+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__schemas` ENGINE=InnoDB;.
2017-10-13T10:30:24+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__session` ENGINE=InnoDB;.
2017-10-13T10:30:27+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__template_styles` ENGINE=InnoDB;.
2017-10-13T10:30:28+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__updates` ENGINE=InnoDB;.
2017-10-13T10:30:29+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__update_sites` ENGINE=InnoDB;.
2017-10-13T10:30:32+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__update_sites_extensions` ENGINE=InnoDB;.
2017-10-13T10:30:34+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__users` ENGINE=InnoDB;.
2017-10-13T10:30:36+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__usergroups` ENGINE=InnoDB;.
2017-10-13T10:30:38+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__user_notes` ENGINE=InnoDB;.
2017-10-13T10:30:38+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__user_profiles` ENGINE=InnoDB;.
2017-10-13T10:30:40+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__user_usergroup_map` ENGINE=InnoDB;.
2017-10-13T10:30:42+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__viewlevels` ENGINE=InnoDB;.
2017-10-13T10:30:46+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__newsfeeds` ADD COLUMN `description` text NOT NULL;.
2017-10-13T10:30:48+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__newsfeeds` ADD COLUMN `version` int(10) unsigned NOT NULL DEFAUL.
2017-10-13T10:30:50+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__newsfeeds` ADD COLUMN `hits` int(10) unsigned NOT NULL DEFAULT '.
2017-10-13T10:30:53+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__newsfeeds` ADD COLUMN `images` text NOT NULL;.
2017-10-13T10:30:57+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__contact_details` ADD COLUMN `version` int(10) unsigned NOT NULL .
2017-10-13T10:31:00+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__contact_details` ADD COLUMN `hits` int(10) unsigned NOT NULL DEF.
2017-10-13T10:31:02+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__banners` ADD COLUMN `created_by` int(10) unsigned NOT NULL DEFAU.
2017-10-13T10:31:06+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__banners` ADD COLUMN `created_by_alias` varchar(255) NOT NULL DEF.
2017-10-13T10:31:08+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__banners` ADD COLUMN `modified` datetime NOT NULL DEFAULT '0000-0.
2017-10-13T10:31:10+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__banners` ADD COLUMN `modified_by` int(10) unsigned NOT NULL DEFA.
2017-10-13T10:31:13+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__banners` ADD COLUMN `version` int(10) unsigned NOT NULL DEFAULT .
2017-10-13T10:31:18+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__categories` ADD COLUMN `version` int(10) unsigned NOT NULL DEFAU.
2017-10-13T10:31:18+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: UPDATE  `#__assets` SET name=REPLACE( name, 'com_user.notes.category','com_users.
2017-10-13T10:31:18+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: UPDATE  `#__categories` SET extension=REPLACE( extension, 'com_user.notes.catego.
2017-10-13T10:31:21+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__finder_terms` ADD COLUMN `language` char(3) NOT NULL DEFAULT '';.
2017-10-13T10:31:21+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__finder_tokens` ADD COLUMN `language` char(3) NOT NULL DEFAULT ''.
2017-10-13T10:31:21+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: ALTER TABLE `#__finder_tokens_aggregate` ADD COLUMN `language` char(3) NOT NULL .
2017-10-13T10:31:21+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: INSERT INTO `#__extensions` 	(`name`, `type`, `element`, `folder`, `client_id`, .
2017-10-13T10:31:22+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: INSERT INTO `#__template_styles` (`template`, `client_id`, `home`, `title`, `par.
2017-10-13T10:31:22+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: UPDATE `#__template_styles` SET home = (CASE WHEN (SELECT count FROM (SELECT cou.
2017-10-13T10:31:22+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: UPDATE `#__template_styles` SET home = 0 WHERE template = 'bluestork';.
2017-10-13T10:31:22+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: INSERT INTO `#__extensions` (`extension_id`, `name`, `type`, `element`, `folder`.
2017-10-13T10:31:23+00:00	INFO ::1	update	Ran query from file 3.0.0. Query text: UPDATE `#__update_sites` SET location = 'http://update.joomla.org/language/trans.
2017-10-13T10:31:46+00:00	INFO ::1	update	Finalising installation.`

**Comment by Webdongle** [comment] 2017-10-14 19:54
@mbabker @wojsmol @brianteeman 
Nothing wrong with the updates unless it uses commands that some databases (for whatever reason) wont process.  **Just tested on a live server FULL SUCCESS in less than 4 minutes.**

-  Installed 2.5.28 with sample data
-  Set Update component options to 'short term' saved and closed
-  Update screen presented me with 3.5.1 ... Installed FULL SUCCESS
-  Update Component screen displayed with a success message
-  Cleared cache and was presented with 3.6.5 ... Installed FULL SUCCESS
- Update Component screen displayed with a success message
- Cleared cache and was presented with 3.8.1 ... Installed FULL SUCCESS
- Update Component screen displayed with a success message
(admin login was offered at some stage but cant remember at what point)

Shared cheap Hosting
PHP Built On 	Linux info 3.0 # 1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux
Database Version 	5.5.57-0+deb7u1-log
Database Collation 	utf8_general_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	5.6.31
Web Server 	Apache
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 3.8.1 Stable [ Amani ] 4-October-2017 14:00 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0

**Closed as completed** 2017-11-18 17:50 UTC
Labels: No Code Attached Yet
