### ISSUE TITLE
[4.2] Login & Registration pages Redirections issue

### ISSUE THREAD

**Issue by joomleb** [joomla/joomla-cms#38321] opened 2022-07-22 17:31 UTC
Hi guys, 
case study: When we set a frontend Login Form and / or Registration Form menu item the most used / logic ACL Access setting is "Guest":
- not "Public" because the Login Form menu item Name used is "Login", so when I'm logged I don't want to see it and we are used to create a Logout menu item (ACL Registered) which will replace the "Login" menu item
- not "Public" because the Register Form menu item Name used is "Register", it is a Register Form and when I'm logged I'm obviously yet Registered. Usually it  will be replaced by a User Profile menu item (ACL Registered)
- and never "Registered" simply because obviously if I'm Logged I'm yet Registered and I don't need to Register and/or to Login

Now:
- I'm displaying the frontend Login Form - [Login test page](https://test1.egulp.net/login)
  and / or Registration Form menu item page - [Registration test page](https://test1.egulp.net/registration)
- I login through the Login module (on the bottom on the pages) with "Module > Login Redirection Page: -Select Menu Item-" setting that should mean "Same Page"
- the Login Form / Registration Form menu item ACL Access setting is set to "Guest"
- so, I'm logged, but automatically I'm redirected to the home page and a Danger Alert is shown: "_You don't have permission to access this. Please contact a website administrator if this is incorrect._"

This is the worst User Experience and Users panic thinking they have done something wrong.

**Solution**:

**A** - just for the Login Form / Registration Form menu items, if I have no the ACL Access permission, I'm automatically redirected to the home page, Okay, but _the ACL Danger Alert should never been shown_
Do you agree ?

OR **Better Solution**
**B** - for them, when I have no the ACL Access permission, I will be redirected to:
- for the the **Login Form** menu item, to the "Options > Menu Item Login Redirect: ..." setting
- for the **Registration Form** menu item, to the "Options > Menu Item Registration Redirect: …" mentioned here #37566

**Comment by richard67** [comment] 2022-07-22 18:15
> When we set a frontend Login Form and / or Registration Form menu item the most used / logic ACL Access setting is "Guest" (not Public because and never Registered).

Not public because of what? Is there something missing in this sentence?

**Comment by richard67** [comment] 2022-07-22 18:18
Maybe you just don’t understand the purpose of the „Guest“ access level? While „Public“ includes also what registered, logged in users can see, „Guest“ doesn’t, and that’s how it shall be.

**Comment by brianteeman** [comment] 2022-07-22 18:32
Something is not correct in your description. If I follow the description then I have no problem.

I am guessing that the instruction that is missing is that you have set the defaultt menu item as the login registration form?

**Comment by joomleb** [comment] 2022-07-22 19:09
@richard67 
> Not public because of what? Is there something missing in this sentence?

Sorry, I corrected it in the original post

**Comment by joomleb** [comment] 2022-07-22 19:31
@brianteeman 
> I am guessing that the instruction that is missing is that _you have set the defaultt menu item as the login registration form_?

I'm not sure I understood what you mean, but No.
With the Login module (on the bottom on the pages) setting "Module > Login Redirection Page: -Select Menu Item-" that should mean "Same Page".
I reformulate the original post to better explain what I mean and I added test pages links hooping this can help to understand me... I remain available

**Comment by brianteeman** [comment] 2022-07-22 20:09
ok I understand you now. This will of course happen and it is working as designed.

1. public => visible to all
2. guest => visible to unregistered
3. registered => visible to logged in

You have login & registration menu items that are set to guest. Therefore registered and logged in users have no access to thos menu items.

You have set the module to stay on the same page after log in but you no longer have access to that page - hence the error message which is correct.

This is exactly why both the login module and the login component have options for where to go after successfully logging in.

**Comment by joomdonation** [comment] 2022-11-13 10:19
As @brianteeman pointed out, it is working as expected (see his previous comment). So I'm closing this issue.

**Closed as completed by joomdonation** 2022-11-13 10:19 UTC
Labels: No Code Attached Yet

**Comment by joomleb** [comment] 2022-11-14 00:22
Hi guys, 
Please, read carefully the use case I described in the first post. 
I did not said that is not working as expected. 
What I said is that in these 2 specific use cases (login form and registration form menu items pages), to show the standard ACL error Danger message and automatically redirect to the homepage is not the best thing for the User Experience.

Why ?
- As user I'm on those pages and my intent is to log in
- When I click I'm logged with success
- But the _Danger_ Alert tell me: "**You don't have permission to access this**. Please contact a website administrator if this is incorrect."
- So, the user understand that he hes not logged with success and he has to contact the administrator 

The **Solution** is super simple and just by using features concept that are yet added into Joomla:

**A** - **Alert Message**
just for the Login Form / Registration Form menu items, if I have no the ACL Access permission, I'm automatically redirected to the home page, as now (okay), but _the ACL Danger Alert should never been shown_ ...just it. 

OR to call a different language string within an Info / Message Alert.  

**B** - **Page Redirection**
AND,, for a better solution, always for the Login Form / Registration Form menu items pages, when I have no the ACL Access permission, I will be redirected to:
- the "Options > Menu Item Login Redirect: ..." setting for the **Login Form** menu item
- the "Options > Menu Item Registration Redirect: …" setting for the **Registration Form** menu item that, right now, it is a missing and it is mentioned here #37566
